chapel-lang/chapel

- util/build_configs.py
The chplenv path was not updated when build_configs.py was moved up to util/ dir.
> Fix file path in build_configs.py.

- util/cron/common.bash
Same for CHPL_TEST_COMP_PERF_DIR.
> Don't override CHPL_TEST_PERF_DIR in common if it already has a value

- test/REGRESSIONS
Update REGRESSIONS for the week of 2014-01-12
This should now be up to date for testing up to 2:00 PM CT today.
> Update REGRESSIONS for the week of 2014-01-12

- util/pastPerformance/testReleasesPerformance
Also noted sensitivity to Cray setup in current script.
> Updating comments to reflect desire to run in /tmp

- test/REGRESSIONS
REGRESSIONS is up to date with respect to all testing completed so far.
> Final update for my triage session.

- util/test/perf/perfgraph.js
You can now use 'today' as a sentinel for startdate/enddate in the URL for
performance graphs. This allows you to save/send links that will always contain
the most recent data regardless of when you saved/sent the link. 'today' will
never get set automatically right now. We have discussed having it set if you
zoom in on today's date, but haven't decided if we actually want to do that
yet. The functionality to do so is included here, it's just commented out for
now.
A few supporting changes/fixes:
- Add a helper function to get the current date
- Add simple helper/wrapper functions to set/get the date to/from the URL
- Add simple helper/wrapper function to check if two date ranges are different
- Update the cleardates function
- It wasn't quite right if you refreshed a page while already …
> Support 'today' in perf graph URL

- test/REGRESSIONS
I haven't yet checked that the test environments are up to date.  I intend to
do that later this week.
> Add TRIAGE notes on two sporadic failures.

- test/ANNOTATIONS.yaml
> Alphabetize the annotations file

- test/ANNOTATIONS.yaml
Whoops, got the date wrong. I used 11/07/2014 instead of 10/07/2014
> Fix annotation for addition of c_string_copy type

- test/release/examples/primers/chpldoc.good
I forgot about the release directory!
> Missed a testcase to update for the whitespace change made in #1203

- test/modules/hilde/Writer.future
After retiring four futures related to name munging yesterday, I started looking at other naming-conflict related futures including this one.  The original description of the problem seemed unclear to me, so I poked around a bit, changed the name of the bug, and updated the description (preserving the original one for posterity).
> Proposed update/clarification to Writer.future

- util/test/chpl_launchcmd.py
> chpl_launchcmd: Use cleaner form for testing env var.

- test/REGRESSIONS
- test/REGRESSIONS-hw
Happy Friday the 13th! :four_leaf_clover: :cherry_blossom:
> Regression file updates for today, 2015-02-13.

- runtime/src/launch/slurm-srun/launch-slurm-srun.c
I was defaulting to "/tmp" but Thomas pointed out there right way to do it is
to check the env var TMPDIR (and it's counterparts) first, then fall back to
P_tmpdir, and if all else fails then use "/tmp"
> Be smarter about picking a tmp dir for slurm launcher

- test/ANNOTATIONS.yaml
(I tripped for awhile over putting a dash before host, and
reordered the comments to make them, what I hope to be, a
little clearer).
> Add annotation for chap04 zombie process; refresh comments

- test/REGRESSIONS
- test/REGRESSIONS-hw
Also updated a lot of REGRESSIONS-hw. Will do full pass on both files tomorrow or Tuesday.
> Update regressions file through today, 2015-02-15.

- util/start_test
- util/test/genGraphs
--multiple-configurations is way to long of a name, changing to --configs
> Change name of genGraph option --multiple-configurations to --configs

- modules/standard/Random.chpl
I think other than ordering issues, this is now ready for prime-time
(and, I still hope to make my proposed interface changes, but that's
orthogonal).
> Remove fixed CHPLDOC items and make some other cleanups

- modules/standard/FileSystem.chpl
- runtime/include/chpl-file-utils.h
- runtime/src/chpl-file-utils.c
- test/modules/standard/FileSystem/lydia/sameFile/basic.chpl
- test/modules/standard/FileSystem/lydia/sameFile/basic.good
- test/modules/standard/FileSystem/lydia/sameFile/blah.txt
- test/modules/standard/FileSystem/lydia/sameFile/foo.txt
I have tested that this feature works to my satisfaction, but in the interest of
time and maximizing the number of file functions that are in the coming release,
I will add the tests after the release.
> Implement sameFile for both file records and strings.

- compiler/optimizations/removeWrapRecords.cpp
On the AMM development branch, I was getting invalid C code after adding memory management
for unwrapped distributions.
I traced the problem back to removeWrapRecords, which was leaving in some (newly-added)
autoCopy calls that were using a _valueType formal as the actual in the call.  The clause
in removeWrapRecords starting at line 88 (old) used to remove the _valueType actual from
all call sites and then remove the _valueType formal from the called function.
In the subject function, references to _valueType can still be left in the code if
functions that *it* calls are not similarly named "_valueType".  After the _valueType
formal is removed, the actual referring to it probably codegens to random junk.
I fixed the problem by splitting the steps that remove actuals bound to _valueType …
> Revise removeWrapRecords to avoid generating bogus C code.

- test/multilocale/bradc/needMultiLocales/remoteReal.chpl
- test/multilocale/bradc/needMultiLocales/remoteString.chpl
- test/multilocale/deitz/needMultiLocales/diagnostics/test_private_broadcast_large.chpl
- test/multilocale/deitz/needMultiLocales/diagnostics/test_private_broadcast_small.chpl
- test/multilocale/deitz/needMultiLocales/test_big_recursive_on.chpl
- test/multilocale/deitz/needMultiLocales/test_big_recursive_on_begin.chpl
- test/multilocale/deitz/needMultiLocales/test_local_int_begin.chpl
- test/multilocale/deitz/needMultiLocales/test_local_sync.chpl
- test/multilocale/deitz/needMultiLocales/test_on_begin2.chpl
- test/multilocale/deitz/needMultiLocales/test_on_var_decl1.chpl
- test/multilocale/deitz/needMultiLocales/test_termination1.chpl
I missed a few tests that were multi-locale only, this is hopefully the last batch.
> Fixup more extern calls using string

- compiler/optimizations/narrowWideReferences.cpp
This patch should resolve a compile-time segfault for programs with a c_ptr argument.
> No-local fix for c_ptr args

- test/REGRESSIONS
New errors
----------
* new (sporadic?) segfault on gasnet.fifo (vass owns)
* all aprun configurations failed with "no default server name"
* testSerialReductions seems to have strated getting timeouts and
pthread_cond_init failures on cygwin
Resolved errors
---------------
* lydia/copy/copying regression fixed for linux32 (hasn't seemed
to resolve on cygwin32 yet, but maybe that just hasn't run since
the fix went in yet?))
* "pbs_iff cannot connect to host" issues resolved
Misc
----
* Updated comments at top of REGRESSIONS file to reflect where
I think we are w.r.t. organization and triage
> Triage hand-off to Ben

- modules/internal/DefaultRectangular.chpl
Inlined followers into leaders then cleaned up to create standalones.
They currently do nothing special for sublocales, so include
!localeModelHasSublocales in the where clause.
> Add standalone parallel iterators for DefaultRectangular

- Makefile
Continuing PR #1539, Thomas and Greg requested that I change the
name of the new target, and Thomas pointed out that I incorrectly
put a dash to allow make to continue if there was a build error.
> Clang included fixes

- compiler/AST/type.cpp
- third-party/chpldoc-venv/requirements.txt
Requires: https://github.com/chapel-lang/sphinxcontrib-chapeldomain/pull/19
> Update EnumType::printDocs() to use enum directive in rst mode.

- compiler/optimizations/remoteValueForwarding.cpp
- compiler/passes/checkResolved.cpp
- compiler/passes/flattenFunctions.cpp
- compiler/passes/resolveIntents.cpp
- test/studies/ssca2/performance/SSCA2_commDiags.good
Reverts chapel-lang/chapel#1515.
> Revert "Pass "record-wrapped" types by 'const in' after resolution."

- modules/Makefile
- modules/standard/Norm.chpl
- spec/Standard_Modules.tex
Removed the section about Norm from the spec as well.
> Add chpldoc comments to Norm

- util/test/sub_test
Reverts chapel-lang/chapel#1628
> Revert "Support valgrind testing on chpldoc tests."

- modules/Makefile
- modules/standard/CommDiagnostics.chpl
Chpldoc modules/standard/CommDiagnostics.chpl.
> Chpldoc modules/standard/CommDiagnostics.chpl.

- third-party/gasnet/README
Document the GASnet release we're currently using and patches applied.
> Document the GASnet release we're currently using and patches applied.

- modules/Makefile
- modules/standard/Memory.chpl
Chpldoc modules/standard/Memory.chpl.
> Chpldoc modules/standard/Memory.chpl.

- modules/Makefile
Reviewing Greg's PR for Memory.chpl dox reminded me of this little detail....
> Add Math.chpl to the list of MODULES_TO_DOCUMENT in modules/Makefile.

- test/release/examples/primers/FFTWlib.chpl
Rework FFTW primer comments to try and better fit into an 80-column
format, format some things more consistently, add a mention of the
multithreaded implementation, etc.
> Massage FFTW primer comments

- modules/standard/Random.chpl
* Provide more of an overview of the RandomStream class's capabilities in the module overview
* Emphasize the desire to support other element types in the module-level comments and TODOs, combining with the point about supporting different algorithms
* Add some more hyperlinking and formatting
* Use the 'note' environment which I just learned about today
* Fix a spelling mistake
> Final pass on the Random module documentation for 1.11

- modules/standard/Sys.chpl
I didn't go to the extreme here, but wrote a decent introduction
and cleaned up the chpldoc output (which now mostly shows all of
these constants and functions without comments).
> Improve chpldoc Sys module

- doc/release/README.executing
Updating this paragraph to reflect the new --task-tracking flag.
Also wordsmithed while here.
> Minor edits to task tracking paragraph

- modules/standard/Curl.chpl
- modules/standard/Error.chpl
- modules/standard/HDFS.chpl
- modules/standard/HDFSiterator.chpl
- modules/standard/RecordParser.chpl
- modules/standard/Regexp.chpl
- modules/standard/Sys.chpl
- modules/standard/SysBasic.chpl
Update titles to make the module index nicer for modules that I've documented.
> Chpldoc title fixes

- doc/release/README
README.reduceIntents    :  'reduce' forall intents
> Added README.reduceIntents to doc/release/README

- modules/standard/Regexp.chpl
Improves the Regexp documentation with some examples
as well as clarifying some of the arguments to proc compile.
Also makes compile produce a compiler error (with compilerError)
in case CHPL_REGEXP=="none". That's an improvement over it being
a run-time error. I don't remove the runtime/src/qio/regexp/none
implementation though I could at this point.
Tested with test/io and test/regexp with CHPL_REGEXP=none and CHPL_REGEXP=re2.
> Improve Regexp documentation and add compiler error

- test/records/ferguson/COMPOPTS
- test/records/ferguson/begin-copy.chpl
- test/records/ferguson/begin.chpl
- test/records/ferguson/call-inout.chpl
- test/records/ferguson/call-ref.chpl
- test/records/ferguson/global-assign.chpl
- test/records/ferguson/global-init-assign-typed.chpl
- test/records/ferguson/global-init-assign.chpl
- test/records/ferguson/global.chpl
- test/records/ferguson/global2.chpl
- test/records/ferguson/local-array-assign-read.chpl
- test/records/ferguson/local-array-forallexpr.chpl
- test/records/ferguson/local-array-init-read.chpl
- test/records/ferguson/local-array-init-typed-read.chpl
- test/records/ferguson/local-array-store-assign.chpl
- test/records/ferguson/local-array.chpl
- test/records/ferguson/local-assign.chpl
- test/records/ferguson/local-init-typed.chpl
- test/records/ferguson/local-init.chpl
- test/records/ferguson/local.chpl
- test/records/ferguson/on.chpl
- test/records/ferguson/on2.chpl
- test/records/ferguson/on3.chpl
- test/records/ferguson/on4.chpl
- test/records/ferguson/return-assign.chpl
- test/records/ferguson/return-init-typed.chpl
- test/records/ferguson/return-init.chpl
- test/records/ferguson/return.chpl
- test/records/ferguson/self-pointer-record/myrecord.chpl
- test/records/ferguson/whole-array-assign.chpl
These tests aren't necessarily correct, but I'm committing them to discuss with Tom.
> Strings as rec new tests

- util/pastPerformance/testReleasesPerformance
- util/test/perf/perfgraph.js
The 1.11 release branch was cut Wed Mar-25, 2015.
> Update perf data to include 1.11 release.

- modules/standard/IO.chpl
Lydia fixed the chpldoc problem with these
> Re-enable docs for iodynamic,ionative,iobig,iolittle

- modules/internal/ChapelLocale.chpl
- modules/internal/DefaultRectangular.chpl
- modules/internal/localeModels/flat/LocaleModel.chpl
- modules/internal/localeModels/numa/LocaleModel.chpl
... from leader-follower.
While there, added chpl_
> Switched initOnLocales() to standalone

- modules/standard/IO.chpl
This commit adds a table "Formatted I/O for C Programmers" to the IO.chpl docs.
> Add c formatted io table

- doc/release/technotes/README.llvm
- third-party/llvm/Makefile
Set CHPL_LLVM_DEVELOPER=1 to request a debug build.
Updated README.llvm to indicate that.
> Change LLVM builds to be non-debug by default

- third-party/qthread/Makefile
- third-party/qthread/qthread-1.10/src/interfaces/chapel/tasks-qthreads.c
- third-party/qthread/qthread-1.10/src/interfaces/chapel/tasks-qthreads.h
These are minor changes preceding my starting to push the Chapel Qthreads changes back to the Qthreads team.
> Qthreads merge pre-clean.

- test/REGRESSIONS-stories
Email coming soon with info about signing up, using jira.
> Add jira issue links to REGRESSIONS-stories file.

- compiler/util/OwnershipFlowManager.cpp
We were using the last member of an alias clique in the autoDestroy, but one test case
(hpl-blc.chpl) was failing due to code like this
call_tmp4 = foo();
col = bar(call_tmp4);
if (cond)
{
...
autodestroy(call_tmp4)
autodestroy(T2);
goto _lbl_end;
}
T2 = col; //oops!
Using the named variable in place of the temporary solves this.  No tests regressed as a
result of this change.
Now at 197 > 41 > 7.
> Now use a named variable as the one of an alias clique to autodestroy.

- test/Suppressions/valgrind.suppress
> Add tests failing valgrind in dl_ functions to suppressions

- test/studies/shootout/pidigits/bradc/pidigits-pretty2.chpl
- test/types/string/StringImpl/common/memTrackSupport.chpl
- test/types/string/StringImpl/memLeaks/main.chpl
How did I miss these in https://github.com/chapel-lang/chapel/pull/1873?
> Change printMemLeaksTable to printMemAllocsByType.

- compiler/optimizations/liveVariableAnalysis.cpp
- compiler/passes/parallel.cpp
- compiler/resolution/lowerIterators.cpp
- modules/standard/FileSystem.chpl
- modules/standard/Regexp.chpl
Now at 6 run-time errors, down from 20.
> String as rec bug fixes, week of April 29

- modules/internal/String.chpl
Also fixed a bug when lhs.len+rhs.len == lhs._size
> Fix string append when rhs is empty

- test/io/vass/time-write.prediff
Reverts chapel-lang/chapel#1902
> Revert "Added instrumentation for time-write.chpl failures."

- test/memory/ferguson/test.c
Add ifdefs around define _BSD_SOURCE and _GNU_SOURCE
so it works with GASNet/fifo.
> Fix new test

- runtime/src/qio/qio_formatted.c
Commit two fixups to QIO routines from the new strings branch.
> Qio tweaks

- compiler/passes/codegen.cpp
An early return in codegen prevented the number of statements emitted from
being printed. This updates that logic so that --print-emitted-code-size will
now work with --llvm.
> Allow --print-emitted-code-size to work with --llvm

- util/buildRelease/testRelease
- util/cron/nightly_email.pl
- util/cron/nightlysubs.pm
- util/start_test
* return 0 only with no failures, return 2 if tests ran but some failed
* fix up nightly testing email to accept 2 as OK
* fix garbles in emails from new Summary line for Suppressions
> Minor test system fixups

- test/REGRESSIONS
- test/REGRESSIONS-stories
Updates based on this morning's returns
> More REGRESSIONS updates

- modules/dists/BlockCycDist.chpl
- modules/dists/BlockDist.chpl
- modules/dists/CyclicDist.chpl
- test/distributions/jglewis/cyclicOnEvenNumLocales.compopts
Tell Block, Cyclic and BlockCyclic distributions to give back their local arrays and domains when done
> Add explicit destructors for distributed arrays and domains

- util/cron/test-cygwin32.bat
- util/cron/test-cygwin64.bat
Hopefully we can get a beefier testing environment in the future, but in the
meanwhile we aren't super worried by this decision.
> We decided to reduce nightly cygwin testing to just examples for now.

- modules/standard/IO.chpl
* fixed format implementation to call new string constructor
* Added c_string methods for format, at least for now. These might not be
needed if string literals have type string.
After this change, all tests Tom reported as failing with
Unresolved call to format()
are now working, except for these two (which have other errors):
[Error matching compiler output for distributions/dm/t5a]
[Error matching program output for studies/amr/advection/amr/AMR_AdvectionCTU_driver]
> fix string.format for strings-as-rec branch

- compiler/resolution/wrappers.cpp
- modules/internal/DefaultOpaque.chpl
- modules/standard/Path.chpl
- test/classes/bradc/arrayInClass/arrayInClassRecord.suppressif
- test/studies/beer/bradc/beer-promoted-infer-explicit.suppressif
Get rid of or silence the five remaining valgrind regressions.
> String as rec June03 bugs

- test/users/npadmana/twopt/do_smu.compopts
- test/users/npadmana/twopt/do_smu.skipif
- test/users/npadmana/twopt/do_smu_soa.compopts
* removed compopts tests which were throwing --fast/-O flags, which
we tend to avoid for correctness testing.
* added .skipif for do_smu.chpl which relies on regular expressions
> Minor mods to Nikhil's new tests

- test/GRAPHFILES
- test/users/npadmana/twopt/do_smu.perfkeys
- test/users/npadmana/twopt/do_smu_soa.perfkeys
- test/users/npadmana/twopt/twopt-buildtrees.graph
- test/users/npadmana/twopt/twopt-paircount.graph
Made @npadmana's tests into performance tests as an example demonstrating how this is done.  I expect he'll want to make additional changes, particularly as the code evolved.  Specific actions I took:
* added .perfkeys files to pick out timings that each test takes
* added .graph files to compare two timings that they had in common
* created a new "Nikhil Padmanabhan" suite to the performance tracking suite for these tests
> Making Nikhil's tests into performance tests

- modules/dists/BlockCycDist.chpl
- modules/dists/BlockDist.chpl
- modules/dists/CyclicDist.chpl
- modules/dists/PrivateDist.chpl
- modules/internal/ChapelArray.chpl
- modules/internal/ChapelDistribution.chpl
- modules/internal/DefaultAssociative.chpl
- modules/internal/DefaultOpaque.chpl
- modules/internal/DefaultRectangular.chpl
- modules/internal/DefaultSparse.chpl
- modules/layouts/LayoutCSR.chpl
- test/studies/hpcc/STREAMS/bradc/stream-block1dpar-arr.compopts
- test/studies/hpcc/STREAMS/bradc/stream-block1dpar.compopts
Fix noRefCount assertions.
Add --no-inline-iterators to two tests.
> String as rec June 06 bugs

- doc/chips/4.rst
- doc/chips/README.md
Summarize the current constructor proposal in a ChIP.
For simplicity, the handling of "noinit" was split off as a separate topic.
> Add constructor chip

- man/chpldoc.txt
- test/compflags/thomasvandoren/chpldoc.doc.good
> Add --[no-]print-commands to the man page and the expected output for

- runtime/src/qio/qio_formatted.c
Added lots of comments to the source code about the related
behavior. The bug was because snprintf(buf, n, fmt) returns
the number of bytes needed for the output not including a '\0',
but it always null terminates. So we need to account for the
null terminator to know if the conversion was successful.
> Fix null byte in output bug.

- compiler/resolution/lowerIterators.cpp
test_glob was failing due to a double deletion in the main routine.  This was
due to a call to _freeIterator() that was added by
addCrossedFreeIteratorCalls() before a GotoStmt that actually preceded the
definition of the iterator.
The solution was to look for that case and avoid it.
Prior to applying this patch, the fault can be observed, for example by running:
```
start_test -compopts --no-inline test_glob.chpl -valgrindexe
```
Inlining apparently masks the error.
> Fix addCrossedFreeIteratorCalls.

- util/test/chpl_launchcmd.py
We're having issues with knc testing on kay-esl. See the thread titled "modules
on kay-esl" It's a pretty specific combination of running on an esl, using the
craype-intel-knc module, and passing -V to the qsub reservation to preserve the
environment.
We're trying to figure out a long term solution to what we believe is a bug in
the knc module. In the meantime, unloading the knc module before doing our qsub
reservation works around the issue. Note that this patch is careful to make
sure self.knc will still return true even after we unload the knc module since
chpl_launchcmd relies on self.knc to add extra flags to the qsub reservation.
> Round 2 of working around knc module bug

- compiler/passes/parallel.cpp
The test case distributions/diten/Cyclic.chpl fails unless the domain task arg
is copied (because it is a temporary returned by the iterand of a coforall).
The autoCopy call is only needed to more the ref count of a ref counted type
away from zero.
The need for an autoCopy only applies to a local variable.  One that is
declared in an outer scope can be referred to (i.e. passed by reference).
The code in parallel.cpp to set up task function calls started out (as of last
release) copying none of the task args (of record or RWT type, passed by
value).  I change that to copy all of them.  This patch is the compromise
solution, copying only those arguments that need to be copied.
> Only add autoCopy/autoDestroy calls on cobegin/coforall task args that are local

- runtime/include/chpl-tasks.h
> Clarify the CHPL_TASK_STD_MODULES_INITIALIZED() comment.

- doc/release/README.launcher
- doc/release/README.multilocale
Updates these READMEs based upon my latest experiences.
Reviewed by @gbtitus, thanks!
> Update README.multilocale and README.launcher

- doc/chips/2.rst
Based on discussions with @lydia-duncan. The approach I am taking here
is to iterate on the design with a few people before asking again for consensus.
> Update the constrained generics CHIP # 2

- doc/chips/README.md.in
- doc/chips/update-readme.bash
Creates README.md.in and an update-readme.bash that generates the table of CHIPS.
> Add a mechanism to generate README.md (for table of CHIPs)

- doc/chips/6.rst
- doc/chips/README.md
This is my proposed solution to the issues discussed at the latest group deep dive on tuples, and generally the long-overdue topic of tuple semantics.
I intend to be guided by this CHIP in my intents-during-resolution compiler work effective immediately. If I encounter cases where this affects the user-visible behavior significantly, I may reconsider.
In any case, post-commit reviews, suggestions, fixes are always welcome.
> Added a CHIP on tuples

- modules/standard/Random.chpl
And renamed these private symbols to lose the RandomPrivate_ prefix.
@bradcray, this has passed full testing now.
> Apply private to some "no doc"ed symbols in the Random module

- modules/standard/GMP.chpl
Passed full testing with GMP enabled
> Add private to symbols marked "no doc" in GMP module

- modules/standard/FileSystem.chpl
@bradcray, did I correctly privatize that module?
> Add private to a helper function and module in FileSystem module

- compiler/resolution/lowerIterators.cpp
This is a spot I missed in #2143.
While there, I moved the comments from this fragment into getTheIteratorFn().
> Factored out one more fragment into getTheIteratorFn()

- compiler/resolution/generics.cpp
(a) I noticed that #2078 (tuple autoCopy) also applies to tuple initCopy.
At which point the two compiler functions became very similar:
instantiate_tuple_initCopy()
instantiate_tuple_autoCopy()
so I went ahead and factored them into:
instantiate_tuple_initCopy_or_autoCopy()
As part of it, #2078 (passing through, not copying, tuple components
that have ref types) now applies to tuple initCopy.
(b) While there, I factored out the detection of the tuple type into:
getTupleArgAndType()
because I am going to change that slightly in my work of ensuring proper
argument intents during resolution.
> Factored out some tuple code + minor fix.

- modules/standard/VisualDebug.chpl
- runtime/src/chpl-visual-debug.c
Fix some files missed in PR 2261.
-- += in runtime/src/chpl-visual-debug.c
-- Add a comment in modules/standard/VisualDebug.chpl to explain VDebugTree
> Phil debug

- util/start_test
Add missing path
Only print junit xml info, don't put it in the summary file
> Start test fixes

- util/test/computePerfStats
There were a few problems with the new python computePerfStats.  This PR should
fix those issues.  It also increases Python 3 compatibility.
> Fixed computePerfStats errors

- modules/internal/ChapelRange.chpl
- modules/internal/String.chpl
- test/distributions/dm/t5a.comm-none.good
- test/types/string/kbrady/multilocale/split.chpl
- test/types/string/kbrady/multilocale/split.good
- test/types/string/kbrady/split.chpl
- test/types/string/kbrady/split.good
Add a cast from `range(?) -> string`.
Add `proc *(string, integral)`.
> Convert string.split to an iterator

- util/test/sub_clean
Update sub_clean to also clean C tests using the .cleanfiles file
> Update sub_clean to also clean C tests using the .cleanfiles file

- modules/internal/String.chpl
- test/types/string/bradc/substring/substringBadRange3.good
- test/types/string/bwross/string_index.good
- test/types/string/ferguson/join.future
- test/types/string/ferguson/split.chpl
- test/types/string/ferguson/split.future
- test/types/string/kbrady/split.chpl
- test/types/string/kbrady/split.good
The maxsplit optional parameter was not working correctly. Also updated
my allocation sizes in several places.
> Fix split on strings

- compiler/AST/expr.cpp
- compiler/passes/parallel.cpp
Fix coding error in codegen for wide-to-wide assignment.
Fix logic error in makeHeapAllocations.
> Fix no local errors

- compiler/include/OwnershipFlowManager.h
- compiler/util/OwnershipFlowManager.cpp
- modules/internal/String.chpl
- test/expressions/lydia/noinit/usedWithString.good
- Update usedWithString.good for changed line number in String.chpl module.
- Revert the "fix" for split.chpl.
- Fix the segfault in split.chpl.
- Fix getLastExprInBB().
> August 13 bug fixes

- compiler/optimizations/copyPropagation.cpp
Increased use of reference variables on the string-as-rec branch put extra
pressure on the copyPropagation optimization.
It forces a distinction between the semantics of PRIM_ASSIGN vs. PRIM_MOVE when
both operands are references.  Namely, PRIM_ASSIGN will dereference the RHS
operand, and copy the bits of the object it points to into the object pointed
to by the LHS.  In contrast PRIM_MOVE merely copies one reference into the
other -- basically a pointer copy.
Based on this distinction, code in extractCopies() was updated so we do
*not* create a symbol pair when PRIM_ASSIGN has two reference arguments.
This resolves the failing test case statements/vass/index-variable-accesses.chpl.
> Fix overaggressive copy propagation.

- compiler/passes/parallel.cpp
Test cases
optimizations/bulkcomm/asenjo/ptransDR/v2/ptrans.1.comp.out.tmp:1:
release/examples/benchmarks/hpcc/stream-ep.comp.out.tmp:1:
were failing under no-local.
Code for inserting autoCopy calls when setting up task function calls in
taskMayOutliveTaskArg() calls findTaskScope() which in turn calls
findSiblingCallPreceding().  The purpose of this is to find the scope in which
a given actual argument is declared and compare this with the scope in which
the task is set up.  If the actual is declared inside that scope, then a copy
is required (because it may die before the task completes).
The findTaskScope function assumes that a call to _upEndCount() appears just
inside the task scope, and uses this as a sentinal to identify the task scope.
In the affected test cases, however, the …
> Fix for no-local compile-time errors.

- test/modules/standard/LAPACK/LAPACK_example.chpl
- test/modules/standard/LAPACK/dgees.chpl
- test/modules/standard/LAPACK/dgesv.chpl
- test/modules/standard/LAPACK/dgesvd.chpl
- test/modules/standard/LAPACK/sgesv.chpl
Changed _all_ instances of c_double and c_float to real(64) and real(32) respectively
c_int remains for C reasons.
Tested and works on XC machine under gnu environment
> LAPACK Chapel types

- modules/internal/ChapelBase.chpl
In _waitEndCount, we now  decrement the running task count before waiting for
all spawned tasks to complete. Then we increment after all tasks are done.
The original task will just be waiting and yielding so we alter the
runningTaskCount to better utilize all the cores.
This was discovered as part of the steam-ep performance work, where locale 0
(where the coforall occurred) had more running tasks. While it's technically
true that the task is still running it's just doing a waitFor(), which will
yield the processor so we might as well do some real work.
Now something like:
```chapel
coforall loc in Locales do on loc {
writeln(loc.runningTasks());
}
```
should report 1 running task everywhere. It does always report 1 when using
network atomics. Unfortunately it's hard to make a portable …
> Don't count the waiting task in _waitEndCount as a running task

- modules/internal/ChapelBase.chpl
See the comment in init_elts for more details
> Improve parallel init_elts heuristic.

- compiler/optimizations/deadCodeElimination.cpp
Will only fire when a variable is defined once via an autoCopy and is only used
in one autoCopy and one autoDestroy.  If a variable has an additional use, it
will not trigger this optimization.  This conservativeness is necessary for
correctness and to avoid memory leaks.  Once a variable has been determined
as eligible for this optimization, its autoDestroy function will be removed and its
use in the autoCopy function will be replaced by the argument to its defining
autoCopy.  In this way, chains of extra autoCopys will be condensed into a single
autoCopy call, and the no longer valid autoDestroy calls will be removed.  The
initialization and DefExpr for this variable will also be removed, as it no longer
needs to live in the code base (and is in fact dead).
It may be possible to apply …
> Add optimization to remove extra autoCopy/autoDestroy pairs

- util/cron/test-cygwin64.bat
This reverts commit d01d51ce3af741b9c9327f53bc25c76ea743cfbd.
> Revert "Temporarily run modules/standard/FileSystem/fsouza/chown/ for cygwin64

- test/types/type_variables/ferguson/ispod.chpl
- test/users/vass/crash4replLclsWFlds.chpl
#2387 disallowed pragma "auto destroy fn".
Here I am removing a couple of left-over pragmas in the tests.
> Removed more "auto destroy fn" pragmas

- test/modules/standard/FileSystem/fsouza/chown/permission_error.prediff
- util/cron/test-cygwin64.bat
Revert the change made to the prediff and to the nightly test, I'm done debugging this test
> Revert all changes made to debug the cygwn permission_error regression

- runtime/src/chpl-visual-debug.c
Should have been part of previous PR.   Merged too fast.
> Document a bug we are working around for now.

- compiler/passes/insertAutoCopyAutoDestroy.cpp
- compiler/util/OwnershipFlowManager.cpp
The insertAutoCopyAutoDestroy pass relies on a simple restructuring
of each function's body, to facilitates ownership analysis
in the presence of early returns.
Namely, the bulk of the function body is moved into a newly-created
nested scope. I.e. the function body like this:
{
DefExpr ret;
STATEMENTS;
DefExpr _end_PROCNAME;
return ret;
}
is restructured to:
{
DefExpr ret;
{
STATEMENTS;
}
DefExpr _end_PROCNAME;
return ret;
}
(Implementation-wise, the original function-body BlockStmt is retained,
and a new BlockStmt for the outer scope is created.)
The analysis used to produce incorrect results e.g. in these tests:
modules/standard/FileSystem/lydia/copy/copying
modules/standard/FileSystem/lydia/copyFile/copyingContents
modules/standard/FileSystem/lydia/copyTree/copying …
> Fixed placement of some autoDestroys

- modules/internal/ChapelBase.chpl
Do parallel initialization for "large" numeric arrays. Large being at least
2MB, which was chosen experimentally by comparing the performance of serial vs.
parallel initialization on a 2 core laptop, 8 core server, and 24 core XC40.
Long term we want users to be able to specify how an array should be
initialized. In the short term, we want users to be able to get better first
touch behavior out of arrays. As a parallel language we believe it's safe to
assume that most large arrays will be used in parallel, and thus defaulting to
parallel initialization will usually result in better first touch behavior. For
the stream benchmark, this results in a 2x performance improvement.
The reason this is limited to numeric types is because we ran into issues
trying to parallel initialize arrays of …
> Initialize "large" numeric arrays in parallel by default

- compiler/include/OwnershipFlowManager.h
- compiler/passes/insertAutoCopyAutoDestroy.cpp
- compiler/util/OwnershipFlowManager.cpp
* Added more debugging functions.
* Shortened the names of the existing functions, for convenience.
* Moved existing debugging functions from .h to .cpp.
> Enhance debugging support in OwnershipFlowManager

- test/release/examples/benchmarks/hpcc/stream-ep.chpl
The optimizations in #2303 eliminate the need for the local block in stream-ep. I have confirmed that there is no performance loss for multilocale. This patch also updates some comments referring to the local block that no longer exists.
> Remove local block from stream-ep

- runtime/src/chpl-visual-debug.c
@gbtitus here is the new PR
@Kyle-B does this work for you?
> Use POSIX rather than BSD

- tools/chplvis/ConcurrencyWin.cxx
- tools/chplvis/DataModel.cxx
- tools/chplvis/DataModel.h
- tools/chplvis/Event.h
- tools/chplvis/Makefile
Current state includes Clock, Gets, Puts and Forks in the tool tip in the concurrent task window.
> Track communication and forks in data model

- test/distributions/sungeun/equality1.future
- test/distributions/sungeun/equality2.future
With the addition of distribution in/equality in PR #2450, these
futures now pass.
> Retire these futures

- test/parallel/forall/vass/ri-1.chpl
- test/parallel/forall/vass/ri-1.sa.good
- test/parallel/forall/vass/ri-4-arrdom.chpl
- test/parallel/forall/vass/ri-4-arrdom.good
* ri-1.chpl -- beefed it up slightly, as enabled by #2462
* ri-4-arrdom.chpl -- reduced problem size to avoid valgrind timeout
> Updated tests of reduce intents

- util/test/activate_chpl_test_venv.py
...though I have to wonder... shouldn't it be based on the host
platform rather than the target one...?
> Fixing the location of the chpl-venv directory used by default

- doc/developer/bestPractices/TestAnnotationsLocally.txt
- test/ANNOTATIONS.yaml
Not yet tested because chap04 annotations seem to be broken in general
(unrelated to this commit).
Also added a best practice that I wrote awhile back but never committed
giving steps to test annotations locally.
> Annotations updates co-developed by the perf team in this week's meeting

- compiler/passes/parallel.cpp
#2462 exposed an omission in makeHeapAllocations(),
specifically a PRIM_ASSIGN into a heap-allocated variable.
This change fills it in.
Passes standard testing and gasnet testing on multilocale tests.
> Handle PRIM_ASSIGN in makeHeapAllocations()

- test/parallel/taskPar/sungeun/barrier/commDiags.chpl
- test/parallel/taskPar/sungeun/barrier/commDiags.good
I think I made the wrong choice with https://github.com/chapel-lang/chapel/pull/2527
After doing a gasnet run, I realized the writeln output was in the gasnet .good file. 
I reverted that change, and updated the .good file used for comm=none
> Re-add comm diags writelns and update comm-none .good fie 

- compiler/passes/parallel.cpp
Make the code I added in #2526 fit style-wise with the surrounding code.
Requested by Elliot.
Does not affect compilation.
> Make the addition in #2526 fit style-wise

- modules/standard/Spawn.chpl
fork doesn't currently work with ugni when memory is registered with the NIC
and it will result in a segfault. Until we resolve that issue, this adds a halt
and nice error message to tell users what went wrong so they aren't just hit
with an unexplained segfault.
Note that the runtime spawn code will use vfork over fork when stdin, stdout,
stderr=FORWARD so we don't halt in that case. Additionally memory isn't
registered with the NIC when numLocales == 1, so we don't halt then either.
See JIRA issue 113 for more info: chapel.atlassian.net/browse/CHAPEL-113
> Add halt to spawn() for CHPL_COMM=ugni

- doc/release/platforms/README.cray.rst
These links are not quite ready to be in the source tree, remove them
for now.
> Remove some links that are not ready for primetime from README.cray

- doc/release/platforms/README.ibm.rst
- doc/release/platforms/README.marenostrum.rst
- doc/release/platforms/README.sgi.rst
- doc/release/platforms/README.tilera.rst
- doc/release/technotes/README.localeModels.rst
While there, did minor wordsmithing throughout and
converted a bullet to a heading in localeModels.rst.
> Converted four READMEs to reST

- doc/sphinx/Makefile.sphinx
Small Makefile output change to give better description of sphinx build location.
> Makefile.sphinx gives actual location of build

- CHANGES
Wrote this on the plane ride back Friday night; just finished some sorting of entries now.
> First draft of CHANGES for version 1.12

- etc/vim/README
The earlier commit didn't mention it included
nice editor settings to support chpldoc.
> Adjust vim README comment

- modules/Makefile
- modules/standard/Spawn.chpl
Add chpldoc documentation for the Spawn.chpl module
> chpldoc Spawn.chpl

- doc/release/README.building.rst
Virtually no content changes, just reST markup to format things.
> Add reST markup for README.building

- doc/release/technotes/README.extern.rst
This PR is formatting only. I intend to make content changes
and further beautification changes in a separate PR.
> RST version of README.extern

- modules/standard/Spawn.chpl
Lydia suggested using versionadded, so did that.
Greg and Elliot suggested decribing the ugni problem
with Spawn, so did that. Greg reviewed the text
added.
> Update spawn module chpldoc

- doc/release/technotes/README.module_search.rst
module_search -> module_search.rst (Lydia can content-review)
> reSTified a README that slipped through the cracks

- doc/release/technotes/README.allocators.rst
Minor clean-ups. Trivial, not reviewed.
> Minor formatting changes to README.allocators

- doc/release/technotes/README.auxIO.rst
Minor formatting, cross-referencing cleanups.
> minor README.auxIO updates

- doc/release/technotes/README.reduceIntents.rst
and rephrased a couple of things while there.
> RST-fied README.reduceIntents

- doc/release/README.compiling.rst
- doc/release/README.debugging.rst
- doc/release/README.executing.rst
- doc/release/technotes/README.firstClassFns.rst
Update some readmes to add cross-references and other minor edits.
> Minor edits to a few readmes

- doc/release/platforms/README.cygwin.rst
- doc/release/platforms/README.ibm.rst
- doc/release/platforms/README.knc.rst
- doc/release/platforms/README.macosx.rst
- doc/release/platforms/README.marenostrum.rst
- doc/release/platforms/README.sgi.rst
Includes unifying the headers, adding cross references, content review, adding warnings to stale READMEs. 
Each file has an individual commit with more details on what exactly changed.
> Update platform readmes

- doc/sphinx/source/index.rst
- doc/sphinx/source/modules/builtins.rst
- doc/sphinx/source/modules/distributions.rst
- doc/sphinx/source/modules/layouts.rst
- doc/sphinx/source/modules/modules.rst
- doc/sphinx/source/modules/standardlibrary.rst
- doc/sphinx/source/platforms/index.rst
- doc/sphinx/source/technotes/index.rst
- doc/sphinx/source/usingchapel/index.rst
Ref names for index files in case we need to link to them.
> Adding ref names for index files

- doc/release/platforms/README.cray.rst
- doc/release/platforms/README.ibm.rst
- doc/release/platforms/README.marenostrum.rst
- doc/release/platforms/README.sgi.rst
- doc/release/technotes/README.localeModels.rst
Also converted "top-level README" to README.md with a github link.
> Converted references to README to :ref: style

- doc/release/README.multilocale.rst
Small content update to provide a link to platforms documentation.
> Minor content update to multilocale readme

- doc/sphinx/Makefile.sphinx
- doc/sphinx/source/conf.py
A common mistake amongst new Crayons
> Cray Inc, not Cray, Inc

- doc/release/README.bugs.rst
Take a pass over this for wording, formatting, and making good use of rst.
> Reformatting and wording of our bug report instructions

- doc/release/README.chplenv.rst
Made a pass over REAMDE.chplenv to update it for looks and to insert
cross-references.
> Clean up README.chplenv

- doc/release/technotes/README.libraries.rst
The instructions in this README were out of date.  After determining how to use this
feature, I updated it to reflect the necessary steps.  I would not recommend using this
feature as it is very brittle, but if one is curious and determined, these steps will be
useful.
> Update library readme

- doc/release/technotes/README.module_search.rst
I don't think this needs further content updates.
> Fix a couple of typos in README.module_search.rst

- doc/release/technotes/README.subquery.rst
Fix subquery title; Add path for distributions primer.
> Subquery readme fixes

- doc/release/technotes/README.auxIO.rst
- doc/release/technotes/README.llvm.rst
* shorten README.auxIO's title
* add a ref from README.llvm to README.extern
These changes requested by @ronawho.
> Minor README updates

- CONTRIBUTORS
This is a first draft, though I need to poll people and review the CLAs to see who I might be forgetting.
> Some updates to CONTRIBUTORS in preparation for 1.12

- doc/release/README.chplenv.rst
Improved table of contents and linking, should be easier for a user to navigate this page.
> Minor chplenv readme layout change

- doc/release/technotes/README.llvm.rst
"LLVM support" => "LLVM Support"
> Title case README.llvm

- doc/release/README.building.rst
- doc/release/README.multilocale.rst
Update a few cross references in README.multilocale and README.building.
> Update readme cross references

- CHANGES
> draft CHANGES for 1.12

- doc/release/technotes/extern.rst
Fixes are the suggestion of @bradcray.
> Fix require in extern readme

- doc/release/chplenv.rst
Rendered files are in http://web/~gbt/Chapel-docs/html/
> Clarify discussion of CHPL_TASKS default.

- util/buildRelease/gen_release
print $CHPL_HOME in gen_release
> Printing CHPL_HOME in gen_release

- util/buildRelease/gen_release
> Fixed Perl syntax

- doc/chips/7.rst
- doc/chips/README.md
Draft proposal for rules for inserting autoCopy and autoDestroy calls.
> Added CHIP 7, autoCopy insertion rules

- modules/standard/Math.chpl
Change suggested by @bradcray.
> Move math constants to top of Math.chpl

- compiler/passes/filesToAST.cpp
- compiler/resolution/callDestructors.cpp
- compiler/util/Makefile.share
- modules/internal/ChapelBase.chpl
- modules/internal/ChapelDistribution.chpl
- modules/internal/DefaultRectangular.chpl
- modules/internal/DefaultSparse.chpl
- modules/standard/Path.chpl
- modules/standard/Regexp.chpl
- spec/Input_and_Output.tex
This patch modifies string-as-rec spaces to reduce the
difference with master.
> Remove string-as-rec specific space changes

- man/chpldoc.txt
- test/compflags/thomasvandoren/chpldoc.doc.good
Forgot to update man-page and chpldoc.good for testing new chpldoc flags. Confirmed with paratest.
> Updated man-page and tests to reflect chpldoc flags

- compiler/AST/type.cpp
- compiler/ifa/num.h
- compiler/include/baseAST.h
- compiler/passes/reservedSymbolNames
- modules/internal/AtomicsCommon.chpl
- modules/internal/ChapelArray.chpl
- modules/internal/ChapelDistribution.chpl
- runtime/include/chplmemtrack.h
This PR is a collection of trivial changes from string-as-rec.  I think
these changes are good, but they are generally tiny code and comment
changes. Each commit describes each individual change.
Reviewed by @lydia-duncan, thanks!
> Trivial changes from string-as-rec

- compiler/AST/bb.cpp
- compiler/include/bb.h
Some minor reformatting etc on string-as-rec in preparation for closing the deltas on bb.{h,cpp}.
No changes in behavior.  Consistent error count for linux64 on string-as-rec.
> Jira 125 sar

- compiler/AST/bb.cpp
Fix a minor braces issue in the middle of a function.
> Another trivial tweak for the BB merge

- compiler/AST/bb.cpp
- compiler/include/bb.h
First step to close deltas between string-as-rec and master for bb.h / bb.cpp.
1) Imported bb.h; some indenting changes and declarations for 3 new methods
2) Simple whitespace tweaks
3) Import three new methods.  These are used on string-as-rec but not currently used on master
All changes are "trivial".  Ran a full linux64 para-test to verify.
> Jira 125 mas

- compiler/resolution/callDestructors.cpp
Non-functional changes designed to clarify the deltas between string-as-rec and master.
Expected number of failures on string-as-rec
> JIRA 143 call-destructors.cpp

- compiler/resolution/callDestructors.cpp
One more trivial change to reduce a delta compared to master
> JIRA 143 callDestructors.cpp

- modules/internal/ChapelBase.chpl
> Remove trailing spaces

- compiler/AST/iterator.cpp
Non-functional changes to rebuildGetIterator() to highlight the deltas between string-as-rec and master
1) Adjustments to honor 80 column target
2) Isolate the portion of rebuidGetIterator() that handles autoCopy for array/domain/distributions.
A run of linux64 had the expected regressions.
> jira 128 :- Trivial changes on string-as-rec to reduce deltas

- compiler/AST/iterator.cpp
Trivial and non-functional updates to rebuildGetIterator on master to reduce the deltas between
master and string-as-rec.
1) Copy some formatting changes that honor the 80 column goal
2) Non-functional changes that help to highlight the string-as-rec code that inserts
autoCopies for array/domain/distributions.
Passes on linux64.
> Jira 128 :- Trivial changes on master to highlight remaining deltas

- test/ANNOTATIONS.yaml
Ben pointed out that I'd made a typo in one of the annotations I added
yesterday.  That'll teach me to go too fast!
> Fix annotations bug

- modules/internal/String.chpl
Also corrected a few checks on the locality of a c_string.
(c_string.locale will always return the executing locale)
> Fix ascii(string) to work correctly when the arg is remote

- test/memory/sungeun/refCount/domainMaps.linux32.good
> Update linux32 memory leak count (reduction in leaks)

- compiler/resolution/functionResolution.cpp
A trivial change that adds FLAG_INSERT_AUTO_DESTROY for the formal_tmp variables
that are created to support functions that accept formals by out intent.  This path is now
consistent with other formals with in intent etc.
Fixes 3 of Michael's record stress tests.
Passes paratest on linux64
> Fix leak for tmps that support out intent

- compiler/passes/normalize.cpp
Calls to initCopy() for building tuples failed to autoDestroy the temps that were used to construct
the call the build_tuple.  Update the code to handle this case specially and attach the required
annotation.
Although the code is in normalize() it is triggered by expanding a generic use of initCopy while in
reconcile; and hence was tricky to track down.
This patch is a focussed change this this case and hence is a "trivial" change.  This reduces the error
count for Michael's record stress tests but does not introduce any new regressions for the remaining
tests.
However this is an unsatisfying way to "trick" callDestructors in to insert autoDestroy when needed.
> Add an AUTO_DESTROY annotation when normalizing build_tuple

- test/arrays/ferguson/choose-array/choose-array10.bad
- test/arrays/ferguson/choose-array/choose-array2.bad
They were causing failures in gasnet testing.
> Remove these .bad files since failure depends on config

- compiler/AST/type.cpp
I didn't notice that I hadn't pushed this before merging
my PR (it has been tested)
> Minor code cleanup that should've gone in with PR #2882

- modules/standard/IO.chpl
These changes are intended to clarify that usually channel.flush()
is not necessary to call before channel.close().
Changes suggested by @vasslitvinov.
> Updates to IO chpldoc

- test/memory/sungeun/refCount/domainMaps.comm-gasnet.good
- test/memory/sungeun/refCount/domainMaps.lm-numa.good
- test/memory/sungeun/refCount/domainMaps.no-local.good
Update domainMaps .good files to reflect leak reduction as a result of f68a24b5
> Update .good files for domainMaps test

- test/ANNOTATIONS.yaml
Nice performance improvement now that re2 is being built with optimizations
> Add perf annotation for regexdna improvement

- compiler/resolution/callDestructors.cpp
The compiler was inserting inappropriate initCopy/autoCopy calls for the return value from some functions that return strings.  The first commit detects this pattern in a "peephole" fashion, for now,
and removes these.
Removing these leaks introduced double-free/memory corruption errors for some tests; this occurred
for functions that return strings and that should have autoCopied the value that was about to be
returned.
1) Functions that receive a string as a formal using ref or const ref intent
2) Functions that return a string that is stored in a module-level variable
The second commit adds the required autoCopy for these two situations.
Both of these commits introduce code that should be generally applicable to Records but 
a) is only currently being applied to strings
b) is therefore …
> Integrate new memory leak fixes for Strings to master

- test/types/string/StringImpl/memLeaks/relational.suppressif
- test/types/string/StringImpl/memLeaks/substring.suppressif
- test/types/string/StringImpl/stress/plusEquals.suppressif
These were introduced by the strings commit.
> Add a few .suppressifs for multilocale memory leaks

- test/ANNOTATIONS.yaml
Lots of nice perf improvements from this!
> Add perf annotation for defaulting to qthreads+hwloc for cce

- runtime/src/comm/gasnet/comm-gasnet.c
This fixes two problems and slightly improves the code.
The first problem was that for a REPLY_PUT, the info block "ack" member
wasn't initialized with the address of the done counter as it needed to
be.  This now fixed.
The second problem was that in AM_reply_put() we were responding with a
completion signal that was piggybacked on a gasnet_AMReplyLong2().  That
signal was delivered to the usual AM_signal() handler.  But that handler
is only appropriate for gasnet_AMReplyShortM() calls.  Handlers for
gasnet_AMReplyMediumM() (we don't use this) and gasnet_AMReplyLongM()
have different prototypes.  Thus the arguments for the handler were
incorrect, and the done counter manipulations caused segfaults.  The fix
is to add a new SIGNAL_LONG completion handler with the right prototype
for …
> Fix completion processing for REPLY_PUT operations.

- .gitignore
- runtime/include/tasks/qthreads/tasks-qthreads.h
- runtime/src/tasks/qthreads/tasks-qthreads.c
At Greg's request, here's a simple PR with the qthreads tasking shim. I did have to remove /runtime/include/tasks/qthreads/ from the gitignore, I hope that's OK.
> Added qthreads tasking shim

- test/memory/sungeun/refCount/domainMaps.cygwin32.good
Updating based on improvements due to string work.
> Updating cygwin32 domainMaps.good file

- compiler/resolution/callDestructors.cpp
updateAssignmentsFromRefTypeToValue in callDestructors is intended to prevent double-frees by inserting an additional autoCopy. In some cases this autoCopy was unnecessary, was never free'd, and resulted in memory leaks (e.g. release version of regexdna). The particular case that revealed this issue involved an initCopy of the same variable for which we intend to insert an autoCopy. The (hacky) solution is to not insert an autoCopy if the copied variable is also used inside an initCopy.
> Prevent insertion of a redundant autoCopy for strings

- compiler/AST/expr.cpp
- compiler/AST/symbol.cpp
- compiler/include/clangSupport.h
- compiler/include/clangUtil.h
- compiler/include/codegen.h
- compiler/include/llvmGlobalToWide.h
- compiler/include/llvmUtil.h
- compiler/passes/codegen.cpp
- compiler/util/clangUtil.cpp
- compiler/util/llvmAggregateGlobalOps.cpp
- compiler/util/llvmGlobalToWide.cpp
- third-party/llvm/unpack-llvm.sh
- third-party/llvm/update-llvm.sh
Upgrade to LLVM 3.7.
We use #ifdefs to allow our code base to compile with multiple versions
of LLVM.  We might want to remove some of the #ifdef ugliness once we
decide older versions of LLVM are no longer necessary to support.
Most of the changes are from minor API changes in LLVM 3.7. One common
one that functions operating on pointers now often take in a type as the
first argument when they did not previously.  We pass in NULL for now,
but in LLVM 3.8 we will need to do something better since the plan is to
make all LLVM pointers untyped.
A big chunk of the diff is a re-write of CCodeGenConsumer based on a
recent version of the LLVM code it is based upon.
I actually completed most of the work to get LLVM 3.7 working last summer
in order to support a contributor. In this PR, I clean up …
> LLVM 3.7 support

- test/GRAPHFILES
I forgot to add it in my last PR.
> Add new perf test to graphfiles

- modules/internal/localeModels/numa/LocaleModel.chpl
(Fix typo I introduced with #3061 last night.)
> Fix a flawed comment I introduced last night.

- util/cron/test-perf.chapcs.numa-playground.bash
> Reduce numa playground to one trial

- spec/Input_and_Output.tex
Updated outdated ChapelIO module link in spec.
> updated ChapelIO module link

- test/studies/labelprop/labelprop-tweets.chpl
- test/studies/labelprop/labelprop-tweets.execopts
- test/studies/labelprop/labelprop-tweets.good
turns off parallelism for correctness testing
> Make this test deterministic

- util/cron/test-perf.chap04.playground.bash
Greg and I our curious about the perf impact of his simplification of the
structured parallelism interface (which really cleans up/simplifies fifo.) As a
quick and easy way of getting these numbers, we're just going to test it in the
playground before and after his commit to see.)
> Test out perf impact of #3178 in chap04 playground

- spec/Modules.tex
Obvious wordsmithing that no one objected to via email, unreviewed.
> Make user-suggested changes to our module visibility section in the spec

- compiler/AST/stmt.cpp
Minor tweak to resolve valgrind errors.  Implemented by Brad.  I reviewed, tweaked,
and did additional testing.
> Ensure every field of UseStmt is initialized

- test/visibility/except/checkUsePathBadAccess.chpl
- test/visibility/except/checkUsePathBadAccess.compopts
- test/visibility/except/checkUsePathBadAccess.good
- test/visibility/except/checkUsePathBadFunctionAccess.chpl
- test/visibility/except/checkUsePathBadFunctionAccess.compopts
- test/visibility/except/checkUsePathBadFunctionAccess.good
- test/visibility/except/checkUsePathWorks.chpl
- test/visibility/except/checkUsePathWorks.compopts
- test/visibility/except/checkUsePathWorks.good
- test/visibility/except/usePath/M.chpl
- test/visibility/only/checkUsePathBadAccess.chpl
- test/visibility/only/checkUsePathBadAccess.compopts
- test/visibility/only/checkUsePathBadAccess.good
- test/visibility/only/checkUsePathBadFunctionAccess.chpl
- test/visibility/only/checkUsePathBadFunctionAccess.compopts
- test/visibility/only/checkUsePathBadFunctionAccess.good
- test/visibility/only/checkUsePathWorks.chpl
- test/visibility/only/checkUsePathWorks.compopts
- test/visibility/only/checkUsePathWorks.good
- test/visibility/only/usePath/M.chpl
At lunch, Ben H. had suggested looking at this as a corner case I may have
missed.  It works just fine, and I figured testing that regularly was a good
thing to do while I was thinking about it.
> Add some tests of the 'only' and 'except' keywords with the -M flag

- doc/sphinx/source/users-guide/index.rst
- doc/sphinx/source/users-guide/locality/onClauses.rst
- test/release/examples/users-guide/locality/coforallPlusOn.chpl
- test/release/examples/users-guide/locality/coforallPlusOn.comm-none.good
- test/release/examples/users-guide/locality/coforallPlusOn.good
- test/release/examples/users-guide/locality/coforallPlusOn.prediff
- test/release/examples/users-guide/locality/dataDrivenOnClause-trivial.chpl
- test/release/examples/users-guide/locality/dataDrivenOnClause-trivial.good
- test/release/examples/users-guide/locality/onClause.chpl
- test/release/examples/users-guide/locality/onClause.comm-none.good
- test/release/examples/users-guide/locality/onClause.good
- test/release/examples/users-guide/locality/onClausePlusOrig.chpl
- test/release/examples/users-guide/locality/onClausePlusOrig.comm-none.good
- test/release/examples/users-guide/locality/onClausePlusOrig.good
This adds a new page to the user's guide describing on-clauses and four new tests which are referenced within the page.
> Users guide on clauses

- test/ANNOTATIONS.yaml
Adding reference to #3288 in perf data annotations.
> Annotations for PRK improvements

- modules/Makefile
- modules/internal/String.chpl
- modules/internal/fixInternalDocs.sh
Also fixed a small bug in isPrintable where I had a < where it should've
been a <=.
> Add chpldoc comments to String.chpl

- runtime/src/mem/jemalloc/mem-jemalloc.c
Move all our static variables that are used to support the shared heap into a
struct. This is a minor code cleanup, it shouldn't impact performance or
anything.
See JIRA 186 for more info: https://chapel.atlassian.net/browse/CHAPEL-186
> Clean up jemalloc shared heap support

- runtime/src/mem/jemalloc/mem-jemalloc.c
Previously we would waste whatever memory jemalloc got from the system (and
thus wasn't in our shared heap) by allocating `sizeof(size_t)` a bunch of
times. Unfortunately this ended up requiring around 130,000 allocations because
jemalloc grabs memory in terms of "chunks" which default to 2MB. Even more
unfortunately it turns out that some size classes could still be allocated
outside of our shared heap because certain fragments of a chunk were reserved
for specific class sizes and we weren't wasting those.
Now what we do is we iterate through all of jemalloc's large and small size
classes and allocate objects until we get one that's in our shared heap. We can
then free that object, and precede onto the next size.
The end result is that we only need ~130 allocations, and we waste very …
> Waste jemalloc memory that's not in our shared heap faster/smarter

- test/release/examples/programs/linkedList.chpl
- test/release/examples/programs/linkedList.good
Changed linkedList.chpl and linkedList.good files
> linkedList new functions added

- test/ANNOTATIONS.yaml
> ISx and array vs ddata annotations

- test/distributions/kushal/assignDomain.bad
- test/distributions/kushal/assignDomain.chpl
- test/distributions/kushal/assignDomain.future
- test/distributions/kushal/assignDomain.good
- Contains sample code to demonstrate the issue.
- Contains a .future file explaining the issue.
- Separate .good and .bad file have been also added to compare outputs.
> Bug : Assigning distributed domains to non-distributed domains is not supported

- test/release/examples/programs/linkedList.good
It appears today's edits to linkedList.good were never tested...the whitespace was wrong...
> Fix linked list example expected output

- test/release/examples/programs/linkedList.chpl
Removed all writeln calls as suggested by mppf
> Updated linkedList.chpl

- test/ANNOTATIONS.yaml
> Annotate ISx XC tests

- test/users/ferguson/bug-zhao.bad
- test/users/ferguson/bug-zhao.chpl
- test/users/ferguson/bug-zhao.future
- test/users/ferguson/bug-zhao.good
This seems to be a strange interaction between modules and adding
end counts.
> Add bug report from a user, simplified

- GOALS
- README.rst
- compiler/main/version_num.h
- doc/release/README.md
- doc/release/chplenv.rst
- doc/sphinx/source/conf.py
- man/confchpl.rst
- man/confchpldoc.rst
- test/compflags/bradc/printstuff/version.goodstart
> Pre-release prep. for Chapel 1.13.0 : increment version numbers

- test/release/examples/benchmarks/miniMD/helpers/forces.chpl
At the time miniMD was written reduce intents were not supported, so I used atomics to get better performance. This is no longer necessary now that + reduce is supported.
> Reduce intents for miniMD

- test/release/examples/benchmarks/isx/isx.precomp
- test/studies/isx/isx-bucket-spmd.precomp
- test/studies/isx/isx-no-return.precomp
- test/studies/isx/isx-per-task.precomp
Fix ISx precomp to check if CHPL_COMM==none instead of CHPL_COMM==gasnet, which would fail during ugni testing.
> Fix ISx precomp

- compiler/AST/type.cpp
- Added the conditions for completeness of the functions
> Adding missing entry for BOOL_SIZE_1

- test/expressions/vass/cast-to-non-type-2.bad
- test/expressions/vass/cast-to-non-type-2.chpl
- Currently the file was same as cast-to-non-type-1.chpl
- Added the needed .bad for the modifications
- Restoring a subset of changes in 1e07e1f5e7bcd4e9ffab6a0808f8e9fe3fd4a9dc
> Modifying cast-to-non-type-2.chpl test 

- modules/standard/FileSystem.chpl
- modules/standard/Path.chpl
Also gave mkdir's arguments type specifiers while I was there.
> Fix the broken links for the Path and FileSystem modules.

- LICENSE
- third-party/chpl-venv/README.md
also etc => highlight in the top-level license file
> Add PyYAML license information

- modules/standard/Random.chpl
* Fixes links
* Improves formatting
* Wordsmiths
* Rearranges TODOs into lowest place they could go
* makes TODOs in nice note boxes
* adds a little more content in a few places where important information seemed to be missing.
This is a docs-only change, but test/modules/standard/Random/ passes, just to be sure.
> More Random documentation clean up

- test/modules/standard/Random/diten/COMPOPTS
- test/modules/standard/Random/diten/testRandomSeed.chpl
- test/modules/standard/Random/diten/test_2D_fillRandom_complex.chpl
- test/modules/standard/Random/diten/test_2D_fillRandom_real.chpl
Since these tests just check for reproducible RNG output,
run them with each RNG.
> Make diten Random tests apply to both NPB and PCG

- STATUS.devel
The fix for this .future had to be reverted.  Put it back into the STATUS file.
> Added a .future back to STATUS.devel

- modules/internal/String.chpl
- modules/internal/fixInternalDocs.sh
* Makes the header more useful from a user perspective
* Indicate which functions may halt
* Add some code examples
* Adds documentation for some operator functions
* Wordsmithing
> Fill in some gaps in Strings documentation

- CONTRIBUTORS.md
I'm not sure how I missed him the first time, sorry Akash!
> Add Akash Thorat to the CONTRIBUTORS.md file

- doc/release/README.md
- doc/release/platforms/knl.rst
Needs more work, but is a decent check-in point
> Add initial draft of our KNL support

- CHANGES.md
* Incorporate changes from the internal repo which I overlooked
* Incorporate changes made since the last time I pushed this and anticipate a few others
* wordsmithing
[@ronawho hasn't taken his pass yet, so "final" is a bold statement...]
> Attempt to finalize CHANGES.md

- doc/sphinx/source/language/evolution.rst
Add a note that we're no longer promoting variables to the heap if they
are used in a task that might outlive the scope in which they are
declared.
This note draws heavily from the text and examples in
http://chapel.cray.com/releaseNotes/1.12/01-Language.pdf
> Add a note about lexical scoping

- doc/sphinx/source/language/evolution.rst
More could be done, but I think this is above the bar and I'm
timing out.
> Minor edits to evolution for wording, spelling, formatting

- doc/release/technotes/reduceIntents.rst
to reflect changes since 1.12.
Added an example of a simple user-defined reduction class.
> updated reduceIntents.rst and added an example

- compiler/util/clangUtil.cpp
Also removes old comment that does not apply to current version.
> Comment changes to better attribute code from ModuleBuilder.cpp

- doc/sphinx/source/conf.py
This changes html title of a given Sphinx page from 
'`<filename>` Chapel Documentation 1.13 - 1.13 documentation`
to
'`<filename>` Chapel Documentation 1.13'
> Improve Sphinx html_title

- QUICKSTART.rst
How did I miss this before...?!?
> Reformat QUICKSTART to fit 80 columns

- doc/developer/bestPractices/ContributorInfo.rst
Added some details about breaking up a feature into multiple pull requests.
> Add note about pull request sizes

- test/param/ferguson/field-value-not-in-range2.chpl
- test/param/ferguson/field-value-not-in-range2.good
Follow on to #3678.
Adds a test Brad requested.
> Add a test for getFieldRef with out of bounds number

- test/release/examples/benchmarks/miniMD/helpers/StencilDist.chpl
StencilDist improvements: 
- inline dsiAccess (like in BlockDist)
- simplify the local branch to avoid additional runtime checks and to hopefully improve performance.
> Improve StencilDist dsiAccess

- compiler/parser/README
to help users understand what to do if they experiment with the parser.
Trivial: no review.
> Add a README to compiler/parser

- test/classes/constructors/error-parenthesless-constructor.bad
The output looked like it would be consistent, so I figured a .bad would be
appropriate.
> Add a .bad file for this future

- test/extern/ferguson/externblock/struct-fn-ptr.chpl
- test/extern/ferguson/externblock/struct-fn-ptr.future
- test/extern/ferguson/externblock/struct-fn.chpl
I meant to include these in PR #3716.
> Add more externblock tests

- test/compflags/sungeun/configs/type_variables/configTypeClass.chpl
- test/execflags/vass/print-callstack-on-warning-2.chpl
- test/execflags/vass/print-callstack-on-warning-2.good
- test/expressions/lydia/noinit/recordHasClassField.chpl
- test/expressions/lydia/noinit/tupleWithClass.chpl
- test/expressions/lydia/noinit/usedWithClass.chpl
- test/multilocale/deitz/linked/test_linked2.chpl
- test/multilocale/deitz/linked/test_linked3.chpl
- test/optimizations/localon/simple-local-on.chpl
- test/optimizations/localon/sublocale.chpl
- test/param/ferguson/fielderator-user-class.chpl
- test/param/nelson/coercion.chpl
- test/types/string/StringImpl/memLeaks/coforall.comm-gasnet.good
- test/variables/kbrady/ref-vars.chpl
- test/visibility/except/canSeeSecondaryMethod.chpl
- test/visibility/only/typeIncludedAccessField.chpl
- test/visibility/only/typeIncludedAccessMethod.chpl
- test/visibility/rename/renameClass.chpl
Correctness verified on darwin/clang and linux64/gcc.
Leak reduction verified on darwin/clang.
No review.
> Wrap up the first pass of reducing the most trivial leaks

- util/test/computePerfStats
I changed some logic in computePerfStats in #3748.
Turned out it did not handle annotations in .dat files.
This PR fixes it and makes the logic easy to follow.
> Fixed an issue in computePerfStats

- test/release/examples/users-guide/taskpar/walkTreeUsingBegins.chpl
Trivial change.  Tested on darwin/clang
No review
> Fix dumb error to repair trivial leak

- test/exercises/boundedBuffer.chpl
- test/exercises/boundedBuffer2.chpl
- test/io/ferguson/json-list2.chpl
- test/io/ferguson/readThis/readclass5.chpl
- test/modules/figueroa/DuplicateConfigVars/RandomNumber_rewrite.chpl
- test/parallel/begin/deitz/test_coforall_sugar1.chpl
- test/parallel/begin/deitz/test_heap_begin.chpl
- test/studies/dijkstra/BC_dijkstra.chpl
- test/studies/dijkstra/driverEdgeBtw.chpl
- test/studies/dijkstra/nodes.chpl
- test/studies/shootout/chameneos-redux/hannah/chameneos-redux-cas.chpl
- test/studies/shootout/chameneos-redux/hannah/chameneos-redux-v1.chpl
- test/studies/shootout/chameneos-redux/hannah/chameneos-redux.chpl
- test/studies/shootout/fannkuch-redux/bharshbarg/fannkuch-redux-coforall.chpl
- test/users/biesack/test_recursive_iterator.chpl
- test/users/biesack/test_recursive_iterator2.chpl
Identified a few more tests that had relatively simple app-level leaks
Tested for correctness on darwin/clang and linux64/gcc
Verified for impact on daring/clang and validated on linux64/gcc
No review
> Eliminate several more trivial leaks

- .gitignore
... corresponding to the respective CLEANFILES.
> Added a couple of entries to .gitignore

- modules/dists/BlockCycDist.chpl
- modules/dists/BlockDist.chpl
- modules/dists/CyclicDist.chpl
- modules/internal/ChapelArray.chpl
- test/distributions/bharshbarg/subQuery.chpl
Continuing commit 028995803812a802b08f815ff8737e9ce9df9b36
Adds to distribution:
* targetLocales()
Adds to domain:
* targetLocales
* hasSingleLocalSubdomain()
* localSubdomain()
* localSubdomains()
Adds dsi functions supporting these to Block, Cyclic, BlockCyclic
Adds checks that these work in an existing test that checked them
for arrays.
Also makes requestCapacity be a documented domain operation.
Passed full quickstart+GASNet testing.
> Extend domain, distribution interface with localSubdomain, targetLocales, requestCapacity

- highlight/highlight/langDefs/chpl.lang
Andre Simon suggested adding these lines to appropriately highlight function
names.
> Make change suggested by author of the highlight program

- test/GRAPHFILES
- test/studies/README.md
- test/studies/elegance/README.md
- test/studies/elegance/arrayAdd.chpl
- test/studies/elegance/arrayAdd.good
- test/studies/elegance/arrayAdd.perfcompopts
- test/studies/elegance/arrayAdd.perfkeys
- test/studies/elegance/elegance.graph
- test/studies/elegance/promotedOp.chpl
- test/studies/elegance/promotedOp.good
- test/studies/elegance/promotedOp.perfcompopts
- test/studies/elegance/promotedOp.perfkeys
- test/studies/elegance/tuplesVSarrays.chpl
- test/studies/elegance/tuplesVSarrays.good
- test/studies/elegance/tuplesVSarrays.perfcompopts
- test/studies/elegance/tuplesVSarrays.perfkeys
New test suite comparing 'elegant' versions of code snippets to 'performant' versions. The 3 initial tests submitted were extracted out of the stencil PRK. This new directory is accompanied by a README.
I've also added a README to studies making its purpose more clear to outside contributors.
> New performance test suite: Elegance

- CHANGES.md
> Fixing some minor typos I found while working on 1.13 release notes

- spec/Records.tex
These are simple and do not address the current issues like "storage" vs. "variable", "constructor" vs. "initializer" etc.
> Minor fixes to spec

- runtime/src/tasks/fifo/tasks-fifo.c
- runtime/src/threads/pthreads/threads-pthreads.c
This PR should correct the build error introduced by commit 937f539
> Correct build problem

- test/release/examples/benchmarks/miniMD/helpers/StencilDist.chpl
Performance and completeness improvements to StencilDist:
- mark some utility functions as 'private'
- inline more dsiAccess functions
- sync with recent changes to BlockArr follower
- support for dsiEqualDMaps
> More updates to StencilDIst

- spec/Domain_Maps.tex
- spec/Domains.tex
- spec/Functions.tex
- spec/Iterators.tex
- spec/LONGTERM
- spec/Memory_Consistency.tex
- spec/Records.tex
- spec/TODO
- spec/Task_Parallelism_and_Synchronization.tex
- spec/chapel_testing.tex
- spec/proposals/constructors/2012/Constructors.tex
- spec/proposals/constructors/Examples.tex
- spec/proposals/glob-and-file-iterator/glob_proposal.tex
- spec/proposals/specialFunctions/Special_Functions.tex
> fix typos in spec/

- test/ANNOTATIONS.yaml
* Array initializations (#3795)
* PRK problem size (#3813)
* Parboil execution (#3742)
> Post perf-meeting annotations

- compiler/AST/AstToText.cpp
- compiler/AST/CForLoop.cpp
- compiler/AST/CollapseBlocks.cpp
- compiler/AST/ParamForLoop.cpp
- compiler/AST/WhileStmt.cpp
- compiler/AST/build.cpp
- compiler/AST/expr.cpp
- compiler/AST/iterator.cpp
- compiler/AST/symbol.cpp
- compiler/AST/type.cpp
- compiler/AST/view.cpp
- compiler/Features
- compiler/ifa/make_prims/make_prims.cpp
- compiler/include/AstVisitorTraverse.h
- compiler/include/TransformLogicalShortCircuit.h
- compiler/include/driver.h
- compiler/include/expr.h
- compiler/include/genret.h
- compiler/include/llvmGlobalToWide.h
- compiler/include/primitive.h
- compiler/include/vec.h
- compiler/ipe/IpeEnv.cpp
- compiler/ipe/IpeReaderFile.cpp
- compiler/main/checks.cpp
- compiler/main/config.cpp
- compiler/main/runpasses.cpp
- compiler/optimizations/copyPropagation.cpp
- compiler/optimizations/deadCodeElimination.cpp
- compiler/optimizations/inlineFunctions.cpp
Fix typos in compiler/{AST,include,ifa,ipe,main,optimizations,Features}
> Fix some typos under compiler/

- test/users/thom/passStrRngToNonstrRng.bad
- test/users/thom/passStrRngToNonstrRng.good
David's passing range future reminded me of some ancient range futures
that I went looking for, which led me to this one.  It is now half
better and its .good file incorrectly contained relative paths, so I
updated the .good and added a .bad.
> Minor update to range future

- compiler/parser/chapel.lex
- compiler/parser/chapel.ypp
- compiler/parser/flex-chapel.cpp
- compiler/parser/parser.cpp
- compiler/passes/checkNormalized.cpp
- compiler/passes/codegen.cpp
- compiler/passes/parallel.cpp
- compiler/passes/scopeResolve.cpp
- compiler/resolution/callDestructors.cpp
- compiler/resolution/cullOverReferences.cpp
- compiler/resolution/functionResolution.cpp
- compiler/resolution/implementForallIntents.cpp
- compiler/resolution/lowerIterators.cpp
- compiler/util/clangUtil.cpp
- compiler/util/llvmAggregateGlobalOps.cpp
- compiler/util/llvmGlobalToWide.cpp
- test/parsing/vass/newline-in-string-err-1.good
- test/parsing/vass/newline-in-string-err-2.good
- test/parsing/vass/newline-in-string-err-3.good
Including fixing up a few .good files depending on misspelled error messages.
> Fix typos in compiler/{parser,passes,resolution,util}

- compiler/include/bison-chapel.h
- compiler/include/flex-chapel.h
- compiler/parser/bison-chapel.cpp
- compiler/parser/flex-chapel.cpp
Rebuild parser after #3871.  bison 3.0.2, flex 2.5.39
> rebuild parser after #3871

- doc/chips/11.rst
- doc/chips/README.md
In today's initializer meeting we preferred placing such features in a separate chip instead of extending the existing chip. Therefore I am closing  #3823.
> Added CHIP 11 on discussed-and-rejected initializer features

- test/ANNOTATIONS.yaml
Annotated last night's switch to the release pidigits version
> Annotated switch of release version to ledrug version

- compiler/passes/createTaskFunctions.cpp
- compiler/resolution/implementForallIntents.cpp
> Fix two more typos

- compiler/resolution/callDestructors.cpp
- compiler/resolution/lowerIterators.cpp
Fix two more typos in compiler
> Fix two typos

- test/release/examples/benchmarks/shootout/README
- test/release/examples/benchmarks/shootout/nbody.chpl
Minor tweaks to comments and namings in preparation for submitting to CLBG.
> N-body cleanup

- test/release/examples/benchmarks/shootout/README
- test/release/examples/benchmarks/shootout/nbody.chpl
More TODOs, removed trailing whitespace
> Some minor edits to nbody based on perf team review today

- modules/packages/LinearAlgebraJama.chpl
My research suggests there is no such thing as a Shur decomposition,
and that what was meant was a Schur decomposition as per wikipedia and
the rest of the file.
> modules/packages/LinearAlgebraJama.chpl: s/Shur/Schur/

- test/GRAPHFILES
- test/users/npadmana/npb-mg/Makefile
- test/users/npadmana/npb-mg/mg.chpl
- test/users/npadmana/npb-mg/mg.execopts
- test/users/npadmana/npb-mg/mg.good
- test/users/npadmana/npb-mg/mg.graph
- test/users/npadmana/npb-mg/mg.perfcompopts
- test/users/npadmana/npb-mg/mg.perfexecopts
- test/users/npadmana/npb-mg/mg.perfkeys
Start  a pull request for CHIUW
> Start putting in the NAS MG benchmark in

- runtime/include/chpl-bitops.h
- runtime/include/chpl-file-utils.h
- runtime/include/mem/cstdlib/chpl-mem-impl.h
- runtime/include/qio/bswap.h
- runtime/include/qio/qio_error.h
- runtime/include/qio/qio_formatted.h
- runtime/include/qio/qio_regexp.h
- runtime/include/qio/qio_style.h
- runtime/include/qio/sys.h
- runtime/include/sys_basic.h
- runtime/src/chpl-cache.c
- runtime/src/chpl-file-utils.c
- runtime/src/chpl-visual-debug.c
- runtime/src/comm/gasnet/comm-gasnet.c
- runtime/src/comm/none/comm-none.c
- runtime/src/launch/slurm-srun/launch-slurm-srun.c
- runtime/src/mem/jemalloc/mem-jemalloc.c
- runtime/src/qio/auxFilesys/curl/qio_plugin_curl.c
- runtime/src/qio/qio.c
- runtime/src/qio/qio_formatted.c
- runtime/src/qio/qio_popen.c
- runtime/src/qio/sys.c
- runtime/src/threads/pthreads/threads-pthreads.c
> Runtime typos

- doc/chips/14.rst
This PR includes the CHIP draft for the stack trace project.
> CHIP draft for stack trace project

- doc/chips/1.rst
- doc/chips/10.rst
- doc/chips/12.rst
- doc/chips/2.rst
- doc/chips/3.rst
- doc/chips/5.rst
- doc/chips/6.rst
- doc/chips/7.rst
- doc/chips/8.rst
- doc/chips/9.rst
> Fix typos in doc/chips

- compiler/resolution/functionResolution.cpp
gatherCandidates had almost exactly the same code twice, except for a
check for user vs compiler-generated.
This PR moves the loop to another function that takes user vs
compiler-generated as a parameter.
This change is a trivial refactoring, but @vasslitvinov, @noakesmichael,
and @lydia-duncan offered feedabck. Thanks!
> Refactor gatherCandidates

- modules/dists/DSIUtil.chpl
I'm submitting this separately as I'm not 100% sure this is what the sentence is supposed to say.  I can't tell if the modified sentence is accurate, and the word "space" does not appear elsewhere in the file.
> modules/dists/DSIUtil.chpl: fix typo

- test/release/examples/benchmarks/shootout/README
- test/studies/shootout/binary-trees/binary-trees-extras.graph
- test/studies/shootout/binary-trees/binary-trees.graph
- test/studies/shootout/binary-trees/binarytrees-blc.chpl
- test/studies/shootout/binary-trees/binarytrees-blc.good
- test/studies/shootout/binary-trees/binarytrees-blc.perfexecopts
- test/studies/shootout/binary-trees/binarytrees-blc.perfkeys
Major changes:
* changed most standalone functions on trees into methods on tree including
a type/factory method to create trees
* moved Tree definition after main()
* tightened up some code and comments
Also updated release README with TODOs while here
TBD:
* can we take the free while adding approach?  Seems plausible based on
the documentation...
> Proposed draft of binary trees

- runtime/src/qio/qio_formatted.c
Passed test/io and test/regex.
> qio_formatted.c: s/elipses/ellipses/

- modules/internal/CString.chpl
- test/types/string/nspark/cast-cstring-to-cvoidptr.c
- test/types/string/nspark/cast-cstring-to-cvoidptr.chpl
- test/types/string/nspark/cast-cstring-to-cvoidptr.execopts
- test/types/string/nspark/cast-cstring-to-cvoidptr.h
(cherry picked from commit a3a156f7816e04f99995854a057ea184b22b3c5a)
> Added cast from c_string to c_void_ptr (from #3557)

- runtime/src/qio/qio_popen.c
- test/modules/standard/Spawn/spawn-popen2.chpl
- test/modules/standard/Spawn/spawn-popen2.good
(cherry picked from commit e5b0f26865d766f47edabfa0e98784eba31b50e3)
> Test case and fix for an issue with closing a spawn chanel before wait (from #3860)

- compiler/AST/build.cpp
(cherry picked from commit 7e5145164d4d571e3a2b248676daf26409c28fe0)
> Fixed race in generated code for reductions (from #3886)

- test/release/examples/benchmarks/shootout/chameneosredux.chpl
- test/release/examples/benchmarks/shootout/chameneosredux.good
Update our release version of chameneos to reflect the changes made by Brad
and the performance team prior to submission to the CLBG site.
> Promote chameneos version

- modules/dists/SparseBlockDist.chpl
- modules/packages/MatrixMarket.chpl
- modules/packages/Sort.chpl
> Fix misc typos

- test/users/ferguson/cast_to_imag.future
This future passes after PR #4029.
> Retire a future

- test/release/examples/benchmarks/hpcc/ra.chpl
After PR #4008, this test was timing out in nightly testing in a slower
configuration. Some basic troubleshooting revealed that the verify step takes
much much longer than the kernel in the tested configuration.
This PR adjusts the verify step to use an on statement, which is much faster,
because it is usually working with a local lock.
While there, I updated the kernel to use a Timer instead of subtracting two
getCurrentTime numbers (noting that getCurrentTime returns the time since
midnight, so we would get a negative elapsed time if the test ran during
midnight).
> Update RA verification to be faster, use Timer

- util/test/chpl_launchcmd.py
By default PBS will write stdout/stderr to a temporary "spool" file. After the
job is complete it'll copy the spool file to whatever output file was
specified. However, the spool file system can get filled up by other jobs,
which can cause our job to be unable to write to it.
I believe this might be the root cause of JIRA 17, which sometimes causes our
output file to be missing. Instead of giving qsub an output file (which leads
to it using a spool file) this updates chpl_launchcmd to redirect output
directly to the output_file instead.
This was suggested by a sys-admin and is apparently a pretty common practice on
qsub machines [[1]](http://www.nas.nasa.gov/hecc/support/kb/avoiding-job-failure-from-overfilling-pbsspool_183.html).
See [JIRA …
> Avoid using PBS spool files

- doc/chips/9.rst
Made the initial major revision. Passing it off to @psahabu for the next iteration.
More pleasantly viewed as [rendered RST](https://github.com/ben-albrecht/chapel/blob/e9836ea32df8bfd19da4cfc2ea1df888a9825142/doc/chips/9.rst)
> Package Manager CHIP 9 Revisions

- compiler/passes/insertWideReferences.cpp
Fix an issue where insertWideReferences attempted to analyze the wrong AST pattern.
The test memory/sungeun/refCount/arrays.chpl was failing intermittently
due to a compile-time assertion failure, and was challenging to reproduce.
Eventually @ronawho discovered that the intermittent nature was due to
the varying order of arguments to a function, something we believe to
be a side-effect of our homegrown map that hashes on pointers.
The problem was that IWR was looking for a pattern like this:
sym = foo(...);
Where foo returned a variable named 'cause'. Instead we were finding
the pattern:
bar(cause);
return cause;
Where bar looks like this:
fn bar(sym, ...) { ... }
To avoid this case, we test that the expr that caused 'sym' to be a
wide variable is used in a PRIM_RETURN.
> Fix compile-time failure in IWR

- test/arrays/vass/initialization-mapped-1.bad
This fix was necessary after #3891
> Fix in future - initialization-mapped-1.bad

- compiler/optimizations/optimizeOnClauses.cpp
- doc/sphinx/source/users-guide/base/basicValues.rst
- runtime/src/error.c
> Misc typos

- test/release/examples/benchmarks/shootout/fannkuchredux.chpl
After discussion in the perf meeting today, and in preparation for submitting it to the CLBG site, promoting my version of fannkuch to the release directory.
> Promoting my study version of fannkuch to release to prep for submission

- test/studies/shootout/regex-dna/bharshbarg/regexdna.chpl
These are minor stylistic cleanups that Ben and I discussed on email.
> Minor cleanups -- discussed with Ben

- test/functions/diten/complexAbsFn.future
We are now doing what the .future requested, so we get the expected result.
> Remove a .future requesting that we use C99 complex types and routines

- doc/sphinx/source/users-guide/base/basicValues.rst
- doc/sphinx/source/users-guide/taskpar/coforall.rst
Improve a few things in the users guide that Paul caught in his review.
> With friends like Paul who needs editors?

- doc/sphinx/source/users-guide/base/forloops.rst
- doc/sphinx/source/users-guide/index.rst
- test/release/examples/users-guide/base/forloops-illegal.good
- test/release/examples/users-guide/base/forloops.chpl
- test/release/examples/users-guide/base/forloops.compopts
- test/release/examples/users-guide/base/forloops.good
This is a proposed users guide section on for loops with a test to support it.
> Users guide: for-loops

- modules/packages/BLAS.chpl
- test/release/examples/benchmarks/shootout/spectralnorm.chpl
- test/studies/shootout/chameneos-redux/hannah/chameneos-redux.chpl
- test/studies/shootout/fasta/bradc/fasta-blc.chpl
- test/studies/shootout/meteor/kbrady/meteor-implicit-domain.chpl
- test/studies/shootout/meteor/kbrady/meteor.chpl
- test/studies/shootout/pidigits/bradc/pidigits-blc.chpl
- test/studies/shootout/pidigits/bradc/pidigits-ledrug-pretty.chpl
- test/studies/shootout/pidigits/bradc/pidigits-pretty1.chpl
- test/studies/shootout/pidigits/bradc/pidigits-pretty2.chpl
- test/studies/shootout/spectral-norm/README
- test/studies/shootout/spectral-norm/bradc/spectralnorm-blc.chpl
- test/studies/shootout/submitted/spectralnorm.chpl
- test/studies/shootout/thread-ring/lydia/thread-ring-coforall-begin.chpl
- test/studies/shootout/thread-ring/lydia/thread-ring-coforall.chpl
- test/studies/shootout/thread-ring/lydia/thread-ring-for-begin.chpl
It's kind of self-referential, tracing the lineage of these DNA-processing tests by following inherited mutations through the code...
> fix more typos, mostly shootout-related

- make/compiler/Makefile.gnu
If both the gcc version and the g++ version we are using support standard atomics, then choose a language standard that enables them.
If either one does not support standard atomics, then choose a language standard that disables them.
> Synchronize gcc and g++ support of standard atomics.

- test/ANNOTATIONS.yaml
off by 1 back in #3864 when documenting #3813 .
> Correct #3864 annotation by 1 day

- runtime/include/chpl-tasks-callbacks.h
- runtime/include/chpl-tasks.h
- runtime/include/tasks/fifo/tasks-fifo.h
- runtime/include/tasks/massivethreads/tasks-massivethreads.h
- runtime/include/tasks/qthreads/tasks-qthreads.h
This adds extern "C" declarations to some header files I missed before.
> Add more extern "C" declarations in individual headers.

- doc/chips/9.rst
@ben-albrecht:
- broke setup into a separate section
+ initialization of a project
- short header about the lock file
- fixed typos
> Mason: final refinements

- test/chplvis/overhead/overhead.chpl
- test/chplvis/overhead/overhead2.chpl
- test/chplvis/tree.chpl
> Replace resumeVdebug() with tagVdebug() calls.

- test/studies/shootout/reverse-complement/bharshbarg/revcomp-begin.chpl
Style improvements along with some simpler logic should make the program easier to follow.
> reverse-complement cleanup

- doc/chips/9.rst
@ben-albrecht: You don't have to review it, just thought you should know.
- streamlined multiple sections
- wordsmithing
> Mason: editorial wordsmithing

- doc/chips/9.rst
Thanks to @ben-albrecht, and shame on me for merging before looking.
> Mason: link typo

- compiler/AST/symbol.cpp
- compiler/AST/type.cpp
- compiler/AST/view.cpp
- compiler/include/type.h
- compiler/passes/checkResolved.cpp
- compiler/resolution/functionResolution.cpp
- compiler/resolution/lowerIterators.cpp
Reverts chapel-lang/chapel#4192
There seems to be a failure with isx.chpl. Reverting while I investigate.
> Revert "Remove special meaning for defaultInitializer for iterators"

- test/ANNOTATIONS.yaml
> Fix senseless typo in annotation

- spec/Domains.tex
It will suffice to alert them.
Also remove an extra "the".
> Domains.tex: stop altering the users

- doc/release/chplenv.rst
This PR inserts in the Chapel environment variables documentation CHPL_UNWIND and its options.
> Document CHPL_UNWIND

- modules/standard/Types.chpl
modules/standard/Types.chpl: fix typo
> modules/standard/Types.chpl: fix typo

- doc/chips/9.rst
@ben-albrecht:
* incorporated feedback from Thomas, Russel, Nicholas, et. al.
* focused on items responded to in the affirmative by BenA
> Mason feedback through 8/5

- doc/chips/9.rst
> remove unnecessary sourceforge links from CHIP9

- highlight/vim/README.rst
Simplify vim Chapel support installation for users of plugins.
> Added instructions for Vundle and vim-plug users

- compiler/AST/type.cpp
- compiler/passes/scopeResolve.cpp
- compiler/resolution/functionResolution.cpp
- compiler/resolution/implementForallIntents.cpp
- compiler/resolution/wrappers.cpp
- modules/internal/ChapelArray.chpl
- modules/internal/ChapelSyncvar.chpl
- test/types/single/vass/readThis.good
- test/types/single/vass/writeThis.good
- test/users/vass/isX/isX.byBlankArgs-compWarns.good
- test/users/vass/isX/isX.module-writeln.good
- test/users/vass/type-tests.good
Apply the same process for sync as record to single.
1) Compiled with/without CHPL_DEVELOPER on clang/darwin and gcc/linux64
2) Tested with --verify, --baseline --verify, --futures
3) Reviewed by BenH
> Single as rec

- compiler/AST/symbol.cpp
- compiler/passes/codegen.cpp
* Minor comment fix + refactoring codegen_header function and the related piece of code into separate functions for now.
* Passed standard, gasnet and std + --incremental testing
> Refactoring codegen_header

- test/distributions/bharshbarg/stencil/localReads.chpl
- test/distributions/bharshbarg/stencil/localReads.good
Add test to confirm that reads from a stencil-distributed array are local
> Test for local reads from StencilDist

- test/classes/engin/super_nooverride.chpl
- test/classes/engin/super_override.chpl
- test/classes/ferguson/newc.chpl
- test/classes/ferguson/newc2.chpl
- test/classes/lydia/overrides/basicOverride.chpl
- test/classes/lydia/overrides/deeperInheritance.chpl
- test/classes/lydia/overrides/deeperInheritance2.chpl
- test/classes/lydia/overrides/recursiveCall.chpl
- test/classes/lydia/overrides/remoteVersion.chpl
- test/classes/lydia/overrides/secondary.chpl
- test/classes/lydia/overrides/secondary2.chpl
- test/classes/lydia/overrides/withArgs.chpl
- test/distributions/robust/arithmetic/modules/test_module_Search.chpl
- test/extern/bradc/classes/extern_big_class.chpl
- test/extern/bradc/classes/extern_class.chpl
- test/extern/sungeun/classes/extern_class_extern_proc.chpl
- test/extern/sungeun/classes/extern_class_nl.chpl
- test/extern/sungeun/classes/extern_class_nl_extern_proc.chpl
- test/extern/sungeun/classes/extern_class_nl_proc.chpl
- test/extern/sungeun/classes/extern_class_proc.chpl
- test/parallel/single/waynew/class1.chpl
- test/types/type_variables/nelson/dependentTypeArgument.chpl
- test/types/typedefs/tzakian/classConstructorsFromTypes.chpl
- test/users/shetag/shareIterator-blc-register.chpl
Tested for correctness and to eliminate leak.
Trivial.  No review
> Fix a handful of trivial leaks (user fails to delete class instances)

- doc/chips/15.rst
- doc/chips/README.md
* Includes a detailed description about all the work done, approaches
taken and decisions made while working on the project
* Also, contains ideas (and future plans) about the issues that
still need to be worked on.
> Adding chip for incremental compilation project

- util/buildRelease/testRelease
- util/cron/lookForTabs.cron
- util/cron/nightly
- util/cron/nightly_email.pl
- util/cron/nightlysubs.pm
- util/cron/start_opt_test
- util/pastPerformance/getoldperf
- util/test/send_email.py
- util/tokencount/tokctnightly
CHAPDEV-130 Suppress all email notifications if env var CHPL_TEST_NOMAIL is defined.
(Scope: chapel.git only)
> Suppress all email notifications if CHPL_TEST_NOMAIL

- compiler/AST/expr.cpp
- compiler/include/exprAnalysis.h
- compiler/passes/denormalize.cpp
- compiler/util/llvmDebug.cpp
> Fix a few more typos

- modules/standard/Buffers.chpl
> Add method to `bytes` type to get raw pointer to memory

- test/ANNOTATIONS.yaml
Annotate the changes caused by PRs:
* #4360 
* #4309
* #4375 
* #4318 
* #4333
* #4350
* #4329
> Performance Triage Annotations: code size, memory leaks, PRKs, and more

- compiler/AST/expr.cpp
Authored by @e-kayrakli, sent as patch to @benharsh
> Better handling of casting for bools in LLVM

- test/release/examples/benchmarks/shootout/fastaredux.perfexecopts
- test/studies/shootout/fasta/fasta.graph
@bradcray:
Here it is, I've tested it on my machine and it appears to work. Thanks for the feedback, hopefully this can get submitted this next week.
> fixing graphs for fasta and fasta-release

- modules/standard/Buffers.chpl
- test/modules/standard/Buffers/copy_strings.chpl
- test/modules/standard/Buffers/copy_strings.execopts
- test/modules/standard/Buffers/copy_strings.good
> Add buffer.copy{in,out} support for strings

- runtime/include/atomics/cstdlib/chpl-atomics.h
> chpl-atomics.h: fix typo

- test/parsing/ferguson/trailing-comma.chpl
@cassella pointed out an issue with this new test - thanks!
> Fix minor issue in a test

- modules/internal/ChapelReduce.chpl
Native qthread sync vars (#4506) resulted in some performance regressions for
tests that use reductions (lulesh, NAS CG, Reductions Time, etc.)
The core problem is that native qthread sync vars are great for long-lived and
heavily-contended locks, but not for short-lived and minimally-contended ones.
That's actually true for sync vars in general, but it's especially true for
native qthread sync vars currently. This is because qthread sync vars use a
global hashtable where a new entry is added when a sync variable is emptied,
and removed when a sync var is filled and has no pending operations left. This
means that sync vars used as locks are repeatedly being added and removed from
the hashtable, which is expensive. For reductions each task did something like:
``` chapel
var lock: sync …
```
> Use an atomic spin lock instead of a sync var for reductions

- third-party/qthread/qthread-src/Makefile.am
- third-party/qthread/qthread-src/Makefile.in
- third-party/qthread/qthread-src/README.md
- third-party/qthread/qthread-src/src/threadqueues/distrib_threadqueues.c
Only difference is their README was added and they're using a configure time
determined cacheline size instead of just using 64 bytes
> Upgrade to the official qthreads 1.11 RC that's been released on github

- modules/standard/GMP.chpl
1) A trivial revision to one extern function signature
2) Add a comment on the nature of mpz_t
> Improve an extern function signature and add some comments

- doc/release/launcher.rst
- doc/release/multilocale.rst
- doc/release/platforms/infiniband.rst
In response to some user issues with running Chapel
on an InfiniBand cluster, I've put some effort into
improving our documentation in this area. This commit:
* improves multilocale.rst to keep the key information
mostly on the first page
* adds a new infiniband.rst file that shows
how to get Chapel running on an InfiniBand cluster
* refactors and improves documentation between launcher.rst
and multilocale.rst.
Reviewed and tested by @ben-albrecht - thanks!
> Re-work multilocale documentation

- test/release/examples/primers/genericClasses.chpl
Just made a small change.
Verified the html output looked good
> Update genericClasses primer for html output

- test/release/examples/primers/arrayVectorOps.chpl
Add back ticks for Chapel code and values in comments.
> Clean up the arrayVectorOps primer for html output

- test/release/examples/primers/varargs.chpl
Entirely a bunch of back tic additions
Verified that the html looked good
> Clean up the varargs primer for html

- test/release/examples/primers/variables.chpl
* back tics
* sections (with reference labels)
* minor word-smithing
> Clean up the variables primer for html

- test/release/examples/benchmarks/shootout/README
- test/release/examples/benchmarks/shootout/knucleotide.chpl
This completes my pass over all the shootouts other than pidigits.  Mostly, I just did minor tweaks and updates to the README here, and converted one 1<<k to 2**k in knuceotide.chpl
> Minor shootout cleanups

- test/release/examples/primers/classes.chpl
The classes primer didn't have enough backticks.  Add some more.
> primers/classes.chpl: add more backticks

- doc/chips/15.rst
* Replacing a link pointing to a code block with the actual code
block in the rst
* Improved the rendering of filenames, function names and variable
names for improved clarity.
* Added quotes around pass-names for better clarity
> Minor Improvements to CHIP-15

- test/release/examples/primers/taskParallel.chpl
Includes many new back tics, a little bit of comment rearrangement,
sections, and a new comment on the config const.
Verified that the html output looks good
> Fix taskParallel primer for html output

- doc/release/multilocale.rst
- doc/release/platforms/cray.rst
- doc/release/platforms/infiniband.rst
These changes address Greg's feedback on the multilocale documentation updates.
Reviewed by @gbtitus - thanks!
> Follow-on to PR # 4581

- test/ANNOTATIONS.yaml
Add annotations for the two major improvements to binary trees
this week.
> Annotate this week's binary trees improvements

- test/release/examples/primers/iterators.chpl
- test/release/examples/primers/parIters.chpl
@ben-albrecht:
* substantial overhaul to formatting
* wordsmithing for clarity
> primers: iterators, parIters

- test/release/examples/primers/atomics.chpl
Lots of back tics, some code rearrangement and some links to the spec.
Verified that the html output looks good.
> Fixes to the html output of the Atomics primer

- modules/Makefile
- modules/standard/BigInteger.chpl
- modules/standard/GMP.chpl
A first pass on documentation for new bigint record.
> Add preliminary documentation for bigint

- test/release/examples/primers/reductions.chpl
primers/reductions.chpl: fix typo
> primers/reductions.chpl: fix typo

- modules/standard/IO.chpl
modules/standard/IO.chpl: fix typos
> modules/standard/IO.chpl: fix typos

- modules/standard/Math.chpl
Napierian seems more supported by the literature.
> Math.chpl: s/Napierien/Napierian/

- modules/internal/ChapelArray.chpl
- test/release/examples/primers/domains.chpl
- test/release/examples/primers/locales.chpl
* Markup.
* Wordsmithing.
* Adjusted vertical space to taste.
* While there, added formal arg names to chpldoc for reshape().
* While there, added a reference to the Chapel spec page
to the domains primer.
> Updated locales primer for online docs + more

- test/release/examples/primers/fileIO.chpl
@ben-albrecht:
* minor reorganization
* editing for clarity
* substantial style edits
> primer: file I/O

- test/release/examples/primers/sparse.chpl
This primer is in need of updates and further attention, but I did some minimal work to clean it up for HTML rendering.
It should:
* refer to CSR
* described SparseBlock distribution
* show bulkAdd
> Clean up sparse primer for HTML rendering

- test/release/examples/primers/randomNumbers.chpl
* deleted note about odd seed as it is no longer relevant
to the default RandomStream
* added sections
* in some places, added more commentary to make the HTML output
flow better or to be clearer
* beautified HTML output
> Beautify and make minor updates to randomNumbers primer

- modules/internal/ChapelArray.chpl
This PR documents bulkAdd and += for sparse domains. This is based upon documentation by @e-kayrakli. 
> Document bulkAdd

- doc/release/multilocale.rst
* a few minor updates
* save example program to ./hello
* reorder CHPL_COMM_SUBSTRATE conduits based upon which we have most experience with, and then the others alphabetically.
Reviewed by @bradcray.
> Addressing Brad's feedback on multilocale.rst

- test/release/examples/README
- test/release/examples/benchmarks/lcals/README
* test/release/examples/README: list subdirs in alphabetical order
* test/release/examples/benchmarks/lcals/README: files added and removed from subdirectory since the last README update
> Detail corrections to examples README files.

- modules/Makefile
- modules/packages/MPI.chpl
* Add MPI package to online documentation
* Remove unwanted comments
* Hide internal functions/variables
* word-smithing
> MPI Documentation

- test/release/examples/primers/FFTWlib.chpl
@ben-albrecht:
* rst-ifying
* reformatting
* slight wordsmithing
> primer: fftw

- util/cron/common-whitebox.bash
Fix swap to craype-target-local_host, and libsci unload
> Try fixing whitebox testing

- modules/dists/BlockCycDist.chpl
The previous version of the comment referred to Block vs BlockCyclic.
> Update the comment at the top of BlockCycDist

- test/release/examples/benchmarks/lcals/LCALSLoops.chpl
Replace repeated function calls with simple for loops in LCALS array
initializations.
> Clean up LCALS initialization

- test/modules/packages/mpi/multilocale/hello-chapel-nl-1/hello.chpl
- test/modules/packages/mpi/multilocale/hello-chapel/hello.chpl
- test/modules/packages/mpi/spmd/hello-chapel/hello.chpl
There is an unnecessary coforall loop in the SPMD hello world test. Also, used the fully qualified access for`C_MPI` symbols.
> MPI test update

- test/release/examples/benchmarks/lcals/RunCRawLoops.chpl
* Changed some nested loops into single loops over a 2D domain
* Marked a few variables as const
> Small cleanup in LCALS HYDRO_2D kernel

- runtime/src/chpl-privatization.c
Fixes a typo. Comment change only.
> Fix typo in a comment

- test/studies/shootout/fasta/bradc/fasta-blc.chpl
It's not only more compact, but on my workstation it's also faster (which is not fully surprising given the small search space.
> Switch fasta to use a linear search

- doc/chips/13.rst
- doc/chips/8.rst
- third-party/chpl-venv/README.md
Fix typos in chips and chpl-venv/README.md
> Fix typos in chips and chpl-venv/README.md

- test/memory/sungeun/refCount/domainMaps.cygwin32.good
- test/memory/sungeun/refCount/domainMaps.linux32.good
Updates .good files to reflect a reduction in leaks after PR #4762.
> Fix domain maps .good for linux32, cygwin32

- CHANGES.md
Fix one more double paren in CHANGES.md
> Fix one more double paren in CHANGES.md

- doc/chips/16.rst
- doc/chips/README.md
A draft based upon my earlier work and elaborated with current thinking.
> Create CHIP about optimizing copies

- doc/chips/16.rst
- doc/chips/6.rst
- modules/internal/ChapelArray.chpl
> Fix a few typos

- test/exercises/c-ray/c-ray.noreal.good
- test/exercises/c-ray/c-ray.toosmall.good
Sigh... Only tested c-ray again, missing the other line# updates... Can
you tell I only slept 3-4 hours last night?
My kingdom for a way to squash compilerError() source line numbers!
> Adjusting line numbers once more

- doc/developer/adding-a-comm-layer.txt
- doc/developer/adding-a-runtime-component.txt
- doc/developer/adding-a-tasking-model.txt
This has already been reviewed and approved by @gbtitus, but please other should chime in if interested.
> Add a little documentation on adding a runtime component and a comm layer

- compiler/AST/symbol.cpp
I meant to include this fix in PR #4827.
> Adjust a comment

- test/runtime/sungeun/chpl-env-gen.precomp
This test was broken by #4826 
@lydia-duncan
> Update path to chpl-env-gen.h as defined by new build directory structure

- test/exercises/boundedBuffer/boundedBuffer.chpl
- test/exercises/boundedBuffer/boundedBuffer.execopts
- test/exercises/boundedBuffer/boundedBuffer.good
This is the single-producer/single-consumer bounded buffer code that will serve as a starting point for the task parallel SC16 hands-on exercise.  Still need to write and test the sample solution.
> SC16 boundedbuffer exercise

- test/exercises/boundedBuffer/boundedBuffer.chpl
exercises/boundedBuffer: fix typos
> exercises/boundedBuffer: fix typos

- test/exercises/c-ray/c-ray.chpl
- test/exercises/c-ray/forStudents/c-ray.chpl
> c-ray: fix typos

- test/exercises/boundedBuffer/Makefile
- test/exercises/boundedBuffer/README
- test/exercises/boundedBuffer/boundedBuffer.chpl
- test/exercises/boundedBuffer/solutions/boundedBuffer-atomic.chpl
- test/exercises/boundedBuffer/solutions/boundedBuffer-atomic.execopts
- test/exercises/boundedBuffer/solutions/boundedBuffer-atomic.good
- test/exercises/boundedBuffer/solutions/boundedBuffer-sync.chpl
- test/exercises/boundedBuffer/solutions/boundedBuffer-sync.execopts
- test/exercises/boundedBuffer/solutions/boundedBuffer-sync.good
Here, I've added a README and Makefile to the bounded buffer example, listed steps to make it work as comments, and added a solutions directory with my solutions using atomics and syncs.
> Bounded buffer instructions and solutions

- compiler/optimizations/inlineFunctions.cpp
The inner loop of inlineFunctions currently has a set of complex tests that handle various cases
for mapping actuals to formals.  One if the 4 primary paths was overly convoluted and had
recently been tagged as a nearer term candidate for removal as the QualifiedType work proceeded.
I studied the situations in which the curious code was triggering and concluded that it was in
fact already reasonable to remove the offending conditional.  BenH concurred.
A nice bonus was that this transformation relied on several helper functions to collect data to
be used in this transformation and all of that code can be removed as well.
Then did a little white-space cleanup.
Compiled with and without CHPL_DEVELOPER on clang/darwin and gcc/linux64
Ran a significant fraction of release/ for darwin.
Ran …
> Remove unnecessary code from inlineFunctions

- compiler/optimizations/inlineFunctions.cpp
- compiler/resolution/functionResolution.cpp
> Fix a pair of typos

- test/parallel/taskCompare/elliot/empty-omp-parallel-for.skipif
- test/parallel/taskCompare/elliot/ompTaskSpawn.h
Fix skipif and guard OpenMP constructs with _OPENMP
> Fix OpenMP task spawn test

- test/exercises/Mandelbrot/mandelbrot.chpl
- test/exercises/Mandelbrot/solutions/mandelbrot4-taskpar.chpl
- test/exercises/Mandelbrot/solutions/mandelbrot5-taskpar-dist.chpl
- test/exercises/Mandelbrot/unit/mandelbrot-zero-bug.chpl
- test/exercises/MonteCarloPi/serial.chpl
- test/exercises/histogram1.chpl
- test/exercises/histogram2.chpl
- test/exercises/histogram3.chpl
- test/exercises/life.chpl
> test/exercises: fix typos

- compiler/passes/initializerRules.cpp
- doc/chips/10.rst
- test/classes/initializers/phase1/hasLoopBadDoWhile.chpl
- test/classes/initializers/phase1/hasLoopBadWhile.chpl
> A few small fixes

- third-party/qthread/qthread-src/src/threadqueues/nemesis_threadqueues.c
Improve task creation times by using a hybrid spin/condwait scheme for qthreads
nemesis scheduler. While digging into LCALS performance we discovered a large
portion of our overhead compared to OpenMP is in task creation. This improves
the performance of a task startup microbenchmark from 21s to 7s compared to
3.2s for an OpenMP variant. While we're still off from OpenMP, this is a vast
improvement, and I have a good lead on the remaining sources of overhead. With
additional work, we should be able to get close if not on par with OpenMP task
creation times.
Details of this commit:
qthreads --enable-condwait-queue controls whether idle workers spinwait or do a
condwait while looking for new tasks. Pure spinwaiting kills single threaded
performance because idle threads pound the cpu …
> Dramatically improve task creation speed

- util/cron/test-perf.chapcs.playground.bash
Test Michael's no-heap-alloc-bundles branch in perf playground
> Test perf of stack allocating arg bundles in playground

- test/studies/dedup/dedup-extern.chpl
- test/studies/dedup/dedup-externblock.chpl
Resolves a nightly testing failure with PGI compiler.
> Tidy up type of SHA1 call in dedup test

- test/release/examples/benchmarks/hpcc/fft.chpl
- test/release/examples/benchmarks/hpcc/hpl.chpl
- test/release/examples/benchmarks/hpcc/ra.chpl
- test/release/examples/benchmarks/hpcc/stream-ep.chpl
- test/release/examples/benchmarks/hpcc/variants/ra-cleanloop.chpl
- test/release/examples/benchmarks/lcals/LCALSDataTypes.chpl
- test/release/examples/benchmarks/lulesh/README
- test/release/examples/benchmarks/lulesh/lulesh.chpl
- test/release/examples/benchmarks/lulesh/luleshInit.chpl
- test/release/examples/benchmarks/miniMD/README
- test/release/examples/benchmarks/miniMD/explicit/helpers/initMD.chpl
- test/release/examples/benchmarks/miniMD/helpers/initMD.chpl
- test/release/examples/programs/norm.chpl
- test/studies/lulesh/bradc/lulesh-dense.chpl
- test/studies/lulesh/bradc/xyztuple/lulesh-dense-3tuple.chpl
- test/studies/lulesh/bradc/xyztuple/luleshInit3.chpl
- test/studies/lulesh/intelVectBug/lulesh.chpl
Fix typos in test/release/examples
> Fix typos in test/release/examples

- test/types/records/ferguson/choose-record/choose-record10.bad
- test/types/records/ferguson/choose-record/choose-record10.chpl
- test/variables/sungeun/refvar-assign-with-cast.bad
- test/variables/vass/ref-to-const-domain.bad
While there, I noticed that choose-record10 had an actual error, which I've corrected.
> Fix .bad files after PR #4899

- compiler/optimizations/inlineFunctions.cpp
The entry point named inlineFunctions() actually invokes 4 sub-passes; three of these are defined
inline.  Separate the three inlined sub-passes into their own functions.
No changes in behavior.
Tested on release/examples on clang/darwin and a full paratest on linux64 single-locale.
> InlineFunctions() has four sub-passes.  Make this clear

- runtime/src/chplsys.c
> chplsys.c: fix typos

- test/ANNOTATIONS.yaml
Added missing annotations and made some effort to improve
some of the existing annotations.
> Annotate recent perf-oriented changes to fasta and c-ray

- runtime/include/chpl-comm.h
- runtime/src/chplsys.c
- runtime/src/tasks/qthreads/tasks-qthreads.c
* Re-indent chpl_computeHeapPageSize
* Add a comment clarifying chpl_comm_desired_shared_heap
* Add disabled-by-default debug code to check_page_size
* Fix qthreads chpl_task_getId to work on non-qthread
Reviewed by @gbtitus - thanks!
> Cleanups after PR #4931

- test/ANNOTATIONS.yaml
Annotate performance effects of:
- #4074
- #4904 
- #4925 
- #4547
Correct the date for: #4902
> Add annotations for perf-triage

- compiler/optimizations/inlineFunctions.cpp
> inlineFunctions.cpp: fix typo

- .gitignore
- doc/developer/chips/Makefile
chips/Makefile: update for docs reorg
.gitignore: update chips for docs reorg
> update chips/Makefile and .gitignore for docs reorg

- runtime/src/chplsys.c
This PR resolves a problem with CHPL_COMM=ugni where allocating and using a large amount of memory could result in some PUTs to fail. This issue was introduced in PR #4931.
In order to be sure we correctly know the page size of the Chapel heap, we experimentally verify the page size with mprotect in computeHeapPageSizeByGuessing. Before this PR, those experiments used memory in the middle of the heap. That has the unfortunate side effect of splitting the heap in the middle as far as the linux kernel is concerned - which complicates memory registration.
This PR changes the logic in computeHeapPageSizeByGuessing to use memory at the end of the heap instead. This memory is less likely to be used in practice. (However if it is used, there is still something to fix within CHPL_COMM=ugni). …
> Move test page to the end of the heap

- compiler/AST/build.cpp
- modules/internal/ChapelBase.chpl
Improve task creation speed for "bounded" local coforalls by limiting how many
times we touch the EndCount and runningTasks atomics.
Previously coforalls were turned into something roughly like:
```chapel
coforall i in 1..10 { body(); }
```
```chapel
for i in 1..10 {
_upEndCount(_coforallCount);
chpl_taskListAddCoStmt(body());
}
_waitEndCount(_coforallCount);
```
where `_upEndCount` bumped the atomics here.runningTasks, EndCount.i, and the
non atomic EndCount.taskCnt. Modifying the atomics for each iteration is
actually quite expensive so this changes the code to do a single upEndCount for
a coforall when we can determine the number of tasks the coforall will create
before executing it. Currently that check is if the coforall is over a
boundedRange, a domain, or an array.
We now create …
> Improve task creation speed for "bounded" coforalls

- util/buildRelease/gen_release
Trivial gen_release error from #4705
> Fix path for chplspell-requirements file

- test/ANNOTATIONS.yaml
I focused on those that affected fasta and LCALS for the sake of
tweeting and things I improved.
> Add some annotations for recent events

- test/errhandling/catch-match.bad
- test/errhandling/try-bang.bad
- test/errhandling/try-catch.bad
- test/errhandling/try-propagation.bad
[trivial, self-reviewed]
- caused by #5046
> 'fix' error handling futures

- test/ANNOTATIONS.yaml
[reviewed by @lydia-duncan]
- perf graph annotation for multi-ddata
> multiddata annotation

- test/studies/shootout/fasta/bradc/fasta-blc-numa.chpl
A lot of the complexity in my former tasking logic for this version
was designed to avoid oversubscription when we were busy-waiting
because it could lead to deadlock.  Now that we're using the more
principled waitFor(), oversubscribing slightly is not an issue so
let's re-simplify the logic.
> fasta: simplify numa study version

- test/release/examples/users-guide/datapar/promotion-error.good
- test/release/examples/users-guide/datapar/promotion.compopts
Whoops, I made the classic error and forgot to add these files
which weren't necessary for this test to work, but which test
an error case.
> Add missing files for new users guide promotion test

- util/cron/test-perf.chapcs.playground.bash
Whoops, forgot it was testing numa, instead of flat
> Stop using numa for the perf playground

- test/studies/shootout/mandelbrot/bradc/mandelbrot-blc.chpl
This version of mandelbrot follows the model of the Swift
implementation, using a vector of real values to do the buffer worth
of computation rather than one pixel at a time.
I found I had to switch from using complexes back to reals because
we can't promote field accessors like .im across arrays or tuples
yet.  :(    I also had to overload a few operators, one which adds
a scalar to a tuple, the second a comparison between a scalar and a
tuple.  Arguably, we could support these in an optional library if not
automatically.
> Swift-like version of mandelbrot

- runtime/include/tasks/massivethreads/tasks-massivethreads.h
- runtime/src/tasks/massivethreads/tasks-massivethreads.c
with this patch, massivethreads tasking layer passes  nightly -examples with no errors on single locale.
I will do fuller tests later.
> massivethreads works with stack-allocated task bundle

- compiler/util/files.cpp
It seems that I updated this comment after committing my fix
to --cpp-lines rather than before as intended.
> Update comment related to beautifying

- test/errhandling/try-bang.bad
- test/modules/sungeun/init/printModuleInitOrder.lm-numa.good
[self-reviewed]
- try-bang.chpl (future .bad)
- printModuleInitOrder.lm-numa (.good)
> Fix tests broken by Error -> SysError

- modules/internal/DefaultRectangular.chpl
As it was coded the multi-ddata serial iterator would not inline.  Both
the execution-time test against mdNumChunks and the doubly-nested loop
around the yield-stmt in the mdNumChunks!=1 case broke the limitations
required for inlining to occur.  Here, recode so that we can inline this
iterator.  This restores the pre-multi-ddata locModel=numa performance
for studies/prk/stencil/stencil and some others.
> Recode the multi-ddata serial iterator so that it will inline.

- .scspell/dictionary
- .scspell/dictionary.fileids.json
Update chplspell dictionary files
> chplspell dictionary updates 20170121

- compiler/passes/buildDefaultFunctions.cpp
A second/final trivial cleanup pass for the old build_record_init_function().
Passed paratest on linux64 single-locale and gasnet
> Continue to refactor the old build_record_init_function()

- doc/developer/chips/10.rst
Based upon discussion, this PR updates CHIP 10 to describe deinitialization and `deinit` methods.
Resolves #5201.
> Update CHIP 10 for deinit

- compiler/passes/initializerRules.cpp
Brad was playing with a class that included a field of array type.  He tried to provide
a user defined init() method where his code ran in phase 2.  The code compiled but
failed with a "dereference nil" bug on master.
The compiler had inserted code to initialize the "omitted" field for phase 1 but
accidentally generated an assign operation on the field rather than implementing
low-level initialization (there isn't a fully principled way for it to do real initialization
yet).
This trivial PR converts the use of the assignment call with an implementation
for low-level init.
Ran on test/classes/initializers on darwin.  Ran full paratest on linux64.
> Update initializer phase1 so that omitted fields implement init rather than assign

- doc/developer/chips/17.rst
- doc/developer/chips/README.md
This PR creates a CHIP about how we might support GPUs in Chapel. It's a work in progress and being placed in the repository so that issues can refer to it and as a starting point for discussion and subsequent updates. It is by no means in its final form.
This CHIP was authored by Daniel Lowell, Mike Chu, Ashwin Aji, and myself.
> CHIP on GPUs in Chapel

- doc/developer/chips/17.rst
Minor edits on examples and references.
> Changes to CHIP 17

- test/functions/jturner/first-class-generic-function.chpl
- test/studies/hpcc/common/bradc/unit/parRandom2-domblock.chpl
- test/studies/hpcc/common/bradc/unit/parRandom2-domblock64.chpl
Tests just needed the corresponding update.
Thanks to @ronawho for pointing out the issue.
> Update a few futures for PR #5303

- util/cron/test-perf.chapcs.playground.bash
Test "arrayViewAllThree" instead of "arrayViewSliceRankChange"
> Change what branch is being tested for array-views perf playground

- compiler/passes/insertWideReferences.cpp
- test/arrays/diten/array_of_c_string.future
Passed full --no-local testing.
> Fix bug where arrays of c_strings would fail to compile in --no-local

- compiler/passes/normalize.cpp
This is a first non-functional update to a portion the normalization of DefExpr in preparation
for updates to improve the handling of initialization for non-generic records.
1) fix_def_expr() has been renamed normalizeVariableDefinition()
2) Trivial updates to clarify logic flow
Passed with local paratest on linux64
> Begin to revise normalize to support non-generic record initializers

- compiler/passes/scopeResolve.cpp
- test/parallel/taskPar/vass/errorFieldMethodInWithClause.good
- test/parallel/taskPar/vass/field-in-task-ref-clause.good
This is a minor aesthetic change.
> Improved the error message for non-vars in with-clauses

- compiler/resolution/functionResolution.cpp
I reuse this in my handling of the primitive I create, so abstract it into a
helper for code maintainability in the generic initializer's work.
Passed full std/ testing
> Make helper function for set member encountering a type mismatch

- test/ANNOTATIONS.yaml
- Fix parse slowdown (#5257)
- Loop over Defs and Uses with SymbolSymExprs (#5285)
- Add Futures package module - lambda functions leaking (#5135)
> Performance Annotations

- compiler/passes/normalize.cpp
Separate handling of type-alias and array-alias from the other uses of variable definitions
No change in functionality.
Passed single-locale paratest
> Continue to straighten out variable normalization

- compiler/passes/normalize.cpp
"Initializing" config variables is fundamentally more complex than record/class fields and local
variables especially for V1 and most particularly for config const and multi-locale.  Separate the
code for configs so that these paths can evolve separately.  This is an initial cut/paste step prior
to additional refactoring.
Paratested on single-locale and (primarily as a sanity check) for gasnet.
> Step 1 to separate handling of config vars from non-config-vars

- compiler/passes/normalize.cpp
Trivial cleanup following the first stage of separating config variables from non-config vars.
Compiled with/without CHPL_DEVELOPER on clang/darwin, gcc/linux64
Passed paratest on single-locale and gasnet
> A clean up pass on normalization of config variables

- compiler/passes/normalize.cpp
This is a first step to update the normalization that is applied to "var x : type;" for non-config
variables in order to improve support for "var x: MyRecord;"
Executed paratest for single-locale and gasnet
> Begin to refactor the code that will support e.g. "var x : MyRecord;"

- compiler/passes/normalize.cpp
The normalization of variable declarations includes some fragile code that diverts the control
flow when the FLAG_NO_COPY is set.  In some cases this code generates ASSERT errors.
This behavior is locked in by slightly curious  futures in test/trivial/sungeun/pragmas/
Recent, intermediate, changes to normalization altered the handling of FLAG_NO_COPY in a
manner that caused 4 futures to begin to pass; two for a principled reason and two more
for reasons that were not entirely planned.
Continued progress on normalization will have further impact on FLAG_NO_COPY but in the
meantime I am making trivial changes to fully restore the pre-existing behavior.  This issue
will receive additional attention in the very near future. …
> Revert some odd handling of FLAG_NO_COPY

- compiler/passes/normalize.cpp
Continue with modest updates to the code to normalize non-config variables declarations
where the type is inferred from the RHS.  No change in behavior.
Passed single-locale paratest.
> Continue refactoring normalization

- test/GRAPHFILES
- test/performance/bharshbarg/views-forall-index.graph
- test/performance/bharshbarg/views-forall-iter.graph
- test/performance/bharshbarg/views-forall.chpl
- test/performance/bharshbarg/views-forall.perfexecopts
- test/performance/bharshbarg/views-forall.perfkeys
- test/performance/bharshbarg/views-forall.skipif
Add performance test to measure iteration and indexing on slices, reindexes and rankchanges.
> Add ArrayViews perf test

- compiler/resolution/lowerIterators.cpp
The inlineSingleYieldIterator optimization was originally added as part of some
prototype GPU code with af0e77e. Most of the GPU code was later removed in
60c2580, but inlineSingleYieldIterator remained.
The only thing this optimization does is permit zippered inlining of iters that
only yield a single value. i.e. iterators that do *not* have any loops and only
have a single top-level yield like `iter myIter() { yield 1; }`
This is not a common iterator idiom, and certainly not a performance critical
one. In fact there are only 3 tests that run into this, and none of them are
compelling.
This code isn't well understood by anybody on the team, and doesn't do anything
for performance, so it's being removed to simply iterator lowering.
This closes …
> Remove the single-yield iterator inlining "optimization"

- compiler/passes/normalize.cpp
Minor changes to normalization of defExpr for non-generic records with initializers to
reduce copying for e.g. "var x : MyRec = new MyRec(1, 2, 3);"
Passed single-locale paratest on linux64
> Streamline initialization of non-generic records with an explicit type

- compiler/passes/normalize.cpp
This is minor, intermediate, update for the normalization of DefExpr of the form
var x = new MyRec(...);
where MyRec is a non-generic record with an initializer.  This PR only affects the AST
generated in normalize for this simple case.
Passed single-locale paratest on linux64
> Streamline some cases of normalizing DefExpr for non-generic records

- compiler/passes/normalize.cpp
PR 5463 was intended to further normalization of non-generic records with initializers
but included another "small change" that seemed to be a simple streamlining.
Unfortunately the second set of adjustments ran afoul of some business logic in
passes/parallel.cpp.  I have a rough sense of what I did wrong but I have yet to
fully characterize the issue.
In the meantime this PR reverts the second portion of the PR to the original state.
I have confirmed compilation with/without CHPL_DEVELOPER, confirmed that the
failing tests are now passing for two multi-locale configs, and ran a single-locale
paratest.
> Revert the component of PR 5463 that broke gasnet testing

- util/devel/chplspell-dictionary
- util/devel/chplspell-dictionary.fileids.json
> chplspell dictionary updates

- compiler/optimizations/deadCodeElimination.cpp
- compiler/resolution/callDestructors.cpp
Summary:
Update callDestructors.cpp to modify the code that converts procedures that
return values with record-type to be an equivalent procedure that returns the
value, in principle, by out-intent.
This change altered AST in a way that impacted deadStringLiteralElimination()
and so this PR includes a second commit that a) makes this code a little more
transparent b) updates the code to handle the new form of AST.  This update
includes a pair of largely "ad hoc" test that are intended to catch situations in
which changes to previous passes impact this cleanup
Passes paratest for single-locale, baseline, and gasnet.
Details/background:
A recent change to normalization of DefExpr caused multiple failures for
many no-local …
> Update to 2nd of implementation of return by ref

- compiler/passes/normalize.cpp
Before this PR the normalization of DefExprs has included code to inject extra temporaries
for const variables.  It isn't entirely clear what role these temporaries have played over time
but recently the primary effect has been to support the replication of const module level
variables.
Recent changes to isUserDefinedRecord() and the newer implementation of the transformation
to update procedures that return values with record-type finally allow these temporaries to be
retired.
This is a simple PR that does this.
Paratested with single-locale -futures on linux64 and gasnet on linux64.
> Additional streamlining for the normalization of DefExpr

- test/distributions/deitz/test_distribution_syntax2.bad
BenH's recent merge for ChapelArray.chpl altered the line number for this future.
Updating the .bad file appropriately.
> Tweak the line number to respond to a recent change to ChapelArray.chpl

- test/ANNOTATIONS.yaml
Add annotations for recent array views work:
* merge of array views
- included separate 16-node entry for hpl.hpcc2012, rewritten as part of array views work
* merge of wide pointer optimization for arrays resulting from array views work
> Array view annotations

- test/ANNOTATIONS.yaml
Remove annotations for dead graphs, add annotations for new graphs, and add an
annotation for isx problem size increase
> Update and fix multi-locale isx annotations

- test/ANNOTATIONS.yaml
In pulling the config tag, I needed to pull the text tag as well.
> Fix a syntax error

- compiler/resolution/tuples.cpp
Summary:
This is a trivial change to instantiate_tuple_init() to reduce the number of locations that
implement "variable initialization" business logic.  There should not be any change in
application behavior
Paratested on single-locale and gasnet for linux64
More detail:
A recent change to variable initialization (in normalize.cpp) altered the behavior of a future;
the future had been seg-faulting but was now timing out.  A little study revealed that the
program under consideration was inspecting uninitialized memory i.e. had undefined behavior.
Specifically there are non-trivial problems with the compiler generated _defaulfOf() function for
some uses of tuples.  It isn't clear how many problem cases there are but it is …
> Revise the code used to initialize a tuple

- util/cron/test-perf.chapcs.playground-2.bash
Similar to #5208, but using the official qthreads 1.12
> Test performance of having qthreads use Chapel's allocator

- test/ANNOTATIONS.yaml
- make blank intent for arrays "ref-if-modified" (#5134) -- improved MiniMD
- remove unnecessary return from array-return tests (#5486)
> Add this weeks perf annotations

- modules/internal/DefaultRectangular.chpl
Fix compile-time failure where I incorrectly passed a 2*int to a max function
>  Fix compile-time numa issue

- compiler/passes/normalize.cpp
Continued work on record initializers requires further edits to insert_call_temps in normalize.cpp;
a function that is already a little bloated.
This PR refactors this function in to a few simpler components but with no change in functionality.
Compiles with/without CHPL_DEVELOPER on clang/darwin and gcc/linux64
Passes single-locale paratest.
> Whitespace preparation for an update to insertCallTemps

- compiler/passes/normalize.cpp
Before this PR statements such as
return new MyRec(10, 20);
or
foo(new MyRec(10, 20), new  MyRec(30, 40));
where MyRec is a non-generic record with an initializer failed to resolve.
The problem was that the compiler was still trying to "construct" the call_tmp
instead of "initializing" it.  A relatively simple change to insertCallTemps()
addressed this oversight; as least for the common cases of new expressions.
start_test classes/initializers -futures on darwin
single-locale paratest on linux64
> Update normalization of new-expressions for non-generic records with initializers

- compiler/passes/normalize.cpp
This fixes a problem with refs to arrays in a global context.  For example:
``` chapel
module bar {
var dom = {1..10, 1..10};
var A : [dom] int;
ref R = A[1..4, 1..4]; // call_tmp = slice
// slice freed here
}
use bar;
proc main() {
writeln("Setting A[1,1] to 1");
A[1,1] = 1;
writeln("R[1,1] is now     ", R[1,1]);
for r in R do write(r);
writeln();
}
```
The problem is that the call_tmp storing A[1..4, 1..4] is destroyed at the end of the module bar's init function. This problem was discovered as part of PR #5576.
This PR resolves the issue by migrating such call_tmps to global variables. It adjusts moveGlobalDeclarationsToModuleScope in normalize to do so.
If the for_SymbolSymExprs loop here is costly, we could change normalize to mark the call_tmps initializing user reference variables …
> In normalize, global-ize call_tmps used to initialize refs too

- test/modules/sungeun/init/printModuleInitOrder.good
I think I understand a recent regression for this test and so I am updating the .good
file
> Update printModuleInitOrder.good to account for a new module

- modules/internal/ArrayViewRankChange.chpl
I thought I'd committed this prior to last night's merge, but apparently not.  Adding it now.
> Add a comment to address one of Michael's review comments

- runtime/src/chpl-topo.c
To get a NUMA sublocale object we were calling hwloc_get_obj_by_depth()
to get the Nth object at the topology level corresponding to NUMA
domains, where N corresponded to the Chapel sublocale ID.  This was
coded under the assumption that the things at the level were all
traditional CPU+memory NUMA domains.  That's not true in some of the KNL
configurations.  We fixed one problem in #5740, to avoid counting NUMA
domain objects not containing CPUs when computing our own NUMA sublocale
count when using Cray KNL nodes in the "quad" mode.  However, it wasn't
enough.  In the "snc4" mode we get 4 groups of pairs of NUMA objects,
with the first object in each pair containing 1/4 of the CPUs and 1/4 of
the regular memory, and the second containing 1/4 of the MCDRAM.  The
objects in order at the …
> Be sure the NUMA objects we refer to have CPUs.

- compiler/passes/initializerRules.cpp
Lydia noted that the "in progress" PR 5797 was initializing fields twice in some circumstances.
In practice this was the result of failing to remove some reference AST after constructing the
desired initialization AST. Thanks Lydia! This simple PR fixes this oversight.
This mistake is reasonably easy to see when one is debugging intermediate AST during the
preNormalize step for initializers, which is what Lydia was doing, but is harder to spot after
the end of normalize unless one is thinking carefully.
start_test on test/classes/initializers with futures on darwin
single-locale paratest with futures on chapcs
> Cleanup AST after initializing a field from a stmt

- test/users/npadmana/twopt/do_smu_soa.chpl
To enable release-over-release graphs.
Verified test/users/npadmana/twopt/ passes with this change on master and on 1.14.
> Adjust do_smu_soa.chpl for backwards compatibility with RandomStream

- test/ANNOTATIONS.yaml
Waiting for [memory-tracking data](http://chapel.sourceforge.net/perf/chapcs/?startdate=2017/03/16&enddate=2017/03/23&graphs=memoryleaksforalltests) to finish before merging.
**Tested:**
```bash
>./check_annotations.py
No fatal annotation errors detected
```
> 03/23/17 Performance Annotations

- doc/technotes/llvm.rst
- doc/usingchapel/chplenv.rst
- third-party/llvm/Makefile.include-system
- third-party/llvm/unpack-llvm.sh
Document new CHPL_LLVM settings added in PR #4822.
Adjust comments in third-party/llvm Makefile and shell script.
> Update LLVM docs

- doc/technotes/voidVariables.rst
Add a technote document describing void variables and fields. Verified that
"make docs" properly generates the html version of this file.
> Add a technote about void variables and fields

- modules/internal/DefaultRectangular.chpl
> Fix integer sign issues exposed by unsigned array API test

- spec/Functions.tex
Responding to combining PR #5800 and PR #5444.
> Fix a cross-reference is the spec

- doc/rst/developer/chips/10.rst
Intended to cover what parts of the feature are and are not supported today.
> Add a section to the beginning of the initializers CHIP for the status

- modules/internal/String.chpl
- test/types/string/psahabu/one-element-split.chpl
- test/types/string/psahabu/one-element-split.good
@cassella caught this bug in ``String.join()``. linux64+flat testing pending.
> String join() needs domain.first

- modules/Makefile
- modules/standard/SysError.chpl
Addresses shortcoming in #5162 pointed out by @bradcray.
> include SysError, remove Error docs in Makefile

- doc/rst/platforms/arm.rst
- doc/rst/platforms/index.rst
This change provides basic documentation for 64-bit ARM support.
> Document ARM support

- spec/Domains.tex
- spec/Modules.tex
While there, adjusted index entries to group things together in fewer top-level index entries.
I am not adding code examples because it is too close to code freeze. TODO this after the release.
> Added module deinitialization to spec

- doc/rst/developer/chips/10.rst
- doc/rst/technotes/initializers.rst
Lydia spotted two errors (one significant and one less material) that are trivially fixed.
> Minor fixes

- doc/rst/platforms/cray.rst
As I understand it, the issue described in this `.. note` is now resolved from  #4931 and the follow-on work.
> Update cray.rst info

- CHANGES.md
Didn't find anything major, just some minor word-smithing
> Minor cleanups to the CHANGES files

- doc/rst/technotes/localeModels.rst
Change some blocks of Chapel code in docs from code-block sh to code-block chapel.
> Tweak markup

- test/ANNOTATIONS.yaml
- test/studies/shootout/binary-trees/binary-trees.graph
* Added an annotation for last night's changes to problem size + approach
* Improved legend on the studies version of the graph
> Binary-trees cleanups for graphs

- test/classes/initializers/generic_initializer.chpl
- test/classes/initializers/initArrayField.chpl
- test/classes/initializers/phase1/omittedCastEtc.chpl
- test/classes/initializers/phase1/omittedDefaultOfField.chpl
- test/classes/initializers/secondary/bothSecondaryAndPrimary.chpl
- test/classes/initializers/secondary/inDiffModule2.chpl
- test/classes/initializers/secondary/inSameModule.chpl
I accidentally forgot to delete some of the class instances I 'new' in my
initializers tests.  Rectify that
> Plug user leaks in some initializers tests

- util/test/perf/index.html
- util/test/perf/perfgraph.js
Some minor changes are needed now that parts of the old API are no longer available.
> Upgrade to dygraphs 2.0

- util/test/perf/index.html
- util/test/perf/perfgraph.js
This ended up causing some rather unfortunate issues with Date parsing, so let's revert this until we're more confident.
Reverts #5977
> Revert "Upgrade to dygraphs 2.0"

- third-party/re2/README
This PR addresses feedback from @ronawho on third-party/re2/README.
> Improve third-party/re2/README

- spec/Methods.tex
Thanks to @noakesmichael for pointing out the issue.
Passed test/release/examples/spec/ in quickstart config.
> Fix defineMethod spec test

- compiler/resolution/visibleCandidates.cpp
While working on a type-alias bug I cleaned up portions of the code that handles
instantiation of functions that accept var-args.  This is the first of a small series
of trivial PRs that will merge that work to master.
Compiled with/without CHPL_DEVELOPER on clang and gcc.
Passed a paratest.
> Begin to merge VarArgs cleanup to master

- compiler/resolution/visibleCandidates.cpp
A sequence of 6 trivial commits that contribute to the task of clarifying the business logic
used to resolve calls to functions that support var-args.
No change in behavior
Compiled on clang and gcc
Passed a paratest
> Continue to merge VarArgs code from branch to master

- modules/packages/LinearAlgebra.chpl
- Fix 2 minor typos
- Remove comment block detailing TODOs
> Tidy Linear Algebra Docs

- CHANGES.md
I got install.html and build.html backwards...
> Fix a typo in CHANGES.md

- compiler/passes/externCResolve.cpp
@dmk42  informed me that my PR to simplify the use of buildClassDefExpr() was failing with
CHPL_LLVM=llvm.  I missed a call to this function that was guarded by HAS_LLVM.
Trivial tweak to the call-site.  Compiled with/without CHPL_DEVELOPER.  Ran a portion of
test/release.
> Fix a use of buildClassDefExpr() that was guarded by HAS_LLVM

- compiler/parser/parser.cpp
A trivial follow up re-alignment of the code within the merged parser/parser.cpp
Compiled with/without CHPL_DEVELOPER on clang/darwin, gcc/linux64.
Passed a single-locale paratest with --no-local as a change of pace
> Simple shuffle for clarity

- compiler/include/bison-chapel.h
- compiler/include/flex-chapel.h
- compiler/parser/bison-chapel.cpp
- compiler/parser/chapel.ypp
- compiler/parser/flex-chapel.cpp
Addresses some missing semicolons pointed out in an email to chapel-developers on April 27. Thanks for pointing out the issue!
Link to email:
https://sourceforge.net/p/chapel/mailman/chapel-developers/thread/CAOWk_Z5RQ0rqaLJOFyCbSY4Jt4e7LASNrRKBNOjEW47xamnBgw%40mail.gmail.com/#msg35809547
> Add missing ; between grammar rules

- compiler/parser/parser.cpp
A trivial update to repair an unintended regression for internal module NetworkAtomicTypes
The module NetworkAtomicTypes is defined in two conflicting files.  Until recently this ambiguous
definition was quietly suppressed at the risk of masking other internal dupes.  I removed this mask
without understanding that the UGNI configuration currently relies on this.
This PR restores the previous behavior.
Compiled under clang/gcc.
Ran a single-locale paratest
Confirmed that UGNI is fixed
> Suppress a warning for the dupe of module NetworkAtomicTypes

- test/exercises/boundedBuffer/README
- test/exercises/boundedBuffer/boundedBuffer.chpl
- test/exercises/boundedBuffer/solutions/boundedBuffer-sync.chpl
Took an editing pass over the bounded buffer exercise for ACCU 2017:
* did some pretty significant worthsmithing to the README and comments in the source
* did a minor simplification to the advance() routine for the sync variable solution.
> ACCU 2017 bounded buffer cleanup

- compiler/passes/scopeResolve.cpp
This is a simple merge that continues the effort to manage the gap between master and
a development branch for scopeResolve.cpp
Before this PR, the code in scopeResolve.cpp has an informal and incomplete sense of a
"Scope" that was implemented using a typedef and a number of file static functions.
This PR introduces a local class `Scope' that begins the effort to represent this state in a
somewhat more formal way.  However the basic state that is being retained and the mechanisms
to manage this state are fundamentally unchanged by this PR.
Passed single-locale paratest
> Introduce Scope

- modules/dists/ReplicatedDist.chpl
I was working in two spaces yesterday, and accidentally left these
proposed wording mods from Vass on the floor in one of them.
> Oops -- forgot to commit these wording changes Vass proposed

- .gitignore
- modules/standard/Path.chpl
- test/modules/standard/Path/saru/getParentName/parentName.chpl
- test/modules/standard/Path/saru/getParentName/parentName.preexec
- test/modules/standard/Path/saru/getParentName/parentNameErr.chpl
- test/modules/standard/Path/saru/getParentName/parentNameErr.preexec
- test/modules/standard/Path/saru/getParentName/testFile.txt
As mentioned here: https://github.com/chapel-lang/chapel/issues/6006
> Added support for IO.file.getParentName()

- util/devel/chplspell-dictionary
- util/devel/chplspell-dictionary.fileids.json
> chplspell dictionary update

- test/chpldoc/module/modDeinit.doc.bad
- test/chpldoc/module/modDeinit.doc.catfiles
- test/chpldoc/module/modDeinit.doc.good
Be sure that it includes the necessary file to append to ensure our
generated output is accurate, and update the .bad and .good
file for the included output.
> Update chpldoc deinit test

- modules/internal/ChapelArray.chpl
Add `reindex()` and `localSlice()` methods to the public documentation.
> Publicize reindex / localSlice

- compiler/include/vec.h
Trivial comment and spacing change.
> Comment and adjust spacing in forv_Vec

- test/ANNOTATIONS.yaml
- NPB MG correctness fix
- nonblocking strided transfer improved PRK
> Add annotations for the last week

- doc/rst/platforms/cray.rst
- modules/packages/MPI.chpl
Update cross-reference in MPI docs
> Update cross-reference in MPI docs

- test/studies/prk/DGEMM/dgemm.chpl
Fix a small bug with potentially big impact in reported performance. Solves #6413 
The test passed with standard linux64 config.
> Fix the timing error in PRK-DGEMM

- test/ANNOTATIONS.yaml
Note multi-locale performance changes for the stencil PRK and NPB EP.
Verified the annotation checker passed these changes
> Add annotations for this week

- compiler/AST/build.cpp
Optimize remote task creation speed. This applies the same optimization done
for local coforalls in #5018, but to remote coforalls
We used to transform code like:
```chapel
coforall loc in Locales do on loc { }
```
into roughly something like:
```chapel
for loc in Locales {
_upEndCount(_coforallCount);
executeOnNB(loc, body());
}
_waitEndCount(_coforallCount);
```
and now we transform it into something like:
```chapel
var tmpIter = Locales;
var bounded = isBoundRange(tmpIter) || isDomain(tmpIter) || isArray(tmpIter);
if bounded {
var numTasks = tmpIter.size;
// only bump EndCount once, instead of once per task
_upEndCount(_coforallCount, numTasks);
for loc in tmpIter {
executeOnNB(loc, body());
}
_waitEndCount(_coforallCount, numTasks);
} else  {
// old style coforall+on
}
```
Under ugni …
> Implement bounded-coforall optimization for remote coforalls 

- compiler/passes/scopeResolve.cpp
Merge a trivial update on my scope-resolve branch to master.
scopeResolve includes a small amount of "remarkable" code to support array aliases in
new expressions.  This code path supports a feature that was deprecated for 1.15 and
is only used in one test in deprecated/
This PR simply extracts two blocks of inline-logic into helper functions, moves these to
the bottom of the file, and adds some comments to clarify what is going on.
Compiled with/without CHPL_DEVELOPER on clang/darwin and gcc/linux64 and ran a
portion of release/ on all 4 configs.  Also tested deprecated/ on all 4 configs.  Then
passed a single-locale paratest
> Cordon off the AliasField code

- test/errhandling/nspark/fn-returns-or-throws.bad
- test/errhandling/nspark/fn-returns-or-throws.chpl
- test/errhandling/nspark/fn-returns-or-throws.future
- test/errhandling/nspark/fn-returns-or-throws.good
- test/errhandling/nspark/generic-fn-throws.bad
- test/errhandling/nspark/generic-fn-throws.chpl
- test/errhandling/nspark/generic-fn-throws.future
- test/errhandling/nspark/generic-fn-throws.good
- test/errhandling/nspark/generic-record-throws.bad
- test/errhandling/nspark/generic-record-throws.chpl
- test/errhandling/nspark/generic-record-throws.future
- test/errhandling/nspark/generic-record-throws.good
- test/errhandling/nspark/generic-record-throws.prediff
- test/errhandling/nspark/method-returns-or-throws.bad
- test/errhandling/nspark/method-returns-or-throws.chpl
- test/errhandling/nspark/method-returns-or-throws.future
- test/errhandling/nspark/method-returns-or-throws.good
- test/errhandling/nspark/method-returns-or-throws.prediff
- test/errhandling/nspark/method-throws.chpl
- test/errhandling/nspark/method-throws.good
- test/errhandling/nspark/record-deinit-throws.bad
- test/errhandling/nspark/record-deinit-throws.chpl
- test/errhandling/nspark/record-deinit-throws.future
- test/errhandling/nspark/record-deinit-throws.good
@nspark:
I've retired and modified some of the futures from #6267 in this branch and will merge them here.
> cleaned up "Add some tests and futures for error-handling use-cases"

- CONTRIBUTORS.md
Boy are we bad at alphabetizing...  (where I realize that "we" == "I"
for the most part here...)
> Fix alphabetization of contributors

- doc/rst/developer/chips/20.rst
Important information was revealed in discussion that isn't reflected in
this CHIP. Since I'm not going to get to it for a while, at least point
to the issue containing the discussion.
> Add TODO to CHIP 20

- test/classes/initializers/phase1/parentAccess.future
- test/classes/initializers/phase1/parentAccess.good
- test/classes/initializers/phase2/parentAccess.future
- test/classes/initializers/phase2/parentAccess.good
Update 2 .good files for initializers and then retire the associated futures
> Update 2 .good files and retire the associated futures

- test/studies/twitter/survey.prediff
Match both lowercase and uppercase letters in the hostname in the prediff
script.
> Fix studies/twitter/survey.prediff to allow uppercase hostname

- test/classes/initializers/initCallsDom.future
Retire a passing initializer future
> Retire a passing initializer future

- compiler/optimizations/localizeGlobals.cpp
- compiler/optimizations/loopInvariantCodeMotion.cpp
Update LICM and localizeGlobals to better use QualifiedType and PRIM_SET_REFERENCE
Testing:
> QualifiedType for LICM

- test/ANNOTATIONS.yaml
Annotating changes that I introduced in k-nucleotide and memory leaks.
Also fixing a bug in #6499 that the annotations checker caught.
> Add annotations for my recent changes

- compiler/AST/AstCount.cpp
- compiler/AST/AstLogger.cpp
- compiler/AST/AstPrintDocs.cpp
- compiler/AST/AstVisitorTraverse.cpp
- compiler/AST/CollapseBlocks.cpp
- compiler/AST/ForallStmt.cpp
- compiler/AST/view.cpp
- compiler/include/AstCount.h
- compiler/include/AstLogger.h
- compiler/include/AstPrintDocs.h
- compiler/include/AstVisitor.h
- compiler/include/AstVisitorTraverse.h
- compiler/include/CollapseBlocks.h
> Added visitors and viewing for ForallStmt

- test/types/records/compilerErrors/deleteRecordMessage.bad
- test/types/records/compilerErrors/deleteRecordMessage.chpl
- test/types/records/compilerErrors/deleteRecordMessage.future
- test/types/records/compilerErrors/deleteRecordMessage.good
See corresponding issue: #6544
> future: deleting record gives wrong line number

- test/users/engin/retInnerFunction.bad
- test/users/engin/retInnerFunction.chpl
- test/users/engin/retInnerFunction.future
- test/users/engin/retInnerFunction.good
Adds a future for issue #6538 
Added test is reported as future with standard linux64. 
TODO before merge (I think):
> Add new error message future for issue #6538

- test/statements/defer/defer-break-in-do-while-loop.chpl
- test/statements/defer/defer-break-in-do-while-loop.future
- test/statements/defer/defer-break-in-do-while-loop.good
- test/statements/defer/defer-break-in-loop.chpl
- test/statements/defer/defer-break-in-loop.good
- test/statements/defer/defer-in-loop.chpl
- test/statements/defer/defer-in-loop.good
- test/statements/defer/defer-manual-container-throws.bad
- test/statements/defer/defer-manual-container-throws.chpl
- test/statements/defer/defer-manual-container-throws.future
- test/statements/defer/defer-manual-container-throws.good
- test/statements/defer/defer-manual-container.chpl
- test/statements/defer/defer-manual-container.execopts
- test/statements/defer/defer-manual-container.fail1.good
- test/statements/defer/defer-manual-container.fail2.good
- test/statements/defer/defer-manual-container.fail3.good
- test/statements/defer/defer-manual-container.success.good
- test/statements/defer/defer-return-in-loop.chpl
- test/statements/defer/defer-return-in-loop.good
- test/statements/defer/do-while-defer.break1.good
- test/statements/defer/do-while-defer.break2.good
- test/statements/defer/do-while-defer.chpl
- test/statements/defer/do-while-defer.execopts
- test/statements/defer/do-while-defer.nobreak.good
This should merge after PR #6551 and PR #6558.
Not reviewed.
> Add new tests of defer

- compiler/include/llvmUtil.h
> Fix typo in llvmUtil.h

- compiler/optimizations/remoteValueForwarding.cpp
- compiler/passes/parallel.cpp
> More QualifiedType for the parallel and RVF passes

- test/classes/initializers/generics/inheritance/inheritance-inline.bad
- test/classes/initializers/generics/inheritance/inheritance-inline.chpl
- test/classes/initializers/generics/inheritance/inheritance-inline.future
Add test for inheriting classes and initializers that fails during inlining
> Initializer bug with inheritance and inlining

- compiler/optimizations/deadCodeElimination.cpp
- test/statements/defer/defer-break-in-do-while-loop.future
- test/types/records/ferguson/deinit/break-in-do-while.future
- test/types/records/ferguson/deinit/return-in-do-while.future
Fix a deadBlockElimination bug that that removed do-while loops with
unconditional breaks/returns.
For something like:
```chapel
proc foo() {
do {
writeln("in loop");
break; // or return;
} while (true);
}
foo();
```
we mistakenly removed the entire do-while loop. For this case the basic block
construction looks something like:
```
0:   >  1 3
189546  def const-val tmp:bool
1:  0 2  >  3
189525  call( fn writeln "in loop" )
189528  goto _breakLabel
2:   >  3 1
189545  tmp
3:  2 1  >
189547  def _breakLabel
408343  return( _void )
```
We can see that block 2 (the condition of the do-while loop) is dead because
the break/return prevents it from ever being evaluated. However, the do-while
loops were triggering a while-loop path that removed the entire loop. If the
condition of a while-loop …
> Fix a deadBlockElimination bug for do-while loops

- compiler/resolution/functionResolution.cpp
Trivial update that extracts the early validation code in to helpers.
> resolveMove() :- extract the early validation code

- spec/Statements.tex
- spec/chapel_listing.tex
Spec changes to describe defer statements. Intended to merge after PR #6526.
Verified that new spec tests are passing.
> Draft spec changes for defer

- spec/Generics.tex
- spec/Procedures.tex
This commit makes spec changes to go along with issue #6641 and PR #6621.
> Spec updates for partially generic arguments

- compiler/resolution/functionResolution.cpp
Trivial update that extracts the code that 
1. exits early if the move implements a return for an unresolved variable unless it is a construtor
2. determines the initial type for RHS and LHS.
> Prim move 3

- compiler/resolution/functionResolution.cpp
Simple update that extracts the code to halt for trivially unacceptable types
> resolveMove() :- Extract code to halt for trivially unacceptable types

- compiler/resolution/functionResolution.cpp
Simple update that shuffles the special case handling for chplHereAlloc();
> resolveMove() :- Juggle the special case for chplHereAlloc()

- compiler/resolution/functionResolution.cpp
A simple update to extract the core logic that finalizes the type evaluation and,
if necessary, inserts a cast.  Leverage this to simplify the control flow on the
primary path through resolveMove().
> resolveMove() :- Extract the core code and simplify control flow

- compiler/resolution/functionResolution.cpp
A simple update that simplifies the interface to moveRhsType() and thence
simplify the signature of moveCast().
> resolveMove() :- Tweak moveRhsType() and then moveCast()

- compiler/resolution/functionResolution.cpp
This PR splits moveSetFlagsAndCheckForConstAccess() in to two functions
and leverages the helper function to simplify/clarify the control flow in the
reduced version of moveSetFlagsAndCheckForConstAccess().
> resolveMove() :- Partition moveSetFlagsAndCheckForConstAccess()

- compiler/resolution/functionResolution.cpp
Before this PR resolveMove() consisted of three sections; initial validation and type evaluation,
handling the case when the RHS is a SymExpr, and handling the case when the RHS is a CallExpr.
Separate these and clean up the resulting, simplified version of resolveMove().
> resolveMove() :- Partition resolveMove()

- modules/dists/PrivateDist.chpl
Avoid documentation-breaking bug documented in #5791
> No-doc PrivateDist deinit

- test/classes/initializers/generics/nested2.future
> Fix a typo in nested.future

- doc/rst/developer/chips/21.rst
Fix typos in cryptography chip 21
> Fix typos in chip 21 (crypto)

- doc/rst/developer/chips/22.rst
> Fix typos in chip 22 (GPUs)

- compiler/resolution/wrappers.cpp
This simple PR groups defaultWrap() and its helpers together.  The delta looks large
but it's just shuffling and adding the odd open/close brace.
Compiled for the various obvious configurations and tested in the standard ways.
> Group the helpers for defaultWrap() together

- compiler/resolution/wrappers.cpp
This simple PR relocates the wrapper helper function reorderActuals() to the natural position.
No change in behavior.
Compiled/tested in the standard ways.
> Move reorderActuals() in to the natural position

- compiler/resolution/wrappers.cpp
This simple PR groups the helper functions for coerceActuals() and places them in a natural
order.  No change in behavior.
Compiled/tested in the standard ways.
> Group wrapper helpers coerceActuals() et. al.

- modules/standard/Types.chpl
> Improved chpldocs for isClass()

- compiler/AST/expr.cpp
Before this PR --verify failed if a method was called using an explicit module e.g.
M1.myInstance.foo(1, 2, 3);
The problem was that CallExpr::verify() enforced the invariant that, if present, gMethodToken must
be in position 1.  However the use of the explicit module means that gModuleToken is in position 1
and gMethodToken is moved to slot 3.
This simple PR
1. extends CallExpr::verify() to confirm that the gModuleToken, if present, is in position 1.
2. updates CallExpr::verify() to confirm that gMethodToken, if present, is in position 1 or 3 based
on the presence of gModuleToken.
Compiled/tested using the standard protocol.
> mod-scope :- update CallExpr::verify()

- compiler/resolution/functionResolution.cpp
Continue to refine the call path for resolveNormalCall().
This is a final clean up pass for this sequence that
extracts the obvious "helper functions".
Compiled/tested with the standard protocol.
> resolveNormalCall :- Extract helper functions

- compiler/AST/symbol.cpp
- compiler/AST/wellknown.cpp
- compiler/include/symbol.h
- compiler/passes/errorHandling.cpp
- modules/internal/ChapelError.chpl
- test/errhandling/mferguson/throws-destroys.1.good
- test/errhandling/mferguson/throws-destroys.2.good
- test/errhandling/mferguson/throws-destroys.4.good
- test/errhandling/mferguson/throws-destroys.5.good
- test/errhandling/mferguson/throws-destroys.6.good
- test/errhandling/mferguson/throws-destroys.7.good
- test/errhandling/mferguson/throws-destroys.8.good
- test/errhandling/psahabu/no-prop-implicit.good
- test/errhandling/psahabu/no-prop.good
- test/errhandling/psahabu/propagate-implicit.good
- test/errhandling/psahabu/propagate.good
- test/errhandling/psahabu/top-notry.good
- test/errhandling/psahabu/top-try-bang.good
* adds well-known-function chpl_uncaught_error
* implements chpl_uncaught_error similarly to halt
* generate code calling chpl_uncaught_error to implement try!
Reviewed by @psahabu - thanks!
> Print out errors on try!
