test/visibility/only/errorWhenBehindPrivateUse.chpl, test/visibility/only/errorWhenBehindPrivateUse.compopts, test/visibility/only/errorWhenBehindPrivateUse.future, test/visibility/only/errorWhenBehindPrivateUse.good
=> Add future tracking bug with only lists containing a symbol behind a private use

modules/packages/Sort.chpl, test/library/packages/Sort/correctness/correctness.chpl, test/library/packages/Sort/performance/performance.chpl, test/library/packages/Sort/performance/performance.good, test/library/packages/Sort/performance/performance.perfexecopts, test/library/packages/Sort/performance/sort-performance-explorer.chpl, test/library/packages/Sort/performance/sorts-linearithmic.graph
Signed-off-by: Yudhishthira1406 <divyen1406@gmail.com>
**Parallel TimSort Implementation**
Implemented parallel insertion sort for each block and parallel merge each segment at each level of merging
The issue #15045
=> Implement Parallel TimSort Algorithm 

test/constrained-generics/basic/param-implementation-of-non-param.bad, util/chpl-completion.bash
Fix a couple of testing issues with #16995
=> Fix test failures from #16995

modules/standard/Sys.chpl
Signed-off-by: Yudhishthira1406 <divyen1406@gmail.com>
Solves Issue #16705 
This PR adds documentation to the sys_getenv procedure in the Sys module
=> Improve sys_getenv documentation

test/optimizations/autoAggregation/dynamicallyAlignedFollowers.good
This future was added in https://github.com/chapel-lang/chapel/pull/17035, but
without a good file. When the feature requested is added, the output might be
slightly different than the good file I am adding here. It'll need to be
adjusted.
=> Add the missing .good file for a new future

test/studies/lulesh/release-valgrind/lulesh.execopts
Duplicate PR 17086's changes into another lulesh test instance.
Signed-off-by: Greg Titus <gbtitus@users.noreply.github.com>
=> Avoid using catfiles for lulesh testing

modules/dists/BlockDist.chpl, modules/dists/CyclicDist.chpl, modules/internal/ChapelDistribution.chpl
This adds a couple of uses of the if-var construct in the modules.
These are the changes that I withheld from #17047 in 391973eae0
to avoid impact on testing at the time.
r: @mppf as part of #17047
=> Add uses of if-var in modules

runtime/src/qio/regexp/re2/re2-interface.cc
Use C11/C++11 `thread_local` instead of pthreads for thread-local regexp cache.
=> Use C++11 thread_local instead of pthreads for thread-local regexp cache

compiler/optimizations/deadCodeElimination.cpp
In working on PR #16643, one of the paths I abandoned required
updating isDeadModule. These changes are no longer required but
make the implementation more robust.
Reviewed by @e-kayrakli - thanks!
=> improvements to isDeadModule

compiler/AST/AstToText.cpp, test/chpldoc/functions/functionArgDefaults.doc.chpl, test/chpldoc/functions/functionArgDefaults.doc.good, test/chpldoc/globals/variableDefaultValues.doc.chpl, test/chpldoc/globals/variableDefaultValues.doc.good, test/chpldoc/types/fields/rangesAndDomains.doc.chpl, test/chpldoc/types/fields/rangesAndDomains.doc.good
Translate chpl_by and chpl_align to " by " and " align ".
Add tests.
Resolves #17163
---
Signed-off-by: Paul Cassella <gitgitgit@manetheren.bigw.org>
=> chpldoc: handle range by and align clauses

test/ANNOTATIONS.yaml
Add perf annotations for:
- IO regression from removing inline from IO procs
=> Annotate IO performance regression

compiler/passes/splitInit.cpp, test/types/records/copy-elision/issue-17272.chpl, test/types/records/copy-elision/issue-17272.good
Resolves #17272.
Follow-up to #17258.
Reviewed by @bradcray - thanks!
=> Update copy elision to allow local blocks

README.rst
Reverts chapel-lang/chapel#17311
=> Revert "temp"

CONTRIBUTORS.md
This is the CONTRIBUTORS file for the Chapel 1.24 release.  Thanks to everyone who contributed code!
=> CONTRIBUTORS for Chapel 1.24

CHANGES.md
This is the CHANGES.md file for Chapel 1.24.  Thanks to everyone for all the hard work (creating this file, but mostly doing the changes themselves)!
=> CHANGES file for Chapel 1.24

test/release/examples/primers/learnChapelInYMinutes.chpl
Fixed a minor typo in [learnChapelInYminutes](https://github.com/chapel-lang/chapel/blob/master/test/release/examples/primers/learnChapelInYMinutes.chpl).
@lydia-duncan Kindly review the changes.
Signed-off-by: piyush0411 <piyush04111999@gmail.com>
=> Fixed a typo

util/pastPerformance/testReleasesPerformance, util/test/perf/perfgraph.js
=> Added 1.24.0 release

doc/rst/language/evolution.rst, util/build_configs/cray-internal/generate-dev-releaseinfo.bash
None of these are deeply important to update, but I figured as long as I'd gone looking for them...
=> Replace links to users.html with links to the new community.html page

util/dockerfiles/Dockerfile, util/dockerfiles/README.md
=> Updated Dockerfile and README to reflect the latest release of 1.24.0

runtime/src/comm/gasnet/comm-gasnet.c
Instead of manually implementing a lock, use the spinlock wrapper. For
`CHPL_ATOMICS=cstdlib` the implementation is the same so this is just a
minor code cleanup. It'll have better performance for other atomic
implementations, but cstdlib is the default in most places anymore.
=> Use our spinlock to serialize gasnet poller calls

compiler/util/stringutil.cpp
Now that the compiler sources require C++11, we can use 
`std::unordered_map`. This PR adjusts the hashtable we use to unique 
strings (for `astr`) to use `std::unordered_map` and, while there, better
factor/optimize a few related functions.
In my experiments, this PR reduces Hello World compile times by about 
0.1s. But, besides that, it migrates one use of the custom `Map` to a
standard C++ type. We would like, over time, to migrate all uses of the
custom `Map` and then remove it.
Reviewed by @leekillough - thanks!
=> Update astr mechanism to use C++11 unordered_map

modules/standard/Regexp.chpl, modules/standard/Spawn.chpl, runtime/src/qio/regexp/re2/re2-interface.cc
Started working on #11417 
This is my first contribution to Chapel. Kindly review the change.
I shall push more commits to this pull request.
Thanks :)
=> Add `throws` documentation to Modules

doc/rst/conf.py
@bradcray  I edited this comment in doc/rst/conf.py according to my  last PR #17400
=> Corrected a comment in doc/rst/conf.py

modules/standard/CommDiagnostics.chpl
Follow-up to PR #16905
Reviewed by @e-kayrakli - thanks!
=> document cache_get_hits etc

modules/standard/List.chpl, test/library/standard/List/indexOf/listIndexOfEmptyList.chpl
Signed-off-by: piyush0411 <piyush04111999@gmail.com>
Fixes #17457 
Tested with the following input.
```
use List;
var l: list(int);
writeln(l.indexOf(3));
```
The output comes out to be `-1`, as required.
=> Fixed 17457

modules/standard/DateTime.chpl
- feat: operator overload for datetime and time
- feat: add operator overload for datetime and date
fixes #16552
=> datetime operators

modules/standard/DateTime.chpl
fixes #16733
Signed-off-by: Lakshya Singh <lakshay.singh1108@gmail.com>
=> feat: time since epoch unix function

util/cron/test-perf.cray-cs-hdr.arkouda.bash, util/cron/test-perf.cray-cs-hdr.arkouda.release.bash
It's available on compute nodes again
=> Stop avoiding /cray/css for Cray CS HDR Arkouda testing

modules/standard/Types.chpl, test/library/standard/Types/isNothing-proc.chpl, test/library/standard/Types/isNothing-proc.good
Resolves #17254.
This a simpler version of a previous [PR](https://github.com/chapel-lang/chapel/pull/17286/files#)
=> refactor isNothingvalue proc

compiler/main/version_num.h, doc/rst/conf.py, doc/rst/usingchapel/QUICKSTART.rst, doc/rst/usingchapel/chplenv.rst, man/confchpl.rst, man/confchpldoc.rst
Updating versions numbers prior to 1.24.1 release
=> Updating version numbers to 1.24.1

test/library/packages/LAPACK/TestHelpers.chpl
Passed a fresh checkout of the tests
----
=> Update the LAPACK helper file to use operator methods and the operator keyword

modules/internal/ChapelIteratorSupport.chpl
=> At Brad's suggestion, transform these operators on iterators into methods

third-party/llvm/Makefile, util/chplenv/chpl_llvm.py
This reverts commit 8551273a2d1755699a38eb3336e05a51248b91dc.
=> Revert "Enable LLVM by default"

util/dockerfiles/Dockerfile, util/dockerfiles/README.md
=> Updating Dockerfile and README

util/test/start_test.py
Creating functionality from https://github.com/Cray/chapel-private/issues/1608
Adding -respect-skipifs flag and changing os.environ variable based on flag
=> Adding ability to respect skipif files when testing individual files

modules/internal/Bytes.chpl, modules/internal/String.chpl, test/release/examples/primers/learnChapelInYMinutes.chpl, test/release/examples/primers/learnChapelInYMinutes.prediff, test/types/bytes/multiplication.chpl, test/types/bytes/multiplication.good, test/types/string/multiplication.chpl, test/types/string/multiplication.good
This PR adds commutativity in bytes and string multiplication with int. 
Resolve #17506
=> Added commutativity in string/bytes multiplication

modules/standard/ChapelIO.chpl, modules/standard/IO.chpl
Fixes https://github.com/chapel-lang/chapel/issues/17525
=> Fix ChapelIO documentation

modules/internal/ChapelLocale.chpl
=> Document locale.runningTasks

doc/rst/developer/implementation/Interfaces.md
This adds a summary of the current implementation of
interfaces aka constrained generics (CG).
=> IFC: Add a writeup on the implementation of Interfaces

compiler/resolution/implementForallIntents.cpp, test/types/records/bugs/segfault-on-task-intent.bad, test/types/records/bugs/segfault-on-task-intent.future
This resolves #17759.
The details about the problem and the solution are in [this comment](
https://github.com/chapel-lang/chapel/issues/17759#issuecomment-843650217).
=> Fix task-intent segfault

test/mason/subdir-commands/.mason.NOTEST, test/studies/lulesh/release-valgrind/PRECOMP, test/studies/lulesh/release-valgrind/lulesh.catfiles, test/studies/lulesh/release-valgrind/lulesh.cleanfiles
Remove four symlinks that are pointing at non-existent files.
=> Remove symlinks pointing to nothing

test/functions/typeMethods/arg-type-type-method.bad, test/functions/typeMethods/arg-type-type-method.chpl, test/functions/typeMethods/arg-type-type-method.good
I added this test in #17776.
Now extending it from testing a concrete class
to testing {concrete, generic} x {class, record}.
=> Beef up the test arg-type-type-method.chpl

compiler/codegen/type.cpp
Resolves a `--baseline` failure with arrays/deitz/promotion/test_scalar_promote1 among other tests.
=> Don't try to generate nothing/void fields for LLVM backend

modules/packages/Sort.chpl, tools/mason/MasonSearch.chpl
- Remove Tail Recursive Call 
- Save memory space by reducing call stack worst-case size
draft for #17178
=> preformance enhanced quicksort

test/functions/firstClassFns/FCFAssertion.chpl, test/functions/firstClassFns/FCFAssertion.good
Fixes: https://github.com/chapel-lang/chapel/issues/17622
Signed-off-by: Lee Killough <lee.killough@hpe.com>
=> Add assertion test for first-class functions which have 0 overloads

make/compiler/Makefile.gnu
When casting int64 values to uint64 values in our generated code,
we have traditionally run into, and then squashed, warnings from
specific versions of gcc in our generated code caused by its concern
that we might be using a negative or too-big number in doing a memcpy()
or the like.  This has become something of a game of whack-a-mole
where we hit a case, and then squash it for a specific version of gcc,
then run into another one in the future.  For example, see PRs #16204
and #6467.
This started happening this past weekend using gcc 10 and -O on some
of our systems where the integer value that the C compiler was complaining
about was received from another locale vs. a chpl_comm_get, so its value
couldn't possibly be known to the C compiler.  I was initially guessing that
this was due to …
=> Improve squashing of conservative gcc warnings

runtime/src/comm/ofi/comm-ofi.c
Comm=ofi performance testing on Cray CS systems has been showing a solid
regression in many-to-one remote fetching atomic performance since PR
17630, which added the message-order-fence MCM conformance mode.  It
turns out this was due to a logic error introduced by a related rewrite
of the routine that sends 'done' indicators for Active Messages (AMs).
That change was to add a libfabric read operation to force visibility of
prior libfabric writes before sending the 'done' in message-order-fence
mode, which doesn't have ordered writes.  The bug was that we also did
that ordering read in the existing message-order mode, where it was not
needed because that mode already has ordered writes including those for
'done' indicators.  Here, adjust so that we do the ordering read in
message-order …
=> Don't force PUT visibility before sending AM done in msgOrder mode.

runtime/include/config.h, runtime/src/config.c
In Re: https://github.com/chapel-lang/chapel/pull/17891#discussion_r648451847
=> Change private and isprivate to isPrivate

runtime/src/comm/ofi/comm-ofi.c
The libfabric wait/poll support requires `epoll`, which is a Linux thing
rather than a POSIX one and thus isn't present on macOS.  But because
macOS is a rather secondary target for libfabric, they haven't coded any
sort of workaround for that either.  The result is that depending on the
circumstances you can see a variety of unpleasant behaviors (internal
error, hang, segfault) if you turn on waiting and/or polling for CQs. So
here, just avoid wait/poll with CQs entirely under macOS.
There is some background information in the comments on this libfabric
issue, though the issue itself isn't directly about this problem:
ofiwg/libfabric#5453
=> Don't try to use CQ wait/poll on macOS in comm=ofi.

util/cron/nightly
I'm not sure how, but I must have misread the nightly output I was checking
to ensure the previous change worked.  This one actually does, though.
----
=> Fix my Perl syntax in checking the Python version and output the comparison

util/cron/common-whitebox.bash
Smoke testing got another failure, so revert #17933 to debug some more.
=> Revert whitebox testing

test/users/ferguson/assoc_domain_zip_range.bad
While looking over the files in my PR #17958 that needed to be updated
as of an 11th hour change to an error message, I overlooked this .bad,
which I'd updated earlier in the PR.  Shoot.
=> Update .bad to reflect final error message

modules/packages/AllLocalesBarriers.chpl
Fix a leak in allLocalesBarrier introduced by #17978
=> Fix a leak introduced in #17978

test/constrained-generics/hashtable/MyHashtable.chpl, test/constrained-generics/hashtable/test-chpl-hashtable.chpl
I am adding unmodified versions of ChapelHashtable.chpl and
test-chpl-hashtable.chpl as tests. I will use these versions
as a baseline to compare against in my upcoming interfaces PR.
Not reviewed.
=> IFC: prep for hashtable tests

modules/standard/Types.chpl
Signed-off-by: strikeraryu <striker.aryu56@gmail.com>
Documentation added for isXValue() as mentioned in Issue #17644.
Docs locally checked using make docs.
=> added doc for isXValue()

compiler/codegen/codegen.cpp, compiler/resolution/virtualDispatch.cpp, test/functions/default-arguments/default-argument-class-override3a.bad
Adds the temporary error for #17683.
Reviewed by @e-kayrakli and @bradcray - thanks!
=> Add not supported yet error for overridden param args with defaults

util/chplenv/chpl_compiler.py
To resolve the issue brought up by @ronawho in https://github.com/chapel-lang/chapel/pull/17923#pullrequestreview-703504129
=> Fix error in error handling for CC/CXX conflict

doc/rst/developer/implementation/Interfaces-new.md
This adds a document that reviews the aspects of implementation
that need to cater to interfaces and outlines a new implementation
direction for interfaces.
=> Writeup on a new implementation for interfaces

test/functions/ferguson/hijacking/issue-18119-rev.chpl, test/functions/ferguson/hijacking/issue-18119-rev.good, test/functions/ferguson/hijacking/issue-18119.bad, test/functions/ferguson/hijacking/issue-18119.chpl, test/functions/ferguson/hijacking/issue-18119.future, test/functions/ferguson/hijacking/issue-18119.good
Adds a future for the case described in issue #18119 as well as a variation
that currently works correctly.
=> Add future for issue 18119

modules/packages/ZMQ.chpl
Previously, an extra copy was being done when calling ZMQ `recv` from
the locale that owns the Socket. This copy can be slow for large
byte/string operations so eliminate it when we can.
Motivated by https://github.com/Bears-R-Us/arkouda/issues/794
=> Optimize out a copy in ZMQ recv for local operations

test/gpu/native/threadBlockAndGridPrimitives.compopts
This should resolve the test failure as discussed here:
https://chapel.discourse.group/t/cron-cray-cs-gpu-native/6340
---
Signed-off-by: Andy Stone <stonea@users.noreply.github.com>
=> Forgot to add compopts file for test.

test/ANNOTATIONS.yaml
- array creation comm count improvement
- arkouda array transfer optimizations
=> Add perf annotations for 2021-08-06

compiler/optimizations/deadCodeElimination.cpp
Revert failing changes for index computation in GPU kernel.
Failing changes introduced in PR for: https://github.com/Cray/chapel-private/issues/2314
---
Signed-off-by: Andy Stone <stonea@users.noreply.github.com>
=> Revert failing changes for index computation in GPU kernel.

modules/packages/LinearAlgebra.chpl, test/library/packages/LinearAlgebra/correctness/no-dependencies/sparse-matmatmult-halt.chpl, test/library/packages/LinearAlgebra/correctness/no-dependencies/sparse-matmatmult-halt.good, test/library/packages/LinearAlgebra/correctness/no-dependencies/sparse-matmatmult.chpl, test/library/packages/LinearAlgebra/correctness/no-dependencies/sparse-matmatmult.good
-- Added a utility method which returns the product of a Sparse Matrix and a
Dense Matrix in that particular order respectively. Method returns a
Dense Matrix.
-- Used this method in dot function. So that dot can now support product of
a Sparse Matrix and a Dense Matrix.(in any order)
Signed-off-by: Prashanth Duvvuri <prashanthsedan@gmail.com>
=> Sparse-Dense Matrix Multiplication

test/library/draft/arrow/Arrow.chpl
Fixed issue with returning a value before it was declared in array functions.
Signed-off-by: Shreyas Khandekar <shreyaskhandekar@email.arizona.edu>
=> Resolved retval use before declaration

runtime/src/comm/ofi/comm-ofi.c
Libfabric will return providers that use the touchbar interface, which won't work. Ignore
it in the list of providers.
=> Ignore touchbar interface on a mac

runtime/src/comm/gasnet/comm-gasnet.c
Quiet warnings about having too few pinned regions by setting `GASNET_PINNED_REGIONS_MAX=0.95`. By default gasnet sets this to a fraction of how many pinned regions the hardware supports where that fraction comes from how much memory can be pinned/registered (`GASNET_PHYSMEM_MAX`) divided by the amount of physical memory. On systems with a high amount of memory this can result in artificially lowering the number of regions, so here we just tell gasnet to give us 95% of them.
This also quiets warnings about multi-rail systems. Currently Chapel does not work with multi-rail configurations so until we're able to address this in #18255 quiet warnings that multiple rails are available.
Resolves https://github.com/Cray/chapel-private/issues/2006
=> Quiet some gasnet-ibv warnings

runtime/src/comm/ofi/comm-ofi.c
As of libfabric v1.12.1 providers with FI_SOCKADDR_IB addresses cannot be used as
doing so will cause an internal error in fi_domain. Ignore these addresses until
libfabric is fixed.
=> libfabric doesn't handle FI_SOCKADDR_IB addresses correctly

runtime/src/comm/ofi/comm-ofi.c
The `sockets` provider has been deprecated by libfabric. Only choose `sockets` if it is specified via the `FI_PROVIDER` environment variable, and print a warning message if it is chosen.
=> Deprecate sockets provider

util/devel/test/vagrant/re2-supported.py
=> Follow-up to #18320 to adjust a vagrant test script

doc/rst/usingchapel/prereqs.rst
=> Update docs required Python version to 3.7 for the Chapel test environment

compiler/passes/flattenFunctions.cpp
The updates to flattenFunctions in PR #18341 change the time in which an
argument is added for multiple nested functions referring to outer
variables. In particular, when propagating outer variables to other call
sites, the arguments are added to inner functions even if they are
visible in normal scoping. (Since these functions won't be inner
functions anymore by the time the pass completes). However, I had left
the part of the pass deciding which variables should be added initially
using the old logic that considered whether the variable was visible with
regular scoping. This created problems with numa configurations because
the pass was using now two different definitions for what an "outer"
variable is.
This PR addresses the problems with numa configurations by making the
initial …
=> Use newer strategy instead of isOuterVar

doc/rst/technotes/gpu.rst, doc/rst/technotes/index.rst
Draft for a tech note about our initial GPU support.
=> Gpu tech note

runtime/src/mem/jemalloc/mem-jemalloc.c
Add `CHPL_RT_INTERLEAVE_MEMORY` to control memory interleaving at
runtime and `CHPL_RT_MERGE_SPLIT_CHUNKS` to control whether jemalloc is
allowed to merge and split chunks. These are undocumented since they
aren't meant to be user-facing, they're just here in case we need to
experiment in the field.
=> Add env var overrides for recent memory settings

third-party/qthread/qthread-src/configure
I forgot to commit the generated configure changes in #18272 and only noticed
while testing out the qthreads 1.17 release candidate.
=> Add qthreads configure changes from 18272

CHANGES.md
This is the list of CHANGES for Chapel 1.25.  Thanks to everyone for all their hard work!
=> Chapel 1.25 `CHANGES.md` updates

CONTRIBUTORS.md
Updates to the CONTRIBUTORS file reflecting people who have contributed to the Chapel 1.25 release.
Thanks to everyone who contributed, and also who helped double-check me!
=> Chapel 1.25 contributors file

compiler/main/version_num.h, doc/rst/conf.py, man/confchpl.rst, man/confchpldoc.rst, test/compflags/bradc/printstuff/version.goodstart, test/compflags/bradc/printstuff/versionhelp.sh
=> Updating version numbers to 1.26

compiler/next/Makefile.help, doc/Makefile
Follow-up to PR #18519.
Thanks to @cassella for pointing out the problem
=> Fix problem with setting variable in subshell

test/classes/delete-free/lifetimes/issue-12164.chpl, test/classes/delete-free/lifetimes/issue-12164.future, test/classes/delete-free/lifetimes/issue-12164.good
=> Add a future for issue #12164

test/ANNOTATIONS.yaml
- Arkouda improvements from memory tracking changes
- Arkouda improvements from reducing allocations
- Associative types improvements from hash table optimizations
=> Add perf annotations for 2021-10-14

test/types/records/intents/issue-14996-1.chpl, test/types/records/intents/issue-14996-1.good, test/types/records/intents/issue-14996-2.chpl, test/types/records/intents/issue-14996-2.good, test/types/records/intents/issue-14996-3.chpl, test/types/records/intents/issue-14996-3.good
Adds 3 test cases for the examples in #14996
Test changes only - not reviewed.
=> Add tests for issue 14996

CHANGES.md, CONTRIBUTORS.md
These are the CHANGES for 1.25.1 (so far)
TODO:
=> CHANGES.md updates for 1.25.1

compiler/main/version_num.h, doc/rst/conf.py, doc/rst/usingchapel/QUICKSTART.rst, doc/rst/usingchapel/chplenv.rst, man/confchpl.rst, man/confchpldoc.rst, test/compflags/bradc/printstuff/version.goodstart, test/compflags/bradc/printstuff/versionhelp.sh
=> Changing version numbers for 1.25.1 release

util/pastPerformance/testReleasesPerformance, util/test/perf/perfgraph.js
=> Preliminary perf graphs changes for 1.25.1

runtime/src/comm/ofi/comm-ofi.c
The part of the ofi comm layer's common Active Message support that
dealt with whether or not we block waiting for the AM to finish was
unnecessarily complicated, especially for AM-mediated atomic ops where
we might want to delay that blocking until our memory consistency model
requires the atomic op to be done.  Here, refactor so that the callers
simply tell the common code whether or not to block immediately, and
handle the delayed-blocking case entirely in the AM-mediated AMO code.
This resolves https://github.com/Cray/chapel-private/issues/2817.
=> Simplify blocking-AM management in comm=ofi.

runtime/src/comm/ofi/comm-ofi.c
Allows completion counters to be used for libfabric events instead of completion queues.
Counters can be selectively enabled via environment variables for task transmits,
AM handler transmits, and AM handler receives.
Resolves https://github.com/Cray/chapel-private/issues/2496 and closes https://github.com/Cray/chapel-private/issues/2661.
=> Implement completion counters

test/release/examples/primers/domains.chpl
Embarrassed to say I inserted some cruft while testing that modifying a file updated the doc where I expected it to. See this comment:
https://github.com/chapel-lang/chapel/pull/18829#discussion_r773583001
Thankfully @cassella caught it.
=> remove cruft accidentally added to doc

util/test/checkCopyrights.bash
=> Adding date check for grace period

test/ANNOTATIONS.yaml
This PR adds an annotation for the leaking set tests added in https://github.com/chapel-lang/chapel/pull/18842.
=> Add perf annotation for set leaks

compiler/AST/interfaces.cpp, modules/packages/ArgumentParser.chpl, modules/packages/SortedMap.chpl, modules/packages/UnrolledLinkedList.chpl
=> Fixing some last minute missed dates

compiler/main/driver.cpp
I said I was going to update a comment here: https://github.com/chapel-lang/chapel/issues/18858#issuecomment-1006924197 but I forgot to actually push the changes. Doing it now.
=> Update comment about when to put validation checks in printchplenv.

compiler/optimizations/loopInvariantCodeMotion.cpp
Quiet a compiler warning about `numLoops` being unused in loop invariant
code motion. It's only used when detailed timings are on, so rework the
code so it's only declared/modified when timings are enabled.
Noticed by the gasnet team with some of their clang-13 CI testing.
=> Quiet compiler warning about unused `numLoops` in LICM

modules/packages/Socket.chpl
Follow-up to PR #17960. Trivial and not reviewed.
=> Update copyright in Socket library

test/ANNOTATIONS.yaml
This PR adds an annotation for https://github.com/Bears-R-Us/arkouda/pull/1014, which optimized Parquet file reading with batch reading.
=> Add Parquet batch reading annotation

util/cron/common-arkouda.bash
See https://github.com/Bears-R-Us/arkouda/pull/1027
=> Upgrade Arkouda release testing from 1.25.0 to 1.25.1

test/studies/adventOfCode/2021/bradc/futures/day24-stringContains.bad
Not caught because I hadn't updated to main.
=> Fix .bad file for one of my futures

test/studies/shootout/pidigits/bradc/pidigits-blc.chpl
This is a version of pidigits based on the fastest gcc #6 version and the one rivalq submitted in #18482
=> Add a new version of pidigits based on the gcc#6 version and rivalq's

modules/internal/ChapelDomain.chpl, test/associative/bharshbarg/domains/badSubsetCall.chpl, test/associative/bharshbarg/domains/badSubsetCall.good, test/deprecated/domain-add-etc.chpl, test/expressions/if-expr/if-loop-const.bad, test/studies/adventOfCode/2021/bradc/futures/day24-stringContains.bad
I missed a couple of changes in #19104.
Adding them here.
=> Changes missed in #19104

test/library/draft/Shlex/API/SKIPIF
=> Skip Shlex tests if CHPL_RE2=none

compiler/dyno/README
* fixed things I noticed when reading through
* add guidance about style for file names
Reviewed by @aconsroe-hpe - thanks!
Documentation change only.
=> dyno: update README

util/chplenv/chpl_compiler.py
The problem was noted here: https://github.com/chapel-lang/chapel/pull/18762/files#r783210154.
The previous behavior required imposed `clang` to be the host compiler. But that's arbitrary.
This PR just validates that  `CHPL_TARGET_COMPILER==llvm` and that's it. It gives an error if that's not the case.
=> Fix target compiler validation for the gpu locale model

test/library/standard/Spawn/redirect-stderr-stdout.chpl
Happened to notice this in testing my own changes.
=> Fix a typo in this test from #19366

test/errhandling/parallel/coforall-in-function-throws.chpl, test/errhandling/parallel/coforall-in-function-throws.good
Related to https://github.com/chapel-lang/chapel/pull/19379
=> Add coforall throwing in function test

test/deprecated/regexMatchFields.skipif
Adding skipif for regexMatchFields deprecation test.
=> Adding skipif for regexMatchFields deprecation test

util/cron/test-perf.cray-xc.arkouda.bash, util/cron/test-perf.cray-xc.arkouda.release.bash
In regards to https://github.com/Cray/chapel-private/issues/2932
=> Updating launcher constraints and core per node in arkouda tests

modules/Makefile, modules/packages/Channel.chpl
And fix one error when building the docs.
Follow-up to PR #18168.
Reviewed by @e-kayrakli - thanks!
=> Include Channel package module docs

modules/standard/CTypes.chpl
Follow-up to #19072
Reviewed by @bradcray - thanks!
=> Improve docs for c_void_ptr

compiler/main/version_num.h, doc/rst/conf.py, doc/rst/language/archivedSpecs.rst, doc/rst/usingchapel/QUICKSTART.rst, doc/rst/usingchapel/chplenv.rst, man/confchpl.rst, man/confchpldoc.rst, test/compflags/bradc/printstuff/versionhelp.sh
=> Changing version numbers for 1.26.0 release.

doc/rst/technotes/gpu.rst, doc/rst/technotes/index.rst
Besides some cosmetic changes this PR:
- Makes the title simply "GPU Programming",
- Drops K20, adds A100 as the tested system,
- Drops single-gpu limitation.
Test:
=> Update the GPU technote

CONTRIBUTORS.md
These are the contributors to Chapel 1.26.0.  Thanks to all!
=> Updates to the CONTRIBUTORS file for Chapel 1.26.0

CHANGES.md
These are the Changes for Chapel 1.26.0.  Thanks to everyone
for all the hard work!
=> CHANGES file for Chapel 1.26.0

test/io/ferguson/ctests/qio_bits_test.test.c
It is one of the longer running ones, so focus
on testing larger problem sizes separately from
testing all of the widths.
Test change only, but reviewed by @ronawho.
=> Adjust qio_bits_test.test.c to run faster

util/pastPerformance/testReleasesPerformance, util/test/perf/perfgraph.js
This is similar to the PRs done in previous releases such as:
https://github.com/chapel-lang/chapel/pull/18441.
=> Performance graph updates for 1.26.0

test/studies/shootout/fasta/bradc/fasta-blc.chpl
The goal of this version was to create a more compact code with no significant
loss in performance, as a variation on the submitted fasta5.chpl.  The result drops
its size from 1391 using the gz metric to 1174.
=> New, more bytes-oriented version of fasta

runtime/src/comm/ofi/comm-ofi.c
Use `fi_cntr_wait` to wait for a completion counter to increment instead of spinning on `fi_cntr_read`. This should reduce overhead with the `cxi` provider.
=> Use fi_cntr_wait when waiting on a completion counter

util/dockerfiles/Dockerfile, util/dockerfiles/README.md
Will need to cherry pick this over to the 1.26 Release branch.
=> Updates for 1.26 Dockerfile and associated Readme

test/studies/shootout/reverse-complement/bradc/revcomp-blc.chpl, test/studies/shootout/reverse-complement/bradc/revcomp-blc.execopts
What I was playing with late yesterday...  At yesterday's perf meeting, we noticed that once heroic versions of the CLBG benchmarks were removed from the mix, our code compactness was not as good as we'd like, so I started looking at revcomp, as one of our outliers.
=> Compact revcomp

test/mason/masonInit/masonInitModifyToml.good, test/mason/masonInit/masonInitTest4.good, tools/mason/MasonInit.chpl
This PR fixes a couple of typos in mason and updates the affected tests.
=> Fix some typos in mason

test/io/ferguson/ctests/qio_pwriteread.test.c, test/users/ferguson/err_tmp.chpl
I regret to say that I'd forgotten that I hadn't run a full test
on this after developing it due to too much time passing between
writing the PR and merging it.  Sorry to have missed these.
=> Update err_t usage in these two tests

util/devel/test/vagrant/current/archlinux-archlinux/Vagrantfile, util/devel/test/vagrant/current/ubuntu-impish64-homebrew/Vagrantfile, util/devel/test/vagrant/provision-scripts/pacman-deps.sh
I created this VM in order to verify PR #19785.
Also increases the memory and CPUs for the Homebrew vm since
we sometimes use that to build Homebrew from source.
=> Add vagrant configuration for Arch Linux

test/modules/shadowing/fn-shadows-private-import.chpl, test/modules/shadowing/fn-shadows-private-import.good, test/modules/shadowing/fn-shadows-public-import.chpl, test/modules/shadowing/fn-shadows-public-import.good, test/modules/shadowing/var-shadows-private-import.chpl, test/modules/shadowing/var-shadows-private-import.good, test/modules/shadowing/var-shadows-public-import.chpl, test/modules/shadowing/var-shadows-public-import.good
PR #19306 addressed issue #19160 but I didn't see tests for two cases
mentioned in the issue. Also added a comment to two other tests related
to the issue with the issue number.
=> Add tests for issue 19160

util/cron/test-perf.chapcs.playground.bash
Test the performance of LLVM-14.
=> Set the performance playground script to test LLVM-14

test/execflags/gbt/dry_run.execopts
=> Removed left-over debug code.

test/library/packages/Collection/insertArrayInBag1.bad, test/library/packages/Collection/insertArrayInBag1.chpl, test/library/packages/Collection/insertArrayInBag1.future, test/library/packages/Collection/insertArrayInBag2.bad, test/library/packages/Collection/insertArrayInBag2.chpl, test/library/packages/Collection/insertArrayInBag2.future
These two codes were from #19859.  It sounds like the issue is a little more intrinsic than I can resolve, so file the futures in case we fix them in the future
Checked a fresh checkout of the tests
=> Adds futures to track bugs filed against DistributedBag

test/types/tuple/errors/indexHetTuple.good, test/types/tuple/errors/indexHetTuple.prediff
To address failure seen here:
https://chapel.discourse.group/t/cron-fast/12791
=> Prediff out line nums in error message for indexHetTuple test

test/ANNOTATIONS.yaml
- compilation time improvements and regressions
- arkouda dataframe and sort optimizations
=> Add perf annotations for 2022-05-26

util/cron/common-arkouda.bash
Fixing error introduced in: https://github.com/chapel-lang/chapel/pull/19698
=> Fix variable set check in Arkouda testing script

doc/rst/tools/mason/mason.rst
Signed-off-by: Luca Ferranti <49938764+lucaferranti@users.noreply.github.com>
This PR updates the documentation for installing `mason` as discussed in #19910
=> updated mason installation instructions

test/ANNOTATIONS.yaml
- compilation time regression fixes
- list regression
=> Add perf annotations for 2022-06-02

test/functions/vass/declaredGenericReturnTuple.bad
Update .bad file with new output now that readWriteThis is deprecated
=> Fix tuple future after readWriteThis deprecation

runtime/src/launch/slurm-srun/launch-slurm-srun.c
In #13667, we started throwing `--mem=0` for the slurm-srun launcher to
get access to all memory on each node. This is still the default we
want, but a secondary use for `--mem` is to request the high memory
nodes (e.g. to select 512G nodes in a partition that has mixed 256/512G
ones.) Update the code to allow overriding with `CHPL_LAUNCHER_MEM`.
=> Make slurm-srun `--mem` overridable

doc/rst/language/spec/modules.rst, doc/rst/language/spec/procedures.rst
=> Add details to spec about public use and method shadowing

doc/rst/technotes/gpu.rst
- Use here.gpus[] instead of here.getChild().
- Add section on multilocale support
=> Updates to gpu tech note

CONTRIBUTORS.md
Refresh the contributors lists for Chapel 1.27.  Thanks to all who contributed to
this release!
=> Contributors for Chapel 1.27

compiler/main/version_num.h, doc/rst/conf.py, doc/rst/language/archivedSpecs.rst, doc/rst/usingchapel/QUICKSTART.rst, doc/rst/usingchapel/chplenv.rst, man/confchpl.rst, man/confchpldoc.rst, test/compflags/bradc/printstuff/versionhelp.sh
=> Removing pre-release for the 1.27.0 release.

CHANGES.md
This adds the list of CHANGES that will be in Chapel 1.27.  Thanks for
all the good work during this release cycle!
=> CHANGES for Chapel 1.27

util/pastPerformance/testReleasesPerformance, util/test/perf/perfgraph.js
This is similar to the PRs done in previous releases such as:
https://github.com/chapel-lang/chapel/pull/18441 and #19563. 
=> Performance graph updates for 1.27.0

doc/util/versionButton.php
This updates the Chapel documentation version button/menu to
reflect today's 1.27.0 release
=> Update version button for 1.27.0 release

util/cron/common-arkouda.bash
=> Upgrade Arkouda release testing from 1.25.1 to 1.26.0

test/gpu/native/studies/shoc/COMPOPTS, test/gpu/native/studies/shoc/EXECOPTS, test/gpu/native/studies/shoc/SKIPIF, test/gpu/native/studies/shoc/result.chpl, test/gpu/native/studies/shoc/triad.chpl, test/gpu/native/studies/shoc/triad.good, test/gpu/native/studies/shoc/triadalt1.chpl, test/gpu/native/studies/shoc/triadalt1.good, test/gpu/native/studies/shoc/triadalt2.chpl, test/gpu/native/studies/shoc/triadalt2.good, test/gpu/native/studies/shoc/triadchpl.chpl, test/gpu/native/studies/shoc/triadchpl.good
Tests for Triad: the first Benchmark from the SHOC repository.
See more about the Triad Benchmark [here](https://github.hpe.com/hpe/shoc-chapel/tree/main/Triad)
=> Creating SHOC Tests for Triad

util/dockerfiles/Dockerfile, util/dockerfiles/README.md
Updates to the dockerfile and README for the 1.27.0 release.
=> 1.27.0 Docker updates

util/cron/common-arkouda.bash
=> Upgrade Arkouda release testing from 1.26.0 to 1.27.0

test/ANNOTATIONS.yaml
- block dist scan optimizations
- k-nucleotide regression
- arkouda upgrades
=> Add perf annotations for 2022-07-07

test/gpu/native/studies/shoc/PERFCOMPOPTS, test/gpu/native/studies/shoc/PERFEXECOPTS, test/gpu/native/studies/shoc/bandwidth.graph, test/gpu/native/studies/shoc/bandwidth2.graph, test/gpu/native/studies/shoc/kernel.graph, test/gpu/native/studies/shoc/kernel2.graph, test/gpu/native/studies/shoc/result.chpl, test/gpu/native/studies/shoc/triad.chpl, test/gpu/native/studies/shoc/triad.graph, test/gpu/native/studies/shoc/triad.perfkeys, test/gpu/native/studies/shoc/triad2.graph, test/gpu/native/studies/shoc/triadalt1.chpl, test/gpu/native/studies/shoc/triadalt1.perfkeys, test/gpu/native/studies/shoc/triadalt2.chpl, test/gpu/native/studies/shoc/triadalt2.perfkeys, test/gpu/native/studies/shoc/triadchpl.chpl, test/gpu/native/studies/shoc/triadchpl.perfkeys
Creating `.perfkeys` and `.graph` files for all Triad tests but not adding it to `GRAPHFILES` since we plan to have a different `GRAPHFILES` file for GPU tests.
Tests pass on Horizon and Graphs look pretty nice.
=> Adding Performance Tests and Graphs for Triad

util/cron/test-perf.cray-cs-hdr.gpu.bash
We would like to start gathering performance data for GPU tests
=> Add test configuration for gpu perf tests

modules/internal/localeModels/gpu/LocaleModel.chpl, test/gpu/native/GRAPHFILES, test/gpu/native/localeName.chpl, test/gpu/native/localeName.good, util/cron/test-perf.cray-cs-hdr.gpu.bash
Other parts of this effort:
- https://github.com/chapel-lang/chapel/pull/20226
- https://github.com/chapel-lang/chapel/pull/20225 and
- https://github.hpe.com/hpe/hpc-chapel-ci-config/pull/919
This PR has small fixes for issues I noticed while trying to get the test
running, and also a way to use a custom GRAPHFILES for gpu testing instead of
using a perflabel.
New performance testing job ran successfully on this branch.
=> Small fixes to get GPU testing working properly

.gitignore, modules/standard/OS.chpl, modules/standard/Path.chpl, modules/standard/Subprocess.chpl, test/execflags/jhh/job_name.chpl, test/execflags/jhh/job_prefix.chpl, test/library/packages/.gitignore, test/library/packages/HDF5/Hdf5PathHelp.chpl, test/library/standard/OS/posix_signals.chpl
There were a few small issues with: https://github.com/chapel-lang/chapel/pull/20126 that this PR addresses.
- Made test-related gitignore local to the relevant directory
- Fixed some use statements/extern delecrations 
- Corrected a POSIX-signal uniqueness test
=> Some small updates to recent Sys Deprecation PR

util/build_configs/cray-internal/setenv-xc-x86_64.bash
Update intel gen compiler version.
=> Update the intel module version for cray-module nightly

test/gpu/native/dataPingPong.good
Accidentally updated in this PR:
https://github.com/chapel-lang/chapel/pull/20412
=> Revert dataPingPong test I accidentally updated

test/interop/C/cmakelists/targetToChpl/CMakeLists.txt, test/interop/C/cmakelists/targetToLibToChpl/CMakeLists.txt
Signed-off-by: Brandon Neth <brandon.neth@hpe.com>
=> fix for linux32 failure; it was the cmake version

test/classes/ferguson/generic-field/generic-field-unmanaged-borrowed.chpl
=> Fix the test generic-field-unmanaged-borrowed

doc/rst/usingchapel/prereqs.rst, util/devel/test/singularity/current/almalinux-8-nollvm/singularity.def, util/devel/test/singularity/current/almalinux-9.0-nollvm/singularity.def, util/devel/test/singularity/current/alpine-3.15-nollvm/singularity.def, util/devel/test/singularity/current/alpine-3.15/singularity.def, util/devel/test/singularity/current/alpine-nollvm/singularity.def, util/devel/test/singularity/current/amazonlinux-2022-nollvm/singularity.def, util/devel/test/singularity/current/arch-nollvm/singularity.def, util/devel/test/singularity/current/arch/singularity.def, util/devel/test/singularity/current/debian-bullseye-nollvm/singularity.def, util/devel/test/singularity/current/debian-buster-nollvm/singularity.def, util/devel/test/singularity/current/fedora-34-nollvm/singularity.def, util/devel/test/singularity/current/fedora-35-nollvm/singularity.def, util/devel/test/singularity/current/fedora-36-nollvm/singularity.def, util/devel/test/singularity/current/opensuse-leap-15.3-nollvm/singularity.def, util/devel/test/singularity/current/opensuse-leap-15.3/singularity.def, util/devel/test/singularity/current/opensuse-leap-15.4-nollvm/singularity.def, util/devel/test/singularity/current/rockylinux-8-nollvm/singularity.def, util/devel/test/singularity/current/rockylinux-9.0-nollvm/singularity.def, util/devel/test/singularity/current/ubuntu-focal-nollvm/singularity.def, util/devel/test/singularity/current/ubuntu-jammy-nollvm/singularity.def, util/devel/test/singularity/current/ubuntu-kinetic-nollvm/singularity.def, util/devel/test/singularity/extract-docs.py, util/devel/test/vagrant/README-distro-timelines.txt, util/devel/test/vagrant/provision-scripts/apk-deps.sh, util/devel/test/vagrant/provision-scripts/apk-llvm.sh, util/devel/test/vagrant/provision-scripts/pacman-llvm.sh, util/devel/test/vagrant/provision-scripts/zypper-deps.sh, util/devel/test/vagrant/provision-scripts/zypper-llvm.sh
This PR updates prereqs.rst to use a table of commands to install the dependencies that matches the commands that we test. It makes some minor adjustments to singularity testing and adds a script `extract-docs.py` that prints out this table.
Reviewed by @bhavanijayakumaran and @lydia-duncan - thanks!
=> Update prereqs.rst dependency installation & update singularity

doc/rst/language/spec/conversions.rst, doc/rst/language/spec/expressions.rst, doc/rst/language/spec/procedures.rst
Update docs for PR #20528
* new implicit conversions from any width int to any width real
* new implicit conversions from int to uint
* clarify rules about param implicit conversions
* describe improved disambiguation rules
=> Update docs to describe new implicit conversions and disambiguation

runtime/src/comm/ugni/comm-ugni.c
Previously, doing an `exit(0)` would hang under ugni on slurm systems.
This is because only locale/process 0 would actually stop executing and
slurm doesn't do anything to kill the other locales/processes. This
updates ugni to make more of an effort to shutdown remote nodes when an
uncoordinated exit is initiated. Specifically, we'll unblock the main
process waiting on the shutdown condvar and stop the polling thread on
each node. This leads to all nodes exiting if there's no outstanding
comm, but if some task is still waiting for comm to complete, we don't
do anything cancel it.
So this improves the simple case of `exit(0)` being called from locale 0
when no remote comm is occurring, but can still hang in more complicated
situations. At the moment, I think that's probably sufficient and …
=> Allow `exit(0)` to work with ugni

test/ANNOTATIONS.yaml
- compile speed improvement
- arkouda "regression" (unrelated work exposing false-sharing)
=> Add perf annotations for 2022-09-01

doc/rst/language/spec/classes.rst, doc/rst/language/spec/methods.rst, doc/rst/language/spec/procedures.rst
Updates the spec for changes in PR #19505.
=> language specification updates for parenless methods

doc/rst/technotes/gpu.rst
This PR updates the GPU tech note for Chapel 1.28.
Specific changes I've made include:
- Adding an "overview" paragraph to the intro listing out the various sections in the note. I also add a table of contents.  The note isn't huge but it's getting big enough that it seems worthwhile to have some of organization (and things will continue to grow from release-to-release).
- Reorganize the sections a little (put the overview and example upfront).
- Move some info about limitations that was previously in our intro into a separate "Requirements and Limitations" section and add some additional information there.
- Add new subsections on "Diagnostics and Utilities" and "Memory Strategies".
Some additional notes for reviewers:
- There's one place I need to update to cross reference to the new …
=> Update GPU tech note for Chapel 1.28

util/packaging/homebrew/chapel-main.rb
=> Simplified LLVM Dependencies across platforms.

CONTRIBUTORS.md
Update the contributors list for Chapel 1.28.  Thanks to all who
contributed to this release!
=> Contributors updates for 1.28

CHANGES.md
Here is the "complete" list of changes for Chapel 1.28.  Thanks to everyone
for their contributions!  (to the release, to this file)
=> CHANGES.md for 1.28

util/dockerfiles/Dockerfile, util/dockerfiles/README.md, util/dockerfiles/entrypoint.sh
Update Dockerfile for 1.28.0 version.
Added an entrypoint.sh script to set the PATH inside container based on the underlying architecture.  
https://github.com/chapel-lang/chapel/issues/19151
=> Docker file changes to accommodate arm arch 

doc/rst/developer/bestPractices/StandardModuleStyle.rst
Slight amendment to PR: https://github.com/chapel-lang/chapel/pull/20699
Adds a statement explaining that we intend to update capitalization rules as more exceptions accumulate.
=> Update description of capitalization rules exceptions

compiler/resolution/resolveFunction.cpp, doc/rst/developer/bestPractices/buildingdocs.rst, doc/rst/meta/compiler-internals-doxygen/base.rst, modules/internal/DefaultRectangular.chpl, modules/packages/SortedMap.chpl, test/classes/delete-free/lifetimes/tuple-vararg-in-lt-clause.chpl, test/classes/figueroa/BogusDestructors.chpl, test/classes/initializers/compilerGenerated/fieldDefaultGlobalArray.chpl, test/classes/initializers/compilerGenerated/fieldDefaultGlobalArrayModified.chpl, test/domains/bradc/domainEquality.future, test/domains/vass/domain-arg-query-expr.future, test/io/readLine/readLine.chpl, test/parallel/forall/vass/reciter/forall-reciter-works.chpl, test/reductions/vass/reductions-today.chpl, test/statements/vass/index-variable-var.future, util/devel/check_paths
Update assorted files that were referring to old or incorrect file paths.
=> Repair dangling file references

.github/workflows/email.yml
Fixed the check in the workflow to run the email flow when the PR is merged.
=> Follow_up PR for #20794

util/devel/chplspell, util/devel/chplspell-dictionary.fileids.json
chplspell and dictionary updates for compiler/dyno -> frontend rename
=> chplspell and dictionary updates for compiler/dyno -> frontend rename

man/chpldoc.rst
Follow-up to PR #20835 to fix `test/man`.
=> Remove --license from chpldoc man page

.github/workflows/email.yml
Add more details to the log message.
=> Format log

.github/workflows/email.yml
Addressing @daviditen 's comment to add PR number to email subject.
=> Add PR number to the subject

.github/workflows/email.yml
For better readability of email body reorder links.
=> Rorder Links for better readability

.github/workflows/email.yml
Add a missing single quote around the LOG env.
=> Fix- unexpected EOF while looking for matching )

.github/workflows/email.yml
=> Remove the formatting in email subject.

runtime/src/chpl-init.c, runtime/src/chpl-launcher-common.c, runtime/src/chpl-string-support.c, runtime/src/chplcast.c, runtime/src/chplmemtrack.c, runtime/src/config.c, runtime/src/launch/aprun/aprun-utils.c, runtime/src/launch/dummy/launch-dummy.c, runtime/src/launch/lsf-gasnetrun_ibv/launch-lsf-gasnetrun_ibv.c, runtime/src/launch/mpirun/launch-mpirun.c, runtime/src/launch/pbs-aprun/aprun-utils.c, runtime/src/launch/pbs-aprun/launch-pbs-aprun.c, runtime/src/launch/pbs-gasnetrun_ibv/launch-pbs-gasnetrun_ibv.c, runtime/src/launch/slurm-gasnetrun_common/slurm-gasnetrun_common.h, runtime/src/launch/slurm-srun/launch-slurm-srun.c, runtime/src/qio/qio.c, runtime/src/tasks/fifo/tasks-fifo.c, runtime/src/tasks/qthreads/tasks-qthreads.c, runtime/src/threads/pthreads/threads-pthreads.c
Replace `sprintf` with `snprintf` in the runtime
Resolves https://github.com/Cray/chapel-private/issues/3996.
=> Replace sprintf with snprintf in the runtime

.github/workflows/email.yml
Replace .\r\nParse the merge log replace…  feeds with html line breaks.
=> Email body was not honoring linefeeds 

modules/standard/IO.chpl, test/library/standard/IO/open/.gitignore, test/library/standard/IO/open/checkFileNotFound.chpl, test/library/standard/IO/open/checkFileNotFound.good, test/library/standard/IO/open/checkNotADir.chpl, test/library/standard/IO/open/checkNotADir.good, test/library/standard/IO/open/checkPermissions.chpl, test/library/standard/IO/open/checkPermissions.cleanfiles, test/library/standard/IO/open/checkPermissions.good, test/library/standard/IO/openreader/.gitignore, test/library/standard/IO/openreader/checkFileNotFound.chpl, test/library/standard/IO/openreader/checkFileNotFound.good, test/library/standard/IO/openreader/checkNotADir.chpl, test/library/standard/IO/openreader/checkNotADir.good, test/library/standard/IO/openreader/checkPermissions.chpl, test/library/standard/IO/openreader/checkPermissions.cleanfiles, test/library/standard/IO/openreader/checkPermissions.good, test/library/standard/IO/openreader/checkPermissions.preexec, test/library/standard/IO/openwriter/.gitignore, test/library/standard/IO/openwriter/checkFileNotFound.chpl, test/library/standard/IO/openwriter/checkFileNotFound.good, test/library/standard/IO/openwriter/checkNotADir.chpl, test/library/standard/IO/openwriter/checkNotADir.good, test/library/standard/IO/openwriter/checkPermissions.chpl, test/library/standard/IO/openwriter/checkPermissions.cleanfiles, test/library/standard/IO/openwriter/checkPermissions.good
Resolves #20139 
These errors were already being thrown by the implementation when
appropriate.  By documenting them more specifically instead of
just the general SystemError case, users will be able to write code
that is aware of these errors and can respond to them on the fly.
For instance, if a FileNotFoundError is encountered, the program can
potentially create missing parts of the path, create the file ahead of
time if that is the problem, or try to use a different mode that doesn't
require the file to already exist.
Add tests to lock in that those particular errors were thrown (no
modifications necessary to get them to work).
=> Add documentation about thrown errors to some IO functions

doc/rst/language/spec/generics.rst
Follow-up to #20755
Updates a spec section I just noticed is now out-of-date.
=> Update a spec section for disambiguation changes

test/gpu/native/jacobi/flags-warn-unstable.good
Needed test update after gpu_mods_warn_unstable PR (#21098).
=> Fix failing test

test/ANNOTATIONS.yaml
- shared objection allocation regression
- arkouda SymEntry optimizations
- arkouda encode/decode improvements
=> Add perf annotations for 2022-12-02

test/studies/adventOfCode/2022/day02/bradc/day02.chpl, test/studies/adventOfCode/2022/day02/bradc/day02a.chpl
Lots of good suggestions here.  Where were you two at midnight last night?  :D
=> Update my day 2 codes based on feedback from Daniel and Jeremiah

doc/rst/developer/bestPractices/buildingdocs.rst
buildingdocs.rst: Update table description to match table layout
Also wordsmith a bit.
=> buildingdocs.rst: Update table description to match table layout

test/studies/adventOfCode/2022/day05/bradc/day05.chpl
Oops, missed one minor commit with a variable renaming in this test.
=> Update variable name to match blog

doc/rst/technotes/gpu.rst, modules/internal/ChapelGpuSupport.chpl, modules/standard/GPU.chpl
Add additional examples to tech report (links to various tests).
Also add doc for gpuClock function since we mention it in CHANGES.MD
=> Add additional examples to tech report.

doc/rst/technotes/gpu.rst
This PR adds tech notes for AMD GPU (mostly describing the state
of things, as well as giving basic instructions for trying it out).
=> Tweak tech notes to add AMD GPU support.

doc/rst/technotes/firstClassFns.rst
Add a few sections to the FCF technote describing new features
Add some new sections describing prototype features added for this
release. Adjust the opening paragraph to indicate the new layout of
the content, and indicate that new features are not yet stable.
Reviewed by @arezaii, @DanilaFe. Thanks!
=> Add a few sections to the FCF technote describing new features

compiler/main/version_num.h, man/confchpl.rst, man/confchpldoc.rst, test/chpldoc/compflags/combinations/versionhelp-chpldoc.sh, test/compflags/bradc/printstuff/version.goodstart, test/compflags/bradc/printstuff/versionhelp.sh
https://github.com/Cray/chapel-private/issues/4055
=> Update chapel version to 1.30

util/pastPerformance/testReleasesPerformance, util/test/perf/perfgraph.js
modified performance graph files to include the new release date and version data.
[Performance Graph changes
](https://github.com/Cray/chapel-private/issues/4055)Signed-off-by: bhavanijayakumaran <82669529+bhavanijayakumaran@users.noreply.github.com>
=> Update performance graph for release 1.29

test/functions/iterators/errors/mistakenIteratorShape.bad, test/functions/iterators/errors/mistakenIteratorShape.chpl, test/functions/iterators/errors/mistakenIteratorShape.future, test/functions/iterators/errors/mistakenIteratorShape.good
=> Add future for an internal error in iterator shape code

test/studies/shootout/submitted/regexredux2.chpl, test/studies/shootout/submitted/regexredux2.good
https://github.com/chapel-lang/chapel/pull/21201 accidentally made changes to the submitted version of the regexredux2 shootout test.
This PR reverts that change and updates the `.good` file instead.
Signed-off-by: Jeremiah Corrado <jeremiah.corrado@hpe.com>
=> Revert changes to submitted regexredux test

test/ANNOTATIONS.yaml, util/test/check_annotations.py
- range iteration changes
- multi-locale affinity regressions
- gpu kernel launch speedups
- Arkouda upgrade
=> Add perf annotations for 2023-01-20

test/parallel/taskPar/cassella/too-many-intents.future
Add an issue number to this old future.
=> Add issue number to too-many-intents future

test/functions/iterators/bugs/raii-iterator-break.chpl, test/functions/iterators/bugs/raii-iterator-break.good
This PR adds the test case from issue #6912 which is now working.
=> Add test case from issue #6912

.gitignore
Add tarfiles generated by home-brew and docker tests to .gitignore
=> add tarfiles generated by the home-brew test to .gitignore

util/cron/docker-chapel.bash, util/cron/docker-gasnet.bash, util/cron/publish-docker-images.bash, util/cron/test-docker.bash
Added scripts to build, test and publish images to docker repositories.
This will address
https://github.com/Cray/chapel-private/issues/4277
https://github.com/Cray/chapel-private/issues/4280
=> Automate docker test run to test  and publish images

test/gpu/native/array_on_device/studies.skipif, test/gpu/native/array_on_device/studies/shoc/result.notest
Add missing skipif files for array_on_device tests.
I should have added these in PR: #21459
=> Add missing skipif files for array_on_device tests

util/cron/publish-docker-images.bash
As part of  #4278. Added code to login to docker before publishing the images.
=> Added code to login to docker

test/library/standard/FileSystem/lydia/sameFile/closeCopy.compopts
I added a .compopts file for this test, but missed doing 'git add' on it. Actually add it now.
=> Add a .compopts file for the closeCopy test.

.github/workflows/email.yml
Get the author name from github.event.pull_request.head.user.login
Put back the diff=$(git --no-pager diff --name-status --diff-filter=ACDMRT ${{github.event.pull_request.base.sha}} ${{github.sha}}) to get the files changed.
=> Diff author

Dockerfile, util/cron/docker.bash
2. Check for docker install and do not fail just print the message, startdocker will start the docker daemon if docker is not running..
=> Add ENV proxy in Dockerfile

util/cron/test-perf.chapcs.playground.bash
Evaluating possible performance impact for Option 2 from issue #21001.
=> Update perf playground to try issue-21001-option-2

test/io/formatters/Json.chpl
This fixes a problem from the combination of PRs #21410 and #21586 (which were each tested independently before merge).
Reviewed by @bmcdonald3 - thanks!
=> Fix a warning in the Json formatter

.github/workflows/CI.yml, .github/workflows/email.yml
This will address Adding a CHPL_LLVM=none Github Action #4220](https://github.com/cray/chapel-private/issues/4220)
This PR also contains minor changes to add new lines in the email body in email workflow to improve readability.
=> test CHPL_LLVM=none in git CI

frontend/lib/parsing/parsing-queries.cpp, frontend/test/resolution/testDeprecationUnstable.cpp
Some code I added to support deprecation/unstable warnings in dyno
was written hastily and had a bug which ended up causing warnings to
be skipped for all formals. It was intended to only skip warnings for
the "this" receiver formal.
Fix the bug and add a unit test.
=> dyno: Fix a bug that skipped warnings for any formal, not just receivers

modules/standard/IO.chpl, test/deprecated/IO/ioChar.chpl, test/deprecated/IO/ioChar.good, test/io/ferguson/io_test.chpl, test/io/jade/readByte-throws.chpl, test/io/jade/readByte-throws.good, test/io/jade/readCodepoint-throws.chpl, test/io/jade/readCodepoint-throws.good, test/io/jade/readWriteByte.chpl, test/io/jade/readWriteCodepoint.chpl, test/unicode/write_read_euro.chpl, test/unicode/write_read_smile.chpl, test/unicode/write_read_smile.good
Based on discussion in #20257, deprecated ioChar and implemented a replacement functions read/writeCodepoint. The same discussion also added read/writeByte, that is also implemented here.
- Deprecates ioChar
- Adds the following functions for codepoints to replace ioChar
```chapel
proc fileWriter.writeCodepoint(codepoint: int) throws
proc fileReader.readCodepoint(): int throws
proc fileReader.readCodepoint(ref codepoint: int): bool throws
```
- Adds the following functions to read/write single bytes
```chapel
proc fileWriter.writeByte(byte: uint(8)) throws
proc fileReader.readByte(): uint(8) throws
proc fileReader.readByte(ref codepoint: int): bool throws
```
- update all uses of ioChar to read/writeCodepoints in modules and tests
- Move io_test case for ioChar to its own file, replace …
=> Deprecate ioChar in favor of read/writeCodepoint and read/writeByte

util/chplenv/printchplbuilds.py
A component in the build path consists of an optional prefix separated from the value by a hyphen. The value itself may contain hyphens, and, in the case of `CHPL_COMM`, may end in an optional "-debug" suffix. These various permutations should now be parsed correctly.
=> Improve component parsing in printchplbuilds.py

util/test/send_email.py
Removing the changes until the changes are tests in all the systems.
=> Revert the changes to add proxy for mac

.github/workflows/email.yml
To address: 
https://github.com/Cray/chapel-private/issues/4459
Fix: 
Add --merge-base and replace merge sha with head.sha to calculate the diff.
=> Replace merge sha with head.sha to calculate diff

test/functions/iterators/vass/yield-by-value.chpl, test/functions/iterators/vass/yield-by-value.good
Add a test of the behavior change in #21789: yielding tuples by value.
Test addition only, not reviewed.
=> Test yielding tuples by value for #21789

doc/rst/technotes/index.rst, doc/rst/technotes/throwingInit.rst
Resolves Cray/chapel-private#4453
Indicates what is currently supported with example codes
(though I don't think the example codes are run today, due
to not being in the spec - I have verified that they build
as written today).  Indicate future support plans.
Made the docs locally
=> Add a technote about throwing initializers

CHANGES.md
List of CHANGES incorporated into Chapel 1.30.
=> CHANGES entries for Chapel 1.30

CMakeLists.txt, doc/rst/conf.py, man/confchpl.rst, man/confchpldoc.rst, test/chpldoc/compflags/combinations/versionhelp-chpldoc.sh, test/compflags/bradc/printstuff/version.goodstart, test/compflags/bradc/printstuff/versionhelp.sh
Update version number in main to 1.31 pre-release
PRs that updated version number for 1.30 release
https://github.com/bhavanijayakumaran/chapel/commit/710ac454c37229e7941423f226cd904793551f7c
https://github.com/bhavanijayakumaran/chapel/commit/5e3dc073ec669eedf2fb59ece0c7c0ecd086d6a3
=> update version numbers to chapel 1.31 pre release

test/ANNOTATIONS.yaml
- 2D array regression fix
- compilation time improvements
- parallel array.find
- old annotations that we missed adding to arkouda
=> Add perf annotations for 2023-03-16

util/cron/common-arkouda.bash
=> Upgrade Arkouda release testing from 1.29 to 1.30

test/ANNOTATIONS.yaml
- compilation regression from tuple yielding
=> Add perf annotations for 2023-03-23

util/packaging/docker/test/brew_install.bash
Issue: #21937 Homebrew test not failing when there were errors in the brew audit tes-bot steps run inside the container.
=>  Fix the if conditions in brew_install.sh

test/ANNOTATIONS.yaml
- Arkouda bigint groupby improvement from bigint aggregation
=> Add perf annotations for 2023-03-30

test/ANNOTATIONS.yaml
Adds missing annotations for some GPU performance changes.
=> Add some missing GPU annotations

doc/rst/meta/compiler-internals-doxygen/index.rst, doc/rst/meta/compiler-internals-doxygen/queries-impl.rst
As I'm digging around with the query system and tracking errors, I thought it might be useful to document some of the things I'm finding useful to know.
Documentation only, no paratests necessary.
=> Document some of my query system implementation findings

test/ANNOTATIONS.yaml
- compilation time improvement from FCF `writeThis` generation
=> Add perf annotations for 2023-05-11

util/chplenv/chpl_llvm.py
On a system using Spack for the Chapel dependencies, a bundled build of LLVM 15 (see PR #22316) found libzstd (through Spack) but the result of running `llvm-config` to find the link flags included `-lzstd` but missed the needed `-L` argument for the path to the library installed by Spack. As a workaround for that issue, update the `chpl_llvm.py` script to replace `-lzstd` with a the result of `pkg-config --libs --static libzstd` if that runs successfully.
=> Fix problem with spack-provided libzstd and LLVM 15

util/cron/test-perf.chapcs.playground.bash
Test LLVM 15 in the perf playground.
=> Update the perf playground to test LLVM 15 (bundled)

util/cron/test-linux64-llvm14.bash, util/cron/test-linux64-llvm15.bash
As part of the llvm 15 upgrade added 2 new tests.
Issue: https://github.com/Cray/chapel-private/issues/4814
=> Added new tests to test llvm 14 and llvm 15 system configurations

util/cron/nightly, util/cron/syncPerfGraphs.py
Removed the modified python script and have commented out the rsync calls in the nightly perl script.
=> Modifying nightly script to disable graph uploads

util/chplenv/chpl_llvm.py
Follow-up to PR #22454 in order to fix problems using a system install of LLVM on Alpine linux, where `clang` works OK but we don't have an absolute path to it, so queries like `os.path.exists(clang_command)` were failing. This PR adds some helper functions to avoid repeatedly running `clang --version` or `llvm-config --version`.
=> Further improve checks for clang version in chpl_llvm.py

test/studies/comd/elegant/arrayOfStructs/util/AccumStencilDist.chpl
I overlooked the CoMD test failure in #22486, so fixing it here, by updating its AccumStencilDist to use `strides` instead of `stridable`.
Merging it without a review in order to reduce nightly testing noise and because these are the same changes that #22486 applied to the standard StencilDist. Post-merge review is welcome.
=> Fix test failure in CoMD

modules/packages/HDF5Helper/hdf5_helper.h
=> Replace unsigned long long with hsize_t in pointer casts in hdf5_helper.h

util/cron/test-perf.chapcs.playground.bash
This PR adjusts the perf playground to test PR #22498.
=> Adjust perf playground to test not emitting llvm.lifetime.start

test/classes/casts/generated-cast-tests/argumentCoerce_Const/.gitignore, test/classes/casts/generated-cast-tests/argumentCoerce_ConstIn/.gitignore, test/classes/casts/generated-cast-tests/argumentCoerce_ConstRef/.gitignore, test/classes/casts/generated-cast-tests/argumentCoerce_In/.gitignore, test/classes/casts/generated-cast-tests/argumentCoerce_Inout/.gitignore, test/classes/casts/generated-cast-tests/argumentCoerce_Out/.gitignore, test/classes/casts/generated-cast-tests/argumentCoerce_Ref/.gitignore, test/classes/casts/generated-cast-tests/coerceAssign/.gitignore, test/classes/casts/generated-cast-tests/coerceInitAssign/.gitignore, test/classes/casts/generated-cast-tests/explicitCasts/.gitignore, test/classes/casts/generated-cast-tests/generate-tests.chpl
Script added in #22356 generates many files which should not be checked into source control, this PR adds a gitignore specific to those directories to prevent this
Also switch `list.append` to `list.pushBack`
---
[not reviewed - trivial]
=> Add gitignore for generated tests

util/cron/syncPerfGraphs.py
The previous iteration had an assumption that all systems can copy files to the chapelu user space.   The performancetests run on systems that can ssh to chapcs11, and this new version will properly synchronize graphs to the internal site.
=> Updates to the syncPerfGraphs script to handle Osprey

modules/standard/AutoMath.chpl, modules/standard/Math.chpl
Resolves Cray/chapel-private#4953
This will make it easier to find the functions within the file and will make it easier to see all the related functions when they are spread out within the file
Double checked the built documentation and their links
=> Add documentation categories to AutoMath and Math

doc/rst/technotes/gpu.rst
This PR in particular includes two changes:
* Remove mention of multilocale limitation for AMD GPUs; AMd now works in multi-locale mode.
* Add a section for device-to-device / peer-to-peer communication of GPUs.
=> Update GPU tech note for the release

modules/internal/ChapelBase.chpl
=> Fix a typo

CONTRIBUTORS.md
Thanks to everyone who contributed to Chapel 1.31, including first-time contributor @twesterhout!
=> CONTRIBUTORS file for Chapel 1.31

CMakeLists.txt, man/confchpl.rst, man/confchpldoc.rst, test/chpldoc/compflags/combinations/versionhelp-chpldoc.sh, test/compflags/bradc/printstuff/version.goodstart, test/compflags/bradc/printstuff/versionhelp.sh
Update chapel version to 1.32 pre-release
1.31 pre-release was removed as part of this PR https://github.com/chapel-lang/chapel/commit/c323a3fbffacf3aaf230b526749927b6a585472e
=> update chapel version to 1.32

util/test/sub_test.py
PR #3928 added an execution limiter to limit how many chapel tests would execute concurrently. This enabled us to compile concurrently, but still only run one chapel executable at a time. Chapel executables can use the whole machine, so we want to avoid multiple executables from contenting with each other. For most tests that compile then execute we'll eventually just have a single executable running with no interference. However, if you have a lot of consecutive compile-only tests, the non-stop chpl compilations can also cause interference.
Avoid interference from normal consecutive compile-only tests (tests that don't generate an executable, but match expected output) by waiting for the last executing test to finish before going on.
Resolves Cray/chapel-private#4967
=> Throttle compile-only tests when the execution limiter is enabled

modules/internal/ChapelRange.chpl
This PR makes no user-facing changes. The key implementation changes are:
(1) Refactor `chpl_by_help()`, which is used to implement the range `by` operator, to match more closely the desired definition in https://github.com/chapel-lang/chapel/issues/19717#issuecomment-1277037089 . While I expected behavioral changes from this refactoring, testing has not detected any.
(2) Ensure that every range with |stride|==1 is aligned regardless of its strideKind, as discussed in #19717, as part of the above refactoring.
(3) Get `range.isAmbiguous()` ready for deprecation in favor of `! range.isAligned()`, per https://github.com/chapel-lang/chapel/issues/19717#issuecomment-1277037842 . That is, remove the check for |stride|==1 from `range.isAmbiguous()`, as I convinced myself that it is no longer …
=> Tidy range.by and range.aligned

runtime/src/chpl-gpu.c, test/GPU-GRAPHFILES, test/gpu/native/studies/coral/coral.chpl, test/gpu/native/studies/coral/coral.compopts, test/gpu/native/studies/coral/coral.execopts, test/gpu/native/studies/coral/coral.good, test/gpu/native/studies/coral/coral.gpu-compopts, test/gpu/native/studies/coral/coral.gpu-execopts, test/gpu/native/studies/coral/coral.gpu-keys, test/gpu/native/studies/coral/coral.graph, test/gpu/native/studies/coral/modules/distance_iter.chpl, test/gpu/native/studies/coral/modules/distance_mask.chpl
This adds the un-optimized code as a correctness and performance test. I am planning to add the optimizations later on to record the impact.
=> Add Scott's GPU-based Coral Image Analysis code as a correctness and performance test

test/compflags/ferguson/mllvm-badarg.skipif
=> Fix mllvm-badarg.skipif

test/ANNOTATIONS.yaml
- Upgrade Arkouda release testing to 1.31
=> Add perf annotations for 2023-07-13

util/cron/test-perf.chapcs.playground.bash
Puts my patch to inline tuple accessors on the performance playground.
Patch: https://github.com/chapel-lang/chapel/compare/main...e-kayrakli:chapel:inline-tuple-access
=> Put tuple accessor inlining branch on perf playground

util/cron/test-email.bash
Adding a new test to test the ci-config changes for the emailer.
=>  Added a new test to test email

util/devel/deprecationScript/deprecateFunction.bash, util/devel/deprecationScript/extractLineNumbers.py, util/devel/deprecationScript/limitations, util/devel/deprecationScript/replaceDeprecatedLines.py
Pull request to merge the deprecation script utility.
This script makes it easier to replace deprecated features with their replacements
=> Add deprecation script utility

test/distributions/bharshbarg/fastFollowerEquality.chpl, test/distributions/deitz/test_block_representation.chpl, test/distributions/robust/arithmetic/basics/test_reshape.chpl, test/distributions/robust/arithmetic/trivial/test_dot_dist.chpl, test/distributions/robust/arithmetic/trivial/test_dot_domain.chpl, test/optimizations/bulkcomm/asenjo/redistBlockToCyclic/FFT_assignment.chpl, test/optimizations/bulkcomm/asenjo/redistBlockToCyclic/FFT_bulk.chpl, test/performance/ferguson/cyclic-id-queries.chpl
Fixed 8 failing tests in all gasnet configurations caused due to #22823
=> Fixing failing gasnet tests due to domain.dist deprecation

doc/rst/platforms/libfabric.rst
Updated the hugepage documentation to reflect changes caused by adding hugepage support to the HPE Cray EX platform.
=> Update hugepage documentation

test/gpu/native/array_on_device/studies/shoc/triadAOD.chpl, test/gpu/native/array_on_device/studies/shoc/triadAodAsync.chpl, test/gpu/native/atomics.chpl, test/gpu/native/bitops.chpl, test/gpu/native/math.chpl, test/gpu/native/studies/multiGpuStream/multiGpuStream.chpl, test/gpu/native/studies/shoc/triad.chpl, test/gpu/native/studies/shoc/triadalt1.chpl, test/gpu/native/studies/shoc/triadalt2.chpl, test/gpu/native/studies/shoc/triadchpl.chpl, test/gpu/native/studies/transpose/transpose.chpl, test/library/packages/LinearAlgebra/correctness/testEigen.chpl
Fix testEigen to use new version of AutoMath.isClose instead of the
deprecated one.
Fix a bunch of GPU tests
Checked a fresh checkout of the tests.  Strategy okay'd with the
GPU team.
=> Fix testing failures from yesterday's isClose adjustments

util/test/sub_test.py
Make `sub_test.py `a module so that it can be imported by custom sub_test implementations.
=> Modularize sub_test.py

runtime/src/qio/qio_formatted.c, test/library/standard/IO/readAndMatchLiteral/matchLiteral.chpl, test/library/standard/IO/readAndMatchLiteral/matchLiteral.good, test/library/standard/IO/readAndMatchLiteral/matchLiteral.stdin, test/library/standard/IO/readAndMatchLiteral/matchLiteralWS.chpl, test/library/standard/IO/readAndMatchLiteral/matchLiteralWS.good, test/library/standard/IO/readAndMatchLiteral/matchLiteralWS.stdin, test/library/standard/IO/readAndMatchLiteral/readLiteral.chpl, test/library/standard/IO/readAndMatchLiteral/readLiteral.stdin, test/library/standard/IO/readAndMatchLiteral/readLiteralWS.chpl, test/library/standard/IO/readAndMatchLiteral/readLiteralWS.stdin
Per the discussion summarized here: https://github.com/chapel-lang/chapel/issues/19487#issuecomment-1591634119, update `readLiteral` and `matchLiteral` to respect leading whitespace in the literal string when `ignoreWhitespace=true`.
=> Respect leading whitespace in `readLiteral` and `matchLiteral`

util/test/sub_test.py
The recent changes to modularize `sub_test.py` overlooked several operations that happened at global scope, in particular one that changed the PATH. This caused "`import sub_test`" to change the PATH. These operations have now been moved into main.
=> Fix problems with modularization

third-party/chpl-venv/chpldoc-requirements3.txt
Bump chapeldomain version to 0.0.29 to include a bug fix.
closes #17057
[reviewed by @lydia-duncan]
=> Bump chapeldomain version to include bug fix

test/llvm/assertVectorize/assertVectorized.compopts, test/llvm/assertVectorize/assertVectorized.prediff
Adds a prediff and more opt flags for this test
=> Add more fixes for llvm/assertVectorize

test/arrays/userAPI/assocDistributedHashed.good
This .good file escaped my notice during testing after #23053.
=> Update assocDistributedHashed.good file

test/gpu/native/studies/compiler-performance/end-to-end.graph
The test in question was renamed, this PR fixes its graph file.
=> Fix a compilation performance graph file

util/devel/deprecationScript/replaceDeprecatedLines.py
This PR improves replaceDeprecatedLines script to be able to handle regular expression based replacement.
I needed this to replace single-identifier statements with something more complex like:
```chpl
myVar;
// into
myVar.locale;
```
The existing behavior should be preserved. Regex behavior is enabled with `-r` or `--regex`.
=> Adjust deprecation replacement script to handle regular expressions

test/gpu/native/studies/shoc/shoc-sort.compopts, test/gpu/native/studies/shoc/shoc-sort.gpu-compopts
Fixes missing dash in compopts for shoc-sort
=> Fix compopts for renamed shoc-sort

third-party/chpl-venv/test-requirements.txt
Our build is running into this GH issue:   https://github.com/yaml/pyyaml/issues/601
=> Update PyYAML to 6.0.1 for homebrew builds

runtime/src/launch/pbs-gasnetrun_ibv/launch-pbs-gasnetrun_ibv.c
Modify to work with "place/select" qsub syntax
Resolves https://github.com/Cray/chapel-private/issues/1800 and fixes https://github.com/chapel-lang/chapel/issues/20685.
=> Update pbs-gasnetrun_ibv launcher

modules/standard/Reflection.chpl
Improves the conditional logic for an error message in the Reflection module to be simpler.
Implements feedback from https://github.com/chapel-lang/chapel/pull/23234#discussion_r1317878459
=> Improve conditional logic of error message in Reflection

modules/standard/IO.chpl
Resolves: https://github.com/chapel-lang/chapel/issues/19528.
Makes a few improvements to the docs for `seek` and `advance` in the IO module to clarify how/why they are different. Specifically, makes the adjustments suggested in [this comment](https://github.com/chapel-lang/chapel/issues/19528#issuecomment-1118988157).
=> Improve docs for `seek` and `advance`

runtime/src/launch/pbs-gasnetrun_ibv/launch-pbs-gasnetrun_ibv.c
Modify pbs-gasnetrun_ibv to support co-locales by launching CHPL_RT_LOCALES_PER_NODE locales per node. Note that currently CHPL_RT_LOCALES_PER_NODE cannot be greater than the number of sockets in a node as each locale will run in its own socket. Due to limitations in the underlying gasnetrun_ibv launcher, if the number of locales isn't evenly divisible by CHPL_RT_LOCALES_PER_NODE then the locales will be distributed as evenly as possible across nodes even if this means that all nodes have fewer than CHPL_RT_LOCALES_PER_NODE locales. For example, if there are 4 locales and CHPL_RT_LOCALES_PER_NODE=3, then two nodes will be allocated, each running two locales.
=> Add co-locale support to pbs-gasnetrun_ibv

runtime/src/comm/gasnet/comm-gasnet-ex.c
Apply #22311 to gasnet-ex shim
=> Add gasnet-ex locale-per-socket support

test/types/bool/boolAcceptsQuery.bad, test/types/bool/boolAcceptsQuery.compopts, test/types/bool/boolAcceptsQuery.future, test/types/bool/boolAcceptsQuery.good
Michael fixed the future I was adding before I merged my PR, and I knew this, but once the PR passed review, I still forgot to retire the future myself before merging it.
=> Retire future I filed earlier today

util/test/prediff-for-unstable-memleaks
This should actually fix the memleaks jobs
Passed full memleaks testing (with both flags this time)
=> Also elide warnings about --memLeaksLog in full memleaks testing

doc/rst/technotes/index.rst, doc/rst/technotes/interfaces.rst, doc/rst/technotes/manage.rst
This locks down the behavior of interfaces. I've elected to only write about stable language features here, which was OK'ed with the team.
Reviewed by @ShreyasKhandekar -- thanks!
=> Add a tech note for interfaces in Chapel

doc/rst/language/spec/procedures.rst
This PR updates the details of disambiguation in the spec for the changes in PR #22917.
=> Update spec disambiguation details for shadowing changes

doc/rst/language/spec/data-parallelism.rst
Rewrites the spec additions made in #23437 to address feedback
=> Rewrite of indirect whole array indexing in spec

doc/rst/language/spec/arrays.rst, doc/rst/language/spec/classes.rst, doc/rst/language/spec/conversions.rst, doc/rst/language/spec/data-parallelism.rst, doc/rst/language/spec/iterators.rst, doc/rst/language/spec/procedures.rst, doc/rst/language/spec/task-parallelism-and-synchronization.rst, doc/rst/language/spec/variables.rst, doc/rst/technotes/extern.rst
This PR adjusts the spec to change the approach for the default & `const` intent to mean `const` [cvref] (#21499). It builds upon PR #23097.
* The approach used here is to describe `const` intent as one where the compiler will choose between `const in` and `const ref`, with the implication that programs relying on one or the other (due to updates to the referred-to-value by other means than the formal) will have unexpected behavior when the compiler makes a different choice. As an extension to the above implication, it adds the constraint that the compiler can assume that the referred-to value will not change.
* This leaves it implementation-dependent for example whether a `.locale` query on a `const` (including default intent for most types) formal argument will refer to the original …
=> Spec changes for const [cvref]

test/studies/hpcc/FFT/fft.ml-compopts, test/studies/hpcc/HPL/hpl.ml-compopts
=> Fix multilocale performance runs for the moved HPL and FFT tests

test/release/examples/primers/Makefile, test/release/examples/primers/README
I completely spaced on the fact that I needed to update the README and Makefile for my recent changes and additions to the primers: the new loops primer and the revamped distributions primer.  This corrects that mistake.  I also opened https://github.com/Cray/chapel-private/issues/5416 to propose that doing these checks might be better suited for a CI job than a nightly one.
=> Update README and Makefile for added/changed primers: loops, distributions

test/ANNOTATIONS.yaml
- change to promoted op= test
- faster 2D heat solvers from stencil swap optimization
=> Add perf annotations for 2023-09-21

doc/rst/usingchapel/launcher.rst
Update the launcher table to include missing launchers and standardize the language.
=> Update launcher table in the documentation

test/ANNOTATIONS.yaml
Added annotations for:
- Arkouda array creation release performance rebound
=> Annotations for 2023-09-21

util/pastPerformance/testReleasesPerformance, util/test/perf/perfgraph.js
Performance graph changes for 1.32 release.
=> Performance graph changes for 1.32

CMakeLists.txt, man/confchpl.rst, man/confchpldoc.rst, test/chpldoc/compflags/combinations/versionhelp-chpldoc.sh, test/compflags/bradc/printstuff/version.goodstart, test/compflags/bradc/printstuff/versionhelp.sh
=> update chapel version to 1.33

doc/util/versionButton.php
[trivial and rote for this point in the release process; not reviewed]
=> Bump default documents version to 1.32; next to 1.33

tools/chapel-py/chapel.cpp
This is motivated by using other "iterator pairs" that come from the Dyno library.
Reviewed @jabraham17 -- thanks!
=> Add a list adapter for Python bindings to help reuse iterator code

util/build_configs/cray-internal/setenv-hpe-cray-ex-x86_64.bash
This is an upgrade for the cce version and migrates Chapel from 12.0.2.
=> Pinned our cce version to 15.0.1

test/release/examples/primers/modules.chpl, test/release/examples/primers/modules.good
This PR simplifies the modules primer by combining the modules OuterNested and OuterNested2.
=> Simplify the modules primer

util/cron/test-perf.chapcs.playground.bash
Test bundled LLVM 16 in the perf playground
[Reviewed by @mppf offline]
=> Update the perf playground to use bundled LLVM 16

test/gpu/native/studies/sort/radixSortGpu.chpl, test/gpu/native/studies/sort/radixSortGpu.execopts, test/gpu/native/studies/sort/radixSortGpu.gpu-execopts, test/gpu/native/studies/sort/radixSortGpu.gpu-keys
Based on feedback from @mppf (thanks!), I wrote a version of the radix sort that uses different approach. The first attempt wasn't parallel in the last (scatter) step, therefore this new approach was needed. There is still work to be done to improve the performance of this new approach.
=> Adding new radix sort algorithm

util/packaging/docker/test/Dockerfile
The two FROM statements cause the build to fail.
=> Resolve issue with double FROM in DockerFile

test/library/packages/Curl/download-http-upload-ftp.good, test/library/packages/Curl/upload-ftp.good
With a .noexec, we should not expect to see output that would trigger if they were to run
Checking a fresh checkout of these tests
=> Remove output from the .good files of these tests

modules/internal/ChapelDomain.chpl
This PR reorders domain methods so that the online documentation shows them in a meaningful order, starting with the primary properties.
This PR makes no code/annotation/pragma changes, except for a couple of trivial comment changes.
The online docs now show the domain methods in this order:
```
distribution
dist*
rank
idxType
fullIdxType
intIdxType*
strides
stridable*
stride
alignment
targetLocales
isEmpty
size
sizeAs
dims
dim
shape
low
high
lowBound
highBound
alignedLow*
alignedHigh*
first
last
tryCreateArray*
unsafeAssignManager
unsafeAssign
clear
remove
add
createIndexBuffer*
bulkAdd*
bulkAddNoPreserveInds*
requestCapacity
contains
orderToIndex*
expand*
exterior*
interior*
translate*
localSlice
sorted
hasSingleLocalSubdomain*
localSubdomain
localSubdomains*
safeCast*
tryCast …
```
=> Reorder domain declarations

runtime/src/launch/gasnetrun_common/gasnetrun_common.h
Add co-locale support to the `gasnetrun_*` launchers.
=> Add co-locale support to the gasnetrun_* launchers.

runtime/src/launch/slurm-gasnetrun_common/slurm-gasnetrun_common.h
Add co-locale support to the `slurm-gasnetrun_*` launchers.
=> Add co-locale support to the slurm-gasnetrun_* launchers

test/arrays/bugs/arrOfRecordNoDefaultInit.chpl, test/arrays/bugs/arrOfRecordNoDefaultInit.good
Thanks to @cassella for noticing that this is now passing a few weeks back.  Here, I'm filing the code from the issue to lock in the behavior going forward.
=> Add test locking in fix for issue #14813

test/gpu/native/studies/bandwidth/p2p.chpl
=> Fix spelling in p2p test

runtime/src/comm/gasnet/comm-gasnet-ex.c
Start migrating our gasnet-ex shim over to the gasnet-ex (GEX) API. To start, just migrate initialization.
The main change is that gasnet now has explicit teams and endpoints. For now we're just using a single endpoint/team (along with segment/client) to mimic the old behavior, but over time this could be used to implement multi-endpoint (parallel comm/injection) and multiple teams (for better collectives between subsets of locales)
Beyond that, the AM handler table takes additional information about how entires are used -- as a request/reply, with short/med/long AMs, how many args are used, and a debug name. `gasnet_attach` has also been split into separate attach and register-handlers steps, though we call them in one after the other so there's no real difference to us.
Testing:
Part of …
=> Convert gasnet-ex shim initialization over to the GEX API

test/studies/parflow/README.md, test/studies/parflow/buildFiles/ChapelReadMe.md, test/studies/parflow/buildFiles/performance-evaluation.sh, test/studies/parflow/chapelCode/BoundaryConditions.chpl, test/studies/parflow/chapelCode/ChapelImpl.chpl, test/studies/parflow/chapelCode/GroundGeometry.chpl, test/studies/parflow/chapelCode/NOTEST, test/studies/parflow/chapelCode/PhaseRelPerm.chpl, test/studies/parflow/chapelCode/RichardsJacobianEval.chpl
Adds a new study to the tests that includes the code written as part of my summer 2022 internship project, a partial port of the ParFlow application. C code is linked and an interop snippet is present in the readme.
Files are not built/run as part of testing, as they need to be in the ParFlow repository for the include statements to resolve.
=> Parflow Study

frontend/lib/resolution/disambiguation.cpp
This PR implements some trivial changes to address reviewer feedback in https://github.com/chapel-lang/chapel/pull/23668 and https://github.com/chapel-lang/chapel/pull/23726.
Trivial changes only, not reviewed
=> trivial changes to address collective feedback in 23668 and 23726

compiler/llvm/clangUtil.cpp
Avoid re-running Clang code generation (over the runtime and included code) in driver phase two.
The skipped work is unnecessary as it is already included in the LLVM Module that gets restored from disk. However, we do need most of `clangInfo` set up for later use in `makeBinary`, so that part is preserved.
This turned out to not have the compiler performance impact I hoped (saving about ~60ms on my machine for helloworld), but is still probably good to have.
This is one component of https://github.com/Cray/chapel-private/issues/5373.
Testing:
=> Skip most of `runClang` in driver phase two

frontend/lib/resolution/disambiguation.cpp
This PR implements the `discardWorseConversions` function for Dyno disambiguation. This PR is part 5 of a series of PRs that implement disambiguation changes already in production from https://github.com/chapel-lang/chapel/pull/20528. 
There remains some work to implement this for tuples and for promotion. 
[reviewed by @mppf - thank you!]
=> [dyno] implement discardWorseConversions disambiguation stub

runtime/src/comm/gasnet/comm-gasnet-ex.c
Convert the naive AM-based broadcast of the seginfo table done for segment everything into a real collective broadcast. This is cleaner and more efficient (and a TODO from 7395837). As part of this, don't broadcast zero'd values, just broadcast locale-0 values and independently zero non locale-0 entries.
While technically more efficient, this is a single small broadcast so doesn't have a noticeable impact on startup. With 100 nodes and 800 processes (`-nl 100x8` with support for process per numa domain) using ibv with segment everything I see the barrier+broadcast+barrier is sub millisecond with either approach. This single use is pretty noisy, but adding an artificial 1,000 trial loop I see timings per iteration go from ~800 microseconds to ~75 microseconds, so there is a real impact of …
=> Convert gasnet-ex shim to use real GEX broadcast for seginfo broadcast

util/cron/test-perf.chapcs.playground.bash
=> Test monolithic compiler performance with driver adjustments

test/functions/diten/formalArrayWithQueriedEltSize.bad, test/functions/diten/formalArrayWithQueriedEltSize.future
Promote a future that passes after #23807.
=> Promote a now passing future

test/ANNOTATIONS.yaml
Add annotations for Arkouda compilation regression and fix for accidentally excluding jemalloc.
=> Add annotations for November 16th

runtime/include/chpl-gpu.h, runtime/src/chpl-gpu.c
Resolves https://github.com/chapel-lang/chapel/issues/23837
I bumped into the issue I linked above. I think this is an obvious fix.
Test:
=> Add printf attribute to CHPL_GPU_DEBUG

modules/standard/IO.chpl
* fix an issue with mixing 32- and 64-bit ints on 32-bit platforms
* fix a comment that I wrote backwards (and caught last night but then forgot to commit+push)
=> Fix a few issues in my binary IO PR from yesterday

frontend/lib/resolution/disambiguation.cpp
This PR fixes build issues on MacOS after updating the dyno disambiguation process to no longer use some functions in https://github.com/chapel-lang/chapel/pull/23886.
TESTING:
[reviewed by @benharsh - thanks!]
=> dyno: remove unused disambiguation procedures after update

doc/rst/developer/bestPractices/NightlyTesting.rst, util/buildRelease/testRelease, util/cron/README, util/cron/nightly
Address https://github.com/Cray/chapel-private/issues/5606
Remove nightly email env from the test script.
=>  Remove CHPL_NIGHTLY_CRON_RECIPIENT from the test scripts

doc/rst/developer/bestPractices/TestSystem.rst
Adds a few notes to `TestingSystem.rst` about running tests
=> Expand testing system docs

CONTRIBUTORS.md
This is the list of CONTRIBUTORS for Chapel 1.33.  Thanks to all who contributed!
=> CONTRIBUTORS for 1.33

CHANGES.md
This is the list of CHANGES for Chapel 1.33.  Thanks to all who contributed!
=> CHANGES for 1.33

CMakeLists.txt, man/confchpl.rst, man/confchpldoc.rst, test/chpldoc/compflags/combinations/versionhelp-chpldoc.sh, test/compflags/bradc/printstuff/version.goodstart, test/compflags/bradc/printstuff/versionhelp.sh
Updates the version numbers for the next Chapel release
=> Set Chapel 1.34 pre-release version data

compiler/llvm/clangUtil.cpp, compiler/llvm/llvmAggregateGlobalOps.cpp, compiler/llvm/llvmExtractIR.cpp, compiler/llvm/llvmGlobalToWide.cpp, compiler/llvm/llvmUtil.cpp, compiler/passes/externCResolve.cpp, frontend/include/chpl/resolution/scope-types.h, test/extern/ferguson/externblock/syntax-error.prediff, test/llvm/gen-ids/llvm-gen-ids.compopts, test/llvm/vectorization/parallel_loop_novec.chpl, third-party/jemalloc/Makefile, util/chplenv/chpl_gpu.py, util/chplenv/chpl_llvm.py
Patches Chapel to build and run with a LLVM 17 system install.
=> Fixes to build Chapel with LLVM 17

util/cron/test-linux64-llvm17.bash
Adds nightly testing configuration for llvm 17
=> Add new test for system llvm 17

.github/workflows/CI.yml
Remove duplicate `make` from CI check
=> Fix duplicate call to make

util/cron/common-champs.bash, util/cron/test-perf.cray-cs-hdr.champs.c-backend.bash, util/cron/test-perf.cray-cs-hdr.champs.llvm.bash
This PR is a quick adjustment for the apollo-hdr CHAMPS performance plots.
=> Update CHAMPS perf plots' start date

util/pastPerformance/testReleasesPerformance, util/test/perf/perfgraph.js
These are the graph updates for the 1.33 release.
=> Performance graph updates for 1.33

util/test/perf/perfgraph.js
Fixes perf graphs rendering by fixing a small syntax error.
Tested with local webserver
=> Fix perf graphs not rendering

test/studies/bale/aggregation/AtomicAggregation.chpl
Updates AtomicAggregators to be in sync with the perf updates in CopyAggregation package
=> Update AtomicAggregators with perf updates

runtime/src/comm/ofi/comm-ofi.c
Previously, to ensure correct AMO ordering in MCM mode message-order-fence, we fenced all fetching atomics (FAMOs) when the provider does not provide `FI_ORDER_ATOMIC_RAW`. This is simple, but has too much overhead. Now we only fence a FAMO if it is necessary to enforce the MCM.
Resolves https://github.com/Cray/chapel-private/issues/5530.
=> Conditionally fence FAMOs under message-order-fence

test/ANNOTATIONS.yaml
- Arkouda symbol table entry initialization fixes
- Arkouda small string optimization with regressions for other groupbys
- Chapel compiler performance hit from GPU code included by default
=> Add annotations for December 14

runtime/src/comm/ofi/comm-ofi.c
Slingshot-11 devices, service IDs, and VNIs are passed to the locale in the environment variables `SLINGSHOT_DEVICES`, `SLINGSHOT_SVC_IDS`, and `SLINGSHOT_VNIS`, respectively. If there are multiple NICs then `SLINGSHOT_DEVICES` will be a comma-separated list, in which case `SLINGSHOT_SVC_IDS` and `SLINGSHOT_VNIS` might also be comma-separated lists. If `SLINGSHOT_SVC_IDS` is a list, then we should authenticate using the element of the list that corresponds to the index of our device in the `SLINGSHOT_DEVICES` list. `SLINGSHOT_VNIS` should be handled similarly.
Resolves https://github.com/Cray/chapel-private/issues/5782
=> Support for per-device SS11 authentication

frontend/include/chpl/parsing/parsing-queries.h, frontend/include/chpl/resolution/resolution-queries.h, frontend/include/chpl/resolution/resolution-types.h, frontend/include/chpl/types/Type.h, frontend/lib/parsing/parsing-queries.cpp, frontend/lib/resolution/prims.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/types/Type.cpp, frontend/test/resolution/testTypePropertyPrimitives.cpp
Add implementations of two primitives to the new compiler.
=> Add PRIM_IS_POD_TYPE and PRIM_IS_EXTERN_TYPE to dyno

test/library/packages/Sort/performance/comparison/CSharpSortRandom.cs, test/library/packages/Sort/performance/comparison/JavaSortRandom.java, test/library/packages/Sort/performance/comparison/futhark-radix-sort.fut, test/library/packages/Sort/performance/comparison/go-sort-random.go, test/library/packages/Sort/performance/comparison/nodejs-sort-random.js
This PR adds programs written in C#, Java, Futhark, and NodeJS to measure sort performance in those languages. These are not run in any testing configuration & only useful for manual performance comparisons.
=> Add more comparison benchmarks for std lib sort perf

modules/standard/CTypes.chpl, test/extern/fnPtrs/compareFnPtrs.chpl, test/extern/fnPtrs/compareFnPtrs.good
=> Make c_fn_ptr equality comparable to nil

CMakeLists.txt
This is also used for chpl and chpldoc.
Should resolve https://github.com/chapel-lang/chapel/issues/24084. 
=> Use install RPATH for libChplFrontendShared.

test/ANNOTATIONS.yaml
- Arkouda ndim field regression
- ArrayView regression
=> Add annotations for January 18

test/library/standard/Set/reduce.chpl, test/library/standard/Set/reduce.good
=> Add test of +reducing a set

test/ANNOTATIONS.yaml
- Compiler performance being impacted by no longer auto-including GPU module
=> Add annotations for January 18 (part 2)

test/library/packages/Sort/performance/comparison/CSharpSortRandom.cs, test/library/packages/Sort/performance/comparison/JavaSortRandom.java, test/library/packages/Sort/performance/comparison/boost-block-indirect-sort.cc, test/library/packages/Sort/performance/comparison/boost-spreadsort.cc, test/library/packages/Sort/performance/comparison/chapel-quicksort-random.chpl, test/library/packages/Sort/performance/comparison/chapel-sort-older-radix-sort.chpl, test/library/packages/Sort/performance/comparison/chapel-sort-random.chpl, test/library/packages/Sort/performance/comparison/chapel-sort-two-array-random.chpl, test/library/packages/Sort/performance/comparison/go-sort-random.go, test/library/packages/Sort/performance/comparison/ipsssso-sort-random.cc, test/library/packages/Sort/performance/comparison/julia-sort-random.jl, test/library/packages/Sort/performance/comparison/nodejs-sort-random.js, test/library/packages/Sort/performance/comparison/numpy-sort-random.py, test/library/packages/Sort/performance/comparison/python-sort-random.py, test/library/packages/Sort/performance/comparison/qsort-random.c, test/library/packages/Sort/performance/comparison/qsort-random.cc, test/library/packages/Sort/performance/comparison/sort-random-rust/src/main.rs, test/library/packages/Sort/performance/comparison/stl-parallel-sort-random.cc, test/library/packages/Sort/performance/comparison/stl-sort-random.cc
This PR updates programs in the test/library/packages/Sort/performance/comparison directory. Note that these tests are only run manually.
The changes are:
* adjust most to output both million elements sorted / second and a MiB/s rate
* adjust several to time the construction of the random array
=> Update sort cross-language comparsion tests

frontend/lib/parsing/README
This PR updates frontend/lib/parser/README which was out of date.
=> Update the parser README which was out of date

tools/chpl-language-server/src/chpl-language-server.py
Adds basic renaming support to the language server. This only works well for symbols defined and used inside of a single file/module. Once cross-workspace references work, this should work for global symbol renaming
=> Add basic rename symbol support to chpl-language-server

test/multilocale/numLocales/bradc/testVFlag.prediff, test/multilocale/numLocales/bradc/testVerboseFlag.prediff
Remove any messages related to co-locales.
=> Fix verbose flag tests

util/cron/test-perf.chapcs.playground.bash
Discussed with Jade, the last user of the playground.
=> Switch perf playground to return-by-ref branch

modules/packages/Crypto.chpl
This routine, provided by #24104, makes these string constructions much faster.
=> Crypto module: make toHex routines use appendCodePointValues()

compiler/optimizations/gpuTransforms.cpp
https://github.com/chapel-lang/chapel/pull/24137 run into a problem with `--gpu-specialization`. With that mode, the loop that we end up launching as a kernel was subjected to aggressive LICM before we can find pids in them. Because the PR initially tried to find array/domain records used in the loop. This PR expands the logic to also find indices used while indexing `chpl_privateObjects` array. The end result is that we potentially capture some pids twice redundantly which may end up with redundant operations on the runtime's part. However, this gives us a better coverage and fixes the issue as a short-term solution.
Ideally, instead of recording "pid gets" we should cache array/domain records accessed in the loop body in a set. And then generate "pid gets" in the preamble using that …
=> GPU Privatization: handle a case where array record is LICM'd

test/gpu/native/atomics.chpl, test/library/packages/BLAS/test_blas2.chpl, test/library/packages/LinearAlgebra/performance/MatrixUtils.chpl, test/library/standard/Random/ferguson/fillrandom-bounded.bad, test/library/standard/Random/ferguson/fillrandom-bounded.future
Fix some test failures caused by: https://github.com/chapel-lang/chapel/pull/24379
=> Test updates from #24379

runtime/src/topo/hwloc/topo-hwloc.c
Iterate the full logical set `logAllSet` of cores and check for each core whether it intersects with `logAccSet`, i.e., whether some PU of the core is accessible to Chapel, before adding it to `physAccSet`.
=> fix for #24371 hwloc finds No useable cores for restricted cpuset

test/runtime/configMatters/comm/comm-ops.chpl
Micro-benchmark for contended fetching atomic operations.
Resolves https://github.com/Cray/chapel-private/issues/5949.
=> Created contended fetching AMO benchmark.

test/library/packages/Curl/COMPOPTS, test/library/packages/Curl/check-http.chpl, test/library/packages/Curl/download-http-upload-ftp.chpl, test/library/packages/Curl/upload-ftp.chpl, test/library/packages/LinearAlgebra/performance/MatrixUtils.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/any/read.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/any/write.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/enums/read.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/enums/write.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/maps/read.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/maps/write.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/messagefield/read.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/messagefield/write.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/oneofs/read.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/oneofs/write.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/repeatedfield/read.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/repeatedfield/write.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/typesTest/read.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/typesTest/write.chpl, tools/mason/MasonExternal.chpl
Resolves a few test failures caused by #24346
=> Fix test failures from #24346

tools/chpl-language-server/src/chpl-language-server.py, tools/chpl-language-server/src/symbol_signature.py
This PR fixes a small omission in #24325. In particular, whereas the original PR always displays the "naive" hover information (not taking into account which instantiation has been selected via 'Show instantiation'), it should draw additional type substitutions from which version of a generic function is currently being viewed. The result of this is being able to view types of variables on hover inside of instantiations.
=> LSP: Use current instantiation to show hover information

test/library/packages/HDFS/hello-hadoop.chpl, tools/mason/MasonSystem.chpl
Fix some test failures caused by #24346, not caught in previous PR.
=> Fix test more failures from #24346

tools/chpl-language-server/src/chpl-language-server.py
Adds a "Show Generic" code lens to complement "Show Instantiation" to show just the plain function. This is especially import after clicking "Show Instantiation" and wanting to go back to the previous view
=> Add a "Show Generic" code lens

doc/rst/developer/bestPractices/Valgrind.rst
Valgrind.rst: Add note about old valgrind and -gdwarf-4 setting
=> Valgrind.rst: Add note about old valgrind and -gdwarf-4 setting

compiler/AST/astutil.cpp
Fix nightly test failures running under `-compopts --baseline -futures-mode 3` (run with `--baseline` and only include futures with SKIPIFs).
Adjust cleanup before code generation to remove symbols with type `uninstantiated` that have zero uses. This is required because currently, we do not run `--dead-code-elimination` when under `--baseline`.
Note that 5 futures still fail when running a plain-old `--baseline` paratest. Fixing them is future work.
In the future, perhaps we should consider always running dead code elimination, and even disabling its command-line flag altogether. This is because the current code generator expects dead code elimination to have occurred in order to function properly (as evidenced by this patch). Currently, we have a bunch of adhoc "code elimination" that …
=> Always prune unused 'uninstantiated' variables before codegen

test/gpu/native/noGpu/basicMem.comm-none.good, test/gpu/native/noGpu/basicMem.good, test/gpu/native/noGpu/basicMem.prediff, test/gpu/native/useAssociativeDomain.compopts, test/studies/ssca2/main/SSCA2_Modules/SSCA2_driver.chpl
Simple fixes to some nightly failures caused due to my associative domain stabilization PR
=> Fix failing tests from Assoc domain changes

doc/rst/technotes/gpu.rst
=> GPU: `@gpu.blockSize` and variable attribute support docs

doc/rst/developer/bestPractices/TestSystem.rst, util/test/sub_test.py
Add more details in the testing system docs for `NUMTRIALS` and related options
=> Improve documentation for NUMTRIALS

doc/rst/technotes/gpu.rst
This PR mainly reworks the "Requirements" section. I tried to make a clear separation for AMD and NVIDIA GPUs, especially after we changed how AMD works with the system LLVM recently.
While there this PR also makes:
- minor language adjustments
- link updates
- updates on "Tested Configurations"
=> Update the GPU technote for the 2.0 release

doc/rst/technotes/index.rst, doc/rst/technotes/static.rst
=> Add a tech note for static variables

test/studies/arkouda/sub_test
=> Fix pip flag name for nightly test

CHANGES.md
(I did run spellcheck, but tend to not pay much attention to the technical terms that are flagged)
=> Fix a spelling mistake Paul caught

test/gpu/native/studies/chop/chplGPU.compopts, test/gpu/native/studies/chop/chplGPU.execopts, test/gpu/native/studies/chop/chplGPU.good, test/gpu/native/studies/chop/chplGPU.prediff, test/gpu/native/studies/chop/chplGPU.skipif, test/gpu/native/studies/chop/patches/no_implicit_ref_various_configs.patch
Currently, we do nightly performance testing for GPUs + ChOp (https://github.com/tcarneirop/ChOp) but we are not doing correctness testing. This PR adds said correctness testing.
=> correctness testing for chop

test/studies/shootout/submitted/fasta3.chpl, test/studies/shootout/submitted/fasta5.chpl, test/studies/shootout/submitted/fasta6.chpl, test/studies/shootout/submitted/mandelbrot.chpl, test/studies/shootout/submitted/mandelbrot3.chpl, test/studies/shootout/submitted/revcomp5.chpl, test/studies/shootout/submitted/revcomp8.chpl, test/studies/shootout/submitted/spectralnorm2.chpl
These are some final edits to the shootout entries for Chapel 2.0, focusing on accuracy in the comments, consistency in style, spacing, formatting, etc.
=> Final edits to proposed Chapel 2.0-compatible shootout entries

frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/Resolver.h, frontend/test/resolution/testResolve.cpp
Fixes https://github.com/Cray/chapel-private/issues/6077.
Dyno handles resolving base expressions (e.g., the `f` in `f(x)`) differently than plain expressions; this is because, although `a.b` should be a field access, if we know that it's actually `a.b(c, d)`, we need to resolve the method `b` on `a` with arguments `c` and `d` (which happens when the call itself is resolved). Thus, resolution of `a.b` is deferred. 
However, Dyno's detection of when an expression is the "called expression" is incorrect. In particular, it doesn't work for nested called expressions, like `a.b(x).c(y)`. This is because the `Resolver` only uses a single state variable, `inLeafCall`, which it sets on entering a call, and resets to `nullptr` upon exiting a call. Unfortunately, since the entering and exiting are …
=> dyno: fix 'called expression' detection

frontend/lib/resolution/Resolver.cpp, frontend/test/resolution/testIf.cpp
An if-variable from a class should be resolved as a borrowed non-nil class type.
Testing:
=> Dyno: Resolve if-vars as borrowed non-nil

test/trivial/skip/skipTest.chpl, test/trivial/skip/skipTest.skipif, test/trivial/skip/wholeDir/SKIPIF, test/trivial/skip/wholeDir/skipTest.chpl, test/trivial/skip/wholeDir2.skipif, test/trivial/skip/wholeDir2/skipTest.chpl, util/test/start_test.py, util/test/sub_test.py
Previously, we would "fail" a skipif if there was any output other than "True"/"False"/0/1, however it would be nice to print logging output from one of these files (for example: an explanation of why a test was skipped).
This change modifies our processing of `.skipif` and `SKIPIF` files so we ignore all output from `stdout` except for the last line.
See: https://github.com/Cray/chapel-private/issues/6103
I've run this through paratests and everything passes.
=> Allow log messages from skipif: ignore all but last line of output

doc/rst/developer/bestPractices/GeneratedCode.rst
Signed-off-by: Nicole Vadot <40442285+ninivert@users.noreply.github.com>
=> docs: Change to reflect rename Timer -> stopwatch

doc/rst/developer/bestPractices/GeneratedCode.rst
Noticed while reviewing Nicole's update, this writeln didn't compile and so needed to be updated so that it would
Verified that the built docs looked good
=> Additional code fix in the generated code documentation

test/studies/1brc/README
Add more info to 1brc README.
- Descriptions of tests
- Link of where to view performance results.
=> add more info to 1brc README

test/ANNOTATIONS.yaml
- (Avoid string copies by implementing replace with match) improvement to regex CLBG test
- (Add permutation to our generators) improvement to to RandInt Array Creation Performance test
=> Add perf annotations for 2024-04-11

modules/standard/IO.chpl
Follow-up to PRs #24783 and #24842 to address problems on 32-bit systems.
Reviewed by @jeremiah-corrado - thanks!
=> Address compilation failures on 32-bit systems

util/cron/test-perf.chapcs.playground.bash
Test new LLVM 18 support in perf playground
Not reviewed - trivial
=> Use performance playground for LLVM 18

test/gpu/native/studies/chop/patches/no_implicit_ref_various_configs.patch
This PR adjusts a ChOp patch to adopt to upstream changes.
=> Modify a ChOp patch following some changes upstream

test/chplcheck/DoKeywordOnFunction.chpl, test/chplcheck/DoKeywordOnFunction.good
The test author did not account for the implicit module warning.
=> Fix the future 'DoKeywordOnFunction'

util/cron/load-base-deps.bash
As part of https://github.com/Cray/chapel-private/issues/6164.
[unlikely to break in a way review would catch, not reviewed]
=> Load Horizon nightly test deps from new Spack install

tools/chapel-py/src/resolution.cpp
Fixes a few incorrect cases pointed out by @jabraham17 (thanks!).
Now, it seems to work in every case I can think of:
=> chapel-py: further beef up the logic for use/import scope resolution

util/cron/load-base-deps.bash
Follow up to https://github.com/chapel-lang/chapel/pull/24914.
[nightly test fix, not reviewed]
=> Fix `util/cron/load-base-deps.bash` for `horizon*` system addition

CHANGES.md
This is a minor edit to CHANGES.md to reflect the reason for the 2.0.1 release.
=> CHANGES.md entry about the 2.0.1 bug fix release

util/cron/load-base-deps.bash
Part of https://github.com/Cray/chapel-private/issues/6231
=> Load deps from Spack on richter

util/cron/test-gpu-xc-cuda.ugni.bash
This adds a nightly testing config for gpu testing using ugni comm layer on xc
=> Add GPU ugni testing on Cray XC

util/packaging/homebrew/chapel-main.rb
Adds `chpl-language-server` and `chplcheck` to the homebrew package
=> Package CLS and chplcheck with homebrew

util/cron/test-perf.chapcs.playground.bash
Switch perf-playground to use always-unroll branch 
=> Switch perf-playground to test always-unroll branch

test/functions/generic/type-func-return-generic.bad, test/functions/generic/type-func-return-generic.chpl, test/functions/generic/type-func-return-generic.future, test/functions/generic/type-func-return-generic.good
Files a future for bug filed in #25039
=> File future for bug #25039

util/cron/load-base-deps.bash
Part of https://github.com/Cray/chapel-private/issues/5503.
[not likely to break in a way review would catch, not reviewed]
=> Load chapcs/chapvm nightly test deps from Spack

doc/rst/meta/static/portability-viz.css, doc/rst/meta/static/portability-viz.js, doc/rst/meta/templates/layout.html, doc/rst/usingchapel/index.rst, doc/rst/usingchapel/portability.rst
This PR adds a new "Portability" section to our documentation, with the goal of growing this page to include links/directions for how to run Chapel on the numerous platforms chapel supports.
Included on this page is a visualization of Chapel's portability as a graph, with some common systems Chapel is run on.
=> Add visualization of Chapel portability

test/functions/default-arguments/default-arg-reduce-distributed.bad, test/functions/default-arguments/default-arg-reduce-distributed.chpl, test/functions/default-arguments/default-arg-reduce-distributed.future, test/functions/default-arguments/default-arg-reduce-distributed.good
=> Add future for 25045 

frontend/lib/resolution/default-functions.cpp, frontend/test/resolution/testInitSemantics.cpp
This PR adds some basic support for compiler-generating initializer signatures on classes that inherit. This currently only works for concrete types, as we have some other pre-existing issues for instantiating generic classes with inheritance.
Various test cases are added to lock in relevant behaviors:
- named arguments working correctly with defaults
- presence of a user-defined initializer on a parent or grandparent class
- invoking a compiler-generated initializer with super.init
Testing:
=> Dyno: Generate concrete initializers on classes that inherit

test/ANNOTATIONS.yaml
- Improve mandelbrot complex performance for LLVM 17 with (#25019)
- Improve Arkouda argsort performance with (Bears-R-Us/arkouda#3163)
=> annotations for week of 5/16/24

test/performance/vectorization/vectorizeOnly/vectorizeOnlyWithIntents.bad, test/users/engin/partial_reduction_support/template_tests/templateTestDistBlockCyc.bad
Remove two .bad files for futures that have previously been resolved.
PRs that resolved these futures
- https://github.com/chapel-lang/chapel/pull/24540
- https://github.com/chapel-lang/chapel/pull/13549
=> Cleanup old .bad files

util/cron/test-slurm-gasnet-ex-ibv.c-backend.bash, util/cron/test-slurm-gasnet-ex-ibv.fast.bash, util/cron/test-slurm-gasnet-ex-mpi.bash
Added more GASNet-EX tests in preparation to making the `gasnet-ex` shim the default.
=> Added more Cray CS GASNet-EX tests

runtime/include/gpu/chpl-gpu-gen-common.h, runtime/src/chpl-gpu.c, test/gpu/native/examples/amd-talk/mGpu.chpl, test/gpu/native/examples/amd-talk/mGpuNoHelper.chpl, test/gpu/native/examples/amd-talk/mLocCpuMGpu.chpl, test/gpu/native/examples/amd-talk/mLocMGpu.chpl, test/gpu/native/examples/amd-talk/sGpu.chpl
While preparing for my talk, I bumped into two issues:
- `unordered` get/put weren't defined for device. This caused compilation issues. Note that we never call those similar to base get/put, but we just need definitions to compile with.
- `chpl_gpu_mem_realloc` was causing trouble in cpu-as-device mode, I believe this might be the first time we tried to create a rank-change view in this mode. The issue was a misplaced assertion. This PR moves it around.
Test:
=> Small fixes in GPU runtime

test/library/standard/GMP/mpf_get_str.chpl
I caught all the manual frees that my new GMP tests needed apart from one... :'(
=> Fix leak in new GMP-related test added in #25124

util/cron/test-perf.chapcs.playground.bash
Switch perf playground to test some changes to the LLVM pass manager for LLVM 16+
=> Switch perf playground to pass manager improvements branch

test/mason/gitErrors.skipif
Fix typo in skipif
[Reviewed by @brandon-neth]
=> Fix typo in skipif

doc/rst/technotes/gpu.rst, doc/rst/usingchapel/chplenv.rst
This importance of setting this variable may not be obvious to newcomers building the code.
Also update the documentation in the list of environment variables.
=> Make CHPL_LOCALE_MODEL more prominent in documentation

doc/rst/technotes/gpu.rst, test/gpu/native/llvmMoved.chpl
Update the GPU technote and llvmMoved test for GPUs to reflect LLVM 18 support
=> Update GPU technote and llvmMoved test

util/packaging/apt/common/fill_docker_template.py, util/packaging/apt/debian11/Dockerfile.template, util/packaging/apt/debian12-gasnet-udp/Dockerfile.template, util/packaging/apt/debian12/Dockerfile.template, util/packaging/apt/ubuntu20/Dockerfile.template, util/packaging/apt/ubuntu22-gasnet-udp/Dockerfile.template, util/packaging/apt/ubuntu22-ofi-slurm/Dockerfile.template, util/packaging/apt/ubuntu22/Dockerfile.template, util/packaging/apt/ubuntu24/Dockerfile.template, util/packaging/rpm/common/fill_docker_template.py, util/packaging/rpm/el9-gasnet-udp/Dockerfile.template, util/packaging/rpm/el9-ofi-slurm/Dockerfile.template, util/packaging/rpm/el9/Dockerfile.template, util/packaging/rpm/fc37/Dockerfile.template, util/packaging/rpm/fc38/Dockerfile.template, util/packaging/rpm/fc39/Dockerfile.template, util/packaging/rpm/fc40/Dockerfile.template
Adds a hook to `fill_docker_template.py` to allow our test config to inject some system specific networking configs
=> Add a hook for injecting extra packaging script steps

test/variables/remote/on-non-locale.bad
I renamed a file but didn't commit my changes to its contents as a result.
Trivial; not reviewed.
=> Fix error in renamed .bad file

modules/internal/ChapelRemoteVars.chpl
The use of `chpl_buildStandInRTT` led to a memory leak when promoted expressions were used with remote variables. My original implementation used a custom function like `remoteWrapperTypeForIR` which explicitly assigned the iterator record to a variable, then got its `.type`; this correctly computed the type, but led to the IR being invoked twice. Then I switched to `chpl_buildStandInRTT`, which avoided the double-run but apparently created memory problems. @vasslitvinov pointed out that the reason my original `remoteWrapperTypeForIR` ran the IR was because it _returned_ a type with a runtime component (array type). If I were to return a statically-known type, the function would not be executed. This makes that change.
=> Avoid using standin runtime type to avoid memory leak

doc/rst/platforms/infiniband.rst
Updates InfiniBand documentation to reflect changes made over the past few days.
=> Update InfiniBand documentation

doc/rst/technotes/static.rst
This PR adjusts documentation to include the sharing kinds introduced in https://github.com/chapel-lang/chapel/pull/25038.
=> Update documentation for static variables

doc/rst/technotes/index.rst, doc/rst/technotes/remote.rst
This PR adds documentation for the remote variables prototype added in https://github.com/chapel-lang/chapel/pull/25240. 
Reviewed by @ShreyasKhandekar -- thanks!
=> Add documentation for remote variables

CONTRIBUTORS.md
This is an update to CONTRIBUTORS.md to reflect those who've contributed to the Chapel 2.0 release.  Thanks to all who did!
=> Update CONTRIBUTORS.md for Chapel 2.1

util/cron/test-perf.chapcs.playground.bash
Switch the perf playground to a branch testing LLVM Region Vectorizer
=> Switch perf playground for llvm rv

util/chplenv/chpl_llvm.py
Improves the error message when `CHPL_TARGET_COMPILER=llvm` and `CHPL_TARGET_CC/CXX` is not a clang-based compiler.
For example
```
> export CHPL_TARGET_COMPILER=llvm
> export CHPL_TARGET_CC=gcc
> printchplenv
Error: 'gcc' is not clang and cannot be used with LLVM
```
This PR also cleans up the mismatching version errors slightly.
=> Improve chplenv errors for CHPL_TARGET_COMPILER=llvm

util/pastPerformance/testReleasesPerformance, util/test/perf/perfgraph.js
This is similar to PRs done in previous releases such as: https://github.com/chapel-lang/chapel/pull/24647.
=> Performance graph updates for 2.1.0

compiler/AST/symbol.cpp, compiler/codegen/cg-expr.cpp, compiler/include/symbol.h, runtime/include/chpl-comm-compiler-macros.h, runtime/include/chpl-mem.h, runtime/include/sys_basic.h, runtime/src/chpl-gpu.c, runtime/src/comm/none/comm-none.c, test/llvm/inlining/no-get-put.notest, test/llvm/inlining/no-get-put.prediff
This is a followup to https://github.com/chapel-lang/chapel/pull/25278 and implements @mppf's requested cleanups to the approach taken in that PR.
Testing
=> Cleanup always inline code for GET/PUT

util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash
Stop using multi-locale playground
=> Stop using ML playground

util/build_configs/cray-internal/setenv-xc-x86_64.bash, util/cron/common-arkouda.bash, util/cron/common-llvm.bash, util/cron/common-native-gpu.bash, util/cron/common-python.bash, util/cron/common-whitebox.bash, util/cron/common.bash, util/cron/load-base-deps.bash, util/cron/test-cray-xc-gpu-arkouda.bash, util/cron/test-gpu-rocm.bash, util/cron/test-gpu-rocm.gasnet.bash, util/cron/test-perf.gpu-rocm.bash
For https://github.com/Cray/chapel-private/issues/6478
=> Update test paths `/cray/css/users/chapelu` -> `/hpcdc/project/chapel`

util/cron/historify-logs, util/cron/nightly
For https://github.com/Cray/chapel-private/issues/6476.
Follow up to https://github.com/chapel-lang/chapel/pull/25434.
=> Update some missed `/cray/css` paths

test/mason/mason-help-tests/masonHelpTests.good
Fix an inadvertent change to the good file for MasonHelpTest [here](https://github.com/chapel-lang/chapel/pull/25427/files).
=> fix masonHelpTest good file

test/classes/generic/explicit-generic-nilable-prefix.chpl, test/classes/generic/explicit-generic-nilable-prefix.good, test/classes/generic/explicit-generic-nilable-suffix.chpl, test/classes/generic/explicit-generic-nilable-suffix.good
The 'design' aspect of the issue is not resolved, but the 'bug' aspect is. These tests lock in that it's possible to write a generic, nilable-specific class, but a separate discussion should probably be had about which we prefer (first, second, both).
=> Add regression tests for #13540

test/studies/lsuHeat/heat_ghost_sync.skipif, test/studies/lsuHeat/heat_queue_sync.skipif, test/studies/lsuHeat/sliceCopyCompilerError.bad, test/studies/lsuHeat/sliceCopyCompilerError.chpl, test/studies/lsuHeat/sliceCopyCompilerError.compopts, test/studies/lsuHeat/sliceCopyCompilerError.future, test/studies/lsuHeat/sliceCopyCompilerError.skipif
Two new tests added in https://github.com/chapel-lang/chapel/pull/22391: `studies/lsuHeat/heat_ghost_sync` and `studies/lsuHeat/heat_queue_sync` were failing to compile in the `--baseline` testing config.
This PR skips those tests for baseline.
It also adds a future to track to the underlying [issue](https://github.com/chapel-lang/chapel/issues/25570).
=> Skip failing LSU heat tests in baseline config

test/param/paramSizedIntInModule.1.good, test/param/paramSizedIntInModule.2.good, test/param/paramSizedIntInModule.chpl, test/param/paramSizedIntInModule.compopts
Closes #11645
The bugs described in the issue are no longer present on `main`. This PR adds a test to ensure this continues to work, so that the issue can be closed.
=> Add a regression test for #11645

util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash
We are considering turning const domain localization optimization on by default. This PR adds that branch on the perf playground to test its impact.
Filing on behalf of @bradcray
=> Put Brad's domain localization optimization on perf playground

test/optimizations/arrayViewElision/avoidExtraCalls.no-local.good, test/optimizations/arrayViewElision/rangeVsDomain.no-local.good, test/optimizations/arrayViewElision/rankChanges.no-local.good, test/optimizations/arrayViewElision/remoteDR.no-local.good, test/optimizations/arrayViewElision/slices-1d-domain.no-local.good, test/optimizations/arrayViewElision/slices-1d-range.no-local.good, test/optimizations/arrayViewElision/slices-2d-domain.no-local.good, test/optimizations/arrayViewElision/slices-2d-range.no-local.good
AVE tests added in https://github.com/chapel-lang/chapel/pull/24390 needed no-local good files. This PR adds those.
Test:
=> Add no-local good files for AVE tests

.github/workflows/CI.yml, util/test/check_perf_graphs.py, util/test/start_test.py
Reverts chapel-lang/chapel#25601
Un-reverting https://github.com/chapel-lang/chapel/pull/25461 with the experiment in chapel-lang/chapel#25601 done.
=> Revert "Revert "Add CI to check for bad performance tests""

frontend/lib/resolution/scope-queries.cpp, frontend/test/resolution/testModuleInitOrder.cpp
Closes https://github.com/chapel-lang/chapel/issues/25620.
Despite its name, the `modulesNamedInUseOrImport` function sometimes allows enums in (if they are `use`d or `import`ed). Since this is occasionally -- but not always -- guarded against in existing code, I assume that the intention was to keep the function true to its name, and to always exclude non-modules. So, I've generalized the check to cover all cases.
Reviewed by @ShreyasKhandekar and @dlongnecke-cray -- thanks!
=> Only list named modules (not named enums) in `modulesNamedInUseOrImport`

test/studies/lcals/LCALSMain.chpl, test/studies/lcals/LCALSMain.good
Fixes .good file mismatch caused by https://github.com/chapel-lang/chapel/pull/25142
Tested locally that `start_test test/studies/lcals/LCALSMain.chpl` works.
=> Fix good file mismatch in LCALS

test/CC-GRAPHFILES, test/GRAPHFILES, test/ML-GRAPHFILES
Updates the paths to the Sort module graph files, which were updated in https://github.com/chapel-lang/chapel/pull/25699
=> Update graph files after moving tests

util/cron/create_release_aptrpm.bash, util/packaging/common/build_helpers.sh
Adds a few helpers to the build scripts for the packaging builds to help with nightly testing
=> Add helpers to do native packaging builds

modules/dists/HashedDist.chpl
Fixes the summary line for HashedDist for issue #25667.
=> Fix summary line for HashedDist

util/cron/load-base-deps.bash
Resolves https://github.com/Cray/chapel-private/issues/6405.
To be merged after https://github.hpe.com/hpe/hpc-chapel-ci-config/pull/1164 adds the pinoak install and it completes successfully
[unlikely to break in a way review would catch, not reviewed]
=> Use Spack install of dependencies on Pinoak

test/gpu/native/studies/math/mathKernels.suppressif
Fixes a suppressif added to use the correct syntax
=> Fix the suppressif for a test

util/packaging/apt/debian11-gasnet-udp/Dockerfile.template, util/packaging/apt/debian11-gasnet-udp/control.template, util/packaging/apt/ubuntu24-gasnet-udp/Dockerfile.template, util/packaging/apt/ubuntu24-gasnet-udp/control.template, util/packaging/apt/ubuntu24-ofi-slurm/Dockerfile.template, util/packaging/apt/ubuntu24-ofi-slurm/control.template, util/packaging/rpm/fc37-gasnet-udp/Dockerfile.template, util/packaging/rpm/fc37-gasnet-udp/spec.template, util/packaging/rpm/fc38-gasnet-udp/Dockerfile.template, util/packaging/rpm/fc38-gasnet-udp/spec.template, util/packaging/rpm/fc39-gasnet-udp/Dockerfile.template, util/packaging/rpm/fc39-gasnet-udp/spec.template, util/packaging/rpm/fc40-gasnet-udp/Dockerfile.template, util/packaging/rpm/fc40-gasnet-udp/spec.template
Adds new multi-locale package configurations for various OSes
- GASNet+udp
- debian 11
- fedora 37
- fedora 38
- fedora 39
- fedora 40 
- ubuntu 24
- OFI+slurm
- ubuntu 24
=> Add more multi-locale package configurations

test/ANNOTATIONS.yaml
- regression from qthreads update and patch to fix it
- note change in testing machine for 16-node xc
=> add graph annotations (Aug 29, 2024)

test/library/packages/ParallelIO/delimIter.chpl
Following, https://github.com/chapel-lang/chapel/pull/25730, `/test/library/packages/ParallelIO/delimIter.chpl` was failing intermittently due to the test containing remote updates to a parallel map (which `map` does not support). This PR fixes the failure by adding an on-clause around the map updates.
=> Fix failing readDelmited test

frontend/lib/resolution/resolution-types.cpp, frontend/test/resolution/testMethodCalls.cpp
Closes https://github.com/Cray/chapel-private/issues/6673; see the regression test added by this PR for details.
=> Fix "generic field looks concrete" warning with inheritance

test/arrays/sparse/copyRemoteSparse-cs.good, test/arrays/sparse/copyRemoteSparse.good
The change had resulted in less communication (yay!)
Checked a fresh version of the tests with the update
=> Update the expected output for these tests after fixing const varargs checking

test/ANNOTATIONS.yaml
Annotations impacting array transfer performance:
```
8/19/24:
- Array transfer perf fix (Bears-R-Us/arkouda#3671)
8/27/24:
- Fix performance regression in to_ndarray (Bears-R-Us/arkouda#3697)
```
=> Arkouda annotations for array transfer performance

util/cron/common-perf-hpe-apollo-hdr.bash, util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.fast.colo.bash
Fix GASNet co-locale performance test scripts.
=> Fix GASNet co-locale performance test scripts

doc/rst/language/spec/locales.rst, doc/rst/technotes/remote.rst
This PR removes some limitations that were fixed in 2.2, and adjusts the spec section on remote variables to not say they're not implemented.
=> Update documentation for remote variables

CONTRIBUTORS.md
This is a refresh to the list of contributors to the Chapel 2.2 release relative to Chapel 2.1
=> Contributors updates for Chapel 2.2

CHANGES.md
This is the (reasonably complete) list of CHANGES for Chapel 2.2.  Thanks to everyone for all the hard work!
=> CHANGES.md for Chapel 2.2

util/cron/create_release_aptrpm.bash
Adds CHPL_TARBALL_LOCATION to nightly test script to aid release testing
=> Add CHPL_TARBALL_LOCATION to nightly test script

util/pastPerformance/testReleasesPerformance, util/test/perf/perfgraph.js
This would be similar to performance graph updates in previous releases like: https://github.com/chapel-lang/chapel/pull/24647 and https://github.com/chapel-lang/chapel/pull/25371.
=> Performance graph updates for 2.2

test/chplcheck/activerules.good
Add missing line to .good file after making a rule the default
[Trivial - not reviewed]
=> Add missing line to .good file

doc/util/versionButton.php
This is our standard update once the default docs are updated to the new release.
=> Update docs menu to reflect that 2.2 is now the default

frontend/test/resolution/testProcThis.cpp
This adds tests to check the behavior of resolving `this` in `begin` and `coforall` blocks. A previous PR resolved https://github.com/Cray/chapel-private/issues/6161 as a side effect, and this PR just adds tests for the behavior from the OP.
=> add dyno tests to lock in resolution of this in begin, coforall

util/cron/test-perf.chapcs.playground.bash
Stop using perf playground for LLVM RV
=> Stop using playground

test/gpu/native/examples/michael-jhu/stream.chpl, test/gpu/native/examples/michael-jhu/stream.good
This PR adds an example Michael will be using in his slides for GPU programming. I think that slide is cool to have in other upcoming talks, too. So, I wanted to lock the behavior.
=> Add an example GPU snippet as a test to lock behavior

test/functions/ferguson/spec-insn-method-no-this.bad, test/functions/ferguson/spec-insn-method-no-this.chpl, test/functions/ferguson/spec-insn-method-no-this.good, test/functions/ferguson/spec-insn-type-method-no-this.bad, test/functions/ferguson/spec-insn-type-method-no-this.chpl, test/functions/ferguson/spec-insn-type-method-no-this.future, test/functions/ferguson/spec-insn-type-method-no-this.good
Adds new futures for #26083
Tested that futures pass locally
=> Add future for #26083

test/classes/methods/nested-method-implicit-field-access.bad, test/classes/methods/nested-method-implicit-field-access.chpl, test/classes/methods/nested-method-implicit-field-access.future
This PR adds a .future test for issue #26088.
=> Add a test for implicit this. in nested method

test/ANNOTATIONS.yaml
- Add Arkouda related annotations related to Array Transfer Regression
- Fix date on annotation related to regression of mandelbrot-complex
- And add annotation for fix to mandelbrot-complex
=> annotations update

runtime/src/comm/ofi/comm-ofi.c
Modify `amPutDone` so that the PUT of the "done" indicator is non-blocking. This is invoked by an active message handler and notifies the sender that the active message has completed. There is no need for the active message handler to wait for the PUT to complete because, by definition, the active message has completed so there is nothing to be performed after the PUT. One complication is that the transmit context must be progressed; normally it would be progressed while waiting for the PUT to complete. Instead, the transmit context is progressed either when it is freed, or during shutdown, whichever comes first, unless it is the transmit context for the active message thread in which case it is progressed continually by that thread.
As a consequence of these changes, RMA PUT injection …
=> Make amPutDone non-blocking

runtime/src/gpu/amd/gpu-amd.c
This slipped through the cracks in PR https://github.com/chapel-lang/chapel/pull/26113, likely because I didn't rebase my branch on a new version of `main` and test it.
=> Fix AMD GPU logical to physical ID mapping

test/gpu/native/studies/chai/tests/multiLocaleInfSharded.good
Update good file for `/test/gpu/native/studies/chai/tests/multiLocaleInfSharded.chpl` to reflect changes made to ChAI's multi-locale distribution in: https://github.com/chapel-lang/ChAI/pull/6
=> Update ChAI sharded-inference test

frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testCast.cpp
Implement casting from `borrowed` to `unmanaged` class types in Dyno.
Supplants an [attempt at getting Dyno to use the existing module code implementation](https://github.com/chapel-lang/chapel/pull/26085) which was unsuccessful and I think would be infeasible. At time of writing this is also implemented in the compiler by the production compiler.
Resolves https://github.com/Cray/chapel-private/issues/6698.
Testing:
=> Implement `borrowed` to `unmanaged` cast in Dyno

test/ANNOTATIONS.yaml, util/test/check_annotations.py
Adds perf annotations for qthreads 1.21 changes
=> Add perf annotations for new qthreads changes

runtime/include/chpl-comm-strd-xfer.h
Adding non-blocking PUT support to `ofi` exposed several errors in how strided PUTs and GETs managed non-blocking handles.
=> Fix non-blocking handle management by strided RMA in CHPL_COMM=ofi

util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.fast.colo-nopshm.bash, util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.fast.colo.bash
Followup to https://github.com/chapel-lang/chapel/pull/26205 which did not fully fix the issue
=> Fix colocale perf graph generation again

modules/packages/ConcurrentMap.chpl, modules/packages/SortedMap.chpl, modules/standard/Map.chpl
I encountered unusual rendering issues in the `Map` module documentation, which I corrected. I then applied the fix to related map-based modules with the same issues, including `sortedMap` and `concurrentMap`. I checked afterwards that the generated documentation is fine.
=> Fix rendering issue in map-based modules doc

test/ANNOTATIONS.yaml
- unknown 16-node-xc performance drop on Veterans' Day
- asynchronous GETs on HPE Cray EX
=> Add annotations

compiler/resolution/cullOverReferences.cpp
A test I added in #26230:
```
test/classes/initializers/records/array-from-iterable-of-owned-tuples.chpl
```
exposed a bug in the `cullOverReferences` pass. This causes a failure in nightly ASAN testing. 
When accessing the _member_ of a tuple, we propagate its index to the left-hand side of an assignment. As a result, we are conflating the index of a tuple's field with the index _into_ that field (which can itself be a tuple). This can result in invalid array accesses.
I've tried for several hours to trigger this bug in a way that modifies users code. However, the `cullOverReferences` pass has too many special cases. The trickiness is that we need nested tuples (so that we can observe the indexing-into-the-field behavior), and these tuples need to contain references to arrays (because …
=> Fix memory bug in cullOverReferences

test/ANNOTATIONS.yaml
Annotate system dependencies for upgrade to LLVM 19
=> Annotate system dependencies for upgrade to LLVM 19

util/chplenv/chpl_gpu.py
This PR fixes several issues I noted while working on https://github.com/chapel-lang/chapel/pull/26267
- Most functions were using `os.environ.get` instead of `overrides.get`, this meant that gpu config variables could not be read from `chplconfig` files
- Several functions were missing `@memoize`, this did not effect correctness but could slow down `printchplenv`
- Explicitly setting `CHPL_GPU=none` and `CHPL_LOCALE_MODEL=gpu` caused internal errors
=> Fix several issues with chpl_gpu.py

modules/packages/Python.chpl, test/library/packages/Python/argPassingTest.comm-none.good, test/library/packages/Python/customType.comm-none.good
Fixes some new Python interop tests (added in https://github.com/chapel-lang/chapel/pull/26156) with COMM!=none. This is caused by a difference between Chapel's stdio and Python's stderr.
The difference is that Chapel does some extra work in the multi-locale case to make sure everything is printed on the right locales, whereas Python has no native concept of locality. In this case, this just manifests as changing whether the Python output comes first or last.
This PR also switches the interpreter to be explicitly an "isolated" interpreter, to prevent potential issues with Python setting up its stdio.
Tested that all Python tests pass with COMM=none and COMM=gasnet
=> Fix new Python interop tests with COMM!=none

doc/rst/usingchapel/chplenv.rst
Add CHPL_NETWORK_ATOMICS documentation
Resolves https://github.com/Cray/chapel-private/issues/6903.
=> Add CHPL_NETWORK_ATOMICS documentation

test/ANNOTATIONS.yaml, util/test/check_annotations.py
Add extra annotation for some GPU configs
=> Annotate llvm upgrade for gpu configs

CONTRIBUTORS.md
This updates our contributors list to reflect those who contributed to Chapel 2.3.  Welcome, and thanks, @Snektron and @chenrui333!
=> CONTRIBUTORS.md updates for Chapel 2.3

CHANGES.md
Here are all the (most noteworthy) CHANGES we got done for Chapel 2.3.  Thanks for the great work everyone!
=> CHANGES.md updates for Chapel 2.3

doc/util/versionButton.php
This updates the website's docs version menu to reflect tomorrow's 2.3 release
=> Update docs version menu for 2.3 release

modules/packages/Python.chpl
Adds support for respecting `PYTHONPATH`, which is an environment variable typically used for Python installs.
Prior to this PR, `PYTHONPATH` was not respected at all. After this PR, it will be appended to `sys.path`.
=> Make Python module respect PYTHONPATH

test/ANNOTATIONS.yaml
Adds annotations for https://github.com/chapel-lang/chapel/pull/26368
=> Add annotations for improvements to log with `--no-checks`

test/chplenv/printchplbuilds/README, test/chplenv/printchplbuilds/printchplbuilds-check.prediff, test/chplenv/printchplbuilds/printchplbuilds-print1.prediff, test/chplenv/printchplbuilds/printchplbuilds.prediff
Updates a test that looked for CHPL_MEM to CHPL_TARGET_MEM. This is a new test that was added just before changing CHPL_MEM to CHPL_TARGET_MEM.
Also adds some comments describing what each test does
=> Update to CHPL_MEM to CHPL_TARGET_MEM in a test case

test/studies/shootout/submitted/knucleotide3.chpl, test/studies/shootout/submitted/knucleotide3.good, test/studies/shootout/submitted/knucleotide3.txt.good, test/studies/shootout/submitted/knucleotide4.chpl, test/studies/shootout/submitted/knucleotide4.good, test/studies/shootout/submitted/knucleotide4.txt.good
This updates our local snapshots of our submitted knucleotide codes to reflect recent changes to the (now stable) Sort module.
=> Update submitted knucleotide versions to work with Chapel 2.3

doc/rst/usingchapel/launcher.rst
Adds some missing documentation on the slurm launcher about some slurm launcher specific flags and environment variables
=> Adding missing documentation for some slurm launcher specifc flags and environment variables

third-party/qthread/README
Updates the readme for qthreads to reflect current patches
=> Update qthread readme

runtime/src/comm/ofi/comm-ofi.c
Remove functionality deprecated by `libfabric 2.x`. Specifically, remove support
for poll sets and wait sets. Support for these was provider-specific, so the
runtime can function without them. The `cxi` provider didn't support them, so
typically we wouldn't use them anyway.
Also removed the `FI_MR_BASIC` memory registration mode, which is deprecated.
`FI_MR_BASIC` was equivalent to specifying `FI_MR_VIRT_ADDR`, `FI_MR_ALLOCATED`,
and `FI_MR_PROV_KEY`, and was only defined for backwards compatibility with
versions 1.4 and earlier. We specify those three modes so FI_MR_BASIC was
redundant.
Resolves https://github.com/Cray/chapel-private/issues/7005.
Resolves https://github.com/Cray/chapel-private/issues/6828.
=> Port to libfabric 2.x

test/gpu/native/assertOnFailToGpuizeAttr.1.good, test/gpu/native/assertOnFailToGpuizeAttr.2.good, test/gpu/native/assertOnFailToGpuizeAttr.3.good
Trivial, will not be reviewed. Introduced by https://github.com/chapel-lang/chapel/pull/26492.
=> Fix nightly failures in GPU test due to changed line numbers

modules/packages/Python.chpl
Fixes more issues with 32 bits with the Python module
=> Fix more 32 bit Python module issues

modules/packages/Python.chpl, modules/packages/PythonHelper/ChapelPythonHelper.h, test/library/packages/Python/correctness/moduleFromString.chpl
Grabbag of Python module improvements, there are no behavior changes or new features in this PR
- cleanup and improve docs
- Adds C version constants for later use
- rewrites a test to use multi-line strings
- remove a todo that I believe we will never be able to resolve
=> Grabbag of Python module improvements

test/arrays/errors/promotedSizeMismatch.chpl, test/arrays/errors/promotedSizeMismatch.good
I believe that PR https://github.com/chapel-lang/chapel/pull/17947 is the one that resolved this test case.
Resolves #15914
=> Add the test in #15914, which is now resolved

test/types/range/arrayOfRanges.bad, test/types/range/arrayOfRanges.chpl, test/types/range/arrayOfRanges.future
Sigh . . .
Fresh checkout of test works
=> Restore missing keyword and resolve the future

frontend/include/chpl/resolution/ResolvedVisitor.h, frontend/lib/resolution/Resolver.cpp, frontend/test/resolution/testLoopIndexVars.cpp
Closes https://github.com/Cray/chapel-private/issues/6740.
```Chapel
proc foo(x) {
compilerWarning(x.type : string);
}
proc helper(xs ...?k) {
for x in xs {
foo(x);
}
}
helper(1, "red", 4.2);
```
Produces:
```
─── warning in heterotup.chpl:7 [UserDiagnosticEmitWarning] ───
Int(64)
|
7 |     foo(x);
|
─── warning in heterotup.chpl:7 [UserDiagnosticEmitWarning] ───
String
|
7 |     foo(x);
|
─── warning in heterotup.chpl:7 [UserDiagnosticEmitWarning] ───
Real(64)
|
7 |     foo(x);
|
```
I implemented this by piggybacking off `param` loop iteration. The fundamental principle is the same (in fact, you can consider iteration over heterogeneous tuples to be by a `for param` over the tuple's bounds, accessing each individual element), and we already have a convenient way to note several …
=> Dyno: enable Iteration over heterogenous tuples

compiler/include/driver.h, compiler/main/driver.cpp, frontend/lib/resolution/call-graph.cpp, frontend/lib/resolution/default-functions.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/resolution-types.cpp
@benharsh has developed a number of small fixes for the resolver while working on testing the spec. This PR simply updates the fixes for a newer `main` branch and makes minor tweaks for consistency with the rest of the codebase.
=> Apply Ben's numerous minor fixes

CHANGES.md
This adds a mention of the 2.3.1 release to CHANGES.md describing the motivation for it and optimistically listing today as the date.  @jabraham17 reviewed and OK'd the wording.
=> Add description of the 2.3.1 release

test/optimizations/arrayViewElision/distributedToLocal.no-local.good, test/optimizations/arrayViewElision/localToDistributed.no-local.good
I forgot to add `no-local.good` files for two relatively new tests, which caused nightly failures. This PR adds those.
Tested locally.
=> Add missing no-local good files for AVE tests

test/studies/arkouda/sub_test
=> Fix venv typo in sub_test

util/test/prediff-for-gasnet
Use bytes string in gasnet prediff
[Trivial - not reviewed]
=> Use bytes string in gasnet prediff

doc/rst/language/spec/memory-consistency-model.rst
After a recent system upgrade, the spec test `atomicSpinWait.chpl` started timing out in a valgrind configuration with some regularity, likely due to the busy-wait starving other tasks from being able to run on the processor.  Here, I've rewritten that section to mention the potential of starvation earlier, and writing the testable code in the "right/preferred" way.
=> Rewrite busy-wait code examples and text to avoid starvation/timeouts

test/library/packages/HDFS/hdfsNumbers.suppressif, test/library/packages/HDFS/hello-hadoop.suppressif
We've asked users if they want us to keep this package, with a deadline of March 4th.  Suppress the failures until that decision has been made
Validated the behavior in a setting where they don't work (my laptop).
=> Suppress the failures for these HDFS tests for now

runtime/src/chpl-cache.c
In writing PR #26746, I enabled some off-by-default debug printing code in `chpl-cache.c` & it needed to be updated in order to compile. Other than updating these debug prints so that they work, this PR adds a comment to describe one of the big ways in which the prefetch counters are currently inaccurate.
This PR only changes comments and off-by-default debug prints.
Reviewed by @jhh67 - thanks!
=> Fix up off-by-default debug printing in chpl-cache.c

util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash
Fix date in perf playground, using 2 digit years
=> Fix date in perf playground

util/packaging/docker/github-ci/Readme.md
Update the README for building the CI docker image to reflect the current PATHS
=> Update README for building the CI docker image

util/chplenv/chpl_llvm.py
If clang is already set up with a config file that has some of these options we should avoid overriding them.
=> Avoid Overriding Clang Sysroot

util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash
Performance testing of GASNet-2025.2.0-snapshot before merging into main.
=> Performance test GASNet-2025.2.0-snapshot

runtime/src/comm/gasnet/comm-gasnet-ex.c
The GASNet shared memory segment created by the Chapel runtime at startup has a big impact on node memory utilization, and its size is an important piece of information for triaging any OOM failure mode with `CHPL_COMM=gasnet`. This PR adds a new verbose message in startup, to address a lack of visibility into the size of this shared heap. The lack of a efficient means to print this information unnecessarily complicated some recent triage over Slack.
Example portion of the output from a run from `-nl 2x2 -v -v`, including the relevant new lines :
```
0: using core(s) 0-19 in socket 0
1: using core(s) 20-39 in socket 1
oversubscribed = False
QTHREADS: Using 20 Shepherds
QTHREADS: Using 1 Workers per Shepherd
QTHREADS: Guard Pages Enabled
QTHREADS: Using 8376320 byte stack size.
QTHREADS: …
```
=> Add GASNet segment size to verbose output

compiler/passes/convert-typed-uast.cpp
This PR fixes a bug that would cause `chpl --dyno-resolve-only` to crash because it expected a `FnSymbol*` for a `main()` function that had not actually been converted.
=> Stop generating AST for 'main()' under '--dyno-resolve-only'

test/library/packages/Python/examples/torch/myModel.skipif
Skip pytorch testing on darwin due to https://github.com/chapel-lang/chapel/issues/26886
=> Skip pytorch testing on darwin

doc/rst/platforms/udp.rst
Stuck an extra underscore into MASTERIP (understandably, I hope).
=> Fix a typo that I noticed while putting CHANGES.md entries together today

test/deprecated/Python/importModule.chpl
Adjusts a new test to make sure the Python output is properly flushed.
=> Make sure flush is called after printing from Python

tools/chpl-language-server/src/chpl-language-server.py, tools/chplcheck/src/rules.py
Fixes two edge case bugs in CLS/chplcheck. These are issues that most users will not hit, I only hit them because I have multiple versions of the Chapel std library open in the same editor.
=> Fix two edge case bugs in CLS/chplcheck

test/studies/arkouda/functions.bash, test/studies/arkouda/multidim.patch, test/studies/arkouda/sub_test, util/cron/test-hpe-apollo-hdr.arkouda.bash, util/cron/test-hpe-apollo-hdr.arkouda.release.bash
Add a patch to modify the registration configuration for multidimensional array support and enable testing on the Apollo test system.
=> Enable multidimensional array testing in Arkouda

util/cron/test-mimalloc.bash, util/cron/test-ml-mimalloc.bash
Adds two test configs that run the test suite with mimalloc
To be merged after https://github.com/chapel-lang/chapel/pull/26246
=> Add test configs for mimalloc

modules/packages/Python.chpl
Fix a few merge conflicts caused by https://github.com/chapel-lang/chapel/pull/27044 and https://github.com/chapel-lang/chapel/pull/27013
=> Fix a few Python module merge conflicts

LICENSE, third-party/README
Updates the third-party/readme and license after adding support for mimalloc
=> Update third-party/readme and license after adding support for mimalloc

util/cron/test-perf.chapcs.playground.bash, util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash
Switches the perf playgrounds to test libmvec being turned on
[Not reviewed]
=> Test using libmvec in the perf playground

frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testClasses.cpp
Closes https://github.com/Cray/chapel-private/issues/7332.
Previously, Dyno always instantiated parent class formals with the child class, which meant that the `Parent(X=?)` became Child(A, B), but this breaks disambiguation for generic formals. Specifically, after instantiations, both of the following overloads would look the same:
```Chapel
proc (Parent(?)).foo() {}
proc (Child(?)).foo() {}
```
In both cases, the `Child(A,B)` actual would be used as the instnatiating type, which would mean the two signatures being compared will be the same. This PR adjusts the logic to find the common parent (if any), and use that for instantiation.
=> Dyno: ensure formal `Parent(X=?)` with actual `Child(A, B)` becomes `Parent(A)`

doc/rst/technotes/libraries.rst
Make sure the correct library suffix for `--library --dynamic` is documented
=> Document the correct library suffix for `--library --dynamic`

util/cron/test-linux64-llvm20.bash
Adds a new test config for LLVM 20
=> Add a test config for LLVM 20

util/cron/test-perf.chapcs.playground.bash, util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash
Stop using perf playgrounds, experiments are done
=> Stop using perf playgrounds

test/library/standard/Debugger/breakpoint/useBreakpoint-gdb.suppressif, test/library/standard/Debugger/breakpoint/useBreakpoint-lldb.suppressif
Adda suppressifs for debugger tests with `--no-local`
=> Add suppressifs for debugger tests with --no-local

.github/workflows/meetings.yml
* Completed bolding of Teams link
* Added missing space between time and "PT"
=> Fix a few typos that slipped into my last edits

test/ANNOTATIONS.yaml
Annotates changes to the backend compiler for the majority of our test systems.
=> Annotate system LLVM upgrade

doc/rst/usingchapel/prereqs.rst
Updates the prereqs.rst docs for LLVM 20
=> Update prereqs docs for LLVM 20

test/llvm/debugInfo/gdb/targetVar.suppressif, test/llvm/debugInfo/lldb/targetVar.suppressif
Adds a missing suppressif for new debugger tests
=> Add missing suppressif for new debug tests

doc/rst/usingchapel/chplenv.rst
Adds mimalloc to the list of allocators in chplenv.rst
=> Add mimalloc to the list of allocators in chplenv.rst

doc/rst/tools/chpl-language-server/chpl-language-server.rst, doc/rst/tools/chplcheck/chplcheck.rst, tools/chplcheck/src/rules.py
Improves the chplcheck and chpl-language-server docs by fixing some typos and adding more information to the LineLength rule
=> Improve chplcheck and chpl-language-server docs

doc/rst/technotes/index.rst, doc/rst/technotes/optimization.rst, doc/rst/usingchapel/executing.rst, test/technotes/optimization/aggregation.chpl, test/technotes/optimization/aggregation.execopts, test/technotes/optimization/aggregation.good, test/technotes/optimization/bulk.chpl, test/technotes/optimization/bulk.execopts, test/technotes/optimization/bulk.good
This PR adds a technote about optimizing Chapel programs with a focus on distributed-memory performance. It is a draft & I expect that it will need to be updated with more experiences and examples in the future.
Reviewed by @DanilaFe, @e-kayrakli, and @ShreyasKhandekar - thanks!
=> Optimization Technote

CHANGES.md
=> Remove an extra newline in the `New Package Module Features` CHANGES section

test/library/packages/Python/correctness/arrays/arrayTypes.good, test/library/packages/Python/correctness/arrays/arrayTypes.prediff
Prediff a Python error message since it can vary between patch versions of Python
=> Prediff Python error message output

util/chplenv/chpl_sanitizers.py
Moves the error checking from `make/compiler/Makefile.sanitizers` to `chpl_sanitizers.py` to make the errors appear sooner in compilation for users
=> Move the errors from `make/compiler/Makefile.sanitizers` to `chpl_sanitizers.py`

test/multilocale/deitz/needMultiLocales/raCommCheck.chpl
We're seeing some ongoing failures in a testing configuration that are hard to recreate, so I'm adding some extra debugging output to hopefully give us a hint as to what's going on.
=> Add debug output for raCommCheckLCG

test/multilocale/deitz/needMultiLocales/raCommCheck.chpl
Follow up to https://github.com/chapel-lang/chapel/pull/27460
That PR somehow made the errors go away. I'm going to continue this on a separate branch that will be pulled into testing.
=> Revert raCommCheck changes

third-party/chpl-venv/chpldoc-requirements3.txt
Bring in the latest version of chapeldomain, 0.0.38
=> Bring in latest version of chapeldomain

util/cron/common-arkouda.bash
Fixes the usage of the wrong syntax in bash script
=> Fix bash syntax in nightly config

frontend/include/chpl/uast/Include.h, frontend/include/chpl/uast/all-location-maps.h, frontend/lib/parsing/bison-chpl-lib.cpp, frontend/lib/parsing/chpl.ypp, frontend/lib/uast/Include.cpp, tools/chapel-py/src/method-tables/uast-methods.h, tools/chapel-py/src/resolution.cpp, tools/chpl-language-server/src/chpl-language-server.py
Adds support to chapel-py/chpl-language-server for goto-definition on `include module ...`
=> Add support for goto-def on `include module ...`

frontend/lib/resolution/default-functions.cpp
Some built-in hash functions are located in `ChapelHashing`. Generating a default function on top of those causes an ambiguity.
=> Dyno: Look in more places for hash functions before generating them

test/types/range/elliot/anonymousRangeIter.expectedGenCode, test/types/range/elliot/anonymousRangeIter.prediff
Updates the good output for a test after https://github.com/chapel-lang/chapel/pull/27531 changed the generated code.
=> Update generated code anonymousRangeIter test

test/technotes/doc-examples/MainProcExample1.prediff
Improves prediff for a test sensitive to exec time flags
=> Improve prediff to also catch memLeaksLog

doc/rst/conf.py, doc/rst/developer/chips/conf.py, doc/rst/usingchapel/prereqs.rst, test/chpldoc/compflags/folder/save-sphinx/saveSphinxInDocs.doc.allowed.good, test/chpldoc/compflags/folder/save-sphinx/saveSphinxInDocs.doc.prediff, third-party/chpl-venv/Makefile, third-party/chpl-venv/c2chapel-requirements.txt, third-party/chpl-venv/chpldoc-requirements1.txt, third-party/chpl-venv/chpldoc-requirements2.txt, third-party/chpl-venv/chpldoc-requirements3.txt, third-party/chpl-venv/chpldoc-sphinx-project/source/conf.py, third-party/chpl-venv/cls-test-requirements.txt, third-party/chpl-venv/test-requirements.txt, tools/chapel-py/pyproject.toml
[reviewed by @jabraham17]
With this change, chpldoc will no longer support Python 3.9.  start_test, c2chapel, and the language server can still do so, but for simplicity we're not allowing their virtualenv to be built with 3.9 any more.
Every package, except Sphinx, is now the most recent version it could be.  Sphinx is not, due to a desire to continue to support Python 3.10 on some platforms.
For start_test, updates:
- filelock from 3.16.1 to 3.18.0
- argcomplete from 3.5.1 to 3.6.2
- setuptools from 75.1.0 to 80.9.0
- junitparser from 3.2.0 to 4.0.2
For CLS, updates:
- pytest from 8.3.3. to 8.4.1
For c2chapel, updates:
- pycparser from 2.20 to 2.22
- pycparserext from 2021.1 to 2024.1
For chapel-py, updates:
- attrs from 24.2.0 to 25.3.0
- cattrs from 24.1.2 to 25.1.1
- typeguard from …
=> Update python deps

util/cron/test-perf.hpe-apollo-hdr.arkouda.playground.bash
Turn on the arkouda playground to see if it works
=> Turn on the arkouda playground

util/cron/load-base-deps.bash
Adds a new hostname to a dependency script
=> Add new hostname to dependency list

util/cron/common-gpu-nvidia-hpe-cray-ex-cuda-12.bash, util/cron/test-gpu-ex-cuda-12.bash, util/cron/test-gpu-ex-cuda-12.colocales.bash, util/cron/test-gpu-ex-cuda-12.interop.bash, util/cron/test-gpu-ex-cuda-12.ofi.bash, util/cron/test-gpu-ex-cuda-12.specialization.bash, util/cron/test-perf.gpu-ex-cuda-12.bash, util/cron/test-perf.gpu-ex-cuda-12.um.bash
Switches nightly testing to use CUDA 12.8
=> Switch nvidia nightly testing to use CUDA 12.8

test/classes/delete-free/borrow-bug-27827.chpl
Fixes a double free I wrote in a new test for a bug I fixed
=> Fix double free in a new test

util/packaging/homebrew/chapel-main.rb
Temporarily drops support for SMP from the homebrew forumla
=> Drop smp support from the homebrew formula

compiler/resolution/preFold.cpp
Ensure will compile as intended.
Closes #27876
=> Fix aliasing
