test/classes/vass/no-instance-for-arg-type.bad
This PR fixes a test's `.bad` file that was modified during the
parser replacement and not updated after a fix was implemented.
The test in question is `test/classes/vass/no-instance-for-arg-type`
TESTING:
=> test: fix .bad file for one test

compiler/main/driver.cpp, util/buildRelease/install.sh, util/chplenv/third_party_utils.py
This PR makes 3 improvements motivated by the effort to create an Arch Linux AUR package:
* adjusts `get_bundled_link_args` in `util/chplenv/third_party_utils.py` to fix a problem with falling back on a `-l` flag if the `.la` file for the library is missing since the AUR install process removes the `.la` files. This fallback logic originated in #15000 but was disrupted by later changes to that function.
* adjusts `chpl --print-chpl-settings` to print out all internal settings if `--devel` is also passed (to make it easier to debug problems with chplenv scripts)
* adjusts `install.sh` to only consider it a staged install if the stage directory is not the empty string (since the Makefile calling it always passes `--stage=${DESTDIR}`. As far as I know, this does not change the behavior of …
=> Fix problem with make install for AUR package

compiler/dyno/include/chpl/parsing/parsing-queries.h, compiler/dyno/include/chpl/queries/Context-detail.h, compiler/dyno/include/chpl/queries/Context.h, compiler/dyno/include/chpl/queries/query-impl.h, compiler/dyno/include/chpl/resolution/scope-types.h, compiler/dyno/include/chpl/uast/AstNode.h, compiler/dyno/include/chpl/uast/prim-ops-list.h, compiler/dyno/lib/parsing/parsing-queries.cpp, compiler/dyno/lib/resolution/scope-queries.cpp, compiler/dyno/lib/resolution/scope-types.cpp, compiler/dyno/lib/uast/AstNode.cpp, compiler/dyno/test/parsing/testParsingQueries.cpp, compiler/dyno/test/resolution/testInteractive.cpp, compiler/dyno/test/resolution/testScopeResolve.cpp, compiler/main/driver.cpp
The main goal of this PR is to adjust dyno to support standard and internal modules.
* Removes `partialResult` from QueryMapResult. It has been unused since #19765 and I had just forgotten to remove it there.
* Adds support for setting the bundled (`modules/`) and internal module (`modules/internal`) search paths and the ability to query if an ID is in a bundled or internal module. Adjusted some of these module search path functions to return UniqueString rather than `std::string` since comparing them is useful. Added a helper function `setupModuleSearchPaths` that does the right setup calls with the configuration as arguments.
* Adjusts the dyno use/import resolver to automatically use ChapelStandard in modules that aren't internal modules. To support that, Scope now includes a bool …
=> dyno: automatically use ChapelStandard

compiler/dyno/lib/resolution/resolution-queries.cpp
This PR fixes a compilation warning-as-error from clang 14 from code added in PR #19765.
=> Fix clang 14 warning

compiler/dyno/include/chpl/uast/AggregateDecl.h, compiler/dyno/lib/uast/AggregateDecl.cpp
dyno: Adjust assertion for AggregateDecl (#19886)
Adjust an assertion which checks body elements in AggregateDecl
so that it accepts TypeDecl and EmptyStmt, which are both
valid children (e.g., `enum` and `;` respectively).
=> dyno: Adjust assertion for AggregateDecl

test/extern/ferguson/mismatch-errors/mismatch-ri-iv.bad, test/extern/ferguson/mismatch-errors/mismatch-ri-iv.prediff, test/extern/ferguson/mismatch-errors/mismatch-riv-iv.bad, test/extern/ferguson/mismatch-errors/mismatch-riv-iv.prediff
These tests were expecting an internal error but then now trip an assert
instead. Update the .bad files.
=> Update .bad files for two mismatch-errors futures

util/cron/test-valgrind.bash, util/cron/test-valgrindexe.bash
clang/llvm 14 started generated dwarf5 debug info by default and that's
not compatible with the version of valgrind we use. Until we get a
chance to upgrade, pin to clang/llvm 13.
For more info see Cray/chapel-private#3373
=> Use llvm 13 for valgrind testing

compiler/passes/convert-uast.cpp, test/performance/vectorization/vectorizeOnly/vectorizeOnlyWithIntents.bad, test/statements/errors/foreachTaskIntents.chpl, test/statements/errors/foreachTaskIntents.good
Add error about foreach loops not supporting task intents (#19887)
The dyno parser supports parsing foreach loops with task intents,
but the old AST is not yet capable of supporting them. Add a
compile-time error stating that task intents are not yet supported
(though we intend to, see #18500).
=> Add error about foreach loops not supporting task intents

test/gpu/native/diags.good, test/gpu/native/diags.prediff, test/gpu/native/distArray/blockOutsideOnWorkaround.chpl, test/gpu/native/distArray/blockOutsideOnWorkaround.good
This PR adjusts two tests to be more portable w.r.t. amount of memory allocated
and parallelism. These seem to differ between personal workstations and the
nightly testing system.
=> Adjust two GPU tests to be more portable

compiler/AST/build.cpp, compiler/dyno/include/chpl/resolution/resolution-queries.h, compiler/include/build.h, compiler/include/convert-uast.h, compiler/passes/convert-uast.cpp
This PR enables the conversion process in convert-uast.cpp to:
* resolve the module to compute types etc
* convert types and params from the resolution result to the production AST
* set the types and param values when the resolution result is known
The optional resolution process within convert-uast.cpp is controlled by `shouldResolve` which currently just returns `false`.
To do so, I refactored a couple of functions in build.cpp so that the functionality could be more easily reused when including types in the conversion process.
=> dyno: optionally resolve and convert types in converter

test/extern/ferguson/mismatch-errors/mismatch-ri-iv.bad, test/extern/ferguson/mismatch-errors/mismatch-ri-iv.prediff, test/extern/ferguson/mismatch-errors/mismatch-riv-iv.bad, test/extern/ferguson/mismatch-errors/mismatch-riv-iv.prediff
This reverts commit 327f3049a8454b701a169cb20074c79972cc6284. The tests
are back to matching the old .bad files.
=> Revert "Update .bad files for two mismatch-errors futures"

compiler/dyno/include/chpl/uast/PragmaList.h, compiler/resolution/generics.cpp, modules/standard/Types.chpl
This is to address the test failures we see here:
https://chapel.discourse.group/t/cron-perf-cray-cs-hdr-arkouda/12773/13
In this PR https://github.com/chapel-lang/chapel/pull/19856 I moved a function (`isArrayValue`) from an internal module to a standard module.
To prevent inifite recursions we limit the number of times a generic function can be instantiated and present an error message if it exceeds this limit.  We exempt functions in internal (but not standard) modules from this limit.
It appears that `isArrayValue` is legitamatly instantiated an enormous number of times so in order to keep these tests running in this PR I introduce a pragma that lets us flag functions to be exempt from this check and exempt the `isArrayValue` function.
It may be worth spending more time to investigate …
=> Add fn exempt instantiation limit pragma and apply it to isArrayValue

test/gpu/native/diags.execopts, test/gpu/native/diags.good, test/gpu/native/diags.prediff, test/gpu/native/distArray/blockOutsideOnWorkaround.chpl, test/gpu/native/distArray/blockOutsideOnWorkaround.good
The `diags` test was failing due to the confusing nature of verbose memory
output. This PR adds `--memTrack` to the execopts of that tests to work around
that. We want to fix this confusing behavior soon. See
https://github.com/Cray/chapel-private/issues/3388.
The `test/gpu/native/distArray/blockOutsideOnWorkaround.chpl` test had too small
data, causing paralellism to be less than the number of cores on the nightly
testing machine. This is a trivial issue with a trivial fix.
Both tests pass on my workstation and the testing system.
=> Another attempt at fixing GPU test failures

modules/standard/IO.chpl, test/deprecated/IO/itemReader.chpl, test/deprecated/IO/itemReader.good, test/deprecated/IO/itemWriter.chpl, test/deprecated/IO/itemWriter.good, test/io/ferguson/io_test.good
After discussion on #19829 this merge will deprecate the ItemReader/Writer types and their methods without no-doc-ing anything.
Testing:
=> Deprecate both ItemReader and ItemWriter

util/cron/common-native-gpu.bash, util/cron/test-cray-cs-gpu-native-gasnet.bash, util/cron/test-cray-cs-gpu-native.bash
I would like to have nightly tests runs everything under `gpu/native` with `CHPL_COMM=gasnet`. This PR adds `util/cron/test-cray-cs-gpu-native-gasnet.bash` to run a job with this configuration.
=> Add cray-cs-gpu-native-gasnet configuration

util/buildRelease/install.sh, util/buildRelease/test_install.bash
Historically, mason was built into `tools/mason`, so that's where
our 'make install' command would try to install it from.  However,
in #16154, it was changed to build directly into `bin/[whatever]/`
causing `make install` to stop finding and copying it (except for
those of us who still had an ancient version of `tools/mason/mason`
lying around).
Here, I'm updating the make install script (`install.sh`) to copy
it from the correct location, and also adding a 'make mason' step
to our test of the installation logic, followed by a check to see
that it got put where expected to try and prevent this from happening
again in the future.
Resolves #19910.
=> Fix installation of mason

test/gpu/native/diags.prediff
With the new gasnet+gpu testing config, we get some more verbose
mem output from the comm layer for this test. This PR prediffs
those lines out.
=> Prediff some comm layer related memory allocations in a test

test/release/examples/benchmarks/isx/SKIPIF, test/studies/isx/SKIPIF
We're finding that the execution times for ISx are higher than we care to
spend on them in the GASNet/mpi configuration, resulting in us running
right up against the timeout in certain performance configurations.  This
PR adds SKIPIF files to the ISx directories when doing performance runs
using GASNet/mpi.
=> Skip ISX tests for GASNet + MPI

compiler/dyno/include/chpl/uast/Domain.h, compiler/dyno/include/chpl/uast/Reduce.h, compiler/dyno/include/chpl/uast/Scan.h, compiler/dyno/lib/parsing/ParserContext.h, compiler/dyno/lib/parsing/ParserContextImpl.h, compiler/dyno/lib/parsing/bison-chpl-lib.cpp, compiler/dyno/lib/parsing/chpl.ypp, compiler/dyno/lib/uast/Domain.cpp, compiler/dyno/lib/uast/Reduce.cpp, compiler/dyno/lib/uast/Scan.cpp, compiler/dyno/lib/uast/chpl-syntax-printer.cpp, compiler/passes/convert-uast.cpp, test/arrays/indexing/arrLitIndexing.bad, test/arrays/vass/literal-indexing.bad, test/extern/rename/renameViaParamExpr.bad, test/users/ferguson/histogram/reductionex_class.bad, test/users/ferguson/histogram/reductionex_record.bad
dyno: Fix bugs and revert changes to .bad files for futures (#19909)
When the dyno parser was turned on by default in #19816, we
preemptively adjusted the .bad files for some futures to clean up
test output before the merge.
Now that testing has settled down, revert the changes to .bad files
and fix bugs as needed in order to get failure modes to match.
Also fix several instances where we were incorrectly creating a
Domain instead of an array, and fix bugs in the converter for
associative arrays.
TESTING
=> dyno: Fix bugs and revert changes to .bad files for futures

test/parsing/bigifthenelse.chpl, test/parsing/bigifthenelse.future
As noted in the .future, large if-then-else statements like this seem
to cause our parser (dyno or traditional) to go off the rails in
surprising ways.  Using a select statement instead seems to work fine.
=> Add bug from Gitter related to large if-then-else statements

compiler/dyno/include/chpl/queries/ErrorMessage.h, compiler/dyno/lib/parsing/parser-yyerror.h, compiler/dyno/lib/parsing/parsing-queries.cpp, compiler/dyno/lib/queries/ErrorMessage.cpp, test/domains/sungeun/rect/at_operator.bad, test/parsing/BlockMissingClosingBrace.chpl, test/parsing/BlockMissingClosingBrace.good, test/users/rohanbadlani/bugs/bug1.bad
dyno: Fix bug that caused syntax errors to disappear (#19923)
Fix a bug which caused syntax errors not to propagate out of the
builder and into the compiler context. This caused programs
with syntax errors such as missing a closing brace to silently
compile.
Resolves #19922.
TESTING
=> dyno: Fix bug that caused syntax errors to disappear

modules/standard/DateTime.chpl, test/deprecated/datetimeMinusDate.chpl, test/deprecated/datetimeMinusDate.good, test/deprecated/datetimeTimeSinceEpoch.chpl, test/deprecated/datetimeTimeSinceEpoch.good, test/deprecated/datetimeToday.chpl, test/deprecated/datetimeToday.good, test/deprecated/timedelta_total_seconds.chpl, test/deprecated/timedelta_total_seconds.good, test/library/standard/DateTime/datetimeInitWithDateAndTime.chpl
We've decided to remove 'type datetime.today()', the "datetime - date" operator,
and 'type datetime.timeSinceEpoch():real'.
Equivalent replacements are: 'type datetime.now()', "datetime - new datetime(date, new time())", and
'timeSinceEpoch().totalSeconds(): timedelta' (a standalone function).
While there also deprecate/replace 'timedelta.total_seconds()'
with a camelCase version.
Added a new datetime initializer that takes a 'date' and 'time' argument. Added
a test of this initializer.
Added test/deprecated tests for everything that was deprecated.
=> Deprecate undesirable DateTime methods

runtime/src/chpl-gpu-diags.c, test/gpu/native/diags.chpl, test/gpu/native/diags.good
This PR addresses issues pointed out be @cassella:
https://github.com/chapel-lang/chapel/pull/19941#issuecomment-1147093973
- Expands a test to cover `resetGPUDiagnostics`
- Fixes comments in the runtime
=> Add the missing test for `resetGPUDiagnostics`, comment fixes

modules/standard/AutoMath.chpl
Accidentally thwarted some optimizations by not making the helpers inlined as
well.
Fix developed by Elliot
Resolves Cray/chapel-private#3419
Saw improvements for InsertFront, Append, and PopFront with
`CHPL_TARGET_CPU=native`.  Passed a full paratest with futures
=> Fix performance of list benchmark by making these helpers inlined

compiler/passes/convert-uast.cpp
dyno: Remove unused method to convert string literals (#19951)
Intel compilers are complaining about an unused method in the
converter, so remove it.
=> dyno: Remove unused method to convert string literals

test/ANNOTATIONS.yaml, test/GRAPHFILES
Remove graph reference to removed test from https://github.com/chapel-lang/chapel/pull/19825.
This benchmark was removed because it was using set-like operators on a map, which are ambiguous in their functionality.
=> Remove timeMapMinusEqual from GRAPHFILE

modules/packages/TOML.chpl, modules/standard/DateTime.chpl, test/deprecated/renameDateTimeMethods.chpl, test/deprecated/renameDateTimeMethods.good, test/library/packages/Curl/check-http-setopt.chpl, test/library/standard/DateTime/testDate.chpl, test/library/standard/DateTime/testDatetime.chpl, test/library/standard/DateTime/testDatetimeTZ.chpl, test/library/standard/DateTime/testTime.chpl, test/library/standard/DateTime/testTimezone.chpl, test/library/standard/DateTime/testTimezoneConversions.chpl
Deprecate and rename DateTime methods from issue https://github.com/chapel-lang/chapel/issues/18846. This has not yet
modified the classes or enums suggested in that issue.
Added a deprecated test to trigger the warnings for each of the deprecated
methods.
Fixed up any tests that were using the now-deprecated names.
=> Deprecate DateTime methods from issue #18846.

make/compiler/Makefile.sanitizers, third-party/qthread/Makefile
Qthreads inline assembly for task switching throws off ASan, so
previously we only supported using fifo. This adds experimental support
for using qthreads with `CHPL_QTHREAD_SANITIZER_SUPPORT`, which really
just disables asm context switching in favor of makecontext/swapcontext.
Asan can still get tripped up by these and some implementations will
warn with:
```
==18623==WARNING: ASan doesn't fully support makecontext/swapcontext functions and may produce false positives in some cases!
```
but this seems to work at least for hellos so I wanted to add prototype
support. This is to help debug a memory corruption issue we're seeing in
Cray/chapel-private#3417
=> Add prototype support for using ASan with qthreads

runtime/include/chpl-mem-hook.h, test/memory/gbt/test-memLog.execopts, test/regex/allocationCounts.execopts, test/regex/allocationCounts.prediff, test/regex/allocationCounts.skipif
Previously, runtime memory hooks (sanity checks and memory tracking)
were enabled if `CHPL_DEBUG` was set or if `CHPL_OPTIMIZE` wasn't set.
This led to pretty confusing behavior, because our third-party, runtime,
and generated code could all get different values of these settings,
which resulted in inconsistent tracking for the final executable.
Simplify things here to only enable memory hooks if memory tracking is
enabled regardless of optimization or debug levels. This should make the
behavior for an executable consistent across all components and should
speed up allocations coming from qthreads, which got tracked since we
don't set `CHPL_OPTIMIZE` when calling our memory layer from qthreads.
This code originated from 9c50debb80, where the flags were more about
memory debugging instead …
=> Require `--memTrack` to enable memory hooks

util/cron/common-arkouda.bash
Switch from python 3.7 to 3.9 since Arkouda now requires at least 3.8
(Bears-R-Us/arkouda#1487). Note that I wanted to use a newer version do
limit when we have to do the next upgrade, but I didn't go with 3.10
since spack is still defaulting to 3.9.
Also note that I added a `setup_python_arkouda` wrapper so that we don't
have to change our testing and dev scripts the next time we have to
upgrade.
=> Upgrade our arkouda python version

configure, test/compflags/ferguson/home/sub_test
Changes `./configure` to create the prefix directory if it doesn't exit. Also changes --print-chpl-home tests so they account for builds that use a prefix directory.
Completes #19762
=> Change `configure` to create prefix directories

test/memory/bradc/allocBig.execopts
This test is checking if allocations that are too large will fail on
32-bit systems, and as of #19933 these checks require `--memTrack`
=> Throw `--memTrack` for allocBig test

test/deprecated/renameDateTimeMethods.chpl, test/deprecated/renameDateTimeMethods.good
Change a call to 'fromtimestamp' to 'utcfromtimestamp' so it gets the same
answer no matter what time zone the machine that calls it from is in.
=> Fix the deprecated DateTime methods test so it works across timezones

modules/standard/ChapelIO.chpl
From a discussion in gitter, the examples in the [ChapelIO](https://chapel-lang.org/docs/modules/standard/ChapelIO.html) page did not compile. The example
```chpl
class IntPair {
var x: int;
var y: int;
proc readWriteThis(f) throws {
f <~> x <~> new ioLiteral(",") <~> y <~> new ioNewline();
}
}
var ip = new IntPair(17,2);
write(ip);
// prints out
// 17,2
delete ip;
```
failed to compile with error
```
sandbox.chpl:5: error: Attempt to 'new' a function or undefined symbol
sandbox.chpl:5: error: Attempt to 'new' a function or undefined symbol
```
because `ioLiteral` and `ioNewline` are not included by default. This was fixed by adding `use IO` at the beginning of the snippet and a note in the text about this (not sure whether this is the best improvement though)
Next, the snippet still …
=> update chapelio docs

test/gpu/native/multiLocale/copyToLocaleThenToGpu.chpl, test/gpu/native/multiLocale/copyToLocaleThenToGpu.good, test/gpu/native/multiLocale/directCopyToGpu.chpl, test/gpu/native/multiLocale/directCopyToGpu.good, test/gpu/native/multiLocale/promotedOpOnAllGpusAndLocales.chpl, test/gpu/native/multiLocale/promotedOpOnAllGpusAndLocales.good
Engin created these multilocale\multiGPU tests that perform different sorts of communication.
`promotedOpOnAllGpusAndLocales`: Stream like computation occurs on all gpus and locales locally without any remote puts\gets.
`copyToLocaleThenToGpu`: Copy relevant portions of input data from Locale[0] to Locale[n] and then back
`directCopyToGpu`: Copy relevant portions of input data from Locale[0] directly to gpu sublocales across all locales.
I want to make sure we get these in our nightly tests.
=> Add additional multilocale GPU tests

doc/rst/technotes/libraries.rst
A chapel function declaration was using C syntax.
=> Fixes a small syntax error in the interop docs

test/optimizations/bulkcomm/asenjo/ptransDR/v1/ptrans.good, test/optimizations/bulkcomm/asenjo/ptransDR/v2/ptrans.good, test/optimizations/bulkcomm/asenjo/stencilDR/v1/stencil.good, test/studies/shootout/spectral-norm/lydia/spectral-norm-barrier.good, test/studies/shootout/spectral-norm/lydia/spectral-norm-double-time.good, test/studies/shootout/spectral-norm/lydia/spectral-norm-no-reduct.good, test/studies/shootout/spectral-norm/lydia/spectral-norm-specify-step.good, test/studies/shootout/spectral-norm/lydia/spectral-norm.good, test/studies/shootout/spectral-norm/sidelnik/spectralnorm.good, test/studies/shootout/spectral-norm/sidelnik/spectralnorm_2.good
The following tests failed after #19974: 
```
[Error matching program output for optimizations/bulkcomm/asenjo/ptransDR/v1/ptrans]
[Error matching program output for optimizations/bulkcomm/asenjo/ptransDR/v2/ptrans]
[Error matching program output for optimizations/bulkcomm/asenjo/stencilDR/v1/stencil]
[Error matching program output for studies/shootout/spectral-norm/lydia/spectral-norm-barrier]
[Error matching program output for studies/shootout/spectral-norm/lydia/spectral-norm-double-time]
[Error matching program output for studies/shootout/spectral-norm/lydia/spectral-norm-no-reduct]
[Error matching program output for studies/shootout/spectral-norm/lydia/spectral-norm-specify-step]
[Error matching program output for studies/shootout/spectral-norm/lydia/spectral-norm]
[Error matching …
```
=> Fixed tests failing due to shifted line numbers in chapelio

modules/dists/BlockDist.chpl, test/modules/bradc/printModStuff/foo.good
Improve the scalability of scans on block distributed arrays by removing
replicated array creation and reducing comm in a serial section.
At a high level, block uses a multi-pass scan. First, each task does a
local scan on its region of an array, then a serial inter locale scan of
the per-locale results is done, and finally each task will update its
region with the per-locale results.
Previously, we used replicated arrays to store per-locale results and
coordinate when results were ready. This led to performance issues since
replicated array creation scales poorly (Cray/chapel-private#1756) and
having initial results and ready flags distributed meant the serial scan
did blocking remote comm to check the ready flags and read results.
This switches to local arrays for the initial results …
=> Improve BlockDist scan scalability

compiler/passes/scopeResolve.cpp, test/modules/errors/callModLikeProc.chpl, test/modules/errors/callModLikeProc.good, test/modules/errors/callModLikeProc2.chpl, test/modules/errors/callModLikeProc2.good
[developed by @mppf; reviewed and tested by me]
Prior to this PR, a module that was "called" but otherwise dead was
dead-code eliminated, causing the compiler error that we'd generate
further along in compilation to refer to dead code.  This PR keeps
such called modules alive for the sake of generating a legal error.
It seems that we could also generate the error here, but this
approach has the benefit of emitting all instances of this error
in a single place.
Beyond putting Michael's suggested code change into a PR, I captured
the tests that were filed to highlight this issue from #19932.
Resolves #19932.
=> Keep "called" modules alive for the sake of generating errors for them

tools/mason/MasonRun.chpl
This PR fixes a bug where running `mason run --example <example_name> --build`
would not rebuild the example prior to running. 
* the flag to tell an example to build was defaulted to false and
never updated with the result of command-line parsing. This caused
`mason run --example <name> --build` to fail to build. 
Reported by user during CHIUW 2022 coding day.
TESTING:
reviewed by @bmcdonald3 - thank you!
=> fix(mason-example): properly set the build flag when running examples

test/optimizations/bulkcomm/asenjo/ptransDR/v1/PREDIFF, test/optimizations/bulkcomm/asenjo/ptransDR/v1/ptrans.good, test/optimizations/bulkcomm/asenjo/ptransDR/v2/PREDIFF, test/optimizations/bulkcomm/asenjo/ptransDR/v2/ptrans.good, test/optimizations/bulkcomm/asenjo/stencilDR/v1/PREDIFF, test/optimizations/bulkcomm/asenjo/stencilDR/v1/stencil.good, test/studies/shootout/spectral-norm/lydia/PREDIFF, test/studies/shootout/spectral-norm/lydia/spectral-norm-barrier.good, test/studies/shootout/spectral-norm/lydia/spectral-norm-double-time.good, test/studies/shootout/spectral-norm/lydia/spectral-norm-no-reduct.good, test/studies/shootout/spectral-norm/lydia/spectral-norm-specify-step.good, test/studies/shootout/spectral-norm/lydia/spectral-norm.good, test/studies/shootout/spectral-norm/sidelnik/PREDIFF, test/studies/shootout/spectral-norm/sidelnik/spectralnorm.good, test/studies/shootout/spectral-norm/sidelnik/spectralnorm_2.good
These tests are very sensitive to line number changes in ChapelIO, which has been seeing an uptick in activity as we deprecate things. This PR adds some PREDIFFs to help avoid the tedium of merge conflicts on these files going forward.
Testing:
=> Ignore line numbers in .good files with ChapelIO warnings

compiler/optimizations/gpuTransforms.cpp
This PR includes some refactoring changes to `GPUTransforms.cpp` (originally proposed in https://github.com/chapel-lang/chapel/pull/19802)
Specifically, I've moved various functions into two classes:
* GpuizableLoop: Which is concerned with determining if a loop is eligible for GPU code generation and extracting the bounds of the loop
* GpuKernel: Which is responsible for generating the kernel function itself and populating it (copying the body of the loop into it)
I've manually verified that our `gpu/native` tests pass on Osprey when `CHPL_COMM=none`.
=> Refactor gpuTransforms.cpp

modules/internal/ChapelArray.chpl, test/deprecated/arrays.chpl, test/deprecated/arrays.good
Specifically front() and back() (should use .first and .last instead).
=> Remove deprecated back and front array procs

modules/standard/ChapelIO.chpl, modules/standard/IO.chpl, test/deprecated/IO/readwrite.chpl, test/deprecated/IO/readwrite.good, test/functions/operatorOverloads/operatorMethods/allOps/ioOperator.chpl, test/io/ferguson/readThis/read-write-locale-arg.chpl, test/visibility/import/enablesUnqualified/multipleUnqualified/operatorsAlone.chpl, test/visibility/import/enablesUnqualified/multipleUnqualified/operatorsFirst.chpl, test/visibility/import/enablesUnqualified/multipleUnqualified/operatorsLast.chpl, test/visibility/import/enablesUnqualified/operatorsAlone.chpl
This PR deprecates `channel.readwrite`.
Resolves https://github.com/chapel-lang/chapel/issues/19500
Calls to `readwrite` are replaced with `readIt`/`writeIt` in the IO modules. They are replaced with `read`/`write` in tests.
Test:
=> Deprecate `channel.readwrite`

test/visibility/only/operatorsAlone.chpl, test/visibility/only/operatorsFirst.chpl, test/visibility/only/operatorsLast.chpl
While running a sanity check paratest tonight, I found that these
three tests failed due to deprecation warnings about
channel.readwrite().  I suspect that these were just overlooked.
=> Fix tests seemingly missed in #19940

modules/internal/ChapelArray.chpl, test/unstable/arrayEquals.chpl, test/unstable/arrayEquals.good
Mark the Array.equals() method as unstable per #19140
Signed-off-by: Jeremiah Corrado <jeremiah.corrado@hpe.com>
=> marked the Array.equals() method as unstable. resolves #19140

tools/protoc-gen-chpl/message.cpp
I deprecated `list.extend` in
https://github.com/chapel-lang/chapel/pull/19828. I missed
its uses in protobuf support. This PR fixes that.
I confirmed that the failing test passes with this patch.
=> Stop using list.extend in protobuf support

test/io/ferguson/readThis/read-write-locale-arg.chpl
I made an error in rebasing #19983 and took the wrong set of changes.
=> Fix read-write-locale-arg test to emit expected output

modules/internal/BytesStringCommon.chpl, modules/standard/IO.chpl, runtime/include/qio/qio.h, test/io/readLine/readLineArrayBoundary.chpl, test/io/readLine/readLineArrayBoundary.good, test/io/readLine/readLineBytesBoundary.chpl, test/io/readLine/readLineBytesBoundary.good, test/io/readLine/readLineStringBoundary.chpl, test/io/readLine/readLineStringBoundary.good
Follow-up to #19937
* improve size checking
* figure out line size in channel buffer
* better optimize to avoid copying the contents of the line
Reviewed by @e-kayrakli and @ShreyasKhandekar - thanks!
=> Improve readLine

Makefile, util/buildRelease/install.sh, util/buildRelease/test_install.bash
For #19992. Related to #19911.
* pre-compile Python code in chpl-venv since it will be installed
* adds chpldoc to installation (as a symbolic link for chpl like usual)
* the chpl-venv install directory was already being installed but chpldoc needs one more directory so add that
* update util/buildRelease/test_install.bash to test chpldoc install and also update it to check --chpl-home install includes mason
=> Update make install to include chpldoc

modules/standard/IO.chpl
Resolves testing failures after PR #20018 on 32-bit systems.
=> Fix readStringBytesData to compile on 32-bit systems

util/chplenv/chpl_gpu.py
I've manually verified that `CHPL_COMM=ugni` works fine (by running all the test under `gpu/native/`) on a Cray XC system and that `CHPL_COMM=ofi` works on a Cray CS system.
=> Remove check disallowing CHPL_LOCALE_MODEL=`gpu` to be used with `CHPL_COMM=ugni` and `CHPL_COMM=ofi`

compiler/llvm/clangUtil.cpp, test/gpu/native/PREDIFF
This PR checks the `device` attribute while adding declarations to `lvt`.
Resolves https://github.com/chapel-lang/chapel/issues/19740
While working on this, I realized that with clang 14, the CUDA version warning
has changed. Instead of fixing our PREDIFF for a warning message that we wanted
to get rid of anyways, I bit the bullet and figured out the correct incantation
for making clang ignore it for us.
This PR doesn't take us all the way to what me and @mppf described starting
https://github.com/chapel-lang/chapel/issues/19740#issuecomment-1145480231. I
have a separate branch that makes lvt use a `llvm::SmallVector` to keep track of
multiple overloads. I haven't figured out how to match the correct version to a
`CallExpr`, yet. But before pursuing that further, I forked off this branch …
=> Fix GPU support for LLVM 14, ignore CUDA version warnings

doc/rst/technotes/gpu.rst
Specifically to indicate that we support things other than CHPL_COMM=none
(although we still consider it experimental, especially for things other than
gasnet).
=> Update gpu tech note

runtime/src/comm/gasnet/comm-gasnet.c, util/chplenv/chpl_comm_segment.py, util/chplenv/chpl_comm_substrate.py
GASNet-EX 2022.3.0 significantly improved the ofi conduit in order to
support Slingshot 10/11 networks and restored support for Omni-Path
networks. Now that ofi support is back, improve our usage of it.
For the chplenv, change the default conduit to be ofi when gasnet is
used on hpe-cray-ex systems and ensure segment fast is used in those
cases. Note that we don't always default to segment fast since that
isn't helpful on omni-path systems.
In the gasnet shim, serialize active-message polling for ofi (this is
similar to #14912 and #17419) and parallelize the heap fault-in for ofi
segment fast (similar to #17405). This results in significant performance
improvements for gasnet-ofi. For instance, parallelizing the heap
fault-in takes 16 node indexgather on SS-11 from 620 MB/s/node to 730 …
=> Improve our gasnet support for the ofi conduit

compiler/dyno/lib/parsing/parser-yyerror.h, test/domains/sungeun/rect/at_operator.bad
Adjust .bad file for future, make dyno parser display all syntax errors
Adjust the `yyerror` hook for the dyno parser to print error messages
that it does not recognize (previously we were omitting the
messages on accident).
Adjust the .bad file for a parsing future accordingly.
Reviewed by @e-kayrakli, @mppf. Thanks!
TESTING
=> Adjust .bad file for parsing future, make sure dyno parser displays all syntax errors

test/functions/iterators/bugs/no-inline-method-iter.bad, test/functions/iterators/bugs/no-inline-method-iter.chpl, test/functions/iterators/bugs/no-inline-method-iter.compopts, test/functions/iterators/bugs/no-inline-method-iter.future, test/functions/iterators/bugs/no-inline-method-iter.good, test/types/range/unbounded/unboundedBoolEnum.chpl, test/types/range/unbounded/unboundedBoolEnum.suppressif, test/types/range/unbounded/unboundedEnumIntVals.chpl, test/types/range/unbounded/unboundedEnumIntVals.suppressif
When #19991 was merged, we started seeing failures for the new tests
with --baseline testing where the loops would go into an infinite
loop.  This was no worse than the behavior prior to #19991 (also an
infinite loop), and turns out to be a pre-existing condition (at least
as far back as 1.25.0) that seems to plague iterator methods of a
certain kind when compiled with `--no-inline-iterators`.  In this PR,
I've illustrated this with `no-inline-method-iter.chpl` which shows
some iterators that work by default but not with --no-inline-iterators.
Interestingly, being a method seems to be part of what causes the
problematic behavior.
For this reason, I've added a '.suppressif' to the tests that were
causing infinite loops in testing to silence them when compiled with
--baseline or …
=> Suppress unbounded enum/bool tests for --baseline; add future showing bug

util/cron/common-native-gpu.bash
With this fix: https://github.com/chapel-lang/chapel/pull/20016 we should now be able to use LLVM.
=> Have gpu tests use latest system llvm

runtime/include/gpu/cuda/chpl-gpu-gen-includes.h
When a routine called from the GPU invoked the `c_pointer_return` function defined in https://github.com/chapel-lang/chapel/blob/main/runtime/include/chpltypes.h#L77 we run into the following issue.
```bash
$CHPL_HOME/modules/internal/ChapelStandard.chpl:24: error: Could not find C function for c_pointer_return;  perhaps it is missing or is a macro?
```
Fix was to create a device version of this function as suggested by @e-kayrakli
=> Fix for not finding c_pointer_return call from GPU

third-party/qthread/README, third-party/qthread/qthread-src/include/qt_blocking_structs.h, third-party/qthread/qthread-src/include/qt_debug.h, third-party/qthread/qthread-src/src/hashmap.c, third-party/qthread/qthread-src/src/patterns/wavefront.c, third-party/qthread/qthread-src/src/qloop.c, third-party/qthread/qthread-src/src/shepherds.c, third-party/qthread/qthread-src/src/syscalls/pread.c, third-party/qthread/qthread-src/src/syscalls/pwrite.c, third-party/qthread/qthread-src/src/syscalls/read.c, third-party/qthread/qthread-src/src/syscalls/write.c, third-party/qthread/qthread-src/src/threadqueues/lifo_threadqueues.c, third-party/qthread/qthread-src/src/threadqueues/mutexfifo_threadqueues.c, third-party/qthread/qthread-src/src/threadqueues/nemesis_threadqueues.c, third-party/qthread/qthread-src/src/threadqueues/nottingham_threadqueues.c, third-party/qthread/qthread-src/src/threadqueues/sherwood_threadqueues.c, util/chplenv/chpl_llvm.py
This PR takes two steps to improve portability to Alpine Linux:
* Brings in the changes from https://github.com/Qthreads/qthreads/pull/105 into the bundled qthreads
* Adjusts chplenv scripts to, as a backup strategy, look for clang dependencies in /usr/include, /usr/lib, and /usr/bin since that is where Alpine installs them. This code includes a check that the version number matches the llvm-config version.
Resolves #19404.
=> Improve portability to Alpine linux

test/gpu/native/useAssociativeDomain.chpl, test/gpu/native/useAssociativeDomain.good
We don't expect a kernel launch but previously this would generate an error:
Unresolved extern function '_ZL16c_pointer_returnPv.
With this PR: https://github.com/chapel-lang/chapel/pull/20053 we no longer
have this problem.
=> Add gpu test using associative domain.

doc/rst/platforms/index.rst, doc/rst/platforms/infiniband.rst, doc/rst/platforms/omnipath.rst
The latest gasnet version restored support for running on Omni-Path with
the ofi conduit. Add documentation on how to run on this network. These
docs are somewhat based on the InfiniBand documentation. Instructions
have been testing on Grid5000 and Sandia Omni-Path systems.
Note that this is for the EOL Intel Omni-Path Architecture (OPA) and not
the upcoming Cornelis Omni-Path Express (OPX).
Resolves #13100
=> Restore Omni-Path documentation

doc/Makefile
The effect of this was that when clicking on the link to view the rst for
a file, you'd be taken to a URL that relied on the `master/` path to
documentation.
=> Fix an overlooked case where we failed to update 'master' to 'main'

compiler/main/version.cpp
Testing:
* It prints out `1.27.0 pre-release (edda1bb5eb)`, without other changes, regardless of `--devel`
* If I disable the `BUILD_VERSION_FILE` rule in `compiler/Makefile` and set `officialRelease = true` in `compiler/main/version_num.h`, and then store `"1"` in `compiler/main/BUILD_VERSION`; `chpl --version` prints out `1.27.0.1`, regardless of `--devel` or not.
* If I do the same as the above but store the `"0"` as the `BUILD_VERSION` then `chpl --version` prints out `1.27.0`,  regardless of `--devel` or not.
* If I let `compiler/Makefile` update `BUILD_VERSION_FILE` and have set `officialRelease = true` in `compiler/main/version_num.h`, it prints out ` 1.27.0` without `--devel` and ` 1.27.0.edda1bb5eb` with `--devel`.
* passed full local testing
Future Work:
* split `BUILD_VERSION` …
=> Don't include sha in version if officialRelease

CHANGES.md
In the time the performance meeting happened, I forgot that while I'd
implemented fixes for Elliot's feedback on CHANGES.md, I hadn't
committed and pushed them, so merged the pre-feedback version.
This addresses his comments.
=> CHANGES.md: Address Elliot's feedback

doc/rst/conf.py, doc/util/versionButton.php
This is the usual update to the docs button version numbers to
distinguish 1.27 (now staged in chapel-www) from 1.28 (main).
=> Update docs buttons/versions to reflect staged 1.27 release

test/scan/scanTargetLocsBlock.skipif
This test assumes at least 2 locales. I thought I added this in #20093,
but apparently forget to commit it.
=> Add comm=none skipif for scanTargetLocsBlock

test/execflags/gbt/dry_run.prediff, test/execflags/gbt/dry_run.skipif, test/library/standard/Prefetch/prefetch.prediff, test/parallel/taskPool/figueroa/TooManyThreads.skipif
Fix some minor test issues identified on mac:
- python -> python3 since python isn't installed
- fix a prefetch test to handle slightly different disassembly
- skip test that adjusts thread stack size, which doesn't work on mac
Part of Cray/chapel-private#3374
=> Fix some tests for mac

runtime/src/chpl-launcher-common.c
In 8aca2b3b575 we added a `find_executable` helper, which changed a
`which` call to `/usr/bin/which --skip-alias --skip-functions`. These
options ended up not being portable to the `which` command on mac, which
meant features like `CHPL_COMM_USE_LLDB` couldn't find executables they
needed and weren't working as a result. To fix this just go back to
using a plain `which`. The motivation for using the skip options was:
> In case the user has an alias or shell function with different
> behavior. I think we want to be using "classic which" rather than
> anything derivative.
But I don't think this gave us trouble in the past.
Part of Cray/chapel-private#3374
=> Fix `CHPL_COMM_USE_(G|LL)DB` on mac

compiler/codegen/cg-stmt.cpp
This does a spot-check in C code generation for chained if-then-else
blocks so that rather than generating:
```c
if (...) {
} else {
if (...) {
} else {
if (...) {
} else {
}
}
}
```
we generate:
```c
if (...) {
} else if (...) {
} else if (...) {
} else {
}
```
Essentially, it checks to see whether there's only one statement in
the else block and whether that one statement is itself a conditional.
If so, it codegens it directly; otherwise it does the normal thing.
Due to the compiler's insertion of temps, cases that _seem_ like they
should generate clean chained conditionals don't always, such as
test/parsing/bigifthenelse.chpl.  Perhaps there's more we could do to
denormalize to address such cases, but in the meantime, this seems
like a step forward.
Resolves …
=> Clean up C code generation of chained if-then-else statements

test/deprecated/BigInteger/deprecateFitsMethods.good
The deprecation test for the old BigInt.Fits_* methods showed outdated deprecation messages. These have been updated in the `.good` file.
`test/deprecated/BigInteger/deprecateFitsMethods` test should no longer be failing.
=> fixed BigInt.Fits_* deprecation test

compiler/llvm/clangUtil.cpp, runtime/include/chplmath.h, runtime/include/sys_basic.h, test/gpu/native/math.chpl
This PR adds a `MAYBE_GPU` specifier, and uses it in some
`static inline` functions in a header that's only included
by the generated code.
Supersedes https://github.com/chapel-lang/chapel/pull/20055
Test:
=> Generate device versions of some functions in runtime

modules/standard/IO.chpl, runtime/include/qio/qbuffer.h, runtime/include/qio/qio.h, runtime/src/qio/qbuffer.c, runtime/src/qio/qio.c, runtime/src/qio/qio_formatted.c, test/io/ferguson/ctests/qio_bits_test.test.c, test/io/ferguson/ctests/qio_formatted_test.test.c, test/io/ferguson/ctests/qio_mark_test.test.c, test/io/ferguson/ctests/qio_memfile_test.test.c, test/io/ferguson/ctests/qio_test.test.c
Perform I/O between a channel buffer and the underlying file in fixed-size I/Os, rather than one large I/O. Previously, if the application did a large read from a channel the data would be read from the file into the buffer in a single large read, then copied from the buffer into the application, requiring twice as much memory as the size of the read. A similar behavior happened with writes.
With these changes even if the application does a large read the data are read into the buffer and copied to the application in fixed-size I/Os. The amount of memory is reduced to the size of the read plus the size of the I/O. Writes are similar.
Changing this behavior required several changes and fixes to the channel implementation. First, the channels are no longer marked when reading or writing …
=> Limit I/O size between channel buffer and underlying file

test/mason/mason-external/libtomlc99/mason-external.suppressif, test/mason/mason-external/masonExternalRanges/mason-external-range.suppressif
Suppress these mason-external tests until we're able to upgrade spack
versions in Cray/chapel-private#3518
=> Suppress mason-external (spack) failures on m1 mac

test/studies/champs/sub_test
This PR makes our nightly testing cover all CHAMPS
executables (except `post`, see #19872).
I made some updates to the patch repository to be able cover
all of them. Once we get successful runs, I'll expand the
plots, too.
=> Compile all CHAMPS executables nightly

test/library/standard/Prefetch/prefetch.prediff
In addition to looking for the `prefetch` instruction, look for `prfum`,
which is the name of the instruction for ARM.
See https://developer.arm.com/documentation/dui0802/b/PRFUM
Part of Cray/chapel-private#3374
=> Fix prefetch test for ARM systems

compiler/dyno/lib/immediates/num.cpp, test/param/ferguson/param-inf.chpl, test/param/ferguson/param-inf.good
Adjust param-inf to avoid outputing negative nans and also adjusted param real : string cast to use inf / nan instead of INFINITY / NAN to better match regular output of these values.
We were observing failures for param-inf on an arm system due to differences in whether or not the NANs were negative. But, a NAN being positive or negative is not guaranteed by C/C++ (the param-evaluation is happening in C++ code within the compiler) and Chapel isn't trying to do anything special for the sign of NANs.
Resolves https://github.com/Cray/chapel-private/issues/3520
=> Improve param-inf test an param real to string casts

doc/rst/usingchapel/prereqs.rst
Add setting LLVM_VERSION in the prereqs commands to install dependencies along
with a comment saying to use the version you have available.
=> Add setting LLVM_VERSION to the prereqs doc

test/types/tuple/errors/tuple-init.bad, test/types/tuple/errors/tuple-init.chpl, test/types/tuple/errors/tuple-init.future, test/types/tuple/errors/tuple-init.good
The error message in the .good file is just what I came up with.
Having the issue/future request successful compilation (raised as an option in the issue) would depend on a design discussion that I'm not proposing here.
=> Add future for tuple initializer internal error (#15718)

compiler/dyno/tools/chpldoc/chpldoc.cpp
This PR captures work to get dyno-chpldoc to pass more of our
chpldoc test suite. We were previously passing about 15/150 tests
and this update brings us up to ~29 passing tests.
* Added new command-line arguments to match `chpldoc`
* Added `checkVersion` from `chpldoc` to validate a version
number passed from the command line.
* Fixed printing of `MultiDecl` to match format needed
by docs. Type and value information will print on the 
first `var` and subsequent matching types and values
will refer to the first `var.type` and value.
Example:
```chapel
var x, y, z: int;
```
printed in docs like:
```
.. data:: var x: int
.. data:: var y: x.type
.. data:: var z: y.type
```
* Print `iterfunction` instead of `iter` for docs
* Print `attribute` when a `var` is part of a `Class` or `Record`.
* …
=> Updates and fixes to dyno-chpldoc

.gitignore
This PR just adds a wildcard match to for `cmake-build-`dirs to the
top level `gitignore`
Motivated by me adding new profiles to my `cmake` builds in `CLion`
(review bypassed due to nature of change)
=> fix(gitignore): add wildcard match for cmake-build dirs

compiler/dyno/lib/uast/chpl-syntax-printer.cpp, compiler/dyno/test/uast/testStringify.cpp, compiler/dyno/tools/chpldoc/chpldoc.cpp
This PR contains work to get `dyno-chpldoc` able to pass more
of our `chpldoc` test suite. At the end of the previous sprint,
`dyno-chpldoc` could pass ~29/150 tests. With these changes we
can now pass ~46/150 tests. 
Changes included in this PR:
* print out parent when child class inherits
* add `override` keyword for procs
* address pathing for submodules in `use` and `import` stmts
* add handling for custom comment indicators
* ignore comments that start with `//`
* special handling to write empty line after enum docs
before a deprecation message
* write a generic deprecation message for marked items with
no message of their own
* skip generic deprecation message if `deprecat` found in docs
* ignore things marked `no doc`
* ignore some things marked `private`
reviewed by @benharsh and …
=> Updates to dyno-chpldoc to pass more chpldoc tests

compiler/dyno/lib/resolution/Resolver.cpp, compiler/dyno/test/resolution/testParamFolding.cpp
This PR fixes a small bug where we were using the wrong index
value to evaluate the `Type` of the RHS of a binary `OpCall`.
It also updates the param folding of binary params that are
used in logical "and" `&&`, and "or" `||` statements. 
With this update, param folding will work properly in 
the following cases:
```chapel
var x: bool = true && false;
var y: bool = false || true;
```
Where previously the paramness of the initialization
expressions for `x` and `y` would have been lost.
TESTING: 
=> fix(dyno-resolver): updates for resolving logical and, or binary ops

compiler/dyno/include/chpl/queries/Context.h, compiler/dyno/include/chpl/queries/query-impl.h, compiler/dyno/include/chpl/resolution/resolution-types.h, compiler/dyno/include/chpl/uast/Function.h, compiler/dyno/include/chpl/util/terminal.h, compiler/dyno/lib/queries/Context.cpp, compiler/dyno/lib/resolution/resolution-types.cpp, compiler/dyno/lib/uast/AstNode.cpp, compiler/dyno/lib/util/CMakeLists.txt, compiler/dyno/lib/util/Makefile.include, compiler/dyno/lib/util/terminal.cpp, compiler/main/arg.cpp, compiler/main/driver.cpp, compiler/util/misc.cpp
This PR updates the dyno query tracing features to include a query depth 
indicator for nested queries, makes small fixes for formatting of `FormalDetail`
and `CallInfo`, implements `stringify` for `Function::Kind` and 
`Function::ReturnIntent`, adds a list of query names to ignore when tracing, 
and changes the `dyno-break-on-hash` flag to accept hex and similarly changes 
query + args hash to output in hex.
The query depth indicator is just a number that indicates the depth of the 
nested query, starting at 1. Here is an incomplete sample output:
```
1 { parse (/home/arezaii/git/chapel/test/types/bool/bradc/numBitsBytesDefault.chpl) QUERY+ARGS HASH: 0x726a5a85ae347e15
2 { parseFile (/home/arezaii/git/chapel/test/types/bool/bradc/numBitsBytesDefault.chpl) QUERY+ARGS HASH: …
```
=> dyno query tracing updates

test/gpu/native/math.chpl
This PR fixes a GPU test by using local variables instead of module-scope ones.
Supersedes https://github.com/chapel-lang/chapel/pull/20152
The underlying issue is captured in https://github.com/chapel-lang/chapel/issues/20156
Test passes with gasnet+gpu config.
=> Fix and improve the GPU math test

compiler/dyno/include/chpl/resolution/resolution-types.h, compiler/dyno/lib/resolution/Resolver.cpp, compiler/dyno/lib/resolution/Resolver.h, compiler/dyno/lib/resolution/resolution-types.cpp, compiler/dyno/test/resolution/ResolvedVisitor.h, compiler/dyno/test/resolution/testLoopIndexVars.cpp
Resolves https://github.com/Cray/chapel-private/issues/3393
This PR implements resolution of param for-loops, the results of which will be stored in the new type ``ResolvedParamLoop``.
We resolve param loops by creating a new Resolver for each iteration, and
storing the collected ResolutionResultByPostorderIDs in a
ResolvedParamLoop result. Each iteration stores a different param
resolution result for the AST representing the index variable.
These temporary Resolvers don't inherit their parent's scopeStacks or
their ResolutionResultByPostorderID values directly. Instead, a
'parentResolver' reference is stored in the Resolver type and used by
'typeForId' to determine whether a parent resolver 'owns' the resolution
results for the desired scope.
The ResolvedParamLoop is finally stored in …
=> dyno: resolve param for loops

doc/rst/platforms/macosx.rst
The cellar isn't in the same place on all systems. By using the
`brew --cellar` command instead of hardcoding a path,
we can be more sure that the instructions and documentation
works on our users' machines.
=> Refer to `brew --cellar` when talking about the Homebrew cellar.

util/chplenv/chpl_llvm.py, util/cron/test-darwin-m1.bash
We're seeing some ABI issues or something with the llvm backend in
#19218. Until we resolve that issue (hopefully soon) just default to the
C backend.
Even though we expect #19218 to be fixed soon, I want to expand nightly
testing (done in this PR) to include the full test suite, and this
allows us to do so.
Part of Cray/chapel-private#3374
Related to #19218
=> Default to the c-backend for arm based macs

third-party/qthread/Makefile
qthreads 1.17 added initial support for arm based macs. This uses the
system ucontext instead of fast asm context switching, but it at least
enables support.
We're seeing much slower task creation compared to fifo (and ucontext on
x86 macs) so we're not changing the default tasking layer, but this at
least enables the ability to use qthreads to experiment more.
For the record, here's the timings I see for creating a task per core
10K times:
```sh
chpl --fast test/parallel/taskCompare/elliot/empty-chpl-taskspawn.chpl -staskingMode=coforallT
./empty-chpl-taskspawn --numTrials=10_000 --printTimings
```
| config             | time   |
| ------------------ | -----: |
| x86 qt asm context |  0.02s |
| x86 qt ucontext    |  0.15s |
| x86 fifo           |  0.17s |
|  m1 qt ucontext    | 11.83s | …
=> Enable opt-in support for qthreads on arm based macs

test/stress/deitz/test_10k_local_coforall_with_remote_update.skipif, test/stress/deitz/test_10k_remote_coforall.skipif, util/chplenv/chpl_mem.py, util/cron/test-gasnet.darwin-m1.bash
Something about jemalloc seems to be causing issues for multi-locale
testing as reported in #17825. I don't know the root cause yet, but
change the default while we look into it.
With cstdlib, all multilocale tests except 2 that create a lot of
communicating threads pass. gasnet only allows so many threads to
communicate concurrently (256 by default) and these tests can result in
10,000 threads. We haven't seen the tests fail previously, but they do
on m1 macs now. I'm not sure if time-slicing on m1 is different or
something is slower or faster but somehow more concurrent threads are
calling into gasnet.
Now that all tests are passing, add full multilocale m1 testing
Part of https://github.com/chapel-lang/chapel/issues/17825
Part of https://github.com/Cray/chapel-private/issues/3374
=> Default to cstdlib mem for arm based macs

compiler/resolution/postFold.cpp, test/expressions/calls/CallInfinity.chpl, test/expressions/calls/CallInfinity.good, test/expressions/calls/CallParenlessWithParens.chpl, test/expressions/calls/CallParenlessWithParens.good, test/expressions/calls/CallParenlessWithParensParam.chpl, test/expressions/calls/CallParenlessWithParensParam.good
Fix internal error when calling a parenless method invocation
Resolves #19945.
Fix a bug which caused calling the result of a parenless method
invocation to result in an internal error:
```chapel
writeln(INFINITY());
```
This code now emits an error:
```
error: unresolved access of 'real(64)' by '()'
```
Which is consistent with the errors emitted when trying to call
a type that does not support that operation.
TESTING
=> Fix internal error when calling a parenless method invocation

make/compiler/Makefile.gnu
Throw -Wno-misleading-indentation on GCC 5.x.x and up (#20163)
When using the C backend and GCC, throw `-Wno-misleading-indentation` to
suppress backend errors that were introduced after #20106.
Tested `gcc 5.4.x` as well.
Reviewed by @bradcray. Thanks!
TESTING
=> Throw -Wno-misleading-indentation on GCC 5.x.x and up

compiler/dyno/lib/resolution/Resolver.cpp, compiler/dyno/lib/resolution/Resolver.h, compiler/dyno/test/resolution/testParamFolding.cpp
The two cases differ pretty much only in what the operation's
1 and 0 elements are. By putting the type of operation behind
a `isAnd` boolean flag, we can share all of the code, including
short-circuiting logic and preserving param-ness.
=> dyno: combine the handling of && and || at the type level.

test/runtime/configMatters/comm/cache-remote/prefetchCounters.chpl, test/runtime/configMatters/comm/cache-remote/prefetchCounters.skipif
Follow-up to PR #19969.
We were seeing failures in this test with `CHPL_COMM=ugni` and with `CHPL_COMM=gasnet` with `CHPL_GASNET_SEGMENT=fast` in an oversubscribed setting, so skip the test there for now. At the present time, `CHPL_COMM=ugni` doesn't do nonblocking GETs at all, so it is not surprising that the counts would behave differently there. It is not completely clear to me what the issue with `CHPL_GASNET_SEGMENT=fast` is, but this PR will cause that configuration to be skipped so it does not create failures in nightly testing.
We saw failures compiling this test with the C backend due to missing arguments to `chpl_cache_invalidate` and so this PR uses a pragma to add those arguments.
=> Adjust new prefetchCounters test

test/library/packages/HDF5/readChunks1DPreprocess.chpl
The string that defines a bash script in this test started with a newline
character because it was written as:
```
const script = """
<script contents>
""";
```
This recently stopped working on some test systems because there was a blank
line before the #! line in the script. Move the <script contents> to the same
line as the opening triple quote.
=> Make a string start on the same line as the opening quote

test/functions/firstClassFns/saveInField-nothing.bad, test/functions/firstClassFns/saveInField-nothing.chpl, test/functions/firstClassFns/saveInField-nothing.future, test/functions/firstClassFns/saveInField-nothing.good, test/functions/firstClassFns/saveInField.chpl, test/functions/firstClassFns/saveInField.good
One just checks saving a fcf in a field and calling it in a method.  The other
is the case I encountered when trying to implement distributed maps, where I
was attempting to use a `nothing` type in the case where I was relying on a
default hasher, which triggered a resolution failure.
A fresh checkout of the tests behaved as expected
=> Add two tests of fcfs as fields

test/functions/firstClassFns/saveInField-nothing.future, test/functions/firstClassFns/saveInField-nothing.good, test/functions/firstClassFns/saveInField-properNothing.chpl, test/functions/firstClassFns/saveInField-properNothing.good
The other test is what I should have written (and works as intended).  The old
future has now been updated to be an "error message" future, since it should not
work but it should generate a better message to the user.  I updated the .good
file with a potential error message, but we may not generate that exact one when
the issue is resolved
A fresh checkout of both tests behaved as expected
=> Update future to reflect correction from Brad and Michael and add another test

modules/dists/BlockDist.chpl
Optimize block dist scans by passing in local views of the result array
to preScan/postScan. This means the indexing in these methods will be on
default rectangular arrays instead of block and DR indexing is cheaper.
Note that this is only legal when the array being scanned and the result
array have the same distribution so reuse the fast-follower checks to
ensure that's the case for this optimization to trigger.
This brings the performance of block scans on par with DR. On a 128-core
rome node I see a 128GB scan go from 2.35s to 2.25, which matches the
performance of DR.
We're operating on wide DR arrays for block, but that doesn't seem to
impact performance at least when using all cores since we're bandwidth
bound. When using fewer cores there is still a difference however.
Part of …
=> Bring block dist scan performance on par with local DR arrays

modules/dists/BlockDist.chpl
Drop `$` suffix from sync vars since we're dropping that convention and
switch `myOutputReady` to be non-nilable.
Part of Cray/chapel-private#3505
=> Make some minor cleanups to block dist scan

compiler/optimizations/gpuTransforms.cpp, test/gpu/native/limitations/iterateOverMultidimDomain.chpl, test/gpu/native/limitations/iterateOverMultidimDomain.good
Currently (with GPU support) we don't support having loops over multi-dimensional domains like the following:
```chpl
on here.gpus[0] {
var A: [1..10, 1..10] real;
forall (i,j) in {1..10, 1..10} do
A(i,j) = i + j;
writeln(A);
}
```
Part of this PR is the "quick fix" mentioned here: https://github.com/Cray/chapel-private/issues/3481 which gets us "further along" to supporting these kind of loops but we run into other issues. Specifically, we'll produce a kernel launch inside a kernel and we don't know how to handle that.
As a convenience in this PR I detect when this situation occurs and produce a compile time error.
One concern is due to the nature of GPU support we will try and generate kernels for all eligible loops even if they won't actually launch on a GPU at runtime.
Maybe this …
=> Produce compile time error if we generate a "launch kernel" call inside a kernel

runtime/src/chpl-launcher-common.c
Removed an extra space in the job name argument to the launcher.
=> Removed extra space in job name argument

test/interop/C/multilocale.skipif, test/interop/python/multilocale.skipif, test/library/packages/ZMQ.skipif
Our tests that use ZMQ assume that if a shared library can be found then
so can the headers and a static lib, but this isn't always the case.  On
many Cray systems just `libzmq.so` is available but nothing else.
Longer term, we probably want more of a configure-like check for zmq
functionality, but for now just add an option to tell the skipifs that
not all zmq functionality is available.
=> Add env var to force skip tests that use ZMQ

make/compiler/Makefile.gnu
We see a warning in GCC 12 along these lines:
```
ErrorMessage.cpp: In function 'std::string chpl::vprint_to_string(const char*, __va_list_tag*)':
ErrorMessage.cpp:53:11: error: pointer 'buf' may be used after 'void* realloc(void*, size_t)' [-Werror=use-after-free]
53 |       free(buf);
|       ~~~~^~~~~
ErrorMessage.cpp:50:35: note: call to 'void* realloc(void*, size_t)' here
50 |     char* newbuf = (char*) realloc(buf, size);
|                            ~~~~~~~^~~~~~~~~~~
```
See also this GCC bug report:  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104069
Thanks to @PHHargrove for reporting the bug and suggesting a solution.
=> Avoid a false positive warning from GCC 12

third-party/llvm/Makefile
Adjust the error to indicate Chapel requires cmake, not just LLVM.
=> Improve error when cmake is missing

test/mason/masonTestSome/CLEANFILES, test/mason/masonTestSome/mason-test-noShow.chpl, test/mason/masonTestSome/mason-test-noShow.good, test/mason/masonTestSome/mason-test-noShow.prediff, test/mason/masonTestSome/mason-test-show.chpl, test/mason/masonTestSome/mason-test-show.good, test/mason/masonTestSome/mason-test-show.prediff, test/mason/masonTestSome/test/compilererror.chpl, tools/mason/MasonTest.chpl
This PR makes a small fix to the output of `mason test` when
any test fails to compile. In the case that the user entered
`mason test --show`, we will no longer add the hint to try
running with the `--show` flag. 
Also added are two tests to lock in the behavior of providing
the hint or not.
TESTING:
reviewed by @bmcdonald3 - thanks!
=> fix(mason-test): suppress hint when --show used

compiler/dyno/CMakeLists.txt, compiler/dyno/test/CMakeLists.txt, compiler/dyno/test/common.cpp, compiler/dyno/test/common.h, compiler/dyno/test/resolution/testEnums.cpp, compiler/dyno/test/resolution/testFieldAccess.cpp, compiler/dyno/test/resolution/testLoopIndexVars.cpp, compiler/dyno/test/resolution/testMultiDecl.cpp, compiler/dyno/test/resolution/testParamFolding.cpp, compiler/dyno/test/resolution/testProcThis.cpp, compiler/dyno/test/resolution/testTuples.cpp, compiler/dyno/test/resolution/testTypeAndInit.cpp, compiler/dyno/test/resolution/testTypeConstruction.cpp, compiler/dyno/test/resolution/testTypeQueries.cpp
A lot of the dyno resolution tests use the same common functions, such as `parseModule`. However, each test file includes its own copy of these functions, which leads to a lot of duplication, and introduces the possibility of these functions going out of sync. If possible, we'd like to avoid this.
This PR introduces a new library target / object file that contains common functions intended to be shared among all dyno tests. This new library is linked with all tests, and thus allows them to share common code. Here's a summary of the changes:
1. The CMake function `comp_unit_test` is pushed into `dyno/tests/CMakeLists.txt` from `dyno/CMakeLists.txt`. It seemed cleaner to introduce the new "common test code" library in `dyno/tests`, and then refer to it in the same place from inside …
=> Factor common code from dyno resolution tests

test/execflags/jhh/job_name.chpl, test/execflags/jhh/job_name.good, test/execflags/jhh/job_prefix.chpl, test/library/packages/HDF5/Hdf5PathHelp.chpl, test/library/packages/HDFS/tzakian/HDFSiterator.chpl, test/library/packages/HDFS/tzakian/chadoop.chpl, test/library/packages/HDFS/tzakian/test.chpl
Removed sys imports from HDF5 and HDFS tests that were not run during initial paratest for sys-deprecation
Signed-off-by: Jeremiah Corrado <jeremiah.corrado@hpe.com>
=> Fixing HDF5 tests broken by sys deprecation

compiler/include/pass-manager-passes.h, compiler/resolution/callDestructors.cpp
These are some relatively straightforward changes to the callDestructors pass that convert sub-passes to use the PassManager.
Splitting off the ``LowerAutoDestroyRuntimeType`` section seems appropriate conceptually, but is somewhat wasteful. In ``CallDestructorsCallCleanup`` we simply overload the functionality when it might technically be more appropriate to split off the section that mutates ``PRIM_ASSIGN_ELIDED_COPY``, rather than removing it.
Testing:
=> Convert more sections of callDestructors to use PassManager

util/chplenv/chpl_llvm.py
On Amazon Linux 2022, it is stored in /usr/lib64/libclang-cpp.so, which our scripting could not find. Builds on logic added in PR #20056.
=> Fix problem finding libclang on Amazon Linux 2022

compiler/AST/ImportStmt.cpp, compiler/AST/UseStmt.cpp, compiler/AST/astutil.cpp, compiler/include/ImportStmt.h, compiler/include/ResolutionCandidate.h, compiler/include/UseStmt.h, compiler/include/astutil.h, compiler/include/scopeResolve.h, compiler/include/stmt.h, compiler/include/visibleFunctions.h, compiler/include/wrappers.h, compiler/optimizations/copyPropagation.cpp, compiler/optimizations/deadCodeElimination.cpp, compiler/passes/ResolveScope.cpp, compiler/passes/normalize.cpp, compiler/passes/scopeResolve.cpp, compiler/passes/splitInit.cpp, compiler/resolution/caches.cpp, compiler/resolution/functionResolution.cpp, compiler/resolution/initializerResolution.cpp, compiler/resolution/resolveFunction.cpp, compiler/resolution/visibleFunctions.cpp, compiler/resolution/wrappers.cpp
This PR adjusts the compiler to use LLVM ADTs from the LLVMSupport library. This PR depends on #19565 to build LLVMSupport even with CHPL_LLVM=none. This provides an approximately 6% performance improvement to the performance of compiling Hello World. 
Changes here were authored by @aconsroe-hpe in https://github.com/Cray/chapel-private/issues/2834
Hello World C backend compile times on my home system - built with quickstart + CHPL_LLVM=none (which includes the LLVM support library after #19565) - showing times from three runs
* main 195a37574cd5a748cbbc9156bbe732bcc6d63eb4 5.1s 5.1s 5.2s
* this PR 7f6272e2de525cf8f701f080376f8eac8794c384 4.8s 4.8s 4.9s
And with CHPL_LLVM=system (so using the LLVM backend):
* main 195a37574cd5a748cbbc9156bbe732bcc6d63eb4 4.8s 4.7s 4.7s
* this PR …
=> Use LLVM ADTs to improve compile times

util/packaging/homebrew/chapel-main.rb, util/packaging/homebrew/chapel-release.rb, util/packaging/homebrew/readme.md
This commit updates both the currently released formula
(chapel-release.rb) for 1.26 which includes updates for the newly
released llvm14 and some other formula clean up and the formula for the
upcoming release (chapel-main.rb).
=> Updating homebrew formulas

test/studies/champs/functions.bash, test/studies/champs/sub_test
This PR makes two updates for CHAMPS nightly testing:
- CHAMPS now uses `-j` by default. This hurts execution performance. For nightly
performance tracking purposes, we should avoid parallel compilation. With this
PR, we pass `NPROCS=0` to CHAMPS' make to disable parallel building.
- With https://github.com/chapel-lang/chapel/pull/20158 in, we can test `post`
executable now. That's the last executable that we weren't testing. Now we
build all CHAMPS executables every night.
=> Update CHAMPS testing for the new version

compiler/dyno/lib/resolution/intents.cpp
The production compiler specifies default intents for a lot
of the built-in types. However, Dyno does not yet know how
to handle intents for these types. This results in assertion
errors whenever a function is called that uses any such built-in
types.
For the following test program:
proc test(s: c_string) {}
test("hello".c_str());
Currently, the compiler reports an assertion error:
Assertion failed: (t->genericity() != Type::CONCRETE)
With this change, however, the call is correctly resolved.
Not all rules from the production compiler are copied in this PR; in particular, I'm not sure how to translate `FLAG_RANGE` (and other flags), as well as other production-compiler-specific things. However, this is an improvement over the current state.
Signed-off-by: Danila Fedorin …
=> dyno: copy some default and const intents from production compiler

modules/packages/TOML.chpl, test/library/packages/TOML/BurntSushi/Passing.chpl, test/library/packages/TOML/test/TomlTest.chpl, test/library/packages/TOML/test/UTomlTest.chpl, test/library/packages/TOML/test/checkParseLoop.chpl, test/library/packages/TOML/test/commentTest.chpl, test/library/packages/TOML/test/date.chpl, test/library/packages/TOML/test/fileTest.chpl, test/library/packages/TOML/test/newline.chpl, test/library/packages/TOML/test/stringTest.chpl, test/library/packages/TOML/test/testtime.chpl, test/mason/masonUpdateTest.chpl, test/mason/pkgconfig-tests/pcTest.chpl, tools/mason/MasonBuild.chpl, tools/mason/MasonDoc.chpl, tools/mason/MasonExample.chpl, tools/mason/MasonExternal.chpl, tools/mason/MasonInit.chpl, tools/mason/MasonModify.chpl, tools/mason/MasonPublish.chpl, tools/mason/MasonRun.chpl, tools/mason/MasonSearch.chpl, tools/mason/MasonSystem.chpl, tools/mason/MasonTest.chpl, tools/mason/MasonUpdate.chpl, tools/mason/MasonUtils.chpl
TOML was previously using unmanaged for everything, which
was causing some problems when trying to parse more advanced
TOML files. This PR removes all instances of `unmanaged` from
`TOML.chpl` and Mason to alleviate some of the difficulty with
having to recursively manage memory.
=> Change TOML to use shared instead of unmanaged

test/studies/champs/functions.bash
This fixes the `make` command edited in https://github.com/chapel-lang/chapel/pull/20224.
=> Use the correct variable name in CHAMPS' make command

test/library/packages/TOML/BurntSushi/TomlTest.chpl, test/library/packages/TOML/specification/TomlTest.chpl, test/library/packages/TOML/test/arrayoftbl.chpl, test/library/packages/TOML/test/quoteTable.chpl
In #20213, TOML usage was changed from unmanaged to shared, so
deletions of TOML objects no longer compile. For updating
testing, futures had not been taken into account and were not
updated, but @dlongnecke-cray thankfully caught those before
testing ran (thank you David!)
=> Remove delete statements from TOML futures

modules/standard/OS.chpl
`OS.POSIX.time_t` and `OS.POSIX.suseconds_t` had casts defined from `c_int` and `c_long`. The `c_int` cast was unneeded and was causing ambiguity errors on 32 bit system where `c_long` is also 32 bits. 
The casts from `c_int` were removed for these types.
=> Removed cast from `c_int->time_t` and `c_int->suseconds_t` from `OS.POSIX` to fix ambiguity errors

compiler/AST/FnSymbol.cpp, test/types/records/bugs/methodOnValue.chpl, test/types/records/bugs/methodOnValue.good
In issue #20259, user @ghbrown pointed out that Chapel currently allows tertiary
methods to be defined on values rather than types (which has the same effect as
defining the method on the type itself, but isn't something I think we ever intended
to support).  This PR closes that loop by tightening up the resolution of the method
receiver to ensure that it's a type and to complain otherwise.
Though I think this is better than what was on `main`, it had a few aspects of it
that were a little disconcerting and worthy of additional looks / future work:
* First, it seems that we call `getValType()` on arbitrary formal type expressions without
checking to see whether the thing we're calling it on is a type or not.  This makes me
wonder where else in the compiler value expressions can be used …
=> Ensure that secondary/tertiary methods are defined on types, not values

modules/internal/localeModels/gpu/LocaleModel.chpl, test/gpu/native/localeName.chpl, test/gpu/native/localeName.good
My https://github.com/chapel-lang/chapel/pull/20249 fixed
`writeln(here.gpus[0].name)`, but broke `writeln(here.gpus[0])`. This PR fixes
that by using the proper internal helper.
Also adjusts a test added by #20249 to make sure we can print GPU locales.
=> Fix writeln'ing GPU locales, expand test to cover that

compiler/codegen/cg-expr.cpp, compiler/codegen/cg-symbol.cpp, compiler/include/clangUtil.h, compiler/llvm/clangUtil.cpp, test/release/examples/primers/fileIO.suppressif, util/chplenv/chpl_llvm.py
Issue #19218 describes a problem where the fileIO primer fails to successfully run on M1 machines under LLVM. The problem appears to be that LLVM is generating incorrect assembly when passing sufficiently large structs by value (and when optimizations are turned off).
This PR works around the underlying issue by querying ABI information from Clang, and providing that information to the existing codegen logic that determines whether such actuals/formals should use a pointer.
This PR also restores ``CHPL_LLVM=system`` as a compatible option for M1 systems, and removes the suppressif on the fileIO primer.
Testing:
=> Use Clang ABI Info to pass extern records by pointer on M1s

compiler/AST/AggregateType.cpp, compiler/dyno/include/chpl/parsing/parsing-queries.h, compiler/dyno/lib/parsing/parsing-queries.cpp, compiler/dyno/lib/resolution/Resolver.cpp, compiler/dyno/lib/resolution/resolution-queries.cpp, compiler/dyno/lib/resolution/scope-queries.cpp, compiler/dyno/lib/types/ClassType.cpp, compiler/dyno/test/resolution/CMakeLists.txt, compiler/dyno/test/resolution/testClasses.cpp, compiler/dyno/test/resolution/testResolveMethodCalls.cpp, compiler/passes/convert-uast.cpp
dyno: More progress on scope resolution, fix bugs in resolver (#20281)
This PR continues the effort of PR #20228 to migrate scope resolution
to the dyno framework and fixes a few bugs in the dyno resolver.
[PR and message written by @mppf]
This PR:
- marks TypeSymbols for decorated class types with FLAG_TEMP so that
if they are created before the production scope resolve runs, the
scope resolver will not report an error about symbols with the
same name
- adds `parsing::idIsField` to support the conversion
- in the dyno type resolver, adjusts the types of formals for class
methods like `proc C.foo` to be borrowed (vs any-management)
- adjusts `prepareCallInfoNormalCall` to avoid unnecessary work if
`isMethodCall == true`
- fixes a bug when resolving method calls
- fixes a bug when …
=> dyno: More progress on scope resolution, fix bugs in resolver

test/gpu/native/llvmIntrinsicAttributes/llvmIntrinsicAttributes.precomp, test/gpu/native/llvmIntrinsicAttributes/llvmIntrinsicAttributes.prediff
This PR fixes a gpu test that fails on Horizon but not Osprey:
The llvmintrinsicAttributes test compares IR generated by clang against IR we generate in our codegen pass for a declaration to an intrinsic (`llvm.nvvm.read.ptx.sreg.tid.x`).  More specifically it ensures that the attributes that are on the declaration of that intrinsic match (between what we generate and what clang generates).
The idea is if something diverges in clang as far as how it generates this declaration we want to be alerted to it. See the README in the test directory for more info.
Anyway, the previous way this test worked was pretty fragile: it assumed the set of attributes we cared about were tied to a specific tag.  For whatever reason this tag would differ on Osprey compared to other machines (like Horizon or …
=> Fix llvmIntrinsicAttributes test

compiler/AST/AggregateType.cpp, compiler/AST/AstToText.cpp, compiler/AST/FnSymbol.cpp, compiler/AST/symbol.cpp, compiler/include/AstToText.h, compiler/include/symbol.h, compiler/passes/normalize.cpp, test/functions/compilation-errors/value-for-arg-type.chpl, test/functions/compilation-errors/value-for-arg-type.good, test/functions/default-arguments/runtime-type-1.bad, test/functions/default-arguments/runtime-type-1.chpl, test/functions/default-arguments/runtime-type-1.future, test/functions/default-arguments/runtime-type-1.good, test/functions/default-arguments/runtime-type-2.bad, test/functions/default-arguments/runtime-type-2.chpl, test/functions/default-arguments/runtime-type-2.future, test/functions/default-arguments/runtime-type-2.good
This extends the checking introduced in #20262 to all formals.
After [making a big deal out of it](https://github.com/chapel-lang/chapel/pull/20262#issuecomment-1190259631), I realized that maybe it is actually simple? Maybe indeed all we need is to add a field `bool typeExprFromDefaultExpr` to `ArgSymbol`?
Turned out that it was not so simple after all. On the upside, I was able to remove some heuristic code, replacing it with a (non-heuristic) check for `typeExprFromDefaultExpr`.
It took some work to handle the various ways a user may declare a formal's type, see `checkFormalType()`. I think that this code will still miss some cases ex. when the formal's type is declared using a value-producing primitive. The way it should be done is by flagging the cases where the `qualType()` of the …
=> Ensure the declared type of a formal is, indeed, a type

compiler/dyno/include/chpl/util/filesystem.h, compiler/dyno/include/chpl/util/subprocess.h, compiler/dyno/lib/util/CMakeLists.txt, compiler/dyno/lib/util/Makefile.include, compiler/dyno/lib/util/filesystem.cpp, compiler/dyno/lib/util/subprocess.cpp, compiler/util/files.cpp, compiler/util/mysystem.cpp
This PR migrates some file and system functionality
into dyno and the `chpl` namespace.
Some motivation for this is the need for `dyno-chpldoc`
to form and execute a shell command to invoke `sphinx`.
Overview of changes:
* move some functions associated with creating temporary directories
to dyno
* rely on `LLVM` support library for deleting directories, where
previously we conditionally built and used different supporting
functions depending on `HAVE_LLVM`, now we assume we using the
support library at least
* migrate `mysystem` functionality to dyno, preserving
old call sites by changing original functions to wrappers around
the new calls in dyno
TESTING:
Reviewed by @dlongnecke-cray and @mppf - thanks!
*Note: Old PR https://github.com/chapel-lang/chapel/pull/20264 is superseded by this …
=> feat(dyno): migrate some system and file funcs

compiler/dyno/lib/CMakeLists.txt
This PR adjusts the `CMake` keyword used when linking `LLVM` to `libdyno`
from `INTERFACE` to `PUBLIC`
The `CMake` docs suggest that `INTERFACE` might be failing here because it 
doesn't link the target, `libdyno` in this case, it only extends the 
link interface.
* BenH. reported builds on mac began failing after PR20280.
While this only appears broken on macs, changing the
keyword from `INTERFACE` to `PUBLIC` fixes the link failure.
failure mode was `ld: symbol(s) not found for architecture ...`
TESTING:
reviewed by @dlongnecke-cray and @DanilaFe - thanks!
=> fix(dyno): change CMake keyword to PUBLIC for libdyno

runtime/include/chpl-gpu.h, runtime/src/chpl-gpu.c
We use `bool` in the GPU layer, but we don't include `stdbool.h`. It looks like
we were getting by, because `CHPL_MEM=jemalloc` brings it in. If you have
`CHPL_MEM=cstdlib`, we aren't able to build the runtime.
Test:
=> Use stdbool in the runtime GPU layer

third-party/chpl-venv/chpldoc-requirements2.txt, third-party/chpl-venv/test-requirements.txt
Updates:
- PyYAML from 5.4.1 to 6.0.0
- argcomplete from 1.12.3 to 2.0.0
- Pygments from 2.9.0 to 2.12.0
- Babel from 2.9.1 to 2.10.3
- Sphinx from 4.3.2 to 4.5.0
- filelock from 3.0.12 to 3.4.1
- Jinja2 from 3.0.1 to 3.0.3
Does not update the following packages further because they
require Python 3.7 or greater:
- filelock (to 3.7.1)
- setuptools (could potentially update to 59.6.0 but the last time we did that, we had problems with arkouda)
- MarkupSafe (to 2.1.1)
- Jinja2 (to 3.1.2)
Can't update docutils because sphinx-rtd-theme won't use it yet (and also this version of
Sphinx isn't compatible with it).
Can't update Sphinx further even though other versions are available because these
versions require a more up to date version of breathe.
Can't update breathe, later versions generate …
=> Update 3rd party packages relied upon by start_test and chpldoc

compiler/AST/FnSymbol.cpp, compiler/dyno/include/chpl/uast/PragmaList.h, compiler/llvm/clangUtil.cpp, compiler/optimizations/gpuTransforms.cpp, modules/internal/ChapelArray.chpl, modules/packages/Sort.chpl, runtime/include/chpl-bitops.h, runtime/include/chplcast.h, runtime/include/chpltypes.h, test/gpu/interop/stream/streamWrapper.h, test/gpu/native/bitops.chpl, test/gpu/native/bitops.good, test/gpu/native/noGPUPragma.chpl, test/gpu/native/noGPUPragma.compopts, test/gpu/native/noGPUPragma.good
This branch makes bunch of small-ish changes in an attempt to get Arkouda to
compile with the GPU locale model. I can separate this into multiple PRs, but I
want to test it some more as a whole. Fixes with this PR:
- Resolves https://github.com/chapel-lang/chapel/issues/19754
- Stops adding `extern "C"` in the C headers included at the command line.
This was proposed by @milthorhpe.
- Fixes an interop test broken by this.
- To be able to do that makes runtime's generated code interface for complex
numbers C-based even if we're compiling with C++. (A prior PR that made some
improvements in that direction is
https://github.com/chapel-lang/chapel/pull/16847)
- This enables defining `c_string_to_complex*` functions to be included in the
generated executable, because their return types are no …
=> Fix some issues with the GPU support to enable simple Arkouda builds

runtime/include/chpltypes.h
clang-11 doesn't support `__builtin_complex`, but it supports complex initializer lists. This PR uses those to create `_Complex_I` if it is not defined.
=> Use the complex initializer that's supported by clang 11

test/mason/masonTestSome/Mason.toml, test/mason/masonTestSome/mason-test-show.chpl, test/mason/masonTestSome/mason-test-show.good, test/mason/masonTestSome/mason-test-show.prediff, tools/mason/MasonTest.chpl
This PR changes the way `mason test` constructs paths for
test files that are defined in the `tests` key of the `mason.toml` file.
The change is to use a relative path rather than an absolute path if
the test is known to the mason package by being defined in the
`tests` key of the `mason.toml` file.
This addresses an issue where the path reported by a failed 
internal `mason test` was absolute, when the expected output would be
relative for internal tests.
TESTING:
Reviewed by @bmcdonald3 - thanks!
=> fix(mason-test): use relative path for internal mason tests

runtime/include/chpl-bitops.h
This was an obvious missing piece from https://github.com/chapel-lang/chapel/pull/20239.
Test:
=> Add the explicit include to runtime's bitops header

compiler/dyno/include/chpl/util/filesystem.h, compiler/dyno/lib/util/filesystem.cpp, compiler/dyno/tools/chpldoc/chpldoc.cpp, compiler/passes/docs.cpp, compiler/util/files.cpp
This PR begins adding support for building HTML docs using the python
package `sphinx` from within `dyno-chpldoc`.
Prior to this work, there were ~23 tests that were failing due to faults 
with `dyno-chpldoc`. This PR fixes 16 of those failures, leaving 7 test 
failures to be fixed in future work.
Much of the supporting functions from `chpldoc` were copied over 
to `dyno-chpldoc` as opposed to adding them to the `dyno` library. 
Future work will refactor these static functions.
TESTING:
Reviewed by @dlongnecke-cray - thank you!
=> feat(dyno-chpldoc): integrate calls to sphinx to build HTML docs

doc/rst/technotes/gpu.rst
`fifo` tasking layer doesn't support our GPU implementation today. This PR adds a sentence for `qthreads` requirement to the GPU technote.
=> Add a small note about the Qthreads requirement for GPU support

modules/internal/ChapelLocale.chpl, modules/internal/localeModels/flat/LocaleModel.chpl, modules/internal/localeModels/numa/LocaleModel.chpl, test/types/locale/promotedCalls.chpl
This PR removes the Knights-Landing memory interface from the `locale` type.
The following methods were unused and undocumented:
- defaultMemory()
- largeMemory()
- lowLatencyMemory()
- highBandwidthMemory()
They have been removed from chapelLocale and the individual locale model implementations.
=> Remove Knights-Landing memory interface from `locale`

compiler/dyno/lib/resolution/resolution-types.cpp
When a resolver is being set up for processing a function signature,
the space allocaed for the `ResolutionResultByPostorderId` is only
nonzero if the function has a body. When considering a call to an
extern function (which doesn't have a body) the `byPostorderId` mapping
is empty, and thus retrieving the resolved expression for any parameter
results in an assertion failure or an error otherwise (presumably).
Instead of using the `body()` of the function as the "largest known
node" when computing a postorder ID, this PR changes the code to look at
the last child. This change is not needed for `setupForParamLoop`, since
a loop will always have a body.
Testing:
=> dyno: avoid resolution failures during calls to external functions.

compiler/optimizations/gpuTransforms.cpp, test/gpu/native/callBuildTupleFunc.chpl, test/gpu/native/callBuildTupleFunc.good
A loop is not considered "gpuizable" if it calls a function where that function accesses an "outside" variable.  This check previously considered any field access to be outside. This commit fixes that.
This should fix: https://github.com/chapel-lang/chapel/issues/20293
=> Exempt field access from outside data check

modules/packages/MatrixMarket.chpl, modules/standard/IO.chpl, modules/standard/Subprocess.chpl, modules/standard/Sys.chpl, test/deprecated/IO/iohints.chpl, test/deprecated/IO/iohints.good, test/functions/iterators/tzakian/open_inside_file_iter.chpl, test/io/tzakian/recordReader/test.chpl, test/library/standard/IO/ioHintSetOperations.chpl, test/library/standard/IO/ioHintSetOperations.good, test/release/examples/benchmarks/shootout/revcomp-fast.chpl, test/release/examples/benchmarks/shootout/revcomp.chpl, test/release/examples/primers/fileIO.chpl, test/studies/lammps/shemmy/m-lammps.chpl, test/studies/lammps/shemmy/s-lammps.chpl, test/studies/shootout/reverse-complement/bharshbarg/revcomp-begin.chpl, test/studies/shootout/reverse-complement/bharshbarg/revcomp-buf.chpl, test/studies/shootout/reverse-complement/bharshbarg/revcomp-line.chpl, test/studies/shootout/reverse-complement/bharshbarg/revcomp-mark-skip-read-begin.chpl, test/studies/shootout/reverse-complement/bradc/revcomp-blc.chpl, test/studies/shootout/submitted/revcomp2.chpl, test/studies/shootout/submitted/revcomp3.chpl, test/studies/ssca2/graphio/SSCA2_RMAT_graph_generator.chpl, test/studies/ssca2/main/SSCA2_Modules/io_RMAT_graph.chpl
This PR implements the changes proposed here: https://github.com/chapel-lang/chapel/issues/20141
The old `iohints` constants are replaced with a new `ioHints` record type.
Still to do:
=> Replace iohints constants with an ioHints Record type

test/optimizations/deadCodeElimination/elliot/countDeadModules.good
I bumped up the number this test reports earlier in my work, but then, the
subsequent changes might have stopped the `Communication` module from being
used/eliminated. This PR reverts the count.
[Trivial, not reviewed]
Test passes with this PR.
=> Revert the countDeadModules test

modules/standard/IO.chpl, test/chpldoc/functions/operatorPrimaryMethods.doc.chpl, test/chpldoc/functions/operatorSecondaryMethods.doc.chpl, test/chpldoc/functions/operators.doc.chpl, test/deprecated/IO/readwrite.chpl, test/deprecated/IO/readwrite.good, test/visibility/except/operatorsExceptions/DefinesOp.chpl
The ``channel.readwrite`` method was deprecated in #19940. This PR removes ``channel.readwrite`` entirely and updates relevant documentation and tests.
Testing:
=> Remove channel.readwrite

compiler/optimizations/gpuTransforms.cpp, test/gpu/native/innerBlock.chpl, test/gpu/native/innerBlock.good
Fixing a bug in the compiler where if a GPUizable loop has a conditional statement whose expression comes from outside the loop, we do not add it as a argument to the code generated for the kernel.
Added conditions in `gpuTransforms.cpp` so that it adds that expression as a kernel argument.
Also added a catch-all `else` block that causes an error if there happen to be any other such cases where we forget to add a compiler argument.
Added a test which fails on main but passes with this fix.
=> GPU Kernel Conditional Statement Bug Fix

compiler/optimizations/gpuTransforms.cpp, modules/internal/Atomics.chpl
This should resolve this failure: https://chapel.discourse.group/t/cron-cray-cs-gpu-native/14597
Basically with https://github.com/chapel-lang/chapel/pull/20342 (Exempt field access from outside data check) we end up trying to gpuize more module code and some of that code ends up calling an extern (atomic_init_bool) that we don't have a device version of.
Long term we might want to cerate a proper device version of the function but in the short term I think it makes sense to just say we don't care to gpuize anything that calls out to that function.
To do this I've applied atomic_init_bool to where we declare the extern in the module code and broadened the definition of the "no gpu codegen" pragma to mean "don't gpuize anything that calls this function" in addition to "don't gpuize any …
=> Do not gpuize call to atomic_init_bool

test/library/standard/Communication/errors.prediff
This prediff was failing on darwin. Use `-r` and more general regex.
=> Make a prediff more portable

compiler/dyno/test/resolution/testVarArgs.cpp
Trivial fix to use a size_t instead of an int to avoid a compiler warning.
=> Fix testVarArgs error

test/gpu/native/studies/shoc/bandwidth.graph, test/gpu/native/studies/shoc/bandwidth2.graph, test/gpu/native/studies/shoc/kernel.graph, test/gpu/native/studies/shoc/kernel2.graph, test/gpu/native/studies/shoc/triad.graph, test/gpu/native/studies/shoc/triad2.graph
Changing the labels of the different Triad versions as follows:
- TriachChpl -> Idiomatic
- Triad -> Transliteration
- Alt1 -> NoSliceLHS
- Alt2 -> NoSlice
Generated graphs before and after making the change on Osprey and viewed the `html` locally. Everything seems to be fine. Hopefully the hosted graphs are also fine.
=> Changing graph legend for Triad

tools/mason/MasonInit.chpl, tools/mason/MasonNew.chpl, tools/mason/MasonRun.chpl
Mason init was incorrectly creating mason "packages", I had
apparently forgotten to update that name to application, so
this PR fixes that by changing the "package" references to
say application instead.
=> Change mason init to default to application

modules/standard/IO.chpl, test/deprecated/IO/unlink.chpl, test/deprecated/IO/unlink.good, test/io/ferguson/bits-errors.chpl, test/io/ferguson/bits-signed.chpl, test/io/ferguson/easybits.chpl, test/io/ferguson/inteof.chpl, test/io/ferguson/zerosatend.chpl, test/library/standard/Spawn/spawn-checkmutate.chpl, test/library/standard/Spawn/spawn-checkret.chpl, test/library/standard/Spawn/spawn-popen-input-output-error-long.chpl, test/library/standard/Spawn/spawn-popen-input-output-error.chpl, test/library/standard/Spawn/spawn-print-args-env.chpl, test/release/examples/primers/fileIO.chpl
This PR deprecates the "unlink" function in the IO module, and recommends using ``FileSystem.remove`` instead. Tests that use the unlink method have been updated to use ``FileSystem.remove``, including the ``fileIO`` primer.
Testing:
=> Deprecate IO.unlink function

compiler/codegen/cg-symbol.cpp, compiler/dyno/include/chpl/uast/PragmaList.h, modules/internal/LocaleModelHelpRuntime.chpl, runtime/include/gpu/cuda/chpl-gpu-gen-includes.h
Similar to the issues https://github.com/chapel-lang/chapel/pull/20356 it looks like  #20342 made it so we gpuize more loops in our module code.  In this case we were getting failures for our gasnet tests ().
It looks like some loop (or loops) that we now gpuize gets access to wide pointers and thus we were get complaints about not having GPUized versions of certain other functions.
To fix I:
* Made `GPU_AND_CPU_CODEGEN` a user visible pragma
* Apply this pragma to `chpl_nodeFromLocaleID`
* Add `__device__` functions for a handful of functions that these call (with the implementation left as a TODO)
=> Fix gasnet related gpu test failures

util/chplenv/chpl_gpu.py
@hokiegeek2 reported some issues with compiling applications with the GPU locale
model, even though build was successful.
The issue was that `which nvcc` was returning non-normal path resulting in us
looking for libdevice in all the wrong places. We should be able to do better
when that happens. This PR:
- normalizes the path returned by `which nvcc`
- errors if we cannot find libdevice in the path we want at `printchplenv`
(today, we just get an `""` which we try to open and link at makeBinary time
resulting in a segfault)
- now that we have a stricter checking, GPU environment scripts try to do
something only with the `gpu` locale model
Test:
=> Improve environments scripts for better CUDA path handling

doc/rst/technotes/gpu.rst
Following a discussion, I wanted to check how we describe what we run on the GPU
and what we run on the CPU. I think the language we have there is a little bit
too static-sounding. The real behavior is more dynamic and much less strict than
the technote suggests.
This PR adjusts the language to make it sound closer to what actually happens.
=> Reduce conservatism in GPU technote

compiler/passes/insertWideReferences.cpp
The following tests were failing with ``--no-local --verify`` with an error complaining about the existence of ``_wide__ref`` types:
- deprecated/URL/depReaderWriter
- library/packages/canCompileNoLink/Curltest
- library/packages/canCompileNoLink/HDFStest
The solution is to not use the _ref type when creating wide temp for virtual method call.
Testing:
=> Fix some --verify errors with --no-local

tools/mason/MasonBuild.chpl, tools/mason/MasonExample.chpl, tools/mason/MasonModules.chpl, tools/mason/MasonUpdate.chpl, tools/mason/MasonUtils.chpl
Previously, support was added to mason for using git repositories 
outside of a mason registry as dependencies, but the TOML files of 
those dependencies were not checked and their revisions were not 
locked in. This meant that if the git repo specified as a dependency 
used another required mason package, it would not be pulled into the 
new build and wouldn't compile.
This PR adds support for checking the TOML file and adding the
dependencies to the lock file of the package using the git repo, so
all dependencies should be resolved.
Additionally, the specific git revision is now always locked in
to ensure build reproducibility. Upon building with a git dep
specified, a directory will be created a and the repo pulled down at
`$MASON_HOME/git/<dep-name>-<branch>`. Then, while generating …
=> Add TOML checking of mason git dependencies and revision locking

test/gpu/native/kernelFnCalls/fnWithForall.chpl
I added comments to a complicated kernel launch test while switching to
GPUDiagnostics-based testing. I thought I understood what's happening, but I was
wrong. I spent some time understanding what's going on, but couldn't because of
the comments. Thanks @daviditen for the explanation.
=> Fix a comment that wants to be helpful but is misleading

runtime/src/qio/qio_formatted.c
When computing the number of bytes remaining to be read in the file the current file offset was subtracted from the current file length. The length may be less than the offset because the file size may change.  Previously, the difference was assigned to an unsigned integer that was compared against zero, leading to a conditional that was always false.  Now the comparison is done prior to the assignment.
=> Fixed signed/unsigned comparison when computing number of bytes to read

compiler/Makefile, compiler/dyno/lib/framework/Makefile.include, compiler/dyno/lib/immediates/Makefile.include, compiler/dyno/lib/parsing/Makefile.include, compiler/dyno/lib/resolution/Makefile.include, compiler/dyno/lib/types/Makefile.include, compiler/dyno/lib/uast/Makefile.include, compiler/dyno/lib/util/Makefile.include, compiler/main/Makefile.include
Resolves #20379.
Adjusts the tags file generation to include the dyno headers.
Reviewed by @bradcray - thanks!
=> Enable tags for dyno headers

compiler/dyno/include/chpl/parsing/parsing-queries.h, compiler/dyno/lib/parsing/parsing-queries.cpp, compiler/dyno/test/resolution/testInteractive.cpp, compiler/include/files.h, compiler/main/driver.cpp, compiler/util/files.cpp
This PR allows ``chpl::parsing::setupModuleSearchPaths`` to accept a list of ".chpl" file names that will be used to add more module search paths depending on the location of the provided files. For example, "chpl foo.chpl" would add the current directory to the module search paths.
This PR adds ``getChplFilenames`` to ``files.h``, which returns a vector of ".chpl" file names.
This PR also separates the error message "Command line contains no .chpl source files" from the addition of source files. This change supports calling ``addSourceFiles`` earlier than ``printStuff``, which supports things like ``chpl --version`` in which no source files are expected.
Testing:
=> dyno: add filenames' directories to module search paths

modules/packages/TOML.chpl, modules/standard/DateTime.chpl, modules/standard/Time.chpl, test/deprecated/datetimeMinusDate.good, test/deprecated/datetimeTimeSinceEpoch.good, test/deprecated/datetimeToday.good, test/deprecated/renameDateTimeMethods.good, test/deprecated/timedelta_total_seconds.good, test/deprecated/useDateTime.chpl, test/deprecated/useDateTime.good, test/library/packages/Curl/check-http-setopt.chpl, test/library/standard/DateTime/datetimeInitWithDateAndTime.chpl, test/library/standard/DateTime/readWriteDatesTimes.chpl, test/library/standard/DateTime/strptime.chpl, test/library/standard/DateTime/strptime2.bad, test/library/standard/DateTime/strptime2.chpl, test/library/standard/DateTime/testDate.chpl, test/library/standard/DateTime/testDatetime.chpl, test/library/standard/DateTime/testDatetimeTZ.chpl, test/library/standard/DateTime/testNow.chpl, test/library/standard/DateTime/testTime.chpl, test/library/standard/DateTime/testTimezone.chpl, test/library/standard/DateTime/testTimezoneConversions.chpl, test/library/standard/DateTime/unstableTimezones.chpl, test/library/standard/DateTime/writeDateTime.chpl, test/modules/vass/deinit-order-modules.verbose.good, test/optimizations/deadCodeElimination/elliot/countDeadModules.good, test/optimizations/sungeun/bulk_transfer/assign.good, test/studies/comd/elegant/arrayOfStructs/util/Util.chpl
Merge the 'DateTime' and 'Time' modules into a single 'Time' module. Deprecate
the 'DateTime' module. Update tests and other modules to use 'Time' instead
of 'DateTime'. Don't add procedures that are deprecated in 'DateTime' to 'Time'.
=> Merge the contents of the 'DateTime' module into 'Time'

doc/rst/mason-packages/guide/buildingandrunning.rst, doc/rst/mason-packages/guide/buildinglargerpackages.rst, doc/rst/mason-packages/guide/chapeldependencies.rst, doc/rst/mason-packages/guide/examples.rst, doc/rst/mason-packages/guide/externaldependencies.rst, doc/rst/mason-packages/guide/gitdependencies.rst, doc/rst/mason-packages/guide/namespacing.rst, doc/rst/mason-packages/guide/testing.rst, doc/rst/mason-packages/index.rst, doc/rst/mason-packages/start/helloworld.rst, doc/rst/mason-packages/start/whymason.rst
This PR updates the mason documentation, adding sections explaining
why there is value in using mason and explaining the three different
types of mason packages.
Also, many general improvements have been made, including suggesting
submodules and discouraging use of the `-M` flag in mason packages.
Git dependency documentation is updated alongside many other small
rewords and improvements.
=> Update mason documentation and recommend submodules

compiler/AST/CatchStmt.cpp, compiler/dyno/lib/resolution/scope-queries.cpp, compiler/include/CatchStmt.h, compiler/passes/convert-uast.cpp
This PR updates dyno and the ``convert-uast`` pass to scope-resolve catch-statements.
The change to dyno is minimal and simply requires identifying Catch nodes as creating a new scope.
The change to support scope-resolution in ``convert-uast`` is slightly more complex. ``CatchStmt::build`` does not create a Symbol that ``convert-uast`` can use to map from dyno's representation to the production compiler's representation. Prior to this PR, the necessary Symbol was created during ``CatchStmt::cleanup``. This PR creates a new method, ``CatchStmt::createErrSym``, that will create the necessary Symbol (only the first time the method is called). ``CatchStmt::cleanup`` will invoke this method at the start to create the symbol if it's not already created. ``convert-uast`` can call this method …
=> dyno: scope-resolve catch statements

compiler/dyno/lib/resolution/Resolver.cpp, compiler/dyno/lib/resolution/Resolver.h, compiler/dyno/test/resolution/testLoopIndexVars.cpp
This PR updates dyno's Resolver to resolve index variables for any ``IndexableLoop``, instead of just ``For`` loops.
Testing:
=> dyno: resolve more loop index variables

modules/standard/CommDiagnostics.chpl, runtime/src/chpl-cache.c
I tried to make the verb form 'read ahead' and use 'readahead' for the nouns/adjectives.
=> Unify read ahead/readahead spelling in CommDiagnostics.chpl and chpl-cache.c

modules/internal/ChapelLocale.chpl, test/gpu/native/dataPingPong.chpl, test/gpu/native/gpuAddNums/gpuAddNums_primitive.chpl, test/gpu/native/innerBlock.chpl, test/gpu/native/kernelFnCalls/callFnAccessModVar.chpl, test/gpu/native/kernelFnCalls/callFnFromFn.chpl, test/gpu/native/kernelFnCalls/callHalts.chpl, test/gpu/native/kernelFnCalls/callRecursiveFn.chpl, test/gpu/native/kernelFnCalls/callTrivialFn.chpl, test/gpu/native/multiGPU/multiGPU.chpl, test/gpu/native/multiGPU/worksharing.chpl, test/gpu/native/multiGPU/worksharingBasic.chpl, test/gpu/native/promotion2.chpl, test/gpu/native/threadBlockAndGridPrimitives.chpl, test/gpu/native/tuple.chpl, test/gpu/native/useAssociativeDomain.chpl, test/gpu/native/varInInnerBlock.chpl
With the GPU locale model we no longer intend end users to use `locale.getChild()` to access gpu sublocales; instead, they should use `locale.gpus`.
This was changed as of https://github.com/chapel-lang/chapel/pull/19673 but for whatever reason there are a bunch of tests using the old style.  This PR brings these tests up-to-date.
While updating these tests a failure in `dataPingPong.chpl` (which compares against a log of expected memory copies) alerted me that I was inadvertently copying the gpus array whenever we call the parenless `gpus` proc.  This PR also fixes that.
=> Update gpu tests to avoid using locale.getChild().

test/gpu/native/dataPingPong.good, test/gpu/native/diags.good
Due to fallout from https://github.com/chapel-lang/chapel/pull/20399.
This changed how the array of gpus gets returned from the locale
(returned as const ref rather than by value) so that impacts what memory
transfers occur. A couple tests were locking down the old behavior
=> GPU test fixes

test/interop/C/cmakelists/SKIPIF, test/interop/C/cmakelists/targetToChpl/SKIPIF, test/interop/C/cmakelists/targetToLibToChpl/SKIPIF
Fixes a failure with the gasnet-everything configuration. These tests shouldn't be running because they don't support CHPL_COMM != NONE like the makefile support.
=> SKIPIF added for CMake library definitions

runtime/include/chpllaunch.h, runtime/src/chpl-launcher-common.c, runtime/src/launch/gasnetrun_common/gasnetrun_common.h, runtime/src/launch/lsf-gasnetrun_ibv/launch-lsf-gasnetrun_ibv.c, runtime/src/launch/pbs-gasnetrun_ibv/launch-pbs-gasnetrun_ibv.c, runtime/src/launch/slurm-gasnetrun_common/slurm-gasnetrun_common.h
Previously, Chapel would determine what character set to use
based off of `LANG`, `LC_COLLATE`, and `LC_ALL`. In #19381, 
this was changed so that we now always use UTF8 and no longer 
check those variables, meaning that they are no longer needed 
and can be removed.
Closes: https://github.com/chapel-lang/chapel/issues/20395
=> Remove env invocation for setting LANG variables in launcher

modules/standard/Time.chpl, test/optimizations/sungeun/bulk_transfer/assign.good
Initialize a private array constant with a tuple instead of array
Now that DateTime is combined into Time a test that does 'use Time'
and tracking bulk transfers is seeing an extra array transfer. This is from
initializing a private const array from DateTime with an array literal.
Replace the literal with a tuple literal instead to avoid the extra transfer
message.
=> Fix bulk transfer tests

util/cron/test-perf.cray-xc.arkouda.release.bash
After our XC nightly testing updated to gcc 12.1.0, we were
seeing some warnings causing build failures regarding some
templates (`error: expected 'template' keyword before dependent
template name`). Reverting to 11.2.0 removes these errors,
but we would like to not need to pin the version, so this
change should be removed on our nightly runs when the problem
is resolved.
=> Pin gcc version 11.2.0 for Arkouda XC testing

compiler/dyno/lib/resolution/Resolver.cpp, compiler/parser/parser.cpp, make/compiler/Makefile.gnu
Some of our nightly testing configurations started using GCC 12.1. That led to several build failures due to new warnings in GCC 12.
For the warnings-as-errors in LLVM headers, update Makefile.gnu to pass `-Wno-error` flags for these, so that they continue to be warnings, but will not break the build. Two of these problems in the LLVM source code should be fixed for LLVM 15. (See [8e066b86a73205cdaf758a9dd4d761406d39bff1](https://github.com/llvm/llvm-project/commit/8e066b86a73205cdaf758a9dd4d761406d39bff1) and [1d9086bf054c2e734940620d02d4451156b424e6](https://github.com/llvm/llvm-project/commit/1d9086bf054c2e734940620d02d4451156b424e6) ). It's unclear to me if third problem related to `-Wno-error=address` and `DeclObjC.h` will remain in LLVM 15.
There were a few warnings about dangling …
=> Address GCC 12 warnings

test/setchplenv/verify_setchplenv_scripts.py, third-party/Makefile, third-party/llvm/Makefile, util/chplenv/chpl_llvm.py, util/chplenv/printchplenv.py, util/quickstart/setchplenv.bash, util/quickstart/setchplenv.csh, util/quickstart/setchplenv.fish, util/quickstart/setchplenv.sh
Follow-up to PR #19565.
This PR takes two steps to improve the situation after PR #19565.
First, it adds `CHPL_LLVM_SUPPORT` as a `printchplenv` variable. This variable indicates where to get the LLVM Support Library (which is currently required to build the compiler). It can be `bundled` or `system`. See issue #20380.
On the name of this variable, I wondered if `CHPL_LLVM_SUPPORT_LIBRARY` would be a better name? `CHPL_LLVM_SUPPORT` could be interpreted as "does Chapel build with LLVM support" but that is what `CHPL_LLVM` does. On the other hand, since it appears in `printchplenv --all` within the `CHPL_LLVM` block, I think `CHPL_LLVM_SUPPORT` is OK.
Second, it adjusts the quickstart scripts to set `CHPL_LLVM=system` if a compatible system LLVM is detected. See issue #20273.
Reviewed by …
=> Add CHPL_LLVM_SUPPORT and adjust quickstart

util/buildRelease/testReleaseHelp
Follow-up to PR #20396 to fix a test failure.
Test code was picking up the LLVM version as well
since now with LLVM support the output looks like this e.g.:
chpl version 1.28.0 pre-release (e4f5b05948)
built with LLVM version 14.0.0
Fix that by adjusting a `grep` call used in buildReleaseHelp.
=> Fix testReleaseHelp to check only Chapel version

modules/internal/ChapelLocale.chpl
Updates to the documentation for `locale.name`, `locale.hostname`, and `locale.id` to clarify their behaviors for sub-locales and oversubscribed execution.
Explicit return type annotations were also added to these methods.
=> `locale` documentation improvements

test/gpu/native/studies/shoc/result.chpl
Simple colon was breaking tests.
Both `start_test` and `start_test --perflabel gpu-` for `test/gpu/native/studies/shoc` are now passing on Osprey so I think this should fix that issue.
=> Fix for failing GPU Perf tests

runtime/Makefile, test/runtime/sungeun/chpl-env-gen.precomp, util/chplenv/chpl_llvm.py, util/cron/common-quickstart.bash
Follow-up to PRs #20396 and #20385 to address issues raised by nightly testing.
* build failures in cron-xc-wb-host-prgenv-cray-failure and xc-wb.prgenv-cray configurations: don't default to CHPL_LLVM_SUPPORT=system if all the LLVM dependencies are not installed. These configurations have just `llvm-config` but not the required headers.
* networking-packages failure with curl tests: update `common-quickstart.bash` to set `CHPL_LLVM=none`. The quickstart setup script can provide `CHPL_LLVM=none` or `CHPL_LLVM=system` but since we test `CHPL_LLVM=system` in most configurations, in the quickstart testing configuration, we want to test `CHPL_LLVM=none`. At the moment, the curl tests do not all work with the LLVM backend.
* darwin-m1 or other Mac OS testing failure with chpl-env-gen: fixed a …
=> Fix problems after LLVM configuration PRs

compiler/dyno/lib/resolution/can-pass.cpp, compiler/dyno/test/resolution/testCanPass.cpp
This was missing from `canPass`, and is required at some point
in resolving the `range` record from the standard library.
=> Make `canPass` properly handle "any enum type"

make/compiler/Makefile.intel
Intel's compiler claims to recognize clang-specific
attributes but then doesn't, and warns about it. Builds
with `Werror` pick this up and break. This change
makes the specific attribute warning not an error, which
lets the builds finish.
In the specific case of failures we observed, the following
happened:
1. Compilation of the LLVM support library failed around
`LLVM_NODISCARD` when using `icc` as the _host_
compiler.
3. The `LLVM_NODISCARD` flag checks for the attribute
`clang::warn_unused_result`, and if it's present,
expands to `[[clang::warn_unused_result]]`.
4. `icc` reports that it has `clang::warn_unused_result`,
but doesn't recognize the attribute when push comes
to shove. This results in a warning.
5. The warning is escalated by `-Werror` into an error.
This PR overrides the …
=> Disable Werror for unknown attribute warnings for icc

test/interop/C/cmakelists/targetToChpl/CMakeLists.txt, test/interop/C/cmakelists/targetToChpl/Makefile, test/interop/C/cmakelists/targetToLibToChpl/CMakeLists.txt, test/interop/C/cmakelists/targetToLibToChpl/Makefile
Previously I had required the tests to use clang, which the 32bit testing machine does not have. Now, I extract the compiler executable path from the CHPL_COMPILER variable and use that instead. Tested to work on my machine, chapcs11, and mnlchapvm04, which is the system that the test was failing for.
=> Another fix for CMake definition generation for the 32bit linux tests 

test/functions/deitz/nested/test_nested_with_begin.chpl, test/parallel/begin/waynew/simple2.chpl, test/parallel/taskPool/figueroa/TooManyThreads.chpl
Resolves #15756.
Issue #15756 listed 3 tests that had workarounds for an issue with split-init combined with sync variables. However the workarounds are no longer needed now that we have deprecated assignment to sync variables since the `s.writeEF` calls do not activate split-init.
A sync variable can be split-initialized today without any deprecation warning e.g. `var s: sync int; ...; s = true;`. However:
* if an assignment is desired, it would need to be `writeEF` or else be a deprecation
* if the code in the `...` uses the sync variable, it should be an error reported by the compiler (for module-level code or code within a function)
We still have issue #15769 for the more general question of how one should write a variable that isn't default initialized.
=> Remove workarounds for issue #15756

compiler/dyno/test/resolution/testReturnTypes.cpp
Clang won't pick these up despite claiming to understand
the flags. It's not fun breaking builds for other people
only.
This is pretty trivial and I'll probably merge it myself tomorrow
morning. Just wanted to "sleep" on it.
TESTING
- The current main didn't build `make test-dyno` on `chapcs11`,
but this branch did. I can't reproduce the bug locally due to
having Apple Clang and no GCC.
=> dyno: Fix GCC-specific warnings in testReturnTypes

doc/rst/usingchapel/prereqs.rst
These versions are required by LLVM, and have full C++17
support. At some point in the future, we would like to
be able to use C++17 as well. See also the following
issue for a more in-depth discussion.
https://github.com/chapel-lang/chapel/issues/20232
=> Update prereqs to require GCC 7.1 or Clang 5.0

modules/internal/ChapelLocale.chpl
Made some small improvements to the locale docs:
- Added return types to public methods that did not already have them: `maxTaskPar`, `numPUs`, `runningTasks()`. 
- Made minor changes to the layout of method descriptions to make them more uniform. I.e. the first line should be a terse description of what the method does, then additional details in the next paragraph if necessary, then the return/argument types, and more advanced notes should be at the end. 
Note: `numPUs` needs to be changed to `numPus`; however, I am waiting on the discussion in this issue https://github.com/chapel-lang/chapel/issues/20445 to finish before moving forward.
=> locale module documentation improvements

modules/standard/IO.chpl, modules/standard/Subprocess.chpl, test/io/tzakian/recordReader/test.chpl, test/library/standard/IO/ioHintSetOperations.chpl, test/library/standard/IO/ioHintSetOperations.good, test/release/examples/benchmarks/shootout/revcomp-fast.chpl, test/release/examples/benchmarks/shootout/revcomp.chpl, test/studies/shootout/reverse-complement/bharshbarg/revcomp-begin.chpl, test/studies/shootout/reverse-complement/bharshbarg/revcomp-buf.chpl, test/studies/shootout/reverse-complement/bharshbarg/revcomp-line.chpl, test/studies/shootout/reverse-complement/bharshbarg/revcomp-mark-skip-read-begin.chpl, test/studies/shootout/reverse-complement/bradc/revcomp-blc-begin-const-ref.chpl, test/studies/shootout/reverse-complement/bradc/revcomp-blc-begin-const-ref.verify.chpl, test/studies/shootout/reverse-complement/bradc/revcomp-blc-begin-ref.chpl, test/studies/shootout/reverse-complement/bradc/revcomp-blc-copyPropBug.chpl, test/studies/shootout/reverse-complement/bradc/revcomp-blc-tpv.chpl, test/studies/shootout/reverse-complement/bradc/revcomp-blc.chpl, test/studies/shootout/reverse-complement/bradc/revcomp-dowhile-bug.chpl
Per the discussion in this issue: https://github.com/chapel-lang/chapel/issues/20346:
- `QIO_METHOD_PREADPWRITE` was added to the `ioHintSet` type as a new hint called `noMmap`
- The hidden `ioHintSet.direct` method was renamed to `ioHintSet.fromFlag()` as its name conflicted with the "direct" iohint that may be added at some point in the future.
- Switched uses of `ioHintSet.direct(QIO_HINT_PARALLEL)` to `ioHintSet.mmap`
Tests and library code were updated to reflect the above changes.
=> Add noMmap hint to ioHintSet

runtime/include/chpl-gpu.h, util/chplenv/chpl_gpu.py
Also while I'm at it add some checks for valid options to CHPL_GPU_MEM_STRATEGY and ensure we use unified memory by default
=> Fix llvm build failure in gpu runtime

doc/rst/conf.py
As things stand, we get warnings about unknown identifiers from LLVM,
which get escalated to errors in CI. For example, a PR using `llvm::SmallSet`
issued the following warnings when building documentation:
```
cpp:identifier reference target not found: llvm
cpp:identifier reference target not found: llvm::SmallPtrSet<const Scope*, 5>
```
These are LLVM symbols, specifically ones from the support library. As
Dyno (and possibly other parts of the code) are starting to rely on 
LLVM's support library, Doxygen will keep running into these. We can
either let Doxygen also generate documentation for LLVM, or we
can silence the LLVM-specific warnings. The latter seems more
appropriate, since it's _Chapel_ documentation we're interested in.
Signed-off-by: …
=> Ignore LLVM identifiers when generating Chapel library docs

compiler/passes/checkParsed.cpp, modules/standard/IO.chpl, test/deprecated/IO/ioOperator.chpl, test/deprecated/IO/ioOperator.good, test/functions/operatorOverloads/operatorMethods/allOps/ioOperator.good, test/visibility/except/operatorsExceptions/DefinesOp.chpl, test/visibility/except/operatorsExceptions/exceptIO.chpl, test/visibility/except/operatorsExceptions/exceptIO.good, test/visibility/import/enablesUnqualified/multipleUnqualified/operatorsAlone.good, test/visibility/import/enablesUnqualified/multipleUnqualified/operatorsFirst.good, test/visibility/import/enablesUnqualified/multipleUnqualified/operatorsLast.good, test/visibility/import/enablesUnqualified/operatorsAlone.good, test/visibility/only/operatorsAlone.good, test/visibility/only/operatorsFirst.good, test/visibility/only/operatorsLast.good
This PR deprecates the ``<~>`` operator in general as well as our usage of the operator in the IO module.
Testing:
=> Deprecate IO Operator

compiler/resolution/functionResolution.cpp, test/classes/delete-free/borrowed/coercions-to-init-borrowed.chpl, test/classes/delete-free/coercions-generic.chpl, test/classes/delete-free/coercions-shared.chpl, test/classes/delete-free/lifetimes/record-borrows.chpl, test/classes/delete-free/lifetimes/stecil-setup.chpl, test/classes/delete-free/tests-from-design-overview/new-myclass.chpl, test/classes/errors/warn-misleading-new-unmanaged.chpl, test/classes/errors/warn-misleading-new-unmanaged.good, test/classes/errors/warn-misleading-new.chpl, test/classes/errors/warn-misleading-new.good, test/classes/ferguson/generic-field/generic-field-unmanaged-borrowed.chpl, test/classes/initializers/generics/phase1/hasLoopGood.chpl, test/classes/lydia/staticMethodInheritance-whenField.chpl, test/classes/vass/ref-like-intents/inout-subclass.good, test/classes/vass/ref-like-intents/ref-subclass.good, test/classes/waynew/dyndis2.chpl, test/modules/diten/mutualuse2.chpl, test/trivial/jturner/iter_overload_simple.chpl, test/visibility/private/uses/accessSecondary.chpl, test/visibility/private/uses/accessSecondary.good, test/visibility/private/uses/pointOfInstantiation/methodOnType2.chpl, test/visibility/private/uses/pointOfInstantiation/methodOnType2.good
For
* https://github.com/Cray/chapel-private/issues/3674
* https://github.com/Cray/chapel-private/issues/3680
This PR adds a warning for patterns like
``` chapel
var x: borrowed C = new C(); // warn
x = new shared C(); // warn
```
including in variable initialization, split init, and assignment cases.
What happens in these patterns in that the result of the `new` expression is stored into a temporary variable and then that is borrowed from. That is because we have implicit conversions from owned/shared to borrowed. It is unlikely that this pattern is useful (specifically when the RHS is a `new` expression) and so this PR adds a warning for that case.
=> Warn for misleading 'new' pattern

test/gpu/native/studies/shoc/EXECOPTS, test/gpu/native/studies/shoc/sort.good, test/gpu/native/studies/shoc/triad.good, test/gpu/native/studies/shoc/triadalt1.good, test/gpu/native/studies/shoc/triadalt2.good, test/gpu/native/studies/shoc/triadchpl.good
We're getting timeouts on some of our implementations of the SHOC benchmarks when our nightly `cray-cs-gpu-native-gasnet` job runs.
Looking at our performance graphs I'm thinking this is fallout from this PR:
https://github.com/chapel-lang/chapel/pull/20460
We should investigate the cause of the performance change but I don't think it's worth having our correctness tests continue to fail in the meantime.
Currently we're running "5 passes" of each benchmark regardless of whether we're doing so for checking correctness or measuring performance. I don't think it's necessary to run it 5 times for correctness so this PR changes it to only run 1 time under this configuration.
Ultimately, we might want to move away from having separate correctness and performance jobs for these tests (it's …
=> For SHOC correctness tests only do one pass

compiler/codegen/library.cpp
This PR adds translation of make to cmake style variables 
to the `.cmake` files written by our cmake library interop
code generation. 
* Previously, if getCompilelineOption returned a path that included 
an env var, it was formatted as `make` would expect, e.g., `$(FOO)`.
`cmake` doesn't read that correctly and expects `${FOO}`, so in 
some environments the interop would fail to build a valid 
`MyLibraryName.cmake` file. This change adds a call to 
`makeToCMake` when writing the `.cmake` file lines for 
`CHPL_COMPILER`, `CHPL_LINKER` and `CHPL_LINKERSHARED`
TESTING:
reviewed by @mppf - thank you!
=> fix(C-interop): fix cmake interop failure in some cases

third-party/gasnet/README, third-party/gasnet/gasnet-src/aries-conduit/Makefile.in, third-party/gasnet/gasnet-src/configure.in, third-party/gasnet/gasnet-src/ibv-conduit/Makefile.in, third-party/gasnet/gasnet-src/mpi-conduit/Makefile.in, third-party/gasnet/gasnet-src/ofi-conduit/Makefile.in, third-party/gasnet/gasnet-src/other/Makefile-conduit.mak.in, third-party/gasnet/gasnet-src/other/Makefile-echovar.mak, third-party/gasnet/gasnet-src/other/Makefile-libgasnet.mak.in, third-party/gasnet/gasnet-src/smp-conduit/Makefile.in, third-party/gasnet/gasnet-src/ucx-conduit/Makefile.in, third-party/gasnet/gasnet-src/udp-conduit/Makefile.in
Bring in https://bitbucket.org/berkeleylab/gasnet/pull-requests/554 and
some related work to enable getting `GASNET_LD_REQUIRES_MPI` out of
gasnet's pkg-config file. This is a follow up to #20385, which has
additional motivation for the change.
=> Bring in upstream gasnet patch for checking if LD requires MPI

test/gpu/native/jacobi/flags-warn-unstable.good
We have a test that locks down that we produce a warning when using the GPU locale model and `--warn-unstable`. It looks like after this PR:
https://github.com/chapel-lang/chapel/pull/20486
We modified the filename/location of this message.
=> Update GPU test locking down warn-unstable message

compiler/dyno/include/chpl/resolution/can-pass.h, compiler/dyno/lib/resolution/Resolver.cpp, compiler/dyno/lib/resolution/can-pass.cpp, compiler/dyno/lib/resolution/resolution-queries.cpp, compiler/dyno/test/resolution/testReturnTypes.cpp
This PR makes several small improvements to the `commonType` function
and the if-expression resolution code.
* `commonType` now returns an llvm::Optional representing whether or not
a common type was successfully found. This helps distinguish the
case when an `UnknownType` was determined to be the common type
(not an error) from the case when no common type could be found
(an error).
* `commonType` now also accepts `useRequiredKind` and `requiredKind`
via another llvm::Optional.
* `commonType` now properly handles the types vector containing an
UnknownType. Previously, the intent computation code would
replace the `UNKNOWN` intent with whatever was computed (such as
`CONST_VAR`), which would create a non-`UNKNOWN` type with
a missing `Type*`. This is not semantically correct.
* …
=> Make improvements to commonType and if expressions

test/associative/types/testBorrowed.bad, test/associative/types/testBorrowed.future, test/associative/types/testBorrowed.good, test/classes/delete-free/borrowed/borrowed-if-expr.chpl, test/classes/diten/subclassMethodCall.chpl, test/io/vass/writeThis-on.chpl, test/library/packages/ZMQ/not-serializable.chpl, test/library/packages/ZMQ/weather.chpl, test/modules/figueroa/DuplicateConfigVars/DuplicateConfigVars.chpl, test/param/ifExprCopyInitBug.chpl
Most of these ran only with CHPL_COMM!=none or were .futures so I didn't
catch them in my initial pass.
Correct some incorrect automatic translations and avoid doing
'new borrowed C()' in a few places.
=> Clean up most of the test failures from last night

test/arrays/deitz/part3/test_record_of_array_type.bad, test/arrays/deitz/part3/test_record_of_domain_type.bad
Adjust the .bad files for two futures related to runtime types.
=> Adjust .bad files for RTT futures

runtime/src/comm/ofi/comm-ofi.c
Call `fi_mr_desc` and `fi_mr_key` after `fi_mr_bind` and `fi_mr_enable`. The MR key is invalid prior to those two calls.
Resolves https://github.com/chapel-lang/chapel/issues/20520.
=> Fix FI_MR_PROV_KEY support.

util/cron/nightly, util/cron/test-linux64-python35.bash
Adds a flag to nightly that can be used with jobs to test versions of Python 3
that are no longer supported by chpldoc and start_test.  This is separate from
the python2 flag, since Python 2 can have additional constraints.  Use this flag
with the job tracking Python 3.5.
This should avoid the sporadic failures we've been seeing when the job happens
to run with the version of Python it is supposed to.  Other changes will be
necessary to avoid running places where Python 3.5 doesn't exist and to ensure
that the correct version of Python is used, but I think this should get in
independently of those.
Tested the Python 3.5 job using the `-debug` flag
----
=> Adjust the Python 3.5 job to behave more like the Python 2.7 job

compiler/codegen/codegen.cpp, compiler/include/misc.h, compiler/llvm/clangUtil.cpp, compiler/main/driver.cpp, compiler/optimizations/gpuTransforms.cpp, compiler/util/misc.cpp, runtime/src/gpu/cuda/gpu-cuda.c, test/gpu/native/page-locked-mem/jacobi.chpl
For the GPU locale model we don't want wide pointers inside kernel functions (which we consider a local block) but we still want to force wide pointers outside of it.
Implementing this just involved special casing the GPU locale model in `forceWidePtrsForLocal()` in `util/misc.cpp`.
This will ensure that when using the `array_on_device` strategy with a program like the following `A` will be a wide pointer so that we perform the `get` that's necessary to copy the data for A from the GPU to the host for the `write`:
```chpl
on here.gpus[0] {
var A : [0..10] int;
writeln(A);  // Previously this would crash when
// GPU_MEM_STRATEGY=array_on_device
}
```
Long term we'll want to update insert wide references pass to be cognizant of the GPU locale model but that's going to be a bit of a project. …
=> Fix to ensure we support `writeln` when `CHPL_GPU_MEM_STRATEGY=array_on_device`

modules/internal/ChapelBase.chpl, modules/standard/ChplConfig.chpl, test/gpu/native/page-locked-mem/COMPOPTS
Based on value of CHPL_GPU_MEM_STRATEGY (previously if using the array_on_device strategy you would need to explicitly pass -schpl_defaultGpuArrayInitMethod=ArrayInit.gpuInit to chpl).
This PR changes this so that CHPL_GPU_MEM_STRATEGY is accessible from the `ChplConfig` module. We can then later look at this value to determine what `chpl_defaultGpuArrayInitMethod` should be set to by default.
I no doc'd this inclusion of CHPL_GPU_MEM_STRATEGY in the `ChplConfig` module as I think we might move away from having this set by environment variable sometime in the future so I'd rather users not have access to it in the meantime.
=> Set defaultGpuArrayInitMethod automatically

compiler/resolution/functionResolution.cpp, compiler/resolution/lowerIterators.cpp, modules/dists/CyclicDist.chpl, modules/standard/Random.chpl, test/errhandling/codePathCoverage/ifOrThrow2.bad, test/errhandling/codePathCoverage/ifOrThrow2.future, test/errhandling/parallel/forall-iterator-throws-at-end.chpl, test/errhandling/parallel/forall-iterator-throws-at-end.good, test/functions/resolution/ignore-unreachable.chpl, test/functions/resolution/ignore-unreachable.good, test/library/standard/Random/RandomStreamInterface/choiceTestErrors.chpl, test/library/standard/Random/RandomStreamInterface/choiceTestLowbounded.chpl, test/library/standard/Random/RandomStreamInterface/choiceTestLowbounded.good, test/statements/conditionals/param/nonparam-and-false.bad, test/statements/conditionals/param/nonparam-and-false.chpl, test/statements/conditionals/param/nonparam-and-false.future, test/statements/conditionals/param/nonparam-and-false.good, test/types/records/intents/out-intent.good, test/users/weili/typefnbug.future
Resolves or affects #14683 #15691 #18597 #20481
When a code block has a statement that interrupts the control flow, such as:
* `return`
* `throw`
* call to a function that terminates the program, like `halt()`
* an `if` whose both branches have this interruption property
then the remainder of the code block is discarded as unreachable.
The following function is now inferred to return `void` because its return statement is discarded:
```chpl
proc testit() {
if true {
halt();
}
return 5;
}
```
There are several places in our code base where we use code like the above, in several shapes and forms, to lead the compiler to infer the desired return type. This PR adjusts those cases that came up in testing. Ex. adjusted .bad for: `test/errhandling/codePathCoverage/ifOrThrow2.chpl`
The following …
=> Ignore unreachable code during resolution

compiler/dyno/include/chpl/types/QualifiedType.h, compiler/dyno/include/chpl/types/TupleType.h, compiler/dyno/lib/resolution/Resolver.cpp, compiler/dyno/lib/resolution/can-pass.cpp, compiler/dyno/lib/types/QualifiedType.cpp, compiler/dyno/lib/types/TupleType.cpp, compiler/dyno/test/resolution/testExprIf.cpp
This is needed for the resolution of if-expressions with `param`
conditions. An if-expression depending on a `param bool` without a value
should be considered unknown (as is the case for an if-expression
depending on any other unknown value).
This commit also implements special-case behavior for `param _tuple`
types, which have their tuple elements' values encoded in the
`QualifiedType`s of the `TupleType`, but not stored into a `Param*`.
There is discussion in https://github.com/chapel-lang/chapel/issues/20487 
about how to properly represent param tuples. It is likely that in the
event that we add param tuples to Dyno, we will settle on a representation
that includes a special `Param` that contains tuple values. This would
preclude the need for special-case handling in isUnknown. In the …
=> dyno: make params without values be considered unknown

compiler/dyno/lib/resolution/resolution-queries.cpp, compiler/dyno/test/common.cpp, compiler/dyno/test/common.h, compiler/dyno/test/resolution/testFunctionCalls.cpp
This PR ensures that Dyno rejects more calls to functions in which types of
later formals depend on the types / values of earlier ones. The canonical
example of the issue present on main is the following:
```Chapel
proc f(param a: bool, param b: if a then string else int) {}
f(true, "hello"); // passes
f(false, 0) // passes
f(true, 0) // also passes, but shouldn't!
```
The issue is that Dyno first computes an initial function signature without
knowing the types of the actuals, which in the case of `f` above is:
```Chapel
proc f(param a: bool, param b: UnknownType) {}
```
We allow formals of `UnknownType` to accept any actuals, so this initial
signature allows for all of the three calls in the example above. We eventually
compute an instantiated function signature, which does have `b: …
=> dyno: fix function resolution for dependent formals

compiler/dyno/include/chpl/framework/Context.h, compiler/dyno/include/chpl/framework/all-global-strings.h, compiler/dyno/include/chpl/framework/query-impl.h, compiler/dyno/include/chpl/resolution/scope-queries.h, compiler/dyno/include/chpl/uast/Builder.h, compiler/dyno/include/chpl/uast/BuilderResult.h, compiler/dyno/lib/resolution/resolution-queries.cpp, compiler/dyno/lib/resolution/scope-queries.cpp, compiler/dyno/lib/uast/BuilderResult.cpp
I individually tested each performance change in
https://github.com/Cray/chapel-private/issues/3702; check it out if interested.
On my local machine, though, the three changes (one per commit) brought
Dyno average execution time[^1] from 20 runs from 463ms to 382ms,
a net improvement of roughly 17%.
The changes consisted of:
1. Using `SmallPtrSet` for the set of visited scopes when looking up
names in scopes.
2. Using `DenseMap` for the `queryDB` in `Context`
3. Using `DenseMap` for the uAST builder when mapping node IDs
to various other things.
In order to be able to use `llvm::DenseMap` with ID keys, we needed
to provide a template specialization for the `DenseMapInfo` struct. This
struct specifies how IDs should be hashed and compared for equality. It also
requires that we provide two …
=> dyno: use LLVM data structures to improve performance

util/cron/common.bash
=> Add output of python3 version information to common.bash instead

modules/standard/IO.chpl, test/io/ferguson/readThis/readclass.chpl, test/io/ferguson/readThis/readclass2.chpl, test/io/ferguson/readThis/readclass3.chpl, test/io/ferguson/recordeof.chpl, test/io/literals/match-literal.chpl, test/io/literals/match-literal.compopts, test/io/literals/match-literal.good, test/io/literals/mismatch-read-write.chpl, test/io/literals/mismatch-read-write.cleanfiles, test/io/literals/mismatch-read-write.compopts, test/io/literals/mismatch-read-write.prediff, test/io/literals/mismatch-read-write.template.good, test/io/literals/read-literal.chpl, test/io/literals/read-literal.compopts, test/io/literals/read-literal.good, test/io/literals/utf8-literal-error.chpl, test/io/recordio.chpl, test/unstable/readMatchLiteral.chpl, test/unstable/readMatchLiteral.good
This PR introduces new methods on channels to support reading and writing of literal strings, bytes, and newlines. The new methods, as discussed in #19487:
```chpl
proc channel.readLiteral(literal:string, ignoreWhitespace=true) : void throws
proc channel.readLiteral(literal:bytes, ignoreWhitespace=true) : void throws
proc channel.readNewline() : void throws
// returns 'false' if literal could not be matched, or on EOF
proc channel.matchLiteral(literal:string, ignoreWhitespace=true) : bool throws
proc channel.matchLiteral(literal:bytes, ignoreWhitespace=true) : bool throws
proc channel.matchNewline() : bool throws
proc channel.writeLiteral(literal:string) : void throws
proc channel.writeLiteral(literal:bytes) : void throws
proc channel.writeNewline() : void throws
```
These methods will be …
=> Introduce unstable read/match/write methods for literals and newlines

third-party/chpl-venv/chpldoc-requirements1.txt, third-party/chpl-venv/chpldoc-requirements2.txt, third-party/chpl-venv/test-requirements.txt
Our testing system is now no longer relying on the deprecated Python 3.6,
enabling us to use newer versions of these packages which drop support
for that version of Python.
This PR updates:
- filelock from 3.4.1 to 3.7.1
- MarkupSafe from 2.0.1 to 2.1.1
- Jinja2 from 3.0.3 to 3.1.2
It does not update:
- setuptools, due to encountering a bug when processing the skipif for
test/studies/dedup/dedup_externblock.chpl
- docutils because sphinx-rtd-theme has not been updated to be compatible
with it
- Sphinx because later versions require a more up-to-date version of breathe
- breathe because later versions generate warnings that we treat as error, a
known issue.
- PyYAML, argcomplete, Pygments and Babel because they were up to date
in July.
Spot checked some files in the generated documentation …
=> Update versions of three python packages we rely on now

runtime/src/comm/ofi/comm-ofi.c
The libfabric comm layer is only partially initialized when there is only one locale to avoid unnecessary overheads. In this situation we should not initialize the fabric domain because doing so depends on other parts of the libfabric layer that have not been initialized.
Passes all multi-locale tests on an EX except for the following failures which appear to be unrelated.
```
[Error matching program output for library/packages/Collection/CollectionCounter (compopts: 2)]
[Error: Timed out executing program library/packages/Collection/CollectionNQueens (compopts: 1)]
[Error matching program output for parallel/forall/task-private-vars/count-tpvs]
```
=> Do not initialize fabric domain when there is only one locale

test/errhandling/parallel/forall-iterator-throws-at-end.skipif
`forall-iterator-throws-at-end.chpl` behaves the same way as `forall-iterator-throws-follower.chpl` -- both tests cause the error: "throwing non-inlined iterators are not yet supported".
The latter test is skipif-ed in --baseline testing. This PR adds an identical skipif to the former. This skipif should have been there from the beginning.
Suggested by @bradcray
=> Add forall-iterator-throws-at-end.skipif

modules/internal/ChapelLocale.chpl, test/unstable/locale-numPUs.chpl, test/unstable/locale-numPUs.good
In the discussion here: https://github.com/chapel-lang/chapel/issues/20445, and a recent re-reveiew, we decided to mark `locale.numPUs` as unstable.
This PR:
* Adds the unstable flag to the method
* Adds an instability test
=> Mark `locale.numPUs` as unstable

util/cron/test-linux64-python36.bash
Now that those tools are relying on python packages that have dropped support
for 3.6, this configuration is no longer expected to work with them.  So have
it behave like the Python 3.5 job
----
=> Update Python 3.6 job to not use start_test or chpldoc any more

util/chplenv/chpl_llvm.py
This PR adjusts the chplenv scripts so that `chpl` builds on Mac OS X with system LLVM will link LLVM and Clang dynamically. That makes Mac OS X less of an exception in this regard.
We were originally statically linking on Mac OS X with system LLVM due to problems with upstream LLVM and Homebrew in building a dynamic library that works with `llvm-config` (in particular, there were errors about a versioned file, like `libLLVM-11.dylib`, missing). See [this LLVM bug report](https://github.com/llvm/llvm-project/issues/39599). However this should be fixed in Homebrew llvm@12 and newer.
Note that we are currently still statically linking for CHPL_LLVM=bundled.
Future Work:
* I observed a problem CHPL_LLVM=none and llvm@11 on Monterey, but this problem exists also on 'main', and this PR does …
=> Link LLVM and clang dynamically on Mac OS X

modules/internal/ChapelLocale.chpl
Implementing the changes to `runningTasks`' documentation discussed here: https://github.com/chapel-lang/chapel/issues/20219
The general goal is to explain the purpose of the method without locking it into a particular definition of "currently-running", as the implementation may be slightly changed/improved in the future.
=> Improvements to `locale.runningTasks` docs

modules/minimal/internal/IO.chpl, test/modules/bradc/printModStuff/foo.good, test/trivial/diten/printvisibleOptFalse.good
Update some tests for a slightly different module initialization order and
make the minimal-modules version of 'errorCode' point at the proper C name
for it. This fixes the errors we had in the linux64 and basic gasnet
configurations last night.
=> Fix test errors in minimal-modules and print-init-order tests

compiler/dyno/tools/chpldoc/chpldoc.cpp
This PR adds an initializer to the `RstResultBuilder` struct in the new
`chpldoc`. Previously the code relied on implicit instantiation, but some 
compilers complain about this and so it breaks our smoke-tests.
TESTING:
Reviewed by @dlongnecke-cray - thank you!
=> fix(chpldoc): add explicit initializer for RstResultBuilder

compiler/resolution/functionResolution.cpp, test/deprecated/typeQueryFuncs.chpl, test/deprecated/typeQueryFuncs.good, test/unstable/typeQueryFuncs.chpl, test/unstable/typeQueryFuncs.good
After merging this PR: https://github.com/chapel-lang/chapel/pull/20466 (which deprecates subtype comparison operators; e.g. `someDerivedType < subBaseType`), we realized there's a user code that will encounter this deprecation warning over a hundred times.
Proceeding with this as deprecated might, ultimately, be the right thing to do, but we'd like to gather user feedback (in part to make sure we're not deprecating a favorite feature).
This PR changes these operators from being deprecated to being marked unstable. This will also give other users the chance to to measure the impact of this by opting into the warnings (by using `--mark-unstable`) rather than having them displayed with each compilation.
=> Make subtype comparison operators unstable

util/buildRelease/gen_release
This PR sets `CMakeLists.txt` files to be explicitly copied into release tarballs
by modifying the `gen_release` script.
I suspect we have been getting away without copying the `CMakeLists.txt` files
into the release tarball because we have been maintaining two build systems for
all the new `dyno` stuff. Now that `dyno-chpldoc` has replaced `chpldoc`, we rely
on `cmake` to build it.
TESTING:
=> fix(release): copy CMakeLists.txt files to tarball

util/buildRelease/gen_release
Reverts chapel-lang/chapel#20581 based on failing smoke-tests
=> Revert "fix(release): copy CMakeLists.txt files to tarball"

compiler/dyno/tools/chpldoc/chpldoc.cpp
Reverts chapel-lang/chapel#20580 based on failing smoke-tests
=> Revert "fix(chpldoc): add explicit initializer for RstResultBuilder"

util/devel/test/singularity/README.md, util/devel/test/singularity/current/amazonlinux-2022/singularity.def, util/devel/test/singularity/current/ubuntu-kinetic/singularity.def
This PR makes some little updates to improve portability testing with singularity. None of these scripts are currently run in nightly testing.
* Adds some more notes to the README
* Fixes the amazonlinux-2022 configuration by removing a workaround
* Adds a singularity image for Ubuntu Kinetic
Reviewed by @bhavanijayakumaran - thanks!
=> singularity portability testing updates

util/chplenv/chpl_llvm.py
This is a follow-up to PR #20396.
In doing some portability testing, I noticed that the `quickstart` configuration was not working on a 32-bit Debian 11 image. The problem was that the image has the right LLVM/clang packages installed, but Chapel does not support using LLVM on a 32-bit platform right now. The result was that `quickstart` set CHPL_LLVM=system but that led to errors later on from `printchplenv` / `make`.
This PR just adjusts the `chpl_llvm.py` code determining the quickstart setting for CHPL_LLVM to use `none` if the platform is not supported for Chapel+LLVM.
Reviewed by @bhavanijayakumaran and @daviditen - thanks!
=> avoid quickstart CHPL_LLVM=system on incompatible platforms

test/users/npadmana/mpi/test_mpi.chpl
This is a follow-up to PR #20528 and it is about this test
```
test/users/npadmana/mpi/test_mpi.chpl
```
This test had several loops of the form
``` chapel
for irank in 0.. #worldSize { }
```
where `worldSize` has type `c_int`. After changes in PR #20528, these loops now have an iteration variable of type `int` aka `int(64)` which is intentional since the count isn't supposed to impact the range type. But that caused problems in this test since the body of the loop expected `irank` to have type `c_int`.
This PR fixes these loops to use the pattern `0..<worldSize` which will infer the range index type as `c_int`.
=> Fix test_mpi to use `0..<worldSize`

modules/dists/BlockDist.chpl
Now that duplicate targetLocales are no longer allowed for block arrays,
we know that the local array pointer `myLocArr` is safe to use. Using it
instead of `locArr[locid]` allows us to do scan operations on narrow
pointers, which reduces any wide pointer overhead.
On a 128-core Rome CPU running with just 2 cores this takes a 16G Block
scan from 4.9s to 2.9s, bringing it on par with DR. This has no real
impact when using all 128 cores since we're bandwidth bound. I expect
this to improve performance on systems with fewer cores and in cases
where not all cores are used (e.g. serial scan in a parallel region)
=> Use narrow arrays for blockdist scan

test/mason/mason-external/libtomlc99/mason-external.suppressif, test/mason/mason-external/masonExternalRanges/mason-external-range.suppressif
The spack version we currently use for mason external only supports up
to python 3.8 and fails for anything newer. Suppress these failures
until we can upgrade spack versions.
https://github.com/chapel-lang/chapel/issues/19517 captures python version info
https://github.com/Cray/chapel-private/issues/3518 captures desire to upgrade spack
=> Suppress mason-external (spack) failures with newer python

modules/internal/ChapelArray.chpl, test/deprecated/deprecatedArrayFunctions.chpl, test/deprecated/deprecatedArrayFunctions.good, test/unstable/arrayFuncs.chpl, test/unstable/arrayFuncs.good
Earlier I jumped the gun on making these deprecated in this PR: https://github.com/chapel-lang/chapel/pull/20140
The backing issue for that is here: https://github.com/chapel-lang/chapel/issues/18089
Given that we don't have consensus on what to do with these functions and we're approaching code freeze marking them "unstable" for now seems like the sensible thing to do. This isn't to imply things will be left as `@unstable`: we need to make a decision for Chapel 2.0 but I think it can wait until next release.
Arguably since these are no longer deprecated I should also pull back the test changes I made in the original PR (https://github.com/chapel-lang/chapel/pull/20140) but I think it's unlikely anything that these would have regressed and the "unstable" test I'm adding provides a little …
=> Mark array sorted, reverse, find, and count @unstable

compiler/AST/ForLoop.cpp, modules/internal/ChapelRange.chpl, test/types/range/elliot/anonymousRangeIter.expectedGenCode
Follow-up to PR #20528.
This PR fixes a test failure for test/types/range/elliot/anonymousRangeIter.chpl.
=> Fix anonymousRangeIter test after disambiguation PR

compiler/optimizations/gpuTransforms.cpp, modules/standard/GPU.chpl, test/gpu/native/assertOnFailToGpuize.1.good, test/gpu/native/assertOnFailToGpuize.2.good, test/gpu/native/assertOnFailToGpuize.3.good, test/gpu/native/assertOnFailToGpuize.4.good, test/gpu/native/assertOnFailToGpuize.5.good, test/gpu/native/assertOnFailToGpuize.6.good, test/gpu/native/assertOnFailToGpuize.7.good, test/gpu/native/assertOnFailToGpuize.8.good, test/gpu/native/assertOnFailToGpuize.chpl, test/gpu/native/assertOnFailToGpuize.compopts, test/gpu/native/gpuWritelnAndAssertOnGpu.chpl, test/gpu/native/gpuWritelnAndAssertOnGpu.good
This change will cause `assertOnGpu` to produce a compile time error in any loop that contains it if that loop fails to GPUize.  This also lets us give some better error messages to explain why a loop failed to GPUize (for example: because it had a call to a recursive function or because it accesses a global variable).
Some additional details:
* I inline the assertOnGpu() procedure so by the time we get gpuTransforms I can just check for the presence of the primitive we use for this.
* From an optimal performance standpoint it's probably not great that I'm introducing an extra pass over the loop body to look for the presence of this primitive. We end up doing a later pass over the loop body anyway so in theory I could try and restructure things to do the check there. In practice I …
=> assertOnGpu do compiletime assert if not gpuizable

compiler/dyno/tools/chpldoc/chpldoc.cpp
This PR fixes an error reported by `chapelmac` smoketests.
The compiler did not like
`const auto& ast : builderResult->topLevelExpressions())`
and complained about the iterator being copied on every loop. 
It suggested replacing the statement with 
`const chpl::uast::AstNode* ast : builderResult->topLevelExpressions())`
which is the change that I implemented. 
TESTING: 
reviewed by @benharsh - thank you!
=> fix(chpldoc): address failed smoketest on mac-overflow

modules/internal/ChapelRange.chpl, test/types/range/nonIntTypes/countedByBool.chpl, test/types/range/nonIntTypes/countedByBool.good
This is to fix a problem building Arkouda after PR #20595.
It is not so clear to me that it makes sense to have a `bool` count, but since `bool` can coerce to an integer type, it seems OK. Before PR #20528, the count arguments were matching the low bound type, but that PR changed them to `integral` to match other choices about counting. However, `count:integral` arguments cannot currently accept a `bool` (but issue #20011 requests that they could). Since the helper code will cast them appropriately, this PR just removes the type constraint.
Reviewed by @benharsh and @bradcray - thanks!
=> Allow iterating over range counted by bool & test it

modules/internal/ChapelArray.chpl, test/deprecated/arrayIndicesAlwaysLocal.chpl, test/deprecated/arrayIndicesAlwaysLocal.compopts, test/deprecated/arrayIndicesAlwaysLocal.good
Remove this outdated/deprecated mechanism for changing the
behavior of `array.indices` which was used to transition from
old behavior to new.  Removing it to clean up.
=> Deprecate 'arrayIndicesAlwaysLocal'

Makefile, Makefile.devel, compiler/Makefile, compiler/dyno/Makefile.help, compiler/dyno/tools/chpldoc/Makefile, compiler/dyno/tools/chpldoc/Makefile.include
This PR adjusts `chpldoc` (which is now the dyno-chpldoc) to build entirely with `make` instead of using `cmake`. This is a temporary measure for this release. In the future it would be good to use `cmake` for this and other tasks and that is possible now that `cmake` is a dependency. However, building `chpldoc` only with `make` will simplify the transition to dyno-chpldoc.
=> Build dyno-chpldoc with Makefiles only

test/gpu/native/assertOnFailToGpuize.4.good
This failed our nightly Jenkins GPU tests job (and good thing to since it's a typo). I'm in the habit of manually running the gpu tests before submitting so I'm unsure how I missed this one (possibly I made a last minute change, walked away, then forgot to redo it). Anyway apologies for the noise but I'm glad Jenkins caught it.
=> Fix typo in gpu test

compiler/optimizations/gpuTransforms.cpp
This is a bug introduced by an earlier PR: https://github.com/chapel-lang/chapel/pull/20593, which was causing the following test to fail with a sefault: `gpu/native/multiLocale/cyclicDist`.
Basically I added a better error message in a case where we fail to gpuize but I accidentally removed the `return false` statement that indicates we should fail to gpuize.
The fix for this is easy but what's more concerning is this shows we only have test coverage for this particular failure mode in our gasnet/multilocale test configuration. The (expected) fail-to-gpuize occurs when we have a CForLoop who's upper bound doesn't match the expected pattern.  I'll add another issue about trying to beef up test coverage for this (and related cases) but I'll do it outside this PR.
=> accidentally allow gpuization on failing upper-bounds check

doc/rst/usingchapel/QUICKSTART.rst, doc/rst/usingchapel/chplenv.rst, doc/rst/usingchapel/prereqs.rst
This PR includes docs updates related to PRs #19565 and #20396. This PR documents:
* changes to how quickstart works
* CHPL_LLVM_SUPPORT and the llvm support library being required.
While there, I:
* adjusted prereqs.rst to only list the supported LLVM versions once and to say it is "LLVM and clang" that is needed
* added sections in chplenv.rst for CHPL_LLVM_SUPPORT, CHPL_LLVM_CONFIG, and CHPL_LLVM_GCC_PREFIX
=> Update docs related to build changes

doc/rst/developer/bestPractices/Potpourri.rst
`grepgoods` and `greptestoutputs` have been merged into `greptests` and
`greptests` has been expanded to include more options.  This change removes the
old entries and expands the entry for `greptests`.
Passed `make docs`
=> Update Potpourri.rst for changes to the util/devel/grep scripts

doc/rst/language/spec/ranges.rst, modules/internal/ChapelRange.chpl, test/deprecated/alignedBoundsByDefault.good
While reviewing my the range docs after my changes to its behavior
last night, I found some pre-existing bugs that needed fixing,
that the operators were now being generated by chpldoc, and some
other opportunities for cleanup.  Summarizing, they were:
* the expected output from the alignedLow/High docs wasn't printing
(and hadn't been in previous releases either)
* the signatures on the param/type queries in the spec used illegal
syntax (though now they fall prey to the poor spacing when
rendered by Sphinx on Chrome.
* I squashed the chpldocumentation of the operators because they're
already described in the text of the spec, which does a better job
of it.  That said, going forward, I think we'd like to find a way to
integrate operator signatures into these sections of the spec so
that …
=> Tidy up range docs

doc/rst/language/spec/ranges.rst
In this release we updated 'by' and '#' on ranges to take any integral
(or boolean, which they had before), but failed to update the spec
to reflect that.  Taking care of that here, now.
=> Update docs for 'by' and '#' on ranges to indicate support for any integral

modules/internal/Atomics.chpl
Updated the text describing atomics to include cast and assignment and then no-doc these operators. I chose this strategy because it seemed that these operators should be documented in a consistent manner with `init=` which is no-doc'd and described in the text.
=> Update atomics docs operators

modules/standard/Random.chpl
These constants are not important to the API for NPBRandom so should not be documented. They are implementation details. This PR simply marks them with `pragma "no doc"`.
=> No-doc some NPBRandom consts

test/parsing/superbigif.suppressif, test/users/ibertolacc/bug-from-issue-9047.suppressif
ASAN significantly increases the size of stack frames. In some experiments, size seemed to go up from roughly `0x180` to `0x2ef0`, which is ~32x larger. Thus, recursive functions that are far from hitting their depth limit under normal circumstances are at risk of stack overflow. In particular, the superbigif and bug-from-issue-9047 tests have large ASTs, and the doAssignIDs function that recursively traverses the ASTs overflows the stack. Since the tests work fine under normal circumstances, it seems like the best course of action is to simply disable the failing cases in ASAN testing. In the future, should recursion depth become a problem in production Chapel code, doAssignIDs can be updated to use something like a queue.
Signed-off-by: Danila Fedorin …
=> Suppress failures from deep recursion under ASAN

test/gpu/native/assertOnFailToGpuize.compopts
Make `assertOnFailToGpuize` not fail our nightly GPU+gasnet configuration.
Not by resolving it, unfortunately, (at least not yet) but by having an executable `.compopts` file that skips the failing configuration when `CHPL_COMM != none`.
We have an issue to make a proper fix here: https://github.com/chapel-lang/chapel/issues/20641
FYI: @DanilaFe (figured you might be interested in this as it vaguely rhymes with your PR https://github.com/chapel-lang/chapel/pull/20636 in that it's an example of filtering out bad behavior from an otherwise working test). Your case had nothing to do with a specific `.compopt` config but for whatever reason I'm reminded of it.
And thanks to @ronawho for showing me how to make an executable `.compopts` file that filters out a specific config.
=> Make assertOnFailToGpuize not fail nightly gasnet config

runtime/src/comm/ugni/comm-ugni.c
In #19516 we updated the ugni MR extent check to consider that the cache can read to the end of a CACHEPAGE (1K), but it turns out the cache can read to the end of a system page (usually 4K). Adjust the extent check to allow the larger system page size check here.
We've seen the MR extent check failures in nightly recently. I haven't been able to come up with a reliable reproducer yet, but I'm confident about this change just from code inspection. I believe we should be able to come up with a reproducer, but I want to get this into the release and I'm timing out coming up with the test case now.
Resolves Cray/chapel-private#3341
=> Fix ugni MR extent check when remote cache is on

doc/rst/language/spec/tuples.rst, modules/internal/ChapelTuple.chpl
Due to the recent changes to `chpldoc` that expose more operators to the public docs, this PR marks most of the Tuple type operators as `no doc`ed, and summarizes them above the type definition instead.
=> Cleaning up Tuple docs

modules/internal/ChapelSyncvar.chpl
This PR "no docs" many operators for `sync` and `single` that were 
exposed when we switched to the new `chpldoc` tool. 
Most of these operators have been deprecated or generate compiler
warnings when used. 
TESTING:
reviewed by @jeremiah-corrado - thank you!
=> fix(doc): add 'no doc' to operators exposed by new chpldoc

modules/internal/ChapelArray.chpl
This PR "no docs" many operators for `ChapelArrays` that were 
exposed when we switched to the new `chpldoc` tool. 
Most of these are documented in the `Arrays` language spec section, and
the ones that aren't are just promotion overloads for scalar
operators. 
TESTING:
reviewed by @DanilaFe - thanks!
=> fix(doc): add no doc to ChapelArray operators

modules/internal/ChapelDomain.chpl
This PR no-docs the operators in ChapelDomain that were exposed by the new chpldoc implementation. Some of these are already documented in the ``domains.rst`` spec file, and others have yet to be stabilized for 2.0.
Testing:
=> no-doc operators in ChapelDomain

doc/rst/language/spec/statements.rst, modules/standard/IO.chpl
This PR updates the IO operator documentation in the modules to point to alternative methods on channels. This PR also updates the spec to warn that the IO operator is now deprecated.
Testing:
=> Update IO operator documentation

doc/rst/language/spec/data-parallelism.rst, doc/rst/language/spec/error-handling.rst, doc/rst/language/spec/procedures.rst, doc/rst/language/spec/task-parallelism-and-synchronization.rst, modules/standard/Errors.chpl
This updates our online docs for the changes implemented in these PRs:
* #20497
* #20601
While there, slightly tidy up the docs on `halt()`.
=> Update docs for changes in this-intents and ignoring unreachable code

doc/rst/conf.py, doc/rst/language/spec/tuples.rst, doc/rst/meta/builtins/index.rst, modules/internal/ChapelTuple.chpl, modules/internal/fixInternalDocs.sh
Implementing the `chapelTuple` portion of this parent issue: https://github.com/chapel-lang/chapel/issues/18027
=> Migrate `tuple` docs from "builtins" section to "language-spec" page

doc/rst/meta/modules/standard.rst, modules/Makefile, modules/standard/GPU.chpl
Add documentation about the new GPU module (with ample warnings that everything in the doc is by nature unstable).
I put this under the "Parallelism/Distributed Computing" category on our [Standard Module's page](https://chapel-lang.org/docs/modules/standard.html) under the idea that GPUs are really about parallelism. Though arguably this could also be put under "Utilities" as what's in there today really is just a couple of utility functions related to GPU support. Longer term I could imagine the module growing to encompass more functionality though.
=> Add gpu module to standard module doc

doc/rst/language/evolution.rst
Adds a section on 'Behavior Differences for Mixes of Signed and Unsigned' to language evolution, based on a draft by @mppf.
=> Update language evolution with section on mixed signed/unsigned

doc/rst/conf.py, doc/util/versionButton.php
This is the usual update to the docs button version numbers to
distinguish 1.28 (now staged in chapel-www) from 1.29 (main).
=> Update docs buttons/versions to reflect staged 1.28 release

util/buildRelease/gen_release
When building the tarball on linux and then untarring it on Mac OS X we were seeing an error like:
chapel-1.28.0/compiler/dyno/tools/chpldoc/BUILD_VERSION: Skipping hardlink pointing to itself: chapel-1.28.0/compiler/dyno/tools/chpldoc/BUILD_VERSION
We did not see this error when untarring on linux.
It turns out that compiler/dyno/tools/chpldoc/BUILD_VERSION was a symbolic link that we listed twice in the tar command so it was included twice in the tar archive. It was included in the explicit files to include section and also automatically added by the loop below:
https://github.com/chapel-lang/chapel/blob/6d2141230691521dc27737d1f1aedc0d516a0977/util/buildRelease/gen_release#L252-L263
Changing the gen_release script to include that file only once in the archive solves the problem. This …
=> Fix the generated tarball on Mac OS X

util/dockerfiles/entrypoint.sh
Saw issue running the commands directly on the container
docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp 41b3b9a9f461 chpl -o hello hello.chplSigned-off-by: bhavanijayakumaran 
Fixed it by replacing /bin/bash with $@
<82669529+bhavanijayakumaran@users.noreply.github.com>
=> Fix entry point script

compiler/main/version_num.h, man/confchpl.rst, man/confchpldoc.rst, test/compflags/bradc/printstuff/version.goodstart, test/compflags/bradc/printstuff/versionhelp.sh
Putting back 1.29.0 pre-release version removed in the PR https://github.com/chapel-lang/chapel/pull/20634.
This PR needs to be merged before we unfreeze chapel/main for future 1.29.0 developments.
=> Modifying version for chapel 1.29.0 release

doc/util/versionButton.php
This is the standard update to make the 1.28 docs the default.
=> Update version button for 1.28 release

test/studies/shootout/submitted/knucleotide3.chpl, test/studies/shootout/submitted/knucleotide4.chpl, test/studies/shootout/submitted/revcomp2.chpl, test/studies/shootout/submitted/revcomp3.chpl
I think these got updated as part of various deprecation/unstable
efforts this past release cycle.  Reverting those changes to keep
the output of `./clbg-diff.py` clean.
=> Sync 'submitted' shootouts directory with the CLBG website

compiler/dyno/tools/chpldoc/Makefile.include
The ALL_SRCS Makefile variable is used to determine which sources
should have tags and/or ebrowse information generated for them.
Traditionally, the chpldoc sources and the `chpl` sources have been
one and the same, but with the recent dyno-based rewrite of chpldoc,
this is no longer the case.  For that reason, it doesn't really make sense
to include its sources in the tags/ebrowse output for `chpl` since it's a
distinct binary / code base.  As a result, this PR removes its sources from
the ALL_SRCS variables.  If/when we want tags/ebrowse information for
chpldoc itself, we can do that as a distinct tags/ebrowse artifact (captured
in https://github.com/Cray/chapel-private/issues/3808).
This PR addresses one part of https://github.com/Cray/chapel-private/issues/3784.
=> Remove (dyno-based) chpldoc sources from `chpl`'s tags/ebrowse output

modules/standard/IO.chpl, test/deprecated/IO/localesForRegion.chpl, test/deprecated/IO/localesForRegion.good
Signed-off-by: Vivian Wang <vwang0101@gmail.com>
For [issue #20274](https://github.com/chapel-lang/chapel/issues/20274)
=> Deprecated file.localesForRegion in I/O module

compiler/dyno/test/resolution/testInteractive.cpp
This uses the output of the existing beginQueryTimingTrace/endQueryTimingTrace functions, which are also tested by testQueryTimingAndTrace. Adding the flag to testInteractive makes it easier to time incremental re-runs. Also, testInteractive has more sophisticated logic when it comes to setting up search paths for the standard library.
=> Add flag to testInteractive to time queries

doc/rst/mason-packages/guide/gitdependencies.rst
Brad pointed out that I should be using double backticks, rather than single in the title for the git docs that were recently added, so this PR makes that change (thanks for pointing this out Brad).
=> Fix "git" formatting in mason docs

compiler/AST/AggregateType.cpp, compiler/AST/wellknown.cpp, compiler/dyno/include/chpl/resolution/resolution-queries.h, compiler/dyno/lib/resolution/Resolver.cpp, compiler/dyno/lib/resolution/Resolver.h, compiler/dyno/lib/resolution/resolution-queries.cpp, compiler/dyno/lib/resolution/scope-queries.cpp, compiler/dyno/test/resolution/testFieldAccess.cpp, compiler/dyno/test/resolution/testFindDecl.cpp, compiler/include/driver.h, compiler/main/driver.cpp, compiler/parser/parser.cpp, compiler/passes/convert-uast.cpp, compiler/passes/scopeResolve.cpp, util/chpl-completion.bash
This PR includes a variety of fixes to improve the status of scope-resolution with --dyno. In particular, two new developer flags are added:
- "--[no-]dyno-scope-bundled" : enables/disables dyno scope resolution for internal, standard, and package modules
- "--[no-]dyno-scope-production" : enables/disables parts of the production compiler's scopeResolve pass
These flags can be used to more easily debug and develop convert-uast and dyno's scope-queries.
This PR adds a new scope-query: "scopeResolveAggregate". This query currently focuses on scope-resolving the fields of an aggregate type by recognizing them as declarations.
This PR includes a commit that improves scope resolution for secondary methods by improving the calculation of the receiver scope when ``scopeResolveOnly`` is ``true``, …
=> dyno: Improve scope resolution of internal/standard modules

test/release/examples/primers/fileIO.chpl
Brad pointed out that since these were computed as a set number past the start point, the count operator would also accomplish the same thing and could be naturally used in the expression.  This impacted two places in the primer.
Will verify a fresh checkout
=> Replace explicit ends of the region in the fileIO primer with the count operator

compiler/codegen/codegen.cpp
CCE 15 started complaining about the lack of `void` here,
and @bmcdonald3 and @dlongnecke-cray put this fix
together, but didn't get a chance to test it before Ben headed
home for the weekend.  The change is sufficiently innocuous
and sufficiently likely to fix the warning that I think it's
worth merging to see (and to see whether there are others
hiding behind this one).
=> Add void to chpl_program_about

compiler/dyno/include/chpl/resolution/resolution-types.h
Fixes a minor problem in a stringify function to fix a core dump I noticed when doing some tracing.
=> Fix a null dereference in a dyno stringify function

compiler/dyno/Makefile.help, compiler/dyno/doc/CMakeLists.txt, util/config/update-if-different
This PR is intended to improve the experience of doing a docs build.
* Quiets the doxygen and related "Copying..." output so that we don't get screens and screens of it
* Adjusts the doxygen rule to rebuild only if the relevant headers have changed in CMake 3.16 and newer. (Note that, since only 3.13 is required, with 3.13, we will just re-run doxygen every time).
=> Quiet doxygen output from docs build

compiler/include/astlocs.h
Added comments to clarify how these fields are used.
Reordered the fields to make the most used field first.
=> Add comments to astlocT fields and reorder them

compiler/dyno/doc/CMakeLists.txt, doc/rst/usingchapel/prereqs.rst
Require Doxygen version 1.8.17 or newer to do build the compiler library API docs. Note that, currently, `make docs` will succeed even if `doxygen` is not found. The idea is that `doxygen` is an optional dependency.
Follow-up to PR #20712.
Why 1.8.17?
* observed problems with 1.8.13 and 1.8.14
* 1.8.17 is used in Ubuntu 20.04 Focal Fossa LTS and seems to work
=> Require doxygen version 1.8.17 for C++ docs

compiler/AST/AggregateType.cpp
This PR updates the production compiler to not consider a placeholder DecoratedClassType DefExpr to be a field when checking for fields with the same name. This is now possible with ``--dyno`` which will create those DefExprs before scopeResolve. The production compiler previously did not create those DefExprs by the time we checked for fields with the same name.
Testing:
=> dyno: Fix a --dyno issue with nested classes

compiler/dyno/include/chpl/resolution/scope-types.h, compiler/dyno/lib/resolution/scope-queries.cpp, compiler/dyno/test/resolution/testScopeResolve.cpp
Fix a bug where Dyno scope resolution would continue searches transitively through non-public `use`s and `import`s.
This contains a TODO for automatic testing that private auto-`use`s, such as for `ChapelStandard`, are subject to the correct transitive visibility rules as well. This has been tested manually but is currently not feasible to automatically test; https://github.com/Cray/chapel-private/issues/3830 might change that.
Resolves https://github.com/cray/chapel-private/issues/3805.
=> Make 'use's transitively private by default in dyno

runtime/src/chpl-comm-diags.c, runtime/src/chpl-comm.c, runtime/src/chpl-gpu-diags.c, runtime/src/chplmemtrack.c
To be more correct & to resolve some warnings from the CCE compiler.
Continues PR #20714.
=> Use f(void) for no-argument functions in C

compiler/dyno/lib/util/terminal.cpp
The line reference was stale, so updated it to point to a specific commit hash instead of a branch name.
Also [saved into the internet archive](https://web.archive.org/web/20220928210459/https://github.com/google/googletest/blob/dfa67352364e00452360e1fa5d59677459712ee7/googletest/src/gtest.cc) for good measure.
=> Update a comment link to googletest code

modules/standard/OS.chpl
Add a doc comment for OS.errorCode derived from the comment for
SysBasic.syserr.
=> Add a doc comment for OS.errorCode

test/regex/ferguson/ctests/sub_test
Follow-up to PR #20738 to address testing failures in asan configurations.
=> Fix regex ctests to work in asan configurations

util/dockerfiles/Dockerfile, util/dockerfiles/entrypoint.sh
This allows us to get around issues with CI builds that overwrite the `ENTRYPOINT`, breaking our current method of dynamically setting `PATH` based on script output.
=> Enable hardcoded PATH in Dockerfile

doc/rst/meta/modules/standard.rst
Things are supposed to be alphabetized under each category.
=> Fix order of 'GPU' in TOC in Doc for Standard Modules.

test/functions/fcf/ExternBlock.chpl, test/functions/fcf/ExternBlock.skipif, test/functions/fcf/Motivators.chpl
Move FCF test using extern block into separate file that is SKIPIF'd
Usual issue of extern blocks being unsupported without LLVM.
=> Move FCF test using extern block into separate file that is SKIPIF'd

test/arrays/diten/time_iterate.c, test/arrays/lydia/time_access.c, test/statements/lydia/forVersusWhilePerf.c
To be more correct & to resolve some warnings from the CCE compiler.
Continuing PR #20739
=> Use f(void) for no-argument functions in C in tests

test/runtime/configMatters/mem/fragmentation/SKIPIF
Skip some fragmentation tests that use up to 1/2 of memory when we might be sharing nodes (basically when we're not using a launcher or using a launcher that can locally oversubscribe.)
Closes https://github.com/Cray/chapel-private/issues/3842
=> Skip some large memory tests when we might be sharing nodes

.github/workflows/build-CI-container.yml
Updates the CI container build action
- updated Dockerfile path for https://github.com/chapel-lang/chapel/pull/20705
- now builds on PRs as well
- pushing image to registry still only triggers on push to main
- build now triggers from workflow file changes as well
=> Update the Github CI container build action

modules/standard/AutoMath.chpl
More accurately represents its behavior.
Double checked a built version of the online docs
=> Fixes to the documentation of `AutoMath.round` at Damian's suggestion

compiler/dyno/lib/framework/ErrorWriter.cpp, test/chpldoc/nodoc/privateClasses.doc.bad, test/chpldoc/nodoc/privateTypeAlias.doc.bad
Attempts to compile with `-Wall -Werror` brought out issues that hadn't been
caught by my local testing or GitHub CI. In particular, `loc.path()` goes out of
scope right after the line on which its `c_str()` is retrieved, creating a dangling
pointer issue. To fix this, it's necessary to keep the `path()` in scope until the
last use of the c-string.
This PR also updates chpldoc futures to also have the new error message format.
Reviewed by @mppf and @dlongnecke-cray - thanks!
Testing:
- PR checks
=> Fix (C++) errors introduced by the "better (Chapel) error messages" PR

compiler/AST/symbol.cpp
Fix a bug with FCF codes running under `--verify`
The `Symbol::verify()` method was not considering the possibility
that `name` or `cname` could be `nullptr`. This is possible when
a formal or function is anonymous (in e.g., a function type).
Reviewed by @behharsh. Thanks!
TESTING
=> Fix a bug with FCF codes running under `--verify`

test/extern/fnPtrs/improveErrorForFcfMismatch.bad, test/extern/fnPtrs/sugarFcfTypes.bad, test/extern/fnPtrs/sugarFcfTypes.future, test/extern/fnPtrs/sugarFcfTypes.good, test/extern/fnPtrs/sugarFcfTypes2.bad, test/extern/fnPtrs/sugarFcfTypes2.future, test/extern/fnPtrs/sugarFcfTypes2.good, test/extern/rename/renameViaParamExpr.bad, test/extern/rename/renameViaParamExpr.compopts, test/functions/lambda/saveInField-nothing.bad
Adjust a bunch of .future files impacted by changes to FCFs
Remove the .compopts for a parsing related future because it was
no longer needed. Promote two futures.
=> Adjust a bunch of .future files impacted by changes to FCFs

test/classes/figueroa/BogusDestructors.chpl
This test started to fail after #20722 because the line numbers in its error message changed. This PR restores the line numbers to allow this test to pass again.
=> Fix testing error in BogusDestructors.chpl

doc/util/chpl2md.py, doc/util/chpl2rst.py, doc/util/litchapel.py, doc/util/literate_chapel.py
We've previously discussed wanting to use roughly the same infrastructure for
handling the primers and possible blog posts. However, Hugo, the static site
generator we are interested in using, does not have first-class support for
Markdown (it calls out to `rst2html`). Furthermore, it seems like the team
either prefers Markdown for authoring content, or is neutral on `rst`/`md`. It
thus seems like the best course of action is to add support for converting code
written in the style of our primers (prose in comments, code in... code) to
Markdown in addition to reStructuredText.
The "read Chapel code, treating comments as prose and code as code blocks"
functionality is very similar between what we'd need to do for Markdown and
what we currently do for reStructuredText. Thus, this PR extracts …
=> Factor out common code from `chpl2rst` to create `chpl2md`

compiler/dyno/lib/resolution/scope-queries.cpp, compiler/dyno/test/resolution/testScopeResolve.cpp, compiler/passes/ResolveScope.cpp
Fixes bugs with scope resolution of use/imports with `except` lists in Dyno:
- Search for symbols *not* named in an `except` list
- Don't bring in the module name itself from a `public use` (see https://github.com/chapel-lang/chapel/pull/19306).
- In production scope-resolver, fix gathering types with method calls defined on them in the searched scope.
Resolves https://github.com/Cray/chapel-private/issues/3814.
Testing:
=> Fix scope resolution of except lists in dyno

tools/mason/MasonBuild.chpl, tools/mason/MasonExample.chpl, tools/mason/MasonModules.chpl, tools/mason/MasonTest.chpl
This PR adds a check to make sure that we aren't in offline
mode before attempting to install dependencies from GitHub. This
means that the dependency will either already have to be in the
registry and installed at `MASON_HOME` in order to be used in
`MASON_OFFLINE` mode. This seems to have been overlooked and
should have always been the case, since we don't want to try to
access the internet when we are offline.
=> Add checking of the MASON_OFFLINE flag before attempting install

test/errhandling/ferguson/it-throws-inline.good, test/errhandling/ferguson/loopexprs-caught.good
The .suppressif files added in #20767 for it-throws-inline.chpl and loopexprs-caught.chpl were not consulted when these tests failed in baseline testing. This is probably because they lacked "straight" .good files.
This PR adds such .good files. Even though their contents should not matter, I made them symlinks to those existing .good files that contain the expected output when executing without any execopts.
Testing: tested the entire directory with and without '--baseline'.
This idea is due to @bradcray.
Not reviewed.
=> Ensure suppressif is consulted

test/mason/chplVersion/mason-chpl-version-build.chpl
In https://github.com/chapel-lang/chapel/pull/20550, the `skipUpdate` flag was added to `masonBuild` and this test slipped past getting updated. This PR updates that test to account for the new flag.
=> Fix outdated test with new flag

modules/packages/UnitTest.chpl, test/library/packages/UnitTest/AssertEqual/test_string_equality.chpl, test/library/packages/UnitTest/AssertEqual/test_string_equality.good
When checking string equality, the UnitTest code would compare the length of strings and, if they differed, would then index into the value at the length of the shorter string+1, which is 1 more than what we want when using 0-based indexing. This was causing an OOB access for strings that differed in length by 1.
Resolves: https://github.com/chapel-lang/chapel/issues/20781
=> Fix OOB error for string comparison in UnitTest assert

compiler/dyno/lib/resolution/scope-queries.cpp, compiler/dyno/test/resolution/testScopeResolve.cpp
Updates the Dyno scope-resolver to search for a name in all use/imports, not just the first one that matches, so that name conflicts between imported symbols can be detected.
Resolves https://github.com/Cray/chapel-private/issues/3903.
Testing:
=> Check conflicting imported symbol names in Dyno scope-resolver

doc/rst/usingchapel/prereqs.rst, util/chplenv/chpl_llvm.py
This PR removes a workaround for issue #19217 (which is the same issue as https://github.com/Homebrew/homebrew-core/issues/96915 and https://github.com/llvm/llvm-project/issues/54438 ).
The problem is solved in the current Homebrew LLVM 14 and LLVM 15 formulae now that libc++ is installed into a different directory than the LLVM libraries. (This problem would still be present for the LLVM 12 and 13 formulae). Since the workaround is removed, this PR adjusts printchplenv to raise an error if using Mac OS X with system LLVM 11, 12, or 13. Such LLVMs will not be selected as a quickstart configuration. Also, it updates prereqs.rst to indicate that LLVM 14 or newer is required on Mac OS X.
=> Remove workaround for Homebrew libc++ issue

test/library/packages/ProtobufProtocolSupport/endToEndRunnerUtils.chpl, test/library/standard/IO/nonUTF8/basic.chpl, test/library/standard/IO/nonUTF8/basic.compopts
Fixes some test failures caused by: https://github.com/chapel-lang/chapel/pull/20508 and https://github.com/chapel-lang/chapel/pull/20769.
- `library/packages/ProtobufProtocolSupport` tests called the chapel compiler on some other files, and needed the `writersReturnBool=false` flag included in those compilation calls. 
- `library/standard/IO/nonUTF8/` was missing the `filePathAbsolute=true` flag.
=> Minor test fixes: writeln and path deprecations

modules/standard/OS.chpl, modules/standard/SysBasic.chpl, test/deprecated/deprecated-errors.chpl, test/deprecated/deprecated-errors.good, test/deprecated/useSyserr.chpl, test/deprecated/useSyserr.good
Remove classes with all uppercase acronyms. Remove the syserr type.
Remove deprecation tests for these symbols.
=> Remove more deprecated symbols related to SysError

test/functions/vass/declaredGenericReturnTuple.bad, test/library/standard/IO/filePath/basic.prediff
Fixes a couple of test failures caused by: https://github.com/chapel-lang/chapel/pull/20769 and https://github.com/chapel-lang/chapel/pull/20508
`test/deprecated/IO/filepath.prediff` was updated to also check for the absolute `$CHPL_HOME` path in the output. This file is used by several tests.
`functions/vass/declaredGenericReturnTuple.bad` was updated to correctly reference `ch._write` instead of `ch.write`.
=> More minor test fixes: writeln and path deprecations

util/buildRelease/gen_release
=> fix gen_release after moving dyno/ to frontend/

tools/mason/MasonExample.chpl, tools/mason/MasonTest.chpl
After https://github.com/chapel-lang/chapel/pull/20508, `mason build` was throwing a couple of deprecation warnings. This PR removes them.
=> fixed some missing ch.write->ch._write's in mason source

CMakeLists.txt
Follow-up to PR #20745 to give an error if running cmake from the source directory, which would overwrite the Makefiles.
=> Add an error for running cmake from the source directory

compiler/main/configured_prefix.h
This PR fixes a `chpl` installation issue caused by removing the CONFIGURED_PREFIX
while developing a CMake build solution. The change should not have been checked
in originally.
TESTING:
=> fix(install): add CONFIGURED_PREFIX back how it was

test/library/standard/IO/filePath/basic.prediff
`library/standard/IO/filePath/basic.prediff` was causing some tests to fail on Mac systems because the `realpath` command isn't available in older versions of bash.
This PR updates the prediff script to skip a secondary absolute path check when `realpath` isn't available.
The relevant tests are now passing on Mac and Linux.
=> Make `library/standard/IO/filePath/basic.prediff` more portable

doc/rst/developer/bestPractices/Sanitizers.rst, util/cron/common-asan.bash
This fixes the address sanitizer tests, which have until now assumed that
`HOST_MEM` will default to `cstdlib` (which is the only option that works when
sanitizing). However, a recent change makes `jemalloc` default, which the tests
do not override, leading to failures. This PR should fix those failures.
=> Use HOST_MEM=cstdlib when running address sanitizer.

compiler/AST/build.cpp, compiler/include/build.h, compiler/include/parser.h, compiler/parser/parser.cpp, frontend/lib/resolution/scope-queries.cpp
This PR addresses two issues with ``--dyno`` testing that resulted in failures to find a ``use``'d module.
The first error occurred with files listed on the command line. If an earlier file referenced a module in a later file, the compiler was unable to find this under ``--dyno``. The cause of this failure was dyno attempting to parse and run convert-uast (thereby resolving ``use`` statements under ``--dyno``) one file at a time. The solution is to parse all of the files listed on the command line before running convert-uast.
The second error was that ``--dyno`` was unable to handle ``require`` statements. This PR addresses this issue by resolving ``require`` statements during the scope-resolution stage in which we also resolve ``use`` and ``import`` statements.
Testing:
=> dyno: Improve finding of modules under --dyno

compiler/llvm/clangUtil.cpp, test/studies/arkouda/sub_test, util/cron/test-cray-xc-gpu-arkouda.bash
This PR is meant to set up nightly testing for building Arkouda with `CHPL_LOCALE_MODEL=gpu`.
Why do this?
* Despite the fact that Arkouda (currently) isn't using the GPU sublocale we still attempt to gpuize eligible loops, Arkouda in an important application with many such loops, and we've already found bugs by trying to compile it in this mode.
* We have users that are attempting to use Chapel GPU support with Arkouda and they're running into issues. As we resolve issues on our end we want to lock down that they don't later "regress".
Note that this nightly test will filter out modules we currently know will not build under this mode (our intent is to remove modules from this list over time). The test will build Arkouda but doesn't perform any correctness test from there (mostly because …
=> Arkouda gpu testing

compiler/passes/convert-uast.cpp, frontend/include/chpl/resolution/scope-types.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/scope-queries.cpp
In particular, make sure that modules-used-as-variables is now an error like in
the regular `scopeResolver.cpp` pass. This PR also fixes some issues that
surface after this change (e.g., problems with converting tuple assignment with
`_` in it). The most prominent of these issues is that renaming a module to
something on import breaks looking up variables within the module.
Testing:
=> dyno: Make tweaks to import lookup to improve scope resolution

runtime/include/chpl-topo.h, runtime/src/tasks/qthreads/Makefile, runtime/src/tasks/qthreads/tasks-qthreads.c, runtime/src/topo/hwloc/topo-hwloc.c, runtime/src/topo/none/topo-none.c, third-party/qthread/Makefile
When using the `qthreads` `binders` topology module, specify the CPU bindings using the `QT_CPUBIND` environment variable. This removes all binding policy decisions from `binders`, as its default policies have problems such as incorrectly computing the number of workers per shepherd, always binding shepherds to PUs, and exiting when PUs are inaccessible. Setting `QT_CPUBIND` allows us to implement our own binding policies and avoid these problems with the default `binders` policies.
Passes all single- and multi-locale tests with the following exceptions:
- test/runtime/configMatters/comm/task-overload -- known problem on ss11
- test/studies/bale/indexgather/ig-variants -- output order is different, also fails on `main` with `hwloc` topology on ss11
No significant impact on the performance …
=> Specify CPU binding via QT_CPUBIND

test/functions/fcf/ExternBlock.suppressif
Add .suppressif for test passing FCF to extern
The test currently leaks and is not trivial to fix.
=> Add .suppressif for test passing FCF to extern

util/cron/test-cray-xc-gpu-arkouda.bash
For some reason we were previously failing our dependency checks. I think changing some of the loaded modules around will fix this.
There was also some code that was Cray CS specific in `common-native-gpu.bash` so rather than sourcing that file I've inlined the relevant portions.
=> Modifications to test-cray-xc-gpu-arkouda.bash

test/studies/arkouda/sub_test, util/cron/test-cray-xc-gpu-arkouda.bash
These are some continued modifications to ensure we have the right set of modules loaded and have sub_test register the test a success if we've built successfully and are in a mode where we're skipping other checks (which we do for the GPU build since we're skipping some modules).
This time I've qualified these changes in Jenkins by first configuring the job to run off of my Chapel repos. I got a passing run, so I'm now merging these changes in with this PR and will change the Jenkins config to run off of the nightly synced repos.
=> Continued modifications for Arkouda + GPU nightly test

compiler/AST/AggregateType.cpp, test/deprecated-keyword/handleClassInheritence.chpl, test/deprecated-keyword/handleClassInheritence.good
Inheriting from a deprecated class was not producing a deprecation warning.
Add a warning for this case and add a test that trips it.
=> Add a warning for inheriting from a deprecated class

test/functions/deitz/iterators/temps/test_iterator_temp8.future
The explanation was actually in a slightly different place than where
the future file said to find it, the deleted file:
test/types/tuple/sungeun/iteration/iteratable.future
=> test_iterator_temp8 future: capture explanation from deleted other future

frontend/lib/framework/Context.cpp
Use the LLVM Support library to check if it's the same file.
Addresses a failure with the test modules/implicit/parseTwice/main.
=> Improve a dyno assertion

modules/standard/IO.chpl, modules/standard/Regex.chpl, runtime/src/qio/regex/bundled/re2-interface.cc, test/regex/empty-channel-matches.chpl, test/regex/empty-channel-matches.good, test/regex/empty-string-matches.chpl, test/regex/empty-string-matches.good, test/regex/ferguson/readfinf.chpl, test/regex/ferguson/readfinf.good, test/regex/regex-and-channel-todos.bad, test/regex/regex-and-channel-todos.chpl, test/regex/regex-and-channel-todos.future, test/regex/regex-and-channel-todos.good
Resolves #20441
When given a regexp that matches an empty string, the iterators
`regex.matches()` supplied with an empty string and
`channel.matches()` supplied with an empty channel
now yield exactly one match.
When given such a regexp and a non-empty channel, `channel.matches()`
now mimics the behavior of `regex.matches()` on a non-empty string.
The key changes are:
* record a valid match even when `spPtr[i].data() == NULL`
in qio_regex_match()
* restore `oldPosition` in proc _channel._extractMatch()
* execute `qio_channel_advance(1 byte)` when the matched string is empty
in iter _channel.matches()
* minor cleanups "while there"
For the last point, we decided to insert this additional advance
into the iterator rather than into qio_regex_match() -- because
this advancement is needed when …
=> Fix regex.matches() and channel.matches() for empty strings

modules/standard/IO.chpl
#20801 introduced trailing spaces, which we should not have.
This change removes them.
=> Fix trailing spaces in #20801

modules/standard/SysBasic.chpl
=> Fix a typo in the SysBasic module chapeldoc

modules/standard/Time.chpl, test/deprecated/DateTimeEnumRename1.chpl, test/deprecated/DateTimeEnumRename1.good, test/deprecated/DateTimeEnumRename2.chpl, test/deprecated/DateTimeEnumRename2.good, test/deprecated/DateTimeSymbols.chpl, test/deprecated/DateTimeSymbols.good, test/library/standard/DateTime/testDatetime.chpl, test/library/standard/DateTime/testDatetimeTZ.chpl, test/library/standard/DateTime/testTime.chpl, test/library/standard/DateTime/testTimezone.chpl, test/library/standard/DateTime/testTimezoneConversions.chpl
This finishes the deprecations in issue https://github.com/chapel-lang/chapel/issues/18846. It issues compiler errors
instead of deprecation warnings for using the old DayOfWeek and ISODayOfWeek
enums.
Add tests for newly deprecated symbols.
=> Update Symbols originally from DateTime to use our preferred spellings

test/library/standard/DateTime/unstableTimezones.good
Testing a branch close to `main`, I saw failures here, and
then saw them on main as well.  Updating the .good to
avoid a failure per configuration that tests this tonight.
=> Update .good to keep unstableTimezones test working

test/library/standard/DateTime/unstableTimezones.chpl, test/library/standard/DateTime/unstableTimezones.good
Update a test to use Timezone instead of TZInfo.
=> Update a test to avoid a deprecation message for TZInfo

.github/workflows/email.yml
In main commits url is available in the request_target handle at github.event.pull_request._links.commits.href
In forked repo the commits url is directly found on the pull_request url.
=> Replace commits URL to use github.event.pull_request._links.commits.href

compiler/llvm/clangUtil.cpp, compiler/resolution/addAutoDestroyCalls.cpp, compiler/resolution/resolveFunction.cpp, doc/rst/language/spec/classes.rst, doc/rst/language/spec/conversions.rst, doc/rst/language/spec/methods.rst, doc/rst/language/spec/procedures.rst, doc/rst/language/spec/statements.rst, modules/internal/ChapelArray.chpl, modules/packages/LinearAlgebra.chpl, modules/standard/GMP.chpl, modules/standard/Regex.chpl, runtime/include/qio/bswap.h, runtime/src/tasks/fifo/tasks-fifo.c, test/gpu/native/studies/shoc/sort.chpl, test/library/draft/arrow/Arrow.chpl, test/reductions/partial/utilities.chpl, test/release/examples/primers/arrays.chpl, test/release/examples/primers/specialMethods.chpl, test/studies/shootout/meteor/kbrady/meteor-implicit-domain.chpl, test/studies/shootout/meteor/kbrady/meteor.chpl, test/types/records/ferguson/expiring-value-alias.chpl
Fix "the the" typos in
compiler: clangUtil.cpp, addAutoDestroyCalls.cpp, resolveFunction.cpp
spec: classes.rst, conversions.rst, methods.rst, procedures.rst, statements.rst
modules: ChapelArray, LinearAlgebra, GMP, Regex, 
runtime: bswap.h, tasks-fifo.c
primers: arrays, specialMethods
tests: shoc sort, partial reductions utilities.chpl, kbrady meteor shootouts,
expiring-values-alias.chpl
=> Fix "the the" typos

.github/workflows/CI.yml, .github/workflows/build-CI-container.yml
To fix the issue reported in the slack thread 
https://cray.slack.com/archives/CGSFYJN86/p1665761869247239
Upgrading checkout options from v2 to v3. 
Version v3 supports latest version node.js 16. 
v2 supports node.js version 12 which will be deprecated soon.
Issue is tracked with https://github.com/Cray/chapel-private/issues/3934
=> Fix node.js warning in workflow CI

modules/standard/FileSystem.chpl, test/deprecated/filesystem-functions.chpl, test/deprecated/filesystem-functions.good, test/functions/iterators/recursive/recursive-iter-findfilesfailure.chpl, test/library/standard/FileSystem/filerator/bradc/testboth.chpl, test/library/standard/FileSystem/filerator/bradc/walk-par.chpl, test/library/standard/FileSystem/filerator/bradc/walk.chpl, test/library/standard/FileSystem/filerator/listdir-errors.chpl, test/library/standard/FileSystem/filerator/listdir-errors.good, test/library/standard/FileSystem/lydia/getIDs/getting.chpl, test/library/standard/FileSystem/lydia/moveDir/moveEmpty.chpl, tools/mason/MasonPublish.chpl, tools/mason/MasonSearch.chpl, tools/mason/MasonUtils.chpl
Deprecate walkdirs, listdir, getUID and getGID in favor of walkDirs,
listDir, getUid, and getGid. Add a deprecation test.
Update Mason and tests to use the new names to avoid
deprecation warnings.
=> Deprecate and rename FileSystem functions to use camelCase

third-party/qthread/Makefile
This allows the runtime to control the binding of `qthread` shepherds to cores/PUs, which will facilitate future runtime improvements such as dedicated cores for active message handler threads, and running one locale per socket on multi-socket machines such as the EX.
This change should not affect performance. The runtime will pack threads to cores in the same fashion as the `hwloc` topology module.
Closes https://github.com/Cray/chapel-private/issues/3845.
=> Make binders the default qthreads topology module.

test/library/standard/FileSystem/nonUTF8/basic.chpl, test/library/standard/FileSystem/nonUTF8/basic.good
Fix some function names that were deprecated yesterday. This test didn't run in my paratest because the SKIPIF for this directory gave "True" in the filesystem where my testing ran, but "False" in /tmp where nightly runs.
=> Update a test for renamings in the FileSystem module

.github/workflows/email.yml
As part of the issue to replace heroku to send email to discourse https://github.com/Cray/chapel-private/issues/3799.
Addressing the formatting suggestions.
=> Address formatting suggestions for the commit email sent by git-actions.

compiler/resolution/functionResolution.cpp, modules/standard/ChapelIO.chpl, modules/standard/IO.chpl, test/deprecated/IO/writersReturnBool.md, test/deprecated/IO/writersReturningBool.good, test/deprecated/IO/writersReturningBoolFlagUnset/normalErrorMessage.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/normalErrorMessage.good, test/deprecated/IO/writersReturningBoolFlagUnset/userDefinedWritelnMethod.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/userDefinedWritelnMethod.good, test/deprecated/IO/writersReturningBoolFlagUnset/wrbTopWritef.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/wrbTopWritef.good, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWrite.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWrite.good, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWriteBytes.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWriteBytes.good, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWritebits.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWritebits.good, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWritef.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWritef.good, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWriteln.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWriteln.good, test/regex/empty-channel-matches.good, util/test/start_test.py
PR: https://github.com/chapel-lang/chapel/pull/20508 introduced a new config-param (`WritersReturnBool`) that allowed users to toggle between implementations of channel writer methods that do/don't return a boolean value.
It defaulted to `true`, maintaining the deprecated behavior (i.e. keep the boolean return value, and emit a warning whenever one of the relevant methods is used). This created too much noise for larger programs, and was unlikely to be helpful given that this return value is rarely used in practice.
This PR does two things to alleviate that noise:
- Switches the default value of `WritersReturnBool` to false.
- Causes the compiler to emit a specialized warning when a users code tries to use the return value from one of the affected methods: `illegal use of boolean return …
=> Reduce noise associated with `WritersReturnBool` deprecation flag

frontend/include/chpl/resolution/scope-queries.h, frontend/include/chpl/resolution/scope-types.h, frontend/lib/resolution/InitResolver.cpp, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/lib/resolution/scope-types.cpp, frontend/test/resolution/testScopeResolve.cpp
__This PR is best reviewed commit-by-commit.__
This tackled mostly one-off scope resolution issues:
- Functions (even parenless ones) have been made to not throw
"multiple declaration" errors (they _can_ be overloaded via
return intents, and they can shadow underlying fields of
the same name)
- Module identifiers found via import search are deduplicated
to prevent the same module, found multiple times, from being
reported as a conflict.
- The "checked scope set" is augmented with the name that was
used to check it. The same scope can be checked multiple times
with different names, which would lead to different results.
However, one of the seemingly one-off issues contributed some 33 tests
to the "uncategorized" group, which I have now lifted into a
"private keyword for declarations" …
=> dyno: fix more scope resolution issues

.github/workflows/email.yml
As part of the git issue to replace the email sent by heroku for PR Merge commits.
Change the email recipient to discourse commit email.
https://github.com/Cray/chapel-private/issues/3799
=> Change the email recipient to discourse commit email

frontend/include/chpl/uast/Decl.h, frontend/include/chpl/uast/IntentList.h, frontend/lib/resolution/scope-types.cpp
On newer compilers, `std::hash` is automatically defined for enum types; on
older ones, it's not. This PR explicitly specializes `std::hash` for enums used
in error messages to make sure we compile under older versions of the stdlib.
This is pretty trivial, as long as it compiles on CI and somewhere with clang,
it's probably safe to merge.
Testing:
=> dyno: fix std::hash failures under older C++ stdlibs

runtime/include/chpl-tasks.h, runtime/include/chpl-topo.h, runtime/src/comm/gasnet/comm-gasnet.c, runtime/src/comm/ofi/comm-ofi.c, runtime/src/comm/ugni/comm-ugni.c, runtime/src/tasks/fifo/tasks-fifo.c, runtime/src/tasks/qthreads/tasks-qthreads.c, runtime/src/topo/hwloc/topo-hwloc.c, runtime/src/topo/none/topo-none.c
Add opt-in support for a dedicated core for the ofi active message handler.  This functionality is enabled when:
-  `CHPL_RT_COMM_OFI_DEDICATED_AMH_CORES = true` (default: `false`)
- `CHPL_COMM = ofi`
- `CHPL_TASKS = qthreads`
- `CHPL_HWLOC != none`
- `CHPL_QTHREAD_TOPOLOGY = binders` (default: `binders`)
- The platform supports CPU binding
- The number of accessible cores > the number of active message handlers
When these conditions are met each active message handler thread is bound to its own exclusive core. The remaining cores run `qthread` shepherd threads.
This functionality is disabled by default. In the future we may change the default on some platforms and extend this functionality to other comm layers. 
While I was here, cleaned up how the bitmap is iterated through in `getCPUs` …
=> Enable dedicated cores for active message handlers

test/optimizations/widepointers/exported-fn.h
This fixes code introduced in #20861 where compiling `exported-fn.h` with gcc gave us:
```
error: function declaration isn~t a prototype [-Werror=strict-prototypes]
static void bar() {
^~~
```
Clang does not complain about this.
Testing: the affected test with C and LLVM backends under gasnet.
=> Fix exported-fn.chpl for C backend

test/library/standard/IO/readAll/readBytesArrayLeaveExcessAlone.compopts, test/regex/empty-channel-matches.good
[#20761](https://github.com/chapel-lang/chapel/pull/20761) caused a couple of test failures when it was merged with main.
This PR fixes failures on:
- `library/standard/IO/readAll/readBytesArrayInsufficientCapacity`
- `regex/empty-channel-matches`
=> Fixes to tests broken by channel.readAll implementation

runtime/src/comm/ofi/comm-ofi.c, runtime/src/topo/hwloc/topo-hwloc.c
Fix two problems with PR #20875:
-  The `hwloc` topology support flag `set_thisthread_cpubind` is the correct flag for checking whether or not the platform supports binding the current thread to a PU.
- Finding a PU within the topology should be done via  `hwloc_get_pu_obj_by_os_index`. The code was erroneously using the OS index as a logical index.
=> fix bugs in PR #20875

test/chpldoc/nodoc/privateClasses.doc.bad, test/chpldoc/nodoc/privateTypeAlias.doc.bad, test/classes/generic/domainQueryField-feature.bad, test/interop/python/defaultValues_global.bad, test/interop/python/multilocale/defaultValues_global.bad, test/visibility/private/classes/privateField.bad, test/visibility/private/classes/privateSecondaryMethod.bad, test/visibility/private/privateEnum.bad, test/visibility/private/typeAlias.bad
The Dyno-based error system does some tweaking of error message letter cases.
Specifically, it wants all brief error messages to be lowercase. I missed
updating some tests because they were futures and don't regularly run with a
paratest. This PR updates those futures. Thanks @dlongnecke-cray for pointing
these out to me.
Testing:
=> Update futures with new error message casing.

test/library/standard/IO/readAll/readBytesArrayInsufficientCapacity.compopts, test/library/standard/IO/readAll/readBytesArrayInsufficientCapacity.good
Fixing unresolved test failure for `test/library/standard/IO/readAll/readBytesArrayInsufficientCapacity` with compopts file for region bounds.
=> fixing unresolved insufficientCapacity test 

modules/standard/Types.chpl
Per discussion in #20666.  These are attached to docs-only functions, so the impact is docs-only. Since they're seen only in docs, the doc's preceding specification for e.g.
\>= returns isSubtype(b,a)
means the unstable warning can just refer to isSubtype without having to spell out the order of arguments.
Also update the methods' comments not to recommend the unstable operators.
---
Signed-off-by: Paul Cassella <gitgitgit@manetheren.bigw.org>
=> Type comparison operators are unstable, not deprecated

compiler/resolution/functionResolution.cpp, modules/standard/ChapelIO.chpl, modules/standard/IO.chpl, test/deprecated/IO/writersReturnBool.md, test/deprecated/IO/writersReturningBool.good, test/deprecated/IO/writersReturningBoolFlagUnset/normalErrorMessage.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/normalErrorMessage.good, test/deprecated/IO/writersReturningBoolFlagUnset/userDefinedWritelnMethod.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/userDefinedWritelnMethod.good, test/deprecated/IO/writersReturningBoolFlagUnset/wrbTopWritef.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/wrbTopWritef.good, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWrite.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWrite.good, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWriteBytes.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWriteBytes.good, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWritebits.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWritebits.good, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWritef.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWritef.good, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWriteln.chpl, test/deprecated/IO/writersReturningBoolFlagUnset/wrbWriteln.good, test/regex/empty-channel-matches.good, test/regex/empty-channel-matches.prediff, util/test/start_test.py
Reapplying these changes: https://github.com/chapel-lang/chapel/pull/20907
Now that this change: https://github.com/Bears-R-Us/arkouda/pull/1866 has gone in to Arkouda.
Summary of 20907:
- switches default value of `WritersReturnBool` to false to get rid of deprecation warnings
- emits a more detailed error message when a program tries to use a return value from one of the affected writer methods.
I'll be submitting another PR that gets rid of the deprecation code all together. This is a temporary measure to reduce the number of warnings.
=> Switch `WritersReturnBool` default to false

frontend/include/chpl/uast/Try.h, frontend/lib/parsing/ParserContextImpl.h, frontend/lib/uast/Try.cpp, frontend/test/parsing/testParseTryCatchThrow.cpp
To resolve problems when scope-resolving:
``` chapel
module M {
proc main() {
try {
var x: int;
} catch {
x; // do not want this to resolve to x above
}
}
}
```
This PR adjusts `Try` so that it always contains a Block or a single other expression for the body. It adds `Try::body()` to access this Block and wires the `stmt(i)` function to go in to it to preserve the old behavior.
=> Use a block for try/catch try body

compiler/optimizations/copyPropagation.cpp, compiler/resolution/cleanups.cpp, compiler/util/misc.cpp, test/extern/ferguson/mismatch-errors/mismatch-ri-iv.bad, test/extern/ferguson/mismatch-errors/mismatch-riv-iv.bad, test/functions/iterators/bradc/captureEmpty.bad, test/studies/shootout/reverse-complement/bradc/revcomp-blc-copyPropBug.bad, test/studies/shootout/reverse-complement/bradc/revcomp-dowhile-bug.bad
Based on a recent user comment, it was noted that our standard
internal error message refers to a line number, but that not all
internal errors generate line numbers.  This improves that message
to only print that part of the message in the event that a line
number was actually printed out.
While here, I also added AST nodes to some assertion errors to
add line numbers for them; however, many more potential cases
for improvement like this remain.
TODO:
=> Improve internal errors w.r.t. mentions of line numbers

doc/rst/language/spec/arrays.rst, doc/rst/language/spec/bytes.rst, doc/rst/language/spec/domains.rst, doc/rst/language/spec/index.rst, doc/rst/language/spec/ranges.rst, doc/rst/language/spec/strings.rst, doc/rst/language/spec/tuples.rst
This PR makes a few minor improvements to the `string` and `bytes` documentation pages:
* Swapped order of `string` and `bytes` lang-spec pages. (Because of the wording, the string page is sort of a prerequisite for the bytes page).
* Included some missing links to other pages
* Improved wording/grammar in a couple of places
* Made headings more consistent across composite-types pages
=> `string` and `bytes` documentation improvements

util/cron/test-cray-xc-gpu-arkouda.bash
This is a new Arkouda module (based on the HDF5 module which we also filter out for these tests).
=> Have nightly GPU+Arkouda tests filter out HDF5Msg_LEGACY

modules/internal/ChapelRange.chpl
I thought CI was catching these cases now, but in any case, removing
some whitespace that slipped through...  (might be time to resurrect
my PR adding a Makefile hook to catch these at build-time...).
=> Remove trailing whitespace

util/buildRelease/install.sh
This PR addresses an issue where `make install` doesn't copy
the new `chpldoc` and continues the process of creating
a symlink called `chpldoc` that points to `chpl`. The update 
changes the symlink name to `chpldoc-legacy` and also copies
the `chpldoc` binary to the same location as `chpl`.
TESTING:
reviewed by @riftEmber - thanks!
=> fix(install): copy chpldoc during make install

compiler/resolution/lowerIterators.cpp, test/functions/iterators/multilocale/zipMultiLocSerIter.good, test/functions/iterators/multilocale/zipMultiLocSerIter.no-local.good, test/multilocale/deitz/needMultiLocales/raCommCheck.chpl
This fixes some failures in GASNet testing due to #20891.  The
first is that there are some CHPL_COMM!=none tests that used
a zip with an unbounded leader iterator which I'd missed due to
not doing GASNet testing.
The other two were cases where the code reorganization I did
in `lowerIterators.cpp` caused us to hit a point where we
tried to dereference the `testBlock`, which was NULL due to
having hit a `USR_FATAL_CONT()` and breaking out of the
loop that would have set it up.  Here, I removed the `break;`
to set it up as before.  This had the side effect of printing more
errors for one of our tests because it invoked two iterators with
a yield within an on.  If the zip() were to only contain a single
such iterator, just a single error would be printed.  Updated the
.good files to reflect …
=> Updates for GASNet tests sensitive to #20891

.github/workflows/CI.yml
Fix for issue: https://github.com/Cray/chapel-private/issues/3993
Problem:
CI workflow failing in SmokeTest Lint with
fatal: detected dubious ownership in repository at '/__w/chapel/chapel'
To add an exception for this directory, call:
git config --global --add safe.directory /__w/chapel/chapel
Root-cause and fix:
The test script is trying to access a file structure that is not not accessible to the github.actor so the fix is to chown of the $PWD after the gitfiles are checked out.
=> Change owner to root for smokeTest lint

frontend/include/chpl/resolution/split-init.h, frontend/lib/resolution/CMakeLists.txt, frontend/lib/resolution/Makefile.include, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/VarScopeVisitor.cpp, frontend/lib/resolution/VarScopeVisitor.h, frontend/lib/resolution/split-init.cpp
Follow-up to PR #20843.
As I am looking at implementing the copy elision analysis in dyno, I'm realizing that many of the details are the same as for split init. So, in this PR, I've factored out these details into VarScopeVisitor.h / VarScopeVisitor.cpp (which are private within the library). This visitor can have subclasses for split init / copy elision / etc. It should just be updated to handle whatever these similar cases need.
This is primarily a refactor. The only behavior change that I've added intentionally is that the replacement for `computeOutFormals`, which is `computeActualFormalIntents`, is now more picky about making sure that the return intent overloads have the same types and intents.
=> dyno: factor VarScopeVisitor out of split init implementation

.github/workflows/CI.yml
Removed  chown added in this PR https://github.com/chapel-lang/chapel/pull/20965 for all the steps except for check_annotations_rt_calls.
Chown is only needed for this job because CheckTabs inside check_annotations_rt_calls is running a script(https://github.com/chapel-lang/chapel/blob/main/util/devel/lookForTabs ) that runs git commands which were failing for "Dubious owner".
Other jobs does not require this fix.
=> Followup for PR 20965

modules/dists/BlockDist.chpl
Bounded coforalls (coforalls with a known trip count) have optimized end count tracking, so when possible we want to use them. While doing some other work I noticed that #20100 unintentionally switched away from a bounded cofororall, so fix that here by adding a bounded leader.
I don't have access to the larger machine I tested #20100 on anymore, but on 256 non-homogeneous nodes of an XC I see a trivial scan go from 0.0028s to 0.0019s with this change.
=> Trigger bounded coforall optimization for broadcast in BlockDist scan

util/buildRelease/install.sh
This reverts a fix for installing `chpldoc` that exposed a shortcoming in
`chpldoc` where it doesn't do a search for possible `CHPL_HOME` values if
`CHPL_HOME` is not detected in the environment or passed using the `--home` 
option.
Once the fixes have been made for `chpldoc`, we will un-revert this revert.
This reverts commit 85c7720ea56ea8762d4b4b4718c89214427ab2b2, reversing 
changes made to 86393aed5d972fa50e737c5807a2b9471fc8fffc.
=> Revert "Merge pull request #20880 from arezaii/chpldoc-install-fix"

test/optimizations/remoteValueForwarding/gmp/nestedOn.prediff, test/performance/ferguson/CommUtil.chpl, test/performance/ferguson/remote-array-write-access.chpl
This PR fixes sporadic failures in these two tests, as suggested by @ronawho.
This should fix the sporadic failure in `performance/ferguson/remote-array-write-access.chpl` when compiled with `--cache-remote` enabled.
The failure mode, most recently observed in our `gasnet.darwin-m1` configuration, is:
```
ERROR -- TOO MANY GETs, 2 EXCEEDS MAX OF 1
```
When Locale 1 issues a cache-get of A._instance, which is a wide pointer, it is typically done with a single get_nb. However, sometimes the _instance field is split across two cache pages, so one cache-get results in two get_nb communications. This PR allows this test to accept either 1 or 2 get_nb.
We limit this adjustment to this configuration; everywhere else it will continue requiring 1 get_nb. This way we will be alerted to extra comms …
=> Fix sporadic failures in nestedOn and remote-array-write-access

modules/internal/ChapelTaskData.chpl, runtime/include/chpl-comm-diags.h, runtime/src/chpl-comm-diags.c, runtime/src/chpl-gpu-diags.c
Previously, comm diagnostics could only be disabled at a locale granularity, but there are some cases where we just want to disable comm for a specific function call for the current task. This adds a mechanism that uses task-locale-storage to temporarily disable comms for the current task and replaces the previous locale-wide disabling code.
This is motivated by some upcoming work to not track communication from end counts, but was useful for replacing an existing mechanism so I wanted to split it into a separate PR.
Note that I removed the comm diags disabling from chapel-gpu-diags since that isn't broadcasting code to enable/disable diags so I don't think it's required and we don't disable for similar broadcasting in memory diagnostics code. If we decide we should disable when …
=> Add a mechanism to disable comm diags for a specific task

test/deprecated/zipUnbounded.skipif, test/types/range/unbounded/test_indefinite1.skipif, test/types/range/unbounded/zipMismatch-case3-fast.good, test/types/range/unbounded/zipMismatch.execopts, test/users/npadmana/mpi/test_mpi.chpl
A few configurations that I did not test turned up some new failures,
addressed here:
* tests that zip unbounded ranges with bounded work differently
when compiled with `--fast`/`--no-checks` than by default
because we don't do the end-of-range check for the bounded
range, so end up spinning until timeout.  Added .skipif files to
zipUnbounded.chpl and test_indefinite.chpl for this reason
* similarly for zipMismatch.chpl, but since this test already had
a complex .execopts script to show the behavior in various
settings, it was more amenable to updating to show the change
in behavior for `--fast` test configurations
* test_mpi.chpl had a zip that was led by an unbounded range
which I missed since it's skipped in most configurations.
=> Address regressions due to zip() changes last night

test/studies/bale/indexgather/ig-variants.comm-none.good, test/studies/bale/indexgather/ig-variants.good, test/studies/bale/indexgather/ig-variants.preexec
The output order is different on various platforms so sort it to quiet testing. Workaround for Cray/chapel-private#3897
=> Sort ig-variants compiler optimizations notes

test/functions/vass/declaredGenericReturnTuple.bad, test/library/packages/ProtobufProtocolSupport/endToEndRunnerUtils.chpl
#20960, caused the following test failures:
```
[Error matching program output for library/packages/ProtobufProtocolSupport/anyRunner]
[Error matching program output for library/packages/ProtobufProtocolSupport/enumsRunner]
[Error matching program output for library/packages/ProtobufProtocolSupport/mapsRunner]
[Error matching program output for library/packages/ProtobufProtocolSupport/messagefieldRunner]
[Error matching program output for library/packages/ProtobufProtocolSupport/oneofsRunner]
[Error matching program output for library/packages/ProtobufProtocolSupport/repeatedfieldRunner]
[Error matching program output for library/packages/ProtobufProtocolSupport/typesRunner]
```
Due to the use of the `-sWritersReturnBool=false` flag in some internal calls to the chapel compiler.
This PR …
=> Correct Protobuff tests following WritersReturnBool removal

modules/minimal/internal/ChapelTaskData.chpl, test/trivial/diten/printvisibleOptFalse.good
A new exported function that's used in the runtime was added in #20973, but I missed adding a dummy stub for minimal modules. Add that here.
=> Fix minimal modules fallout from 20973

util/cron/test-cray-xc-gpu-arkouda.bash
My previous PR didn't fully fix it: https://github.com/chapel-lang/chapel/pull/20959
It looks like HDF5MultiDim is temporarily including HDF5 (which we need to filter out) so we also need to filter out HDF5MultiDim in the mean time:
https://github.com/Bears-R-Us/arkouda/blob/fc187718709a059f8e2a5353a7a1e3db15a22132/src/HDF5MultiDim.chpl#L6
I've tested things manually this time (and it resolves it). Apologies for the noise.
=> Further fix for nightly Arkouda + GPU testing (filter out HDF5MultiDim)

compiler/include/misc.h, compiler/main/checks.cpp, compiler/parser/parser.cpp, compiler/util/misc.cpp
This PR fixes a bug (explained below) encountered in the course of testing https://github.com/chapel-lang/chapel/pull/20942 for https://github.com/Cray/chapel-private/issues/3949.
I noticed that compiling `test/arrays/bradc/noelemtype.chpl` resulted in a segfault only when the `--detailed-errors` flag was used. This segfault occurred because we attempted to proceed to the resolution pass after a fatal error was encountered in parsing.
@DanilaFe and I investigated and determined the cause: when [this error-reporting code](https://github.com/chapel-lang/chapel/blob/edac77ce53ec4ef2f534c674f1bdb97fc7bc30e8/compiler/parser/parser.cpp#L890) is selected due to the presence of `--detailed-errors`, it sidesteps the production compiler's exit-on-error functionality which would otherwise be invoked …
=> Ensure exit-on-error logic also applies to Dyno errors

frontend/include/chpl/resolution/copy-elision.h, frontend/lib/framework/Context.cpp, frontend/lib/resolution/VarScopeVisitor.cpp, frontend/lib/resolution/VarScopeVisitor.h, frontend/lib/resolution/call-init-deinit.cpp, frontend/lib/resolution/copy-elision.cpp, frontend/lib/resolution/split-init.cpp, frontend/test/resolution/CMakeLists.txt, frontend/test/resolution/testCopyElision.cpp, frontend/test/resolution/testSplitInit.cpp
Continuing #20843 and #20963.
This PR implements copy elision analysis in dyno and adds a test of the same. It also improves the split init testing and the call-init-deinit logic.
Changes that need a bit more description:
* It migrates copy-elision.cpp and call-init-deinit.cpp to use the new VarScopeVisitor. To enable call-init-deinit.cpp to update resolution results, changed the VarScopeVisitor to a MutatingResolvedVisitor. But, split init and copy elision analysis don't mutate, so they cost away the const-ness to keep things simple.
* adds a call to `gdbShouldBreakHere()` to `Context::report` since it is often useful to stop compilation on an error when debugging.
* merges VarFrame returns and throws fields and updates VarScopeVisitor to update this information.
The call-init-deinit …
=> dyno: implement copy elision

test/gpu/native/studies/shoc/triadchpl.chpl
The timers in the CUDA version of SHOC triad include the time needed to transfer the A and B vectors to the GPU.
However, in our Chapeltastic version we were initializing these vectors on the GPU and avoided the memory transfer.  In order to make the comparison more fair I'm modifying our implementation of the benchmark to initialize these vectors on the CPU.
For more details see this comment: https://github.com/Cray/chapel-private/issues/3882#issuecomment-1297515792
=> Ensure we time mem transfer in SHOC Triad

frontend/test/resolution/testCopyElision.cpp
Follow-up to PR #20989. This PR fixes a warning/error from clang for a new dyno C++ test.
=> Fix an unused variable warning/error from clang in a test

compiler/llvm/clangUtil.cpp, test/extern/ExternBlockClangError.chpl, test/extern/ExternBlockClangError.compopts, test/extern/ExternBlockClangError.good
Stop tying Clang flags for extern blocks to the --cc-warnings flag
There is a large list of `-W` warning flags we pass to our internal
Clang compiler when invoking it. These flags were not previously
required and were tied to the `--cc-warnings` flag, which meant that
it was possible for non-developer compiles to skip throwing the
flags.
This PR adjusts the invocation to always add the flags. They protect
against a large class of "warnings" (that really ought to be errors)
in C code that the Chapel backend does not know how to handle.
For further justification: the `--cc-warnings` flag is intended to
suppress warnings for _generated_ C code, however C code in extern
blocks is handwritten and is consumed only by the Chapel compiler.
Since `chpl` is the only consumer, it seems fine to …
=> Stop tying Clang flags for extern blocks to the --cc-warnings flag

compiler/resolution/functionResolution.cpp, frontend/lib/immediates/num.cpp, test/param/ferguson/inf-nan-narrowing.chpl
Resolves an issue brought up in https://github.com/chapel-lang/chapel/issues/18599#issuecomment-1306002949
This PR enables param narrowing conversion from a `real` `param` storing infinity or NaN to a smaller sized `real` type. Supporting such param narrowing conversion is reasonable because all `real` types of various sizes will support infinity and NaN values. So there is no loss of precision when converting to the smaller width.
This is arguably already implied by the spec language in https://chapel-lang.org/docs/language/spec/conversions.html#implicit-compile-time-constant-conversions :
> `param` `real(s)` that is exactly representable in the target type can implicitly convert to `real(t)` or to `complex(t)` regardless of the values of `s` and `t`.
=> Fix param narrowing conversion for INFINITY and NAN

.github/workflows/email.yml
Address some of the formatting changes for this issue #3995
Moved the PR to the end and prefixed with #.
Removed extra details and left just the html link to the PR.
Removed extra details from the log message.
Removed files changed link.
=> Email Enhancements based on the feedback. Part 1.

modules/internal/ChapelBase.chpl, modules/packages/Buffers.chpl, modules/packages/Curl.chpl, modules/packages/HDFS.chpl, modules/packages/Socket.chpl, modules/standard/BigInteger.chpl, modules/standard/ChapelIO.chpl, modules/standard/FileSystem.chpl, modules/standard/IO.chpl, modules/standard/OS.chpl, modules/standard/Subprocess.chpl, modules/standard/Sys.chpl, modules/standard/SysBasic.chpl, test/compflags/ferguson/print-module-resolution.good, test/deprecated/SysBasic/chapel_specific_errors.good, test/deprecated/SysBasic/qio_err_t.good, test/io/sungeun/ioerror.chpl, test/modules/bradc/printModStuff/foo.good, test/users/ferguson/err_tmp.chpl
Resolves #3943.
This deprecates the entire SysBasic module per module review discussion. See meta issue https://github.com/Cray/chapel-private/issues/3467.
Testing:
=> Deprecate the SysBasic module

.github/workflows/email.yml
Part 2 to address https://github.com/Cray/chapel-private/issues/3995
=> Parse the email body and replace newline with <br>

test/extern/ExternBlockClangError.skipif
Skipif a test that relies on extern block support
This recently added test relies on extern block support, which
requires that CHPL_LLVM != none. Add a skipif.
=> Skipif a test that relies on extern block support

test/gpu/native/studies/shoc/triadchpl.good
I should have done this in PR #20961. That PR modified the Chapelastic triad benchmark to not initialize the 'A' and 'B' vectors of the computation in a kernel. As such I should have update the .good file to expect one less kernel launch.
=> Update triadchpl.good file

.github/workflows/email.yml
Add a single quote around the LOG env.
Issue: Unable to process file command 'env' successfully.
=> Fix- Email workflow failure to parse LOG

modules/packages/Crypto.chpl, test/library/packages/Crypto.skipif, test/library/packages/Crypto/blowfish.skipif, test/library/packages/Crypto/blowfish/bfTest1.good, test/library/packages/Crypto/blowfish/bfTest2.good, test/studies/dedup/dedup-extern.skipif, test/studies/dedup/dedup-externblock.skipif
* Improves skipifs for tests using openssl to skip if libcrypto isn't installed and to work with openssl version 1.1.1k
* Adjusts CryptoBuffer.init(string) to work correctly with Unicode and added a bytes version
* Deprecated Blowfish support in Crypto because
* it does not work as written in OpenSSL 3
* Blowfish is considered legacy in OpenSSL 3
`start_test test/studies/dedup/dedup-extern.chpl  test/studies/dedup/dedup-externblock.chpl  test/library/packages/Crypto --respect-skipifs` passes:
=> Improve openssl skipifs and adjust Crypto package module

.github/workflows/email.yml
To address one of the comments in the issue https://github.com/Cray/chapel-private/issues/3995 to preserve the newline a change was merged, but the email client does not honor the <br> tags added.
Putting back the log in the email body while we figure out how to send multi line git actions ENV to an email body.
=>  Add the Log message back in the email body.

tools/mason/MasonUtils.chpl
There are some mason tests that are currently sensitive to stderr, so in this PR we are piping the stderr and then not displaying when quiet=true for the `runCommand` procedure, which should make the tests no longer fail from git warnings.
=> Hide stderr for Mason's `runCommand`

test/gpu/native/studies/shoc/triadchpl.gpu-keys
Like #21009.  This is another change I should have made for #20961
Again, the number of kernel launches changed for this test so it's necessary to update all the output files (guess I'm learning this the hard way).
Anyway I previously updated the .good file but for performance tests there's also a .gpu-keys file that needs to be updated. This PR updates the corresponding .gpu-keys file.
=> Update triadchpl gpu-keys (changed num kernels)

modules/packages/Socket.chpl, test/library/packages/Socket.skipif, test/library/packages/Socket/ipv6/connect_timeout_ipv6.chpl, test/library/packages/Socket/ipv6/udpio_ipv6.chpl
Similar to PR #21013.
This PR:
* Fixes some compilation failures from the Socket module and tests
* Adjust the skipif to better handle libevent missing entirely
`CHPL_TARGET_PLATFORM=linux64 CHPL_TARGET_COMPILER=gnu start_test test/library/packages/Socket` works in several configurations:
=> Fix problems with Socket module and adjust skipifs

modules/dists/BlockDist.chpl, modules/internal/DefaultRectangular.chpl
Fixes a test failure after PR #20755 with
optimizations/arraySwap/edgeCases
Adjusts doiOptimizedSwap `where debugOptimizedSwap` to use `pragma "last resort"`. Otherwise, this generic function will be preferred to the other overload.
=> Adjust debug support in doiOptimizedSwap

test/library/packages/ZMQ.skipif, test/library/packages/ZMQ/COMPOPTS, test/library/packages/ZMQ/getLastEndpointMain.preexec, test/library/packages/ZMQ/interop-py/COMPOPTS, test/library/packages/ZMQ/multilocale/COMPOPTS, test/library/packages/ZMQ/version.prediff
Previously, the ZMQ package tests required a system install of libzmq to work. Our skipif would look for a libzmq library and if it was found assume that a zmq.h header would be found too. However, this isn't always the case and we have systems that have the libzmq library but not the headers, which caused the tests to run and then fail. To improve this, use pkg-config to check if zmq is installed and to get appropriate compilation cflags/libs.
We've run into the zmq library only issue before and added a workaround in #20191 that let us manually skip the tests, but this makes that check automatic, at least for the package tests. We'll want to do something similar for the multi-locale interop tests at some point too, but I think that will require updating the compiler or makefile makefile …
=> Use pkg-config for zmq package tests

.github/workflows/email.yml
Email body was not honoring linefeeds.
Parse the merge log replace line feeds with '<br>' .
In the merge message quoted in the mail, newlines/paragraphs seem to be lost. For example, compare the OP in this PR https://github.com/chapel-lang/chapel/pull/20891 with its merge mail message here: [https://chapel.discourse.group/t/chapel-merge-20891-make-zippered-for-loops-more-like-pa[…]-zippered-loops-by-having-the-first-expression-lead/17148](https://chapel.discourse.group/t/chapel-merge-20891-make-zippered-for-loops-more-like-parallel-zippered-loops-by-having-the-first-expression-lead/17148) I think it’s important to preserve these linefeeds in the mail for readability.
=>  Parse the commit log. Replace line feeds with <br>

.github/workflows/email.yml
Revert the log-parser changes.
Due to the challenges with testing the email workflow that is triggered only when a PR is merged, Changes merged after testing from a git-workflow triggered from a fork(on a push request).
In production the parsing is not working as expected so reverting back.
=>  revert- Parse the commit log. Replace line feeds with <br>

test/compflags/link/sungeun/static_dynamic.skipif
Currently, the `--static` compiler flags maps to a backend flag like `-static`, which tries to create a fully static executable. This is support by fewer and fewer distributions anymore since they don't ship static versions of libraries we need like pthreads. We could probably stand to revisit what `--static` means or whether we want to continue to have the flag, but for now I just want to prevent the test from failing on systems that lack static versions of libraries we need.
Part of Cray/chapel-private#4011
=> Skip `--static` test if libpthread.a isn't found

modules/internal/ChapelArray.chpl, test/classes/ferguson/check-init-array-classes-nil.chpl
Follow-up to PR #20755.
This PR adds `pragma "last resort"` to the generic `chpl__coerceMove` to get this code pattern working:
var x:[1..10] unmanaged C? = nil
The `pragma "last resort"` was already present on the corresponding `chpl__coerceCopy`.
This resolves a problem building `prep` from CHAMPS.
This PR also adds a small test showing the pattern that was failing to compile.
=> Add last resort to generic chpl__coerceMove

test/library/packages/ZMQ/COMPOPTS, test/library/packages/ZMQ/getLastEndpointMain.preexec
In #21026, we started getting ZMQ include/lib paths from pkg-config, but they were being passed directly to the chpl compiler. This was under the assumption that we'd only get `-I`/`-L`/`-l` args, which our compiler supports, but there can also be some variants that we don't support (like `-isystem`). Fix that here by passing pkg-config flags to `--ccflags`/`--ldflags` instead.
=> Fix how we get ZMQ flags from pkg-config

modules/internal/ChapelArray.chpl
When creating distributed rectangular domains, directly create the final distributed domain instead of creating an empty domain and assigning the local domain into it. This eliminates a distributed domain assignment and re-privatization, which gets rid of 3 coforall+ons resulting in some domain creation speedups.
Here's the performance results for creating a block distributed domain on 16 nodes of a CS and XC:
```
./distCreate --size=arraySize.tiny --dist=distType.block -nl 16
```
16-node-cs-hdr
| config | domInit  |
| ------ | -------: |
| before | 0.00464s |
| after  | 0.00288s |
16-node-xc:
| config | domInit  |
| ------ | -------: |
| before | 0.00055s |
| after  | 0.00027s |
Part of #20197
=> Optimize distributed rectangular domain creation

util/test/sub_test.py
Previously, all runs of the same test (caused by having multiple compiler and/or execution options) would use the same execution environment, generated from the `EXECENV` and `.execenv` files prior to the first test run. This made it impossible for each test run to use a different environment. With this change, the `EXECENV` and `.execenv` files are read on each run, and both are passed the compiler options and execution options as arguments, allowing them to specialize the environment for the test run.
Passes all single- and multi-locale tests.
=> Allow per test-run customized environments

modules/packages/BLAS.chpl
Documentation fix addressing #20736. Fixes links by updating to new MKL BLAS links.
I reordered link definitions in terms of BLAS 1 -> BLAS 2 -> BLAS 3, but this is an internal thing so it shouldn't cause any issues as far as I know.
Perhaps the only discussion point per the issue thread is whether we'd prefer to use Netlib's slightly less attractive and more detailed (perhaps a bad thing here?) docs to favor open source.
Resolves #20736
=> Update BLAS documentation links

modules/standard/FileSystem.chpl, test/deprecated/fileSystemFindFiles.chpl, test/deprecated/fileSystemFindFiles.good, test/exercises/duplicates/duplicates-alt-assoc-reduce.chpl, test/exercises/duplicates/duplicates-alt-assoc.chpl, test/exercises/duplicates/duplicates-bonus-b2-record.chpl, test/exercises/duplicates/duplicates-bonus-b3-size.chpl, test/exercises/duplicates/duplicates-step1-for.chpl, test/exercises/duplicates/duplicates-step2-forall.chpl, test/exercises/duplicates/duplicates-step3-error.chpl, test/exercises/duplicates/forStudents/duplicates.chpl, test/library/standard/FileSystem/filerator/bradc/findfiles-par.chpl, test/library/standard/FileSystem/filerator/bradc/findfiles.chpl, test/parallel/forall/vass/reciter/forall-reciter-alt.chpl, test/parallel/forall/vass/reciter/outbound-ibb-goto.chpl, test/patterns/cltools/grep/grep.chpl, test/studies/dedup/dedup-distributed-ints.chpl, test/studies/dedup/dedup-distributed-strings.chpl, test/studies/dedup/dedup-extern.chpl, test/studies/dedup/dedup-local.chpl, test/studies/dedup/dedup-spawn-sort.chpl, test/studies/labelprop/labelprop-tweets.chpl, test/studies/mstrout/wordCount.chpl, tools/mason/MasonExample.chpl, tools/mason/MasonTest.chpl
Deprecate the all lowercase version in favor of the camelCase version. Add
a deprecation test.
Did not add a deprecation warning to the standalone parallel version because
it causes multiple messages for a single forall loop. Instead rely on the
single warning for the serial version.
=> Deprecate 'findfiles' in favor of 'findFiles'

modules/packages/HDF5.chpl, test/functions/iterators/thomasvandoren/ParallelOnly.chpl, test/library/packages/Curl/check-http.chpl, test/library/packages/Curl/download-http-upload-ftp.chpl, test/library/packages/Curl/upload-ftp.chpl, test/studies/dedup/dedup-externblock.chpl
These tests don't run in a standard linux64 paratest so I missed them in the first PR that deprecated 'findfiles'. Nightly testing caught them, so update them now.
=> Update more tests for 'findfiles' deprecation

compiler/passes/convert-uast.cpp, compiler/passes/scopeResolve.cpp, frontend/include/chpl/uast/Interface.h, frontend/lib/parsing/ParserContextImpl.h, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/uast/Builder.cpp, frontend/test/parsing/testParseInterface.cpp
This PR addresses some of the `--dyno` failures related to scope resolution. In
particular:
- __`scopeResolve.cpp` didn't know what to do with resolved interfaces.__. This
issue came up when interface names were used for defining secondary methods,
like `proc MyInterface.foo`. Whereas the old compiler leaves `MyInterface`
unresolved, Dyno already determines that `MyInterface` is an
`InterfaceSymbol`. The code in `scopeResolve` assumed that the only time a
receiver is defined is when it was a record, causing issues. This PR modifies
code in `scopeResolve.cpp` to properly handle the receiver being a `SymExpr`
pointing to an interface.
- __Interface formals weren't considered declarations.__. This was because the
interface formals were represented by `Identifier`s, and thus skipped when …
=> Fix up dyno scope resolution for  constrained generics

modules/standard/GPU.chpl, runtime/include/chpl-gpu.h, runtime/include/gpu/cuda/chpl-gpu-gen-includes.h, runtime/src/gpu/cuda/gpu-cuda.c, test/gpu/native/measureGpuCycles.chpl, test/gpu/native/measureGpuCycles.good
This function can be used to measure performance from within a GPU kernel.  The function returns the number of clock cycles on a SM that have occurred since kernel launch.
The PR also adds `gpuClocksPerSec` and `gpuPrintTimeDelta`. The clocks per second function can currently only be called by the host and the print delta function exists so that (in the absence of getting `writeln` to work) we can output this data from the kernel.
Due to these usability issues I have these functions no doc'd for the time being.
=> Add gpuClock() function to GPU module

test/compflags/bradc/gdbddash/declint-lldb.skipif, test/compflags/bradc/gdbddash/declint.skipif, test/execflags/bradc/gdbddash/SKIPIF, test/execflags/lldbddash/SKIPIF
Instead of hard coding what platforms have gdb/lldb, just check for the executables directly. This should make the tests more portable in general and avoids running the gdb tests on systems without gdb.
Part of Cray/chapel-private#4011
=> Update tests that require gdb to check for the executable

util/test/paratest.chapcs
Instead of hard cording to 'chapel', enable overriding with `CHPL_TEST_PARTITION` to enable using on other systems.
Part of Cray/chapel-private#4011
=> Make paratest.chapcs partition overridable

compiler/passes/convert-uast.cpp
Sometimes, a `UniqueString` struct contains the `c_str()` it represents (small
string optimization), which means it needs to stay in scope for the `c_str()`
to remain valid. This temporary goes out of scope right away, so the `c_str()`
may be invalid.
Testing:
=> Fix dangling reference bug.

test/ANNOTATIONS.yaml
- distributed array creation speedups
- 16-node-xc regression from hardware changes
- compiler speedup from using host-mem=jemalloc
=> Add perf annotations for 2022-11-17

runtime/src/tasks/qthreads/Makefile, runtime/src/tasks/qthreads/tasks-qthreads.c, runtime/src/topo/hwloc/Makefile, runtime/src/topo/hwloc/topo-hwloc.c
Add `CHPL_TOPO_DEBUG` and `CHPL_TASKS_DEBUG` that turn on debug messages for the `topo` and `tasks` runtime layers, respectively. In addition, `DEBUG_NODEID` controls whether or not the node ID is printed as a prefix to the debug messages.
=> Add debug flags for topo and tasks layers

make/compiler/Makefile.intel
Add a disable warning flag to disable Intel compiler compatibility warning message.
The warning is seen on this test run.
https://chapel-ci.us.cray.com/job/cray-module-performance-cray-xc-single-locale/CHPL_LAUNCHER=slurm-srun,COMMUNICATION=none,COMPILER=intel,LOCALE_MODEL=flat,label_exp=horizon/744/console
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
=> Add the disable flag to disable warning. 

.github/workflows/email.yml
Special chars like @#, etc in the git description were evaluated.
Replacing  "double quotes"  around the git env with 'single quotes'.
=> Fix an issue in log parsing where the special chars are evaluated in the merge log/

.github/workflows/email.yml
Git actions not parsing the logs if special chars are present.
Test if the Log is parsed if the log has #@, "" ''.
=> Fix an issue where the special chars are evaluated in the merge log

compiler/AST/AstDump.cpp, compiler/AST/AstDumpToNode.cpp, compiler/AST/AstToText.cpp, compiler/AST/view.cpp, compiler/codegen/cg-expr.cpp, compiler/codegen/codegen.cpp, compiler/include/version.h, compiler/llvm/clangUtil.cpp, compiler/llvm/llvmDebug.cpp, compiler/main/PhaseTracker.cpp, compiler/main/driver.cpp, compiler/main/version.cpp, compiler/passes/ResolveScope.cpp, compiler/passes/addInitGuards.cpp, compiler/passes/convert-uast.cpp, compiler/resolution/generics.cpp, compiler/resolution/interfaceResolution.cpp, compiler/resolution/preFold.cpp, compiler/util/misc.cpp, compiler/util/stringutil.cpp, test/compflags/link/deitz/dir/link2.c, test/compflags/link/deitz/link1.c, test/library/standard/Memory/Diagnostics/countMemory/countMemory.makegood, test/studies/compOcean/compOcean.h, test/studies/nqueens/nqueens-c++.cpp, test/studies/uts/brg_sha1.c
Change all remaining instances of `sprintf`->`snprintf` due to `sprintf` deprecation (and general unsafety). Instances in the runtime have already been changed by https://github.com/chapel-lang/chapel/pull/21021. Instances in third-party code are left untouched as we don't own them.
Resolves https://github.com/Cray/chapel-private/issues/3999.
Testing:
=> Change remaining sprintf calls to snprintf

modules/standard/IO.chpl
The new `fileReader.readBinary` overloads added by #20988 were failing in a 32-bit setting.
This PR fixes those failures.
=> addressing 32-bit test failure for readBinary(string/bytes)

util/cron/common-arkouda.bash
Codec support is being added in Arkouda and the dependencies have been installed on the testing machines and this PR adds that to the Arkouda bash script to allow finding of the iconv and idn2 libraries.
Closes: https://github.com/Cray/chapel-private/issues/4015
=> Add iconv and idn2 Arkouda deps to Arkouda script

compiler/AST/astutil.cpp, test/functions/vass/override-def-use.chpl, test/functions/vass/override-def-use.good
Resolves #21073
This fixes a bug where an actual argument was always considered a "use" upon a call to a virtually-dispatched method even when the corresponding formal had a ref or [in]out intent.
The bug was observed when such an actual argument was an array indexing expression, which involved return intent overloading. Because of the bug, the return-value overload was chosen instead of the return-ref one.
Next steps: check if this bug can occur upon calls to ftable-ed functions.
Testing: standard paratest; gasnet paratest over multilocale tests.
=> Account for ref+out intents with virtual methods

modules/standard/Version.chpl, test/library/standard/Version/compareVersionTypes.chpl, test/library/standard/Version/compareVersionTypes.good, test/library/standard/Version/versionCastIsParam.chpl, test/library/standard/Version/versionCastIsParam.good
This PR reinstates the `createVersion` function and creates a type alias
for `sourceVersion` and marks both as deprecated. 
Both of these items were dropped without deprecation in PR #19300 and this
PR corrects that mistake. 
TESTING:
reviewed by @riftEmber - thanks!
=> reinstate and deprecate createVersion

.github/workflows/email.yml
For better readability preserve the number of newlines by fixing the sed command in the log parsing.
This addresses [Git Email Workflow Enhancements #3995](https://github.com/Cray/chapel-private/issues/3995)
=> Fix formatting in email body.  Multiple newlines are squashed to a single new line. 

.github/workflows/email.yml
Discourse client html formatting does not treat double br as paragraph. This is to update the parsing to use the <p> tag instead of double br.
=>  Followup for 21094.

compiler/passes/parallel.cpp
In makeHeapAllocations() we walk all defs and make certain transformations for
them. Treat virtual method calls the same as regular function calls when doing
these transformations. This fixes a regression in
test/optimizations/copyPropagation/cp-problem2.chpl with --no-local from
#21080.
=> Fix a bug involving virtual method calls with ref arguments

modules/internal/ChapelBase.chpl, modules/standard/Regex.chpl, test/deprecated/regexTertiary.good, test/regex/bytes/cast.chpl, test/regex/bytes/cast.good
This PR marks casts from strings or bytes to regex as deprecated and 
suggests using `compile()` from `Regex` module as a replacement until 
throwing initializers are implemented and we can suggest `new regex()`.
Updates some test `.good` files to expect the deprecation message.
TESTING:
reviewd by @jeremiah-corrado - thanks!
=> chore: add deprecation warnings when casting string/bytes to regex

modules/standard/IO.chpl, test/unstable/iostyle/iostringformat.chpl, test/unstable/iostyle/iostringformat.good, test/unstable/iostyle/iostringstyle.chpl, test/unstable/iostyle/iostringstyle.good
Mark `iostringstyle` and `iostringformat` from `IO` as unstable. Internal copies of each are introduced to be used in the interim before full-featured replacements for `iostyle` are complete.
Resolves https://github.com/chapel-lang/chapel/issues/19756.
Testing:
=> Mark iostringstyle and iostringformat as unstable

modules/standard/IO.chpl, test/deprecated/IO/unicodeSupported.chpl, test/deprecated/IO/unicodeSupported.good, test/io/ferguson/writefstring.chpl, test/release/examples/primers/fileIO.chpl, test/unicode/write_read_euro.chpl
Deprecate `IO.unicodeSupported`, which always returns `true`.
Resolves https://github.com/chapel-lang/chapel/issues/20275.
Testing:
=> Deprecate IO.unicodeSupported

make/compiler/Makefile.gnu, make/platform/Makefile.linux32
Gmake 4.4 now supports exporting exported variables to `$(shell ...)` commands. This caused issues for variables like `GNU_GCC_MAJOR_VERSION` that we were lazily setting and recursively using through subsequent shell invocations. Fix that here by using immediate set to avoid lazy evaluation.
Without this, we got screens full of messages like:
```
/bin/sh: line 0: test: -lt: unary operator expected
/bin/sh: line 0: test: -eq: unary operator expected
```
and could add the wrong or not enough CFLAGS for gcc because `GNU_GCC_MAJOR_VERSION` and friends weren't set when trying to do version checks like `$(shell test $(GNU_GCC_MAJOR_VERSION) -lt 4)`.
From https://lists.gnu.org/archive/html/info-gnu/2022-10/msg00008.html (gmake 4.4 release notes):
```
* WARNING: Backward-incompatibility! …
```
=> Fix support for gmake 4.4

modules/packages/CopyAggregation.chpl
When flushing, previously all aggregators would flush to locale 0, then 1 and so on in psdueo lockstep. This created a many-to-one bottleneck, especially at scale. This updates aggregators to start flushing to the locale they last aggregated a value for. Keeping track of the last locale is trivially fast and getting rid of the lockstep comm behavior improves performance, particularly at scale.
This change was made to Arkouda's aggregators in Bears-R-Us/arkouda#1826 and this PR effectively pulls in an "upstream" change. Eventually we just want Arkouda to use Chapel's aggregators, but there have been frequent enough changes to aggregators that it's been hard to time.
=> Avoid flushing aggregators in lockstep

compiler/codegen/cg-symbol.cpp, compiler/include/files.h, compiler/include/symbol.h, compiler/llvm/clangUtil.cpp, compiler/util/files.cpp, test/compflags/ferguson/print-asm.chpl, test/compflags/ferguson/print-asm.compopts, test/compflags/ferguson/print-asm.good, test/compflags/ferguson/print-asm.prediff, test/compflags/ferguson/print-asm.skipif
Resolves #15043
This adds 'asm' as a stage for 'llvm-print-ir' so that it can be displayed with, for example:
```
chpl bb.chpl --fast  --llvm-print-ir foo,bar --llvm-print-ir-stage asm
```
At present, this functionality only works with the LLVM backend.
This functionality works by running an `llvm-objdump` command, e.g. `llvm-objdump --disassemble-symbols=foo_chpl tmp/chpl__module.o`. It will fail if `llvm-objdump` is not installed along with the `clang` we are working with.
New test passes:
=> Add support for displaying resulting assembly

test/deprecated/testFile.txt
This was used when deprecating the `out error` pattern 5 years ago and
accidentally got left behind when those tests were cleaned up.  Remove
it now to reduce clutter
I'm planning on running a full paratest to make sure this doesn't cause
problems for any other tests, just in case.  Not planning on asking for a
review, but have let the team know I'm doing this so folks can object if
they feel so moved.
=> Remove this file, which was used by tests that have now been removed

.github/workflows/email.yml
This will address
https://github.com/Cray/chapel-private/issues/3995
=> Workaround tj actions limitations with using newline as separator.

modules/internal/SharedObject.chpl, test/classes/weakPointers/concurrentUpgrades.good, test/classes/weakPointers/initWeakPtr.good, test/classes/weakPointers/passiveCache.good
This PR makes it more clear that the `weakPointer` type is experimental.
- Adds an extra warning to the top of the `weakPointer` docs page
- Re-words the unstable warning on `shared.downgrade` to make it clear that the method itself is unstable, not just the `weakPointer` type
- Makes some minor working improvements
=> Documentation improvements for `weakPointer`

modules/standard/IO.chpl, test/library/standard/IO/writeOutOfRange.chpl, test/library/standard/IO/writeOutOfRange.cleanfiles, test/library/standard/IO/writeOutOfRange.compopts, test/library/standard/IO/writeOutOfRange.good
Adds the following line to the documentation for `channel.write` and `channel.writeln`:
```
EofError – Thrown if EOF is reached before all the arguments could be written.
```
This clarifies which error type would be used to catch an EOF for a write[ln] call on a finite sized channel.
Also adds a test to ensure that the docs match the actual behavior.
=> Document EofError case for channel.write[ln]

modules/standard/GPU.chpl, modules/standard/GPUDiagnostics.chpl
Produce a warning message when using the `GPU` and/or `GPUDiagnostics` module with `--warn-unstable`.
I give a more detailed message on the doc. I've manually verified that the message on the `@unstable` keyword doesn't conflict with the warning on the doc.
=> Mark GPU and GPUDiagnostic modules unstable

modules/internal/ChapelBase.chpl, test/deprecated/modOnReal.chpl, test/deprecated/modOnReal.compopts, test/deprecated/modOnReal.good, test/deprecated/modOnReal.noexec
It looks like I added this `%=` overload on reals in commit
433d9c5558 without rationale, which makes me think it
was a mistake, particularly since (a) we don't support a `%`
on reals, and (b) it doesn't seem to work (with the C back-end,
at least).  As a result, I'm deprecating it.
Issues #19255 and #6205 propose implementing these
operators in terms of `fmod()` on reals, and I don't have
any objection to proceeding with that plan, but am only trying
to remove a place where it feels like we're exposed for now.
I think that, arguably, since the feature doesn't work, we could
remove it without deprecation, but given that Arkouda was
briefly relying on it (compiling at least) in 1.28, I felt a little
nervous just pulling it without warning.  And maybe by
deprecating it, I'll be more …
=> Deprecate support for %= on reals for now

doc/rst/usingchapel/prereqs.rst
This PR updates prereqs.rst with the automatically generated commands to install prerequisites based upon the updates to portability testing from PR #21128.
Further notes:
* We can test for Fedora 37 but I removed the generated Fedora 37 docs since I couldn't figure out the command to install clang 14 on that platform (I think something is missing).
* Fedora 31, 32, 33, and Ubuntu 21.10 are removed because they have reached end-of-life.
* CentOS Stream 9 commands are now present since I was able to add testing for it.
* Ubuntu 22.10 now defaults to LLVM 15 which we don't support yet, so it has a separate section to install LLVM 14.
=> Update prereqs install commands

frontend/lib/resolution/resolution-queries.cpp
This is an almost-trivial change. This unused variable is something that our testing infra didn't catch, but leads to compiler warnings (and therefore errors) in others' builds. 
=> Remove unused variable from resolution-queries.cpp

test/library/standard/IO/open/checkPermissions.suppressif, test/library/standard/IO/openreader/checkPermissions.suppressif, test/library/standard/IO/openwriter/checkPermissions.suppressif
These tests pass when run by hand with Cygwin testing but fail when run through our testing harness.
I copied this suppressif from test/library/standard/FileSystem/chmod/chmod_noprivilege.suppressif
=> Suppress the open* test failures when run as a windows service

doc/rst/language/spec/expressions.rst
Follow-up to PR #20805.
Updates the spec to indicate than unary `-` applied to a `uint` of any width will result in a compilation error.
=> Update spec about unary negation of uints

compiler/main/PhaseTracker.cpp, test/performance/compiler/elliot/passCheck.prediff
This PR is in service of the "coarse performance graphs" work. In brief, every
time a pass is added, renamed, moved, or deleted, our compiler performance data
has to be updated. This effort is manual, so pass changes basically require
additional manual intervention. Instead, we'd rather broadly group passes into
three categories: front-end, middle-end, and back-end. The compiler can report
timing totals for each pass category, and the performance graphs can just plot
these groups. Passes within groups can then be re-ordered, renamed, added,
etc., without requiring any additional work.
This PR in particular adds output for pass groups to the production compiler's
`--print-passes` flag.
Reviewed by @mppf and @ronawho - thanks!
=> Add pass group (front-end, back-end, middle-end) output to `--print-passes`

modules/standard/IO.chpl
`test/library/standard/IO/writeBinary/write_c_void_ptr` was failing to compile on 32-bit systems due to a missing cast to `c_ssize_t` in `writeBinary(ptr: c_void_ptr)`.
This PR fixes that failure.
=> Fix 32-bit failure for `writeBinary(c_void_ptr)`

modules/internal/ChapelGpuSupport.chpl, modules/internal/ChapelStandard.chpl, runtime/include/chpl-gpu.h, runtime/src/chpl-gpu.c, test/gpu/native/promotion.execopts, test/gpu/native/varInInnerBlock.execopts
Prior to this PR, to get verbose debug output for GPUs you would pass `--verbose` to a chapel program.  `--verbose` is used in other contexts and it seems like it would be better if this was separated out.
This PR introduces a new config constant `debugGpu` that can be used for this.
So instead of invoking a program like:
`./foo --verbose`
You would do:
`./foo -sdebugGpu=true`
To get the same verbose GPU debugging output.
The bulk of this PR is from work Engin did but didn't get around to committing before:
https://github.com/chapel-lang/chapel/compare/main...e-kayrakli:chapel:gpu-verbose-v2
=> Remove use of --verbose for gpu debugging

test/library/standard/IO/open/checkPermissions.chpl, test/library/standard/IO/openwriter/checkPermissions.chpl
#21130 deprecated FileSystem.chmod().
This PR switches two tests from this chmod
to its replacement in OS.POSIX, to avoid .good mismatches.
The two chmod overloads have different types of formals.
Both overloads are visible in these tests.
The switch is achieved by adjusting the types of the actuals.
=> Avoid calling the deprecated chmod()

test/compflags/ferguson/print-module-resolution.good, test/execflags/configs/privateconfigs-help-set.comm-none.good, test/execflags/configs/privateconfigs-help.comm-none.good, test/execflags/ferguson/help2.good, test/execflags/shannon/configs/help/basehelp.txt, test/execflags/shannon/help.good, test/modules/sungeun/init/printModuleInitOrder.good
The introduction of the gpuDebug config const (and ChapelGpuSupport module) has broken some tests. I've regolded as needed.
=> Fix broken tests (gpuDebug config const)

test/execflags/configs/privateconfigs-help-set.good, test/execflags/configs/privateconfigs-help.good
This is a continuation of https://github.com/chapel-lang/chapel/pull/21143 (fix broken debugGpu tests) for tests that are not `COMM=none` specific.
=> Continued test updates for debugGpu config const

modules/standard/FileSystem.chpl, test/library/packages/HDF5/HDF5Preprocessors.chpl, test/library/standard/FileSystem/nonUTF8/basic.chpl
I added a local version of 'copyMode' that uses local versions of 'getMode' and 'chmod' to the FileSystem.copy function. It would be nice to make 'copy' work with only the OS.POSIX functions, but in at least one case it isn't currently working that way.
Updated tests to work with FileSystem permissions functions deprecated.
=> Fix some tests that broke due to the FileSystem permissions deprecation

doc/rst/language/spec/variables.rst
Fixes some issues with the spec section on split init that I noticed while looking at it while developing PR #20843.
* promotes the Split Initialization section and subsequent sections up a level in the outline so that they appear on the left
* adds a link from the Variable Lifetimes section back to Split Initialization
* clarifies one of the split init rules which was not clear about type inference for variables with a generic declared type
=> Fixups to spec split init details

highlight/tmbundle/README.md
Github Lightshow appears to now be deprecated or paid-only, so replace the instructions involving it with ones that worked this time around.
While here, also mentioned that you need to merge a PR with the changes, since the old instructions could be construed to imply that merely making the changes on your local copy was sufficient.
=> Update the tmbundle update instructions for testing highlight changes.

doc/rst/language/spec/procedures.rst
Follow-up to PR #20755. Since the genericity of formals is now only considered if they are the same instantiated type, add that to the spec.
=> spec: clarify less-generic rule applies with same type

compiler/main/version_num.h, doc/rst/conf.py, doc/rst/language/archivedSpecs.rst, doc/rst/usingchapel/QUICKSTART.rst, doc/rst/usingchapel/chplenv.rst, man/confchpl.rst, man/confchpldoc.rst, test/compflags/bradc/printstuff/versionhelp.sh
As part of 1.29 release check list,  remove pre-release tags and update the current chapel version(1.29)
https://github.com/Cray/chapel-private/issues/4055
=> 1.29 Release : Remove pre-release tags

modules/standard/BigInteger.chpl
Resolves #17687
Should not impact the behavior of these operators, but will test regardless.
Covers:
- unary `+`
- unary `-`
- `~`
- `+` between bigints, uints, ints
- `-` between bigints, ints, uints
- `*` between bigints, ints, uints
- `**` between bigints, ints, uints
- `%` between bigints, ints, uints
- `<<` between bigints, ints, uints
- `>>` between bigints, ints, uints
- `&` between bigints
- `^` between bigints
- `==` between bigints, ints, uints (returns bools)
- `!=` between bigints, ints, uints (returns bools)
- `>` between bigints, ints, uints (returns bools)
- `<` between bigints, ints, uints (returns bools)
- `>=` between bigints, ints, uints (returns bools)
- `<=` between bigints, ints, uints (returns bools)
Does not cover:
- `=` (assignment, no return statement nor should …
=> Add explicit return types for the majority of operators in the BigInteger module

frontend/include/chpl/util/filesystem.h, frontend/lib/util/filesystem.cpp, tools/chpldoc/CMakeLists.txt, tools/chpldoc/chpldoc.cpp, tools/chpldoc/configured_prefix.h, util/buildRelease/install.sh
This PR gives `chpldoc` the ability to detect `CHPL_HOME` if it is not set
nor given as a command-line option.
`chpl` has the ability to locate `CHPL_HOME` if it's not set in the environment
nor given from the command-line. Previously, `chpldoc` also had this 
functionality as it was just a symlink to `chpl`. When we moved to 
`dyno-chpldoc`, we did not maintain this functionality, which wasn't detected 
because the installation script was not properly copying the new `chpldoc`. 
Once the installation script was corrected, this missing feature caused test 
failures, which forced us to revert PR 20880 (the installation script fix). 
With this PR, we should be able to un-revert PR 20880 and verify that the 
installation works and `chpldoc` detects `CHPL_HOME` appropriately when
it's not …
=> fix(chpldoc): make chpldoc detect CHPL_HOME if not set or passed

runtime/src/comm/ofi/comm-ofi-internal.h, runtime/src/comm/ofi/comm-ofi-locales.c, runtime/src/comm/ofi/comm-ofi-oob-mpi.c, runtime/src/comm/ofi/comm-ofi-oob-pmi2.c, runtime/src/comm/ofi/comm-ofi-oob-sockets.c, runtime/src/comm/ofi/comm-ofi.c
Added a few sanity checks to `comm=ofi` to prevent seg faults in situations that shouldn't happen, but might if the system is misconfigured:
* Added a check that the `tci` table is not zero-size.
* Added a check that the `tci` table index is valid when allocating an entry.
* Added functionality to `chpl_comm_verify_num_locales` to verify that the number of locales specified on the command-line matches that determined by the OOB module. This is only checked in runtime and not in the launcher.
* Added `chpl_comm_oob` that contains the name of the OOB module for use in `ofi` OOB messages and debugging.
Passes all multi-locale tests. 
This resolves https://github.com/Cray/chapel-private/issues/4089.
=> Additional ofi sanity checks

modules/standard/IO.chpl
This PR adds a brief warning to the top of the IO docs page to inform users that there may be some inconsistencies in the documentation due to ongoing deprecations, etc.
It specifically points out the problem with the `channel` type being referenced throughout the docs.
=> Warning about construction-zone status of the IO docs

test/library/standard/FileSystem/nonUTF8/basic.suppressif
This test fails in a way we suspect is related to issue https://github.com/Cray/chapel-private/issues/4097. Suppress the failure for Windows testing.
=> Add a suppressif for a test that fails on cygwin64

compiler/passes/convert-uast.cpp, test/parsing/IfExprInArrayComp.chpl
Fix bad lowering for forall statements containing an 'if' expr
Resolves #21125.
Prior to this PR the code in #21125 would trigger an internal
assertion.
After removing the assertion, the existing pattern matching was
incorrectly catching all if-expr and discarding the else branch.
The builder only cares about: `forall i in x do if x then ...;`.
So tighten up the pattern to only match conditional expressions
without an else branch.
TESTING
=> Fix bad lowering for forall statements containing an 'if' expr

runtime/src/comm/ofi/comm-ofi-locales.c
The launcher is built with the host compiler and `comm-ofi-internal.h` includes headers that might not be available, e.g., `rdma/fabric.h`. The fix is to not include `comm-ofi-internal.h` when building the launcher.
=> Don't include comm-ofi-internal.h when building the launcher

util/buildRelease/install.sh
This PR fixes a bug where the `install` script would always try
to copy the `chpldoc` binary, leading to errors if it hadn't been 
built. This change moves the install logic behind a check that
the `chpldoc` file exists.
TESTING:
reviewed by @ronawho - thanks!
=> fix(install): only try to install chpldoc if it was built

test/chpldoc/compflags/combinations/versionhelp-chpldoc.sh
This PR updates the `chpldoc` version test helper for release mode,
similar to how `test/compflags/bradc/printstuff/versionhelp.sh` was
updated in https://github.com/chapel-lang/chapel/pull/21162/.
This will fix the four failing chpldoc tests we see in paratest:
TESTING:
```
[Error matching compiler output for chpldoc/compflags/combinations/version.doc]
[Error matching compiler output for chpldoc/compflags/combinations/z_copy_version.doc]
[Error matching compiler output for chpldoc/compflags/combinations/z_copyright_help_version.doc]
[Error matching compiler output for chpldoc/compflags/combinations/z_help_version.doc]
```
reviewed by @bradcray - thanks!
=> update chpldoc test helper for release

frontend/include/chpl/uast/uast-classes-list.h, frontend/test/parsing/testParseSync.cpp
This PR fixes bug where `Sync` nodes would not respond
properly to `isSimpleBlockLike()` because they were listed
in `uast-classes-list.h` as deriving from `AstNode` directly.
TESTING:
reviewed by @dlongnecke-cray - thanks!
=> fix: define Sync as a subclass of SimpleBlockLike

third-party/chpl-venv/chpldoc-requirements3.txt
This PR updates the version number of the `sphinxcontrib-chapeldomain` package
required for building docs from `0.0.23` to `0.0.24`. The change corresponds
to the release of an updated package which can correctly format function
signatures that have a `this` intent type of `ref`, such as `proc ref myFunc()`
Changes motivated by https://github.com/chapel-lang/chapel/issues/13983
TESTING:
=> update required version of sphinxcontrib-chapeldomain

modules/standard/IO.chpl, test/deprecated/IO/unicodeSupported.good
At @bradcray's suggestion, adding rationale for deprecation to the deprecation message of `unicodeSupported`. (`unicodeSupported` was recently deprecated in https://github.com/chapel-lang/chapel/pull/21086.)
Testing:
=> Add rationale for deprecation of unicodeSupported

modules/internal/ChapelGpuSupport.chpl
That made `debugGpu` a private config param
I didn't intend to submit this but it accidentally got rolled into https://github.com/chapel-lang/chapel/pull/21175
=> Fix accidental commit

modules/standard/IO.chpl, modules/standard/OS.chpl, modules/standard/SysBasic.chpl, test/deprecated/SysBasic/chapel_specific_errors.good
Add `pragma "no doc"` to the Chapel-specific `IO` error codes `EEOF`, `ESHORT`, and `EFORMAT`.
I should have done this for https://github.com/chapel-lang/chapel/issues/20130 (implemented in https://github.com/chapel-lang/chapel/pull/20834) but misunderstood and left them user-facing after the move. Additionally, these symbols should be made `private`, but as we are past code freeze for the 1.29 release that will be done in a follow-up PR.
Testing:
=> No-doc Chapel-specific IO error codes

util/buildRelease/gen_release
Un-tar in mac fails with  chapel-1.29.0/tools/chpldoc/COPYRIGHT: Skipping hardlink pointing to itself: chapel-1.29.0/tools/chpldoc/COPYRIGHT
Based on a previous fix 
https://github.com/chapel-lang/chapel/pull/20679 removed COPYRIGHT from util/buildRelease/gen_release
=> fix un tar issue in mac

doc/rst/conf.py, doc/util/versionButton.php
This is the usual post-branch, pre-release update to the
docs button while capturing docs to chapel-www.
=> Update docs menu/button to reflect staged release

test/io/ferguson/seeking.chpl, test/library/packages/LinearAlgebra/performance/me/me-perf.execopts, test/library/standard/Random/RandomStreamInterface/choiceTestUtils.chpl
Decrease some problem sizes for:
- me-perf: 240s -> 1s
- seeking: 120s -> 1s (for all 4 execopts on NFS)
- choiceTest{Arr,Dom,Rng}: 200s -> 20s (for all three tests)
Part of Cray/chapel-private#3211
=> Drop problem sizes for some slow running tests

highlight/vim/README.rst, highlight/vim/ftplugin/chpl.vim, highlight/vim/sample-vimrc
Resolves #21083
This PR adjusts the `ftplugin/chpl.vim` file to not set and indent level, instead relying upon the user's `.vimrc` to set that as appropriate. It updates some of the related comments and consolidates the commands to enable filetype detection, highlighting, and plugins.
=> Adjust vim editor support indent settings

frontend/include/chpl/framework/UniqueString-detail.h, frontend/include/chpl/framework/UniqueString.h, frontend/include/chpl/parsing/parsing-queries.h, frontend/include/chpl/resolution/can-pass.h, frontend/include/chpl/resolution/copy-elision.h, frontend/include/chpl/resolution/resolution-queries.h, frontend/include/chpl/resolution/resolution-types.h, frontend/include/chpl/types/QualifiedType.h, frontend/lib/parsing/parsing-queries.cpp, frontend/lib/resolution/InitResolver.cpp, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/Resolver.h, frontend/lib/resolution/VarScopeVisitor.cpp, frontend/lib/resolution/VarScopeVisitor.h, frontend/lib/resolution/call-init-deinit.cpp, frontend/lib/resolution/copy-elision.cpp, frontend/lib/resolution/default-functions.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/resolution-types.cpp, frontend/lib/resolution/split-init.cpp, frontend/test/framework/testUniqueString.cpp, frontend/test/resolution/CMakeLists.txt, frontend/test/resolution/testCallInitDeinit.cpp, frontend/test/resolution/testInteractive.cpp, frontend/test/resolution/testLoopIndexVars.cpp, frontend/test/resolution/testResolveNew.cpp, frontend/test/resolution/testSplitInit.cpp, frontend/test/resolution/testTuples.cpp, frontend/test/resolution/testTypeConstruction.cpp, frontend/test/resolution/testTypeQueries.cpp
* Fixes a bug with UniqueStrings starting with the zero byte returning `true` for `isEmpty()` even if that is not the case
* Adjusts the resolver to infer the types of generic/untyped `out` formals from the function body. Added a concept of `inferredFrom` to `TypedFnSignature` to support that & avoid resolving function bodies twice (because the `TypedFnSignature` with the different `out` values is actually a different input to the queries to resolve the function, so we go back to the version without that inference when resolving).
* Changes associatedFns to associatedActions to include a wider variety of things we need to resolve. For now, deinits are associatedActions attached to the Block in which the deinit occurs. Each associatedAction includes an enum value indicating what type of …
=> dyno: fill in details to call init, deinit, etc

compiler/passes/checkParsed.cpp, compiler/resolution/functionResolution.cpp, compiler/resolution/resolveFunction.cpp, compiler/resolution/wrappers.cpp, frontend/test/resolution/testCallInitDeinit.cpp
This PR fixes 4 warnings from compiling Chapel with clang 15 and e.g. `CHPL_HOST_COMPILER=clang make WARNINGS=1`. In all of the cases, a local variable is not used other than being incremented.
=> Fix warnings from clang 15 due to unused variables

test/GPU-GRAPHFILES, test/gpu/native/studies/chop/README, test/gpu/native/studies/chop/chplGPU.chpl, test/gpu/native/studies/chop/chplGPU.gpu-compopts, test/gpu/native/studies/chop/chplGPU.gpu-execopts, test/gpu/native/studies/chop/chplGPU.gpu-keys, test/gpu/native/studies/chop/chplGPU.graph, test/gpu/native/studies/chop/chplGPU.skipif, test/gpu/native/studies/chop/headers, test/gpu/native/studies/chop/modules
This sets up nightly performance testing for ChOp with GPU support enabled. We intend to run this on the same Cray CS machine we do other GPU testing with.
In order to automatically download ChOp before running the test I make <strike>hacky</strike> clever use of an executable `.skipif` file that will clone the ChOp repos. The test dir has symbolic links into the relevant files/dirs of the (to be downloaded) clone that we want to test. Before cloning the ChOp repos these links will be pointing to invalid targets but that's fine (it'll be fixed before the test actually runs).
---
I have some concern about whether `chapelu` can do a git clone of the repos from the `https` address on this machine due to the fact that I get an OpenSSL error if I do that under my user account. See this issue …
=> Add nightly ChOp + GPU performance testing

test/multilocale/numLocales/bradc/testVFlag.launcher-slurm-srun.goodstart, test/multilocale/numLocales/bradc/testVFlag.prediff, test/multilocale/numLocales/bradc/testVerboseFlag.launcher-slurm-srun.goodstart, test/multilocale/numLocales/bradc/testVerboseFlag.prediff
The `testVFlag` and `testVerboseFlag` tests assumed that `--mem=0` is passed to `srun`. However, the `CHPL_LAUNCHER_MEM` variable controls the `--mem` argument and can break these tests. If `CHPL_LAUNCHER_MEM` is not set then the default value of 0 is used with `--mem`, otherwise if the value of `CHPL_LAUNCHER_MEM` is "unset" the `--mem` option is not passed to `srun`, otherwise the value of `CHPL_LAUNCHER_MEM` is used with `--mem`. The exact value passed to `--mem` is not tested, just whether or not it appears as an argument to `srun`.
=> Handle --mem correctly in vflag slurm-srun launcher tests

util/cron/test-perf.cray-cs-hdr.gpu.bash
The URL we were using, although valid, fails on the particular machine we do nightly testing on. Update our nightly tests to use a different URL.
=> Update path used to clone ChOp for testing

frontend/lib/uast/post-parse-checks.cpp
Fixes a memory issue caught by ASan that was introduced in https://github.com/chapel-lang/chapel/pull/21135/files.
=> Fix use of deallocated string in post-parse-checks

doc/util/versionButton.php
This is the standard change to make the 1.29 docs the default for today's release
=> Update version button to reflect 1.29 release

util/cron/common-arkouda.bash
Apparently I missed upgrading to 1.28 before, but there were no major perf changes in 1.28 so this wasn't a big deal.
See Bears-R-Us/arkouda#1966
=> Upgrade Arkouda release testing from 1.27.0 to 1.29.0

util/buildRelease/install.sh
This PR removes the portion of the install.sh script that was responsible for 
copying chpldoc and creating the chpldoc-legacy link. This step is no longer 
needed as it is being handled by CMake now, and continuing to copy and 
overwrite the chpldoc file creates errors when trying to run chpldoc 
w.r.t shared library libdyno.so
This should fix a failing `make-install-check` nightly test
TESTING:
reviewed by @riftEmber - thank you!
=> fix(build): don't copy chpldoc in install.sh

util/cron/common.bash
This PR adds another nightly script for sourcing to the `common.bash` file. 
I added a local install of `cmake 3.25.1` to `/cy/users/chapelu`,
along with a script to add it to the path for nightly testing. 
This change makes the `common.bash` script aware of the `cmake` 
setup script.
This change, along with the local `cmake` install, should fix
a number of nightly test failures.
TESTING:
=> fix(test): add local cmake for nightly testing on raptor

compiler/parser/parser.cpp
Follow-up to #20919. Initializes the variable `hadErrors` to `false`.
I noticed this problem when running `valgrind` on the compiler for other reasons.
While this error is worth fixing, it's unlikely to present a problem in the 1.29 release (see details).
<details>
`dynoRealizeErrors` is only called as `if (dynoRealizeErrors()) USR_STOP();` and `USR_STOP` itself does nothing if there were no errors. In fact, I can compile Hello World if `dynoRealizeErrors` always returns `true`. Nonetheless, I think having `dynoRealizeErrors` return an accurate `bool` better communicates the intent here than relying on the behavior of `USR_STOP`. The one counter-argument than I can think of is that the current logic still relies on `USR_STOP` not stopping if only warnings were issued.
</details>
Reviewed …
=> Fix an uninitialized variable in dynoRealizeErrors

compiler/main/runpasses.cpp, test/compflags/stopAfterNonexistentPass.chpl, test/compflags/stopAfterNonexistentPass.compopts, test/compflags/stopAfterNonexistentPass.good
This PR adds functionality to ensure that a pass specified with `--stop-after-pass` actually exists. If it does not, we emit a fatal error.
While working on https://github.com/chapel-lang/chapel/pull/21063, I realized this would be nice to have when trying to determine if the user has specified any flags that would cause compilation to stop before `makeBinary`.
Testing:
=> Verify that --stop-after-pass pass actually exists

frontend/include/chpl/framework/error-classes-list.h, frontend/lib/framework/error-classes-list.cpp
Error macros in `error-classes-list.h` and their corresponding `write` definitions in `error-classes-list.cpp` are now grouped by compilation stage, and alphabetized within their groups. Delineation between groups is made more clear, and groups are ordered by the order they occur in compilation.
Resolves https://github.com/Cray/chapel-private/issues/4136.
=> Alphabetize and group error lists

compiler/etc/gdb.commands
This should resolve failures in nightly testing in this test:
test/compflags/bradc/gdbddash/declint.chpl
on systems running gdb 8.2 or later.
On these systems, gdb goes into an infinite loop generating the error `'tmpdirname' has unknown type; cast it to its declared type`. The change in this PR avoids the infinite loop.
gdb 8.0.1 does not go into an infinite loop because it prints out 'tmpdirname' as an int, given a nondevel-built compiler, even though it is a char*. My speculation is that gdb devs changed it to an error thinking that it would be a better behavior in the case where the type is unknown.
tmpdirname is referenced in the hooks in compiler/etc/gdb.commands:
define hook-quit
if ($forcecmd != 1)
if (tmpdirname != 0)
call cleanup_for_exit()
end
end
set $forcecmd = 0
end
Note …
=> Adjust gdb.commands

frontend/README
In particular, clear up when to create class-based errors and when to
use the more simple error reporting mechanism. Also adds some note
about when to create separate classes and when to use a single class.
=> Add a note on error message style in the README.

doc/rst/usingchapel/prereqs.rst
This PR updates the optional prerequisites section of our docs to
indicate that `cmake` version 3.16 or newer is required to install
`chpl` after choosing an installation with `./configure --chpl-home=/path/to/install`.
This change was motivated by changes in https://github.com/chapel-lang/chapel/pull/21271,
which added an error when `cmake` < 3.16 and `./configure --chpl-home=/path/to/install`
has been ran. 
TESTING:
reviewed by @mppf - thank you!
=> chore(docs): update prereqs to indicate cmake requirement for installs

modules/packages/Curl.chpl, modules/packages/HDFS.chpl, modules/standard/BigInteger.chpl, modules/standard/ChapelIO.chpl, modules/standard/IO.chpl, test/io/ferguson/inteof.chpl, test/studies/lulesh/bradc/tests/lulesh-eof.chpl, test/studies/ssca2/graphio/SSCA2_RMAT_graph_generator.chpl, test/studies/ssca2/main/SSCA2_Modules/io_RMAT_graph.chpl
These internal Chapel-specific `IO` error codes should not be user facing, but were unintentionally left that way in https://github.com/chapel-lang/chapel/pull/20834.
This is a follow-up to https://github.com/chapel-lang/chapel/pull/21199 which `no doc`'d the symbols but did not `private` them due to code being frozen for 1.29 release. Getting rid of or otherwise modifying the subclasses of `SystemError` corresponding to these error codes will be done in a future PR.
Testing:
=> Make EEOF, ESHORT, and EFORMAT private

doc/rst/developer/index.rst
Extra space before the last period at https://chapel-lang.org/docs/1.29/developer/index.html does not appear necessary for the link to render properly.
=> Remove an extraneous space before a period in docs

util/cron/nightly
To resolve out-of-memory issues in some configurations now that `make -j` can have more parallelism after PR #20920.
=> Avoid python27 testing config doing make -j

test/library/draft/DistributedMap/v3/ChainTable.chpl, test/library/draft/DistributedMap/v3/SKIPIF
Some of the new distributed map prototype was using deprecated code, so this PR cleans up those deprecations and adds a `SKIPIF` for `memLeaks` so that those can be resolved after the holidays.
=> Fix distributed map prototype tests

frontend/lib/CMakeLists.txt
This PR adjusts how liblibdyno.so links with LLVM to avoid including LLVM symbols within it to avoid errors like this:
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
which seem to occur with LLVM 11 or 12
=> Workaround problems when statically linking with older LLVMs

test/compflags/ferguson/home/sub_test
This PR removes some configurations that were testing if the `chpl`
binary could locate `CHPL_HOME`. The removed configurations don't make sense 
after PR https://github.com/chapel-lang/chapel/pull/21271, where we made the 
compiler library path relative to the `chpl` binary by setting
its `RPATH` to start with `$ORIGIN`. In the tests, we were moving the location of
the `chpl` binary, which broke the relative location of the library
W.R.T `chpl` when we copied it to `bin/`. 
=> fix(test): remove some test configs for finding chpl_home

test/classes/initializers/records/array-from-for-expr.bad, test/expressions/loop-expr/recordWrappedClassBug.bad
Follow-up to PR #21263 which removed an unnecessary default initialization which now no longer appears in error messages in the .bad files. These tests still do not work as intended for other reasons, however.
Test change only - not reviewed
=> Update two .bad files after removing unnecessary default-init

util/buildRelease/smokeTest
This PR aligns the `make` args used for building `chpl`, `chpldoc`, and the 
chapel documentation from the `nightly` script. Previously, `chpl` and 
`chpldoc` were built with the `make` args `DEBUG=0 WARNINGS=1 OPTIMIZE=1`, 
but the `doc` target was not getting any of those args. 
Since the changes in PR #20920, CI builds for the `make doc` step have 
been running noticeably longer. This is because the presence/absence of those
`make` args made `CMake` see the need for different builds, so it would build
the compiler twice. 
This change returns the CI to a more reasonable running time.
1. Last CI prior to #20920: https://github.com/chapel-lang/chapel/actions/runs/3707337056
make docs runtime ~ 11 minutes (same as `make check`)
2. After #20920, the runtime jumped to ~23 minutes: …
=> fix(test): add make args to make docs command

test/compflags/bradc/gdbddash/declint.prediff
This PR adjusts the prediff for this test:
test/compflags/bradc/gdbddash/declint.chpl
to ignore more cases in gdb output that are reasonable yet resulted in .good mismatches after #21269.
For example:
Reading symbols from /path/to/chpl...
Breakpoint 1 at 0x33890
(gdb) 'tmpdirname' has unknown type; cast it to its declared type
(gdb) quit
Tested by running start_test on this test
in a linux64 and a linux32 configurations.
Merging for expediency. Post-merge review is welcome.
=> Adjust declint.prediff

util/buildRelease/smokeTest
Arkouda now needs `CHPL_GMP` for the newly added bigint module, so this PR skips setting `CHPL_GMP` to none if it is an Arkouda smoke test.
Companion PR: https://github.hpe.com/hpe/hpc-chapel-ci-config/pull/942
=> Don't set CHPL_GMP to none for Arkouda smoke

frontend/lib/CMakeLists.txt
This PR fixes builds on Cygwin which started breaking after PR #21276- which made the
link option INTERFACE for all non-apple builds. Apparently Cygwin also falls
into the special use case and needed similar treatment.
TESTING:
=> fix(build): change libdyno link to PUBLIC for cygwin

util/build_configs/cray-internal/chapel.modulefile.lua.template
Based on the comment on the PR #21313, removing copyright from the file util/build_configs/cray-internal/chapel.modulefile.lua.template
=> Followup_21312

test/classes/assignments/noAssignClassModuleScope.bad, test/classes/assignments/noAssignClassModuleScope.chpl, test/classes/assignments/noAssignClassModuleScope.future, test/classes/assignments/noAssignClassModuleScope.good
=> Add future for 14740: User definition of a class operator= not detected when unused in its module

util/config/write-git-sha
This PR fixes a problem where a git-sha would be written out with a
preceding `'b'`. This was introduced with fixes for python 2.7 compatibility
that came in https://github.com/chapel-lang/chapel/pull/21268.
Testing:
reviewed by @riftEmber - thank you!
=> fix(build): capture python subprocess output as string, not bytes

frontend/Makefile.help
This PR adjusts the path used when building the parser
using the `make parser` command. The change allows for 
building of the parser where it would fail before due to
an invalid path specification. 
I believe this was caused by changes to `frontend/Makefile.help` in https://github.com/chapel-lang/chapel/pull/20815
that were modified with https://github.com/chapel-lang/chapel/pull/20920
Thanks to @DanilaFe for reporting this!
TESTING:
reviewed by @dlongnecke-cray - thanks!
=> fix(build): adjust Makefile path for building parser

compiler/util/misc.cpp
Resolves #21291 which most likely appeared as a result of PR #20920.
With GCC at least, it depends on the exact details of the compilation command whether or not `__FILE__` is an absolute path. With the cmake change, it appears we are now getting an absolute path. This PR changes the error reporting logic to compute the file basename (since the directory is handled by other means) in order to make the error reporting produce the same error whether or not `__FILE__` is an absolute path.
=> Adjust error reporting to use basename of __FILE__

modules/standard/BigInteger.chpl
The modulus operator, when operating on remote data, was only creating a local copy of the LHS bigint value, so if the RHS was remote, this would cause a gasnet error.
=> Make bigint mod operator operate on local copies

test/compflags/bradc/html/testit.compopts, test/compflags/diten/noInlineAndHtml.compopts
Switch tests from `--html` to `--html-user`. `--html` results in 200M of data in ~3500 files and `--html-user` only results in 300K of data in 40 files. This speeds up these tests on slower filesystems, especially NFS. On a fairly good NFS, this takes the tests from 120s to 5s.
Another alternative would be to write the full logs a tmp directory if we think there's value in generating the full log.
Part of Cray/chapel-private#3211
Part of Cray/chapel-private#4110
=> Reduce filesystem load of `--html` tests

compiler/passes/convert-uast.cpp, frontend/include/chpl/framework/error-classes-list.h, frontend/include/chpl/resolution/scope-types.h, frontend/lib/framework/error-classes-list.cpp, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/Resolver.h, frontend/lib/resolution/scope-queries.cpp, frontend/test/resolution/testScopeResolve.cpp
This fixes a few scope resolution issues.
* Dyno doesn't go the "usual" way for finding import targets when faced with a top-level dot-expression like `M.f`, because `f` may be overloaded. This is needed because the "usual" way doesn't cope with overloading. However, when the last identifier in a dot chain is `super` or `this`, there's no need to account for overloading, so this PR changes Dyno to use the "usual" algorithm for handling these (and thus makes it understand `super` and `this` in the rightmost position of a dot expression in imports/uses).
* With the addition of support for private fields, all modules discovered via renaming (`import M as X`) were marked as public. This is not correct, since a `private` module should not show up outside of its scope.
* The `Dot` operator was …
=> Fix some import and module scope resolution issues

util/test/find_slow_tests.py, util/test/paratest.server
Paratest farms out directories to worker nodes to parallelize and speed up testing. Previously, it farmed out in lexicographic order, but this could result in a long tail of tests if a long running directory was handed out near the end. This updates paratest to try and run the slowest directories first. It does this by extracting directory timings from a previous test log into a file in `$HOME/.chpl/paratest_times/`.
For this first version, only save the historical data if we're running the full test suite and there were less than 10 failures. Results are saved into comm layer specific files since `comm==none` vs `comm!=none` will likely have a big impact on what tests are run and how long they take.  Longer term, we may want to include other things that impact results (valgrind/asan, …
=> Paratest the slowest directories first

util/test/paratest.chapcs
Bump number of paratest clients from ~4 to 6. Historically, there was no advantage to running more clients since we got stuck waiting for a long tail, but now that we're running slower dirs first there is a speedup and this should shave a couple minutes off a paratest.
We also used to have more complicated logic to drop the number of clients when doing a gasnet run or if another paratest was running to try to limit interference. In practice we haven't had any issues with interference so I want to try a fixed number of clients.
Part of Cray/chapel-private#3211
=> Increase the amount of oversubscription for paratesting

util/test/paratest.chapcs, util/test/paratest.chapdl
Add paratest.chapdl as a variant of paratest.chapcs that sets the new partition and increases oversubscription.
=> Add paratest.chapdl wrapper

frontend/include/chpl/framework/Context.h, frontend/include/chpl/framework/ErrorBase.h, frontend/include/chpl/framework/ErrorMessage.h, frontend/include/chpl/framework/ErrorWriter.h, frontend/include/chpl/parsing/FileContents.h, frontend/include/chpl/parsing/parser-error.h, frontend/include/chpl/uast/Builder.h, frontend/lib/framework/Context.cpp, frontend/lib/framework/ErrorBase.cpp, frontend/lib/framework/ErrorMessage.cpp, frontend/lib/framework/ErrorWriter.cpp, frontend/lib/parsing/Parser.cpp, frontend/lib/parsing/ParserContext.h, frontend/lib/parsing/ParserContextImpl.h, frontend/lib/parsing/bison-chpl-lib.cpp, frontend/lib/parsing/chpl.ypp, frontend/lib/parsing/flex-chpl-lib.cpp, frontend/lib/parsing/flex-chpl-lib.h, frontend/lib/parsing/lexer-help.h, frontend/lib/parsing/parsing-queries.cpp, frontend/lib/uast/Builder.cpp, frontend/lib/uast/post-parse-checks.cpp, test/parsing/errors/stringLiteralEOF-detailed.good
Miscellaneous tweaks for the error system, such as:
* Removal of `ParseError` and `ParseSyntax` in favor of `GeneralError`
* Removal of `_NOTE` and `_SYNTAX` macros where appropriate (`NOTE` in particular will likely never be needed, since it's superseded by `ErrorWriter::note` calls from `ErrorBase::write`. 
* Merging of "empty `ID` or empty `Location`" logic into an `IdOrLocation` class to help reduce duplication.
* Switch from macros like `CHPL_REPORT` to `error` and `syntax` methods where possible (in particular for generic errors without special classes)
* Rename `ErrorType::GENERAL` to `ErrorType::General` to match every other generated `ErrorType`.
Testing:
=> Error system tweaks

util/config/write-git-sha
This PR makes a small but important change to how we generate
the `git-version.cpp` file. Rather than write the temp file
in-source, we will now write it to a temp directory to avoid
the possibility of getting a race condition when using an IDE
that supports multiple build configurations (e.g., CLion).
TESTING: 
reviewed by @dlongnecke-cray - thank you!
=> fix(build): write temp git-sha file to temp location

compiler/llvm/llvmAggregateGlobalOps.cpp, compiler/llvm/llvmUtil.cpp
Removes usages of `getPointerElementType` in `llvmAggregateGlobalOps.cpp` and `llvmUtil.cpp` when using llvm >= 15, to accommodate the switch to opaque pointers.
Resolves https://github.com/Cray/chapel-private/issues/4057.
Testing:
=> Replace getPointerElementType in llvmAggregateGlobalOps and llvmUtil

modules/internal/String.chpl
Have the documented example of using string.items() actually invoke string.items() instead of relying on the implicit string.these() being equivalent.
---
Signed-off-by: Paul Cassella <gitgitgit@manetheren.bigw.org>
=> Update string.items() doc example

modules/standard/Map.chpl, test/library/standard/Map/types/MapTest.chpl, test/library/standard/Map/types/testBorrowed.good, test/library/standard/Map/types/testNilableBorrowed.chpl, test/library/standard/Map/types/testNonNilableUnmanagedIndexingError.chpl, test/library/standard/Map/types/testNonNilableUnmanagedIndexingError.good, test/library/standard/Map/types/testRecord.chpl, test/library/standard/Map/types/testTupleIndexingError.chpl, test/library/standard/Map/types/testTupleIndexingError.good
The error is about non-nilable classes, not nilable classes, so correct it to say that.  Also have the error indicate that it's coming from a Map.this() routine to help the user identify what part of their code is to blame.
Update test/library/standard/Map/types tests to:
- Test indexing operations for maps with nilable classes and records as value types
- Test that maps with nilable class value types can have nil stored, retrieved, and removed.
- Test that indexing fails to compile for non-nilable classes and tuples.
Resolves #21222
=> Correct and improve Map.this() non-nilable class error, add tests

compiler/llvm/llvmAggregateGlobalOps.cpp
Fixes an unintentional change from https://github.com/chapel-lang/chapel/pull/21121 that caused nightly test failures.
Thanks @mppf for the debugging help.
Testing:
- manually verified this resolves the observed nightly test failure
=> Fix a typo from opaque-pointer changes

test/classes/initializers/cond-only-then-2.chpl
This test file comment was out of date - conditionals with different uses of field initializers are fine
Noticed while working on supporting initializers that throw during Phase 2.
Passed a fresh checkout of the test
=> Update the comment in this test file

test/studies/adventOfCode/2022/day11/bradc/SKIPIF
My day 11 solution is 'sync' variable based, and on 32-bit platforms,
'sync' is not implemented with native qthread syncs, so is painfully slow.
Skip this test in those configurations for that reason. ARM-based systems
also don't use native qthread 'sync', but should soon, and we're not seeing
failures with this test in those configs (most likely, not testing this test in
those configs), so I'm not skipping it for now.
This issue made me wonder whether we would want to have a CHPL_SYNCS
setting like CHPL_ATOMICS that said which implementation we were using s.t.
a skipif could focus on that rather than platform-specific details.
=> Skip my day11 AoC 2022 test for 32-bit platforms

test/library/standard/Map/types/ClassWithMapWithRecord.bad, test/library/standard/Map/types/ClassWithMapWithRecord.chpl, test/library/standard/Map/types/ClassWithMapWithRecord.execopts, test/library/standard/Map/types/ClassWithMapWithRecord.future, test/library/standard/Map/types/ClassWithMapWithRecord.good
Add a future for #21193.
This test is developed in @cassella in #21307 - many thanks! This PR replaces that one with a slightly polished version of the test.
I am adding .execopts with --memLeaks because I suspect that even if the test compiles, it will leak an object or two. See a comment in the source.
Once this test works without memleaks, the --memLeaks should be removed so that most testing configs run without it just like for most other tests.
=> Add future for #21193

util/cron/test-homebrew.bash
Fix for the failure in the weekly homebrew jenkins testun:
https://chapel-ci.us.cray.com/job/homebrew-test-homebrew/lastBuild/consoleFull
Removed $CWD/nightly.
homebre-test in cron runs pidig to verify chpl install so $CWD/nightly -cron does not seem to add any value here.
=> Remove nightly -cron from homebrew test

test/extern/ferguson/bug-global-c-array.bad, test/extern/ferguson/bug-global-c-array.chpl, test/extern/ferguson/bug-global-c-array.future, test/extern/ferguson/bug-global-c-array.skipif
Update the #12055 future.
Add "use CTypes" to test.
Add .bad file for internal error with COMM=gasnet
Add skipif since internal error doesn't happen with COMM=none
=> Update future for 12055 global extern record containing array

test/types/records/ferguson/leak-futures/iterate-loop-break.chpl, test/types/records/ferguson/leak-futures/iterate-loop-break.future, test/types/records/ferguson/leak-futures/iterate-loop-break2.chpl, test/types/records/ferguson/leak-futures/iterate-loop-break2.future, test/types/records/ferguson/leak-futures/iterate-twice-break.chpl, test/types/records/ferguson/leak-futures/iterate-twice-break.future, test/types/records/ferguson/tracking-record/myrecord.chpl, test/types/records/ferguson/tracking/Tracking.chpl
Fix Tracking.chpl printthem() to use arr keys instead of values to index into to_x.  This fixed a Map out-of-bounds error in at least iterate-twice-break.chpl.
Fix the make() routine in iterate-twice-break, iterate-loop-break, iterate-loop-break2 to call ret.setup() instead of ret.init().  This seems to resolve the leaks -- self-reported and via --memLeaks=true.
Remove those tests' futures, as they now pass.
Fix a typo in myrecord.chpl
=> Update and defuturize types/records/ferguson/leak-futures

compiler/AST/symbol.cpp, compiler/codegen/cg-symbol.cpp, compiler/codegen/cg-type.cpp, compiler/codegen/codegen.cpp, compiler/include/symbol.h, compiler/llvm/llvmDebug.cpp
With opaque pointers we now need to store store the class structure type instead of the class pointer type because we need this information in a few places. So when storing this type don't make it a pointer.
Change the name of 'TypeSymbol::llvmType' to 'TypeSymbol::llvmImplType' and add accessors to get the field either as a pointer or as the underlying structure. Update accesses of llvmType to use the accessor that returns a pointer for classes.
The accessor that returns the structure is currently unused so is commented out to avoid unused function warnings. It will be used shortly.
=> Start storing class structure type instead of pointer type for TypeSymbols

compiler/codegen/codegen.cpp
The CHPL_LLVM=none build failed with an undefined function. The bad function call was in a section that should have only been included for LLVM.
=> Add an ifdef HAVE_LLVM for an llvm-only section of codegen

compiler/codegen/cg-expr.cpp, compiler/optimizations/gpuTransforms.cpp, runtime/include/chpl-gpu-impl.h, runtime/include/chpl-gpu.h, runtime/src/chpl-gpu.c, runtime/src/gpu/common/cuda-shared.h, runtime/src/gpu/cuda/gpu-cuda.c, runtime/src/gpu/rocm/gpu-rocm.c, test/gpu/native/streamPrototype/stream.chpl
This PR improves GPU kernel launch times by loading the binary CUDA module only
once per locale.
Previously, we used to re-load the module everytime we launch a kernel. There
was nothing smart behind it -- it was an artifact from earlier prototypes.
The change is relatively straightforward. The only interesting note is that
it appears that you have to load the module per context (i.e., per device).
Which is a bit strange, but that's what the documentation says and not doing
it that way breaks multi-gpu execution.
While there, this test also changes the stream prototype to use `foreach`
instead of `forall` to make it a more apples-to-apples comparison to a
single-GPU C+CUDA reference. `forall` option is available with a `config param`.
On my A100 based system, I am seeing 250 GB/s as …
=> Avoid loading CUDA module at each kernel launch

compiler/codegen/cg-expr.cpp
This change is needed to enable building the compiler under CHPL_LLVM=none.
Testing:
* the compiler builds for CHPL_LLVM=none on my mac
* hello4 passes
=> Fix compiler build with CHPL_LLVM=none

compiler/codegen/cg-expr.cpp
This `ifdef LLVM` was modified in df3f504.
However, I should have deleted it, as the LLVM call that it
protects was also removed in that commit. This PR deletes that
check, which also caused a ton of issues with `CHPL_LLVM=none`. 
Test:
=> Remove an unnecessary LLVM check

compiler/codegen/cg-symbol.cpp, compiler/codegen/codegen.cpp, compiler/include/LayeredValueTable.h, compiler/llvm/clangUtil.cpp
Add a 'Type* chplType' field to the LVT to track pointer types. Adjust the LayeredValueTable::addGlobalValue() function to take a Type* argument and set the chplType field.
Adjust all calls to addGlobalValue() to pass a Chapel Type* to the new argument.
Adjust LayeredValueTable::getValue() to set the returned GenRet's chplType to the field set by addGlobalValue().
=> Add a chplType field to the LVT

runtime/include/chpl-comm.h, runtime/include/chpl-topo.h, runtime/src/chpl-comm.c, runtime/src/chpl-init.c, runtime/src/comm/gasnet/comm-gasnet.c, runtime/src/comm/none/comm-none.c, runtime/src/comm/ofi/comm-ofi-internal.h, runtime/src/comm/ofi/comm-ofi-oob-mpi.c, runtime/src/comm/ofi/comm-ofi-oob-pmi2.c, runtime/src/comm/ofi/comm-ofi-oob-sockets.c, runtime/src/comm/ofi/comm-ofi.c, runtime/src/comm/ugni/comm-ugni.c, runtime/src/launch/slurm-srun/launch-slurm-srun.c, runtime/src/tasks/qthreads/tasks-qthreads.c, runtime/src/topo/hwloc/topo-hwloc.c, runtime/src/topo/none/topo-none.c, test/multilocale/numLocales/bradc/testVFlag.launcher-slurm-srun.goodstart, test/multilocale/numLocales/bradc/testVFlag.prediff, test/multilocale/numLocales/bradc/testVerboseFlag.launcher-slurm-srun.goodstart, test/multilocale/numLocales/bradc/testVerboseFlag.prediff, test/runtime/jhh/lps_test.chpl, test/runtime/jhh/lps_test.py, util/test/prediff-for-slurm
Adds the ability to run multiple locales per node as determined by the CHPL_RT_LOCALES_PER_NODE environment variable. The default is to run one locale per node. If the number of locales per node is less than or equal to the number of sockets, then each locale uses only the cores associated with its socket. 
This functionality is only supported for the following configuration:
CHPL_COMM = ofi
CHPL_LAUNCHER = slurm-srun
CHPL_COMM_OFI_OOB = pmi2
CHPL_TASKS = qthreads
CHPL_QTHREAD_TOPOLOGY = binders
CHPL_HWLOC = bundled
=> Support for one locale per socket.

frontend/lib/resolution/scope-queries.cpp
The current mechanism for looking up a variable in a scope traverses the scope chain upwards until it hits a module. Unfortunately, when the _starting_ scope is a module, this meant that the _starting_ scope's parents, their parents, and so on, would be checked. This is improper, since a variable declared inside an inner module should not have access to the variables in the outer module.
<details>
<summary>Test program and output</summary>
__Program__
```Chapel
module A {
param x = 1;
module B {
param y = x;
}
}
```
__Compiler output__
```
➜  chapel git:(daniel-scope-resolve-6) chpl nesting.chpl --main-module A.B
nesting.chpl:3: In module 'B':
nesting.chpl:4: error: 'x' undeclared (first use this function)
```
</details>
So, this PR adds a check to prevent the parent-scope iteration if …
=> dyno: fix lookups extending outside scopes

compiler/codegen/cg-expr.cpp, compiler/codegen/cg-symbol.cpp
Instead of getPointerElementType(), use the type stored in TypeSymbols.
=> Update function 'codegenTernary' to avoid getPointerElementType()

frontend/lib/CMakeLists.txt
This PR modifies the build system behavior to check for the existence
of the git binary before trying to write a git sha value to `git-version.cpp`.
If git is not found or .git is not found, and we don't have an existing
`git-version.cpp` file, then write a dummy sha (`xxxxxxxxxx`) to the file.
TESTING:
=> fix(build): check for existence of git binary in CMake

test/with-runtime-fields-errors.done.good
This .good file is at the top-level test directory and isn't used by any test. Remove it.
=> Delete an extra .good file I accidentally added to the test/ directory

modules/internal/ChapelRange.chpl
In implementing #21332, I changed a degenerate range check from comparing ._low and ._high to something involving more helper routines and translating between representations.  This resulted in generating code that caused the C compiler to warn about comparisons that were tautologically true or false (like how the following will never be true):
```
if ((int)(x == y) > (int)true)
```
Here, I'm changing them back, which simplifies the code for readers, doesn't break any of the new tests I added, and makes the warnings go away (ironically, probably just by making the values less evident to the C compiler :).
We also saw some performance regressions in our nightly runs, and I'm wondering whether this could have been a factor.  On one hand, it's a long-shot that this happens to be it; on the …
=> Simplify a range iterator's check for an empty/degenerate range

modules/internal/ChapelRange.chpl
Looking at the 'anonymousRangeIter' failure caused by merging #21332, it appeared the the expression for computing the first/last element in a typical bounded range iteration had become more complicated by my refactoring.  Here, I'm splitting the common case of a completely bounded range into its own case and handling it identically to how we did prior to #21332, which should limit the complicated cases to iterations over unbounded ranges of enum and bool (the motivation for my refactoring).  This resolves the anonymousRangeIter test and makes the generated code much more similar to what we had before.
This change seems more likely to affect/improve the performance of range iteration than #21405, so I am cautiously optimistic that it will restore the performance of cases that slipped as …
=> Simplify the implementation of chpl__first|lastForIter for bounded ranges

test/gpu/native/localeName.chpl, test/library/standard/Spawn/spawn-checkmutate.chpl, test/library/standard/Spawn/spawn-checkret.chpl, test/library/standard/Spawn/spawn-print-args-env.chpl
This is a follow up to #21337 that adds a trailing comma to tests that
use 1-element array literals but are not part of the standard paratest
configuration (gnu-specific tests in one case; gpu-specific in the other).
=> Fix one-element array literals in skipif'd tests

test/studies/shootout/reverse-complement/bradc/revcomp-blc-gcc8-algs.perfcompopts
I originally wrote this performance test to use the spin-wait to see whether it was more stable than revcomp-blc-gcc8.chpl, but with CHPL_ATOMICS=intrinsics, as when using 'intel' compilers, the performance due to the contested reads is waaaay too slow.  I think switching to the waitFor() algorithm should be enough to speed it up, and is the preferred way to write this anyway.  If this doesn't fix the timeout, I'll add a skipif or suppressif...
=> Switch performance run of revcomp-blc-gcc8-algs to use 'waitFor' algorithm

frontend/test/resolution/testDeprecationUnstable.cpp
This PR fixes warning from GCC 12 that appeared after PR #21328 when running `make test-dyno`.
=> dyno: avoid a gcc warning

.github/workflows/email.yml
Added a retry logic in get commits payload step in case of any failures to parse the json in commits url.
This will address issues in https://github.com/Cray/chapel-private/issues/4149
=> Added a retry logic in email workflow

compiler/codegen/cg-expr.cpp, runtime/include/gpu/cuda/chpl-gpu-gen-includes.h, test/GPU-GRAPHFILES, test/gpu/native/studies/shoc/sort.chpl, test/gpu/native/studies/shoc/sort.gpu-compopts, test/gpu/native/studies/shoc/sort.gpu-keys, test/gpu/native/studies/shoc/sort.graph
This PR makes two changes:
* Changes how we generate threadblock barrier sync calls
* Starts gathering performance data for SHOC sort benchmark
To give some context ---
As discussed here (https://github.com/Cray/chapel-private/issues/4179) with our Chapel implementation of the SHOC sort benchmark we were running into an issue where we'd succeed when not compiling with `--fast` and fail when using `--fast).
I was able to narrow this down to a small reproducer example (seen here https://github.com/Cray/chapel-private/issues/4179#issuecomment-1382366379), which looks incredibly similar to this example on an LLVM bug report: https://github.com/llvm/llvm-project/issues/58626
In that bug report the author shows they can work around it by using inline assembly (marked volatile) to generate the …
=> Alt approach for GPU threadblock barrier sync

util/test/start_test.py
Adds a `--respect-notests` flag to the start_test script. When set, start_test will look for `.notest` files even when called on a specific chapel source file. 
This is analogous to the behavior of the existing `--respect-skipifs` flag.
=> Add respect-notests option for start_test

doc/rst/developer/bestPractices/CHPL_DEVELOPER.rst
Fixes an unclosed parenthesis and sentence.
=> Fix a typo on the CHPL_DEVELOPER docs page

modules/internal/ChapelDomain.chpl, modules/packages/SortedMap.chpl, modules/standard/Heap.chpl, modules/standard/List.chpl, modules/standard/Map.chpl, test/arrays/compilerErrors/arrayFieldOfSharedGenericClassType.chpl, test/arrays/compilerErrors/arrayFieldOfSharedGenericClassType.good
In https://github.com/chapel-lang/chapel/issues/21417#issuecomment-1402165732, it was noted that our internal domain module code has been using stacking of memory management types (e.g., 'borrowed shared C') in order to print out its errors, which is no longer supported.  Here, I'm rewriting it from 'borrowed t' to 't: borrowed'.  With a 'git grep', I also found other instances of this pattern in the collection modules, so have updated those as well.  I've added the test that led to this error.
=> Address cases of stacking class memory management types in our code

tools/c2chapel/test/help.2.good, tools/c2chapel/test/no-args.3.good, tools/c2chapel/test/tester.sh
Python 3.10 seems to have slightly different help output,
so add that as an alternative.
Reviewed by @bmcdonald3 - thanks!
=> Update c2chapel testing to handle help output from newer Python

runtime/include/chpl-comm.h, runtime/include/chpl-topo.h, runtime/src/chpl-init.c, runtime/src/comm/gasnet/comm-gasnet.c, runtime/src/comm/none/comm-none.c, runtime/src/comm/ofi/comm-ofi.c, runtime/src/comm/ugni/comm-ugni.c, runtime/src/topo/hwloc/topo-hwloc.c, runtime/src/topo/none/topo-none.c
The topology layer is initialized before the comm layer, however the topology layer calls `chpl_get_num_locales_on_node` during initialization, which requires that the comm layer be initialized enough to be able to provide this value. The new function `chpl_comm_pre_topo_init` does enough initialization so that `chpl_get_num_locales_on_node` returns the correct value. Also added error checking that the number of CPUs is set before it is used.
Resolves https://github.com/Cray/chapel-private/issues/4236 and closes https://github.com/Cray/chapel-private/issues/4281.
Also resolves https://github.com/Cray/chapel-private/issues/4229 and closes https://github.com/Cray/chapel-private/issues/4282. Initial experiments show that the performance of the tests that experienced regressions as a result …
=> Fix topo/comm initialization sequence.

compiler/codegen/codegen.cpp, test/gpu/native/environment/gpuCodegenErrorExitStatus.chpl, test/gpu/native/environment/gpuCodegenErrorExitStatus.compopts, test/gpu/native/environment/gpuCodegenErrorExitStatus.good
When GPU codegen has a failure, it exits the GPU subprocess with a non-zero exit code. The main compiler process then sees that the code from 'wait' is non-zero and also exits with that code. But the code from 'wait' is not just the code the subprocess exited with, so this ends up being equivalent to 'exit(0)'. Extract the actual exit code from the code set by 'wait' and exit with that code instead.
Add a test that causes GPU codegen to fail. start_test was previously failing for this test with errors like:
"[Error could not locate executable gpuCodegenErrorExitStatus for gpu/native/environment/gpuCodegenErrorExitStatus]".
Now it correctly detects that the compilation failed and stops there and diffs the compilation output vs. the .good file.
Fixes …
=> Fix failure to forward error code from gpu codegen

doc/rst/developer/bestPractices/CHPL_DEVELOPER.rst
The note implied that `TAGS`/`BROWSE` are built even when `CHPL_DEVELOPER` is not set, which is not currently true; see discussion in https://github.com/chapel-lang/chapel/issues/21432.
Resolves https://github.com/chapel-lang/chapel/issues/21432.
=> Remove an outdated todo note about TAGS from docs

modules/standard/IO.chpl
Fixes docs formatting issues introduced in https://github.com/chapel-lang/chapel/pull/21339 and pointed out by @jeremiah-corrado.
The issue was caused by some `throws` declarations not having any description text, causing these declarations to render as a single line of plain text instead of a bulleted list with a `Throws` header.
Incorrect rendering:
Correct rendering after fix:
This PR adds descriptions to all throws declarations in doc comments. It also includes some slight consistency improvements to docs added in https://github.com/chapel-lang/chapel/pull/21339, particularly in punctuation and indentation.
Testing:
=> Fix IO error docs formatting issues

test/mason/mason-external/masonExternalRanges/masonExternalExitCodes.suppressif, test/mason/mason-help-tests/masonHelpTests.suppressif
Continuing #20118.
This PR suppresses failures on two mason-external tests until we're able to upgrade spack versions (see https://github.com/Cray/chapel-private/issues/3518 and #21439).
=> Suppressif two more mason external tests

modules/standard/FileSystem.chpl, modules/standard/IO.chpl, test/deprecated/IO/fileCheck.chpl, test/deprecated/IO/fileCheck.good, test/io/dtjong/file-close-check.chpl, test/io/dtjong/file-close-check.good, test/library/standard/FileSystem/lydia/sameFile/givenNull.good, test/library/standard/FileSystem/lydia/sameFile/givenNull2.good, test/library/standard/FileSystem/lydia/sameFile/givenNull3.good
Resolves #20153 
Resolves Cray/chapel-private#4256
This method was intended to guard against performing operations on null or
closed files.  Replace it with something that is more explicitly for that, to
make it more obvious for users.
Adds a test locking in the deprecation message.
Adjusts the modules and testing system to use the new method:
- in FileSystem.sameFile, ensure both files are open and if not, throw an EBADF
about the operation, to maintain the original behavior
- Adjust the tests of sameFile for this new error message when it would be
triggered
- adjust file-close-check.chpl to use the new functions and not put the calls in
try/catches since it doesn't throw any more.  I also adjusted the output
slightly to reflect the new method name.  I chose not to rename the test since …
=> Replace `file.check` with `file.isOpen`

frontend/lib/resolution/Resolver.cpp
This PR fixes a bad name that slipped in between merging 
https://github.com/chapel-lang/chapel/pull/21357 and 
https://github.com/chapel-lang/chapel/pull/21396.
In #21357 I renamed `Attributes` to `AttributeGroup` and also renamed methods 
related to it. In #21396 the old name was used and while I rebased on `main` 
earlier today, #21396 came in between my last rebase and the merge of #21357.
reviewed by @DanilaFe - thanks!
=> update Attributes name after refactor

test/parallel/taskPar/nested/forall-with-continue-forall-bracket-expr.bad, test/parallel/taskPar/nested/forall-with-continue-forall-expr.bad, test/parallel/taskPar/nested/forall-with-continue-reduction-over-forall-bracket-expr.bad, test/parallel/taskPar/nested/forall-with-continue-reduction-over-forall-bracket-expr.prediff
This adjusts .prediff and .bad for the tests added in #21411 to eliminate a source of nondeterminism, where the following test:
test/parallel/taskPar/nested/forall-with-continue-forall-expr.chpl
reports nondeterminisic second error. The first two observed errors that have been either:
Conditional jump or move depends on uninitialised value(s)
Conditional jump or move depends on uninitialised value(s)
or:
Conditional jump or move depends on uninitialised value(s)
Invalid read of size 4
So, adjust .prediff to keep just the first error and adjust .bad appropriately. Since the same .prediff is shared across all three tests, adjust all three .bad files.
Related: the above test has been timing out in my own testing. If we observe that in the nightly testing, we could .notest it.
Trivial. …
=> Fix valgrind .bad mismatch

make/compiler/Makefile.clang, make/compiler/Makefile.gnu
Adds `-Og` flag to debug builds with GCC/Clang, which includes any build with `CHPL_DEVELOPER` set. This flag is intended to provide a level of optimization ideal for debugging. Flags for building with other compilers are unaffected.
Resolves https://github.com/Cray/chapel-private/issues/3202.
Testing:
=> Add -Og flag to CHPL_DEVELOPER builds on GCC/Clang

compiler/passes/InitErrorHandling.cpp, test/classes/initializers/siblingCall/reductionBefore.chpl, test/classes/initializers/siblingCall/reductionBefore.good
It looks like our testing system didn't have any tests of initializers with
reductions in their body, which meant that I missed a bug in my prototypical
implementation of throwing initializers.  Fix that bug and add a small
reproducer I made to verify the fix.
<details>
This part of the code was copied from the checking in normalize, but the AST
will have changed in between those passes, so it's perfectly reasonable for a
forall to have the fRecIterIRdef field set.  However, it shouldn't be relevant
when determining the initializer's phase at this time, as the normalize checking
of initializers should have errored if there was any `super.init()` or
`this.init()` call in code that would be included there.
</details>
With this change, the CHAMPS test that failed built appropriately. …
=> Fix bug with throwing initializers found by CHAMPS

test/library/packages/HDF5/HDF5Preprocessors.chpl
This one slipped by me because we don't test these in general due the HDF5 requirement, and we hadn't run the xc configuations that do since #21337 was merged.
=> Add a trailing comma to a test-specific one-element array literal

util/chplenv/chpl_mem.py
Our chplenv scripts typically just define defaults, but allow users to override even if they select unsupported configs. However, `CHPL_MEM` was forcing the default for some cases and wouldn't allow users to override. This wasn't a huge issue because jemalloc doesn't work on cygwin or as a target allocator for ARM macs. However, it also prevented using jemalloc as a host compiler on macs, but that configuration should work, we just haven't figured out rpath stuff to make it the default.
Part of Cray/chapel-private#4113
=> Stop overriding user supplied `CHPL_*_MEM`

make/compiler/Makefile.clang
Remove `-Og` optimization flag from Clang builds which was added in https://github.com/chapel-lang/chapel/pull/21434.
This flag seems to break debuggability as mentioned in the OP of https://github.com/Cray/chapel-private/issues/3202; I was optimistically hoping it would "just work".
[trivial, urgent, not reviewed]
=> Remove -Og for CHPL_DEVELOPER builds with Clang

compiler/llvm/clangUtil.cpp
I started seeing a warning for a potentially uninitialized variable after PR #21434. This PR fixes the warning by initializing two pointer variables to `nullptr`.
=> Fix a GCC 12 warning that appears with -Og

.github/workflows/email.yml
Adding a polling interval to the retry.
https://github.com/Cray/chapel-private/issues/4149
We usually see timeouts if the git server is busy, the default retry polling wait is 1 sec, retrying every second will add more workload to already loaded system so increased the polling interval to 60 sec.
=> Add a polling interval in email workflow using polling_interval_seconds

modules/standard/BigInteger.chpl, test/deprecated/BigInteger/deprecatedInitializers.chpl, test/deprecated/BigInteger/deprecatedInitializers.good, test/library/standard/BigInteger/badFormat.chpl, test/library/standard/BigInteger/badFormat.compopts, test/library/standard/BigInteger/badFormat.good, test/library/standard/BigInteger/exponentiation.compopts, test/library/standard/BigInteger/fitsIntoMethod64.compopts, test/library/standard/BigInteger/modCorrectness.compopts, test/library/standard/BigInteger/testHash.compopts, test/library/standard/BigInteger/testOps.compopts, test/library/standard/GMP/congruence.compopts, test/library/standard/GMP/ferguson/gmp_dist_array.compopts, test/library/standard/GMP/ferguson/gmp_test.compopts, test/library/standard/GMP/ldelaney/gmp_Bigint_number_theoretic.compopts, test/library/standard/GMP/ldelaney/gmp_Bigint_record_constructors.compopts
Resolves #17686
Resolves Cray/chapel-private#4257
The old initializers were not in keeping with behavior we want -
library operations should not halt, and returning error codes
via out arguments (or otherwise) is a strategy we have stopped
following since the addition of proper error handling.
This PR adds a new initializer that will throw when the arguments
would not result in a proper `bigint`.  Since it has the same
arguments as the halting version, add a new `config` to control
which behavior is used.  This config is off by default, giving
users a deprecation message indicating that they will need to
adjust their code.
<details>
Note that since initializers can only call throwing functions now
rather than throwing themselves, this adds a private proc to
perform the `throw`.  This was …
=> Replace the bigint initializers that halt or return error codes with one that throws

test/library/packages/ProtobufProtocolSupport/EXECENV, test/library/packages/ProtobufProtocolSupport/anyRunner.skipif, tools/protoc-gen-chpl/Makefile
Previously, our protobuf support and tests assumed that protoc and other things were provided by a "system" install. Adjust them here to work in an environment where pkg-config provides paths (such as a spack installed env). Note that system installs still work, this just adds support for additional support for pkg-config .
Tested (ProtobufProtocolSupport tests pass) on:
- mac with brew install protobuf and pip installed python protobuf
- chapdl with spack install protobuf and py-protobuf
- chapcs with custom built protobuf and python protobuf
Tested (properly skipped or doesn't blow up) on:
- system without pkg-config
- system with pkg-config, but no protobuf
- system with protobuf, but no python protobuf
Part of Cray/chapel-private#4291
=> Enable pkg-config support for our protobuf tooling

test/errhandling/lydia/tryExpressionDefaultValue.bad, test/errhandling/lydia/tryExpressionDefaultValue.chpl, test/errhandling/lydia/tryExpressionDefaultValue.future, test/errhandling/lydia/tryExpressionDefaultValue.good
Tracks the extra error message I was seeing when a throwing function with a
complex default value is called in a try expression
A fresh checkout of the future behaved as expected.
=> Add future about extra message for try expressions around funcs with defaults

util/chplenv/third_party_utils.py
Modified `read_bundled_pkg_config_file` to also return the path to the pc file for use in subsequent warning messages.
=> Return pc path from read_bundled_pkg_config_file

make/compiler/Makefile.gnu
Remove `-Og` optimization flag from GCC builds which was added in https://github.com/chapel-lang/chapel/pull/21434.
Unfortunately it seems that `-Og` causes us to run afoul of a GCC implementation quirk/bug which spuriously warns of maybe-uninitialized variables when using specifically the `-Og` level of optimization, but not higher levels of optimization or no optimization. [Here](https://gcc.gnu.org/bugzilla/buglist.cgi?quicksearch=may%20be%20uninitialized) is a reference for GCC bugs with maybe-uninitialized warnings, and [this bug comment](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90710#c1) explains why this can happen for `-Og` specifically.
We considered the option of suppressing these warnings-as-errors with `-Wno-error=maybe-uninitialized` when using `-Og`, but this could …
=> Remove -Og for CHPL_DEVELOPER builds with GCC

compiler/passes/normalize.cpp, compiler/resolution/initializerResolution.cpp, test/classes/initializers/errors/errHandling/calls/tryBangExpression.chpl, test/classes/initializers/errors/errHandling/calls/tryBangExpression.good, test/classes/initializers/errors/errHandling/calls/tryBangExpressionDefault.chpl, test/classes/initializers/errors/errHandling/calls/tryBangExpressionDefault.good
Prior to this change, the compiler was not recognizing when
calls to throwing initializers were within `try!` expressions and
was incorrectly generating an error that they were not handled.
<details>
This was because both normalize and initializerResolution were
creating new calls and repopulating them, rather than copying
the original call or the fields associated with it.  This change
copies the tryTag field from the old calls to the new ones.
</details>
Adds two new tests that lock in:
- That you can call new for an initializer that throws in a try! expression
- That you can also do it if the initializer has a complicated default value
that involves a function call.
=> Fix a bug with calling throwing initializers in try! expressions

frontend/test/resolution/testMaybeConst.cpp
Follow-up to #21396 to address a warning-as-error
that occurs with clang when compiling with
make test-dyno WARNINGS=1
=> Remove an unused variable in a dyno test

test/studies/arkouda/sub_test, util/cron/common-arkouda.bash, util/cron/test-perf.cray-xc.arkouda.bash, util/cron/test-perf.cray-xc.arkouda.release.bash
In order to bring Arkouda testing more in line with the non-Arkouda XC testing, this PR adds an environment variable that allows you to opt out of graph generation.
=> Stop generating graphs for XC

compiler/parser/parser.cpp
Fixes an outdated invocation of AST dump method which does not compile.
This compilation failure likely hasn't been encountered thus far because it is guarded by a macro that must be manually set true for this to get compiled.
=> Fix AST dump invocation in uAST conversion

modules/standard/FileSystem.chpl, test/deprecated/deprecate-copyFile.chpl, test/deprecated/deprecate-copyFile.good, test/library/packages/HDF5/ex_lite2.chpl, test/library/packages/HDF5/readChunks1D.chpl, test/library/packages/HDF5/readChunks1DPreprocess.chpl, test/library/standard/FileSystem/copyFile/copyFile.chpl, test/library/standard/FileSystem/lydia/copyFile/copyingContents.chpl, test/mason/mason-modify/masonModifyTest.chpl, test/mason/masonAddBadDep.chpl
Add an argument 'permissions' to 'FileSystem.copy' that defaults to true to copy the file's permissions, but can be set to false to match the behavior of the old 'copyFile' function.
Deprecate 'copyFile' and update tests that used it. Add a deprecated/ test for 'copyFile'.
Closes https://github.com/chapel-lang/chapel/issues/19663
Closes https://github.com/Cray/chapel-private/issues/4273
=> Deprecate the FileSystem.copyFile function - use copy instead

frontend/include/chpl/framework/stringify-functions.h
dyno: Adjust dump methods to print to stdout and flush with newline
"Dump" methods (literally `foo->dump()`) were added to dyno as a
useful way of debugging AST, IR for Chapel types, meta-types, and
generally any C++ type that stores information used for compilation.
They are modelled after similar helper methods in LLVM.
For awhile now `dump()` has not functioned correctly when used with
the LLDB debugger. For one reason or another, the debugger REPL and
the output of a `dump()` call clash with each other, resulting in
mangled or missing output.
After getting fed up with things, I discovered that flushing the
channel is sufficient - but only if done by printing a newline.
While here, also make `dump()` print to `stdout` instead of `stderr`,
as the latter seemed a bit strange for …
=> dyno: Adjust dump methods to print to stdout and flush with newline

util/chplenv/compile_link_args_utils.py
We auto generate a header `chpl-env-gen.h` that defines macros named as the key/value pairs (separated by an underscore) for various CHPL_ environment variables (including CHPL_GPU_MEM_STRATEGY). Previously, we also passed in as a macro (with `-D`) `CHPL_GPU_MEM_STRATEGY_ARRAY_ON_DEVICE` when using the `array_on_device` memory strategy. These two approaches led to `CHPL_GPU_MEM_STRATEGY_ARRAY_ON_DEVICE` being defined multiple times.
To avoid this I've modified `chplenv/compile_link_args_utils.py` to not pass in this macro and instead rely on including and using the version passed in by `chpl-env-gen.h`.
=> Remove redundant redifinition of CHPL_GPU_MEM_STRATEGY_ARRAY_ON_DEVICE

test/gpu/native/array_on_device/studies/shoc/EXECOPTS, test/gpu/native/array_on_device/studies/shoc/GPU-COMPOPTS, test/gpu/native/array_on_device/studies/shoc/GPU-EXECOPTS, test/gpu/native/array_on_device/studies/shoc/result.chpl, test/gpu/native/array_on_device/studies/shoc/result.notest
In #21459 (adding nightly testing for array_on_device mode with GPU support) I added some symbolic links; these links should have used relative paths but I accidentally had them using absolute paths.  This PR updates this.
=> Fix symbolic links for array_on_device perf test

frontend/lib/parsing/ParserContextImpl.h, frontend/lib/resolution/Resolver.cpp, frontend/test/parsing/testParseAggregate.cpp, frontend/test/resolution/testMaybeConst.cpp, frontend/test/resolution/testMethodCalls.cpp
Prior to this commit, Dyno inserted an implicit `this` formal for all methods. For secondary methods, the type expression of this implicit formal was derived from the type expression in the user code. That is to say, the following secondary method:
```Chapel
proc (someTypeExpr).foo() {}
```
translated to the following:
```Chapel
proc foo(this: someTypeExpr) {}
```
In the case of primary methods, however, the type expression was simply the name of the class in which the method is being declared. For instance, the following:
```Chapel
record R {
proc foo() {}
}
```
becomes:
```Chapel
proc foo(this: R) {}
```
However, this led to problems in the case that a field of the record had the same name as the record itself. In these situations, the Dyno resolver would decide that `this` refers not …
=> Make primary method `this` formals not have type exprs.

frontend/include/chpl/framework/resolution-error-classes-list.h, frontend/lib/framework/resolution-error-classes-list.cpp, frontend/lib/resolution/Resolver.cpp, frontend/test/resolution/testFieldAccess.cpp
This wasn't considered an error in Dyno until this commit, but is an error in the production compiler's scope resolution. 
This adds another validation check to `validateAndSetToId` function.
=> dyno: throw errors when referencing fields of an outer class.

frontend/include/chpl/framework/mark-functions.h, frontend/include/chpl/framework/resolution-error-classes-list.h, frontend/include/chpl/resolution/scope-types.h, frontend/lib/framework/resolution-error-classes-list.cpp, frontend/lib/resolution/scope-queries.cpp, test/errors/fullImportPath-brief.good, test/errors/fullImportPath-detailed.good, test/errors/fullImportPath.chpl, test/errors/fullImportPath.compopts, test/errors/fullUsePath-brief.good, test/errors/fullUsePath-detailed.good, test/errors/fullUsePath.chpl, test/errors/fullUsePath.compopts, test/visibility/relative-use/relative-use-error2.chpl
The production compiler reports errors when you try to import or use a module that's not at the top level, or if you try to use an implicit relative import. It typically shows the name of the module, but points out that this module cannot be imported and recommends to use `super.M` or `this.M`. Dyno, however, at the moment simply reports that a module cannot be found. This PR adds an extra step that occurs if a module could not be found, which performs another search for that module name. This second search is more lax, and only serves to find possible candidates that the user _wanted_ to use or import, but was forbidden from importing by the `use`/`import` rules. These candidates are then printed as part of the error message, thus matching the production compiler's output (roughly).
The …
=> Add errors for explicit relative imports

util/chplenv/chpl_gasnet.py
This updates a use of `read_bundled_pkg_config_file` that
https://github.com/chapel-lang/chapel/pull/21482 missed.
This was the cause of CHAMPS testing failures last couple
of nights.
=> Fix a use of read_bundled_pkg_config_file

compiler/resolution/initializerResolution.cpp, test/classes/initializers/errors/errHandling/calls/tryBangExpressionDefaultRecord.chpl, test/classes/initializers/errors/errHandling/calls/tryBangExpressionDefaultRecord.good, test/classes/initializers/errors/errHandling/calls/tryBangExpressionRecord.chpl, test/classes/initializers/errors/errHandling/calls/tryBangExpressionRecord.good
I had only tested classes before, but the change I made earlier
didn't work for records.  Fix that oversight and verified that this
allowed me to remove the stdout and stderr workarounds in my
other branch.
Added a pair of the same tests but for records.  These tests
failed before and now work.
=> Fix try! expressions around new calls for records, too

compiler/AST/build.cpp, compiler/include/build.h, compiler/passes/convert-uast.cpp, frontend/test/resolution/testForwarding.cpp, test/classes/forwarding/forwarding-lambda-inner-record.chpl, test/classes/forwarding/forwarding-lambda-inner-record.good
This PR is intended to resolve some test failures with `--dyno` to activate the new scope resolver after PR #21470.
The approach is to separate the construction of the lowered forwarding method from the construction of the target for the forwarding expression. That way, it is possible to arrange for the forwarding method's `this` function to be used when converting a field access.
=> Fix forwarding after dyno scope resolution

test/studies/arkouda/sub_test
For Arkouda XC testing, we are switching to store data locally
and then collating the log files rather than writing directly
to the global file.
=> Switch Arkouda testing to generate graph files locally 

test/studies/arkouda/sub_test
This PR changes the path for the Arkouda perf data directory to be based off of ARKOUDA_HOME, rather than the CWD to make sure that we've got the path right.
=> Always create perf directory for Arkouda XC testing

test/studies/arkouda/sub_test, util/cron/common-arkouda.bash, util/cron/test-perf.cray-xc.arkouda.bash, util/cron/test-perf.cray-xc.arkouda.release.bash
This PR switches to making the data directory relative to the `WORKSPACE`, which is where Jenkins artifacts start their search, so that directory is needed to match with the location relative to the top level workspace, not `ARKOUDA_HOME`, which is located at `$CHPL_HOME/test/studies/arkouda/arkouda/` for XC testing currently.
=> Switch to storing data in workspace instead of Arkouda dir for XC testing

compiler/include/driver.h, compiler/llvm/clangUtil.cpp, compiler/main/driver.cpp, util/chpl-completion.bash
This includes a hack to strip out the debug directive from the generated PTX assembly file (since changing llvm::DIBuilder configuration causes segfaults inside LLVM for some reason). The implementation of stripping is probably not very efficient (it reads into memory, then writes back out; that helps avoid needing to use `mv` or the like, but how big does the assembly file get?).
Signed-off-by: Daniel Fedorin <daniel.fedorin@hpe.com>
Reviewed by @e-kayrakli - thanks!
=> (GPU) Force -O3 flag for ptxas when compiling --fast.

frontend/include/chpl/resolution/resolution-types.h, frontend/lib/resolution/call-init-deinit.cpp, frontend/lib/resolution/maybe-const.cpp, frontend/lib/resolution/resolution-types.cpp, frontend/lib/resolution/return-type-inference.cpp, frontend/test/resolution/CMakeLists.txt, frontend/test/resolution/testCallInitDeinit.cpp, frontend/test/resolution/testConstChecking.cpp, frontend/test/resolution/testForwarding.cpp, frontend/test/resolution/testLoopIndexVars.cpp, frontend/test/resolution/testMaybeConst.cpp, frontend/test/resolution/testOperatorOverloads.cpp, frontend/test/resolution/testTuples.cpp
This PR adjusts `maybe-const.cpp` to also include doing const checking after return intent overloading.
In order to support that:
* Adjusted functions that return by value to end up with a return type with kind `Qualifier::CONST_VAR` (instead of `Qualifier::VAR`). Generally speaking, the Chapel compiler does not allow a value returned by a function to be mutated. (The production compiler currently has an exception for arrays, where returning an array by value does return something mutable).
* Changed `call-init-deinit.cpp` to make `=` calls that are not split-init initializations resolve more normally instead of always resolving them as associated actions
While working in this area, I also shortened `AssociatedAction::kindToString` by using `return` within each case.
Future Work:
* Add …
=> dyno: draft const checking for the dyno resolver

test/studies/arkouda/sub_test
The Arkouda data files were being created in a `nightly` or `release` subdirectory under `dat-dir`, but for XC testing, since we are collating the data, rather than writing directly to the global file, we don't want that to be stored under a separate subdirectory.
=> Remove perf description for Arkouda XC graph generation

frontend/lib/resolution/VarScopeVisitor.cpp, frontend/lib/resolution/VarScopeVisitor.h, frontend/lib/resolution/call-init-deinit.cpp, frontend/lib/resolution/copy-elision.cpp, frontend/lib/resolution/split-init.cpp
Currently some logic in the standard library conditionally declares a variable depending on an input type. Something like:
```Chapel
proc f(type t) {
if isNumber(t) { return true; }
else {
var x: t;
// ...
}
}
```
Currently, Dyno fails to handle cases like these because it attempts to perform various analyses in the vein of copy elision, init-deinit, and others backed by `VarScopeVisitor`. However, some of these analyses require type information; they therefore require to know the type of `x` in the else branch, even if `isNumber(t)` is `param true`. However, the resolver does not visit `param false` branches, so this information is absent, and errors occur.
This PR therefore changes the behavior of VarScopeVisitor to skip param-elided branches, and therefore avoid requesting type …
=> Have VarScopeVisitor skip param-elided branches.

frontend/include/chpl/resolution/resolution-queries.h, frontend/lib/parsing/parsing-queries.cpp, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/Resolver.h, frontend/lib/resolution/default-functions.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/test/resolution/testDeprecationUnstable.cpp, frontend/test/resolution/testInteractive.cpp, frontend/test/test-common.h
dyno: Fix bugs with deprecation and unstable warnings
Fix a few bugs that were causing test failures when running tests
with the dyno scope resolver.
Add a query `isTypeDefaultInitializable` that is used to fix a bug
with initializers. The bug was screwing up unit tests.
The query is not complete and is missing some obvious logic like
returning `false` for non-nilable owned classes, or detecting when
a type's default initializer does not exist. I will improve it
in future efforts.
TESTING
=> dyno: Fix bugs with deprecation and unstable warnings

compiler/AST/foralls.cpp, test/parallel/forall/task-private-vars/tpv-no-init.chpl, test/parallel/forall/task-private-vars/tpv-no-init.good
Fix a missing space in the error message for not initializing a task-private variable. Also adds a simple test of the error message.
Observed while working on https://github.com/Cray/chapel-private/issues/2716.
Testing:
=> Fix typo in error message for uninitialized task-private variable

frontend/lib/resolution/Resolver.cpp
I didn't rebase onto the latest main and let a test failure slip through.
Fix the failure and clean up some complicated boolean logic by
moving expressions into local variables.
=> dyno: Fix CI test failure after #21529

modules/standard/CTypes.chpl
Replaces `c_sizeof(type x)` with `c_sizeof(type t)` and deprecates the former.
Deprecation is just to be safe in case anyone was using the formal name `x` to call this function.
Resolves https://github.com/Cray/chapel-private/issues/4222.
Testing:
=> Rename c_sizeof argument x->t and deprecate old version

frontend/include/chpl/resolution/scope-types.h, frontend/lib/resolution/call-init-deinit.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/lib/resolution/scope-types.cpp, frontend/test/resolution/testScopeResolve.cpp
This PR updates the dyno scope resolver to follow the current language design rules about shadow scopes. These evolved a bit after the dyno scope resolver was created (see PR #19306). See also [this spec section](https://chapel-lang.org/docs/language/spec/modules.html#using-and-importing).
To do so:
* added a field to `VisibilitySymbols` to indicate which shadow scope (if any) the use/imported symbols go into
* renamed `doLookupInImports` to `doLookupInImportsAndUses` and have it only consider symbols at the current shadow scope level
* created `doLookupInAutoModules` (pulled out of `doLookupInImports`)
* adjusted `doLookupInScope` to check the non-shadow scope and then the two shadow scopes
* adjusted `doResolveUseStmt` and `doResolveImportStmt` to provide a shadow scope value when …
=> dyno: handle shadow scopes for 'private use'

util/buildRelease/smokeTest
Recently, I observed a CI failure where the only failure output was this:
```
Checking for tabs
Checking for trailing spaces
Error: Process completed with exit code 1.
```
I eventually determined that my PR added a trailing space. However, we would like `smokeTest` to print out the failing lines. The reason that it did not is that this script is running with `set -e`, which makes the script exit before it has a chance to print out the captured output from `util/devel/lookForTrailingSpaces`.
So, this PR adjusts the invocations of `lookForTabs` and `lookForTrailingSpaces` to not capture their output, so the problematic lines will be clear in CI testing.
When I add a tab somewhere, the smoke test output looks like this:
```
Checking for tabs
compiler/AST/view.cpp:1435:     return …
```
=> Adjust smoke test to print out lines with tabs/spaces

compiler/main/version.cpp, compiler/resolution/preFold.cpp, frontend/include/chpl/util/version-info.h, frontend/lib/util/version-info.cpp, tools/chpldoc/chpldoc.cpp, util/buildRelease/gen_release
This PR fixes a bug in `gen_release` that would prevent building
from a non-local repo. There are some other fixes for carrying the
git SHA forward from the source when using `gen_release` to build
from a remote repo. 
The major change is and update to `gen_release` to explicitly copy 
the generated files that contain the git SHA, `git-version.cpp` and
`BUILD_VERSION`. This is to fix a bug that always forced the dummy 
SHA if not using the local git repo with `CHPL_GEN_RELEASE_NO_CLONE`
This bug was introduced in https://github.com/chapel-lang/chapel/pull/20920.
The first deviation from previous behavior in `gen_release` is that we will include the
git SHA in the tarball regardless of how `gen_release` was called. This will place
all of the decision of whether to print a git `SHA` from …
=> fix(release): copy generated files that contain SHA value into archive

doc/rst/language/spec/data-parallelism.rst
Fixes an invalid link under [Reductions and Scans](https://chapel-lang.org/docs/1.29/language/spec/data-parallelism.html#reductions-and-scans) to the page on [User-Defined Reductions and Scans](https://chapel-lang.org/docs/1.29/language/spec/user-defined-reductions-and-scans.html#chapter-user-defined-reductions-and-scans).
=> Fix a docs link to user-defined reductions page

test/library/packages/HDF5.skipif, test/library/packages/HDF5/COMPOPTS, test/library/packages/HDF5/EXECENV
Add a COMPOPTS to set include directories and lib directories for HDF5 and add -lhdf5 to the compile command.
Add an EXECENV to set the LD_LIBRARY_PATH for HDF5.
Update the directory-wide .skipif file to make it work with both XC systems and chapdl.
=> Add COMPOPTS and EXECENV for HDF5 tests

runtime/include/chpl-gpu-impl.h, runtime/include/chpl-gpu.h, runtime/include/chpl-mem-array.h, runtime/src/chpl-gpu.c, runtime/src/gpu/cuda/gpu-cuda.c, runtime/src/gpu/rocm/gpu-rocm.c
Page-locking memory can lead to better data-transfer performance in CUDA. This PR page locks memory for all arrays allocated on the host when using the `array_on_device` memory strategy.
See https://developer.nvidia.com/blog/how-optimize-data-transfers-cuda-cc/ or https://stackoverflow.com/questions/5736968/why-is-cuda-pinned-memory-so-fast for more information
This change seems to work fine and improve performance with my limitted testing of it.
I think it makes sense to try and merge https://github.com/chapel-lang/chapel/pull/21459 (which adds a nightly performance test for array_on_device mode) first so we can see that it makes a change in our performance graphs.
=> Page-lock arrays allocated on host in array_on_device mode

modules/standard/GPU.chpl, runtime/include/chpl-gpu-impl.h, runtime/include/chpl-gpu.h, runtime/src/chpl-gpu.c, runtime/src/gpu/cuda/gpu-cuda.c, test/gpu/native/array_on_device/studies/shoc/triadAodAsync.chpl, test/gpu/native/array_on_device/studies/shoc/triadAodAsync.compopts, test/gpu/native/array_on_device/studies/shoc/triadAodAsync.good, test/gpu/native/array_on_device/studies/shoc/triadAodAsync.gpu-keys, test/gpu/native/array_on_device/studies/shoc/triadAodBw1.graph, test/gpu/native/array_on_device/studies/shoc/triadAodBw2.graph
This PR:
* adds a couple of functions to the GPU module that can be used to perform asynchronous communication: `asyncGpuComm` and `gpuCommWait`
* adds a version of the `array_on_device` version of SHOC triad that uses these new functions
For the time being I no doc these functions as we may wish to change their design in the near future. Nevertheless I'd like to have this feature submitted so that we have some groundwork set and can explore its impact on performance.
=> Add async comm functions to GPU module

modules/standard/Map.chpl, test/deprecated/Map/testGetRemove.good, test/library/draft/DistributedMap/v2/use-distributed-map.bad, test/library/standard/Map/testGetRemove.chpl
With the removal of `getAndRemove` in #21549, there was a test 
failing dueto a borrow of the class going invalid after the map 
value was removed, so this updates that to use the `get` method 
instead, which creates a deep copy. Additionally, a `.bad` file
for a gasnet test needed updating for line numbers.
=> Fix failing map tests and update getAndRemove deprecation message

.github/workflows/email.yml
1. Merge log. 2. correct diff 3. use text body instead of html
Will address 
https://github.com/Cray/chapel-private/issues/4305
1. Fix merge log:
Existing git actions extracted git log from the pull_request_target body which does not seem to reflect the merge log.
The fix is to get the merge log using
' merge_log=$(git show -s --format=%B ${{github.event.pull_request.merge_commit_sha}}) '
The above git command will get the merge log for the specific merge commit sha. 
--format=%B will remove the --diff details that follows the merge messages.
2. Use text body instead of html
There is an issue with discourse where html body is not honored so the  html linefeeds  inside the body is not honored and the log message was squashed.
Use plain body instead of html_body to resolve the issue.
3 . …
=>  Fixed git actions. 

modules/internal/SharedObject.chpl, test/classes/weakPointers/initWeakPtr.chpl
Fixes a bug where the `weakPointer` prototype's cast to a non-nilable `shared` was not working for non-default initializable types.
Also corrects indentation in sharedObject.chpl.
Testing:
=> `weakPointer` bug fix

test/library/packages/FFTW/guru-interface-example.chpl, test/library/packages/FFTW/guru-interface-example.good
The test guru-interface-example.chpl creates a temp negative-stride array when calling reshape(), in order to reverse the order of elements of a unit-stride array and store the result in another unit-stride array.
This PR adjusts its .good to account for the warning about the negative stride that is now issued due to #21496, the same way I adjusted other tests in that PR.
=> Adjust .good for negative stride

.github/workflows/email.yml
Email workflow cleanup.
The existing workflow is getting the author name from commits.json. There are issues when the author and the person merging the PR is different. The email prints the person merged the PR as author.
Fix that by using actor from the pull_request.
Diff is calculated usinf merge_commit_sha and head_sha(head of main) this will work if the branch is rebased with main before merging.
Use base_sha of the branch to get the diff instead and see if it works.
Please note that it cannot be tested using the [test repository
] (https://github.com/bhavanijayakumaran/workflow)  as I am the only user and there is no easy way to simulate the scenario.
=>  Fix Author and diff url

Dockerfile
Adds support for using the C backend (in addition to currently-supported LLVM backend) in the Docker image.
This is accomplished by building Chapel with `CHPL_TARGET_COMPILER` having each value of `{gnu, llvm}`. The runtime and some third-party support code is rebuilt to accomplish this, mildly increasing the size and complexity of the image.
The `chpldoc`, `test-venv`, and `mason` targets are not rebuilt as I consider them unlikely to be behave differently with different target compilers.
Resolves https://github.com/chapel-lang/chapel/issues/21448.
Testing:
=> Build Docker image for multiple backends

compiler/passes/convert-uast.cpp, frontend/include/chpl/resolution/resolution-queries.h, frontend/include/chpl/resolution/resolution-types.h, frontend/include/chpl/resolution/scope-queries.h, frontend/include/chpl/resolution/scope-types.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/Resolver.h, frontend/lib/resolution/call-init-deinit.cpp, frontend/lib/resolution/copy-elision.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/resolution-types.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/lib/resolution/scope-types.cpp, frontend/test/resolution/testDeprecationUnstable.cpp, frontend/test/resolution/testMethodFieldAccess.cpp
This PR includes changes to fix the following tests when running with `--dyno`:
classes/diten/nesting_with_inheritance.chpl
reductions/thomasvandoren/test/TestScanCounts.chpl
reductions/thomasvandoren/test/TestScanCountsInherit.chpl
The `scan` tests are fixed through a bug fix for `Converter::noteAllContainedFixups` in `convert-uast.cpp`. That function does not visit nested functions (because they should be handled as separate symbols). However, converting a scan expression generates an special inner function that wasn't being visited by the traversal to note a contained TemporaryConversionSymbol for later fixup. Use the fact that such generated functions are marked with `FLAG_COMPILER_NESTED_FUNCTION` to address the issue. To help debugging such errors in the future, this PR includes …
=> dyno scope resolver: fix three more failing tests

modules/standard/FileSystem.chpl, test/library/standard/FileSystem/copyTree/copyRootMetadataBadPerms.chpl, test/library/standard/FileSystem/copyTree/copyRootMetadataBadPerms.cleanfiles, test/library/standard/FileSystem/copyTree/copyRootMetadataBadPerms.good, test/library/standard/FileSystem/copyTree/copyRootMetadataBadPerms.skipif
If the 'metadata' argument is true, copy the UID and GID from the original directory.
When copying files, forward the 'metadata' argument to 'copy'.
Add a test that tries to copy a directory owned by root with metadata=true. Since that's not allowed as a non-root user it expects and gets a Permission error.
I also tested a modified version of this test that prints the UID and GID of the copied directory and ran it with 'start_test --launchcmd fakeroot' and verified that the UID and GID of the copy were both 0 (root).
Closes https://github.com/chapel-lang/chapel/issues/19664
Closes https://github.com/Cray/chapel-private/issues/4304
=> Add a 'metadata' argument to 'copyTree'

test/library/packages/ProtobufProtocolSupport/endToEndRunnerUtils.chpl, test/mason/mason-external/masonExternalRanges/COMPOPTS, test/mason/mason-external/masonExternalRanges/mason-external-range.compopts
A few tests that were only running in specific configurations were failing after adding the `mapMethodsThrow` deprecation message, so this PR fixes that.
=> Fix failing protobuf test after map deprecations

doc/rst/language/spec/procedures.rst
This sentence is referring to procedures with ref or const ref intents as requiring an lvalue be returned, so update it to say that.
=> Drop outdated reference to variable procedures from spec procedures.rst

modules/internal/Bytes.chpl, modules/internal/BytesStringCommon.chpl, modules/packages/Sort.chpl, modules/standard/Random.chpl
This PR drops `no doc`ed `type idxType` from the Bytes module.
It has no clear purpose and currently seeps into user's namespace.
Test
=> Remove idxType from Bytes

util/packaging/docker/gasnet-smp/Dockerfile, util/packaging/docker/gasnet/Dockerfile
Follow up to https://github.com/chapel-lang/chapel/pull/21538, which just made this change for the main Dockerfile. Prior to these changes, building gasnet or gasnet-smp images from the new Chapel image gave us both backends for `CHPL_COMM=none` but only `llvm` backend for `CHPL_COMM=gasnet`.
Related to https://github.com/chapel-lang/chapel/issues/21448.
No further testing is done for this as it is covered by 1) the testing done for identical changes in https://github.com/chapel-lang/chapel/pull/21538 and 2) validation to be done before the new images are pushed.
=> Build both backends for gasnet and gasnet-smp images

frontend/include/chpl/framework/ErrorWriter.h, frontend/include/chpl/framework/resolution-error-classes-list.h, frontend/lib/framework/resolution-error-classes-list.cpp, frontend/lib/resolution/scope-queries.cpp, test/errors/fullImportPath-brief.good, test/errors/fullImportPath-detailed.good, test/errors/fullUsePath-brief.good, test/errors/fullUsePath-detailed.good, test/errors/useImportUnknownMod-brief.good, test/errors/useImportUnknownMod-detailed.good, test/errors/useImportUnknownSym-brief.good, test/errors/useImportUnknownSym-detailed.good
A few minor things in here to make the error messages better.
1. Deprecation and unstable warnings now print their text verbatim, without mangling punctuation. It seems to make sense to forward what the user wrote in the "deprecated" attribute directly rather than possibly surprising them by changing it.
2. Tweak the wording of some module-related errors (`cannot 'import' 'bla'` => `cannot 'import' symbol 'bla'`, `cannot find module or 'enum' 'bla' for 'import'` => `cannot find module or enum named 'bla'`)
3. Print what module was searched when unable to find an import (i.e., `could not find N in M` vs previous `could not find N`).
Reviewed by @benharsh and @riftEmber - thanks!
=> Changes to scope resolver errors to prepare for full `--dyno`-by-default switch.

compiler/passes/convert-uast.cpp
Resolves a failure with --dyno scope resolving
visibility/submodule-in-file/errors/DoubleNested
=> Adjust convert-uast for module include

test/library/standard/FileSystem/copyTree/copyRootMetadataBadPerms.chpl, test/library/standard/FileSystem/copyTree/copyRootMetadataBadPerms.cleanfiles, test/library/standard/FileSystem/copyTree/copyRootMetadataBadPerms.good
This test used the same directory name as another test and so failed with a "directory already exists" error. Update it to use a different directory name.
=> Fix a test with a filename collision

compiler/AST/ImportStmt.cpp, compiler/AST/UseStmt.cpp, frontend/include/chpl/framework/resolution-error-classes-list.h, frontend/lib/framework/resolution-error-classes-list.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/test/resolution/testScopeResolve.cpp
The production compiler reports when a user tries to rename a variable twice in an import list:
```Chapel
import M.{a as b, b as c}
```
The result of the above import is _not_ an import of `a as c`, but rather, `M.a` being imported as `b` and `M.b` being imported as `c` (if it exists). The warning is thus issued to help users diagnose `M.b not found` if they intended the import to work in the former way.
```
renameChain.chpl:5: warning: identifier 'bar' is repeated
note: Did you mean to rename 'foo' to 'baz'?
renameChain.chpl:5: error: Bad identifier in rename, no known 'bar' in 'M'
```
Dyno didn't have this functionality, or indeed any `as`-validation functionality. This PR adds this, by modifying `convertLimitations` to validate each additional limitation against preceding ones. This …
=> Dyno scope resolver: chain rename and other `as`-related warnings.

doc/rst/language/spec/error-handling.rst
This PR fixes the formatting of `try!` in the error-handling portion
of the language specification docs.
Previously, the bang was placed outside of the format indicators, so
it read like `try`! in the docs. This PR moves the bang inside the format
so it reads like `try!`
TESTING:
reviewed by @dlongnecke-cray - thank you!
=> fix(docs): add formatted bang as part of `try!` symbols

util/cron/test-networking-packages.bash
Fixes a few lines and adds a cleanup command in nightly test script for HDFS tests
nightly HDFS tests failed with
```
RemoteException: Permission denied: user=chapelu, access=WRITE, inode="/tmp":abrahaja:supergroup:drwxr-xr-x
```
This was caused by manual testing of the HDFS leaving behind files. These left behind files (/tmp/lots-of-numbers.txt and /tmp/testfile.txt) where owned by the user `abrahaja`. When the nightly test then tried to overwrite these files as user `chapelu`, the tests failed with the above permission issues. This is manually fixed by just deleting the files, but adding them to the testing script will hopefully prevent these issues in the future.
- make existing code more user agnostic
- fix typo that was erroring
- add cleanup of `/tmp`
- tested manually
- will watch …
=> Add fixes to prevent permissions errors with nightly HDFS

frontend/include/chpl/framework/resolution-error-classes-list.h, frontend/lib/framework/resolution-error-classes-list.cpp, frontend/lib/resolution/scope-queries.cpp
This is intended to resolve a failure with `--dyno` with the test
modules/lydia/fnModNameConflict2
It adds an error for the case that a use/import statement can refer to multiple things. (PR #20866 added an assertion instead of an error for this case).
Example error messages:
```
$ chpl test/modules/lydia/fnModNameConflict2.chpl --dyno --detailed-errors
─── error in test/modules/lydia/fnModNameConflict2.chpl:14 [AmbiguousIdentifier] ───
'M1' is ambiguous
|
14 |   use M1;
|       ⎺⎺
|
It could refer to this 'M1'
|
3 |   proc M1() {
|        ⎺⎺
|
Or it could refer to this 'M1'
|
7 |   module M1 {
|   ⎺⎺⎺⎺⎺⎺⎺⎺⎺
|
```
```
$ chpl test/modules/lydia/fnModNameConflict2.chpl --dyno 
test/modules/lydia/fnModNameConflict2.chpl:1: In module 'OuterModule': …
```
=> Add error for ambiguous use

test/ANNOTATIONS.yaml
According to the YAML spec it's not legal to have duplicate keys, but PyYAML silently ignores (last entry wins) due to issues with detecting duplicates coming from of merge keys.
Without removing support for merge keys, I don't see a good way to check for duplicates ourselves, so just remove the ones we have (found with a custom loader and manually removing merge keys to avoid false-positives)
=> Fix duplicate annotation keys

frontend/lib/resolution/Resolver.cpp, frontend/test/resolution/testTaskIntents.cpp
Type resolve shadow variable in reduce intents, and improve resolution testing for reduce and task/loop intents.
Type resolution for task/loop intents besides reduce intents was already implemented, so the main thing this PR adds is resolution for reduce intents.
Type resolution of `in` intents where type can change, such as array slices, is not implemented in this PR.
Resolves https://github.com/Cray/chapel-private/issues/2716.
Testing:
=> Resolve task/loop intents in Dyno

compiler/resolution/functionResolution.cpp, modules/packages/Channel.chpl, test/classes/initializers/initequals/changing-param-field.chpl, test/constrained-generics/basic/set2/record-instantiations.chpl, test/library/draft/DistributedMap/v2/DistributedMap.chpl, test/library/draft/DistributedMap/v3/DistributedMap.chpl, test/library/standard/List/initEquals/list-init-eq-many.chpl, test/types/partial/bad-managed-init.chpl, test/types/partial/default-init-generic2.chpl, test/types/partial/inOrder.chpl, test/types/partial/inheritance.chpl, test/types/partial/initeq.chpl, test/types/partial/invalid-set-param-again-type-ctor.chpl, test/types/partial/isFieldBound.chpl, test/types/partial/managed-alias.chpl, test/types/partial/outOfOrder.chpl, test/types/partial/owned-shared.chpl, test/types/partial/partial-no-q-warning.chpl, test/types/partial/partial-no-q-warning.good, test/types/partial/partial-type-alias-generic.chpl, test/types/partial/partialIsSubtype.chpl, test/types/partial/partialTypeFormal.chpl, test/types/partial/partialTypeFormal.error.good, test/types/records/generic/partial-instantiation-equivalence.chpl
This PR is intended to resolve #18665. It adds a warning for partial instantiations that do not include a `?` argument.
Chapel supports partial instantiations when some, but not all, arguments are provided to the type constructor for a generic type. So, partial instantiations are generic (vs complete instantiations which are concrete). Partial instantiations are described in the technote: https://chapel-lang.org/docs/technotes/partialInstantiations.html
Now, a partial instantiation can end with `?` to indicate "the rest is generic". This syntax can also be useful when working with a type with generic defaults. For example, `range(?)` refers to a generic type but `range` refers to the type with the defaults applied (although we are thinking of changing that).
At the same time, it has come …
=> Warn for partial instantiations without '?'

test/release/examples/primers/classes.chpl
Adds variable highlighting that was missing for a few lines in classes primer docs.
Tested locally with `make docs`
=> Source code formatting in docs for classes primer

compiler/resolution/functionResolution.cpp, modules/standard/IO.chpl, test/deprecated/IO/channel-writebits.catfiles, test/deprecated/IO/channel-writebits.chpl, test/deprecated/IO/channel-writebits.cleanfiles, test/deprecated/IO/channel-writebits.good, test/deprecated/IO/specailWritersReturnErrorMessage/wrbWritebits.chpl, test/deprecated/IO/specailWritersReturnErrorMessage/wrbWritebits.good, test/exercises/Mandelbrot/MPlot.chpl, test/exercises/c-ray/Image.chpl, test/io/ferguson/bits-errors.big-writebits.good, test/io/ferguson/bits-errors.chpl, test/io/ferguson/bits-errors.negative-writebits.good, test/io/ferguson/bits-signed.chpl, test/io/ferguson/bits64error.chpl, test/io/ferguson/easybits.chpl, test/release/examples/primers/fileIO.chpl
Based on discussion,`channel.writeBits` has been renamed to `fileWriter.writeBits`.
- The renamed function also had some argument names and types changed.
```chapel
proc fileWriter.writeBits(x:integral, numBits:int):void throws
```
- `channel.writeBits` has been deprecated and now points to fileWriter.writeBits
- All modules/tests using `channel.writebits` have been updated to the new name
- a new deprecation test for `channel.writebits`.
- ran full paratest
- clicked through the docs to make sure they are still correct
Closes #19491 
Closes Cray/chapel-private#4351
=> Refactor channel.writebits to fileWriter.writeBits

modules/packages/EpochManager.chpl, test/library/draft/DistributedMap/v2/use-distributed-map.bad
In #21586 I introduced a usage of ``fileReader`` without use-ing the IO module. Testing didn't pick this up due to some prediffs. This PR inserts the correct ``use`` and fixes a line number in a .bad file.
=> Testing fixes for EpochManager 

util/cron/test-networking-packages.bash
Adds a permission change for the root directory to the currently running user. This should prevent further permissions issues with the nightly testing, as well as be more robust against local testing.
After watching the tests over a few days, the problem does seem to now be fixed. Changing the ownership of the DFS root node to the current user allows the tests to run. The fix to the script should allow users to run the tests manually without disturbing the nightly environment
=> additional fix for hadoop nightly tests

runtime/include/tasks/qthreads/chpl-tasks-impl-fns.h, runtime/src/tasks/qthreads/tasks-qthreads.c
Since #19804, `--memTrack` calls `chpl_task_getRequestedSubloc`. Under qthreads this calls `chpl_qthread_get_tasklocal`, which only works when qthreads is initialized. This was coded to work before qthreads was initialized, but wasn't expecting to be called after qthreads had been deinitialized and #19804 resulted in these functions getting called after qthreads deinit. Fix that here by marking that qthreads is no longer initialized in a way `chpl_qthread_get_tasklocal` already checks.
Resolves Cray/chapel-private#3417
=> Fix `--memTrack` under qthreads

modules/standard/IO.chpl, test/deprecated/IO/ioBits.chpl, test/deprecated/IO/ioBits.good, test/io/ferguson/io_test.chpl, test/io/jade/readWriteBits.chpl
Based on discussion, deprecates externally facing `ioBits` in favor of `readBits`/`writeBits`
- rename `ioBits` to `_internalIoBits`
- make `ioBits` a type alias and deprecate the type
- rename all internal uses to new name
- deprecation test for `ioBits`
- move `ioBits` test from generic `io_test` to its own test with `readBits` and `writeBits`
- ran full paratest
- clicked through the docs to make sure they are still correct
Closes #20258 
Closes Cray/chapel-private#4364
=> Deprecate ioBits in favor of readBits/writeBits

modules/standard/IO.chpl, modules/standard/Subprocess.chpl, test/library/standard/IO/initWithCFile/errorCase.chpl, test/library/standard/IO/initWithCFile/openCFile.chpl
Resolves #20430 
Resolved Cray/chapel-private#4374
This changes gathers several updates to the file initializers into one
place.  Those updates include:
- Rename the fd argument, as decided
- Use `int` instead of `c_int` for the argument type
- add new `own` argument and use it instead of `QIO_HINT_OWNED`
Update places that were using `QIO_HINT_OWNED` outside of the
`IO` module to use the new argument instead, except for the
deprecation test of `openfp` because we haven't added the argument
to the deprecated function and don't intend to.
=> Updates to file initializers replacing openfp and openfd

modules/standard/Map.chpl, test/classes/weakPointers/passiveCache.chpl, test/unstable/Map/COMPOPTS, test/unstable/Map/parSafe.chpl, test/unstable/Map/parSafe.good
`parSafe` is being marked unstable for map since the decision has
not been made how to handle `parSafe` with the new distributed map
implementation. The `init` procs have now been duplicated, with
one having a `parSafe` argument with no default so, if a map is
attempted to be created setting `parSafe`, only at creation will
an unstable warning be issued.
=> Mark 'Map.parsafe' unstable

modules/standard/Map.chpl, test/unstable/Map/mapIterators.chpl, test/unstable/Map/mapIterators.good
As discussed in #14718, what we would like both `Map.these()` and 
`Map.items()` to yield would be tuples of `(key, value)` pairs 
with return intent of `(const ref, ref)`, but, since that is not 
possible today, we are marking them both as unstable until the 
ability to return with the correct intent is enabled in Chapel.
=> Mark 'Map.these' and 'Map.items' as unstable 

util/cron/publish-docker-images.bash
Problem : On demand docker publish is not recognizing the command line parameter referenced by $n 
Fix: Use the jenkins $parametername instead of  $n
=> fix the script to use jenkins parameter name instead of param location

runtime/src/qio/qio.c
The mark stack starts off pointing to a fixed-size c array, but can later be allocated or reallocated when the stack size increases. Somehow this hasn't bitten us in testing before, and so it was never large enough to be resized, and so was never leaked.
Testing:
=> QIO fix: Free the mark stack if it has been allocated
