modules/packages/TOML.chpl, modules/standard/Regex.chpl, test/deprecated/regexSubSubn.chpl, test/deprecated/regexSubSubn.good, test/regex/correctness.chpl, test/regex/emptyregex.chpl, test/regex/ferguson/regex-no-leak.good, test/regex/ferguson/regexp.chpl, test/regex/ferguson/regexp.good, test/regex/localFastPath.chpl, test/regex/nullByteBug.chpl, test/regex/replaceAndCount.chpl, test/regex/replaceAndCount.execopts, test/regex/replaceAndCount.good, test/regex/replaceAndCountPerf.chpl, test/regex/replaceAndCountPerf.good, test/release/examples/benchmarks/shootout/regexdna-redux.chpl, test/release/examples/benchmarks/shootout/regexdna.chpl, test/studies/shootout/regex-dna/bharshbarg/regexdna.chpl, test/studies/shootout/regexdna-redux/engin/regexredux.chpl, test/studies/shootout/submitted/regexredux2.chpl, test/studies/shootout/submitted/regexredux2.good, test/studies/shootout/submitted/regexredux3.chpl
With this PR a new `doReplaceAndCount` internal helper will handle all the regex-based replacement. This function chooses between `doReplaceAndCountSlow` and `doReplaceAndCountFast` implementations. The latter is pretty much the same as the current `regex.subn` implementation. The former allows arbitrary `count`s to be passed to match `string.replace(string,count=-1)` interface. This implementation can't fully rely on RE2, so it does its own bookkeeping. In quick performance tests, I observed this function to perform 10% slower compared to the other one when both of them are doing the same effective operation.
Resolves https://github.com/chapel-lang/chapel/issues/19079
Test:
=> Deprecate `regex.sub/subn` in favor of `replace` and `replaceAndCount` on `string` and `bytes`

test/GRAPHFILES, test/arrays/elliot/arrayInitDeinitPerf.chpl, test/arrays/elliot/arrayInitDeinitPerf.execopts, test/arrays/elliot/arrayInitDeinitPerf.graph, test/arrays/elliot/arrayInitDeinitPerf.perfkeys
Add a performance test to track deinit times for array-of-arrays and array-of-records (with alloc/dealloc). This is meant to track the impact of an upcoming patch to parallelize array deinitialization.
Part of #15215
=> Add array deinit perf test

test/studies/shootout/submitted/regexredux3.chpl, test/studies/shootout/submitted/regexredux3.good
I changed a `submitted` implementation of a shootout in https://github.com/chapel-lang/chapel/pull/21600. This reverts the change and updates the good file instead.
Thanks @lydia-duncan for noticing it.
=> Revert changes to a submitted shootout, update good file instead

frontend/lib/resolution/scope-queries.cpp, frontend/test/resolution/testMethodFieldAccess.cpp
This PR fixes a bug in the dyno scope resolver where, if there is enough nesting, a field with the same name as a local variable was preferred to a local variable.
To fix it, this PR:
* factors out lookup in receiver scopes to a helper `doLookupInReceiverScopes` and lookup in parents of receiver scopes to the helper `doLookupInReceiverParentScopes`
* looks in receiver scopes just after the declarations / use import handling for a method scope
* when considering parent scopes, if we arrive at a method scope, look in receiver scopes just after the declarations / use import handling for that parent scope. The key change here is that the check for declarations in a parent scope *does not* also check receiver scopes.
=> Fix a bug in dyno scope resolver

doc/rst/usingchapel/debugging.rst
Adds note about lldb flag to existing debugging documentation
Tested `make docs` to ensure formatting was correct
=> Update debugging documentation with lldb information

compiler/util/misc.cpp, test/constrained-generics/basic/generic/ic-req-function.bad, test/constrained-generics/basic/set3/hashtable-table.bad, test/expressions/loop-expr/ifExprWithForallBug.bad, test/extern/ferguson/bug-global-c-array.bad, test/extern/ferguson/mismatch-errors/mismatch-ri-iv.bad, test/extern/ferguson/mismatch-errors/mismatch-riv-iv.bad, test/functions/bradc/paramThis/funParamThis3.bad, test/functions/iterators/bradc/captureEmpty.bad, test/functions/iterators/errors/mistakenIteratorShape.bad, test/functions/iterators/recursive/recursive-iter-yield-recursive-iter.bad, test/functions/promotion/declareVarFromPromotedType.bad, test/library/standard/Map/types/ClassWithMapWithRecord.bad, test/parallel/taskPar/taskIntents/inCopyPassedToRef.verify.bad, test/reductions/classes/classReduction.bad, test/reductions/vass/reduce-of-more-promoted.bad, test/studies/shootout/reverse-complement/bradc/revcomp-blc-begin-const-ref.verify.bad, test/studies/shootout/reverse-complement/bradc/revcomp-blc-copyPropBug.bad, test/studies/shootout/reverse-complement/bradc/revcomp-dowhile-bug.bad, test/types/enum/lydia/declaredInClass-initializer.bad, test/types/records/tupleFields/detupleFieldDecl.bad, test/types/tuple/errors/tuple-init.bad, test/types/tuple/heterogeneous/loops/varargsHetTuple.bad, test/types/tuple/split-init/multipleInit.bad, test/types/tuple/these/iterHetTupleArg.bad, test/users/engin/retInnerFunction.bad, test/users/vass/uniquify/u1-local-user-extern.bad, test/users/vass/uniquify/u2-local-extern-extern.bad
Removes the parenthetical "It's us, not you" from our internal error message.
Resolves https://github.com/Cray/chapel-private/issues/4144.
Testing:
=> Remove 'It's us, not you' from internal error message

test/ANNOTATIONS.yaml, util/test/perf/perfgraph.js
Historically annotations have just linked to PRs responsible for changes, but sometimes performance changes from other factors and it can be nice to link to issues that contain more detail. Add support for that here.
=> Add support for linking annotations to private issues

third-party/gmp/README, third-party/gmp/gmp-src/mpn/arm64/aors_n.asm, third-party/gmp/gmp-src/mpn/arm64/aorsmul_1.asm, third-party/gmp/gmp-src/mpn/arm64/aorsorrlshC_n.asm, third-party/gmp/gmp-src/mpn/arm64/cnd_aors_n.asm, third-party/gmp/gmp-src/mpn/arm64/logops_n.asm, third-party/gmp/gmp-src/mpn/arm64/lshift.asm, third-party/gmp/gmp-src/mpn/arm64/lshiftc.asm, third-party/gmp/gmp-src/mpn/arm64/mul_1.asm, third-party/gmp/gmp-src/mpn/arm64/rsh1aors_n.asm, third-party/gmp/gmp-src/mpn/arm64/rshift.asm, third-party/gmp/gmp-src/mpn/arm64/sqr_diag_addlsh1.asm
Pull in an upstream GMP patch to avoid using register 18 on ARM, since that's not supported on arm based macs. Technically, register 18 was always reserved on arm based macs, but only with recent OS versions has it actually become an issue. Pull in the upstream patch that uses other register to fix this.
Verified that this fixes GMP builds on an M1 mac running Ventura 13.2.1
Related to Cray/chapel-private#4289
=> Fix GMP support on recent ARM macs

util/chplenv/chpl_gmp.py
`CHPL_TARGET_PLATFORM=aarch64` was a temporary name for ARM on Cray XCs, which has since become just Cray XC with `CHPL_TARGET_ARCH=arm64`. This vestige should have been removed in 641c143850, but I missed it then.
Closes Cray/chapel-private#4289
=> Remove old support `CHPL_TARGET_PLATFORM=aarch64` from gmp chplenv

compiler/AST/ForallStmt.cpp, compiler/AST/build.cpp, compiler/include/build.h, frontend/include/chpl/framework/parser-error-classes-list.h, frontend/lib/framework/parser-error-classes-list.cpp, frontend/lib/uast/post-parse-checks.cpp, test/errors/parsing/controlFlow-brief.good, test/errors/parsing/controlFlow-detailed.good, test/errors/parsing/controlFlow.chpl, test/errors/parsing/controlFlow.compopts, test/functions/iterators/bharshbarg/moduleYield.good, test/parallel/begin/deitz/test_control_flow.good, test/statements/bharshbarg/breakOutsideOfLoop.good, test/statements/sungeun/bad_break.good, test/statements/sungeun/bad_continue.good, test/statements/sungeun/bad_label.good, test/trivial/deitz/statements/return_error.good, test/trivial/dinan/bad_return.good, test/trivial/vass/error-return-at-top-level.good, test/trivial/vass/error-yield-at-top-level.good
Control-flow checks are syntactic, and are pretty easy to get working with Dyno. Furthermore, we can do them in a single traversal by keeping track of a stack of control-flow nodes (already accessible via `post-parse-checks.cpp`'s `Visitor`), instead of collecting ASTs every time a new loop is built. This also helps address the case where the deferred building of coforall nodes (see #21650) hides control flow errors in coforall loops.
Reviewed by @mppf and @benharsh - thanks!
=> Move control flow checks into Dyno

test/deprecated/regexSubSubn.skipif
Adds the skipif that I forgot to add in https://github.com/chapel-lang/chapel/pull/21600.
=> Add the missing skipif for a regex test

test/gpu/native/studies/shoc/sort.chpl, test/gpu/native/studies/shoc/sort.execopts, test/gpu/native/studies/shoc/sort.gpu-keys
This PR updates the SHOC Sort benchmark implementation to make it closer to the reference C+CUDA version.
Changes:
- use foreach instead of forall: delivers small but noticable improvement
- use array-of-record-wrapped-arrays instead of array-of-lists to implement ragged arrays: delivers 2-3x improvement
- use param-unrolled loops to copy tuples (this is not necessarily making things closer with the reference. But, I believe it is a much better implementation. I am somewhat surprised that it didn't deliver performance improvements, though)
Test:
=> Improve SHOC-Sort implementation

test/ANNOTATIONS.yaml
In #21677, Elliot pointed out that I accidentally put the annotations under `memLeaks`, when they actually belonged under `memLeaksFull`.
=> Move annotations from memLeaks to memLeaksFull

frontend/include/chpl/framework/Context.h, frontend/include/chpl/framework/query-impl.h, frontend/include/chpl/util/terminal.h, frontend/lib/util/terminal.cpp
This PR corrects a bug where dyno debug statements were adding the terminal code to reset font color before checking to make sure that the terminal supported color, as it does when setting the font color. This caused escape sequences to reset the terminal font color to be present even when capturing the output to a file. 
TESTING: 
reviewed by @benharsh - thank you!
=> fix: check that terminal supports color before clearing

modules/dists/StencilDist.chpl, modules/internal/ChapelArray.chpl, modules/internal/ChapelBase.chpl, modules/internal/ChapelHashtable.chpl, modules/internal/DefaultAssociative.chpl, modules/internal/DefaultRectangular.chpl, test/constrained-generics/hashtable/MyHashtable.chpl, test/studies/comd/elegant/arrayOfStructs/util/AccumStencilDist.chpl
Historically, we have deintialized array elements serially. For many codes this isn't an issue because POD types don't need any element deinit, but for types with non-trivial deinit (typically things that deallocate) like arrays-of-strings or arrays-of-bigints this can cause non-trivial slowdowns.
This changes array deinit to be parallel using the same heuristics as parallel init. This ensures we don't create a lot of tasks for small arrays and that affinity will be similar between init and deinit.
This speeds up deinit for most arrays whose elements require deinit, but slows down array-of-arrays since the performance hit from contentions on reference counters exceeds the speedup for parallel deallocation. Future improvements to speed up reference counting and do bulk counting for AoA is …
=> Parallelize array deinitialization

test/library/standard/BigInteger/bigintops.graph
When adding the bigintops benchmark, all of the dat files were the same (bigintops.dat), so rather than list them all out, we can instead change it to use `repeat-files`.
=> Switch bigintops benchmark to use repeat-files

compiler/AST/symbol.cpp, compiler/resolution/functionResolution.cpp, test/types/records/split-init/split-init-error-bug/Foo.chpl, test/types/records/split-init/split-init-error-bug/FooUser.chpl, test/types/records/split-init/split-init-error-bug/Reproducer.chpl, test/types/records/split-init/split-init-error-bug/Reproducer.good
This PR is intended to resolve a compiler hang discussed in [this Discourse thread](https://chapel.discourse.group/t/1-29-0-infinite-looping-in-splitinitmissingtypeerror/19549).
There were two problems:
1. There was an error in the code looking for a user variable that led to infinite looping.
2. Split init checking was firing for passing a generic type to a function, but passing a generic type to a `type` formal is OK
This PR fixes those problems and adds the reproducer as a test.
=> Resolve a compiler hang when reporting a split init error

modules/standard/Errors.chpl, test/unstable/taskErrorsFirst.chpl, test/unstable/taskErrorsFirst.good
Per some discussion summarized here: https://github.com/chapel-lang/chapel/issues/21068#issuecomment-1431696946, we decided to mark `TaskErrors.first()` as unstable with the expectation that it may be renamed or modified in the future.
This PR adds the unstable annotation and an unstable test.
=> Mark TaskErrors.first() as unstable

modules/standard/Errors.chpl, test/deprecated/illegalArgumentErrorInit.chpl, test/deprecated/illegalArgumentErrorInit.good
Per discussion here: https://github.com/chapel-lang/chapel/issues/19803#issuecomment-1430187621, the formal in`IllegalArgumentError`'s one-argument initializer is being renamed from `info` to `msg`.
=> Rename formal in `IllegalArgumentError`'s initializer to `msg`

modules/standard/Time.chpl
Add explicit 'int' types for the initializers for date/time/datetime/timedelta types.
=> Add explicit types to 'init' methods for date/time types

frontend/lib/parsing/parsing-queries.cpp
Keep track of modules we've seen before when loading modules from
search paths in `getToplevelModule`. This avoids emitting the same
error twice in a row in the event that e.g., the search path `.`
appears twice.
For the following code:
```chapel
// SomeLibrary.chpl
module M {
var x = 42;
}
// main.chpl
proc main() {
use SomeLibrary only;
writeln(SomeLibrary.M.x);
}
```
The error looks like:
```
/SomeLibrary.chpl:1: error: In use/imported file, module name M
does not match file name SomeLibrary.chpl
--> Old error appears from both production and dyno...
main.chpl:1: In function 'main':                                                                                                                                                     │
main.chpl:2: error: cannot find module or enum named …
```
=> dyno: Avoid emitting a module/file name mismatch error twice

runtime/src/chpl-gpu.c, runtime/src/gpu/common/cuda-shared.h
After this PR: https://github.com/chapel-lang/chapel/pull/21516 (Remove redundant redefinition of CHPL_GPU_MEM_STRATEGY_ARRAY_ON_DEVICE) we need any file that uses the `CHPL_GPU_MEM_STRATEGY_ARRAY_ON_DEVICE` macro to `#include "chpl-env-gen.h"`.
In this PR https://github.com/chapel-lang/chapel/pull/21644 I noticed this include was missing from one file and added it. This triggered a bug because there was another file that was missing it. In this PR I've added it.
=> Include chpl-env in files that use CHPL_GPU_MEM_STRATEGY_ARRAY_ON_DEVICE  macro

test/statements/loops/labeledLoopBreakWithoutNestedCoforall.chpl, test/statements/loops/labeledLoopBreakWithoutNestedCoforall.good, test/statements/loops/labeledLoopBreakWithoutOnStatement.chpl, test/statements/loops/labeledLoopBreakWithoutOnStatement.good, test/statements/loops/labeledLoopContinueWithoutNestedCoforall.chpl, test/statements/loops/labeledLoopContinueWithoutNestedCoforall.good, test/statements/loops/labeledLoopContinueWithoutOnStatement.chpl, test/statements/loops/labeledLoopContinueWithoutOnStatement.good
These were futures, but have been fixed in the meantime by #21664.
=> Add tests for 21651: internal errors continue/breaking to labeled loop outside coforall or on statement

frontend/lib/resolution/resolution-error-classes-list.cpp
Improves the error message from
chpl --dyno test/functions/iterators/recursive/recursive-iter-findfilesfailure.chpl --detailed-errors
=> Improve symbol-hiding-formal warning

test/interop/C/multilocale.skipif, test/interop/python/multilocale.skipif
Multi-locale interop (MLI) requires ZMQ. Currently, it requires a true system install of ZMQ (we only provide `-lzmq` and don't have a way to provide non-default `-L`/`-I` paths.) Previously, the skipif was just checking for `libzmq.so` and assuming the headers would be available if the shared object was found, but this isn't true on SLES15 and some other systems.
For other ZMQ tests, we switched to using `pkg-config` for the skipifs and providing lib/include paths, but since we don't have a way to provide lib/include paths for MLI support that won't work here. Instead this does a "configure-like" check to compile a small zmq test program and skip based on whether that succeeded.
This isn't ideal, but is better than letting the tests fail on systems with libzmq.so, but without headers. …
=> Do a configure-like check for MLI skipifs

compiler/AST/symbol.cpp, test/functions/fcf/pointers/SKIPIF
Fix an internal assertion in codegen for function types introduced by
#20991 by fixing a bug in a helper function that maps LLVM function
types to their Chapel equivalents.
Add a skipif to a FCF subdirectory intended to test the new pointer
implementation (under development).
=> Flip boolean logic in code that caches LLVM function types

modules/standard/CTypes.chpl, test/extern/PointerToEmpty.chpl, test/extern/PointerToEmpty.compopts, test/extern/PointerToEmpty.good
When `c_ptrTo` is passed an empty array, today we will get a halt for OOB, but that error message can be confusing, so this PR adds an explicit check for that in `c_ptrTo` that provides a more helpful error message.
=> Add error when passing empty array to `c_ptrTo`

frontend/lib/uast/post-parse-checks.cpp, frontend/test/parsing/testParseChecks.cpp, test/parsing/issue-21710.chpl, test/parsing/issue-21710.good
The post-parse checks I added to search for generic array types were
only firing for the expression `[]`. Expand them to also fire when
a variable specifies something like `var x: [] bytes`, and specialize
the error message a little bit.
Resolves #21710.
TESTING
Reviewed by @bradcray, @arezaii. Thanks!
=> Improve post-parse checks for generic array types

compiler/AST/symbol.cpp, test/deprecated-keyword/messageFiltering.chpl, test/deprecated-keyword/messageFiltering.good, test/deprecated-keyword/messageFiltering.prediff, test/deprecated/HDFS/HDFS-open-iomode.good, test/deprecated/IO/iomodeDeprecation.good
In comments on #21581, we realized that `:enum:` does not get filtered out of the command line deprecation warnings. Concluded to be an oversight, this PR fixes it
- add `enum` to the list of `:tags:` to filter in a deprecation message
- update deprecation filtering test to have `enum`
- update `ioMode` deprecation tests to match correct filtered output
- currently `ioMode` was the only instance of this filtering issue
- full paratest
- also ran nightly Hadoop tests, which were touched by `ioMode` changes
- There is a note about supporting filtering `~` in `Symbol::getSanitizedMsg`. The `ioMode` deprecations for HDFS do use this and it would cleanup the output
=> Add new tag filter for :enum:

modules/standard/IO.chpl, test/deprecated/IO/mmapParenless.chpl, test/deprecated/IO/mmapParenless.good, test/io/tzakian/recordReader/test.chpl, test/library/standard/IO/ioHintSetOperations.chpl, test/release/examples/benchmarks/shootout/revcomp-fast.chpl, test/studies/shootout/reverse-complement/bharshbarg/revcomp-mark-skip-read-begin.chpl
Implements the change proposed in this issue: https://github.com/chapel-lang/chapel/issues/21508.
`ioHintSet.mmap` and `ioHintSet.noMmap` are deprecated in favor of `ioHintSet.mmap(useMmap: bool)`, so that the single type method can be used to select either hint.
Adds a deprecation test and changes other tests as needed.
=> New `ioHintSet.mmap` interface

util/test/sub_test.py
This PR enables `start_test` to find `.good` files along the lines of `testname.<configuration>.<compoptsnum>.good` when there is a directory-wide COMPOPTS or when the .compopts file does not specify the .good files.
In the `test/errors` directory, we want to easily test brief and detailed error messages. The easiest way to do that is with a directory-wide COMPOPTS file, but the current implementation of `sub_test.py` didn't know how to look for `.good` files like `testname.1.good` and `testname.2.good` when compilation failed with an error. This PR fixes that by adjusting `sub_test.py` to support this case. It works along the same lines as the compopts + execopts logic.
Reviewed by @jhh67 - thanks!
=> Improve start_test to find .good files with directory-wide COMPOPTS

modules/internal/OwnedObject.chpl, test/classes/jade/owned/adopt-release.chpl, test/classes/jade/owned/adopt-release.execopts, test/classes/jade/owned/adopt-release.good
Implements owned.adopt() and owned.release() per #21372. They are not currently used anywhere other than the added tests. They will eventually replace owned.create, owned.retain, and owned.clear.
- implement `owned.adopt()` to create owned object from unmanaged
- implement `owned.adopt()` to create owned object from owned object (matching existing `owned.create()`)
- implement `owned.release()` to let go of its ownership of an object and return an unmanaged object
- add test of adopt/release with memLeaks enabled
- full paratest
- checked docs to ensure correct formatting
Closes cray/chapel-private#4435
=> Add owned.adopt() and owned.release()

test/arrays/bradc/noelemtype.bad, test/arrays/dinan/no_element_type_error.bad, test/arrays/errors/arrOfRanges.compopts, test/library/draft/DistributedMap/v2/use-distributed-map.bad, util/chpl-completion.bash
(watch out for those #21x33 PRs, kids!)
This fixes a few futures that I must've missed in my last paratest run (prior to paratest running futures by default!) as well as an obvious problem with the test of the bash autocompletion which I'm not sure how it slipped past me.
It also fixes an issue from Ben McDonald's #21733 which I happened to notice since he's likely out for the evening.
While here, I noticed that an erroneous condition that I'd noted earlier in #21652 has been resolved, probably by #21614 as Michael predicted, so I added a compopts line to lock that behavior in (and removed another that, in retrospect, felt overly paranoid).
=> Fix up some failures from #21633 and #21733

modules/packages/ProtobufProtocolSupport.chpl
'map.items()' has been deprecated in favor of zipping over the keys and values, so this updates some protobuf code to follow that recommendation.
=> Replace protobuf 'map.items' call with a zip over keys, values

modules/internal/SharedObject.chpl, test/classes/jade/shared/adopt.chpl, test/classes/jade/shared/adopt.good
Fixes a one word typo in PR #21737 that causes `shared.adopt` to return `owned` instead of `shared`.
Also improved existing test for `shared.adopt()` to prevent this kind of error from occurring again.
Since no one is using `shared.adopt()` yet, change does not affect any existing tests.
- fix typo in shared.adopt()
- modify associated test to catch this error in the future
- no new tests, just added to existing
- full paratest
- no documentation change
=> Fixes shared.adopt() of an owned object

frontend/include/chpl/parsing/parsing-queries.h, frontend/lib/parsing/parsing-queries.cpp, frontend/test/resolution/testDeprecationUnstable.cpp, frontend/test/resolution/testFindDecl.cpp
Adjust when dyno emits deprecation/unstable warnings to better match
the production compiler.
Specifically, deprecation warnings will not show in either:
- A deprecated symbol
- An unstable symbol
- A symbol marked "compiler generated"
While unstable warnings are the same but will show in deprecated
symbols. The rationale for this is that unstable things will
likely stick around longer than deprecated things, so we want to
make sure that the unstable things stay up to date.
While here, adjust `idIsInInternalModule` and friends to return false
immediately if the `internalModulePath` is the empty string.
TESTING
=> dyno: Adjust when to skip emitting deprecation/unstable warnings

util/cron/test-perf.chapcs.playground.bash
The branch vasslitvinov/unref-yields changes yields of tuples to yield all components by value rather than by their respective default argument intents.
=> Update perf playground to test yield-by-value

test/functions/iterators/vass/const-ref-iterator-1.chpl, test/functions/iterators/vass/const-ref-iterator-4.chpl, test/multilocale/deitz/needMultiLocales/diagnostics/test_remote_value_forwarding1.chpl, test/multilocale/deitz/needMultiLocales/diagnostics/test_remote_value_forwarding2.chpl, test/optimizations/bulkcomm/asenjo/ptransDR/v1/ptrans.chpl, test/optimizations/bulkcomm/asenjo/redistBlockToCyclic/FFT_assignment.chpl, test/optimizations/bulkcomm/asenjo/redistBlockToCyclic/FFT_bulk.chpl, test/optimizations/bulkcomm/asenjo/stencilDR/v1/stencil.chpl, test/parallel/forall/vass/other/binary-tree-spawn.no-recurse.chpl
One pair may have been modified concurrently since my last merge with main?  The others suggest I never checked gasnet testing before now.
=> Fix tests needing 'do return' that slipped past me

test/studies/shootout/submitted/knucleotide3.chpl, test/studies/shootout/submitted/knucleotide3.good, test/studies/shootout/submitted/knucleotide4.chpl, test/studies/shootout/submitted/knucleotide4.good
In #21733, I had updated submitted benchmarks rather than updating their good files so that we remember to go and update the submitted files. This PR undoes the changes that were made and updates the good files to reflect the deprecations.
=> Revert submitted benchmarks and update good files

modules/standard/BigInteger.chpl
For bigint functions that allocate today, there are 3 branches that check for locality and decide how to handle that case for each function. This results in a great deal of duplicated code, obfuscating the code and making bugs difficult to spot.
This PR adds a `bigintWrapper` record and a
`bigint.localize()` method to get rid of the need to have the branching in every function call.
Impacts:
- about 600 lines removed from bigint
- about 60s saved on Arkouda gasnet compilation
- about 5% reduction in raw performance for operations that allocate for both operands (such as `bigint+bigint`)
Backing issue: https://github.com/Cray/chapel-private/issues/4146
Follow up issue for performance regression: https://github.com/Cray/chapel-private/issues/4449
=> Add a 'bigint.localize' for functions that allocate

modules/standard/BigInteger.chpl
The bigint record has a field with an extern type of `mpz_t`, which is being zero initialized by default, adding a `memset` to the generated C code. This is not needed for bigint, since we are always calling a version of `mpz_init` when initializing a bigint record, which will handle the initialization, regardless of whether it has been zero initialized by Chapel.
Backing issue: https://github.com/Cray/chapel-private/issues/4146
=> Stop zero-initializing the mpz_t field for bigint

modules/internal/localeModels/gpu/LocaleModel.chpl, test/library/packages/LinearAlgebra/performance/SPA-perf.chpl
This addresses a few cases that didn't show up in my paratesting, but did show up in then nightlies, the first of which was a fairly obvious oversight, in retrospect:
* 16 cases in the gpu Locale Model, which I'd failed to check or test
* 1 case only enabled in LinearAlgebra testing on XCs
=> Fix some missing cases that relied on the single-statement return exception

test/functions/fcf/pointers/SKIPIF
Adjust the skipif for a test exercising the FCF pointer implementation
to ensure `CHPL_TARGET_COMPILER != llvm` rather than `CHPL_LLVM`.
Nightly confs will build with LLVM enabled but target Clang instead.
=> Adjust skipif for FCF pointer implementation to check target compiler

doc/util/nitpick_ignore, frontend/include/chpl/parsing/parsing-queries.h, frontend/include/chpl/resolution/scope-queries.h, frontend/include/chpl/resolution/scope-types.h, frontend/lib/parsing/parsing-queries.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/lib/resolution/scope-types.cpp, frontend/test/resolution/testMethodFieldAccess.cpp, frontend/test/resolution/testScopeResolve.cpp
This PR improves name lookup within methods for the dyno scope resolver to better handle preferring local variables and formals to fields/methods and fields/methods to outer variables. This PR is motivated by getting cases from #21668 working. It adds the tests from that issue to testMethodFieldAccess.cpp but not all of them are working yet.
For the most part, this PR is motivated by this draft rule from #21668:
> When looking for symbols with a particular name, the compiler will search upwards in enclosing scopes. When a method scope is reached in that process, the compiler will search the method definition point for visible fields and methods. Then, it will proceed to the enclosing scope. In other words, the method definition point counts as a kind of shadow scope just outside the …
=> Improve dyno scope resolution within methods

modules/internal/DefaultRectangular.chpl
This aims to fix the performance regressions we observe as a result of #21665.
No new tests are added or needed.
First, array.this(idx) invokes DefaultRectangularArr.dsiAccess(idx).
This passes `idx` by the default intent, which triggers copying the tuple,
since #21665.
array.this() and dsiAccess() engage in return intent overloading.
Copying the tuple now occurs three times for each call to dsiAccess.
Copying involves creating call and return temps, so we now observe
three of these sitting in the AST for a call like `dsiAccess(dataIdx)`:
```
def val coerce_tmp: 2*int(64)
def val ret_tmp: 2*int(64)
call fn : (dataIdx, ret_tmp)
move coerce_tmp <-- ret_tmp
```
Second, consider this loop over two DefaultRectangular multi-D arrays:
```chpl
for (a,b) in zip(A,B) do
a = b;
```
the serial …
=> Switch DR.dsiAccess tuple arg to const ref

test/library/standard/FileSystem/nonUTF8/basic.chpl
Modified the test to check the return status from `chmod`, change the mode to be different from file's current mode, and encode the path properly before calling `chmod`.
=> Fix non-UTF8 chmod test

runtime/src/comm/ofi/comm-ofi.c
The `CHPL_RT_COMM_OFI_EP_COUNT` environment variable overrides the maximum number of endpoints reported by the `ofi` provider in the `ep_cnt` field of the domain attributes. Some providers report an incorrect maximum that is too low to allow one endpoint per thread. As a result, endpoints are not bound to threads and the runtime cannot make use of endpoint ordering properties.
=> CHPL_RT_COMM_OFI_EP_COUNT overrides maximum number of endpoints

tools/mason/MasonSystem.chpl, tools/mason/mason.chpl
Apparently our testing suite doesn't check everything that `make mason` does, and that deprecation warnings from GitHub actions can go unnoticed.
This PR makes two fixes to mason to avoid deprecation warnings.
Test:
=> Fix two deprecations that are exposed by `make mason`

modules/internal/ChapelDomain.chpl, modules/packages/SortedMap.chpl, modules/standard/Heap.chpl, modules/standard/List.chpl, modules/standard/Map.chpl, test/arrays/compilerErrors/array-of-generic-management.good, test/library/packages/SortedMap/init/testInitGenericError.good, test/library/packages/SortedMap/init/testInitGenericError2.good, test/library/standard/List/init/listInitGenericError.good, test/library/standard/Map/testInitGenericError.good, test/library/standard/Map/testInitGenericError2.good
In https://github.com/chapel-lang/chapel/issues/21417, Michael pointed out that our error messages about generic management styles use the phrase "which now means" which made sense at the time that class definitions were changing, but now feels odd...  Here, I reword such cases to "is a" in hopes of making the error messages clearer.
=> Reword "which now means" to "is a" in generic class error messages

test/GPU-GRAPHFILES, test/gpu/native/array_on_device/studies/shoc/triadAodBw1.graph, test/gpu/native/array_on_device/studies/shoc/triadAodBw2.graph
The plots are reordered to make things slightly easier while comparing performance. We can reduce number of plots we have, but I am leaving that as a future work.
Also fixes Y axis labels on two plots that caused us to believe that they were regressions: https://github.com/Cray/chapel-private/issues/4426
=> Reorder GPU plots, fix two Y labels

util/test/send_email.py
To address:
https://github.com/Cray/chapel-private/issues/4478
Fix:
Check if the underlying OS is mac and add proxies for the tests running in macs in Houston.
Issue is resolved with the fix:
[Done with tests - 230307.105201]
[Log file: /var/folders/m0/pycx4cws2k9bgwygvs5l35l8000p12/T/day2-Tue-gasnet.fast.darwin.log.30935 ]
[Test Summary - 230307.105201]
[Summary: #Successes = 6 | #Failures = 0 | #Futures = 0 | #Warnings = 0 ]
[Summary: #Passing Suppressions = 0 | #Passing Futures = 0 ]
[END]
Moving the log and summary files
2023-03-07 10:52:02 [INFO] Finished running ./test-gasnet.fast.darwin.bash on C07N70Y6DY3H
=>  Add proxies to send_email.py for macs in Houston

util/test/testEnv
`testEnv` should ignore `printchplenv` warnings because including them in its output causes problems with the programs that use `testEnv`, e.g., `sub_test.py` will not process executable `.skipif` files properly and will always conclude that the test should not be skipped.
=> Suppress printchplenv warnings in testEnv

util/cron/test-perf.chapcs.playground.bash
This reverts #21756 because the branch being tested prior to this PR has been merged to main in #21789 and deleted.
=> Revert perf playground to temp-assign-lifetime

test/gpu/native/cudaOnly.skipif, test/gpu/native/studies/compiler-performance/math.chpl, test/gpu/native/studies/compiler-performance/math.good
- Fix broken link for math test
- add skipif file for cudaOnly directory (accidentally removed)
=> Fix nightly tests accidentally broken from ROCM PR

frontend/include/chpl/resolution/scope-types.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/VarScopeVisitor.cpp, frontend/lib/resolution/VarScopeVisitor.h, frontend/lib/resolution/default-functions.cpp, frontend/lib/resolution/disambiguation.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testInteractive.cpp, frontend/test/resolution/testMethodFieldAccess.cpp
This PR continues #21715 and addresses some of the Future Work from that PR.
It is focused on fixing a variety of bugs in the dyno resolver that were interfering with a number of test cases in testMethodFieldAccess.cpp.
Future Work:
* Implement disambiguation behavior for Example 2 in #21668 if that is desired
* Come to a conclusion about what the programs in #21668 should do
=> Fix bugs with dyno scope resolution within methods

test/modules/implicit/parseTwice/main.prediff
Adjust a test that produces variable output under dyno to use a
prediff.
The test `'modules/implicit/parseTwice/main.chpl` takes a bunch of
files on the command line that use paths like `././SomeLibrary.chpl`.
The dyno frontend produces an additional error that mentions
`././SomeLibrary.chpl`, which means a prediff is required to avoid
introducing 9 different `.good` files.
Both dyno and production display paths exactly as they are input to
the compiler. We could consider having the compiler produce absolute
paths or performing a `normpath` operation on paths to avoid this
sort of prediff in the future.
=> Add prediff for test that has a new error message under 'dyno'

modules/standard/IO.chpl, test/deprecated/IO/fileLines.good, test/library/standard/IO/linesBadRegion.good, test/library/standard/IO/linesLimited.good
The old deprecation message for `file.lines` indicated that `fileReader.lines` should be used instead, but did not specify how to obtain one. This PR corrects that.
=> Improved `file.lines` deprecation message

modules/internal/OwnedObject.chpl, modules/internal/SharedObject.chpl
Add a note to mark the following functions as experimental.
- owned.adopt
- owned.release
- shared.adopt
After discussion offline, these functions will be kept in the release with appropriate notations in the documentation. These will eventually replace the owned and shared functions/methods `create`, `retain`, and `clear`, but the actual work to do the replacement is not done yet.
---
Tested docs for formatting
=> Add documentation to mark owned/shared adopt and release as experimental

test/gpu/native/studies/compiler-performance/math.compopts
This is another thing I need to fix a nightly test failure for one of our GPU tests (see https://github.com/chapel-lang/chapel/pull/21794)
=> Add missing symlink to math.compopts

util/chplenv/chpl_gpu.py
This change automatically sets `CHPL_GPU_CODEGEN` to either `cuda` or `rocm` based on whether the user has `nvcc` or `hipcc` in their path. If they have both or neither then this variable must be set manually.
This PR also adds in some checks when `CHPL_GPU_CODEGEN=rocm` to check that the user's LLVM installation supports the AMDGPU target. If it can't validate this it suggests using the bundled llvm.
=> Automatically set CHPL_GPU_CODEGEN if not already set

runtime/src/comm/ofi/comm-ofi.c
Include whether or not OFI endpoints are bound to threads in the verbose output.
=> Include endpoint bound state in verbose output

frontend/lib/resolution/Resolver.cpp, frontend/test/resolution/testFieldAccess.cpp
The checking for "referring to field of outer type" did not consider the case where the "field" wasn't a field at all, but the outer type itself. This actually _is_ allowed, and used in particular in the standard library (the `_domain` record is referenced from a context manager class, which is defined inside `_domain`). This PR fixes the Dyno scope resolver to not error in this case.
=> dyno: Fix validateAndSetToID bug blocking bundled scope resolve

frontend/lib/parsing/parsing-queries.cpp
Some tests weren't having their Sphinx markup sanitized for warning
messages because the markup was linking to an `enum`. Fix that, and
also perform the sanitation for unstable messages as well.
TESTING
=> dyno: Add 'enum' to regex that sanitizes Sphinx markup from warning messages

test/library/packages/FFTW/guru-interface-example.chpl, test/library/packages/FFTW/guru-interface-example.good
This fixes the testing failure in FFTW/guru-interface-example.chpl
The test behavior changed due to #21760. The assignment `Array1 = Array2;` traversed the elements of Array1/Array2 in a different order before that change than after that change when one of Array1's or Array2's domains has dimension(s) with negative stride(s). With #21760, the array assignment iterates over the same set of pairs of array elements as a zippered iteration over `zip(Array1,Array2)`.
Therefore this PR makes this change:
```chpl
// replace this code that no longer reverses the array
a2 = reshape(a1, D by -1);  // where a1.domain == a2.domain == D
// with this code, suggested by @dlongnecke-cray
a2 = [idx in D by -1] a1[idx];
// another way of doing the same:
forall (i2,i1) in zip(D, D by -1) do a2[i2] = a1[i1]; …
```
=> Fix array reversal in guru-interface-example.chpl

frontend/lib/parsing/ParserContextImpl.h
this PR fixes a build failure on mac after merging https://github.com/chapel-lang/chapel/pull/21425.
The failure is due to a copy elision warning that is promoted to an error and just requires assigning the value to a temporary local variable.
TESTING:
=> fix copy elision warning on mac

modules/standard/FileSystem.chpl
Dyno makes the "module use shadows formal" warning more strict, and detects cases such as those in our module code. The warning is accurate, so it seems to make the most sense to just fix the offending module code.
=> Fix module code to avoid throwing "use shadows formal" warning

util/chplenv/chpl_gpu.py
In https://github.com/chapel-lang/chapel/pull/21800 I add a check to ensure
that LLVM was built with the AMD or NVPTX target when using rocm/cuda.  This
check relies on calling out to `llvm-config` a tool that's packaged with LLVM.
This has a problem when calling `printchplenv` when using CHPL_LLVM=`bundled`
before the bundled LLVM has been built (namely that `llvm-config` itself won't
have been built yet.
As a workaround I exempt this check when using `CHPL_LLVM=bundled`. I think
it's safe to assume our bundled LLVM has the appropriate targets built.
=> Exempt bundled llvm from GPU targets check

test/gpu/native/studies/chop/chplGPU.skipif, test/gpu/native/studies/chop/patches/gpuDiagnostics.patch
ChOp uses the `GPUDiagnostics` module, which is now `GpuDiagnostics`. The Chapel release that brings this change isn't out yet, so we don't want to PR to ChOp just yet, but to get our testing working, we need to patch the code locally to work with the pre-release Chapel version.
=> Patch ChOp with GPU diagnpstics change

modules/standard/Time.chpl
Mark Time functions that are essentially just shims for C functions with the unstable attribute.
=> Mark Time C-shim functions unstable

frontend/include/chpl/util/hash.h, util/chplenv/chpl_llvm.py
This PR takes a few steps to improve the portability of Chapel.
* improves portability to Alpine Linux 3.17 by enabling the LLVM detection logic to find `llvm14-config`. That version of Alpine defaults to LLVM 15 but we don't support that yet. Along the same lines, added support for finding `/usr/bin/clang-14` which is the style that Alpine uses.
* improves portability to GCC 13 by adding some `#include`s that GCC insists upon.
=> Improve portability to Alpine 3.17 and to GCC 13

doc/rst/technotes/gpu.rst, modules/standard/GPU.chpl, test/gpu/native/memory/sharedMemory.chpl, test/gpu/native/studies/shoc/sort.chpl, test/gpu/native/studies/transpose/transpose.chpl
This simply provides user-facing wrappers for these primitives, since the features they provide are frequently used in GPU codes (see https://github.com/Cray/chapel-private/issues/4454).
=> GPU: Add procedures wrapping `syncThreads` and `allocShared` primitives.

modules/standard/Types.chpl, test/deprecated/typeQueryFuncs.chpl, test/deprecated/typeQueryFuncs.good, test/library/draft/DistributedMap/v2/use-distributed-map.bad
This PR remove deprecated isFloat* functions.
These functions were deprecated in 1.28: https://github.com/chapel-lang/chapel/pull/20548
The test for this (`typeQueryFuncs.chpl`) also includes use of subtype comparison operators. I don't remove those in this PR since those were deprecated in 1.29 (https://github.com/chapel-lang/chapel/pull/21108). FWIW, those changes also seem riskier to remove so we might consider keeping them around for longer than the normal 6 month cycle.
=> Remove deprecated isFloat functions

modules/internal/ChapelRange.chpl, test/deprecated/alignedBoundsByDefault.chpl, test/deprecated/alignedBoundsByDefault.compopts, test/deprecated/alignedBoundsByDefault.good
This was used to opt into the new range/domain.[low|high] behavior, but has been deprecated since 1.28 and no longer serves a purpose.
=> Remove the deprecated config param 'alignedBoundsByDefault'

modules/standard/BigInteger.chpl, test/deprecated/BigInteger/invert_int_returning.chpl, test/deprecated/BigInteger/invert_int_returning.good, test/library/standard/BigInteger/inversion_error.compopts, test/library/standard/GMP/ldelaney/gmp_Bigint_number_theoretic.compopts
Removes deprecation of the int-returning overload of `bigint.invert` from a few releases ago.
-  [x] paratest
=> Remove deprecation of int-returning `bigint.invert` method

test/studies/champs/sub_test
This modifies champs sub_test to clone only the current source tree without bringing in all branches and dev history. This is done in order to reduce the cloning time and the size of the cloned tree. As of this writing, this change reduced the tree size from 499Mb to 7.4Mb.
The tree cloned the fast way, using git clone options `--single-branch --depth=1`, is not suitable for development. If this presents hardship, we can reconsider.
Testing: I verified that the source trees cloned before and after this change are identical, except for the .git directory.
=> Git-clone only the current tree of champs

test/multilocale/numLocales/bradc/testVFlag.launcher-slurm-srun.goodstart, test/multilocale/numLocales/bradc/testVerboseFlag.launcher-slurm-srun.goodstart
The `--cpu-bind=none `argument is only passed to `srun` when `CHPL_RT_LOCALES_PER_NODE` > 1.
=> Fix verbose flag tests for slurm-srun launcher

compiler/resolution/functionResolution.cpp, test/types/partial/partial-no-q-warning.chpl, test/types/partial/partial-no-q-warning.good
Follow-up to PR #21410 to improve the `partial instantiation without '?' argument` warning.
The goal of this PR is to avoid listing fields that need to be instantiated when the field has a type that depends on an earlier field, for example, with `record R { param p; type eltType; var element: eltType; }`, the warning for `R(1)` should not include `element` since it's not really a generic field (just one that hasn't yet been instantiated).
See also https://github.com/chapel-lang/chapel/pull/21410#issuecomment-1463004071 which describes a situation in which this came up.
Instead of actually computing whether such a field is dependent or not, the approach here is to only report a non-type non-param field with a type expression if it is the first field. This is an approximation, but it is …
=> Don't name dependent fields in partial instantiation warning

doc/rst/technotes/partialInstantiations.rst
This PR updates the partial instantiation technote to describe warning for partial instantiations that do not include a `?` argument.
Follow-up to PR #21410.
=> Update the partial instantiation technote

modules/standard/IO.chpl, test/deprecated/IO/fileReaderFlush.chpl, test/deprecated/IO/fileReaderFlush.good, test/deprecated/IO/fileReaderFlush.txt
It's a no-op, but people might have thought they needed to
to call it on reading channels, so give them a gentler warning
instead of just removing the function.
Add a test locking in the deprecation message
=> Deprecate fileReader.flush instead of removing it

doc/rst/language/spec/expressions.rst, doc/rst/language/spec/iterators.rst, doc/rst/language/spec/procedures.rst, doc/rst/language/spec/variables.rst
This updates the spec's syntax diagrams to add support for single-statement 'do' subroutine bodies and to remove the previous exception for single-statement returns.  It also makes the iterator's syntax diagrams use the `function-body` rule from the procedures chapter, as the previous definition was incorrect (had a single-statement yield exception that the implementation doesn't support) and it doesn't require its own case.
While here, we were surprised to find that there was no text talking about procedure bodies, so I added a new short section about that, mentioning the single-statement `do` form, and moved the return statement section into it as a subsection.
It also udpates a few examples that I ran into while looking for other places that might need changing; apparently these are …
=> Update spec w.r.t. single-statement 'do'; lack of 'return' special case

test/gpu/native/studies/compiler-performance/math.gpu-compopts
For `gpu/native/studies/compiler-performance` we have a `.compopts` file, however since we run GPU perf tests with `-perflabel gpu-` so if we want to use the compiler options we need a `.gpu-compopts` file. This PR creates the file and links it to the non-perf test version.
=> Add missing compopts file for GPU math perf test

modules/standard/IO.chpl
Resolves #21519 
A user pointed out that this code did not work in relaxed and strict error
handling settings, only fatal error handling mode.  Update the code to include
`try!` on all throwing calls, such that it will work in these settings
While here, also corrected the expected output for the read example to include
the extra text it adds
=> Update the example code in the IO docs to work in any error handling setting

doc/rst/usingchapel/prereqs.rst
This PR updates prereqs.rst according to the current output of `extract-docs.py`.
(Note that PR #21829 includes the portability testing changes that were used to generate this documentation change).
Reviewed by @tzinsky and @lydia-duncan - thanks!
=> Update prereqs per current portability testing

modules/standard/Time.chpl, test/deprecated/timeGetCurrentTime.good
The `getCurrentTime` deprecation message was previously only recommending to use `timeSinceEpoch()`, which is not an equivalent replacement by itself, so this PR updates it to instead recommend `timeSinceEpoch().totalSeconds()`, which can be put in place of old `getCurrentTime` calls by itself.
=> Update 'getCurrentTime' deprecation message

doc/rst/platforms/libfabric.rst
Explain the use of `CHPL_RT_COMM_OFI_EP_COUNT` to override the number of endpoints reported by the provider.
=> Document CHPL_RT_COMM_OFI_EP_COUNT

runtime/src/chpl-gpu.c
My #21753 added debug-related conditionals that executes even without `--debugGpu` this really slows down execution of tests. This PR removes those conditionals.
Test:
=> Remove a debug-related check that was executing always

doc/rst/language/spec/arrays.rst, doc/rst/language/spec/procedures.rst, doc/rst/language/spec/types.rst
In #21584 I adjusted the implementation grammar to parse array types
and bracket loops with a single production. This PR adjusts the spec
grammar to reflect those changes.
Apply `expression` from `type-expression`. This mirrors how the
production compiler has collapsed `type-expression` into `expression`,
but also keeps the category of things that are logically considered
"type expressions" separate from other expressions.
Remove redundant rules of the form `? identifier[OPT]` as those terms
are reachable by `query-expression`.
Adjust `array-type` to make the `domain-expression` and
`type-expression` optional. Add a sentence explaining that currently,
they may only be omitted in specific circumstances.
=> Make adjustments to spec grammar to reflect array type parsing changes

util/chplenv/compile_link_args_utils.py
This PR passes AMD libraries' path to `rpath` while linking.
It looks like they are shared libraries that require rpath or LD_LIBRARY_PATH to be set.
While there, it also uses the parent directory for the path as that contains symlinks to both HSA and HIP libraries.
Test:
=> Pass AMD library paths with rpath, too

test/functions/iterators/vass/yield-by-value-4.skipif
The .bad file for this test expect certain amounts of leaked memory. The latter differs for baseline and no-local/gasnet testing. So, skip this test in those cases.
Once the leak is fixed, the skipif can be removed. Actually, the entire test should be folded into yield-by-value-2,3, for simplicity.
=> Skip yield-by-value-4 future in non-standard configurations

modules/standard/IO.chpl
@bradcray caught an outdated reference to the now private internal error code `EEOF` on `file.reader()`, which this PR replaces with updated reference to `OS.EofError`.
=> Remove outdated reference to EEOF in file.reader docs

runtime/src/launch/slurm-gasnetrun_common/slurm-gasnetrun_common.h, runtime/src/launch/slurm-srun/launch-slurm-srun.c
Passing the `--quiet` argument to `srun`, `salloc`, or `sbatch` is incompatible with `SLURM_DEBUG`, `SALLOC_DEBUG` and `SBATCH_DEBUG`, respectively.
=> Don't specify --quiet if SLURM_DEBUG/SALLOC_DEBUG/SBATCH_DEBUG is set

test/gpu/native/array_on_device/studies/shoc/triadAOD.chpl, test/gpu/native/array_on_device/studies/shoc/triadAOD.gpu-keys, test/gpu/native/array_on_device/studies/shoc/triadAodAsync.chpl, test/gpu/native/array_on_device/studies/shoc/triadAodAsync.gpu-keys, test/gpu/native/studies/shoc/triad.chpl, test/gpu/native/studies/shoc/triad.gpu-keys, test/gpu/native/studies/shoc/triadalt1.chpl, test/gpu/native/studies/shoc/triadalt1.gpu-keys, test/gpu/native/studies/shoc/triadalt2.chpl, test/gpu/native/studies/shoc/triadalt2.gpu-keys, test/gpu/native/studies/shoc/triadchpl.chpl, test/gpu/native/studies/shoc/triadchpl.gpu-keys
This updates SHOC perf studies to not count kernel launches if `--perftest` is thrown in.
We've recently seen perf test failures mostly due to the line number of the output and sometimes because of changes in number of kernel launches due to https://github.com/chapel-lang/chapel/pull/21753.
In any case, performance tests shouldn't count kernel launches as it is an atomic increment that can have noticeable effects in short-running and/or launch-heavy tests.
Test:
=> Update GPU performance tests to not count launches in perf mode

doc/rst/technotes/attributes.rst, doc/rst/technotes/index.rst
This PR adds some documentation about Attributes in general, and some specifics about the stability and chpldoc attributes. It also indicates the current state of support for attributes and details some future work plans.
For the 1.30 release, we are too close to release to issue an update to the `sphinxcontrib-chapeldomain` repo as `chpldoc` uses that package to build docs and could be affected. For now, the examples in this document update are labeled as `text` rather than `chapel`. Once https://github.com/chapel-lang/sphinxcontrib-chapeldomain/pull/70 can be merged, the docs can be updated to indicate the code blocks are Chapel and highlighting will resume. 
TESTING:
reviewed by @DanilaFe - thank you!
=> add a technote about Attributes

doc/rst/technotes/firstClassFns.rst
Mention that new features added to support first-class functions may
not work unless `fcfsUseLegacyBehavior` is set to `false`.
=> Add a warning to FCF technote mentioning config param

compiler/resolution/functionResolution.cpp, test/functions/lambda/NewSyntaxInLegacyMode.chpl, test/functions/lambda/NewSyntaxInLegacyMode.good
An error message that fired when using the `proc()` procedure type
constructor in "legacy mode" is outdated and can be removed. Do so
to make it more convenient to try out new FCF syntax in 1.30.
TESTING
=> Remove error for using FCF type constructor syntax in legacy mode

compiler/resolution/resolveFunction.cpp
The comment reflects on compilation time improvements due to #21789.
Suggested by @benharsh.
=> Add a todo comment to the compiler

modules/standard/IO.chpl
Instead of using `try!` on the calls that throw errors, surround them in `try` / `catch` blocks with a note to look up the individual errors thrown.
This avoids recommending that users always halt on errors and points them to places where they can find more information
Built the docs locally without issue
=> Further adjustments to the IO documentation example codes

doc/rst/language/spec/records.rst
This PR resolves https://github.com/chapel-lang/chapel/issues/21523 by updating the docs for records to indicate that fields which are arrays or other complex data types only store the descriptor for the object, and that the underlying data is managed by the descriptor. 
TESTING:
=> docs(record): indicate array fields store data outside record

doc/rst/usingchapel/building.rst
In #21622, it was pointed out that CHPL_HOME is not documented for users of `make install` builds.  This updates the "Building Chapel" documentation to indicate that $CHPL_HOME is in the `share/chapel/x.yz/` directory under the prefix into which Chapel was installed.
This is not a perfect solution because someone may be using a version of Chapel installed by someone else and never read those instructions (and/or they may do the install themselves and never finish reading the instructions or forget about them).  Still, documenting it here seems like an obvious step forward.
Another thing we should consider doing in the near future is to promote the `--print-chpl-home` to a user flag (potentially calling it `--print-CHPL_HOME` to improve chances of finding it; or maybe we can just rely on …
=> Document the meaning of CHPL_HOME for `make install` builds

doc/rst/developer/bestPractices/StandardModuleStyle.rst
Resolves Cray/chapel-private#4451
Resolves #21691
This change is mostly focused on adding the guidance we
decided on for accessor method naming.  It also corrects
an incorrect use of "CamelCase" to "PascalCase", which
is the proper term.
Built the docs locally.
=> Improvements to the Standard Module Style Guide

doc/rst/language/spec/data-parallelism.rst
add a clarifying note to the spec about arguments that don't get promoted.
came out of discussion in #21649.
- add a note about only evaluating scalar expressions once to zippered promotion
- built docs locally
---
[Reviewed by ]
references Cray/chapel-private#4419
=> Add note in spec about arguments that don't get promoted

modules/standard/IO.chpl
The PR makes a few improvements to the IO module docs:
- summarizes more of the read/write methods in the module docs
- unifies the channel-offset terminology to use "offset" instead of a mixture of "offset" and "position"
- wraps lines to 80 columns for a variety of methods
- a few small wordsmithing changes
- adds backticks to `fileReader`, `fileWriter`, `true`, and `false` in a few places
- adds links in a few places (ex: 'string' -> :type:'~String.string')
=> Documentation cleanup for the IO module

doc/rst/language/spec/generics.rst
This PR updates the documentation for parameters in generic types to include a user submitted example from https://github.com/chapel-lang/chapel/issues/21524. 
TESTING:
=> docs(generics): update parameters with user submitted example

doc/rst/tools/chpldoc/chpldoc.rst
This PR updates the `chpldoc` documentation to change the method for suppressing generated documentation from `pragma "no doc"` to `@chpldoc.nodoc`.
This required changing the code block style from Chapel to plain text as the sphinxcontrib-chapeldomain and pygments packages both require updates to parse attributes.
Future work will change these back to Chapel blocks once those updated packages are available.
TESTING:
reviewed by @lydia-duncan - thanks!
=> docs(chpldoc): replace pragma 'no doc' with attribute

doc/rst/developer/bestPractices/Deprecation.rst
This PR updates deprecated docs to include the `@deprecated` attribute instead of the `deprecated` keyword. 
As with https://github.com/chapel-lang/chapel/pull/21915, this required changing the code block style from Chapel to plain text as the sphinxcontrib-chapeldomain and pygments packages both require updates to parse attributes.
Future work will change these back to Chapel blocks once those updated packages are available.
TESTING:
reviewed by @lydia-duncan - thank you!
=> docs(deprecated): update uses and examples of keyword with attribute

doc/rst/platforms/raspberrypi.rst
This PR updates the formatting of docs for building Chapel on a cluster of Raspberry Pis to be limited to 80 cols (except links that are too long). 
It also removes a note about Chapel 1.28 being the last version that builds on Raspberry Pis, as the limitation is based on the amount of RAM on the hardware (<2GB), not anything intrinsic to building Chapel on Pis. 
TESTING:
reviewed by @ronawho - thank you!
=> docs(raspberryPi): format lines to 80 cols and remove version note

doc/rst/usingchapel/building.rst
This PR adds some documentation for the new VERBOSE and QUIET flags that were added as Makefile options in PR https://github.com/chapel-lang/chapel/pull/21700. 
While here, updated capitalization on `Makefile` to be consistent within doc.
TESTING:
reviewed by @e-kayrakli - thank you!
=> docs(build): add verbose and quiet flag docs

runtime/include/gpu/rocm/chpl-gpu-gen-includes.h
These were accidentally reversed (the block size functions were calling the ROCM primitives for block index and vice versa).
With the approval of others I'm going to try and submit this now even though we're near our release deadline on the basis that:
- it's pretty small / innocuous in terms of complexity yet with major impact on correctness and
- it’s in GPU code, which at this point isn't heavily used and considered more prototypical (though getting less over time)
- the previous bullet is doubly the case for AMD
=> Fix GPU ROCM runtime calls for block size and idx

doc/rst/language/spec/iterators.rst, doc/rst/language/spec/procedures.rst, doc/rst/language/spec/ranges.rst, doc/rst/language/spec/tuples.rst, doc/rst/language/spec/variables.rst
This updates the spec for the changes in:
* rules for range slicing #21760
* implementation of yielding tuples #21789
While there, clarify yielding by value (not just the tuples), reorg/tidy up the sections on value/referential tuples and tuple arg intents, and do some minor cleanups/updates.
Testing: local build of the docs.
=> Spec updates for range slicing and tuples

doc/rst/language/spec/generics.rst
This PR fixes failing spectests that started after https://github.com/chapel-lang/chapel/pull/21902. This commit was supposed to be part of that PR, but didn't get pushed prior to it being merged due to user error (It was ME!)
The test was missing the command-line execopts and known good output to compare.
TESTING:
reviewed by @mppf
=> docs(generics): add test for MemberWidth example

CONTRIBUTORS.md
Update the contributors file to highlight those who have contributed to Chapel 1.30.  I also simplified the header line to make it shorter and suggest that it's speaking about the file's contents as a whole and not just the first section.
=> CONTRIBUTORS.md for 1.30

doc/rst/conf.py, doc/util/versionButton.php
This is the normal update when we're staging docs for the pending release, to make the docs version menu / button reflect those staged docs.
The diff here is slightly different than the one for https://github.com/chapel-lang/chapel/pull/21228 though it matches the bestPractices instructions.  I'm assuming I did the wrong thing last time, but if that turns out to be wrong, I'll back that part of the change out and update the best practices instructions.
=> Update the docs version menu / button to reflect the staged docs for 1.30

test/compflags/ferguson/default-binary-name/sub_test, test/library/packages/FFTW/SKIPIF, test/library/standard/FileSystem/fsouza/chown/permission_error.suppressif, test/library/standard/IO/open/checkPermissions.suppressif, test/library/standard/IO/openreader/checkPermissions.suppressif, test/library/standard/IO/openwriter/checkPermissions.suppressif, test/library/standard/OS/POSIX/chmod/chmod_noprivilege.suppressif, test/studies/cholesky/jglewis/version2/performance/test_cholesky_performance.suppressif, test/studies/parboil/stencil/stencilSerial.skipif, test/testsystem.notest, test/testsystem/runtime-error.chpl, util/test/sub_test.py
Migrate:
- Cygwin suppressifs for Jira 74/81 to private issues 4556/4097
- testsystem tests (manual tests to check sub_test filters)
Remove:
- References to pgi specific issues since we don't test pgi anymore
- Jira 164 for inline text since there wasn't much info to migrate
Part of Cray/chapel-private#4543
=> Migrate Jira references in tests to github

make/compiler/Makefile.clang
...so that they will apply to both C++ and C compiles.
The motivation for this is that our CI testing was catching things with g++ that we weren't catching as developers using clang++.  This should bring the clang++ warnings more in-line with what we're getting from g++.
It looks to me as though it's been this way since we first added support for clang, so putting them in both was either an oversight, or perhaps they weren't supported by clang++ back then.  I also get the sense (though I didn't look into it very carefully) that g++ and clang++ may have slightly different warnings associated with different flags in their C/C++ compilers.  In any case, my guess is that this will help any developers using warnings in recent versions of clang++, but please alert me if that's incorrect.
=> For clang, move `-W[missing|strict]-prototypes` to `WARN_CXXFLAGS` from `WARN_CFLAGS`

test/io/corrado/write_buffering_optimization/dynamic_buffering.chpl, test/io/corrado/write_buffering_optimization/growing_buff_write.chpl, test/io/corrado/write_buffering_optimization/large_write.chpl
This fixes up a few tests that were added in #21786, presumably developed before noMmap was deprecated, but merged afterwards, in hopes of not having them fail tonight.
=> Convert some new ioHintSet.noMmaps to ioHintset.mmap(false)

modules/standard/IO.chpl
This PR resolves a test failure introduced by https://github.com/chapel-lang/chapel/pull/21786, where `writeBinary` would pass a pointer to a remote array into an external C function.  This call is now only made if the array is local.
=> Fix array localization in `writeBinary(data: [])`

modules/standard/AutoMath.chpl, modules/standard/Math.chpl, test/deprecated/Math/cargDep.chpl, test/deprecated/Math/cargDep.good, test/types/complex/diten/cplxMathFnTypes.chpl
We don't want to include this function in all programs.
<details>
The commit for this ends up looking a little odd so that we don't accidentally
build the Math module by default as well - make an undocumented version that
Math and the deprecated version can call, so that Math depends on AutoMath and
the two versions stay in sync until the deprecated version is removed.  This
strategy was previously followed for other symbols in the Math module.
</details>
While here, adjust the documentation for `carg` and the related version of `abs`.
`abs` of complex arguments is closely related to `carg`, so add documentation
links now that they are a little more separated.  Also, be more specific and
accurate when describing their functionality.  Documentation changes suggested
by Damian.
Adjusted a …
=> Deprecate auto-included version of carg and move it to the Math module

doc/rst/developer/bestPractices/TestSystem.rst
Noticed when went to track it down for Daniel
----
=> Fix a typo in the TestSystem best practices doc

compiler/AST/symbol.cpp, frontend/include/chpl/util/filtering.h, frontend/lib/parsing/parsing-queries.cpp, frontend/lib/util/CMakeLists.txt, frontend/lib/util/filtering.cpp, test/deprecated-keyword/messageFiltering.chpl, test/deprecated-keyword/messageFiltering.good, test/deprecated/HDFS/HDFS-open-iomode.good
Inline markup filtering for deprecation messages was not filtering out a
'~'. This PR adds filtering for this, filtering out all components
except the last one.
This PR also implements better filtering for '!'
- The string ':proc:\`~abc.def\`' was filtered to '~abc.def', now it
filters to 'def'.
- The string ':proc:\`!abc.def\`' was filtered to '!abc.def', now it
filters to 'abc.def'.
- update tests to reflect new filtered string
- update the only usage of '~' in HDFS deprecations
- remove duplicated regular expression
- tested changes locally
---
Resolves some of the todo tasks mentioned in #18549
=> Improve deprecation filtering for comments using '~' and '!'

modules/standard/BigInteger.chpl
In response to reviews on #21956, remove extra locale checks and replace with usage of the `bigint.localize()` function 
- replace non `result.localeId` checks with `bigint.localize()`
- full paratest + gasnet
---
[Reviewed by @]
=> Remove extra locale checks in BigInteger

frontend/lib/util/filtering.cpp, test/deprecated-keyword/messageFiltering.chpl, test/deprecated-keyword/messageFiltering.good
Adds support for rst hyperlinks of the form `nicename<target>`. The filter will keep just `target`
- add regex for rst hyperlinks, captures only the target
- added test for rst hyperlinks to existing deprecation filtering test
- tested locally
---
Completes support for #18549, resolved
[Reviewed by @]
=> Filtering for rst direct hyperlinks to deprecations

CMakeLists.txt
This PR updates the root ``CMakeLists.txt`` file to generate ``compile_commands.json`` for the entire project. This will help to facilitate use of various tools in the future.
=> Generate compile_commands.json for the whole project

test/ANNOTATIONS.yaml
Include primary Arkouda annotations in bigint graphs. While here annotate the 1.30 upgrade.
=> Fix perf annotations for Arkouda bigint graphs

test/gpu/native/stringBytesConfig/bytesConfigIssue20276.comm-none.good
The test was added in https://github.com/chapel-lang/chapel/pull/21976. I forgot to check-in a good file. This PR fixes that.
=> Add a missing comm-none.good file

modules/internal/ChapelArray.chpl, test/arrays/diten/arrayCount.chpl, test/arrays/userAPI/arrayAPItest.chpl, test/arrays/userAPI/arrayOps2D-IRV.good, test/arrays/userAPI/arrayOps2D.good, test/arrays/userAPI/blockOps2D.comm-none.good, test/arrays/userAPI/blockOps2D.good, test/arrays/userAPI/blockOpsRankChange.comm-none.good, test/arrays/userAPI/blockOpsRankChange.good, test/arrays/userAPI/blockOpsReindex.comm-none.good, test/arrays/userAPI/blockOpsReindex.good, test/arrays/userAPI/callExternArrTest.good, test/arrays/userAPI/enumArray.good, test/arrays/userAPI/rankChangeOps3to2D.good, test/arrays/userAPI/reindexOps2D.good, test/arrays/userAPI/sliceOps2D.good, test/arrays/userAPI/unsignedOps.good, test/unstable/arrayFuncs.chpl, test/unstable/arrayFuncs.good
Previously, we marked `Array.count` as unstable due to the thought that we might want to change its interface to be more consistent with uses of counts in other datastructures. After further consideration it looks like the interface for `Array.count` is unlikely to change (at least not in a way that would break backwards compatibility).
This PR is for: https://github.com/chapel-lang/chapel/issues/21730
=> Make array.count stable

modules/standard/BigInteger.chpl, test/library/standard/BigInteger/apiTest.chpl
Revert a change in #21986 where a number of BigInteger operators where changed from having an `int` version and a `uint` version to having an `integral` version (or a version type checked by a `where` clause). The `integral` version fails when passed a `bool` (see #20125 and #20011). The `where` clause version fails under promotion. 
- change methods previously changed to `integral`/`where` clause back to `int` and `uint`
- change some of these methods which are single lines to use `do` instead of `{}`.
- add more tests for `bool` passed as integers to `apiTest.chpl`
- add a handful of operator promotion tests to `apiTest.chpl`
- local testing
- paratest
- build and run Arkouda tests
---
[Reviewed by @bmcdonald3 ]
=> Fix regression in BigInteger operators with bools and promotion

test/distributions/bharshbarg/constInIdxBlock.chpl, test/optimizations/remoteValueForwarding/serialization/destroyGlobals.chpl, test/optimizations/remoteValueForwarding/serialization/domains.chpl, test/optimizations/remoteValueForwarding/serialization/missingDeserializer.chpl, test/optimizations/remoteValueForwarding/serialization/returnsClass.chpl, test/optimizations/remoteValueForwarding/serialization/strings.chpl
These tests started failing in our gasnet job after https://github.com/chapel-lang/chapel/pull/21648 which deprecated `Array.tail()`. This PR updates the tests to use `Array.last`.
=> Fix failing tests after tail() deprecation

util/packaging/docker/test/brew_install.bash
To fix a failure in homebrew, removing a brew test that is not required in the weekly run.
=> Remove a test bot formula that is not required in weekly testing

test/library/standard/IO/readAll/readBytesType.chpl, test/library/standard/IO/readAll/readStringType.chpl
Fixes a memory leak in a couple of `readAll` tests caused by writing to the channel after calling `close()` on it.
=> Fix memory leaks in `readAll` tests

modules/standard/BigInteger.chpl
In #22000, when a bigint was RVFed locally, the RVFed record would do a shallow copy of the `mpz_t` field. This meant that the `mpz_t` field was being freed twice, once by the RVFed record and once by the original record. Doing a deep copy in this PR will fix this issue.
=> Deep copy for bigint values RVFed locally

util/packaging/docker/test/brew_install.bash
Homebrew CI is updated with new set of test-bot commands.
Updating our homebrew-runs to align with the homebrew-CI (for ex https://github.com/Homebrew/homebrew-core/actions/runs/4598529663/jobs/8122829052).
Correct brew test bot command to test --cleanup-before
Remove the stale test-bot commands
https://github.com/Cray/chapel-private/issues/4642
=> Align homebrew tests to align with homebrew CI.

doc/rst/users-guide/base/constParam.rst, modules/standard/AutoMath.chpl, modules/standard/Math.chpl, test/classes/ferguson/forwarding/call-forwarded-omit-this.bad, test/classes/ferguson/forwarding/call-forwarded-omit-this.chpl, test/deprecated/Math/mathConstants.chpl, test/deprecated/Math/mathConstants.good, test/exercises/c-ray/c-ray.chpl, test/exercises/c-ray/old/c-ray.chpl, test/exercises/c-ray/solutions/c-ray-1.chpl, test/exercises/c-ray/solutions/c-ray-1a.chpl, test/exercises/c-ray/solutions/c-ray-2.chpl, test/exercises/c-ray/solutions/c-ray-2a.chpl, test/exercises/c-ray/solutions/c-ray-3.chpl, test/exercises/c-ray/solutions/c-ray-3a.chpl, test/exercises/c-ray/solutions/c-ray-4.chpl, test/exercises/c-ray/solutions/c-ray-4a.chpl, test/exercises/c-ray/solutions/c-ray-5.chpl, test/exercises/c-ray/solutions/c-ray-6.chpl, test/exercises/c-ray/solutions/c-ray-7.chpl, test/exercises/c-ray/solutions/c-ray-8.chpl, test/modules/engin/pkg_module_res.chpl, test/npb/ft/npadmana/ft_transposed.chpl, test/release/examples/users-guide/base/constParam-error.good, test/release/examples/users-guide/base/constParam.chpl, test/studies/prk/PIC/pic.chpl, test/types/real/transmute-toUint.chpl, test/types/string/sungeun/c_string/concat.chpl, test/types/string/sungeun/c_string/decls.chpl
The following constants will be no longer included in user programs
by default:
- `e`
- `log2_e`
- `log10_e`
- `ln_2`
- `ln_10`
- `pi`
- `half_pi`
- `quarter_pi`
- `recipr_pi`
- `twice_recipr_pi`
- `twice_recipr_sqrt_pi`
- `sqrt_2`
- `recipr_sqrt_2`
Adjusts line numbers in the user's guide document for the altered
test.
Adds a test locking in the deprecation messages.  Modifies tests in
the testing system to add explicit uses or imports of the Math module
where they now live, as appropriate.
Note: modified one test to stop using `e` period - I believe it was a typo
and the test author intended to refer to a different symbol in the test
instead instead based on how other parts of the test are written.  By
stopping including `e` by default, it should now be easier to notice when
these …
=> Deprecate including these math constants by default

compiler/util/files.cpp
For the C compiler, this computes dependencies via #includes when compiling the generated .c file(s) the first time, such that any subsequent edits to them by developers will re-compile the appropriate files as necessary.
The approach taken here is to throw our standard DEPEND_CFLAGS when doing a '--savec' compile, and to include the generated .d files within the Makefile in such cases.
Resolves https://github.com/Cray/chapel-private/issues/4467
=> Compute dependencies when using --savec

modules/packages/TOML.chpl, modules/standard/Time.chpl, test/classes/delete-free/shared/shared-default-arg-nil-ref.chpl, test/classes/delete-free/shared/shared-default-arg-nil.chpl, test/deprecated/DateTimeSymbols.chpl, test/deprecated/useDeprecatedDateTimeNames.chpl, test/deprecated/useDeprecatedDateTimeNames.good, test/library/draft/arrow/parquetHeaders.chpl, test/library/packages/Curl/check-http-setopt.chpl, test/library/standard/DateTime/datetimeInitWithDateAndTime.chpl, test/library/standard/DateTime/readWriteDatesTimes.chpl, test/library/standard/DateTime/readWriteDatesTimes.good, test/library/standard/DateTime/strptime.chpl, test/library/standard/DateTime/strptime2.bad, test/library/standard/DateTime/strptime2.chpl, test/library/standard/DateTime/testDate.chpl, test/library/standard/DateTime/testDatetime.chpl, test/library/standard/DateTime/testDatetimeTZ.chpl, test/library/standard/DateTime/testNow.chpl, test/library/standard/DateTime/testTime.chpl, test/library/standard/DateTime/testTimezone.chpl, test/library/standard/DateTime/testTimezoneConversions.chpl, test/library/standard/DateTime/unstableTimezones.chpl, test/library/standard/DateTime/writeDateTime.chpl, test/library/standard/Time/stonea/getCurrentDayOfWeek.chpl, test/studies/comd/elegant/arrayOfStructs/util/Util.chpl
Update 'datetime', 'timedelta', 'enum Day', 'getdate', 'gettime' to use our regular
capitalization rules. So the new names are 'dateTime', 'timeDelta', 'enum day',
'getDate', and 'getTime'.
Update modules that use dateTime. Update tests to use the new names.
Add a deprecated test for the old names.
=> Update DateTime symbols for camelCasing

modules/standard/BigInteger.chpl, test/library/standard/BigInteger/resultAsArgument.chpl, test/library/standard/BigInteger/resultAsArgument.good
Several BigInteger functions which have `ref result` and some `const ref arg` can fail when the same argument is passed to both of these, but only when asan is enabled with `CHPL_COMM!=none`. This issue is not caused by the same argument being passed, but seems to be related to an underlying issue within gmp. For example, `mul` is affected in all cases, but `powMod` is not affected at all and `sub` is only affected in certain combinations. 
Example
```
var a = new bigint(5);
var b = new bigint(6);
mul(a, a, b); // a now contains garbage
```
- remove `.localize()` for affected functions
- list of affected functions
```chapel
proc pow(ref result: bigint, const ref base: bigint, exp: int)
proc pow(ref result: bigint, const ref base: bigint, exp: uint) 
proc nextprime(ref result: bigint, …
```
=> Fix BigInteger issue with a result parameter used as an argument

test/gpu/native/assertOnFailToGpuize.4.good
The 4th .good file for this test didn't get checked in. Add it now.
=> Fix a test with a missing .good

test/release/examples/benchmarks/shootout/regexdna.chpl, test/release/examples/benchmarks/shootout/regexdna.good
https://github.com/chapel-lang/chapel/pull/21201 deprecated `readstring` in favor of `readString` and/or `readAll(string)`, but left the deprecated symbol in `test/release/examples/benchmarks/shootout/regexdna.chpl`. This PR corrects that error.
=> Fix `readstring` deprecation in shootout benchmark

test/library/packages/LinearAlgebra/correctness/inv-test.chpl, test/library/packages/LinearAlgebra/correctness/testEigen.chpl
inv-test.chpl relies on pi while testEigen.chpl relies on sqrt_2 and recipr_sqrt_2, all of which are no longer included by default.
Double checked that the solution worked
=> Add a use of the Math module to these tests

modules/standard/BigInteger.chpl
Removes extra local checks in four places that PR #21990 missed.
- remove extra locale checks in `rootrem`, `sqrtrem`, `divR2Exp` and `mod`
- NA
- locally
--- 
[Reviewed by @bmcdonald3 ]
=> Remove extra locale checks previously missed in BigInteger

compiler/optimizations/gpuTransforms.cpp, test/gpu/native/studies/transpose/transpose-throughput.graph, test/gpu/native/studies/transpose/transpose-time.graph, test/gpu/native/studies/transpose/transpose.chpl, test/gpu/native/studies/transpose/transpose.gpu-execopts
This PR adds a memory coalesced benchmark that does not use our three-dimensional kernel launch primitive. To make this work, this version of the benchmark includes code to compute the intended two-dimensional coordinates of each thread and block given their one-dimensional indices. 
To make this benchmark work, I also fixed two issues in the compiler:
* The `set blockSize` primitive did not work in multidimensional loops (note that these loops still have one-dimensional _kernels_ -- the outer loop is turned into a kernel, the inner loop is run on the GPU). This was because the GPU transformations expected the primitive to be in the top-level block in the outer loop body, but a multidimensional for loop will have a `CForLoop` inside the outer `CForLoop`, wrapping the primitive. This PR …
=> Add a `foreach`-based optimized transpose benchmark

frontend/include/chpl/framework/ErrorWriter.h, frontend/lib/parsing/parser-error-classes-list.cpp, frontend/lib/resolution/resolution-error-classes-list.cpp, test/errors/parsing/controlFlow.2.good, test/errors/scope-resolution/redefinition/redefinition-variables.1.good, test/errors/scope-resolution/redefinition/redefinition-variables.2.good, test/errors/scope-resolution/redefinition/redefinition-variables.chpl
Some detailed error messages have the flaw of printing out an entire definition/statement when code is printed. This is problematic in the cases of records and multi-line definitions, which can span multiple lines (records in particular can be very long). Thus, it's possible to accidentally print a huge chunk of the program as part of the error. This PR introduces a new wrapper struct, `JustOneLine`, which wraps a code location and ensures that only one line of code is printed. The PR also adds two helper methods to `ErrorWriter`, namely `codeForDef` and `codeForLocation`, which offer a more declarative and abstract way of printing code. These two methods use `JustOneLine`. Finally, this PR converts existing errors to using this functionality, thereby reducing the risk of printing too …
=> Add support to one-line-only code output to detailed error messages

make/compiler/Makefile.intel
This is a follow-on to #20426 that changes another warning to a diagnostic around LLVM_NODISCARD for the Intel Classic Compiler 2023.1.0 release.  Without it, the GASNet team was seeing:
```
/path/to/chpl-home/third-party/llvm/install/support-only-linux64-x86_64/include/llvm/ADT/StringRef.h(781): error #1292: unknown attribute "clang::warn_unused_result"
LLVM_NODISCARD
^
```
in a developer build (with WARNINGS=1 on).  Note that this is a subtle shift from the previous warning that didn't seem to recognize the namespace rather than the attribute itself.
I have not tested this, but the GASNet team did test the equivalent (made the same change to their sources) and saw that it let the build go through, though in a noisy manner due to the diagnostic messages.
I did not do any research to see …
=> Add another workaround for LLVM_NODISCARD for intel compilers

test/functions/fcf/Motivators.chpl
Adjust a FCF test to invoke each test manually instead of walking
over an array of tests in a loop. This should fix a sporadic bug
where test names would not print correctly.
The test `test/functions/fcf/Motivators.chpl` has been failing off
and on with a fairly consistent failure mode. All the tests in the
module are stored in an array (an array of FCFs), and then that
array is iterated over and the tests run sequentually. Before each
test is run, its name is printed out.
The bug is that sometimes the test name will not display - nothing
appears when something like "test2a" should be showing. I am not
sure what is causing this bug, but it is flakey and hard for me to
pin down. I was able to see the bug locally on `df14e4`, but after
making some environment changes, it seems to have …
=> Adjust FCF test to call tests manually instead of walking array

frontend/include/chpl/uast/PrimOp.h
It turns out not all compilers provide a default `std::hash` implementation for enums. This caused failures in the build after I merged #22022, where I was using an `unordered_map` with enum keys. This PR fixes the build failures by adding a template specialization for `std::hash` and the specific enum that was used as a map key.
=> Provide a std::hash implementation for PrimitiveTag

modules/dists/BlockDist.chpl, modules/dists/StencilDist.chpl, modules/internal/OwnedObject.chpl, modules/internal/SharedObject.chpl, test/library/packages/Search/correctness.chpl
This removes 'proc type borrow()'. It is not used and would not work even if it were, because it accesses a field on 'this'. Also touches up a couple of comments.
=> Add 'inline' on .borrow()

compiler/main/driver.cpp, modules/internal/localeModels/gpu/LocaleModel.chpl, test/gpu/native/jacobi/flags-warn-unstable-internal.good, test/gpu/native/jacobi/flags-warn-unstable.good, test/gpu/native/jacobi/flags.compopts, test/gpu/native/jacobi/jacobi.chpl
https://github.com/chapel-lang/chapel/pull/22033 changed how unstable warnings are generated and broke a test for `--warn-unstable`.
We were generating the unstability message through the GPU locale model, which is now suppressed without `--warn-unstable-internal`. This PR moves the message to the compiler, adjust the relevant test and rewords the message.
Test:
=> Generate GPU unstability warning in the compiler, reword the message

modules/standard/BigInteger.chpl, test/library/standard/BigInteger/resultAsArgument.chpl, test/library/standard/BigInteger/resultAsArgument.compopts, test/library/standard/BigInteger/resultAsArgument.good
Fixes a regression in BigInteger in that occurred in Arkouda.
In discussion on an Arkouda failure with @bmcdonald3, we realized that more than just the previously addressed functions (PR #22039) fail when the `ref result` is also used as one of the `const ref` arguments with `.localize()`. This is caused by gmp performing swaps under the hood.
From @bmcdonald3 
OK, so I feel like what we've learned can be summarized as:
- problems can happen when a single bigint value is passed as both the result and an operand
- this has been in the code for a long time, but the recent refactoring brought it to the surface since we are doing that pattern more frequently
- this could potentially be a problem in any of the gmp functions, we just have to get unlucky enough for one to surface
And how we …
=> Fix regression in BigInteger with ref arguments

util/test/perf/perfgraph.js
The perf graph has missing partition for 1.30 release.
Fix: Fix the branch date
=> fix the branch date

modules/standard/IO.chpl
A few IO tests failed in 32-bit testing because of a missing cast to `c_ssize_t` in `readBinary`. This PR corrects those failures.
=> Fix some 32-bit failures related to `readBinary(arr)`

util/cron/test-homebrew.bash
Recent changes in homebrew is not overriding the tarfile download.
Added code to remove the cached tar file before running brew install.
=> Add code to remove the cache before running brew install

compiler/passes/convert-uast.cpp, frontend/include/chpl/resolution/resolution-types.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/VarScopeVisitor.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/resolution-types.cpp
Replaces the vector used in ResolutionResultByPostorderID with a hash map to avoid wasting memory.
Previously ResolutionResultByPostorderID stored a `std::vector` of `ResolvedExpression`s with indexes corresponding to IDs. This is replaced with a `std:unordered_map` with IDs as keys and `ResolvedExpression`s as values. This saves memory because we often store IDs that do not start at 0 and/or are non-consecutive. For example, storing IDs `10`, `11`, `15` would previously allocate 16 "slots", vector indices 0-15, with only 3 being used. With a map, we do not rely on empty placeholder slots to keep track of IDs, so we can allocate only slots that are being used.
I conducted testing to ensure this change had no negative impact on performance, detailed in …
=> Replace vector with map in ResolutionResultByPostorderID

doc/rst/developer/bestPractices/buildingdocs.rst, doc/rst/developer/bestPractices/index.rst, doc/rst/meta/compiler-internals-doxygen/index.rst, doc/rst/meta/compiler-internals-no-doxygen/index.rst
This change is for consistency with how we refer to Dyno in code and other documentation.
Resolves https://github.com/Cray/chapel-private/issues/4143.
Testing:
=> Change 'Compiler Library'->'Frontend Library' in docs

compiler/resolution/preFold.cpp, test/library/standard/Reflection/getField-managed.chpl, test/library/standard/Reflection/getField-managed.good
Implements a fix for the bugs described in #14154 and #20491 where `getField` and `getFieldRef` get wrapper class fields instead of the actual class. This does not match the behavior of other `Reflection` methods such as `getFieldName` and `numFields`.
- add a check to `PRIM_FIELD_BY_NUM` for managed ptrs and look through the `chpl_p` pointer.
- add a new test that checks `getField` and `getField` on classes
- paratest
---
[reviewed by @dlongnecke-cray ]
closes #14154
closes #20491
closes Cray/chapel-private#4677
=> Fix `Reflection.getField` on wrapper classes

runtime/src/launch/slurm-srun/launch-slurm-srun.c
The `--cpu-bind` argument should be passed to `srun`, not `sbatch`. Also, `--cpus-per-task` should be passed to both `sbatch` and `srun` as of `slurm` 22.05.
Resolves https://github.com/Cray/chapel-private/issues/4683 and https://github.com/Cray/chapel-private/issues/4682.
=> Fix sbatch/srun arguments

third-party/qthread/Makefile, third-party/qthread/README, third-party/qthread/qthread-src/config/qthread_check_hwloc.m4, third-party/qthread/qthread-src/configure, third-party/qthread/qthread-src/include/config.h.in
`Qthreads` configuration contained a static list of sets of potential link-time arguments needed to link against `hwloc`. The `configure` script would iterate through this list until a set of arguments was successful. This was problematic because it required keeping the list up-to-date with respect to `hwloc` changes. This commit makes the check configurable as it is only beneficial to Chapel developers as any problems with linking against `hwloc` will be found when compiling an app. It's not worth the cost of maintaining the list nor the complexity of adding support for `pkg-config`.  The `--disable-hwloc-configure-checks` argument to `configure` turns off the `hwloc` link check. The link check also tests whether or not `hwloc` supports distance information. If the link check is …
=> Make qthreads config-time check of hwloc linking configurable

compiler/llvm/clangUtil.cpp, compiler/main/driver.cpp, frontend/include/chpl/util/clang-integration.h, frontend/include/chpl/util/filesystem.h, frontend/lib/util/clang-integration.cpp, frontend/lib/util/filesystem.cpp, frontend/test/clang/testClangCC1Args.cpp
Follow-up to PR #21944
PR #21944 improved extern block in the dyno scope resolver by adding integration with clang. However, there were some problems with computing the correct clang arguments, especially when `CHPL_LLVM_GCC_PREFIX` is used. Additionally, there were problems with LLVM 11 and 12 since SHA256 was added to the LLVM Support library in LLVM 13. This PR fixes these problems.-
=> Fix problems with extern block improvement PR.

doc/rst/technotes/gpu.rst
We should document what version of third-party dependencies for GPU support (e.g. cuda/rocm) are needed.
This PR adds that information to the GPU tech note.
Some other changes:
* I change the requirements section to talk about the CUDA Toolkit and ROCM rather than `nvcc` and `hipcc` as (apart from inferring a default for `CHPL_GPU_CODEGEN` we don't actually use these, rather we use APIs that are packaged as part of these toolkits).
* Since I no longer mention `nvcc` or `hipcc` in the requirements section, I removed the line about how we "automatically deduce the path to these libraries based on the location of the ``nvcc``/``hipcc`` executable." I think if we want to mention this the requirements section isn't the place to do it and in the "GPU Related Environment Variables" section we …
=> Update GPU technote with CUDA/ROCM version requirements

test/gpu/native/cudaOnly/gpuAddNums/README, test/gpu/native/cudaOnly/gpuAddNums/gpuAddNums.chpl, test/gpu/native/rocmOnly/README, test/gpu/native/rocmOnly/extern_kernel_launch.chpl
We have some tests in our GPU suite that call out to CUDA/ROCM externs. On the one hand keeping these tests around might have some value, on the other if the maintenance cost is anything but trivial we should probably just get rid of them. This PR adds a README to explain that.
This is in response to this issue:
https://github.com/Cray/chapel-private/issues/3195
=> Readme for GPU extern only tests

compiler/codegen/codegen.cpp, compiler/include/files.h, compiler/main/driver.cpp, compiler/util/files.cpp, compiler/util/misc.cpp, frontend/include/chpl/framework/Context.h, frontend/lib/framework/Context.cpp
Follow-up to PR #21944
When compiling for GPU, the compiler `fork()`s and the child process needs to use the same temp dir. But, after PR #21944, the child process was deleting the temp dir. This PR fixes that problem. While there, it cleans up a memory leak when reconfiguring the Context and it adds documentation for a few Context methods.
Future Work:
* remove `tmpdirname.h` and `tmpdirname.cpp` from the compiler. These are currently built but unused.
* Consider renaming `Context::Configuration` to `Context::InitConfiguration` or something like that to indicate it is only the initial context of the configuration.
* Adjust the 2-argument Context constructor to handle the case that the temp dir was generated in the old context but the new configuration specifies a different temp dir.
* …
=> Avoid deleting the temp dir in the GPU subprocess

modules/packages/ZMQ.chpl
The current ZMQ close function is externing to a function with incorrect arguments for the linger option. This PR removes the linger argument, making `close()` only close the socket. The linger argument is one of many options, so it seems like it would make sense to either support all of the options or none of them.
See: http://api.zeromq.org/4-2:zmq-setsockopt
=> Fix ZMQ socket.close function

test/gpu/native/cudaOnly/gpuAddNums/gpuAddNums.chpl
Follow-up to PR #21944 which makes extern blocks more strict about needing the relevant `#include`s. This PR updates a GPU test to have the extern block have the `#include`s for the features used.
=> Include missing headers in gpuAddNums.chpl

test/gpu/native/rocmOnly/extern_kernel_launch.chpl
Follow-up to PR #21944.
Add `#define __HIP_PLATFORM_AMD__`. Somehow this was previously being communicated to clang when compiling the extern block but not so with the new current extern block logic.
=> Update extern_kernel_launch.chpl test with a #define

test/gpu/native/streamPrototype/gpuStream.graph, test/gpu/native/streamPrototype/stream.chpl, test/gpu/native/streamPrototype/stream.gpu-keys
As opposed to GB/s. That is: use units that are powers of 2 rather than powers of 10.
=> Report GPU Stream performance in GiB/s

modules/standard/CTypes.chpl, test/types/cptr/cross_type_cast.chpl, test/types/cptr/cross_type_cast.good
Fixes incorrect strict aliasing check behavior for casts between pointers-to-pointers, originally introduced in https://github.com/chapel-lang/chapel/pull/21934.
The check will now recurse into pointee types when both `from` and `to` pointee types are pointers types themselves. I experimentally verified with GCC that the warning for casts between double pointers appears to work recursively. Since we always allow casting a typed C pointer to and from a void C pointer, this is also allowed for pointees.
Should fix nightly failures for the following tests:
- `interop/fortran/FortranCallChapel/chapelProcs`
- `interop/fortran/genFortranInterface/chapelProcs`
Both of these tests cast a `c_ptr(c_string)` to `c_ptr(c_ptr(c_char))`, and the pointee type change from `c_string` to `c_ptr(c_char)` …
=> Fix strict aliasing check for pointers-to-pointers

compiler/AST/type.cpp, compiler/codegen/cg-symbol.cpp, compiler/codegen/cg-type.cpp, compiler/include/type.h
Removes generation of `const` qualifiers for const C pointers in C backend, which was originally added in https://github.com/chapel-lang/chapel/pull/21913.
This was causing some nightly test failures because we do not currently consistently emit `const` qualifiers in our C backend. For example, one particular failure was occurring because `writeln` is codegen'd to take non-const, even though its arguments are a const varargs in Chapel. This causes some C compilers to (rightly) warn that we are discarding a `const` qualifier.
I have replaced the places where the `const` qualifier would be printed with TODOs, including an explanation of why we can't do it now.
This does remove some functionality that we would in theory like to have, however there is a lot of work to do with emitting `const` …
=> Stop emitting const qualifiers in generated C code

modules/standard/AutoMath.chpl, modules/standard/Math.chpl, test/deprecated/Math/erfErfc.chpl, test/deprecated/Math/erfErfc.good, test/library/standard/Math/erf.chpl, test/library/standard/Math/erfc.chpl, test/release/examples/benchmarks/hpcc/ptrans.chpl, test/studies/hpcc/PTRANS/PTRANS.chpl, test/studies/hpcc/PTRANS/jglewis/ptrans_2011-blkcyc.chpl, test/studies/hpcc/PTRANS/jglewis/ptrans_2011.chpl
In earlier discussions on which Math symbols should be included
in all programs by default, we decided to stop including `erf` and
`erfc`.
<details>
The commit for this ends up looking a little odd so that we don't accidentally
build the Math module by default as well - make an undocumented version that
Math and the deprecated version can call, so that Math depends on AutoMath and
the two versions stay in sync until the deprecated version is removed. This
strategy was previously followed for other symbols in the Math module.
</details>
Adds a test locking in the deprecation warning.
Adds a use of the Math module to tests that were relying on these functions
being included by default
=> Stop including erf and erfc in all programs by default

modules/standard/IO.chpl, test/io/ferguson/io_test.chpl, test/io/readLine/lines.chpl
adds an option to the `lines()` iterator on `fileReader` to remove the trailing newline.
```chapel
iter fileReader.lines(stripNewline = false)
```
- implement `stripNewline`
- augment an existing `lines()` test to test new option
- add a new test just for `fileReader.lines()` to test boundary conditions
- paratest
---
closes #19547
closes cray/chapel-private#4734
=> Implement stripNewline option for lines() on a fileReader

compiler/llvm/clangUtil.cpp, frontend/include/chpl/util/clang-integration.h, frontend/lib/util/clang-integration.cpp, test/extern/ExternBlockClangError.good
Follow-up to PR #21944.
This PR fixes a problem in warning option handling for the clang invocation in the new extern block handling. The warning options were not being handled correctly. Clang configures warnings through diagnostics options & these were being constructed with default settings. With this PR, the diagnostic options are computed from the clang command line. This PR switches two other clang integration points to use the pattern that handles the warning options correctly.
This PR is meant to resolve failures with the gsl_demo.chpl test.
=> Fix clang integration warning handling

test/c2chapel/c2chapel-tester.good
Fixes `test/c2chapel/c2chapel-tester.good` for addition of const pointer test in https://github.com/chapel-lang/chapel/pull/21913.
The const pointer c2chapel test appears to be working properly, but I had neglected to update this `.good` to expect output from it.
Testing:
=> Fix c2chapel-tester const pointer test

modules/standard/CTypes.chpl, test/types/cptr/c_ptr_c_string.chpl, test/types/cptr/c_ptr_c_string.good
This is a second attempt at fixing an incorrect strict aliasing warning when casting from a `c_ptr(c_string)` to a `c_ptr(c_ptr(c_char))`, which is causing nightly test failures.
This is a follow up to the first attempt in https://github.com/chapel-lang/chapel/pull/22116 which fixed part of the issue. Although comparing pointee types is fixed, the strict aliasing check was incorrectly warning on the cast from the contained pointee types `c_string` to `c_ptr(c_char)`. This is not tripped for a direct cast from a `c_string` to `c_ptr(c_char)` as that is separately implemented, and not handled via the cptr-to-cptr that has a strict aliasing check.
This PR causes the check to treat a `c_string` as a pointer to `c_char` for the purpose of aliasing. It works for casting either to or from a …
=> Fix strict aliasing check for c_string pointee casts

test/gpu/interop/cuBLAS/cuBLAS.chpl
Suppresses a warning for casting between incompatible pointee types in the `cpu_to_gpu` function in GPU `cuBLAS` test, by casting through `c_void_ptr`.
Testing:
=> Suppress pointer cast strict aliasing warning in cuBLAS test

test/types/records/generic/issue-22011.bad, test/types/records/generic/issue-22011.chpl, test/types/records/generic/issue-22011.future
Issue #22011 describes an internal error that occurs during the use of a `c_ptr` with generic record. It looks like the issue is that the genericity of `bar` is not known at the time that its field access procs are being resolved. If `bar` is explicitly made generic, things work out. Ideally, there shouldn't be a difference (as long as we allow for implicitly generic fields -- see discussion on https://github.com/chapel-lang/chapel/issues/19120) in user output. We definitely would rather avoid throwing internal errors.
Simple future - not reviewed.
=> Add a future to lock down internal error in issue #22011

frontend/include/chpl/resolution/resolution-types.h, frontend/test/resolution/testInteractive.cpp
Previously, this code in `testInteractive` used `ID::contains` to check if it was safe to access the function's resolution results. This worked because the resolution results always had a vector big enough to contain all the IDs in the function. However, recent changes (https://github.com/chapel-lang/chapel/pull/21765), switched this from a vector to a map, which is only filled on-demand. In a const-access, it's possible that calls to `byAst` will not find an `ID` in the map when previously it would be found in the vector. This PR fixes such issues in `testInteractive` by using `byAstOrNull` instead of the (possibly-throwing) `byAst`.
=> Fix testInteractive code to not assert the existence of resolve results

compiler/AST/checkAST.cpp, compiler/include/passes.h, compiler/main/checks.cpp
Calls to the "checkNoUnresolveds" check have been commented out for quite a long time. I spent a small amount of time investigating what it might take to re-enable, but the internal state of the compiler has changed so much since this test was disabled that it's probably not worth trying to get working again.
Since we've lived without this check for so long, this PR removes the check so that we don't have to think about maintaining it anymore.
=> Remove old, unused checkNoUnresolveds function

modules/standard/CTypes.chpl, runtime/include/chpltypes.h, runtime/include/gpu/cuda/chpl-gpu-gen-includes.h, runtime/include/gpu/rocm/chpl-gpu-gen-includes.h
This PR modifies the `c_pointer_return_const` runtime function added in https://github.com/chapel-lang/chapel/pull/21913 to return a `void*` instead of `const void*`, addressing nightly failures related to discarding this const qualifier in generated C code that uses it.
Previously, `c_pointer_return` took a `void*` and returned it as a `void*`, and `c_pointer_return_const` took a `const void*` and returned it as a `const void*`. Unfortunately, returning a `const void*` does not work as we get warnings in the C backend for discarding the `const` qualifier, as our C backend does not consistently use `const` qualification; `c_pointer_return_const` needs to return a `void*`.
This PR is a follow up to https://github.com/chapel-lang/chapel/pull/22122, which removed `const` qualifier in …
=> Make c_pointer_return_const return a non-const pointer

test/studies/diffusion/heat_2d.chpl, test/studies/diffusion/heat_2d_dist.chpl, test/studies/diffusion/heat_2d_dist.skipif
Improvements to heat equation FD solvers (under `test/studies/diffusion`) based on Brad's post-merge feedback here: https://github.com/chapel-lang/chapel/pull/22105
These changes are mostly stylistic. I also removed the `.skipif` on the distributed version s.t. it also runs for `CHPL_COMM=none`.
=> Improvements to diffusion tests

Makefile
This PR fixes build failures introduced with PR #21876 for `chpldoc` when `chpl` was not built first. It adds a step to the top-level `Makefile` for the `chpldoc` target to also build LLVM, which is necessary when `CHPL_LLVM` is set to `none` or `bundled` 
reviewed by @vasslitvinov - thanks!
=> fix(chpldoc): add LLVM as a build step for chpldoc

frontend/include/chpl/types/TupleType.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/can-pass.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/types/TupleType.cpp, frontend/test/resolution/testGenericDefaults.cpp, frontend/test/resolution/testMethodCalls.cpp, frontend/test/resolution/testTuples.cpp
This PR fixes a couple of bugs in our resolution of generic functions/methods and adds tests for code involving:
- optional type formals
- type methods on generic types
This PR also adds basic resolution for creating a tuple by multiplying a ``param int`` by a type.
This PR also renames some tuple-creating functions that were previously named in terms of variable arguments, but have broader usability in other contexts.
There were some other minor bugs exposed by existing testing:
- fix to 'canPass' so that a type query will always succeed
- bug where primitives could be resolved as method calls
Testing:
=> dyno: minor fixes to support domains and arrays

runtime/src/launch/slurm-srun/launch-slurm-srun.c, test/runtime/configMatters/launch/jhh/reservation/README, test/runtime/configMatters/launch/jhh/reservation/bin/sbatch, test/runtime/configMatters/launch/jhh/reservation/bin/sinfo, test/runtime/configMatters/launch/jhh/reservation/hello.chpl, test/runtime/configMatters/launch/jhh/reservation/reservation.py, test/runtime/configMatters/launch/jhh/reservation/sub_test
The `slurm-srun` launcher uses `sinfo` to determine the number of cores and the threads per core on the nodes. The output from `sinfo` is sorted by the number of cores so if there are heterogeneous nodes the launcher will limit each locale to the fewest number of cores per node. However, if there is a `slurm` reservation that has fewer cores it will show up in the `sinfo` output even if the launcher isn't running in the reservation, causing the launcher to use the wrong number of cores. This commit fixes that by making the launcher ignore any `sinfo` output for reservations that the launcher is not in.
Resolves https://github.com/Cray/chapel-private/issues/4561.
=> Handle reservations correctly in the slurm-srun launcher

modules/standard/AutoMath.chpl, modules/standard/Math.chpl, modules/standard/Random.chpl, test/deprecated/Math/depLdexp.chpl, test/deprecated/Math/depLdexp.good, test/modules/bradc/printModStuff/foo.good, test/separate_compilation/serialization/testGenLib.MyMod.good, test/separate_compilation/serialization/testGenLib.OtherMod.good, test/separate_compilation/serialization/testGenLib.both.good
In earlier discussions of which Math symbols should be included
in all programs by default, we decided to stop including `ldexp`.
<details>
The commit for this ends up looking a little odd so that we don't
accidentally build the Math module by default as well - make an
undocumented version that Math and the deprecated version can
call, so that Math depends on AutoMath and the two versions stay
in sync until the deprecated version is removed. This strategy was
previously followed for other symbols in the Math module.
Note that, unlike previous PRs along these lines, this is not
sufficient to prevent Math.chpl's inclusion in some of our tests
that track which files are traversed (though it is still sufficient to
prevent it from being initialized, which I think means it is not
generated for …
=> Deprecate including ldexp by default and move it to the Math module

test/runtime/configMatters/launch/jhh/reservation/reservation.py
Fixes an issue where `test/runtime/configMatters/launch/jhh/reservation/reservation.py` parses the output of `printenv` by newline. This does not work when `SHELL` is `bash`, because exported functions (and any environment variable really) may contain newlines. This breaks the parsing as each `line` is no longer a complete environment variable.
~~The fix is to use `-0` with `printenv` to delimit by NUL not newline.~~
The better fix, as pointed out by @jhh67 is to directly use `os.environ` directly. This also eliminates the need for the `for` loop.
---
[Reviewed by @jhh67 ]
=> Change reservation.py test to parse env with `os.environ`

test/runtime/configMatters/launch/jhh/reservation/reservation.py
Invoking `printchplenv --simple` and parsing the output doesn't work very well because `printchplenv` can produce warning messages. Instead, use `printchplenv.py` directly to create a dictionary of the Chapel configuration.
Also, fix a bug in `CHPL_RT_LOCALES_PER_NODE` processing and parsing the batch file name from the `sbatch` output.
=> Improve Chapel config processing in reservation tests

compiler/llvm/clangUtil.cpp, doc/rst/technotes/gpu.rst, test/gpu/native/extern/extern_c_test.c, test/gpu/native/extern/extern_c_test.h, test/gpu/native/extern/main.chpl, test/gpu/native/extern/main.good
Resolves https://github.com/chapel-lang/chapel/issues/21905.
This PR changes how the Chapel compiler compiles `.c` files that are passed through the command line or the `require statement` with `CHPL_LOCALE_MODEL=gpu`. The main motivation for this change is that when you are compiling for GPU you have to use C++ linkage even if your files are `.c`.
I was hoping that this can also address https://github.com/chapel-lang/chapel/issues/21906, but that doesn't seem to be the case.
Test:
=> Fix linkage for C files with the GPU locale model

compiler/llvm/clangUtil.cpp
Shortly after merging https://github.com/chapel-lang/chapel/pull/22089, I realized that it led to always adding `-Wno-unknown-cuda-version` while compiling `.c` files. However, this is only relevant when `CHPL_LOCALE_MODEL=gpu`. I suspect it may be a problem if a clang that doesn't support that is used with C interop.
Test:
=> Stop generating GPU-related flags without the GPU locale model

frontend/lib/parsing/parser-error-classes-list.cpp, frontend/lib/uast/post-parse-checks.cpp, test/errors/parsing/controlFlow.1.good, test/errors/parsing/controlFlow.2.good, test/errors/parsing/controlFlow.chpl, test/studies/shootout/reverse-complement/bradc/revcomp-blc-gcc8-algs.chpl
This came up in https://github.com/chapel-lang/chapel/issues/21924
We might be able to support these statements in `foreach` statements (as well as `forall`). However, for `foreach`es we don't do anything special for them at the moment. Until we do, we should disallow to make them more aligned with `forall` loops.
This only required one test change.
Test:
=> Disallow break, return and continues with labels in foreach loops

modules/packages/MatrixMarket.chpl, modules/packages/ProtobufProtocolSupport.chpl, modules/packages/RecordParser.chpl, modules/standard/IO.chpl, modules/standard/Regex.chpl, modules/standard/Subprocess.chpl, test/deprecated/IO/offsetWithLocking-deprecated.good, test/deprecated/IO/offsetWithLocking.chpl, test/deprecated/IO/offsetWithLocking.compopts, test/deprecated/IO/offsetWithLocking.good, test/deprecated/IO/underscoreMethods.chpl, test/deprecated/IO/underscoreMethods.cleanfiles, test/deprecated/IO/underscoreMethods.good, test/io/literals/match-literal.compopts, test/io/literals/read-literal.compopts, test/library/packages/canCompileNoLink/HDFStest.compopts, test/regex/empty-channel-matches.compopts, test/regex/ferguson/readfinf.compopts, test/regex/ferguson/readfre.compopts, test/regex/ferguson/rechan.compopts, test/regex/regex-and-channel-todos.compopts, test/studies/labelprop/labelprop-tweets.chpl, test/studies/labelprop/labelprop-tweets.compopts, test/studies/shootout/mandelbrot/ferguson/mandelbrot-opt2.compopts, test/studies/shootout/mandelbrot/ferguson/mandelbrot2-opt.compopts
In discussion on #19827, the decision was made to remove `_mark` on `fileReaders` and `fileWriters`. `_mark` has the same implementation as `mark`, so it was decided to relax the restriction on `mark` and update the documentation to explain the locking behavior.
In an offline discussion, similar consensus was reached about `_revert`, `_commit`, and `_offset`
- deprecate `fileReader._mark` and `fileWriter._mark`
- extract `mark` implementation to a helper, as it is the same for `fileReader` and `fileWriter`
- deprecate `fileReader._revert` and `fileWriter._revert`
- deprecate `fileReader._commit` and `fileWriter._commit`
- deprecate `fileReader._offset` and `fileWriter._offset`
- extract `offset` implementation to a helper, as it is the same for `fileReader` and `fileWriter`
- remove …
=> Deprecate IO module's `_mark`, `_revert`, `_commit`, and `_offset`

test/gpu/native/continue/contFromLoop.chpl, test/gpu/native/continue/contFromLoop.good, test/gpu/native/continue/contFromLoop2.chpl, test/gpu/native/continue/contFromLoop2.good
This PR adds two tests that I was planning to add in https://github.com/chapel-lang/chapel/pull/21620.
These tests lock the behavior discuss/reported in https://github.com/chapel-lang/chapel/issues/21924
=> Add two tests using `continue` in a kernel

modules/standard/AutoMath.chpl, modules/standard/Math.chpl, test/deprecated/Math/gammas.chpl, test/deprecated/Math/gammas.good, test/library/standard/Math/bradc/math32bits-more.chpl, test/library/standard/Math/lgamma.chpl
In an earlier discussion of which Math symbols should be included
in all programs by default, we decided to stop including `lgamma`
and `tgamma`.  Move them to the Math module.
<details>
The commit for this ends up looking a little odd so that we don't
accidentally build the Math module by default as well - make an
undocumented version that Math and the deprecated version
can call, so that Math depends on AutoMath and the two versions
stay in sync until the deprecated version is removed. This strategy
was previously followed for other symbols in the Math module. 
</details>
Adds a use of the Math module to two tests to enable them to
continue to pass without deprecation warnings.
Adds a new test to lock in the deprecation warnings.
=> Deprecate including lgamma and tgamma by default

modules/standard/Map.chpl
Most other errors thrown by module functions are listed this way, and I think this is what's intended.
=> Map.chpl: Use :throws Error: instead of :throws: Error

test/studies/shootout/reverse-complement/bradc/revcomp-blc-gcc8-algs.chpl, test/studies/shootout/reverse-complement/bradc/revcomp-blc-gcc8-algs.compopts
My changes to this test in https://github.com/chapel-lang/chapel/pull/22167 resulted time outs. The correct implementation requires foreach intents (https://github.com/chapel-lang/chapel/issues/18500). Strangely enough, changing `foreach` to `for` should work but results in what looks to be an infinite loop.
For now, add a comment in the source, and comment out the relevant compopt.
Test passes locally with this PR.
=> Don't correctness-test foreach based revcomp variant as it times out

test/gpu/native/measureGpuCycles.chpl
For some reason we're seeing this test now fails our nightly tests for AMD.
The test works by running three successively longer loops, measures each, and errors out if our GPU clocks don’t say each loop takes longer than the last. These loops read/write from an array. I think what’s happening is with unified memory the first loop ends up taking a long time because it has to “pull” that data from the host.
So it makes sense this would fail. It's not obvious to me why it's not failing for NVIDIA and why this would regress.
Nevertheless, it seems like the right thing to do is update the test to have a warmup loop to ensure the array is on the device before we do any timing runs.
=> Add warmup loop to measureGpuCycles.chpl test

test/classes/jade/error-messages/generic-field-nil.chpl, test/classes/jade/error-messages/generic-field-nil.compopts, test/classes/jade/error-messages/generic-field-nil.good, test/classes/jade/error-messages/generic-field-nil.prediff
Adds a test to lock in an error message for a generically managed nilable field.
Error message was added in #19709, merging this PR should allow closing of #19613 and #18923
- NA
- `test/classes/jade/error-messages/generic-field-nil.chpl`
- local testing
---
Note: the error message is not the best, but is better than the previous issues of internal asserts and set faults. Issue discussing this captured here #22184
closes #19613
closes #18923
=> Lock in error message for generically managed nilable fields

modules/standard/Time.chpl, test/deprecated/timeFactoryFunctions.chpl, test/deprecated/timeFactoryFunctions.good, test/library/packages/Curl/check-http-setopt.chpl, test/library/standard/DateTime/fromTimestampComm.chpl, test/library/standard/DateTime/testDate.chpl, test/library/standard/DateTime/testDatetimeTZ.chpl
Rename factory functions in the Time module to start with 'create'. Add
deprecated versions of the old names and update other uses of them in the
Time module. Add a test/deprecated/ test for them.
Update a few tests to use the new names.
=> Rename Time factory functions

test/functions/fcf/Motivators.chpl, test/functions/fcf/Motivators.good
A test that prints out function names (by calling `writeln` on a
function value) is not printing names on certain configurations
(right now, specifically LLVM `--fast`). Comment out a call to
the offending `test5` until the bug can be fixed.
=> FCFs: Comment out call to test until bug is fixed

compiler/main/driver.cpp, util/chplenv/chpl_gpu.py, util/chplenv/printchplenv.py, util/chplenv/utils.py
This PR also adds a check for the requirement that when configured to target NVIDIA GPUs we have an installed version of the CUDA API >= 11.0 and < 12 and when configured to target AMD we have an installed version of the HIP API >= 4 and < 6.
In https://github.com/chapel-lang/chapel/issues/22087 we had discussions about whether this and a few associated requirements should be done as part of the build for the compiler and/or runtime but ultimately decided to have it as part of the compiler build on the basis that:
- Although some of these requirements are not needed of `chpl` does not get to the codegen some are needed at build time for `chpl`.
- If the user doesn't care about getting to the codegen pass an easy workaround is to use the new 'none' GPU layer. I add this as a suggestion in …
=> Validate installed CUDA and ROCM version

modules/internal/ChapelGpuSupport.chpl, modules/internal/LocaleModelHelpGPU.chpl, modules/internal/localeModels/gpu/LocaleModel.chpl, modules/standard/ChplConfig.chpl, modules/standard/GPU.chpl, runtime/include/chpl-gpu-impl.h, runtime/include/chpl-gpu.h, runtime/src/chpl-gpu.c, runtime/src/gpu/cuda/gpu-cuda.c, runtime/src/gpu/rocm/gpu-rocm.c, test/gpu/native/nvlink.chpl, test/gpu/native/nvlink.execopts, test/gpu/native/nvlink.good
This PR has some initial work for getting Chapel to work with nvlink.  The punchline seems to be: I think all we need to do this is call `cuCtxEnablePeerAccess` between all pairs of GPUs that support it.  So I've added some no doc'd functions to the GPU module to query/enable this as well as a no doc'd enableGpuP2P config constant that will enable peer-to-peer access wherever its possible on startup.
More specifically, this PR:
* Adds the aforementioned `enableGpuP2P` config constant (which lives in the `ChapelGpuSupport` internal module)
* Adds no doc'd `canAccessPeer` and `setPeerAccess` to `GPU` module, that call out to:
* Added `chpl_gpu_can_access_peer` and `chpl_gpu_set_peer_access` in runtime (CUDA and ROCM versions)
* Adds `CHPL_GPU_CODEGEN` as a no doc'd function to the …
=> Add (no doc'd) functions to enable P2P GPU access

test/runtime/configMatters/launch/jhh/reservation/reservation.py, util/test/send_email.py
If smtp instantiation failed `send_email.py` would try to call `smtp.quit()` on the non-existent smtp object. Now uses a context manager to avoid this problem.
=> Fix smtp instantiation in send_email.py

util/chplenv/chpl_gpu.py
This PR (https://github.com/chapel-lang/chapel/pull/22170) introduced code that validates the installed version of a GPU SDK (i.e. CUDA or ROCm). My validation code works by looking for a certain file that contains the version; unfortunately it looks like the name of this file is different for different versions of both CUDA and ROCm. This PR updates to look for other known names/formats.
Since this is failing our nightly tests I plan to merge this quickly but we may want to consider if this is robust enough to handle future versions or deal with versions that we say we're supporting but haven't explicitly tested.  Some thoughts:
- We could compile a small program using CUDA/ROCm that calls the API to report the version and use that. This seems awfully heavy-handed to me.
- We could also …
=> Make gpu SDK version checking code more robust

compiler/llvm/clangUtil.cpp, compiler/llvm/llvmAggregateGlobalOps.cpp, compiler/llvm/llvmGlobalToWide.cpp, util/chplenv/chpl_llvm.py
This PR just applies the remainder of @daviditen 's work on building the compiler with LLVM 15, and is all his work. See https://github.com/Cray/chapel-private/issues/4028, particularly [this comment](https://github.com/Cray/chapel-private/issues/4028#issuecomment-1401237911) describing the status of the work as he left it off.
With this patch applied, all the remaining build failures with LLVM 15 are from usages of typed pointers.
The code in this PR is cherry picked from https://github.com/chapel-lang/chapel/commit/d93f2d34b361f0c50970a8432d6413f1cee2ca4c. The only modification is to remove LLVM 15 from the list of supported LLVM versions in `chpl_llvm.py`, as LLVM 15 support is not done and this would cause failures on systems where it is present.
Testing:
=> Apply patch to build compiler with LLVM 15

frontend/lib/uast/post-parse-checks.cpp, test/functions/fcf/ExternBlock.bad, test/functions/fcf/ExternBlock.chpl
Resolves #22150
This PR adds a post-parse check to make sure that extern blocks only appear at module scope. We might relax that in the future but currently, having an extern block at non-module scope leads to strange behavior.
=> Emit an error for extern blocks not a module scope

test/execflags/configs/privateconfigs-help-set.good, test/execflags/configs/privateconfigs-help.good
More test updates needed for <https://github.com/chapel-lang/chapel/pull/22157> which adds an 'enableGpuP2P' flag. Tests that lock down the `--help` output need to be updated to account for this.
=> Fix gasnet tests missing 'enableGpuP2P' in help message

third-party/gasnet/Makefile, third-party/gmp/Makefile
For some time, we have relied on a GASNet target that was introduced for our sake, `amudprun-host`, which builds `amudprun` in a way that permits it to be run on the host rather than target in a cross-compiling setting.  It seems that, since forever, that target has relied on default values of `CC=gcc` and `CXX=g++` which work in most places, but of course wouldn't work on a system that didn't have such compilers available.  This changes our invocation of the build line to pass along our own predetermined values for HOST_CC and HOST_CXX for use instead.
While here, I also updated third-party/gmp/Makefile to use the same Makefile variables rather than an explicit `shell` command (which is how my first draft of this change was also written until I found myself thinking "surely there must be …
=> Build amudprun-host with host values of CC/CXX

util/chplenv/chpl_gpu.py
I found another install of CUDA that doesn't have either `version.json` or `version.txt` so I've added in yet another way of trying to extract the CUDA version: using `nvcc --version`, which is perhaps what I have should have done from the start.
I'm thinking maybe the `version.json` and `version.txt` files are put there by the package manager rather than something officially added by NVIDIA.
I figured while I was at it I should add a similar fallback for ROCm using `hipcc`.
Annoyingly enough for ROCm the version returned by `hipcc --version` is not the same as the ROCm version.  On my system for `hipcc --version` I got output like this:
```
$ hipcc --version
HIP version: 4.4.21432-f9dccde4
AMD clang version 13.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-4.5.2 21432 …
```
=> chplenv: try and get CUDA/HIP version from nvcc and/or hipcc

compiler/resolution/fcf-support.cpp, test/functions/fcf/Motivators.chpl, test/functions/fcf/Motivators.good
Fix a bug where FCF names were not displaying when printed with
`writeln()`. Generate `writeThis` and `encodeTo` method stubs
for FCF superclass types.
Special thanks to @lydia-duncan for sharing a backtrace of a run
that segfaulted.
TESTING
Reviewed by @lydia-duncan. Thanks!
=> Generate write method stubs for FCF superclass types

compiler/codegen/library.cpp, frontend/lib/resolution/resolution-queries.cpp
Resolves https://github.com/Cray/chapel-private/issues/4782
This PR fixes two warnings from GCC 13 (note that some build configurations use `-Werror` so these can also be fatal build errors)
* Renames some local variables from `requires` since that is a keyword in C++ 20
* Adds wrapper functions to avoid false-positive 'possibly dangling reference to a temporary' warnings. See also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108165 which seems to indicate such false positives will not be fixed. If this approach turns out to be unweildy, alternatives include disabling this warning or using a GCC-specific pragma.
=> Fix warnings when building compiler with GCC 13

test/runtime/configMatters/launch/jhh/reservation/SKIPIF, test/runtime/configMatters/launch/jhh/reservation/reservation.py, test/runtime/configMatters/launch/jhh/reservation/sub_test
Added `SKIPIF` to indicate that these are not performance tests. Also made file paths in the output conform to those produced by `sub_test.py`.
=> Fix slurm-srun reservation tests

frontend/include/chpl/resolution/scope-types.h, frontend/lib/resolution/scope-queries.cpp, frontend/lib/resolution/scope-types.cpp, frontend/test/resolution/testScopeResolve.cpp, frontend/test/resolution/testScopeTypes.cpp
This fixes the issue presented in https://github.com/chapel-lang/chapel/issues/22217. By using an arbitrary-length list of checked conditions, we don't have to worry about not being able to represent a particular combinations of checks.
To support the change, this introduces a new struct `FlagSet` that contains a list, and represents their logical disjunction. Combined with the fact that individual `Flags` values represent logical _conjunctions_ of their set fields, this means that `FlagSet` effectively represents a sum-of-products representation of what has been checked so far (or should be excluded).
I used an LLVM `SmallVector` to represent the list of Flags, in the hope of reducing the memory footprint. Since this PR replaces a single `int16_t` with a whole set, it does cause an …
=> Dyno: switch CheckedScopes to using a list of past filters instead of a single Flags filter 

test/unstable/unstableGMP.skipif
This test uses the GMP module, so needs to be skipped if CHPL_GMP is none.
=> Add a skipif for unstableGMP test when CHPL_GMP==none

Makefile, util/buildRelease/gen_release, util/buildRelease/testReleaseHelp
The release documentation has instructions for using protobuff with Chapel that haven't worked since it was introduced because we didn't actually bundle the code into the release.  This PR does so and also adds a testRelease step to make sure it builds OK.  
In reviewing this PR, Michael pointed out that this check requires a particular version of protobuff to be available on the system doing the test.  Since we only run these tests in a small number of Jenkins configs, the plan is to merge, see if any of those break, and comment out the checks if they do.  If this check causes issues in the future, we can consider satisfying the dependence, beefing up the code to check for it, or commenting out the check then.
While here, I made the `make clobber` step for protobuff ignore failures out …
=> Bundle protobuff support into the release

util/chplenv/chpl_llvm.py
When compiling on M1 macs with the following variables (the CXX/CC overrides are needed because Apple Clang poses as `gcc`/`g++` 😠 ):
```Bash
export CHPL_HOST_CXX=/opt/homebrew/Cellar/gcc/13.1.0/bin/g++-13
export CHPL_HOST_CC=/opt/homebrew/Cellar/gcc/13.1.0/bin/gcc-13
export CHPL_HOST_COMPILER=gnu
```
CMake immediately reports that the C++ compiler cannot create executables, reporting:
```
g++-13: error: unrecognized command-line option '-stdlib=libc++'
```
I tracked this down to an option being thrown by `llvm-config`, which is always invoked nowadays due to our use of the support library. This PR attempts to fix the issue by removing `-stdlib=libc++` from the `llvm-config` flags when the host compiler is `gnu`. 
Tested locally with M1 mac, and on paratest …
=> Filter out `-stdlib` flags when compiling for GCC

compiler/AST/CatchStmt.cpp, compiler/passes/convert-uast.cpp, compiler/passes/scopeResolve.cpp, frontend/include/chpl/resolution/resolution-types.h, frontend/include/chpl/resolution/scope-types.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/default-functions.cpp, frontend/lib/resolution/disambiguation.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/lib/resolution/scope-types.cpp, frontend/test/resolution/testScopeResolve.cpp, frontend/test/resolution/testScopeTypes.cpp, test/visibility/import/enablesUnqualified/multipleUnqualified/badName-this.good
On main, running
```Bash
chpl hello.chpl --dyno --dyno-scope-bundled --no-dyno-scope-production &>errors.txt
```
produces a file that's 1054 lines long. This is because the Dyno scope resolver doesn't yet handle all the functionality that the production scope resolver takes on. This PR attempts to start bridging the gap, though it still doesn't quite get hello world compiling. It does, however, produce a file with far fewer error lines (476). It does so by:
* Fixing up the Dyno conversion for forwarding declarations
* Adding support for properly converting (parenless) methods 
* Hiding methods from Dyno identifier lookups by default (to match the fact that the production scope only returns methods in some situations)
* Directly refering to the _owned and _shared types instead of relying …
=> Make dyno scope resolver work better without production

frontend/lib/resolution/scope-queries.cpp, test/visibility/import/enablesUnqualified/multipleUnqualified/badName-this.good
Methods can be imported, but the search function for checking if an identifier is valid to be imported didn't check for modules, leading to errors. This tweaks that setting, making sure that modules can be imported.
I'll be adding regression tests for this tomorrow, don't want the build to be broken overnight.
Reviewed by @dlongnecke-cray -- thanks!!
=> Fix import validity checking to allow importing methods

modules/packages/CopyAggregation.chpl
This addresses some failures in `test/optimizations/autoAggregation/arrTypes.chpl` that were seemingly introduced in #22165 (which introduced `c_addrOf()` and changed some behaviors of `c_ptrTo()`).
I can't currently explain why the changes are necessary and haven't tried to spend the time to get my head around them, but stumbled across the failures while doing some post-merge sanity checking of my own PR, so am filing this in hopes of reducing testing noise tonight.
=> Change some c_ptrTo() calls to c_addrOf() in CopyAggregation.chpl

compiler/codegen/codegen.cpp, compiler/include/llvmVer.h
This PR updates the Chapel compiler to request typed pointers from LLVM 15 instead of opaque pointers. This is a transitional strategy while we are migrating to LLVM 15 and the opaque pointers. Using typed pointers with LLVM 15 allows us to update calls to get the pointer element type in another way, and then existing LLVM assertions check that the type we provided is consistent with the pointer type. This mode can be disabled or removed once we have completely migrated to LLVM 15 and removed the reliance on pointer element types.
=> Transitionally, disable opaque pointers in LLVM 15

test/extern/ExternBlockClangError.chpl, test/extern/ExternBlockClangError.good, test/extern/bradc/externClock.c, test/release/examples/primers/cHelper.c, test/release/examples/primers/fact.c, test/visibility/require/helperFiles/baz.c, test/visibility/require/helperFiles/foo.c
Clang 15 gives a new warning (or error with `-Werror`) for code like `int foo(void); int foo() { }`. The `int foo()` is declaring something other than a 0-argument function and the warning has to do with that. So, this PR updates tests with C code using this pattern to avoid it in order to ease transition to LLVM 15.
=> Update tests to prepare for clang 15

third-party/chpl-venv/chpldoc-requirements2.txt
Pin the version of urllib3 used so that nightly tests stop breaking
when running sphinx. Special thanks to @lydia-duncan for walking me
through how to pin the version of a Python module.
=> Pin the version of urllib3

modules/standard/IO.chpl, test/types/range/minMaxStrides.chpl, test/types/range/minMaxStrides.good
Fixes an issue introduced in PR #22225 which inconsistently printed on different platforms, due to an incorrect format string.
From @vasslitvinov: Also added a change to the IO docs to clarify '%i'
Ran full paratest
=> Fix test print formatting issue

test/runtime/configMatters/comm/ugni/overflow-mem-region-table.prediff
Save the original output from the
`test/runtime/configMatters/comm/ugni/overflow-mem-region-table` test to help with debugging failures.
=> Save original output from overflow-mem-region-table test

modules/internal/ChapelRange.chpl, modules/internal/OwnedObject.chpl, modules/standard/ChapelIO.chpl
Print range alignment without normalizing it, since it should be stored already normalized since #22225.
Restore the type proc `owned.borrow()`, which was mistakenly removed in #22038.
=> Simplify printing of range alignment and restore borrow()

util/chplenv/chpl_llvm.py
This PR addresses problems with linker errors when using static libraries for LLVM and clang version 15. LLVM 15 support is not yet complete so & it requires other patches (not in this PR) to build. These additional libraries are not needed when using dynamic LLVM and clang libraries.
=> Include additional dependencies to build with LLVM/clang 15

compiler/AST/primitive.cpp, compiler/codegen/cg-expr.cpp, compiler/codegen/cg-symbol.cpp, compiler/codegen/cg-type.cpp, compiler/codegen/codegen.cpp, compiler/include/codegen.h, compiler/include/genret.h, compiler/include/llvmUtil.h, compiler/include/llvmVer.h, compiler/llvm/clangUtil.cpp, compiler/llvm/llvmUtil.cpp
This PR is focused on removing cases where cg-expr.cpp was relying on typed pointers (since LLVM 15 and future versions use opaque pointers). Generally speaking, it accomplished that by separately computing the relevant type. In some cases, I relied on computing the value type for a GlobalVariable or AllocaInst, since the types are available in those cases as well and that case is relatively common.
This PR also fixes some problems with `getLLVMStructureType` where it was still storing the pointer type in some cases (follow-up to PR #21376), and it updates the ternary expression computation to keep class types as pointers (follow-up to PR #21394 -- AFAIK the use of `getLLVMStructureType` was still returning the pointer type for classes before this PR).
Future Work:
* The LLVM backend …
=> Avoid relying on typed LLVM pointers in cg-expr.cpp

compiler/codegen/cg-symbol.cpp
This PR is focused on removing cases where cg-symbol.cpp was relying on typed pointers (since LLVM 15 and future versions use opaque pointers). For the most part, it relied on using that information available in a different way from LLVM (from a GlobalVariable or a relevant StructType).
=> Avoid relying on typed LLVM pointers in cg-symbol.cpp

compiler/optimizations/gpuTransforms.cpp, runtime/include/chpl-gpu-impl.h, runtime/include/chpl-gpu.h, runtime/src/chpl-gpu.c, runtime/src/gpu/cuda/gpu-cuda.c, runtime/src/gpu/rocm/gpu-rocm.c, test/gpu/native/largeLoop.chpl, test/gpu/native/largeLoop.good
This addresses a bug reported in https://chapel.discourse.group/t/gpu-forall-over-large-range-doesnt-enqueue-enough-gpu-threads/21659.
It looks like we have been using `int`s in the runtime for `num_threads`, and similarly `dtInt[INT_SIZE_32]` while generating index computation code within GPU kernels. Both of these limited us to run GPU kernels on loops with bounds that can fit in 32-bit ints. This is an arbitrary limitation as GPUs can run more than 2**32 threads. This PR fixes that.
While there improves `--debugGpu` output in the following ways:
- adds grid dimensions to the output. Ideally, we should move this computation from the `chpl-gpu-impl` layer to `chpl-gpu` layer and print the info out with `startVerboseGpu` output. But that's more than I am willing to do in this bug fix PR
- …
=> Selectively use 64-bit ints for GPU kernel index computation 

test/extern/bradc/require/usefoobarbaz.precomp, test/interop/C/makefiles/commandLineLib.precomp, test/interop/C/makefiles/requireStmt.precomp
This PR updates a few test precomp files that create .o files to use same C compiler / linker as Chapel.
On systems where 'gcc' defaults to a configuration that is not position-independent-executables, the clang-15 might be configured to be position-independent, leading to a linker error when a separately compiled .o file is linked with a Chapel program.
Note that this is very system dependent. It occurs on a SLES 15 but not on an Ubuntu 23.04 system.
To fix, just compile these .o files with the same compiler.
=> Update a few .precomp files for LLVM 15

modules/internal/Bytes.chpl, modules/internal/String.chpl, modules/packages/ArgumentParser.chpl, modules/standard/IO.chpl
This seems to be the form chpldoc is expecting that all the other modules but these use consistently, and formats the `Error` specially in the docs.
=> Replace ":throws: Error:" with ":throws Error: "

compiler/codegen/cg-type.cpp
This PR is focused on removing cases where cg-type.cpp was relying on typed pointers (since LLVM 15 and future versions use opaque pointers). The one case it updates was computing a global pointer type from a local pointer type, so if the pointer type is opaque, it can propagate that information.
=> Avoid relying on typed LLVM pointers in cg-type.cpp

compiler/llvm/llvmGlobalToWide.cpp
Removes usages of typed pointers (except with macro guards) from `llvmGlobalToWide.cpp` in preparation for the deprecation of typed pointers in LLVM 15.
Uses the `HAVE_LLVM_TYPED_POINTERS` macro from #22240 to use old typed pointer code when LLVM is supporting typed pointers.
Testing:
=> Remove typed pointer usages from llvmGlobalToWide

compiler/codegen/cg-expr.cpp
Follow-up to PR #22240 to fix an unused variable when using LLVM 11. This PR just removes an ifdef that is unnecessary since LLVM 11 supports the newer form of CreateLoad.
=> Fix an LLVM 11 compatability issue

compiler/llvm/llvmDebug.cpp
Adds macro guards so the usage of a typed pointer only occurs if our LLVM has typed pointers enabled.
On Michael's recommendation I am ifdef'ing out this entire section of code that is relying on pointer element types. It is likely already not working properly, and does not seem to be tested beyond basic functionality.
Testing:
=> Ifdef out typed-pointer-dependent llvmDebug code

compiler/codegen/cg-expr.cpp, compiler/codegen/codegen.cpp, compiler/include/llvmUtil.h, compiler/llvm/llvmUtil.cpp
This PR is focused on removing cases where codegen.cpp was relying on typed pointers (since LLVM 15 and future versions use opaque pointers). The one case it updates was computing the value to load from a GlobalVariable, so it moves `tryComputingPointerElementType` (used in earlier work to compute the value type of a GlobalVariable since these are always pointers in LLVM) to make it available here and uses it.
=>  Avoid relying on typed LLVM pointers in codegen.cpp

util/chplenv/chpl_compiler.py
Follow-up to #21985 to resolve a Cygwin configuration failure where `CHPL_HOST_CC` is set to `gcc.exe` and the compiler detection logic is unable to infer `CHPL_COMPILER=gnu` from that.
=> Handle computing CHPL_COMPILER=gnu from CC=gcc.exe

CMakeLists.txt, compiler/CMakeLists.txt, frontend/CMakeLists.txt, frontend/include/chpl/resolution/scope-types.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/can-pass.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/return-type-inference.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/lib/resolution/scope-types.cpp, frontend/test/resolution/testReturnTypes.cpp, frontend/test/resolution/testScopeTypes.cpp, make/compiler/Makefile.clang, make/compiler/Makefile.gnu
The focus of this PR is to enable `CHPL_LLVM=none` builds when using LLVM 16 to provide the LLVM Support library. That is slightly complicated for two reasons:
* LLVM 16 requires C++17 and the LLVM 16 headers will not compile with just C++14
* LLVM 16 deprecates `llvm::Optional` and replaces it with `std::optional`. However, it is not a clean deprecation, since some methods are spelled differently, and so causes errors in some cases (and not just warnings).
This PR:
* updates build scripts to use C++17 when working with LLVM 16. LLVM 16 headers will not compile with C++14.
* adds `#if` blocks to adjust for the different spelling of `optional` methods in LLVM 11 vs LLVM 16.
* updates BorrowedIdsWithNameIter to avoid a C++ `std::iterator` template deprecated in C++17
* removes some useless …
=> Enable CHPL_LLVM=none builds with LLVM 16

compiler/llvm/llvmAggregateGlobalOps.cpp
Follow-up to PR #21121. (Note: that PR was merged before we could test its code changes.)
This PR fixes some problems in computing the pointer cast instructions with LLVM 15. It also adjusts the alignment logic to handle stores as well as loads.
=> Fix problems in llvmAggregateGlobalOps.cpp for LLVM 15

modules/internal/SharedObject.chpl
Fixes a bug where concurrently deinitializing shared objects could result in the underlying `ReferenceCount` object being leaked.
This failure mode was difficult to reproduce, but came up in `test/types/records/copy-elision/copy-elision-default-behavior.chpl` which exhibits the following pattern:
```chapel
proc test() {
var s: sync int;
var x = new shared myClass();
begin {
var y = x;
writeln(y);
s.writeEF(1);
// y deinitialized here
}
s.readFE();
// x deinitialized here
}
sync { test(); }
```
Here, the two deinitializers can be executed concurrently, which was occasionally preventing the `ReferenceCount` object from being deleted.
=> Fixing sporadic memory leak in `shared` deinitializer

compiler/llvm/clangUtil.cpp
This PR updates the regexp that determines what version of a `oclc_isa_version` file to use based on the value of `CHPL_GPU_ARCH`.  There's some question in my head about if merely updating the regexp is the right thing to do, I go into more detail about that in the underlying issue: <https://github.com/chapel-lang/chapel/issues/21964>.  But this PR is an improvement over what we currently have.
=> Update regexp to determineOclcVersionLib based on CHPL_GPU_ARCH

modules/internal/ChapelRange.chpl
Adds a check to `chpl__mod` to only call `abs` on the `modulus` if it is well defined. 
`abs` is implemented as `if i < 0 then -i else i`. If this code is passed `min(int(?w))`, it will return the same value since there is no valid positive representation at that bit width. This is fine under normal codegen, but in optimized code an optimizer may decide this is invalid and insert `poison`.
This resolves an issue seen in our nightly testing
- add signed min check for `chpl__mod`, which could also insert poison values.
---
=> Avoid calling abs on at integer min in chpl__mod

test/extern/ferguson/mismatch-errors/mismatch-ri-iv.bad, test/extern/ferguson/mismatch-errors/mismatch-ri-iv.prediff
Adds a `.prediff` stripping the symbol name on the offending line from the compiler output (and corresponding `.bad`), so additional symbols before the line do not affect the test.
In this case, this was necessary because moving to opaque pointers removes a bitcast that was previously required.
[trivial test change, not reviewed]
Testing:
=> Fix LLVM IR symbol name comparison in mismatch-ri-iv.bad

modules/standard/List.chpl, modules/standard/Map.chpl, test/library/standard/List/testJson.chpl, test/library/standard/List/testJson.good, test/library/standard/Map/testJson.chpl, test/library/standard/Map/testJson.good
This PR adds some basic support for reading and writing standard ``map``s and ``list``s with the ``%jt`` formatting option.
Testing:
=> Add some basic JSON IO support to standard Map and List

compiler/llvm/llvmDebug.cpp
Guards the `myGetTypeName` function with `ifdef HAVE_LLVM_TYPED_POINTERS`, as its only usage is guarded with the same. This is just to silence an unused function warning in compilation.
The function's usage was just ifdef'd in https://github.com/chapel-lang/chapel/pull/22262.
=> Ifdef an llvmDebug helper used only in ifdef'd code

test/runtime/jhh/SKIPIF, test/runtime/jhh/lps_test.py, test/runtime/jhh/sub_test
Handle Slurm reservations correctly, and also general improvements wrt to `skipif` and the output from this test as required by the test infrastructure.
=> Add support for Slurm reservations

util/cron/test-gpu-rocm.gasnet.bash
This PR added `util/cron/test-gpu-rocm.gasnet.bash` but I realize I had a line `CHPL_COMM=none` in there, which we definitely wouldn't want for nightly gasnet testing.
This PR fixes that.
=> Remove CHPL_COMM=none out of test-gpu-rocm.gasnet.bash

modules/standard/GPU.chpl, runtime/include/gpu/cuda/chpl-gpu-gen-includes.h, runtime/include/gpu/rocm/chpl-gpu-gen-includes.h, test/gpu/native/atomics.chpl, test/gpu/native/atomics.compopts, test/gpu/native/atomics.good
This PR adds various undocumented gpuAtomic procedures to the GPU module.  These correspond to various `atomic` functions in the CUDA/HIP APIs. Note that I only write (or have implementations for) the corresponding GPU bound (i.e. `__device__`) implementation for these procedures.  In the GPU module I have these procs call `assertOnGpu` so attempting to use them in CPU code should fail.  In theory I could imagine these falling back to calling the CPU-bound functions we have in our runtime library for atomics but I imagine eventually we'll want the normal Chapel `atomic` datatypes to call out to these undcoumented APIs, in which case I think we would want the code in `Atomics.chpl` to be responsible for dispatching as appropriate rather than code in the GPU module.  So IOW: I don't think …
=> Gpu atomics

runtime/src/qio/regex/bundled/re2-interface.cc, test/regex/empty-string-matches.chpl, test/regex/empty-string-matches.good, test/regex/matchesOnlyEnd.chpl, test/regex/matchesOnlyEnd.good, test/regex/regex-and-channel-todos.bad, test/regex/regex-and-channel-todos.chpl, test/regex/regex-and-channel-todos.good
Resolves a bug where `regex.match('$')` would always return an offset equal to the start of the match. This was due to incorrectly copying the correct offset from RE2 in the runtime shim.
- remove check for an empty match in runtime shim for RE2
- add #20431 as a test - `test/regex/matchesOnlyEnd.chpl`
- paratest + futures
---
resolves  #20431
Fixes some of the bugs in #20864, updated future accordingly
=> Fix bug in regex.match('$')

modules/standard/Sys.chpl
`Sys.sys_getenv` was deprecated without replacement in https://github.com/chapel-lang/chapel/pull/20126; however, the deprecation message said to find a replacement in the OS module. This PR corrects the deprecation message.
=> Fix erroneous deprecation message on `sys_getenv`

test/GRAPHFILES
In the performance meeting, we decided that it didn't make sense to be tracking the memory leaks in the performance suite now that memory leaks send out a test failure and we are handling those as a part of regular triage. Based on this, we are dropping memory leaks from the performance tracking suite.
=> Drop memory leaks graphs from performance tracking suite

test/optimizations/bulkcomm/asenjo/redistBlockToCyclic/PARACR-BC-bulk.chpl
This test relies on log2, which we are going to stop including in all user programs by default.  For the test to continue working in the future, we need a use of the Math module
Checking a fresh checkout with gasnet (where the test is run)
=> Add a use of the Math module to avoid a deprecation warning in this test

frontend/include/chpl/parsing/parsing-queries.h, frontend/lib/parsing/parsing-queries.cpp, frontend/lib/uast/post-parse-checks.cpp, test/modules/paths/int/ChapelNumLocales.chpl, test/modules/paths/noWarnUnstableInt.good, test/modules/paths/noWarnUnstableStd.good, test/modules/paths/std/Path.chpl, test/modules/paths/warnUnstableBoth.chpl, test/modules/paths/warnUnstableBoth.compopts, test/modules/paths/warnUnstableBoth.good, test/modules/paths/warnUnstableInt.chpl, test/modules/paths/warnUnstableInt.compopts, test/modules/paths/warnUnstableInt.good, test/modules/paths/warnUnstableStd.chpl, test/modules/paths/warnUnstableStd.compopts, test/modules/paths/warnUnstableStd.good
This PR addresses an issue where modules that serve as replacements for standard or internal modules using the compiler flags `--prepend-internal-module-dir` and `--prepend-standard-module-dir` were not being marked as internal or standard like the modules they replaced. This caused some issues where adding the `--warn-unstable` flag would generate lots of messages from the usage of unstable features inside those replacement modules. 
To treat those modules appropriately, we now store a list of paths given through those compiler flags and treat modules found in those paths as either internal or standard. This will help keep the behavior similar when using replacement modules combined with the `--warn-unstable` flag.
TESTING:
reviewed by @dlongnecke-cray - thanks!
=> mark replacement modules using compiler flags as internal/standard

test/execflags/configs/privateconfigs-help-set.comm-none.good, test/execflags/configs/privateconfigs-help-set.good, test/execflags/configs/privateconfigs-help.comm-none.good, test/execflags/configs/privateconfigs-help.good, test/execflags/ferguson/help2.good, test/execflags/shannon/configs/help/basehelp.txt, test/execflags/shannon/help.good
Add the new GPU related config to some good files that test `--help` output.
Tests pass with local and gasnet configs.
=> Fix some good files that include --help output

test/extern/ferguson/global-var-type-mismatch.skipif
Follow-up to PR #22277.
The new error checking of `extern var` Chapel type vs C type only works with the LLVM backend, so skip the test of it for `CHPL_LLVM=none`.
=> Add skpif for global-var-type-mismatch

test/llvm/with-opaque-ptrs/function-args/ref_nonnull.skipif, test/llvm/with-typed-ptrs/function-args/ref_nonnull.skipif
Follow-up to PR #22275. Before that PR, this directory had a directory-wide skipif containing 'COMPOPTS <= --no-local'. Since the other test seems to be passing, this PR just adds that constraint to ref_nonnul.skipif.
=> Add missing skip for --no-local for ref_nonnul

test/users/npadmana/gsl_demonstration/gsl_demo.chpl
PR #22284 deprecated including `log` by default, this test was missed while fixing deprecation messages.
---
=> Fix failing test case due to use of `AutoMath.log`

frontend/include/chpl/types/ArrayType.h, frontend/include/chpl/types/DomainType.h
Follow-up to PRs #22096 and #22097.
This PR just removes some useless `const` modifiers on return values. These cause warnings with some Intel compilers.
=> Remove useless 'const' on return values

compiler/codegen/cg-expr.cpp, compiler/codegen/codegen.cpp, compiler/include/llvmVer.h, compiler/llvm/llvmGlobalToWide.cpp
This PR enables opaque pointers when using LLVM 15. Opaque pointers are the default in LLVM 15 and the alternative of typed pointers is not supported in future versions of LLVM.
Besides adjusting ifdefs to enable it, this PR fixes two problems uncovered in testing this mode:
* Fixes a use of getContainedType in codegen.cpp that was computing a pointer element type.
* Fixes a problem with llvmGlobalToWide.cpp where a Constant GetElementPointer would not have its types adjusted from the Global types (which can use address space 100) to the wide pointer versions. It seems to me to be something that LLVM's ValueMapper should do, but for now we fix it in llvmGlobalToWide. Since I was working on llvmGlobalToWide this PR also makes a a simplification to that pass that should not change its …
=> Enable opaque pointers for LLVM 15

doc/rst/meta/compiler-internals-doxygen/base.rst, frontend/include/chpl/resolution/can-pass.h, frontend/include/chpl/resolution/scope-types.h, frontend/include/chpl/util/memory.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/can-pass.cpp, frontend/lib/resolution/return-type-inference.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/lib/resolution/scope-types.cpp, frontend/test/resolution/testReturnTypes.cpp, frontend/test/resolution/testScopeTypes.cpp
We currently have a `chpl::owned<T>`. If we make a symmetric addition of `chpl::optional`, aliased (initially) to `llvm::Optional`, and later (via an `LLVM >= 16` check) to `std::optional` directly (in case LLVM eventually removes `llvm::Optional`), we can get rid of all the LLVM-specific ifdefs in the frontend. The last ingredient here (thanks, @dlongnecke-cray !) is the fact that although `has_value` and `hasValue` are not the same name, both data types support `operator bool` and `operator *`, and most of the code can be written in terms of those and work for either optional implementation.
Michael says the following about LLVM16:
> I've verified that the latest revision builds successfully with LLVM 16 for the Support library (ie. with CHPL_LLVM=none). I …
=> Define new chpl::option data type to avoid some LLVM16 ifdefs

util/cron/common-native-gpu.bash, util/cron/test-gpu-cuda.aod.bash, util/cron/test-gpu-cuda.bash, util/cron/test-gpu-cuda.gasnet.bash, util/cron/test-gpu-rocm.bash, util/cron/test-gpu-rocm.gasnet.bash
We have `module load cudatoolkit` in the common cron script. This causes problems when you also load `rocm` without specifying `CHPL_GPU`. This PR:
- removes that top level `module load`
- explicitly sets `CHPL_GPU` in GPU test scripts
- while there, also sets `CHPL_COMM` explicitly because it took me a while to understand that it gets set automatically on CS.
=> Use modules and CHPL_GPU in test scripts individually

compiler/llvm/llvmGlobalToWide.cpp, util/chplenv/chpl_llvm.py
Follow-up to PR #22266 to fix build errors with LLVM 11 and 12.
=> Update llvmGlobalToWide to build with LLVM 11, 12

util/chplenv/chpl_llvm.py
Follow-up to PR #22317 because Mac OS X does not include pkg-config
=> Skip Spack LLVM 15 workaround on Mac OS X

util/cron/test-gpu-rocm.bash, util/cron/test-gpu-rocm.gasnet.bash, util/cron/test-perf.gpu-cuda.aod.bash, util/cron/test-perf.gpu-cuda.bash
- Use the correct module and environment for GPU performance test scripts.
- Use `CHPL_GPU_ARCH` for AMD testing explicitly.
I missed these in https://github.com/chapel-lang/chapel/pull/22314
=> More GPU test script fixes

compiler/include/driver.h, compiler/llvm/clangUtil.cpp, compiler/main/driver.cpp, doc/rst/technotes/gpu.rst, util/chplenv/chpl_gpu.py
With this PR:
- we no longer have a default `CHPL_GPU_ARCH` for AMD. It needs to be set by the user: This is because we currently don't have an AMD architecture compatibility story.
- fix `--gpu-arch` that was largely going unused
Test:
=> Drop default arch for AMD, wire `--gpu-arch` flag correctly

CMakeLists.txt, tools/chpldef/misc.cpp, tools/chpldef/misc.h
Adjust a call to a throwing function to be a call to a `noexcept`
function instead to silence GNU compiler errors. Adjust the top-level
`CMakeLists.txt` to only build `chpldef` if the files exist and we
are not in release mode.
Reviewed by @e-kayrakli. Thanks!
=> Fix issues which were causing chpldef to break release smoke-tests

test/gpu/native/multiLocale/NUMLOCALES
We replaced using the $CHPL_GPU_CODEGEN environment variable with $CHPL_GPU. This PR updates a test configuration file (`NUMLOCALES`) that should have been updated to account for that.
=> Fix NUMLOCALES script to use CHPL_GPU

util/cron/test-apptainer.bash
To fix the failure in jenkins run, changing the file permission and formatting.
=> Change the file permission and fix formatting in apptainer test

third-party/gasnet/Makefile
This PR resolves link errors when using `chpl` to compile a program on Cray XC when using CHPL_COMM=gasnet after PR #22316. It does so by adding `-fPIE` to the GASNet build flags when using LLVM 15 or newer as the target compiler.
The issue stems from LLVM 15 making PIE (Position-Independent-Executable) the default. At the same time, on XC, we build GASNet with a different C compiler (other than `clang-15`). The result is link errors when the clang linker tries to link with `-pie` but the GASNet library is not built in a way to enable that.
Details about the LLVM 15 change to enable `-fPIE` by default (from https://releases.llvm.org/15.0.0/tools/clang/docs/ReleaseNotes.html ):
> CMake -DCLANG_DEFAULT_PIE_ON_LINUX=ON is now the default. This is used by linux-gnu systems to decide whether …
=> Build gasnet with -fPIE when working with LLVM 15

runtime/src/gpu/amd/gpu-amd.c, runtime/src/gpu/nvidia/gpu-nvidia.c
Apparently the compiler now warns about the functions in `gpu-amd.c` and `gpu-nvidia.c`  that don't have arguments but also don't include `(void)` in their argument list. This PR fixes that.
Trivial; I'm going to merge without review.
=> Fix ROCm and CUDA build

test/gpu/native/extern/extern_c_test.c
Turns out one of the tests in ROCm CI also used C code, and used it without that `(void)` argument list! This PR fixes that.
=> Follow up for GPU compilation: add another missing (void) to fix a failing test

util/devel/test/vagrant/provision-scripts/chapel-setmakej.sh
Jenkins executor is not able to handle concurrent IO write from the test.
hudson.remoting.SynchronousCommandTransport.run(SynchronousCommandTransport.java:77)
https://chapel-ci.us.cray.com/job/portability-apptainer/17/console
Reducing the thread count to see if the issue resolves.
=> Reduce the thread size to avoid jenkins error

frontend/include/chpl/resolution/resolution-error-classes-list.h, frontend/include/chpl/resolution/resolution-types.h, frontend/include/chpl/types/DomainType.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/Resolver.h, frontend/lib/resolution/resolution-error-classes-list.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/resolution-types.cpp, frontend/lib/resolution/return-type-inference.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/lib/types/DomainType.cpp, frontend/test/resolution/testDomains.cpp, frontend/test/test-minimal-modules.h
Just like in the production compiler, this is implemented by invoking the standard library function `chpl__buildIndexType`. 
I also did the following:
* Fix up the `.rank` generated method on Domains to work with associative domains (it previously asserted that the domain should be rectangular)
* Fixed `setIsPrimitive` to be called `setIsBuiltin` (to match `isBuiltin` in `ResolvedExpression`)
Reviewed by @benharsh  -- thanks!
=> Add support for the `index(D)` operation to Dyno

test/gpu/native/studies/chop/chplGPU.skipif
Our nightly GPU + ChOP test clones the ChOp repos from GitHub. It does this via a `.skipif` script and this script has a step that pings GitHub to see if it's available and skips the test if it isn't. 
This test hasn't been running recently because of changes in our test configuration environment that would cause it to always fail when pinging GitHub. However, this isn't due to actual network connectivity issues and the subsequent `git clone` in the script would have worked had we let it.
It also turns out any output from a `.skipif` script that isn't directed to stderr will get swallowed by `start_tests` so we won't see it in any of our log files.
This PR removes that initial check and redirects error output from that `.skipif` for this test to `stderr` so it will get logged.
=> Nightly ChOp test was silently skipifing; correct this

test/gpu/native/multiLocale/NUMLOCALES
For out nightly multilocale GPU testing, when using AMD, we want to set it to use 2 locales (this is what the machine we're testing this on has available, any more and things hang forever). We have a `NUMLOCALES` script to configured to do just that. This script works by looking at the value of `CHPL_GPU` and if that's "amd" returns 2 (otherwise it returns 4 for our nvidia testing).
The script extracts `CHPL_GPU` by running `printchplenv` and grepping for "CHPL_GPU", but that grep ends up being too broad and capturing other `CHPL_GPU` related variables. This PR fixes the regexp used to be more narrow and ensure we only capture `CHPL_GPU` and not something like `CHPL_GPU_MEM_STRATEGY`.
=> Fix bug causing us to use an invalid number of locales for multilocale gpu testing

util/cron/test-apptainer.bash, util/devel/test/apptainer/chapel-quickstart-delete.sh, util/devel/test/apptainer/tryit-jenkins.sh
Jenkins test run is causing the chapvm-build to crash with low disk space every time the test is executed.
Clean up each the images after testing each linux version.
=> Added code to delete the cloned repository and .sif inside each linux folders

test/library/packages/ProtobufProtocolSupport/endToEnd/enums/write.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/messagefield/write.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/repeatedfield/read.chpl, test/library/packages/ProtobufProtocolSupport/endToEnd/repeatedfield/write.chpl
Replaces the uses of `list.append` with `list.pushBack` in:
-  `library/packages/ProtobufProtocolSupport/enumsRunner`
- `library/packages/ProtobufProtocolSupport/messagefieldRunner`
- `library/packages/ProtobufProtocolSupport/repeatedfieldRunner`
=> Fixing protobuf test failures per `list.append` deprecation

modules/standard/GPU.chpl, test/gpu/native/createSharedArrayError.chpl, test/gpu/native/createSharedArrayError.good
This is intended to close #22309.
`[Summary: #Successes = 71 | #Failures = 0 | #Futures = 0 | #Warnings = 0 ]`
=> Improve createSharedArray error if argument type doesn't have a known size.

test/library/packages/LinearAlgebra/correctness/testElementwise.chpl, test/library/packages/LinearAlgebra/performance/SPA-perf.chpl
Replaces the uses of `list.append` with `list.pushBack` in:
- library/packages/LinearAlgebra/correctness/testElementwise
- library/packages/LinearAlgebra/performance/SPA-perf
=> Fixing linear algebra test failures per `list.append` deprecation

modules/internal/ChapelHashing.chpl, modules/standard/AutoMath.chpl, modules/standard/BitOps.chpl, modules/standard/Random.chpl, test/constrained-generics/random/MyRandom.chpl
Adds `pragma "fn synchronization free"` to all of the `extern proc` functions in `BitOps.chpl`. This should allow the compiler to infer that these functions do not cause hazards during optimization.
- Add `pragma "fn synchronization free"` to all 16 `extern proc`s in BitOps
- Add `pragma` to other uses of the BitOps `extern proc`s
- These really should just use BitOps, but there are other considerations (not importing standard modules in internal modules?)
- local testing of BitOps functions
---
=> Remove compiler checking for hazards on BitOps functions

util/cron/test-perf.gpu-cuda.bash
Our nightly GPU ChOp test is timing out when trying to clone from GitHub. The fix is to simply use an https based URL. The script that checks this repos out defaults to using an `https` based URL unless it gets overwritten by an explicitly set by a `$CHOP_URL` environment variable. This is what our cron script for the nightly job was doing so I just removed it being explicitly set (there's no need to override it the https based default is what we want).
=> Fix nightly GPU ChOP testing to not timeout on git clone

frontend/include/chpl/framework/Context-detail.h, frontend/lib/framework/Context.cpp, frontend/test/framework/testErrorTracking.cpp
The Dyno error silencing system currently ensures that _queries_ that produce errors while errors are being silenced are properly handled. However, if the an error occurs after silencing has started, but before a sub-query has been invoked, that error gets added to the current query's list of errors, and re-reported once the query result is re-used (which occurs when a new generation begins). This PR fixes this bug by tracking whether or not errors stored on a query result have themselves been silenced; this way, while results keep tracking all occurring errors, these errors are not accidentally re-emitted when they shouldn't be.
=> dyno: Fix silenced errors reoccurring in new generations

util/chplenv/chpl_gpu.py
Currently, running `CHPL_GPU=cpu` on my M1 mac (without a GPU) gives the following beauty:
> Exception: CHPL_GPU=cpu requires also setting CHPL_GPU_ARCH. Please check the GPU programming technote <https://chapel-lang.org/docs/technotes/gpu.html> for more information.
This is not correct (why would a CPU-only implementation require GPU_ARCH?) and is driven by a tiny logic error in `chpl_gpu.py`. This PR fixes that, so you can use t`CHP_GPU=cpu` without setting the architecture.
=> Tweak chpl_gpu to not require GPU_ARCH for cpu runs.

modules/standard/Collectives.chpl, test/deprecated/barrierCheck.chpl, test/deprecated/barrierCheck.good, test/deprecated/barrierReusable.chpl, test/deprecated/barrierReusable.good, test/parallel/taskPar/diten/barrierCheck.chpl
Make changes agreed to by the barriers ad-hoc sub team. Deprecate non-reusable
barriers and replace the barrier.check function with barrier.pending.
Add tests for the new deprecation and update the one test that had a problem
with this.
=> Deprecate non-reusable barriers and barrier.check in favor of barrier.pending

test/exercises/wavelet/ecgIO.chpl, test/exercises/wavelet/wavelet.skipif
`test/exercises/wavelet/wavelet.chpl` was failing under --baseline due to a throwing iterator not being inlined. This PR adds a skipif to skip
the test under the `--baseline` config.
=> Fix wavelet test failing under --baseline config

util/cron/test-linux64-gcc101.bash, util/cron/test-linux64-gcc112.bash, util/cron/test-linux64-gcc54.bash, util/cron/test-linux64-gcc63.bash, util/cron/test-linux64-gcc73.bash, util/cron/test-linux64-gcc91.bash
We are in the process of moving all nightly testing dependencies to a Spack install, in which all dependencies (including updated LLVM 15) are built with GCC 12. This is likely to cause failures for the test configs that pin a specific old GCC version, so this PR updates those configs to use `CHPL_LLVM=none`.
In the long term it would be valuable for these configs to run in an environment where their specific GCC version is the system GCC, i.e. in a container/VM. For now, this keeps these configs testing something valuable while being less likely to break due to dependency version changes.
This is a nightly test config change and is not feasible to test manually before tonight's nightly test runs.
=> Use CHPL_LLVM=none for nightly configs testing specific GCC versions

modules/internal/ByteBufferHelpers.chpl, modules/internal/ChapelBase.chpl, modules/internal/ChapelHashtable.chpl, modules/packages/Curl.chpl, test/interop/python/otherPointer.chpl, test/interop/python/otherPointer_int.chpl, test/interop/python/otherPointer_int32.chpl, test/interop/python/stringAllocated.chpl, test/library/packages/Sort/RadixSort/ips4o-like.chpl, test/library/standard/Endian/Endian.chpl, test/optimizations/parallelAssign/basicDR.chpl
This PR fixes some fallout from https://github.com/chapel-lang/chapel/pull/22381:
- Python interop tests now use the new `POSIX.memcpy` instead of the deprecated `c_memcpy`
- internal uses of new `mem*` procs now safecast the size argument to `c_size_t` to avoid compilation failures on 32-bit systems
- Endianness tests now use `POSIX.memcpy`
testing:
=> Test failure corrections from new POSIX.mem* procs

test/gpu/native/multiGPU/worksharing.skipif, test/gpu/native/studies/shoc/triadchpl.skipif
We have a new test configuration for AMD+AOD testing so it's not unexpected that we have some failing tests.  I want to get things in a stable state where the job is expected to pass and any failure represents a regression.
So for the short-term I'm adding skipif files for these tests.
I'll fork another GH issue to investigate why these tests are failing and decided what our next steps ought to be. (edit see: https://github.com/Cray/chapel-private/issues/4885)
=> Skip nightly testing for GPU AMD+AOD tests that are timing out

util/cron/test-linux64-clang.bash
While we generally don't want to `spack load llvm` as it causes some unwanted changes to `CC/CXX` environment variables, it is needed for this test as we are using the `clang` provided by that LLVM install.
Nightly test change, cannot feasibly test besides waiting for tonight's run.
=> Spack load LLVM for linux64-clang nightly test config

compiler/passes/insertWideReferences.cpp, test/gpu/native/bug22114.chpl, test/gpu/native/bug22114.good
This should fix #22114. It appears as though some of the code in `insertWideReferences` didn't insert local accesses of local variables in enough cases, including when accessing an array. This made GPU procedures that were turned into `local_` versions still have some communication. This, in turn, is unimplemented on the GPU device, so array assignment became a no-op.
@benharsh pointed out that we now have a different way of checking if something is a wide reference (which I believe also consults the `wide-ref` qualifier, and not just an expression's type symbol). Switching logic in `insertWideRefs` to using this check made it pick up and "localize" the array accesses. Thanks Ben!
=> Fix mutable arrays on GPU

modules/standard/AutoMath.chpl, modules/standard/Math.chpl, test/deprecated/Math/depGcd.chpl, test/deprecated/Math/depGcd.good, test/library/standard/Math/testcases_gcd.chpl
In a recent discussion on which symbols in the AutoMath
module should continue being included by default, we
decided to stop including `gcd`.  This change implements
that decision.
<details>
Similar to the previous deprecations along these lines, add
a hidden helper function that both the deprecated version
and the new version can call to maintain their unity. This
version will be removed and its contents migrated into the
new version once the deprecations have been removed.
We did this to avoid causing `AutoMath` to rely on `Math`. 
</details>
Updates one test to use the Math module so that it
continues to work.
Add a new test locking in the deprecation message.
=> Stop including gcd by default

doc/rst/language/spec/conversions.rst
Fixes a small typo in the "Conversions" spec page.
Previous:
```
Signed integral types ``int(s)`` can implicitly convert to ``uint(s)`` where ``s <= t``.
```
Fixed (`uint(s)`->`uint(t)`):
```
Signed integral types ``int(s)`` can implicitly convert to ``uint(t)`` where ``s <= t``.
```
Checked correctness of the change against the table of legal numeric implicit conversions that follows this section.
=> Fix a small spec typo on legal int->uint implicit conversions

compiler/include/driver.h, compiler/main/driver.cpp
Follow up to https://github.com/chapel-lang/chapel/pull/22322.
My string operations were a bit haphazard that triggered warnings/errors with clang 15. This PR adjusts the string handling for `--gpu-arch` flag in the compiler.
Test:
=> Tighten up string operations around setting

modules/packages/CopyAggregation.chpl, modules/packages/DistributedBag.chpl, modules/standard/IO.chpl, modules/standard/Regex.chpl, test/arrays/elliot/arrayInitDeinitPerf.chpl, test/deprecated/string-bytes-factoryFunctions.chpl, test/npb/ft/npadmana/DistributedFFT.chpl, test/runtime/configMatters/mem/align.chpl, test/runtime/configMatters/mem/concurrent-alloc.chpl, test/runtime/configMatters/mem/testMemApi.chpl, test/types/bytes/io/writeread-pattern.chpl, test/types/bytes/io/writeread-random.chpl, test/types/string/validation/randomByteEscape.chpl
Follow up to https://github.com/chapel-lang/chapel/pull/22358, which replaced `c_*alloc`s (with `integral` sizes) with `allocate` (with `c_size_t` size). While on 64-bit systems our default `int` can implicitly convert to a `c_size_t`, on 32-bit systems it does not fit, causing a number of test failures. This PR adds casts and `safeCast`s to `c_size_t` as appropriate to fix this on 32-bit systems.
Testing:
=> Add [safe]casts in module and test code for allocate size

runtime/src/launch/slurm-srun/launch-slurm-srun.c
The `slurm-srun` launcher invokes `sbatch --version` to determine how slurm is configured on the system. It searches the result for the string "slurm", and if it doesn't find it, it exits with a less than helpful error message:
```
Error: This launcher is only compatible with native slurm
Slurm version was 3
```
This PR produces a better error message that should help in debugging.
=> Improve error message when checking slurm version

runtime/src/error.c
This resolves a problem in a nightly testing configuration where /usr/bin/addr2line is too old as compared to the compiler in use (in particular it was giving errors about not supporting dwarf 5). This PR solves the problem by finding `addr2line` from the PATH since in the nightly testing spack configuration, that `addr2line` came with `gcc` and has the required dwarf 5 support.
Reviewed by @jhh67 - thanks!
=> Run addr2line from the PATH in stack trace handling

make/compiler/Makefile.gnu
This PR adjusts Makefile.gnu to avoid two spurious warnings with GCC 12.
First, use -Wno-use-after-free for GCC 12 when building the runtime. This is a a follow-up to PR #20199. When working with GCC 12.2, we are seeing spurious warnings-as-errors with realloc (similar to the case from PR #20199). We have already turned off use-after-free warnings from GCC for C++ compiler code due to this issue. This change turns it off for the runtime C code as well.
Second, avoid a GCC bug when combining certain warnings with `-fsanitize=address`. See also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105616 . At present it looks like GCC 13 also has this bug.
Note that these warnings are only in effect with a make command like `make WARNINGS=1` for example.
=> Avoid two spurious warnings with GCC 12

util/chplenv/chpl_llvm.py
Currently on my mac if I don't have LLVM installed or I have LLVM 16 installed by homebrew, I get this error message:
```
OSError: command not found:
```
What appears to be happening is that printchplenv tries to compute defaults for various `CHPL_` variables and while trying to compute `CHPL_LLVM_STATIC_DYNAMIC` it calls out to `compute_host_link_settings`, which then tries to determine the path for `llvm-config` and uses that.  If `llvm-config` is not found it errors with that "command not found" error. 
In this PR I have `compute_host_link_settings` exit early and return dummy values if it can't find `llvm-config`. This appears to work and later on I'll get an error like this:
```
Exception: CHPL_LLVM=system but could not find an installed LLVM with one of the supported versions: 15, …
```
=> Fix bug causing printchplenv to error with "Command not found" when LLVM not installed

test/gpu/native/multiGPU/worksharingBasic.skipif
Skip workSharingBasic nightly test (that is currently timing out) for GPU AMD+AOD
Looks like there's one more test that should have been added in https://github.com/chapel-lang/chapel/pull/22392 where we added `.skipif` files for several tests in the new GPU AMD+AOD testing configuration.
The missing test was `workSharingBasic.chpl` (in the previous PR we filtered out `worksharing.chpl` but didn't add this one too). I've noted this in https://github.com/Cray/chapel-private/issues/4885 (we need to followup and investigate why this is timing out but for now we want a clean nightly test job).
=> Add worksharingBasic.skipif for nightly AOD+AMD GPU testing config

compiler/main/driver.cpp
String operations for handling `--gpu-arch` is still causing trouble with older GCCs. This PR uses `memcpy` and adds null-termination to hopefully avoid the issues. For some reason, I am unable to reproduce the issue, but I am hoping that this will fix.
Test:
=> Use mempcy instead of strncpy, null-terminate manually in `--gpu-arch` handling

util/cron/common-native-gpu.bash, util/cron/common.bash, util/cron/test-linux64-llvm11.bash, util/cron/test-linux64-llvm12.bash, util/cron/test-linux64-llvm13.bash, util/cron/test-linux64-llvm14.bash, util/cron/test-linux64-llvm15.bash, util/cron/test-valgrind.bash, util/cron/test-valgrindexe.bash
Currently our nightly tests that are locked to use LLVM 11-15 are actually all just using LLVM 15. This is because we first check `CHPL_LLVM_CONFIG` to find our LLVM, but only the script that initially sets the default LLVM (latest install) is actually setting that variable. System LLVM setup scripts have been adjusted to set this variable, including for the old LLVM installs. As the second component of the fix, this PR adjusts old LLVM version loading to happen after `common.bash` pulls in the default LLVM, and override it.
Also removes the `OFFICIAL_SYSTEM_LLVM` variable as it no longer has any use (and wasn't providing the desired effect after test server script changes anyways).
There are more improvements to be made to the `common.bash` script such as eliminating the need to `source …
=> Fix nightly test scripts that use specific LLVM versions

util/cron/test-perf.chapcs.clang.bash
Similarly to #22393, this test config needs the `clang` provided by the default LLVM install to be available in the `PATH`. This is accomplished by adding a `spack load` for the LLVM install. As in the previous PR, the extraneous `CC` and `CXX` the `load` sets are then `unset`.
=> Spack load LLVM in perf.chapcs.clang nightly test config

util/cron/common-arkouda.bash, util/cron/test-perf.chapcs.arkouda.release.bash
`test-perf.chapcs.arkouda.release.bash` tests Arkouda against the latest Chapel release at time of writing (1.30.0), which does not support our now-default LLVM 15. This PR loads LLVM 14 specifically for when we are using this version of Chapel, and does nothing otherwise.
Although it's slightly overdoing it for the task at hand, this also introduces a `CHPL_WHICH_RELEASE_FOR_ARKOUDA` in `common-arkouda.bash` that one would have to modify to test Arkouda against a different Chapel release, to ensure that we do not leave this config permanently testing against LLVM 14 even as new Chapel versions come out.
=> Load LLVM 14 when testing Arkouda against 1.30 release

modules/internal/ChapelBase.chpl, test/deprecated/modOnReal.chpl, test/deprecated/modOnReal.compopts, test/deprecated/modOnReal.good, test/deprecated/modOnReal.noexec
This removes the support for `%=` on reals, which has been deprecated for two releases now and doesn't work anyway (so in retrospect, probably it could've been removed without deprecation...).
=> Remove %= on reals

compiler/resolution/lowerIterators.cpp, test/deprecated/zipUnbounded.chpl, test/deprecated/zipUnbounded.good, test/deprecated/zipUnbounded.skipif, test/types/range/unbounded/test_indefinite1.good, test/types/range/unbounded/unboundedBoolEnum3.good, test/types/range/unbounded/zipMismatch-case2-baseline.good, test/types/range/unbounded/zipMismatch-case2.good, test/types/range/unbounded/zipMismatch-case3-fast.good, test/types/range/unbounded/zipMismatch-case3.good, test/types/range/unbounded/zipMismatch.good
This removes the warning that the behavior for serial zippered loops led by unbounded ranges has changed now that the warning has been on for the past two releases.
=> Remove warning for change in behavior for zip() being led by unbounded range

doc/rst/language/spec/classes.rst
PR #20589 added a deprecation for creating new classes as `new borrowed`, but our spec still suggests this as an option.
This PR adds a warning to the spec telling users this is deprecated.
Built docs locally and checked them
---
[Reviewed by @daviditen]
=> Add deprecation warning to docs on classes

modules/standard/BigInteger.chpl
Previously, the bigint serialization routines were using plain assignment of the extern `mpz` field, which would result in bad memory accesses, since the `mpz` field had not been initialized. Switching to `mpz_init_set` does both the initialization and assignment.
This bug was revealed by https://github.com/Bears-R-Us/arkouda/pull/2437 and a test is added in https://github.com/chapel-lang/chapel/pull/22403 for the `+ scan` over a block distributed array that was triggering this.
=> Switch bigint serialization to use `mpz_init_set` instead of assign

make/compiler/Makefile.gnu
Follow-up to PR #22400 to avoid GCC 12's use-after-free error (which has false positives with `realloc`) when compiling the generated code. This PR just extends the `Wno-use-after-free` to apply to compiling the generated C code as well in order to fix problems in asan configurations.
This PR also extends `-Wno-stringop-overread` to GCC 12 since we saw problems with that in gasnet quickstart testing.
Reviewed by @lydia-duncan - thanks
=> Avoid spurious GCC 12 use-after-free error when compiling generated code

tools/chpldef/Logger.cpp, tools/chpldef/Logger.h, tools/chpldef/Message.cpp, tools/chpldef/Message.h, tools/chpldef/Server.h, tools/chpldef/Transport.cpp, tools/chpldef/chpldef.cpp, tools/chpldef/command-line-flags.cpp, tools/chpldef/message-compute.cpp, tools/chpldef/message-macro-list.h, tools/chpldef/misc.cpp, tools/chpldef/misc.h, tools/chpldef/protocol-types.cpp, tools/chpldef/protocol-types.h
Add initial support for responding to notifications. A notification
is like a request, but the server should not send a response back to
the client. Notifications do not have IDs. Implement the
`Initialized`, `Shutdown`, and `Exit` messages.
For now, the `ServerCapabilities` type turns all server capabilities
to false, so a lot of ugly "wiring-up" code that `clangd` has to
implement is avoided.
While unit testing is not set up yet, I can actually confirm via a
local `vscode` extension that the server does run to completion.
As soon as the client sees that we have no capabilities to offer, it
immediately asks us to shutdown (boy was that a blow to my pride -
I know `chpldef` can't do much yet, but _immediately_ sending the
`Shutdown` message? - oof).
Adjust the message `compute` method to …
=> chpldef: Implement core language server protocol lifecycle messages

util/cron/test-linux64-llvm15.bash
Replaces a check using clang, which is not in the path for our Spack install by default. It now uses `llvm-config` as retrieved from `CHPL_LLVM_CONFIG` after sourcing `setup_system_llvm.bash`.
Also changes checked version from `15.0.0` to `15.0.4` since that's what we actually have as latest LLVM 15.
=> Check LLVM 15 version using llvm-config

util/cron/common-arkouda.bash
The iconv and idn2 libraries that were built with asan are no longer working since the LLVM 15 upgrade, failing to locate `libasan.so.5.0`. Reverting these to use the regular iconv and idn2 libraries for now, but we would probably want to install new asan versions of these libraries in the future.
See: https://github.com/Cray/chapel-private/issues/4901
Issue for follow up work: https://github.com/Cray/chapel-private/issues/4911
=> Fix Arkouda asan testing after LLVM 15 upgrade

test/library/standard/FileSystem/nonUTF8/basic.suppressif
This test was updated in #21769 in a way that makes it pass in the suppressed configuration. Remove the .suppressif file.
=> Remove a .suppressif file for a test that no longer needs it

util/cron/common.bash
For chapcs/chapvm systems, just `source` `setup_chpl_deps.bash` for all dependencies, including avoiding sourcing `.bashrc`.
Once this is merged we should remove the source of `setup_chpl_deps.bash` from the chapelu `.bashrc` on chapcs.
=> Simplify common.bash and avoid sourcing .bashrc

test/library/packages/Socket.precomp, test/library/packages/Socket/COMPOPTS
Fixes passing `--ccflags` and `--ldflags` to `chpl` for `library/packages/Socket` tests requiring `libevent`.
This appears to have not passed the flags to `chpl` previously, which was not causing problems until the new `libevent` install in Spack. To fix it I copied what the sibling `ZMQ` tests are doing.
=> Fix COMPOPTS for Socket package tests

compiler/codegen/cg-expr.cpp, compiler/codegen/codegen.cpp, compiler/include/genret.h, test/llvm/dbg-intrinsics/dbg-proc.chpl, test/llvm/with-opaque-ptrs/llvm-invariant/NOTEST, test/llvm/with-typed-ptrs/lifetime-intrinsics/lifetime-multi-blocks.chpl, test/llvm/with-typed-ptrs/lifetime-intrinsics/lifetime-multi-return.chpl, test/llvm/with-typed-ptrs/lifetime-intrinsics/lifetime-no-return.chpl, test/llvm/with-typed-ptrs/lifetime-intrinsics/lifetime-record.chpl, test/llvm/with-typed-ptrs/lifetime-intrinsics/lifetime-temporaries.chpl, test/llvm/with-typed-ptrs/lifetime-intrinsics/lifetime-throws.chpl, test/llvm/with-typed-ptrs/llvm-invariant/NOTEST
This PR adjusts the Chapel code generator to not generate calls to `llvm.invariant.start`. The reason for doing that is that we are seeing test failures for some tests with `--fast` after upgrading to LLVM 15. Generation of `llvm.invariant.start` was initially added in PR #6706. I'd like to fix the problems with these in a better way than just not generating `llvm.invariant.start`, but removing it for now is the short-term solution in case I cannot come up with a fix in a reasonable amount of time. Note that it is still possible to generate a call to one of these with `PRIM_INVARIANT_START` but that is not done in any modules or tests.
<details>
Reproducer:
``` chapel
use Sort;
var d : domain(string);
var A:[0..10] string;
d.add("two");
d.add("zero");
{ …
```
=> Remove calls to codegenInvariantStart

test/types/range/enum/rangeCastsWithEnum.good
My previous PR had a bad merge with other changes on main.  This test should probably be prediffed (well, really all of our test output involving module code in errors should probably be prediffed), but I don't trust myself to get it right before nightly testing starts, ao am taking the easy (read: lame) fix for now.
=> Fix unstable warning line numbers

compiler/include/pass-manager-passes.h, compiler/passes/insertLineNumbers.cpp
I observed a problem (when developing another PR) where insertLineNumbers added 9 line numbers to the calls to `message` in the `Errors` module. Note that this only happens with `CHPL_DEVELOPER` unset (because of the logic in insertLineNumbers).
This PR fixes it by updating the insertLineNumbers pass to track the CallExprs that it has modified in a set and not to modify them twice. Note that PR #19260 added the pass structure to insertLineNumbers. I chose the simplest solution I could imagine here but we might want a different solution as insertLineNumbers / the pass manager evolve. A reasonable alternative would be to check that the call and the called function have matching numbers of arguments.
=> Don't insert too many line numbers

doc/rst/language/spec/classes.rst
Removes lines in `classes.rst` that reference being able to allocate a class with the `borrowed` management style like `new borrowed MyClass()`.
Tested locally by building docs
---
[Reviewed by @daviditen]
=> Remove deprecated `new borrowed` from the spec

modules/packages/ArgumentParser.chpl, modules/packages/TOML.chpl, modules/standard/List.chpl, modules/standard/Path.chpl, test/deprecated/listPopIdx.chpl, test/deprecated/listPopIdx.good, test/library/draft/Shlex/Shlex.chpl, test/library/standard/List/perf/listBenchmark1.chpl, test/library/standard/List/pop/listAppendPopLeak.chpl, test/library/standard/List/pop/listAppendPopLeakClassInRecord.chpl, test/library/standard/List/pop/listPopHaltEmpty.good, test/library/standard/List/pop/listPopIndex.chpl, test/library/standard/List/pop/listPopIndexHaltBadIndex.chpl, test/library/standard/List/pop/listPopIndexHaltBadIndex.good, test/library/standard/List/pop/listPopIndexHaltEmpty.good, test/library/standard/List/pop/listPopLeakClassInRecord.chpl, test/release/examples/primers/listOps.chpl, tools/mason/MasonExternal.chpl, tools/mason/MasonUpdate.chpl, tools/mason/SpecParser.chpl
Deprecates the `list.pop` method in favor of `list.getAndRemove` (see: https://github.com/chapel-lang/chapel/issues/21933#issuecomment-1563624603). Tests and module code are updated accordingly.
=> Rename `list.pop` to `list.getAndRemove`

test/types/range/rangeSafeCasts.chpl
I'd only tested this test with the clang C back-end, and gcc is better at warning about pointless bool comparisons, so did.
=> Update some boolean logic to avoid gcc warnings about pointless comparisons

modules/packages/ZMQ.chpl
Fixes an instance of `memmove` being called with a size parameter that doesn't fit into `c_size_t` on 32-bit systems. This one was showing up weirdly in night tests so it was harder to catch (see https://github.com/Cray/chapel-private/issues/4928).
Follow up to https://github.com/chapel-lang/chapel/pull/22381.
[review info placeholder]
Testing:
=> Fix an instance of memmove called with >uint32 size

test/types/complex/diten/cplxOperators.prediff
With the upgrade to GCC 12.2.0 on `chapcs`, and corresponding newer install of Valgrind, we are seeing `test/types/complex/diten/cplxOperators.chpl` output a `+0.0i` for the imaginary part of a quotient when executed directly, and a `-0.0i` when run in Valgrind. This does not occur when using the new install of Valgrind but compiling Chapel with GCC 8.3.
I am chalking this up to a quirk of Valgrind or GCC floating-point handling, and adding a `cplxOperators.prediff` that replaces negative zeros with positive zeros.
Testing:
=> Add cplxOperators.prediff handling negative vs positive zero for Valgrind

modules/internal/ChapelDistribution.chpl
#22441 resulted in added `get` communications for the call `rhs.getIndices()` that it hoisted out from the loop `for e in lhs._arrs` in chpl_assignDomainWithGetSetIndices(). While hoisting helps in many cases, here it was detrimental because this loop had no iterations at all.
Given that chpl_assignDomainWithGetSetIndices already invokes `rhs.getIndices()` outside of the loop, I changed the code to invoke it just once and reuse its result whenever necessary.
I also moved the call to castIndices(), which #22441 also hoisted out of the loop, back into the loop. However it probably does not matter because it will be no-op in most cases, otherwise have low overhead.
Testing: standard+gasnet paratests; distribution robustness suites for block, cyclic, replicated.
=> Fix commcount regressions from #22441

test/types/range/elliot/anonymousRangeIter.expectedGenCode
#22441 changed how some range bounds are calculated. As a result, the compiler now produces a temp called `call_tmp` where previously it was called `tmp`. Adjust the expectations that the test `anonymousRangeIter` makes about the generated code.
=> Fix failure in anonymousRangeIter

modules/internal/DefaultRectangular.chpl
This PR updates the guard for invoking _simpleTransfer() in the implementation of chpl__bulkTransferArray() to require the viewing domains on both sides to have stride=1. Prior to this change it also accepted the case where the two domains both had stride=-1. However, the implementation was not intended to work in this latter case and so resulted in invalid memory accesses. This change avoids invoking _simpleTransfer() in such case.
Suggested by @benharsh, not reviewed.
=> Fix ASAN failures in negativeStrideWarnings

util/chplenv/chpl_llvm.py
This PR includes the patches that were necessary to build the Chapel compiler under Nix as tested in this project https://github.com/twesterhout/nix-chapel .
The code should be self-explanatory, but let me know if you feel that additional explanations/justifications are needed.
One thing to note is that, for now, we skip some checks when we're in Nix environments. That means that if you add `llvmPackages.clang` to your build inputs, but forget `llvmPackages.libclang.dev`, the build system won't print a pretty error message saying that we're missing libclang; rather, the compilation will just fail with a missing include file. This should be fixed, but probably in a later PR.
Pinging @mppf since we discussed this patch at length yesterday.
=> Support building Chapel in a Nix shell 

modules/internal/fixInternalDocs.sh, modules/standard/CTypes.chpl
This PR (mis)uses `fixInternalDocs.sh` to change the headers for `c_ptr`, `c_ptrConst`, and `c_array` to hide their underlying implementation types as classes (`c_ptr[Const]`) and records (`c_array`).
`CTypes` is not an internal module, so technically this would better belong in a `fixStandardDocs.sh`, but I view this as an acceptable temporary hack that would be obviated by https://github.com/chapel-lang/chapel/issues/22461.
Also includes some doc comment improvements for `c_ptr`, `c_ptrConst`, and `c_array`.
Resolves https://github.com/chapel-lang/chapel/issues/21385.
Testing:
=> Hack-ily hide c_ptr/c_array types with fixInternalDocs

test/gpu/native/studies/chop/chplGPU.skipif
On the system where we do our nightly test of using Chapel's GPU support with ChOp we have an issue where we can not have 'cmake' loaded by Spack and be able to use 'git' commands (see  https://github.com/Cray/chapel-private/issues/3781#issuecomment-1238501988).
Ultimately, we should update things on the system to avoid this issue. But in the meantime one workaround is to unload the Spack version SSL, do the git operation, and then reload it.
That's what this PR does.
=> Fix nightly testing for ChOp (git clone fails when spack version of cmake is loaded)

test/gpu/native/dataPingPong.good
This test needs to be updated due to changes here (which adds trailing comma in stringify for 1-tuples):
https://github.com/chapel-lang/chapel/pull/22469
FYI: @vasslitvinov
=> Update GPU test to account for change in how we print tuples

modules/standard/IO.chpl
There appears to be some kind of bug in no-local configurations involving a wrapper class around 'nothing', where the only 'var' member is 'none'. Adding the '__dummy' field here fixes some kind of memory error in the 'library/draft/DistributedMap/v2/use-distributed-map' test.
Future work: investigate and resolve the underlying bug
Testing:
=> Add dummy field to _serializeWrapper class

modules/dists/BlockDist.chpl, modules/standard/BigInteger.chpl
BigInt values were being improperly remote value forwarded for block array scans (see https://github.com/Cray/chapel-private/issues/4925 for more information), so switching to yield BigInt values by ref in the scan, rather than creating copies to avoid what is believed to be stack memory corruption from values being cleaned up too early fixes this issue.
Closes https://github.com/Cray/chapel-private/issues/4925
=> Yield BigInt values by ref for block array scans

util/cron/common-cray-cs.bash, util/cron/common.bash, util/cron/load-base-deps.bash
For our perf tests, after sourcing `common.bash`, `common-cray-cs.bash` wipes out all modules and loads new ones. This worked fine previously, but with the Spackification, `common.bash` sources `setup-chpl-deps.bash` which loads all our Spack dependences using the module system. Those are now getting purged shortly after being loaded.
Commit 3fb64c90463b68a9d1cefaa365bd180f9ac03cba provides the reason this `module purge` is necessary. In future we should probably change it to remove specifically the modules we are concerned about. For the moment, this PR re-loads all the base dependencies after the `module purge`. To make this possible, loading base dependencies is separated out from `common.bash` into its own `load-base-deps.bash` script, `source`d by `common.bash`.
[reviewer info …
=> Fix Spack deps getting 'module purge'd from common-cray-cs.bash

modules/standard/IO.chpl
The tests in ``library/packages/ProtobufProtocolSupport/`` exposed an issue with re-assigning channels. The solution is to set the wrapper fields to ``nil`` after deleting, so later checks against ``nil`` work as expected.
Testing:
=> Set (de)serializer wrappers to 'nil' after deleting

frontend/include/chpl/types/CompositeType.h, frontend/lib/resolution/InitResolver.cpp, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/prims.cpp, frontend/lib/types/CompositeType.cpp, frontend/lib/types/Param.cpp, frontend/lib/types/Type.cpp, frontend/test/resolution/testInitSemantics.cpp, frontend/test/resolution/testParamFolding.cpp, frontend/test/resolution/testReturnTypes.cpp
This PR includes a few bundled improvements for type-resolving in dyno:
- Updates ``handleResolvingFieldAccess`` to ignore ``Dot`` expressions that don't start with "this"
- Enables param folding for unary operators
- Adds support for mapping the "locale" type to the "_locale" implementation
- Adds workaround for potential ``out_of_range`` exception in the cased of skipped calls
- Updates test to use ``value_or`` on llvm's ``Optional`` type if LLVM 15 is available
- since the other method was deprecated in version 15
Testing:
=> Several minor type resolution fixes for dyno

frontend/lib/resolution/return-type-inference.cpp, frontend/test/resolution/testReturnTypes.cpp
The production module code occasionally has a pattern like the following:
```Chapel
if someParam then return 1;
return "hello";
```
Since the `param` is known at compile time, this shouldn't be an error, as the `return "hello"` shouldn't be considered. This PR adds some control flow analysis to Dyno to properly handle cases like this.
It might be nice to throw a warning in some situations where multiple returns like `return x; return y`; are used, but I didn't do so in this PR.
=> dyno: Perform some control flow checking to skip unused return statements

util/cron/nightly, util/cron/syncPerfGraphs.py
This change allows for uploads to either an internal host or an external host.  The flag is set in the CI script for the build.  See this PR: https://github.hpe.com/hpe/hpc-chapel-ci-config/pull/987
=> Graph sync script update to check system flag

modules/standard/CTypes.chpl
This helper was introduced in https://github.com/chapel-lang/chapel/pull/19262 to make it easier to add a large number of compiler warnings about moved types, but those warnings have all been phased out by now and it is unlikely to see use again. This PR removes the helper, as well as a comment about "former CPtr contents" as it has been over a year since CPtr's contents were moved into CTypes.
Testing:
=> Remove chpl_typeMoveWarning helper from CTypes

compiler/include/driver.h, compiler/main/driver.cpp, compiler/optimizations/gpuTransforms.cpp, frontend/include/chpl/uast/PragmaList.h, test/GPU-GRAPHFILES, test/gpu/native/studies/tightLoopNotOnGpu/tightLoopNotOnGpu.chpl, test/gpu/native/studies/tightLoopNotOnGpu/tightLoopNotOnGpu.compopts, test/gpu/native/studies/tightLoopNotOnGpu/tightLoopNotOnGpu.execopts, test/gpu/native/studies/tightLoopNotOnGpu/tightLoopNotOnGpu.gpu-compopts, test/gpu/native/studies/tightLoopNotOnGpu/tightLoopNotOnGpu.gpu-execopts, test/gpu/native/studies/tightLoopNotOnGpu/tightLoopNotOnGpu.gpu-keys, test/gpu/native/studies/tightLoopNotOnGpu/tightLoopNotOnGpu.graph, util/chpl-completion.bash
This PR adds a new mode for GPU transforms that can be enabled by passing `--gpu-specialization` to `chpl`. In this mode we clone functions reachable from 'on' statements and then rewrite the 'on' statement to query if you're on a GPU sublocale. If so, we go to these cloned versions (and otherwise go to the originals). With this now being the case, we can safely assume that a user is "on" a GPU sublocale in all of these cloned versions, so we have kernel launches in these functions launch directly without checking. For more info see: https://github.com/Cray/chapel-private/issues/4566
**Notes to reviewers**:
- The bulk of work is in a new `CreateGpuFunctionSpecializations` class in `GpuTransforms`.
- Start by reading the `CreateGpuFunctionSpecializations::doit` function and go from there. …
=> Add mode to avoid overhead of asking "are we on a GPU sublocale?" per kernel launch (with GPU-bound specializations)

runtime/src/comm/ofi/comm-ofi.c
Change `init_ofiReserveCores()` to `init_ofiReserveCores(void)` to match the prototype. Caught by clang 15 upgrade, but was always incorrect.
=> Fix `init_ofiReserveCores` declaration

util/cron/test-perf.cray-cs-hdr.arkouda.release.bash
Arkouda release tests on `raptor` are using the latest LLVM version, 15, which Chapel 1.30.0 does not support. This change makes the test use LLVM 11 (the latest installed LLVM before 15) for that release. Similar to what #22416 did for `chapcs`.
Note this can't be handled in `common-arkouda.bash` as it has to be loaded after `common-cray-cs.bash` purges and re-loads base deps.
Testing
=> Load LLVM 11 for Arkouda 1.30.0 release test on Raptor

doc/rst/technotes/allocators.rst
This PR makes a small update to the `allocators.rst` technote (titled "Using the Chapel Allocator from C"), which was referring to `c_alloc` and `c_free` in `SysBasic`. These functions have long since been moved to `CTypes` and replaced with `allocate` and `deallocate` respectively.
=> Fix use of SysBasic and c_alloc/c_free in allocators technote

modules/internal/ChapelDomain.chpl, modules/standard/IO.chpl, test/deprecated/IO/unicodeSupported.chpl, test/deprecated/IO/unicodeSupported.good, test/deprecated/domains/makeIndexBuffer.chpl, test/deprecated/domains/makeIndexBuffer.good
This PR removes two symbols deprecated in the 1.29 release for the 1.31 release:
- `domain.makeIndexBuffer` (deprecated and renamed to `domain.createIndexBuffer` in #21085)
- `IO.unicodeSupported` (deprecated in #21086)
Testing:
=> Remove domain.makeIndexBuffer and IO.unicodeSupported

modules/standard/CTypes.chpl
Changes return type of `c_ptrTo` on a class type from `c_ptr(classType)` to `c_void_ptr`, and similarly for `c_ptrToConst`. This is more in line with the old behavior of casting a class type to `c_void_ptr`, allowing a user to take a class instance from Chapel->C->Chapel.
Follow up to #22367.
See #22478 for discussion of this change.
Testing:
=> Make c_ptrTo on class types return c_void_ptr

compiler/AST/AggregateType.cpp, compiler/AST/primitive.cpp, compiler/passes/InitNormalize.cpp, compiler/passes/buildDefaultFunctions.cpp, compiler/resolution/preFold.cpp, frontend/include/chpl/uast/prim-ops-list.h, frontend/lib/resolution/prims.cpp, modules/standard/ChapelIO.chpl
This PR introduces a "simple type name" primitive that returns the name of the type as it was declared, rather than including instantiation information (e.g. "R" vs. "R(int)"). The default implementations of ``serialize`` and ``deserialize`` methods are updated to use this new primitive instead of creating a string literal during ``buildDefaultFunctions``.
This change was motivated by a pair of mysterious baseline failures related to unused string literals in LLVM configurations. By only generating the string literal during resolution of the new primitive, we no longer leave the unused string literals around in the baseline configuration.
Testing:
=> Add 'simple type name' primitive, for use in serialize/deserialize

frontend/lib/uast/post-parse-checks.cpp, test/classes/weakPointers/passiveCache.good, test/functions/resolution/parenless-call-segfault.bad, test/functions/resolution/parenless-call-segfault.chpl, test/functions/resolution/parenless-call-segfault.future, test/functions/resolution/parenless-call-segfault.good, test/unstable/Map/parSafe.good, test/unstable/const-return-intent.chpl, test/unstable/const-return-intent.good
With this PR, the compiler generates unstable warnings for uses of `const` return/yield intent. This is in preparation for the future work discussed in https://github.com/chapel-lang/chapel/issues/21888#issuecomment-1563535855 .
Testing highlights four methods in our standard Map that use `const` return/yield intent:
```chpl
proc get(k: keyType, const sentinel: valType) const
iter values() const where isNonNilableClass(valType)
// two more 'const' methods are deprecated
```
I updated .good files for two tests that have --warn-unstable compopts and call these methods.
With this PR, the future test `test/functions/resolution/parenless-call-segfault.chpl` passes, for an unknown reason. I de-futurized it, we will see how it behaves in nightly. I made a note on its issue, #16128 .
=> Unstable warning for 'const' return intent

test/gpu/native/jacobi/flags-warn-unstable-internal.good, test/gpu/native/jacobi/flags.prediff
The `test/gpu/native/jacobi/flags.chpl` test has a compopt mode where it passes `--flags-warn-unstable-internal`.  
In a previous PR (https://github.com/chapel-lang/chapel/pull/22376) we update the test to account for `warning: 'allocate' is unstable, and may be renamed or moved` (which there is no stable alternative for).
The locations of these warnings has since changed and this test currently fails. Having to keep this test up-to-date with line changes and new internal warnings is a bit of a hassle and I believe the intent of this test is to lock down when/where the "GPU module is unstable" warnings occur internally.
So to avoid this in the future I've added a `.prediff` file that when run with `--flags-warn-unstable-internal` filters out all output except for the relevant warnings …
=> Make GPU "flags-warn-unstable-internal" test only consider the GPU module warnings

modules/internal/ChapelLocale.chpl, modules/internal/LocaleModelHelpSetup.chpl, modules/internal/localeModels/apu/LocaleModel.chpl, modules/internal/localeModels/flat/LocaleModel.chpl, modules/internal/localeModels/gpu/LocaleModel.chpl, modules/internal/localeModels/numa/LocaleModel.chpl, test/deprecated/locale-callStackSize.chpl, test/deprecated/locale-callStackSize.good, test/deprecated/localeGetChild.chpl, test/deprecated/localeGetChild.good, test/deprecated/localeGetChild.skipif, test/deprecated/localeGetChildCount.chpl, test/deprecated/localeGetChildCount.good, test/deprecated/localeGetChildCount.skipif
Removes the following symbols which have been deprecated for over two releases:
- `locale.callStackSize`: deprecated in https://github.com/chapel-lang/chapel/pull/20317
- `locale.getChild()`: deprecated in https://github.com/chapel-lang/chapel/pull/20428
- `locale.getChildCount()`: deprecated in https://github.com/chapel-lang/chapel/pull/20428
Testing:
=> Remove some deprecated symbols from the Locale module

modules/packages/FFTW.chpl
Fixes an issue where the opaque ptr type `fftw_plan` caused errors when compiling the generated C with an Intel compiler. Changing the type to `c_void_ptr` resolves the problem.
This issue cropped up in our nightly testing and this PR should resolve it.
Tested against all the FFTW tests I could find.
=> Fix compilation issue with Intel compiler for FFTW

compiler/AST/astutil.cpp, compiler/codegen/codegen.cpp, compiler/include/astutil.h, compiler/include/driver.h, compiler/main/driver.cpp, compiler/optimizations/gpuTransforms.cpp, test/gpu/native/reportGpu.chpl, test/gpu/native/reportGpu.compopts, test/gpu/native/reportGpu.good, util/chpl-completion.bash
This PR adds a flag to `chpl` (`--report-gpu`) that when run will produce a report like this:
```
GPU INELIGIBLE LOOPS:
---------------------
reportGpu.chpl:1
reportGpu.chpl:5
reportGpu.chpl:10
reportGpu.chpl:22
reportGpu.chpl:32
reportGpu.chpl:36
reportGpu.chpl:100
GPU ELIGIBLE LOOPS:
-------------------
reportGpu.chpl:41
reportGpu.chpl:45
reportGpu.chpl:51
reportGpu.chpl:58
reportGpu.chpl:63
reportGpu.chpl:64
reportGpu.chpl:66
reportGpu.chpl:67
reportGpu.chpl:68
reportGpu.chpl:69
```
Where each entry is a file/linenum to an order-independent loop. Output in each category is sorted by filename and line number.
If run with `--developer` we'll print information for all modules, if not we only print instances in user code.
While I'm here I also add a flush to stdout before we fork the …
=> Flag to report GPU eligible and ineligible loops (--report-gpu flag). Also avoid duplicate output by flushing stdout before forking compiler.

doc/rst/technotes/extern.rst
Adds some information on using pointers to classes to the C Interoperability technote (`extern.rst`). Also adds mention of `c_addrOf` as a method that doesn't use the special behavior. This is following discussion at https://github.com/chapel-lang/chapel/issues/22478 about confusion on how to use these methods to take a class instance from Chapel->C->Chapel.
Follow up to https://github.com/chapel-lang/chapel/pull/22367 and https://github.com/chapel-lang/chapel/pull/22505.
Testing:
=> Add some info to C Interop technote about c_ptrTo on classes

test/classes/cast/castClassPtr.chpl, test/classes/cast/castClassPtr.compopts, test/classes/cast/castClassPtr.good
We've been talking recently about ways to convert from classes to pointers and back, and this was a test I wrote up to convince myself we could, in two ways currently at least.  Whether or not we should keep both of them relates to #22341.
=> Add test locking in conversion from unmanaged class to c_void_ptr and back

util/chplenv/chpl_llvm.py, util/chplenv/third_party_utils.py
Use `pkg-config` to get the link arguments for `libzstd`, if possible.
Resolves https://github.com/Cray/chapel-private/issues/4905.
=> Use pkg-config to get libzstd link args

modules/standard/FileSystem.chpl
Changes a `c_ptr(opaque)` type definition to be a `c_ptr` to an actual concrete type in FileSystem.chpl. This resolves an issue that showed up in our nightly testing with the Intel compiler as the backend.
=> Remove opaque pointer usage in FileSystem.chpl

test/library/packages/Yaml/basic-types.notest
In paratesting on our old system this afternoon, I found that this test didn't pass there, nor on my Mac, and that it hadn't been tested by our nightly testing since it was checked in due to the various outages.
I don't know whether the output I'm getting is correct vs. whether something else about the code ought be changed, so rather than trying to fix it or just accept the new output, I'm just marking it a notest for tonight to avoid unnecessary noise in testing with the hope that @jeremiah-corrado can provide some guidance and apply a more intelligent fix tomorrow.
A few other notes while here:
* @jabraham17 ran a paratest in the usual place which did not fail, making me wonder whether the SKIPIF causes the directory to be skipped on that platform
* On my Mac, all the Yaml tests other …
=> Marking Yaml basic-tests.chpl file .notest for tonight

frontend/lib/CMakeLists.txt
This PR is intended to resolve a portability problem with the quickstart configuration when running in Debian Buster with no system LLVM installed. In that mode, our build system will build the LLVM Support library as a static library, and also the ChplFrontend library as a static library (to avoid mixing static/dynamic between these two -- see 02795bcf9addef2fd1d2c55e5b64983990106ef5). At the same time, with CMake version 3.13, the `ARCHIVE DESTINATION` option is required to install a static library. This PR adds it and sets it to the same location as the `LIBRARY DESTINATION`.
=> Include ARCHIVE DESTINATION for ChplFrontend install

modules/packages/Yaml.chpl, test/library/packages/Yaml/basic-types.good, test/library/packages/Yaml/basic-types.notest
The `library/packages/yaml/basic-types` test was failing due to a change in the way type names are generated by the serializers api (see: https://github.com/chapel-lang/chapel/pull/22513). This failure was a post-merge interaction that was not caught in the original paratest. Specifically, the names of class types now include the management type, so output failed to match. This PR corrects the relevant `.good` file.
It is also the case that Yaml doesn't support multi word type names (like `borrowed myClass`), so the libyaml implementation was printing them out as `borrowed%20myClass`. This PR also changes the format to use an underscore instead (e.g.,`borrowed_myClass`).
=> Fix yaml basic-types test failure

frontend/lib/uast/Builder.cpp, test/compflags/configs/stringWithSpace.chpl, test/compflags/configs/stringWithSpace.compopts, test/compflags/configs/stringWithSpace.good
When setting a `config var` string from the command line at compile time, the compiler was expecting it to compile correctly. When this was not the case, it would abort with an internal error.
Specifically, passing `-sx="hello world"` would fail, since the quotes would be eaten by the shell and the compiler would then see `-sx=hello world`, which would incorrectly be parsed and compiled.
- adds a check to `Builder::parseDummyNodeForInitExpr` which checks for an `ErroneousExpression`
- `test/compflags/configs/stringWithSpace.chpl`
- paratest
=> Replace internal error with error message when setting config variables

util/chplenv/chpl_llvm.py
We were seeing errors along the lines of
fatal error: 'stdatomic.h' file not found
These appeared after PR #22454 which changed the printchplenv logic to compute CHPL_LLVM_CLANG_C etc as 'clang' rather than '/usr/bin/clang' on this platform. For some reason, using clang as a library without the full path causes it to miss adding a system include path. So, this PR just adjusts the clang search process to run 'which' if it doesn't already have a directory component.
=> Resolve a problem using system clang on Alpine linux

util/chplenv/chpl_llvm.py
Follow-up to PR #22530. Intended to resolve smoke test failures with that PR. Certain testing configurations run commands with the environment including CHPL_LLVM_CLANG_C output by a previous printchplenv run. As such, it might include arguments, which caused errors along the lines of 'Error: Missing or wrong version for clang'.
This PR pulls out the consideration of overrides into a helper function that returns a list and uses the helper function in both `get_system_llvm_clang` and `get_llvm_clang`. Note that `get_system_llvm_clang` only needs the command name and no arguments to run `clang --version` etc; while `get_llvm_clang` returns the full list with the arguments for use during compilation.
=> Handle CHPL_LLVM_CLANG_C containing arguments

util/cron/common-arkouda.bash
The asan testing has been failing for Arkouda and it turns out that this was due to the gcc version update causing the ZMQ installation to be out of date and no longer compatible with that version. See https://github.com/Cray/chapel-private/issues/4944 for more info.
Since we have seen issues with three of these installations, I've decided to revert all the depdencies for now to avoid any other sneaky issues like this.
Follow up tracked in https://github.com/Cray/chapel-private/issues/4911.
=> Stop using specific asan dependencies for Arkouda

test/deprecated/IO/.gitignore, test/deprecated/IO/filePtrTest.txt, test/library/standard/IO/.gitignore, test/library/standard/IO/outOfRange.txt
Remove some output files created by IO tests that don't need to be tracked:
- test/library/standard/IO/outOfRange.txt
- test/deprecated/IO/filePtrTest.txt
testing:
=> Untrack output files created by IO tests

test/classes/cast/castClassPtr.chpl
Close an obvious user-level memory leak that showed up in last night's testing.
=> Free an unmanaged class that I forgot to...  :'(

modules/packages/Yaml.chpl
New tests for the Yaml package module were failing in the `--baseline` config due to some incorrect declarations of external c-functions. This PR corrects those declarations, and tests are now passing with `--baseline`
yaml tests passing:
=> Correcting `--baseline` failures in Yaml tests

modules/standard/CTypes.chpl, test/deprecated/IO/cFileWithPtr.good
This PR improves the error message for the `c_FILE` behavior deprecation s.t. users will be less likely to run into the error described here: https://github.com/chapel-lang/chapel/issues/22492 when transitioning to the new behavior.
Specifically, it indicates that instances of `c_FILE` will need to be wrapped in `c_ptr` with the new behavior in order to correctly represent a `FILE*`.
=> Improve error message for `c_FILE` pointer deprecation

doc/rst/usingchapel/prereqs.rst
Updates the prerequisite docs with the commands from portability testing results after PR #22552. These commands are generated from the commands we use in our portability testing.
Reviewed by @tzinsky - thanks!
=> Update prerequisite installation commands for 1.31 testing

doc/rst/usingchapel/chplenv.rst
Follow-up to https://github.com/chapel-lang/chapel/issues/19898#issuecomment-1553302233 where I noticed the documentation might be misleading given that current platforms might default to position independent executables but these aren't useful for shared libraries. So this PR updates the `CHPL_LIB_PIC` docs to acknowledge the difference between `-fPIC` and `-fPIE` without explicitly mentioning these flags.
=> Update documentation around CHPL_LIB_PIC

test/gpu/native/reportGpu.suppressif
This test fails in our nightly GPU+GASNET job because of a known failure mode (see https://github.com/chapel-lang/chapel/issues/20641).
This failure mode has nothing to do with GPU report generation itself, so arguably, I could just avoid this by removing the use global variable and the offending loop but I kind of like having this test demonstrating the various ways a loop might be made ineligible.
=> Suppress reportGpu test if CHPL_COMM!=none

CMakeLists.txt, doc/rst/conf.py, doc/rst/language/archivedSpecs.rst, doc/rst/usingchapel/QUICKSTART.rst, doc/rst/usingchapel/chplenv.rst, man/confchpl.rst, man/confchpldoc.rst, test/chpldoc/compflags/combinations/versionhelp-chpldoc.sh, test/compflags/bradc/printstuff/versionhelp.sh
As part of the 1.31 release process remove the 1.31 pre release tags.
=> Remove 1.31  pre release from chapel

doc/rst/usingchapel/chplenv.rst
Follow-up to PR #22530 to update chplenv.rst to describe how overriding `CHPL_TARGET_CC` / `CHPL_TARGET_CXX` will impact the LLVM backend.
=> Update docs about CHPL_TARGET_CC and LLVM backend

doc/rst/technotes/gpu.rst, modules/standard/GPU.chpl
Updates to  GPU tech note for 1.31:
- Add note about not calling certain extern functions to our definition of a GPU eligible loop at the top.  (This isn't a new limitation but something that seems notable and missing).
- Update supported LLVM version to 15.
- Reorganize the "GPU-Related Environment Variables" section to be a list of  environment variables with (shortish) descriptions. More details on each variable are given in relevant sections.
- Add Vendor Portability as a subsection of our "Features" section
- Move Engin's section on CPU as Device Mode to be after vendor portability (since I think the second can segue from the first).
- Add a sentence about `--report-gpu` to the "Diagnostics and Utilities" section
- Various other word tweaks and edits.
Updates to GPU module:
- I now …
=> Update GPU technote for 1.31; doc atomic functions in GPU module

doc/rst/language/spec/conversions.rst, doc/rst/language/spec/domains.rst, doc/rst/language/spec/iterators.rst, doc/rst/language/spec/procedures.rst, doc/rst/language/spec/ranges.rst, doc/rst/language/spec/tuples.rst, doc/rst/technotes/dsi.rst, test/release/examples/primers/LinearAlgebralib.chpl, test/release/examples/primers/learnChapelInYMinutes.chpl, test/release/examples/primers/ranges.chpl
Update the Ranges and Domains and Coercions chapters of the spec and the comments in the ranges and other primers for the change `range.stridable` --> `strides: strideKind` in #22441, with follow-ons #22486 and #22508.
Also remove the remaining occurrences of `BoundedRangeType` from the spec and primers -- it is deprecated as of #22059.
Remove the `const` return and yield intent in the Procedures, Iterators, and Tuples sections of the spec -- it is unstable as of #22515. I did not see any need to update the primers for this change.
While there, I did some rephrasing and restructuring of the text for better readability or precision.
Testing: visual examination of the generated docs; a standard paratest.
Post-merge: update the Chapel Evolution document.
=> Update the spec and primers for range and const changes

doc/rst/language/evolution.rst
This PR updates the Chapel Evolution document for the change range.stridable --> strides: strideKind in #22441 / #22486 / #22508 and for the change range.boundedType to range.bounds in #22059.
Testing: built and examined the docs.
=> Update the evolution doc for 1.31 range changes

doc/rst/conf.py, doc/util/versionButton.php
This is the normal update when we're staging docs for the pending release,
to make sure the docs version menu/button reflects those staged docs.
=> Update docs menu to reflect staged 1.31 release docs

util/cron/common-whitebox.bash
The goal of this is to make our environment more robust on heterogeneous Cray systems.  HPE developers can see https://github.hpe.com/hpe/hpc-chapel-code/pull/574 for more information.
=> Prepend CRAY_LD_LIBRARY_PATH to LD_LIBRARY_PATH for Cray whitebox testing

doc/util/versionButton.php
This is the standard day-of-release update of the docs menu to reflect that 1.31 is now the default.
=> Update docs menu for today's release

CONTRIBUTORS.md
As part of my bookkeeping when sorting people between categories for a given release, I temporarily change them from '*' to 'o' bullets until I sort them into the right category.  This time around, I sorted Gabriel and Vivian without remembering to turn them back to '*' entries, which makes them render poorly in GitHub.  Whoops!
Thanks to @gbtitus for catching and reporting this!
=> Fix some dumb typos in CONTRIBUTORS

compiler/AST/type.cpp, compiler/main/driver.cpp, frontend/include/chpl/framework/Context.h, frontend/include/chpl/framework/compiler-configuration.h, frontend/lib/framework/Context.cpp, frontend/lib/framework/compiler-configuration.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testCompilationGlobals.cpp
I noticed that the compiler flags are implemented as an input query that must be set by the user of the Dyno library. I think that the compiler globals are very similar (_and_ in production they are also set from the variables in `driver.cpp). This PR makes compiler globals be implemented in the same way that compiler flags are.
=> dyno: Change compiler global impl to match the compiler flags impl

compiler/backend/beautify.cpp
[conceived of by @jabraham17, typed in by me]
This PR updates the beautify pass that we take on our generated code to insert `#line` directives in order to stop removing paths to files.  Doing so made debugging harder when the source file was not in the CWD because that's where the debugger would look for it.
Resolves #22589
=> Stop removing paths in #line directives

frontend/lib/resolution/InitResolver.cpp, frontend/lib/resolution/call-init-deinit.cpp, frontend/lib/resolution/default-functions.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testInitSemantics.cpp
This PR replicates some of the behavior from #9004, which prevents the compiler from trying to resolve the signatures of initializers on types other than the type being initialized. In this PR, we selectively resolve the "this" formal on candidates and use ``canPass`` to check whether it is an initializer on the desired type. Without this change we could easily encounter recursive query errors whenever a class or record was initialized in an initializer's signature:
```chpl
proc MyType.init(x = new X(5))
```
Testing:
=> Dyno: only resolve relevant initializer signatures

runtime/src/qio/regex/bundled/re2-interface.cc
Replaced asserts with calls `chpl_internal_error` in `re2-interface.cc`. This ensures that our assert logic doesn't get compiled away, especially during testing.
Tested with paratest
[Reviewed by @mppf ]
=> Replace asserts with `chpl_internal_error` in `re2-interface.cc`

test/classes/casts/generated-cast-tests/argumentCoerce_Const/error/PRETEST, test/classes/casts/generated-cast-tests/argumentCoerce_Const/noerror/PRETEST, test/classes/casts/generated-cast-tests/argumentCoerce_ConstIn/error/PRETEST, test/classes/casts/generated-cast-tests/argumentCoerce_ConstIn/noerror/PRETEST, test/classes/casts/generated-cast-tests/argumentCoerce_ConstRef/error/PRETEST, test/classes/casts/generated-cast-tests/argumentCoerce_ConstRef/noerror/PRETEST, test/classes/casts/generated-cast-tests/argumentCoerce_In/error/PRETEST, test/classes/casts/generated-cast-tests/argumentCoerce_In/noerror/PRETEST, test/classes/casts/generated-cast-tests/argumentCoerce_Inout/error/PRETEST, test/classes/casts/generated-cast-tests/argumentCoerce_Inout/noerror/PRETEST, test/classes/casts/generated-cast-tests/argumentCoerce_Out/error/PRETEST, test/classes/casts/generated-cast-tests/argumentCoerce_Out/noerror/PRETEST, test/classes/casts/generated-cast-tests/argumentCoerce_Ref/error/PRETEST, test/classes/casts/generated-cast-tests/argumentCoerce_Ref/noerror/PRETEST, test/classes/casts/generated-cast-tests/coerceAssign/error/PRETEST, test/classes/casts/generated-cast-tests/coerceAssign/noerror/PRETEST, test/classes/casts/generated-cast-tests/coerceInitAssign/error/PRETEST, test/classes/casts/generated-cast-tests/coerceInitAssign/noerror/PRETEST, test/classes/casts/generated-cast-tests/explicitCasts/error/PRETEST, test/classes/casts/generated-cast-tests/explicitCasts/noerror/PRETEST
When `chpl` has been compiled for multi-locale, generating and running tests for `test/classes/casts/generated-cast-tests/generate-tests.chpl` did not work properly
tested with paratest with comm=none and comm=gasnet
Note: all of the changes in separate files are the same
=> Add PRETEST script logic for multi-locale

test/users/bachman/Beta_Diversity/main.chpl, test/users/bachman/Beta_Diversity/main.good
While running a paratest on a branch made from main today, I was seeing failures in the sum reduce output of the Beta_Diversity test that was added today, and then testing on my Mac saw a different value in the output.  This adds a config const for the time being that suppresses the output so that we'll still get the check that the code compiles and runs completely, but without any validation that the output is expected (the goal being to head off potentially getting a test mail for every configuration tonight if all of them similarly get different answers).
=> Silence unstable output in Beta_Diversity for now

compiler/codegen/cg-symbol.cpp, compiler/codegen/codegen.cpp, compiler/include/clangUtil.h, compiler/include/codegen.h, compiler/include/llvmDumpIR.h, compiler/include/llvmVer.h, compiler/llvm/clangUtil.cpp, compiler/llvm/llvmDumpIR.cpp
Continuing PR #22282, this PR updates Chapel's use of LLVM optimization passes to work with the new Pass Manager instead of the legacy one. It is currently configured to only use the new pass manager with LLVM 16 and newer (and note that the compiler does not yet build with LLVM 16 but see PR #22335 for that).
LLVM has introduced a new pass manager and the old pass manager is deprecated for running the optimization pipeline as of LLVM 15. And, some features of optimization with the old pass manager are removed in LLVM 16. So, we are looking at migrating Chapel's LLVM passes to the new pass manager. (Some historical details: `clang` started to use the new pass manager in LLVM 12; the new pass manager existed in LLVM 11; and even as of LLVM 16, the LLVM IR to assembly code generators still …
=> Use new pass manager with LLVM 16

test/classes/initializers/phase1/grandparentAccess.good
Follow-up to PR #22614 to fix test failures due to trivial line number differences.
=> Fix line numbers in grandparentAccess.good

compiler/codegen/cg-CForLoop.cpp, compiler/codegen/cg-DoWhileStmt.cpp, compiler/codegen/cg-WhileDoStmt.cpp, compiler/codegen/cg-expr.cpp, compiler/codegen/cg-stmt.cpp, compiler/codegen/cg-symbol.cpp, compiler/llvm/clangUtil.cpp, compiler/llvm/llvmAggregateGlobalOps.cpp, compiler/llvm/llvmDebug.cpp, compiler/llvm/llvmGlobalToWide.cpp, compiler/llvm/llvmUtil.cpp, make/compiler/Makefile.gnu
This PR updates the compiler to build with LLVM 16. It continues the effort from PRs #22260 #22282 #22300 to add compiler support for LLVM 16.
Note that this PR adds `-Wno-error=missing-braces` to the GCC flags because I am seeing it from within the LLVM headers (which we do not control). As far as I know, this works with old GCCs.
With these changes, as well as enabling LLVM 16 in chplenv, I'm able to build `chpl` and compile and run Hello World with LLVM 16.
=> Update the compiler to build with LLVM 16

test/library/draft/DistributedList/DistributedList.chpl
Following [this](https://github.com/chapel-lang/chapel/issues/21933#issuecomment-1563624603) decision, add a summary about how we plan to move forward with the distributed list data structure(s) to `/test/library/draft/DistributedList.chpl` so that we don't forget what we decided when it comes time to implement.
=> Addition to distributed list docs

test/types/range/elliot/anonymousRangeIter.expectedGenCode
Follow-up to PR #21894 to address a failure with test/types/range/elliot/anonymousRangeIter working. This PR just updates the pattern to search for in the generated C to account for a trivial change in a temporary name.
=> Adjust anonymousRangeIter for trivial code generation difference

compiler/resolution/preFold.cpp, frontend/include/chpl/uast/PragmaList.h, test/library/standard/Types/copyable-sync-single-string.chpl, test/library/standard/Types/copyable-sync-single-string.good, test/library/standard/Types/copyable-sync-string.bad, test/library/standard/Types/copyable-sync-string.chpl, test/library/standard/Types/copyable-sync-string.future, test/library/standard/Types/copyable-sync-string.good, test/types/sync/lydia/arrayOfArrayOfSyncsInField.bad, test/types/sync/lydia/arrayOfArrayOfSyncsInField.future, test/types/sync/lydia/arrayOfArrayOfSyncsInField.prediff
With the `sync`/`single` implicit reads/writes deprecation, the `init=` for the implementing records were marked as deprecated. This causes `isCopyableType` to throw a deprecation warning when it trys to resolve the `init=` while checking if a type is copyable (bug reported in #20984). This behavior should go away when the deprecation is removed, but until then users may get unintended deprecation warnings. This is resolved in the short term by special casing the check to not try to resolve `init=` for `sync`/`single`. In the long term, this special case can be removed when the deprecated `init=` is removed.
- add a check for a `sync` or `single` before trying to resolve `init=` in `setRecordCopyableFlags`
- explicitly set `FLAG_TYPE_INIT_EQUAL_FROM_CONST` for `sync`/`single` to maintain …
=> Special case `isCopyableType` to avoid warning

test/studies/colostate/Jacobi1D-DiamondByHand-OMP_dyn.test.c, test/studies/colostate/Jacobi1D-DiamondByHand-OMP_static.test.c, test/studies/colostate/cfd-mini-c.test.c
After the testing infra change in https://github.com/chapel-lang/chapel/pull/22611, some performance tests are failing because they emit non-zero exit codes.
The following C tests are updated to `reaturn 0` from `main` instead of `1` to avoid these failures:
- studies/colostate/Jacobi1D-DiamondByHand-OMP_dyn
- studies/colostate/Jacobi1D-DiamondByHand-OMP_static
- studies/colostate/cfd-mini-c
=> Remove uneeded non-zero exit codes from performance tests

test/types/cptr/func_ptr_as_c_fn_ptr.skipif, test/types/cptr/func_ptr_as_void_ptr.chpl, test/types/cptr/func_ptr_as_void_ptr.skipif
This PR adjusts func_ptr_as_c_fn_ptr after PR #21894 caused it to start passing in non-baseline C backend configurations. That PR changed some of the temporaries for module-scope statements to not be module-scope but rather local variables. That allowed the denormalizer to be more effective and removed the expression that caused a problem. 
Meanwhile, based on the .future text, I think that perhaps func_ptr_as_c_fn_ptr was only ever intended to run in `--baseline` configurations and in fact it still fails there. So, this PR updates the .skipif to skip non-baseline configurations.
While there, I updated the skipif for func_ptr_as_void_ptr in a similar (that one was missing the part about skipping for the LLVM backend) and adjusted that test to resolve a compilation error due to a missing …
=> Fix up func_ptr_as_c_fn_ptr / func_ptr_as_void_ptr

modules/standard/IO.chpl, runtime/src/qio/qio.c, test/compflags/TestWarnUnstableSuppression.3.good, test/compflags/TestWarnUnstableSuppression.5.good, test/compflags/TestWarnUnstableSuppression.6.good, test/compflags/TestWarnUnstableSuppression.7.good, test/library/standard/IO/append/.gitignore, test/library/standard/IO/append/append.chpl, test/library/standard/IO/append/append.cleanfiles, test/library/standard/IO/append/append.good, test/library/standard/IO/append/multipleWriters.chpl, test/library/standard/IO/append/multipleWriters.future, test/library/standard/IO/append/multipleWriters.noexec, test/library/standard/IO/append/multipleWriters.notest, test/unstable/ioModeAppend.chpl, test/unstable/ioModeAppend.cleanfiles, test/unstable/ioModeAppend.good
Implements a prototype implementation for appending to a file, discussed in #22084 and #9992. It only supports one `fileWriter` at a time, using more can cause races.
- enable ioMode.a in `IO.chpl` and `qio.c`
- `test/library/standard/IO/append/append.chpl`
- `test/library/standard/IO/append/multipleWriters.chpl`
- marked as `notest`, but including as it exhibits the potential races
- `test/unstable/ioModeAppend.chpl`
=> Prototype for `ioMode.a`supporting one `fileWriter`

frontend/include/chpl/resolution/resolution-types.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testForwarding.cpp
This PR implements forwarding to methods expressions in a class or record, which is a recurring pattern in our internal/standard modules.
Previously, we were resolving forwarding statements at the same time we were resolving fields. The core of this PR is to separate the resolution of forwarding statements involving expressions, like "forwarding foo()", and resolve them later during ``gatherAndFilterCandidatesForwarding``. To allow for resolving this kind of forwarding statement the ``Resolver`` implementation was updated to more broadly infer a potential method receiver type.
Other changes to account for newly exposed issues were:
- Fixing ``createForParentClassScopeResolve`` to start scope resolving at the parent symbol, not the class itself
- Attempting to set the correct ID for …
=> Dyno: Implement forwarding to methods

test/classes/override/override-making-arg-default.bad, test/classes/override/override-making-arg-default.chpl, test/classes/override/override-making-arg-default.future, test/classes/override/override-making-arg-default.good
Add a future for #17679 and #22517.
=> Add future for compiler segfault when overriding method gives default value to arg which didn't have one in base class

modules/internal/ChapelArray.chpl, modules/internal/ChapelBase.chpl, modules/internal/ChapelDomain.chpl, modules/internal/ChapelRange.chpl, modules/internal/DefaultRectangular.chpl, modules/standard/ChapelIO.chpl, modules/standard/DynamicIters.chpl, test/deprecated/intIdxType.chpl, test/deprecated/intIdxType.good, test/expressions/if-expr/unexpected-AST.chpl
Since our reviews of the domain and range modules... last year?... I've owned a task to look at the uses of intIdxType, which I believe I introduced without much discussion or review, to see whether I thought it should be part of the stable interface of ranges, domains, and arrays for Chapel 2.0.  Checking the code validated my sense that it's not really used outside of our internal modules (which is what I'd expected/hoped), which makes it seem like an obvious candidate for deprecation and replacement with an internal method.
To that end, I've deprecated the methods that were documented (on domains and arrays) and renamed the versions on ranges and domains for our own continued use (the range version was already @nodoc'd, so didn't really need deprecation; and the array's version wasn't …
=> Deprecate/rename the intIdxType queries on ranges, domains and arrays

util/cron/common-arkouda.bash, util/cron/test-perf.chapcs.arkouda.release.bash, util/cron/test-perf.cray-cs-hdr.arkouda.release.bash
See https://github.com/Bears-R-Us/arkouda/pull/2552 and https://github.com/Bears-R-Us/arkouda/pull/2551
=> Upgrade Arkouda release testing from 1.30 to 1.31

compiler/codegen/codegen.cpp, compiler/include/driver.h, compiler/main/driver.cpp, doc/rst/technotes/llvm.rst, man/chpl.rst, test/compflags/bradc/help/userhelp.good, test/llvm/llvmOptRemarks/shouldBeInlined-optFailed.good, test/llvm/llvmOptRemarks/shouldBeInlined.chpl, test/llvm/llvmOptRemarks/shouldBeInlined.compopts, test/llvm/llvmOptRemarks/shouldBeInlined.good, test/llvm/llvmOptRemarks/shouldBeInlined.noexec, test/llvm/llvmOptRemarks/shouldBeInlined.prediff, test/llvm/llvmOptRemarks/shouldBeInlined.skipif, util/chpl-completion.bash
Adds flags to report LLVM optimization remarks, which allows inspecting which optimizations did/did not occur without inspecting the assembly. This is a general tool which should resolve #22596.
This adds two new flags, `--llvm-remarks` and `--llvm-remarks-function`. Use of either causes remarks to be emitted or they can be combined for filtering of which optimization remarks are emitted.
- `--llvm-remarks`: regex filtering based on the optimization pass name
- `--llvm-remarks-function`: comma separated list of function names to filter for
- Implement new flags, `--llvm-remarks` is passed directly to LLVM
- Add documentation to the LLVM technote 
- `test/llvm/llvmOptRemarks/shouldBeInlined.chpl`
=> User flags to inspect LLVM optimizations

doc/rst/developer/bestPractices/Sanitizers.rst
Rationale: I almost never want to asan the compiler, and find the traditional instructions that start by setting something and then unsetting it (while not unsetting other things that need not bet set) to be roundabout and to require far too much thinking.
I also added a comment to the CHPL_LLVM=none case for exe-only because there's really no need to rebuild the compiler just to use the C back-end, so I put the option of just switching to the C back-end as an option.
=> Separate instructions for asan-ing compiler+exe vs. just exe

frontend/lib/resolution/resolution-queries.cpp, frontend/lib/util/clang-integration.cpp, make/compiler/Makefile.gnu
Recently on my desktop machine I updated to gcc 13.1.1, ever since then I get these error when compiling Chapel:
```
[  0%] Building CXX object frontend/lib/CMakeFiles/ChplFrontend-obj.dir/util/clang-integration.cpp.o
/home/stonea/chapel/frontend/lib/util/clang-integration.cpp: In function ‘chpl::owned<chpl::TemporaryFileResult>& chpl::util::createClangPrecompiledHeader(chpl::Context*, chpl::ID)’:
/home/stonea/chapel/frontend/lib/util/clang-integration.cpp:252:37: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
252 |     const std::vector<std::string>& cc1args =
|                                     ^~~~~~~
/home/stonea/chapel/frontend/lib/util/clang-integration.cpp:253:24: note: the temporary was destroyed at the end of the full expression …
```
=> Invalid warning when compiling frontend with gcc 13

compiler/codegen/cg-expr.cpp, compiler/codegen/cg-stmt.cpp, compiler/codegen/cg-symbol.cpp, compiler/include/genret.h, compiler/include/llvmUtil.h, compiler/llvm/llvmUtil.cpp, test/llvm/with-opaque-ptrs/lifetime-intrinsics/NOTEST, test/llvm/with-typed-ptrs/lifetime-intrinsics/NOTEST
This is sortof continuing PR #22439 which removed the generation of llvm.invariant.start (while llvm.invariant.end was not generated, leading to bugs). This PR entirely removes the llvm.lifetime.start / llvm.lifetime.end as well because I don't think that what we are doing today adds any value beyond what can be assumed of a function local variable (namely: the variable lifetime starts at the `alloca` and ends when the function returns).
I spent a while trying to get llvm.lifetime.start / llvm.invariant.start to work the way I think would be ideal, but that was more challenging than I anticipated. I observed several issues:
* control flow is hard to analyze at code generation time (where do llvm.lifetime.end hints belong?). In particular for llvm.invariant.start / llvm.invariant.end, the …
=> Stop generating llvm.lifetime.start / llvm.lifetime.end

test/llvm/llvmOptRemarks/shouldBeInlined.good, test/llvm/llvmOptRemarks/shouldBeInlined.prediff, test/llvm/llvmOptRemarks/shouldBeInlined.skipif
A recently added test is susceptible to both the configuration (gasnet, valgrind, etc) and llvm version, this PR improves both the `.skipif` and the `.prediff` for the test to resolve this.
Test: `test/llvm/llvmOptRemarks/shouldBeInlined.chpl`
=> Improve filtering for LLVM opt test

modules/standard/IO.chpl
Rearranges the `where` clauses for some IO functions to be more readable in the generated documentation. 
- move the check for `t` equal to `int(8)` or `uint(8)` to the end of the statement which makes the docs slightly better.
- manually inlined `hasUnitStride`, I think this actually makes the `where` clause more verbose and potentially harder to immediately understand, but the function is currently marked `nodoc`.
- For `where` clauses which accept an array and check `.rank` (or others), modified the ones which refer to the domain to just use the array.
- paratest
[Reviewed by @bradcray and @nikkirad]
=> Refactor `where` clauses for `IO.chpl` to improve documentation

compiler/llvm/llvm-global-to-wide/CMakeLists.txt, compiler/llvm/llvm-global-to-wide/RUN_CONFIG, compiler/llvm/llvm-global-to-wide/llvmPgasPlugin.cpp, compiler/llvm/llvm-global-to-wide/test/a.ll, compiler/llvm/llvm-global-to-wide/test/aggregate.ll, compiler/llvm/llvm-global-to-wide/test/b.ll, compiler/llvm/llvm-global-to-wide/test/c.ll, compiler/llvm/llvm-global-to-wide/test/d.ll, compiler/llvm/llvm-global-to-wide/test/e.ll, compiler/llvm/llvm-global-to-wide/test/f.ll, compiler/llvm/llvm-global-to-wide/test/g.ll, compiler/llvm/llvmAggregateGlobalOps.cpp
In trying to debug a problem with `--llvm-wide-opt` with opaque pointers enabled, I sought to run the LLVM lit-style tests that exist for that pass with opaque pointers. I had trouble running these tests due to changes in the build process but I got them working eventually (on my system, anyway).
This PR:
* updates the compiler/llvm/llvm-global-to-wide test directory to be able to build and test the passes with LLVM 15
* updates the tests themselves to have opaque pointer input and output
Note that these tests do not run in any nightly testing configuration. The TODO of adding such testing is covered in issue #11192.
Test change only.
=> Migrate llvm-global-to-wide testing to opaque pointers

modules/internal/SharedObject.chpl, modules/packages/ReplicatedVar.chpl
For https://github.com/Cray/chapel-private/issues/5003
This PR improves where clauses in SharedObject and ReplicatedVar to have only user-facing things in them because we are now showing the where clauses in the generated documentation.
Reviewed by @jeremiah-corrado - thanks!
=> Improve where clauses in SharedObject and ReplicatedVar

test/gpu/native/measureGpuCycles.chpl, test/gpu/native/measureGpuCycles.good
The measureGpuCycles.chpl test does a verification test by running a series of progressively larger loops. It performs a correctness check to verify that the larger loops always run for a longer amount of time compared to the smaller loops.
Most of the times this works fine, but we've had this test fail sporadically. The `gpuClock` function is a pretty thin wrapper on the cuda `clock()` function and the vast majority of times things do run fine so I find it doubtful that this is due to any legitimate issue on our end and more likely due to noise in the system.
Nevertheless, (assuming these are false negatives), it's a bit annoying so I'm going to change the testing strategy to just assert that our clocked times for each loop is > 0 ms.
See this (internal) issue for more details: …
=> Update measureGpuCycles test to be less brittle

frontend/include/chpl/types/TupleType.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/can-pass.cpp, frontend/lib/resolution/resolution-types.cpp, frontend/lib/types/CompositeType.cpp, frontend/test/resolution/testTuples.cpp
This PR implements support for generic tuple type expressions like ``(int, ?)`` or ``(string, integral)``.
``CallInfo`` was updated to allow for multiple question marks in ``Tuple`` expressions, and improvements were made to ``canPass`` to correctly check instantiations of generic tuples. Tests involving generic tuple types have been added to the ``testTuples`` suite.
Testing:
=> Dyno: Implement generic tuple type expressions

doc/rst/platforms/libfabric.rst, runtime/src/comm/ofi/comm-ofi.c
The `CHPL_RT_COMM_OFI_EP_COUNT` environment variable was added as an expedient workaround to the erroneous `ep_cnt` value returned by the `cxi` provider. However, it requires documentation and relies on the user to specify a large enough value to bind all cores to endpoints. Instead, until the `cxi` bug is fixed, simply assume the `cxi` provider can create as many endpoints as we need.
Resolves https://github.com/Cray/chapel-private/issues/5025 and resolves https://github.com/Cray/chapel-private/issues/4968.
=> Remove CHPL_RT_COMM_OFI_EP_COUNT

modules/internal/ChapelRange.chpl, modules/standard/ChapelIO.chpl, test/types/range/align/rangeAlignTest.chpl, test/types/range/align/rangeAlignTest.good, test/types/range/enum/rangeCastsWithEnum.good
This PR makes no user-facing changes. The key implementation changes are:
(1) Remove `range._aligned`.  An unaligned range is indicated by storing -1 in its field `range._alignment`.
(2) Switch the type of `range._alignment` from `chpl_integralIdxType`, formerly `intIdxType`, to `strType`. This allows this field to store -1 for a range with an unsigned idxType. Since the alignment is stored normalized as of #22225, the value of `range._alignment` will never overflow `strType`.
"While there" implementation changes: rename `hasParamAlignmentVal()` to `hasParamAlignmentField()` (this is not a user-facing function); slightly reorganize some code so it looks better; simplify some code where the "aligned" property does not need to be passed separately; change some casts between integer types. …
=> Remove range._aligned field

modules/internal/Bytes.chpl, modules/internal/BytesStringCommon.chpl, modules/internal/String.chpl, modules/standard/Errors.chpl, test/deprecated/cpSplittingError.chpl, test/deprecated/cpSplittingError.good, test/types/string/ilseqByteSlice.good, test/types/string/ilseqByteSlice2.good
Per the discussion summarized [here](https://github.com/chapel-lang/chapel/issues/21069#issuecomment-1611857359), rename `CodepointSplittingError` to `CodepointSplitError`.
Also updates some `string` and `bytes` docs to link to `CodepointSplitError` and `DecodeError`.
=> Rename `CodepointSplittingError` to `CodepointSplitError`

compiler/llvm/clangUtil.cpp, compiler/main/driver.cpp, test/compflags/ferguson/mllvm-badarg.chpl, test/compflags/ferguson/mllvm-badarg.compopts, test/compflags/ferguson/mllvm-badarg.good, test/compflags/ferguson/mllvm-badarg.skipif, test/compflags/ferguson/mllvm-help.chpl, test/compflags/ferguson/mllvm-help.compopts, test/compflags/ferguson/mllvm-help.good, test/compflags/ferguson/mllvm-help.prediff, test/compflags/ferguson/mllvm-help.skipif
Resolves #22702
This PR is intended to resolve the confusing user experience when passing a wrong argument to `--mllvm` e.g. `chpl --mllvm --whoops`. Previously, it would refer to a fictitious command. Now, output related to such a wrong argument refers to `chpl --mllvm` and prints out a suggestion to try `chpl --mllvm --help`. Additionally, this PR arranges for `chpl --mllvm --help` to output the help information for the LLVM flags.
=> Improve `--mllvm --help`

frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/Resolver.h, frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testClasses.cpp
This PR resolves a bug in the dyno compiler where compilation could recurse through a field type's initialization expression, despite that field having a concrete type expression.
This PR adds a new field to ``Resolver`` named ``fieldTypesOnly``. This field is set in the cases where we are creating a ``Resolver`` for the purpose of resolving a type's fields. When this property is set, resolution of a ``NamedDecl`` will check if it is the field being resolved, and if so, will attempt to only use the field's type expression (if one is available). If the type expression is not a concrete type, then resolution will proceed to resolve the field's initialization expression.
This property does not apply to ``type`` or ``param`` fields since the initialization expression is necessary in those …
=> Dyno: field type resolution using only type expression

frontend/include/chpl/resolution/resolution-types.h, frontend/include/chpl/types/NothingType.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/Resolver.h, frontend/lib/resolution/prims.cpp, frontend/lib/resolution/resolution-types.cpp, frontend/lib/resolution/return-type-inference.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/lib/types/NothingType.cpp, frontend/test/resolution/testReturnTypes.cpp
This PR implements param-folding for ``select`` statements in dyno. The ``Resolver`` will iterate through each ``when`` statement and resolve a ``==`` call between the ``select``'s expression and the case's expression. This ``==`` call will be added as an ``AssociatedAction`` of the kind ``COMPARE``, which is introduced in this PR. Chapel allows for the ``otherwise`` statement to appear anywhere in the ``select`` statement, but semantically resolves it last.
If a ``when`` statement's case comparisons all return as being param-false, then the ``Resolver`` will not attempt to resolve the body of that ``when`` statement. If any case comparison returns as param-true, then the ``Resolver`` will resolve the body of that ``when`` statement and will not resolve any of the remaining ``when`` …
=> Dyno: param-folding 'select' statements

runtime/include/gpu/cpu/chpl-gpu-gen-includes.h, test/gpu/native/array_on_device/README, test/gpu/native/atomics.skipif, test/gpu/native/gpuWritelnAndAssertOnGpu.skipif, test/gpu/native/memory/basic.skipif, test/gpu/native/memory/ops.skipif, test/gpu/native/memory/sharedMemory.skipif, test/gpu/native/nestedForall.suppressif, test/gpu/native/nestedForeach.suppressif, test/gpu/native/noGpu/assertOnGpu.compopts, test/gpu/native/nvlink.skipif, test/gpu/native/sharedMemory.skipif, test/gpu/native/studies/shoc/sort.skipif, test/gpu/native/studies/tightLoopNotOnGpu/tightLoopNotOnGpu.skipif, test/gpu/native/threadBlockAndGridPrimitives.skipif, util/cron/test-gpu-cpu.bash
cpu-as-device is a (relatively) new mode for GPU support set by using `CHPL_GPU=cpu`.  This PR adds a script to conduct nightly testing in this mode and adds various `.skipif`/`.supressif` files to exempt portions of our GPU test suite that are expected (or currently don't) work in cpu-as-device mode.
The tests covered by `.suppressif` are things that I'm somewhat surprised don't currently work so we should do some followup investigation there. In the meantime though, I think locking down what currently works with nightly testing is valuable.
Somewhat tangentially: I also update a function declaration in `chpl-gpu-gen-includes.h` to avoid a compiletime warning due to the prototype having no arguments but instead of having an argument list like `foo(void)` we had it empty like: `foo()`.
=> Cpu as device job

test/deprecated/cpSplittingError.skipif
The deprecation test for `CodepointSplittingError` introduced in https://github.com/chapel-lang/chapel/pull/22678 is failing in the address sanitization config due to a potential bug summarized here: https://github.com/chapel-lang/chapel/issues/22720.
This PR updates the test to be skipped for `CHPL_SANITIZE=address` until the failure can be investigated more thoroughly.
=> Skip `CodepointSplittingError` deprecation test in asan config

test/gpu/native.skipif
Our native.skipif file was inadvertedly skipping the native/ tests even when `CHPL_GPU=cpu`. This commit fixes it.
=> Fix issue preventing nightly cpu-as-device testing

test/optimizations/sungeun/bulk_transfer/assignMultiloc.chpl, test/studies/hpcc/HPL/vass/bl.md.chpl
divceilpos and divfloorpos will soon no longer be included by default, so these tests need a use of the Math module to continue working
Checked a fresh checkout of the tests
=> Add uses of the Math module to these two tests to avoid deprecation warnings

doc/rst/technotes/gpu.rst
@stonea noticed this issue while working on https://github.com/chapel-lang/chapel/pull/22674. I am hopeful that we can solve this soon. But probably not very soon that I wanted to add a bullet in our technote. https://github.com/Cray/chapel-private/issues/5064 is the internal tracker for this effort.
=> Add a limitation about nested loops with the cpu-as-device mode

util/cron/common-champs.bash
Our nightly CHAMPS test relies on a repos where we store various patches that need to be applied. Currently we rely on manually running 'git pull' on this repos anytime a new patch is submitted. This PR updates our nightly job to run 'git pull' automatically.
To resolve: https://github.com/Cray/chapel-private/issues/3030
=> Pull champs-nightly repos for nightly job

test/gpu/native/noGpu/basicMem.prediff, test/gpu/native/studies/transpose/transpose.skipif
We have a couple of failures in our new nightly test job for cpu-as-device for GPU support.
This PR modifies these tests so that they will no longer fail in this job.
transpose.chpl: is something we should be .skip'ifing for this job (I'll submit a followup PR to do that).
basicMem.chpl: It looks like we have some non-deterministic allocations in internal module code. This isn't really what the test is trying to lock down so it seems like we should just filter these messages out.
=> Fix broken tests for new cpu-as-device nightly test

test/gpu/native/loopNaming.good, test/gpu/native/loopNaming.prediff
The loop naming GPU test was sensitive to loops being moved around in the standard library. To avoid that, I'm switching the test to only display kernel names for the `loopName.chpl` file, and not the standard library.
=> Restrict the kernel naming test to only work on the current file.

test/gpu/native/studies/multiGpuStream/multiGpuStream.chpl
The new multi-gpu stream test was timing out on AMD with `array_on_device`. Looks like it is because the validation code uses reduction that seems to be problematic in this setup: https://github.com/chapel-lang/chapel/issues/22736. For now, do sequential and manual reduction on AMD to get the test running.
With this the test passes with NVIDIA and AMD.
=> Avoid reductions with AMD+AOD in test

test/multilocale/bharshbarg/onStmtInIntent.chpl
This test can't use deinit because of the memory management issues involving the ``in`` intent. Instead, track the pointers in a list and free them manually at the end of the test.
=> Fix memory leak in onStmtInIntent future

compiler/parser/parser.cpp, frontend/include/chpl/framework/Context.h, frontend/lib/framework/Context.cpp, frontend/lib/framework/ErrorWriter.cpp, test/unstable-keyword/in-function.bad, test/unstable-keyword/in-function.future
Resolves #22752
This PR adjusts `frontend/` error message printing to use `$CHPL_HOME` as the start of the path instead of its value. This avoids inconsistencies depending on whether the error is coming from `frontend/` or the older production compiler code in `compiler/`.
=> Use $CHPL_HOME in locations printed from frontend errors

modules/internal/LocaleModelHelpSetup.chpl
Fixes an issue which showed up in our nightly testing. `init_helper` would not be resolved in some configurations
Tested in failing configuration using OFI.
=> Fix default copy init for atomics

modules/internal/localeModels/gpu/LocaleModel.chpl
Follow on to https://github.com/chapel-lang/chapel/pull/22637.
That PR missed the GPU locale model's `chpl_here_free` which was subject to the weird issue that was worked around with `raw_c_void_ptr` in that PR. This PR makes that particular `chpl_here_free` to also take a `raw_c_void_ptr` argument.
I expect all GPU testing to fail without this PR.
Test:
=> Fix chpl_here_free by using raw_c_void_ptr instead

modules/internal/ChapelPrivatization.chpl, modules/internal/localeModels/gpu/LocaleModel.chpl
Switch from `c_ptr(void)` to `raw_c_void_ptr` for the element type of a `chpl_privateObject_t` in the `ChapelPrivatization` internal module.
This is a band-aid solution to some yet-undiagnosed compiler behavior that caused a change in behavior here with the switch from an old `c_void_ptr` (`raw_c_void_ptr`) to a `c_ptr(void)`. This was causing GPU nightly test failures. It is also unknown why this only affected GPU configurations.
It should be possible to use a `c_ptr(void)` here with appropriate compiler changes, which is future work tracked in https://github.com/Cray/chapel-private/issues/5096. Along with that it is likely also possible to remove other usages of `raw_c_void_ptr` that remain as similar band-aid solutions.
Follow up to https://github.com/chapel-lang/chapel/pull/22637. …
=> Use a raw_c_void_ptr for chpl_privateObject_t

modules/internal/ChapelArray.chpl, test/compflags/TestWarnUnstableSuppression.2.good, test/compflags/TestWarnUnstableSuppression.3.good, test/compflags/TestWarnUnstableSuppression.4.good, test/compflags/TestWarnUnstableSuppression.5.good, test/compflags/TestWarnUnstableSuppression.6.good, test/compflags/TestWarnUnstableSuppression.7.good, test/compflags/TestWarnUnstableSuppression.prediff, test/distributions/block/redistBlock.comm-none.good, test/distributions/block/redistBlock.good, test/unstable-keyword/in-function.prediff, test/unstable/dmapped-sparse.chpl, test/unstable/dmapped-sparse.good
This marks the type `dmap` as unstable, as discussed in a design subteam on May 30.
While there, simplify test/compflags/TestWarnUnstableSuppression.prediff and remove test/unstable-keyword/in-function.prediff, thanks to #22757.
Testing: standard+gasnet paratests; distribution robustness suite.
=> Unstabilize `dmap`

modules/standard/BigInteger.chpl, test/deprecated/BigInteger/deprecateBitFunctions.chpl, test/deprecated/BigInteger/deprecateBitFunctions.good, test/library/standard/GMP/ldelaney/gmp_Bigint_logic_bit.chpl
Renames both the procedure name and the argument name to `bigint`'s *bit methods (#17735 and #22008)
- rename `setbit(bit_index: integral)` to `setBit(idx: integral)`
- rename `clrbit(bit_index: integral)` to `clearBit(idx: integral)`
- rename `tstbit(bit_index: integral)` to `getBit(idx: integral)`
- rename `combit(bit_index: integral)` to `toggleBit(idx: integral)`
- add documentation for these 4 functions
- includes links to the underlying GMP function's documentation
- updated tests as needed
- adds `test/deprecated/BigInteger/deprecateBitFunctions.chpl`
[Reviewed by @bmcdonald3]
closes #17735
closes #22008
closes cray/chapel-private#5095
=> Rename bigint's setbit, tstbit, combit, and clrbit methods

modules/standard/BigInteger.chpl, test/deprecated/BigInteger/argumentNames.chpl, test/deprecated/BigInteger/argumentNames.good, test/library/standard/BigInteger/modByZero.chpl, test/library/standard/BigInteger/modByZero.compopts, test/library/standard/BigInteger/modByZero.execopts, test/library/standard/BigInteger/modByZero.good, test/library/standard/BigInteger/modByZero.prediff
Adds a divide by zero check to `BigInteger.mod`, `BigInteger.%` and `BigInteger.%=` to match the divide functions (#19384). While doing this work, implemented part of the change for argument names (https://github.com/chapel-lang/chapel/issues/19005#issuecomment-1634712958).
- add a divide by zero check to `mod`
- reimplement `mod` in terms of the `divR` with the proper rounding argument
- add helper methods for `modTrunc` by a `integral` to reduce code duplication
- deprecate argument names `a`/`b` on `mod` in favor of `x`/`y`
- adds `test/library/standard/BigInteger/modByZero.chpl`
- adds `test/deprecated/BigInteger/argumentNames.chpl`
[Reviewed by @bmcdonald3]
closes #19384
closes cray/chapel-private#5094
=> Add divide by zero check to BigInteger mod

modules/standard/ChplConfig.chpl, test/compflags/TestWarnUnstableSuppression.2.good, test/compflags/TestWarnUnstableSuppression.3.good, test/compflags/TestWarnUnstableSuppression.4.good, test/compflags/TestWarnUnstableSuppression.5.good, test/compflags/TestWarnUnstableSuppression.6.good, test/compflags/TestWarnUnstableSuppression.7.good
These configuration `param`s are made unstable to give us room to change how the information is accessed in the future.
Resolves https://github.com/Cray/chapel-private/issues/5018.
Testing:
=> Unstable-ize CHPL_* params in ChplConfig

util/cron/common-native-gpu.bash, util/cron/test-perf.gpu-cuda.aod.bash, util/cron/test-perf.gpu-cuda.bash, util/cron/test-perf.gpu-rocm.bash
Makes some adjustments to one of the common scripts and adds a new one for AMD GPU performance testing.
Uses `rocm` as the distinguishing name as opposed to `amd` (we went with vector names in the recent runtime overhaul, we may want to do the same in the test names, but there are other changes coming up w.r.t GPU testing in the medium-term).
Leaves the current performance test as just `gpu`, although we probably need to suffix that with `nvidia`.
=> Add AMD GPU performance test

test/compflags/TestWarnUnstableSuppression.3.good, test/compflags/TestWarnUnstableSuppression.5.good, test/compflags/TestWarnUnstableSuppression.6.good, test/compflags/TestWarnUnstableSuppression.7.good, test/types/chplhashtable/noHashForRecordWithEq.good, test/types/chplhashtable/noHashForRecordWithEq2.good
Fixes a few test failures from https://github.com/chapel-lang/chapel/pull/22772:
- `compflags/TestWarnUnstableSuppression`
- `types/chplhashtable/noHashForRecordWithEq`
- `types/chplhashtable/noHashForRecordWithEq2`
=> Test fixes from unstabilizing `set.parSafe` and `map.parSafe`

test/gpu/native/jacobi/flags-warn-unstable.good
`test/gpu/native/jacobi/flags.chpl` uses `ChplConfig.CHPL_GPU_MEM_STRATEGY` which is unstable after https://github.com/chapel-lang/chapel/pull/22727. We see a warning for this when compiling with the `--warn-unstable` compopts set, so the `flags-warn-unstable.good` file is updated to include the warning.
Follow-up to https://github.com/chapel-lang/chapel/pull/22727.
[trivial test change, not reviewed]
Testing:
=> Re-good flags-warn-unstable.good for unstable CHPL_GPU_MEM_STRATEGY

runtime/src/qio/qio_formatted.c, test/compflags/TestWarnUnstableSuppression.3.good, test/compflags/TestWarnUnstableSuppression.5.good, test/compflags/TestWarnUnstableSuppression.6.good, test/compflags/TestWarnUnstableSuppression.7.good
The default floating point precision style for `%t` was accidentally changed in https://github.com/chapel-lang/chapel/pull/22766. This PR reverts that change.
Also fixes .good files for compflags/TestWarnUnstableSuppression, which was failing on main.
=> Revert change to `%t` default precision

test/io/ferguson/issue-16945.skipif
https://github.com/chapel-lang/chapel/pull/22766 introduced a future: `test/io/ferguson/issue-16945.chpl` which produces different output for `CHPL_COMM != none` or `--no-local`. This PR adds a check to the tests `skipif` for `--no-local` to avoid a test failure in that configuration.
=> Fix io future test failure

compiler/llvm/clangUtil.cpp, runtime/src/gpu/amd/gpu-amd.c, test/gpu/native/array_on_device/studies/shoc/triadAodAsync.skipif, test/gpu/native/math.chpl, test/gpu/native/multiGPU/worksharing.chpl, test/gpu/native/multiGPU/worksharing.skipif, test/gpu/native/multiGPU/worksharingBasic.chpl, test/gpu/native/multiGPU/worksharingBasic.skipif, test/gpu/native/studies/shoc/triadchpl.skipif
This PR:
* Updates things so the `asyncGpuComm` proc in the GPU module now works when using `CHPL_GPU=amd`. For some reason `hipify-perl` struggles to find the right API to translate the cuda code in our runtime lib for the underlying CUDA API call we make for this (hence why I didn't just get to work from the "get go". But replacing it with the "obvious" API (using `hipMemcpyAsync` in place of `cuMemcpyAsync`) seems to work.
* Fix a bug in how we filter out what extern functions we consider linking to when doing the  GPU pass of code generation. We're supposed to limit ourselves to `__device__` functions but for some reason some non device math functions from the C++ standard lib were getting through and this was causing issues for us if we ever called the corresponding functions in GPU …
=> Improve AMD GPU support parity (asyncGpuComm, more math functions)

util/cron/test-gpu-cuda.aod.bash, util/cron/test-gpu-cuda.bash, util/cron/test-gpu-cuda.gasnet.bash
In https://github.com/chapel-lang/chapel/pull/22785, I made some changes that caused CUDA testing to use the default partition on the testing system. This PR makes sure that we have the correct partition used for CUDA testing.
=> Add launcher partition back to cuda tests

third-party/hwloc/Makefile
We've historically had issues generating the hwloc README and did some file touching to try to trick the build system into not generating it. Hwloc 2.8 added a `--disable-readme` option, so now that we've upgraded to 2.9 we can use that option instead of touching specific files.
For more context see #19522 and open-mpi/hwloc#526
=> Disable hwloc readme generation

runtime/src/comm/gasnet/comm-gasnet.c, runtime/src/comm/ofi/comm-ofi.c, runtime/src/comm/ugni/comm-ugni.c, test/multilocale/numLocales/bradc/testVFlag.comm-gasnet.goodcont, test/multilocale/numLocales/bradc/testVFlag.comm-ofi.goodcont, test/multilocale/numLocales/bradc/testVFlag.comm-ugni.goodcont, test/multilocale/numLocales/bradc/testVFlag.prediff, test/multilocale/numLocales/bradc/testVerboseFlag.comm-gasnet.goodcont, test/multilocale/numLocales/bradc/testVerboseFlag.comm-ofi.goodcont, test/multilocale/numLocales/bradc/testVerboseFlag.comm-ugni.goodcont, test/multilocale/numLocales/bradc/testVerboseFlag.prediff
Change the wording of the multi-locale informational message from the form
executing on node 8 of 10 node(s): amd-0005
to the form
executing locale 8 of 10 on node 'amd-0005'
to make the distinction between locales and nodes clearer.
Resolves https://github.com/Cray/chapel-private/issues/4909.
=> Change wording of multi-locale informational message

compiler/passes/normalize.cpp, compiler/resolution/wrappers.cpp, frontend/include/chpl/uast/PragmaList.h, test/deprecated/implicit-numeric-to-int-qw-etc.chpl, test/deprecated/implicit-numeric-to-int-qw-etc.good, test/functions/bradc/resolution/smallIntBoolTests/boolInt-testenum.good, test/functions/bradc/resolution/smallIntBoolTests/boolInt.chpl, test/functions/bradc/resolution/smallIntBoolTests/paramNon.chpl, test/functions/bradc/resolution/smallIntBoolTests/paramNon2.chpl, test/functions/bradc/resolution/smallIntBoolTests/paramNon3.chpl, test/types/coerce/ferguson/coercion-dispatch-minimal-modules.chpl
Resolves #20011
This PR implements a warning to deprecate implicit conversion when passing to formal types such as `int(?w)`. Such formal types have historically been implemented by an early stamping-out process within the compiler, but we want to make them behave the same as generic formals. Since generic formals don't allow numeric implicit conversion, neither should these.
The implementation approach here is to add a flag to such formals that are stamped-out in `cloneParameterizedPrimitive` in normalize.cpp and then check for this flag in `handleCoercion` in wrappers.cpp.
The warning currently only applies to formals declared in user modules. I explored enabling the warning more broadly and observed 19 failures in full testing, primarily with lulesh implementations. It looks like these …
=> Add warning for deprecated implicit conversion to int(?w) etc

test/gpu/native/largeLoop.skipif
The largeLoop gpu test checks what happens if you have a gpuizable loop who's upper bound exceeds the bounds of a 32-bit signed integer.
Now that we do nightly cpu-as-device testing, this test is timing out for taking too long in that mode. On the one hand, having this test might seem silly, on the other checking boundary conditions is what testing is all about.
I could bump the timeout threshold but it seems unlikely that this test would fail in cpu-as-device mode and not in GPU mode. I could also just remove the test, but again it seems to be working fine for our nightly GPU tests and it seems like a "nice to have" sort of thing.
So I'm inclined to keep this test, but skip it for our cpu-as-device job.
Though, ideally, even in the GPU case (given that even there I think its long …
=> Add skipif largeloop cpu

test/gpu/native/studies/gpuArrayOps/gpuArrayOps.gpu-keys, test/gpu/native/studies/gpuArrayOps/gpuArrayOps.graph, test/gpu/native/studies/transpose/transpose-throughput.graph, test/gpu/native/studies/transpose/transpose.gpu-keys
Follow on to https://github.com/chapel-lang/chapel/pull/22349.
I did some late fixes in new performance tests w.r.t the reported units. I forgot to update the relevant keys files. This PR fixes that.
Two tests in question pass in performance setting with this PR.
=> Fix performance-related files in two GPU tests

modules/packages/BLAS.chpl, modules/packages/Crypto.chpl, modules/standard/Errors.chpl, modules/standard/FileSystem.chpl, modules/standard/IO.chpl, modules/standard/MemMove.chpl, modules/standard/Path.chpl, test/deprecated/illegalArgumentErrorInit.chpl, test/deprecated/illegalArgumentErrorInit.good, test/errhandling/psahabu/coforall-try-bang.chpl, test/expressions/casts/enumCastErrors-4.good, test/expressions/casts/enumCastErrors-8.good, test/io/ferguson/bits-errors.big-readbits.good, test/io/ferguson/bits-errors.big-writebits.good, test/io/ferguson/bits-errors.negative-readbits.good, test/io/ferguson/bits-errors.negative-writebits.good, test/io/jade/readBits-castchecking.good, test/library/standard/Path/king-11/replaceExt/cases.good, test/types/enum/diten/varEnumOutOfBounds.good, test/types/range/enum/castEnumRange4a.good, test/types/range/enum/rangeCastsWithEnum.good
In discussion summarized here: https://github.com/chapel-lang/chapel/issues/19803#issuecomment-1638946105, we decided to deprecate `IllegalArgumentError`'s two-argument initializer in favor of its single-arg initializer. This PR makes that change and updates module code and tests accordingly.
=> Deprecate `IllegalArgumentError`'s two-argument intializer

modules/packages/YAML.chpl
Fix a test failure following https://github.com/chapel-lang/chapel/pull/22068 by replacing a call to `stringify` with `"%?".format()` in the Yaml module.
=> Remove `stringify` call from Yaml serializer

util/cron/nightly, util/cron/nightly_email.pm, util/cron/nightlysubs.pm, util/cron/test-email.bash
This PR will add code to create email.txt file in the Jenkins workspace.
Email.txt will be used by Jenkins to send emails in case of build/test failures and success.
https://github.com/Cray/chapel-private/issues/5144
=> Added code to create email.txt

test/gpu/native/studies/gpuArrayOps/gpuArrayOps.chpl, test/gpu/native/studies/gpuArrayOps/gpuArrayOps.gpu-keys, test/gpu/native/studies/gpuArrayOps/gpuArrayOps.graph, test/gpu/native/studies/transpose/transpose-throughput.graph, test/gpu/native/studies/transpose/transpose.chpl, test/gpu/native/studies/transpose/transpose.gpu-keys
Further fallout from test changes. I switched to reporting `GiB/s` instead of `GB/s` but we already have performance data with `GB/s`. This PR reverts back to GB/s while reporting. But the generated plot will have `GiB/s` in its y-axis label. I also add some comments about the units.
Tests pass under correctness and performance settings.
=> Revert back to using GB/s in gpu performance tests

util/cron/common-arkouda.bash
Today, Arkouda graphs show the release version by default, which means that changes to Chapel will be missed. Switching this to default to nightly will make it more obvious of Chapel-side changes that impact Arkouda.
=> Switch Arkouda graphs to display nightly by default

test/gpu/native/studies/coral/coral.chpl, test/gpu/native/studies/coral/coral.gpu-compopts, test/gpu/native/studies/coral/modules/distance_iter.chpl, test/gpu/native/studies/coral/modules/distance_mask.chpl
This PR patches the Coral Image Analysis GPU performance test to have some of the application level optimizations that I had developed in the past. https://github.com/Cray/chapel-private/issues/4827 has the detailed discussion on those optimizations. But the summary is:
(All performance results are with 8000x8000 input with windowSize 100. V100 was the GPU used)
1. Reduce block size to 64: The kernel is relatively large and requires a lot of registers. If you have a lot of threads within a block (threads in the same block share the same physical memory for registers and L1), you end up thrashing registers a lot. (~3.2x improvement over base)
2. Transpose input array: Without transposing the input, GPU threads read sequential data individually, which is intuitive for CPUs. But you want to …
=> Application-level optimizations for the Coral Image Analysis code

test/gpu/native/streamPrototype/stream.chpl, test/gpu/native/studies/coral/coral.chpl
This PR fixes two tests to have better performance outside of the timed region with `CHPL_GPU_MEM_STRATEGY=array_on_device`. The changes are similar to what I've done in the past -- (1) use smaller `on gpu` regions, and/or (2) do `on host` regions for output validation.
Both tests run significantly faster overall and pass correctness changes with these.
=> Fix two tests to have less host/device comm

runtime/src/comm/ofi/Makefile.share, runtime/src/comm/ofi/comm-ofi-hugepages.c, runtime/src/comm/ofi/comm-ofi-internal.h, runtime/src/comm/ofi/comm-ofi-launch.c, runtime/src/comm/ofi/comm-ofi-no-hugepages.c, runtime/src/comm/ofi/comm-ofi.c
Enable use of hugepages on the hpe-cray-ex platform. Due to limitations in the hugepage interface, the runtime will not size the heap dynamically based on available physical memory, but will instead use the default heap size or the size specified by `CHPL_RT_MAX_HEAP_SIZE`. The program may fail with an out-of-memory error if there is insufficient physical memory for the heap.
The `CHPL_RT_COMM_OFI_USE_HUGEPAGES` environment variable controls whether or not hugepage support is included in the Chapel runtime. The `CHPL_RT_COMM_OFI_USE_HUGEPAGES` variable controls whether or not hugepages are used at runtime.
Resolves #https://github.com/Cray/chapel-private/issues/4844 and resolved https://github.com/Cray/chapel-private/issues/3141.
=> Enable use of hugepages on the hpe-cray-ex platform

test/library/packages/LinearAlgebra/correctness/inv-test.chpl
Adjusts a test to adapt to the new error from PR #22816.
=> Avoid lvalue error in inv-test.chpl

compiler/resolution/fcf-support.cpp
With the serializer implementation, FCFs were being printed in the JSON serializer without `"`s, which made it invalid JSON. This was caught while converting Arkouda to use the new serializers. This PR switches the compiler to call `write` instead of `writeIt` for FCFs.
=> Switch to calling `write` instead of `writeIt` for FCFs

runtime/src/comm/ofi/comm-ofi.c
The environment variable `CHPL_RT_COMM_OFI_NEED_FIXED_HEAP` causes the `ofi` comm layer to create a fixed heap even if one isn't required, e.g., the provider doesn't require one, or there is only one locale (in which case the comm layer isn't fully initialized). This is useful to applications that want to ensure there is a fixed heap that can be accessed via `chpl_comm_regMemHeapInfo`().
Resolves #22384
=> Allow user to force creation of fixed heap with comm=ofi

util/test/sub_test.py
At this time, sub_test expects `Popen` to behave the way it did in Python 2. That is, it expects Popen to convert the output and error streams to a string, unless it can't, in which case it keeps them as bytes. Python's new Popen uses bytes exclusively. Furthermore, a brief analysis of the sub_test code seems to indicate that it doesn't properly handle the bytes case, even assuming Python 2 behavior: it passes a bytes object to various string methods and `stdout.write`, both of which are string-only.
Motivated by all of this, this PR switches to using plain Python 3 Popen (instead of using the custom compatibility shim that preserved Python 2's behavior). It also makes the decision to immediately encode all outputs from Popen as strings, using surrogate pair encoding to avoid dropping …
=> Adjust sub_test to no longer rely on Python 2's Popen behavior

test/runtime/configMatters/launch/jhh/reservation/reservation.py
Use the `pop` method to avoid exceptions when deleting a non-existent key from a dictionary. This way is a lot cleaner than using `try`.
=> Clean up how environment variables are deleted

util/test/sub_test.py
This is a bug I introduced in #22831.
Reviewed by @ronawho -- thanks!
=> Fix unrecognized use of 'p' in sub_test.

test/c2chapel/c2chapel-tester.good, test/c2chapel/printfGen.chpl
Updates `c2chapel-tester.good` to expect the "OK" output from the tester on the new `nestedArrays` test from https://github.com/chapel-lang/chapel/pull/22813.
Follow up to https://github.com/chapel-lang/chapel/pull/22813, I forgot to check for this before merging.
[trivial test fix, not reviewed]
Testing:
=> Add new `nestedArrays` test to `c2chapel-tester.good`

test/domains/sungeun/assoc/stress.numthr.skipif, test/domains/sungeun/assoc/stress.skipif, test/exercises/RandomNumber6.skipif, test/parallel/cobegin/deitz/test_many_threads.skipif
Some tests that create a lot of concurrent tasks lower the stack size to run on systems with limited memory. This was causing issues for a few tests under baseline since we were exceeded a 128k stack size. This is an unusual situation (small stack size and baseline) so just skip all tests using less than 256K stacks under baseline.
=> Skip tests that use a really small stack size under baseline

test/gpu/native/largeLoop.compopts, test/gpu/native/largeLoop.good
The "largeLoop" test times out occasionally. It is important to have a loop tripping enough times to overflow a 32-bit ints. So, I can't make the loop shorter. But luckily `--fast` improves the kernel performance significantly (`--no-checks` is already implied).
The test is about 2x faster with gasnet after this PR.
=> Use --fast in a GPU test that times out occasionally

modules/dists/BlockDist.chpl, modules/dists/SparseBlockDist.chpl, modules/internal/ChapelDomain.chpl, test/distributions/sparseBlock/distTypeTest.chpl, test/distributions/sparseBlock/distTypeTest.good
I'd failed to anticipate that if someone made a `.distribution` query on a sparse block-distributed domain that we'd get an old `_distribution()` object back, wrapping a `BlockImpl` class, rather than the new `Block` record type that we'd expect.  It turns out that this tripped up some of the logic in the LinearAlgebra module that was trying to reason about whether a given matrix was distributed or not.  This PR fixes that by adding the new dsiGetDist() call to the SparseBlockDom class, similar to the BlockDom class.
Though that change got the `.distribution` query working properly, it then led to an internal error for some code patterns, which turned out to be due to a code path in 'defaultSparseDist()' that was expecting all domain values to have a `.dist` field that they could use …
=> Fix up distributions for Block-Sparse Domains/Arrays

modules/dists/SparseBlockDist.chpl
I'd mistakenly only tested #22893 with CHPL_COMM=gasnet, thinking that the change was so multi-locale specific that passing there would ensure passing for CHPL_COMM=none.  A post-merge check pointed out I was wrong due to a branch of a param conditional containing a typo.  This fixes that typo.
=> Fix dumb typo

modules/internal/ChapelArray.chpl
In refactoring 'Block' to be a record, I inadvertently added an extra copy of the 'Block' record when creating a new distribution for many common code patterns.  This PR removes the extra copy by updating the 'chpl__buildDistValue() routine (which is intended to just be a pass-through for the case of a record-based distribution) from:
```chapel
proc chpl__buildDistValue(x:record) {
return x;
}
```
to:
```chapel
proc chpl__buildDistValue(ref x:record) ref {
return x;
}
```
I'd naively assumed/hoped that with the default intents, copy elision would simply have done this for me automatically, but no such luck.
I then had to do a similar update to the version of chpl__buildDistDMapValue() that takes records for
backwards-compatibility.
This extra copy was only detected by one of our GPU tests …
=> Reduce the number of copies of a 'Block' record made in common code patterns

compiler/codegen/cg-expr.cpp, modules/internal/ChapelGpuSupport.chpl, modules/standard/Communication.chpl
PR #2884 added a dereference in code that is now `codegenPutGet`, so that `chpl_string_comm_get` could use the primitive to move data from one `c_ptr` to another.
However, efforts to replace `c_string` with `c_ptrConst(c_char)` in #22622 have run into challenges due to this change. In particular, since `c_string` used to be a primitive type (meaning it did not have `FLAG_DATA_CLASS`, but its replacement does have that flag, we were seeing problems in an HDF5 test related to this logic, when trying to bulk transfer arrays of `c_string` / `c_ptrConst(c_char)`. But, the array bulk transfer logic shouldn't be dereferencing `c_ptr` elements, so this seems to be a latent bug.
The fix here is to change the primitive to always expect references and to adjust the Chapel code invoking it to create …
=> Deprecate dereference in put/get primitives

compiler/llvm/clangUtil.cpp
Resolves https://github.com/chapel-lang/chapel/issues/22112.
This PR has to be merged after https://github.com/chapel-lang/chapel/pull/22840 as it resolves a bug that this bumps into.
Today, we link device bitcode library after the optimization pipeline is run. This means we are missing crucial optimization opportunities around functions in device libraries. At least for nvidia, these are math and bit operation functions. One of those optimization opportunities is inlining, and the fact that we were missing it was reported in #22112. Later on @milthorpe also confirmed that this had noticeable impact on miniBUDE performance on GPU.
This PR moves bitcode device library linking early in compilation to benefit from the optimizations in our standard optimization pipeline. I have some vague …
=> Link bitcode device libraries before the optimization pipeline

test/chpldoc/enum.doc.good, test/chpldoc/enum/deprecatedEnum.doc.good, test/chpldoc/enum/docConstants.doc.good, test/chpldoc/globals/enums.doc.good, test/chpldoc/types/arguments/enums.doc.good, test/chpldoc/types/fields/enums.doc.good, test/chpldoc/types/returns/enums.doc.good, third-party/chpl-venv/chpldoc-requirements3.txt, tools/chpldoc/chpldoc.cpp
This PR, along with [sphinxcontrib-chapeldomain PR #74](https://github.com/chapel-lang/sphinxcontrib-chapeldomain/pull/74), contains changes made to `chpldoc.cpp` to generate documentation for each enum constant rather than only for the enum. Solution to #5022.
Previously, documentation for enum constants have been either nonexistent, or written in different ways (such as a table) in order to be shown. Since this form of documentation is already available for other types that contain inner content (i.e. records), it is intuitive for enum constant documentation to exist as well.
These changes allow chpldoc to recognize enum constants (written as `EnumElement` in the AST) as enum's children. However, only prefix comments will be recognized and documented. There is intent to allow suffix …
=> Add enum constant Documentation

modules/standard/BigInteger.chpl, test/deprecated/BigInteger/argumentNames.chpl, test/deprecated/BigInteger/argumentNames.compopts, test/deprecated/BigInteger/argumentNames.good
Renames remaining BigInteger arguments to `x` and `y`, unless they imparted a special meaning of their functionality (like `n` or `numer`). This unifies argument names for differing types in overloaded functions. 
Implements changes from https://github.com/chapel-lang/chapel/issues/19005#issuecomment-1634712958
- change arguments of `init(num)` and `init(str)` to `init(x)`
- also changed `init=`, but that should not be a user facing change 
- change arguments of `root(result, a, b)` to `root(result, x, y)`
- change arguments of `sqrt(result, a)` to `sqrt(result, x)`
- change arguments of `invert(result, a)` to `invert(result, x)`
- change arguments of `add(result, a, b)` to `add(result, x, y)`
- change arguments of `sub(result, a, b)` to `sub(result, x, y)`
- change arguments of …
=> Rename BigInteger arguments to `x` and `y` 

modules/internal/Atomics.chpl, modules/internal/NetworkAtomics.chpl, modules/internal/fixInternalDocs.sh, modules/packages/PeekPoke.chpl, modules/packages/UnorderedAtomics.chpl, test/compflags/vass/callstack-internal-modules.d+s+.good, test/runtime/configMatters/comm/AtomicsAPI.chpl, test/runtime/configMatters/comm/atomic-stress.chpl, test/runtime/configMatters/comm/atomics-api-on.chpl, test/runtime/configMatters/comm/atomics-api.chpl, test/runtime/configMatters/comm/unordered/unorderedAtomicsApiOn.chpl
Switch the atomic formal `value` to `val` and change the value type from `T` to `valType`. `valType` was chosen to match syncs and be similar to `eltType` on arrays and `idxType`. The formal name `val` was then used to match `valType` and so we could distinguish the stored "value" in the atomic and the name of the formal more easily. The `value`->`val` formal renaming is being done without deprecation since we believe named args are never used with atomics and if we had a way to disable named args we may have just used that.
Part of Cray/chapel-private#3730
Resolves https://github.com/chapel-lang/chapel/issues/20182
=> Stabilize atomic formal and type names

modules/internal/Atomics.chpl, modules/internal/NetworkAtomics.chpl, modules/packages/DistributedDeque.chpl, test/exercises/boundedBuffer/solutions/boundedBuffer-atomic.chpl, test/studies/labelprop/labelprop-tweets.chpl, test/studies/shootout/fannkuch-redux/bharshbarg/fannkuch-redux-iter.chpl, test/studies/uts/uts_deq.chpl, test/unstable/Synchronization/COMPOPTS, test/unstable/Synchronization/compareAndSwap.chpl, test/unstable/Synchronization/compareAndSwap.good
We currently have similar atomic `compareAndSwap` and `compareExchange` methods:
```chpl
proc  compareAndSwap(    expected: valType, desired: valType): bool
proc compareExchange(ref expected: valType, desired: valType): bool
```
Where the difference is that `compareExchange` takes `expected` by ref and updates it on failure. This is more efficient when you want to update expected since it avoids having to do another read to get the current value. 
`compareExchange` aligns with the C/C++ `compare_exchange_strong` API, but is more cumbersome when you don't want to modify expected or you're using non-mutable values. It can also be confusing/surprising that `expected` gets updated, even for C/C++ users. We decided to stick with the name/behavior to match the C/C++ interface since we based the …
=> Mark atomic `compareAndSwap` as unstable

util/test/sub_test.py
This time I didn't include a variable in the pattern match.
* This particular test doesn't handle `--baseline` well and produces unexpected .bad output, which is the case that this bug affects.
=> Fix a bug in sub_test caused by my earlier refactor

util/cron/nightly
As part of the fix to remove duplicate emails sent for certain failures and fixes, comment out the line in nightly that will send an email.
issue is tracked with https://github.com/Cray/chapel-private/issues/5144
=> Comment out the line that invokes cron email

frontend/lib/parsing/ParserContextImpl.h, frontend/lib/parsing/bison-chpl-lib.cpp, frontend/lib/parsing/chpl.ypp, frontend/test/parsing/testParse.cpp
Resolves an issue introduced by #22903 where the same attribute would be attached to multiple loops, causing double frees.
Added a parse test to check the parse tree to catch this issue.
=> Resolve issue with duplicate attributes on loops

modules/standard/Math.chpl, test/deprecated/Math/mathConstantsRenamed.chpl, test/deprecated/Math/mathConstantsRenamed.good, test/exercises/c-ray/c-ray.chpl, test/exercises/c-ray/old/c-ray.chpl, test/exercises/c-ray/solutions/c-ray-1.chpl, test/exercises/c-ray/solutions/c-ray-1a.chpl, test/exercises/c-ray/solutions/c-ray-2.chpl, test/exercises/c-ray/solutions/c-ray-2a.chpl, test/exercises/c-ray/solutions/c-ray-3.chpl, test/exercises/c-ray/solutions/c-ray-3a.chpl, test/exercises/c-ray/solutions/c-ray-4.chpl, test/exercises/c-ray/solutions/c-ray-4a.chpl, test/exercises/c-ray/solutions/c-ray-5.chpl, test/exercises/c-ray/solutions/c-ray-6.chpl, test/exercises/c-ray/solutions/c-ray-7.chpl, test/exercises/c-ray/solutions/c-ray-8.chpl, test/library/standard/Math/constants.chpl, test/unstable/Math/unstableConstants.chpl, test/unstable/Math/unstableConstants.good
Resolves #19000 
In that issue, we decided to perform the following renamings:
- half_pi is renamed to halfPi
- quarter_pi is renamed to quarterPi
- recipr_pi is renamed to reciprPi
- twice_recipr_pi is renamed to twiceReciprPi
- twice_recipr_sqrt_pi is renamed to twice_recipr_sqrt_pi
- sqrt_2 is renamed to sqrt2
- recipr_sqrt_2 is renamed to reciprSqrt2
The new versions are are marked unstable because we don't think they're used
much in practice and some of them shouldn't be necessary any more due to
improvements to the compiler's handling of param computations.
Ensures that the deprecation warnings are tested by adding them to the already-
existing renaming test.  Ensures that the unstable warnings are tested by making
a new test.  Updates the old test of the math constants …
=> Rename remaining Math constants and mark them unstable

modules/internal/ChapelBase.chpl, modules/internal/ChapelDomain.chpl, modules/internal/DefaultRectangular.chpl, modules/standard/Errors.chpl
The Arkouda devs have requested that the throwing array allocation
interface have a specific type of error message thrown so that it
can be handled uniquely. This PR adds an `ArrayOOMError` for when
an array allocation fails.
Related PR: https://github.com/chapel-lang/chapel/pull/22786
=> Add an ArrayOOMError for throwing array allocation interface

modules/standard/GPU.chpl, test/gpu/native/cudaOnly/gpuAddNums/gpuAddNums_primitive.chpl, test/gpu/native/gpuWritelnAndAssertOnGpu.chpl, test/gpu/native/studies/transpose/transpose.chpl, test/gpu/native/threadBlockAndGridPrimitives.chpl
This PR removes calls to the unstable `.c_str()` in `GPU` and tests, and replaces those calls with a cast to `c_ptrConst(c_char)`. 
This should resolve test failures for GPU tests affected by the deprecation of `c_string` in https://github.com/chapel-lang/chapel/pull/22622.
TESTING:
[reviewed by @e-kayrakli - thanks!]
=> remove `c_string` literals and calls to `.c_str()` in GPU module and tests

test/interop/python/defaultValues.chpl, test/interop/python/errorMessages/badFormalIntent-cstring.chpl, test/interop/python/errorMessages/badFormalIntent-cstring.comm-none.good, test/interop/python/errorMessages/badFormalIntent-cstring.good, test/interop/python/stringAllocated.chpl, test/interop/python/stringFunctions.chpl
This PR should fix some broken testing of the python library generation feature. For now, I have just updated the test code to remove the offending use of `c_string` and methods that accept `c_string`. A future task will be to handle code generation for `c_ptrConst(c_char)`. The initial attempt to treat it similarly to `c_string` did not work, so I'm putting this in to fix the tests while I work on the python interface generation changes. 
TESTING:
failing tests addressed with this PR:
```
test/interop/python/defaultValues
test/interop/python/errorMessages/badFormalIntent-cstring
test/interop/python/stringAllocated
test/interop/python/stringFunctions
```
[reviewed by @lydia-duncan - thanks!]
=> fix deprecation warnings from c_string uses in python lib

modules/standard/GPU.chpl
Makes small adjustments to the GPU module documentation to remove `c_string` references.
=> Adjust GPU module documentation to remove c_string

test/users/ferguson/type-alias-method.future
This test was added in PR #3072 and is now working as expected after PR #22622 made some minor improvements to it while updating it for the `c_string` deprecation.
=> Un-future type-alias-method.chpl

frontend/lib/uast/post-parse-checks.cpp, test/unstable/llvmMetadata.good
Fixes unstable warning for assertVectorized not being thrown.
[not reviewed - trivial]
=> Fix unstable warning for assertVectorized

modules/packages/JSON.chpl, test/io/ferguson/json-basic.chpl, test/io/ferguson/json-basic.good, test/io/ferguson/json-basic.notest, test/studies/labelprop/labelprop-tweets.chpl, test/studies/labelprop/labelprop-tweets.notest
Fixes a bug where the `JsonDeserializer` could fail to parse a list if the element type's deserializing initializer threw an error.
Also removes some `notest` files from two Json IO tests that are now working.
=> list parsing bug fix for JsonDeserializer

test/types/string/sungeun/c_string/defaultExpr.chpl, test/types/string/sungeun/c_string/genericClassesAndRecord.chpl, test/types/string/sungeun/c_string/initExpr.chpl
This PR fixes some `c_string` tests that assign default values or initialize args of type `c_ptrConst(c_char)`. The expectation is that a future PR will address the root cause of the failure, but this just gets the test working again by adding `.c_str()` calls on the literals where needed.
I  have opened https://github.com/Cray/chapel-private/issues/5231 to resolve the workaround in these tests.
TESTING:
[test file change only - not reviewed]
=> fix failing `c_string` tests when compiled with `--verify`

modules/packages/Curl.chpl
This PR corrects a bad cast to a 64 bit sized int that caused tests to fail on 32-bit systems. This was introduced in https://github.com/chapel-lang/chapel/pull/22622.
The fix is just to change the cast to a `c_size_t`, which will always be the correct size for the receiver since it also expects a `c_size_t`.
TESTING:
[trivial change - not reviewed]
=> fix incorrect int64 cast for 32-bit system

modules/internal/tasktable/on/ChapelTaskTable.chpl, modules/minimal/internal/ChapelTaskTable.chpl, modules/minimal/internal/MemTracking.chpl, test/trivial/diten/printvisibleOptFalse.good
This PR should correct some broken tests in asan and valgrind test configurations. In the process of deprecating `c_string` in https://github.com/chapel-lang/chapel/pull/22622, I removed some signatures from `minimal` modules that included `c_string` as a formal. While it worked in all the regular paratest configurations I ran, it failed in asan and valgrind configurations. This PR corrects those failures by adding the missing signature back in, and updating the formal type to a void pointer type.
TESTING:
[reviewed by @mppf - thank you!]
=> Fix tests minimal module tests broken in asan and valgrind configurations

test/library/packages/LinearAlgebra/correctness/dependencies/testEigen.chpl
Replaces uses of sqrt_2 with sqrt2 and recipr_sqrt_2 with reciprSqrt2
Built a fresh version of the test on our arm XC testing machine
=> Fix this test to avoid deprecation warnings for some Math constants

modules/minimal/internal/ChapelTaskTable.chpl, modules/minimal/internal/MemTracking.chpl, test/trivial/diten/printvisibleOptFalse.good
Inline the type expression for `faux_c_string` added by #22940 to prevent warning "Could not find extern def of type faux_c_string"
tested with paratest and asan
=> Inline definiton of `faux_c_string` to prevent symbol error

util/test/sub_test.py
A recent PR that made `sub_test.py` more modular (#22878) had to work around our constant use of global variables. To this end, it ended up using `global` declarations. However, `perflabel` slipped through as a non-global declaration, was never set to `gpu`, and perftests would try reading `.keys` files instead of `.perfkeys` files. This PR fixes this issue.
Reviewed by @jhh67 -- thanks!
=> Fix bug in sub_test causing performance tests to fail

util/test/sub_test.py
The function `LauncherTimeoutArgs` uses the global variable `useLauncherTimeout`, so it must be declared `global` in `main`.
=> Fix bug in sub_test.py causing tests with CHPL_LAUNCHER_TIMEOUT to fail

test/llvm/assertVectorize/SKIPIF, test/llvm/assertVectorize/assertVectorized-baseline.good, test/llvm/assertVectorize/assertVectorized-debug.good, test/llvm/assertVectorize/assertVectorized.chpl, test/llvm/assertVectorize/assertVectorized.compopts, test/llvm/assertVectorize/assertVectorized.good, test/llvm/attributes/ir-check/SKIPIF
Makes llvm.assertVectorized tests less fragile by forcing vectorization.
[not reviewed - trivial test change]
=> Fix llvm.assertVectorized tests

compiler/llvm/clangUtil.cpp, test/gpu/native/savec.chpl, test/gpu/native/savec.cleanfiles, test/gpu/native/savec.compopts, test/gpu/native/savec.good, test/gpu/native/savec.prediff, test/gpu/native/savec.skipif
This change modifies how we do code generation for AMD GPUs by dumping to an assembly (.s) file and then calling `llvm-mc` to assemble it into a .o file.  Previously we dumped to a .o file directly.
I think the prior way of doing things is undesirable because:
* It's not what we do for NVIDIA and the inconsistency might make it harder to maintain things, and
* (probably more importantly) when using `--savec` you'd have the assembly available to inspect for NVIDIA but not AMD
Notes to reviewers:
- To find `llvm-mc` I factored out some existing code we used to find llvmObj into a general `findSiblingClangToolPath` function (which I then call with `llvm-mc` and `llvm-objdump` as appropriate.
- There's also a version of `llvm-mc` packaged with HIP but if we use one version of clang to …
=> Have AMD GPU codegen dump assembly

modules/standard/Math.chpl, test/unstable/Math/unstableLogs.chpl, test/unstable/Math/unstableLogs.good
(except logBasePow2, which is already unstable)
log2 had explicit overloads to allow calls with `int` and `uint` arguments,
which would return ints.  This was not consistent with the behavior of the other
log functions, which did not have explicit overloads and so coerced such
arguments to reals of the nearest size, thus returning reals.
W.r.t. 2.0, the plan is to mark all such calls as unstable.  This may mean that
the log2 overloads return reals in the future, or it may mean that log, ln,
log10, and log1p will change their return type when provided int or uint
arguments in the future.  We are short on time before the 2.0 release, though,
so will not make that decision yet.
Though "new" overloads are added, they are not included in the generated
documentation.  This will enable users …
=> Mark the log functions as unstable when uint and int arguments are provided

test/gpu/native/studies/gpuArrayOps/gpuArrayOps.graph
Fixes a graph file for a test that is not rendering correctly:
https://chapel-lang.org/perf/gpu/?graphs=arrayinitialization100mints,datacopybetweenhostanddevice100mints
The issue was with the mismatch in dat file names. I confirmed this by seeing nulls vs actual values in the generated json file. I also confirmed that we have been collecting data for these tests since they were added. We were just not able to generate the plot correctly.
=> Fix a GPU performance test's .graph file

test/gpu/native/savec.good, test/gpu/native/savec.prediff
This test locks down what `.s` and `.o` files get put in the generated directory when compiling with `chpl --savec`.
One of the files that might get added is `savec.tmp_launcher.o` but this is only added when chpl is configured to use a launcher (which we do for the nightly testing job but not for our paratest runs).
Anyway, I've updated the prediff to filter this out so it should now work regardless of whether a launcher is being used or not.
=> Fix nightly testing for new GPU 'savec' test

modules/standard/BigInteger.chpl, test/deprecated/BigInteger/deprecateFitsMethods.chpl, test/deprecated/BigInteger/deprecateFitsMethods.good
Remove the `biting.fits_*` methods, deprecated in [this PR](https://github.com/chapel-lang/chapel/pull/20039). These symbols have been deprecated for multiple releases.
=> Remove deprecated `bigint.fits_*` methods

runtime/include/chpl-init.h, runtime/include/chplexit.h, runtime/src/chpl-init.c, runtime/src/chplexit.c, runtime/src/main.c, test/interop/C/deinit/codeAfterFinalize.cleanfiles, test/interop/C/deinit/codeAfterFinalize.good, test/interop/C/deinit/codeAfterFinalize.lastcompopts, test/interop/C/deinit/codeAfterFinalize.precomp, test/interop/C/deinit/codeAfterFinalize.test.c, test/interop/C/deinit/foo.chpl, test/interop/C/deinit/foo.notest, test/interop/C/errorMessage/foo.chpl, test/interop/C/errorMessage/foo.notest, test/interop/C/errorMessage/initTwice.cleanfiles, test/interop/C/errorMessage/initTwice.good, test/interop/C/errorMessage/initTwice.lastcompopts, test/interop/C/errorMessage/initTwice.precomp, test/interop/C/errorMessage/initTwice.test.c
This changes `chpl_library_finalize()` to not explicitly exit the Chapel program, permitting the user to do other computations or cleanup activities after finalizing the Chapel library, as requested in #22739 and as our docs already suggest is possible (by showing code following the finalize() call and not having finalize() take an exit status).  It adds a test of this in `test/interop/C/deinit/codeAfterFinalize.test.c` demonstrating it works.
It also adds an error if `chpl_library_init()` is called twice, in the event that a user tries to re-initialize the Chapel library after finalizing it (or simply tries to initialize it twice, which has never been supported—we just haven't guarded against it in the past).  It adds a test of this in `test/interop/C/errorMessage/initTwice.test.c`.
In …
=> Make chpl_library_finalize() not exit; Make chpl_library_init() error on second call

compiler/include/type.h, compiler/optimizations/scalarReplace.cpp, compiler/passes/insertWideReferences.cpp, modules/internal/ChapelIteratorSupport.chpl, modules/internal/ChapelPrivatization.chpl, modules/internal/LocaleModelHelpMem.chpl, modules/internal/localeModels/gpu/LocaleModel.chpl, modules/minimal/internal/CPtr.chpl, modules/minimal/internal/IO.chpl, test/deprecated/Map/mapIterators.good, test/trivial/diten/printvisibleOptFalse.good
Removes all usages of `raw_c_void_ptr`, which maps to the `PrimitiveType` `dtCVoidPtr` like the old `c_void_ptr`, in favor of the non-primitive `c_ptr(void)`.
With this PR there are no more uses of `raw_c_void_ptr` in module code. However, `dtCVoidPtr` is still used in the compiler for some primitives and compiler-inserted calls. Eventually these usages can be replaced with a well-known `AggregateType` for `c_ptr(void)`, and this PR adds a TODO to do so. However, I think it's not worth doing so now as the work would be made redundant when we bring the Dyno resolver into production.
Follow up to https://github.com/chapel-lang/chapel/pull/22637.
Testing:
=> Remove remaining usages of `raw_c_void_ptr` in modules

test/optimizations/bulkcomm/asenjo/redistBlockToCyclic/FFT_assignment.chpl, test/optimizations/bulkcomm/asenjo/redistBlockToCyclic/FFT_bulk.chpl
Avoids the deprecation warning for the old name
Brad pointed out that I had missed these in my initial PR, rectify that.
=> Update these tests to use the new name for `conjg`

test/llvm/assertVectorize/SKIPIF, test/llvm/attributes/ir-check/SKIPIF
Add skipifs to failing tests
[not reviewed - trivial test change]
=> Add missing skipif lines for llvm.assertVectorized tests

test/studies/comd/elegant/arrayOfStructs/util/AccumStencilDist.chpl
Update CoMD's AccumStencilDist to eliminate recent deprecation warnings, especially from #22784 and #22858, following the changes to our standard StencilDist in those PRs. CoMD's prediff filters out warnings so newly-introduced warnings go unnoticed in paratest testing.
While there, make some more changes that make CoMD's AccumStencilDist closer to our standard StencilDist.
In particular, change a couple of occurrences of `.low` and `.high` to `.lowBound` and `.highBound`. The corresponding changes in StencilDist were made in #19820 when the warnings on `.low` / `.high` were enabled. Now `.low` / `.high` no longer generate warnings, however have a (slightly) different meaning than they had before #19820.
Future work:
* Should we changes more occurrences of `.low` / `.high` to `.lowBound` …
=> Eliminate some warnings in CoMD

test/gpu/native/noGpu/assertOnGpu-do-assert.good, test/gpu/native/noGpu/assertOnGpu-dont-assert.good, test/gpu/native/noGpu/assertOnGpu.prediff
An `assertOnGpu` test failed recently with line number changes. This PR adds a prediff for that test to filter out line numbers.
The test passes with `CHPL_GPU=cpu` with this PR.
=> Add a prediff to filter out line numbers in a test

frontend/lib/uast/Foreach.cpp
Remove an extraneous call to `debuggerBreakHere()` in `Foreach::build`
This appears to have been left in accidentally from https://github.com/chapel-lang/chapel/pull/22932 and causes a lot of unnecessary debugger breaks in parsing.
=> Remove extraneous debuggerBreakHere in Foreach::build

test/parallel/sync/diten/returnSync.chpl, test/parallel/sync/diten/returnSync.good, test/parallel/sync/diten/returnSync.skipif
Removes `test/parallel/sync/diten/returnSync.chpl`, as the feature is deprecated and will be removed.
tested locally
[not reviewed - trivial test change]
=> Remove test for returning sync by value

make/compiler/Makefile.intel
This PR should fix Intel compiler test failures that started happening after deprecating `c_string` in https://github.com/chapel-lang/chapel/pull/22622.
The PR squashes the warning emitted from the Intel compiler about "value of type X being assigned to entity of type Y" in our generated code as below:
```
error #556: a value of type "const char **" cannot be assigned to an entity of type "c_ptr_c_ptrConst_int8_t_chpl={c_ptrConst_int8_t_chpl={int8_t={__int8_t={signed char}} *} *}"
>   call_tmp_chpl37 = qio_spawn_allocate_ptrvec(((uint64_t)(nenv_chpl)));
```
This should be in alignment with changes to the `Makefile.gnu` in #22622 that suppressed warnings for discarding of `const` qualifiers.
TESTING:
[Summary: #Passing Suppressions = 0 | #Passing Futures = 0 ]`
[reviewed by @ronawho - …
=> squash icc warning about "type X assinged to entity of type Y"

compiler/main/checks.cpp
Add an exception to formal/actual type match checking to allow a mismatch between a `raw_c_void_ptr` and `c_ptr(void)`.
This exception is needed until we are able to replace `raw_c_void_ptr` with `c_ptr(void)` in all compiler-inserted code, likely when `c_ptr` becomes a primitive or compiler well-known type. A TODO comment on the code implementing the exception notes it can be removed once this is done. However, this isn't feasible to do in the production compiler at the moment due to 2.0 time pressure, as well as potentially being obviated soon by the Dyno resolver being brought into production.
The case specifically worked around by this is `chpl_here_free` calls inserted by `lowerIterators`, which are passed a `raw_c_void_ptr` argument. (There are likely more instances with the same …
=> Allow raw_c_void_ptr/c_ptr(void) mismatch in formal/actual checks

test/compflags/albrecht/chplenv/generateChplEnvFiles, util/chplenv/chpl_gpu.py, util/chplenv/printchplenv.py
Makes the following changes:
1) `printchplenv` now prints `CHPL_GPU` by default (i.e. even without the `--all` flag)
(Resolves #22894)
2) Adds validation to make `printchplenv` print a simple warning when
using CPU-as -device mode in tandem with `CHPL_TASKS=fifo` since that
leads to issues with launching GPU kerneks (Resolves #22598)
Also removes an unused `chplComm` argument being passed to `validate()` in `chpl_gpu.py`
=> Print `CHPL_GPU` by default and warn users when using `fifo` tasks with cpu-as-device

test/ANNOTATIONS.yaml
Add annotations for recent changes and catch up on older ones:
- llvm 15 upgrade
- minor list regression from removing `codegenInvariantStart`
- surprising list and rev-comp improvements from `c_string` deprecation
- Arkouda:
- Some bigint regressions from not reusing result as an arg
- Regression to non-default dataframe display from segaray to client
- Dataframe display regression from %j5 deprecation and later fix
=> Add perf annotations for 2023-08-18

modules/standard/FileSystem.chpl
This PR adds a note to the documentation on `FileSystem.chown` to indicate that the operations typically require elevated privileges or a combination of file ownership and group membership.
The addition was motivated by discussion summarized in https://github.com/Cray/chapel-private/issues/5015, with the goal of being explicit about the limitations of the operation. 
Testing:
[reviewed by @lydia-duncan - thank you!]
=> add note about privileges to `chown` docs

modules/standard/ChapelIO.chpl, modules/standard/IO.chpl, test/deprecated/IO/skipField.chpl, test/deprecated/IO/skipField.good
Deprecates the ``skipField`` method on ``fileReader`` and adds a deprecation test to make sure the feature continues working until it is removed.
Testing:
=> Deprecate fileReader.skipField

modules/standard/Math.chpl
This PR proposes some minor improvements in the `Math` module documentation:
- add an extended doc for `erf`, as suggested by #18997;
- modify the doc of `inline proc ldexp(x:real(64), n:int(32)):real(64)` to better fit the standard (i.e. "Returns ...");
- add the missing doc of `inline proc ldexp(x:real(32), n:int(32)):real(32)`;
- add some missing argument names;
- add some missing end points;
- fix some typos.
Issue #18997 also asks for an extended doc for `erfc`, but in my opinion it is meaningful enough given the new `erf` doc.
Resolves #18997
=> Improve `Math` module doc

modules/standard/GPU.chpl, runtime/include/gpu/amd/chpl-gpu-gen-includes.h, runtime/include/gpu/nvidia/chpl-gpu-gen-includes.h, test/gpu/native/atomics.chpl
Make the GPU atomic functions return the appropriate old values. Currently these atomics are wrappers to nvidia or amd atomics, which do return the old values, we didn't pass it along earlier. Now we pass along the return value we get from the nvidia and AMD atomic functions so we can use them in Chapel code.
=> Add return values for GPU Atomics

test/library/packages/BLAS/test_blas1.chpl, test/library/packages/BLAS/test_blas2.chpl, test/library/packages/LinearAlgebra/correctness/dependencies/testEigen.chpl, test/library/packages/LinearAlgebra/correctness/dependencies/testLeastSquares.chpl
Avoids the deprecation warning for the old function name
=> Update these tests to use `conj` instead of `conjg`

third-party/README, third-party/qthread/README
Update the qthreads git repo from https://github.com/Qthreads/qthreads to https://github.com/sandialabs/qthreads to reflect its move to the Sandia github organization.
=> Update qthreads repo links

modules/packages/CopyAggregation.chpl
Aggregation performance on Slingshot-11 benefits from smaller buffer sizes. Similar to ugni/Aries, we can reach peak bandwidth rates at a smaller message size so we don't lose out on bandwidth and sending messages sooner allow us to progress remote work faster.
Here's some 256 node indexgather results:
| Buffer size | Performamance  |
| ----------: | -------------: |
|  512        | 6.69 GB/s/node |
| 1024        | 9.68 GB/s/node |
| 2048        | 9.86 GB/s/node |
| 4096        | 9.77 GB/s/node |
| 8192        | 9.14 GB/s/node |
Where 2K performs "best", but 1K isn't far off and I thought the additional savings in memory pressure was worth the tradeoff. We can always continue to tune more in the future, but for now this default is still better than the old 8K default.
=> Tune the aggregation buffer size for Slingshot-11

runtime/src/comm/ofi/comm-ofi.c
OFI uses a "landing zone" into which incoming active messages are received. The landing zone is split into two buffers used in a double-buffered fashion -- messages are placed in one buffer until it is full as which point libfabric switches to the other buffer. Once the active message handler has finished processing the messages in a buffer it re-registers the now-empty buffer with libfabric. Previously, the landing zone was 40MB. This size was determined empirically on somewhat older hardware. Increase the default size to 64MB and make it configurable via the CHPL_RT_COMM_OFI_AM_LZ_SIZE environment variable.
Closes https://github.com/Cray/chapel-private/issues/5245.
=> Improve OFI landing zone sizing

compiler/AST/build.cpp, compiler/resolution/preFold.cpp, doc/rst/language/spec/statements.rst, doc/rst/technotes/manage.rst, modules/internal/ChapelBase.chpl, modules/internal/ChapelDomain.chpl, test/library/draft/DistributedMap/DistributedMap.chpl, test/library/draft/DistributedMap/v3/DistributedMap.chpl, test/statements/manage/ContextManagerSyntax.chpl, test/statements/manage/ContextManagerSyntax.good, test/statements/manage/ExplicitConstRefResourceMutation.chpl, test/statements/manage/InferredConstRefResourceMutation.chpl, test/statements/manage/InferredConstRefResourceMutation.good, test/statements/manage/InferredRefResourceMutation.chpl, test/statements/manage/InferredResourceMultipleReturnIntents1.chpl, test/statements/manage/InferredResourceMultipleReturnIntents1.good, test/statements/manage/InferredResourceStorage.chpl, test/statements/manage/InferredResourceStorage.good, test/statements/manage/SpinlockGuard.chpl, test/statements/manage/UseSpinlockGuardBadTaskIntent.good, test/statements/manage/WarnUnstable.chpl
Due to the discussion in https://github.com/chapel-lang/chapel/issues/22618, the decision was made to rename `enterThis`/`leaveThis` to `enterContext` and `exitContext`.
=> Rename `enterThis`/`leaveThis` to `enterContext`/`exitContext`

runtime/src/gpu/amd/gpu-amd.c
Today on `main`, we get an error while running any GPU program built for AMD when the runtime was compiled with `CHPL_DEVELOPER=1`. This error is triggered by a `ROCM_CALL` to `hipPointerGetAttributes` inside of an assertion that gets compiled out in release mode. 
The error message is as follows:
```
> start_test test/gpu/native/jacobi/jacobi.chpl 
...
internal error: gpu-amd.c:156: Error calling HIP function: hipErrorInvalidDevice (Code: 101)
```
It appears that the warning is triggered by calling our `host_to_device` copy using a pointer returned from `hipModuleGetGlobal`. Apparently, `hipModuleGetGlobal`'s return value, even though it's a device pointer, is not a valid argument to `hipPointerGetAttributes`. I have verified this by applying the following patch to [the HIP test for …
=> GPU: Fix running AMD runtime with CHPL_DEVELOPER set.

test/llvm/assertVectorize/SKIPIF, test/llvm/assertVectorize/SUPPRESSIF, test/llvm/assertVectorize/assertVectorized.compopts
Add compopts and skipif to assertVectorized test to resolve nightly test issues
[not reviewed - trivial test change]
=> Fix assertVectorized tests

test/deprecated/atomic/return-by-ref-array.suppressif, test/deprecated/single/return-by-ref-array.suppressif, test/deprecated/sync/return-by-ref-array.suppressif
Running `test/deprecated/[sync/single/atomic]/return-by-ref-array.chpl` in a non-local config causes the test to fail due to a bug
Bug: https://github.com/chapel-lang/chapel/issues/22685
=> Suppress deprecation test in broken configuration

frontend/lib/util/filtering.cpp, modules/standard/BigInteger.chpl, test/deprecated-keyword/messageFiltering.chpl, test/deprecated-keyword/messageFiltering.good, test/deprecated/BigInteger/deprecatePowm.good, test/deprecated/BigInteger/deprecateSizeinbase.good
Improves BigInteger documentation by adding it where missing and trying to make the existing docs feel unified.
As a part of this PR, added filtering support for `enumconstant` to `frontend/lib/util/filtering.cpp`. I also tried to reduce the code duplication to reduce the maintenance burden 
- added docs to functions missing it 
- for some functions, just needed to augment the existing documentation with types, links, etc 
- added docs for operators and exposed cast operators in docs
- update rounding enum definitions and move to the bottom of the file
- this change makes the first thing you see on the BigInteger docs page be `bigint`, not a deprecated `enum ROUND` 
- cleanup some old deprecation messages
- refactor some more functions to use `.localize()` where applicable
- refactor some …
=> Improve BigInteger documentation

modules/internal/ChapelSyncvar.chpl
Switch the formal name for syncs/singles to `val`. This matches what we did for atomics in #22859 and was done for the same reasons and for consistency with atomics.
Part of Cray/chapel-private#3727
=> Rename sync/single formals from `x` to `val`

test/gpu/native/studies/sort/radixSortGpu.chpl
The number of kernels launched differs based on the memory strategy used in radix sort. Array on device has 4 more kernels used in bulk copies. Modified the assertGpuDiags so nightly testing works.
No other tests impacted.
=> Number of GPU radix sort kernels by mem strategy

modules/internal/OwnedObject.chpl, test/deprecated/deprecateOwnedBorrow.chpl, test/deprecated/deprecateOwnedBorrow.good
Based on #22273, we are deprecating the `owned.borrow()` type method.
Tested with paratest + futures. Also built docs to check deprecation looks right
[reviewed by @riftEmber]
closes #22273
=> Deprecate owned.borrow() type method

modules/standard/BigInteger.chpl
In a previous PR, `num` was accidentally put in a place where the argument name was `str`.
=> Fix argument name for a bigint init function

runtime/src/comm/ofi/comm-ofi.c
Make comm=ofi debug message conditional based on CHPL_COMM_DEBUG to avoid unused variable error when debugging is not enabled.
=> Make debug message conditional to avoid unused variable

modules/standard/GPU.chpl, test/gpu/native/noGPUPragma.chpl, test/gpu/native/streamPrototype/stream.chpl, test/gpu/native/studies/coral/coral.chpl, test/gpu/native/studies/sort/radixSortGpu.chpl, test/gpu/native/studies/transpose/transpose.chpl
fixes failing tests by adding `ref` where needed in gpu tests.
ref-maybe-const was deprecated in #22958. Array formals can no longer be modified with the default intent, an explicit `ref` must now be supplied. This cascades to other functions that may require a `ref` like `c_ptrTo`.
Tested with `CHPL_GPU=cpu`
Note that `test/gpu/native/studies/sort/radixSortGpu` will not be fully fixed due to prior issue.
=> Fix failing gpu tests from ref-maybe-const deprecation

modules/internal/ExternalArray.chpl, test/interop/python/arrayOpaquePointer_block.chpl, test/interop/python/arrayOpaquePointer_block_with.chpl
Fix issues missed with ref-maybe-const deprecation (https://github.com/chapel-lang/chapel/pull/22958). We now require `ref` to be used when modifying an array
Added `ref` where needed in python interop tests
=> Fix python interop with ref-maybe-const

util/cron/test-cray-xc-arkouda.bash, util/cron/test-cray-xc-arkouda.release.bash
With the loss of our CS testing, we now only have multilocale testing running oversubscribed with gasnet+asan. Restarting XC testing for only correctness tests will allow us to at least track if there are any failures for distributed builds.
Corresponding PR: https://github.hpe.com/hpe/hpc-chapel-ci-config/pull/1032
Testing:
=> Add scripts to restart XC testing for Arkouda

modules/standard/IO.chpl
Adds optional 'deserializer' arg to file.reader variant so that the fileIO primer can be compiled without its usual compopts, as done in 'make check'.
Testing:
=> Fix fileIO 'make check'

modules/packages/LinearAlgebra.chpl, test/library/packages/LAPACK/LAPACK_Matrix_test.chpl
Fixes issue in tests with LinearAlgebra.chpl where `ref` is missing due to ref-maybe-const deprecation. When modifying array formals, the `ref` intent is now required.
[Not Reviewed - trivial test change]
=> Add ref where needed in linear algebra tests

compiler/resolution/cullOverReferences.cpp
Fixes issue introduced with #23049 which uses `sprintf`, which causes the compiler to fail to compile with certain versions of the C++ compiler.
=> Remove usage of sprintf

test/ANNOTATIONS.yaml
Catch up on older chapcs perf annotations:
- 2D strided array improvement range stride kinds
- IO improvement from non-buffered IO read optimization
=> Add missing chapcs perf annotations

util/cron/nightly, util/cron/nightly_email.pm, util/cron/nightlysubs.pm
Under some conditions the "cron" scripts such as "nightly" would send email directly, instead of relying on Jenkins to do it. Now the messages are written to the console where Jenkins will pick them up and email them if appropriate.
=> Remove email capability from cron scripts

runtime/src/comm/gasnet/Makefile.share, runtime/src/comm/gasnet/comm-gasnet-ex.c, util/chplenv/chpl_gasnet.py, util/chplenv/overrides.py, util/chplenv/printchplenv.py
Create a gasnet-ex shim that we can use to upgrade to the gasnet-ex API. Today we use the gasnet-ex source, but the gasnet-1 API. We want to start upgrading to the new API, but don't want to disrupt production usage. To enable this, add a `CHPL_GASNET_VERSION` chplenv that can either be `1` (the default) or `ex`. When `ex`, this will trigger using the new `comm-gasnet-ex.c` source. Currently that's just a straight clone, but we'll update over time. Note that `CHPL_GASNET_VERSION` is part of the unique build path, so we can have gasnet-1 and gasnet-ex builds in the same tree.
I considered doing this as a `CHPL_COMM=gasnet-ex`, but we have a lot of things that check for `CHPL_COMM==gasnet` and it didn't feel worth the time to track all those down and copy more of the runtime build …
=> Create a gasnet-ex shim

compiler/main/driver.cpp, compiler/optimizations/gpuTransforms.cpp
See https://github.com/Cray/chapel-private/issues/5227 for information about a bug (that we saw in the coral code) that exists when there are nested `on` statements that can go from a gpu locale to a cpu locale.
This PR fixes this bug and also makes some changes needed to get "gpu specializations" mode to work well in tandem with "cpu-as-device" mode.
Specifically, this PR:
- Prevents specializing `wrap_on` functions since (somewhat by definition) we don't want to rewrite the calls in these to only go to gpu functions.
- When using cpu-as-device mode we should sill dispatch to the gpu specific specialization
- When using cpu-as-device mode with gpu specializations keep the cpu-bound loop in the gpu-based specialization (in addition to generating the launch call to the runtime so that we …
=> Fix gpu-specializations bug (and fix to work in cpu-in-device mode)

modules/internal/ChapelRange.chpl, test/unstable/rangeUnboundedEnumBoolFirstLast.chpl, test/unstable/rangeUnboundedEnumBoolFirstLast.good
From https://github.com/chapel-lang/chapel/issues/20896#issuecomment-1678354784
For `first` and `last`, the name suggests "first/last in the sequence."
Given that the sequence is finite if idxType is finite (i.e. enum or bool),
it makes sense for `first` and `last` to be defined as if the range is bounded,
similarly to iteration.
To be on the safe side, we will mark this behavior as unstable.
=> Unstabilize `range.first` and `range.last` when applied to a range over bool or enum and that side of it is unbounded

test/ANNOTATIONS.yaml
- Deprecate 'iokind' type and 'kind' field
There is also an Arkouda in1d performance improvement that went in between the 8th and the 16th, where we don't have data for that that I don't know the cause of yet.
=> Add perf annotations for 2023-08-23

compiler/include/driver.h, compiler/llvm/clangUtil.cpp, compiler/main/driver.cpp, doc/rst/technotes/gpu.rst, frontend/lib/util/chplenv.cpp, test/gpu/native/.gitignore, test/gpu/native/savec.base.good, test/gpu/native/savec.precomp, test/gpu/native/savec.prediff, util/chplenv/chpl_gpu.py
This PR allows the `CHPL_GPU_ARCH` variable to specify a comma-separated list, thereby allowing a user to request an executable to be built for multiple GPU architectures. It also modifies the clang driver code to support building multi-architecture objects, by invoking the assembler multiple times and giving more arguments to the platform-specific bundler.
However, thus approach currently relies on the ability to re-assemble a single file generated by clang (`.ptx` or `.S`) into multiple specialized object files for different architectures. Unfortunately, although this is possible for Nvidia, the assembly files generated by Clang for AMD (especially without a `--offload-arch` argument) are not compatible between different GPU architectures. It seems like the proper approach in this …
=> Add support for multi-arch GPU executables for Nvidia

modules/standard/List.chpl, test/release/examples/primers/listOps.chpl, test/unstable/listSort.chpl, test/unstable/listSort.good
The sort method on list did not make it into 2.0 stability discussions. The symbol will be marked unstable for now.
See related discussion here: https://github.com/chapel-lang/chapel/issues/18100
=> Unstabilize `list.sort`

test/gpu/native/studies/multiGpuStream/multiGpuStream.chpl
fixes failing test by adding `ref` where needed in gpu test.
ref-maybe-const task intents were deprecated in #23049.  To modify an array inside a parallel structure like `coforall`, an explicit `ref` must now be supplied.
Tested with `CHPL_GPU=cpu`
=> Add ref task intent to failing GPU test

runtime/src/comm/gasnet/Makefile.share
In #23037, I missed updating some Makefile references to the source file, but didn't notice since I wasn't doing a clean build and had leftover .o's from a previous build. Fix that by updating `comm-gasnet.{c,o}` references to use a suffix set by `CHPL_GASNET_VERSION`.
=> Fix gasnet-ex Makefile

modules/dists/HashedDist.chpl, modules/dists/StencilDist.chpl, modules/internal/ChapelArray.chpl, modules/internal/DefaultAssociative.chpl, modules/internal/DefaultRectangular.chpl, modules/packages/LinkedLists.chpl, modules/standard/ChapelIO.chpl, modules/standard/IO.chpl, modules/standard/List.chpl, modules/standard/Time.chpl, test/deprecated/IO/binaryQuery.chpl, test/deprecated/IO/binaryQuery.good, test/studies/comd/elegant/arrayOfStructs/util/AccumStencilDist.chpl
Per discussion [here](https://github.com/chapel-lang/chapel/issues/19317) `fileReader.binary` and `fileWriter.binary` are deprecated.
Resolves https://github.com/chapel-lang/chapel/issues/19317
=> Deprecate `fileReader.binary` and `fileWriter.binary`

test/gpu/native/multiGPU/worksharing.chpl, test/gpu/native/multiGPU/worksharingBasic.chpl, test/gpu/native/multiLocale/copyToLocaleThenToGpu.chpl, test/gpu/native/multiLocale/cyclicDist.chpl, test/gpu/native/multiLocale/directCopyToGpu.chpl
fixes failing tests by adding `ref` where needed in gpu tests to coforalls and cobegins.
ref-maybe-const task intents were deprecated in #23049.  To modify an array inside a parallel structure like `coforall`, an explicit `ref` must now be supplied.
[Not reviewed - trivial test changes]
=> Add ref task intents where needed in gpu tests

test/runtime/configMatters/forall-unordered-opt/needsFence.chpl, test/studies/nbody/md.chpl
After deprecating ref-maybe-const for task intents, `ref` must be added explicitly when modifying an array inside of a parallel feature like `cobegin`
test locally
[Not reviewed - trivial test changes]
=> Add ref task intent to resolve nightly failures

compiler/AST/build.cpp, compiler/include/build.h, compiler/passes/convert-uast.cpp
I misused `AList` in my `convert-uast` code, and apparently that worked fine despite the obvious bugs. ASAN caught it; the fix was to use a `std::vector`, which is easier to pass around since `Expr`s don't internally store pointers to their container `vector` (but they do store pointers to their parent `AList`!)
=> Fix failures under ASAN in convert-uast.cpp

util/test/chpl_launchcmd.py
Add support for queues and filter out prologue/epilogue output by throwing away any PBS output that doesn't include the `PBS:` sentinel. This allows us to capture errors (like timeouts or incorrect submission) while ignoring node setup/teardown output.
While here, poll for completion a little more often since it takes a while for us to notice short running jobs have finished.
Part of https://github.com/Cray/chapel-private/issues/5295
=> Improve chpl_launchcmd support for systems with queues and prologues

util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.fast.bash
The new apollo system has more memory, so the old 124G is not enough for tests that use a fraction of memory. I stuck with that to try to keep startup times lower, but it wasn't enough so bump here.
=> Increase GASNET_PHYSMEM_MAX for gn-ibv-fast testing

util/cron/test-perf.hpe-apollo-hdr.gasnet-ex-ibv.large.bash
Add 16-node apollo performance testing for the new gasnet-ex shim.
Part of #14443
=> Perf test GASNet-EX shim for gn-ibv-large

compiler/resolution/functionResolution.cpp, compiler/resolution/preFold.cpp, modules/packages/Sort.chpl, test/classes/deitz/infer/infer_field10.good, test/classes/deitz/infer/infer_field11.good, test/classes/delete-free/owned/owned-record-instantiation-types.chpl, test/classes/delete-free/tests-from-design-overview/generic-collection-owned.chpl, test/classes/delete-free/tests-from-design-overview/generic-collection-unspecified.chpl, test/classes/ferguson/generic-field/generic-field-integral-not-inited-record.good, test/classes/ferguson/generic-field/generic-field-record-not-inited.good, test/classes/ferguson/generic-field/generic-field-record-not-inited2.good, test/classes/initializers/compilerGenerated/generics/issue-16508-default-ok.good, test/classes/initializers/compilerGenerated/generics_check_record.chpl, test/classes/initializers/compilerGenerated/generics_check_record.good, test/classes/initializers/generics/copy-init-generic-field.chpl, test/classes/initializers/generics/copy-init-generic-field.good, test/deprecated-keyword/handleField.chpl, test/functions/ferguson/partially-generic-overloads.chpl, test/functions/promotion/passPromotedToFunction.chpl, test/library/standard/Types/copyable.chpl, test/types/partial/partial-no-q-warning.chpl, test/types/records/generic/warn-field-generic-declared-type.chpl, test/types/records/init/no-default-init-generic-var.chpl, test/types/records/init/no-default-init-generic-var.good, test/types/records/init/no-default-init-typeless.chpl, test/types/records/init/no-default-init-typeless.good, test/types/records/with-runtime-types.bad
For #16508.
This PR changes the behavior of examples like the below, when the type uses a compiler-generated default initializer:
``` chapel
record R { var genericField; }
var x: R(int); // was OK; now error
record U { var genericField: integral; }
var x: U(int); // was OK; now error
```
Historically, when faced with a default initialization like `var x: R(int)` above, the compiler would default initialize an `int` to pass as the value for `genericField`. However, it is worrying that this pattern default-initializes something without it being clear that the user has requested it. A further concern is that the default initializer should be possible for users to write, but this is a case where a user cannot write it. Additionally, a similar pattern was already producing a compilation error …
=> Don't allow default initialization for typeless fields

compiler/resolution/functionResolution.cpp, test/functions/sungeun/const_ref_arg_default_value.future, test/functions/vass/const-ref-lvalue-error.chpl, test/functions/vass/const-ref-lvalue-error.good, test/performance/vectorization/vectorizeOnly/nonIterableErrorMessage/nonVectorizeOnlyInvalidIterable.good, test/performance/vectorization/vectorizeOnly/nonIterableErrorMessage/vectorizeOnlyInvalidIterable.good
This PR enables passing numeric param values to `const ref` formals. Note that this was already allowed for `const` values and for bytes/string param values.
For example:
``` chapel
proc f(const ref arg) { writeln(arg); }
f(1); // previously, lvalue error. Now, OK
```
=> Allow passing numeric param values (e.g. 1) to const ref

compiler/AST/type.cpp, modules/internal/ChapelBase.chpl, modules/internal/ChapelUtil.chpl, modules/minimal/internal/ChapelUtil.chpl, runtime/include/chpltypes.h, test/constrained-generics/hashable/user-hash-no-implements-weird.good, test/constrained-generics/hashable/user-hash-no-implements-weird.prediff, test/unstable/c_fn_ptr.chpl, test/unstable/c_fn_ptr.compopts, test/unstable/c_fn_ptr.good
Make `c_fn_ptr` unstable for 2.0, as it will likely be replaced with a better solution (FCPs) soon after 2.0.
This is done by pulling `c_fn_ptr` into `ChapelBase` as a symbol, since it's much simpler to mark as `@unstable` there than modify compiler code to consistently achieve the same effect.
Completes the 2.0 component of https://github.com/chapel-lang/chapel/issues/17994.
Testing:
=> Make `c_fn_ptr` unstable

frontend/include/chpl/framework/all-global-strings.h, frontend/lib/uast/post-parse-checks.cpp, test/llvm/assertVectorize/assertVectorized-baseline.good, test/llvm/assertVectorize/assertVectorized-debug.good, test/llvm/assertVectorize/assertVectorized.good, test/llvm/attributes/paramLoopAttribute.bad, test/unstable/llvmMetadata.good
Adds `llvm` as known toolname for an attribute. All attributes under it (`assertVectorized` and `metadata`) are still marked unstable for 2.0
Tested with paratest and paratest+gasnet
=> Add 'llvm' as a known toolname for an attribute

modules/dists/PrivateDist.chpl
Adds task intent for coforall loop in PrivateDist
[Not reviewed - trivial update]
=> Add missing ref to coforall in PrivateDist

compiler/passes/normalize.cpp, test/functions/castFormalType-1.bad, test/functions/castFormalType-1.chpl, test/functions/castFormalType-1.future, test/functions/castFormalType-1.good, test/functions/castFormalType-2.bad, test/functions/castFormalType-2.chpl, test/functions/castFormalType-2.future, test/functions/castFormalType-2.good, test/functions/castFormalType-3.bad, test/functions/castFormalType-3.chpl, test/functions/castFormalType-3.future, test/functions/castFormalType-3.good, test/functions/castFormalType-4.bad, test/functions/castFormalType-4.chpl, test/functions/castFormalType-4.future, test/functions/castFormalType-4.good, test/functions/castFormalType.chpl, test/functions/castFormalType.good, test/functions/castFormalTypeFromNonType-1.bad, test/functions/castFormalTypeFromNonType-1.chpl, test/functions/castFormalTypeFromNonType-1.future, test/functions/castFormalTypeFromNonType-1.good, test/functions/castFormalTypeFromNonType-2.bad, test/functions/castFormalTypeFromNonType-2.chpl, test/functions/castFormalTypeFromNonType-2.future, test/functions/castFormalTypeFromNonType-2.good, test/functions/castFormalTypeFromNonType-3.chpl, test/functions/castFormalTypeFromNonType-3.good
Allows simple expressions like `myOwnedType:borrowed` to be used in function formals types.
Resolves by extracting the formal type definition to a temporary type variables during normalization. This is somewhat limited and doesn't work for more complex expressions like `getMyOwnedType():borrowed`. However, this adds an error message that should better guide users to a solution.
Added test of feature in `test/functions/castFormalType.chpl`, as well as future tests for more complex expressions
partially fixes #22994 
future work:
- make this more general beyond just simple casts to `borrowed`. For example, this should also support `myOwnedType:unmanaged`.
=> Allow simple type casts in function formals

runtime/include/tasks/qthreads/chpl-tasks-impl-fns.h, third-party/qthread/README, third-party/qthread/qthread-src/include/qthread/qthread.h, third-party/qthread/qthread-src/src/qthread.c
Switch from our manual patch using `qthread_chpl_reset_spawn_order()` to `qthread_reset_target_shep`, which was upstreamed to qthreads.
Same code/functionality, this just makes it easier to upgrade to the next release.
While here, update README to reflect which patches have been upstreamed
=> Switch to using upstream qthreads task reset mechanism

runtime/include/tasks/qthreads/chpl-tasks-impl-fns.h, runtime/src/tasks/qthreads/tasks-qthreads.c, third-party/qthread/README, third-party/qthread/qthread-src/src/feb.c
Disable stealing of running qthreads tasks. We have runtime code that relies on tasks not migrating to different pthreads (cache remote, parts of ofi) so we disable features or fallback to a slower implementation for (non-default) work-stealing qthreads schedulers where tasks can migrate threads. Here as a compromise, prevent stealing of running tasks. This should still allows us to load balance tasks that haven't started when using a work-stealing scheduler.
Note that our default scheduler (nemesis) doesn't support work-stealing, so this really only impacts experimental schedulers like distrib. Even for that we disabled work-stealing in #4505, but in the longer term we'd like work-stealing and I think this is a good compromise.
The current motivator was that this allows us to remove an …
=> Prevent qthreads from stealing running tasks

test/constrained-generics/basic/withdecl/withdecl-class-single.chpl
I don't know why, but I thought we don't care about memory leaks like this in tests. Turns out, we do :)
Fortunately, `unmanaged` wasn't at all essential to this test. Using the default (owned) memory management strategy should stop the failure.
Trivial; not reviewed.
=> Fix a memory leak failure due to reckless unmanaged.

modules/internal/ChapelDomain.chpl, test/unstable/associativeDomain.chpl, test/unstable/associativeDomain.good, test/unstable/range-domain-binary-ops.good
From https://github.com/chapel-lang/chapel/issues/21330, we decided to mark associative domains as unstable due to issues with parallel safety. 
Covers both domain literals (ex: `{"a", "b"}`) and domain types (ex:`domain(string)`)
For stable associative-like functionality use set and map instead.
=> Unstabilize Associative  Domains

util/chplenv/third_party_utils.py
Handle the situation in which the `pkg-config` command exists, but doesn't know about a package. Without this fix,
on `richter` the `printchplenv` command encounters the following error: `Error: command failed: ['pkg-config', '--exists', 'libzstd']`.
=> handle pkg-config --exists exit status correctly

modules/standard/IO.chpl
Improves the docs for the `mark`/`commit`/`revert` methods on fileReader/fileWriter:
- Minor wording/clarity improvements
- The meaning of `revert` and `commit` were swapped. This is corrected
- Some method links are shortened with `~` to make docs more readable
- Clarify that a fileReader/fileWriter must be manually locked before calling `mark` even if it has `locking=true`
Per the discussion [here](https://github.com/chapel-lang/chapel/issues/19611), also adds a comment about our desire to support mark/commit/revert via a context manager in the future.
=> Improve docs for `mark`/`commit`/`revert`

test/library/packages/LinearAlgebra/correctness/dependencies/testSVD-error.chpl, test/optimizations/cache-remote/ferguson/comm_counting/ra_prefetch.chpl
These two tests aren't run in our regular testing configuration,
so I missed that they needed an update for the new
deprecations.  Rectify that oversight
=> Fix nightly failures with INFINITY and NAN

frontend/lib/uast/post-parse-checks.cpp, test/unstable/foreachLoop.chpl, test/unstable/foreachLoop.compopts, test/unstable/foreachLoop.good
This PR marks foreach loops as unstable.
First and foremost, we need to implement intents on `foreach` loops, which will have breaking consequences on existing code. Also, we want to gain confidence in our vectorization support and vectorization/GPU portability in general before we can call `foreach` loops stable.
Test
=> Mark foreach loops as unstable

test/unstable/llvmMetadata.good
Heading off a failure in nightly testing that I caught while double-checking my own PR.
=> Add missing unstable warning for foreach loop to .good file

test/optimizations/sungeun/bulk_transfer/assignMultiloc.chpl, test/studies/hpcc/HPL/vass/bl.md.chpl
While sanity checking gasnet testing to make sure I hadn't broken anything in my PR, I caught that these multilocale tests were getting new warnings due to calls to 'divceilpos'/'divfloorpos', which got migration warnings added for them today.
=> Rename 'divceilpos'/'divfloorpos' calls in multilocale-only tests

test/ANNOTATIONS.yaml, test/GPU-GRAPHFILES
Fixes rename of `sort.chpl` to `shoc-sort.chpl` by making the change in GPU_GRAPHFILES, which was forgotten in #23127. Also renames annotation in ANNOTATIONS.yaml
[Not reviewed - trivial change]
=> Fix rename of shoc-sort in GRAPHFILES

test/library/standard/IO/nonUTF8/basic.chpl, test/parsing/errors/nameLength/longName.precomp
Fix nonUTF8/basic.chpl when the test path is a symbolic link by using `realPath` to construct an absolute path to a filename. Instead of manually building a path to a known test location, you could just use `absPath(filename)`, but that I wasn't sure if that would defeat the purpose of the test (if `file.path` uses `absPath` under the covers.)
Also update nameLength/longName.precomp to call `getconf NAME_MAX` on the current directory instead of on `/` since the root filesystem and the current one can have different max name lengths.
=> Fix some filesystem portability issues in tests

modules/packages/Socket.chpl, test/constrained-generics/basic/set3/hashtable-table.chpl
Adds ref intent to methods which need it, due to deprecation of ref-maybe-const this-intents in #23060
[Not reviewed]
=> Add ref to methods missed in ref-maybe-const deprecation

test/runtime/configMatters/comm/AtomicsAPI.chpl, test/runtime/configMatters/comm/atomics-api.good
`compareExchangeWeak` is allowed to spuriously fail even when the `atomic.val == expected`, this means we can't rely on expected not getting updated from spurious failures and need to stop printing it and reset it when it can fail spuriously. We were already looping to handle spurious failures but didn't account for `expected` getting updated.
We haven't see this before because `compareExchangeWeak` doesn't fail spuriously on x86, but I have hit this in some recent arm testing. A sequence of instructions is used to implement `compareExchange*` on arm and this sequence can fail for things like a context switch or if another thread modifies the same cacheline. The atomics-api test was failing for the promoted case where we have multiple tasks/threads doing concurrent `compareExchangeWeak` …
=> Fix compareExchangeWeak in atomic API tests

modules/internal/BytesStringCommon.chpl
This works around the bug described in https://github.com/chapel-lang/chapel/issues/23155 which was uncovered / exposed by #22857. Looks like we didn't have baseline tests that required resolving `getHash` on `bytes`, but now all tests resolve `getHash`, so here we are.
To avoid recursive resolution, I've switched one of the simple for-loops to a C-style for loop.
=> Rewrite a byte buffer operation as a C loop to avoid --baseline failures

test/performance/sungeun/assign_across_locales.chpl, test/performance/sungeun/assign_across_locales.good
This is a test update needed after merging this PR (https://github.com/chapel-lang/chapel/pull/23025) that deals with treating 'init' as a keyword.
This test used to use 'init' as an enum value and I updated it to use 'initial' instead (since 'init' is now a keyword). The string representation of this enum value is printed to stdout and it is used as part of a perfkey.
This started causing a nightly test failure because in my previous PR I didn't update the `.perfkey` and `.graph` files for this "new" name. There are a couple of things I could do to fix this:
- Properly update the perfkey. This best practice document discusses how this can be done (https://github.hpe.com/hpe/hpc-chapel-docs/blob/main/bestPractices/updatingDatFiles.rst)
- Update the test to print things out using the old …
=> Fix nightly test failure: update test so we can continue to use old perf key ('init', which is now a Chapel keyword)

test/arrays/literals/cStringLiteral.chpl, test/arrays/literals/cStringLiteral.good, test/deprecated/IO/localesForRegion.skipif, test/interop/fortran/genFortranInterface/unhandledType.chpl, test/interop/fortran/genFortranInterface/unhandledType.compopts, test/interop/fortran/genFortranInterface/unhandledType.good, test/interop/fortran/genFortranInterface/unhandledType.noexec, test/interop/fortran/genFortranInterface/unhandledType.skipif, test/studies/colostate/util.h, test/types/string/ferguson/return-coerce-to-c-string.chpl, test/types/string/ferguson/return-coerce-to-c-string.good, test/types/string/kbrady/c_str_literal.chpl, test/types/string/kbrady/c_str_literal.good
The sign of `char` is implementation defined in C, but in practice is signed on x86 and unsigned for arm (except for mac). We had a few tests that we're baking in the signed type into .good files, which caused failures on some recent arm testing. Fix tests here by:
- Adjusting c_str_literal, cStringLiteral, and return-coerce-to-c-string to assert the type instead of print
- Skiping localesForRegion since it's deprecated and going away soon anyways (type is in an error message.)
- Removing unhandledType since I think unhandledTypeTuple still covers the spirit of the test.
- Adjusting a C benchmark to use `int` for `getopt` instead of `char`
=> Fix tests that assumed `c_char` was an alias for `int(8)`

modules/standard/IO.chpl
This PR updates the "fast path" check in ``readBinary`` and ``writeBinary`` to allow default rectangular arrays _or_ dense slices of default rectangular arrays.
Testing:
=> Improve performance of readBinary and writeBinary for dense arrays

modules/internal/DefaultRectangular.chpl
This PR updates the implementation of ``chpl_serialReadWriteRectangularHelper`` to only attempt calling the "bulk elements" methods of the serialization API when the number of indices is greater than zero. This change was motivated by a testing failure in ``--baseline`` testing where the snippet ``c_addrOf(arr.dsiAccess(dom.dsiFirst))`` incurred a nil-dereference error involving the uninitialized ``shiftedData`` pointer. It's not clear to me why exactly baseline testing ran into this problem, but the simplest option is to simply guard the pointer creation with a check on the domain size.
Testing:
=> Only attempt to read/write bulk elements if size is non-zero

doc/rst/language/spec/classes.rst, doc/rst/language/spec/procedures.rst, modules/internal/OwnedObject.chpl, modules/internal/SharedObject.chpl, modules/internal/fixInternalDocs.sh, modules/standard/Types.chpl
Makes a number of updates to the `owned` and `shared` documentation. Listing changes below.
- Rewrite `owned` and `shared` docs to use secondary methods so that the docs better hide the `record` implementation details.
- closes #15114 
- Tweak default intent in the spec for `owned` and `shared` to reflect cvref changes. The compiler can assume `owned` and `shared` formals will not change during execution of the procedure body.
Built docs and reviewed. Ran a paratest to ensure `owned` and `shared` changes did not break anything
For example, the `owned` docs now look like this. The `shared` docs are similar.
Implements decisions from Cray/chapel-private#5169
=> Update owned and shared documentation

modules/standard/AutoMath.chpl, test/deprecated/Math/argNames/cprojZ.good, test/deprecated/Math/depCproj.chpl, test/deprecated/Math/depCproj.good, test/types/complex/diten/cplxMathFnTypes.chpl
Resolves #19011 
Since we'd already deprecated the argument name this release, adjust the
deprecation message to instead talk about the function name and move the
implementation of the replacement so that it's sorted alphabetically after the
rename.  Remove the "last resort" pragma from the deprecated function,
since that was only necessary because the new version had shared the same
name.
Also adjust the quick links at the beginning of the documentation so that they
refer to the new name instead of the deprecated one.
Updates a test that was using the old name to use the new one.
Adjusts the cproj deprecation test to cover the new deprecation.
=> Deprecate the name cproj and add a new function riemProj to replace it

compiler/codegen/library.cpp
Since #22137, we have frameworks included in system link args on mac when hwloc is used. e.g. `-framework Foundations`. cmake doesn't like frameworks in link args and adjusts it to `-framework -lFoundations`, which isn't valid. Quote the framework args to prevent cmake from adjusting the args.
Testing:
=> Fix `--library-cmakelists` on mac by quoting framework link args

test/studies/shootout/submitted/fasta5.chpl, test/studies/shootout/submitted/fasta5.good
Revert changes in a submitted test that added explicit ref intents to a coforall loop
Tested locally
=> Revert changes to coforall in submitted tests

modules/standard/Time.chpl, test/deprecated/Time/getCurrentDate.chpl, test/deprecated/Time/getCurrentDate.good, test/deprecated/Time/getCurrentDayOfWeek.chpl, test/deprecated/Time/getCurrentDayOfWeek.compopts, test/deprecated/Time/getCurrentDayOfWeek.good.base
Consistently use local/UTC versions of time-querying methods, and clarify differences in documentation.
In the `Time` module we have different versions of some time-querying methods for local vs UTC time (amongst those that do not take a `Timezone` argument and are therefore still naive). This PR resolves inconsistency between the deprecated `getCurrentDate` method, which uses UTC time, and its suggested replacement `date.today` which uses local time.
Changes:
- add a new `date.utcToday` method, paralleling `dateTime.now/utcNow`
- update the `getCurrentDate` deprecation to point users to `date.utcToday` instead of `date.today`
- clarify the difference in functionality between `date.today` and `date.utcToday` in their docs
- add to module-level docs to mention we support both local and UTC …
=> Fix inconsistent local/UTC methods and add to docs

modules/standard/AutoMath.chpl, test/unstable/Math/unstableSignbit.chpl, test/unstable/Math/unstableSignbit.good
We probably will at least camelcase this name in the future, but we might end up
with a different name or decide it counts as one word instead.  This function
is not a high priority for 2.0 as compared to other things, so for now punt on
discussing it and mark it unstable.
Add a test locking in the unstable warning
=> Mark both versions of signbit unstable

modules/standard/AutoMath.chpl, test/deprecated/Math/argNames/cargZ.good, test/deprecated/Math/depCarg.chpl, test/deprecated/Math/depCarg.good, test/types/complex/diten/cplxMathFnTypes.chpl
Resolves #19006 
Since the argument name for the `carg` function had been deprecated this
release, we merely needed to update the deprecation message to include the name,
instead of having multiple deprecated versions around.
Alphabetizes the new version.  Removes the "last resort" pragma from the
deprecated version, as it was only needed when they shared the name function
name.
Updates all the documentation links to refer to the new name instead of the
deprecated version.
Updates a test that was using the old name to refer to the new one.
Adjust the carg deprecation test to handle the new changes.
=> Deprecate the `carg` function fully, to be replaced by a new function `phase`

modules/internal/Bytes.chpl, modules/internal/String.chpl, test/unstable/c_str.good, test/unstable/createBorrowingBuffer.chpl, test/unstable/createBorrowingBuffer.compopts, test/unstable/createBorrowingBuffer.good
Marks createBorrowingBuffer on string and bytes as unstable for 2.0
`createBorrowingBuffer` has potentially questionable behavior that we want to discuss further before stabilizing this (see #22269).
Added test `test/unstable/createBorrowingBuffer.chpl`
Tested with paratest + futures
=> Mark createBorrowingBuffer on string and bytes as unstable

test/release/examples/benchmarks/shootout/mandelbrot-fast.skipif, test/release/examples/benchmarks/shootout/mandelbrot.skipif
PBS/qsub add carriage returns and we can't remove them from binary files like we can non-binary files, so just skip mandlebrot.
Similar to 97eb8fbe04
=> Skip mandlebrot for pbs- based launchers

compiler/optimizations/gpuTransforms.cpp
Some older versions require a copy constructor for some reason, but GPU loop does not allow it. Declare a default copy constructor to make those failures go away.
=> Fix compilation failures under older GCC versions.

doc/rst/technotes/gpu.rst, modules/standard/GpuDiagnostics.chpl
It is not easy at all to capture data movement in cpu-as-device mode. This PR makes sure that `assertGpuDiags` ignores data movement similar to `unified_memory` mode. While there, it also adjusts related documentation to mention this limitation.
https://github.com/chapel-lang/chapel/issues/23191 talks about the limitation itself.
Tests that failed because of this pass with after this PR.
=> Ignore data movement in `assertGpuDiags` with cpu-as-device mode

util/cron/test-homebrew.bash
Homebrew changed the file layout and now chapel is in the Formula/c directory
=> Change location for chapel.rb in homebrew tests

util/cron/test-linux64-aarch64.bash
The recent qthreads 1.19 upgrade provides mature arm support, which is faster and resolves a lot of sporadic issues we've seen. Between that and some recent test fixes we now have clean arm testing and I want to lock that in with a new config.
Resolves Cray/chapel-private#4540
Resolves Cray/chapel-private#5334
=> Add linux64 aarch64 testing

test/gpu/native/multiLocale/onAllGpusOnAllLocales.chpl, test/gpu/native/multiLocale/onAllGpusOnAllLocales.good
This test locks in number of kernel launches in a custom way and needed adjusting now that `array_on_device` is the default memory strategy.
Test passes under gasnet+gpu configuration.
=> Adjust a multilocale GPU test for AOD runs

test/studies/dedup/dedup-debug-1.chpl, test/studies/dedup/dedup-debug-1.compopts, test/studies/dedup/dedup-debug-1.prediff, test/studies/dedup/dedup-debug-1.skipif, test/studies/dedup/dedup-debug-2.chpl, test/studies/dedup/dedup-debug-2.compopts, test/studies/dedup/dedup-debug-2.prediff, test/studies/dedup/dedup-debug-2.skipif
This PR adds clones of the test `studies/dedup/dedup-extern` to debug recent valgrind+ASAN failures and earlier sporadic execution crashes in this test that we have not been able to reproduce in manual runs.
These clones are skipif-ed for non-valgrind configurations. They have `--savec` in compopts, with and without `--devel -g`, to generate persisting artifacts.
They are missing .good files intentionally to draw my intention to them.
Not reviewed.
=> Debug dedup failures with additional tests

test/studies/dedup/PREDIFF, test/studies/dedup/dedup-debug-1.prediff, test/studies/dedup/dedup-debug-2.prediff
This PR removes the `-i` option when saving away the compiled executables in the tests added in #23198. Otherwise it may hang forever if the tests re-run without cleaning up the gen directories. While there, prevent the PREDIFF from mingling these tests' output.
While these tests are no longer needed, I would like to keep them around until we resolve the underlying issue.
Not reviewed.
=> Fixup dedup debugging tests

test/studies/dedup/dedup-extern.compopts, test/studies/dedup/dedup-externblock.compopts
Previously, these tests just used pkg-config to check if a new enough libcrypto is installed, but then didn't provider any compopts, so essentially assumed it was a system install and that `-l libcrypo` would find the correct one. However, this isn't right since others tools can put things in the pkg-config path in a way that won't be found by default by a compiler.
This resulted in cases where a spack install provides a new enough libcrypto pass the skipif, but then our test was using too old over a system version. Fix that here by using pkg-config to get the include and lib paths.
This should resolve recent failures on valgrind and I believe explains sporadic failures we've seen since the reason we require a newer version is that old versions weren't thread safe and cause sporadic …
=> Use pkg-config to find libcrypo deps for dedup tests

util/cron/test-linux64-aarch64.bash
Default nodepara 2 is taking over 24 hours, so try 3 to get under.
=> Bump new linux64-aarch64 testing nodepara to 3

test/studies/dedup/PREDIFF, test/studies/dedup/dedup-debug-1.chpl, test/studies/dedup/dedup-debug-1.compopts, test/studies/dedup/dedup-debug-1.prediff, test/studies/dedup/dedup-debug-1.skipif, test/studies/dedup/dedup-debug-2.chpl, test/studies/dedup/dedup-debug-2.compopts, test/studies/dedup/dedup-debug-2.prediff, test/studies/dedup/dedup-debug-2.skipif
Revert #23200 and #23198.
They are (hopefully) no longer needed, thanks to #23199.
Not reviewed.
=> Remove dedup debugging tests

modules/standard/Math.chpl
=> Update documentation for `Math.exp` and `Math.expm1` to link to `e`

test/localeModels/gbt/maxTaskPar.prediff
Since #22945 `here.maxTaskPar` reflects the number of performance cores on mac. Use `sysctl -n hw.perflevel0.physicalcpu` to compute that if it's available, falling back to the current `hw.physicalcpu` if that doesn't exist.
=> Fix maxTaskPar test on arm macs under qthreads

modules/standard/Math.chpl, test/unstable/Math/unstableBessel.chpl, test/unstable/Math/unstableBessel.good, test/unstable/Math/unstableErf.chpl, test/unstable/Math/unstableErf.good, test/unstable/Math/unstableErfc.chpl, test/unstable/Math/unstableErfc.good
We will look at these functions post-2.0 to determine if we want to
continue using those names for them and if we want them to
continue to live in the Math module or get moved to an even more
specific module.  Mark them unstable so that users have warning
of this change.
Adds tests to lock in the unstable warnings for these functions.
Passed a full paratest with futures.
=> Mark erf, erfc and bessel functions unstable

compiler/passes/expandExternArrayCalls.cpp, test/unstable/externProcArrayFormal.chpl, test/unstable/externProcArrayFormal.compopts, test/unstable/externProcArrayFormal.good
Mark extern array formals as unstable for 2.0. Implements unstable warning for #22957.
The following pattern warns: `extern proc foo(x: [] int)`
Tested with full paratest
=> Mark extern proc array formals as unstable

test/gpu/native/multiLocale/onAllGpusOnAllLocales.chpl, test/gpu/native/multiLocale/onAllGpusOnAllLocales.good
I "fixed" this test in https://github.com/chapel-lang/chapel/pull/23197. But kernel launch math was incorrect for systems where there is multiple GPUs per locale.
This PR re-fixes the test, hopefully correctly this time.
=> Fix math in a test validation

test/chpldoc/unstableSymbols.doc.catfiles, test/chpldoc/unstableSymbols.doc.chpl, test/chpldoc/unstableSymbols.doc.good, tools/chpldoc/chpldoc.cpp
Resolves Cray/chapel-private#5352
Ben H had pointed out that unstable modules were failing to generate
unstable warnings in their documentation (the Heap module was
an example of this).  While testing that change, I also noticed that
we were:
- failing to properly generate the message when relying on the
default unstable warning
- and had stopped avoiding generating the message in documentation
when the documentation comment already had the word unstable in it
Fix all three of these problems and add a test locking in the behavior
for all three.
Verified that the generated online documentation for Heap now displayed
the warning appropriately.
=> Fix some issues with unstable documentation and add a test

util/test/sub_test.py
Some of the `sub_test.py` output is standardized so it can be parsed by downstream tools such as `start_test.`py and
`convert_start_test_log_to_junit_xml.py`. This output is now created via methods that can be called by programs that use `sub_test.py` as a module.
=> Create methods for standardized output

doc/rst/users-guide/base/basicValues.rst, modules/standard/FileSystem.chpl, test/unstable/changeMaskFlat.chpl, test/unstable/changeMaskFlat.good, test/unstable/changeMaskFlat.skipif, test/unstable/changeMaskNotFlat.chpl, test/unstable/changeMaskNotFlat.good, test/unstable/changeMaskNotFlat.prediff, test/unstable/changeMaskNotFlat.skipif
This PR marks `locale.umask` in the `FileSystem` module as unstable for locale models that are not `flat`. It also adds some text to the `mask` argument description indicating it can be assigned an octal literal.
This was motivated by design discussions on changing the location, return type or argument types for `umask`, where the major consideration for was how `umask` should behave on locale models with sub-locales. The summary issue can be found here https://github.com/Cray/chapel-private/issues/4988.
The unstable warning is written directly into the docs so that it shows up without double documenting the `umask` procedure.
TESTING:
=> mark umask unstable, add doc example for octals

test/exercises/RandomNumber6.skipif
#23152 increased the stack task size for RandomNumber6, which caused sporadic OOMs on linux32 depending on how many tasks were live at the same time. Just skip this test under linxu32 instead of trying to find the perfect stack size.
=> Skip RandomNumber6 on linux32

runtime/src/threads/pthreads/threads-pthreads.c
Fifo was setting `PROT_EXEC | PROT_WRITE` when disabling guard pages, but pages aren't allowed to have both on recent macs. From newer darwin `mmap` man pages:
> When the hardened runtime is enabled (See the links in the SEE ALSO
> section), the protections cannot be both PROT_WRITE and PROT_EXEC
> without also having the flag MAP_JIT and the process possessing the
> com.apple.security.cs.allow-jit entitlement
We weren't checking the `mprotect` return code, so we were just silently letting guard pages remain, which led to later segfaults when the program touched that memory. This was causing sporadic segfaults on mac arms when using gasnet+fifo+jemalloc, so we switched to using cstdlib in #20160. This worked around the issues since we happen to disable guard pages on macs with the cstdlib …
=> Fix fifo guard pages on arm macs when using jemalloc

util/cron/test-cray-xc-arkouda.bash, util/cron/test-cray-xc-arkouda.release.bash
Now that XC graphs are being synced to an intermediate machine, reenabling performance testing for XC to see if it just falls out or if additional steps are required.
=> Reenable XC graph generation

test/gpu/native/studies/shoc/shoc-sort.chpl
After https://github.com/chapel-lang/chapel/pull/23218, there were some resolution errors in shoc-sort because of mixed-type ranges. This PR fixes that.
=> Fix index types of ranges in shoc-sort

modules/standard/JSON.chpl, test/deprecated/IO/iokind/printing-iokind-types.good, test/deprecated/IO/jsonSerializer.chpl, test/deprecated/IO/jsonSerializer.good, test/io/ferguson/printing-channel-types.good, test/library/standard/Map/readMapStringsBytes.chpl, test/library/standard/Map/readMapStringsBytes.good
https://github.com/chapel-lang/chapel/pull/23219 replaced `JsonSerializer` and `JsonDeserialier` with camelCase versions without keeping the old versions around as deprecated symbols. This PR properly deprecates them.
=> Fix deprecation of `JsonSerializer` and `JsonDeserializer`

test/runtime/jhh/cpuKinds/cpuKinds.py
The JUnit XML test results are created by scraping the log, which requires that tests produce the output expected by the scraper. The heterogeneous processing unit test (cpuKind.py) wasn't doing that, so Jenkins didn't notice that it was failing.  The test now produces the correct output and it is skipped in configurations in which `CHPL_HWLOC==none`.
=> Produce output required for XML test results

modules/standard/Reflection.chpl, test/library/standard/Reflection/cannotInspectBuiltins-array.good, test/library/standard/Reflection/cannotInspectBuiltins-atomic.good, test/library/standard/Reflection/cannotInspectBuiltins-domain.good, test/library/standard/Reflection/cannotInspectBuiltins-range.good, test/library/standard/Reflection/cannotInspectBuiltins-string.good, test/library/standard/Reflection/cannotInspectBuiltins-sync.good, test/library/standard/Reflection/cannotInspectBuiltins-tuple.good, test/library/standard/Reflection/cannotInspectBuiltins.chpl, test/library/standard/Reflection/cannotInspectBuiltins.compopts, test/library/standard/Reflection/cannotInspectBuiltins.good, test/library/standard/Reflection/cannotInspectBuiltins.prediff
Adds more extensive tests of Reflection functions which query the fields of a record. We have a number of internal types which are implemented as records but that should not be visible. 
Added checks to `getFieldRef` to verify that the type was not a implementation record. Other tested functions already had these checks.
tested full paratest with futures
closes #14546
closes cray/chapel-private#2829
Future work
- Some of these error messages could be improved to refer to the users code instead of the Reflection module, see #23244
=> Add more tests of Reflection errors for implementation records

modules/internal/ChapelGpuSupport.chpl, modules/internal/DefaultRectangular.chpl, modules/internal/MemTracking.chpl, modules/internal/PrintModuleInitOrder.chpl, runtime/src/config.c, test/distributions/bharshbarg/fastFollowerEquality.good, test/distributions/robust/arithmetic/reindexing/simple-alias-mem-use.comm-none.good, test/distributions/robust/arithmetic/reindexing/simple-alias-mem-use.good, test/execflags/configs/privateconfigs-help-set.comm-none.good, test/execflags/configs/privateconfigs-help-set.good, test/execflags/configs/privateconfigs-help.comm-none.good, test/execflags/configs/privateconfigs-help.good, test/execflags/ferguson/help2.good, test/execflags/shannon/configs/help/basehelp.txt, test/execflags/shannon/help.good, test/statements/manage/WarnUnstable.good, test/unstable/.gitignore, test/unstable/unstableConfigs.chpl, test/unstable/unstableConfigs.cleanfiles, test/unstable/unstableConfigs.datapar.good, test/unstable/unstableConfigs.execopts, test/unstable/unstableConfigs.good, test/unstable/unstableConfigs.gpu.good, test/unstable/unstableConfigs.help.comm-none.good, test/unstable/unstableConfigs.help.good, test/unstable/unstableConfigs.initorder.good, test/unstable/unstableConfigs.mem.good, test/unstable/unstableConfigs.prediff
Based on discussion in #21150, marked the following configs as unstable, and thus prevent them from showing up in `--help`
- printModuleInitOrder (modules/internal/PrintModuleInitOrder.chpl)
- dataPar* (modules/internal/DefaultRectangular.chpl)  <-- 3 configs
- mem* (modules/internal/MemTracking.chpl) <--  9 configs
- debugGpu, enableGpuP2P, gpuNoCpuModeWarning (modules/internal/ChapelGpuSupport.chpl) <-- 3 configs
=> Marking more configs as unstable

test/studies/nbody/md.chpl
Adds explicit ref forall intents to a test which failed in nightly test configurations
Fixes more fallout from https://github.com/chapel-lang/chapel/pull/23175.
=> Resolve test failures from deprecating ref-maybe-const forall intents

compiler/AST/type.cpp, compiler/include/type.h, compiler/resolution/fcf-support.cpp
PR #23185 introduced a bug that was caused by sharing code for printing types between _user_ strings (which should be pretty-printed) and _mangled_ strnings (which should be valid C identifiers). This PR disentangles the two uses of type printing in FCFs to make both work.
=> Adjust FCF mangled names to not include special characters
