chapel-lang/chapel

- third-party/qthread/Makefile
- util/chplenv/chpl_tasks.py
- util/cron/test-darwin-m1.bash
- util/cron/test-gasnet.darwin-m1.bash
qthreads 1.19 has mature support for ARM64, including native ARM context switching and bugfixes for ARM memory consistency issues. This significantly improves the stability and performance of qthreads on ARM, especially for arm-based macs where system ucontext switching was slow enough that we defaulted to fifo previously. Qthreads with native asm is now much faster than fifo on arm macs and correctness testing looks stable, so make it the default.
Here's performance for a task creation and switching microbenchmark on a 10 core M1 Pro (8 performance cores, 2 efficiency):
<details>
```chpl
// Small parallel/taskCompare/elliot/{empty-chpl-taskspawn.chpl,chpl-taskyield.chpl}
use Time;
config const trials = 500_000;
var s: stopwatch; s.start();
for 1..trials do
coforall 1..here.maxTaskPar { } …
```
> Default to qthreads tasking layer on arm based macs

- modules/packages/Curl.chpl
Adds explicit ref intent to method in `Curl`, which is not tested in our nightly test suite.
> Fix Curl to use explicit ref intent

- test/runtime/jhh/cpuKinds/cpuKinds.c
The test harness `cpuKinds.c` needed to be updated to the new way of initializing the topology layer.
> Update to new initialization sequence

- doc/rst/language/spec/lexical-structure.rst
- frontend/lib/uast/post-parse-checks.cpp
- test/chpldoc/functions/WhereClause.doc.chpl
- test/chpldoc/functions/WhereClause.doc.good
- test/functions/iterators/bradc/leadFollow/leadNoYield.chpl
- test/functions/iterators/theseKeyword.chpl
- test/functions/iterators/theseKeyword.good
Adds a check in `post-parse-checks.cpp` prohibiting identifiers named `these` except for iter methods, and documents `these` as a keyword.
Also allows proc methods named `these` that forward iterators via `pragma "fn returns iterator"`.
Resolves https://github.com/Cray/chapel-private/issues/5317.
Testing:
> Reserve name 'these' for iter methods only

- compiler/resolution/functionResolution.cpp
- test/classes/casts/cast-managed-to-unmanaged.chpl
- test/classes/casts/cast-managed-to-unmanaged.good
Fixes bug when casting to `unmanaged` from a managed class where the compiler would insert an automatic borrow.
If a user wanted to write the following code, the first cast would print the type correctly and the second cast would always print the type of `x` as `owned MyClass`, regardless of the actual argument type.
```chapel
operator :(x: MyClass, type t: int) {
writeln("x.type is ", x.type:string);
return x.field;
}
operator :(x: MyClass, type t: unmanaged) {
writeln("x.type is ", x.type:string);
return x.field;
}
```
- tighten borrowing logic in `adjustClassCastCall` to not borrow from an `unmanaged`
- removing this logic outright caused ~70 failures in a paratest, but adding this one extra check caused no failures 
- add test case of original bug
- paratest …
> Tighten class casting logic when casting to an `unmanaged`

- frontend/lib/uast/Builder.cpp
- test/distributions/bharshbarg/fastFollowerEquality.good
- test/distributions/robust/arithmetic/reindexing/simple-alias-mem-use.comm-none.good
- test/distributions/robust/arithmetic/reindexing/simple-alias-mem-use.good
- test/unstable-keyword/config/paramConfigInCmd.compopts
- test/unstable-keyword/config/paramConfigInCmd.good
Resolves #23248 
The config check wasn't accounting for the presence or absence of the
`--warn-unstable` flag.  Rectify that.
Remove the warnings inserted when Shreyas was marking configs unstable.
Now that the warnings only trigger with the flag, the .good files for these
tests can be restored to their earlier state.
Fix the test of unstable configs.  The test was not throwing
`--warn-unstable`, so when we stopped generating that warning in all
settings, it stopped turning up.  Additionally, by actually throwing
`--warn-unstable`, we discovered that the test needed an additional
warning because it was referencing the config in the body of the program as
well.  (Thanks Daniel for pointing that out!)
Testing:
> Adjust dyno to only trigger unstable config warnings when --warn-unstable is set

- test/gpu/native/multiLocale/onAllGpusOnAllLocales.chpl
- test/gpu/native/multiLocale/onAllGpusOnAllLocales.good
This puts a bandaid on a test that does a custom kernel launch number assertion.
I am not a big fan of the solution, but it'll keep us going. Ideally we want to improve our `*Here` story in the GpuDiagnostics module and maybe add an `assertGpuDiags` overload for multilocale runs.
> Yet another fix for a multilocale GPU test

- test/ANNOTATIONS.yaml
- fasta and revcomp improvements from https://github.com/chapel-lang/chapel/pull/23162
- Arkouda regressions from https://github.com/Bears-R-Us/arkouda/pull/2735
Also add missed revcomp annotation for the iokind deprecation.
> Add perf annotations for 2023-09-07

- doc/rst/language/spec/lexical-structure.rst
- frontend/lib/uast/post-parse-checks.cpp
- modules/packages/HDF5.chpl
- modules/standard/Types.chpl
- test/classes/stonea/superKeyword.chpl
- test/classes/stonea/superKeyword.good
- test/domains/userAPI/contains.chpl
This PR adds 'super' as a reserved word and updates tests accordingly. 
See the added [test/classes/stonea/superKeyword.chpl](https://github.com/chapel-lang/chapel/compare/main...stonea:chapel:super_keyword#diff-1a0b98eb267b6a66b9dc504a1be697359f7d354154f1325845cf7c6ffeadca2d) test for examples that now fail.
This resolves this issue: https://github.com/chapel-lang/chapel/issues/22058
> Super keyword

- util/devel/deprecationScript/extractLineNumbers.py
- util/devel/deprecationScript/usage.md
Touch up the wonderful script:
* sort the output
* remove "../" from the paths
* ignore matches in .good files, i.e., lines starting with `< `
* print the default for the output file in the help message
> Improve extractLineNumbers.py

- util/test/genGraphs.py
Tonight we see failures in nightlies because of `perfKeys` key instead of `perfkeys` in a graph file. This PR generates a warning to help triage the issue.
Improved logging capabilities have been asked in https://github.com/chapel-lang/chapel/issues/9430. This is a small part of that.
> Warn if there's an invalid key in a graph file

- util/chplenv/chpl_unwind.py
This fixes a simple logical error that's been in `chpl_unwind.py` since it was first added in which we returned `none` rather than the value inferred from the environment or chplconfig files when running on non-linux/osx platforms.
Resolves #23262.
> Fix bug in which CHPL_UNWIND could not be overridden for non-linux/osx

- modules/standard/IO.chpl
- test/modules/bradc/userInsteadOfStandard/ChapelIO.chpl
For what is suspected to be recursive usage of the module, Arkouda was failing with a bus error due to the `public use ChapelIO` in `IO.chpl`. Limiting that use resovles the issue.
Code changes from @lydia-duncan
> Restrict ChapelIO usage in IO module

- util/build_configs/cray-internal/setenv-hpe-cray-ex-x86_64.bash
- util/build_configs/cray-internal/setenv-xc-aarch64.bash
- util/build_configs/cray-internal/setenv-xc-x86_64.bash
This PR removes the automatic building of the lustre auxfs for the Chapel
runtime module builds.   This change should reduce the time for running
the builds.
> Remove lustre from the Aux filesystem list for config builds

- runtime/src/comm/ofi/comm-ofi.c
Previously, we pinned the ofi API version used in `fi_getinfo()` to whatever version we built the runtime with. However, the docs explicitly recommend against this and suggest hard-coding values.
From [`fi_getinfo()`](https://ofiwg.github.io/libfabric/v1.9.1/man/fi_getinfo.3.html)man pages:
> The version parameter is used by the application to request the desired version of the interfaces. The version determines the format of all data structures used by any of the fabric interfaces. Applications should use the FI_VERSION(major, minor) macro to indicate the version, with hard-coded integer values for the major and minor values. The FI_MAJOR_VERSION and FI_MINOR_VERSION enum values defined in fabric.h specify the latest version of the installed library. However, it is recommended that the …
> Pin ofi fi_getinfo API version to 1.9

- util/chplenv/chpl_unwind.py
Although #23270 fixed the behavior of the chpl_unwind.py script for non-osx/linux systems, I accidentally broke it for osx/linux systems that did not have an explicit setting made by removing the fall-through logic that defaulted it to 'none', causing the script to return 'None' when none of the other options were hit.  More proof that I should never write Python scripts.
This fixes the error by moving the val or 'none' conditional that I added last night out a level so that it's always used when none of the other cases trigger.  Thanks to @jabraham17 for pointing out the error in my control flow and improving my style to boot.
> Fix a Python logic bug I introduced in #23270

- test/io/serializers/basic-types.chpl
- test/io/serializers/deserialize-by-ref.chpl
Deletes manual or IO-created unmanaged classes that were recently added to these tests.
> Delete unmanaged classes in serializer tests

- modules/standard/IO.chpl
Resolves #20253 
File descriptors should be considered implementation details in Chapel, so we should avoid referencing them in the documentation for these variables
Double checked the built docs and their links worked as expected
> Modify the stdin/stdout/stderr documentation to avoid referencing file descs

- modules/standard/CTypes.chpl
Fix documentation of `c_addrOf` which lists types for which `c_ptrTo` has special behavior, and left out classes. This documentation update was missed when the special behavior for classes was originally added, in https://github.com/chapel-lang/chapel/pull/22367.
While here, also changes docs to show only the nilable-class-type overload of `c_ptrTo` on classes, since it's redundant to show both the nilable and non-nilable implementation.
As future work, we should probably overhaul the docs of `{c_ptrTo,c_addrOf}[Const]` to just document one overload per method, which is tracked in https://github.com/Cray/chapel-private/issues/5386.
Testing:
> Fix list of c_ptr special behavior in c_addrOf docs

- compiler/AST/astutil.cpp
- compiler/include/astutil.h
- compiler/passes/checkNormalized.cpp
Fixes an issue that came up in our nightly testing where `--verify --warn-unstable` was over-warning. The primary solution was to change the `forv_Vec` over all `CallExpr` to `for_alive_in_Vec`, since the warnings were occurring for CallExpr not in the tree.
Additionally, adds a check to make sure `checkExplicitThis` is only run once.
Fixes issue introduced in https://github.com/chapel-lang/chapel/pull/23245.
Tested locally on the `test/unstable` directory with `--verify` and with a full `paratest --verify`
> Fix issue with `--verify` and `--warn-unstable` for explicit this

- compiler/main/driver.cpp
- util/cron/test-gpu-cuda.specialization.bash
This PR turns off gpu specialization by default.
We previously thought were going to ship with this on by default for the upcoming release but it has a pretty significant compile-time impact (~30% longer on Jacobi).
So lets leave it off while we continue to investigate and perhaps do additional work to trim down the number of specializations.
This PR also introduces a nightly test with gpu specialization on (so things don't regress in the meantime).
> Turn off gpu specialization by default

- frontend/lib/uast/post-parse-checks.cpp
- test/deprecated/chplCommGetPut.chpl
- test/deprecated/chplCommGetPut.good
- test/npb/ft/npadmana/DistributedFFT.chpl
This PR adds compiler warnings if we encounter the primitive calls `chpl_comm_get` or `chpl_comm_put` in user code. 
In PRs #22884 and #22622 we changed the behavior of the primitives `chpl_comm_get` and `chpl_comm_put` to expect references instead of `c_ptr`s, a breaking change for places that were previously passing `c_ptr` directly. Because it only affected the primitive calls (which are not intended to be user facing), we deprecated without replacement or warning. 
Since then, we have received at least one user report of test failures due to the change. Out of an abundance of caution we decided it would be good to add a compiler warning about the changed behavior when these primitives are found in user code.
TESTING:
> warn about new behavior in prim comm_get/put

- modules/internal/ChapelRange.chpl
- test/unstable/defaultUnboundedRange.chpl
- test/unstable/defaultUnboundedRange.good
Per the discussion [here](https://github.com/chapel-lang/chapel/issues/21474), make default initialization of low and high bounded ranges unstable.
The following will produce ranges with the values `0..` and `..1` respectively; however, we may want to change the default values in the future or make them implementation dependant, so an unstable warning will be emitted for each.
```chapel
var rl: range(int, boundKind.low),
rh: range(int, boundKind.high);
```
> Make default initialization of low and high bounded ranges unstable

- compiler/resolution/postFold.cpp
- test/unstable/fcfProcName.chpl
- test/unstable/fcfProcName.good
This takes care of the decision in https://github.com/chapel-lang/chapel/issues/22795#issuecomment-1709219214. At the place where the special `getRoutineName` call is replaced with the routine's name, we also emit a warning if the function is first-class.
> Emit depecation warnings for 'getRoutineName' inside FCFs.

- compiler/AST/symbol.cpp
- compiler/include/symbol.h
- compiler/passes/checkResolved.cpp
- test/unstable/iterTheseWithArguments.chpl
- test/unstable/iterTheseWithArguments.good
Marks any `iter these` which takes any extra arguments. For serial iterators, this is any argument. For standalone and leader parallel iterators, this is any argument other than `tag`. For follower parallel iterators, this is any argument other than `tag` and `followThis`.
Based on discussion in #23075
- add check in `checkResolved` for `iter these` with extra arguments
- required some extra logic to not warn for internal iterators like for arrays 
- add new test of unstable warning in `test/unstable/iterTheseWithArguments.chpl`
[Reveiwed by @riftEmber]
> Mark 'these' iterators which take arguments as unstable

- modules/internal/localeModels/gpu/LocaleModel.chpl
It's a typo (`int this` should be `init this`). It wasn't caught by a paratest because it's in GPU module code.
Trivial, probably will not ask for review.
> Fix a stupid typo in `this.complete()` -> `init this` change.

- test/studies/ml/correctness/SKIPIF
- test/studies/ml/performance/SKIPIF
Skip the `studies/ml` tests in the valgrind configuration to avoid testing timeouts.
> Skip studies/ml/ tests for valgrind config

- compiler/AST/AggregateType.cpp
- compiler/AST/build.cpp
- compiler/AST/type.cpp
- compiler/AST/wellknown.cpp
- compiler/include/AggregateType.h
- doc/rst/language/spec/lexical-structure.rst
- frontend/include/chpl/framework/all-global-strings.h
- frontend/lib/types/CompositeType.cpp
- frontend/lib/types/Type.cpp
- frontend/lib/uast/post-parse-checks.cpp
- modules/internal/ChapelRange.chpl
- modules/packages/Buffers.chpl
- modules/packages/LAPACK.chpl
- test/library/packages/Collection/CollectionBulk.chpl
- test/npb/is/mcahir/intsort.mtml.chpl
- test/types/range/stonea/rangeKeyword.chpl
- test/types/range/stonea/rangeKeyword.good
This PR is addressing https://github.com/chapel-lang/chapel/issues/18216
Add range as a reserved word (see its addition in `isNameReservedType)
To make it so we could still have range as type in our internal modules I rename `range` to `_range` in `ChapelRange.chpl` and define `_range` as an internal type similar to what we do for `_locale`, `_bytes`, etc.
I've updated tests that previously used 'range' as an identifier (in some cases shortening to 'r' in some cases to 'rang').  I'm not particularly happy with it being renamed 'rang' for the `LAPACK.chpl` module but don't have a better idea so I'd be happy to hear suggestions there.
> Range as a reserved word

- test/functions/vass/ref-intent-bug-2big.chpl
I missed this straggler because my automatic process did not catch it, and because the test that triggers the bug is skipped under `comm == none`.
> Remplace 'complete' with 'init this' in a straggler

- util/cron/test-cray-xc-arkouda.bash
- util/cron/test-cray-xc-arkouda.release.bash
Arkouda XC tests are running the performance tests and saving the data, but not syncing the graphs, so reverting to the old syncing to see if that works with the new syncing technique that is being used.
> Reenable graph syncing for XC Arkouda tests

- test/statements/manage/WarnUnstable.skipif
- test/unstable/unstableConfigs.execopts
- test/unstable/unstableConfigs.mem.chpl
- test/unstable/unstableConfigs.mem.execopts
- test/unstable/unstableConfigs.mem.good
- test/unstable/unstableConfigs.mem.skipif
- util/cron/common-memleaks.bash
- util/test/prediff-for-unstable-memleaks
Because the `--memLeaks` flag is unstable, when we use it in our
nightly memleaks job on tests that use the `--warn-unstable` flag,
extra output is generated.  Fix that
<details>
To fix that, add a prediff script that will be used for the
single locale and multilocale memleaks jobs.  This script will
explicitly remove the memLeaks warning from from tests that
encounter it.
</details>
There are two tests that intentionally throw both of these flags
together normally.  Unfortunately, that means that they would
generate an extra error, which would cause them to fail.  So,
skip them when the flag is thrown generally (which is fine,
because what it would otherwise be testing is already handled
in the default nightly setting, as a result of those flags being
always provided to those tests) - …
> Fix memleaks testing warnings for with `--warn-unstable`

- compiler/passes/splitInit.cpp
- doc/rst/language/spec/variables.rst
- test/types/records/copy-elision/copy-elision-sync.chpl
- test/types/records/copy-elision/copy-elision-sync.good
- test/types/records/split-init/split-init-sync.chpl
- test/types/records/split-init/split-init-sync.good
Closes https://github.com/Cray/chapel-private/issues/5375
Closes #20974
This PR enables split init of a variable across a `sync` block. (Note: sync blocks are typically used with `begin` and split init is still not allowed across a `begin`). Copy elision was already allowed across `sync` blocks.
Additionally, this PR
* adjusts the language specification to indicate split init and copy elision are allowed across `sync` blocks themselves
* adds two tests to lock in split init and copy elision with `sync` blocks
> Enable split init for sync blocks

- compiler/resolution/preFold.cpp
- test/deprecated/IO/iokind/kind-queries.chpl
- test/deprecated/IO/iokind/kind-queries.good
This PR adjusts the implementation of PRIM_QUERY during resolution specifically for the ``fileReader`` and ``fileWriter`` types. While these types have had their ``kind`` field deprecated, it is still technically the first generic field in the type. This PR modifies the PRIM_QUERY implementation to skip the 'kind' field unless it is explicitly specified. A deprecation test is also added exercising various queries.
Note: The production compiler currently inserts PRIM_QUERY calls into a 'where' clause during the ``normalize`` pass even when queries are not present. For example, a type expression like ``R(int)`` would see a where-clause generated comparing ``int`` to the first generic field in ``R``.
Testing:
> Adjust PRIM_QUERY for fileReader/fileWriter

- test/compflags/driver/debugger/declint.prediff
Fix `test/compflags/driver/debugger/declint.prediff` which was not handling `gdb`'s version-dependent newline after prompt behavior.
This was copied in https://github.com/chapel-lang/chapel/pull/21063 from `test/compflags/bradc/gdbddash/declint.prediff`, which _does_ handle this behavior if the prompt is the last thing in program output. Since the driver version expects further output after the prompt, it needed adjustment to still work correctly across testing systems.
[trivial test fix, not reviewed]
Testing:
> Fix prediff for compiler-driver gdb invocation test

- modules/standard/CTypes.chpl
Remove `c_sizeof(type x)` signature that was deprecated in 1.30 for formal name change from `x`->`t`.
This is my only deprecation from 1.30 per my CHANGES.md for that release.
Testing:
> Remove old `c_sizeof` version with deprecated formal name

- compiler/include/arg-helpers.h
The typedefs were added in #20546 and don't seem to be necessary.
> Remove typedefs that create a portability problem on Alpine 3.15

- test/interop/fortran/FortranCallChapel/chapelProcs.chpl
- test/interop/fortran/fortArrayToDRAutomatic/chapelProcs.chpl
- test/interop/fortran/fortArrayToDefaultRectangular/chapelProcs.chpl
- test/interop/fortran/genFortranInterface/chapelProcs.chpl
This PR updates Fortran interop tests to use the replacement for `c_string`, `c_ptrConst(c_char)`. This change was made possible due to (PR https://github.com/chapel-lang/chapel/pull/23143), which modified the generation of signatures for libraries to treat `c_ptrConst(c_char)` similar to how `c_string` used to work. This resolves a TODO to change the type in the tests, leftover from https://github.com/chapel-lang/chapel/pull/22943.
TESTING:
```
[Error matching program output for library/packages/Socket/connectblocking]
[Error matching program output for library/packages/Socket/connecttimeout]
[Error matching program output for library/packages/Socket/ipaddr]
[Error matching program output for library/packages/Socket/ipfamily]
[Error matching program output for …
```
> update `c_string` to be `c_ptrConst(c_char)`

- modules/internal/Bytes.chpl
- modules/internal/String.chpl
- test/unstable/localize.chpl
- test/unstable/localize.good
This PR marks the `localize()` method `unstable` on `string`/`bytes`. 
Backing issue is https://github.com/Cray/chapel-private/issues/5389.
TESTING:
```
[Error matching program output for library/packages/Socket/connectblocking]
[Error matching program output for library/packages/Socket/connecttimeout]
[Error matching program output for library/packages/Socket/ipaddr]
[Error matching program output for library/packages/Socket/ipfamily]
[Error matching program output for library/packages/Socket/listen]
[Error matching program output for library/packages/Socket/networkoptimization]
[Error matching program output for library/packages/Socket/sockaddr]
[Error matching program output for library/packages/Socket/tcpio]
[Error matching program output for library/packages/Socket/udpio_ipv4]
``` …
> mark localize() unstable

- util/cron/test-cray-xc-arkouda.bash
- util/cron/test-cray-xc-arkouda.release.bash
When the XC tests were reenabled, they were added just as correctness tests, not as performance tests, so the CHPL_TEST_PERF_CONFIG_NAME was removed. Now that we are running the XC configurations as performance tests again, we need to add that back in.
> Readd XC testing CHPL_TEST_PERF_CONFIG_NAME

- frontend/include/chpl/parsing/parser-error-classes-list.h
- frontend/lib/parsing/ParserContextImpl.h
- frontend/lib/parsing/lexer-help.h
- frontend/lib/parsing/parser-error-classes-list.cpp
- test/errors/parsing/stringLiteralLocations.1.good
- test/errors/parsing/stringLiteralLocations.2.good
- test/errors/parsing/stringLiteralLocations.chpl
- test/parsing/errors/exceptOnlyInvalidExpr-detailed.good
- test/unstable-keyword/deprecated/1.30/noParens-detailed.good
This PR fixes https://github.com/chapel-lang/chapel/issues/20747, in which a string literal's location doesn't include its left quote, but does include its right quote. Example copied fron the issue:
```
--- error in bad.chpl:2 ---
Branches of if-expression have incompatible types.
In the following if-expression:
|
2 | var x = if b then """hello""" else 1;
|                      ────────      ─
|
the first branch is a param of type 'string', while the second is a param of type 'int(64)'
```
The problem was that we were advancing the (Flex) string location before starting to process the string literal. The proper way is to compute the offset, and then advance the location once, by an amount that includes both the left and right quotes (and the stuff between them).
On the tip of this …
> Fix the string literal locations reported by the parser.

- third-party/llvm/llvm-src/tools/clang/lib/Headers/__clang_cuda_texture_intrinsics.h
Resolves https://github.com/Cray/chapel-private/issues/5260
Better fix for now-closed https://github.com/chapel-lang/chapel/issues/22085
This PR pulls the patch in https://github.com/llvm/llvm-project/commit/817340569bf98b696329c53508a0d87cc0daec25 to our bundled LLVM. This enables CUDA 12 support.
Related PRs:
- https://github.com/chapel-lang/chapel/pull/23338 enables scripts to allow CUDA 12 with bundled LLVM
- https://github.com/chapel-lang/chapel/pull/23339 adds the nightly testing script
Test:
> Patch bundled LLVM to support CUDA 12

- util/chplenv/chpl_gpu.py
Depends on https://github.com/chapel-lang/chapel/pull/23332.
https://github.com/chapel-lang/chapel/pull/23332 patches our bundled LLVM to be able to build CUDA 12. This PR makes chplenv script changes to let CUDA 12 pass with bundled LLVM.
I tested some combinations manually with a system that has several CUDA 11.x installations and a CUDA 12.0 installation.
> Enable CUDA 12 with bundled LLVM

- util/cron/test-gpu-ex-cuda-12.bash
The script added in this PR is almost identical to `util/cron/test-gpu-ex-cuda-11.bash`. The differences are:
- different cudatoolkit module version
- `CHPL_LLVM=bundled` (we support CUDA 12 only with the bundled LLVM)
> Add CUDA 12 nightly script

- test/gpu/interop/cuBLAS/cuBLAS.chpl
- test/library/packages/LAPACK/TestHelpers.chpl
Follow-up to PRs #23291 and #23283. This PR just updates some testing files that don't run in all configurations to remove warnings introduced in those PRs.
> Test updates following 23291 and 23283

- modules/dists/BlockCycDist.chpl
- modules/dists/DimensionalDist2D.chpl
- modules/dists/HashedDist.chpl
- modules/dists/PrivateDist.chpl
- modules/dists/ReplicatedDist.chpl
- modules/dists/StencilDist.chpl
- modules/internal/DefaultRectangular.chpl
- modules/layouts/LayoutCS.chpl
- test/unstable/dmapped-sparse.good
- test/unstable/unstableDists.chpl
- test/unstable/unstableDists.good
Mark modules with unstable distributions as unstable for 2.0. To mark these unstable, this PR wraps the existing implicit modules as prototype modules to maintain the error handling behavior.
- mark the LayoutCS module as unstable
- mark the BlockCycDist module as unstable
- mark the DimensionalDist2D module as unstable
- mark the HashedDist module as unstable
- mark the PrivateDist module as unstable
- mark the ReplicatedDist module as unstable
- mark the StencilDist module as unstable
- mark the marks DefaultDist as unstable directlly, as this is defined in an internal module
- mark the update `test/unstable/dmapped-sparse.good`
- paratest with gasnet
Implements and closes …
> Mark modules with unstable distributions as unstable

- modules/standard/CommDiagnostics.chpl
- modules/standard/Communication.chpl
- modules/standard/Random.chpl
- test/classes/weakPointers/passiveCache.good
- test/library/standard/Random/stonea/fillRandomAssociative.good
- test/library/standard/Random/stonea/permutationAssociative.good
- test/library/standard/Random/stonea/shuffleAssociative.good
- test/unstable/commDiagnosticsModule.chpl
- test/unstable/commDiagnosticsModule.good
- test/unstable/communicationModule.chpl
- test/unstable/communicationModule.good
- test/unstable/randomModule.chpl
- test/unstable/randomModule.good
Adds `@unstable` to the `Random`, `CommDiagnostics`, and `Communication` modules to mark them as unstable.
- Mark modules as unstable
- Adds test of unstable warning for each of these modules to `test/unstable`
- updated `.good` files of tests which relied on line numbers in `Random`
- updated `test/classes/weakPointers/passiveCache.good` since the test uses `Random` and `--warn-unstable`
> Mark the Random, CommDiagnostics, and Communication modules as unstable

- modules/standard/AutoMath.chpl
- modules/standard/Math.chpl
- test/library/standard/Math/testcases_gcd.chpl
- test/library/standard/Math/testcases_gcd.good
Resolves #20983
Damian requested a more generic and tighter version of gcd for 32 bit and 16 bit
integers.  While smaller sized ints could be sent to the original implementation
just fine because of coercion, it would always return the default-sized int.
Adjust the implementation for the default version to use his suggested code, and
add explicit overloads for `int(32)`, `int(16)`, `int(8)`, `uint(64)`,
`uint(32)`, `uint(16)`, and `uint(8)`.
Extends the gcd test for the new overloads.  Guarantees that the right type is
returned and that the answers are consistent in all versions.
> Adjust gcd implementation and add overloads to return different sized ints/uints

- modules/dists/BlockDist.chpl
- modules/dists/CyclicDist.chpl
- test/unstable/blockDistArgs.chpl
- test/unstable/blockDistArgs.good
- test/unstable/cyclicDistArgs.chpl
- test/unstable/cyclicDistArgs.good
This PR unstabilizes all but the first two arguments for the `cyclicDist` and `blockDist` distributions. It does so by creating a new overload of the function that _doesn't_ have these arguments, making it the "canonical" way to construct the two distributions. The original constructor, with the unstable arguments, is kept, and marked "last resort". This original constructor is annotated with `@unstable`.
The PR also removes the documentation of the unstable arguments from the module docs.
Reviewed by @bradcray -- thanks!
> Unstabilize most args for `cyclicDist` and `blockDist`

- test/unstable/blockDistArgs.good
Adds an extra warning line to `test/unstable/blockDistArgs.good`.
Tested was added in #23345 and warning was added in #23349
Tested locally
> Add extra unstable warning to test

- compiler/llvm/clangUtil.cpp
We have seen some failures in CUDA 12 extern testing last night. It was because we were not passing `--offload-arch` to clang specifically, which was ending up using `sm_35`. My strong guess is that `sm_35` is deprecated with CUDA 12. Because our CUDA 12 support is somewhat half-baked, our bundled clang still used `sm_35` under the hood by default.
This PR adjusts our compilation pipeline to pass `--offload-arch` to clang while using it to compile extern code. We use the same arch as we compile Chapel code.
Test:
> Use gpu arch while compiling extern code, too

- util/chplenv/compile_link_args_utils.py
In https://github.com/chapel-lang/chapel/issues/23282, @razoumov reported that with recent releases he's been having an issue in which a system jemalloc library superceded the one we built due to the ordering of -L flags in our generated code.  Specifically, the order in his link line's -L paths goes something like:
* our general lib/ path
* the bundled GMP path
* the bundled hwloc path
* the bundled gasnet path
* other paths / libraries that we get from GASNet (I believe)
* our bundled qthread path
* our bundled jemalloc path
* our bundled re2 path
The problem is the "other paths ; libraries that we get from GASNet" step, which causes the system library path to precede other bundled library paths, notably the qthreads path.
This PR moves the order of any communication library link paths …
> Move communication library link args last amongst our main third-party pkgs

- modules/internal/ChapelBase.chpl
- test/arrays/cast/castArrOfBoolToBool.chpl
- test/arrays/cast/castArrOfBoolToBool.good
This restores the bool->bool cast that I removed when removing 'bool(w)', thinking it was pointless.  It turns out that it mostly is, except that it was the only thing keeping an Arkouda '(array-of-bool):bool' cast working.
Restore it for now, though I think the more proper thing to do is to add an 'array-of-T:T' cast to handle such patterns in general.  That is, it should not be required to create a self cast in order to do a no-op cast on an array, I think.  Will pursue that question and effort separately.
> Restore bool->bool cast

- test/studies/champs/functions.bash
- util/cron/common-champs.bash
The machine where CHAMPS was nightly-tested was decommissioned a while back. This PR adjusts our support scripts here to adjust for the new system. Important changes:
- now we use `chpl_launchcmd` to run on this system
- we use `PrgEnv-gnu` instead of `PrgEnv-cray`
- we use `cray-hdf5-parallel` instead of a custom build
- intel stuff is wired in a custom way
> Patch CHAMPS nightly testing support for the new system

- runtime/src/topo/hwloc/topo-hwloc.c
Co-locales should only be created if either CHPL_RT_LOCALES_PER_NODE is greater than 1, or if the -nl argument specifies that there should be more than one locale per node, e.g., -nl 3x2. Previously, the runtime would implicitly assign each locale its own socket if the node had at least as many sockets as locales.
Resolves https://github.com/Cray/chapel-private/issues/5398
> Co-locales should be explicitly requested

- util/chplenv/chpl_hwloc.py
- util/packaging/homebrew/chapel-main.rb
Our nightly testing is encountering an issue we're linking to a system version of jemalloc despite configuring Chapel to use a bundled version (ultimately resulting in unsightly linker errors):
```
Undefined symbols for architecture arm64:
"_chpl_je_dallocx", referenced from:
_chpl_free in chpl__module.o
_chpl_realloc in chpl__module.o
_chpl_mem_layerInit in libchpl.a(mem-jemalloc.o)
_qio_readv in libchpl.a(qio.o)
_chpl_mem_free in libchpl.a(qio.o)
_qio_writev in libchpl.a(qio.o)
_qio_preadv in libchpl.a(qio.o)
```
I believe this is the same issue as: https://github.com/chapel-lang/chapel/issues/18955
In order to get nightly testing back on track I think we should use the system version of jemalloc (and hwloc, which I think would run into a similar issue).
> Have homebrew use system jemalloc and hwloc

- compiler/AST/type.cpp
- test/arrays/bradc/arrayOfArrayArg.bad
- test/functions/generic/generic-formal-qs.chpl
- test/functions/generic/generic-formal-qs.good
- test/users/kreider/bug_array_of_arrays.bad
Follow-up to PR #23291. This PR just adjusts `toString` on a `Type*` for `_domain` to print as `domain` rather than `_domain`.
Reviewed by @vasslitvinov and @bradcray - thanks!
> Use domain and not _domain in new warning

- test/unstable/packageModules.skipif
Fixes an issue in nightly testing from #23340. `test/unstable/packageModules.chpl` fails if the compiler is not `llvm` or if `chpl` is compiled with `CHPL_LLVM=none`.
Tested locally
> Add `skipif` for failing test in non-llvm configuration

- test/unstable/packageModules.skipif
Fixes the wrong kind of comment used in a `skipif` file. Added in #23383
> Fix comment in skipif for `test/unstable/packageModules`

- test/studies/champs/functions.bash
- util/cron/common-champs.bash
Follow up from https://github.com/chapel-lang/chapel/pull/23376
For some reason sourcing `common-hpe-apollo` wasn't allowing me to load `PrgEnv-gnu` later on. Could be because it loads `gcc` itself? This PR removes sourcing that, instead does the same stuff in different order.
While there, it also uses `CHPL_TEST_LAUNCHCMD` while running executables.
> Followups for CHAMPS nightly script adjustments

- modules/dists/fixDistDocs.perl
Adjusts the fixup script for distributions (`modules/dists/fixDistDocs.perl`) to preserve '.. warning' in the rst so that `unstable` warnings show up in the docs.
> Adjust `fixDistDocs.perl` to preserve '.. warning'

- compiler/passes/normalize.cpp
- test/types/records/generic/generic-with-defaults-q-problem.bad
- test/types/type_variables/ferguson/notGenericQ-var.good
- test/variables/declareVariableGenericType.chpl
- test/variables/declareVariableGenericType.good
Fixes declaring a variable with an explicit generic type, like `var d: domain(?) = {1..34};`. Prior to this PR, this would result in a seg fault when trying to resolve the runtime type. This seems to be due to a difference in how `domain` and `domain(?)` are handled in normalization. This PR normalizes `domain(?)` into `domain` with the flag `MARKED_GENERIC`.
Tested with paratest with futures and paratest with gasnet.
Resolves https://github.com/chapel-lang/chapel/issues/23357
> Fix declaring a variable with an explicit generic type

- test/library/standard/BigInteger/nestedOn.compopts
[suggested by @jabraham17 ; @lydia-duncan should give this a post-merge review]
Ran into this while testing `main` and branches made from it today.
> Remove deprecated flag -- presumably overlooked in #23384?

- util/cron/common-arkouda.bash
https://github.com/chapel-lang/chapel/pull/23395 removed the deprecated `regex.compile`. But that caused failures in dependency checking in Arkouda testing. To avoid failures, this PR avoids that dependency checking. We should update Arkouda to use regex initializers and/or use a compatibility module as the ideal solution.
> Skip dependency checking in Arkouda tests

- test/npb/ft/npadmana/DistributedFFT.chpl
This PR makes minor changes to a performance test. In https://github.com/chapel-lang/chapel/pull/23275 I updated the test to use the `Communication` module instead of calling primitive `get`/`put` routines directly. This caused a failure in the test. After investigating, the suspicion is that there is a bug in code generation that causes the locale numbers to be reset in the generated code. 
The workaround I implemented is to capture the locale numbers in their own variables ahead of the call to the `get`/`put` routines. 
TESTING:
[test change only - not reviewed]
> Fix performance test failure

- test/unstable/packageModules.skipif
Removes extra line from a skipif file that is not needed
> Remove extra line from skipif

- doc/rst/language/spec/ranges.rst
Update the range spec with a warning to reflect the change made in: https://github.com/chapel-lang/chapel/pull/23299.
> Docs warning about default initialization of high/low bounded ranges being unstable

- doc/rst/language/spec/statements.rst
Add a spec section for 'require' statements based largely on part of the 'extern' technote.
> Add a spec section for 'require' statements

- util/packaging/homebrew/chapel-main.rb
In https://github.com/chapel-lang/chapel/pull/23366, I updated the Homebrew formula to use system versions of jemalloc and hwloc.
Unfortunately, this change runs into issues. Some of which may be fixed later by this PR (https://github.com/chapel-lang/chapel/pull/23409#issuecomment-1721704578).
And also this issue about the bundled jemalloc makefile being run and failing despite the fact that we're supposed to be using the system one https://github.com/chapel-lang/chapel/pull/23409#issuecomment-1721704578).
Given all this and how close we are to the release, we decided to have the formula use cstdlib for memory management instead.
> Homebrew formula: use cstdlib and fifo tasks

- doc/rst/language/spec/arrays.rst
- doc/rst/language/spec/methods.rst
- doc/rst/language/spec/procedures.rst
- doc/rst/language/spec/records.rst
Based on https://github.com/chapel-lang/chapel/issues/21398#issuecomment-1654660481, we have deprecated ref-maybe-const. This means that using the default intent no longer allows modification of record receivers or arrays. It also requires task/forall intents to modify them inside of task constructs such as [co]forall and [co]begin. This PR updates the spec to reflect that.
- remove the special section on the default intent for arrays and record this
- removes abstract intent table, as the `const` and the default intent are now the same except for `sync` and ``atomic``
- technically also `single`, but `single` is now deprecated.
- adjust `methods.rst` and `records.rst` to list the default intent for records as `const`.
- adjust `arrays.rst` to list the default intent as `const`.
Note: …
> Update spec to reflect ref-maybe-const work

- modules/dists/dims/BlockCycDim.chpl
- modules/dists/dims/BlockDim.chpl
- modules/dists/dims/ReplicatedDim.chpl
I couldn't figure out why these weren't working last night but Jade solved it this morning: Because chpldoc ignores the type of symbol field (e.g., ':class:'), we'd been linking to the module rather than the type in question, and I couldn't link to the type without providing a module path.
After implementing that fix and looking at the resulting docs, I decided that linking to the module itself is the better thing to do since (a) the type's the first/only thing in the module and (b) linking to the type causes things like the instability warning to scroll off the screen.  So here, I kept the link to the module, fixed the white lie that we were relying on before last night's change, and renamed the link to still name the distribution.
> Fix links from per-dimension distributions back to DimensionalDist2D

- CMakeLists.txt
This PR prevents the nightly 'make-install-check' job from trying to
build and install the language server.
Unless `EXCLUDE_FROM_ALL` is thrown when adding the language server
to the CMakeLists.txt, the `make install` command will always
attempt to build and install the language server (which currently
fails on `linux64` due to an oversight on my part).
Reviewed by @arezaii. Thanks!
> Exclude the language server from the make install

- test/studies/ml/performance/SKIPIF
The `ml/performance` tests are failing with a seg-fault in our nightly intel configuration. This PR will skip those tests in the intel config until more time can be put into debugging the failures.
> Skip ml/performance tests for cray-prgenv-intel compiler

- modules/standard/IO.chpl
- test/library/standard/IO/readBinary/multiloc/binaryArray.good
- test/library/standard/IO/readBinary/multiloc/binaryArray.notest
- test/library/standard/IO/writeBinary/multiloc/writeArray.good
- test/library/standard/IO/writeBinary/multiloc/writeArray.notest
This is a follow up to #23396. In that PR, having discovered a case that seems to cause segmentation faults in some configurations, I notested a couple of tests that would _properly_ be throwing exceptions. This PR improves the situation; Instead of throwing directly from an `on` block in a method, the code will now assign the error to a variable, and throw from outside the `on` block. This avoids the segmentation faults, and thus allows for removing the `.notest` files.
The bug in question is https://github.com/chapel-lang/chapel/issues/23400.
Reviewed by @bradcray -- thanks!
> Work around throwing exceptions under GASNet in IO module code.

- compiler/passes/expandExternArrayCalls.cpp
- test/unstable/externProcArrayFormalStandard.chpl
- test/unstable/externProcArrayFormalStandard.compopts
- test/unstable/externProcArrayFormalStandard.good
- test/unstable/externProcArrayFormalStandard.noexec
- test/unstable/externProcArrayFormalStandard.prediff
Makes the unstable warning for extern proc array formals respect the `--warn-unstable-internal` and `--warn-unstable-standard` flags.
Added a test for `--warn-unstable-standard` on extern proc array formals
Tested with paratest and paratest with gasnet
[Reviewed by @lydia-duncan ]
> Fix unstable warning for extern array formals

- doc/rst/language/evolution.rst
- doc/rst/technotes/extern.rst
Update the C Interoperability technote to state that `c_string` is deprecated (https://github.com/chapel-lang/chapel/pull/22622) and that `c_fn_ptr` is unstable (https://github.com/chapel-lang/chapel/pull/23072).
Testing:
> Add `c_string` deprecation and `c_fn_ptr` unstable to C Interop technote

- doc/rst/technotes/driver.rst
- doc/rst/technotes/index.rst
Add a technical note about the experimental compiler driver mode, containing a summary, motivation, description of control flags, and future work.
Follow up to https://github.com/chapel-lang/chapel/pull/21063 which added the driver mode.
Testing:
> Add a technote for the compiler driver functionality

- util/packaging/homebrew/chapel-main.rb
- util/packaging/homebrew/chapel-release.rb
The homebrew formulas are out of date with what is released on
homebrew-core.   This update brings them back into alignment.   The
chapel-release.rb formula is what is available in homebrew-core, and
the chapel-main.rb will be the formula used for the next Chapel
release.
> Update release and main formulas to include settings from last release

- modules/dists/BlockCycDist.chpl
- modules/dists/BlockDist.chpl
- modules/dists/CyclicDist.chpl
- modules/dists/StencilDist.chpl
- modules/dists/dims/BlockDim.chpl
- modules/packages/LinearAlgebra.chpl
- test/release/examples/primers/chplvis/chplvis2.chpl
- test/release/examples/primers/chplvis/chplvis3.chpl
- test/release/examples/primers/chplvis/chplvis4.chpl
- test/release/examples/primers/distributions.chpl
- test/release/examples/primers/forallLoops.chpl
Replace various uses of `dmapped` throughout the docs with distribution factory functions due to `dmapped` being unstable.
Also adds documentation for the `createDomain` methods on `blockDist`, `cyclicDist`, and `stencilDist` that were missing documentation.
> Remove `dmapped` from docs

- test/studies/shootout/submitted/Compat.chpl
- test/studies/shootout/submitted/CompatGMP.chpl
- test/studies/shootout/submitted/CompatGMP.notest
- test/studies/shootout/submitted/CompatRE2.chpl
- test/studies/shootout/submitted/CompatRE2.notest
- test/studies/shootout/submitted/pidigits2.chpl
- test/studies/shootout/submitted/regexredux2.chpl
- test/studies/shootout/submitted/regexredux3.chpl
In #23428, I failed to recognize the obvious — that in introducing my 'Compat' module, I was infecting all tests that used it with potential dependencies (GMP, RE2) that their skipifs wouldn't skip past.  Here, I'm splitting the Compat module into three so that each test can only bring in those third-party dependencies that it was already expecting to use.
> Split shootout compatibility module into three — normal, GMP, and RE2

- modules/dists/CyclicDist.chpl
Fix the typo pointed out here: https://github.com/chapel-lang/chapel/pull/23440#discussion_r1330157143.
> Fix typo in `cyclicDist` docs

- doc/rst/language/spec/statements.rst
Document that require statements involving .chpl files must be at module-level and must use string literals.
> Improve documentation for require statements for .chpl files

- util/test/chpl_launchcmd.py
This PR causes the following warning to be generated when `-nlX` is passed for number of locales to the `chpl_launchcmd`.
```
[chpl_launchcmd] 2023-09-18 11:57:27,200 [WARNING] Argument format -nl4 is not supported. Please put a space between "-nl" and number of locales, if that's the purpose.
```
I think we can make this parse fine, but for the time being I am just issuing a warning to avoid issues in nightly testing.
> Issue a warning in chpl_launchcmd for  arguments

- doc/rst/language/spec/data-parallelism.rst
Square bracket foralls should result in order-independent (foreach) iteration instead of serial iteration when parallel iterators are not available. Update the data-parallelism spec section to say this.
Closes https://github.com/chapel-lang/chapel/issues/22638
Closes https://github.com/Cray/chapel-private/issues/5378
> Update spec documentation for square-bracket foralls

- compiler/AST/build.cpp
- compiler/include/build.h
- compiler/passes/convert-uast.cpp
- compiler/resolution/postFold.cpp
- test/deprecated/dummyFile.chpl
- test/deprecated/requireNotAtModuleScope.chpl
- test/deprecated/requireNotAtModuleScope.compopts
- test/deprecated/requireNotAtModuleScope.good
Deprecates the 'require' statement used on chpl files at non-module scope.
Based on discussion in https://github.com/chapel-lang/chapel/issues/23418#issuecomment-1725825232
- add check to `processStringInRequireStmt` for chpl files if the statement is at module scope
- this check is against a boolean passed in, since this function can be called when `expr` is not yet in the tree (and thus has no parent information)
- add test `test/deprecated/requireNotAtModuleScope.chpl`
- paratest with gasnet
> Deprecate 'require' on chpl files at non-module scope

- modules/internal/ChapelDomain.chpl
Updates documentation for `bulkAdd` and `bulkAddNoPreserveInds`, which where modified in #22958.
> Update docs for `bulkAdd` and `bulkAddNoPreserveInds`

- doc/rst/language/spec/data-parallelism.rst
Updates the spec on promotion to include a section on indirect whole array indexing. This also calls out the soon-to-be-an-error `A[B] += 3` pattern deprecated in #23208
> Update spec for deprecated modification of indirect whole array indexing 

- compiler/resolution/functionResolution.cpp
Prior to this change, 3 tests in `release/examples` included these messages for code that was within the standard/internal modules (ChapelRange, IO).  We want unstable warnings to only fire in user code unless `--warn-unstable-internal` or `--warn-unstable-standard` are also passed, so limit this message.
> Limit int->uint conversion unstable warnings to user code (without other flags)

- doc/rst/language/spec/interoperability.rst
- doc/rst/technotes/extern.rst
- doc/rst/technotes/libraries.rst
- doc/rst/tools/c2chapel/c2chapel.rst
This PR updates the docs to indicate the deprecation of the `c_string` type, and replaces its use in example codes for C interop, Fortran libraries, `c2chapel` and the interop spec doc. 
TESTING (manually review changes in generated docs for):
[reviewed by @jabraham17 - thank you!]
> update docs regarding c_string and c_ptrConst(c_char)

- doc/rst/technotes/extern.rst
Adds a note about how extern procedures respect intents with regards to `c_ptrTo` and `c_ptrToConst`.
This does not call out that the feature is unstable, as this is tech note and inherently an unstable/experimental feature.
> Add note on array formal intents to extern technote

- doc/rst/tools/chpldoc/chpldoc.rst
- modules/standard/DynamicIters.chpl
- modules/standard/IO.chpl
- modules/standard/Subprocess.chpl
- test/unstable/ioModeAppend.good
Using features added in #22750, improves the documentation of enums in our modules. Updated both stable and unstable enums, but left deprecated enums alone. Also updated the docs for `chpldoc` to mention the attribute used (`:enumconstant:`)
- Refactor `IO.ioMode`
- Refactor `IO.ioendian`
- Refactor `DynamicIters.Method`
- Refactor `Subprocess.pipeStyle`
- Add small note about `:enumconstant:` to `doc/rst/tools/chpldoc/chpldoc.rst`
- paratest sanity check
> Improve documentation of enums in modules

- compiler/codegen/cg-expr.cpp
- compiler/optimizations/gpuTransforms.cpp
- test/gpu/native/basics/README
- test/gpu/native/basics/bug23045.chpl
- test/gpu/native/basics/bug23045.good
- test/gpu/native/basics/outerRef.chpl
- test/gpu/native/basics/outerRef.good
- test/gpu/native/basics/outerRefFuture.bad
- test/gpu/native/basics/outerRefFuture.chpl
- test/gpu/native/basics/outerRefFuture.future
- test/gpu/native/basics/outerRefFuture.good
Resolves https://github.com/chapel-lang/chapel/issues/23045
This PR handles *some* `ref` variables outside of GPU kernels properly. Previously, all refs were falling into the same code path as class variables where the variable was not offloaded by the runtime. With this PR, refs of primitive types will no longer execute that codegen path, but instead will be passed with a non-zero size, which triggers the runtime to offload the variable to the GPU memory.
In effect, outer `ref`s will be copied onto the GPU memory and `ref`s will refer to that. Arguably, we should tighten the story when proper intents and shadow variables are implemented for `foreach` loops.
Tests:
> Handle outer ref variables properly in GPU kernels

- doc/rst/technotes/gpu.rst
Tech note updates for 1.32:
- We now have features parity for AMD in regards to math functions so remove the bullet saying we don't.
- Add a new small section: "Examining Generated Assembly"
> GPU technote updates for 1.32

- frontend/lib/uast/post-parse-checks.cpp
- test/unstable/leadingUnderscore.chpl
Skip unstable warning for names with leading underscores for the special name that is _just_ `_`, as used in de-tupling, and test that the warning is not emitted.
Resolves https://github.com/chapel-lang/chapel/issues/23430.
Testing:
> Skip leading underscore warning for name "_"

- modules/standard/CTypes.chpl
- test/types/cptr/c_ptrTo_domain.1.good
- test/types/cptr/c_ptrTo_domain.2.good
- test/types/cptr/c_ptrTo_domain.3.good
- test/types/cptr/c_ptrTo_domain.4.good
- test/types/cptr/c_ptrTo_domain.chpl
- test/types/cptr/c_ptrTo_domain.compopts
- test/types/cptr/c_ptrTo_domain.prediff
Fix incorrect error text for `c_ptrTo`/`c_ptrToConst` on `domain` types, and add a test locking it in.
Before this PR, an error is emitted, but it mentions the corresponding `c_addrOf`/`c_addrOfConst` procedure instead of the called procedure. This bug appears to have been introduced in https://github.com/chapel-lang/chapel/pull/22165.
Testing:
> Fix and test error for `c_ptrTo[Const]` on `domain`s

- modules/internal/ChapelRange.chpl
- test/unstable/rangeUnboundedEnumBoolFirstLast.chpl
- test/unstable/rangeUnboundedEnumBoolFirstLast.good
These functions on ranges had behavior inconsistent with `range.first` and `range.last` for unbounded ranges over `enum`s/`bool`s We marked `range.first` and `range.last` as unstable over ranges over `enum`s/`bool`s and that side of the range is unbounded. This is because our current working theory is to treat ranges over `enum`s/`bool`s as always representing a bounded range since the types are finite. based on this `hasFirst()`, `hasLast()`, and `isEmpty()` should also be unstable in those cases and follow the correct behavior.
I also replaced internal use of `hasFirst()` with `hasFirstForIter()` and similarly for `hasLast()` with `hasLastForIter()`
Since I marked `hasFirst()` and `hasLast()` as unstable using `compilerWarning`s,
these warnings were causing test failures when the …
> Fix bug with hasFirst, hasLast, and isEmpty

- doc/rst/technotes/gpu.rst
As of https://github.com/chapel-lang/chapel/pull/22932, we have moved to using the `@assertOnGpu` attribute. This PR implements the documentation change. It keeps references to the "regular" `assertOnGpu` in the docs, but switches to describing `@assertOnGpu` instead of `assertOnGpu()`.
> Update the GPU tech note to include the @assertOnGpu attribute

- frontend/include/chpl/uast/PragmaList.h
- modules/internal/ChapelRange.chpl
- test/chpldoc/functions/WhereClause.doc.chpl
- test/chpldoc/functions/WhereClause.doc.good
- tools/chpldoc/chpldoc.cpp
This PR enables hiding the where-clause from the chpldoc of a function by annotating the function with a pragma `"no where doc"` . It applies this pragma to `range.tryCast`, whose where-clause is not intended for user-facing documentation.
The same result could be achieved as easily with `@chpldoc.noWhere`, however that would be a "feature" and we are past feature freeze for the release.
Testing: standard paratest.
Here are two overloads of `range.tryCast` (with @chpldoc.nodoc removed) before the pragma:
Here are the same overloads with the pragma implemented and added to the first overload:
I anticipate this pragma to be used in the Reflection module, which has a couple of non-user-facing where clauses, ex. https://chapel-lang.org/docs/main/modules/standard/Reflection.html#Reflection.getF …
> Disable where-clauses in chpldoc with a pragma

- modules/standard/IO.chpl
- modules/standard/Subprocess.chpl
This PR adds an example of how to use serializers to achieve binary IO with the subprocess module, as an alternative to the deprecated ``kind`` field.
This PR also adds some documentation to the overlooked ``withSerializer`` and ``withDeserializer`` methods.
> Add serializer example to Subprocess module docs

- doc/rst/language/spec/arrays.rst
- doc/rst/language/spec/domains.rst
- doc/rst/language/spec/ranges.rst
- test/release/examples/primers/associative.chpl
- test/release/examples/primers/domains.chpl
- test/release/examples/primers/sparse.chpl
This PR updates documentation for the following changes:
- Sparse Domains were marked unstable. (#22741 )
- Associative Domains were marked unstable. (#23117)
- equality between unbounded ranges over enum's and bools was marked
unstable  (#23036) 
- deprecate assignment between unbounded ranges with incompatible idxtypes(#22823)
> Doc changes for range/domain unstable/deprecated

- compiler/llvm/clangUtil.cpp
- doc/rst/technotes/gpu.rst
- util/chplenv/chpl_gpu.py
This PR:
- improves the GPU SDK path finding heuristic (resolves https://github.com/chapel-lang/chapel/issues/22780)
- links `oclc_abi_version_400.bc` file (resolves https://github.com/chapel-lang/chapel/issues/22781)
- updates the GPU technote w.r.t. supported ROCm versions
Test:
> Add support ROCm versions through 5.4

- modules/standard/IO.chpl
- test/library/standard/IO/writeBinary/multiDimArraySlices-block.good
- test/library/standard/IO/writeBinary/multiDimArraySlices-old.chpl
- test/library/standard/IO/writeBinary/multiDimArraySlices-old.compopts
- test/library/standard/IO/writeBinary/multiDimArraySlices-old.good
- test/library/standard/IO/writeBinary/readBlockArray-old.chpl
- test/library/standard/IO/writeBinary/readBlockArray-old.compopts
- test/library/standard/IO/writeBinary/readBlockArray-old.good
- test/library/standard/IO/writeBinary/readWriteMultidimArray-block.good
- test/library/standard/IO/writeBinary/readWriteMultidimArray-old-block.good
- test/library/standard/IO/writeBinary/readWriteMultidimArray-old-dr.good
- test/library/standard/IO/writeBinary/readWriteMultidimArray-old.chpl
- test/library/standard/IO/writeBinary/readWriteMultidimArray-old.compopts
PR #23396 modified the `where` clauses of deprecated overloads, but didn't change their implementations (since they were deprecated, and shouldn't be updated). This was effectively a change in behavior for these routines, since they would now accept multi-dimensional arrays (but not have any logic to throw etc.). This PR restores the old `where` to limit arguments to the _old_ `readBinary` to 1-dimensional, rectangular arrays (as opposed to the new implementation's N-dimensional _local_ rectangular arrays). 
Since the new no-`where` overload introduced by Brad serves to prevent accidental promotion for arrays of unsupported types, I've kept it. However, I've specialized the message to be consistent with the `where` clause of the current `readBinary` overload, be it the "old" or the "new" …
> Fixup deprecated readBinary overloads

- tools/chpldef/Message.cpp
- tools/chpldef/Message.h
- tools/chpldef/Server.h
- tools/chpldef/Transport.cpp
This PR fixes several compiler errors that only appear when compiling
the language server with GCC. Shamefully, I forgot to test my build of
#22861 w/ GCC, and let in some bugs as I only develop with Clang.
The most frustrating bug here by far was "full specialization in
non-namespace scope", which I finally tracked down to the following
defect report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85282
This is still not fixed yet as of GCC 12 as far as I know (haven't
used 12, so don't quote me on it), so it certainly isn't a feature
we can rely on.
I worked around the bug by using `constexpr` folding instead of
specialization, but it's a solution I'm still not quite happy with.
Another frustrating bug involved parameter-packing and recursive
template instantiation. While Clang knew to …
> [LSP] Adjust language server code to fix bugs when compiling with GCC

- test/release/examples/primers/distributions.chpl
- test/release/examples/primers/distributions.comm-none.good
- test/release/examples/primers/distributions.good
This does a few things:
* refreshes the introductory text to provide more context for distributions and using distributed domains and arrays
* tries to improve the narrative and flow once computations start getting written
* removes the BlockCyclic and DimensionalDist2D distributions, as they're not nearly as stable and complete as Block and Cyclic, and I don't think they're worth featuring at the same level of detail. (Moreover, I think it's more important for this primer to introduce the concept of distributions than to introduce every single distribution we might write — distributions can document themselves in their documentation rather than here).
> Major refresh to the distributions primer

- doc/rst/technotes/ioSerializers.rst
- modules/standard/ChapelIO.chpl
This PR updates the serializers technote to include the full Serializer and Deserializer API, as well as information concerning the relevant interfaces (e.g. ``writeSerializable``).
> Update serializers technote and ChapelIO

- test/gpu/native/basics/bug23045.skipif
The test in question is the code from https://github.com/chapel-lang/chapel/issues/23045 which has `__device__` functions in an extern block. That doesn't compile in cpu-as-device mode. This PR adds a skipif for that.
> Skip a test with cpu-as-device mode

- modules/standard/IO.chpl
This PR documents the ``defaultSerializer``, ``defaultDeserializer``, ``binarySerializer``, and ``binaryDeserializer`` types. Each format is specified in terms of how it prints primitive types and the various type kinds. Each Serializer and Deserializer also directs users to the serializers technote for a more in-depth description of the serialization feature of the standard IO library.
> Document default and binary (De)Serializers

- doc/rst/language/spec/classes.rst
- doc/rst/language/spec/conversions.rst
- doc/rst/language/spec/generics.rst
- doc/rst/language/spec/procedures.rst
- doc/rst/language/spec/records.rst
- doc/rst/language/spec/types.rst
This PR updates the language specification to cover the changes in PRs #23291 #22784 #22745 #23356 where marking a generic type with `(?)` is now needed.
This PR adds several new spec sections:
* Fields with Generic Types
* Fully Defaulted Generic Types
* Marking Generic Types
> Update language specification to describe T(?)

- doc/rst/language/spec/classes.rst
- doc/rst/language/spec/procedures.rst
This PR updates the language specification to clarify how an identifier within a method is interpreted. If the identifier has the same name as both a formal and a field, the formal will take precedence over a field. But, if the identifier has the same name as a field and an outer variable, it will be interpreted as referring to the field.
Future Work:
* seek to clarify other test cases mentioned in https://github.com/Cray/chapel-private/issues/5163
> Add a note to the spec about intepreting identifiers as fields

- doc/rst/language/spec/generics.rst
Follow-up to PR #23475 to correct a trivial error in the expected output.
> Adjust spec test expected output for minor difference

- modules/standard/CTypes.chpl
Simplify the documentation of `c_ptrTo`, `c_ptrToConst`, `c_addrOf`, and `c_addrOfConst` by documenting just the catch-all overload for each, hiding the fact they are implemented via numerous overloads taking specific argument types.
This includes the following changes:
- No-doc all overloads of these procedures except for the "catch-all" overload that takes any type, and some deprecated overloads so they still show up in docs during the deprecation period.
- Expand the documentation of the remaining documented `c_ptrTo` overload to describe all its special behavior cases, and refer users to `c_addrOf` for a non-special behavior version.
- Reorganize the order of the various definitions, to make the code a little easier to follow (imo) and to display deprecated overloads after the primary …
> Simplify documentation of `c_ptrTo` and related procedures' overloads

- doc/rst/platforms/cray.rst
The docs mentioned "pals support added in 1.24", which is true, but makes the content feel dated. Remove the section talking about version support and just add pals to the list of launchers. Also remove the note saying we haven't tested gasnet on EX, since that's no longer true.
Closes https://github.com/Cray/chapel-private/issues/5388
> Update dated comment about pals launcher in cray docs

- doc/rst/platforms/omnipath.rst
The experimental label was removed from gasnet-ofi in GASNet-EX 2022.9.0 (#21099), so no need to warn about it anymore.
> Remove warning about gasnet-ofi being experimental

- doc/rst/language/spec/error-handling.rst
- doc/rst/language/spec/statements.rst
- test/release/examples/primers/distributions.chpl
- test/release/examples/primers/replicated.chpl
This PR:
* Adds the rationale for the restrictions on the require statements, written by @bradcray.
* Adds an unstable warning to the Replicated Distribution primer. Refer to it as Replicated where appropriate.
* Adjusts the level of the headings in the Distribution primer.
*  This removes the primer's top-level sections from the Primers index page where they used to appear.
*  This adds the subsections "Reasoning About Ownership", "Creating an Aligned Domain", and "Specifying Target Locales" to the sidebar when viewing the primer.
* Removes the open issue about `return` statements following a `throw`, as that has been resolved in #23309.
Testing: built the docs and examined the modified areas.
> Minor doc touch-ups

- doc/rst/meta/modules/standard.rst
- modules/standard/AutoMath.chpl
- modules/standard/ChapelIO.chpl
- modules/standard/IO.chpl
- modules/standard/Math.chpl
Does a number of things (some of which were suggested by Brad):
- Hides the AutoMath name from the standard module index page
- Unifies how AutoMath and ChapelIO are displayed on the standard
module index page
- Rearranges the standard module index so that Errors and Types
come first, then the subsections of IO and Math symbols
- Rearranges AutoMath and Math's order in the Math/Numerical section
of the standard module index
- Moves the unstable warning for the module names AutoMath and ChapelIO higher
in their docs (by explicitly chosing where to include it)
- Insert a reference in Math back to AutoMath and its symbols
- Mentions in IO and Math that the automatically included symbols can also use
those module names for qualified access
Double checked that the built docs looked as expected …
> Improve documentation of AutoMath/Math and ChapelIO/IO pairs

- CMakeLists.txt
- doc/rst/conf.py
- doc/rst/language/archivedSpecs.rst
- doc/rst/usingchapel/QUICKSTART.rst
- doc/rst/usingchapel/chplenv.rst
- man/confchpl.rst
- man/confchpldoc.rst
- test/chpldoc/compflags/combinations/versionhelp-chpldoc.sh
- test/compflags/bradc/printstuff/versionhelp.sh
As part of the release process for 1.32 Release, remove pre-release.
> Remove Pre Release from chapel repo for 1.32 release

- modules/standard/CTypes.chpl
- modules/standard/CommDiagnostics.chpl
This PR either adds a nodoc to ``writeThis`` and ``serialize`` methods, or shifts documentation from ``writeThis`` to ``serialize``.
> Adjust documentation for some standard writeThis/serialize methods

- doc/rst/language/spec/iterators.rst
- doc/rst/language/spec/procedures.rst
- doc/rst/language/spec/tuples.rst
This add the definitions of the `out` return/yield intent to the spec:
* for procedures
* for iterators
* for tuples
Testing: build and examine the docs
> 'Out' return/yield intent in the spec

- modules/standard/IO.chpl
- modules/standard/JSON.chpl
This PR adds documentation to the serializer API methods in the JSON module, and documents the way that serializer type-kinds are translated to valid JSON.
> Document JSON module

- doc/rst/platforms/udp.rst
- doc/rst/usingchapel/launcher.rst
- doc/rst/usingchapel/multilocale.rst
Sometimes, users will get a complaint when using GASNet about SSH_SERVERS not being set, but our documentation doesn't mention SSH_SERVERS at all, just the preferred GASNET_SSH_SERVERS, so it can be hard for them to figure out what they need to do.  This takes the simple approach of mentioning SSH_SERVERS in our docs so that a search will find it at least, and hopefully understand that they can set either of these two variables.
> Update docs to mention SSH_SERVERS

- doc/rst/usingchapel/QUICKSTART.rst
This PR touches up some wording in the quickstart instructions to try and drive home the point that the quickstart configuration is not ideal for performance-oriented programmers.  Specifically, the old use of the term "stripped down" could be viewed as "no frills == fast" when in fact it was just meant to mean "less capable".  So try to clarify that here and provide users with an indication that if they want performance they should make sure they get to the preferred configuration.
> Clarify that "stripped-down" does not mean "fast" in QUICKSTART instructions

- test/release/examples/benchmarks/hpcc/ra-atomics.chpl
- test/release/examples/benchmarks/hpcc/ra.chpl
- test/release/examples/benchmarks/hpcc/variants/ra-cleanloop.chpl
- test/release/examples/benchmarks/hpcc/variants/ra-unordered-atomics.chpl
- test/release/examples/primers/arrays.chpl
- test/release/examples/primers/forallLoops.chpl
- test/release/examples/primers/forallLoops.good
- test/studies/hpcc/FFT/fft.chpl
- test/studies/hpcc/HPL/hpl.chpl
- test/studies/hpcc/RA/diten/ra.chpl
Adds comments about forall loops requiring ref intents. This does not add a comment at every place, just where the loop structure is called out.
Note that the "Task Intents Inside Record Methods" section in `test/release/examples/primers/forallLoops.chpl` needs to be updated, but that requires both a test code change and bug fix, which will happen post-release
> Add notes to 'release/examples' about ref intents

- doc/rst/language/evolution.rst
Adds a section about ref-maybe-const (also called ref-if-modified) to the language evolution document
[Reviewed by @bmcdonald3]
> Add ref-maybe-const changes to evolution.rst

- doc/rst/language/spec/conversions.rst
- doc/rst/language/spec/domains.rst
- doc/rst/language/spec/ranges.rst
- modules/internal/ChapelDomain.chpl
- modules/internal/ChapelRange.chpl
This PR makes the following changes, mostly in the language spec:
* Remove the difference between the definitions of "the range has ambiguous alignment" and "the range is ambiguously aligned".
* Add implicit conversions for ranges and updates explicit conversions for ranges and domains. 
* Remove several counter-productive where-clauses from online docs.
* Indicate that `domain` written by itself is generic.
TODO:
> Spec updates for ranges and domains

- doc/rst/language/spec/arrays.rst
- doc/rst/language/spec/domain-maps.rst
- doc/rst/language/spec/domains.rst
- doc/rst/language/spec/expressions.rst
- doc/rst/language/spec/iterators.rst
- doc/rst/language/spec/organization.rst
This PR makes the following changes to the language spec:
* Rename "domain map" to "distribution", based on a group discussion.
* Remove the `dmap` type, since we are moving away from it.
* Indicate that `dmapped` is unstable.
* Switch from "domain map class" to "distribution record".
* Switch from `Block` to `blockDist`.
* General text and link improvements.
> 'dmap', "domain map", and 'dmapped' updates in the spec

- doc/rst/meta/primers/index.rst
- test/release/examples/primers/loops.chpl
It turns out when a primer contains top-level section headers set off by `======` they appear on the primers table of contents page as well (?!), so this PR steps all headers in the loops primer down a level to fix this.  I apparently hadn't looked at the index in awhile.
While here, I moved the distributions and forall loops primers up in their section because I think they're more prominent now than some of the others, particularly due to the improved discussion of distributed arrays and domains, and the growing importance of task intents.
> Minor primer index adjustments

- CHANGES.md
These are the CHANGES for Chapel 1.32—thanks everyone for all the hard work!
Soo...many...changes...
Top-level CHANGES bullets per release:
1.27: 142
1.28: 158
1.29: 163
1.30: 207
1.31: 186
1.32: **379**
(not to say that "bullets" is the most reasonable unit of measure...)
> CHANGES.md for Chapel 1.32

- doc/rst/conf.py
- doc/util/versionButton.php
This is our normal update to the docs menu when we've staged a release but not yet made it available.
> Update docs menu to reflect staged release

- util/cron/common-hpe-cray-ex.bash
Loading PrgEnv/8.5.0 currently causes an error on pinoak.
> Load PrgEnv-gnu/8.4.0

- compiler/resolution/resolveFunction.cpp
- test/reductions/userdefined/bug21402.chpl
- test/reductions/userdefined/bug21402.good
Resolves #21402.
The internal error is due to the simple fact that we don't have an AST location marker when creating the copy temp. Adding the marker prevents the internal error, and we get a much more obvious error message from the case listed there.
> Add a missing `SET_LINENO` to resolve bug #21402.

- doc/rst/language/spec/lexical-structure.rst
- highlight/vim/syntax/chpl.vim
Adds the following missing keywords to the vim syntax highlighter.
- foreach
- super
- postinit
- deinit
- implements
- interface
- __primitive
- defer
Removes the following from the vim syntax highlighter
- enumerated
- delete (was listed twice)
Adds `void` to the keywords list in `lexical-structure`.
> Add missing keywords to vim syntax highlighter

- frontend/include/chpl/uast/uast-classes-list.h
Fixes the uast list to correctly list `TypeQuery` as a `NamedDecl`
Tested with full paratest.
> Fix uast list for TypeQuery

- util/cron/test-gpu-ex-cuda-11.bash
Adds an `export CHPL_CUDA_PATH` to avoid a module setup complication on the nightly testing system. I think it is likely that the system issue will be resolved soon, and we'll take this out.
> Explicitly set CHPL_CUDA_PATH in a nightly script as a workaround

- frontend/include/chpl/framework/ErrorWriter.h
- frontend/lib/framework/ErrorWriter.cpp
This aims to resolve https://github.com/chapel-lang/chapel/issues/21656.
Though I've read Brad's opinion on the various sketches, I am not inclined to put the filename on the same line as the previous error message. The reason for this is that it doesn't mesh well with the current approach we take (each piece of the error message is a distinct call that writes text to a stream). To be able to splice the file from code output back into the line before it, we'd need the code that prints the error message to be coupled with the code that prints the lines of Chapel. Furthermore, the approach is not resilient to non-standard phrasing of the message above (it modifies them grammatically!).
Thus, I've taken the approach of Rust error messages, and print the filename with an `-->` character. I …
> Print file path in detailed errors when jumping files

- util/devel/test/apptainer/tryit.py
- util/devel/test/vagrant/provision-scripts/chapel-update.sh
This PR takes two steps to improve nightly apptainer testing:
1. It checks for files before deleting them, so that a failure to `git clone` in one config does not stop the testing for all configs.
2. It adds a wait-and-retry loop to the `git clone` command.
Reviewed by @bhavanijayakumaran - thanks!
> Improve resilience of apptainer testing

- test/compflags/bradc/printstuff/version.goodstart
This PR removes an extra whitespace character accidentally inserted a file we use to generate a .good file to check the output when running `chpl --version`.
> remove extra whitespace in version.goodstart file

- compiler/codegen/codegen.cpp
- compiler/include/files.h
- compiler/main/driver.cpp
- compiler/util/files.cpp
Remove `intDirName` as it is completely redundant with `gContext->tmpDir()`.
Also remove some supporting code that is not needed, such as `ensureTmpDirExists` which is covered by the `Context`.
The similar `tmpdirname` variable is also unused and could likely be removed, but as that interacts with the gdb tmp-dir cleanup hook (see https://github.com/chapel-lang/chapel/issues/23554) it is not removed in this PR.
Resolves https://github.com/Cray/chapel-private/issues/5390.
Testing:
> Remove intDirName

- test/chpldoc/nested.doc.catfiles
- test/chpldoc/nested.doc.chpl
- test/chpldoc/nested.doc.good
- tools/chpldoc/chpldoc.cpp
This PR fixes the indentation of nested types in ``chpldoc``. Prior to this PR, if a nested type's documentation ended in a ``.. code-block::``, then the nested type's methods would be "absorbed" into that code-block:
For example, consider the following program:
```chpl
/*
Documentation for record R.
.. code-block:: text
a code block!
*/
record R {
var x : int;
/* Document 'foo' */
proc foo() {
}
/*
Documentation for ``Inner``
.. code-block:: text
This code-block should not overflow to 'innerMethod'!
*/
record Inner {
/* Inner Method. */
proc innerMethod() {
}
}
}
```
The ``rst`` chpldoc output for ``Inner`` would previously have indented the ".. method::" section under the code-block section:
```
.. record:: Inner
Documentation for ``Inner``
.. code-block:: text
This code-block should …
```
> Fix nested type indentation in chpldoc

- util/cron/test-driver.bash
Adds `util/cron/test-driver.bash` test script that runs our test suite with `--compiler-driver`.
Testing:
> Add `--compiler-driver` nightly test script

- util/build_configs/cray-internal/setenv-hpe-cray-ex-x86_64.bash
The previous change removed the pin, but a change is needed to the load_prgenv_cray function to not attempt to load a module and accept the default module.
> Fix the load scripts to use the default cce compiler

- modules/standard/IO.chpl
- test/deprecated/IO/fileLines.chpl
- test/deprecated/IO/fileLines.good
Remove `file.lines`, which was deprecated in: https://github.com/chapel-lang/chapel/pull/21260
> Remove deprecated `file.lines`

- modules/internal/ChapelBase.chpl
- modules/standard/CTypes.chpl
- test/deprecated/IO/cFileWithPtr.chpl
- test/deprecated/IO/cFileWithPtr.compopts
- test/deprecated/IO/cFileWithPtr.good
- test/extern/deitz/COMPOPTS
- test/interop/C/cFileType.compopts
- test/library/packages/Yaml/COMPOPTS
- test/library/standard/IO/initWithCFile/COMPOPTS
In https://github.com/chapel-lang/chapel/pull/22435, the `c_FILE` type was adjusted to represent a `FILE` rather than a `FILE*`, where the deprecated/new behavior could be selected by `cFileTypeHasPointer`.
This PR removes the deprecated behavior and deprecates the `cFileTypeHasPointer` flag. A `c_FILE` now represents a `FILE` without the pointer.
> Remove deprecated c_FILE pointer behavior

- modules/standard/IO.chpl
- test/deprecated/IO/advancePastByte.chpl
- test/deprecated/IO/advancePastByte.good
Remove `advancePastByte` which was deprecated in https://github.com/chapel-lang/chapel/pull/21703
> Remove deprecated `advancePastByte`

- test/release/examples/primers/cClient.skipif
- test/release/examples/primers/distributions.skipif
These are the only two tests in release/examples that currently fail for the GPU locale model when using `CHPL_GPU=cpu`. Skip them for now so we can run the CHPL_GPU=cpu testing configuration on the examples directory.
Closes https://github.com/Cray/chapel-private/issues/5447
> Add .skipifs for a couple tests if using the GPU locale model

- modules/dists/HashedDist.chpl
- modules/internal/DefaultAssociative.chpl
- modules/internal/DefaultRectangular.chpl
- modules/packages/ChplFormat.chpl
- modules/packages/LinkedLists.chpl
- modules/standard/ChapelIO.chpl
- modules/standard/IO.chpl
- modules/standard/JSON.chpl
- modules/standard/List.chpl
- modules/standard/Map.chpl
- modules/standard/Time.chpl
- test/library/draft/DistributedMap/v2/DistributedMap.chpl
The "_readLiteral" and "_writeLiteral" methods were created at a time when the "readLiteral" and "writeLiteral" methods were unstable, and could not be called from internal or standard modules. Now that the original methods are stable, we can remove these helpers.
Testing:
> Remove _readLiteral and _writeLiteral methods

- modules/standard/Math.chpl
Adds the newly added `fma` function to the list of Math functions at the top of the Math module.
Tested `test/library/standard/Math/docs` locally
> Add fma to Math docs index

- test/exercises/diffusion-1D/heat_1d_tasks.chpl
One of the tests introduced in https://github.com/chapel-lang/chapel/pull/23583 (`exercises/diffusion-1D/heat_1d_tasks.chpl`) was failing sporadically due to slight numerical inaccuracies. This PR adds a missing barrier to correct the issue.
> Fix sporadic failures with heat-1d example

- modules/internal/DefaultRectangular.chpl
- modules/standard/IO.chpl
- test/deprecated/IO/readbytes.chpl
- test/deprecated/IO/readbytes.good
- test/deprecated/IO/readstring.chpl
- test/deprecated/IO/readstring.good
- test/release/examples/benchmarks/shootout/regexdna-redux.chpl
- test/release/examples/benchmarks/shootout/regexdna-redux.good
- test/release/examples/benchmarks/shootout/regexdna-redux.perfkeys
- test/studies/shootout/submitted/Compat.chpl
Removes the `fileReader.readstring` and `fileReader.readbytes` methods deprecated in: https://github.com/chapel-lang/chapel/pull/21201.
Also replaces uses of the undocumented `_readbytes` helper with `readBinary`.
> Remove deprecated `readstring` and `readbytes` methods

- test/library/packages/Socket/COMPOPTS
Adds missing `libevent` `-rpath` linker argument to enable running Socket package tests on chapdl.
Resolves https://github.com/Cray/chapel-private/issues/5016.
Testing:
> Set `-Wl,-rpath` in Socket tests' COMPOPTS

- test/io/serializers/inflexible-types.bad
PR #23585 replaced the ``_readLiteral`` and ``_writeLiteral`` helper methods with calls to ``readLiteral`` and ``writeLiteral``. The non-underscore methods have nicer error message text that says "string literal" instead of "chpl_ioLiteral". This PR fixes a stray .bad file that checked the "chpl_ioLiteral" output.
> Fix error message with chpl_ioLiteral

- configure
- util/buildRelease/install.sh
In an effort to copy the behavior of autoconf (which is what users expect our configure script to do), we delay the creation of installation directories till the `make install` step instead of in the `./configure` script. 
We also don't normalize the path anymore since `autoconf` doesn't do it either based on.
Resolves https://github.com/chapel-lang/chapel/issues/23271
> Have make install rather than configure create the installation directory

- test/llvm/fma/FmaHardwareSpecialization.chpl
A new LLVM optimization test I added in #23572 failed when run with `--fast` because the LLVM compiler was statically optimizing away the call to the `fma()` intrinsic. This patch modifies the test to use `config const` as inputs to the `fma()` call so that it cannot be inlined away and the machine instruction persists.
> Use 'config const' to keep LLVM from statically optimizing FMA call

- test/ANNOTATIONS.yaml
- regressions from OOM full convert
- change in default benchmark size for Parquet IO benchmark
> Add annotations for October 5th

- util/test/genGraphs.py
The new `--addfile` flag allows the genGraphs user to drop a file into the `html` directory that contains the performance plots.
While there, I also deindented a block of code that was in `with open` block, seemingly unnecessarily.
> Add an --addfile flag to genGraphs

- util/cron/test-perf.chapcs.playground.bash
adds `unset CHPL_LLVM_CONFIG` to prevent the warning `Warning: CHPL_LLVM_CONFIG is ignored for CHPL_LLVM=bundled` in the perf playground
> Unset CHPL_LLVM_CONFIG to prevent warning in perf playground

- frontend/include/chpl/framework/ID.h
- frontend/include/chpl/framework/Location.h
- frontend/include/chpl/parsing/parsing-queries.h
- frontend/include/chpl/uast/Builder.h
- frontend/include/chpl/uast/BuilderResult.h
- frontend/include/chpl/uast/all-location-maps.h
- frontend/include/chpl/uast/location-map-macro.h
- frontend/lib/parsing/ParserContext.h
- frontend/lib/parsing/ParserContextImpl.h
- frontend/lib/parsing/bison-chpl-lib.cpp
- frontend/lib/parsing/bison-chpl-lib.h
- frontend/lib/parsing/chpl.ypp
- frontend/lib/parsing/parser-yyltype.h
- frontend/lib/parsing/parsing-queries.cpp
- frontend/lib/uast/Builder.cpp
- frontend/lib/uast/BuilderResult.cpp
- frontend/test/parsing/CMakeLists.txt
- frontend/test/parsing/testParseAdditionalLocations.cpp
- test/errors/scope-resolution/redefinition/function-and-record.2.good
- test/errors/scope-resolution/redefinition/function-and-var.2.good
- test/errors/scope-resolution/redefinition/parenless-and-parenful-fns.2.good
- test/trivial/diten/printvisibleOptFalse.good
This PR allows developers to associate more than one location with an AST node. The mechanism is built with macros in order to make it easy to add more locations as needed.
For example: when parsing a dot expression `x.foo`, an `Identifier` is created for `x` and a `Dot` is created for `x.foo` (with `x` as a child).
The location normally created for the `Dot` will span the entire text `x.foo`. However, it is impossible to tell precisely where `foo` is in `x.    foo`.
This PR adds support for associating the location of a "dot field" with a `Dot` AST by calling `Builder::noteDotFieldLocation`. As well, it adds support for pairing declaration names with `NamedDecl` using `Builder::noteDeclNameLocation`.
Additional locations can be added to "chpl/uast/all-location-maps.h".
This support is …
> [dyno] Add support for associating additional locations with AST

- util/packaging/docker/test/Dockerfile
- util/packaging/docker/test/brew_install.bash
Homebrew moved their CI to use Ubuntu 22.04 and added a flag to allow Linux testing to impersonate a Mac.
> Modify homebrew testing to use new CI settings

- compiler/codegen/cg-symbol.cpp
- compiler/codegen/codegen.cpp
- compiler/include/files.h
- compiler/llvm/clangUtil.cpp
- compiler/main/driver.cpp
- compiler/util/files.cpp
Refactors the many instances of ad-hoc saving to/restoring from tmp files on disk for driver mode to all use helper functions in `files.h`.
Previously the same logic was written slightly differently many times. The symbols needing save/restore, which now all go through the helpers, are: `incDirs`, `libDirs`, `libFiles`, `llvmPrintIrCNames`, `compileCommand`, `getMainModuleFilename`, `restoreAdditionalSourceFiles`. Note `incDirs`, `libDirs`, and `libFiles` were already being done in a uniform way through the functions that were adapted to become the helpers. Also, `loadModuleFromBitcode` is not included as it is a more complicated save/restore (of the entire LLVM Module) than the others which are just strings.
Follow up to https://github.com/chapel-lang/chapel/pull/21063.
Completes a …
> Refactor driver mode tmp file save/restore code to use a helper

- compiler/main/checks.cpp
- compiler/resolution/implementForallIntents.cpp
- test/unstable/ref-maybe-const-forall-intent.chpl
- test/unstable/ref-maybe-const-forall-intent.good
Resolves an issue were the ref-maybe-const unstable warning on foralls was over-eager and warning for incorrect cases. 
The warning was made extra eager in https://github.com/chapel-lang/chapel/pull/23518, but it is too eager and would warn for `B` incorrectly for something like
```
forall i in 1..10 with (ref A) do A[i] = B[i];
```
The fix to make this less eager caused the warning for foralls inside of record methods to no longer work, requiring a fix for that as well. While there, I improved the warning to tell users to use a ref intent for 'this'.
> Fix over-eager ref-maybe-const unstable warning

- compiler/codegen/cg-symbol.cpp
- compiler/llvm/clangUtil.cpp
- test/compflags/ferguson/print-asm-nonexistent.chpl
- test/compflags/ferguson/print-asm-nonexistent.compopts
- test/compflags/ferguson/print-asm-nonexistent.good
- test/compflags/ferguson/print-asm-nonexistent.skipif
- test/compflags/ferguson/print-asm.1.good
- test/compflags/ferguson/print-asm.2.good
- test/compflags/ferguson/print-asm.3.good
- test/compflags/ferguson/print-asm.compopts
- test/compflags/ferguson/print-asm.prediff
Add a warning for non-existent symbols requested to be disassembled with `--llvm-print-ir`.
Also removes the separate warning for when no symbols to disassemble are found, as it's covered by this new one. Includes testing for the case in which some but not all specified symbols are not found, as well as the case where no specified symbols are found.
Resolves https://github.com/Cray/chapel-private/issues/5387.
Contributes to a component of https://github.com/Cray/chapel-private/issues/5373.
Testing:
> Add warning for non-existent symbols to disassemble

- compiler/AST/AggregateType.cpp
- compiler/passes/convert-uast.cpp
- frontend/include/chpl/uast/AggregateDecl.h
- frontend/include/chpl/uast/Class.h
- frontend/include/chpl/uast/Record.h
- frontend/include/chpl/uast/Union.h
- frontend/lib/parsing/ParserContextImpl.h
- frontend/lib/uast/AggregateDecl.cpp
- frontend/lib/uast/Class.cpp
- frontend/lib/uast/Record.cpp
- frontend/lib/uast/Union.cpp
- frontend/lib/uast/chpl-syntax-printer.cpp
- test/constrained-generics/basic/withdecl/withdecl-union-notinterface.chpl
- test/constrained-generics/basic/withdecl/withdecl-union-notinterface.good
- test/constrained-generics/basic/withdecl/withdecl-union.chpl
- test/constrained-generics/basic/withdecl/withdecl-union.good
- tools/chpldoc/chpldoc.cpp
This turned out a lot simpler than I thought. All this does is:
* Lift the `inheritExprs` from `Class` to `AggregateDecl` (replacing `interfaceExprs` on `Record` with `inheritExprs` too, as a unified accessor). 
* Slightly tweak `Union` to allow it to accept a list of children and to set the `interfaceExprs` of the parent `AggregateDecl` class.
* Slightly tweak the parser to remove the "unions can't inherit" check and just give the union its inherit exprs.
Everything else seems to work as-is!
> Add support for the `: interface` syntax for unions.

- test/library/packages/URL/RunServer.chpl
- test/library/packages/URL/regionArgReader.chpl
- test/library/packages/URL/regionArgReader.good
- test/library/packages/URL/test.txt
Uses a local http server we set up ourselves locally instead of one hosted on
the web.  The server code was copied from the `test/library/packages/Curl`
directory, as was the .txt file
As a result of making this change, I had to change the starting location to look
at, since I wasn't sure how to make the file we're getting seekable (so we can't
start at anywhere other than the first point in the file).
Worked locally and on a fresh checkout with 200+ trials (though I haven't been
able to reproduce the timeout that has plagued nightly testing, so I can't
guarantee this will fix things)
> Change the regionArgReader test to be more reliable

- util/test/start_test.py
This updates our test scripts to not run local `sub_test` scripts when we're in `-performance` or `--gen-graphs` modes.  The motivations for this are that none of our current `sub_test` scripts are used for performance runs, so we're effectively doing bonus correctness runs while doing performance testing (or generating graphs) that are not necessary and may introduce failures that we don't care about / shouldn't be testing in those configuration to begin with.
I reviewed the existing `sub_test` scripts and didn't find any whose directories seemed to be involved in performance testing.  I'm also polling the performance team to make sure nobody's aware of any cases that are subtly disguised.
If, in some future, we want a way to run a custom `sub_test` for a performance run, we'll need to …
> Update test scripts to not run local 'sub_test' scripts for performance runs

- compiler/util/files.cpp
We intend to only save the list of additional source files to a tmp file when running in driver phase one. However, it is possible to add source files for compilation before the point driver flags are validated for consistency, meaning we could have the phase one flag specified for an actually monolithic compilation. Before this PR this leads to an assertion failure via calling a driver save-to-disk helper while actually in monolithic mode, instead of a correct error for conflicting flags. To fix this, check that we are not in a monolithic compilation before attempting to save added source files list.
Fixes nightly failure with `test/compflags/driver/monolithic/monolithic-subinvocation.chpl`.
Follow up to https://github.com/chapel-lang/chapel/pull/23606. …
> Skip saving added source files to driver tmp with inconsistent flags

- frontend/include/chpl/types/CPtrType.h
- frontend/lib/resolution/prims.cpp
- frontend/lib/types/CPtrType.cpp
- frontend/test/resolution/testClassPrimitives.cpp
I'm leaving alone `TO_LEADER` and `TO_FOLLOWER` because they seem to involve call wrangling to insert the iterator tag -- I don't know how to approach this right now, and hope that this isn't what's blocking the `writeln` efforts.
> Implement some more primitives from the 'cast' family.

- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/Resolver.h
- frontend/lib/resolution/resolution-queries.cpp
- frontend/test/resolution/testReturnTypes.cpp
This PR updates support for comparisons between type variables in dyno for both user-written comparisons and compiler-generated comparison resolution. With this change, ``Resolver::typeForTypeOperator`` is obsolete and can be removed. To be exact, this PR is updating the implementation for comparing two types, and not two values.
A new test is also added to ``testSelectTypes``, which captures a previously untested case that was unaffected by this PR. The artificial comparison operator in the test file itself can now be removed, though.
Testing:
> Update type comparison implementation in dyno

- test/exercises/Oct2023tutorial/03-heat-2D-block.chpl
- test/exercises/Oct2023tutorial/03-heat-2D-stencil.chpl
- test/exercises/Oct2023tutorial/03-heat-2D.chpl
Make domain naming consistent across 1D and 2D heat examples.
> Rename domains in heat-2D tutorial examples

- frontend/test/parsing/testParseAdditionalLocations.cpp
- frontend/test/resolution/testClassPrimitives.cpp
- frontend/test/resolution/testSubtypePrimitives.cpp
This PR just updates some dyno-tests that were making comparisons between `int` and `size_t` types, which caused a warning that gets promoted to an error on some systems (Ubuntu, for example).
It also addresses a warning about missing curly braces in an array initializer in one test.
[reviewed by @dlongnecke-cray]
> [tests] fix some dyno tests comparing int to size_t

- test/puzzles/deitz/histogram.chpl
Fixes race introduced in #23208. The previous code was `H[A] += 1;`, which was likely serialized and so we did not see the race. The previous PR used an explicit parallel construct with a `ref` intent and was not serialized, causing the race.
Replaced the `ref` intent with a reduce intent.
> Fix race in histogram test

- tools/chapel-py/method-tables.h
Fixes the inherit_expressions call for Records and Classes in the chapel-py bindings. By proxy, this also implements the call for unions.
This was broken by #23618, and trying to build the python bindings with the new version of the frontend library failed. 
> Fix inherit expressions in chapel-py

- compiler/optimizations/forallOptimizations.cpp
- test/optimizations/autoLocalAccess/use-before-def-bug.chpl
- test/optimizations/autoLocalAccess/use-before-def-bug.good
Adds new check `loopHasValidOptInfo` to prevent the compiler trying to optimize loops with semantic errors.
This resolves #23653, where the compiler would try to optimize the loop, but because the variable did not exist the optimization would fail. Sadly, this couldn't be handled by the existing use-before-def check because it occurs after the optimization.
Testing: paratest and paratest with gasnet
> Prevent auto local access from optimizing loops with semantic errors

- modules/internal/ChapelDomain.chpl
- modules/internal/ChapelRange.chpl
Unstabilize `range.strType` belatedly, as we have not approved it for the stable interface for ranges.
Remove from the spec the configs `noNegativeStrideWarnings`, `newSliceRule`, and `newRangeLiteralType` because they are purely implementation-specific.
Also remove from the spec the domain initializers because users are not supposed to write `new domain(....)`, and also the domain methods `this` and `these` because they are presented as slicing and as iteration over domains, respectively.
Add or adjust some comments.
Move the chpldoc for `domain.clear` to the overload without the where-clause. Previously the online docs for `domain.clear` showed a where-clause unnecessarily.
Change the chpldoc for `localSlice` to say "sub-domain" instead of "sub-array."
Add missing periods at the end of …
> Range+domain doc minor improvements

- doc/rst/technotes/gpu.rst
- modules/packages/Socket.chpl
Fix broken links.
I found the broken link in the `GPU` technote while browsing on the site, and I used a broken link detector for the two others (broken since 1.26.0). In addition, it detected some broken links in the Chapel website (ping @bradcray), e.g.:
- in https://chapel-lang.org/community.html: ... in real-time (also accessible via [IRC](https://irc.gitter.im/))
- in https://chapel-lang.org/whatsnew.html: April 16, 2020 - ...—[download](https://chapel-lang.org/downloads.html) your copy today!
- in https://chapel-lang.org/whatsnew.html: September 22, 2015 - Added talks from last week's [PGAS 2015](http://hpcl.seas.gwu.edu/pgas15/) conference to ...
- in https://chapel-lang.org/whatsnew.html: May 25, 2016 - ... from [Programming Models for Parallel …
> Fix broken links in `GPU` technote and `Socket` doc

- runtime/include/chpl-mem-desc.h
- runtime/src/gpu/amd/gpu-amd.c
- runtime/src/gpu/nvidia/gpu-nvidia.c
- test/gpu/native/diags.good
Fix of (relatively minor) memory leak in our runtime lib as described here (https://github.com/chapel-lang/chapel/issues/21689).
Along the way, since I saw this TODO comment:
`TODO: this should use chpl_mem_free`
I changed the free to use of `chpl_free` there to use `chpl_mem_Free` as well.  I'm not sure why this wasn't just done. I'm running things through paratests now, maybe I'll find out?
> Fix memory leak in gpu runtime

- compiler/AST/CallExpr.cpp
- compiler/AST/primitive.cpp
- compiler/passes/normalize.cpp
- compiler/resolution/cleanups.cpp
- compiler/resolution/functionResolution.cpp
- compiler/resolution/resolveFunction.cpp
- frontend/include/chpl/uast/prim-ops-list.h
- frontend/lib/resolution/prims.cpp
- test/deprecated/atomic/return-by-ref-array.compopts
- test/deprecated/atomic/return-by-ref-array.good
- test/deprecated/sync/return-by-ref-array.compopts
- test/deprecated/sync/return-by-ref-array.good
- test/variables/ref/errors-type-mismatch-1.chpl
- test/variables/ref/errors-type-mismatch-1.good
- test/variables/ref/errors-type-mismatch-2.chpl
- test/variables/ref/errors-type-mismatch-2.good
- test/variables/ref/type-decls-1.chpl
- test/variables/ref/type-decls-1.good
- test/variables/ref/type-decls-arrays-1.bad
- test/variables/ref/type-decls-arrays-1.chpl
- test/variables/ref/type-decls-arrays-1.future
- test/variables/ref/type-decls-arrays-1.good
- test/variables/ref/type-decls-arrays-2.bad
- test/variables/ref/type-decls-arrays-2.chpl
- test/variables/ref/type-decls-arrays-2.future
- test/variables/ref/type-decls-arrays-2.good
Given `ref r: t = rr;`, ensure that `t` is exactly the type of `rr`, see #8947.
When `rr` is an array or a domain, warn the user that there is no runtime checking that the runtime types of `t` and `rr` are identical. This PR adds a future requesting that such runtime types be identical, and another one requesting that they at least be equal.
When `t` is generic, the check requires that it be instantiatable with the type of `rr`.
When `t` and `rr` are classes and `r` is a `const` reference, we could potentiall allow `t` to be a superclass of `rr`. However this PR does not do this.
Implementation: I introduce `PRIM_INIT_REF_DECL` during normalization as an anchor for performing the type check during resolution. The first commit on this PR's branch performs the type check without introducing …
> Check the declared types of 'ref' variables

- doc/rst/usingchapel/executing.rst
- runtime/src/topo/hwloc/topo-hwloc.c
"Heterogeneous PU" could imply that the processing units on CPUs such as Intel's Alder Lake have different ISAs, which they do not. Intel uses the term "hybrid" so we should adopt that.
> Replaced "heterogenous PU" with "hybrid PU"

- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/Resolver.h
- frontend/lib/resolution/resolution-queries.cpp
- frontend/test/resolution/testMethodCalls.cpp
This PR fixes various bugs when trying to use a field or method in the signature of a method on the same type. The ``Resolver::createForInitialSignature`` method is updated to resolve a ``this`` formal in the case of methods, and used the resolved type as the Resolver's ``inCompositeType`` value.
Add ``Resolver::setCompositeType`` as a means of setting the Resolver's composite type once the ``this`` formal has been instantiated.
This PR also implements the logical-not operator, ``!``,  for param bools.
Testing:
> Dyno: Fix method scopes when using methods or fields in signatures

- tools/chapel-py/chplcheck.py
This PR adds a warning to the Chapel linter for "misleading indentation". Misleading indentation occurs when a non-curly-brace block is used in a for loop or if-else statement, but a line of code underneath is indented to the same extent. For example:
```Chapel
for i in 1..10 do
writeln("Hello, ");
writeln("World!");
```
The issue with the above code is that it _looks_ like both statements are a part of the loop; the user might have even intended that. However, the syntax of the `do` keyword is that only the statement following it is part of the block; thus, the code printing `World` is not run in a loop. Thus, the way the code _looks_ (and might be written in an indentation-sensitive language like Python) is not how it actually behaves.
```
➜  chapel git:(confusing-indentation) cat …
```
> Add a warning to chplcheck for confusing indentation

- test/gpu/native/llvmMoved.chpl
- test/gpu/native/llvmMoved.execopts
- test/gpu/native/llvmMoved.good
- third-party/llvm/README
Somewhat in response to comments on <https://github.com/chapel-lang/chapel/issues/22085>.
I think it would be good if we had some kind of alert whenever LLVM updates to ensure that we update GPU support in kind.  This test hard codes the version of LLVM we expect to use for our nightly tests and if we run it on a job with a newer LLVM it will fail.
The test includes a checklist of things to consider regarding GPU support and an LLVM update and gives instructions on how to update.
> Add llvmMoved GPU test

- test/gpu/native/diags.cpu.good
- test/gpu/native/diags.execopts
In a prior PR (https://github.com/chapel-lang/chapel/pull/22592) I, among other things, changed some allocations during kernel launch to use `chpl_mem_alloc` instead of `chpl_malloc`. The effect of this is these allocations are now being reported in our memory diagonstics log when previously they weren't. I updated the `.good` file associated with the `diags.chpl` to account for this but didn't account for the fact that these newly reported allocations won't happen when using cpu-as-device.
In this PR I add a new `.cpu.good` file for when we do cpu-as-device testing and update the `.execopts` file to be a script that will tell start_test to use this new good file when appropriate.
> Fix diags.chpl gpu test (add separate good file for cpu-as-device)

- frontend/include/chpl/framework/Context.h
- frontend/include/chpl/framework/UniqueString.h
- frontend/include/chpl/framework/serialize-functions.h
- frontend/lib/framework/CMakeLists.txt
- frontend/lib/framework/serialize-functions.cpp
- frontend/test/framework/CMakeLists.txt
- frontend/test/framework/testVarint.cpp
- runtime/include/qio/bswap.h
This PR adds implementation of and testing for a variable-length byte encoding (aka "variable byte encoding") for signed and unsigned integers. The implementation is based upon the existing variable-byte encoding in the runtime and matches the wire format used in Protocol Buffers (see https://protobuf.dev/programming-guides/encoding/#varints ).
In addition, this PR includes a few trivial improvements:
* a trivial comment correction in runtime/include/qio/bswap.h
* fixing the header guard name in frontend/include/chpl/framework/Context.h
* sorting the includes in frontend/include/chpl/framework/UniqueString.h
Future PRs will adjust the uAST serializes to use these new mechanisms.
> Add support for variable-length byte encoding for uAST serializers

- Makefile
- third-party/Makefile
- third-party/chpl-venv/Makefile
- tools/chapel-py/chplcheck
- tools/chapel-py/chplcheck.py
- util/config/run-in-venv-common.bash
- util/config/run-in-venv-with-python-bindings.bash
- util/config/run-in-venv.bash
This PR adds a new target to our Makefile which builds on top of the `test-venv` and adds support for installing the Python bindings into the Python Application directory structure. This should make it possible to run scripts like `chplcheck` "out of the box", the same way we can run `chpldoc` (which requires Python for sphinx). The overarching goal is to be able to ship Python-based tools with Chapel, allowing our users to make use of `chplcheck` with no additional setup. It would also be nice if we could run the Python-based tools in CI jobs.
Reviewed by @jabraham17 and @mppf -- thanks!
> Allow installing Python bindings into our Python Application

- frontend/lib/resolution/Resolver.cpp
The 'validateAndSetToId' function is meant to always wrap calls to 'setToId', providing additional checking to make sure that they're valid. There's one call in `Resolver.cpp` that invokes `setToId` without `validateAndSetToId`. This PR corrects the call.
> Route all setToId calls through validation

- frontend/lib/resolution/prims.cpp
- frontend/test/resolution/testParams.cpp
This PR adds an implementation for the primitive `string_length_bytes` for `param string` and `param bytes` arguments. It also adds a test to demonstrate correct behavior for `param this` intent with an `enum`. 
TESTING:
> implement prim string_length_bytes in dyno, add param tests

- compiler/include/driver.h
- compiler/include/files.h
- compiler/main/driver.cpp
- compiler/util/files.cpp
Fix two bugs relating to driver save/restore of command-line library and include info, which could cause an assertion failure in developer mode.
1. Library and include info can come from either the command-line or `require` statements. The driver needs to save and restore this info from disk, as phase two has no access to the AST including `require` statements. However, phase two does have access to the command-line, so by the restore point it can already have some library/include info, tripping an assertion that it has none. Solved by removing the assertion.
2. It was intended for phase one to also save info gathered from the command-line, but it was getting saved before the driver-specified tmp dir was set up, so it was thrown away. However, this info isn't needed anyways -- if it had …
> Fix driver compilation with command-line library info

- test/gpu/native/basics/outOfOnArr.chpl
- test/gpu/native/basics/outOfOnArr.good
This came up in a meeting where arrays that outlive the scope of an `on` statement was requested. Today, you can achieve that with some class-wrapping. This PR adds a test for that.
An earlier version of this pattern was written by @mppf. However, it was not working at that time. The issue was resolved by @DanilaFe in https://github.com/chapel-lang/chapel/pull/22373.
Test:
> Add a test showing for GPU arrays that are not bound to on lexical scope

- frontend/include/chpl/uast/Builder.h
- frontend/lib/uast/Builder.cpp
- frontend/lib/uast/BuilderResult.cpp
Historically, `uast::Builder` is a class that contains as fields all of the fields of `uast::BuilderResult`. However, that adds unnecessary maintenance burden. This PR adjusts `Builder` to store a `BuilderResult` as a field. It can update the same elements (even though they are private in `BuilderResult`) because `BuilderResult` declares `Builder` as a friend.
> Adjust Builder to store a BuilderResult instead of its fields

- compiler/main/driver.cpp
- man/chpl.rst
- test/compflags/bradc/help/userhelp.good
- util/chpl-completion.bash
> Make the `--detailed-errors` flag user-facing

- test/exercises/Oct2023tutorial/04-atomic-type.chpl
- test/exercises/Oct2023tutorial/parfilekmer.good
- test/exercises/Oct2023tutorial/parfilekmer.prediff
Fix a couple of sporadic failures on Oct23tutorial tests:
* Fix a sporadic failure in `exercises/Oct2023tutorial/parfilekmer.chpl` due to output order being non-deterministic. A prediff is added to sort the output.
* Fix a sporadic timeout in `exercises/Oct2023tutorial/04-atomic-type.chpl`. With the original implementation, task 1 reset the barrier before other tasks finished waiting causing them to wait indefinitely. (Also lowers the amount of time spent sleeping to speed up test.) The test is no longer timing out - testing with 1000 trials.
> Fix sporadic Oct23Tutorial failures

- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/call-init-deinit.cpp
- frontend/lib/resolution/can-pass.cpp
- frontend/lib/resolution/default-functions.cpp
- frontend/lib/resolution/return-type-inference.cpp
- frontend/test/resolution/testGenericDefaults.cpp
This PR fixes several cases of resolution bugs involving methods or method-like things called on generic-with-defaults types. The called type is instantiated, of course, but the receiver in a number of cases is often fully-generic. Prior to this PR the compiler was automatically resolving the types in such a way that used the defaults, rather than leaving the receiver as generic as possible.
As a bonus, this PR also fixes an issue in ``can-pass`` where a formal whose type was "generic-with-defaults" was considered concrete, when it should be considered generic for the purposes of instantiation and candidate selection.
Lastly, this PR fixes some bugs on generic-with-defaults types for compiler-generated copy initializers and deinit methods. The bugs involved these compiler-generated …
> Dyno: Fix resolution of methods on generic types with defaults

- frontend/include/chpl/resolution/can-pass.h
- frontend/include/chpl/resolution/resolution-types.h
Tests under GCC 5.4 failed because that version of GCC doesn't auto-specialize hash for enums, and I added two enums in my `canPass` PR (#23709). This PR adds the missing specializations. It also replaces a call to `hasValue` (which doesn't work in all compile-time configs since Chapel's optionals are either `std::optional` or `llvm::Optional`) with a cast to bool, which works with both.
> Add missing `hash` specialization for new enums and avoid using non-portable `hasValue` on `optional`.

- runtime/src/chpl-gpu.c
- test/gpu/native/basics/bug23658.chpl
- test/gpu/native/basics/bug23658.execopts
- test/gpu/native/basics/bug23658.good
- test/gpu/native/basics/bug23658.prediff
- test/gpu/native/nestedForeach.chpl
Resolves https://github.com/chapel-lang/chapel/issues/23658 and adds a test for it
Resolves https://github.com/chapel-lang/chapel/issues/20635 and updates the associated test
Resolves https://github.com/chapel-lang/chapel/issues/23095
This changes the behavior of GPU diagnostics as well to not register this as a kernel launch.
We also print a message informing the developer that a kernel was not launched when using `--debugGpu`.
Pending Nvidia and AMD testing for latest commit.
> Avoid kernel launch when number of threads is 0

- compiler/llvm/llvm-global-to-wide/CMakeLists.txt
- frontend/include/chpl/framework/serialize-functions.h
- frontend/lib/resolution/return-type-inference.cpp
- frontend/lib/resolution/return-type-inference.h
- frontend/lib/resolution/signature-checks.cpp
- frontend/lib/resolution/signature-checks.h
- frontend/lib/types/ExternType.cpp
- frontend/test/resolution/testDeprecationUnstable.cpp
- frontend/test/resolution/testModuleInitOrder.cpp
- frontend/test/resolution/testSuper.cpp
- util/test/checkCopyrights.bash
Improve the copyright checking script
* check `frontend/`
* check `CMakeLists.txt` files
* show the full command to add copyright when missing
* separately output files that need a copyright date update. Previously, the script misleadingly suggested adding a copyright to the listed files with `add_license_to_sources.py`, but that script does not update an existing copyright; it just adds a new one. Now, the script only makes this suggestion for files that do not appear to contain an old copyright.
Updates a few files that had old or missing copyrights.
> Improve the copyright checking script

- test/unstable-keyword/catchUnstableError.chpl
- test/unstable-keyword/catchUnstableError.compopts
- test/unstable-keyword/catchUnstableError.good
There was a point where deprecated Error subclasses would trigger their deprecation warning twice when caught.  That has since been resolved, but figured it would be good to also lock in that unstable warnings also behave appropriately
Checked a fresh checkout of the test
> Add a test locking in that catching unstable Errors only warns once

- modules/standard/GPU.chpl
- test/gpu/native/basics/blockSize-int32.chpl
- test/gpu/native/basics/blockSize-int32.good
- test/gpu/native/basics/intCoercion.chpl
- test/gpu/native/basics/intCoercion.good
The compiler primitive `setBlockSize` used was causing issues when the function was called with 32-bit integers. This PR drops the formal type and makes the function completely generic. Probably I should test making the type `integral` and merge that if it works.
Test:
> Drop explicit formal type in GPU.setBlockSize

- test/unstableAnonScript/scriptTest.prediff
grep doesn't support the `-P` flag in the nightly tests and was causing a failure in the unstable warning script test.
Using `-E` with `cut` instead
> Using a more portable flag with grep to fix nightly

- runtime/include/gdb.h
Fixes the macro check added in #23678 to be portable across gcc versions
This failed in our nightly testing with gcc version 8.3.1, complaining about `__has_builtin(...)`. A simple solution would have been to just put a space before '(', but I just rewrote the check based on gcc docs: https://gcc.gnu.org/onlinedocs/gcc-10.1.0/cpp/_005f_005fhas_005fbuiltin.html
> Improve macro check to be resilient to gcc versions

- doc/rst/tools/mason/guide/buildinglargerpackages.rst
This PR updates the docs for building large packages with mason to indicate that `--` is needed prior to compiler flags, such as `-M`. This is in response to a user reporting trouble on discourse with trying to use `mason build -M src/subdir/myfile.chpl`. 
TESTING:
[reviewed by @bmcdonald3 - thanks!]
> update mason large package docs to show use of `--` before `-M`

- modules/standard/IO.chpl
- test/io/corrado/buffering_optimization/optimization_flag.chpl
- test/io/corrado/buffering_optimization/optimization_flag.compopts
- test/io/corrado/buffering_optimization/optimization_flag.opt-off.good
- test/io/corrado/buffering_optimization/optimization_flag.opt-on.good
Recently, it was pointed out that there is no easy way to disable the IO optimization added in https://github.com/chapel-lang/chapel/pull/22031 and https://github.com/chapel-lang/chapel/pull/21786.
This PR adds a config param `IOSkipBufferingForLargeOps` that disables the optimization when set to `false`.
> Add flag to control IO dynamic buffering optimizaiton

- util/cron/create_release_tarball.bash
- util/cron/create_tarball.bash
Add sourcing of our nightly test dependencies (via `common.bash`) to `util/cron/create_[release_]tarball.bash` like we have for most of the scripts in that directory.
Part of [removing the need to load dependencies in the `chapelu` `.bashrc` on `chap*` systems](https://github.com/Cray/chapel-private/issues/5499#issuecomment-1789641313).
> Source nightly dependencies in tarball scripts

- modules/standard/BitOps.chpl
- test/deprecated/BitOps/popcount.chpl
- test/deprecated/BitOps/popcount.good
Remove previously deprecated `BitOps.popcount`, deprecated in 1.31 in this PR: https://github.com/chapel-lang/chapel/pull/22121
Tested with a full paratest using comm=none and comm=gasnet
> Remove previously deprecated BitOps.popcount

- test/studies/shootout/pidigits/thomasvandoren/pidigits-ledrug-BigInt.execopts
Fixes name of .good file changed in #23755
Tested locally
> Fix name of .good file in execopts for bigint test

- test/compflags/bradc/gdbddash/declint.prediff
Add a `-i` to a `grep` command in a test `.prediff` to make it case-insensitive.
It seems like in newer versions of `GDB` a loaded program without debuginfos will display "(No debugging symbols...)" instead of "no debugging symbols". The `grep` command in a test `.prediff` is not case-insensitive and so fails to filter out the warning from the newer `GDB`.
Reviewed by @bradcray. Thanks!
> Make 'grep' command in GDB test case-insensitive

- compiler/etc/gdb.commands
This adds a type cast to tmpdirname as a means of trying to make error messages go away when using the --gdb flag that complain that the type can't be determined, suggesting to apply a cast.  I got motivated to add it when a user ran into it today and I mistakenly thought it was the same thing that was breaking linux32 testing.
This change is a bit speculative because I haven't been able to reproduce the error, have just seen that it occurs in some configurations and that we have tests that try to grep the message away.  But I also don't think it's at all problematic.
> Add cast to tmpdirname in compiler/gdb.commands

- util/cron/common-hpe-cray-ex.bash
The Cray EX we run some of our nightlies on has a problematic `cray-libsci` installation. We don't need it but it comes with the PrgEnv. This PR unloads `cray-libsci` explicitly to avoid issues with it.
> Unload cray-libsci on a system that has problems with it

- modules/standard/BigInteger.chpl
- modules/standard/CTypes.chpl
- modules/standard/Errors.chpl
- modules/standard/IO.chpl
- modules/standard/List.chpl
- modules/standard/Map.chpl
- modules/standard/OS.chpl
- modules/standard/Regex.chpl
- modules/standard/Subprocess.chpl
- modules/standard/Time.chpl
- modules/standard/Version.chpl
Adds documentation based on warnings from `$CHPL_HOME/tools/chpldoc/findUndocumentedSymbols $CHPL_HOME/modules/standard/ --ignore-deprecated --ignore-unstable`. After this PR, this command should return clean except for one `init` in `Regex`.
Summary of changes
- fix inline rst in `OS`
- hide internal `Subprocess.spwanshellHelper` method from docs
- add docs to `List`, `BigInteger`, `Map`, `Version`, `Regex`, and CTypes
- cleanup docs in `IO`
- nodoc overridden `init` and `message` procs in `Error` subclasses since these don't really add to the docs
- add POSIX docs
Tested locally by building docs and checking the formatting after each commit.
> Add missing documentation for standard modules

- util/cron/common-native-gpu-perf.bash
- util/cron/test-perf.gpu-cuda.bash
- util/cron/test-perf.gpu-cuda.um.bash
- util/cron/test-perf.gpu-rocm.bash
Part of https://github.com/Cray/chapel-private/issues/5399
Recently, I have broken GPU performance plots while fiddling with array_on_device testing. Currently, we run performance testing, but data goes to the wrong place and end up being not plotted, whereas our plots are missing that recent data.
This PR will not fix the problem, but will adjust names of configs so that there's a better structure in the generated dat files. I'll manually splice data when the new directories are online.
The structure I am hoping to achieve with this PR is
```
| gpu
|-- 1-node-p100
|---- aod
|---- um
|-- 1-node-mi60
```
> Rename some GPU pref test configs and descriptions

- test/compflags/driver/debugger/declint.prediff
This adjusts a second prediff, as in #23769, to handle the outstanding linux32 regression.
> Make grep case-insensitive as in #23769

- test/studies/shootout/submitted/knucleotide4.good
- test/studies/shootout/submitted/knucleotide4.prediff
Fixes `test/studies/shootout/submitted/knucleotide4.chpl`, which was failing after https://github.com/chapel-lang/chapel/pull/23672 changed the line numbers. This PR uses a prediff to resolve that error and future proof the test
Tested locally
> Fix failing test from line changes in Map

- util/cron/common-hpe-cray-ex.bash
We are seeing some failures while building the bundled LLVM with GCC 10 and 11 on our nightly EX testing system. This PR adjusts those configs to use GCC 12.
> Load a newer GCC in EX testing to avoid LLVM build issues

- runtime/src/comm/gasnet/comm-gasnet-ex.c
Convert non-strided RMA calls overs to GEX API. This is mostly a direct transliteration (`gasnet_{put,get}` -> `gex_RMA_{Put,Get}Blocking` and `gasnet_{put,get}_nb_bulk` -> `gex_RMA_{Put,Get}NB`), but there are some mildly interesting changes in how we wait for NB ops.
Specifically, this highlighted that `chpl_comm_test_nb_complete` doesn't check if a NB op is complete, but checks if was performed as a blocking operation. I'm not sure that's intended, so I added a TODO to revisit it. Additionally, some of the new GEX functions don't do AM polling. I think this is preferable since we have a dedicated polling thread so there's a TODO to explore eliminating more internal polling.
Testing:
Part of #14443
> Convert gasnet-ex shim in-segment contiguous get/put over to GEX API

- runtime/src/gpu/cpu/gpu-cpu.c
I updated the reduction interface in the runtime a little late in the PR process and forgot to update the cpu-as-device implementation for it. This PR adjusts that.
> Fix the runtime reduction interface for cpu-as-device

- compiler/AST/ForLoop.cpp
- compiler/AST/ForallStmt.cpp
- compiler/AST/LoopExpr.cpp
- compiler/AST/symbol.cpp
- compiler/include/ForLoop.h
- compiler/include/ForallStmt.h
- compiler/include/LoopWithShadowVarsInterface.h
- compiler/include/baseAST.h
- compiler/include/driver.h
- compiler/include/resolution.h
- compiler/main/driver.cpp
- compiler/passes/cleanup.cpp
- compiler/passes/convert-uast.cpp
- compiler/passes/scopeResolve.cpp
- compiler/resolution/functionResolution.cpp
- compiler/resolution/implementForallIntents.cpp
- test/domains/compilerErrors/constDomain11.good
- test/domains/compilerErrors/constDomain3.good
- test/domains/compilerErrors/constDomain8.good
- test/functions/ferguson/ref-pair/array-tasks-const1.good
- test/parallel/forall/checks/forall-inout-domain-bug-16301.good
- test/parallel/forall/vass/other/const-errors-due-to-intents.good
- test/release/examples/users-guide/datapar/promotion.error2.good
- test/statements/foreach/COMPOPTS
- test/statements/foreach/constIntent.chpl
- test/statements/foreach/constIntent.good
- test/statements/foreach/refIntent.chpl
- test/statements/foreach/refIntent.good
- util/chpl-completion.bash
This PR begins work on enabling intents on `foreach` loops.  Specifically, it changes things so that this example now properly errors out (saying you can't assign to the constant 'c'):
```chpl
var c = 42; 
foreach i in 0..0 with (const c) do c = 1;
```
While ensuring that an example that doesn't modify 'c' still works fine. It also allows `ref` intents syntactically, so this will work:
```chpl
foreach i in 0..0 with (ref x) do x = 52;
```
Although at this point the `ref` intent itself won't change any existing behavior (so for example if this loop is gpuized and run on the gpu it will keep the existing behavior where `x` is passed to the kernel by-value effectively treating like an `in` intent).
Anyway, this is all a work in progress but I would like to get code merged early and often as …
> Foreach intents first steps

- test/studies/champs/functions.bash
- test/studies/champs/sub_test
- util/cron/common-champs.bash
This PR adds a mode to our CHAMPS testing infrastructure to be able to compile CHAMPS locally.
- This mode is enabled by `export CHAMPS_QUICKSTART=1`
- With that, the custom `sub_test` will skip over some steps, but most importantly will use `CHPL_STOP_AFTER_PASS=denormalize` as starting with `codegen` we'll need dependencies.
- The rest of the build/triage should be pretty similar to how CHAMPS is triaged normally on DC machines.
- By default, only `icing` is built. `export CHAMPS_COMPILE_ALL_EXECS=1` will make `sub_test` build all the executables.
Note: with this mode issues with codegen/linkage/correctness will not be captured.
I (and some others in the recent past) tested the branch locally.
> Add quickstart compilation mode for CHAMPS

- tools/chapel-py/src/chapel/replace/__init__.py
- tools/chapel-py/src/method-tables.h
Fixes typos in `method-tables.h` and `replace.py`
> Fix typos in chapel-py

- tools/chplcheck/src/rules.py
Running `./tools/chapel-py/runChplcheck` on the following problem used trigger an assert in the frontend library.
```chapel
for i in 1..10 do
writeln("hello");
// misleading
foo();
```
This is because you cannot get the location of a Comment. This PR sidesteps the issue by skipping over comments in the relevant rule.
[Reveiwed by @DanilaFe]
> Fix `MisleadingIndentation` in chplcheck for comments

- compiler/include/driver.h
- compiler/passes/convert-uast.cpp
- test/errors/parsing/COMPOPTS
- test/errors/scope-resolution/COMPOPTS
- test/errors/scope-resolution/redefinition/COMPOPTS
This PR updates ``--dyno`` to trigger type resolution in the frontend during ``convert-uast``. This change is primarily for the benefit of developers working on the frontend so that we can start fully resolving programs with both the frontend and production compiler.
Testing:
> Start using --dyno to trigger type resolution

- tools/chplcheck/src/chplcheck.py
- tools/chplcheck/src/driver.py
- tools/chplcheck/src/rules.py
Improves how we specify that a given `chplcheck` rule is default or not, by enabling a non-required argument on the decorator.
Tested locally
> Improve chplcheck rule default specification

- frontend/include/chpl/util/assertions.h
- frontend/lib/resolution/call-init-deinit.cpp
- frontend/lib/resolution/can-pass.cpp
- frontend/lib/resolution/default-functions.cpp
- frontend/lib/resolution/disambiguation.cpp
- frontend/lib/resolution/prims.cpp
- frontend/lib/resolution/resolution-queries.cpp
- frontend/lib/resolution/resolution-types.cpp
- frontend/lib/util/assertions.cpp
This PR introduces an alternative to the frontend's usage of ``CHPL_ASSERT`` to indicate unimplemented parts of resolution. These assertions can hinder the progress of resolution by stopping earlier than is strictly required. The frontend is intended to be resilient against resolution failures, so generally speaking resolving something as an "unknown type" should be fine.
Instead of using ``CHPL_ASSERT``, we can now use ``CHPL_UNIMPL``. ``CHPL_UNIMPL`` prints a message provided by the caller. Developers wishing to break on these calls can do so using the ``chpl_unimpl`` helper function. Eventually I expect this macro to go away once the frontend becomes sufficiently capable of performing full type resolution.
> Dyno: Introduce and use CHPL_UNIMPL instead of halting assertions

- frontend/lib/parsing/bison-chpl-lib.cpp
- frontend/lib/parsing/chpl.ypp
- frontend/lib/parsing/flex-chpl-lib.cpp
- frontend/lib/parsing/flex-chpl-lib.h
Fixes an issue with the locations reported by Chapel for an `extern record` being different than a `record`.
For example, the location for this record includes everything from `record` to the closing curly brace.
```chapel
record foo {
var x: int;
var y: int;
}
```
The location for this record was only for `extern`, now it is everything from `extern` to the closing curly brace.
```chapel
extern record bar {
var x: int;
var y: int;
}
```
- local testing with `chplcheck` to view locations
- paratest with comm=none
- paratest with comm=gasnet
> Fix `extern record` locations to be consistent with `records`

- frontend/include/chpl/resolution/resolution-types.h
- frontend/include/chpl/types/Type.h
- frontend/lib/parsing/parsing-queries.cpp
- frontend/lib/resolution/InitResolver.cpp
- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/call-init-deinit.cpp
- frontend/lib/resolution/copy-elision.cpp
- frontend/lib/resolution/prims.cpp
- frontend/lib/resolution/resolution-queries.cpp
- frontend/lib/resolution/resolution-types.cpp
- frontend/lib/resolution/return-type-inference.cpp
- frontend/lib/types/Type.cpp
This PR fixes a variety of type resolution errors in the interest of unblocking progress towards resolving "hello world":
- introduces the ``locale`` type in the frontend
- works around some deprecation issues with the ``kind`` field in fileReader/Writer
- avoids some issues when resolving the return type of extern procs
- adds some basic support for atomic type construction (though this is still blocked by an issue with ChplConfig)
- implements PRIM_GET_COMPILER_VAR
Testing:
> Dyno: Miscellaneous fixes to simple resolution errors

- frontend/include/chpl/framework/Location.h
- tools/chpldef/compute-goto-declaration.cpp
- tools/chpldef/protocol-types.cpp
- tools/chpldef/protocol-types.h
- tools/chpldef/test/TestClient.cpp
- tools/chpldef/test/TestClient.h
- tools/chpldef/test/test-declaration.cpp
Improve the accuracy of the `Declaration` message by fixing bugs, and allow it to connect more symbols to their definitions such as dot fields or the operands of binary expressions.
> [LSP] Improve the accuracy and coverage of the 'Declaration' message

- frontend/lib/resolution/default-functions.cpp
- frontend/lib/resolution/resolution-queries.cpp
- frontend/lib/resolution/return-type-inference.cpp
- frontend/test/resolution/testOperatorOverloads.cpp
This PR adds compiler generated signatures for record assignment and record comparison to dyno. 
If we detect a matching operator already defined, we will skip generating the signature. 
Adds some minimal testing for generating signatures of `==` and `=` with and without `R.==` or `==` defined.
[reviewed by @mppf - thank you!]
> [dyno] implement compiler generated record comparison and assignment

- compiler/include/files.h
- compiler/main/driver.cpp
- compiler/util/files.cpp
- frontend/include/chpl/util/chplenv.h
- frontend/lib/util/chplenv.cpp
Save the output of calling `printchplenv` in the driver initial invocation and restore it in sub-invocations, to avoid redundant work.
On my machine this reduces the compilation time in driver mode by about 0.5s, bringing it almost on par with monolithic.
This is one component of https://github.com/Cray/chapel-private/issues/5373.
Testing:
> Avoid re-calculating `printchplenv` output in driver mode

- compiler/main/driver.cpp
Prevent generating extraneous warnings about unused `--driver-debug-phase`, some of which were incorrect.
This warning message is intended to be displayed only for an initial invocation of the driver with an unused --driver-debug-phase flag. Previously it was also emitted by sub-invocations, even if the sub-invocation is inside the debugger (meaning the user didn't specify anything incorrect).
Testing:
> Prevent driver debug phase warning in sub-invocations

- frontend/lib/resolution/disambiguation.cpp
This PR implements the `discardWorsePromoting` function in Dyno resolution. This PR is part 4 of a series of PRs that implement changes already in production from https://github.com/chapel-lang/chapel/pull/20528.
> [dyno] implement discardWorsePromoting disambiguation stub

- frontend/lib/resolution/disambiguation.cpp
This PR implements the `discardWorseWhereClauses` function for Dyno disambiguation. This PR is part 6 of a series of PRs that implement disambiguation changes already in production from https://github.com/chapel-lang/chapel/pull/20528.
> [dyno] implement discardWorseWhereClauses disambiguation stub

- frontend/lib/resolution/disambiguation.cpp
This PR implements the `discardWorseArgs` function for Dyno disambiguation. This PR is part 7 of a series of PRs that implement disambiguation changes already in production from https://github.com/chapel-lang/chapel/pull/20528.
Also implemented in this PR are several supporting helper functions for `discardWorseArgs`.
There is future work to implement rules ignoring the differences between ref and value tuples.
> [dyno] implement discardWorseArgs disambiguation stub

- runtime/src/qio/regex/bundled/re2-interface.cc
Fixes a regex build failure that showed up in nightly testing with uninitialized fields
> Fix regex build failure with `-Wmaybe-uninitialized`

- test/chplcheck/MethodsAfterFields.chpl
- test/chplcheck/MethodsAfterFields.good
- test/chplcheck/PREDIFF
- test/chplcheck/SKIPIF
- tools/chplcheck/src/rules.py
This redoes yesterday's reverted changes with the fix to the SKIPIF. Flattening the directory structure ensures the SKIPIF applies to the test. Now, all the test files are present in the chplcheck directory and the prediff file is generalized to be used for future tests.
> Linter rule enforcing methods come after all fields

- Makefile
- compiler/Makefile
- frontend/lib/CMakeLists.txt
- tools/chapel-py/setup.py
- tools/chapel-py/src/chapel.cpp
- tools/chapel-py/src/core-types-pernode.cpp
- tools/chapel-py/src/core-types.cpp
- tools/chapel-py/src/core-types.h
- tools/chapel-py/src/error-tracker.cpp
- tools/chapel-py/src/error-tracker.h
- tools/chapel-py/src/iterator-support.cpp
- tools/chapel-py/src/iterator-support.h
This includes three separate fixes:
* Fixing the string processing in `setup.py` to split on multiple whitespace characters (`a   b => [a, b]`) and to ignore `*` for "variable changed" modifiers from `chplenv`.
* Removing designated initializers `{ .tp_xyz = ... }` because they are not supported by older GCCs. I've replaced these with a global function that updates the object's non-default fields. This does introduce an extra call to `setupPythonObjectX` for each python type `X` we provide, but it seemed like a pretty small price to pay for more portability. Designated initializers may or may not be a C++20 extension.
* Adds an always-on `ChplFrontendShared` library that is _always_ built as a shared object (as opposed to a `ChplFrontend`, which is sometimes built as a static library …
> Get `chapel-py` building on chapdl

- runtime/include/qio/qio.h
- runtime/src/qio/qio.c
- test/io/corrado/buffering_optimization/growing_buff_read_write.chpl
Fixes a bug in the IO runtime where a `fileReader` could read from the incorrect file offset when the runtime transitioned from buffered reading to non-buffered reading.
The bug was somewhat unlikely to come up in practice, as the total size of the buffered reads needed to add up to exactly the size of one qio buffer chunk (2**16 bytes).
Resolves: https://github.com/chapel-lang/chapel/issues/23800
> Bug fix in QIO buffering optimization

- tools/chapel-py/src/core-types-pernode.cpp
This was a silly bug in which we (I) clobbered the variable whose `toId` being searched for while finding its parent.
> Fix bug in finding toId in Chapel Python bindings

- compiler/resolution/preFold.cpp
This PR fixes a compilation error when using the `UnitTest` package with certain code structures and resolves https://github.com/Cray/chapel-private/issues/2300.
The issue stems from reading through `gFnSymbols` and assuming that each function that throws would have a module associated. In the case that a symbol has been pruned from the ast, it will not have a module, the compiler would try to read the empty `mod` variable and crash. 
[reviewed by @dlongnecke-cray - thanks!]
TESTING:
```
[Error matching program output for chplenv/chplconfig/warnings/warnings]
```
(same C-backend failure on main)
> ignore pruned functions in PRIM_GATHER_TESTS

- runtime/src/comm/gasnet/comm-gasnet-ex.c
Convert strided RMA calls over to GEX API. The strided APIs were made a little more general in GEX, so adapt to the changes here. Specifically, `count[0]` is no longer special and was moved out into a separate `elemsz` variable so `count` is now of `stridelevels` size  instead of `stridelevels+1`.
Our strided interface was at least partially based on the gasnet-1 interface, so I think it could be worth revisiting the interface to see if it could be simplified now.
Note that during review we discovered a bug where we were using 0 length VLAs for `stridelevels == 0` (contiguous transfers). 0-size VLAs are undefined-behavior, so fix that here by ensuring the arrays are always at least of size 1 (they will be ignored by gasnet for stridelevels==0). I suspect in practice this didn't matter …
> Convert gasnet-ex shim strided get/put over to GEX API

- compiler/llvm/clangUtil.cpp
Conditionally replace the call to `CompilerInstance::createTarget()` added in https://github.com/chapel-lang/chapel/pull/23795 with the equivalent code for Clang 11/12.
Determined the correct code by inspecting Clang 12 source code and seeing this is what `ExecuteAction` calls instead of the not-yet-existent `createTarget()` function.
Follow up to https://github.com/chapel-lang/chapel/pull/23795.
Testing:
> Replace CompilerInstance::createTarget() for old LLVMs

- test/regex/defaultInitializer.no-local.good
Add `no-local.good` file for regex test which has different behavior with and without comm
Address an issue with nightly testing
Tested locally with `comm=none`, `comm=gasnet`, and `--no-local`
[not reviewed - trivial]
> Add no-local.good file for regex test

- compiler/AST/AstDump.cpp
- compiler/include/log.h
- compiler/main/driver.cpp
- compiler/main/log.cpp
- util/chpl-completion.bash
Often times I want to use `--log` to get pretty prints of the AST after each pass but I want it in the same format used by `nprint_view` which I use when debugging.
This PR adds a new developer-oriented flag `--log-fmt <format>` where (for now) format can either be `default` or `nprint`. If left off, as one would expect, it defaults to `default` and we print logs the same as we always have.
In terms of implementation, to get this to work I ended up redirecting `stdout` to the log file we're generating.  This comment I added kind of explains it:
```C++
// This is an absolute hack. nprint_view prints directly to stdout, we should
// update it to take a file pointer use it and pass it along as needed. But rather
// than update all the code I instead redirect stdout to the file (and then …
```
> add support for --log-fmt=nprint

- compiler/passes/convert-uast.cpp
- frontend/lib/framework/Context.cpp
- test/modules/errors/duplicateModules.chpl
- test/modules/errors/duplicateModules.compopts
- test/modules/errors/duplicateModules.good
- test/modules/errors/duplicateModules2.chpl
- test/modules/errors/duplicateModules2.compopts
- test/modules/errors/duplicateModules2.good
This adds an error message when two files define the same module name, replacing an assertion / internal error as reported in #23775 (though that only occurred for a compiler built with NDEBUG left unset).  It also adds new tests of this error.
The approach I took here was to essentially move the assertion that used to take place into code that's always executed and to replace it with a user-facing error message when it fails.  That said, I also squashed the error for bundled modules (as defined by the Dyno front-end) because failing to do so caused tests in which the user re-used module names to fail, like `test/modules/bradc/overrideStd/foo.chpl` and `test/modules/bradc/userInsteadOfStandard/foo2.chpl`.
While here, I also "fixed" the indentation of the code (making the diff look worse …
> Add user-facing error when multiple files define the same module

- compiler/main/driver.cpp
- doc/rst/developer/bestPractices/GeneratedCode.rst
- doc/rst/usingchapel/building.rst
- test/compflags/testPgWithLlvm.chpl
- test/compflags/testPgWithLlvm.compopts
- test/compflags/testPgWithLlvm.good
- test/compflags/testPgWithLlvm.skipif
Based on user interactions this week, this refreshes some documentation w.r.t. profiling and also adds a warning to the compiler if trying to use the `-pg` flag with the LLVM back-end to indicate that it is not supported.  Specifically it:
* adds a warning to the compiler when the target compiler is LLVM and ccflags or ldflags contains the string `-pg`
* adds a test for this warning
* adds a caveat to the documentation about profiling generated code using `gprof` not being supported by the LLVM back-end
* adds an indication that other performance analysis tools may be used with Chapel without providing instructions
* refreshes the profiling-related text now that this developer-oriented document is available on the web docs and readily findable by searching.  Specifically, it:
* fixed …
> Cleanups to docs and compiler w.r.t. `-pg` and particularly the LLVM back-end

- compiler/passes/normalize.cpp
- test/functions/NestedFunctionBug.chpl
Resolves #23560.
Fix an internal error by skipping functions that are no longer in the tree during normalize.
There are times during normalize where a function may be cloned and then removed from the tree. If this happens then any nested functions are also effectively cloned and pruned as well. Add a simple check that skips a function in normalize if it is no longer in the tree.
TESTING
> Skip over functions that may no longer be in tree during normalize

- compiler/AST/symbol.cpp
- compiler/resolution/resolveFunction.cpp
- modules/standard/IO.chpl
- test/classes/delete-free/shared/coerce-owned-to-shared.good
- test/classes/errors/nilability-init-field-dflt/init-field-dflt-nonnil-shared-from-nonnil-owned.good
- test/classes/errors/nilability-init-field-dflt/init-field-dflt-nonnil-shared-from-oknil-owned.good
- test/classes/errors/nilability-init-field-dflt/init-field-dflt-oknil-shared-from-nonnil-owned.good
- test/classes/errors/nilability-init-field-dflt/init-field-dflt-oknil-shared-from-oknil-owned.good
- test/deprecated-keyword/warn-in-init.chpl
- test/deprecated-keyword/warn-in-init.future
- test/deprecated-keyword/warn-in-init.good
- test/deprecated/CyclicTest.comm-none.good
- test/deprecated/CyclicTest.good
- test/deprecated/rangeStridable.good
- test/distributions/block/redistBlock.comm-none.good
- test/distributions/block/redistBlock.good
Adds calls to `maybeGenerate[Deprecation|Unstable]Warning` in `resolveFunction` to catch more cases of deprecated functions not being warned for. This is a relatively lazy fix in that it is prone to generate duplicate warnings, so dedup code has been added to `maybeGenerate[Deprecation|Unstable]Warning`.
This resolves #23787, where some resolved functions would not warn. It handles the initializer problem by adding an exception for `"default actual functions"` for what is considered 'compiler-generated' code, since the user wrote it and is able to change and get rid of the deprecation warning.
This PR takes the approach that multiple warnings is better than no warning at all, which requires updates to a few test's .good files
- test/deprecated/rangeStridable
- …
> Add extra warnings for resolved functions

- frontend/include/chpl/libraries/LibraryFile.h
- frontend/include/chpl/libraries/LibraryFileWriter.h
Follow-up to PR #23862 to fix a `clang` error/warning when building with `clang` on Mac OS X about mixing `struct` and `class` in forward declarations. Also removes an unused forward declaration.
> Fix forward declaration in LibraryFileWriter.h

- compiler/resolution/functionResolution.cpp
- test/classes/casts/GenericDowncast.1.good
- test/classes/casts/GenericDowncast.2.good
- test/classes/casts/GenericDowncast.3.good
Fix bugs in #23799 that were breaking Arkouda.
The "downcast to generic subclass" error message I added was firing even when the target type `T` was generic with defaults. Adjust the code to skip emitting the error in that case. While here, fix a silly mistake with the error message wording. We're downcasting to a _subclass_ not a superclass.
TESTING
> Fix bugs with generic class downcast error message

- test/compflags/testPgWithLlvm.skipif
Something about the configurations that use `--ldflags -pg` leads to a segfault in valgrind testing.  Since this test isn't about valgrind or support for profiling with valgrind, I'm just skipping it in valgrind mode.  I considered suppressing it, but only two of the five configurations fail (the two that use `--ldflags`), and I don't think it's worth the effort to break into two tests or the time spent testing under valgrind at this point.  If/when we support profiling as more of a first-class feature, we can revisit this.
> Skip new "warn about -pg with LLVM" test for valgrind runs

- Makefile
- third-party/Makefile
- third-party/chpl-venv/Makefile
- tools/chplcheck/Makefile
- util/config/run-in-venv-common.bash
- util/config/run-in-venv.bash
This PR adds a `chplcheck` target to our Makefile, which serves to build the Chapel Python bindings if necessary, as well as to install `chplcheck` into `bin`, making it accessible without specifying the path to the `tools` directory. While there, this PR also cleans up some of the Makefiles, slightly untangling the dependencies between the various `third-party/chpl-venv` targets and `chapel-py` (changing the `run-in-venv-*` scripts in the process).
> Add a Makefile target for `chplcheck` and install it to `bin` for in-source builds.

- test/io/corrado/buffering_optimization/growing_buff_read_write.chpl
https://github.com/chapel-lang/chapel/pull/23805 fixed a bug in the IO runtime related to the non-buffered read optimization.
This PR updates a test related to the optimization to ensure that a bug of a similar nature isn't introduced in the future (per the recommendation in [this comment](https://github.com/chapel-lang/chapel/pull/23805#issuecomment-1813182936)). The bug only occured when a series of reads added up exactly to the size of one QIO buffer chunk, so the test is updated to meet that condition.
> Update test to lock in bug fix from #23805

- runtime/src/gpu/nvidia/Makefile.share
This is a draft PR to attempt fixing runtime builds with the newly added CUB wrappers. As-is, this takes us further and keeps things compiling with `sm_60`. But with newer architectures, I see failures. Some may be due to us using LLVM 15 with a patch.
> Fix runtime build issues with CUB wrappers when CUDA 12 used

- test/compflags/testPgWithLlvm.skipif
Though the skipif I committed yesterday worked as expected when running 'start_test -valgrindexe' locally, it did not get skipped in nightly testing as expected.  Jade and I guessed it could have something to do with the end-of-line comment (and Jade successfully proved it where I floundered :D ). so here, I'm hoisting the comment onto a line of its own.
> Second attempt at skipping this test under valgrind

- modules/standard/GPU.chpl
- modules/standard/Math.chpl
Since this function has not recieved any design discussion yet, we don't want to add it to the Math module (which has been stabilized). For now, since the only use case is in the GPU module, I'm moving it back there. We can move it to the Math module once it is stabilized
> Move new roundToPowerof2 out of Math module to GPU

- compiler/include/files.h
- compiler/util/files.cpp
Overwrite driver tmp files the first time they are written to, so stored results from previous compilations are not saved.
Along the way, simplify the implementation of `saveDriverTmp` to just call its sibling `saveDriverTmpMultiple` and avoid duplicated code.
Resolves https://github.com/Cray/chapel-private/issues/5642.
Testing:
> Overwrite driver tmp files on first use

- compiler/main/PhaseTracker.cpp
- compiler/main/PhaseTracker.h
- compiler/main/driver.cpp
- compiler/main/runpasses.cpp
- test/compflags/stopEarly/parseOnly.prediff
- test/performance/compiler/elliot/passCheck.prediff
Make significant changes to the output of `--print-passes` in driver mode so it accurately times each pass group as well as the overall time, displays this information more clearly, and is compatible with our performance testing.
Changes to `--print-passes` output (in driver mode only unless otherwise specified):
- In both monolithic and driver mode, the total times per pass group and overall total time are now displayed at the end of all output. Previously in monolithic mode this information was displayed immediately after individual pass timings.
- Besides these sweeping totals, normal `--print-passes` output is now displayed three times: for phase one, phase two, then for driver overhead. Each section begins with a header, contains only the passes that run in that process; driver …
> Make driver mode `--print-passes` output more accurate and useful

- util/chplenv/compile_link_args_utils.py
As part of adding reduction support, I modified how we build the runtime by adding `-B` in the compilation command so that we can use the lld that comes with the ROCm installation. But the side effect of that is we ended up using `clang-offload-bundler` from the ROCm installation instead of the the target compiler. This causes issues with the flags we pass to the bundler, especially with older versions of ROCm, where the corresponding clang version is 12. We'll need a solution to the `lld` problem when we enable reduction support for AMD GPUs via hipCUB, but until then, this `-B` doesn't have any use.
> Remove -B flag while building the runtime for AMD GPUs

- modules/standard/GPU.chpl
- test/gpu/native/noAmd/reduction/basic.good
- test/gpu/native/noAmd/reduction/largeArraysMinMax.chpl
- test/gpu/native/noAmd/reduction/nonZeroBased.good
- test/gpu/native/noAmd/reduction/stringError.good
Fixes two issues with the gpu*Reduce functions:
- I've made a mistake in `gpuMinLocReduce` and `gpuMaxLocReduce` where I made them return `(idx, val)` (a la CUB), whereas they should return `(val, idx)` (a la Chapel). 
- `stringError` test checks an error message for unsupported types. However, cpu-as-device branch of the code was before that check, so it was not exercising the check.
Both issues are fixed with this PR.
> Fix GPU-based reductions for cpu-as-device mode

- compiler/passes/convert-uast.cpp
- frontend/include/chpl/uast/When.h
- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/return-type-inference.cpp
- frontend/lib/uast/When.cpp
- frontend/lib/uast/chpl-syntax-printer.cpp
- frontend/test/parsing/testParseSelect.cpp
- frontend/test/resolution/testReturnTypes.cpp
1. Updates the when node to store a child block node rather than storing the statements directly as children of the when node. 
2. Adds support for skipping select statement branches that are statically known not to run. For example, a branch with a param false or the branches after one with a param true. There was a bug caused by the internal data structures not being marked as skip for select statements without an otherwise clause. I went ahead and refactored the entire method for brevity.
3. Adds 2 return type inference tests.
> Return type resolution ignores dead branches in select statements

- runtime/src/gpu/amd/gpu-amd.c
- runtime/src/gpu/nvidia/gpu-nvidia.c
When calling a kernel that lives inside a standard module, we propagate line numbers and file names for memory tracking and error reporting in a way that these arguments are added as formals to the kernel funciton generated by our compiler. The ln and fn arguments are already passed to the kernel launch functions in our runtime, but they were not being passed on the to the respective Nvidia and AMD kernel launch calls. 
This meant that the number of formals was more than the actuals and caused an error/segfault. 
By adding these arguments we fix the issue with the caveat that when in developer mode (CHPL_DEVELOPER) we don't need to pass these arguments since the line number is that of the Standard module. In this case the extra arguments are dropped on the floor. If there is an easy way …
> Add missign arguments to kernel launch calls

- compiler/passes/InitNormalize.cpp
- compiler/passes/initializerRules.cpp
- test/classes/initializers/errors/errHandling/initInsideTryBang.chpl
- test/classes/initializers/errors/errHandling/initInsideTryBang.good
- test/classes/initializers/parentCall/syncStatements.bad
- test/classes/initializers/parentCall/syncStatements.chpl
- test/classes/initializers/parentCall/syncStatements.future
- test/classes/initializers/phase1/syncStatements.bad
- test/classes/initializers/phase1/syncStatements.chpl
- test/classes/initializers/phase1/syncStatements.future
- test/classes/initializers/siblingCall/syncStatements.bad
- test/classes/initializers/siblingCall/syncStatements.chpl
- test/classes/initializers/siblingCall/syncStatements.future
This PR fixes a bug in the compiler where we would not apply initializer semantics to field initialization inside a ``try!`` block. This PR also updates some tests and fixes several outdated futures. A new test is added to demonstrate that fields are being initialized as expected.
Testing:
> Fix try! usage in initializers

- compiler/codegen/cg-symbol.cpp
- compiler/codegen/codegen.cpp
- compiler/include/driver.h
- compiler/include/files.h
- compiler/llvm/clangUtil.cpp
- compiler/main/PhaseTracker.cpp
- compiler/main/driver.cpp
- compiler/main/runpasses.cpp
- compiler/util/files.cpp
- doc/rst/technotes/driver.rst
- test/compflags/driver/debugger/declint-lldb.good
- test/compflags/driver/debugger/declint.good
- test/compflags/driver/driver-multiple-phases.compopts
- test/compflags/driver/driver-subinvocation-commands.good
- test/compflags/driver/monolithic/monolithic-debug-phase.compopts
- test/compflags/driver/monolithic/monolithic-subinvocation-no-tmp.compopts
- test/compflags/driver/monolithic/monolithic-subinvocation.compopts
- util/chpl-completion.bash
Change names of driver phases to `compilation` and `makeBinary` (previously just "phase one" and "phase two", respectively).
Includes flags, references in source code and comments, and docs.
Resolves https://github.com/Cray/chapel-private/issues/5643.
Testing:
> Rename driver mode phase names to `compilation` and `makeBinary`

- modules/standard/IO.chpl
This optimizes write/readBinary() to use the fast-path "native" code whenever the endianness requested explicitly matches the current architecture's endianness.  Previously, we fell into the slow path for both big/little choices whether or not our architecture is big/little.  Also applied this optimization to readBulkElements() and writeBulkElements().
While testing, I noticed and fixed a bug in which readBinary() was returning the number of bytes read rather than the number of array elements read when using the fast path.  Our only tests of the fast path were testing 8-bit values which is why this was not noticed previously.
While here, I also refactored some logic to exchange multi-case select statements for a singleton call that makes use of a new param->param helper procedure for …
> Optimizations and fixes to write/readBinary()

- frontend/lib/libraries/LibraryFileWriter.cpp
> Fix uninitialized variable warning in LibraryFileWriter.cpp

- tools/chplcheck/src/rules.py
Turns the `UnusedFormal` rule to be off by default due to its experimental nature.
Tested locally
> Turn chplcheck unused formal rule off by default

- test/reductions/thomasvandoren/test/TestSorted.bad
- test/reductions/thomasvandoren/test/TestSorted.chpl
- test/reductions/thomasvandoren/test/TestSorted.good
- test/separate_compilation/serialization/bug/.gitignore
- test/separate_compilation/serialization/bug/MyMod.chpl
- test/separate_compilation/serialization/bug/testGenLib.bad
- test/separate_compilation/serialization/bug/testGenLib.chpl
- test/separate_compilation/serialization/bug/testGenLib.cleanfiles
- test/separate_compilation/serialization/bug/testGenLib.compopts
- test/separate_compilation/serialization/bug/testGenLib.future
- test/separate_compilation/serialization/bug/testGenLib.precomp
#23752 broke `reductions/thomasvandoren/test/TestSorted` by replacing the test's .good file with its .bad file. This PR corrects that mistake.
Also adds a new future to track a bug related to separate compilation discovered while implementing changes to the Random module. See: https://github.com/chapel-lang/chapel/issues/23929
> Follow up to #23752

- compiler/optimizations/gpuTransforms.cpp
- compiler/resolution/lowerForalls.cpp
- frontend/include/chpl/uast/PragmaList.h
- test/gpu/native/basics/reductionNoGpuize.chpl
- test/gpu/native/basics/reductionNoGpuize.good
Currently if a gpuizable forall loop has a reduction intent it will produce
a wrong answer.
Long term we'd like to support this but in the meantime this PR changes
things so these loops will not gpuize (and will run on the cpu instead).
Specifically, this PR flags a temporary var introduced by reduce intents
and then detects the presence of a variable with this flag during gpuTransforms
to determine that the loop is ineligible.
Resolves #23827
TODO:
> Do not gpuize forall loop that has a reduction intent

- runtime/src/chpl-gpu.c
Fixes an issue in `chpl-gpu.c` where an `int64_t` was passed to the format specifer `%ld`. 
On some systems/compilers, we could get away with this. But after [23901](https://github.com/chapel-lang/chapel/pull/23901) some compilers will do more stringent checking and complain. The solution is to just use the right format specifier for `int64_t`.
Built locally
> Use correct specifier for `printf`-like function

- modules/internal/ChapelBase.chpl
This change simplifies the generated code for the comparisons `c == nil` and `c != nil` in multilocale compilations, where `c` is a nilable class represented in the compiler as a wide pointer, as in:
```chpl
var c: unmanaged RootClass?;
proc main {
if c != nil then writeln("hi");
}
```
Prior to this change this comparison looked like this:
```c
chpl_macro_tmp_3298.locale = chpl_gen_getLocaleID();
chpl_macro_tmp_3298.addr = NULL;
T2 = chpl_macro_tmp_3298;
... (((&T)->addr != (&T2)->addr) || ((!(! (&T)->addr)) && (chpl_nodeFromLocaleID((&T)->locale, [...]) != chpl_nodeFromLocaleID((&T2)->locale, [...])))) ...
```
With this change it looks like this:
```c
... ((&T)->addr != nil) ...
```
I expect no significant impact from this change on --local compilations.
A somewhat relevant tidbit: …
> Reduce generated code for nil comparisons

- test/release/examples/primers/chpldoc.doc.skipif
This test uses chpldoc which doesn't have `--no-checks` flag. That flag is implied with GPU nightly testing. So, for now, skip the test so that we can have cpu-as-device testing in `release/examples`.
> Update a skipif for a chpldoc test

- test/separate_compilation/serialization/SKIPIF
- test/separate_compilation/serialization/bug/SKIPIF
- test/separate_compilation/serialization/bug/testGenLib.precomp
- test/separate_compilation/serialization/testGenLib.precomp
Follow-up to PR #23906
This PR skips the `--dyno-gen-lib` tests when not using LLVM, since the generated `.dyno` files now store LLVM IR. While there, it improves the error handling in the `.precomp` files to make the issue easier to see in the future.
> Skip serialization tests when not using LLVM

- frontend/include/chpl/util/memory.h
- test/llvm/parallel_loop_access/different_numbers.chpl
Fixes two issues after merging LLVM 16 fixes. 
- `test/llvm/parallel_loop_access/different_numbers.chpl` was checking the ir too strictly, and didn't work with LLVM versions prior to 16
- `frontend/include/chpl/util/memory.h` was using `HAVE_LLVM_VER`, which is not defined in the frontend
Tested locally with llvm version 15 and 16
[reviewed by @benharsh]
> Fix LLVM 16 issues

- modules/packages/ProtobufProtocolSupport.chpl
- modules/standard/IO.chpl
- test/exercises/Mandelbrot/MPlot.chpl
- test/exercises/c-ray/Image.chpl
- test/exercises/duplicates/forStudents/FileHashing.chpl
- test/io/diten/checkpoint.chpl
- test/io/ferguson/channel-changing-type.chpl
- test/io/ferguson/writebinaryarray.chpl
- test/io/ferguson/writebinaryclass.chpl
- test/io/ferguson/writebinaryrecord.chpl
- test/io/ferguson/writebinarytuple.chpl
- test/io/ferguson/zerosatend.chpl
- test/io/jhh/readbinary.chpl
- test/io/jhh/writebinary.chpl
- test/io/serializers/FormatHelper.chpl
- test/library/standard/IO/readBinary/arrayOfValues.chpl
- test/library/standard/IO/readBinary/multiloc/binaryArray.chpl
- test/library/standard/IO/writeBinary/writeArray.chpl
- test/release/examples/primers/FFTWlib.chpl
- test/studies/ml/lib/Chai.chpl
- test/studies/ml/lib/MNIST.chpl
- test/studies/ssca2/graphio/SSCA2_RMAT_graph_generator.chpl
- test/studies/ssca2/main/SSCA2_Modules/io_RMAT_graph.chpl
- test/users/npadmana/fftw/testFFTWsegfault.chpl
- util/devel/chplspell-dictionary
Based on the discussion about the name change for `ioendian`.
Resolves https://github.com/chapel-lang/chapel/issues/23868
> Renaming `ioendian` to `endianness`

- frontend/lib/resolution/disambiguation.cpp
- frontend/test/resolution/testDisambiguation.cpp
This PR integrates changes from previous work to refactor the dyno resolver's disambiguation rules to more closely match production's following https://github.com/chapel-lang/chapel/pull/20528.
There remains a TODO to implement the warning when allowing `int`->`uint` conversion, captured in https://github.com/Cray/chapel-private/issues/5709
TESTING:
```
proc f(arg: int(8)) { }                   // 1
proc f(arg: uint(64)) { }                 // 2
var x: int(64);
f(x);
```
using the new disambiguation rules, the resolver will pick the `uint` version of `f` (labeled 2) because of matching bit widths.
[reviewed by @mppf - thank you!]
> update dyno resolver to use new disambiguation rules

- test/llvm/parallel_loop_access/different_numbers.chpl
After #23942, the test `test/llvm/parallel_loop_access/different_numbers.chpl` was too relaxed and would match the wrong lines in the IR, causing test failures on LLVM versions prior to 15.
Tested with llvm 14, 15, and 16
> Make FileCheck not match i32* test

- compiler/passes/scopeResolve.cpp
- modules/standard/IO.chpl
- test/deprecated/IO/ioendian/ioendianUse.chpl
- test/deprecated/IO/ioendian/ioendianUse.good
- test/deprecated/IO/ioendian/readWriteBinary.chpl
- test/deprecated/IO/ioendian/readWriteBinary.good
Using @DanilaFe 's (thanks!) strategy to have `ioendian` be a type alias to the new `endianness` enum.
This didn't work at first because the alias was a reference to a type variable instead of a type itself, so we dereference hoping that there's a type declaration at the end.
Added testing for deprecated `ioendian`
> Deprecate `ioendian`

- util/devel/test/spliceDat
The `spliceDat` script was ignoring commented out lines, but that meant the corresponding line from the other file to be selected regardless of the dates. This PR adjusts the script to read until the comments finish to find the first actual entry after a comment rather than stopping there.
> Fix a helper script for data splicing

- test/unstableAnonScript/specialCases/constArgs.skipif
The check this test validates doesn't run when --fast is used, so skip it
Verified the skipif worked in a fresh checkout
> Skip this test with --fast

- runtime/src/chpl-const-arg-check.c
chpl_glom_strings allocates memory for the message, so we need to clean it up when we are done with it.
Checked the new tests with `-memLeaks` and the remote test with CHPL_COMM=gasnet and `-memLeaks`
> Fix memory leak with const check warning message

- doc/rst/technotes/driver.rst
Update Future Work bullets in the driver technote to reflect the current status of the work.
I left the issues to be resolved vague since we don't know enough about their cause yet to provide any useful information.
[minor dev-oriented docs change, not reviewed]
> Update driver technote Future Work to reflect current status

- doc/rst/usingchapel/multilocale.rst
Add `slurm-gasnetrun_* `and `gasnetrun_*` launchers, and improve the wording.
> Improve co-locale documentation

- test/chplcheck/BoolLitInCondStatement.chpl
- test/chplcheck/BoolLitInCondStatement.good
- test/chplcheck/CaseRules.chpl
- test/chplcheck/CaseRules.good
- test/chplcheck/ChplPrefixReserved.chpl
- test/chplcheck/ChplPrefixReserved.good
- test/chplcheck/ConsecutiveDecls.chpl
- test/chplcheck/ConsecutiveDecls.good
- test/chplcheck/DoKeywordAndBlock.chpl
- test/chplcheck/DoKeywordAndBlock.good
- test/chplcheck/MethodsAfterFields.chpl
- test/chplcheck/MethodsAfterFields.good
- test/chplcheck/MisleadingIndentation.chpl
- test/chplcheck/MisleadingIndentation.good
- test/chplcheck/NestedCoforalls.chpl
- test/chplcheck/NestedCoforalls.good
- test/chplcheck/PREDIFF
- test/chplcheck/Unused.chpl
- test/chplcheck/Unused.good
- test/chplcheck/UseExplicitModules.chpl
- test/chplcheck/UseExplicitModules.good
- tools/chplcheck/src/chplcheck.py
- tools/chplcheck/src/rules.py
Three changes:
1. Testing for the existing linter rules
2. Variable casing rule changed from camelCase only to camelCase or PascalCase to match [style guide](https://chapel-lang.org/docs/developer/bestPractices/StandardModuleStyle.html#other-identifiers).
3. Linter driver now sorts violations by line number.
> Linter tests

- modules/standard/IO.chpl
- test/io/corrado/buffering_optimization/optimization_flag.compopts
- test/io/corrado/buffering_optimization/optimization_flag.opt-off.good
Make the `IOSkipBufferingForLargeOps` flag publicly documented (and unstable).
> Document the `IOSkipBufferingForLargeOps` flag

- modules/standard/Random.chpl
Initializing a `randomStream` without a seed is unstable. This PR adds a note to the Random module's documentation providing some more detail about this change.
> Add note about seeds to `Random` docs

- runtime/src/gpu/amd/gpu-amd-reduce.cc
With ROCm 4, some runtime functions for reduction are just empty stubs (they actually error out). In that world, one of the includes is not necessary and causing unused function errors. This PR adjust the reduction support in the runtime for AMD GPUs.
> Fix an include in the runtime causing failures while building with ROCm 4

- doc/rst/meta/modules/packages.rst
- modules/Makefile
- modules/standard/IO.chpl
This PR improves some of the documentation following #23932 :
- document ``ObjectSerialization`` package module
- document new ``IllegalArgumentError`` for binaryDeserializer and string/bytes types
- update documentation for binarySerializer/binaryDeserializer to point to ``ObjectSerialization`` as alternative
> Docs improvements for binarySerializer changes

- doc/rst/language/spec/procedures.rst
- doc/rst/language/spec/variables.rst
Adding more specification of `ref` variables and a related open issue.
> Update the language spec on ref variables

- modules/standard/Errors.chpl
- test/errhandling/errorMessages/taskerrors-remote-1.good
- test/errhandling/errorMessages/taskerrors-remote-2.good
- test/modules/bradc/userInsteadOfStandard/ChapelIO.chpl
This reverts the change to Errors.chpl made in #23992's commit cfebf149d2. That change switched two asserts from displaying `someLocale.id` to displaying `someLocale`, which threw off a lot of tests due to problems with resolution order. For example, the test `errhandling/parallel/forall-wrap-first-error` started reporting "error: module-scope variable 'count' may be used before it is initialized". Using `someLocale.id` in the assertions avoids these problems. Correspondingly, this reverts the change to `test/modules/bradc/userInsteadOfStandard/ChapelIO.chpl` as no longer needed.
Merging without a review for expediency.
> Fix more fallouts from #23992

- test/chplcheck/CaseRules.chpl
- tools/chplcheck/src/rules.py
The chplcheck warning to camel case functions was incorrectly firing for operators, since they use non-ascii charcters. This PR just skips checking operator function names.
Tested locally
[Reviewed by @brandon-neth]
> Fix lint checks for CamelCaseFunctions on operators

- compiler/llvm/clangUtil.cpp
Resolves https://github.com/Cray/chapel-private/issues/5509
Since the beginning of AMD support, we have been using `clang-offload-bundler` from the ROCm installation instead of from our backend. This is probably based on a decision in the prototyping phase that we haven't revisited or didn't feel the need to.
Recently, we've observed that this resulted in some deprecation warnings because the flags we use while launching `clang-offload-bundler`: https://github.com/chapel-lang/chapel/issues/23480. Sticking to ROCm's bundler, we'd have to do some wiring to be able to determine the version so that we can use the right arguments. We already have that wiring laid out for the backend's clang version. So, with this PR, we'll start using backend's bundler. On a more abstract level, it also makes …
> Use backend's `clang-offload-bundler` instead of ROCm's

- test/studies/shootout/submitted/knucleotide3.perfkeys
- test/studies/shootout/submitted/knucleotide4.perfkeys
https://github.com/chapel-lang/chapel/pull/23957 removed a deprecation warning from our implementation of the knucleotide computer language benchmark game test.
This shifts line numbers in the output and so we need to update what line numbers we specify for validation during our perf tests. I failed to do that in the previously mentioned PR but now this PR fixes it.
> update line numbers for validation of knucleotide perf tests

- test/library/standard/CommDiagnostics/commDiagnosticsWarnings.chpl
- test/library/standard/CommDiagnostics/commDiagnosticsWarnings.no-local.good
Fixes a test failing in our nightly tests with `--no-local`.
Tested locally with and without `--no-local` and comm.
> Fixes nightly test issue with `--no-local`

- doc/rst/usingchapel/prereqs.rst
- util/devel/test/apptainer/extract-docs.py
This PR updates the `prereqs.rst` example installation commands to install prerequisites. They are generated from a script that uses the commands used in PR #23984. Additionally, updates these installation commands with some notes about incompatibilities e.g., for Alpine we have issue #23414.
Reviewed by @brandon-neth - thanks!
> Update prereqs.rst with current portability prereq cmds

- runtime/src/gpu/nvidia/Makefile.share
- runtime/src/gpu/nvidia/gpu-nvidia-reduce.cc
Resolves https://github.com/chapel-lang/chapel/issues/23893
Resolves https://github.com/Cray/chapel-private/issues/5712
This PR aligns `nvidia` reduction support to `amd`: https://github.com/chapel-lang/chapel/pull/23950/files#diff-eb05ab5f4c9820ed534cd67b2f2f83426c7fd52e90c86b5afcbb29dc7992296dR24 where we build the reduction support source only for `CHPL_GPU_ARCH`. This improves the build time of the reduction support by about 4x on my workstation (1 vs 4 minutes).
Related: https://github.com/chapel-lang/chapel/issues/23960
Test:
> Build the runtime support for reductions on NVIDIA GPUs only for `CHPL_GPU_ARCH`

- tools/chpldoc/CMakeLists.txt
This PR fixes build issues for `chpldoc` on older versions of LLVM and GCC. Similar to the changes in https://github.com/chapel-lang/chapel/pull/22260, this adds a check for LLVM versions < 16.0 and assigns the `CXX_STANDARD` as either 14 or 17.
TESTING:
[reviewed by @jabraham17 - thank you!]
> fix [chpldoc]: adjust cxx standard based on LLVM version

- test/ANNOTATIONS.yaml
- util/test/check_annotations.py
Adds annotation for every change I can catch and notes for things that I can't repro easily or looked but chose to ignore.
Also adjusts `check_annotations.py` to have the new config names (`1-node-p100` etc)
> Move existing GPU annotations to new plots, add new ones

- frontend/lib/parsing/bison-chpl-lib.cpp
- frontend/lib/parsing/chpl.ypp
- frontend/test/parsing/testParseErrors.cpp
- test/functions/generic/genericReturnMemKind.bad
- test/parsing/ferguson/many-errors-2.good
This PR reverts a late change in #23973 which broke a number of tests. Adding an extra `context->syntax(...)` created extra syntax errors in unwanted places, this PR removes that.
Ran full paratests with comm=none and comm=gasnet
> Fix test errors after parser fix

- tools/chpldoc/CMakeLists.txt
This PR adjusts the relative positions of setting the global CMake CXX standard value and defining the `chpldoc` target so that setting the value affects the target, where before the target was unaffected by the change. This is an update to https://github.com/chapel-lang/chapel/pull/24008.
This should fix remaining build failures for `chpldoc` when using llvm versions 11 and 12.
[reviewed by @jabraham17 - thank you!]
> set c++ standard for chpldoc before defining target in cmake

- doc/rst/technotes/reduceIntents.rst
It was out of date with recent Chapel changes.
Add "do" to the braceless single-statement functions. Add a "(?)" to a generic typed argument.
I took the liberty of changing the second example to use different variable names than the first example so that the whole code block could be compiled at once.
> Update code example in reduceIntents tech note

- doc/rst/technotes/gpu.rst
This PR includes several adjustments to the GPU technote:
- Drops support for CUDA 10.x: we never really did anything special for it in the past. It did work but in an inefficient way. With 12 out, 10 feels pretty old.
- Removes warnings about ROCm deprecation warnings (Resolved via https://github.com/chapel-lang/chapel/pull/23972)
- Drops references to `assertOnGpu()` function that was deprecated.
- Adds a subsection about "Reductions and Scans"
- Improves d2d communication section
> GPU technote updates for 1.33

- doc/rst/developer/bestPractices/TestSystem.rst
- util/test/sub_test.py
- Add PRETEST to docs.
- Update guidance on precomp, prexec, and prediff.
- Add some missing items to summary.
- Add how to specify a `.good` file without changing default args. Add CHPL_SYSTEM_PREDIFF env var to docs
> Update testing system docs with files and examples

- doc/rst/technotes/gpu.rst
This PR adds a "Performance Tips" section to the gpu tech note and adds a first tip about GPU initialization time (and that it can be alleviated by using the NVIDIA persistence daemon).
> add performance tips section to gpu tech note

- doc/rst/meta/modules/standard.rst
- doc/rst/usingchapel/prereqs.rst
Bundle of 2 cleanups to the docs
- Fix alphabetization of the Diagnostics section for standard modules
- Add a note about LLVM 16 to the prerequisites section
Build docs locally
> Bundle of doc cleanups

- util/buildRelease/gen_release
Thanks @bradcray for the catch!
This PR makes sure that `chapel-py` and `chplcheck` are are included in source tarballs of Chapel. 
Built the release tarball with:
```
export CHPL_GEN_RELEASE_NO_CLONE
./util/buildRelease/gen_release   
```
Then, built `chplcheck` via the release as follows:
```
source ./util/setchplenv.bash
make chplcheck -j32
```
Running `chplcheck` produced the following:
```
> chplcheck --help
usage: chplcheck [-h] [--disable-rule DISABLED_RULES] [--enable-rule ENABLED_RULES] [--lsp]
[filenames ...]
```
> Bundle chapel-py and chplcheck in the release tarball.

- modules/packages/LinearAlgebra.chpl
- test/library/packages/LinearAlgebra/correctness/no-dependencies/solveLU.chpl
- test/library/packages/LinearAlgebra/correctness/no-dependencies/solveLU.good
- test/library/packages/LinearAlgebra/correctness/no-dependencies/solveTriangular.chpl
- test/library/packages/LinearAlgebra/correctness/no-dependencies/solveTriangular.good
This PR is part of #17624 and improves the index-neutrality (any offset) of the following procedures:
- `solve_tril`
- `solve_triu`
- `solve`
- private `_lu`
- private `permute`
- `lu` (implicitly)
- `det` (implicitly)
It also adds several correctness tests.
Resolves #17513
> Improve index-neutrality of `LinearAlgebra`

- frontend/include/chpl/types/Param.h
- frontend/lib/resolution/prims.cpp
- frontend/test/resolution/testResolve.cpp
'transmutation' in this case means literally taking the bits of a real number and interpreting them as bits of an unsigned integer, and vise versa. Because there are four related primitives that do this, I implemented them all using a templated function that accepts the `Param` containers and the (C++) types to be converted.
I didn't find a way to generate params of types other than `real(64)` without modifying compiler code, so I am only testing that case. However, since the same code is used for all four primitives, I have a high confidence that it works.
> Dyno: implement 'transmute' primitives between reals and uints.

- frontend/include/chpl/resolution/can-pass.h
- frontend/lib/resolution/can-pass.cpp
- frontend/lib/resolution/prims.cpp
- frontend/lib/types/TupleType.cpp
- frontend/test/resolution/testResolve.cpp
- frontend/test/test-resolution.cpp
- frontend/test/test-resolution.h
This PR is probably best reviewed commit-by-commit. I've started my test names from `14` because other PRs I have open right now use the numbers 11 through 13. The primitives are:
* `PRIM_ADDR_OF`
* `PRIM_TYPEOF` and `PRIM_STATIC_TYPEOF`
* `PRIM_STATIC_FIELD_TYPE`
> Dyno: implement a few more miscellaneous primitives

- frontend/include/chpl/resolution/can-pass.h
- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/Resolver.h
- frontend/lib/resolution/can-pass.cpp
- frontend/lib/resolution/prims.cpp
- frontend/lib/types/TupleType.cpp
- frontend/test/resolution/testReflection.cpp
- frontend/test/resolution/testResolve.cpp
- frontend/test/test-resolution.cpp
- frontend/test/test-resolution.h
The `resolves` primitive accepts an arbitrary expression and attempts to resolve it. If it resolves, the primitive returns `true`; if it does not resolve the primitive returns `false`. 
This PR adds special treatment for `resolves` because unlike most other primitives, its behavior cant' be described in terms of already-resolved actual types: in fact, the way that it resolves actuals is unusual (it hides and ignores errors). Thus, this PR adds a new `resolveSpecialPrimCall` method to the `Resolver`, and skips "usual" actual handling for `PRIM_RESOLVES`. 
> Dyno: Add the "resolves" primitive

- frontend/include/chpl/resolution/can-pass.h
- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/Resolver.h
- frontend/lib/resolution/can-pass.cpp
- frontend/lib/resolution/prims.cpp
- frontend/lib/types/TupleType.cpp
- frontend/test/resolution/testReflection.cpp
- frontend/test/resolution/testResolve.cpp
- frontend/test/test-resolution.cpp
- frontend/test/test-resolution.h
This PR adds the version primitives (major, minor, update, hash) that return this values as params.
Reviewed by @arezaii and @dlongnecke-cray -- thanks!
> Dyno: add version primitives

- make/compiler/Makefile.clang
Fixes a typo in a version check that caused CHPL_DEVELOPER=1 builds to fail with clang compilers prior to version 16
- Building Chapel with COMM=gasnet and CHPL_DEVELOPER=1
resolves #24045
> Fix unknown `-Wno-cast-function-type-strict`

- frontend/lib/resolution/prims.cpp
- frontend/test/resolution/testFunctionCalls.cpp
This PR expands the resolution of the primitive `string_length_bytes` to also work for non-param string and bytes type arguments. This is needed to allow for some module code to resolve using Dyno.
> expand prim string_length_bytes to non-param kinds

- .github/workflows/CI.yml
- compiler/include/misc.h
- frontend/lib/immediates/make_prims/make_prims.cpp
- util/devel/lookForBadCompCalls
This PR replaces the `#define exit` in `compiler/include/misc.h` with a script that checks for calls to `exit` similarly to the way that `lookForBadRTCalls` already works.
The `#define exit` causes problems when using the LLVM Support Library with `CHPL_LLVM=none`. If `CHPL_LLVM=llvm` then the `#define exit` error was already disabled.
> Change define about exit to a script to check sources

- .github/workflows/CI.yml
- compiler/Makefile
- frontend/util/linters/CMakeLists.txt
Resolves #22551
While testing #24019, I added portability testing for Alpine 3.19 and I noticed a problem with the `find_package(Clang)` command supporting the frontend linter, so I investigated.
The frontend linter is not normally built at all (its main use is as a CI check) but because of the way it was using `find_package`, it occasionally introduced portability problems. However, it turns out that the `find_package` command is completely unnecessary and the tool was already finding clang headers and libraries through other cmake variables. So, this PR simply removes the `find_package` command.
Additionally, it adds some checking to give a more straightforward error in the case that the frontend linter is run with `CHPL_HOST_COMPILER=gnu` (or any compiler other than `clang`). In that …
> Remove find_package(Clang) from frontend linter CMakeLists.txt

- test/library/packages/Sort/performance/comparison/chapel-quicksort-random.chpl
- test/library/packages/Sort/performance/comparison/numpy-sort-random.py
- test/library/packages/Sort/performance/comparison/python-sort-random.py
These tests are not run in any testing config & only run manually.
This PR updates a few tests to fix incorrect comments, handle Python 3 deprecation of `time.clock()`, and handle Chapel changes.
> Update Sort comparison tests

- Makefile
- third-party/chpl-venv/Makefile
Move build step of `.pyi` into a chapel-py specific Makefile. Also fixes an issue where the directory might not exist.
Tested with complete clobber and rebuild
> Move build of chapel-py python include's to chapel-py-venv Makefile

- Makefile
- test/chplcheck/CaseRules.chpl
- test/chplcheck/CaseRules.good
- test/chplcheck/PREDIFF
- tools/chplcheck/src/rules.py
`chplcheck` testing has been broken and I'm the only one who found out because I'm the only one who has `chplcheck` built on `chapdl`. The `PREDIFF` script relies on `sed` which is apparently different between macOS and Linux. Fix the script to use a sed command that works on both. Also fix the `CaseRules` test which turned out to be broken.
Reviewed by @jabraham17 and @brandon-neth -- thanks!
> Fix `sed` calls in `chplcheck` scripts on test machines, and other fixes to our tests.

- frontend/lib/resolution/prims.cpp
- frontend/test/resolution/testFunctionCalls.cpp
This PR implements resolution of the return types for `PRIM_GET_REAL` and `PRIM_GET_IMAG` in Dyno.
The backing issue for implementing these primitives is https://github.com/Cray/chapel-private/issues/5512
> implement return type resolution of prims get_real and get_imag in dyno

- doc/rst/usingchapel/prereqs.rst
- util/devel/test/apptainer/current/alpine-3.18-nollvm/image.def
- util/devel/test/apptainer/current/alpine-3.19-nollvm/image.def
- util/devel/test/apptainer/current/alpine-3.19/image.def
- util/devel/test/vagrant/README-distro-timelines.txt
This PR adds apptainer testing for Alpine 3.19 which was recently released. Alpine 3.19 with a system install of LLVM should work OK after PRs #24019 and #24059. However, I observed problems building the LLVM Support library if no system LLVM is present. The error looked like this for me:
```
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/raw_ostream.cpp.o
/home/mppf/w/vagrant/util/devel/test/apptainer/current/alpine-3.19-nollvm/chapel/third-party/llvm/llvm-src/lib/Support/raw_ostream.cpp: In member function 'uint64_t llvm::raw_fd_ostream::seek(uint64_t)':
/home/mppf/w/vagrant/util/devel/test/apptainer/current/alpine-3.19-nollvm/chapel/third-party/llvm/llvm-src/lib/Support/raw_ostream.cpp:808:11: error: '::lseek6' has not been declared; did you mean 'lseek'?
808 |   pos …
```
> Add alpine 3.19 to portability testing

- .github/workflows/CI.yml
- tools/chpldoc/findUndocumentedSymbols.py
Adds a CI check for undocumented symbols. This currently only checks undeprecated and stable module code in `modules/standard`. The check was added as a part of the the existing dyno checks to reduce the extra time added to the CI.
> Add a CI check for undocumented symbols

- test/library/packages/LinearAlgebra/correctness/no-dependencies/solveTriangular.chpl
Fixes a sporadic failure in `/test/library/packages/LinearAlgebra/correctness/no-dependencies/solveTriangular` caused by some floating point inaccuracies. Adds seed values to the random number generation so that poorly conditioned matrices aren't generated on occasion by the random number generator.
(also adds `1` to the list of offsets for coverage of a potentially common case)
> Fix sporadic failure in solveTriangular linalg test

- util/cron/test-perf.chapcs.playground.bash
Use perf playground with a branch that sets the calling convention of non-extern/export functions to be LLVM's fastcall
> Use perf playground with fastcall branch

- test/gpu/native/intents/SKIPIF
Currently when using foreach intents (enabled today using the `--foreach-intents` compiler flag) and cpu-as-device mode `in` intents will exhibit the behavior expected when running a foreach loop on a CPU rather than a GPU.
I think its an open question about what we should do, but in the meantime (since this is work-in-progress and these tests are failing our nightly cpu-as-device job) I'm going to exempt foreach testing for cpu-as-device.
> exempt foreach intents tests with cpu-as-device mode

- test/compflags/ferguson/gen-lib-flags/SKIPIF
Follow-up to PR #24032 to skip a new test when `CHPL_TARGET_COMPILER!=llvm` because it gives an unrelated error in that case.
> Skip new test for CHPL_TARGET_COMPILER!=llvm

- .github/workflows/CI.yml
- Makefile
- Makefile.devel
- modules/dists/BlockDist.chpl
- modules/dists/CyclicDist.chpl
- modules/dists/DSIUtil.chpl
- modules/dists/SparseBlockDist.chpl
- modules/dists/dims/BlockCycDim.chpl
- modules/dists/dims/BlockDim.chpl
- modules/dists/dims/ReplicatedDim.chpl
- test/chplcheck/CaseRules.chpl
- test/chplcheck/CaseRules.good
- test/chplcheck/ChplPrefixReserved.good
- test/chplcheck/PREDIFF
- test/chplcheck/SkipUnstableInternal.chpl
- test/chplcheck/SkipUnstableInternal.good
- test/chplcheck/Unused.chpl
- test/chplcheck/Unused.good
- test/chplcheck/UnusedFormalBug.bad
- test/chplcheck/UnusedFormalBug.chpl
- tools/chplcheck/src/chplcheck.py
- tools/chplcheck/src/driver.py
- tools/chplcheck/src/rules.py
This PR uses `chplcheck` to start linting modules in our `modules/` folder. For the time being, it lints only `modules/dists`, which is the first directory there alphabetically. Since adding each new directory requires some manual involvement to fix linter issues, the checks will be run on progressively more standard modules as they are brought to compliance. 
This PR also:
* Tweaks the `UnusedLoopIndex` rule to handle `_` properly (i.e. not warn!)
* Disables the `NestedCoforalls` rule.
* Adds a flag to skip unstable modules (since we don't want to put in the effort to make them lint-free)
* Also adds logic to skip linting variables starting with `chpl_` and `_` (specified from the command line), since these are internal implementation details and not worth our attention.
* Tweaks …
> Start linting some standard modules in CI checks

- compiler/optimizations/gpuTransforms.cpp
- test/gpu/native/diags.cpu.good
- test/gpu/native/noGpu/basicMem.comm-none.good
- test/gpu/native/noGpu/basicMem.good
- test/gpu/native/studies/transpose/transpose.chpl
- Adjusts some tests' good files to add new verbose output.
- Fixes the transpose test's low-level launch that was failing with --fast
- Add a comment in the compiler for a case that strikes me as wrong
> Fix test failures after adjustments to kernel launch

- Makefile.devel
- compiler/Makefile
Adds `frontend-tests` as a top level makefile target to build the dyno tests without running them.
> makefile target for building the dyno tests without running them.

- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/Resolver.h
- frontend/test/resolution/testTypeAndInit.cpp
This PR adjusts the dyno resolver to allow numeric type conversions when defining initializer expressions (such as default values) for formals. This resolves original issue https://github.com/Cray/chapel-private/issues/5730. 
Prior to this PR, dyno wouldn't allow the following program to compile:
```chapel
proc foo(arg: uint = 0) {
return arg;
}
var x = foo();
```
Previously, the resolver wouldn't evaluate a possible numeric conversion for `arg` because it hadn't resolved what the `default_intent` should be. This PR moves the intent resolution up for the case of formal initialization expressions with defaults.
TESTING:
> bug(dyno): let int->uint pass when formal has default value

- util/packaging/homebrew/chapel-main.rb
- util/packaging/homebrew/chapel-release.rb
The chapel-release.rb file now matches the currently released homebrew formula and the chapel-main.rb is configured for the 1.33 release.
> Homebrew updates for the 1.32 and 1.33 release

- test/llvm/no-math-errno/check-sqrt-noieee.suppressif
Follow-up to PR #24066 and PR #24106 to extend the `suppressif` to another testing configuration.
Note: I created issue #24112 about the problem that these .suppressif files are suppressing.
> Also suppressif check-sqrt on chapvm

- test/library/standard/Types/copyable/copyable-generic.skipif
- test/types/integral/integral-alias-baseline.bad
- test/types/integral/integral-alias-baseline.chpl
- test/types/integral/integral-alias-baseline.future
- test/types/integral/integral-alias-baseline.good
- test/types/integral/integral-alias-baseline.skipif
- test/types/integral/integral-alias.chpl
- test/types/integral/integral-alias.good
- test/types/integral/integral-alias.skipif
Work around the bug with `type t = integral` with `--baseline`, described in https://github.com/chapel-lang/chapel/issues/24113, and add a future for it.
This bug causes the test `library/standard/Types/copyable/copyable-generic` to fail with `--baseline`, so add a skipif for it.
Follow up to https://github.com/chapel-lang/chapel/pull/24058 which added the test.
Testing:
> Work around `integral` bug with `--baseline` and add future

- test/studies/hpcc/STREAMS/bradc/stream-block1d-dom.chpl
- test/studies/hpcc/STREAMS/bradc/stream-block1d-local.chpl
- test/studies/hpcc/STREAMS/bradc/stream-block1d.chpl
- test/studies/hpcc/STREAMS/bradc/stream-block1dclass.chpl
- test/studies/hpcc/STREAMS/bradc/stream-block1dpar-arr.chpl
- test/studies/hpcc/STREAMS/bradc/stream-block1dpar.chpl
- test/studies/hpcc/STREAMS/bradc/stream-nopromote.chpl
- test/studies/hpcc/STREAMS/elliot/stream-spmd-barrier.chpl
- test/studies/hpcc/STREAMS/elliot/stream-task-placement.chpl
- test/studies/hpcc/STREAMS/stream-nopromote.chpl
Performance validation was failing for some of the STREAM benchmarks following https://github.com/chapel-lang/chapel/pull/24081. This was occuring in 32-bit testing and for some intel compiler configurations.
With the NPB random number generator, the benchmarks were able to pass with an epsilon of `0.0`; however, with the update to PCG, an epsilon of `1e-15` is required. (This is likely related to the fact that NPB creates random numbers that have exact floating point representations while PCG does not).
Note: under normal configurations (LLVM/gcc/clang on a 64-bit system), the STREAM tests that use promotion were also failing with the PCG rng for similar reasons. Those tests were already updated to use an epsilon of `1e-15` in the above mentioned PR. The remaining tests (those that don't …
> Fix failing stream performance tests following switch to PCG random number generator

- third-party/re2/re2-src/Makefile
GNU `sed` handles -i differently from BSD `sed` in that the former doesn't want a space before the suffix while the latter does. With the space GNU `sed` does not create `re2.pc` correctly.
> Add support for GNU sed on Darwin

- doc/rst/language/spec/statements.rst
- frontend/include/chpl/parsing/parser-error-classes-list.h
- frontend/lib/parsing/parser-error-classes-list.cpp
- frontend/lib/uast/post-parse-checks.cpp
- frontend/test/parsing/testParseSelect.cpp
To better match the documented behavior of `select` statements (control transfers to first match) and the natural language analogy of `select`-`when`-`otherwise`, and to simplify the compiler treatment of select statements, `otherwise` clauses are now required to come at the end of the `select` statements.
Pull request updates the documentation to match this and adds a post-parse check and tests for it.
Resolves #24030.
Tested locally
Reviewed by: @DanilaFe
> `otherwise` required to come at the end of `select` statements

- test/compflags/unknownLlvmFlag.chpl
- test/compflags/unknownLlvmFlag.compopts
- test/compflags/unknownLlvmFlag.good
- test/compflags/unknownLlvmFlag.skipif
This PR is a capture of the behavior reported in https://github.com/chapel-lang/chapel/issues/21296 which seems to be working OK today.  I have a vague memory of someone improving this situation (or something similar to it) recently, though I can't find the PR I'm thinking of with a quick search.  I didn't see any existing tests with 'unsupported option' in their .good files, so am adding this to ensure the behavior does not backslide.
Resolves #21296 (well, something else resolved it; this just locks in that it is resolved).
> Add test locking in current behavior for #21296

- test/functions/default-arguments/default-argument-class-override3c.chpl
- test/functions/default-arguments/default-argument-class-override3c.good
- test/functions/default-arguments/default-argument-class-override3d.chpl
- test/functions/default-arguments/default-argument-class-override3d.good
One of them used to result in a compiler segfault, per #14167.
Resolves #14167
> Add two more default-argument-class-override test variants

- doc/rst/language/spec/memory-consistency-model.rst
> Fix typo in memory consistency model docs

- third-party/Makefile
In #24128, @twesterhout pointed out that `make c2chapel` would set up the respective venv even if `CHPL_DONT_BUILD_C2CHAPEL_VENV` said not to.  This fixes the issue by pushing the check against the environment variable into an inner Makefile rule where we specify how to build the environment.
Resolves #24128.
> Only build the c2chapel venv if CHPL_DONT_BUILD_C2CHAPEL_VENV permits it

- test/classes/errors/int-error-generic-field.chpl
- test/classes/errors/int-error-generic-field.good
- test/classes/errors/int-error-generic-field2.chpl
This PR adds a pair of tests that lock in the current behavior for a test reported as resulting in an internal error in https://github.com/chapel-lang/chapel/issues/21298.  It seems that the behavior has improved since then, likely due to Michael's work in adding warnings around generic types, but possibly other changes as well.
Resolves #21298.
> Add tests locking in current behavior w.r.t. #21298

- frontend/test/resolution/testTypePropertyPrimitives.cpp
Update copyright notice in `frontend/test/resolution/testTypePropertyPrimitives.cpp` for 2024.
Missed in https://github.com/chapel-lang/chapel/pull/24122 because the file was added while that PR was in flight.
Testing:
> Update a missed copyright notice for 2024

- modules/packages/DistributedBagDeprecated.chpl
Follow-up to PR #23204. This PR just updates the copyright in a new file.
Trivial and not reviewed. Comment change only.
> Update copyright on DistributedBagDeprecated.chpl

- frontend/lib/resolution/prims.cpp
- frontend/test/resolution/testRuntimePrimitives.cpp
Not sure how much more I have to say. The primitives are complicated in the backend, because we need to thread user line information throughout various functions as extra arguments. However, it seems like Dyno resolution need not concern itself with this.
> Add type inferene for `_get_user_line` and `_get_user_file` prims. They're just ints!

- frontend/include/chpl/types/IntType.h
- frontend/include/chpl/types/Type.h
- frontend/lib/resolution/prims.cpp
- frontend/test/resolution/testRuntimePrimitives.cpp
This PR adds GPU primitives to Dyno. While there, it also modifies the code for testing primitives to considerably clean it up, and adds new `to` methods to types to make it possible to use them from a templated context. 
The `toWhateverType` methods on types and AST nodes a great, but a problem with them is that the target of the conversion is encoded in the name. Thus, it's impossible to e.g., accept a general AST node type as a template parameter, and then call the appropriate `toWhatever` method on it. I've hit this a couple of times before, and decided to improve the situation.
The situation is improved by adding a new `to<TargetType>` template, which makes it possible to perform a cast from a base type to a subclass type given by a template argument. The template `to<Whatever>` …
> Add GPU primitives to Dyno

- test/studies/bale/aggregation/AtomicAggregation.chpl
Fixes an issue that came up in nightly testing of AtomicIncAggregator on 32 bit platforms. This is fixed both with a cast on the `allocate` call and by turning off the aggregator when COMM=none. This is done similarly to [Src|Dst]Aggregator where if COMM=NONE then the aggregator does nothing.
This potentially exposes a larger issue with aggregators, which has its own issue (#24148)
Tested locally w/wo comm.
> Fix testing failure for AtomicIncAggregator on 32-bit platforms

- test/gpu/native/noGpu/basicMem.comm-none.good
- test/gpu/native/noGpu/basicMem.good
This PR updates .good files with line numbers that changed due to #24136.
Could we instead prediff-out these line numbers?
Yes, by copying from one of multiple existing prediff scripts (possibly using a more specific path) that contain this:
```bash
!/usr/bin/env bash
sed '\|CHPL_HOME/modules|s/:[0-9]*:/:nnnn:/' $2 > $2.tmp
mv $2.tmp $2
```
SHOULD we prediff-out the these line numbers?
Citing Engin, "this is one of those cases where it is not as clear to me: this is a memory diagnostic test, and it is kind of important to see which line numbers are producing the message." So I choose to retain the (very mild) maintenance burden of keeping the explicit line numbers in order to provide more robust testing.
For a general background, we apply the above prediff conversion in 50+ .prediff and …
> Update line numbers in .good for #24136

- modules/internal/Bytes.chpl
- modules/internal/BytesStringCommon.chpl
- modules/internal/String.chpl
- test/library/packages/DistributedBag/nqueens.chpl
- test/types/bytes/appendvalues.chpl
- test/types/bytes/tohex.chpl
- test/types/bytes/tohex.good
- test/types/string/appendvalues.chpl
- test/unstable/bytesStringAppendValue.chpl
- test/unstable/bytesStringAppendValue.good
- test/unstable/bytesToHexadecimal.chpl
- test/unstable/bytesToHexadecimal.good
This PR came about from [a Stack Overflow question about the performance of converting a hash to a hex string](https://stackoverflow.com/questions/77673067/is-there-a-way-to-string-format-a-runtime-determined-number-of-items-in-one-call). In particular, I noticed that we don't currently have a way to append a single numeric byte value to a `bytes` or similarly to append a single numeric codepoint value to a `string.`
This PR adds those mechanisms as unstable methods for now. Using these mechanisms, we can make a `toHexString` that is about 4000 times faster than the approach of repeatedly appending (e.g. with `buffHexString += try "%02xu".format(this.buff[i]);`). 
Additionally, this PR adds a `bytes.toHexadecimal` method that efficiently constructs a hexadecimal string/bytes representing …
> Add functions to append a numeric byte / numeric codepoint

- compiler/llvm/clangUtil.cpp
- test/compflags/unknownLlvmFlag.good
[designed by @riftEmber, typed up by me]
Prior to this PR, if the LLVM back-end's processing of `--ccflags` turned up any bad/unexpected flags, an error would be printed, but the Chapel compiler would continue.  As an example of that, the existing `unknownLlvmFlag.chpl` test would issue the LLVM error, then complete compilation, permitting the program to be run.  Here, we detect the presence of the the error when asking `clang` to process `--ccflags`, and halt the Chapel compiler as a result, which seems appropriate for an erroneous condition.
This change was motivated by the fact that the `--compiler-driver` mode invokes this check twice, so was generating the error message twice.  By having the first case halt after generating an error, both modes now behave the same and the error …
> Make clang checks of bad `--ccflags` fatal

- util/chplenv/chpl_libfabric.py
Fixes an issue where chplenv would crash with a python error if it could find find a system install of libfabric using pkg-config. This PR just adds a nicer error message that tells the user what the problem is and a possible solution.
Tested that with this change the error message is printed when no libfabric is found.
> Add check for a missing libfabric system install

- frontend/test/resolution/testTestPrimitives.cpp
CI checks didn't catch this one because I opened the PR before the error period, I suppose.
> Add a license comment to a new file

- tools/chapel-py/setup.py
- tools/chapel-py/src/chapel/visitor/__init__.py
Example Python code:
```Python
from chapel import *
from chapel.core import *
from chapel.visitor import *
from inspect import signature
from collections import defaultdict
@visitor
class Test:
@enter
def enter_named_decl(self, x: NamedDecl):
print("Entering a named decl with name " + x.name())
@enter
def enter_ident(self, x: Identifier):
print("Entering an identifier with name " + x.name())
@exit
def exit_ident(self, x: Identifier):
print("Exiting an identifier with name " + x.name())
@enter
def enter_opcall(self, x: OpCall):
print("Entering an op with name " + x.op() + ", and not visiting the children.")
return False
@exit
def exit_opcall(self, x: OpCall):
print("Exiting the op.")
context = Context()
asts = context.parse("fib.chpl")
Test().visit(asts)
```
This roughly mirrors Dyno's C++ …
> Add a 'visitor' API to chapel-py

- tools/chapel-py/src/method-tables.h
Adds the remaining uast accesor methods to the frontend python bindings, chapel-py.
List of classes added:
- Import
- Use
- As
- Include
- Require
- Interface
- Implements
- Try
- Catch
- Cobegin
- Select
- When
- Scan
- ExternBlock
- PrimCall
- Manage
- VarArgFormal
- ForwardingDecl
closes https://github.com/Cray/chapel-private/issues/5622
> Add remaining missing uast accessors to python bindings

- runtime/src/comm/ofi/comm-ofi.c
- runtime/src/topo/hwloc/topo-hwloc.c
- runtime/src/topo/none/topo-none.c
- test/runtime/jhh/colocales/Makefile
- test/runtime/jhh/colocales/README
- test/runtime/jhh/colocales/colocales.c
- test/runtime/jhh/colocales/colocales.chpl
- test/runtime/jhh/colocales/colocales.py
- test/runtime/jhh/colocales/ex2.xml
- test/runtime/jhh/colocales/hpc6a.48xlarge.xml
- test/runtime/jhh/colocales/m6in-dy-m6in32xlarge.xml
- test/runtime/jhh/colocales/sub_test
Generalizes NIC selection to handle NICs that aren't in a socket. The assignment is based on the locales' cpusets and distances to NICs, rather than on locales and NICs sharing sockets. Each locale is represented by the lowest common ancestor of its cpuset, and each NIC is represented by its lowest ancestor that has a cpuset. The distance between a locale and a NIC is the length of the path between them in the topology. The assignment process is a greedy algorithm that finds the shortest path and assigns that NIC to that locale. Then it repeats with the remaining locales and NICs until all locales have a NIC or there are no remaining NICs. If some locales do not have a NIC the entire process is repeated until all locales are assigned a NIC. This heuristic avoids sharing NICs unless there …
> Generalize NIC selection

- tools/chapel-py/examples/replace.py
- tools/chapel-py/scripts/generate-pyi.py
- tools/chapel-py/setup.py
- tools/chapel-py/src/chapel.cpp
- tools/chapel-py/src/chapel/__init__.py
- tools/chapel-py/src/chapel/replace/__init__.py
- tools/chapel-py/src/core-types-pernode.cpp
- tools/chapel-py/src/core-types.cpp
- tools/chapel-py/src/error-tracker.cpp
- tools/chapel-py/src/iterator-support.cpp
- tools/chplcheck/src/chplcheck.py
- tools/chplcheck/src/driver.py
- tools/chplcheck/src/lsp.py
- tools/chplcheck/src/rules.py
The years were showing much older initial dates. That was due to copy-pasting.
> Fix copyright starting years in chplcheck and chapel-py (they didn't start until 2023!)

- runtime/src/topo/hwloc/topo-hwloc.c
The NICs are sorted during NIC selection to ensure that all locales see them in the same order. Previously, they were sorted based on the hwloc `os_index`, which isn't guaranteed to be unique, and furthermore, the arguments to the comparison routine were dereferenced incorrectly. This should fix both of those problems, the former by sorting based on the PCI bus address.
> Sort NICs based on PCI bus address

- modules/packages/Sort.chpl
- test/compflags/ferguson/print-module-resolution.good
- test/library/packages/Sort/RadixSort/distributedRadixSort.chpl
- test/library/packages/Sort/correctness/SortTypes.chpl
- test/library/packages/Sort/correctness/two-array-radix-sort-bug.chpl
- test/library/packages/Sort/correctness/two-array-radix-sort-bug.good
- test/library/packages/Sort/performance/comparison/chapel-sort-older-radix-sort.chpl
- test/library/packages/Sort/performance/comparison/julia-sort-random.jl
- test/library/packages/Sort/performance/comparison/sort-random-rust/Cargo.toml
- test/library/packages/Sort/performance/comparison/sort-random-rust/src/main.rs
- test/library/packages/Sort/performance/comparison/sort-random.jl
- test/library/packages/Sort/performance/dist-performance.chpl
- test/modules/sungeun/init/printModuleInitOrder.good
This PR updates the `proc sort` in the `Sort` package module to use the two-array sort.
This PR:
* adds an optional `param` arguments that can request an in-place/lower-memory sort. The one requesting an in-place algorithm is `inPlaceAlgorithm` to avoid confusion with the fact that the `sort` call modifies the passed array in-place rather than returning a new an array. The one requesting a stable sort is just called `stable` but that currently leads to a compilerError about it being unimplemented.
* fixes a few bugs in the two-array sort code especially for records and arrays with idxType not `int`.
* rearranges the code in the Sort module to put the sample sort and distributed two array sorts into different modules so that we can avoid using Random and/or BlockDist on every compile …
> Update sort to use the faster two-array implementation

- compiler/codegen/codegen.cpp
- compiler/codegen/mli.cpp
- compiler/llvm/clangUtil.cpp
- compiler/main/driver.cpp
- compiler/util/files.cpp
Fix remaining bugs that came up in nightly testing when driver mode was turned on by default.
Fixes:
- Multilocale C interop failures, due to `gMultiLocaleLibServerFile` not being initialized in the makeBinary phase. This was getting set to a constant in the compilation phase anyways, so refactored to just always initialize it with the constant.
- `make-install-check` failures, due to a quirk causing `CHPL_RUNTIME_DIR` to be set incorrectly in sub-invocations for a prefix install. This occurs in `setChplHome`, which is also responsible for setting `CHPL_HOME` and the corresponding environment variable. However, if it detects `CHPL_HOME` is already set in an environment variable, it happens to skip the `CHPL_RUNTIME_DIR` adjustment logic, and it's always the case the environment variable …
> Driver mode nightly failure bug fixes

- frontend/lib/parsing/bison-chpl-lib.cpp
- frontend/lib/parsing/chpl.ypp
- frontend/lib/parsing/parser-error-classes-list.cpp
- test/errors/scope-resolution/fullImportPath.1.good
- test/errors/scope-resolution/fullImportPath.2.good
- test/errors/scope-resolution/fullImportPath.chpl
Fixes the locations reported by Chapel for Modules to represent the entire module, rather than just the name. This matches how other blocked constructs report their locations like `class` and `record`.
Ran full paratest w/wo comm
[reviewed by @DanilaFe]
> Fix issue with Module locations being incorrectly reported

- test/runtime/jhh/colocales/SKIPIF
Skip this test until I figure out why it's broken on Jenkins but not elsewhere.
> Skip broken colocales test

- compiler/include/resolution.h
- compiler/resolution/functionResolution.cpp
- compiler/util/misc.cpp
- test/functions/resolution/errors/printAdditionalErrors-1.all.good
- test/functions/resolution/errors/printAdditionalErrors-1.chpl
- test/functions/resolution/errors/printAdditionalErrors-1.compopts
- test/functions/resolution/errors/printAdditionalErrors-1.dflt.good
- test/functions/resolution/errors/printAdditionalErrors-1.pae.good
- test/functions/resolution/errors/printAdditionalErrors-2.chpl
- test/functions/resolution/errors/printAdditionalErrors-2.compopts
- test/functions/resolution/errors/printAdditionalErrors-2.good
This PR enables the existing compiler option `--print-additional-errors` to print errors that are being postponed, ex., when resolving copy initialization, such as chpl__coerceCopy and chpl__coerceMove, as in `var B = (an array slice);`.
The benefit is that this enables printing the call stack leading to such an error. When a postponed error is finally printed, if at all, the call stack is no longer available. Without a call stack, it is often impossible to detect the cause of the error without running the compiler under the debugger.
Next steps: have the compiler recommend compiling with `--print-additional-errors` when this can explain the final compilation error.
Testing: standard and gasnet paratests; distribution robustness suite.
> --print-additional-errors : another use

- test/library/packages/DistributedBag/nqueens.skipif
Follow-up to PR #23204.
Skip the new nqueens test on valgrind and cygwin testing configurations where it is timing out. We will still have basic testing of the data structure in these configurations with other tests.
> Skip nqueens on cygwin and valgrind test configs

- modules/internal/OwnedObject.chpl
- test/deprecated/deprecateOwnedBorrow.chpl
- test/deprecated/deprecateOwnedBorrow.good
Removed the `owned.borrow` type method, deprecated in #22997
Testing
> Remove deprecated owned.borrow type method

- compiler/codegen/codegen.cpp
Prevent trying to restore filenames from tmp file in compilation phase, which contains the invocation of `makeBinary` for GPU backend.
Follow up to https://github.com/chapel-lang/chapel/pull/24166.
Testing:
> Fix trying to restore filenames in compilation phase on GPU

- modules/packages/Sort.chpl
Follow-up to PR #24147.
This PR removes two halts if bulk transfer fails & uses the already existing fallback code in that case. These halts were coming up in nightly testing in two configurations that can be reproduced with:
```
./util/start_test  test/distributions/robust/arithmetic/modules/test_module_Search.chpl -compopts -sdistType=DistType.replicated
./util/start_test  test/distributions/robust/arithmetic/modules/test_module_Search.chpl -compopts -sdistType=DistType.cyclic
```
I think we probably want bulk transfer to work for Cyclic but we have issue #17764 for that.
> Remove two halts and use fallback code instead

- frontend/test/resolution/testInteractive.cpp
Adjusts the Dyno `parseInteractive` tool to re-run on `Return` input in addition to `Y`/`y`.
The tool runs once then prompts for input like so:
```
Would you like to incrementally parse again? [Y]:
```
To me the `[Y]` implies (by some familiar command-line tool convention) that `Y` is the default action if no input is specified, so I've always expected hitting return would cause it to run again. However, newlines are actually ignored as input, so hitting it does nothing; this seems like it might be unintentional since slightly further down in code we have `\n` written as one of the characters that would cause it to re-run, but that part of the condition isn't reachable. This PR changes the script to re-run on `\n` input.
I'll plan to bring this up to the Dyno team before merge since it …
> Parse again on return key in `testInteractive`

- util/buildRelease/testRelease
- util/cron/test-release.bash
Remove emailing code from `util/cron/testRelease` as it is undesired and redundant with the email sent by Jenkins.
Includes removing the `-debug` and `-cron` arguments for this script as they were used only to control emailing behavior.
Resolves https://github.com/Cray/chapel-private/issues/5763.
Testing:
> Remove emailer code from `testRelease`

- runtime/include/chplcast.h
- runtime/include/chpltypes.h
- test/types/complex/bradc/tupleToComplex.chpl
- test/types/complex/bradc/tupleToComplex.good
This updates the implementation of the _chpl_complexNNN() routines in the runtime which are used to convert a Chapel 2-tuple of reals into a complex.  Specifically, my rewrite tries to use the 'CMPLX()' initializer macros rather than math to initialize the complex values.  The motivation for this is to work around [an issue](https://chapel.discourse.group/t/complex-imaginary-multiplication/29534) in which inf/nan values would creep in due to an apparent [bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=48760).  See the output of the test added in this PR prior to this change to see the old, odd behavior.
When this macro isn't available (as with when using C++ compilers and potentially some others?  CI failed when I didn't have this option available), I am currently falling back to an …
> Improve how tuples are converted into complex values

- frontend/test/resolution/testTestPrimitives.cpp
- frontend/test/resolution/testTypePropertyPrimitives.cpp
This PR fixes some warnings that were treated as errors in the dyno tests. 
trivial test changes only, not reviewed.
(docs failures are unrelated and known to be caused by `chpldoc` dependency failures)
> fix size_t to int comparison and unused variable warnings in dyno tests

- modules/internal/ChapelGpuSupport.chpl
- modules/standard/GPU.chpl
- test/gpu/native/studies/bandwidth/p2p.chpl
- test/gpu/native/studies/bandwidth/p2p.skipif
This PR removes 'use GPU' from the internal module `ChapelGpuSupport`. Since `ChapelGpuSupport` is included in each compilation, its having 'use GPU' cased the `GPU` module to be included in each compilation as well. This is undesirable. With this PR, the `GPU` module is compiled only when used/imported from user code.
Implementation notes: this PR moves the implementation of `canAccessPeer()` and `setPeerAccess()` from `GPU` to `ChapelGpuSupport`. These are the only things from `GPU` that `ChapelGpuSupport` used. Now they are available without `use GPU`.
This PR also updates `test/gpu/native/studies/bandwidth/p2p.chpl` to use `canAccessPeer` and `setPeerAccess` from the GPU module instead of calling their underlying extern procs directly. This test now also passes under CHPL_GPU=cpu, …
> Remove 'use GPU' from ChapelGpuSupport

- test/runtime/jhh/cpuKinds/cpuKinds.py
For consistency with the output of other tests, the "[test: " line in the test output should not contain the initial "test/" directory, e.g. it should be [test: runtime/jhh/cpuKinds/cpuKinds.py], not [test: test/runtime/jhh/cpuKinds/cpuKinds.py].
> Fix "[test: " line in test output

- doc/Makefile.sphinx
- third-party/chpl-venv/chpldoc-requirements1.txt
- third-party/chpl-venv/chpldoc-requirements2.txt
- third-party/chpl-venv/chpldoc-requirements3.txt
chpldoc was failing to build because Sphinx is dropping support for versions older then 5.0 (by updating their dependencies to require later versions).  Update the version of Sphinx we rely on in chpldoc itself as well as in the Chapel sphinx domain.
This caused us to need to update the version of breathe we rely on to build the compiler documentation.  That version of breathe generates extra warnings for links that don't exist, so we need to temporarily turn off those warnings until the dyno subteam is able to resolve them.  Our hope is to restore these warnings quickly, so that we can ensure our documentation links work.
While here, I also updated several other Python dependencies that had newer versions.
Updated:
- MarkupSafe from 2.1.1 to 2.1.3
- Jinja2 from 3.1.2 to 3.1.3
- Pygments …
> Resolve chpldoc build failure with Sphinx and update dependencies

- compiler/codegen/cg-symbol.cpp
- compiler/include/codegen.h
- compiler/include/driver.h
- compiler/include/llvmDumpIR.h
- compiler/include/symbol.h
- compiler/llvm/clangUtil.cpp
- compiler/llvm/llvmDumpIR.cpp
- compiler/main/driver.cpp
- doc/rst/technotes/llvm.rst
- util/chpl-completion.bash
This PR adds a number of useful developer features for debugging LLVM backend issues.
Namely:
- Adds more stages to the existing `--llvm-print-ir-stage`
- Adds `--llvm-print-passes`
- when using the new pass manager (enabled in Chapel with LLVM 16+), allows dumping of the optimization pipeline used by the compiler
- Adds docs on printing and inspecting llvm passes using the new pass manager (enabled in Chapel with LLVM 16+)
Testing:
> Add developer oriented flags to help LLVM debug

- frontend/lib/CMakeLists.txt
- tools/chapel-py/README.md
- tools/chapel-py/scripts/generate-pyi.py
- tools/chplcheck/README.md
- tools/chplcheck/src/driver.py
- tools/chplcheck/src/rules.py
- tools/chpldoc/findUndocumentedSymbols.py
Grabbag of fixes to make chapel-py work on platforms with older toolchains.
- fix linker build issue with ChplFrontendShared, of which chapel-py is currently the only consumer
- The way ChplFrontendShared was previously built, it duplicated symbols, causing global objects to be duplicated as well. This was an issue for `rootContext`, where its destructor would be called twice and result in a double free.
- fix type hints in `generate-pyi`
- improve README
- remove uses of the walrus operator in python (`:=`)
> Grabbag of fixes to make chapel-py more portable

- runtime/src/comm/ofi/comm-ofi.c
The `CHPL_RT_COMM_OFI_EXPECTED_PROVIDER` environment variable specifies the name of the provider that should be chosen by the `ofi` communication layer. It is an error if the selected provider does not match this value. This variable is intended to be used during testing to ensure that the correct provider is chosen.
> Add CHPL_RT_COMM_OFI_EXPECTED_PROVIDER

- util/cron/test-hpe-cray-ex-ofi.bash
Verify that the `cxi` provider is selected when testing on HPE Cray EX machines by setting `CHPL_RT_COMM_OFI_EXPECTED_PROVIDER`. This is facilitate debugging an issue in which on some HPE Cray EX machines `fi_getinfo` sometimes does not return the `cxi` provider.
> Verify cxi ofi provider is selected when testing

- frontend/include/chpl/types/CPtrType.h
- frontend/lib/resolution/can-pass.cpp
- frontend/lib/resolution/resolution-queries.cpp
- frontend/lib/types/CPtrType.cpp
- frontend/test/resolution/testCPtr.cpp
This was the only missing conversion in Dyno -- non-const pointers can be safely converted to const ones.
This PR also tweaks the instantiation rules to allow `c_ptrConst(?t)` to be instantiated by `c_ptr(X)` etc.. This isn't present in production, but it doesn't seem explicitly ruled out -- the case just didn't seem considered.
> Add conversion rule from pointer to const pointer to Dyno.

- tools/chapel-py/src/core-types-pernode.cpp
- tools/chapel-py/src/core-types.cpp
- tools/chapel-py/src/core-types.h
- tools/chapel-py/src/method-tables.h
- tools/chapel-py/src/python-types.h
- tools/chpl-language-server/src/chpl-language-server.py
This PR does a few things:
* Makes sure that `nodeOrNullFromToId` is a query, so that repeated calls are memoized. 
* Allows AST node methods to return location objects (with some refactoring to help create Python location objects)
* Adds a method to `Dot` that returns its field location (the substring after the `.`)
* Uses the new `field_location` method to implement goto-def, hover, etc. for dot expressions. 
> Minor Python LSP tweaks

- modules/packages/Sort.chpl
- test/library/packages/Sort/correctness/SortTypes.chpl
Follow-up to PR #24147.
Fixes a problem where the test `test/domains/vass/arrays-of-domains.chpl` would leak memory. For some reason (that I did not dig in to), code like `var x = shallowCopyInit(src)` calls the usual initCopy when applied to domains. But, in the sorting code, we need it to not do that, so I added a `pragma "no copy"` to avoid it. (Note that such variables already need `pragma "no auto destroy"` in the sorting code).
Additionally, this PR removes testing for shellSortMoveElts (which is called within other sort code) from the test module SortTypes because this was making these test much slower, leading to timeouts.
Future Work:
* #16431 investigate "move" memory management for domains, which I worked around here
> Avoid a memory leak when sorting domains

- third-party/chpl-venv/c2chapel-requirements.txt
- tools/c2chapel/Makefile
Despite this seeming like a reasonable update, this caused c2chapel testing to break with multiple missing extern declarations.  Weird.
We should probably look into making it easier to run c2chapel testing, since the current job only runs on the vms and I was having some difficulty verifying it locally and on our normal testing machine
> Undo update to c2chapel's dependency

- test/runtime/jhh/colocales/SKIPIF
- test/runtime/jhh/colocales/colocales.py
It's not necessary to run the colocales test with `CHPL_COMM != none`. Also fixed the format of the "[test: " line in the output to not include the initial "test" directory so as to conform to the standard `sub_test` output.
> Don't run colocales test with multi-locales

- third-party/chpl-venv/test-requirements.txt
The version I grabbed actually required Python 3.8 (as opposed to some of these packages which say they do, but don't necessarily need that recent a version of Python).  Though we can drop our Python 3.7 testing, this is still a more recent version of filelock than we had been using before, so in the interest of getting testing back fully (especially since I put off upgrading Sphinx fully), take the path of least resistance until we have updated the versions of Python we are testing.
> Downgrade filelock depended on by start_test to a slightly older version

- util/cron/test-perf.chapcs.playground.bash
Switches playground to test main as the current config is not needed.
[not reviewed - trivial]
> Stop using perf-playground

- test/parallel/forall/blank-intents/array-intent-from-actual-error-task.chpl
- test/parallel/forall/blank-intents/array-intent-from-actual.chpl
Fixes a sporadic memory bag that showed up sporadically in our nightly tests every about 1 in 100 runs. The bug results from unstructured tasks trying to modify an array after that array has gone out of scope.
Fixed by synchronizing the unstructured parallel tasks created. Note that this PR also updates `array-intent-from-actual-error-task.chpl` to match, although this is a compile-only test that didn't technically need to be updated.
Test on failing test machine with `for i in {1..1000}; do ./array-intent-from-actual -nl 1 >/dev/null; echo $?; done` and saw no failures.
> Fix memory bug in default intents test

- test/gpu/native/noGpu/basicMem.comm-none.good
- test/gpu/native/noGpu/basicMem.good
This PR reacts to #24127 analogously to #24157, following the same argument in favor of changing the line numbers vs. introducing a prediff.
Additionally, it reflects a reduction in the allocation/freeing size of `[domain(1,int(64),one)] int(64)` from 168 to 160 bytes. I did not investigate where that comes from.
> Update line numbers in .good for #24127

- tools/chpl-language-server/src/bisect_compat.py
- tools/chpl-language-server/src/chpl-language-server.py
Improves the portability of chpl-langauge-server to work with python3 versions older than 3.10. We were relying on `bisect_right` with a `key` parameter, which was not added until 3.10. To work with older python3 versions, this PR implements `bisect_right` manually
> Improve chpl-language-server portability

- third-party/chpl-venv/test-requirements.txt
The old version was not compatible with Python 3.7, but this new version is still newer than the one we were previously using
Running a full paratest with futures
> Downgrade the version of argcomplete we're using

- runtime/src/comm/ofi/comm-ofi.c
Works around an issue causing timeouts due to hangs when running some Chapel programs with libfabric using EFA. Users will hit this is they run on AWS.
The workaround is purely a temporary solution, it just skips some cleanup code when the provider is EFA.
Tested `test/users/bachman/Beta_Diversity` on AWS, which would hang prior to this PR and no longer hangs with this PR.
> Workaround indefinite hang when COMM=ofi using EFA

- util/test/checkCopyrights.bash
Prevent `checkCopyrights.bash` exiting with error when no files are missing copyright.
With the addition of `set -e` in `util/test/checkCopyrights.bash` in https://github.com/chapel-lang/chapel/pull/24126, when the `grep` for files without copyright turns up no results, the resulting exit code 1 causes the script to fail. Since there are many `grep`s in this file and they are the core functionality, we might as well turn off `set -e` rather than manually ignore errors in each instance.
Follow up to https://github.com/chapel-lang/chapel/pull/24126.
Testing:
> Ignore no matches from `grep` in `checkCopyrights.bash`

- frontend/lib/parsing/ParserContext.h
- frontend/lib/parsing/ParserContextImpl.h
- frontend/lib/parsing/bison-chpl-lib.cpp
- frontend/lib/parsing/chpl.ypp
- tools/chapel-py/scripts/generate-pyi.py
- tools/chapel-py/src/chapel.cpp
- tools/chapel-py/src/core-types.cpp
- tools/chapel-py/src/core-types.h
- tools/chapel-py/src/method-tables.h
- tools/chpl-language-server/src/chpl-language-server.py
This PR implements a few extra features in the Python-based language server.
* It adds `Scope` objects to the Python API. This makes it possible for Python code to inspect scopes (currently, just listing used/imported modules in a scope). 
* It refactors the binary search code to be stored in a class, so that other things (definitions) can be binary searched via cursor position.
* It uses the used/imported modules from the given file to provide autocomplete suggestions for identifiers (currently not intelligent enough to filter based on type / `bla.`).
* It builds another segment list for _defined_ symbols, and uses that (and some additional bookkeeping) to find references _within a file_.
I'm planning on a refactor to keep track of workspace changes, so that _global_ 'find references' …
> Language Server Improvements: find references, basic autocompletion

- test/gpu/native/noGpu/basicMem.comm-none.good
- test/gpu/native/noGpu/basicMem.good
- test/gpu/native/noGpu/basicMem.prediff
This extends the prediff for basicMem.chpl to canonicalize the size of `[domain(1,int(64),one)] int(64)` in the "allocate"/"free" lines of the test's output.
In #24226 I changed basicMem.good to contain 160 instead of the previous 168 bytes in those lines. I did so based on the test behavior that I observed on my laptop. However apparently that size is platform-dependent because it is still 168 bytes in our nightly testing.
Since the test is not intended to lock in the size of the array, this PR makes the prediff replace any size between 100 and 199 bytes with "1nn".
> Prediff-out the array size in basicMem.good

- modules/standard/ChplConfig.chpl
- tools/chpl-language-server/src/chpl-language-server.py
- tools/chpl-language-server/src/symbol_signature.py
Adds support for chpl-language server to pretty-print functions when a user hovers over a reference to them.
Also removes extra semicolons from ChplConfig
> Add language server suppoprt to show function signatures

- third-party/chpl-venv/test-requirements.txt
I'm hoping this will be the last one to downgrade.  If not, I may just remove the Python 3.7 job, since we have the okay from some users that were bit by Python compatibility in the past.
Running a full paratest with futures
> Downgrade setuptools for Python 3.7 compatability.

- runtime/src/comm/ofi/comm-ofi.c
Clean up visibility bitmap usage by removing extraneous NULL checks.
> Clean up visibility bitmap usage

- modules/packages/ParallelIO.chpl
Fix a typo (`here.maxTaskpar`  -> `here.maxTaskPar`) in a couple of places in the parallelIO module.
> Typo fix in ParallelIO

- compiler/codegen/codegen.cpp
Fix python multilocale library compilation for driver mode.
Multilocale python compilation uses library mode, with library output to `libDir`. The `libDir` path gets set to the Python module name in `ensureLibDirExists`, which is hit a few times in the `compilation` phase. Although the `makeBinary` phase has access to the Python module name (since fix in https://github.com/chapel-lang/chapel/pull/24166), it tries to use the unset `libDir` without ever hitting `ensureLibDirExists`. Fix by running `ensureLibDirExists` in `setupDefaultFilenames` so it happens for the `makeBinary` phase as well.
Follow up to https://github.com/chapel-lang/chapel/pull/23930.
Testing:
(with and without `--no-compiler-driver`)
> Set `libDir` as part of `setupDefaultFilenames` for driver python multilocale

- test/studies/ssca2/main/SSCA2_main.ml-compopts
I think this got missed because it only happens in multilocale performance testing and because the test itself suppresses some warnings.
> Remove old flag from SSCA2 multilocale performance testing compiler options

- util/cron/test-linux64-python37.bash
Some of the packages that we've updated to in order to support chpldoc require Python 3.8.  We've asked users that were bit by dropping Python versions in the past and they are okay with dropping support for Python 3.7, so treat it like we treat our Python 3.5 and 3.6 jobs.
----
> Stop testing chpldoc in Python 3.7 job

- test/distributions/robust/associative/performance/COMPOPTS
- test/library/packages/Sort/correctness/COMPOPTS
- test/parallel/bundles/bundles.execopts
Follow-up to PR #24147. After that PR, we saw valgrind timeouts in several tests that do some sorting. This PR makes the valgrind testing more efficient by compiling with `--ccflags -O3` when valgrind testing is enabled. In my experiments, this makes running these tests under valgrind at least 4 times faster.
This PR also fixes a missing letter in a comment in another test that adjusts how it runs for valgrind testing.
> Address valgrind timeouts

- doc/rst/language/spec/interoperability.rst
This should be one of the last things needed for #22088, after Guillaume's documentation updates earlier.
Resolves #22088 
Thanks to Brad for pointing it out!
Letting CI testing double check the fresh doc build, but it looked fine locally
> Add a missing semi-colon to the external-procedure-declaration-statement

- util/chplenv/overrides.py
This PR adds a missing gpu variable to the list of known env variables in `overrides.py`. Previously, if this script encountered `CHPL_GPU_MEM_STRATEGY` in a `chplconfig` file it would emit a warning about an unknown variable name.
The problem would really only be visible if you had installed chapel or otherwise edited a `chplconfig` file to contain this key. 
TESTING:
[reviewed by @e-kayrakli - thanks!]
> add `GPU_MEM_STRATEGY` to list of Chapel variables in overrides.py

- util/cron/load-base-deps.bash
Switch to loading Chapel nightly test dependencies via new Spack install for Osprey.
Testing:
> Load deps from Spack install on Osprey

- frontend/lib/immediates/CMakeLists.txt
- frontend/lib/immediates/complex-support.c
- frontend/lib/immediates/complex-support.h
- frontend/lib/immediates/num.cpp
- frontend/lib/immediates/num.h
- test/library/standard/AutoMath/sqrtparams.suppressif
Follow-up to PR #24127.
After #24127, the new `sqrtparams` test started to fail on Mac OS X system. Upon investigating, I identified that the difference in behavior from what the test expects is due to differences in how `std::sqrt` is implemented for complex numbers in libc++ vs stdlibc++. Also, I noticed that the issue is limited to the C++ implementation of the complex square root.
This PR changes the implementation to use a C implementation of complex square root since it appears to have more reliable precision. Note that this C implementation required some workarounds for `CMPLX` not being available on all systems (as with PR #24184 and #24211). In particular, `CMPLX` does not seem to be available when using `clang` on Ubuntu 23.10, even though it is available with `gcc` on that …
> Adjust complex sqrt in compiler to use the C functions

- util/cron/test-no-compiler-driver.bash
Rename the `util/cron/test-monolithic.bash` script to `test-no-compiler-driver.bash` for clarity.
To be merged with https://github.hpe.com/hpe/hpc-chapel-ci-config/pull/1098 making the change in CI configuration.
> Rename nightly test script `test-monolithic.bash`->`test-no-compiler-driver.bash`

- util/chplenv/chpl_gpu.py
- util/chplenv/chpl_llvm.py
This PR adjust our environment scripts to use ROCm's LLVM for ROCm version > 5.
When our bundled LLVM is upgraded to 16, we should disallow `CHPL_LLVM=bundled`, but this PR doesn't do that.
Test:
> Use ROCm's LLVM as system LLVM

- util/chplenv/printchplenv.py
This PR adds `--csh` and `--bash` options for `printchplenv`, to allow users to paste its output into shell prompts/scripts. Here are sample outputs:
```
export CHPL_TARGET_PLATFORM=darwin
export CHPL_TARGET_COMPILER=llvm
export CHPL_TARGET_ARCH=x86_64
...
```
```
setenv CHPL_TARGET_PLATFORM darwin
setenv CHPL_TARGET_COMPILER llvm
setenv CHPL_TARGET_ARCH x86_64
...
```
These formats wrap a value in single quotes when it contains whitespace or might otherwise be interpreted by the shell.
Next steps:
* Cater for values containing single quote(s).
* Add an option to print only those variables that are set in the environment.
> [T]csh and bash output formats for printchplenv

- runtime/src/comm/ofi/comm-ofi.c
The Chapel MCM requires that any pending Puts and AMOs to all locales be made visible prior to performing a sequentially consistent AMO. Messaging ordering guarantees only apply to the target node of the AMO; we must call `forceMemFxVisAllNodes` to force visibility on all other nodes.
> Force visibility of pending writes on AMO in message-order-fence

- modules/internal/ChapelRange.chpl
This PR removes the `inline` annotation on `proc const range.this(range(?))` to fix a performance regression in `performance/bharshbarg/create-views`, most noticeably in Slice-1D, that was caused by #24154.
#24154 introduced the `inline` annotation on the underlying implementation of range slicing. This may have caused increased size of some generated functions and possibly missed optimization opportunities. This PR reverses this particular aspect.
Here is the relevant history of `inline` on `range.this()`. For a while we had:
```chpl
proc const range.this(other: range(?))
{
// the underlying implementation of range slicing
```
After [#21760](https://github.com/chapel-lang/chapel/pull/21760):
```chpl
inline proc const range.this(other: range(?))
{
return this.chpl_slice(other, …
```
> range.this() no longer 'inline'

- doc/rst/technotes/driver.rst
Make a few clarifications to the driver mode technote.
- Add a message to the "Note" section at the top of the driver technote pointing out that `--no-compiler-driver` will be going away at some point.
- Fix a sentence which incorrectly states the driver was turned on by default for 1.33 -- it was for 1.34.
- Note the names of the phases in the first paragraph.
Made with suggestions from @vasslitvinov , thanks!
[trivial doc update, not reviewed]
> Made driver technote clarifications

- test/gpu/native/studies/chop/chplGPU.skipif
Removing the unload-reload of Spack-installed `openssl` (added in https://github.com/chapel-lang/chapel/pull/22471) as it should no longer be needed with the new Spack install.
The underlying issue was some packages being loaded in Spack and expecting newer versions of shared libraries from other packages than the system installs offer. This should be fixed on the new install (https://github.com/chapel-lang/chapel/pull/24271) as all dependencies of the Spack packages are loaded and their library paths added to `LD_LIBRARY_PATH`.
[small test change to match Spack changes, not reviewed]
> Remove Osprey Spack openssl unload for ChOp testing

- compiler/AST/baseAST.cpp
Fix a bug where driver mode reports near-0 maximum AST size.
This was due to the maximum being emitted immediately after `makeBinary`, which runs in its own driver phase during which there is no AST. Fixed by emitting immediately after `codegen`, the final pass of the first phase.
Thanks @stonea for pointing out this bug.
Follow up to https://github.com/chapel-lang/chapel/pull/23930.
Testing:
> Fix maximum AST size reporting in driver mode

- tools/chapel-py/README.md
- tools/chapel-py/examples/replace.py
- tools/chapel-py/scripts/generate-pyi.py
- tools/chapel-py/setup.py
- tools/chapel-py/src/chapel.cpp
- tools/chapel-py/src/chapel/__init__.py
- tools/chapel-py/src/chapel/replace/__init__.py
- tools/chapel-py/src/chapel/visitor/__init__.py
- tools/chpl-language-server/src/chpl-language-server.py
- tools/chpl-language-server/src/symbol_signature.py
- tools/chplcheck/src/chplcheck.py
- tools/chplcheck/src/driver.py
- tools/chplcheck/src/lsp.py
- tools/chplcheck/src/rules.py
- tools/chpldoc/findUndocumentedSymbols.py
Removes the need for `chapel.core` from the python bindings, making all the C extension code visible from the top level module `chapel`. This hides some of the implementation details and opens up some possibilities for wrapping C types with python code.
> Remove need for `chapel.core` in python bindings

- tools/chpl-language-server/src/chpl-language-server.py
Adds support for LSP CodeActions to chpl-language-server. This allows users to auto-fix subsets of warnings in their code in the IDE.
Currently this has limited support for deprecations based upon regular expressions. This handles most simple deprecations like renamings, but is currently limited by what is resolved by dyno/chapel-py so this may not work for deprecated functions
This also adds support for GotoDeclaration, which for Chapel is the same as GotoDefinition.
> Add auto-fix warning support to chpl-language-server

- test/compflags/ferguson/munge-with-ids.good
- test/compflags/ferguson/munge-with-ids.prediff
Fixes a test which relies on a specific LLVM IR layout to be less sensitive to LLVM version
I saw this test fail when using LLVM 17, it now works with LLVM 17 and other LLVM versions
> Make munge-with-ids test less sensitive to llvm version

- modules/standard/Random.chpl
- test/classes/weakPointers/passiveCache.good
- test/unstable/randomModule.chpl
- test/unstable/randomModule.good
Improve the default seed generated for a `randomStream` by including the following pieces of information:
* process ID
* task ID
* locale ID
* current time
* bits from `/dev/urandom` (if available)
This extra information will significantly reduce the likelihood that two `randomStream`'s generated around the same time will have the same seed value.
Resolves: https://github.com/chapel-lang/chapel/issues/24178
> Improve default seed generation in Random module

- tools/chapel-py/src/core-types.cpp
- tools/chapel-py/src/python-types.h
This PR defines the to- and from- conversion for vectors of Python-convertible types. This makes it possible to return and accept lists of things in methods listed in `method-tables.h`. This is particularly useful for future work, such as returning formal-actual maps (which can be represented as a vector of indices). 
> chapel-py: allow accepting and returning lists of arbitrary types in methods

- tools/chpl-language-server/src/bisect_compat.py
- tools/chpl-language-server/src/chpl-language-server.py
This helps for things like inlay hints; whenever the server requests some information in the user's view, we can use two binary searches to compute the range.
> LSP: Add support for finding a range of elements given two document positions

- util/chplenv/chpl_llvm.py
- util/cron/test-gpu-ex-rocm-54.bash
This PR is a follow on to https://github.com/chapel-lang/chapel/pull/24195 and it is supposed to fix cases where we are using bundled LLVM whose `llvm-config` hasn't been built yet.
> Fix chpl_llvm.py for AMD GPU + bunded-but-not-built LLVM

- test/compflags/ferguson/munge-with-ids.prediff
Fixes test using sed which failed in Mac nightly testing since the `sed` command did not match.
Tested on Mac and Linux
> Fix test prediff to use more portable sed

- test/c2chapel/testStructs.c
- test/c2chapel/testStructs.chpl
- test/c2chapel/testStructs.good
- test/c2chapel/testStructs.h
- tools/c2chapel/c2chapel.py
Resolves #24167.
Adjust `c2chapel` to not skip a typedef for `foo` if we have only encountered a forward declaration for `foo` beforehand.
TESTING
> Adjust c2chapel to handle forward declared structs/unions

- modules/packages/Sort.chpl
- test/distributions/robust/arithmetic/modules/test_module_Search.chpl
- test/library/packages/Sort/RadixSort/distributedRadixSort.chpl
Follow-up to PR #24147.
This PR addresses two problems with the two-array sort that came up in testing:
1. The `twoArrayRadixSort` routine no longer handles distributed arrays, but it used to. PR #24147 changed this to move the dependency on Block to a module that isn't included by default, but that led to timeouts for programs expecting `twoArrayRadixSort` to do something reasonable with a distributed array. This PR makes the issue more apparent by issuing a compilation warning (although it will require other changes to Arkouda).
2. One of the optimizations / bug fixes in PR #24147 was to adjust the twoArrayRadixSort (and related functions) to allocate the scratch array without initializing the elements. However, I forgot to also tell the runtime that it could go ahead and register the …
> Fix sort issues revealed by Arkouda testing after two-array sort changes

- compiler/AST/symbol.cpp
- compiler/passes/scopeResolve.cpp
- frontend/include/chpl/resolution/resolution-types.h
- frontend/include/chpl/util/hash.h
- frontend/lib/resolution/VarScopeVisitor.cpp
- frontend/lib/resolution/resolution-types.cpp
- frontend/test/framework/CMakeLists.txt
- frontend/test/framework/testQueryEquivalence.cpp
This improves the ergonomics of Dyno-as-an-API. If I resolve a function call node, I implicitly know that its actuals map properly to its formals. However, until now, without constructing a brand-new `CallInfo` object, it was impossible to access formal information in Dyno. This was reflected in my efforts to get inlay hints in the LSP, where I was trying to mark each actual with the name of the formal it's passed to; I just couldn't do it.
This PR adjusts `MostSpecificCandidate` to contain a `FormalActualMap` when it's non-empty (i.e, when its `fn` is non-`null`). To reduce the memory footprint of this change (since all `ResolvedExpression`s have a `MostSpecificCandidates` value), this is implemented using a heap-allocated `owned` pointer. This pointer is copied when the map itself is …
> Store formal-actual maps in found candidates

- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/try-catch-analysis.cpp
- frontend/test/resolution/testCatch.cpp
Add support for writing catchless `try`/`try!` within functions marked `throws`. While here, also propagate types from child expressions of `try` to the `try` expression itself.
Reviewed by @arezaii. Thanks!
> dyno: Add support for catchless try/try! in throwing functions

- modules/packages/LinearAlgebra.chpl
- test/library/packages/LinearAlgebra/correctness/no-dependencies/solveLU.chpl
This PR addresses a concern raised in #24095 that LinearAlgebra's `solve()` modifies its second argument. The comments on that issue agree that ideally `solve()` should not modify its arguments.
With this PR, the actual arguments to `sort()` are no longer modified. It uses the solution proposed by @damianmoz in https://github.com/chapel-lang/chapel/issues/24095#issuecomment-1858606584. While there, mark the formals as passed by ref because there is no need to copy the actuals into the formals.
Next steps: see if we want to apply the explicit intent `const` or `const ref` to the formals of other functions in LinearAlgebra. Another thought: replace `var` with `const` for local variables that are not intended for modification, such as `x`, `y`, `z` in the `solve()`.
Testing: standard and …
> LinearAlgebra.solve() constant formals

- compiler/resolution/functionResolution.cpp
- doc/rst/language/spec/classes.rst
- test/statements/loops/CoforallDefaultInitBug.chpl
- test/statements/loops/CoforallDefaultInitBug.good
Resolves #21272.
Fix a bug that caused a generic class variable mentioned in a `coforall` to crash the program with an internal assertion.
Remove the internal assertion. It asserts that actuals passed to a task function are not generic, but it is possible for this to be the case if we are already in an error state. In that case, we should continue to the end of the pass rather than crash.
While here, adjust the class section of the spec to indicate that for a class type `C`, the expression `C` is taken to mean generic management except in the `new` expression, where it implies `owned C`.
TESTING
Reviewed by @vasslitvinov. Thanks!
> Fix a bug causing generic variables used in a `coforall` to crash compilation

- third-party/chpl-venv/chplcheck-requirements.txt
- tools/chapel-py/scripts/generate-pyi.py
- tools/chapel-py/src/chapel/__init__.py
- tools/chapel-py/src/core-types.cpp
- tools/chapel-py/src/core-types.h
- tools/chapel-py/src/method-tables.h
- tools/chapel-py/src/resolution.cpp
- tools/chapel-py/src/resolution.h
- tools/chpl-language-server/src/chpl-language-server.py
- tools/chpl-language-server/src/chpl-shim.py
This PR makes use of the changes in https://github.com/chapel-lang/chapel/pull/24283 to add some user-facing features. These features are:
* Support for (currently disabled due to editor quirks) for a user-provided configuration file (`.cls-config.toml`). This file can be used to enable to the resolver (off by default), which in turn allows for all the features listed below. The configuration options exposed in this file are also exposed by the executable as command-line flags.
* Labeling literal actuals to calls with their formal names. Thus, `f("Jackson")` gets rendered in VSCode as `f(firstName = "Jackson")`. 
* Showing the inferred type of a declaration if it doesn't have an explicit type.
* Go-to-type definition (currently only within a particular file). 
This PR also changes …
> LSP: make use of Dyno resolver to provide inlay hints and go-to-type-definition

- test/llvm/dbg-intrinsics/dbg-proc-declare.skipif
Skips an LLVM debug info test which fails with newer LLVM versions and `--fast`. This is because the newer versions completely optimize away a variable, and the test is checking that the debug info is emitted for that variable.
Test locally with `start_test --respect-skipifs -compopts --fast test/llvm/dbg-intrinsics/dbg-proc-declare.chpl`
> Skip debug test with `--fast`

- test/library/standard/List/initEquals/listInitEqualsArrayBug.future
Update `test/library/standard/List/initEquals/listInitEqualsArrayBug.future` with the issue number for the bug.
> Update future with issue number

- util/cron/test-gpu-ex-rocm-54.bash
Fixes a typo in a test config which caused nightly failures
> Fix typo in test config

- modules/packages/Sort.chpl
- test/library/packages/Sort/correctness/SortTypes.chpl
- test/library/packages/Sort/performance/sort-performance-explorer.chpl
This PR makes some performance adjustments to Sort.chpl:
* adjust `sort` to use the older in-place radix sorter for problems too small for TwoArrayRadixSort before creating the Scratch array (because it will not be needed for small subproblems). My experiments indicate using QuickSort in these cases is even better but we aren't quite ready to do that yet.
* added a skip-ahead mechanism for the two-array radix sort for when multiple key bytes are the same for all elements. To do this, made the `startbit` formal to `bucketize` use `inout` intent; so it might change the start bit being considered during the counting process (if all the data starts with the same pattern)
* it adds throttling for the case of sorting within a nested parallel region
The tables below contain data generated by …
> Some performance tuning for sorting

- compiler/optimizations/gpuTransforms.cpp
- util/devel/chplspell-dictionary
- util/devel/chplspell-dictionary.fileids.json
Update chplspell dictionaries
Without the change to `gpuTransforms.cpp`, the dictionary would need to include `uization` because it treats "GPUization" as GP + Uization. Thankfully the capitalization of "gpuization" is a better fit with the other occurrences of this word. While the dictionary already contains "ufunction" and "lcode" and some others in order to accept "CUfunction" and "CURLcode" et al. for the same reason, these are more benign than "uization" and also we cannot change them.
> Update chplspell dictionaries

- modules/internal/ChapelArray.chpl
- modules/internal/ChapelDomain.chpl
- modules/packages/Sort.chpl
This PR adds the `chpl_` prefix to `domainDistIsLayout()` in order to remove it from the public API.
domainDistIsLayout() was made public in #18829 so it can be used across the internal modules. We consider such addition a bug because this function has not received a design review and was/is not intended to be user-facing. This PR fixes that bug.
This also removes the intended-for-user comment added to domainDistIsLayout in #23664, as it is no longer needed.
> 'domainDistIsLayout' --> 'chpl_domainDistIsLayout'

- test/gpu/native/compilerDriver.suppressif
Suppresses a test which fails in some nightly configs due to invalid llvm ir.
> Suppress gpu test that tests the compiler driver

- modules/standard/Random.chpl
The recent improvements to default seed generation in the Random module were causing timeouts in a few tests that concurrently create many `randomStream`'s.
This is a temporary fix to correct those test timeouts. A more permanent solution is in the works.
> Temporary fix for random seed initialization timeouts

- test/gpu/native/compilerDriver.suppressif
Makes a suppressif more specific so it only suppresses the test config that causes the test to fail.
> Make suppressif more specific

- .gitignore
- test/library/packages/Sort/performance/comparison/sort-random-rust-rayon/.cargo/config.toml
- test/library/packages/Sort/performance/comparison/sort-random-rust-rayon/Cargo.toml
- test/library/packages/Sort/performance/comparison/sort-random-rust-rayon/src/main.rs
- test/library/packages/Sort/performance/comparison/sort-random-rust/.cargo/config.toml
- test/library/packages/Sort/performance/comparison/sort-random-rust/Cargo.toml
- test/library/packages/Sort/performance/comparison/sort-random-rust/src/main.rs
On my machine, Rust has almost the same performance now. Please update your blog post for a better comparison.
Why would you use the `rand` crate for random number generation and not `rayon` for parallelism?
`rayon` is written in 100% Rust. About the "Standard library" thing: Rust by design keeps its standard library as small as possible. Major crates like `rayon` are often maintained by the Rust maintainers themself. For `rayon`, the two main maintainers Josh Stone and Niko Matsakis are core Rust contributors. Niko is even a team leader of the language team: https://www.rust-lang.org/governance
> Rust sorting benchmark

- .gitignore
- test/library/packages/Sort/performance/comparison/.gitignore
- test/library/packages/Sort/performance/comparison/sort-random-rust-rayon/src/main.rs
- test/library/packages/Sort/performance/comparison/sort-random-rust/.cargo/config.toml
- test/library/packages/Sort/performance/comparison/sort-random-rust/src/main.rs
Follow-up to PR #24302 to adjust `test/library/packages/Sort/performance/comparison`
* use a subdirectory .gitignore since that is preferred to adjusting the top-level one
* include the parallel array generation as a commented-out alternative to keep the blog performance reproducible
* comment out some cargo configuration that makes it slower on the benchmark system
> Follow 24302 to further adjust Rust sort comparison

- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/resolution-queries.cpp
- frontend/test/resolution/testForwarding.cpp
- frontend/test/resolution/testOperatorOverloads.cpp
- frontend/test/resolution/testResolve.cpp
- modules/standard/CTypes.chpl
Implement resolution of functions with `pragma "last resort"` in Dyno.
Modeled off of how the production compiler resolves `last resort`s -- `last resort` candidates are kept aside and not considered unless no non-`last resort`s work. If they're needed, they are considered in groups starting from non-POI through each successive containing POI scope, stopping after any group that has any candidates. Includes handling of forwarded-to `last resort` methods, with forwards-to-forwards treated as less preferable.
This originally surfaced in https://github.com/Cray/chapel-private/issues/5863 as two identical `c_ptr(void)->c_ptr(T)` casts (one of which was last resort) being considered ambiguous by Dyno but not production.
Thanks @DanilaFe for help ensuring the resolution behavior for …
> Implement `pragma "last resort"` resolution in Dyno

- modules/standard/Random.chpl
This PR reinstates the use of `/dev/urandom` for default seed initialization (after https://github.com/chapel-lang/chapel/pull/24324), but ensures that each time the file is opened, only 8 bytes are loaded into the `fileReader`'s buffer.
This change will prevent programs that use many `randomStream`s with default seed values from "overwhelming" `/dev/urandom` by requesting too many bytes in a short span of time.
> Fix use of `/dev/urandom` in default seed initialization

- test/visibility/bug-22186.chpl
Adds the reproducer from https://github.com/chapel-lang/chapel/issues/22186 which has since been resolved.
Tested locally
> Add test for resolved visibility issue

- doc/rst/usingchapel/multilocale.rst
- runtime/src/launch/smp/launch-smp.c
- runtime/src/topo/hwloc/topo-hwloc.c
Add support for co-locales to the `smp` launcher. The `smp` launcher runs the locales on the local machine, thus when using the "-nl NxL" argument N must be one, otherwise it's an error.
> Add co-locale support to smp launcher

- frontend/include/chpl/resolution/resolution-queries.h
- frontend/include/chpl/types/QualifiedType.h
- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/resolution-queries.cpp
- frontend/lib/types/QualifiedType.cpp
- frontend/test/resolution/testResolve.cpp
- frontend/test/resolution/testSplitInit.cpp
Get resolving the `param` value of `param`s split-init'd at module level working.
Previously, https://github.com/chapel-lang/chapel/pull/24116 got some cases of resolving module-level split-inits working, but it did not fix the original motivating case from https://github.com/Cray/chapel-private/issues/5602. This PR resolves two bugs that prevented it from working:
- Previously, split-init would be skipped for variables that have a declared type, since there's no need to infer their type. However, for `param`s this meant we wouldn't get their `param` value, which is part of their type. Fixed by changing to skipping variables with declared type, _unless_ they are `param` and don't have a value yet.
- The implementation of module-level split-init adjustments is in `resolveModule`. But in …
> Resolve module-level split-init'd `param`s' values in dyno

- test/types/records/generic/issue-22011-resolve-warning.chpl
- test/types/records/generic/issue-22011-resolve-warning.good
- test/types/records/generic/issue-22011.bad
- test/types/records/generic/issue-22011.future
- test/types/records/generic/issue-22011.good
Resolves the future from #22011. This test gives both a warning and an error. Responding to the suggestion from the warning and adding a `(?)` causes the error to go away. This PR keeps the original test (locking in the error message) and adds a second test with the `(?)` fix.
Tested locally
Resolves #22011
> Resolve generic record future 

- compiler/optimizations/gpuTransforms.cpp
- test/gpu/native/assertOnFailToGpuize.3.good
- test/gpu/native/assertOnFailToGpuizeAttr.3.good
- test/gpu/native/errors/outeraccess.good
The error would say "call has outer variable access", but the thing that has the outer variable access is actually the function. So, add the call to the trace, but say that the _function_ is what has the outer variable access.
> Adjust GPUization error wording

- util/build_configs/cray-internal/setenv-xc-x86_64.bash
Resolves an issue in nightly testing due to a bug in gcc8.1 that prevents building LLVM 17. This bug exists in gcc 8.1 and 8.2, but the particular test system has gcc 9.3.
<details>
This particular bug comes from using an enum in a constant expression. See this compiler explorer example which tests multiple compiler versions: https://godbolt.org/z/7d68GK45n.
The original code that caused this problem was the `static constexpr fltSemantics = ...` definitions in `lib/Support/APFloat.cpp` in LLVM 17.
This is the same code from the above link, inlined here
```c++
enum class myEnum {
A, B
};
struct myStruct {
int i;
int j;
myEnum k = myEnum::A;
};
static constexpr myStruct foo = {1, 2};
myStruct get() {
return foo;
}
```
</details>
Tested manually on the failing system
> Avoid gcc 8.1 with xc testing

- compiler/etc/lldb.commands
- frontend/include/chpl/resolution/resolution-types.h
- frontend/include/chpl/types/type-classes-list.h
- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/can-pass.cpp
- frontend/lib/resolution/default-functions.cpp
- frontend/lib/resolution/prims.cpp
- frontend/lib/resolution/return-type-inference.cpp
- frontend/lib/types/Type.cpp
- modules/internal/ChapelLocale.chpl
- modules/standard/CTypes.chpl
This PR includes various bug fixes for dyno:
- Fixes name of ``c_fn_ptr``
- Silences errors for PRIM_IS_FCF_TYPE to simply return ``false`` for now.
- Correctly computes ``void`` return type of extern procs when no return type is declared
- basic support for "unmanaged" and "borrowed" type classes
- Modifies ChapelLocale implementation to avoid recursive resolution
- Avoids need to re-implement ``_anyManagedAnyNilable`` in dyno by using ``class``
- Implements default-init-then-assign for extern variables, which don't necessarily support ``init=``
- Fixes a minor bug for param for-loops where resolution was missing the typed signature
- Implement implicit conversions between vararg-tuples, reference tuples, and value tuples
- Support for ``.size`` on tuples, and allowing other methods on …
> Miscellaneous Dyno Fixes

- test/gpu/native/noGpu/assertOnGpu-do-assert.good
- test/gpu/native/noGpu/assertOnGpu.prediff
The error message has improved, but I didn't catch the change because I was running a paratest on GPU-enabled machine.
> Fix cpu-only test for assertOnGpu

- runtime/src/chpl-gpu.c
This PR fixes another batch of `printf` issues which occur only on some platforms and compilers. In particular, `lu` is not always a proper format specifier for 64-bit integers, since on some platforms they are long longs (two 'long's there!). We've dealt with this before (https://github.com/chapel-lang/chapel/pull/23936).
> Fix compilation errors in runtime from improper use of '%lu'

- compiler/optimizations/gpuTransforms.cpp
- test/gpu/native/errors/badblocksize.chpl
- test/gpu/native/errors/badblocksize.good
A user coming from CUDA might think that they need to set the block size using a function call before calling the loop:
```Chapel
setBlockSize(1024);
foreach a in A do a+= 1;
```
However, `setBlockSize` is actually a special function that the compiler recognizes and handles. In the case above, the function is not in a format that the compiler expects, resulting in an internal error. This PR simply improves the error messages to explain what's wrong. 
> Emit non-internal errors when `setBlockSize` is used outside of a GPU loop

- frontend/test/resolution/testTypePropertyPrimitives.cpp
Designated initializers are awesome, but not technically part of the standard, so they get us in hot water with older compilers.
- `make test-frontend`
> Fix use of designated initializers in testTypePropertyPrimitives.

- test/gpu/native/diags.prediff
- test/gpu/native/reduction/stringError.prediff
- test/gpu/native/savec.prediff
- test/localeModels/gbt/maxTaskPar.prediff
- test/runtime/gbt/numThreadsSymbolicLogical.prediff
- test/runtime/gbt/numThreadsSymbolicPhysical.prediff
- test/studies/lsms/shemmy/m-lsms.par-forall.prediff
'\+' is a GNU extension and doesn't work on some platforms, including macOS. Replace it with the standard `*` using the equivalence `a+` <-> `aa*`.
> Remove uses of '\+' from invocations of sed.

- util/cron/test-perf.gpu-rocm.bash
This should fix the performance testing for ROCm 4. The problem was, one of our dependency scripts is setting `CHPL_LLVM_CONFIG=$(which llvm-config)`. When it is run, we mustn't have the `rocm` module loaded, because then we end up choosing ROCm's LLVM. We don't want that for ROCm 4.x.
This PR adjusts the test config.
> Load the rocm module late in a config to avoid picking wrong system LLVM

- util/cron/test-gpu-cpu.bash
https://github.com/chapel-lang/chapel/pull/24137 checked in some code that broke some distributed array cases in `release/examples`. This PR disables testing in that directory until we have a solution for the problem.
See https://github.com/Cray/chapel-private/issues/5926#issuecomment-1933054368 for more context.
My task for fixing the underlying issue: https://github.com/Cray/chapel-private/issues/5957
> Stop testing release/examples with cpu-as-device until we fix an issue

- make/compiler/Makefile.gnu
Turns off `deprecated-declarations` when compiling with llvm 11 and 12. This PR takes the approach of using `-Wno-`, rather than using `-Wno-error=` as the amount of warnings took over the output.
Tested build on system with llvm 11
> Avoid deprecation warnings with llvm11 and llvm 12

- runtime/src/gpu/amd/gpu-amd-reduce.cc
Fixes an issue in nightly testing where a C++ version upgrade caused hip calls in the runtime that were missing a `ROCM_CALL` wrapper to start failing.
Tested build on nightly test system with rocm 5.4
> Wrap runtime hip calls to catch errors

- modules/packages/CopyAggregation.chpl
Updates DstAggregator.copy to take 'this' by ref, avoiding a deprecation warning about inferring default intents.
> Take 'this' by ref in DstAggregator.copy

- doc/rst/language/spec/variables.rst
The docs now reflect the DCE behavior for split-init and copy elision in pull request #24080. I added more examples and reformulated the exceptions for clarity. It should now be a bit easier to understand when copy elision and split-init do not apply. Once reviewed, I'll wait until the DCE pull request is merged to merge this one so that the docs reflect the compiler behavior.
> Documentation updates for split-init and copy elision

- frontend/lib/uast/post-parse-checks.cpp
- test/unstable/localBlock.chpl
- test/unstable/localBlock.good
As discussed in https://github.com/chapel-lang/chapel/issues/24198, marking `local` blocks as unstable.
Added a simple test.
> Mark local blocks as unstable

- modules/standard/IO.chpl
- test/library/standard/IO/FileReaderOrWriterGetFile.chpl
Resolves #23066.
Add the `getFile()` method to the `fileReader` and `fileWriter` records. This method gets the underlying file the reader or writer is using.
The methods are marked as `@unstable` and indicate they may change based on feedback. The `@unstable` tag can be removed after a final review has occurred. The methods are named `getFile()` instead of `file()` due to name conflicts with the `IO.file` type that are a hassle to fix.
This PR is a patch from @mppf that has been adapted. Thanks, Michael!
TESTING
Reviewed by @lydia-duncan. Thanks!
> Add 'getFile()' to 'fileReader' and 'fileWriter'

- doc/rst/language/spec/variables.rst
One error was caused by indentation errors. The other comes from param-folding on select statements that will need more exploration to understand. Removed and will re-add at a later date.  
---
Signed-off-by: Brandon Neth <brandon.neth@hpe.com>
> Quick-fix for spectests failure.

- compiler/optimizations/gpuTransforms.cpp
The bad `set blockSize` primitive gets copied during GPU specialization, which leads to duplicate errors about it. Simply stop warning if the bad primitive lives in a GPU specialization -- for it to be "bad", it must be outside of a loop, and if it's outside of a loop, it won't be removed or modified in the non-specialized function. Thus, the warning will be issued elsewhere.
> Fix duplicate blockSize errors under GPU specialization

- modules/packages/Sort.chpl
This PR updates the docs comment for `proc sort` to:
* make a correction because quickSort is parallel now
* use the term "improved quick sort" to avoid an interpretation that it is Hoare's original quickSort.
See https://chapel.discourse.group/t/comparing-standard-library-sorts-the-impact-of-parallelism/30411/4
Open Question:
* should it, when describing the quick sort, cite Engineering a Sort Function (1993) by Jon L. Bentley , M. Douglas McIlroy ? Citing this in the `proc sort` docs about the current implementation seems like including more information than is needed / necessary there, but we could do it. I don't have a similar radix sort paper to reference at the ready, either.
* for now I opted not to include this reference in the implementation …
> Update proc sort docs about quick sort

- test/library/standard/Random/elliot/testBadNth.compopts
`test/library/standard/Random/elliot/testBadNth` was failing in a test config that uses `--fast` because it relies on checks being enabled. This PR turns on checks for that test.
> Fix `Random` test failure for `--fast` config

- frontend/test/framework/testRecursionFails.cpp
Cast boolean operands to `&` in `testRecursionFails` to ints, to avoid warnings with some compilers.
Compiling `testRecursionFails` fails on my system since https://github.com/chapel-lang/chapel/pull/24321 with this error:
```
/Users/rift/chapel/frontend/test/framework/testRecursionFails.cpp:166:11: error: use of bitwise '&' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
res = queryF(context, callFFirst, runHandler) &
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
&&
/Users/rift/chapel/frontend/test/framework/testRecursionFails.cpp:166:11: note: cast one or both operands to int to silence this warning
```
I see this didn't come up in CI checks on that PR and assume it is compiler version specific. Casting to int should avoid the error for compilers that care about it without …
> Avoid boolean `&` warning in `testRecursionFails`

- frontend/include/chpl/resolution/disambiguation.h
- frontend/include/chpl/resolution/resolution-queries.h
- frontend/include/chpl/resolution/resolution-types.h
- frontend/lib/resolution/disambiguation.cpp
- frontend/lib/resolution/resolution-queries.cpp
- frontend/lib/resolution/resolution-types.cpp
Replace usage of `CandidatesVec` and `ForwardingInfoVec` with a new `struct CandidatesAndForwardingInfo` that combines the two, as they are nearly always used together.
Use of the forwarding info part of `CandidatesAndForwardingInfo` is optional since sometimes we don't care about it.
Follow up to https://github.com/chapel-lang/chapel/pull/24282.
Testing:
> Unify `CandidatesVec` and `ForwardingInfoVec` into `CandidatesAndForwardingInfo`

- test/runtime/jhh/misc/Makefile
- test/runtime/jhh/misc/misc.py
- test/runtime/jhh/misc/sub_test
- test/runtime/jhh/misc/tester.c
- test/runtime/jhh/misc/tester.chpl
- test/runtime/jhh/topos/ex2.xml
Add tests that inaccessible cores and threads are handled correctly. Currently, there are two tests that fail because of issue [24371](https://github.com/chapel-lang/chapel/issues/24371)
> Add inaccessible cores/threads tests

- test/gpu/native/distArray/SKIPIF
This PR adds a somewhat wonky SKIPIF to stop testing some distributed array tests with AMD GPUs. The tests in question fail in a way that I don't understand and not reproducible with ROCm 5.4. As we are planning to steer away from ROCm 4, I choose not to invest more time towards understanding the problem that doesn't exist with newer ROCms.
Test:
> Add a SKIPIF to stop running some distributed array tests with ROCm 4

- util/cron/syncPerfGraphs.py
Our webhost changed the name of the server where we synchronize module documents and graphs.   This PR changes the python script to point at the correct server.
> Update dreamhost server name

- tools/chpl-language-server/src/chpl-language-server.py
Improves the InlayHints for types to work like other symbols. This allows users to hover over the inlay and see documentation information, as well as supporting goto definition/
Also adds symbol highlighting, so if a user selects 1 symbol all of the symbols in the file are also highlighted
> Improve language server inlays and symbol highlighting

- test/studies/1brc/CLEANFILES
- test/studies/1brc/SKIPIF
I mistakenly assumed that CLEANFILES ran before rather than after tests and accidentally wrote it to remove the input dataset for this test just before we need it.  I've updated the file to not do that.
Along the way I also made some changes to the SKIPIF so we don't have to redownload and rebuild the input dataset between each test.
> fix nightly testing for 1brc

- test/arrays/stonea/genericElementArray.future
Promote a future to do with generic array types that passes after #24415.
> Promote passing future

- test/gpu/native/distArray/blockUseInFunction.future
This PR makes an existing test a future. The bug in question is captured in https://github.com/chapel-lang/chapel/issues/24429.
> Make a distributed array test a future

- tools/chpl-language-server/src/chpl-language-server.py
A tuple is a `CompositeType`, but it does not have a `decl` AST node. Thus, `None` slips into the `get_tooltip` method, and causes an error. This PR guards against `None` here. The same issue does not occur in regular `get_tooltip` because it relies on 'to-segments', which are guaranteed to have a node they refer to.
> Fix the 'hover over inlay' hint for tuples.

- util/cron/test-hpe-cray-ex-ofi.bash
On a HPE Cray EX test machine cxi services sometimes die expectedly. The probability of this happening appears to be proportional to the size of the heap. Limit the size of the heap to 16GB via CHPL_RT_MAX_HEAP_SIZE as a larger heap is not needed by the tests and it reduces the chance of spurious test failures.
> Set CHPL_RT_MAX_HEAP_SIZE

- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/resolution-types.cpp
- frontend/test/resolution/testResolve.cpp
- frontend/test/resolution/testResolverVerboseErrors.cpp
Add support for resolving calls to the `this` method of a field in Dyno.
If there's a field matching the name called, this implementation will try to resolve it as a `this` call and fail otherwise; else, try to resolve as a normal method call. It doesn't support cases where a field and a method have the same name, however in https://github.com/chapel-lang/chapel/issues/24376 we decided to consider that illegal anyways.
Resolves https://github.com/Cray/chapel-private/issues/5923.
Testing:
> Dyno resolve calls to `this` on fields

- .github/workflows/CI.yml
- .github/workflows/email.yml
Modify the Github Actions email-on-merge workflow to cut off the git diff output at 1000 lines, including a note if it was truncated.
Job https://github.com/chapel-lang/chapel/actions/runs/7907690909/job/21585278415?pr=24417 shows this working with a temporary patch to let it do a dry run on an unmerged PR. Click into the step "Get merge log" to see diff output with max 2 allowed lines.
Resolves https://github.com/Cray/chapel-private/issues/5915.
Testing:
> Set a maximum number of diff output lines in email workflow

- compiler/llvm/clangUtil.cpp
- test/llvm/llvmDebug/llvmDebug_test.py
- test/llvm/llvmDebug/sub_test
Resolves #24088.
This PR adjusts LLVM debug symbol generation on OSX to emit a standard `.dSYM` archive. It also adjusts a test for debug symbols so that it can run on OSX in addition to linux64.
The archive is created by invoking LLVM's `dsymutil` on the final binary before it is moved into the user view. In order to get this patch to work, I had to rewrite `moveResultFromTemp` to consider directories in addition to files.
TESTING
> Emit a `.dSYM` archive on OSX when generating LLVM debug symbols

- frontend/lib/parsing/ParserContext.h
- frontend/lib/parsing/ParserContextImpl.h
- frontend/lib/parsing/bison-chpl-lib.cpp
- frontend/lib/parsing/chpl.ypp
- tools/chapel-py/src/method-tables/uast-methods.h
- tools/chpl-language-server/src/chpl-language-server.py
Fixes the rename feature of the language server by improving how decl names are noted by the parser.
Cases fixed by this PR:
- variables `var x = 10;`
- functions `proc foo()`
- type query `proc f(x: ?t)`
- var args `proc f(x: int...2)`
- loop indicies `for i in 1..10` and `for (j, k) in zip(1..10, 1..10)`
- task intents `with (ref A)`
- reduce intents `with (+ reduce A)`
- interfaces `interface A {}`
This also changes how CLS uses `name_location`, by making it fall back to `location` if there is no `name_location`.
Since the parser was touched, ran a full paratest
> Improve decl name reporting from the parser

- runtime/include/chpl-topo.h
- runtime/src/arg.c
- runtime/src/topo/hwloc/topo-hwloc.c
- test/runtime/jhh/colocales/colocales.c
- test/runtime/jhh/colocales/colocales.py
- test/runtime/jhh/colocales/sub_test
Allow the "-nl NxL" argument to have a suffix so it is now of the form "-nl NxLt". The 't' suffix specifies the type of architectural feature in which the co-locales should run. An 's' suffix indicates that co-locales should run on separate sockets, 'n' indicates separate NUMA nodes, 'c' indicates separate cores, and '$' indicates separate level 3 caches. Thus specifying "-nl 1x2s" will create two co-locales on a single node, each running in its own socket. In this example it is an error if the node has fewer than two sockets. If the node has more than two sockets the extra sockets will be unused.
> Add support for co-locale suffix

- tools/chpl-language-server/src/chpl-language-server.py
This PR modifies the 'use tracking' aspect of the language server to lift uses to the "dyno context" level. Since Dyno contexts are created such that one context is shared among multiple files compiled together, this leads to a "workspace-wide rename" functionality. 
The PR works by replacing the `Dict[NodeId, List[Reference]]` with a `Dict[NodeId, ReferenceList]`, where `ReferenceList` is a new class. The `ReferenceList` class is _also_ inserted into the "dyno context" container, also associated with a `NodeId`. The context-level container is `Dict[NodeId, List[ReferenceList]]`, containing reference lists from multiple files. By making the `ReferenceList` object be shared between the `FileInfo` and the context container, so when the `FileInfo` is updated, so is the corresponding entry in …
> Implement whole-workspace reference tracking and update existing features to make use of it

- tools/chplcheck/README.md
- tools/chplcheck/src/chplcheck.py
This PR adds support for user-defined linting rules in chplcheck. This allows a Chapel developer to create and maintain their own set of custom linting rules for chplcheck outside of the chapel-py source tree.
> Add support for user-defined lint rules

- compiler/llvm/llvmExtractIR.cpp
Fixes `--llvm-print-ir` when using llvm 17. The passes that strip unnecessary symbols where being built but never run.
Resolves #24448
> Fix `--llvm-print-ir` with llvm 17

- compiler/llvm/clangUtil.cpp
This PR disables generation of OSX `.dSYM` debugging archives when compiling Chapel programs with `--library`. Libraries can produce `.a` archive files which the `dsymutil` tool does not understand how to unpack directly. Enabling debug symbols for libraries under OSX is future work.
> Disable generation of '.dSYM' archives when compiling with '--library'

- modules/internal/String.chpl
- test/classes/weakPointers/concurrentUpgrades.chpl
- test/classes/weakPointers/initWeakPtr.chpl
- test/classes/weakPointers/passiveCache.skipif
- test/io/serializers/unstableWriting.skipif
- test/unstable-keyword/promotionCall.skipif
- test/unstable/BlockFactoryMethods.skipif
- test/unstable/Math/unstableNearbyint.skipif
- test/unstable/Math/unstableRint.skipif
- test/unstable/Time/timezones.compopts
- test/unstable/const-intent/arrayField.skipif
- test/unstable/unstableScans.skipif
We were seeing testing failures with gasnet and valgrind as a result of expanding the indirect modification check to apply to arguments with the default intent.
Some of the failures were due to accidentally overwriting a string's locale field.  The original locale field was restored, and the gasnet failures related to it were resolved.  Thanks to Michael for helping to track down this cause.
Some of the failures were due to detecting actual indirect modification.  In a couple of cases, this was rectified by explicitly allowing it, in the remainder it was rectified by skipping the test in those settings (where the justification for timezones was because we are not particularly worried about this feature and the justification for the array const intent test was because more work will be …
> Fix nightly failures with the expanded indirect modification check

- tools/chpl-language-server/src/chpl-language-server.py
- tools/chpl-language-server/src/symbol_signature.py
Add experimental type and param value resolution to the existing hover capability in chpl-language-server. This is enabled when `--resolve` is used.
This PR also includes a substantial rewrite of SymbolSignature, which should allow for more customization in the future 
> Use resolution when hovering over a symbol in chpl-language-server

- tools/chapel-py/src/method-tables/uast-methods.h
- tools/chpl-language-server/src/chpl-language-server.py
This PR implements support for call hierarchies. In doing so, it makes the following changes:
* Tweaks the id-to-instantiation list to use a `Dict`, which makes it preserve insertion order. This helps ensure that within a particular generation, indices into that list are constant.
* Adjusts the 'Dict' to also include call information for each instantiation, as well as the relevant instantiation if the call itself was made from an instantiated function. This helps compute 'incoming calls' for each function.
* Adjust the instantiation list to also store concrete function signatures. I leave it as future work to rename the "instantiations" field (and related accessors) to avoid implying that only generic instantiations are stored. The reason this change is needed is to provide "incoming …
> LSP: add support for call hierarchy

- compiler/codegen/cg-expr.cpp
This PR relaxes the restriction on #24455 that we could only codegen sqrt and abs directly to LLVM IR in non-strict floating point mode. Based on discussion in #24464, this PR relaxes that.
Tested locally
> Relax floating point restrictions on sqrt and abs optimization

- Dockerfile
This PR tweaks our main `Dockerfile` somewhat. In particular, it:
1. Splits the build into several steps. Currently this doesn't do much to affect cache behavior, because of #24397. However, it's cleaner, and if we ever fix the `COPY . .` thing, that should help things.
2. Adds `chapel-py-venv`, `chpl-language-server`, and `chplcheck` to the Dockerfile. This makes it possible to use `chpl-language-server` and `chplcheck` from inside the Docker image. This is helpful for cases like GitHub codespaces, where editor support would rely on these tools.
~~This PR depends on https://github.com/chapel-lang/chapel/pull/24384 and https://github.com/chapel-lang/chapel/pull/24393, which makes the diff huge. The actual changes in this PR specifically are to `Dockerfile`~~. They have merged!
In a team …
> Minor docker tweaks

- frontend/include/chpl/uast/FunctionSignature.h
- tools/chapel-py/src/chapel.cpp
- tools/chapel-py/src/core-types-gen.cpp
- tools/chapel-py/src/core-types-gen.h
- tools/chapel-py/src/core-types.cpp
- tools/chapel-py/src/core-types.h
- tools/chapel-py/src/generated-types-list.h
- tools/chapel-py/src/iterator-support.cpp
- tools/chapel-py/src/iterator-support.h
- tools/chapel-py/src/method-tables.h
- tools/chapel-py/src/method-tables/core-methods.h
- tools/chapel-py/src/method-tables/type-methods.h
- tools/chapel-py/src/method-tables/uast-methods.h
- tools/chapel-py/src/python-types.h
- tools/chpl-language-server/src/chpl-language-server.py
- tools/chplcheck/src/rules.py
This PR makes some changes to the method tables and marshaling API to generate better (Python) type information about the types exposed by the python bindings. Importantly, these changes __only affect the types as reported by the generated .pyi` file__: this change affects developers who program using `chapel-py`. The changes are as follows:
* Allow returning subclasses (e.g. `IntLiteral*`) instead of the parent class (e.g. `AstNode*`) where appropriate. This makes it possible to narrow the types of methods that are known to return certain subsets of the class hierarchy: `Function.formal(i)` now reports returning a `chapel.Decl` instead of a `chapel.AstNode` on the Python side.
* To make use of X-macros for "all generated types", this required some changes to said X-macros (adding …
> chapel-py: various changes to narrow the Python types listed in .pyi

- frontend/include/chpl/types/CompositeType.h
- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/VarScopeVisitor.cpp
- frontend/lib/resolution/can-pass.cpp
- frontend/lib/resolution/disambiguation.cpp
- frontend/lib/resolution/intents.cpp
- frontend/lib/resolution/prims.cpp
- frontend/lib/resolution/resolution-queries.cpp
- frontend/lib/types/CompositeType.cpp
- frontend/lib/types/Type.cpp
- frontend/test/resolution/testCanPass.cpp
- frontend/test/resolution/testDisambiguation.cpp
- frontend/test/resolution/testTuples.cpp
- frontend/test/resolution/testTypeOperators.cpp
This PR includes a number of fixes for dyno resolution bugs encountered while trying to resolve "Hello World":
- Support for chpl_localeID_t and PRIM_ON_LOCALE_NUM
- Fix "can pass" bug that allowed passing complex to real
- Allows c_string in certain primitives
- Implement PRIM_STRING_CONCAT for param values
- Implement casting from type to string (e.g. ``x.type : string``)
- Implement 'this' indexing for tuples with param indices
- Fix some minor mis-uses of CallInfo and MostSpecificCandidates
- Fix an ID-related bug for calls like ``MyModule.foo()``
- Removes a workaround for the ``kind`` field that was recently removed from fileReader/Writer
Testing:
> Miscellaneous dyno fixes in support of "Hello World"

- test/unstable/const-intent/arrayField.skipif
It has inconsistent behavior, but we intend to expand the check on arrays anyways, so skip it until we have done that expansion.
Double checked that the skipif modification was respected in `--no-local` testing
> Skip this test in --no-local runs

- test/studies/1brc/concurrentMapVer.skipif
The concurrentMap module has a memory leak bug. This PR skips the concurrent map version of the 1BRC test for the memleaks and valgrind configs.
> Skip concurrentMap 1BRC implementation for memleaks testing

- runtime/src/topo/hwloc/topo-hwloc.c
- test/runtime/jhh/colocales/colocales.c
If the number of co-locales on a node equals the number of an architectural feature (sockets, NUMA domains, level 3 caches, or cores), then the co-locales will be bound (confined) to the feature. Thus, '-nl 3x2' on nodes with two sockets will run each co-locale in its own socket.
> Implicitly bind co-locales to architectural features

- util/chplenv/printchplbuilds.py
Gasnet builds now include `GASNET_VERSION` in the path. This is to support GASNet-ex.
> Gasnet builds now include GASNET_VERSION in the path

- frontend/lib/parsing/bison-chpl-lib.cpp
- frontend/lib/parsing/chpl.ypp
- tools/chpl-language-server/src/chpl-language-server.py
- tools/chplcheck/src/lsp.py
Improves how chplcheck shows warnings on NamedDecl to use `name_location`. This makes the warnings less distracting and look better in an editor for a user.
Before:
After:
Passed full paratest
> Improve how chplcheck shows warnings on NamedDecl

- compiler/passes/convert-uast.cpp
- test/functions/Issue24493.chpl
- test/functions/Issue24493.good
Resolves #24493.
Fix a bug that caused the compiler to crash when compiling code that used nested functions as call actuals. We walk nested functions twice when checking for fixups (and thus note fixups contained in them twice). Note the initial fixup performed in addition to additional fixups to avoid triggering an internal assertion.
TESTING
> Fix compilation bug involving nested functions

- doc/rst/tools/mason/guide/submitting.rst
a small but imho nice change.
I find the word "gatekeepers" to convey some negative vibes (*) and I think "maintainers" is much more appropriate and inclusive, sounds to fit better mason open-source community nature :)
(*): I am not a native speaker, so can be wrong, but some quick googling also seemed to confirm my impression on the negative connotation.
> change gatekeepers -> maintainers

- test/studies/1brc/SKIPIF
- test/studies/1brc/wget.out
The 1BRC tests are timing out under the valgrind config. This PR skips them when `CHPL_NIGHTLY_TEST_CONFIG_NAME==valgrind`.
> Skip 1BRC tests in valgrind config

- test/classes/weakPointers/concurrentUpgrades.skipif
I had thought changing the argument to the function explicitly would be sufficient but forgot that the function also contained a coforall, so it still needs to be skipped.
Copied the skipif from one of the other tests in the directory
> Also skip this test for valgrind due to const intent warnings

- test/users/engin/context/basicArrayHoist-link-for-memleaks.execopts
- test/users/engin/context/basicArrayHoist.chpl
- test/users/engin/context/basicArrayHoist.execopts
- test/users/engin/context/basicBarrier.chpl
- test/users/engin/context/basicBarrier.comm-none.good
- test/users/engin/context/basicTaskIds.chpl
- test/users/engin/context/basicTaskIds.comm-none.good
This PR fixes failures in `basicBarrier` and `basicTaskIds` when tested with `-memleaks` under gasnet. These two tests used to turn on `startVerboseMem()` unintentionally. This produced no output by default, however produced verbose-memory diagnostics upon `-memleaks`, which implicitly turns on `--memTrack`. There were no failures in memleaks testing for local compilation because in the `--local` mode these tests produce compilation errors and so are not executed.
Since `startVerboseMem()` is unrelated to what these two tests are testing, I removed it. While there, I switched `basicArrayHoist.chpl` to avoid `startVerboseMem()` by default, so that the default behavior is more user-friendly.
Testing: `test/users/engin/context` under several configurations.
> Fix some iterator-context test failures

- compiler/passes/resolveIntents.cpp
Fixes a bug that we encountered when testing an unstable warning for associative domains - that test had a type argument which was getting passed a runtime type. Since runtime types by definition must exist at runtime, the argument had been transformed and was now relying on the default argument intent, making it inaccurately eligible for the indirect modification const check.  Something about the runtime type was causing valgrind to complain, which is how we noticed these unnecessary checks were getting inserted.
Type variables are only created, they cannot be modified, so it is unnecessary to worry about if they will be indirectly modified over the course of a function which takes them as an argument.  So just avoid inserting the checks when we know we have been given a runtime type …
> Don't perform const checks on type arguments, even if they're runtime types

- modules/standard/AutoMath.chpl
Fixes a few docstrings for `sqrt` that reference `z`, when they should reference `x`.
Built docs locally
> Fix docstrings for a few overloads of `sqrt`

- frontend/lib/resolution/call-init-deinit.cpp
- frontend/test/resolution/testCallInitDeinit.cpp
This PR fixes the invocation of default initializers to only pass type and param arguments, rather than passing something for each "substitution" in the generic type.
Testing:
> Dyno: Fix default calls to initializers to only pass type/param fields

- frontend/lib/resolution/Resolver.cpp
- frontend/test/resolution/testTypeOperators.cpp
- frontend/test/resolution/testTypeQueries.cpp
This PR fixes a dyno bug in which we would incorrectly attempt to instantiate types with an un-substituted type query, which could result in false errors. For example, in the following snippet, the compiler would encounter errors when resolving the ``data`` field. This was because at a particular stage of resolution we don't know the type of ``?val``, but resolution was trying to instantiate the expression ``R(?val)`` anyways.
```chpl
record R {
param val : bool;
var data : foo(val);
}
proc helper(arg: R(?val)) {
return arg.data;
}
```
This PR resolves this issue by adjusting the cases in which we will "skip" resolution of an expression during certain preliminary stages of resolving a function signature.
Testing:
> Dyno: Fix bug involving type queries and fields depending on generic types.

- compiler/main/driver.cpp
- frontend/include/chpl/util/chplenv.h
- frontend/lib/util/chplenv.cpp
- tools/c2chapel/c2chapel
- tools/chpl-language-server/chpl-language-server
- tools/chplcheck/chplcheck
- tools/chpldoc/chpldoc.cpp
- util/buildRelease/install.sh
- util/chpl-completion.bash
This PR was created with the intention of adding support for installing `c2chapel` and other Python-based tooling when it has been built. However, doing so -- particularly in the prefix-based installation case -- required some additional implementation work in `chpl` and `chpldoc`.
The main problem was the `CHPL_THIRD_PARTY` directory, which is transitively (via `chpl_home_utils.py`)  used by all the `run-in-venv` scripts and `chpldoc`. Two problems stemmed from the environment variable:
* This directory is correctly inferred when the environment is completely blank, but in an explicitly-set `CHPL_HOME`, it points to an (assumed) home-based directory. Thus, `export CHPL_HOME=$(chpl --print-chpl-home)`  breaks both `chpl` and `chpldoc`. 
* It's very hard to find this directory (and …
> Install Python-based tools using `make install`; make changes to `chpl` and `chpldoc` to work better in prefix installs

- util/buildRelease/gen_release
Adds `chpl-language-server` to the release bundle.
Tested by running command locally with `CHPL_GEN_RELEASE_NO_CLONE=1` and ensuring that `make chpl-language-server` works
> Add chpl-language-server to the release bundle

- doc/rst/meta/static/style.css
This PR adjusts the default css theme for the sphinx docs to not have extra padding on some procs
Before:
After:
Tested in firefox and chrome
> Tweak css for chpldoc to fix spacing

- .dockerignore
- Dockerfile
This PR does a major and a minor thing:
* __Major__: splits the dockerfile into multiple stages: a 'common' stage which represents the build-and-run environment of the final image, a 'build' environment which contains all the sources etc. necessary to build Chapel, and a 'release' environment which contains the final build products etc. The multi-stage nature of the build allows files that we don't care about (the `.git` directory, the LLVM sources, most of the `test` directory) to be skipped when building the final image. This way, we are able to strip off at least 0.6GB from the image, and that's not including the size of `.git` (not included in my experiments).
* __Minor__: Adds a `.dockerignore` file that ignores the `Dockerfile`. This way, the `COPY . .` has less of a chance to …
> Split docker image into multiple stages and improve cache behavior

- .github/workflows/CI.yml
- .github/workflows/build-CI-container.yml
- .github/workflows/email.yml
Github's CI migrated to a new version of node.js and this causes
warnings on our CI jobs.   The new version of the checkout action
picks up this new version of node to resolve the warnings.
> Update CI actions to use checkout@V4 to resolve node.js warning

- test/library/standard/Math/docs/usemath.doc.prediff
Updates to `chapeldomain` changed the plaintext output of documentation, which broke the regexes that processed that structure. This PR fixes the regexes -- by adding "one or more spaces" instead of "one space".
> Fix regular expressions in usemath test with updated chapeldomain

- modules/standard/Random.chpl
`Random.sample` was using a `DstAggregator` where it should have been using a `SrcAggregator` which was causing a segfault in some multi-locale configurations.
This PR removes the use of aggregators from `Random.sample` all together, where it could be reintroduced later as a performance optimization.
> Resolve asan failure originating in `random.sample`

- compiler/include/config.h
- compiler/main/config.cpp
- compiler/resolution/fcf-support.cpp
- compiler/resolution/functionResolution.cpp
The `getConfigParamBool` function is an expensive operation to get the value of a `config param` which iterates over the `paramMap` in the compiler. This means that we want every place which calls this function to cache the result for later use. So far, there are only two uses of this function which cache the result as of this commit.
> Cache results from calls to getConfigParamBool

- doc/rst/conf.py
- doc/util/versionButton.php
When doing the 1.33 release, we conservatively set the 'main' version of the docs to be 1.34 pre-release.  Now that we're more confident that this month's release will be 2.0, this PR bumps the menu to refer to it as "2.0 pre-release".
> Make 'main' version of docs 2.0 pre-release

- compiler/main/runpasses.cpp
This code seeped in in https://github.com/chapel-lang/chapel/pull/24451. My bad!
> Remove debugging code that seeped in inadvertently

- test/performance/vectorization/vectorizeOnly/vectorizeOnlyWithIntents.future
This future passes as of the addition of implicit foreach intents in https://github.com/chapel-lang/chapel/pull/24451.
> Promote a foreach intent future into a test

- CMakeLists.txt
- Makefile
- compiler/Makefile
- frontend/util/linters/CMakeLists.txt
- tools/chpldoc/CMakeLists.txt
- util/buildRelease/install.sh
This PR fixes a bug that was introduced sometime around the introduction of CMake to handle the installation process for `chpl` and `chpldoc`. The fix allows `make install` to only install `chpldoc` if it has been built already using `make chpldoc`. This aligns with the previous behavior before the bug. 
There are two parts to the resolution. First, make `chpldoc` excluded from the `all` target in CMake. Then separate the install commands in CMake so that `chpl` is still required to be built before `make install`, but `chpldoc` will only be installed if it was found in the build directory. 
TESTING:
> fix bug that always installed `chpldoc`

- test/studies/sinLUT/PREDIFF
- test/studies/sinLUT/c_sin.c
- test/studies/sinLUT/c_sin.h
- test/studies/sinLUT/chplSin.chpl
- test/studies/sinLUT/chplSin.good
- test/studies/sinLUT/chplSinBlock.chpl
- test/studies/sinLUT/chplSinBlock.good
- test/studies/sinLUT/chplSinReplicated.chpl
- test/studies/sinLUT/chplSinReplicated.good
- test/studies/sinLUT/chplSinReplicatedReplicand.chpl
- test/studies/sinLUT/chplSinReplicatedReplicand.good
Fixes the .good files for the sinLUT tests I added. These were relying on random numbers with a seed that varied. This PR passes a seed value to `srand` that is constant.
Also, due to platform differences in the `rand` algorithm, this PR adds a PREDIFF to validate that Calculated and Lookup give the same answer, since putting just the value returned in the good file is not portable.
tested on MacOS and Linux, with and without comm
> Fix sinLUT tests

- test/io/vass/time-write.chpl
Update the left-justification format specifier from `-` to `<` in io/vass/time-write.chpl. With this change, the test is passing in its performance configuration.
> Fix test failure from #24527

- runtime/src/arg.c
- runtime/src/topo/hwloc/topo-hwloc.c
- test/runtime/configMatters/launch/jhh/co-locales/co-locales.py
Allow long-form suffixes to the -nl argument, including "socket", "numa",  "llc", and "core".
Resolves https://github.com/Cray/chapel-private/issues/6041.
> Allow long-form suffixes to -nl argument

- test/studies/sinLUT/PREDIFF
- test/studies/sinLUT/chplSin.chpl
- test/studies/sinLUT/chplSinBlock.chpl
- test/studies/sinLUT/chplSinReplicated.chpl
- test/studies/sinLUT/chplSinReplicatedReplicand.chpl
Fixes two distinct issues with new perf tests I added yesterday.
- A late breaking change meant that I added a PREDIFF, which I did not expect to run for the perf configs. This prevented the timings from being found. The solution is to use the prediff when doing correctness testing
- ASAN+gasnet testing caused the correctness testing to timeout. The solution is to do less iterations for a correctness test
Testing - done on macos and linux, with and without comm
- `start_test test/studies/sinLUT`
- `start_test --performance test/studies/sinLUT`
- `start_test --performance --perflabel ml- test/studies/sinLUT`
> Fix issues with new perf test in nightly

- compiler/llvm/clangUtil.cpp
- util/chplenv/chpl_gpu.py
- util/chplenv/compile_link_args_utils.py
These are the changes I found necessary to get Chapel with AMD GPU support working in spack. When using spack to install the dependencies for our rocm support, the paths are not necessarily the same as we have been expecting. With these changes, I was able to get spack to build and run with AMD GPU support on `chapdl-amd`
[reviewed by @DanilaFe - thank you!]
> GPU and LLVM util changes to enable AMD support in spack

- modules/standard/Math.chpl
- test/library/standard/Math/fma.chpl
Remove unstable `imag` overloads of `fma()` since they compute an incorrect result. We can add additional overloads if users request them.
> Remove unstable 'imag' overloads of 'fma()'

- compiler/passes/convert-uast.cpp
- compiler/resolution/preFold.cpp
- test/classes/delete-free/borrowed/borrowed-array.good
- test/classes/errors/Issue18717.chpl
- test/classes/errors/Issue18717.good
Resolves #18717.
Fixes a bug which caused an array type preceded by the `borrowed` keyword to be incorrectly transformed into a loop. This led to internal errors when the loop was queried for its type information.
At a syntactic level, array types and loops are indistinguishable. However, in type-only contexts (such as for formal types, or for return types) we can always convert a "loop" into an array type. This PR adjusts the uAST converter so that it can handle converting array types at arbitrary depths. This covers array types that follow the `borrowed` keyword (which is represented as a "call").
TESTING
Reviewed by @mppf, @vasslitvinov. Thanks!
> Fix a uAST conversion bug that incorrectly converted some array types

- frontend/include/chpl/resolution/resolution-types.h
- frontend/include/chpl/types/UintType.h
- frontend/lib/resolution/default-functions.cpp
- frontend/lib/resolution/default-functions.h
- frontend/lib/resolution/resolution-queries.cpp
- frontend/lib/resolution/return-type-inference.cpp
- frontend/test/resolution/testEnums.cpp
This PR adds casts to and from enums when the enum / integer is not a param value. It does so by mimicking what the production compiler does: building a single, generic "from" function, and a single, generic "to" function. The functions look something like this:
```Chapel
operator :(from: theEnum, type to: integral)
operator :(from: integral, type to: theEnum)
```
This requires some adjustments:
* An easy initial adjustment is that the existing framework relies on the first formal to determine whether a compiler-generated candidate should be considered. However, in the above, the cast _to_ an enum uses a generic integral type as its "receiver". Thus, I make changes to support finding compiler-generated candidates for general binary operation.
* A more significant adjustment is that to …
> Dyno: add non-param casts to and from enums

- modules/standard/AutoMath.chpl
#13824 used `|` instead of the conventional `||` for min and max on reals. This [raised some eyebrows](https://github.com/chapel-lang/chapel/issues/13922#issuecomment-528646124) back then, yet remained this way. 
This PR switches them to `||` because [this has been observed to improve performance](https://github.com/chapel-lang/chapel/issues/14000#issuecomment-1911475870) -- thanks @damianmoz for this finding.
Damian also reports that at the time of 13824 `|` was faster in his testing, which most likely used GCC. He also suggests that we may want to switch to compiler intrinsics for these.
No test changes. Passes {standard, gasnet} paratests with {llvm, gnu} backends.
> Speed up min() and max() on reals

- compiler/main/driver.cpp
- frontend/include/chpl/framework/Context.h
- frontend/include/chpl/framework/check-build.h
- frontend/lib/framework/CMakeLists.txt
- frontend/lib/framework/check-build.cpp
- tools/chapel-py/setup.py
- tools/chapel-py/src/chapel.cpp
This PR fixes a problem with chapel-py on some systems after PR https://github.com/chapel-lang/chapel/pull/24477. That PR added a field to `Context` that depends on `#ifdef HAVE_LLVM`. Due to a mismatch between the library compile environment and the chapel-py compile environment, the `Context` would be allocated without this field, but then the library would try to set it, leading to writing outside of the allocation.
The simple fix to this is to declare a dummy field for the case that LLVM is not available.
Additionally, to avoid this sort of problem in the future, this PR adds a mechanism to check if the relevant `#define`s for the header files match those used when building the library. It uses this from `chpl` and `chapel-py`.
Lastly, to resolve the misconfiguration, it adds …
> Fix problem with chapel-py

- test/gpu/native/studies/minibude/SKIPIF
The system we do nightly testing on for minibude has issues doing `git clone` with an ssh-based url. This PR simply updates the url we clone from to use https rather than ssh (which is also what we do for nightly chop testing).
> fix for recently added nightly minibude testing

- runtime/src/launch/slurm-srun/launch-slurm-srun.c
- test/runtime/configMatters/launch/jhh/co-locales/co-locales.py
Added launcher tests for the `-nl `argument suffix. Also, removed dependencies on `sinfo` and  `sbatch` so the tests can be run on a system on which `slurm` is not installed, and fixed the wording of a few error messages.
Resolves https://github.com/Cray/chapel-private/issues/5997.
> clean up launcher -nl suffix tests

- util/chplenv/chpl_platform.py
- util/chplenv/compile_link_args_utils.py
This PR adds the ability to detect if we are using an NVidia GPU while running in Windows Subsystem for Linux (WSL) and make appropriate additions to properly detect the location of `libcuda`. 
This change was needed because WSL has a special configuration w.r.t. the GPU drivers where the drivers are installed only in Windows and then made available to WSL.
TESTING:
[reviewed by @e-kayrakli - thanks!]
> fix libcuda path when running in WSL

- doc/rst/usingchapel/multilocale.rst
Added documentation for the suffix to the `-nl` argument, and cleaned up the co-locale description in general.
Resolves https://github.com/Cray/chapel-private/issues/5995.
> Document suffix to -nl argument

- doc/rst/language/spec/domains.rst
- modules/internal/ChapelDomain.chpl
- test/arrays/localQueries/localAccess.chpl
- test/domains/compilerErrors/promo-unsafe.chpl
- test/domains/compilerErrors/promo-unsafe.good
- test/domains/userAPI/contains.good
This PR reverses the part of #24565 that forced a promoted `add` to a sparse or non-parSafe domain to execute serially. Instead it makes the compiler issue a warning that such promoted add can lead to races. The reason for the reversal is that we are not sure the "force to execute serially" is a good solution and we have not discussed it adequately.
This PR also reverses the change that 24565 made to `test/arrays/localQueries/localAccess.chpl` because it would be racy otherwise. It also records the warning issued in contains.chpl. So far this test has been passing despite the race in `assoc_sub2 += n..#10;` where `assoc_sub2` is a parSafe=false domain, so I am leaving the code unchanged.
While there, correct+clarify pieces of the language spec on domains.
Testing: standard and gasnet …
> Restore non-serial promotion for domain.add()

- runtime/src/gpu/nvidia/gpu-nvidia-cub.cc
This should fix all the build failures with nvidia testing
- Testing:
> Fix clang not behaving with loop unrolling in CUB

- test/functions/generic/warn-generic-actual.skipif
Follow-up to PR #24021 to address a test failing with `--baseline`.
This PR just adds a .skipif file as a work around to issue #24113.
> Skipif this test to work around issue #24113

- doc/rst/usingchapel/prereqs.rst
This PR updates prereqs.rst in two ways:
1. Updates the commands and platform-specific notes based on the result of recent portability testing (after #24567)
2. Updates the GCC and Apple Clang requirements to track the versions required by LLVM 17 which we bundle.
> Update prereqs.rst for the 2.0 release

- modules/standard/Math.chpl
This was pointed out by Damian - the hyperbolic Math functions were listed under the trigonometry section but really should have their own section
Verified the built docs looked good and that `test/library/standard/Math/docs/usemath.doc.chpl` still passes
> Recategorize the hyperbolic Math functions in the documentation

- test/library/standard/List/initEquals/listInitEqualsArrayBug.chpl
- test/library/standard/List/initEquals/listInitEqualsArrayBug.future
- test/library/standard/List/initEquals/listInitEqualsArrayBug.good
Resolves #24305.
This future passes because array types at arbitrary depths are now converted into array types instead of loops.
> Promote a future that passes after #24560

- doc/rst/language/spec/generics.rst
Follow-up to PR #24021.
This PR adds a sentence to the spec section about marking generic types to include cases like `f(myGenericRecord)`.
> Update spec for marking generic types passed to type formals

- CMakeLists.txt
- doc/rst/language/evolution.rst
- doc/rst/technotes/driver.rst
- doc/rst/technotes/ioSerializers.rst
- frontend/lib/uast/post-parse-checks.cpp
- man/confchpl.rst
- man/confchpldoc.rst
- test/compflags/bradc/printstuff/version.goodstart
- test/deprecated/chplCommGetPut.chpl
- test/mason/chplVersion/tomls/pass/ivrsChooses.good
This PR updates the Chapel version number in advance of the release of Chapel 2.0.
Updates to the major version were caught in mason tests which check for compatibility of package dependencies w.r.t the chapel version. I updated the `.good` file to expect a more recent version of the dependency, based on the updated version of Chapel
TESTING:
> update v1.34 - v2.0 in several places

- test/gpu/native/studies/minibude/Bude.good
- test/gpu/native/studies/minibude/Bude.prediff
- test/gpu/native/studies/minibude/SKIPIF
Fixes a few issues with the test configuration for miniBude in nightly testing.
- SKIPIF testing for CHPL_GPU=cpu
- filter output when running on multiple gpus
Tested on system with 1 gpu, 2 gpus, and with CHPL_GPU=cpu
> Fix miniBude nightly testing

- compiler/passes/denormalize.cpp
This PR disables invoking collapseTrivialMoves() by default. If desired, it can be enabled using the compiler flag `--no-return-by-ref`.
collapseTrivialMoves() was added in #24519 under the presumption that it was harmless. However, we observe it to cause, or at least trigger, the following error when running on NVIDIA GPUs under CUDA 12:
```
internal error: gpu-nvidia.c:292: Error calling CUDA function: misaligned address (Code: 716)
```
So I am turning it off by default to clear testing, pending further investigation.
Suggested by @e-kayrakli .
> Guard collapseTrivialMoves() with --no-return-by-ref

- frontend/include/chpl/framework/ErrorWriter.h
- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/call-init-deinit.cpp
- frontend/lib/resolution/default-functions.cpp
- frontend/lib/resolution/resolution-queries.cpp
- frontend/lib/util/assertions.cpp
This comes up when you run the language server on the IO module. Prior to this PR, several points of the resolver cause a hard crash (segmentation fault or assertion error), which also crashed the language server. This PR makes tweaks to avoid hard crashes like that, and thus allows LSP to be used with the resolver in more cases.
> Avoid crashing when resolving the IO module

- man/chpl.rst
Brad pointed out that we didn't have documentation for the `const` and default argument intent indirect modification warning.  Since the check is implementation-specific, it doesn't make sense to mention it in the spec.  Brad suggested the man page as a place people are likely to encounter it in the steady state (and the entry didn't necessarily give sufficient context to begin with).
Here's how the entry now renders
Passed a full paratest with futures.
> Extend the man page description of `--[no-]const-arg-checks`

- modules/dists/BlockDist.chpl
This PR fixes a bug where distributed array accesses on non-GPU-bound loops could cause compilation errors. This is because we try to write a stub for nonLocalAccess when it is called from a GPU kernel. The way we do that is less than ideal and caused problems before (https://github.com/Cray/chapel-private/issues/5957).
To fix, we remove the special pragma on the `nonLocalAccess`. With that, we'll still be able to use distributed arrays in GPU kernels in rudimentary cases as before. They just have to be accessed via `localAccess`, either manually, or through automatic local access optimization.
Test
> Limit GPU distributed array support to only locally-accessed arrays

- frontend/doc/doxygen-pitfalls.txt
- frontend/include/chpl/resolution/scope-types.h
- frontend/include/chpl/types/ClassTypeDecorator.h
This PR adds a workaround to avoid "Invalid C++ declaration" errors when doing `make docs`. Oddly enough, the errors seemed to go away with a second `make docs`, and appeared on some platforms but not others.
The errors looked like this:
```
/some/path/to/file.rst:11: WARNING: Invalid C++ declaration: Expected identifier in nested name. [error at 0]
```
It seems to be connected to unnamed enums declared within a class, e.g.
``` c++
class Something {
enum {
A = 1,
B = 2
};
}
```
This PR works around the problem by adding `/// \cond DO_NOT_DOCUMENT` around such enums.
> Fix docs build errors from frontend C++ code docs

- compiler/codegen/cg-expr.cpp
This PR recovers a performance regression seen in our nightly testing for GPU kernels that make heavy usage of sqrt. 
For GPU codegen, we do `linkGpuDeviceLibraries()`, which among other things replaces the libc `sqrt` with a special gpu optimized `sqrt` (at least for nvidia). This PR #24455 changed how we codegen `sqrt` to directly codegen to LLVM, meaning we were no longer getting the "special" nvidia sqrt. Note that using the `sqrt` intrinsic resulted in an AMD gpu improvement.
Testing using `test/gpu/native/studies/coral`, lower is better
|    | llvm sqrt intrinsic | libc sqrt | percent diff |
| --- | --- | --- | --- |
| nvidia (sm_60) | 1.20545 | 0.993516 | 19% |
| amd (gfx908) | 1.69853 | 1.87864 | -10% |
Based on this, this PR turns off the `sqrt` intrinsic transformation only for …
> Recover nvidia gpu performance for sqrt

- modules/internal/DefaultRectangular.chpl
- modules/standard/IO.chpl
This PR fixes a bug where reading or writing a DefaultRectangular array using ``binary(De)Serializer`` to a remote locale would fail at runtime. The runtime error message would unhelpfully point to the DefaultRectangular implementation and complain about using remote data with ``c_pointer_return``.
The core issue was that we should not have been trying to get a ``c_ptr`` to the array's data when that data and the file did not exist on the same locale. This PR updates the implementation to check the locality of the data and file before trying the optimized "bulk elements" path, and otherwise will fall back on the element-by-element approach.
A potential future optimization could be to create a small local buffer on the file's locale into which we could copy chunks of the array's data.
The …
> Fix bug when writing DefaultRectangular arrays in binary across locales

- doc/rst/platforms/aws.rst
This PR is a near-complete rewrite of `doc/rst/platforms/aws.rst` to reflect current best-practices for running Chapel on AWS, which is to use ParallelCluster (`pcluster`). This document now describes how to setup a `pcluster` for best results when using Chapel, as well as notes on building Chapel in a good configuration.
This also contains some notes on running on instances with GPUs, although my testing of this has been less thorough.
Built and checked docs locally
> Refresh AWS platform documentation

- runtime/src/topo/hwloc/topo-hwloc.c
We encountered a problem in which `hwloc_get_pcidev_by_busid` received different values from those passed to it. The circumstances were unclear -- perhaps the caller and callee were compiled by different compilers. Cast the parameters to ensure there wasn't a problem with coercion.
> Cast parameters instead of coercing

- compiler/resolution/functionResolution.cpp
- test/classes/corrado/interfaces_warning_bug.bad
- test/classes/corrado/interfaces_warning_bug.future
- test/classes/generic/canInstantiate-generic.1.good
- test/classes/generic/canInstantiate-generic.2.good
- test/classes/generic/canInstantiate-generic.3.good
- test/classes/generic/canInstantiate-generic.4.good
- test/classes/generic/canInstantiate-generic.chpl
- test/classes/generic/canInstantiate-generic.compopts
- test/classes/generic/canInstantiate-generic.prediff
- test/constrained-generics/basic/generic/generic-classes.chpl
- test/studies/1brc/aggregators.good
Fixes https://github.com/chapel-lang/chapel/issues/24408. 
Code in interface resolution attempts to check if an (instantiated) interface statement really does produce an interface for the given actual type. This code uses `canInstantiate`; however, prior to this PR, `canInstantiate ` seemed to return false for an `owned T(x)` being passed to an `anymanaged T` (`T` generic). This was because `anymanaged T` is not a class container, but `owned T` is. The invalid return from `canInstantiate` causes interface resolution based on generic `implements` statements (such as those written during a class declaration as `class c : myInterface`) to fail when it should succeed. This caused the warning in #24408 , because an implementation of `contextManager` really was not found (the warning was not …
> Fix 'can instantiate'-driven error in interface resolution

- doc/rst/language/spec/conversions.rst
- doc/rst/language/spec/types.rst
This PR adds information to the description of numeric types in the types.rst spec chapter. It adds examples and links to later sections since it forms a jumping-off point and it's fairly early in the spec, in terms of chapters, for anyone reading it consecutively.
One of the main motivations of this PR is to describe in the spec the behavior of casting between `real` and `imag` types.
I created this PR to address https://chapel.discourse.group/t/getting-the-imaginary-part-of-an-imaginary-number/31200
> Update the spec description of numeric types

- doc/rst/platforms/index.rst
- doc/rst/platforms/windows.rst
- doc/rst/technotes/gpu.rst
This PR updates our platform specific documentation for Windows. Specifically it moves Cygwin to a section within Windows and adds a section above it for WSL. 
I have also added a small section to the GPU technote indicating it's possible to use NVidia GPUs through WSL.
TESTING:
[reviewed by @e-kayrakli - thanks!]
> update platform docs for windows

- test/library/standard/List/initEquals/listInitEqualsArrayBug.bad
The future I "re-added" for #24305 is still sometimes failing with a segfault under gasnet. Because of this, just remove the `.bad` file for now.
Reviewed by @arezaii. Thanks!
> Remove .bad file for segfaulting list future

- CMakeLists.txt
- doc/rst/conf.py
- doc/rst/language/archivedSpecs.rst
- doc/rst/usingchapel/QUICKSTART.rst
- doc/rst/usingchapel/chplenv.rst
- man/confchpl.rst
- man/confchpldoc.rst
- test/chpldoc/compflags/combinations/versionhelp-chpldoc.sh
- test/compflags/bradc/printstuff/versionhelp.sh
This PR prepares for the 2.0 release by removing the wording "pre-release" from several places, and setting the `release` flag to `true` in `CMakeLists.txt`
Changes modeled from https://github.com/chapel-lang/chapel/pull/24028
TESTING:
[reviewed by @lydia-duncan - thanks!]
> remove pre-release wording for 2.0

- doc/rst/language/evolution.rst
- doc/rst/language/spec/arrays.rst
- doc/rst/language/spec/domains.rst
- test/release/examples/primers/associative.chpl
This PR adds documentation related to the stabilization of associative domains:
1. Adds an entry to language evolution describing in detail the changes made to parSafety for associative domains and all the different flags, options, and what they do.
2. Edits the note about Parallel Safety for Associative Domains and Arrays to reflect the new default for associative domains being parSafe=false
3. Adds links to the above from a few different places which mention parSafe.
4. Remove messages about associative domains being unstable.
> Add the assoc par safe change to language evolution

- test/types/records/generic/named-field-q-2.compopts
Rationale: --minimal-modules does not work with several configurations, see
```
test/compflags/bradc/minimalModules/SKIPIF
```
To reduce the risk of testing noise, do not use this option on this test.
Not reviewed.
> Do not use ---minimal-modules for `named-field-q-2.chpl`

- modules/standard/GPU.chpl
Simple change made to reflect the fact that the CUB sort supports all primitive numeric types.
Trivial, no tests, not reviewed.
> Change gpuSort docs to reflect newly supported types

- doc/rst/language/spec/input-and-output.rst
- modules/standard/Errors.chpl
- modules/standard/GPU.chpl
After https://github.com/chapel-lang/chapel/pull/24542, any reference to ChapelIO in the docs will result in a broken link. This PR fixes that oversight.
> Fix ChapelIO links

- doc/rst/usingchapel/executing.rst
The section "Setting the Number of Locales" didn't cover the co-locale syntax. It's now an overview of multi-locale programs with links to more detailed information about multiple locales, co-locales, and launchers.
> Cleaned up -nl discussion

- CONTRIBUTORS.md
This updates the list of contributors to the most recent release to reflect work done since 1.33.  Thanks to everyone who has contributed since 1.0, not to mention the very beginning!
> CONTRIBUTORS for Chapel 2.0

- doc/rst/conf.py
- doc/util/versionButton.php
This is the standard bump to the docs pull-down menu we do during release time to make 'main' reflect the 2.1 pre-release.
> Bump version number of 'main' version of docs to 2.1 pre-release

- CMakeLists.txt
- man/confchpl.rst
- man/confchpldoc.rst
- test/chpldoc/compflags/combinations/versionhelp-chpldoc.sh
- test/compflags/bradc/printstuff/version.goodstart
- test/compflags/bradc/printstuff/versionhelp.sh
This PR updates version numbers to 2.1 (pre-release) for `chpl`, `chpldoc`, and the website documentation. 
This is the corresponding update to the previous PRs that changed the status from pre-release to release:
- https://github.com/chapel-lang/chapel/pull/24588
- https://github.com/chapel-lang/chapel/pull/24533
Changes are compared against past PRs doing the same:  
- https://github.com/chapel-lang/chapel/pull/24061
~~- https://github.com/chapel-lang/chapel/pull/23530~~
TESTING:
[reviewed by @ShreyasKhandekar - thanks!]
> update version numbers to reflect pre-release status of Chapel 2.1

- test/studies/arkouda/sub_test
Avoid PIP timeouts in nightly testing by utilizing the default pip caching behavior and increasing the network timeout.
[Reviewed by @bmcdonald3]
> Avoid PIP timeouts in nightly testing

- third-party/chpl-venv/Makefile
Fixes an oversight in the makefile for chapel-py (and all python binding tools) where if CHPL_HOME is not set, it causes the build to fail.
This is important for prefix based installs
> Enable building python binding tools without CHPL_HOME

- frontend/lib/resolution/can-pass.cpp
- frontend/lib/resolution/resolution-queries.cpp
- frontend/lib/resolution/resolution-types.cpp
- frontend/test/resolution/testMethodCalls.cpp
This PR updates the implementation of instantiating a signature in dyno to correctly set the type of ``this`` while resolving the non-formal elements of a secondary method. Prior to this PR, we were potentially setting the type of ``this`` to be the fully-generic type, rather than the instantiation we had just computed. For example, for a method like ``R.foo()`` we would use ``R`` instead of something like ``R(int)``.
While in the area, I also observed and fixed a related issue when referencing fields of a generic type while within an instantiated secondary method. The solution was to simply reset the Resolver's "computed receiver scopes" flag so that they would be appropriately recomputed.
This PR also includes a couple of minor cleanups to avoid generating some false "unimplemented" …
> Dyno: Improve resolution of where-clauses on generic methods

- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/call-init-deinit.cpp
- frontend/lib/resolution/default-functions.cpp
- frontend/test/resolution/testCallInitDeinit.cpp
- frontend/test/resolution/testIf.cpp
- frontend/test/resolution/testNew.cpp
Make dyno resolution treat a nilable class type declared in an `if var` as non-nilable inside the `then` body, since it must be non-nil there.
Along the way, make it possible to init/deinit a nilable class type from a `new` non-nilable value, as is possible in the production compiler. The `init` is made possible by accepting a subtype conversion (which includes nilability) in move-init. `Deinit` is made possible by changing the nilable to be deinited to non-nilable, as we'll have a runtime check to avoid deiniting `nil`. 
Resolves https://github.com/Cray/chapel-private/issues/5975.
Testing:
> Dyno resolve `if var` decl type with nilable classes

- frontend/lib/resolution/call-init-deinit.cpp
- frontend/test/resolution/testCallInitDeinit.cpp
Skips CallInitDeinit::handleInFormal for builtin/primitive types to avoid dead variable errors related to passing such types to formals with the ``in`` intent.
> Dyno: Silence dead variable errors for builtin/primitive types

- doc/rst/language/spec/arrays.rst
- doc/rst/language/spec/bytes.rst
- doc/rst/language/spec/classes.rst
- doc/rst/language/spec/conversions.rst
- doc/rst/language/spec/data-parallelism.rst
- doc/rst/language/spec/domain-maps.rst
- doc/rst/language/spec/domains.rst
- doc/rst/language/spec/error-handling.rst
- doc/rst/language/spec/expressions.rst
- doc/rst/language/spec/generics.rst
- doc/rst/language/spec/interoperability.rst
- doc/rst/language/spec/iterators.rst
- doc/rst/language/spec/language-overview.rst
- doc/rst/language/spec/lexical-structure.rst
- doc/rst/language/spec/locales.rst
- doc/rst/language/spec/memory-consistency-model.rst
- doc/rst/language/spec/methods.rst
- doc/rst/language/spec/modules.rst
- doc/rst/language/spec/procedures.rst
- doc/rst/language/spec/ranges.rst
- doc/rst/language/spec/records.rst
- doc/rst/language/spec/statements.rst
- doc/rst/language/spec/strings.rst
- doc/rst/language/spec/task-parallelism-and-synchronization.rst
- doc/rst/language/spec/tuples.rst
- doc/rst/language/spec/types.rst
- doc/rst/language/spec/unions.rst
- doc/rst/language/spec/variables.rst
- doc/rst/technotes/noinit.rst
This PR adds `.. index::` directives to the .rst language specification based upon `\index` entries that were present in the .tex version. All directives added here use the `single:` format.
Note that the sphinx index only supports 2-level nesting. That meant adjusting some of the more deeply nested cases that we had in the .tex version.
This PR also adds a few index entries that were noticeably absent from the .tex version (since the language specification had evolved since then).
See also [the sphinx documentation about index directives](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#index-generating-markup)
> Add spec index entries based on .tex index entries

- util/cron/test-docker.bash
Includes:
- Adding `--load` to the Docker build command. For reasons unknown to me (perhaps an update, or something I did unintentionally while doing https://github.com/chapel-lang/chapel/pull/24562) the build is now trying to use the `docker-container` (BuildKit) driver rather than Colima, which needs `--load` to export the image from the building container to Docker. I think it should be fine to just adjust this in response.
- Changing the image names we build to include their repository name (`chapel/`) prefixes. This means that the gasnet and gasnet-smp builds, whose Dockerfiles contain `FROM chapel/chapel`, will now build off of the newly-built chapel image. Previously it appears they unintentionally were built based off of the latest `chapel/chapel` that exists in Dockerhub -- from …
> Make more fixes to `test-docker.bash`

- util/cron/syncPerfGraphs.py
Update a hardcoded home path from the soon-to-be decommissioned `/users/chapelu` to `/hpcdc/data/users/chapelu`.
The path is still hardcoded as this script is meant to be run from a system other than the one where the path exists. We could use a `~` for `$HOME` to be expanded on the destination system but I feel less confident in that being portable, and not getting expanded on the source system side.
[urgent test fix, not reviewed]
> Update hardcoded home path in syncPerfGraphs.py

- compiler/codegen/cg-expr.cpp
- compiler/codegen/cg-symbol.cpp
- compiler/include/clangUtil.h
- compiler/llvm/clangUtil.cpp
- test/interop/C/errorMessage/errorInArgNMismatch.chpl
- test/interop/C/errorMessage/errorInArgNMismatch.good
- test/interop/C/errorMessage/errorInArgNMismatch.h
This replaces a compiler assertion with a user-facing error message. Noted by @twesterhout on [gitter](https://matrix.to/#/!PBYDSerrfYujeStENM:gitter.im/$D4ys_1Xy9ZLD437uk64oeOPAXzVkPMdBMYYgGJtLA1I?via=gitter.im&via=matrix.org&via=envs.net).
The assertion was triggered when Chapel code exports a function with more number of arguments then there is in the C header that declares the function on C side.
Test:
> Add a user facing error message for export proc argument mismatch

- doc/rst/platforms/cray.rst
While reviewing the website for the 2.0 release today, we realized that HPE Cray EX isn't highlighted as a platform on our download page alongside XC, which is increasingly being put to bed.  Updating the website is easy, but most of the material is here in the platform docs, which was still very XC-centric in terms of ordering of material.
Here, I've taken a pass to try and bring HPE EX and Apollo more to the forefront relative to Cray XC and CS, while also touching up some other things that caught my eye.  I think there's more we could/should do here to bring HPE systems to the forefront and give them equal time and attention to the historical Cray systems (like, for example, renaming this file), but am currently imagining that to be post-2.0 work.
> Make HPE EX/Apollo more prominent in cray.html

- util/cron/test-perf.gpu-cuda.bash
- util/cron/test-perf.gpu-cuda.um.bash
- util/cron/test-perf.gpu-rocm.bash
We got confused by lack of this setting in the past. Without it, runs always generate warnings that get ignored in the performance setting. That is fine in steady state, but if there's a failure, we see the warning in the full output, which is almost always a red herring.
> Set CHPL_TARGET_CPU=native in GPU performance testing

- doc/rst/usingchapel/prereqs.rst
Fixes a link to note about Amazon Linux 2 in prereqs.rst
> Fix link for Chapel prereqs

- doc/util/versionButton.php
This is the update to the docs pull-down menu corresponding to the 2.0 docs going live (staged, but not yet pushed at the time of opening this PR).
> Update the docs button to reflect that the current docs are 2.0

- tools/chpl-language-server/src/chpl-language-server.py
Fixes inlay hints not being shown when `--resolver` is enabled due to boolean flag being flipped
> CLS: Fix InlayHints that rely on `--resolver`

- util/chplenv/chpl_gpu.py
With GPU support, we can't use the `fifo` tasking layer. We do have an error message for that, but for some reason it was just checking it for cpu-as-device mode. This PR fixes the error message to cover all GPU configs.
Resolves https://github.com/chapel-lang/chapel/issues/24619.
> Expand error message for when fifo is used with GPU locale model

- frontend/include/chpl/framework/ErrorBase.h
- frontend/include/chpl/framework/ErrorWriter.h
- frontend/lib/framework/ErrorBase.cpp
- tools/chapel-py/src/core-types-gen.cpp
- tools/chapel-py/src/error-tracker.h
- tools/chapel-py/src/method-tables/core-methods.h
- tools/chpl-language-server/src/chpl-language-server.py
This makes them clickable and goto-able :)
The functionality requires _locations_, which `chapel-py` itself does not currently concern itself with. So, the functionality is in CLS, which makes additional assumptions about files and their URLs right now. In other words, `chplcheck` doesn't benefit -- but barely any errors that `chplcheck` can report have additional notes anyway.
> LSP: Display notes from error messages as part of the error message

- test/interop/C/errorMessage/errorInArgNMismatch.skipif
The test in question is supposed to test a compilation error message. But with C backend, we get a relatively user-facing message from the C backend already. So, we should only run this test with the LLVM backend. This PR adds a skipif for that.
> Add a skipif for a test

- util/packaging/docker/test/homebrew_ci.bash
This PR adds the `--load` flag to the docker build command in `homebrew_ci`. A previous change to delete the images immediately after use made it so docker could no longer locate the image. 
In #24562 we fixed some test scripts to properly remove old docker images and this ~~brought up~~ exposed an issue with docker tests that was fixed in #24658, but the fix wasn't also made to the homebrew CI testing script that also uses docker and was updated the same way in #24562. 
The result was that running the homebrew test script would fail when it tried to load the homebrew_ci image that the script had built in a previous step, resulting in the following output:
```
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image …
```
> fix homebrew test failure, add --load to docker run

- doc/rst/tools/index.rst
Reorders the documentation for the tools section of our docs
Built and checked the docs locally, they look like this:
> Reorder documentation for "Tools"

- tools/chpl-language-server/src/chpl-language-server.py
Adds a feature flag to CLS for "Show instantiation", so that users who don't want/like the code lens can turn it off. The feature is still on by default.
> Allow users to turn off "Show instantiation" code lens

- compiler/optimizations/gpuTransforms.cpp
- compiler/resolution/lowerIterators.cpp
- test/statements/foreach/inIntentToRecordWithConstructor.chpl
- test/statements/foreach/inIntentToRecordWithConstructor.good
We would like consistent semantics for task intents between `forall` and `foreach` loops.
When using an `in` intent on a record that defines `init=` in a `forall` loop we will see that `init=` gets called once per task. Previously, in a `foreach` loop we wouldn't do this (instead we would create copies but would do so doing something akin to a strict field-by-field rather than calling the user-defined `init=` method). This was a bug that is now fixed in this PR.
This PR also modifies things so the only copies we create are the task-private copies (in a non-vectorized, non-gpuized loop). Previously, we would first create a "captured" copy of the `in` intent'd variable and then make copies from that. This would ensure all tasks would have the same copy; a safer thing to do in case there's a …
> Make semantics (of when to call init=) for 'in' intents more consistent between forall and foreach loops 

- util/test/sub_test.py
I recently updated to python3.12 and found that I was getting a `SyntaxWarning` for the string "'AM_ERR_RESOURCE \(Problem with requested resource\)'" when running `start_test`. The simple fix is to mark the string as a raw/regex string with `r`. I applied this fix, and also applied it to other filter strings which ultimately get passed to `re.search` to future-proof them.
Tested locally by running `start_test` on any test
> Fix sub_test error filtering for python 3.12

- test/gpu/native/studies/sort/gpu-sort-performance-explorer.chpl
- test/library/packages/Sort/performance/sort-performance-explorer.chpl
In the sort performance explorers for CPU and GPU sorting, number of bytes was hard-coded to be `8`. This was resulting in incorrect calculation for the MiB/s (sort speed) for types which were not 64 bits. Replaced `8` with `numBytes(eltType)` to fix this issue.
> Calculate the numBytes correctly

- tools/chpl-language-server/Makefile
- tools/chpl-language-server/chpl-shim
- util/buildRelease/install.sh
Adds a Makefile target for chpl-shim so that it gets put in `bin` and picked up by `make install`
> Make chpl-shim available in PATH

- test/studies/shootout/submitted/revcomp3.perfkeys
- test/studies/shootout/submitted/revcomp5.perfkeys
Somehow, as part of #24698, I broke the revcomp perfkeys files by removing the 'real' lines that are used to track the execution time. Worse, I saw this in my testing, but misinterpreted the warnings, thought it was just a sign that my perfdat files were out of sync with 'main' (not the first time that would've happened), deleted them, re-ran and saw that it was clean.  :facepalm:
I'm not sure quite what led me to remove the 'real' lines to begin with, but I've been working on this PR for 3-12 months, and I must've done it awhile ago for good or bad reasons and completely forgotten about it / overlooked it in reviewing the diff.  Sorry for the noise.
> Fix revcomp perfkeys files that I accidentally broke in #24698

- modules/packages/Zarr.chpl
Small PR to remove documentation of private helper methods and modules from the Zarr IO module. This will make the documentation for the module more comprehensible for users.
> Tidying up Zarr IO Module Documentation

- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/can-pass.cpp
- frontend/lib/resolution/resolution-queries.cpp
- frontend/test/resolution/testParams.cpp
Prior to this PR dyno would fail to properly coerce params in the cases of param-var initialization or when passing to a formal:
```chpl
proc foo(param arg: int(32)) param {
return arg;
}
// no matching candidate!
param fooval = foo(0xffff);
// initialization error complaining about type mismatch!
param p : int(32) = 0x1234;
```
These bugs were mainly caused by a failed result from ``canPass`` originating from a call to ``canInstantiate``. ``canInstantiate`` sees two concrete types that are different and returns a failure. In the case of failure, we should allow the switch statement below to try a conversion.
``getTypeForDecl`` is updated to use the correct Kind when calling ``getInstantiationType``, and ``getInstantiationType`` is updated to instantiate params.
Testing:
> Dyno: Fix some issues with implicit param coercions

- test/chplcheck/COMPOPTS
- test/chplcheck/MisleadingIndentation.chpl
- test/chplcheck/Unused.chpl
- test/chplcheck/Unused.good
- tools/chplcheck/src/driver.py
- tools/chplcheck/src/rules.py
This PR adjusts chplcheck's rule handling to support silencing advanced rules. Since advanced rules are full-scale AST traversals, they need to opt into being silencable by providing "anchors": nodes that can be marked with `@chplcheck.ignore` to skip warnings. This PR allows advanced rules to opt into silencing by yielding a tuple rather than a single node. The tuple is in the form `(node, anchor)`.
While there, I fixed a bug in `UnusedLoopIndex` that caused annotating a loop with _any_ attribute (including `chplcheck.ignore`, e.g.) to break the warning. This was due to an overly specific AST pattern, which I replaced with a plain getter. 
I also adjusted the tests to check the handling of `chplcheck.ignore`. This required tweaking `COMPOPTS` to allow through chplcheck attributes. …
> chplcheck: Allow silencing advanced rules

- frontend/include/chpl/resolution/can-pass.h
- frontend/lib/resolution/can-pass.cpp
- frontend/test/resolution/testCanPass.cpp
Fix a bug causing disambiguation between `unmanaged` and `borrowed` fully-generic class formals to fail.
This bug was likely introduced in https://github.com/chapel-lang/chapel/pull/24207, when borrowing was added as a separate type of conversion. The problem was `canInstantiate`'s usage of `canPassClassTypes`, which after that PR only checked for subtype conversion. Switched to use `canPassSubtypeOrBorrowing` to preserve original intention.
This PR also includes:
- some `canPass` refactors, most significantly inlining `canPassClassTypes` into its one remaining call site in `canPassSubtypeNonBorrowing`
- added testing in `testCanPass` for the original bug
Resolves https://github.com/Cray/chapel-private/issues/6070.
Testing:
> Fix can-pass disambiguation bug for fully-generic class formals

- test/chplcheck/activerules.chpl
- test/chplcheck/activerules.good
- test/chplcheck/activerules.prediff
- test/chplcheck/allrules.chpl
- test/chplcheck/allrules.good
- test/chplcheck/allrules.prediff
- tools/chplcheck/src/chplcheck.py
- tools/chplcheck/src/driver.py
- tools/chplcheck/src/rules.py
This PR adds two flags to `chplcheck`:
* `--list-rules`
This flag simply prints all the registered rules. Rules that are enabled by default are marked with a '*'. The documentation for the rule comes from the Python implementation's docstring.
" src="https://github.com/chapel-lang/chapel/assets/4361282/1b699fe7-ccc1-4f1d-9d93-3d5eb316d392">
* `--list-active-rules`
This flag prints only the rules that are currently enabled by the user, taking into account which rules were explicitly enabled/disabled using `--enable-rule` and `--disable-rule`.
> chplcheck: add ways to list rules

- man/chpl.rst
- man/chpldoc.rst
- test/release/examples/primers/modules.chpl
Adds per flag links to the chpl and chpldoc man pages in the rendered HTML (e.g. https://chapel-lang.org/docs/main/usingchapel/man.html). This allows direct links for flags, instead of having to tell users to search through the docs.
Example: https://chapel-lang.org/docs/main/usingchapel/man.html#man-module-dir
Tested locally by building docs. Also compared the generated man pages `man chpl`/`man chpldoc` and made sure there was no visual change in those docs as well.
<details>
All updates where made with the following script
```python3
import re
r = re.compile(r'(?<!:\n\n)(?<=\n)\*\*(?:-., )?\\--(?:\[no-\])?(.*?)( <.*?)?\*\*(?=\n)')
for filename in ["man/chpldoc.rst", "man/chpl.rst"]:
with open(filename, "r") as f:
content = f.read()
content = r.sub(lambda m: f".. …
```
> Allow chpl/chpldoc flags to be linked to individually

- compiler/codegen/library.cpp
- compiler/main/driver.cpp
Replaces uses of nonstandard variable length arrays with smart pointers
Tested by building compiler
> Remove uses of variable length arrays from compiler

- compiler/codegen/cg-symbol.cpp
- test/interop/C/PtrConstQualifier.chpl
- test/interop/C/use_PtrConstQualifier.cleanfiles
- test/interop/C/use_PtrConstQualifier.good
- test/interop/C/use_PtrConstQualifier.lastcompopts
- test/interop/C/use_PtrConstQualifier.prediff
- test/interop/C/use_PtrConstQualifier.test.c
Enable generation of `const` qualifiers for `c_ptrConst` types in exported routine signatures. Built on previous work by @riftEmber.
Addresses part of #24668.
TESTING
> Add 'const' qualifier to generated 'c_ptrConst' types in C code

- util/chplenv/chpl_llvm.py
Improves the errors when the version of CHPL_TARGET_CC does not match the version of CHPL_LLVM_CONFIG. The error will now distinguish between "can't find CHPL_TARGET_CC" and "the versions don't match". The error will also print out what versions are and what value was used for those environment variables.
Based on suggestions in https://github.com/chapel-lang/chapel/issues/24669
> Improve errors when clang version doesn't match llvm

- util/cron/test-darwin-m1.bash
- util/cron/test-linux64.bash
Adds `-blog` to some nightly test scripts to begin testing our blog sources regularly. This is a follow-up to #24510 that added this flag to the `nightly` script. 
This PR only adds testing to two configurations (`linux64` and `darwin-m1`) to avoid blowing up nightly testing in the case there are any problems when it runs for the first time.
> Add blog testing to some nightly scripts

- runtime/src/gpu/amd/gpu-amd.c
Accidentally reverted by https://github.com/chapel-lang/chapel/commit/48b9f2750d346493f8abb43ab97de2a3a6b19ee9. 
> GPU: Restore workaround in gpu-amd.c

- compiler/codegen/cg-symbol.cpp
- test/functions/export/in-intent-formals.chpl
- test/functions/export/in-intent-formals.compopts
- test/functions/export/in-intent-formals.good
- test/functions/export/in-intent-formals.h
Resolves #23419.
This PR forces stack-allocation of numeric `in`-intent formals of `export` procs during codegen for LLVM. Before this PR such formals were not stack-allocated. As a result, passing such a formal to __primitive("=") for assignment crashed the codegen; passing it to a ref formal incorrectly passed a stack-allocated copy. In-intent formals in the other cases are already stack-allocated along different code paths. During codegen to C stack-allocation is not an issue, so it is not affected by this PR.
While there, add a gdbShouldBreakHere() for LLVM codegen of a formal with a given breakOnCodegenID and factor out some code.
> Fix export procs with numeric in-intent formals

- test/studies/shootout/submitted/fasta3.chpl
- test/studies/shootout/submitted/fasta5.chpl
- test/studies/shootout/submitted/fasta6.chpl
- test/studies/shootout/submitted/knucleotide3.chpl
- test/studies/shootout/submitted/knucleotide4.chpl
- test/studies/shootout/submitted/revcomp3.chpl
- test/studies/shootout/submitted/revcomp5.chpl
- test/studies/shootout/submitted/revcomp8.chpl
After some discussion with the performance team, we decided we like this way better of creating non-locking stdin/stdout channels -- essentially cloning the default ones and renaming them.
(That said, we'd also like either built-in unlocked stdin/stdout or a simpler .getNonLocking() method that could be applied to clone any such channel).
> Switch CLBG non-locking stdin/stdout to use new idioms and names

- frontend/lib/resolution/resolution-queries.cpp
- frontend/lib/resolution/return-type-inference.cpp
Closes https://github.com/Cray/chapel-private/issues/6030. 
This PR fixes a segmentation fault that occurs while resolving a call to `locale.home`:
```Chapel
var x : locale;
var y = x.home;
```
There are two layers to this issue:
* The segmentation fault (a symptom) is caused by the auto-handler for infinite recursive queries. This handler (introduced in https://github.com/chapel-lang/chapel/pull/24321) replaces the computed (bogus) result of an infinitely recursive query with its default type. In this case, the infinite recursion comes from forwarding statements (see next bullet), but poisons `resolveFunction`.
Because `resolveFunction` is poisoned, it too returns `nullptr`. This makes code that relies on `resolveFunction` without checking for null break. The PR fixes this by adjusting …
> dyno: Fix resolution of `locale.home`

- test/studies/shootout/submitted/spectralnorm2.chpl
Yesterday, in doing some code cleanups, I couldn't remember why this version of spectralnorm's 'A' routine took explicit ': real' arguments and the other took the generic (therefore 'int') arguments.  At the time, I was thinking it was a correctness issue, and seeing that things worked fine either way, removed the constraints for cleaner code.
Last night's performance testing reminded me that it's really a matter of performance, as the 'real' versions permit better vectorization to take place.
As a result, I'm restoring them here, to restore the performance.
> Restore ': real' type constraints + therefore performance to spectralnorm2

- make/compiler/Makefile.intel
Ignore discarded const qualifiers in generated C code with the Intel `icc` compiler, as we do for `gcc`.
This is newly needed because we now represent `export`ed `c_ptrConst`s as `const`, as of https://github.com/chapel-lang/chapel/pull/24674.
Testing:
> Ignore discarded const qualifier with Intel compiler

- frontend/include/chpl/types/CStringType.h
- frontend/include/chpl/types/NilType.h
- frontend/include/chpl/types/Param.h
- frontend/include/chpl/types/VoidType.h
- frontend/lib/types/CStringType.cpp
- frontend/lib/types/ClassType.cpp
- frontend/lib/types/CompositeType.cpp
- frontend/lib/types/ExternType.cpp
- frontend/lib/types/NilType.cpp
- frontend/lib/types/Type.cpp
- frontend/lib/types/VoidType.cpp
- frontend/test/resolution/testResolverVerboseErrors.cpp
This PR adjusts the `stringify` function to properly support generating Chapel syntax, and not a Dyno approximation of it. Fixes https://github.com/chapel-lang/chapel/issues/24481.
The most changes were made to `CompositeType`, but other types (`Void`, `CString`, and `Nil`) were also adjusted. The PR also adjusted the stringification of string params to quote the strings, so that it prints `param x = "hello"` and not `param x = hello`, which looks like an identifier access.
> dyno: adjust `stringify` on types to actually produce Chapel syntax

- modules/standard/GPU.chpl
- runtime/include/gpu/amd/chpl-gpu-gen-includes.h
- runtime/include/gpu/chpl-gpu-gen-common.h
- runtime/include/gpu/cpu/chpl-gpu-gen-includes.h
- runtime/include/gpu/nvidia/chpl-gpu-gen-includes.h
- test/gpu/native/syncWarp.chpl
For Nvidia GPUs, starting with Volta architectures and later, threads within a warp can diverge. For applications needing memory and synchronization barriers, calling `syncWarp` provides this functionality within warps. It is like `syncThreads`, but at a more granular level.
For AMD GPUs, threads within a warp are guaranteed to be executed in lockstep. Therefore `syncWarp` is a no-op in that case. This may change in the future as new AMD architectures emerge.
Resolves https://github.com/Cray/chapel-private/issues/5002, https://github.com/Cray/chapel-private/issues/5453
> Add support for syncWarp

- util/chplenv/chpl_llvm.py
Removes a usage of f-strings from chpl_llvm.py added in https://github.com/chapel-lang/chapel/pull/24687. This syntax was not added until Python 3.6 and broke out testing for earlier python versions
> Remove usage of f-strings to support older python versions

- test/interop/C/errorMessage/errorInArgNMismatch.skipif
`errorInArgNMismatch` test should be run with the LLVM backend only. But `CHPL_LLVM==none` is not a sufficient skipif as `CHPL_TARGET_COMPILER` is the ultimate environment controlling the backend. Our c-backend correctness testing indeed has `CHPL_LLVM=system`, which was causing the test to be not skipped.
This PR fixes that.
> Fix errorInArgNMismatch skipif to cover C backend more properly

- frontend/lib/resolution/InitResolver.cpp
- frontend/lib/resolution/Resolver.cpp
- frontend/lib/resolution/Resolver.h
- frontend/test/resolution/testMethodFieldAccess.cpp
Resolves https://github.com/Cray/chapel-private/issues/6076.
This PR adjusts Dyno's resolver to support selecting a parenless procedure from an overload set.
To make this work, I had to adjust the `lookupIdentifier` method on the `Resolver` to not immediately issue ambiguity errors even if multiple candiadte IDs were found. Instead, it now uses an out-parameter to return a `ParenlessOverloadInfo` struct. This struct has a public boolean property for calling code to check if all candidates were parenless functions; if this is the case (whether there were multiple candidates or one), we run call resolution. 
To match Dyno's existing behavior (which makes ambiguity between method and non-method parenless procedures an error), we actually run call resolution twice: one with a method receiver, …
> dyno: handle parenless overloads based on 'where' clauses

- test/studies/shootout/nbody/bradc/nbody-blc.chpl
While thinking about our fastest/smallest nbody entry on yesterday's CLBG results, I was wondering how a foreach-based version would compare to the for+param version in terms of performance these days. It will probably be less compact in terms of code size—particularly because we're using a tuple of records, which require a `with` clause to modify—but it also feels like a more intuitive use of the language features.  And since my study version has been in sync with the submitted nbody3.chpl, no need to keep timing it as it was.
> Change param-based nbody to foreach-based
