modules/standard/Reflection.chpl
These terms are a bit jargony and should be replaced with clearer language.
=> Stop using lvalue/rvalue in Reflection module docs

.github/workflows/CI.yml, frontend/include/chpl/types/CPtrType.h, frontend/lib/resolution/default-functions.cpp, frontend/lib/resolution/default-functions.h, frontend/lib/resolution/prims.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/lib/types/CompositeType.cpp, frontend/lib/types/Type.cpp, frontend/test/resolution/testCPtr.cpp, frontend/test/resolution/testReturnTypes.cpp
This PR contains various improvements to the representation of ``c_ptr`` and ``c_ptrConst`` in the frontend.
The most significant change is to stop treating ``c_ptr[Const]`` as a builtin and instead rely on the ``c_ptr`` and ``c_ptrConst`` classes in ``CTypes``. This allows us to use a real ID as a point of reference to find methods on ``c_ptr`` when ``CTypes`` is not in scope. Tests have also been updated to now use ``CTypes``.
Another notable change is to allow ``eltType`` to be called on both types and values of ``c_ptr``. This is achieved by updating ``getCompilerGeneratedMethodQuery`` to take a ``QualifiedType`` instead of a ``Type*``, so that we can preserve the relevant ``Kind``.
Other changes:
- implement PRIM_ARRAY_GET for ``c_ptr``
- allow ``c_ptr`` in PRIM_STRING_LENGTH_BYTES …
=> Dyno: Fixes to c_ptr representation

test/gpu/native/errors/outeraccess.suppressif
On a new multilocale GPU testing with OFI, we see a failure in a test with suppressif `CHPL_COMM==gasnet`. This PR adjusts it to check `CHPL_COMM!=none` instead to cover OFI, too.
=> Modify a GPU test's suppressif to cover all comm layers

util/cron/test-gpu-ex-cuda-12.ofi.bash
This PR adds a nightly config for CUDA 12 + ofi testing on EX systems.
=> Add CUDA 12 + ofi testing on EX

doc/rst/tools/chpl-language-server/chpl-language-server.rst, doc/rst/tools/chplcheck/chplcheck.rst
Removes a small note in the docs about a possibly broken link, the link should now always work.
=> Remove note about VSCode extension in docs

test/ANNOTATIONS.yaml
Add annotations to nightly perf graphs for Arkouda indicating when we updating to 1.33 and 2.0 release.
=> annotations for updating Arkouda release

frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testMultiDecl.cpp, frontend/test/resolution/testTuples.cpp
This commit fixes a bug in which module-scope MultiDecl or TupleDecl variables had an UnknownType outside of their declarations. The problem was that ``typeForModuleLevelSymbol`` was trying to fetch the previously resolved variable with ``resolveModuleStmt`` using the ID of the variable. This didn't work because the ID of a MultiDecl or TupleDecl entry is not at the statement level and so a previous query result did not exist.
The solution is to add a helper that walks up the tree to find the correct module statement ID.
Testing:
=> Dyno: Fix resolution of module-scope MultiDecl and TupleDecl

compiler/resolution/lowerIterators.cpp, test/statements/foreach/reduceIntent.chpl, test/statements/foreach/reduceIntent.good, test/statements/foreach/varIntent.chpl, test/statements/foreach/varIntent.good
We don't currently support `var` intents on `foreach` loops. Previously, if users tried to do this we would assert and produce an "internal error". This PR makes things a little more user friendly by giving an error message. 
While there I also add a test locking down that we produce an error for reduce intents on `foreach` (which we also don't currently support)
See https://github.com/chapel-lang/chapel/issues/24764.
TODO:
=> user friendly error for var intent on foreach

util/cron/test-darwin-m1.bash, util/cron/test-linux64.bash
Reverts commits from PR #24690 because cloning the blog from github.com in the nightly script failed on the test machines, so undoing for now. 
Error reported is 
```
Cloning into 'chapel-blog'...
fatal: could not read Username for 'https://github.com': Device not configured
Error cloning blog repo: 128
```
which I think is a configuration issue with git
=> Revert blog test

modules/internal/String.chpl
Dyno has exposed the fact that the NVStringFactory module requires use-ing ChapelStandard to bring the '=' operators for base types. This original bug was a failure to resolve ``=`` between two integers.
Testing:
=> Dyno: Fix NVStringFactory failure by using ChapelStandard

test/ANNOTATIONS.yaml
Add annotation to nbody test (this has caused us to go from running in 3.97s to 4.79):
```
04/03/24:
- Change param-based nbody to foreach-based (#24745)
```
Also added some historical annotations that also had performance impacts:
```
12/18/23:
- Always use -fno-math-errno to configure the LLVM optimizer (#24066)
02/21/24:
- Codegen sqrt and fabs directly to llvm intrinsics when possible (#24455)
```
=> annotation updates for nbody test

util/cron/test-perf.gpu-ex-cuda-12.bash
This adds a nightly testing config for single locale gpu perf tests using CUDA 12 on pinoak
=> Adding single locale gpu performance testing using CUDA 12

runtime/include/chpl-topo.h, runtime/src/tasks/qthreads/tasks-qthreads.c, runtime/src/topo/hwloc/topo-hwloc.c, runtime/src/topo/none/topo-none.c
Bind the progress thread to the locale's PUs with COMM=ofi. Otherwise, when there are co-locales the progress thread may migrate to PUs used by another co-locale, or not used at all. This can lead to incorrect performance measurements.
=> Bind progress thread to locale's PUs with COMM=ofi

runtime/include/gpu/chpl-gpu-gen-common.h, runtime/include/gpu/cpu/chpl-gpu-gen-includes.h
Follow up to #24751
These default arguments are not supported in C. They were redundant anyway so we are not losing anything here; the module version of syncWarp already has the default arguments so it doesn't matter if the implementation has that.
Fixes some nightly test failures.
=> Remove default arguments from syncWarp impl part 2

test/chplcheck/SimpleDomainAsRange.chpl, test/chplcheck/SimpleDomainAsRange.good, tools/chapel-py/src/method-tables/uast-methods.h, tools/chplcheck/src/rules.py
Adds a linter warning for simple domains used in loops. Domain literals like `{1..10}` used as the iterand of a loop cause an unnecessary domain creation. Although this may be optimized away by the compiler, it is cleaner and possibly more performant to not have the domain literal.
=> Add linter warning for simple domains used in loops

compiler/AST/astutil.cpp, compiler/include/astutil.h, compiler/optimizations/gpuTransforms.cpp, compiler/passes/convert-uast.cpp, test/gpu/native/assertOnGpuVarRuntime.chpl, test/gpu/native/assertOnGpuVarRuntime.good, test/gpu/native/ineligibleBlockSizeExpr.chpl, test/gpu/native/ineligibleBlockSizeExpr.good
Fixes https://github.com/chapel-lang/chapel/issues/24611.
Prior to this PR, it wasn't possible to set GPU block size to an expression that isn't GPU eligible. This was because the GPU attribute and function call end up as primitives _inside the loop body_, and get picked up by the ineligibility detector. 
To make this work, we need to fence off GPU primitives as "special", so that the ineligibility detector can skip them. Fortunately, there's already a feature for this -- the `gpu primitives block` attribute + "block type". Until now, this block was only used GPU attributes on variables (to make the primitives easy to copy and relocate into loop expressions). However, by making plain loops with attributes also use this block, we can create a "barrier" between the ineligibility detector …
=> GPU: allow `@gpu.blockSize` attribute to contain GPU-ineligible expressions

modules/standard/Regex.chpl, runtime/include/qio/qio_regex.h, runtime/src/qio/regex/bundled/re2-interface.cc, runtime/src/qio/regex/none/fail-regex.c, test/regex/replaceTricky.chpl, test/regex/replaceTricky.good
This PR optimizes the 'replace' methods in Regex. It avoids string copies that were coming from moving the data to and from a `std::string` when calling RE2's Replace/GlobalReplace.  It does so by using our own implementation of Replace by calling RE2's Match function in the re2-interface.cc code so that we can construct a result buffer by repeatedly doubling & then provide that when constructing a Chapel string.
While there, this removes the need for doReplaceAndCountSlow, since now that we have our own implementation of the replace function, we can handle a maximum number of matches right there. While here, I noticed a bug in the old implementation, which this change fixes.
The bug:
``` chapel
use Regex;
writeln("bb".replace(new regex(""), "a"); // ababa
writeln("bb".replace(new …
```
=> Avoid string copies by implementing replace with match

frontend/lib/resolution/call-init-deinit.cpp, frontend/test/resolution/testTuples.cpp, frontend/test/test-common.cpp, frontend/test/test-common.h
This PR resolves a bug where the frontend was issuing a constness error for statements like ``(a, b, c) = foo();``. The error originated from an attempt to resolve an assignment operator between the tuple literal ``(a, b, c)`` and the returned tuple from ``foo()``. The LHS naturally accepts a ``ref``, which is not compatible with a tuple literal. The Resolver has already taken responsibility for implementing this case, so resolving the assignment would be incorrect. This PR avoids resolving the assignment altogether.
A new helper function, ``buildStdContext()``, is added to the ``test-common.h`` header. This function returns a ``unique_ptr`` to a Context that has been configured to load the standard modules. Use of the standard modules in this instance was necessary to expose the issue …
=> Dyno: Fix constness error for unpacked tuple assignment

test/studies/bale/aggregation/histo.chpl, test/studies/bale/aggregation/ig-readme.md, test/studies/bale/aggregation/ig.chpl
These benchmarks were originally written to use Cyclic by default in order to more closely mimic the reference versions that they were based upon.  In our performance runs and work, we've definitely focused on Block in recent runs and years, so here I'm switching the default to indicate that preference without removing the ability to switch back to Cyclic.  Updated the README by flipping the flags specified on the 'chpl' command lines.
=> Switch aggregation-based bale benchmarks to use Block by default

util/cron/test-perf.gpu-ex-rocm-54.bash
This adds a nightly testing config for single locale gpu perf tests using ROCm 5.4 on pinoak
=> Adding single locale gpu performance testing using ROCm 5.4

runtime/src/topo/none/topo-none.c
Make `chpl_topo_bindCPU` and `chpl_topo_bindLogAccCPUs` no-ops with `CHPL_HWLOC=none` instead of warnings. In general, functionality is pretty limited with `CHPL_HWLOC=none` and there is no reason to warn the user about these particular limitations.
=> Make CPU binding a no-op with CHPL_HWLOC=none

compiler/main/driver.cpp, compiler/passes/convert-uast.cpp, frontend/include/chpl/framework/Context.h, frontend/include/chpl/resolution/ResolvedVisitor.h, frontend/lib/framework/Context.cpp, frontend/lib/resolution/InitResolver.cpp, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/default-functions.cpp, frontend/lib/resolution/disambiguation.cpp, frontend/lib/resolution/prims.cpp, frontend/lib/resolution/resolution-error-classes-list.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/util/assertions.cpp, util/chpl-completion.bash
This PR addresses a variety of segfaults and crashes encountered while running the primers with ``--dyno``.
Some other changes:
- Adds ``--dyno-no-break-error`` to disable the breakpoint in ``Context::report``. This is useful when trying to avoid a breakpoint for every single error during compilation (which, right now, is quite a few).
- ``ErrorNoMatchingCandidates`` is updated to account for TupleDecls
Testing:
=> Fix various segfaults and crashes in frontend

frontend/include/chpl/resolution/resolution-queries.h, frontend/include/chpl/resolution/resolution-types.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/Resolver.h, frontend/lib/resolution/call-init-deinit.cpp, frontend/lib/resolution/copy-elision.cpp, frontend/lib/resolution/prims.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/resolution-types.cpp, frontend/test/ErrorGuard.h, frontend/test/resolution/testResolve.cpp
Resolves https://github.com/Cray/chapel-private/issues/6100. 
This PR implements resolving function calls like `M.f()`, where `M` is a module. This effort is in two parts:
1. **Detecting when a module-qualified call occurs (i.e., distinguishing `myVar.f()` from `MyMod.f()`)**. Currently, `CallInfo::create` is responsible for doing this for other things (e.g., detecting method calls, detecting calls to `proc this`, etc). This PR adjusts `CallInfo::create` with another out-parameter to determine if a module was called.
To achieve this, I flattened the logic in `CallInfo::create` a bit, so that the cases and order in which they are tried are more obvious. At present, they are as follows, in order of priority: call to _any_ value (including one retrieved from a module via `M.x`), call to …
=> dyno: resolve module-qualified function calls.

compiler/codegen/cg-expr.cpp, compiler/codegen/cg-type.cpp, make/compiler/Makefile.gnu, make/compiler/Makefile.intel, runtime/include/chpl-comm-compiler-macros.h, runtime/include/chplio.h, runtime/include/chpltypes.h, runtime/include/gpu/chpl-gpu-gen-common.h, runtime/src/chplio.c, test/extern/bradc/cprintarr.h, test/extern/diten/testVoidExternFns.h, test/extern/kbrady/array_fns.h, test/extern/passArrays/passViewToExtern.h, test/studies/shootout/k-nucleotide/bharshbarg/knucleotide-associative.chpl, test/studies/shootout/k-nucleotide/bharshbarg/knucleotide-chaining.chpl, test/users/bugzilla/bug794131/bug794131.chpl, test/users/ibertolacc/void_extern_proc_array.chpl
Reverts chapel-lang/chapel#24746
Reverting as I accidentally merged this before a day off and checked in to find a lot of failures, which I don't want to resolve on my day off.
[reverting broken PR, not reviewed]
=> Revert "Emit C `const` qualifier for `c_ptrConst` type"

modules/standard/IO.chpl, test/io/ferguson/utf8/offset-after-invalid-read.chpl, test/io/ferguson/utf8/offset-after-invalid-read.good
This PR adds a test to lock in the behavior and updates the I/O documentation to clarify the current behavior.
Reviewed by @jeremiah-corrado - thanks!
=> Clarify where fileReader offset is after reading invalid UTF-8

test/release/examples/primers/distributions.chpl
debug code:
```Chapel
// ...
const BigBlockSpace = blockDist.createDomain({0..n+1, 0..n+1});
var BigA: [BigBlockSpace] int;
forall biga in BigA do biga = here.id;
writeln("Big Block Array Ownership Map");
writeln(BigA);
writeln();
// ...
```
**before**
produces with `./distributions -nl 2 --n 3`
```
Block Array Ownership Map
0 0 1
2 2 3
4 4 5
// ...
Big Block Array Ownership Map
0 0 0 1 1
0 0 0 1 1
2 2 2 3 3
2 2 2 3 3
4 4 4 5 5
```
**with proposed changes**
produces with `./distributions -nl 2 --n 3`
```
Block Array Ownership Map
0 0 1
2 2 3
4 4 5
// ...
Big Block Array Ownership Map
0 0 0 1 1
0 0 0 1 1
2 2 2 3 3
4 4 4 5 5
4 4 4 5 5
```
=> docs: Fix BigBlockSpace not sharing domain with BlockSpace in primer

frontend/lib/types/CompositeType.cpp, frontend/test/resolution/testRanges.cpp
Today on `main`, trying to feed a range literal into a function that accepts a `range(?)` reports the following error:
```
─── error in poundrangeparam.chpl:3 [NoMatchingCandidates] ───
Unable to resolve call to 'myProc': no matching candidates.
|
3 | myProc(1..10);
|
The following candidate didn't match because an actual couldn't be passed to a formal:
|
1 | proc myProc(x: range(?)) {}
|             ⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺
|
[frontend/lib/types/CompositeType.cpp:126 in stringify] Unimplemented: attempting to stringify odd type representation as Chapel syntax
The formal 'x' expects a value of type '_range', but the actual was a value of type 'range(<const-var> int(64), ChapelRange.boundKind@2, ChapelRange.strideKind@2)'.
|
3 | myProc(1..10);
|        ⎺⎺⎺⎺⎺
|
```
The reason for this is that the …
=> dyno: make the 'synthetic' `getRangeType` be called `_range` to match standard library.

frontend/include/chpl/types/ExternType.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/types/ExternType.cpp, frontend/test/resolution/testOpaqueExternTypes.cpp
Fixes https://github.com/Cray/chapel-private/issues/6096, implementing the proposal to make `==` report 'false' on two types with the same `extern` name if they're declared in different scopes.
The fix really is quite easy: bundling the ID of the variable that declares the extern type (much like a composite type declaration does) makes this fall out quite naturally.
=> dyno: use declaration site of extern types to compute method scopes

modules/dists/BlockDist.chpl, runtime/include/chpl-gpu.h, runtime/src/chpl-gpu.c, test/gpu/native/studies/coral/coral.chpl, test/gpu/native/studies/coral/coral.good
This PR modifies the `test/gpu/native/studies/coral.chpl` test to support multiple locales+GPUs+tasks.
The input is generated on `Locales[0]` and then chunked up to locales before GPU operation begins. Eventually we want to have each locale read their own portion of the input file and write their outputs. So, this is a temporary solution for having reproducible output.
This PR also changes the iteration order of the GPU kernel for better memory coalescing. This results in changes in the checksum. I am fairly confident that this is due to the order of floating point operations and the changes at individual elements are less than half a percent for cases that I tested.
TODO: this also has a workaround for https://github.com/chapel-lang/chapel/issues/23574 that ideally should be removed when …
=> Add multiple GPU, multiple Locale support for the Coral code

util/cron/nightly, util/cron/test-linux64-blog-only.bash
Adds a test script for testing only the chapel blog and adjusts blog arguments and handling in the `nightly` testing script. 
Changes the nightly script to no longer attempt to clone the chapel-blog repo, instead accepting the location of the repo as a separate argument `-blogdir` or through an environment variable, `CHPL_NIGHTLY_BLOGDIR`. 
These changes allow us to better support testing of the chapel-blog using our nightly test framework by moving the clone step outside of the nightly test and into the CI setup. 
Additionally, this PR adds a new script for testing the blog in Chapel's default `linux64` configuration.
=> add blogonly test script, adjust nightly script blog handling

frontend/lib/resolution/InitResolver.cpp, frontend/test/resolution/testNew.cpp, frontend/test/resolution/testRanges.cpp
This PR improves initializers for generic types with initializers. The core issue it's trying to address is the fact that, prior to this PR, calling `new range` resulted in an assertion error (turned into a regular error on `main` by #24790):
https://github.com/chapel-lang/chapel/blob/2d130287495a49f5f91555faab0b1787e5368d0f/frontend/lib/resolution/resolution-queries.cpp#L2113
This was caused by the fact that `range` is generic-with-defaults. Since its fields, when defaults are used, are thus all concrete, the `InitResolver` skipped re-assigning them. However, this is obviously incorrect, since the record being constructed is (at the time of initialization) fully generic, so the default values of its fields should have no say in whether we can assign to them. This PR changes the logic to …
=> dyno: improve initializers for generic types with (some, all) defaults

frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/resolution-queries.cpp
Depends on https://github.com/chapel-lang/chapel/pull/24814. 
This PR switches our way of resolving range literals to use the (production) `chpl_build_*_range` functions. This was always planned, but until now, range constructors like `new range` didn't work. Since #24814 makes most range constructors work (I discovered plain `range()` didn't), we can now use the builders.
To view the diff without #24814, see here: https://github.com/chapel-lang/chapel/pull/24816/files/b648c39e05e8a072014a4bfe46f45654edc7e692..3b18d41c12bed27f0ef79c743a58e8583f33b61c
=> dyno: resolve range literals using `chpl_build_*_range`.

frontend/include/chpl/resolution/scope-queries.h, frontend/include/chpl/resolution/scope-types.h, frontend/lib/resolution/scope-queries.cpp, tools/chapel-py/src/core-types.h, tools/chapel-py/src/method-tables/core-methods.h, tools/chapel-py/src/python-types.h, tools/chpl-language-server/src/chpl-language-server.py
Should fix #24743.
This PR beefs up CLS's ability to find symbols in imported modules. It does so by:
* Transitively searching for visible symbols instead when modules are imported. This means that if module `A` re-exports variables from module `B`, importing `A` will make `B`'s variables appear in completions.
* Ensuring that auto modules, in addition to regular modules, are considered for auto-completion. These are the modules that bring in `Locale`, `here`, and all others.
Prior to this, Dyno did not have a way to collect _all_ visible symbols (opting instead for per-symbol lookups). Thus, this PR adds the corresponding Dyno query (memoization and all).
This PR does _not_ address the `Locales.size` aspect of #24743, as this relies on parser improvements and type resolution (the former …
=> LSP: use globally visible symbols (including via auto modules) to suggest autocompletion

tools/chapel-py/setup.py
Prior to this PR, if a developer changed the a header file in the python bindings, it would not trigger a rebuild of the C++ sources. This PR fixes that by making `setup.py` depend on the header files
=> Make chapel-py rebuild on changes to header files

runtime/src/launch/pbs-gasnetrun_ibv/launch-pbs-gasnetrun_ibv.c
Pass the `exclhost` option to `qsub` requesting exclusive access to the nodes.
=> Specify exclhost with the pbs-gasnetrun_ibv launcher

frontend/include/chpl/uast/uast-classes-list.h, test/chplcheck/CaseRules.chpl, test/chplcheck/IncorrectIndentation.chpl, test/chplcheck/IncorrectIndentation.good, test/chplcheck/activerules.good, test/chplcheck/allrules.good, tools/chplcheck/src/rules.py
This PR does a few things.
1. Fixes a small bug in which `When` was listed to inherit from `SimpleBlockLike`, but didn't. This led to some segmentation faults / memory issues when iterating over 'statements' of 'SimpleBlockLike' nodes.
2. Adjusts the `IncorrectIndentation` rule to skip all private and public things, because visibility modifiers' locations are not correctly reported by the parser (https://github.com/chapel-lang/chapel/issues/24818).
3. Adds a new rule for cases like this:
```Chapel
enum {};
```
Previously, `;` (which is unnecessary here and creates a new statement), would count as a same-line sibling to `enum`, resulting in a warning for `IncorrectIndentation`. However, the trouble isn't that `;` is improperly indented, but that it exists at all. Thus, the PR adds a new …
=> chplcheck: improve the 'bad indentation' rule, and add rule for ';;;'.

runtime/include/chpl-gpu.h
https://github.com/chapel-lang/chapel/pull/23913 made some changes to the `--debugGpu` output. I wasn't expecting/remembering that some tests use that flag to lock in behavior. Taking a look at the changes in question, I think they are more noise than signal in most common use cases of `--debugGpu` to me. So, this PR just reverts those changes.
Test
=> Revert some recent changes to --debugGpu output

test/gpu/native/studies/coral/coral.chpl
While modifying the coral code, I dropped the printout of the perfkey, breaking performance testing. This PR fixes that.
=> Fix coral's perfkeys

test/library/standard/IO/readAll/readStringInvalid.chpl, test/library/standard/IO/readAll/readStringInvalid.good
Follow-up to PR #24783.
This PR fixes a portability problem in the new test readStringInvalid.chpl. The error prints out differently on Mac OS X vs Linux.
=> Fix a portability problem in a new test

runtime/src/launch/slurm-srun/launch-slurm-srun.c
If the `slurm-srun` launcher is unable to parse the output from `sinfo`, print the output to help with debugging.
=> Show sinfo output when it can't be parsed

tools/chapel-py/src/method-tables/core-methods.h, tools/chpl-language-server/src/chpl-language-server.py
Fixes two different bugs in CLS
1. CLS would crash with the following code (#24843)
```chapel
enum myEnum {a, b, c};
use myEnum;
```
2. Visual glitch with symbol highlighting. Locations from other modules where incorrectly being applied to the current document
Tested locally
resolves #24843
=> Fix two bugs in CLS

runtime/src/comm/ofi/comm-ofi.c
Sequential consistency requires that multiple writes to the same memory address occur in program order. This requires `FI_ORDER_RMA_WAW` ordering guarantees when in the `message-order-fence` MCM mode.
=> Require FI_ORDER_RMA_WAW with message-order-fence MCM

modules/standard/IO.chpl, runtime/include/qio/qio_error.h, runtime/include/qio/qio_formatted.h, runtime/src/qio/qio_formatted.c
Follow-up to PR #24783.
This PR is intended to improve the performance of `readAll(string)` and other functions using `readStringImpl`. It adds `qio_channel_read_chars` which is similar to `qio_channel_read_char`, but can read many codepoints at once, and then uses it in `readStringImpl`.
How does it affect performance? These measurements were collected on my PC with `start_test -performance test/studies/shootout/submitted/regexredux2.chpl --numtrials 4` (and note that `main` here includes #24783). Please note that the performance gain for `readAll` itself will be a larger percentage (since it is not most of the benchmark time). The speed gain for `readAll(string)` specifically within the benchmark is about 2x.
| Benchmark    | main   | this PR | speedup    |
| ------------ | ------ | …
=> Further improve readAll(string) performance

compiler/codegen/cg-expr.cpp, compiler/codegen/cg-symbol.cpp, compiler/codegen/cg-type.cpp, compiler/include/clangUtil.h, compiler/llvm/clangUtil.cpp, compiler/llvm/llvmAggregateGlobalOps.cpp, compiler/llvm/llvmDebug.cpp, compiler/llvm/llvmExtractIR.cpp, compiler/llvm/llvmGlobalToWide.cpp, compiler/llvm/llvmUtil.cpp
Given that we no longer support LLVM versions <= 10, this PR removes compiler code guarded by `#if` conditionals that will never be used.
While there, fix a bug in checking for LLVM 12 and reorder a couple of lines.
Motivation: get some obsolete code out of my way for an upcoming PR.
Testing: standard and gasnet paratest, using LLVM 15.
=> Remove compiler code for LLVM 10 and below

runtime/src/topo/hwloc/topo-hwloc.c
Do not issue a warning if the platform doesn't support CPU binding and the runtime tries to bind a thread to the set of accessible PUs (e.g., the progress thread in the communication layer). `qthreads` does not issue a warning if threads can't be bound, so neither should we.
=> Remove warning if platform doesn't support CPU binding

frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/Resolver.h, frontend/lib/resolution/VarScopeVisitor.cpp, frontend/lib/resolution/maybe-const.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/test/resolution/testMethodCalls.cpp, frontend/test/resolution/testNew.cpp, frontend/test/resolution/testRanges.cpp, frontend/test/resolution/testResolve.cpp, modules/internal/ChapelRange.chpl
This PR makes a few bugfixes that enable Dyno to resolve nontrivial ranges. Closes https://github.com/Cray/chapel-private/issues/6102 in favor of https://github.com/chapel-lang/chapel/issues/24854. Closes https://github.com/chapel-lang/chapel/issues/24811. Closes https://github.com/Cray/chapel-private/issues/4932. Closes https://github.com/Cray/chapel-private/issues/6108. 
To make all of this work:
* Adds the 'none' keyword, which is used in a bunch of resolver functions. In doing so, moves both 'nil' and 'none' handling into the "builtin scope". In addition to make `none` work, this also fixes a (previously untracked) bug in which `nil` could not be found in initializers, since `InitResolver` didn't go through `resolveIdentifier` (where `nil` was handled), but did go through …
=> dyno: (almost) resolve nontrivial ranges

frontend/include/chpl/resolution/scope-queries.h, frontend/lib/resolution/scope-queries.cpp, tools/chapel-py/src/method-tables/core-methods.h, tools/chpldoc/chpldoc.cpp
The function `findUsedImportedModules` doesn't just return modules, it also returns enums. Thus, the name is misleading; I renamed the function to fit its actual purpose.
Reviewed by @mppf  -- thanks!
=> Rename a function to make it clearer that it returns non-module IDs

test/man/checkManPages
Fixes a syntax warning that would show in `test/man/checkManPages` when the test system was run with python3.12. Similar to https://github.com/chapel-lang/chapel/pull/24643 and https://github.com/chapel-lang/chapel/pull/24664
Not reviewed - trivial
=> Fix syntax warning in checkManPages with python3.12

doc/rst/language/spec/generics.rst, doc/rst/language/spec/procedures.rst, frontend/test/resolution/testPoi.cpp, test/functions/resolution/parenless-method-poi.chpl, test/functions/resolution/parenless-method-poi.good, test/functions/resolution/parenless-no-poi.chpl, test/functions/resolution/parenless-no-poi.good, test/functions/resolution/parenless-overloads.bad, test/functions/resolution/parenless-overloads.skipif
This PR updates the language specification to clarify POI behavior of non-method parenless calls.
* adds a test to make sure that parenless non-method calls can't be resolved through POI and parenless method calls can be
* also adds C++ dyno tests of the same
* updates the language specification to describe this behavior
* adjusts a few test-specific problems with a .future about parenless functions
The rationale for calls for parenless methods not being found through POI is primarily that it simplifies the case of resolving an identifier. Any identifier could potentially be a parenless call that is found through POI. At the same time, the production compiler has not considered POI as a source for parenless non-method calls. (And one reason for that is the way the production compiler …
=> Clarify language specification about parenless calls and POI

util/cron/load-base-deps.bash
Update `util/cron/load-base-deps.bash` to use the path of a newer Spack install for loading dependencies on Osprey.
Tested manually with one Osprey job that this still works.
Follow up to https://github.com/chapel-lang/chapel/pull/24271.
[trivial change unlikely to cause problems review can catch, not reviewed]
=> Use newer path for Spack install on Osprey

frontend/lib/resolution/Resolver.cpp, frontend/lib/types/CompositeType.cpp
Fix an error message observed in `testInteractive --std` for some codes that include a range literal.
This occurred due to the `Resolver` looking up the existence of `ChapelRange._range` AST as a way of checking if the standard library is available before proceeding with range resolution. However, this can get hit before the `ChapelRange` module is resolved, such as when a range is used as an argument to a method on another type (e.g., slicing). The `idToAstQuery` for `ChapelRange._range` fails, and that stored result is used later when the `_range` AST _does_ exist and we need to get it.
Fixed by replacing the AST existence check with a call to `CompositeType::isMissingBundledRecordType`, plus fixing the name of the type (`range`->`_range`) in that method. While there, also removed a …
=> Fix dyno range literal resolution bug

runtime/src/comm/ofi/README.md
Update the `message-order-fence` description to include `FI_ORDER_RMA_WAW`, which is necessary to provide sequential consistency for individual tasks.
Resolves https://github.com/Cray/chapel-private/issues/6169.
=> Update message-order-fence description

tools/chapel-py/src/method-tables/uast-methods.h
Depends on https://github.com/chapel-lang/chapel/pull/24878.
This PR fixes a segmentation fault that occurs when we try to resolve the type of an expression in a particular instantiated function. Resolving concrete functions can fail (e.g., due to recursion), and return null. We didn't handle that. This PR fixes that.
=> LSP: another hot fix for runtime crashes

runtime/src/comm/ofi/README.md, runtime/src/comm/ofi/comm-ofi.c
Fenced operations in `message-order-fence` MCM mode in `COMM=ofi `are used to
force visibility of previous operations. Previously, we did not also specify
`FI_DELIVERY_COMPLETE`, and as a result the fence only forced previous
operations to be transmit-complete, meaning they were transmitted but might
not be visible in memory. Specifying `FI_DELIVERY_COMPLETE` along with `FI_FENCE`
causes the previous operations to be visible.
Resolves https://github.com/Cray/chapel-private/issues/6169.
=> Fenced operations in message-order-fence mode must be delivery-complete

make/compiler/Makefile.intel
Due to an apparent difference in how ICC interprets `const` pointer `typedef`s to arrays, suppress "discarding qualifiers" warnings in ICC.
See issue https://github.com/chapel-lang/chapel/issues/24894 for more information.
Follow up to https://github.com/chapel-lang/chapel/pull/24809.
Testing:
=> Suppress ICC const discarding warning

test/hash/throwingHash.chpl, test/hash/throwingHash.good, test/hash/throwingHashCallsRef.bad, test/hash/throwingHashCallsRef.chpl, test/hash/throwingHashCallsRef.future, test/hash/throwingHashCallsRef.good, test/hash/throwingHashInModule.bad, test/hash/throwingHashInModule.chpl, test/hash/throwingHashInModule.future, test/hash/throwingHashInModule.good, test/hash/throwingHashIndirect.chpl, test/hash/throwingHashIndirect.good, test/hash/throwingHashRef.bad, test/hash/throwingHashRef.chpl, test/hash/throwingHashRef.future, test/hash/throwingHashRef.good, test/interop/python/cptrConstCharArrays.bad, test/interop/python/cptrConstCharArrays.chpl, test/interop/python/cptrConstCharArrays.future, test/interop/python/cptrConstCharArrays.good, test/interop/python/cptrConstCharArrays.prediff, test/interop/python/stringArrayArg.chpl, test/interop/python/stringArrayArg.future, test/interop/python/stringArrayArg.good, test/interop/python/stringArrayArg.prediff, test/interop/python/use_cptrConstCharArrays.py, test/interop/python/use_stringArrayArg.py
Covers:
- taking and returning arrays of `c_ptrConst(c_char)` in exported functions
- accepting arguments of arrays of strings in exported functions
- throwing from hash functions in script-like .chpl files
- throwing from hash functions in script-like .chpl files due to calling functions that throw
- calling functions with `ref` intent for the `this` argument from hash functions
- explicitly declaring the hash function to have `ref` intent for its `this` argument
- throwing from hash functions in explicit modules
Checked a fresh checkout of the hash tests behaved as expected.  The Python
interop tests worked locally
=> Add tests and futures motivated by HPO's use of these features

tools/chplcheck/src/rules.py
Adds an fixit for the chplcheck rule `EmptyStmts`. This allows users to automatically fix their code.
This also fixes an issue where the lint rule would warn in places where it was syntactically invalid to remove the `;`, for example `if a then ; else b;`
To be merged after #24744
=> Add linter fixit for EmptyStmts

runtime/src/comm/ugni/comm-ugni.c
This PR has two minor fixes for building the ugni layer with bundled LLVM.
1. On `flat` locale model, we get strict prototype errors because of a missing `void` in a function with 0 formals
2. On `gpu` locale model with `nvidia`, we use `-D__STRICT_ANSI__` while building the runtime. `comm-ugni.c` has some non-compliant code, so this PR undefines that if it is defined.
Resolves a bug reported by @ninivert  on [gitter](https://matrix.to/#/!PBYDSerrfYujeStENM:gitter.im/$-qXpYCwU3SWps1_izeV9aCr1PbqREN5A8EuQYwNvzQE?via=gitter.im&via=matrix.org&via=envs.net). 
Test:
=> Small fixes for UGNI builds with bundled LLVM

test/chplcheck/MisleadingIndentation.chpl, test/chplcheck/MisleadingIndentation.good, test/chplcheck/MisleadingIndentation.good-fixit, tools/chplcheck/src/rules.py
This PR adds a fixit to chplcheck for MisleadingIndent. This lets users auto-fix and improve their code.
Tested locally
=> Add auto-fixit for MisleadingIndent lint rule

tools/chpl-language-server/src/chpl-language-server.py
Extends the existing support for end marker inlay hints to include Select and When.
Tested locally
=> CLS: Support inlay end markers for Select and When

frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testResolve.cpp
I didn't realize we had a `NoneParam` value for params of type `nothing`. I looked for a `NothingParam`, but obviously didn't find any. In reading some unrelated code today, I noticed that we _do_ have params of `nothing`; this PR adjusts the builtin type and the corresponding test to ensure that paramness is available. 
=> dyno: Make 'none' support param-ness.

third-party/gasnet/gasnet-src/other/firehose/firehose_region.c
This PR patches the bundled gasnet to pull in a fix for gasnet using the ibv-conduit with clang16+.
Gasnet bug: https://gasnet-bugs.lbl.gov/bugzilla/show_bug.cgi?id=4617
Gasnet patch: https://bitbucket.org/berkeleylab/gasnet/pull-requests/625
Resolves https://github.com/chapel-lang/chapel/issues/24779
Resolves https://github.com/chapel-lang/chapel/issues/22055
Tested by building with `CHPL_COMM=gasnet` and `CHPL_COMM_SUBSTRATE=ibv` and confirming that the correct codepath for the conditional compilation is taken
I was also able to reproduce the issue on an InfiniBand system without the patch, and confirmed that applying the patch  results in correct execution.
```
> chpl examples/hello6-taskpar-dist.chpl 
> ./hello6-taskpar-dist.chpl  -nl 4
SEGFAULT
> ...apply patch....
> chpl …
```
=> Patch bundled gasnet to pull in bugfix for IBV

util/cron/load-base-deps.bash
Switch dependency loading on Atlas to use the new Spack install.
This is part of https://github.com/Cray/chapel-private/issues/6116, but I don't believe any jobs running on Atlas actually use this script so it doesn't need to get merged on its own to make progress. I just want to have it for completeness alongside the change on the internal code repo copy (https://github.hpe.com/hpe/hpc-chapel-code/pull/586).
Backing issue: https://github.com/Cray/chapel-private/issues/6116
=> Load deps from new Spack install on Atlas

doc/util/nitpick_ignore, frontend/include/chpl/resolution/scope-queries.h, frontend/lib/resolution/Resolver.cpp, tools/chapel-py/src/resolution.cpp
Fixes https://github.com/chapel-lang/chapel/issues/24905.
This PR beefs up the logic for scope resolving identifiers that occur in the use / rename list of a node. When the node-to-be-resolved is part of a visibility clause such as the 'x' in `use M only x` or the `b` in `import M.{a as b}` etc, the new logic performs a proper scope search of the module being accessed. Thus, when the user hovers over 'fillRandom', which is a visibility clause, the scope resolution process now finds a 'fillRandom' overload.
=> chapel-py: scope resolve uses and imports

runtime/src/launch/slurm-srun/launch-slurm-srun.c
`--gpus-per-node` or the like are required to be able to use GPU nodes on some systems. I noticed this requirement on Perlmutter. However, we don't have the ability to pass that flag through the launcher executable we generate. This PR adds `CHPL_LAUNCHER_GPUS_PER_NODE` environment flag to add that ability.
=> Add a new environment variable to pass `--gpus-per-node` to slurm

modules/standard/Random.chpl, test/library/standard/Random/fillRandom.chpl
For filling random values for `real` arrays within a specified `min` and `max` where these values are `int`s, the overload which results in a compiler error was being selected.
For example:
```chapel
use Random;
var a : [0..<10] real;
fillRandom(a, min=-1, max=1);
```
would give us the following error:
```console
random.chpl:4: error: 'fillRandom' does not support non-rectangular arrays
```
This is because we expect the types of the `min` and `max` arguments to match the `eltType` of the array. However, the headers of the overload which results in the `compilerError` does not have the types enforced. This means that before trying to coerce the types (which should be done in this case), the compiler simply chooses the overload and results in an unhelpful error.
Based on the discussion in …
=> Fix `fillRandom`'s wrong overload being selected

.github/workflows/python-format-CI.yml
Only on chapel-py and its derivative projects.
This CI check only runs on PRs that touch files in `chapel-py`, `chplcheck`, or `chpl-language-server`.
Reviewed by @tzinsky -- thanks!
=> Add a 'black' check to verify formatting of Python files

tools/chapel-py/examples/replace.py, tools/chapel-py/setup.py, tools/chapel-py/src/chapel/__init__.py, tools/chapel-py/src/chapel/lsp/__init__.py, tools/chapel-py/src/chapel/replace/__init__.py, tools/chapel-py/src/chapel/visitor/__init__.py, tools/chpl-language-server/src/bisect_compat.py, tools/chpl-language-server/src/chpl-language-server.py, tools/chpl-language-server/src/chpl-shim.py, tools/chpl-language-server/src/symbol_signature.py, tools/chplcheck/src/chplcheck.py, tools/chplcheck/src/fixits.py, tools/chplcheck/src/lsp.py, tools/chplcheck/src/rule_types.py, tools/chplcheck/src/rules.py
We've done this before on files such as `chpl-language-server.py` or `chplcheck.py` or `rules.py`. This PR just does that again, but also applies it to other, less-often formatted files.
=> chapel-py: Apply black to chapel-py and its derivative files.

tools/chpl-language-server/src/symbol_signature.py
Extends symbol signature to be able to print out FnCalls. This is important for function signatures like `proc foo(a: int(?w), b: real(32))`
Tested locally
=> Extend symbol signature to work FnCall

CMakeLists.txt, doc/rst/conf.py, doc/rst/usingchapel/QUICKSTART.rst, doc/rst/usingchapel/chplenv.rst, man/confchpl.rst, man/confchpldoc.rst, test/compflags/bradc/printstuff/version.goodstart
This bumps the version number to 2.0.1 and is intended for the 2.0 branch only.
=> Bump version number to 2.0.1

tools/chplcheck/src/rules.py
Fixes an issue with the `IncorrectIndentation` lint rule where a module level attribute was treated as a child of the module
For example:
```chapel
@myAttribute() // Warning: IncorrectIndentation
module foo {
...
}
```
This is fixed by skipping the AttributeGroup, if it exists
Tested locally
=> Fix chplcheck bug with IncorrectIndentation and attributes

tools/chpl-language-server/src/chpl-language-server.py
Exclude operators from completion suggestions in CLS, as these show up first in some editors alphabetically and are not really that useful to users
Tested locally
=> Exclude operators from completion suggestions in CLS

modules/packages/BLAS.chpl, test/library/packages/BLAS/COMPOPTS, test/library/packages/BLAS/test_blas1.chpl, test/library/packages/BLAS/test_blas2.chpl
Several of the alpha/beta arguments in our BLAS routines have historically been declared `ref` because the Fortran implementations of the routines (and their C headers) pass the scalar values in question using a pointer when using complex values.  However, these should have been `const ref` arguments in order to permit `const` and `param` expressions to be passed in for these arguments, which are logically "in" arguments and read-only.
Here, I'm taking that change one step further and just making the user-facing Chapel routines take these scalar arguments by default intent, then applying a `c_ptrToConst()` within the body of the routine to pass the value along to the underlying C routines by pointer-to-const as they want.  This has the benefits of supporting a simpler interface / avoiding …
=> Change read-only scalar arguments from 'ref' to default intent in BLAS routines

doc/rst/language/spec/task-parallelism-and-synchronization.rst
Remove a whitespace to fix rst rendering in `task-parallelism-and-synchronization` language spec.
The old behavior causes the last item in the list to be bold, along with a line-break:
=> Fix rst rendering in `task-parallelism-and-synchronization`

tools/chapel-py/src/method-tables/uast-methods.h, tools/chpl-language-server/src/chpl-language-server.py
As of #24776, CLS does a proper traversal of included symbols -- including `ChapelStandard` -- to find autocompletion suggestions. However, this means it picks up internal symbols from `ChapelStandard`, ones that weren't meant for the users' eyes. To solve (part of) this problem, this PR configures CLS to skip symbols that have `@chpldoc.nodoc` on them: if they aren't meant for public-facing documentation, they likely aren't meant for the user. 
This exception does not apply when editing standard module files, since the implication there is that the user is a developer.
Reviewed by @jabraham17. Tested locally.
=> LSP: skip undocumented names when providing autocompletion

runtime/src/chpl-gpu.c
Previously seen in https://github.com/chapel-lang/chapel/pull/23936 and https://github.com/chapel-lang/chapel/pull/24360. 
=> Fix `printf` format specifier in `chpl-gpu.c`

frontend/lib/uast/post-parse-checks.cpp, frontend/test/parsing/testParseChecks.cpp, test/arrays/methods/specialMethodKeywords.chpl, test/arrays/methods/specialMethodKeywords.good, test/classes/deinitializers/deinitExplicitCall.good, test/types/records/init/init-post-postinit.bad
I somehow missed these in a paratest.
=> Fix tests broken by PR that disallowed `x.init()`

compiler/passes/convert-uast.cpp, frontend/lib/resolution/InitResolver.cpp, frontend/lib/resolution/Resolver.cpp, frontend/test/resolution/testCallInitDeinit.cpp, frontend/test/resolution/testInitSemantics.cpp
This PR updates the ``init=`` implementation to correctly instantiate the declaration when a record is initialized from a type other than that record. For example, something like ``var x : MyWrapperType(?) = 42;``.
There are two parts to this PR:
1) Updating InitResolver to call ``updateResolverVisibleReceiverType`` for each field. This will account for any potential substitutions needed to fully instantiate the type, including fields like ``var x : T;``.
2) In ``Resolver::getTypeForDecl``, using the computed instantiated type from the ``init=`` to set the type of the declaration.
A couple of tests are added to lock in this behavior.
Testing:
=> Dyno: Fix init= for generic types initialized from different types

frontend/lib/parsing/parsing-queries.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testClasses.cpp
Updates the resolution of symbols in the body of a method to properly resolve the type of fields that are part of a multi-decl. 
The following reproducer would not resolve properly with `--dyno`:
```
class C {
var a, b : int;
}
proc C.getA() {
return a;
}
var foo = new C(40, 2);
var x = foo.getA();
```
because the type of `a`, although previously identified to be `int`, would be `unknown` when evaluating the return type of `getA()` and make `x` erroneous. 
This was happening because in this specific case we were not normalizing the symbol for the possibility it was an element of a multi-decl or tupledecl or other type of decl that is more like a container for other decls. We were attempting to resolve the type of `a` without the information about its multi-decl parent. 
TESTING:
[reviewed …
=> fix dyno resolution of multi-decls as fields 

man/chpl.rst
Updates the wording in the description of `chpl` to remove references to `C99`, removes some details about source files and intermediate steps of compilation.
=> small edits to the `chpl` manpage

util/buildRelease/gen_release, util/cron/test-homebrew.bash, util/devel/test/vagrant/provision-scripts/chapel-update.sh, util/devel/test/vagrant/provision-scripts/git-clone-chapel.sh
Use `--reference-if-able` for all manual `git clone`s in our scripts under `util/`.
The path of the reference repo is assumed to be provided as an environment variable, either on the command line if used manually or from Jenkins as set in CI config for nightly runs. If the variable is missing we will use the path `/missing/{repo-name}` and get a warning that no such path exists.
To be merged with https://github.hpe.com/hpe/hpc-chapel-ci-config/pull/1155 which sets up the environment variables from the Jenkins side.
=> Use `--reference-if-able` for `git clone`s in scripts

doc/rst/platforms/macosx.rst
This PR updates the Mac OS X platform README with details about how to install the required prerequisite tools without using Homebrew. This is based on my experience working with a user that didn't want to install Homebrew.
=> Update Mac OS X instructions with non-homebrew option

frontend/lib/types/Param.cpp, make/compiler/Makefile.gnu, util/cron/test-linux64-gcc101.bash, util/cron/test-linux64-gcc112.bash, util/cron/test-linux64-gcc73.bash, util/cron/test-linux64-gcc91.bash
This PR applies a few fixes that resolve build issues with the compiler when built with newer llvm
- Opt out of -Wnonnull due to false positives in LLVM headers
- Patch `Param.cpp` to work around gcc 9 bug (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80635)
- Adjust test configs for older gcc versions to avoid linker/abi incompatibility issues
=> Additional fixes for build warnings with LLVM 17

test/gpu/native/studies/chop/main.gpu-keys, test/gpu/native/studies/chop/main.prediff, test/gpu/native/studies/chop/patches/time.patch
Technically the output for the time measurement has changed in ChOp. But adapting to it would require changing our dat files for performance tracking, which is never fun. Instead this PR modifies the source to print out `Elapsed time:` as it used to. Also reverts some of the recent changes to go back to using `Elapsed time` as the key.
=> Revert ChOp back to using old perfkeys

runtime/src/qio/qio.c
Follow-up to PR #24849.
This PR fixes test failures for `regex/empty-channel-matches` and `regex/ferguson/rechan` in linux32 testing after that PR.
The switch to using `qio_channel_advance` instead of `qio_channel_advance_past_byte` to advance to the end of a fileReader in certain regular expression searching scenarios revealed a bug in `qio_channel_advance_unlocked`. It used `qio_space_in_ptr_diff`, which accepts an `intptr_t`, but it passed in an `int64_t`. On 64-bit systems, this is not an issue, because `intptr_t` and `int64_t` are both 64-bit. But, on a 32-bit system, `intptr_t` is 32 bits, and the resulting implicit conversion led to overflow, causing the comparison to have an unexpected result.
Reviewed by @mstrout - thanks!
=> Fix regex test failures on linux32 after advanceThrough fixes

test/regex/flags/SKIPIF
Follow-up to PR #24935 to add a SKIPIF to skip the new tests in quickstart testing where they can't run.
=> Skip new regex tests when no regex support

runtime/src/comm/ofi/comm-ofi-launch.c
This PR explicitly sets `SLURM_MPI_TYPE` when using `CHPL_COMM_OFI_OOB=pmi[x|2]`. This reduces the number of environment variables required to be set on some platforms, notably AWS, making it easier for users to use chapel.
Tested on AWS that explicitly setting `SLURM_MPI_TYPE` was no longer required.
This PR is based on https://github.com/chapel-lang/chapel/issues/18975. Some discussion there suggested determining when it is actually required to set `SLURM_MPI_TYPE`. This PR takes the simpler approach of always setting it, but only when using pmi.
=> Explicitly set SLURM_MPI_TYPE when using OFI_OOB=pmi

make/compiler/Makefile.gnu
Set `-Wno-error=uninitialized` for GCC >= 12 (rather than just == 12) after observing the suppressed error with GCC 13 as well.
This is to work around a true instance of the errors in LLVM <= 14 headers.
Testing:
=> Make uninitialized memory errors non-fatal for GCC 13

compiler/codegen/cg-CForLoop.cpp, compiler/codegen/cg-DoWhileStmt.cpp, compiler/codegen/cg-WhileDoStmt.cpp, compiler/codegen/cg-expr.cpp, compiler/codegen/cg-stmt.cpp, compiler/codegen/cg-symbol.cpp, compiler/codegen/codegen.cpp, compiler/include/llvmTracker.h, compiler/include/llvmUtil.h, compiler/llvm/clangUtil.cpp, compiler/llvm/llvmAggregateGlobalOps.cpp, compiler/llvm/llvmExtractIR.cpp, compiler/llvm/llvmGlobalToWide.cpp, compiler/llvm/llvmUtil.cpp
This PR introduces an opt-in support for breakpoints on creation of LLVM Value objects during codegen, as identified with what I will call "LLVM IDs". This is analogous to `breakOnID` for BaseAST objects. The implementation is different, however, in order to allow it to work with unmodified LLVMs, ex. when CHPL_LLVM==system.
To enable tracking LLVM IDs, set `TRACK_LLVM_VALUES` to 1 in `llvmTracker.h` or using `-D`, and rebuild the compiler.
This PR also adds overloads of the compiler's traditional helpers `list_view` and `nprint_view` for LLVM's Value, Type, and Module objects. This allows compiler developers to use their existing debugger aliases to examine these LLVM items. When tracking is enabled, `nprint_view` dislays the LLVM IDs when available.
The workflow may look like this:
``` …
```
=> Track llvm::Value objects during codegen

runtime/src/comm/ofi/comm-ofi.c
This PR fixes the way that co-locales determine their fixed heap size when using COMM=ofi. Previously, co-locales would divy up 85% of the memory. Now, co-locales divy up the memory based upon the max heap size set in `CHPL_RT_MAX_HEAP_SIZE`. In other words, `CHPL_RT_MAX_HEAP_SIZE` represents the maximum heap per node, and the co-locales just divide it evenly. If `CHPL_RT_MAX_HEAP_SIZE` is not set, then the previous default of 85% is used.
Tested using COMM=ofi with no co-locales, 2 co-locales, and 4 co-locales, with/without `CHPL_RT_MAX_HEAP_SIZE` set
=> Make co-locales respect CHPL_RT_MAX_HEAP_SIZE

runtime/src/comm/ofi/comm-ofi.c
Reverts chapel-lang/chapel#24232. This PR fixed some issues with hangs in the chapel runtime with the OFI EFA provider, however since this does not truly release all the resources subsequent runs may no longer work.
=> Revert indefinite hang workaround for ofi+efa

tools/chpl-language-server/src/chpl-language-server.py
Fixes an issue where errors from other files were shown in the file that had window focus.
tested locally
=> Only show LSP errors that pertain to the current file

modules/standard/Types.chpl
- Hide the where clauses for `numBits()`, `min()` and `max()`
The documentation speaks generally, but the where clauses are for one of the
specific cases (because we have several overloads and only wanted to document
it generally).  Hide the where clause so that the documentation is not confusing
- Remove some out-of-date mention of "fixed-width bool types"
We removed support for fixed-width bool types a while ago, but it looks like we
missed updating this documentation to not mention them.  Since the default width
bool (which is all that remains) is not supported, just remove mentions of bools
from these entirely.  Note that I left the overload for numBits, because it seemed
like a reasonable enough error message.
Double checked the built documentation.  Running a paratest (even though I …
=> Minor documentation cleanup for the Types module

third-party/libfabric/Makefile
This PR adds a few warning opt outs when building the bundled libfabric with specific versions of clang.
Testing
=> Allow bundled libfabric to be built with newer clang

test/studies/lcals/LCALSMain.skipif, test/studies/lcals/LCALSMain.suppressif
A recent upgrade on a test system to LLVM 17 has caused LCALS to timeout when compiled with `--no-local`. This PR adds a suppressif for this case to reduce nighty test noise while I investigate the issue
=>   Suppress LCALS nightly test timeouts

util/cron/test-gpu-ex-cuda-11.bash, util/cron/test-gpu-ex-cuda-12.bash, util/cron/test-gpu-ex-cuda-12.ofi.bash, util/cron/test-perf.gpu-ex-cuda-12.bash
Updates `cudatoolkit` module versions after the system on which we run these tests got upgraded.
- For versions where we pin 11, we still use the explicit version.
- For versions where we use 12, we just rely on it being the default CUDA version.
This PR changes 4 configs, I tested one by manually launching the job.
=> Update CUDA versions for the EX testing system upgrade

test/library/standard/Math/trigImagFunctions.suppressif
Adds suppressif to a test checking that the `complex` and `imag` versions of a function return the same value. The comparison in the test does not seem to work on cygwin.
=> Add suppressif for complex/imag test on cygwin

frontend/lib/resolution/scope-queries.cpp
This PR removes code that was added temporarily in #22059 to support deprecation of the enum BoundedRangeType. The latter has been removed in #24136, so this this code is no longer needed.
Suggested by @mppf .
=> Remove no longer needed deprecation support

doc/rst/platforms/aws.rst, runtime/src/comm/ofi/comm-ofi-internal.h, runtime/src/comm/ofi/comm-ofi.c
This PR adds a new runtime variable, `CHPL_RT_COMM_OFI_THP_HINT`, which controls if the OFI comm layer will use transparent huge pages to allocate memory. The default value is false, except when the provider being used is EFA. The default is true for EFA, since EFA is severely limited in the number of pages it can register.
This PR also updates the docs for using Chapel on AWS to explain how to enable and use transparent huge pages.
This PR requires https://github.com/chapel-lang/chapel/pull/24969 to be merged first
Tested on AWS
=> Allow Chapel programs with COMM=ofi to use explicit transparent huge pages

runtime/src/comm/ofi/comm-ofi.c
This changes the default for the `CHPL_RT_COMM_OFI_INJECT_*` environment variables. This works around a bug in our runtime using OFI with non-blocking operations.
https://github.com/chapel-lang/chapel/issues/24972 is a symptom of this, and this PR restores correctness for this issue. I do not consider the issue resolved as this is more of a workaround.
Environment variables changed
- CHPL_RT_COMM_OFI_INJECT_AM
- CHPL_RT_COMM_OFI_INJECT_AMO
- CHPL_RT_COMM_OFI_INJECT_RMA
Tested using COMM=ofi and the EFA provider using `test/users/bachman/Beta_Diversity/main.chpl` (from #24972) and `test/release/examples/benchmarks/hpcc/ra-atomics.chpl` (which has the same problem), and validated that these tests do not hang with this patch
[Reviewed  by @jhh67]
=> Change the default for COMM_OFI_INJECT_* to false to workaround runtime bug

util/cron/test-linux64-gcc74.bash
Switches a test config to gcc 7.4, as we no longer support gcc 7.3
=> Switch test config to gcc 7.4.0

doc/rst/platforms/libfabric.rst
Adds more documentation to `doc/rst/platforms/libfabric.rst` about `CHPL_RT_MAX_HEAP_SIZE` and `CHPL_RT_COMM_OFI_THP_HINT`
This is a follow-on to https://github.com/chapel-lang/chapel/pull/24971/ and https://github.com/chapel-lang/chapel/pull/24967
Built and checked docs locally
=> Add more documentation on OFI heap environment variables

util/cron/nightly, util/cron/test-perf.chapcs.arkouda.release.bash
This PR adds a `-no-warnings` flag to `util/cron/nightly`, allowing nightly test configs to flip the default for building Chapel (similar to `-asserts`). This PR then uses that flag in `util/cron/test-perf.chapcs.arkouda.release.bash`
=> Add `-no-warnings` flag to `nightly` test script

runtime/src/gpu/nvidia/Makefile.share
This fixes an issue that came up in our nightly testing with cuda 11, where new warnings in cub headers caused builds to fail.
Tested that chapel built on test system with cuda 11
=> Turn off warning for cuda 11

man/confchpl.rst, man/confchpldoc.rst
Rationale: man pages shouldn't need to be updated in major ways with updates to minor releases, and having them reflect those numbers suggests they do while also introducing overhead when such releases need to be made.
=> Dial the version numbers on the man pages down to just major.minor

.github/ISSUE_TEMPLATE/00-bug.md, .github/ISSUE_TEMPLATE/03-documentation.md
Michelle discovered that when a user installs using homebrew, `$CHPL_HOME/util/printchplenv --anonymize` doesn't work because `$CHPL_HOME` is not set.  List the alternative option Jade mentioned, though it does not anonymize the output (being explicit that that is the case so it doesn't surprise users).
Only the bug report and documentation report templates needed to be updated, the others do not include the command in question
I think this works based on looking at how the file displays in Github, but would need to make a test repository to fully check - if my reviewer is okay with it, I would like to check how it displays by merging and following up with tweaks as needed.
=> Improve the templates when the user doesn't have CHPL_HOME set

doc/rst/technotes/gpu.rst
The current link leads to "404 - Page Not Found". I updated it.
=> Fix broken link for AMD GPUs specs

modules/internal/ChapelBase.chpl, runtime/include/chplmath.h
Fixes an issue in nightly where definitions for creal and cimag could not be found when the runtime is built with a C++ compiler (for gpus). This was technically an existing problem that was hidden by rewriting these functions to use builtins, but that was removed for newer LLVM versions in https://github.com/chapel-lang/chapel/pull/25019.
Tested that GPU tests work on system with GPUs and LLVM 17
=> Fix creal and cimag support for gpus

util/packaging/homebrew/chapel-main.rb, util/packaging/homebrew/chapel-release.rb, util/packaging/homebrew/readme.md
This PR updates `chapel-main.rb` to match the currently released formula for 2.0 and updates `chapel-release.rb` to contain the previous 1.33 released formula.
I skipped this step during the release process, it should have happened earlier. It probably needs to be called out as a separate step because it's not really part of the homebrew PR itself. 
[reviewed by @tzinsky - thanks!]
=> update homebrew formulas after 2.0.1 release

frontend/include/chpl/resolution/can-pass.h, frontend/lib/resolution/can-pass.cpp, frontend/lib/resolution/prims.cpp, frontend/test/resolution/testTuples.cpp
Implement `get svec member` and `get svec member value` primitives in Dyno and add some testing.
Along the way, split `KindProperties::combineWith` into `combineWithJoin` and `combineWithMeet` variations. These take the mathematical join and meet with respect to constness, considering `const > non-const`. `combineWithJoin` is equivalent to the previous version, whereas the new `combineWithMeet` is a "less strict" version used to remove ref-ness in the `get svec member value` primitive. Thanks @DanilaFe for the out-of-band suggestions on this.
Part of https://github.com/Cray/chapel-private/issues/5512 and https://github.com/Cray/chapel-private/issues/6104.
Testing:
=> Implement `PRIM_GET_SVEC_MEMBER*` in Dyno

util/cron/test-linux64-llvm18.bash
Adds a new nightly test config for LLVM 18 testing
=> Add LLVM 18 nightly testing

doc/rst/meta/static/searchtools.js
Follow-up to PR #24785.
This PR keeps the yellow highlighting to the search page itself instead of allowing it to appear when you open a link from the search results.
Reviewed by @ShreyasKhandekar - thanks!
=> Don't highlight on pages opened from search results

compiler/llvm/clangUtil.cpp
Removes a usage of `-Wno-nan-infinity-disabled`, which is only enabled in Clang/LLVM 18+
=> Fix usage of `-Wno-nan-infinity-disabled`

util/build_configs/cray-internal/setenv-hpe-cray-ex-x86_64.bash
When building the EX modules, the build environment utilizes a set of configuration files and scripts that define the dependencies needed for the build.  This script was overriding those settings and pinning the gcc to 10.3.0 causing build errors.   This PR will remove the hard coded pin and resolves this error: 
libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by cmake)
The script in this PR will need additional updates that are considered out of scope for this error.   That is considered to be a TODO at this time.
=> Update the EX build to not pin the GCC compiler.

util/chplenv/chpl_compiler.py
This fixes a typo in our scripts that Paul Hargrove pointed out, which also serves as an indication that we haven't done much w.r.t. testing against PGI in recent years.
=> Fix typo: 'pgicc' -> 'pgcc'

tools/chapel-py/src/core-types-gen.cpp
Add a default case return to fix a build error in Chapel-Py.
@jabraham17 
Solves #25054
=> Add default case to switch to fix build error

test/c2chapel/testFunctions.c, test/c2chapel/testFunctions.h, tools/c2chapel/c2chapel.py
Fixes a bug in `c2chapel` where signatures with `FILE` or `FILE*` types were incorrectly generated as `_FILE` in the corresponding Chapel source files. Also adds some tests for `c2chapel` that make use of signatures with `FILE` and `FILE*` types to catch changes in the behavior.
TESTING:
=> map c2chapel FILE to c_FILE and add tests that use FILE type ptrs

test/execflags/lldbddash/SKIPIF, test/execflags/lldbddash/declint.suppressif
We currently don't support `--lldb` on compiled executables for any `CHPL_COMM` except none. For others the runtime continues on ignoring the flag.
The test for this was previously skipped due to not having LLDB available in the `PATH` where it ran, but recent dependency management changes have made it available, causing nightly test failures. To resolve, suppress resulting test failures under `COMM != none`. Suppression is chosen over skipping as if we add support for `--lldb` under different comm configurations we'd want to remember to enable test coverage for it.
Testing:
=> Suppress `--lldb` execflag test fails for `COMM != none`

frontend/lib/resolution/maybe-const.cpp, frontend/test/resolution/testConstChecking.cpp
This PR fixes a bug in which AdjustMaybeRefs was incorrectly computing the alignment while trying to check for constness errors in argument passing. The alignment was wrong because the code was not accounting for an implicit receiver, and failed to add a suitable 'this' actual to the ``CallInfo``. Fortunately the receiver's type information is readily available through ``Resolver::methodReceiverType()``.
A short test is added to lock in the correct behavior.
Testing:
=> Dyno: Correctly handle implicit receivers in AdjustMaybeRefs

util/cron/test-homebrew.bash, util/packaging/homebrew/chapel-main.rb
Makes small updates to homebrew formula that we keep up to date so that it can build the latest main. Fixes a problem in homebrew builds where we were having to reset the cmake cache between calls to make, or we'd see an error during the build about how the cmake variables for `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` were being reset. In this and other packages, we just want to use the CC and CXX values that the packager is providing, so by setting `CHPL_CMAKE_USE_CC_CXX` we avoid problems.
Previously, the `brew install` was failing and moving the new builds of the `chapel-language-server` and `chplcheck` in with `chpldoc` fixes it. While here, remove code that was temporarily introduced to work around bugs with python 3.12 and also code to add a `clean-cmakecache` target on the fly, …
=> update homebrew formula for main

test/classes/forwarding/forwardToNonVar.bad, test/classes/forwarding/forwardToNonVar.chpl, test/classes/forwarding/forwardToNonVar.future
=> Add future for bug when applying `forwarding` to badly formatted variable declaration

util/config/compileline.py
Removes `#!usr/bin/env python` from `compileline.py`, as this causes issues when building RPMs.
Now that we no longer support python2, it can just always be `#!usr/bin/env python3`
[Reviewed by @mppf and @riftEmber]
=> Always use `python3` in bash env shebang

util/cron/load-base-deps.bash
We don't want to load deps from Spack on Horizon as that's where we do module builds.
I thought that https://github.hpe.com/hpe/hpc-chapel-ci-config/commit/9db0ae56a63de443f6c58658e7817808d6564e25 made it so no Horizon tests used Spack deps anymore, but some apparently do, such as https://chapel-ci.us.cray.com/job/cray-xc-correctness-test-cray-xc-arkouda.release/200/consoleFull. This PR removes the code responsible.
=> Remove spack dep loading on horizon

tools/protoc-gen-chpl/Makefile
Recent versions of protobuf [depend on abseil-cpp](https://protobuf.dev/news/2022-08-03/#abseil-dep), and abseil requires at least C++14. However, we specify the use of C++11 in the compile flags for our `protoc-gen-chpl` target. Update it to C++17 since that's what Chapel in general requires.
[`d1a649a` (#16817)](https://github.com/chapel-lang/chapel/pull/16817/commits/d1a649afd0308f55dba09bf71841a176ec62a63b) asserts the `-std` argument is required for building on Mac, which holds up on my Mac with Clang 15; however, it works with `-std=c++17` instead of 11.
Testing:
- not on the latest protobuf however, due to https://github.com/Cray/chapel-private/issues/6313, but that's a separate issue
=> Update C++ standard specified for protobuf build

runtime/src/launch/slurm-srun/launch-slurm-srun.c
The `strsep` function modifies the buffer it is given, so make a copy of the buffer before calling `strsep` so that we can include the output in an error message if the buffer cannot be parsed.
=> Produce the correct output when the sinfo command fails

test/library/draft/DataFrames/diten/readHDF5Df.suppressif
Suppress this newly-running failing test pending further discussion, to end a few days of noise in multiple configs.
See https://github.com/Cray/chapel-private/issues/6322 for explanation and discussion.
=> Suppress readHDF5Df.chpl test always

doc/rst/tools/mason/guide/buildinglargerpackages.rst, tools/mason/MasonPublish.chpl
Fix the bug in Mason's main-module check, outlined in [this issue](https://github.com/chapel-lang/chapel/issues/25064), that prevents packages that use sub-modules from being accepted in the mason registry.
=> Fix mason CI check that was failing for packages with sub-modules

doc/rst/language/spec/classes.rst, doc/rst/language/spec/data-parallelism.rst, doc/rst/language/spec/iterators.rst, doc/rst/language/spec/ranges.rst, doc/rst/language/spec/records.rst, doc/rst/language/spec/statements.rst, doc/rst/language/spec/task-parallelism-and-synchronization.rst, doc/rst/technotes/local.rst, doc/util/literate_chapel.py, test/release/examples/primers/forallLoops.chpl, test/release/examples/primers/taskParallel.chpl
This PR improves the documentation search results for specific searches:
* new
* with
* by
* zip
* local
In order to do so, it adds `.. index::` entries to the forallLoops.chpl and taskParallel.chpl primers. I added index entries for other sections present there, while there. To get these `.. index::` entries to work, I needed to update `literate_chapel.py` because it was de-indenting the lines following `.. index::` which lead to invalid RST.
This PR also has a minor impact on the Chapel blog rendering (since the blog uses `chpl2rst.py` which this PR modifies to support `.. index::`). Now whitespace is more accurately respected within the .rst comments.
=> Improve search behavior for specific keywords

util/cron/test-valgrind.bash, util/cron/test-valgrindexe.bash
Remove workaround setting use of LLVM 13 in Valgrind nightly test configs, as it is no longer needed and causing [other problems](https://chapel.discourse.group/t/test-chapcs-correctness-test-valgrindexe/33620/3).
Resolves https://github.com/Cray/chapel-private/issues/3373.
[merging without review for expediency as the test is broken now anyways)
=> Switch to using default LLVM version in valgrind tests

test/execflags/lldbddash/declint.prediff
The test `test/execflags/lldbddash/declint.chpl` has been failing in `memleaks` configuration since LLDB became available to it and the test was no longer `skipif`'d. This is because LLDB prints out a line about arguments to the executable being set (`--memLeaks` and `--memLeaksLog`) which doesn't apply otherwise. Prediff out these lines so the test can pass.
Testing:
=> Prediff out LLDB test line for `--memLeaks` being set

tools/mason/MasonPublish.chpl
Follow-up of https://github.com/chapel-lang/chapel/pull/25084, make sure that `moduleCheck` only considers `.chpl` files, otherwise the following case
```
myPkg/
src/
myPkg.chpl
notes.txt
```
would lead the check to fail
=> make moduleCheck more robust

test/mason/gitErrors.good, test/mason/gitErrors.prediff, test/mason/masonInit/masonInitTest3.good, test/mason/masonInit/masonInitTest3.prediff, tools/mason/MasonPublish.chpl, tools/mason/MasonUtils.chpl
This PR expands on the work in https://github.com/chapel-lang/chapel/pull/25069 to improve mason errors when dependencies (specifically git) are missing. This PR adds additional logic to account for portability issues exposed by nightly testing
Testing
- Tested the two tests added in #25069 pass on a Mac
- Tested `start_test test/mason` passes on linux x86
- Tested `start_test test/mason` passes on the nightly test machine (a slightly different linux x86)
=> Make mason missing command errors more portable

util/cron/create_release_aptrpm.bash
Adds a script that will serve as the driver for a nightly test job to build Chapel apt and rpm packages.
=> Add test script for nightly runs of Chapel packages

doc/rst/technotes/extern.rst
[based on feedback and suggestions by @psath]
Based on feedback in #24963, this PR strives to improve the documentation of the ``require`` statement to clarify that it doesn't accept general `chpl` command-line flags and refactors the description of the -I and -L flags to try and clarify their role in common to listing files on the command-line or `require` statements.  While here, I also did some wordsmithing and formatting adjustments.
Resolves #24963.
=> Touch up text around require statements w.r.t. -I / -L flags

.github/ISSUE_TEMPLATE/00-bug.md, .github/ISSUE_TEMPLATE/01-feature_request.md, .github/ISSUE_TEMPLATE/02-performance.md
We had a user recently seem confused whether calling the issue "blocking" was talking about the state of the project or their personal experience.  In response, it seemed like a good idea to adjust the request a bit.
Based on the structure of the feature request template, make the other two templates talk about potential work-arounds in the "Description" section, and make the request say "if any", so the user doesn't feel like they have to have looked into work-arounds themselves.
Transform the question about if it is blocking to not mention work-arounds and be more explicit about who is being blocked ("you", the person filing the request, though I would expect Chapel developers filing such issues to use their "user hat" and answer based on if they can accomplish what they are trying to …
=> Clarify the issue templates w.r.t. workarounds and if the issue is blocking

frontend/include/chpl/uast/TupleDecl.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/uast/post-parse-checks.cpp, frontend/test/resolution/testTuples.cpp, test/types/tuple/bharshbarg/intentTupleGroup.good
This PR makes several improvements to the resolution of tuple-grouped formals in the frontend. After this PR, the following cases are now functional:
- tuple-grouped formal with a star-tuple type expression
- generic tuple-grouped formals (flat and nested)
This PR also adds an error for tuple-grouped formals with a non-default formal intent. This matches the production compiler's behavior.
Technical details:
- ``resolveTupleUnpackDecl`` is improved to better handle unknown or erroneous types
- ``TupleDecl::isTupleDeclFormal()`` has been added to aid in distinguishing such formals from variable declarations
- To allow generics, substitutions and star-tuples of ``AnyType`` were required
Testing:
=> Dyno: Improvements to tuple-grouped formals

util/cron/nightly
Fixes a problem when the nightly `test-linux64-blog-only` is ran when setup for paratest. Also adds better error output to differentiate between `blogdir` not found and `blogdir` not set.
Previously the `blogonly` testing did not play well with paratest because it placed the `testdirs` after the paratest args instead of in the `DIRFILE`. This changes that by checking for a paratest file and then writing our test directories to it in `blogonly` mode, similar to how `examples` tests do. In normal `blog` mode, the test dirs should be included by way of being located within the `test` directory.
While here, noticed that the `hello` flag is an outlier in this script, and was not being used by any of our testing. After some discussion with @DanilaFe and the dev-ops subteam, we decided to remove …
=> fix nightly script for parallel blog tests, remove hello flag

test/ANNOTATIONS.yaml
Annotations for perf triage week of 5/23/24:
- we've seen some pretty big changes to our dataframe indexing tests as a result of this PR: Bears-R-Us/arkouda#3109
=> annotations for 5/23/24

util/packaging/apt/test/.gitignore, util/packaging/apt/test/Dockerfile.template, util/packaging/common/README.md, util/packaging/common/test_package.py, util/packaging/rpm/test/.gitignore, util/packaging/rpm/test/Dockerfile.template, util/packaging/rpm/test/test_package.py
Adds a few scripts and Docker templates to test chapel packages built for various OSes in apt/rpm formats
Followup to https://github.com/chapel-lang/chapel/pull/25051
=> Add scripts to test Chapel apt/rpm packages

tools/chapel-py/setup.py
Fixes an issue where users would get a misconfiguration warning erroneously.
With CHPL_LLVM=none, users would receive the following warning. This was a configuration issue with how chapel-py was being built.
```
Misconfiguration of the C++ Chapel compiler library
headers in use with HAVE_LLVM defined
.cpp files compiled without HAVE_LLVM defined
```
=> Fix incorrect warning with chapel-py tools and CHPL_LLVM=none

test/functions/generic/type-func-return-generic.skipif
Skip a future for all x86 architectures (64 bit and 32 bit). This future passes on x86, but continues to fail on ARM
=> Skip future for ARCH=x86

compiler/optimizations/noAliasSets.cpp, modules/standard/GPU.chpl, runtime/include/gpu/chpl-gpu-reduce-util.h, runtime/include/gpu/nvidia/chpl-gpu-dev-reduce.h, test/gpu/native/reduction/basic.chpl, test/gpu/native/reduction/basic.good
Arkouda+GPU compilation testing suffered as fallout from https://github.com/chapel-lang/chapel/pull/24787. The issues were twofold:
- Compiler segfault: In Arkouda, some order-independent loops are subject to what we call "late gpuization failure". In such cases, we generate a kernel, but then remove it from the AST. Removing a function from AST doesn't remove it from `gFnSymbols`. Scrubbing `gFnSymbols` et al. happens in between passes and removes such functions. However, `gpuTransforms` are technically part of LICM. After `gpuTransfroms` there are some LICM operations (that also seem unrelated to LICM, unfortunately) that iterate over `gFnSymbols`. One such operation would get the removed function from the AST that would cause segfaults down the road. As a solution, this PR uses …
=> Fixes for Arkouda following GPU-based reduction

test/mason/mason-help-tests/masonHelpTests.good
Fixes a mason test `.good` file to match the output from `--help` since the documentation was updated in https://github.com/chapel-lang/chapel/pull/25099
TESTING:
[trivial change to test `.good` file only, not reviewed]
=> update mason test .good file to match help output after removing 'new'

test/mason/gitErrors.skipif
Skip this test for valgrind testing only, as valgrind interacts strangely with subprocesses that capture stdout/stderr (https://github.com/chapel-lang/chapel/issues/25130).
=> Add skipif for valgrind for gitErrors test

runtime/include/gpu/amd/chpl-gpu-dev-reduce.h
This is a small patch symmetric to the one I added here: https://github.com/chapel-lang/chapel/pull/25108/files#diff-fd9cac0eea147dc210859903e7107766edc1abaeb335360064f415f1ba1f0571. I missed the AMD side as our typical manual test system doesn't have the correct ROCm version and the reduction tests are skipped.
Test:
=> Add the missing reduce helper decl in AMD runtime, too

test/studies/arkouda/sub_test
The Arkouda devs are planning to switch to a new set of unit tests, so we are starting to run those in nightly now before officially making that change on the Arkouda side of things.
=> Add proto testing for Arkouda nightly

util/test/sub_test.py
This is a long-standing sporadic. It is long overdue we add this filter.
Test:
=> Add a sub_test filter for known failures on OFI testbed

tools/chpl-language-server/src/chpl-language-server.py, tools/chpl-language-server/test/type_inlays.py, tools/chpl-language-server/test/util/utils.py
This fixes an issue where `chpl-language-server` would add insertable type inlays for loops, even though thats not valid syntax. If a user tried to insert the type inlay, they would then get a syntax error. This PR prevents users from making that mistake by removing the insertable inlay. The inlay still shows, it is just not insertable.
Prior to this PR, users woild be able to insert the type as shown below
Inserting this type creates the following error
This PR prevents this situation from occurring all together.
Tested locally with `make test-cls`
=> Prevent chpl-language-server from providing type inserts for loops

tools/chpl-language-server/src/chpl-language-server.py
Fixes an issue where chpl-language-server would incorrectly call `resolveFunction` on a non-function by adding a missing check in `_search_instantiations`
Tested locally
=> Prevent misuse of `resolveFunction` in chpl-language-server

third-party/qthread/Makefile, util/chplenv/chpl_hwloc.py, util/chplenv/chpl_platform.py
This PR patches some of our build scripts to work with `CHPL_HWLOC=system`. By default, we will still continue to default to `CHPL_HWLOC=bundled` with qthreads, but users can opt in to using a system install by explicitly setting `CHPL_HWLOC=system`
This is a step in the right direction to allow us to use the preferred Chapel configuration for Macs in homebrew. 
Testing:
Notes:
- Partially unblocks https://github.com/chapel-lang/chapel/issues/24931 and https://github.com/chapel-lang/chapel/issues/24655
- Used https://github.com/chapel-lang/chapel/pull/23409 as a starting point
=> Patch build system to allow building with CHPL_HWLOC=system

frontend/include/chpl/types/Param.h, tools/chpl-language-server/test/param_inlays.py, tools/chpl-language-server/test/show_generic.py
Fix how Dyno prints booleans, prior to this PR they were printed as `0` and `1` for `false` and `true`, respectively.
This effects how chpl-language-server prints param values.
```chapel
record R {
param P: bool;
}
// prior to this PR
var a /*: R(1)*/ = new R(true);
// after this PR
var b /*: R(true)*/ = new R(true);
```
Note that this makes dyno printing match the production compiler.
```chapel
compilerWarning(b.type:string); // prints 'R(true)'
param p = false;
compilerWarning(p:string); // prints 'false'
```
Testing
- `make test-cls`
=> Fix how Dyno prints param booleans

util/cron/common-perf.bash, util/cron/common-quickstart.bash
This fixes an issue without `util/cron/common-perf.bash` where `comm-fast.bash` was never being loaded into the environment, meaning that `unset CHPL_TARGET_CPU` was never being run. This was causing the confusing behavior of nightly tests running with `CHPL_TARGET_CPU=none` when they should not have.
The root cause was calling `$(cd $(dirname ${BASH_SOURCE[0]}) ; pwd)` twice in the same `.bash` file, instead of having `CWD=$(cd $(dirname ${BASH_SOURCE[0]}) ; pwd)`.
In an effort to future proof other test scripts, I also changed `common-quickstart` even though it wasn't currently an issue.
=> Fix scripts for perf tests

util/cron/nightly, util/cron/nightly_email.pm, util/cron/nightlysubs.pm
I noticed a relatively significant problem in our `nightly` script. We have two variables in `mysystem`: one that configures whether failing the command should be fatal, and one that configures whether an email should be sent. Most commands are either non-fatal non-email, or fatal and send-email. However, some commands (e.g., `make spectests`, `rsync`) are non-fatal send-email. Despite this, the code for sending an email (or doing any kind of error tracking) is lacking.
```Perl
sub mysystem {
$command = $_[0];
$errorname = $_[1];
$fatal = $_[2];
$mailmsg = $_[3]; # !!!! Not used anywhere?
$showcommand = $_[4];
if ($showcommand) { print "Executing $command\n"; }
my $status = system($command);
if ($status != 0) {
$endtime = localtime;
$somethingfailed = 1;
if($status != -1) {$status = …
```
=> BTR: catch non-fatal, but failed `mysystem` commands in `nightly` script

frontend/include/chpl/resolution/resolution-error-classes-list.h, frontend/lib/immediates/cast_code.cpp, frontend/lib/resolution/resolution-error-classes-list.cpp, frontend/lib/types/Param.cpp, frontend/test/resolution/testCast.cpp, tools/chpl-language-server/test/type_inlays.py
Closes https://github.com/chapel-lang/chapel/issues/25154.
It turns out there's a case missing for casting from {strings, bytes} to {strings, bytes}. Strictly speaking, only string -> string and string -> bytes casts are allowed, but all of them would be implemented the same way (by just copying the string data). This is [how the production compiler does it](https://github.com/DanilaFe/chapel/blob/14f2f0b5b58cf453517a6315747d7a2c8241c6d9/compiler/resolution/preFold.cpp#L2697-L2720).
To match production's "invalid cast" errors, this PR adds some logic that matches that of `preFold.cpp`, which just checks the from- and to- types of the cast, and doesn't attempt casting if the pair is not allowed.
Of course, the PR also adds tests on top of that.
This fixes the hover-on-string bug, too. …
=> dyno: fix string -> bytes cast, disallow casts that are disallowed by production.

modules/internal/DefaultRectangular.chpl, test/functions/export/exportArrProc.chpl, test/functions/export/exportArrProc.good
While sketching out some code involving 'export' declarations, I ran into an error pointing out that an internal method was missing its override keyword, which was accurate.  Fixing that here.
=> Add a missing 'override'

compiler/AST/AggregateType.cpp, compiler/resolution/functionResolution.cpp, modules/standard/Map.chpl, modules/standard/Set.chpl, test/unstable/Map/parSafe.chpl, test/unstable/Map/parSafe.good, test/unstable/Set/parSafe.chpl, test/unstable/Set/parSafe.good
Add special logic to the compiler to prevent the following `map` and `set` initializations from emitting unstable warnings for their `parSafe` field:
```chpl
var m: map(int, int);
var s: set(int);
```
Also add logic to emit unstable warnings when specifying the `map` or `set` types with a value for `parSafe`:
```chpl
type mt = map(int, int, false);
type st = set(int, parSafe=true);
```
=> Add special handling for map.parSafe and set.parSafe unstable warnings

tools/chapel-py/src/chapel/lsp/__init__.py, tools/chapel-py/src/method-tables/core-methods.h, tools/chpl-language-server/src/chpl-language-server.py
This PR fixes several CLS issues as a bundle, as they are all small changes
Bugs fixed:
- Dead code for `if; else if; else` was not displayed correctly
- Errors like "Cannot establish type for call expression" that have no custom error type displayed strangely
=> Fix CLS bugs bundle

test/chplcheck/SKIPIF, test/chplcheck/fixit-interactive/SKIPIF, third-party/chpl-venv/Makefile, third-party/chpl-venv/Makefile.include, util/chplenv/chpl_home_utils.py, util/config/run-in-venv-common.bash, util/config/run-in-venv-with-python-bindings.bash
This PR significantly improves the errors users get when they try and use a chapel-py based tool with mismatched python versions.
This PR splits the chpldeps install directory into general dependencies and python version specific dependencies. This allows the `run-in-venv-with-python-bindings` script to be able to easily distinguish python versions. This also allows builds for multiple python versions to live side-by-side, without needing to `make clobber`.
Resolves https://github.com/chapel-lang/chapel/issues/24892
Tested locally, switching between python3.11 and python3.12
[Reviewed by @mppf and @DanilaFe]
=> Improve chapel-py errors when python versions are mismatched

util/cron/nightly, util/cron/test-linux64-chplcheck-only.bash
Closes https://github.com/chapel-lang/chapel/issues/24782 (except for the part about adding a new Jenkins job)
This PR builds on top of https://github.com/chapel-lang/chapel/pull/25149 to add support for `chplcheck` testing. It does so by adding a new flag, `chplcheck`, which is used to trigger `make chplcheck` during the build. As a consequence of `make chplcheck`, the Python bindings for Dyno are built. This enables existing tests in `test/chplcheck`, because their `SKIPIF` explicitly tries loading the `chapel-py` package from the virtual environment.
This PR depends on #25149 because it relies on the fixes in that PR to send emails on failure.
=> Add support for chplcheck testing to `nightly`

compiler/passes/ResolveScope.cpp, test/modules/use/issue-25172-abc.chpl, test/modules/use/issue-25172-abc.good, test/modules/use/issue-25172-math.chpl
Closes https://github.com/chapel-lang/chapel/issues/25172.
The problem is simple; it's due to the order in which modules are searched. It's possible to reproduce it in a single file, and the bug effectively has to do with the `public use` having not been resolved at the time that a module is searched. Here' a reproducer based on Shreyas' original example.
```Chapel
module A {
proc main() {
use C;
import B.{foo};
foo();
}
}
module B {
public use C;
}
module C {
proc foo() {
writeln("Just chilling");
}
}
```
Produces
```
shreyasrepro.chpl:2: In function 'main':
shreyasrepro.chpl:4: error: Bad identifier, no known 'foo' defined in 'B'
```
The sequence is as follows:
1. A, B, C are constructed and added to the global module list, in that order.
2. A is scope-resolved. To verify the import …
=> Fix symbol-not-found errors when checking imports due to module order

util/packaging/apt/debian11/Dockerfile, util/packaging/apt/debian12/Dockerfile, util/packaging/apt/ubuntu20/Dockerfile, util/packaging/rpm/fc37/Dockerfile, util/packaging/rpm/fc38/Dockerfile, util/packaging/rpm/fc39/Dockerfile
This PR adds a few missing parts to some of the packaging scripts used to build OS packages.
These are currently error-prone, as there is a lot of duplicated code between scripts. This PR serves as a stop gap measure until [this PR is ready](https://github.com/chapel-lang/chapel/pull/25076).
=> Add missing parts of packaging scripts

test/ANNOTATIONS.yaml
Adds an perf annotation for a change to the perf testing infrastructure for chapcs, #25161
=> Add perf annotation for `unset CHPL_TARGET_CPU`

test/functions/export/exportArrProc.skipif
I had forgotten that we generate an error when passing arrays by 'ref' to 'export' proces in multilocale programs, and didn't think to test this new test in that setting.  This skips it in those settings since the point of the test is independent of that question.
=> Skip new test in multilocale compilations

compiler/include/driver.h, compiler/main/driver.cpp, compiler/passes/parseAndConvert.cpp, compiler/util/misc.cpp, frontend/include/chpl/framework/query-impl.h, frontend/include/chpl/resolution/scope-queries.h, frontend/lib/parsing/parsing-queries.cpp, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/test/resolution/testSuper.cpp, test/separate_compilation/serialization/buildAll.compopts, test/separate_compilation/serialization/buildAll.good, test/separate_compilation/serialization/testGenLib.MyMod.good, test/separate_compilation/serialization/testGenLib.OtherMod.good, test/separate_compilation/serialization/testGenLib.both.good, test/separate_compilation/serialization/testGenLib.compopts, test/separate_compilation/serialization/testGenLib.prediff, test/separate_compilation/serialization/testGenLib.standard.good, util/chpl-completion.bash
This PR makes a number of changes that serve to improve the performance of `chpl` under `--dyno-scope-bundled.` They are as follows:
* Disable query tracing. This is currently done system-wide while this PR is a draft, but a merge-ready version of this PR should have some kind of build switch or configuration to disable query tracing when a release build is being created.
* Deliberately leak the memory associated with the Dyno context. This one might be a bit controversial. The Dyno context's destruct -- thanks to all the memoized queries -- takes 0.1s to run. We only ever `delete` it on `clean_exit`, which means that the OS is about to reclaim memory anyway.
* Reduce usage of `parentAst` in identifier lookups (specifically, the logic that checks for, and silences, warnings about …
=> dyno: changes to improve `--dyno-scope-bundled` performance

runtime/src/mem/jemalloc/mem-jemalloc.c, third-party/qthread/Makefile, util/chplenv/chpl_jemalloc.py, util/chplenv/compile_link_args_utils.py, util/chplenv/third-party-pkgs
This PR patches some of our build configuration scripts to be able to use `CHPL_TARGET_JEMALLOC=system`. This allows us to use our preferred configuration for performance (`CHPL_MEM=jemalloc`) in situations where we cannot build the bundled jemalloc (i.e. for packaging)
When using a system jemalloc 5.x, we have to turn off chunk hooks (jemalloc 5.x does not support it)
Testing:
Notes:
- Builds on top of https://github.com/chapel-lang/chapel/pull/25145
- Fully unblocks https://github.com/chapel-lang/chapel/issues/24931 and https://github.com/chapel-lang/chapel/issues/24655, and enables homebrew to use the preferred config (https://github.com/chapel-lang/chapel/pull/25148)
- Uses diffs from https://github.com/chapel-lang/chapel/pull/23409
=> Patch build system to allow building with CHPL_TARGET_JEMALLOC=system

util/packaging/homebrew/chapel-main.rb
Switches the homebrew formula in the chapel tree to use a system install of hwloc, which allows chapel to use qthreads. This results in better performance for users. This also uses a system install of jemalloc, which also increases performance.
To be merged after https://github.com/chapel-lang/chapel/pull/25145 and https://github.com/chapel-lang/chapel/pull/25158
Resolves https://github.com/chapel-lang/chapel/issues/24655
Resolves https://github.com/chapel-lang/chapel/issues/24931
=> Switch homebrew to use system hwloc and jemalloc

frontend/include/chpl/parsing/parsing-queries.h, frontend/lib/parsing/parsing-queries.cpp, frontend/lib/types/ArrayType.cpp, frontend/lib/types/BasicClassType.cpp, frontend/lib/types/CPtrType.cpp, frontend/lib/types/CompositeType.cpp, frontend/lib/types/DomainType.cpp, frontend/lib/types/EnumType.cpp
Normally, IDs are only assigned to ASTs once they've been parsed, so `idToAst` is safe to assume that it should just find the AST that corresponds to a given ID in the existing list of parsing results. However, some of our code expects IDs for certain modules to exist, and returns those. However, this means that sometimes the modules haven't been parsed, and `idToAst` lookups will fail. This PR adds a wrapper for this "return expected ID" pattern that forced the parsing of the module in question.
=> dyno: adjust functions that return pre-determined IDs to parse the modules these IDs come from.

util/chplenv/chpl_gasnet.py, util/cron/test-gasnet-1-everything.bash, util/cron/test-perf.hpe-apollo-hdr.gasnet-1-ibv.large.bash, util/cron/test-slurm-gasnet-1-ibv.c-backend.bash, util/cron/test-slurm-gasnet-1-ibv.fast.bash, util/cron/test-slurm-gasnet-1-ibv.large.bash, util/cron/test-slurm-gasnet-1-mpi.bash
Make `comm-gasnet-ex.c` the default GASNet shim instead of `comm-gasnet.c`.  This will facilitate future development using the GASNet-EX API. As a result of this change, the standard `gasnet` tests in `util/cron` will use GASNet-EX, so the `*gasnet-ex*` tests scripts have been renamed to `*gasnet-1*` and modified to use the GASNet-1 shim. Eventually these tests will be removed when the GASNet-1 shim is deprecated.
Resolves https://github.com/Cray/chapel-private/issues/6356.
=> Switch to using the GASNet EX API as the default

doc/rst/tools/chpl-language-server/chpl-language-server.rst, doc/rst/tools/chplcheck/chplcheck.rst
Resolves Cray/chapel-private#6378
Currently both can't be used at the same time so note that for the time being.
Verified the built docs looked nice
=> Add documentation on how to install the language server and linter in emacs

util/cron/test-linux64-chplcheck-cls-only.bash
No idea how `-assertions` got in there instead of `-asserts`.
Reviewed by @tzinsky -- thanks!
=> Use proper nightly flag for chplcheck-cls-only test

tools/chpl-language-server/src/chpl-language-server.py, tools/chpl-language-server/test/call_inlays.py
Closes https://github.com/chapel-lang/chapel/issues/25115.
This just involves adding some smarter AST inspection to detect what we want to treat like "literals" for the purposes of call inlays. Specifically, I've opted for the following:
1. Complex number literals should only have 'two' components; in the same way that `1+1` is not a literal, neither is `1 + 1i + 1`. On the other hand, `1 + 1i` _is_ a literal.
2. The numbers can be in any order: `1 + 1i` or `1i + 1`. This is a bit liberal, but I think it's reasonable.
3. Double negation is not allowed, neither for real/imaginary numbers nor complex literals.
* So, `-4` is a "literal", but `- -4` is not.
* Similarly, `4 - (-i)` is not a literal.
I've un-xfailed the test that locked this down, and added a separate test for negative numbers. …
=> LSP: add call inlays for complex literals

util/test/sub_test.py
Fixes an issue were `start_test` would not suppress timeout errors properly. Adjusted `sub_test` to add the appropriate future line.
[Review by @jeremiah-corrado]
=> Fix `start_test` not suppressing timeout errors

compiler/util/misc.cpp
This was previously causing some pollution due an accumulation of temporary folders.
Fortunately, doing this does not make any difference in terms of performance improvements that came from leaking the context.
=> Ensure tmp folder is deleted even if context is deliberately leaked

runtime/make/Makefile.runtime.gmp-system, third-party/Makefile, util/chplenv/chpl_compiler.py, util/chplenv/chpl_gmp.py, util/chplenv/chpl_hwloc.py, util/chplenv/chpl_jemalloc.py, util/chplenv/chpl_llvm.py, util/chplenv/chpl_platform.py, util/chplenv/chpl_re2.py, util/chplenv/homebrew_utils.py, util/chplenv/third_party_utils.py, util/packaging/homebrew/chapel-main.rb
Improves Chapels ability to use system packages for GMP and RE2.
This PR adds some `pkg-config`/`brew` logic to use CHPL_GMP=true when GMP is not in the library path. It also adds some extra detection for GMP. This means that if a user has GMP installed, `CHPL_GMP` will default to `system`
This PR makes CHPL_RE2=system a config time error, because Chapel relies on a special version of RE2 that is not available in any package manager. This should improve errors if a user tries to use a system install of RE2
This PR also puts some utils in place to check if GMP is installed on the system, but it does not switch the default for CHPL_GMP
This PR also now requires `pkg-config` on systems with homebrew, and makes the necessary adjustments to hwloc, jemalloc, gmp, and the homebrew formula …
=> Improve ability to use system packages for GMP/RE2

test/chplcheck/MisleadingIndentation.chpl, test/chplcheck/MisleadingIndentation.good-fixit, tools/chplcheck/src/rules.py
This was caused by the incorrect location reporting for variables. If the code above is 4-indented, and then location of the name is used, that name is also 4-indented, code flags as misleading.
As an example:
```Chapel
for 1..10 do
writeln("Hello, world!");
var unrelated = "hi";
```
Note that `unrelated` and `writeln` happen to be aligned, which is sufficient for the false positive.
Reported by @alvaradoo -- thanks!
The solution is to steal the logic from IncorrectIndentation that avoids AST nodes that report their locations oddly.
=> Misleading indent var warn

third-party/gasnet/Makefile
PR #18049 temporarily disabled GASNet's use of hwloc to work-around link failures arising from disparate versions of hwloc ending up in the same executable. Unfortunately this also hobbled GASNet's built-in support for toplogy-aware intelligent selection of network adapter on multi-NIC nodes, especially on InfiniBand multi-rail systems.
This commit restores GASNet's ability to detect hwloc, and ensures that it uses the same hwloc as the rest of the Chapel runtime.
I've tested this on the JLSE Cascade InfiniBand cluster using both `CHPL_HWLOC=bundled` and `CHPL_HWLOC=system`
[Contributed by @bonachea, reviewed and merged by @jabraham17]
=> Fix #18050: Ensure GASNet can use hwloc

compiler/main/driver.cpp
Pending further discussion, I'll disable this feature for the release.
=> Disable exit memory leaks by default

third-party/qthread/Makefile, util/chplenv/chpl_gmp.py, util/chplenv/chpl_hwloc.py
Fixes 2 scripts added in https://github.com/chapel-lang/chapel/pull/25184 and https://github.com/chapel-lang/chapel/pull/25145 to print strings, instead of python tuples and arrays. This caused strange build failures 
I also fixed a whitespace oddity in a Makefile
Thank you @bonachea for pointing this out!
=> Fix `chpl_gmp` and `chpl_hwloc` to not print python arrays

doc/rst/tools/chpl-language-server/chpl-language-server.rst, doc/rst/tools/chplcheck/chplcheck.rst, tools/chpl-language-server/src/chpl-language-server.py, tools/chpl-language-server/test/linting.py, tools/chplcheck/src/chplcheck.py, tools/chplcheck/src/config.py, tools/chplcheck/src/driver.py, tools/chplcheck/src/lsp.py
This makes it possible for `chpl-language-server` to supply linting diagnostics, without users needing to use `chplcheck` directly.
Although using `chplcheck` standalone is the preferred config, some editors only allow one language server per language (like emacs). So this provides a workaround for those editors.
This PR also adds some limited `chplcheck` integration testing with `chpl-language-server`
[Reviewed by @DanilaFe and @lydia-duncan]
=> Make `chplcheck` available from `chpl-language-server`

third-party/Makefile, util/chplenv/chpl_gmp.py, util/chplenv/third_party_utils.py
On Cray X* systems, gmp should be in the default library search and does not require `pkg-config`
Restores the behavior prior to https://github.com/chapel-lang/chapel/pull/25184
Tested that this change allows a system gmp to be used on a Cray XC without pkg-config
Note: We could also do something like `$CHPL_TARGET_COMPILER --print-file-name=libgmp.so` to check if a shared library is available in PATH, rather than special casing for platforms. But that has the potential to cause problems, so this close to a release I just restored the previous behavior.
=> Restore default `-lgmp` on Cray X* systems

test/studies/lcals/LCALSConfiguration.chpl, test/studies/lcals/LCALSMain.chpl, test/studies/lcals/LCALSMain.good, test/studies/lcals/RunVectorRawLoops.chpl, test/studies/lcals/RunVectorizeOnlyRawLoops.chpl
Removes a use of `vectorizeOnly` in LCALS, which can now be replaced with `foreach`. Since the test now uses all `foreach`, the filenames and variables that use `vectorizeOnly` have also been renamed.
=> Remove use of vectorizeOnly

frontend/lib/resolution/default-functions.cpp, frontend/test/resolution/testLibrary.cpp
This PR updates serialize/deserialize signature generation for classes to use a borrowed non-nil receiver type, instead of using a managed type.
Testing:
=> Dyno: Fix serialize/deserialize generation for classes

doc/rst/tools/chpl-language-server/chpl-language-server.rst, tools/chpl-language-server/src/chpl-language-server.py
Followup to https://github.com/chapel-lang/chapel/pull/25214, fixes a missing variable forgotten when applying reviewer feedback
Tested with `make test-cls`
[Reviewed by @DanilaFe and @lydia-duncan ]
=> Add missing variable in `chpl-language-server`

compiler/resolution/functionResolution.cpp, test/functions/ferguson/ref-pair/explain-call.chpl, test/functions/ferguson/ref-pair/explain-call.compopts, test/functions/ferguson/ref-pair/explain-call.good
This PR makes `--explain-call` option show all "best" candidates being considered in the case of return intent overloads. This may be useful when the user is expecting one overload to be invoked and does not realize that another overload is also being considered because of return intent overload.
=> --explain-call to report multiple best candidates

util/cron/nightly
There was some cross-contamination of emails caused by multiple configuratiobs using `mysystem-.txt` instead of `mysystem-config1.txt` vs `mysystem-config2.txt`. I've also found places where my calls to `mysystem` were not properly adjusted for the new convention, and fixed those.
Reviewed by @tzinsky -- thanks!
=> Fixes to `nightly`'s emails from bash

util/packaging/rpm/fc37/Dockerfile, util/packaging/rpm/fc38/Dockerfile, util/packaging/rpm/fc39/Dockerfile
Fixes the usage of `rpmlint` to use the correct flags.
=> Fix rpmlint usage for fedora package builds

runtime/include/tasks/qthreads/chpl-tasks-impl-fns.h, runtime/src/comm/gasnet/comm-gasnet-ex.c, runtime/src/comm/gasnet/comm-gasnet.c, runtime/src/tasks/qthreads/tasks-qthreads.c, runtime/src/topo/hwloc/topo-hwloc.c, third-party/gasnet/Makefile
This PR makes several changes to add support for GASNet PSHM (shared-memory bypass) for co-locales, and to improve RDMA performance via a send progress thread. These are related because the both require changes to how GASNet progress threads are implemented. The changes include:
- Modify the communication task functionality in `tasks-qthreads.c` to support more than one progress thread.
-  When there are co-locales, create an external GASNet progress thread to progress PSHM.
- When there is an external GASNet progress thread, do not create an internal RCV thread because it is redundant.
-  By default, set `GASNET_SND_THREAD` to create an internal GASNet thread that progresses send operations. This can be overridden by setting `GASNET_SND_THREAD=false` in the environment.
- Set …
=> Add support for GASNet PSHM and send progress thread

tools/chpl-language-server/src/chpl-shim.py
Prevents chpl-shim from overwriting files when there is nothing to do. This can cause issues with `chpl-shim mason build` where `mason` doesn't rebuild without source modification. This results in `chpl-shim` writing an empty `.cls-commands.json` file.
Resolves https://github.com/chapel-lang/chapel/issues/25226
Tested that multiple `chpl-shim mason build` runs do not break `.cls-commands.json`
=> Prevent chpl-shim from overwriting files when unnecessary

test/gpu/native/studies/sort/nonGpuError.good
This is a follow up to #25192.
A test with the wrong good file slipped past me after reviewer feedback. Making that change now.
=> Update incorrect error message in good file

test/library/draft/DistributedMap/v3/staticMemManager.chpl
There's probably a race in the test or the context manager it relies on, but given that this is a proof-of-concept rather than a piece of code we want people to rely on, just avoid the problem for now by turning the test off and leave a note warning about the race.
I wasn't able to observe the sporadic failure on OSX, but I was seeing it very rarely on linux - in 5 out of 2200 runs.  Running the other tests in the directory around 1000 times didn't reveal any sporadic behavior for them, so don't turn them off.
Ran a fresh checkout of the directory to verify that the test no longer runs
=> Turn off this test due to it occasionally encountering a sporadic failure

util/cron/common-native-gpu.bash, util/cron/test-gpu-rocm.bash, util/cron/test-gpu-rocm.gasnet.bash, util/cron/test-perf.gpu-rocm.bash
Unset the `CHPL_LLVM_CONFIG` environment variable for GPU tests.
This variable is set by the new Spack install, and prevents the test scripts from overriding with another LLVM such as ROCM LLVM when necessary. Unsetting it is a temporary solution; it should be possible to change the Spack install to never set it in the first place in all configurations, but we want to minimize potential fallout leading up to release.
See discussion at https://cray.slack.com/archives/GDP57GWNS/p1718226256981199?thread_ts=1718211492.378619&cid=GDP57GWNS.
=> Unset CHPL_LLVM_CONFIG variable for GPU tests

doc/rst/usingchapel/chplenv.rst
Updates `chplenv.rst` to include `CHPL_TARGET_JEMALLOC=system` (does not show in rendered docs) and `CHPL_HWLOC=system`.
This documentation should now reflect changes from the following PRs
- https://github.com/chapel-lang/chapel/pull/25145
- https://github.com/chapel-lang/chapel/pull/25158
- https://github.com/chapel-lang/chapel/pull/25184
Built and viewed docs locally
[Reviewed by @jhh67 and @bonachea]
=> Update docs for Chapel enviroment variables

util/cron/nightly, util/cron/nightlysubs.pm
`nightlysubs` defines `$ignoreError`, but the `nightly` script uses `$ignoreErrors`. I renamed the former to the latter, because it reads nicer.
=> Fix variable name mismatch in `nightly` script

test/distributions/block/checkLocalizeConstBlockDom.comm-none.good
In my earlier PR today, I'd been testing almost exclusively locally and then with GASNet in a paratest setting, so missed that I'd forgotten to 'git add' the comm-none .good file that I'd been testing against. This adds it.
=> Add missing .comm-none.good file

runtime/src/comm/gasnet/comm-gasnet-ex.c
This was causing unused variable warnings (and errors in `CHPL_DEVELOPER=1`) for non-ibv conduits, eg:
```
comm-gasnet-ex.c:730:18: error: 'pshmInUse' defined but not used [-Werror=unused-variable]
730 | static chpl_bool pshmInUse = false;
|                  ^~~~~~~~~
```
Fix the warning and fix verbose reporting to work correctly for all conduits.
=> comm-gasnet-ex.c: Fix the pshmInUse variable

test/multilocale/numLocales/bradc/testVFlag.prediff, test/multilocale/numLocales/bradc/testVerboseFlag.prediff
Fix the testVerboseFlag and testVFlag prediffs to ignore new verbose messages from GASNet and the comm layer.
=> Handle new verbose messages from GASNet and the comm layer

util/cron/test-perf.chapcs.arkouda.release.bash
This PR fixes testing of Arkouda with the Chapel release after a system upgrade to LLVM 18.
=> Pin llvm version for arkouda release testing

test/gpu/native/studies/minibude/patches/Bude.patch
Our nightly minibude test pulls from a repos and applies a patch.  Some of the changes in the patch have since been integrated into minibude proper (which was causing the patch to fail to apply during nightly testing). This PR updates the patch.
=> update minibude patch (nightly testing fix)

compiler/main/driver.cpp, util/buildRelease/install.sh, util/chplenv/chpl_home_utils.py, util/chplenv/overrides.py
Changes `install.sh` to install `chplconfig` to `CHPL_HOME` in prefix-based installs, so that `chpl` and `printchplenv` agree on the default environment variables and location of `chplconfig`.
This also adjusts `util/chplenv/chpl_home_utils.py` and `util/chplenv/overrides.py` so the correct CHPL_HOME value is used when looking for `chplconfig`, regardless of the environment variables.
=> Install `chplconfig` to `CHPL_HOME` in prefix installs

compiler/resolution/implementForallIntents.cpp, test/parallel/forall/vass/other/const-errors-due-to-intents.chpl, test/parallel/forall/vass/other/const-errors-due-to-intents.good
Prints the note "The shadow variable 'xyz' is constant due to task intents in this loop" in more cases, see test additions. For example:
```chpl
var i: int;
forall ... do
forall ... do
i = 8;     // error here due to an (implicit) task intent
// in the forall loop on the previous line
```
Somewhat of an aside, consider this example, which came from a  user and motivated this change:
```chpl
var path: ...;
forall ... do
forall ... do
forall ... with (ref path) do
// use 'path' here
```
I consider the `ref path` intent in the inner-most forall loop to be an error already. This is because `path` is a shadow variable in the enclosing loop that is constant and so cannot be passed by the non-const `ref` intent. However, the compiler, due to an implementation quirk, does not check ref intents. …
=> Print "constant due to task intents" in more cases

test/gpu/interop/cuBLAS/c_cublas.compile.sh, test/gpu/interop/cuBLAS/level1/PRECOMP, test/gpu/interop/stream/streamChpl.precomp
This adds extra `nvcc` compilation flags required when doing CUDA interop with Chapel code compiled with LLVM 15+.
The problem with this test was exposed by a test system upgrade to LLVM 18.
Tested that `start_test test/gpu/interop/cuBLAS/ test/gpu/interop/stream/` works with LLVM 18
=> Fix CUDA interop tests for newer LLVM versions

test/multilocale/diten/localBlock/needMultiLocales/localBlock5.chpl
This is a longstanding test, but it isn't one that worked (ran to completion) until I updated it to use a new optimization yesterday. It has leaked memory all along, but because it didn't complete, we didn't complain about it; now that it does, we started to.
Here, I'm changing the class types to use 'shared' (similar to what was already done in its sibling, localBlock6.chpl) to close the leak in a simple way without changing the point of the test (to see how local blocks and classes interact).
Note that neither of these tests used any memory management styles when originally written and that they were added later as we were changing the way classes were managed by default.
=> Update test to avoid memory leak

test/unstableAnonScript/compilationOutput/unstableAnonScript.chpl, tools/unstableWarningAnonymizer/unstableAnonScript.chpl
This adds testing for making sure the compilation output from the `unstableAnonScript` does not contain any warnings.
We `.noexec` the script since we're just testing the compilation output.
Used sym links to get the script into the testing dir.
Adds explicit paramets for `locking` for `openReader` and `openWriter` and also reflows the script code to fit in 80 columns.
=> Update unstable warning anonymizer script

doc/rst/tools/mason/guide/submitting.rst, doc/rst/tools/mason/mason.rst
Adds a 'quickstart' section to the main mason documentation page. Intended to be helpful for people who are experienced with package managers and just need a few hints/reminders to get them going.
Adds a link to the mason-registry to the page about how to publish mason packages.
=> Improve Mason Documentation

runtime/src/arg.c, runtime/src/topo/hwloc/topo-hwloc.c, test/runtime/configMatters/launch/jhh/co-locales/co-locales.py
The argument -nl Mx1 did not cause the launcher to set CHPL_RT_LOCALES_PER_NODE because one locale per node is implied. However, if this variable was already set in the environment it would be passed along to the runtime, causing an inconsistency between the launcher and the runtime. By setting it to 1 both the launcher and runtime agree on the number of co-locales.
=> Set CHPL_RT_LOCALES_PER_NODE correctly in the launcher

doc/rst/usingchapel/prereqs.rst
This PR adjusts prereqs.rst to add some tested commands for installing on Ubuntu 24.04 Noble Numbat. This is a docs change only.
=> Add Prereqs section for Ubuntu Noble

util/devel/test/apptainer/current/ubuntu-noble-nollvm/image.def, util/devel/test/apptainer/current/ubuntu-noble/image.def, util/devel/test/apptainer/extract-docs.py, util/devel/test/vagrant/README-distro-timelines.txt
This PR adds Ubuntu Noble to the apptainer testing and fixes an incompatibility with recent Python 3 versions for extract-docs.py.
This is a test change only.
=> Add Ubuntu Noble to apptainer testing

doc/rst/language/spec/domain-maps.rst
Add some text to the docs to reflect the change made in: https://github.com/chapel-lang/chapel/pull/24952
=> Document dmapped-without-new deprecation in the language spec

doc/rst/technotes/libraries.rst
Resolves #25174 
A user was confused about how to call the module initialization function when using their Chapel library in another language.  While currently the function takes two arguments, these arguments were not documented and are not needed in the Fortran example that demonstrates the call.
Add documentation to the C section talking about these arguments but making it clear that they may be removed in the future.  Be explicit in the Fortran section that the arguments are not needed there, so that users are aware of the difference in that scenario.
Double checked the built documentation
=> Clarify how to call the module initialization function in interop scenarios

test/gpu/native/studies/coral/coral-ep.chpl, test/gpu/native/studies/coral/coral-ep.gpu-compopts, test/gpu/native/studies/coral/coral-ep.gpu-execopts, test/gpu/native/studies/coral/coral-ep.gpu-keys, test/gpu/native/studies/coral/coral-ep.skipif
This adds an "embarassingly parallel" version of Coral to our nightly perf graph. It shows an "upper bound" of performance we could expect to get by removing the communication needed to send input data to nodes.
We would expect this version to scale linearly (it doesn't) so there's something going on there that I'm leaving as future work to investigate.
=> Add coral embarassingly parallel testing

doc/rst/platforms/infiniband.rst
Document the use of GASNET_SUPERNODE_MAXSIZE and CHPL_RT_COMM_GASNET_DEDICATED_PROGRESS_CORE to disable PSHM and to dedicate a core to the GASNet progress threads, respectively.
=> Document GASNET_SUPERNODE_MAXSIZE and CHPL_RT_COMM_GASNET_DEDICATED_PROGRESS_CORE

util/cron/test-perf.gpu-rocm.bash
Moves `unset CHPL_LLVM_CONFIG` lower in a perf config script so that it comes after `common-perf.bash`, which sets `CHPL_LLVM_CONFIG`
[Not reviewed, will get a post-merge review]
=> Use ROCm LLVM in GPU perf test config

compiler/llvm/clangUtil.cpp
Allows `--llvm-print-ir-stage every` to be used with the old pass manager, which is useful when debugging LLVM versions prior to LLVM 16.
=> Fix `--llvm-print-ir-stage every` for old pass manager

third-party/llvm/README, third-party/llvm/llvm-src/lib/Support/APFloat.cpp
Patches our bundled LLVM (similar to #24354) to workaround an [LLVM bug](https://github.com/llvm/llvm-project/issues/81013) that prevents the LLVM support library from being built with GCC 8.1
Tested that Chapel builds with `CHPL_LLVM=none` and `CHPL_LLVM_SUPPORT=bundled` with gcc 8.1
=> Workaround GCC 8.1 and LLVM bug

test/distributions/block/checkLocalizeConstBlockDom.chpl, test/distributions/block/checkLocalizeConstBlockDom.no-local.good
I hadn't thought about how this test would behave in a no-local setting, and am not sure I would've guessed the behavior would match the multilocale .good file even if I had.  This adds a no-local.good file to lock in the current behavior.
While here, I also noticed that I accidentally changed the problem size of the domain without also changing the bbox in the blockDist argument, and didn't mean for them not to match; it doesn't seem to impact how the test works, but seemed worth updating to avoid suggesting I was trying to do anything clever or unusual—I wasn't.
=> Add a no-local.good file for this test

compiler/resolution/functionResolution.cpp, test/functions/ferguson/parenless-call-bug.chpl, test/functions/ferguson/parenless-call-bug.good
This PR fixes #25266 and adds the problematic program from that issue as a test case.
The bug fix is to ignore unresolved functions within `insertReturnTemps`. For certain cases with parenless procs, `call->resolvedOrVirtualFunction()` can return a function that isn't resolved yet & has return type `dtUnknown`. We don't know yet that it needs a return temp in that case & it's equivalent to an unresolved `Call` (and return temps for unresolved calls must be handled somewhere else). So, this change arranges for `insertReturnTemps` to ignore calls in this situation, just as it ignores unresolved calls.
=> Fix incorrect error with some parenless calls

compiler/AST/symbol.cpp, compiler/codegen/cg-expr.cpp, compiler/include/symbol.h, runtime/include/chpl-comm-compiler-macros.h, test/llvm/inlining/no-get-put.chpl, test/llvm/inlining/no-get-put.compopts, test/llvm/inlining/no-get-put.good, test/llvm/inlining/no-get-put.prediff
Improves Chapel codegen with `--fast` and `--no-local` by always inlining `chpl_gen_comm_get` and `chpl_gen_comm_put` and by directly calling `memmove` (instead of through a wrapper.).
Prior to LLVM 16, we used the legacy LLVM pass manager which had a much more aggressive inliner, and these functions would be inlined into performance critical code. With newer LLVMs, the legacy pass manager has been replaced, and the new inliner is much less aggressive. When functions are inlined, the LLVM optimizer has more to work with and can optimize better and perform various forms of LICM, which is important for potentially expensive operations like GET/PUT.
Additionally, when accessing a wide pointer on the same node, the Chapel runtime uses `memmove`. LLVM has a number of optimizations for memory …
=> Improve `--no-local` codegen

modules/standard/Regex.chpl
Follow-up to PR #24935. The rendered docs for \0 was just showing as 0.
=> Fix Regex docs formatting problem with \0 \1 \9

test/variables/static/multilocale.chpl
I made the loop `forall` instead of `for`, which makes the `on` statements sometime execute out of order. This isn't important for the test, so instead, use a `for` loop.
=> Avoid race in multilocale static variable test

third-party/gasnet/Makefile
This reverts commit 9a2d0ba30fcab88241ab957276fa3dd50a9fe064.
Enabling PSHM causes a startup performance regression when `CHPL_GASNET_SEGMENT=fast` and perhaps other runtime performance regressions as well. The former can be observed via the `test/performance/elliot/no-op.chpl` test, which is about 9x slower on one platform. The hypothesis is that this because of differences in the way that the fixed heap is allocated with PSHM enabled vs. disabled. When PSHM is disabled the heap is mmapped, and it's thought that the kernel is mapping all pages at that time, so that `chpl_comm_regMemHeapTouch` isn't doing anything. When PSHM is enabled the heap is not mapped, but `chpl_comm_regMemHeapTouch` is only touching every 2MB so with a much smaller page size there are many pages to be faulted in …
=> Revert "gasnet/Makefile: --enable-pshm for all conduits"

modules/layouts/LayoutCS.chpl
This adds an initializer to 'LayoutCS', taking the two bools that characterize it.  This is motivated by my new compressRows-cs.chpl in which I did not use named arguments, assumed that 'compressRows' was the first argument (it is the first field in the 'CS' class, and ended up (a) not testing what I intended to and (b) introducing a mysterious memory leak, due to setting some bool other than the one I thought I was.  While name-based argument passing would be the obvious/safe/self-documenting thing to do (and the thing all our existing tests of CS that pass arguments happen to do), it also seems like we don't really want users setting fields in the abstract sparse base classes.  So this PR introduces a new initializer taking the two param bools saying whether to compress the rows or …
=> Add an explicit initialzer to LayoutCS to avoid confusion / close memory leak

test/llvm/inlining/no-get-put.notest
Turns off `test/llvm/inlining/no-get-put.chpl` to prevent nightly test noise. 
When merging https://github.com/chapel-lang/chapel/pull/25281 post-release, this `notest` can be deleted
=> Turn off new inlining test

doc/rst/usingchapel/chplenv.rst
removes an extra character and changes 'a' to 'the' in one place.
=> fixup typo in chplenv docs

doc/rst/usingchapel/compiling.rst
Fixes a typo from #24844 that indicates the flag to tell the compiler about additional user module directories is `--M` instead of `-M` (has an extra `-`).
=> fix 'compiling' docs typo indicating an extra '-'

runtime/include/chpltypes.h
This PR aims to fix issue #25245.
Some rocPRIM template definitions use capital I, which conflicts with the macro 'I' defined in the C header <complex.h>. 
For example: https://github.com/ROCm/rocPRIM/blob/release/rocm-rel-5.4.3.1/rocprim/include/rocprim/types/tuple.hpp#L92 
As the C macro is not used elsewhere in Chapel runtime code, it can simply be undefined after <complex.h> is included.
=> undefine C complex I macro which conflicts with ROCm

doc/rst/usingchapel/debugging.rst
The comment is a remnant of the past; the team has been tracking memory leaks in the runtime and fixing them, so Chapel programs (that don't themselves leak memory via unfreed `unmanaged` etc.) should not leak.
=> Stop claiming that Chapel's runtime leaks memory; it doesn't.

test/errors/parsing/underscores.chpl
As @cassella pointed out in [this comment](https://github.com/chapel-lang/chapel/pull/25168#discussion_r1641277014), the test claims to test underscores in assignment positions, but doesn't actually use an underscore there. This PR fixes this oversight.
=> Adjust 'underscores' test to actually lock down what it claims to

util/cron/test-perf.chapcs.arkouda.release.bash
Unload Spack-installed gdb (and transitively its dependency gmp) for Arkouda perf tests on chapcs, as its presence causes bundled GMP self-tests to link against the system GMP and encounter a version mismatch.
To resolve nightly issues from https://chapel.discourse.group/t/test-chapcs07-performance-test-perf-chapcs-arkouda-release/34288.
Testing:
=> Work around bundled gmp build issue in Arkouda perf test

util/cron/test-perf.chapcs.playground.bash
Switch perf playground to main as it is not being used right now and testing main will reduce nightly noise.
=> Switch perf playground to main

doc/rst/technotes/gpu.rst
Add a note that `CHPL_TARGET_COMPILER=llvm` is required for GPU codegen. This was implied by `CHPL_LLVM=[system|bundled]`, but this is more explicit
Built and checked docs locally
=> Make GPU chplenv settings more clear 

runtime/src/comm/gasnet/comm-gasnet-ex.c
This commit partially reverts the effects of 8ecfa22, by restoring the GASNet default of GASNET_SND_THREAD=0 which disables creation of the internal progress thread used to reap send completions.
Users still have the ability to enable the send thread by setting envvar GASNET_SND_THREAD=1 (confirmed through manual testing).
Example:
```
cascade11$ ./hello6-taskpar-dist -nl 2 -v -v -v
<redacted>/chapel/third-party/gasnet/install/linux64-x86_64-unknown-llvm-none/substrate-ibv/seg-large/bin/gasnetrun_ibv -n 2 -N 2 -c 0 -E LC_ALL,LANG,COBALT_JOBID,COBALT_NODEFILE,USER,LOGNAME,HOME,PATH,SHELL,TERM,SSH_AUTH_SOCK,XDG_SESSION_ID,XDG_RUNTIME_DIR,DBUS_SESSION_BUS_ADDRESS,XDG_SESSION_TYPE,XDG_SESSION_CLASS,SSH_CLIENT,SSH_CONNECTION,SSH_TTY,HOSTTYPE,VENDOR,OSTYPE,MACHTYPE,SHLVL,PWD,GROUP,HOST,CSHEDIT,M …
```
=> Revert to default GASNET_SND_THREAD=0

test/library/standard/List/initEquals/listInitEqualsArrayBug.skipif
Switches `test/library/standard/List/initEquals/listInitEqualsArrayBug.chpl` to only run with valgrind, as this is the only config we can reliably assume it will fail in.
Tested that `start_test test/library/standard/List/initEquals/listInitEqualsArrayBug.chpl -respect-skipifs -valgrindexe` is a future and that `start_test test/library/standard/List/initEquals/listInitEqualsArrayBug.chpl -respect-skipifs` skips the test
[Not reviewed - will get a post-merge review]
=> Switch test to only run with valgrind

util/packaging/homebrew/chapel-main.rb
Fix the order of `depends_on` statements to put `"pkg-config" => :build` at the top of the dependency list. It seems `brew style` will fail if it finds this dependency anywhere else in the dependency list.
=> reorder depends_on statements in brew formula per style guide

modules/packages/UgniPerfStats.chpl
The UgniPerfStats module had this error since it used CHPL_COMM without
using or importing it first. I happened to come across it by chance.
No tests exist for this module in particular. It isn't used enough to
add tests.
=> Add use for CHPL_COMM in UgniPerfStats Module

runtime/src/comm/gasnet/comm-gasnet-ex.c
This commit partially reverts the behavioral changes introduced in 8ecfa22, by making the use of `GEX_FLAG_DEFER_THREADS` at GASNet initialization time optional.  The optional behavior is controlled by a new environment variable
`CHPL_RT_COMM_GASNET_DEFER_PROGRESS_THREADS`, which defaults to False.
The net impact of this change is to restore the behavior prior to PR#25140 in which GASNet launches the ibv-conduit receive thread, while allowing the end-user to opt-in to the alternative behavior in which Chapel creates the thread.
As a side-effect of this change, by default ibv-conduit's internal receive thread is *not* impacted by the setting of `CHPL_RT_COMM_GASNET_DEDICATED_PROGRESS_CORE`, nor does GASNet do any pinning of this thread.
=> GASNet: disable GEX_FLAG_DEFER_THREADS by default

modules/standard/GPU.chpl, runtime/src/chpl-gpu.c, test/gpu/native/reduction/basic.compopts
This PR fixes an issue reported by @milthorpe. https://github.com/chapel-lang/chapel/pull/25314 is the key part for solving his case, but the lack of it caused the CPU fall back on `gpu*Reduce` functions to fire. Which turns out is untested and faulty.
The root cause is `here.parent` on a GPU sublocale doesn't return a correctly-setup parent. It does look like a CPU locale, which is nice, but its sublocale is still the same as the GPU sublocale from which it was called. I started to track the issue down, but I don't have a good solution for it yet. I'll create an issue for it.
Until that's fixed, this PR avoids `here.parent` in the fallback logic and implements a low-level "on" statement.
While there, this also adds a flag to test the CPU fallback and modifies a test to use it.
While …
=> Fix CPU-fallback for GPU-based reduction functions

util/chplenv/compile_link_args_utils.py
A standard ROCm module installation has key headers under ROCM_PATH/include - so this should be added as a system include for AMD GPU compilation.
=> add ROCM_PATH/include as a system include path for AMD GPU

runtime/include/tasks/qthreads/chpl-tasks-impl-fns.h
Removes an incorrect assertion in `chpl_qthread_get_tasklocal`. 
This was added in #25140, but because `chpl_qthread_comm_pthreads` always had at least 1 thread this wasn't a problem. However, after #25317 it was now possible (and the default) to have 0 `chpl_qthread_comm_pthreads`.
Removing the assert is sufficient, as the loop itself will already check for `chpl_qthread_comm_num_pthreads` and prevent a null pointer dereference. And it is not an error for `pthread_t me` to not be the process thread or one of the comm threads.
This assert causes issues with out nightly tests, but should not affect users who compile without asserts (which is the default).
Testing
- Tested `start_test test/gpu/native` with gasnet and `CHPL_GPU=nvidia` with cuda 11
=> Remove incorrect assert for missing comm threads

doc/rst/users-guide/TODO, doc/rst/usingchapel/chplenv.rst
Since the `numa` locale model has been deprecated for a while, we should remove it from the docs.
There are other docs which mention numa domains using the `-nl NxLt` syntax, which still works and is unstable today so we keep those.
There are also other mentions of NUMA locale model in `rst/developer/chips/inactive/18.rst` but since it is inactive, I left it as is.
=> Remove NUMA locale model from the docs

doc/rst/usingchapel/QUICKSTART.rst, doc/rst/usingchapel/building.rst, doc/rst/usingchapel/prereqs.rst
Based on the conversation in #24411 we update the memory requirements for building Chapel as follows:
1. Quickstart config requires >2GB of memory
2. CHPL_LLVM=system requires >2GB of memory
3. CHPL_LLVM=bundled requires >4GB of memory
4. Makes clean that other configurations may vary in memory requirements
=> Update memory requirements for building Chapel

doc/rst/technotes/foreach.rst
This PR makes a small adjustment in the `foreach` technote to mention that `with` clauses work but that their behavior may change in vector- or GPU-based executions.
=> Adjust the foreach technote for the recent changes in intents

doc/rst/technotes/gpu.rst
Adjustments on the bigger side:
- Drop limitations on attributes' applicability to promoted functions
- Mention the new `reduce` support
Smaller side:
- Reduce redundancy in LLVM-related bullets
- Clarify requirements for cpu-as-device
- Update tested systems
=> GPU technote updates for 2.1

doc/rst/conf.py, doc/util/versionButton.php
This is the standard update we make after cutting the release branch and releasing the new version.
=> Update docs menu to reflect that 'main' is now 2.2 pre-release

modules/standard/Regex.chpl
Follow-up to PR #25283 to implement a formatting change suggested by @bradcray.
Using
```
``\1``
```
instead of
```
`\\1`
```
has two benefits:
1. It appears in a code font in the rendered docs
2. Anyone viewing the source code will see only a single slash (the intention is to show a single slash and both forms do that in the rendered docs)
Formatting change only, not reviewed.
=> Better format \1 in regex docs

compiler/AST/baseAST.cpp, compiler/include/baseAST.h, compiler/include/expr-class-def.h, compiler/include/expr.h, compiler/include/symbol.h, compiler/include/type.h
This PR removes some overhead in `typeInfo()` in the compiler by "inlining" its prior implementation for `Type` and `Symbol`. Doing this for `Expr` is more involved and is left for another day. No user-visible changes.
The implementation of `typeInfo()` prior to this PR was introduced at the time we introduced `QualifiedType`. The expectation was that we would switch from using `Type*` to using`QualifiedType` in most cases throughout the compiler, so it was natural to derive a `Type*` from  a `QualifiedType`. This aspiration has not come to life so far. If/when it does, this PR can be reverted.
=> Reduce overhead in BaseAST::typeInfo()

frontend/include/chpl/framework/ID.h, frontend/include/chpl/uast/BuilderResult.h, frontend/lib/parsing/parsing-queries.cpp, frontend/test/framework/testIds.cpp, frontend/test/resolution/testCanPass.cpp
Add an overload of the ID constructor that takes only `symbolPath`, leaving default values for postorder traversal number and number of children.
This lets us remove some instances of the default values being hardcoded.
Resolves https://github.com/Cray/chapel-private/issues/4346.
Testing:
=> Add an ID constructor overload taking only `symbolPath`

frontend/lib/parsing/parsing-queries.cpp, frontend/test/resolution/testInteractive.cpp, tools/chapel-py/src/chapel/__init__.py, tools/chplcheck/src/chplcheck.py
Require that setting the module search path occurs before any other queries in the Context revision, if at all. This is to prevent unexpected results from its default empty value being used before it is set, as many queries rely on it. Implemented as an assertion that it is the first query run in the revision.
Also change `testInteractive` to setup module search path earlier to be in line with this requirement. This fixes buggy behavior with `testInteractive --std`, in which we might not find standard module types, that was incidentally introduced in https://github.com/chapel-lang/chapel/pull/25190.
Depends on https://github.com/chapel-lang/chapel/pull/25326 which should be merged first.
Testing:
=> Require `setupModuleSearchPaths` be called before any other queries

runtime/include/tasks/qthreads/chpl-tasks-impl-fns.h
Adds an assert for `chpl_qthread_comm_pthreads != NULL` inside a loop prior to dereferencing it.
This adds back the assertion removed in https://github.com/chapel-lang/chapel/pull/25325, but puts it into the correct location. This has no behavior or user-facing change, rather it just more direcrtly encodes the invariant that at this stage in the code `chpl_qthread_comm_pthreads` must have a value, implied by `chpl_qthread_comm_num_pthreads>0`.
I expect this have no testing change, but sanity checked with `start_test test/gpu/native` with GASNet+CUDA+IBV.
[Reviewed by @jhh67 and @bonachea]
=> Add assert for non-null pointer inside loop

compiler/codegen/cg-CForLoop.cpp
Adds a missing `if(id == ...)` for `--break-on-codegen-id`, a useful feature for debugging Chapel codegen.
=> Add missing id check for `--break-on-codegen-id`

frontend/test/framework/CMakeLists.txt, frontend/test/framework/testUniqueString.cpp
Modify dyno test `testUniqueString` to not rely on the `moby.txt` test data file being present.
Also adjust build system to not make a copy of this file from `test/types/string/psahabu/perf/moby.txt` to be used in this test.
This makes it possible to build and test the frontend without the production test dir existing.
Resolves https://github.com/Cray/chapel-private/issues/6437.
=> Remove testUniqueString dependence on moby.txt test file

doc/rst/developer/bestPractices/StandardModuleStyle.rst, doc/rst/tools/chpldoc/chpldoc.rst
Resolves #25122 
Add more information about the following decisions made during the 2.0 stabilization process, so that future module stabilization can rely on the document:
- documenting/declaring return types for functions
- when to use error handling versus halting
- formal names
Verified the built docs looked okay and that I could follow all the links
=> Extend Standard Module Style Guide

doc/rst/developer/bestPractices/StandardModuleStyle.rst
This was in the original wording but I wasn't sure why it was there because I didn't recall any discussion about it.  But there also wasn't discussion that they had to be camelCase only, either, just that we don't want snake_case at all.  So restore the wording allowing PascalCase to those names
Pointed out by Brad when I merged the previous style guide PR.
Double checked the built docs
=> Specify that it's okay for formal names to be PascalCase as well in the Standard Module Style guide

frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testInitSemantics.cpp
This PR updates the frontend to improve the error messages for the case in which we initialize a generic type field before calling ``init`` (without ``this``). For example:
```chpl
record pair {
type fst;
type snd;
proc init(type fst, type snd) {
this.fst = fst;
this.snd = snd;
}
proc init(type both) {
this.fst = both; // error!
init(both, both); // also error!?
}
}
var x = new pair(int);
```
Prior to this PR the user would encounter potentially-confusing error messages claiming that the ``init`` call could not be resolved. This resolution failure was caused by the the initialization of ``fst``, which in turn partially instantiated ``this``. When resolving the ``init`` call we rejected the partially instantiated ``this`` because initializers can only take concrete or fully generic …
=> Dyno: Fix confusing errors when incorrectly setting fields before 'init' calls

test/variables/static/multilocale-deinit.comm-none.good
This test (which is multi-locale), introduced by https://github.com/chapel-lang/chapel/pull/25320 did not have a `.good` output for local executions.
=> Add local .good file for variables/static/multilocale-deinit.chpl

doc/util/versionButton.php
This is our normal day-of-release bump to the docs version menu once the website updates have been made public.
=> Update version menu to reflect that default docs are about to become 2.1

util/cron/test-homebrew.bash, util/packaging/docker/test/Dockerfile, util/packaging/docker/test/brew_install.bash, util/packaging/homebrew/chapel-main.rb, util/packaging/homebrew/chapel-release.rb
Updates the homebrew formulas for release (what homebrew has committed to homebrew-core) and main (what we use to test our latest changes against) and also updates the dockerfile and test script we use to install and test our package changes. 
This testing updates are necessary to ensure we are actually testing the current changes and not the formula that is currently released. Additionally, the changes include more robust testing that matches the command used (currently) by homebrew CI.
A new check is implemented to ensure that the if the published formula in `homebrew-core` gets updated that we will get a test failure for the homebrew tests. That should help us keep our `chapel-release.rb` formula up to date with what Homebrew has released in the wild. 
Removes …
=> update homebrew formulas and testing scripts

test/chplcheck/ComplexLiteralOrder.chpl, test/chplcheck/ComplexLiteralOrder.good, test/chplcheck/activerules.good, test/chplcheck/allrules.good, tools/chapel-py/src/chapel/__init__.py, tools/chpl-language-server/src/chpl-language-server.py, tools/chplcheck/src/rules.py
This PR adds a rule for complex number literals that are written with the imaginary number first. Conventionally, imaginary number literals are written with the real part first (i.e., `1 + 2i`, not `2i + 1`).
To re-use some code, this PR moves the complex number detection logic out of `chpl-language-server.py` and into the `chapel` module provided by `chapel-py`. In doing so, it also adds comments.
=> chplcheck: Add a rule for writing complex number literals in the wrong order

util/cron/test-homebrew.bash
Updates the path variable name and makes the path expectation consistent in its uses in the script. Removes the reference cloning process for the homebrew-core repo. Needed because the `REPO_CACHE_PATH` available in Jenkins is on a network drive not available to mac minis.
Removes some commented code while here.
Trivial test script configuration change, not reviewed.
=> update homebrew-core repo paths in testing

util/packaging/docker/test/brew_install.bash
Disables some checking of homebrew, not necessarily our formula, just general homebrew checks that are failing outside of our changes and causing us to not be able to test our changes against the homebrew `chapel-main.rb` file.
If the test starts passing after this is merged I will look at adding some or all of these other steps back.
Testing change only, not reviewed.
=> disable some homebrew checks

compiler/include/checks.h, compiler/include/passes.h, compiler/main/checks.cpp, compiler/main/runpasses.cpp, compiler/passes/CMakeLists.txt, compiler/passes/Makefile.share, compiler/passes/checkGeneratedAst.cpp, test/compflags/stopEarly/parseOnly.good, test/parsing/ferguson/var-decl-keyword-type.compopts
This PR renames `compiler/passes/checkUast.cpp` to `compiler/passes/checkGeneratedAst.cpp`.  It also renames the related pass. The name `checkUast` is confusing because it might be interpreted as checking the uAST. However it is checking the AST that is generated from the uAST, just after it is created.
=> Rename checkUast to checkGeneratedAst

util/packaging/apt/common/fill_docker_template.py, util/packaging/apt/debian11/Dockerfile.template, util/packaging/apt/debian12-gasnet-udp/Dockerfile.template, util/packaging/apt/debian12/Dockerfile.template, util/packaging/apt/ubuntu20/Dockerfile.template, util/packaging/apt/ubuntu22-gasnet-udp/Dockerfile.template, util/packaging/apt/ubuntu22-ofi-slurm/Dockerfile.template, util/packaging/apt/ubuntu22/Dockerfile.template, util/packaging/apt/ubuntu24/Dockerfile.template, util/packaging/rpm/common/fill_docker_template.py, util/packaging/rpm/el9-gasnet-udp/Dockerfile.template, util/packaging/rpm/el9-ofi-slurm/Dockerfile.template, util/packaging/rpm/el9/Dockerfile.template, util/packaging/rpm/fc37/Dockerfile.template, util/packaging/rpm/fc38/Dockerfile.template, util/packaging/rpm/fc39/Dockerfile.template, util/packaging/rpm/fc40/Dockerfile.template
Fixes warnings from `docker build` about mismatched casing on `FROM` and `as`.
=> Silence docker FromAsCasing warning

util/packaging/rpm/fc40/Dockerfile.template, util/packaging/rpm/fc40/spec.template
Update the dependencies for fedora 40 to not require LLVM 17, they can now use LLVM 18
=> Update fedora 40 package dependencies

util/chplenv/chpl_gpu.py
Fixes an error message when chplenv cannot find a path in `CUDA/nvvm/...`.
Resolves https://github.com/chapel-lang/chapel/issues/25402
=> Fix typo in error message for nvvm

util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash
Adds a new test config which functions similarly to `util/cron/test-perf.chapcs.playground.bash`, but for multi-locale code on IBV.
=> Add config for multi-locale playground

util/cron/create_release_aptrpm.bash
Fixes the path used when copying a local tarball specified in `CHPL_TARBALL` for nightly packaging tests.
=> Fix path for nightly build script

compiler/codegen/cg-type.cpp, test/types/integral/integral-alias-baseline.bad, test/types/integral/integral-alias-baseline.skipif
This replaces an internal compiler error introduced in #25215 with a user error message. This is for the test that illustrates #24113.
The test `types/integral/integral-alias-baseline` when compiled with --baseline propagates the Chapel type `integral` all the way into codegen. Since `integral` is a generic type, it means that codegen receives invalid AST. Prior to #25215 the compiler reported a user error message, after that PR it failed an assertion. The latter is reasonable because the compiler indeed ends up with something invalid due to its own fault, not user's. However, this PR restores this scenario to a user-facing error just because it looks nicer.
=> Avoid compiler crash under --baseline

frontend/lib/resolution/Resolver.cpp, frontend/test/resolution/testMethodFieldAccess.cpp
Correctly emit an ambiguity error (rather than redeclaration error) in the case of ambiguity between a local variable and a parenless method declared within a method.
Also adds a test that an ambiguity error is emitted.
Follow up to https://github.com/chapel-lang/chapel/pull/25231 which incorrectly made this a redeclaration. Per explanation in https://github.com/chapel-lang/chapel/issues/25376#issuecomment-2197428093.
Testing:
=> Correctly emit error for ambiguity between local var and parenless method

util/cron/test-perf.hpe-cray-ex.ofi.bash
There were a few issues with the previous PR to add nightly perf testing for an HPE Cray EX machine (#25375). This PR resolves them.  Specifically:
- Need to pass `--performance` to nightly
- Need to source `common-perf.bash` to set some environment variables.
Testing done: I've tried explicitly running this script by having the Jenkin's job pull from the branch on my repos and it appears to work.
=> Fixes to nightly EX perf testing script

test/studies/champs/sub_test
@mppf mentioned that he needed to use HTTPS to clone the champs-nightly repo while triaging CHAMPS warnings locally. This PR changes the link to use HTTPS in `sub_test` as well. This should be more portable in general.
=> Use https link while cloning champs-nightly repo in CHAMPS testing

tools/chapel-py/src/chapel/__init__.py, tools/chplcheck/src/driver.py, tools/chplcheck/src/rule_types.py, tools/chplcheck/src/rules.py
This PR builds on the work started by @jabraham17 before the release.
Jade's original work functioned by adding a new `fixit_funcs` field to the `BasicRule` data structure. Previously, `BasicRule` was only used as a convenient way to store the name, pattern, and checking function for basic rules. Then, at the time that basic rules were checked, Jade's implementation also executed the `fixit_funcs`, and added any fixits they produced to this list. This made it possible to mix and match fixit approach (some inline, some using hooks).
My PR builds on this work in the following ways:
* It converts the `BasicRule` data class into a class hierarchy; a parent `Rule` class is extended by `BasicRule` (the existing data structure) and `AdvancedRule` (a new class analogous to `BasicRule`, but …
=> Add support for a `@fixit` decorator to `chplcheck`

frontend/include/chpl/util/filesystem.h, frontend/lib/parsing/parsing-queries.cpp, frontend/lib/util/filesystem.cpp, frontend/test/util/CMakeLists.txt, frontend/test/util/testPathUtils.cpp, frontend/test/util/testShaFile.cpp, test/modules/vass/userInsteadOfStandard/ChapelIO.chpl, test/modules/vass/userInsteadOfStandard/foo2.good
Follow-up to PR #25125.
Adjusts getExistingFileInModuleSearchPath to avoid issuing an ambiguity warning for CHPL_LOCALE_MODEL=gpu where it is intentional that
modules/internal/localeModels/gpu/ChapelGpuSupport.chpl
is used instead of the fallback
modules/internal/ChapelGpuSupport.chpl
It does that by fixing getExistingFileInModuleSearchPath to avoid the warning if both are bundled modules. However, for this to work in a straightforward manner, I needed also to improve some of the related code, which was not handling cases such as "." being a module search path (because it was using prefix checks rather than something file-path aware).
=> Avoid ambiguity warning for bundled modules

modules/packages/Zarr.chpl, test/library/packages/Zarr/CLEANFILES, test/library/packages/Zarr/ZarrTest.chpl
This PR adds support for single-locale reading/writing of Zarr stores, which was a user request. It also adds an `updateZarrChunk` method to allow for writing individual chunks to storage rather than writing the whole array. This is in anticipation of adding more support for partial IO on Zarr stores. 
Testing: CHPL_COMM={none,gasnet} x machines={mac, horizon}
Reviewed by:
=> Single-locale Zarr IO + single chunk updates

third-party/gasnet/README, third-party/gasnet/gasnet-src/other/spawner/gasnetrun.pl
Cherry-pick [GASNet fix](https://bitbucket.org/berkeleylab/gasnet/commits/76c8a6a3904d10fe3e9a6d2f3442cf810d00c5a5) to [bug 4723](https://gasnet-bugs.lbl.gov/bugzilla/show_bug.cgi?id=4723), which resolves ssh-spawner failures when using tcsh.
Problem was reproduced on JLSE cascade, and fix confirmed using the patched Chapel build tree.
Demonstration:
```
ac.dbonachea@cascade12> echo $SHELL
/bin/tcsh
ac.dbonachea@cascade12> ps
PID TTY          TIME CMD
2715 pts/0    00:00:00 ps
35195 pts/0    00:00:00 tcsh
65107 pts/0    00:00:00 bash
ac.dbonachea@cascade12> env | grep -A30 BASH                
BASH_FUNC_module%%=() {  local _mlredir=0;
if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
_mlredir=0;
else
if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then …
```
=> Cherry-pick GASNet bug4723 fix : ssh-spawner failures with tcsh

test/library/packages/LockFreeQueue/memLeaks/consistencyCheck.chpl, test/library/packages/LockFreeStack/memLeaks/consistencyCheck.chpl
This should have been included as part of #25392. Basically I intended to have some symlinks for memory tests for `LockFreeStack`/`LockFreeQueue` but forgot to `git add` them to my commit. This PR fixes it. Looking at last night's test jobs the correctness tests part of that PR ran as expected.
=> Test update: add missing symlinks for memleak tests for LockFreeStack/LockFreeQueue

test/ANNOTATIONS.yaml, util/test/check_annotations.py
Annotations ---
- (#25140) introduced shared-memory bypass behavior that caused several perf. regressions, (#25307) helped resolve that somewhat by reverting some behavior.
Arkouda annotations:
- (Bears-R-Us/arkouda#3323) reverted a prior PR that caused a perf regression a dataframe indexing test
- (Bears-R-Us/arkouda#3335) and (Bears-R-Us/arkouda#3368) Annotate for a PR (and the fixing) that incorrectly changed how the number of bytes were calculated for string IO benchmark.
=> Annotations from week of 6/27

util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash
Fix the generated graphs from the multi-locale playground to use the correct configs.
Removed perf_hpe_apollo_args, which should not be in the arg list
=> Fix graphs for multi-locale playground

test/mason/mason-help-tests/masonHelpTests.good, tools/mason/MasonExternal.chpl
Mason's Spack support relied on being able to clone the `releases/latest` branch from[ spack's repo](https://github.com/spack/spack/), but it appears to have been removed with the latest spack release yesterday.
This PR hardcodes the branch to `releases/v0.22` to avoid test failures caused by this problem.
It's possible that the spack developers will reintroduce a `releases/latest` branch soon (not sure if this is something that happened intentionally, or was just missed in their recent release), in which case I will revert this PR.
=> Fix mason spack branch

test/types/string/ternaryPlain.future, test/types/string/ternaryPlain.skipif, test/types/string/ternaryPlainRef.future, test/types/string/ternaryPlainRef.skipif, test/types/string/ternaryReturn.future, test/types/string/ternaryReturn.skipif
They appear to not encounter memory issues in those circumstances, so only test them in the scenarios where they fail.
Also update the .future files to indicate that the skipifs should be removed when they are resolved
Verifying a fresh checkout of the tests behave as expected
=> Skip these futures when CHPL_COMM != none

test/types/string/ternaryPlain.skipif, test/types/string/ternaryPlainRef.skipif, test/types/string/ternaryReturn.skipif
The behavior with this test is inconsistent across platforms due to the memory issues encountered, so limit it to only situations where the failure is guaranteed.
Checked the behavior with and without using valgrind
=> Update the skipifs for these futures to only run with valgrind testing

test/expressions/ferguson/if-expr/range-field-ifexpr.skipif
This test was originally made to only run under valgrind because it ran into issues.  When the test was resolved, we didn't notice it had a skipif so didn't also remove it then.  Remove the skipif now
Verified a fresh checkout behaved as expected
=> Remove old skipif left over from when this test was a future

tools/chpl-language-server/test/diagnostics.py
Follow-up to PR #25125.
That PR moved "same name as the implicit file module" warning to dyno, so it's now present in the warning output for chpl-language-server. Update the test to reflect that.
=> Update a chpl-language-server test for additional warning

util/packaging/homebrew/chapel-release.rb
Updates the `chapel-release.rb` formula to match the updates that were made recently on `homebrew-core:master` due to version bump of `hwloc` formula in homebrew.
homebrew release recipe change only - not reviewed
=> update chapel-release.rb to match homebrew changes on master

util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash
Enable no-op performance testing to investigate recent `gasnet` performance regression.
=> Enable no-op performance testing

tools/mason/MasonExternal.chpl
Revert changes in https://github.com/chapel-lang/chapel/pull/25427
=> Use releases/latest to clone spack in Mason

test/library/packages/ConcurrentMap.skipif, test/library/packages/EpochManager.skipif
PR #25392 replaced a set of futures that were locking down that (for ConcurrentMap, LockFreeQueue, and LockFreeStack) we failed with memory leaks (when passing '--memLeaks') with normal correctness tests. To lock down the known memory failures I also created a handful of other tests that lock down the "known leak" when passing in '--memLeaks' by execopt (this is the precedent we have for other known leaks as we have a script that detects such tests).
Anyway, we don't want the pure correctness tests to fail on our memleak job so we should skip them. This PR adjusts the skipif files to do that.
=> skip memleaks job for ConcurrentMap/LockFreeQueue/LockFreeStack

compiler/resolution/functionResolution.cpp, test/parallel/taskPar/taskIntents/errorAccessTuple.1.good, test/parallel/taskPar/taskIntents/errorAccessTuple.2.good, test/parallel/taskPar/taskIntents/errorAccessTuple.chpl, test/parallel/taskPar/taskIntents/errorAccessTuple.compopts
This PR builds on #24089 to improve task intent errors for tuples.
After #24089 and prior to this PR, the error for tuples would look like:
```
error: cannot assign to const variable
note: The shadow variable 'call_temp' is constant due to task intents in this begin statement
```
However, `call_temp` is a compiler temporary, so this is not a useful error. This PR improves this so that the error message refers to the tuple variable in user code.
Tested with a full paratest with/without comm.
=> Improve task intent errors for tuples

modules/internal/Atomics.chpl, runtime/include/chpl-comm.h, runtime/src/comm/gasnet/comm-gasnet-ex.c, runtime/src/comm/gasnet/comm-gasnet.c, runtime/src/comm/none/comm-none.c, runtime/src/comm/ofi/comm-ofi.c, runtime/src/comm/ugni/comm-ugni.c
Endpoints that have pending non-blocking operations must be progressed while waiting for the operations to complete. Consider non-blocking `on` statements such as those that occur as a result of the `for loc in Locales do on loc` idiom. The compiler-generated code loops through all locales, invokes a non-blocking `on` operation on each one, and issues the next `on` operation before the previous one completes. Upon completion, each `on` statement decrements an atomic counter, on which the main thread waits until the counter drops to zero. The problem is that the main thread does not progress the network stack while waiting on the atomic variable, and as a result the application may come to a halt waiting for the atomic variable to be decremented while there are `on` operations yet to be …
=> Progress non-blocking operations in OFI

.github/workflows/CI.yml
Resolves https://github.com/Cray/chapel-private/issues/6340.
Testing:
=> Update `upload-artifact` Github CI action from v3->v4

compiler/AST/type.cpp, compiler/include/type.h, compiler/resolution/functionResolution.cpp, test/functions/fcf/ErrorArray.chpl, test/functions/fcf/ErrorArray.good, test/functions/fcf/ErrorCaptureGeneric.good, test/functions/fcf/ErrorGenericClass.chpl, test/functions/fcf/ErrorGenericClass.good, test/functions/jturner/first-class-generic-function.good, test/functions/lambda/captureGenericFn.good, test/io/sungeun/funcPtr6.good
Chapel does not yet support using generic anonymous functions. Although we currently have errors that tell users this, it can be confusing why a given function is generic.
This PR adds some additional logic in function resolution to print why a specific anonymous function is generic. Specifically, 2 cases can trip users up.
1. A class without specific lifetime (e.g. `borrowed` or `unmanaged`)
2. An array (generic due to runtime type)
Tested with a full paratest with/without comm.
Resolves #14202
=> Improve error message for generic anonymous functions

compiler/passes/externCResolve.cpp, compiler/resolution/preFold.cpp, frontend/include/chpl/uast/PragmaList.h, test/extern/records/OpaqueStructUseError.bad, test/extern/records/OpaqueStructUseError.future, test/extern/records/OpaqueStructUseError.good
Prior to this, cg-expr would fail while trying to zero-initialize an incomplete type.
This change only affects the LLVM backend, but the test in this issue was already skipped for the C backend.
Resolves https://github.com/chapel-lang/chapel/issues/18061.
Ensure that the behavior for the C backend is reasonable as well.
=> Mark extern incomplete types as such and fail to default-init them.

compiler/resolution/functionResolution.cpp, modules/internal/ChapelBase.chpl, test/expressions/casts/enumCastErrors-10.good, test/expressions/casts/enumCastErrors-9.good, test/types/enum/bad-cast-to-bool.good, test/types/enum/bad-cast-to-complex.good, test/types/enum/bad-cast-to-imag.good, test/types/enum/bad-cast-to-real.bad, test/types/enum/bad-cast-to-real.chpl, test/types/enum/bad-cast-to-real.future, test/types/enum/bad-cast-to-real.good, test/types/enum/bad-cast-to-type.chpl, test/types/enum/bad-cast-to-type.compopts, test/types/enum/bad-cast-to-type.good, test/types/enum/diten/paramEnumOutOfBounds2.good, test/types/enum/enumCast-abstract-nonparam-toenum.good, test/types/enum/enumCast-abstract-nonparam.good, test/types/enum/paramEnumCast.good, test/types/range/enum/castEnumRange2.good
Specializes the error message when casting an abstract enum to a non-intergal numeric type.
For example, prior to this PR the following code would report an error about casting to int. Now it properly errors with a message about real
```chapel
enum E { R,G,B };
writeln(E.B:real);
```
Resolves https://github.com/chapel-lang/chapel/issues/10385. This issue only talks about `real` being a problem, but other types suffered from this same issue. Namely, `bool`, `imag`, and `complex`. This PR improves the error message for all of them.
Tested with a full paratest with/without comm
=> Improve errorrs when casting abstract enums to numeric types

.github/workflows/CI.yml, util/test/check_perf_graphs.py, util/test/start_test.py
Adds a new CI check that runs some of the code in `start_test` that checks for bad performance test setup. Namely that there are no duplicates, that all `.graph` files and listed in a `*GRAPHFILES`, and that no `file` is listed in `*GRAPHFILES` that does not exist.
Resolves https://github.com/chapel-lang/chapel/issues/6422
=> Add CI to check for bad performance tests

doc/rst/language/spec/domain-maps.rst
Update distributions spec page to include the distribution factory method alternatives to the `dmapped `syntax
Resolves: https://github.com/chapel-lang/chapel/issues/23329
=> Distribution factory methods in language spec

test/performance/ferguson/CommUtil.chpl, test/performance/ferguson/array/remote-array-write.chpl, test/performance/ferguson/record/remote-record-write-copy.chpl, test/performance/ferguson/record/remote-record-write.chpl, test/performance/ferguson/tuple/remote-tuple-write-copy.chpl, test/performance/ferguson/tuple/remote-tuple-write-small-copy.chpl, test/performance/ferguson/tuple/remote-tuple-write-small.chpl, test/performance/ferguson/tuple/remote-tuple-write.chpl
This is a follow up to https://github.com/chapel-lang/chapel/pull/24390.
It looks like the LLVM and C backends generate different number of gets when the remote cache is enabled in some tests. While the updates in that PR covered the changes in the LLVM backend for those tests, it didn't cover for the C backend's behavior. This PR adjusts comm counts checking in those tests.
Michael's theory for the difference between the backends is:
> The cache for remote data is sensitive to the memory layout used in the end. And this could vary between C and LLVM, in particular, how things are laid out in the stack memory.
which I find to be very reasonable.
While there, I also added a `config const verboseComm` flag to the relevant tests' utility module to help with debugging.
Test:
=> Fix some commcounts tests, add a flag to test utility module

compiler/AST/symbol.cpp, compiler/AST/type.cpp, compiler/include/symbol.h, compiler/resolution/wrappers.cpp, test/library/standard/Reflection/canResolvePromoReturn.chpl, test/library/standard/Reflection/canResolvePromoReturn.good
This PR fixes https://github.com/chapel-lang/chapel/issues/13160.
The issue was caused by the fact that for unused promoted expressions, we elide the `yield`s (since nothing needs to be returned, and the side effects are presumably the only thing we care about). 
https://github.com/chapel-lang/chapel/blob/adc72107e038052bff389f27595675d47fe84131/compiler/resolution/wrappers.cpp#L2588-L2596
However, if a promoted result is used in one place and ignored in another, we store one of these (yielding or non-yielding) versions into the cache, and re-use it. As a result, depending on the other, either both don't yield, or both yield; in either case, this is problematic. #13160 triggers this because the promoted expression in `canResolve` is resolved "standalone", and looks like a statement; as a …
=> Fix issue with promotion cache that caused incorrect type inference

compiler/AST/LoopExpr.cpp, test/expressions/new-expr/field-init-missing-args-bug.bad, test/expressions/new-expr/field-init-missing-args-bug.future
Closes https://github.com/chapel-lang/chapel/issues/15588.
The top-level issue is that we call `normalize` a second time while building the loop functions (`chpl__loopexpr`). However, the calls to `normalize` re-visit the calls to `new C`, and trigger double-normalization. This is a known issue that's already worked around by the compiler.
https://github.com/chapel-lang/chapel/blob/adc72107e038052bff389f27595675d47fe84131/compiler/passes/normalize.cpp#L1431-L1438
The check below the comment avoids the error for compiler-generated functions. However, for some reason, the loop lowering functions aren't marked compiler generated, so when they are encountered, the error is not skipped. I marked them as COMPILER_GENERATED, got a clean paratest, and this bug is fixed.
The more "pure" solution …
=> Mark functions generated by `lowerLoopExprs` compiler generated

test/errors/parsing/underscores.1.good, test/errors/parsing/underscores.2.good, test/errors/parsing/underscores.chpl
Lock in that a when clause with a tuple value can't use an underscore to ignore part of the match.
Resolves #24102
=> lock in error for use of _ in when clause

test/library/packages/Curl/COMPOPTS
Removes `-sOpenReaderLockingDefault=false` compopts from curl package tests as OpenReaderLockingDefault is now deprecated.
=> Fix test failures from #25454

frontend/lib/resolution/Resolver.cpp, frontend/test/resolution/testLoopIndexVars.cpp
This PR fixes a failing `chplcheck` test by adjusting the dyno resolver so that it always resolves zip actuals.
Faulty logic in `resolveZipExpression` caused the resolver to exit resolution of a `zip(...)` early if the leader could not be resolved. I've adjusted things so that all actuals are resolved (though _iterators_ for each actual may not be resolved if the leader is unusable).
=> dyno: Fix a bug that skipped resolution of zip actuals

runtime/src/chpl-launcher-common.c, runtime/src/launch/slurm-srun/launch-slurm-srun.c
If `sinfo` produces no output it could be because the specified partition does not exist.
Resolves https://github.com/Cray/chapel-private/issues/4101.
=> Produce better error message if partition doesn't exist

compiler/AST/AggregateType.cpp, compiler/passes/convert-uast.cpp, frontend/include/chpl/uast/AggregateDecl.h, frontend/lib/parsing/ParserContextImpl.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/uast/AggregateDecl.cpp, frontend/lib/uast/post-parse-checks.cpp, frontend/test/resolution/testModuleInitOrder.cpp, test/classes/ferguson/generic-inherit6.bad, test/errors/parsing/bad-superclass.1.good, test/errors/parsing/bad-superclass.2.good, test/errors/parsing/bad-superclass.chpl
Closes https://github.com/chapel-lang/chapel/issues/13086.
This PR adds support for module-qualified inheritance expressions in classes.
```Chapel
module ModuleA {
class A { }
}
module ModuleB {
import ModuleA;
class B: ModuleA.A { }
}
```
Importantly, this __relies on the Dyno scope resolver__ to find the module references prior to converting the AST into the "classic" / old AST. Thus, unless `--dyno-scope-bundled` is used, the bundled modules __will not__ support this feature. It's much harder to get the production resolver to make this work, due to various ordering dependencies of when classes are constructed / unresolved expressions are resolved.
I think this is fine because:
1. The limitation only affects standard library developers. User code will get this feature, because the Dyno …
=> Resolve qualified inheritance expressions in classes

modules/standard/CTypes.chpl, test/library/standard/CTypes/cptrToArrays.chpl
Apparently we can get C pointers to array views and CHAMPS make use of that (but no unit tests). So, my #24390 has broken CHAMPS code where that happens.
This PR adjusts the type checking and adds a relevant test.
Test:
=> Adjust the type checking in c_ptrTo et al. w.r.t. arrays

test/types/records/casts/castToNonType.chpl, test/types/records/casts/castToNonType.good
Locks in the nicer error message when casting a value to a record type
Resolves https://github.com/chapel-lang/chapel/issues/11368
[Not reviewed - trivial test added]
=> Lock in error message for bad cast to record

runtime/src/comm/ofi/comm-ofi.c
Modified message-order MCM mode to not use fi_inject* functions as they do not generate a completion event. See
the comment in` comm-ofi.c` for details. Also cleaned up transmit context initialization and refactored several
functions to have similar control flow. 
=> Fixed injection in message-order MCM mode

doc/rst/usingchapel/chplenv.rst, util/chplenv/chpl_atomics.py
Using `CHPL_ATOMICS=intrinsics` is only available to provide maximum portability, but is a killer for performance (see https://github.com/chapel-lang/chapel/issues/10996). This PR adds documentation to that effect and a `printchplenv` warning when `CHPL_ATOMICS=intrinsics`.
Closes https://github.com/chapel-lang/chapel/issues/10996, which has been left open to document the performance issue. Now that this will be documented in our actual docs, this issue can be closed.
Note: this is related to https://github.com/chapel-lang/chapel/issues/11029, which is about making the default for `CHPL_ATOMICS` cstdlib on all platforms. But `CHPL_ATOMICS=intrinsics` is important for portability with the intel compiler
=> Warn when using CHPL_ATOMICS=intrinsics

runtime/etc/rtmain.c, third-party/qthread/README, third-party/qthread/qthread-src/include/qthread/qthread.h
This resolves the failure in the test `gpu/native/examples/releaseNotes/tasks/begin` in the configuration "gpu-xc-cuda.ugni", which uses the bundled LLVM 18 and CUDA 12 (not sure though). It is a workaround for the problem of handling C++ overloading while parsing the runtime headers during our LLVM codegen, see #25506. The above test failure was triggered by, unlikely caused by, the PR #25215.
[The change is a simple two-liner. Read on for the rationale.]
Prior to this change, qthreads headers defined two overloads of qthread_fill: `qthread_fill(const aligned_t *dest)` in qthread.h and `qthread_fill(syncvar *const dest)` in qthread.hpp. Calls from ChapelSyncvar.chpl intended to invoke the former instead invoked the latter. Given that qthread's `syncvar` is a virtual class due to the …
=> Workaround for overloading in qthreads

modules/packages/LAPACK.chpl, modules/packages/LinearAlgebra.chpl
Improves the compilation commands in the docs for LAPACK and LinearAlgebra to not use undefined environment variables.
This PR just implements the suggestion in https://github.com/chapel-lang/chapel/issues/16433#issuecomment-697036608
Resolves https://github.com/chapel-lang/chapel/issues/16433
=> Improve compilation commands for LAPACK and LinearAlgebra

doc/rst/usingchapel/chplenv.rst
Removes a recommendation to use `CHPL_ATOMICS=locks` over intrinsics as they are even worse for performance.
=> Remove mention of locks from docs warning

compiler/llvm/clangUtil.cpp
Infers the path of CUDA executables from `CHPL_CUDA_PATH`. On a system with CUDA installed to `/usr/local/cuda/`, users can now either set `CHPL_CUDA_PATH=/usr/local/cuda/` or `PATH=/usr/local/cuda/bin:$PATH`.
Tested that Chapel builds and compiles programs with only `CHPL_CUDA_PATH=/usr/local/cuda/` and that `which nvcc` fails (CUDA is not in PATH from shell)
Resolves https://github.com/Cray/chapel-private/issues/4046
=> Allow only setting `CHPL_CUDA_PATH` to find CUDA install

compiler/passes/checkGeneratedAst.cpp, compiler/passes/checkResolved.cpp, test/functions/bradc/varFns/declVarRetHalt.chpl, test/functions/bradc/varFns/declVarRetHalt.good, test/functions/bradc/varFns/declVarRetNothing.chpl, test/functions/bradc/varFns/declVarRetNothingFromNonVoidFn.chpl, test/functions/bradc/varFns/declVarRetNothingFromNonVoidFn.good, test/functions/bradc/varFns/declVarRetVoidFromRefFn.chpl, test/functions/bradc/varFns/declVarRetVoidFromRefFn.good, test/functions/bradc/varFns/declVarUsedRetHalt.chpl, test/functions/bradc/varFns/declVarUsedRetHalt.good
This PR defers a check that causes https://github.com/chapel-lang/chapel/issues/10936 (thus, it closes https://github.com/chapel-lang/chapel/issues/10936).
The error message / check is only intend for cases where the function has no `return`, or has a non-value returning statement (`return;`). If even one value return exists -- even if it's not always reached -- the check will not trigger. Instead, the post-resolution control-flow return checking would catch the issue. However, this check accidentally captures the case when a value is claimed to be returned, but a halt is present. Normally, this case is handled by the aforementioned before-resolution control flow checking.
This PR defers the check for "returning nothing by ref" to the control-flow sensitive stage as well, and narrows it …
=> Allow ref-intent functions to not return anything if they halt

modules/standard/Types.chpl, test/functions/generic/genericActual-isType.chpl, test/functions/generic/genericActual-isType.good
Patches `Types.chpl` to fix a warning that could not be fixed in user code.
Resolves https://github.com/chapel-lang/chapel/issues/25492
=> Fix warning that was unfixable by users

modules/standard/Subprocess.chpl, test/library/standard/Spawn/chpl_signal.h, test/library/standard/Spawn/sendBadSignal.chpl, test/library/standard/Spawn/sendBadSignal.compopts, test/library/standard/Spawn/sendBadSignal.good, test/library/standard/Spawn/sendBadSignal.skipif
Resolves #12162 
The following functions could throw errors, but did not tell users what errors could be thrown, making it more difficult for users to catch those errors and adjust their programs if possible.  Add documentation of what errors could be thrown to:
- subprocess.close()
- subprocess.sendPosixSignal()
Some of the errors thrown by sendPosixSignal and friends were a result of deferring errors from spawn/spawnshell.  Note those errors in spawn/spawnshell and refer back to them.
While here, I updated `sendPosixSignal` to throw an `IllegalArgumentError` if a bad signal was sent to the method.  The method was previously just throwing a `SystemError`, but that would be indistinguishable from the `SystemError`s that could be thrown if there was something wrong as a result of creating …
=> Updates to Subprocess w.r.t. throwing (documentation and behavior)

compiler/include/fcf-support.h, compiler/passes/scopeResolve.cpp, compiler/resolution/fcf-support.cpp, compiler/resolution/functionResolution.cpp, test/exits/albrecht/exitWithNoCall.good, test/exits/sungeun/exitWithNoParensNoArgs.good, test/functions/fcf/standalone-capture-late.chpl, test/functions/fcf/standalone-capture-late.good, test/functions/fcf/standalone-capture.chpl, test/functions/fcf/standalone-capture.good
Closes https://github.com/chapel-lang/chapel/issues/14484.
This PR ensures that a function that was referenced but not called (due to a lack of parentheses) gets warned about, since it's likely a mistake.
```Chapel
proc myFun() {
writeln("executing myFun()");
}
myFun;
```
Produces:
```
standalone-capture.chpl:5: warning: function 'myFun' is mentioned but not called, so it is being captured as a first-class function
standalone-capture.chpl:5: note: 'myFun' is a parenful function, so it needs '(...)' to be called
```
=> Warn for standalone function capture

util/cron/common-arkouda.bash
In https://github.com/chapel-lang/chapel/pull/23402/, check-deps tests for Arkouda were temporarily disabled due to regex.compile failures.
This PR re-enables these tests to ensure Arkouda's dependency check tests keep working and to catch potential deprecations early on.
=> Re-enable Arkouda check-deps tests

test/users/csep524/userDefReduceSlim.chpl, test/users/csep524/userDefReduceSlim.good, test/users/csep524/userDefReduceSlim.prediff
Updates the test to use '?' and avoid the warning, and updates the .good file with the correct line number.
=> Fix userDefReduceSlim by updating test and .good file

compiler/passes/convert-uast.cpp, compiler/passes/flattenClasses.cpp, compiler/passes/scopeResolve.cpp, frontend/include/chpl/resolution/resolution-error-classes-list.h, frontend/include/chpl/resolution/resolution-queries.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/Resolver.h, frontend/lib/resolution/resolution-error-classes-list.cpp, frontend/lib/resolution/resolution-queries.cpp, test/attributes/stability/stability.set.good, test/types/enum/lydia/declaredInClass-initializer.bad, test/types/enum/lydia/declaredInClass-initializer.chpl, test/types/enum/lydia/declaredInClass-initializer.future, test/types/enum/lydia/declaredInClass-nestedRef-method.chpl, test/types/enum/lydia/declaredInClass-nestedRef-method.good, test/types/enum/lydia/declaredInClass-nestedRef.chpl, test/types/enum/lydia/declaredInClass-nestedRef.good, test/unstable/enumInClass.chpl, test/unstable/enumInClass.good
Fixes https://github.com/chapel-lang/chapel/issues/6871.
This PR adds support for enums within classes. The internal error locked in by Lydia's test is due to the fact that an enum is interpreted as a "field" and used accordingly (but it isn't a field!). Instead, I took the same approach that we take for classes, and flattened declaration of nested enums to be alongside their parent class. To ensure that the flattening didn't "break any links", I extended Dyno's existing error for outer variable references to enums nested in classes (classes can't be nested in enums, so the change is "one-directional"). This made all the tests in #6871 pass.
=> Allow declaring enums within classes.

test/classes/forwarding/typeVar.chpl, test/classes/forwarding/typeVar.good, test/classes/forwarding/typeVarExplicitType.chpl, test/classes/forwarding/typeVarExplicitType.good
Closes #7840.
Forwarding with a class with a type field is no longer a problem. Certainly there's no forwarding-specific issue at play, though the second program in that issue does produce an internal compiler error -- and does so even without a forwarding statement. The remaining issue is https://github.com/chapel-lang/chapel/issues/20500, which is unrelated.
=> Add regression tests for #7840

test/functions/promotion/issue-22573.chpl, test/functions/promotion/issue-22573.compopts
Adds a test for promotion with defaults to ensure it continues to compile and work. This was captured in https://github.com/chapel-lang/chapel/issues/22573 but it works on main today.
Not reviewed - trivial test change
Resolves https://github.com/chapel-lang/chapel/issues/22573
=> Lock in behavior for promotion with defaults

compiler/resolution/wrappers.cpp, test/functions/default-arguments/default-argument-out.bad
Closes https://github.com/chapel-lang/chapel/issues/7924, leaving design discussion up to https://github.com/chapel-lang/chapel/issues/25526.
The error was caused due to trying to coerce the default value to the default value's type. However, since no type is explicitly specified, the default value's expression is used. The resulting coercion / move ends up assigning a value to a type. The fix was simply to observe that the type expression was already used to infer the formal's type, so that can be used instead.
=> Fix internal error when `out` intent is used with a default value and no type.

test/arrays/deitz/part5/test_array_type_field_type.future, test/arrays/deitz/part5/test_array_type_field_type.skipif
In #22616 I retired this future because it had been relying on some very old syntax for domain literals. This test happened to pass on my mac, but fails in other configurations due to memory issues, so it needs to become a .future again.
=> Re-futurize test using runtime types for type fields

compiler/codegen/library.cpp, runtime/etc/Makefile.include, test/gpu/native/interop/gpuLibrary/CLEANFILES, test/gpu/native/interop/gpuLibrary/CMakeLists.txt, test/gpu/native/interop/gpuLibrary/Makefile, test/gpu/native/interop/gpuLibrary/test_udf2.cpp, test/gpu/native/interop/gpuLibrary/udf2.chpl, test/gpu/native/interop/gpuLibrary/udf2.compopts, test/gpu/native/interop/gpuLibrary/udf2.good, test/gpu/native/interop/gpuLibrary/udf2.noexec, test/gpu/native/interop/gpuLibrary/udf2.prediff
Used C linkage in the generated header when compiling with `--library` with the GPU locale model. 
Implemented by adding `extern "C"` around all of the function prototypes.
While there, also fixed an issue with `compileline`, which was missing a line to libraries from the system like other commands.  This prevented using `--library` with systems installs of bundled libraries, like jemalloc.
Testing
Resolves https://github.com/chapel-lang/chapel/issues/25222
=> Use C linkage when compiling with `--library` for GPUs

test/compflags/checks/checkModByZeroScope-llvm-none.chpl, test/compflags/checks/checkModByZeroScope-llvm-none.future, test/compflags/checks/checkModByZeroScope-llvm-none.good, test/compflags/checks/checkModByZeroScope-llvm-none.skipif, test/compflags/checks/checkModByZeroScope.good, test/compflags/checks/checkModByZeroScope.skipif
The checkModByZeroScope test for #6188 works under llvm, but still hits the backend C error under gcc.  Split the non-llvm version out to its own future.
Update the checkModByZeroScope.good file to have the correct filename and error message so that it's detected as passing.
=> Split issue 6188 future to a passing llvm test and a non-llvm future

test/gpu/native/interop/gpuLibrary/SKIPIF
Adds a skipif for a new gpu library test (from https://github.com/chapel-lang/chapel/pull/25538), which will not work for multi-locale or systems which require launchers
=> Add skipif for new gpu library test

test/gpu/native/arrays/arraysInKernel.bad, test/gpu/native/arrays/arraysInKernel.chpl, test/gpu/native/arrays/arraysInKernel.future, test/gpu/native/arrays/arraysInKernel2.bad, test/gpu/native/arrays/arraysInKernel2.chpl, test/gpu/native/arrays/arraysInKernel2.future
#20290 captures an issue about not being able to create arrays inside a GPU kernel.
This adds a future related to it. There are some hints as to why we can't do this today in the `.bad` files since it points out what part of array allocation inside a kernel makes it ineligible for GPU execution.
=> Add futures associated with Issue #20290

compiler/codegen/library.cpp, compiler/include/files.h, compiler/llvm/clangUtil.cpp, compiler/util/files.cpp
Resolves #14269 
Prior to this change, `--library-python` compilation with `--print-commands` would not include the Cython command used to make the Python library.  Including the Cython command (and other helpful commands along the way) would allow faster debugging and experimentation when the Cython command fails.
In more details, library compilation was using `runCommand` instead of the usual `mysystem` commands that checked for `printSystemCommands`, due to wanting a string result.  This commit made `runCommand` also check that boolean.
Ran python interop testing on my Mac.  Also ran with `--print-commands` explicitly and it looked good. No failures with a standard paratest on linux (though that location was not set up for python interoperability testing)
=> Include interoperability commands when compiling with `--print-commands`

man/chpl.rst
Anna pointed out in #25514 that it was difficult to know what values were valid for the new flag I added, but also that this was a general problem with the flags in the compiler configuration options section.  The `--help` output seemed generally more barebones, so didn't seem like a good place to add additional information.  But the man page tends to have more information, so it seemed reasonable to refer to the online documentation for the general category.
Note that this will not help if someone jumps to the flag they care about, but it seemed annoying and repetitive to add the link to every single flag in the section.  I'm open to suggestions on how to draw attention to the section header, though
Passed full paratest with futures
=> Add pointer in the man page to documentation on values for environment variables

test/interop/C/cmakelists/targetToChpl/CLEANFILES, test/interop/C/cmakelists/targetToLibToChpl/CLEANFILES
These tests were cleaning up old files, but not cleaning up the directory they lived in.  Which is fine, but it led to errors in their prediff along the lines of "Cannot create directory 'build': File exists" when the tests were re-run. These did not cause the test to fail or anything, but it seemed like a good idea to stop putting the tests in a situation where their prediff would do that.
Verified that the tests ran okay after this change and that the prediff error was gone.
=> Improve test cleanup for these tests

test/runtime/stacktrace/fact-linenum.bad, test/runtime/stacktrace/fact-linenum.future
This PR un-futures the test
test/runtime/stacktrace/fact-linenum.chpl 
as it is now working as expected according to nightly testing.
Resolves https://github.com/Cray/chapel-private/issues/2610 .
I checked that this test works correctly in the following configs on an Ubuntu 24.04 system:
=> Un-future fact-linenum stack trace test as it is now working

util/buildRelease/smokeTest
Remove logic in the `smokeTest` script which sets `CHPL_HOST_COMPILER` and `CHPL_TARGET_COMPILER` based on the `CC` environment variable, as it is no longer needed and can cause issues in some cases (https://github.com/Cray/chapel-private/issues/6320#issue-2306414633).
Resolves https://github.com/Cray/chapel-private/issues/6320.
Testing:
=> Remove special logic in `smokeTest` script for `CC` env var

compiler/AST/AggregateType.cpp, modules/internal/OwnedObject.chpl, modules/internal/SharedObject.chpl, test/classes/delete-free/error-owned-record-in-operator.chpl, test/classes/delete-free/error-owned-record-in-operator.good, test/classes/delete-free/error-owned-record.good, test/classes/delete-free/error-shared-record.good, test/classes/delete-free/owned-shared-on-record.future, test/classes/delete-free/owned-shared-on-record.good, test/classes/delete-free/owned/errors/owned-int-type.bad, test/classes/delete-free/owned/errors/owned-int-type.future, test/classes/delete-free/owned/errors/owned-int-type.good
Realized I forgot to open this during the day.
Closes https://github.com/chapel-lang/chapel/issues/14121. Closes https://github.com/chapel-lang/chapel/issues/25549.
This PR ensures that errors are thrown when non-class types are used with `shared` and `owned`. The previous error was limited to invocations of the initializers for `_owned` / `_shared`, which does not happen in certain cases, including when using type aliases and specifying formal types. This PR adds special-case logic for management types to the type instantiation code directly, which guarantees that it's run as soon as `owned(T)` is attempted. As a result, errors are now caught earlier and in more cases.
=> Strict memory management checks for non-classes

test/arrays/formals/promotedExprAsArrayActual.bad, test/arrays/formals/promotedExprAsArrayActual.chpl, test/arrays/formals/promotedExprAsArrayActual.future
One might expect that promoted expressions get coerced into arrays when giving to arary formals, but this does not happen, which is the underlying cause for the bug in https://github.com/chapel-lang/chapel/issues/7936. It would be nice to have that.
=> Add a future for #7936

compiler/resolution/preFold.cpp, test/types/tuple/these/iterHetTupleArg.bad
This bug was caused by an incorrect usage of PRIM_GET_MEMBER for tuple components that are references. Instead, use PRIM_GET_MEMBER_VALUE. We don't see this in normal production configurations because optimizations eliminated the tuple literal entirely.
Testing:
=> Fix baseline bug for iteration over heterogeneous tuples

test/studies/lsuHeat/heat.graph
Fix the `perfkeys` line in the graph file added [here](https://github.com/chapel-lang/chapel/pull/22391/files#diff-d3f1a3dc82d01de8002362c04c50731962a2d6c2987b7142ce60249fa64e4bab), which was incorrectly camel-cased.
=> Fix graph file for lsu-heat perf tests

util/cron/test-linux64-llvm-bundled.bash
Add a nightly test script which tests examples on linux64 using the bundled LLVM.
To be merged with https://github.hpe.com/hpe/hpc-chapel-ci-config/pull/1247 which sets up a test config using this script.
Resolves https://github.com/Cray/chapel-private/issues/4937.
Testing:
=> Add nightly test script for bundled LLVM

test/types/partial/issue-18005.chpl, test/types/partial/issue-18005.good, test/types/partial/issue-18005.prediff
Adds a test for partial instantiation of a generic to serve as a regression test against #18005.
TESTING:
=> add regression test for partial generic instantation

test/io/serializers/arrays.skipif
IO/serializers/arrays was failing on 32-bit linux because the binary representation of real numbers was different than 64-bit platforms. This PR skips that test on 32-bit linux.
=> Skip IO/serializers/arrays test for 32-bit linux

util/cron/common-arkouda.bash
As of https://github.com/Bears-R-Us/arkouda/pull/3477, the Chapel frontend bindings are required to build Arkouda. This is needed to support a build script that handles the new `registerCommand` and `instantiateAndRegister` annotations added in https://github.com/Bears-R-Us/arkouda/pull/3371.
This PR adds a step to `pip install` the frontend bindings as a part of the nightly testing setup for arkouda.
=> Install python frontend bindings before building arkouda

compiler/AST/LoopExpr.cpp, compiler/AST/stmt.cpp, compiler/AST/thunks.cpp, compiler/include/LoopExpr.h, compiler/passes/convert-uast.cpp, compiler/passes/normalize.cpp, compiler/resolution/functionResolution.cpp, modules/internal/ChapelRemoteVars.chpl, test/gpu/native/errors/assertOnGpuNoLoops.good, test/variables/remote/init-on-target.chpl, test/variables/remote/init-on-target.good, test/variables/remote/on-non-locale.bad
This PR builds (and depends on) on top of my thunks PR (https://github.com/chapel-lang/chapel/pull/25387) to ensure that initialization of remote variables occurs on the target locale. Thus:
```Chapel
class C{}
proc doStuff() {
writeln("On locale: ", here);
return new C();
}
on Locales[1] var myVar = doStuff();
```
Will print `On locale: LOCALE1` and allocate `C` on `Locales[1]` as well. This makes the behavior match the loop expression case, and closes https://github.com/chapel-lang/chapel/issues/25298.
This PR adds test for non-array arguments executing on the target locale, whereas existing GPU tests (which were previously exercising a special case) will serve to continue testing that loop expressions etc. execute on the target locale.
Reviewed by @brandon-neth -- thanks!
=> Remote variables: execute initialization expression on the target locale

frontend/lib/resolution/InitResolver.cpp, frontend/test/resolution/testInitSemantics.cpp
Fixes a dyno init resolver bug, where an error is emitted for an initializer that assigns to a generic field after a concrete field.
Thanks @DanilaFe for suggesting this solution.
Resolves https://github.com/Cray/chapel-private/issues/6522.
Testing:
=> Fix dyno bug resolving init of generic field after concrete field

compiler/codegen/cg-expr.cpp, compiler/include/misc.h, compiler/optimizations/gpuTransforms.cpp, runtime/include/chpl-gpu-impl.h, runtime/include/chpl-gpu.h, runtime/src/chpl-gpu.c, runtime/src/gpu/amd/gpu-amd.c, runtime/src/gpu/cpu/gpu-cpu.c, runtime/src/gpu/nvidia/gpu-nvidia.c, test/gpu/native/cudaOnly/gpuAddNums/gpuAddNums_primitive.chpl, test/gpu/native/intents/forall_refIntentScalar.chpl, test/gpu/native/intents/forall_refIntentScalar.good, test/gpu/native/intents/forall_refIntentScalar.skipif, test/gpu/native/intents/foreach_refIntentScalar.chpl, test/gpu/native/intents/foreach_refIntentScalar.future, test/gpu/native/intents/foreach_refIntentScalar.good, test/gpu/native/studies/transpose/transpose.chpl, test/gpu/native/threadBlockAndGridPrimitives.chpl
This PR enables using `ref` intent'd scalars on a `forall` loop by host registering the scalar before calling the kernel.
In other words, the following:
```chpl
on here.gpus[0] {
var x = 1;
writeln("Before loop x = ", x);
@assertOnGpu
foreach 0..0 with (ref x) do x = 2;
writeln("After loop x = ", x);
}
```
now, correctly, results in `2` where previously it resulted in 1.
This PR will only work for `forall` loops and when using `CHPL_GPU=nvidia` or `CHPL_GPU=cpu`.  I believe it should be possible to get this to work for AMD and `foreach` loops as well but the work required is significant enough that I'd like to do that in a separate PR. More details on the followup work is in this comment: https://github.com/Cray/chapel-private/issues/6442#issuecomment-2234252037
Implementation details for …
=> Support `ref` intent scalar on gpuized forall loop for NVIDIA

compiler/resolution/functionResolution.cpp, test/variables/ref/errors-type-mismatch-fn-1.chpl, test/variables/ref/errors-type-mismatch-fn-1.good, test/variables/ref/errors-type-mismatch-fn-2.chpl, test/variables/ref/errors-type-mismatch-fn-2.good
Closes https://github.com/chapel-lang/chapel/issues/25596.
This PR fixes a bug in which the reference compatibility checking is skipped. In particular, this happens when assigning to the return symbol (with flag `RVV`) from a symbol expression (_not_ an `ADDR_OF` call). Because an error is never emitted, a later assertion that requires compatibility between reference assignments is triggered and compilation fails.
This PR adjusts the condition to also fire off a reference compatibility check for return symbols.
=> Avoid internal error when returning a reference to a value of a different type

runtime/src/comm/ofi/comm-ofi.c
Changes OFI active messages and puts to be blocking when not using `FI_INJECT`.
This partially fixes a bug introduced by https://github.com/chapel-lang/chapel/pull/25483 where code would never get a response to a put/am. This affected HPE EX machines and AWS with EFA.
This PR should fully fix the issue by default on HPE EX machines and AWS with EFA. However, the AWS with EFA case is still broken when using `CHPL_RT_COMM_OFI_INJECT_AM=true` which requires future work to fix.
Tested that the failing tests on HPE EX and AWS no longer fail by default. Also checked that with `CHPL_RT_COMM_OFI_INJECT_AM=true` HPE EX does not fail.
=> Default to blocking when not using OFI injection

util/test/convert_start_test_log_to_junit_xml.py, util/test/find_slow_tests.py
Needed to avoid `SyntaxWarning: invalid escape sequence` in Python 3.12.
See [Python 3.12 release notes](https://www.python.org/downloads/release/python-3120/):
> Invalid backslash escape sequences in strings now warn with SyntaxWarning instead of DeprecationWarning, making them more visible. (They will become syntax errors in the future.)
Warning observed in https://chapel-ci.us.cray.com/job/correctness-test-darwin-m1/651/consoleFull and many other runs.
See similar PR https://github.com/chapel-lang/chapel/pull/24664.
=> Use raw strings for regex patterns in some of our Python scripts

tools/chapel-py/setup.py
Fixes an issue when building chapel-py where the wrong compiler was being used.
=> Explicitly set `CC`/`CXX` when building `chapel-py`

modules/internal/Bytes.chpl, modules/internal/String.chpl
Update the docs for `string/bytes` methods to indicate that the terminating null byte in a buffer is optional, as requested in https://github.com/Cray/chapel-private/issues/4895#issuecomment-2119362267
TESTING:
[reviewed by @vasslitvinov - thanks!]
=> indicate terminating null byte is optional on string/bytes buffers

modules/standard/Sort.chpl, test/deprecated/Sort/depSortInPlace.chpl, test/deprecated/Sort/depSortInPlace.good, test/deprecated/Sort/isSortedDep.chpl, test/deprecated/Sort/isSortedDep.good
Resolves #25544 
Implements the decisions reached by the Sort discussion team.  Updates the argument lists for:
- `sort` by renaming the array argument and removing the `inPlaceAlgorithm` argument (which was confusing), and removing the queries.  Also uses `new DefaultComparator()` instead of the module-scoped variable.
- `isSorted` by renaming the array argument, removing the queries and using `new DefaultComparator()` instead of the module-scoped variable.
- and the `sorted` iterator by removing the queries and using `new DefaultComparator()` instead of the module-scoped variable.
The sorted iterator did not need a deprecation for this change.
Adds tests locking in the deprecation messages for `sort` and `isSorted`.
=> Deprecate old Sort functions and replace with new argument lists

doc/rst/tools/mason/mason.rst
This pull request introduces new documentation that clarifies when to leverage Mason for building Chapel applications and when alternative approaches might be more suitable.
The new documentation provides a breakdown of ideal use cases for Mason, including:
- Pure Chapel Applications: Mason excels at managing the build process for projects written entirely in Chapel.
- External Dependencies with Spack or pkg-config: Mason integrates seamlessly with external dependencies managed by these popular package managers.
Additionally, the documentation highlights scenarios where alternative build tools like Make might be better suited, such as:
- Complex Compilation Needs: When a Chapel program requires intricate build commands beyond the capabilities of the Chapel compiler, tools like Make offer …
=> Enhance User Guidance Docs: Clarify When to Use Mason

compiler/passes/normalize.cpp, compiler/resolution/functionResolution.cpp, compiler/resolution/preFold.cpp
This fixes some niche compilation errors to do with `chpl_getStandInRTT` under `--baseline` (specifically `--no-dead-code-elimination`).
Consider the following comment:
https://github.com/chapel-lang/chapel/blob/ad1bbdf6a8b32d09186fdb901643d683ca6eccd2/modules/internal/ChapelIteratorSupport.chpl#L209-L216
Here, we rely on the fact that `static typeof` gets only static type information. That's because `instanceObj` is null (default-initialized).
The code above is eventually normalized to something like this:
```Chapel
var call_tmp = instanceObj.eltType;
type instanceEltType = __primitive("static typeof", call_tmp);
```
The normal resolution process replaces the primitive with its result:
```Chapel
var call_tmp = instanceObj.eltType;
type instanceEltType = int; // e.g.
```
Later, dead code …
=> Make the `static typeof` primitive actually static (ensure it has no side effects)

doc/rst/usingchapel/debugging.rst
Makes the caveat about `CHPL_TARGET_COMPILER` for Macs more obvious
[Rveiewed by @DanilaFe]
=> Make debugging Mac caveat more obvious

test/release/examples/gpu/README
Looks like we have a script that checks README files under dirs under `test/release/examples/`. This script requires that the README mention every `.chpl` file under that dir.
In #25562 I added this README but didn't mention the `hello-gpu.chpl` file I added. This PR should fix that.
=> add file to README

Dockerfile
This fixes a warning from Docker about mismatched casing between `FROM` and `as` in two lines. Previously Docker would issue a warning about this like so:
```console
WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match
```
This just updates the casing to match and eliminate the warning.
TESTING:
=> fix docker FROM-AS case mismatch

frontend/test/parsing/testParseBegin.cpp, frontend/test/parsing/testParseCobegin.cpp, frontend/test/parsing/testParseCoforall.cpp, frontend/test/parsing/testParseFor.cpp, frontend/test/parsing/testParseForall.cpp, frontend/test/parsing/testParseForeach.cpp, frontend/test/resolution/testLoopIndexVars.cpp
Adds `size_t` casting to `int` vars to fix warning about unsigned to signed comparisons, removes an unused `auto` var.
These fixes were needed to allow `make test-dyno` to proceed without failure - unsure how the original PRs made it passed the dyno-test CI stage.
TESTING:
=> fix size_t and unused var errors in dyno tests

util/cron/common-arkouda.bash
Arkouda nightly tests have been unstable for roughly a month. To address recent test failures attributed to hpcdc changes, this PR reverts the hpcdc directory to its previous configuration. This rollback will allow for continued testing while we diagnose and resolve the compatibility issues.
=> Temporary hpcdc rollback due to Arkouda test instability

runtime/include/chpl-gpu-impl.h, runtime/src/chpl-gpu.c, runtime/src/gpu/amd/gpu-amd.c, runtime/src/gpu/nvidia/gpu-nvidia.c, test/gpu/native/intents/forall_refIntentScalar.skipif
This PR extends the work from #25594 so that `ref` intent scalars will work with `forall` loops on AMD GPUs (the prior PR got it to work for NVIDIA).
Since AMD GPUs (or at least the ones we're using today) don't have universal addressing we need to convert the host pointer to the `ref` intent'd parameter into a "device pointer" before it can be used by the device. This PR performs this step.
Notes to reviewers:
For reasons I don't fully understand, in order to get this to work the thing I pass to the `cfg_add_direct_param` function (to add the ref intent'd param as a kernel argument) needs to be a double pointer (with the pointee being the aforementioned device pointer). To get this all to work I create an array of void pointers and then a second array where each element is a pointer to …
=> support ref intent on gpuized forall w/ AMD

runtime/src/gpu/cpu/gpu-cpu.c
This should have been done as part of #25647 (which made updates so we could have ref intents to scalars in gpuized loops work on AMD). Anyway, that PR updated the signature of `chpl_gpu_impl_host_register` (to have it return the device pointer for the thing you're ref intent'ing) but I forgot to update it in the `cpu-as-device` implementation. This PR does that update.This should have been done as part of #25647 (which made updates so we could have ref intents to scalars in gpuized loops work on AMD). Anyway, that PR updated the signature of `chpl_gpu_impl_host_register` (to have it return the device pointer for the thing you're ref intent'ing) but I forgot to update it in the `cpu-as-device` implementation. This PR does that update.
=> update cpu-as-device mode for prior PR on ref intent scalars

test/studies/arkouda/sub_test, util/cron/common-arkouda.bash
After migrating to the new HPCDC location, compute nodes on our XC testing are unable to access shared libraries containing required dependencies. While tests execute successfully on the login node (`CHPL_LAUNCHER=none`), they fail when launched on compute nodes using `CHPL_LAUNCHER=slurm-srun`.
This PR implements a workaround by installing dependencies directly within the clone for each test run. This approach is expected to increase test runtime by approximately 2 minutes. We will investigate the root cause of the dependency access issue in a subsequent PR.
=> Dependency Access Issue on XC from HPCDC Move

doc/rst/language/spec/procedures.rst
This change clarifies the spec's definition of "`param` narrowing conversion."
Inspired by my confusion expressed in https://chapel.discourse.group/t/implicit-generic-parameter-conversion-odd-error-message/35500/4 and Michael's clarification in the "details" section of https://github.com/chapel-lang/chapel/issues/25604#issuecomment-2243331777
=> "Param narrowing conversion" in the spec - clarification

util/cron/test-docker.bash
Adjust the nightly Docker testing script to push (and pull) `nightly` tags of the images.
This incidentally makes the chapel-gasnet and chapel-gasnet-smp images build off of the just-built Chapel base image. Previously it was building off of the `latest` tag from the last release, not accessing the local copy of `latest` due to [behavior of the buildx builder](https://github.com/docker/buildx/issues/847).
While here, adjust formatting of `util/cron/test-docker.bash` script for clarity.
Resolves https://github.com/Cray/chapel-private/issues/6436.
Testing:
=> Push and pull 'nightly' tag Docker images in nightly test job

util/test/genGraphs.py
Adds error message emission (via just allowing exceptions to bubble out) in `util/test/genGraphs.py`, including for the error silently occurring in https://chapel.discourse.group/t/test-chapcs-perf-test-perf-chapcs/35404/7.
Testing:
=> Emit more error messages from `genGraphs`

util/cron/load-base-deps.bash
This prevented users from sourcing `util/cron/load-base-deps.bash` in their `.bashrc` (directly or indirectly) on un-Spackified systems, due to an infinite loop.
Thanks @mppf for identifying this as the cause.
This source of `.bashrc` should no longer be necessary with Spackification; if anything breaks it should be replaced with a better solution.
=> Remove source of `~/.bashrc` in `load-base-deps.bash`

util/packaging/docker/test/brew_install.bash, util/packaging/homebrew/chapel-main.rb, util/packaging/homebrew/chapel-release.rb
Update `chapel-release.rb` to match changes made to the published formula on `homebrew-core`, merge changes into `chapel-main.rb` so we're prepared for the next release.
Changes revealed some errors in our existing formula where we try to remove directories that don't exist so I updated the paths in the case of `qthread` and `fltk`.
I also added the `--skip-online-checks` flag to `brew test-bot` because our tests aren't concerned about reaching `chapel-lang.org` or other liveness checks.
TESTING:
=> update chapel homebrew formula with upstream changes

compiler/resolution/fixupExports.cpp, test/interop/python/defaultValuesBug.chpl, test/interop/python/defaultValuesBug.good, test/interop/python/defaultValuesBug.prediff, test/interop/python/use_defaultValuesBug.py
Default values seemed to work just fine except when a string was used as one of
the other arguments.
Resolves #25670 
<details>
It turned out that the issue was because string arguments were causing us to
make a wrapper function and that wrapper function was what was getting exported.
Our default value tracking was assuming the argument stored wasn't going to get
replaced with another version after function resolution.
To fix, check for any formals that have a default value tracked in the old
function and insert a map entry for the new version of that function
</details>
Added a new test file to track the bug fix.
Passed a full paratest with futures, and a local run of python interoperability testing
=> Fix a bug with default values in Python interoperability

test/gpu/native/remote-bulk-transfers-par.skipif, test/gpu/native/remote-bulk-transfers.skipif
These are affected by odd sporadic memory corruption which we believe to be due to the ROCm driver more so than the actual GPU implementation, so skip them to avoid polluting nightly testing. 
=> Skip bulk transfer tests on ROCm 4

test/studies/arkouda/sub_test, util/cron/common-arkouda.bash
Rather than quitting after failing to install the deps, fallback on the existing dependencies and try working with those.
=> Stop logging fatal error when installing Arkouda deps fails

util/cron/nightly, util/cron/nightly_email.pm, util/cron/nightlysubs.pm
Builds upon https://github.com/chapel-lang/chapel/pull/25149.
The prior PR added support for sending emails about non-fatal system / bash errors in `nightly`. However, it did not add logic to only send emails when the bash failures change. Thus, each night that a particular bash command fails, a new email is sent out.
This PR adjusts this by only sending an email if a new bash command fails, or if a previously-failing bash command resolves. This avoid redundant emails for failures that last several days. When an email is sent, it also includes the currently-failing bash commands (but an email won't be sent _just_ for existing failures).
=> Avoid re-sending emails for the same bash errors

modules/standard/Subprocess.chpl
Removes an old pragma and updates a reference to `channel` to be `fileReader`/`fileWriter` instead.
It looks like the pragma was added when the `kind` field was getting deprecated, but we forgot to remove it when the deprecated field was removed.  Rectify that oversight so we don't accidentally sweep future issues under the rug
=> Minor cleanups to the subprocess record

util/cron/nightly
This PR adds a `CHPL_NIGHTLY_DO_NOTHING` environment variable that causes `nightly` to exit instead of doing any work (such as running tests, cloning repos, etc).
The reason to do this is to make it easier to reproduce nightly testing configurations locally, for trying to diagnose failures. Most of our testing configs execute a bash script in the `util/cron` directory. The scripts there set a variety of environment variables -- sometimes dynamically depending on the system. Having set these environment variables, they execute `nightly`, which takes care of cloning, building, and executing the Chapel compiler on the selected tests.
When I want to replicate the environment of a particular job, the way to do this most precisely is to connect to the machine that executed the job, and execute …
=> Add an option to `nightly` to do nothing upon being executed

test/gpu/native/distArray/SKIPIF, test/gpu/native/reduction/SKIPIF, test/gpu/native/remote-bulk-transfers-par.skipif
Apparently, hipcc behaves oddly when its output is piped into `head`. Piping the output into grep -- which should still work -- should still work, and doesn't cause the same odd hipcc error.
=> Avoid using `head` for skipif for hipcc.

test/studies/arkouda/sub_test, util/cron/common-arkouda.bash
While we wait for HPCDC to be accessible via the XC compute nodes, we are working around that issue with a mirror of the dependencies installed on the lustre filesystem, which is accessible to the compute nodes. If the lustre filesystem doesn't exist, we will continue to use the old dependencies (for single-node testing).
=> Start using lustre dependencies for Arkouda XC testing

compiler/passes/insertLineNumbers.cpp
With https://github.com/chapel-lang/chapel/pull/24511 merged, we started to propagate line/file numbers for kernels correctly. But that exposed an issue that occurs with `--gpu-specialization` which showed up as junk source code location with verbose GPU.
The problem is a bit complicated. When calling `coforall_fn`s and other similar task functions, we bundle arguments into structs. We call these "arg bundles". Historically, (and currently by default) we have an arg bundle per `coforall_fn`. The pass insertLineNumbers (ILN) relies on this fact when propagating line/file numbers. That means when it starts processing a `coforall_fn`, it first adds `_ln` and `_fn` fields to that function's arg bundle. This works fine because ILN doesn't visit the same function twice.
With …
=> Fix a line no propagation bug with `--gpu-specialization`

test/library/packages/Zarr/ZarrTestLocal.chpl
The 4D test case was using the sizes from a user code, which meant a store of 150MB. It is now reduced to about 150KB instead.
=> Reduced store size for 4d case to reduce testing time

util/cron/test-compare-homebrew-release.bash, util/cron/test-homebrew.bash
Moves the check that makes sure we are notified of changes to the Chapel formula published in homebrew-core to its own test. 
This creates a new test configuration for checking that the version of the homebrew formula we cache in our Chapel tree is consistent with the version published by homebrew. Separating this test because it's a quick test to run and isolating it means we'll get specific failure messages for it, instead of generic homebrew test failures that could currently be caused by three different failure modes. Also since it's such a short test we could run this more than just once per week.
the companion PR for CI changes is https://github.hpe.com/hpe/hpc-chapel-ci-config/pull/1252
Updates the original hombrew-test script to no longer need a to clone the homebrew-core …
=> move homebrew chapel-release diff check to its own test

modules/packages/Zarr.chpl
The write function manually allocates the buffer to write the compressed data to. This PR adds the matching deallocate call.
=> Added a missing deallocate call

compiler/optimizations/gpuTransforms.cpp, compiler/optimizations/refPropagation.cpp, compiler/resolution/implementForallIntents.cpp, compiler/resolution/lowerIterators.cpp, frontend/include/chpl/uast/PragmaList.h, runtime/src/chpl-gpu.c, test/gpu/native/intents/foreach_refIntentScalar.future
This PR enables the following future to work:
```chpl
on here.gpus[0] {
var x = 1;
writeln("Before loop x = ", x);
@assertOnGpu
foreach 0..0 with (ref x) do x = 2;
writeln("After loop x = ", x);
}
```
It now print `After loop x = 2` where before it printed `x = 1`.
As far as implementation:
The gpuized loop needs to have `x` passed in as a pointer so we can do a direct-memory-access from the GPU to RAM. To ensure this happens when we outline the loop body, we rewrite `ref` intents passed to foreach like this during iterator lowering:
```chpl
foreach 0..0 with (ref x) do x = 2;
```
To:
```chpl
ref ref_x = x;
foreach 0..0 with (ref ref_x) do ref_x = 2;
```
**TODO**
=> support ref intent on scalars for gpuized foreach loops

frontend/lib/resolution/call-init-deinit.cpp, frontend/test/resolution/testCallInitDeinit.cpp
Previously, CallInitDeinit::handleInFormal would attempt to resolve an assignment function even if the receiver was a borrowed class. This resulted in a failure when trying to resolve a forwarded call when the corresponding actual was not a class. For example, in the following program:
```chpl
class C {
var x : int;
proc helper() {
return x;
}
}
record R {
var c = new unmanaged C(5);
forwarding c;
proc wrapper() {
return this.helper(); // HERE!
}
}
proc main() {
var r : R;
var x = r.wrapper();
}
```
We would encounter the error:
```
─── error in bar.chpl:16 [NoMatchingCandidates] ───
Unable to resolve call to '=': no matching candidates.
|
16 |     return this.helper();
|
```
This was because CallInitDeinit was incorrectly trying to resolve assignment between ``R`` and a ``borrowed C``.
=> Dyno: Fix erroneous error when resolving forwarded method on class value

test/studies/arkouda/sub_test
In https://github.com/Bears-R-Us/arkouda/pull/3625, `make test-python` was removed from Arkouda, so this PR is updating our testing script to reflect that.
=> Remove make test from Arkouda testing now that it's been removed

test/gpu/native/studies/math/mathKernels.precomp
Fixes errors that occurred from `mathKernels.precomp` on CUDA12 because we need to explicitly pass the CUDA arch (`CHPL_GPU_ARCH`)
Tested on nightly test system with CUDA 12 which was causing errors.
=> Fix GPU interop test by specifying CUDA arch

compiler/resolution/lowerIterators.cpp
#25704 introduced a bug where under the following:
- Doing a non COMM=none build
- `--no-live-analysis` passed at compile time
- Passing `--memTrack` at runtime
We would see any Chapel program fail at runtime. For our nightly tests this occurs with `library/standard/MemMove/setRTTypeBaseline` but I can repro with a simple "hello world" Chapel program.
Investigating I discovered:
- #25704 introduces a new `ref` variable for `ref` intent'd variables passed to `foreach` loop.
- It looks like when passing `--memTrack` we have such a foreach loop (really the `chpl_bytes` iterator in `String`) and when passing `--no-liveness-analysis`
- In `Iterator.cpp` there's a pass that collects the local variables in some iterator (I guess to package them in a record?) and the way this is conducted depends …
=> fix failing test (introduced in prior PR): add FLAG_REV_VAR to ref made for ref'd foreach intents

modules/packages/Zarr.chpl
There are some lingering failures on linux32 configurations because the arguments to the blosc library functions weren't at the right bit width. This PR adds the necessary casts to resolve this failure.
Tested on linux32 machine and locally
Reviewed by:
=> Fixes Zarr Failure for Linux32 Config

modules/standard/Sort.chpl, test/deprecated/Sort/comparatorArgs.chpl, test/deprecated/Sort/comparatorArgs.good
Continues progress for #25552 
`a` and `b` argument names do not match the style of other standard modules, so
replace them with `x` and `y`.  This should not have much impact for user code,
as the compare method is mostly used by the sort implementation itself and the
number and position of arguments is the same.
Additionally, specify that the type of the y argument is expected to be the same
as that of the x argument
Add a test locking in the deprecation messages for the old arguments.
=> Deprecate defaultComparator.compare and reverseComparator.compare argument names

test/studies/shootout/submitted/README.md
Looks like we missed adding that version to the README when we added it, so do so now
=> Add knucleotide4 to the README in the submitted shootouts directory

test/studies/shootout/binary-trees/binarytrees-inner.chpl
Adjusts a comment on binarytrees variation per feedback
Per feedback [here](https://github.com/chapel-lang/chapel/pull/25416#issuecomment-2284778682)
=> Adjust comment on binarytrees benchmark

modules/standard/WeakPointer.chpl
The description for `WeakPointer` was too long to fit in one line on the [module index page](https://chapel-lang.org/docs/chpl-modindex.html), so only part of the text was rendered (see: https://github.com/chapel-lang/chapel/issues/25667). This PR shortens the text to fit.
=> Shorten module description for WeakPointer

modules/packages/Image.chpl, modules/standard/Debugger.chpl, modules/standard/OS.chpl
Fixes the module index for the Image, Debugger, OS, and POSIX modules.
These were identified in https://github.com/chapel-lang/chapel/issues/25667
Prior to this they were not rendered correctly because an extra line existed after `/*` for the doc strings
=> Fix module index text for Image, Debugger, OS, and POSIX

test/library/standard/CTypes/cAddrOfDistArr.suppressif, test/library/standard/CTypes/cAddrOfDistArrLocaleCheck.suppressif
The idiom `c_addrOf(DistributedArray)` doesn't compile with `--baseline` with some codegen assertions. The root cause or the solution wasn't immediately clear to me. So, this PR adds suppressifs for relevant tests for `--baseline`.
=> Add baseline suppressifs for new c_addrOf tests

modules/packages/Zarr.chpl, test/library/packages/Zarr/ZarrCompressors.chpl, test/library/packages/Zarr/ZarrCompressors.good
This PR adds support for selecting between different compression algorithms when writing Zarr stores. Supported options are `blosclz`, `lz4`, `lz4hc`, `zlib`, and `zstd`. This PR also includes tests for these options. Resolves https://github.com/Cray/chapel-private/issues/6588.
Zarr tests run locally, paratest passes on ChapDL
Reviewed by:
=> Support for configurable compression algorithm in Zarr IO 

modules/standard/Sort.chpl
Continues #25552 
Does not require a deprecation due to being an implementation detail.  Also, it's a single argument function, so it is highly unlikely anyone is actually using named argument passing for it
Passed a standard paratest with futures, and the test/library/standard/Sort directory with gasnet
=> Rename the argument for TwoArrayDistSortPerBucketTaskStartComparator.key()

util/test/checkChplInstall
Fixes a bash error in `checkChplInstall`, caused by `CHPL_LOCALE_MODEL` not always being a set environment variable.
The error I saw was `util/test/checkChplInstall: line 153: [: ==: unary operator expected` and the simple fix was to wrap `CHPL_LOCALE_MODEL` in quotes, but I also switched this line to query the `chplenv` scripts (in case `CHPL_LOCALE_MODEL` comes from a .chplconfig file, or similar).
=> Fix bash error in `checkChplInstall`

test/chplenv/errors/noLocksOnDarwin.chpl, test/chplenv/errors/noLocksOnDarwin.good, test/chplenv/errors/noLocksOnDarwin.prediff, util/chplenv/chpl_atomics.py
Explicitly disallow `CHPL_ATOMICS=locks` on MacOS.
This was already unsupported, as the runtime would fail to build. The `CHPL_ATOMICS=locks` implementation uses `pthread_spinlock_t`, which is not supported on MacOS. This PR just makes it clearer to the user that this is not supported, rather than some strange build error.
Tested that `CHPL_ATOMICS=locks printchplenv` on MacOS gets the correct error.
=> Disallow CHPL_ATOMICS=locks on MacOS

test/studies/arkouda/sub_test
The Arkouda testing framework has been consolidated to a single testing library and with that consolidation there was a change in naming of how to run the unit tests from `make test-proto` to `make test-python`.
=> Switch from test proto to test for Arkouda testing

test/chplenv/errors/noLocksOnDarwin.skipif
Adds a skipif to only run new printchplenv test on MacOS
=> Add skipif to only run test on MacOS

test/optimizations/autoLocalAccess/stencil/unsupportedCases.suppressif
The test in question generates slightly different output with `--baseline --report-auto-local-access`. There is no behavioral difference at execution time. This PR adds a suppressif for this test with `--baseline`.
Tested locally with `--respect-skipifs`
=> Add a suppressif for an ALA test

modules/packages/PrecisionSerializer.chpl
The description for `PrecisionSerializer` was too long to fit in one line on the [module index page](https://chapel-lang.org/docs/chpl-modindex.html), so only part of the text was rendered (see: https://github.com/chapel-lang/chapel/issues/25667). This PR shortens the text to fit on one line.
=> Shorten module description for `PrecisionSerializer`

util/chplenv/third_party_utils.py
Resolves #25381.
This PR adds a workaround to address #25381. The workaround is to filter out `-L/usr/lib` in `filter_libs_skip_arg` from `third_party_utils.py`. The justification for removing this is that it shouldn't be required since it's a system default (if/when it is appropriate).
=> Add a workaround for issue #25381

test/io/ferguson/preadc/preadvpwritev_sys.skipif, test/io/ferguson/preadc/preadvpwritev_sys.test.c, test/io/ferguson/preadc/preadwrite_sys.skipif, test/io/ferguson/preadc/preadwrite_sys.test.c
Fixes two broken `preadc` tests that had regressed after renaming `err_t` to `qio_err_t`. Since these tests were not run in the default configuration, they were missed in nightly testing. This PR also changes the skipif for these tests to let them run in the default configuration.
Tested manually locally on MacOS
=> Fix `preadc` tests

modules/packages/ChplFormat.chpl, modules/packages/ObjectSerialization.chpl, modules/standard/JSON.chpl
Updates the first line of documentation to fit into the rendered module index list.
Also adds a link to the IO module's high-level serialization documentation.
=> Improve serializer module documentation

modules/internal/ChapelSyncvar.chpl, test/types/sync/syncNothing.chpl, test/types/sync/syncNothing.good
This is a simple fix to disable support for `sync nothing` similar to how we recently have for `sync void`.  From what I've been able to tell, I don't believe we've ever supported either, and think that this was a case of lack of sufficient testing/forethought to realize that both should've been made illegal when `none`/`nothing` were introduced.
The approach here was to simply remove `isNothingType` from the list of types that support `sync` variables in module code.  I also added the test from #20929 to lock it in.
Resolves #20929
Note that there's an ongoing desire to support a value-less full/empty bit using `sync void` or `sync nothing` in #9370
=> Disable 'sync nothing' (because it doesn't currently work)

modules/dists/StencilDist.chpl
Reduce the amount of fine-grained communication incurred by `stencilArr.updateFluff` using privitization.
To give an idea of the performance benefits of this PR, the following table shows the runtime improvements on a navier-stokes simulation that uses the stencil distribution with a few different problem sizes:
| problem size | main (sec) | this branch (sec) |
| :--- | :--- | :--- |
| 1024^2 | 9.0031 | 8.23441 |
| 2048^2 | 11.3919 | 8.9551 |
| 4096^2 | 22.3191 | 19.6735 |
I also tested a few other changes to `updateFluff` on the same navier-stokes benchmark. All of these either hurt performance or didn't result in a noticeable improvement:
* using puts instead of gets for the buffer assignment
* using a barrier instead of atomic synchronization
* parallelizing the buffer …
=> Stencil Distribution performance improvments

frontend/test/resolution/testCPtr.cpp
This appears to have been left in accidentally in https://github.com/chapel-lang/chapel/pull/22654 (https://github.com/chapel-lang/chapel/pull/22654/files#diff-2c0c215b3271a5265835dc847315a79c13df3b1db4df5a25d9b0d01352c67984R69).
=> Remove extraneous debugger breakpoint in testCPtr

util/chpl-completion.bash
Adds `--llvm-print-ir-file` to `util/chpl-completion.bash`. This was missed in https://github.com/chapel-lang/chapel/pull/25201
=> Add missing flag to bash complete script

test/gpu/native/studies/math/mathKernels.chpl, test/gpu/native/studies/math/mathKernels.cu
Use a smaller problem size for `mathKernels`, so that perf testing on older hardware does not take too long
=> Use smaller size for GPU perf test

util/cron/test-gpu-ex-rocm-62.bash, util/cron/test-gpu-ex-rocm-62.ofi.bash
Adds two new testing configs for ROCm 6.2, with/without comm, on EX
=> Add test scripts for ROCm 6 nightly tests

test/studies/hpcc/PTRANS/old/PTRANS.valgrind.compopts
This is a fix to #25772 which needed an explicit -o flag due to its use of modules, but wasn't caught in my testing due to being a valgrind-only test.
=> Fix: Get PTRANS.valgrind.chpl working again without auto -o flag

test/runtime/jhh/colocales/colocales.py, third-party/hwloc/Makefile
Reverts a small piece of https://github.com/chapel-lang/chapel/pull/25734. By unconditionally enabling pci support with hwloc, this caused issues with chplenv and reading the hwloc dependencies
Specifically, `printchplenv --internal` would print:
```
Warning: Simple pkg-config parser does not handle Requires.private
Warning: in $CHPL_HOME/third-party/hwloc/install/...../lib/pkgconfig/hwloc.pc
```
This broke some nightly tests, so I am reverting this temporarily. Enabling PCI support is required eventually for full colocales+GPUs support
=> Revert change to always use hwloc with pci

doc/rst/language/spec/arrays.rst
=> Remove a double space between words in array spec docs page

modules/packages/Image.chpl, test/gpu/native/simpleExternHello.skipif
Fixes a few sets of failures in last nights tests
- skips a GPU test with `CHPL_GPU=cpu`
- adds the proper imports for the formal types
- fixes a c_ptr vs c_ptrConst issue
=> Fix nightly failures from new test changes

test/exercises/life.chpl, test/exercises/life.compopts
Expands `test/exercises/life.chpl` to have distributed examples using `BlockDist` and `StencilDist`.
Tested locally
=> Add distributed Game of Life example

test/studies/arkouda/sub_test
Arkouda requires chapel-py to build servers with a non-default configuration. Eventually we'd like to make it a requirement for any Arkouda build.
To move in that direction, all of our nightly testing configurations should be able to build Arkouda using chapel-py (some configurations are currently resorting to a fallback build mode). This PR update's Arkouda's sub_test script to `make chapel-py-venv` before attempting to build Arkouda.
=> Build chapel-py-venv in Arkouda testing

doc/rst/index.rst
While the sidebar shows both module and doc indexes, the main page of the doc only shows the second one. This PR fixes this mismatch by linking the module index as well.
=> Link module index to global doc index

modules/packages/DistributedBag.chpl
Fix `DistributedBag` description in module index.
Related to #25667.
=> Shorten `DistributedBag` module description for module index

runtime/src/gpu/amd/gpu-amd.c
Fixes a typo introduced in https://github.com/chapel-lang/chapel/pull/24706, where `chpl_gpu_impl_copy_host_to_device` was replaced with `hipMemcpyDtoD`, when it should have been replaced with `hipMemcpyHtoD`
=> Fix typo in hip memcpy call

frontend/lib/resolution/Resolver.cpp, frontend/test/resolution/testMethodCalls.cpp
Closes https://github.com/Cray/chapel-private/issues/6469.
In some cases for methods on classes, the receiver is not `in borrowed`, but a generic type; this is in particular true for `type` methods (like `MyClass.foo()`) and parenless procedures that return types or params. The [spec describes this here](https://chapel-lang.org/docs/language/spec/classes.html#class-methods). This PR implements that logic.
=> Dyno: implement specification of parenless `type`/`param` procs on nilable types

frontend/include/chpl/framework/mark-functions.h, frontend/include/chpl/resolution/resolution-error-classes-list.h, frontend/include/chpl/resolution/resolution-queries.h, frontend/include/chpl/resolution/resolution-types.h, frontend/include/chpl/resolution/scope-queries.h, frontend/include/chpl/types/QualifiedType.h, frontend/include/chpl/types/Type.h, frontend/lib/resolution/InitResolver.cpp, frontend/lib/resolution/resolution-error-classes-list.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/resolution-types.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/test/resolution/testMethodCalls.cpp, frontend/test/resolution/testNew.cpp, frontend/test/resolution/testTypeConstruction.cpp, frontend/test/resolution/testTypePropertyPrimitives.cpp
Closes https://github.com/Cray/chapel-private/issues/6281.
Up to this point, Dyno used the types of a record's fields to determine whether or not said fields need to be included in the type constructor. The trickiest cases were something like the following:
```Chapel
class C {}
record myRec {
var myField: C; // Need to know that C is a class;
// Classes without a memory management strategy are generic
// Records don't have memory management and so would be concrete 
}
```
```Chapel
record myRec {
var myField: someFunction(args); // If someFunction produces a generic type, myField is generic.
}
```
The problem with the approach of resolving the fields to build the type constructor is that the type expression of a field may invoke the type constructor. An example is the following code: …
=> Dyno: syntactically determine the genericity of fields for building type constructors

modules/packages/Image.chpl
Fixes a memory leak when calling `writeImage` for JPG or PNG, caused by missing calls to `deallocate`
Tested `start_test --memLeaks test/library/packages/Image` locally.
=> Fix memory leak when writing JPG and PNG images

frontend/include/chpl/framework/ID.h, frontend/include/chpl/parsing/parsing-queries.h, frontend/include/chpl/resolution/resolution-queries.h, frontend/include/chpl/resolution/resolution-types.h, frontend/include/chpl/uast/AstNode.h, frontend/include/chpl/uast/Builder.h, frontend/lib/parsing/parsing-queries.cpp, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/resolution-types.cpp, frontend/lib/resolution/return-type-inference.cpp, frontend/lib/types/CompositeType.cpp, frontend/lib/uast/AstNode.cpp, frontend/lib/uast/Builder.cpp, frontend/test/resolution/testTypeConstruction.cpp
This PR implements type constructors for inheriting generic classes, which requires some substantial changes to the way type constructors are implemented in dyno.
Prior to this PR, we used a compiler-generated signature that re-used the uAST and IDs for fields in place of real formals. This breaks down when inheriting classes are involved because the parent fields will have different symbol paths from the child's fields, which can confuse the rest of dyno's infrastructure. This especially causes issues for the way we store resolution results, which cannot account for IDs from different symbol paths.
This PR addresses this problem by generating dedicated uAST for the type constructor, rather than trying to fake formals with the uAST of fields. Generating uAST on the fly like this is new …
=> Dyno: Type constructors for inheriting generic classes

test/runtime/jhh/colocales/colocales.py
PCI must be enabled for `hwloc` to detect PCI devices, but it's not required when using `hwloc` topologies from XML files.
=> Co-locale tests don't require PCI to be enabled

util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash
It's enabled by default now, so no need to keep playground testing it.
=> Disable playground testing of localize domain optimization

modules/packages/Zarr.chpl, test/library/packages/Zarr/.gitignore, test/library/packages/Zarr/CLEANFILES, test/library/packages/Zarr/ZarrCompressors.chpl
Removes the requirement that zarr metadata contain a "compressor" field. 
Tested locally and chapdl with comm none, locally with gasnet.
Reviewed by:
=> Optional compressor field for Zarr stores

test/gpu/native/studies/math/mathKernels.chpl, test/gpu/native/studies/math/mathKernels.cu, test/gpu/native/studies/math/mathKernels.suppressif
Skips testing of `mathKernel.chpl` perf test on cray-cs, as doing CUDA interop seems to cause hangs.
I observed that running the perf test without any interop, the test finished in a matter of seconds. But as soon as the CUDA version was linked the program would hang (before running any kernels). I was unable to diagnose this further due to network issues, but given that cray-cs is an older, unsupported hardware I don't think its the important.
Also reverts the change in https://github.com/chapel-lang/chapel/pull/25781, as its no longer needed. 
=> Skip math GPU perf test on cray-cs

util/chplenv/chpl_gpu.py
Fixes a check for the GPU sdk path that was incorrectly giving errors when not using the GPU locale model
=> Fix check for GPU sdk path when not using GPU support

frontend/lib/resolution/Resolver.cpp, frontend/test/resolution/testFunctionCalls.cpp
Fix a dyno bug in resolving a dependently typed type constructor call used as the type of a formal, when the type constructor has a constrained generic formal.
Example:
```
record Foo
{
param fooStrides : int;
// param fooStrides; // always worked
}
proc bar(param strides = 1, other: Foo(strides)) {}
// proc bar(param strides : int, other: Foo(strides)) {} // always worked
bar(1, new Foo(1));
```
Previously, `Foo(strides)` would fail to resolve; we attempted to resolve it in `Resolver::handleCallExpr` which occurs prior to instantiation, at which point `strides` is an unknown param and therefore cannot be passed to the `int` param required by `Foo`'s type constructor. This is resolved by extending `handleCallExpr`'s skip-until-later logic to also allow skipping type constructors, in the …
=> Fix bug resolving constrained, dependently typed, type constructor formals

frontend/lib/resolution/InitResolver.cpp, frontend/lib/resolution/InitResolver.h, frontend/test/resolution/testInitSemantics.cpp
This PR improves the resolution of initializers to handle super.init calls involving generic classes. The core improvement is to have ``InitResolver`` store the parent's type, and update that type after a call to super.init. With an accurate parent type ``InitResolver`` can use that when it incrementally recomputes the current receiver type as fields are initialized.
Testing:
=> Dyno: Implement super.init for generic classes

modules/standard/Sort.chpl, test/deprecated/Sort/keyPartInt-resolved.good, test/deprecated/Sort/keyPartInt.chpl, test/deprecated/Sort/keyPartInt.compopts, test/deprecated/Sort/keyPartInt.good, test/deprecated/Sort/keyPartInt.prediff, test/library/standard/Sort/correctness/SortTypes.chpl, test/library/standard/Sort/correctness/SortTypesStrided.chpl, test/library/standard/Sort/correctness/keyPartEnding.chpl, test/library/standard/Sort/correctness/sortStrings.compopts, test/library/standard/Sort/correctness/testMsbRadixSort.chpl, test/library/standard/Sort/errors/errors-keyPart.chpl, test/library/standard/Sort/errors/errors-keyPart.compopts, test/library/standard/Sort/errors/errors-keyPart.tIntReal.good, test/library/standard/Sort/errors/errors-keyPart.tStrStr.good, test/library/standard/Sort/errors/errors-keyPart.tStrStrDep.good, test/library/standard/Sort/errors/errors-keyPart.tUintInt.good, test/library/standard/Sort/errors/errors-keyPart.tUintIntDep.good
Adds the `keyPartComparator` interface, which requires users to implement `proc keyPart` and optionally implement `proc compare`. Also adds the `keyPartStatus` enum, which replaces the 0th element of the tuple returned from `keyPart`
Adds `keyPartStatus` from https://github.com/chapel-lang/chapel/issues/25552
Implements `keyPartComparator` from https://github.com/chapel-lang/chapel/issues/25553
Testing
Future work:
- this PR adds a number of TODOs that should be resolved when `relativeComparator` and `keyComparator` are added
=> Add `keyPartComparator` interface for `Sort`

modules/packages/Image.chpl
Fixes a issue where the Image module failed to compile on 32 bit systems due to a type mismatch
Spot checked `test/library/packages/Image/downSample.chpl` and `test/library/packages/Image/basicJpg.chpl` on a 32 bit system
=> Fix Image module compilation on 32 bit systems

modules/standard/Sort.chpl
Reserves the name `sortComparator` as an interface in `Sort`. https://github.com/chapel-lang/chapel/issues/25554 captures the details of how this interface should behave, but that is future work.
=> Reserve the sortComparator identifier in the Sort module

util/build_configs/cray-internal/setenv-xc-x86_64.bash
`setup_cmake_nightly.bash` gives a non-working CMake on Atlas, where this script is used in nightly testing. But Atlas already loads a working CMake from the new Spack install setup, which is replaced by this one, so just stop replacing it.
=> Remove call to `setup_cmake_nightly.bash` in `setenv-xc-x86_64.bash`

test/studies/arkouda/sub_test
Remove manual build of chapel-py from arkouda's sub_test s.t. tests only rely on `make chapel-py-venv`.
All of our nightly configs appear to be working with the `chapel-py` install in chpl-venv, so manually building it should no longer be necessary.
=> Stop manually building `chapel-py` in Arkouda nightly testing

frontend/lib/resolution/resolution-queries.cpp
This was done in https://github.com/chapel-lang/chapel/pull/21765.
=> Remove completed TODO for using hashmap in ResolutionResultByPostorderID

frontend/lib/parsing/parsing-queries.cpp, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/resolution-queries.cpp
Do not compare postOrderIds to specific integer values. Instead, use the method ``ID::isSymbolDefiningScope()``.
Testing:
=> Dyno: Clean up usage of postOrderId numbers

doc/rst/language/spec/records.rst
@jeremiah-corrado pointed out that searching for `init=` does not lead to the appropriate spec section to describe the feature. This PR fixes that problem by adding an `.. index::` entry for `init=`.
Reviewed by @jeremiah-corrado - thanks!
=> Add an index entry for init=

frontend/include/chpl/uast/Builder.h, frontend/include/chpl/uast/BuilderResult.h, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/lib/uast/Builder.cpp, frontend/lib/uast/BuilderResult.cpp, frontend/test/resolution/testTypeConstruction.cpp
Modifies the idToParentId map of a BuilderResult to point to the module ID from which the compiler-generated module was created.
In the scope query logic, we then reject a compiler-generated module as a boundary for lookups, and allow the logic to proceed as though the compiler-generated module lived within the original code.
The implementation of Builder/BuilderResult is updated to better support these changes.
Also, a new test is added to lock in the correct behavior.
Testing:
=> Dyno: Fix scope resolution bug for type constructors and private-use

util/cron/test-darwin-arm.bash, util/cron/test-gasnet.darwin-arm.bash
Follow up to https://github.com/chapel-lang/chapel/pull/25835 in which I forgot to update the config names 🤦 .
=> Fix config names for darwin-arm tests

test/library/standard/Allocators/bumpAlignment.chpl, test/library/standard/Allocators/customAllocator.32.good, test/library/standard/Allocators/customAllocator.execopts, test/library/standard/Allocators/customAllocatorClass.32.good, test/library/standard/Allocators/customAllocatorClass.execopts, test/studies/shootout/binary-trees/binarytrees-pool.chpl
Fixes tests for custom allocators to be compatible for linux32 as well.
=> Fix allocator tests when running on linux32

third-party/qthread/README, third-party/qthread/qthread-src/include/qthread/qthread.h, third-party/qthread/qthread-src/src/feb.c
This is a backport of https://github.com/sandialabs/qthreads/pull/269 from the development version of qthreads. It should hopefully resolve any performance regressions.
=> Qthreads: Adjust Fences To Fix Perf Regression

modules/internal/DefaultRectangular.chpl, test/optimizations/autoAggregation/localArrays.bad, test/optimizations/autoAggregation/localArrays.future, test/optimizations/autoLocalAccess/localArrays.notest, test/parallel/forall/checks/const-indices-blc.good, test/users/alvaradoo/refToSubclassInternalError-shared.good, test/users/alvaradoo/refToSubclassInternalError.good
Resolves an issue @bradcray bumped into his PR: https://github.com/chapel-lang/chapel/pull/25754#issuecomment-2294427566. As such, merging this should unblock https://github.com/chapel-lang/chapel/pull/25754.
Consider:
```chpl
forall i in MyArr.domain {
... MyArr[i] ...
}
```
This innocent loop is suitable for ALA (and AA in more complicated scenarios) if MyArr is distributed. In such cases, distributed arrays' iterators will ensure that the array is accesssed locally. That's not the case for DefaultRectangular arrays, though. I personally find this confusing and [want to change it](https://github.com/chapel-lang/chapel/issues/25351). However, until we do that, we should disable the optimization to comply with the current semantics/implementation of the parallel iterators.
We could …
=> Disable ALA and AA for Default Rectangular arrays

util/cron/create_release_aptrpm.bash, util/packaging/apt/test/Dockerfile.template, util/packaging/common/build_helpers.sh, util/packaging/common/test_package.py, util/packaging/rpm/common/fill_docker_template.py, util/packaging/rpm/test/Dockerfile.template
Adds basic correctness testing of Linux packages to nightly tests. This improves upon the unused `util/packaging/common/test_package.py` script and actually begins using in the nightly build script. This should validate the packages and catch mistakes when making changes to the package configs
Tested that `__test_package` works with existing packages.
=> Add basic correctness testing of Linux packages to nightly tests

runtime/src/comm/gasnet/comm-gasnet-ex.c
This pull request addresses something which I noticed while trying to understand what code actually runs in Chapel's "no-op" test.  As explained in the commit message (reproduced below), I observed that the hook to touch heap memory between allocation and static registration with the NIC was only ever enabled for `FAST` segment mode, even though `LARGE` is identical to `FAST` in all registration-based conduits other than ibv.  This single-commit pull request resolves this.
This is anticipated to have minimal impact on users, since my understanding of Chapel's documentation is that it does not recommend any of aries, ofi or ucx-conduits (except where ucx is mentioned as an alternative to ibv in "rare cases").
I have taken an approach that splits the preprocessor logic into two groups of …
=> Enable chpl_comm_regMemHeapTouch() for more configurations

frontend/lib/parsing/bison-chpl-lib.cpp, frontend/lib/parsing/chpl.ypp, test/chplcheck/IncorrectIndentation.chpl, test/chplcheck/IncorrectIndentation.good, test/chplcheck/IncorrectIndentation.good-fixit, tools/chapel-py/src/resolution.cpp, tools/chpl-language-server/test/basic.py, tools/chplcheck/src/rules.py
This PR fixes two CLS and adds a workaround for an existing chplcheck issue.
- Prior to this PR, name locations where not being recorded for enum element
```chapel
enum A {
a = 123 // the location is `a = 123`, the name location is `a`
}
``` 
- Prior to this PR, inherit expressions and expressions inside enum elements were not being properly scope resolved by chapel-py
```chapel
class CC { }
class C: CC { } // now goto-def works on `CC`
proc foo param do return 1;
enum A {
a = foo // now goto-def works on `foo`
}
```
- Prior to this PR, `chplcheck` would report IncorrectIndentation for `if`/`else if` chains erroneously. While [that bug](https://github.com/chapel-lang/chapel/issues/25256) still exists, this PR adds a skip for `else if` (similar to the `public`/`private` workaround)
Tested …
=> Fix several CLS bugs

modules/standard/Math.chpl
On Discourse, Damian pointed out that the documentation for `atan2` was not as accurate as it could be - atan2 is not the equivalent of the arctangent, it is the arctanget.  He also suggested adding information about the range of the result for it and `atan`.
Double checked the built documentation looked right
=> Improves the documentation for atan and atan2 in the Math module

doc/rst/technotes/gpu.rst
Removes a link to the github issue tracking ROCm 5 support
=> Remove github issue on ROCm 5 support from GPU technote

test/studies/shootout/binary-trees/binary-trees.graph
Adds existing performance test `binarytrees-pool` to the existing binarytrees `.graph` file
=> Add graph of binarytrees-pool

test/library/standard/Allocators/customAllocator.execopts, test/library/standard/Allocators/customAllocatorClass.execopts, test/studies/shootout/binary-trees/binarytrees-pool.skipif
Followup to https://github.com/chapel-lang/chapel/pull/25834
Fixes a typo in the execopts scripts and validated it works on a linux32 platform.
Skip `binarytrees-pool` on linux32 to avoid out-of-memory. The program attempts to allocate far more than a 32 bit program can address.
=> Followup to Allocator linux32 fix

modules/standard/Sort.chpl, test/unstable/sortInterfaces.good, test/unstable/sortModule.chpl, test/unstable/sortModule.good, test/unstable/sortRegion.good
This PR marks the Sort module as a whole as stable. Any publicly visible symbols inside of the module are now considered stable, unless otherwise specified.
=> Mark the Sort module as stable

runtime/src/gpu/amd/gpu-amd.c
Add support for partitioning GPUs among co-locales.
Resolves https://github.com/Cray/chapel-private/issues/6640.
=> Co-locale support for AMD GPUs

util/packaging/apt/common/fill_docker_template.py, util/packaging/apt/test/Dockerfile.template, util/packaging/common/build_helpers.sh, util/packaging/common/test_package.py, util/packaging/rpm/common/fill_docker_template.py, util/packaging/rpm/test/Dockerfile.template
Fixes an issue where the Linux packages built for multi-locale would warn about `CHPL_TARGET_CPU=unknown`. This is just a warning that users could ignore, but after this PR it won't show anyways.
The also fixes an issue where the packages used the default of `CHPL_TARGET_CPU=native` for `COMM=none` builds. This only really worked by happenstance and we should not continue to rely on it. `native` specializes builds for the current microarchitecture the compiler is being run on, this is not correct for packages that need to be distributed to other microarchitectures. However, we got away with it because the docker builds where already the "lowest denominator" platforms. This change does mean we no longer get user code specialization, but that is a [separate …
=> Fix `CHPL_TARGET_CPU=unknown` warning with linux packages

test/studies/champs/sub_test
We are seeing OOM issues with the C backend that we attribute to a
system/backend issue. Until we figure out what's going wrong, stop testing
a CHAMPS executable with the C backend.
=> Skip testing a CHAMPS executable with the C backend

util/packaging/common/build_helpers.sh
Fixes paths to be absolute based on CHPL_HOME in the test scripts for the linux packages.
[Reviewed by @jhh67 and @tzinsky]
=> Fix paths in packaging scripts

doc/util/nitpick_ignore, frontend/include/chpl/types/Param.h, frontend/include/chpl/types/param-classes-list.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/return-type-inference.cpp, frontend/lib/types/EnumType.cpp, frontend/lib/types/Param.cpp, frontend/test/resolution/testEnums.cpp, frontend/test/resolution/testParams.cpp, frontend/test/resolution/testRanges.cpp, frontend/test/resolution/testTypeConstruction.cpp, tools/chapel-py/src/method-tables/param-methods.h
Prior to this change, param enums could not be stringified because EnumParam only stored an ID and the stringify signature lacks a ``Context*`` needed to map the ID to uAST. Without the uAST we cannot compute the original name of the enum element. Instead, store a pair of ``ID`` and ``string`` inside EnumParam and compute the element's name ahead of time.
``EnumParam::get`` is supplanted by ``Param::getEnumParam``, which is a helper that uses the provided context to fetch the enum element's name as a string, then builds the stored pair.
Using this capability, this PR easily implements param enum to string casts.
After this PR, we can now print types with param-enum fields more cleanly. Rather than ``R(mod.colors@0)`` we simply print, e.g., ``R(green)``.
Testing:
=> Dyno: Implement param enum-to-string casts and fix param enum stringify

runtime/src/comm/ofi/comm-ofi.c
According the "Limitations" section of the `fi_efa` man page, inject is not supported. However, `fi_getinfo` returns a non-zero `inject_size`. Set it to zero to prevent injection.
Resolves https://github.com/Cray/chapel-private/issues/6525.
=> EFA provider does not support injection.

compiler/resolution/expandVarArgs.cpp, modules/standard/IO.chpl, test/functions/constVarargs.chpl, test/functions/constVarargs.good, test/functions/constVarargsQuery.chpl, test/functions/constVarargsQuery.good
Resolves #25858 
When expanding a varargs function, we were accidentally dropping the constness of the argument on the floor.  Rectify that mistake.
Fix a varargs function in the IO module that was taking advantage of this bug by making the function it calls with the contents of the varargs also accept a const.
Adds two tests of this bug, covering queried and non-queried sizes for the varargs.
=> Fix a bug with varargs and const checking

frontend/include/chpl/types/CompositeType.h, frontend/lib/resolution/InitResolver.cpp, frontend/test/resolution/testInitSemantics.cpp
This prevented Dyno from resolving method calls on class types that are generic only by virtue of inheriting from a generic parent.
Fixed by relaxing the guard on setting `instantiatedFrom` in `ctFromSubs` to also allow it for class types with a generic parent. Along with this, relax the assertion in the `CompositeType` constructor requires no `instantiatedFrom` with empty substitutions, to not be enforced on class types.
Includes adding test coverage of the fixed case.
Resolves https://github.com/Cray/chapel-private/issues/6672.
Testing:
=> Fix missing `instantiatedFrom` on generic-inheriting class types

test/optimizations/deadCodeElimination/elliot/countDeadModules.good
Jade also incremented this number for an unrelated reason in 0e429a932a6e1d72205921d018255b89c216b544 and Git thought we meant to change the code the same way. We didn't; we needed two increments.
=> Fix incremented module count.

runtime/src/gpu/amd/gpu-amd.c
You can't query the PCI domain on ROCm < 5.0.0, so assume it's zero.
=> ROCm < 5.0.0 doesn't support PCI domain attribute

frontend/include/chpl/framework/Context-detail.h, frontend/lib/framework/Context.cpp
@mppf observed that a disproportionate amount of time is being spent finding errors to add into the error collection vector when tracking is enabled. The thing is that most graph nodes don't have any errors to speak of, so the traversals are redundant. This PR adds a simple transitive counter that detects how many errors have occurred. This helps avoid traversing the query graph, and saves most of the overhead that Michael was seeing originally.
=> Avoid redundant query graph traversals when tracking errors

util/cron/create_release_aptrpm.bash, util/packaging/common/build_helpers.sh, util/packaging/common/test_package.py
Forces the packaging builds to exit with an error if an error occurs in one of the invoked scripts.
This also adds a missing flag to the test package script.
=> Force a build script error when a subcommand fails in packaging builds

modules/packages/SortedMap.chpl, modules/standard/Sort.chpl, test/deprecated/Sort/internalCompare.chpl, test/deprecated/Sort/internalCompare.good, test/library/packages/SortedSet/partialGenericFieldWorkaround.chpl
Adds a deprecation warning to `chpl_compare` for deprecated usages of comparators. While this is technically an internal function and as such shouldn't need deprecations, it is used by other Chapel standard modules and by some users, so this PR gives a warning instead of code potentially breaking down the road.
=> Add deprecation warning to `chpl_compare`

test/unstable/sortModule.chpl
Changes a test for unstable warnings to avoid https://github.com/chapel-lang/chapel/issues/25885
=> Workaround asan bug with generic type names

util/chplenv/chpl_home_utils.py, util/chplenv/printchplbuilds.py
Fixes an issue where `chpl --print-chpl-settings` and `printchplenv` would give very different output in a prefix-based install.
This PR uses a heuristic to determine if Chapel is in a prefix-based install.
- if CHPL_HOME has a `frontend` and `doc` directory, its a from-source build
- if its not a from source build and CHPL_HOME has a `bin` and `lib` directory, its a CHPL_HOME install
- otherwise, its a prefix install. The actual path is also sanity checked that it ends with`share/chapel/VERMAJOR.VERMINOR`
Resolves https://github.com/chapel-lang/chapel/issues/25874
Tested by confirming that everything still works as expected in a from-source/CHPL_HOME-based build and that a prefix install is now correct.
=> Fix printchplenv and printchplbuilds when installed with a prefix

frontend/lib/resolution/scope-queries.cpp
Follow-up to #25853. This PR avoids errors from GCC 13 when building with `make DEBUG=0 WARNINGS=1 ASSERTS=0 OPTIMIZE=1 compiler`. The warnings look like this:
```
/usr/include/c++/13/bits/stl_algobase.h:437:30: error: ‘void* __builtin_memmove(void*, const void*, long unsigned int)’ forming offset 40 is out of the bounds [0, 40] of object ‘<anonymous>’ with type ‘chpl::resolution::MatchingIdsWithName’ [-Werror=array-bounds=]
437 |             __builtin_memmove(__result, __first, sizeof(_Tp) * _Num);
|             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mppf/w/main/frontend/lib/resolution/scope-queries.cpp: In function ‘const bool& chpl::resolution::emitMultipleDefinedSymbolErrorsQuery(chpl::Context*, const Scope*)’: …
```
=> Work around a GCC 13 error

test/library/standard/Sort/errors/sortDomainArray.assoc7.good, test/library/standard/Sort/errors/sortDomainArray.chpl
Captures the result of `sorted` in a dummy variable to avoid memory leaks due to https://github.com/chapel-lang/chapel/issues/25893
Tested that `start_test test/library/standard/Sort/errors/sortDomainArray.chpl --memLeaks` passes
=> Workaround memory leak bug in sort test

frontend/include/chpl/parsing/parsing-queries.h, frontend/lib/parsing/parsing-queries.cpp, test/visibility/submodule-in-file/Recursive.chpl, test/visibility/submodule-in-file/Recursive/SubModule.chpl, test/visibility/submodule-in-file/test-Recursive.chpl, test/visibility/submodule-in-file/test-Recursive.good
Resolves #25569
This PR fixes a problem with using `import super.something` from within a submodule that was stored in a different file using `include module`.
=> Fix error with certain `include module` patterns

test/unstableAnonScript/specialCases/search1.notest, test/unstableAnonScript/specialCases/search1/MyModule.chpl, test/unstableAnonScript/specialCases/search2.notest, test/unstableAnonScript/specialCases/search2/MyModule.chpl, test/unstableAnonScript/specialCases/unstable-module-ambiguity.chpl, test/unstableAnonScript/specialCases/unstable-module-ambiguity.compopts, test/unstableAnonScript/specialCases/unstable-module-ambiguity.good, tools/unstableWarningAnonymizer/unstableAnonScript.chpl
This adds a few things to the unstable warning anonymizer script in order to update it for the 2.2 release.
- Add handling for a warning starting with the word `<command line>`: previously, we were assuming that a warning either starts with a Chapel file name (like `foo.chpl`) or with `<command-line arg>` but a new unstable warning was added this release which starts with `<command line>` and it also doesn't have a number following it (the other two have numbers following them which indicate a line number of argument number)
- Add special case handling for the ambiguous modules warning (which is what also required the change from the 1st bullet) since it exposes implementation details (module names), we scrub these names now.
- Add testing for the special case
=> Unstable anon script for 2.2: special case & <command line>

compiler/passes/convert-uast.cpp
This PR makes two tiny changes to convert-uast.cpp:
1. It removes an unused function that is local to this file.
2. It switches from using a query to decide if scope resolution should be attempted to checking the current `modTag`. (Note: we are currently using `MOD_STANDARD` for package modules, and as a result, only `MOD_USER` code is not in a bundled module. See also this code that sets `modTag` https://github.com/chapel-lang/chapel/blob/08f4df28ccbc1428b35d1b96b3cbe79fb997947e/compiler/passes/parseAndConvert.cpp#L299-L309
No behavior changes in this PR.
=> Two tiny cleanups to convert-uast

compiler/optimizations/gpuTransforms.cpp, test/gpu/native/basics/itersPerThread.chpl, test/gpu/native/basics/itersPerThread.good
This fixes a bug introduced in #25855 where the attribute `@gpu.itersPerThread` was ignored when calculating the number of threads used to set up a GPU kernel. The number of threads is calculated correctly now.
Testing:
=> Fix gpu num threads

compiler/AST/AggregateType.cpp, compiler/AST/AstDump.cpp, compiler/include/AstDump.h, test/constrained-generics/basic/set3/interface-in-proc.chpl, test/constrained-generics/basic/set3/scoped-use-interface.chpl
Fixes an issue where `record R: I` was not being correctly resolved, due to an issue with how the `ImplementsStmt` AST node was being created.
Resolves https://github.com/chapel-lang/chapel/issues/25838 and https://github.com/chapel-lang/chapel/issues/25911
=> Fix scoping for interfaces inside of functions

test/studies/champs/sub_test
CHAMPS uses `CHPL_TARGET_COMPILER` to set the actual backend. To my surprise, it runs with `CHPL_LLVM=system` even with the C backend. I am not sure if it has any implications. In any case, this PR adjusts the recent fix to skip a problematic example to use the correct environment variable.
=> Use the correct environment to detect the backend in CHAMPS testing

util/chplenv/chpl_gpu.py
1. Suggested by @mppf, this PR adds `Try setting CHPL_CUDA_PATH to the cuda installation path` to the error message. Before, `CHPL_CUDA_PATH` was not mentioned in the error message.
2. The error says "nvidia toolkit" or "amd toolkit". Those are not real things. We need "cuda toolkit" or "rocm toolkit". This PR adjusts for that. Capitalizations are still not perfect, but I don't want to wire a new variable in on these scripts at this point.
Tested on a system with no GPUs that:
```
> export CHPL_GPU=nvidia
> printchplenv
Error: Can't find cuda toolkit. Try setting CHPL_CUDA_PATH to the cuda installation path. To avoid this issue, you can have GPU code run on the CPU by setting 'CHPL_GPU=cpu'. To turn this error into a warning set CHPLENV_GPU_REQ_ERRS_AS_WARNINGS.
> export CHPL_GPU=amd
> …
```
=> Improve "Can't find nvidia/amd toolkit" error

runtime/src/comm/ofi/README.md, runtime/src/comm/ofi/comm-ofi.c
This reverts commit 9575c8567aa72e65af46f7c6364c76f1a11f4981.
`FI_ORDER_RMA_WAW` is not required in message-order-fence because the compiler does not issue non-blocking PUTs, and even it if did `chpl_comm_put_nb` is currently implemented using blocking PUTs. So there is no opportunity for PUTs by a single task to be re-ordered.
=> Revert "Require FI_ORDER_RMA_WAW with message-order-fence MCM"

doc/rst/usingchapel/chplenv.rst, util/chplenv/chpl_llvm.py
This PR adds `CHPL_LLVM_GCC_INSTALL_DIR` as an alternative to `CHPL_LLVM_GCC_PREFIX`.
This PR is motivated by the discussion in https://chapel.discourse.group/t/cannot-make-gpu-enabled-chapel/37046/12 .
`CHPL_LLVM_GCC_PREFIX` allows one to select a GCC installation. The trouble is, on some systems (E.g. Ubuntu 24.04), there can be multiple versions of GCC installed at the same time, with the same prefix (`/usr` in this case).
`clang` actually supports `--gcc-install-dir` as of `clang` 16. That flag can be used to request a particular version of GCC on Ubuntu.
To understand what one might want to include:
* run `clang++ -v hello.cc` where `hello.cc` might just contain `int main() { return 0; }`
* you can see the GCC installations it considers at the beginning, e.g.
```
Found candidate GCC …
```
=> Add CHPL_LLVM_GCC_INSTALL_DIR as an alternative to CHPL_LLVM_GCC_PREFIX

runtime/src/comm/ofi/README.md, runtime/src/comm/ofi/comm-ofi.c
The Cassini-1 NIC does not support `FI_DELIVERY_COMPLETE` and specifying it can cause hangs. See Cray/chapel-private#1661 and Cray/chapel-private#6677 for details.
=> Remove FI_DELIVERY_COMPLETE in message-order-fence mode

compiler/resolution/addAutoDestroyCalls.cpp, test/errhandling/stmt-try-memory-leak.chpl, test/errhandling/stmt-try-memory-leak.compopts, test/errhandling/stmt-try-memory-leak.good
Closes https://github.com/chapel-lang/chapel/issues/25548, in which `try! whatever()` caused the result of `whatever()` to not be cleaned up, even if no exception occurred.
To see why this happens, consider the following (simplified) code desugaring `try! expr`:
```Chapel
var x1 = ... 
var x2 = ...
var x3 = ...
if (error) {
goto error handling;
}
```
`x3 = …` is presumably the call that creates the error, so `x3` may be uninitialized at the time we do `if (error)`. When traversing this code linearly and inserting autodestroys, to avoid processing `x3` (which may be uninit'ed), we go right into the `if (error)` just before we visit `x3` (going out of order). This way, when we insert auto-destroys for error handling (which happens to auto-destroy all variables in scope, since we are …
=> Ensure variable declarations at the end of try blocks are cleaned up

compiler/llvm/clangUtil.cpp, runtime/src/gpu/nvidia/Makefile.share
This PR suppresses some warnings coming from CUB 11. We discovered these when on one of the test machines was upgraded from clang 14 to 18. I am not sure at which clang version we start to see the warnings in question. So, the changes do not check for the clang version. It'd be great if we could check for the CUDA version, but unfortunately that's not wired in right now.
Test:
=> Adjust flags to suppress/disable warnings from CUB 11 with newer Clangs

util/cron/test-perf.hpe-cray-ex-ofi.1node.bash, util/cron/test-perf.hpe-cray-ex.ofi.1node.bash, util/cron/test-perf.hpe-cray-ex.ofi.bash
Our currently nightly EX perf testing isn't passing -perflabel ml so even though we call it a "16 node" job, in actuality it's only running our single locale tests.
This PR fixes this so the job passes the perf label and we have another 1-node ex perf test.
=> separate 1-node and 16-node ex perf jobs

runtime/src/gpu/amd/gpu-amd.c
The variable in question slipped by as a copy/paste leftover from the NVIDIA implementation. This PR removes the variable.
Test:
=> Remove an unused variable in the runtime causing errors

util/build_configs/cray-internal/setenv-hpe-cray-ex-x86_64.bash
The `cce` module appears to cause a problem when used with the `PrgEnv-gnu` and `libfabric` modules loaded, as the `hwloc` configuration fails because` -lfabric` is not found. Unload the `cce` module prior to loading the `PrgEnv-gnu`  module and let it reload `cce` should it want to, but this way `cce` isn't loaded if `PrgEnv-gnu` doesn't need it.
=> Unload cce prior to loading PrgEnv-gnu

runtime/src/gpu/nvidia/Makefile.share
https://github.com/chapel-lang/chapel/pull/25918 added `-Wno-error=deprecated-builtins` when compiling the runtime's CUB wrappers. However, that flag is not supported in some older clangs. Specifically, we added that to enable builds with clang 18, but clang 14 doesn't have that flag. This PR adds the problematic flag only if the clang version supports it.
Test:
=> Be more selective in terms of clang version when using a flag in CUB compilation

compiler/optimizations/forallOptimizations.cpp, test/optimizations/autoLocalAccess/blockWithOffset.chpl, test/optimizations/autoLocalAccess/blockWithOffset.compopts, test/optimizations/autoLocalAccess/blockWithOffset.good, test/optimizations/autoLocalAccess/blockWithOffset.prediff
This PR makes sure that ALA is applicable for:
```chpl
var A = blockDist.createArray(...)
const InnerDomain = A.domain.expand(-1);
forall i in InnerDomain {
A[i] = A[i-1];
}
```
Things of note:
- this is a dynamically optimized loop, because the compiler can't statically determine that `InnerDomain` and `A.domain` are aligned.
- the body contains both regular (`A[i]`) and offset (`A[i-1]`) access, where the latter is not optimizable for a block-distributed array
The problem is, https://github.com/chapel-lang/chapel/pull/25712 modified the dynamic checks in scenarios like this. After that PR, the generated optimization looked like
```chpl
param staticRegularFlag = alaStaticallySupported(A);  // added for A[i] (true)
param staticOffsetFlag = alaOffsetStaticallySupported(A);  // added for …
```
=> Prevent offset access with block arrays to thwart dynamic ALA

compiler/AST/AggregateType.cpp, compiler/AST/interfaces.cpp, compiler/include/stmt.h, test/constrained-generics/basic/qualified-interface-constraint.chpl
Closes https://github.com/chapel-lang/chapel/issues/25829.
Strangely, even though we have an `isym` when building the class hierarchy, I chose to use the symbol's name to construct an `implements` statement. This works when the name is available in scope without qualification, but not when qualified access is used. The principled solution is to allow interface statements to be constructed using a known interface symbol. This PR does that, and switches the class hierarchy logic to avoid using a name.
=> Add support for qualified interface access

doc/rst/language/spec/methods.rst
This PR updates the language specification to describe the implicit `this.` that the compiler adds within methods. It also discusses how shadowing works in such cases.
Follow-up to PR #25878.
=> Add a description of implicit 'this.' to methods section

doc/rst/language/spec/modules.rst, doc/rst/language/spec/statements.rst
This PR adds documentation to the language specification about the module search path & describes how it is used to find a top-level module for something like `use MyModule;`.
Follow-up to PR #25421.
=> Add docs about module search path / finding toplevel modules

man/chpl.rst
We used to require docs/latest to get to the latest docs online, but haven't for some time, and prefer using the non-latest/ URLs from the perspectives of simplicity and SEO.
[I've got updates to other files in another branch, but those are in code / not user-facing, so I'm saving those until after 2.2]
=> Change docs/latest/ to docs/ in man page

doc/rst/platforms/udp.rst
Prior to this commit, the recommended environment setting to silence ssh login banners set `GASNET_SSH_OPTIONS` to a value which discarded the `-x` recommended earlier to disable X11 forwarding.  So, this commit updates the recommendation in a way that retains the `-x`.
=> Preserve -x with "-o LogLevel=Error"

test/ANNOTATIONS.yaml
- moved qthreads update/patch annotations to apply to all chapcs graphs (since they seem to impact a slew of graphs and not just the 2 I previously had annotated).
- annotation for "Avoid array allocation for moving to equal domain" to "array return performance" graph
- annotation for AVE to apply to miniMD graph
- annotation for AVE on "2D Heat Solver" graph
- annotation for "Stencil Distribution performance improvments" to NPB MG Time Size B
=> annotations for release-over-release 2.2 triage

doc/rst/platforms/macosx.rst, doc/rst/platforms/windows.rst
Adds to the WSL documentation by explaining two main ways to get Chapel on WSL. The change also includes the commands to get WSL installed and an example that shows the commands to install Chapel with the package management system in Ubuntu.
=> update WSL docs with example installation

doc/rst/tools/chplcheck/chplcheck.rst
Add documentation for `@fixit` decorator in `chplcheck`. This feature was introduced by https://github.com/chapel-lang/chapel/pull/25399.
=> Add documentation for `@fixit` decorator

CMakeLists.txt, doc/rst/conf.py, doc/rst/language/archivedSpecs.rst, doc/rst/usingchapel/QUICKSTART.rst, doc/rst/usingchapel/chplenv.rst, man/confchpl.rst, man/confchpldoc.rst, test/chpldoc/compflags/combinations/versionhelp-chpldoc.sh, test/compflags/bradc/printstuff/versionhelp.sh
This PR updates the Chapel tree for the official 2.2 release by updating
the official release flag and documentation variables.
PR from previous release:   https://github.com/chapel-lang/chapel/pull/25324
Test results for version checks: 
`[Test Summary - 240917.224756]
[Summary: #Successes = 10 | #Failures = 0 | #Futures = 0 | #Warnings = 0 ]
[Summary: #Passing Suppressions = 0 | #Passing Futures = 0 ]
`
=>  Version number update for 2.2 release

doc/rst/technotes/gpu.rst
Some changes to call out here:
- More confident tone, where Intel limitation is removed from the first paragraph and replaced with a link to the blog series
- Replacing the focus on `foreach`/`forall` with order-independent statements to cover promotion and reduction
- Highlight `reduce` expressions more than the standalone functions
- Massaging the language around ROCm 6 and LLVM versions
=> GPU technote updates for 2.2

doc/rst/technotes/gpu.rst
This documents and makes use of the various changes I made in https://github.com/chapel-lang/chapel/pull/25826, https://github.com/chapel-lang/sphinxcontrib-chapeldomain/pull/97, and https://github.com/chapel-lang/chapel/pull/25884.
=> Update GPU attribute documentation

CMakeLists.txt, man/confchpl.rst, man/confchpldoc.rst, test/chpldoc/compflags/combinations/versionhelp-chpldoc.sh, test/compflags/bradc/printstuff/version.goodstart, test/compflags/bradc/printstuff/versionhelp.sh
This is the follow up review to
https://github.com/chapel-lang/chapel/pull/25957.
Test results: 
`[Done with tests - 240923.213451]
[Log file: /Users/tzinsky/Source/chapel/test/Logs/tzinsky.darwin.log ]
[Test Summary - 240923.213451]
[Summary: #Successes = 10 | #Failures = 0 | #Futures = 0 | #Warnings = 0 ]
[Summary: #Passing Suppressions = 0 | #Passing Futures = 0 ]
[END]`
=> Update version numbers to 2.3 pre-release

LICENSE
While reviewing some of our third-party licenses, I happened to notice that the copy of LLVM we redistribute is actually Apache 2.0 licensed, meaning our file was out of date.
The last release with UIUC license was LLVM 8 although some later releases have legacy licenses with UIUC.
The license was changed to Apache License v2.0 with LLVM Exceptions in llvm-project commit 469bdefd448b76c5adcdd67256e9a44fabf7e027 in Jan 2019.
Docs https://llvm.org/docs/DeveloperPolicy.html#legacy indicate some of LLVM still uses the old license but as far as we know, nothing that Chapel uses falls into that category.
=> Update LLVM's license to Apache 2.0

frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testClasses.cpp
Enable dyno to type resolve usages of dependently-typed class fields, used within methods.
This wasn't working due to the method receiver type being left generic during instantiation. Fixed by using the actual `BasicClassType` to instantiate the formal when it's generic.
Resolves https://github.com/Cray/chapel-private/issues/6690.
Testing:
=> Fix dyno resolving dependently-typed fields in method

doc/rst/platforms/aws.rst
Update the AWS docs to suggest to users that they use binary distributions when they are available.
Also restructured the docs to separate buildtime env vars and runtime env vars
=> Update AWS docs to suggest binary distributions

tools/chplcheck/src/rule_types.py, tools/chplcheck/src/rules.py
Improves the location reporting for ControlFlowParentheses to only report the location for the condition, not the full body.
=> Improve location reporting for ControlFlowParentheses

compiler/main/driver.cpp, test/chplenv/printchplenv/print-chpl-settings.chpl, test/chplenv/printchplenv/print-chpl-settings.cleanfiles, test/chplenv/printchplenv/print-chpl-settings.compopts, test/chplenv/printchplenv/print-chpl-settings.precomp, test/chplenv/printchplenv/print-chpl-settings.prediff
Fixes an issue where Chapel environment variables were not printed right with `--print-chpl-settings` when set via the commandline.
Resolves https://github.com/chapel-lang/chapel/issues/25958.
Also renames `setEnv` to `setChplEnv` to avoid confusion.
Added test of new feature and made sure the test passes.
=> Fix printing of Chapel enviroment variables with `--print-chpl-settings`

frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testInitSemantics.cpp, frontend/test/resolution/testResolve.cpp
Fix a bug preventing dyno from resolving unqualified uses of `type` fields or parenless procs in method signatures.
Resolved by setting `Resolver::inCompositeType` in more cases where it appears to have been accidentally omitted, and by delaying resolution of parenless procs on generic receivers until later when they are instantiated.
Also adds dyno tests for the fixed cases.
Note this PR includes one incidental test change in `testInitSemantics`, due to now resolving an incompletely-specified generic type's generic field as `UnknownType` rather than `AnyType`. I believe this is equally or more correct as the generic type is not initialized properly and in fact errors on initialization.
Resolves https://github.com/Cray/chapel-private/issues/6689.
Testing:
=> Fix dyno resolving `type` fields in method signatures

frontend/lib/resolution/Resolver.cpp, frontend/test/resolution/testMethodCalls.cpp
Fix a bug preventing Dyno resolving parenless method calls from within a param for loop in a method.
Fixed by adjusting receiver scope info calculation in the param loop child resolver to defer to (and trigger calculation of) the parent's results.
Resolves https://github.com/Cray/chapel-private/issues/6718.
Testing:
=> Enable using receiver scope info in param loop resolution

modules/standard/IO.chpl, test/deprecated/IO/offsetWithLocking.chpl, test/deprecated/IO/offsetWithLocking.compopts, test/deprecated/IO/offsetWithLocking.good
Removes the transitional config `fileOffsetWithoutLocking`, which has been unused and deprecated for a few releases now.
=> Remove the unused and deprecated config `fileOffsetWithoutLocking`

modules/internal/DefaultRectangular.chpl
Remove a workaround for `ref`-intent issue with `_distribution`s that does not appear to exist anymore.
This workaround was implemented 9 years ago in https://github.com/chapel-lang/chapel/commit/3e1a5a339981ce803eedb622e0a76563366a889c (part of https://github.com/chapel-lang/chapel/pull/2178).
Testing:
=> Remove outdated `chpl_defaultDistInitPrivate` workaround

runtime/src/comm/ofi/comm-ofi.c
Added missing `tciFree` to `chpl_comm_ensure_progress`.
=> Add missing tciFree

util/cron/test-docker.bash
Build `linux/amd64` platform image in addition to system default `linux/arm64` in the nightly Docker test script.
In addition to improving test coverage, this will cause our `nightly` image tag to be multi-arch going forward.
To be merged after https://github.hpe.com/hpe/hpc-chapel-ci-config/pull/1280 adjusts this job to run on our test machine that supports multi-arch build.
Implements https://github.com/Cray/chapel-private/issues/6563.
Testing:
=> Build multiarch image in test-docker.bash

test/chplcheck/UnusedFormalBug.bad, test/chplcheck/UnusedFormalBug.chpl, test/chplcheck/UnusedFormalBug.future
Retire the future `test/chplcheck/UnusedFormalBug.chpl` which now passes.
The underlying bug was fixed in https://github.com/chapel-lang/chapel/pull/25954.
Testing:
=> Retire passing `chplcheck` `UnusedFormalBug` future

compiler/include/convert-uast.h
This PR fixes a compilation failure for frontend/ when compiling with clang.
Follow-up to PR #25946.
=> Fix a class/struct mismatch causing build failure on clang

doc/rst/language/spec/expressions.rst
The language spec section on precedence includes conflicting statements that 'We were tempted to diverge from the C precedence rules for the binary bitwise operators ... However, ... we felt it unwise to stray from the pack.' and 'In contrast to C, we give bitwise operations a higher precedence than binary addition/subtraction and comparison operators.'
The second statement is correct; Chapel does indeed stray from the pack by using a different precedence order than C. This commit aims to clarify the situation.
=> lang spec: clarify precedence of binary bitwise ops

doc/rst/usingchapel/building.rst, doc/rst/usingchapel/chplenv.rst
Clarifies chplconfig and its relationship with `./configure` and `make install`.
Resolves the remaining concerns from https://github.com/chapel-lang/chapel/issues/14932 
=> Clairfy docs regarding installed chapel and chplconfig

test/ANNOTATIONS.yaml
This adds the folllowing annotations to the stencil 2d graph (would be nice to put in release notes):
- https://github.com/chapel-lang/chapel/pull/25712 went in on 8/13 which caused the StencilDist line to meet the StencilDist_localAccess line
- https://github.com/chapel-lang/chapel/pull/25701 went in on 8/19 which improved the performance of both StencilDist versions
- https://github.com/chapel-lang/chapel/pull/25933 when in on 9/11, fixing the slight performance regression in the BlockDist version
=> add annotations for stencil 2d graph

frontend/lib/resolution/disambiguation.cpp
This addresses a bug in the dyno disambiguation mechanism that was comparing `QualifiedType`s (including the `kind`) instead of just `Type`s without the kind. 
I discovered this while trying to implement the `_owned` to `owned` mapping, where choices were being ignored because one was `const ref` and one was `ref`.
Talking with @mppf, it seems like we should probably not be making that comparison including the kind in `testArgMapping`. 
=> Fix disambiguation bug in dyno resolver

test/library/packages/ConcurrentMap.skipif, test/library/packages/EpochManager.skipif
Restores skipifs removed in https://github.com/chapel-lang/chapel/pull/25928, only 1 line from the skipif should have been removed
=> Restore skipif for ConcurrentMap and EpochManager

Makefile, doc/rst/tools/chplcheck/chplcheck.rst, test/chplcheck/PREDIFF, test/chplcheck/Unused.chpl, test/chplcheck/allrules.good, test/chplcheck/fixit-interactive/PREDIFF, tools/chplcheck/src/rules.py
Enables the UnusedFormal linter rule by default, which was turned off due to confusing bugs.
@riftEmber resolved the known bugs with this rule in https://github.com/chapel-lang/chapel/pull/25954, so this rule can be reenabled by default. 
=> Enable UnusedFormal linter rule by default

frontend/lib/resolution/InitResolver.cpp, frontend/lib/resolution/InitResolver.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/resolution-types.cpp, frontend/test/resolution/testInitSemantics.cpp
This PR improves support for initializers on classes that inherit. With this commit dyno now supports:
- implicit 'super.init' calls
- errors for accessing parent fields before 'super.init'
- usage of initialized fields part-way through initializing the whole type
This PR updates the Resolver to rely somewhat less on 'InitResolver' for explicitly handling ``Identifier`` and ``Dot`` uAST nodes. Instead we continue to rely on established Resolver mechanisms and selectively invoke the ``InitResolver`` when appropriate.
This PR also improves a fix within 'handleCallExpr' originally meant to support receiver-less 'init' calls. Instead, this fix is adapted to any 'init' call within an initializer, and will replace or create the receiver using a fully-generic type. This is done in case the user …
=> Dyno: Improve initializers on classes that inherit

test/ANNOTATIONS.yaml
This PR adds an annotation to a couple of the Arkouda graphs.
(noted by @jeremiah-corrado): For the sorting tests, the historical behavior was buggy (i.e., for real-valued arrays we were completely ignoring the algorithm argument and always used the LSD algorithm). After https://github.com/Bears-R-Us/arkouda/pull/3602 (merged on 8/7), we are now using the algorithm argument, so the LSD and MSD lines have different performance.
=> add annotation that impacted algorithm used in Akrouda sort tests

util/packaging/homebrew/chapel-release.rb
This updates the formula we use to detect changes in homebrew's chapel formual on the `master` branch. This was needed because they release new bottles for sequoia OS and also because LLVM was updated to 19 and so they pinned us to 18.
Trivial formula change only used for testing, not reviewed.
=> update homebrew formula to match released ver

util/packaging/homebrew/chapel-main.rb
This updates the homebrew formula we use to test main against. Homebrew's default LLVM package was recently updated to 19 and we don't yet support it, so this pins our dep to 18. 
This is a trivial change to our testing formula only, not reviewed.
=> update chapel-main homebrew formula for 2.3

util/packaging/homebrew/chapel-release.rb
This updates the homebrew release formula that we capture to catch changes to the published formula. The update matches our version to the version for 2.2 recently released in Homebrew.
trivial test file change only, not reviewed
=> update homebrew release formula to match release version

util/cron/nightly, util/cron/test-darwin.bash, util/cron/test-linux64-clang.bash, util/cron/test-linux64-gcc112.bash, util/cron/test-linux64-llvm16.bash
This adds blog testing to nightly correctness tests on `linux64-clang`, `linux64-gcc112`, `linux64-llvm16`, and `darwin` configs. It has a required CI companion PR https://github.hpe.com/hpe/hpc-chapel-ci-config/pull/1271 that enables cloning of the chapel-blog repo in these configs. 
=> Test blog in a few correctness configs

test/gpu/native/studies/chai/SKIPIF
Skip ChAI testing on AMD GPUs for now. One of ChAI's tests is failing on AMD with an esoteric error message — this needs to be investigated and fixed before AMD testing can be re-enabled.
=> skip ChAI testing on AMD

util/cron/create_release_aptrpm.bash
Fixes inverted logic in a bash script which resulted in the wrong branch being taken
=> Fix inverted logic in bash script

frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/return-type-inference.cpp, frontend/test/resolution/testResolve.cpp
This PR fixes bugs that were causing test failures in `chpl-language-server`.
Make sure to skip resolving function bodies in `resolveFunction` if the function does not have one (e.g., for `extern` functions).
If `typedSignatureInitial` is called on a nested function and parent frames are not present, emit a warning and continue if the parent(s) are generic instead of returning `nullptr`. Future work should make `typedSignatureInitial` take the parent function signature instead.
TESTING
=> dyno: Fix bugs that were breaking chpl-language-server tests

util/packaging/homebrew/chapel-release.rb
This updates our homebrew tracking test formula to match the formula on homebrew/homebrew-core:master
changes to Homebrew from https://github.com/Homebrew/homebrew-core/commit/25cb91a7f7079a40738d06bd6919466e5ad3f939
and https://github.com/Homebrew/homebrew-core/commit/43e8218f26762e28bb8ecbcbd3bb53d191389562
This is a trivial change to fix a failing test, not reviewed
=> update chapel-release.rb to match upstream Homebrew formula

frontend/lib/resolution/Resolver.cpp, frontend/test/resolution/testTuples.cpp
Closes https://github.com/Cray/chapel-private/issues/6385; prior to this PR, the following program:
```Chapel
var x: 2*int = (7,3);
```
Produced an error:
```
─── error in onetuple.chpl:1 [IncompatibleTypeAndInit] ───
Type mismatch between declared type of 'x' and initialization expression.
In the following declaration:
|
1 | var x: 2*int = (7,3);
|        ⎺⎺⎺⎺⎺   ⎺⎺⎺⎺⎺
|
the type specifier has type '(int(64), int(64))', while the initial value has type '(int(64), int(64))'.
```
The (chapel syntax) output is quite confusing in the error message, but the difference between the specified type and the actual type are the intents of the components. On the left hand site we have a 'type' tuple, but on the right we have a value tuple.
There is already logic on `main` to adjust the type of the …
=> Dyno: fix decls with tuple type expressions and initialization expressions

util/chplenv/third_party_utils.py
Tightens up the logic for when we should warn about 'Requires.private' (and also 'Requires'). We only need to warn when the compiler/linker flags are not already handled by 'Cflags'/`Libs`.
Details:
`Requires`/`Requires.private` list what other pkg-config libraries are needed, so that `pkg-config` can pull in the need dependencies/flags. This ends up being a recursive operation (i.e. 'A' has 'Requires: B', so we must process 'B.pc'). But if we already have the information needed, this is unnecessary. So if we have 'Requires: B', but 'B' is already listed in 'Libs', then for our purposes we have satisfied the 'Requires.'
Our simple pkg-config parser is used only for bundled third-party libs, and we do not need to ability to recursively search other .pc files to satisfy the requirements. So …
=> Tighten warning for 'Requires.private' in simple pkg-config parser

util/packaging/common/test_package.py, util/packaging/rpm/amzn2023-gasnet-udp/Dockerfile.template, util/packaging/rpm/amzn2023-gasnet-udp/spec.template, util/packaging/rpm/amzn2023-ofi-slurm/Dockerfile.template, util/packaging/rpm/amzn2023-ofi-slurm/spec.template, util/packaging/rpm/amzn2023/Dockerfile.template, util/packaging/rpm/amzn2023/spec.template, util/packaging/rpm/common/fill_docker_template.py, util/packaging/rpm/test/Dockerfile.template
Add new configs for AmazonLinux2023 for COMM=none, COMM=gasnet, COMM=ofi
Testing:
=> Add support for building AmazonLinux2023 OS packages

test/studies/shootout/binary-trees/binarytrees-pool.chpl, test/studies/shootout/binary-trees/binarytrees-pool.execenv
Tweak `binarytrees-pool` based on feedback. Many of the changes are cosmetic (changing how constants are written) and others improve the portability (making sure enough memory is available when running with limited cores) 
=> Tweak `binarytrees-pool` based on feedback

modules/internal/ChapelLocale.chpl, modules/internal/localeModels/gpu/LocaleModel.chpl, test/gpu/native/multiGPU/gpuId.chpl, test/gpu/native/multiLocale/gpuId.chpl, test/gpu/nongpu/gpuId.chpl, test/gpu/nongpu/gpuId.good
This PR adds a way to query gpuID (the location in the parent locale's `here.gpus` array) that a gpu locale is.
If used on a non gpu locale it will error out with this message:
`Can not use 'gpuId' field on a non gpu locale`
This should resolve #23650
**TODO:**
=> Add gpuId proc on locale

frontend/lib/framework/ID.cpp, frontend/lib/parsing/parsing-queries.cpp, frontend/lib/resolution/InitResolver.cpp, frontend/lib/resolution/default-functions.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/test/resolution/testCanPass.cpp, frontend/test/resolution/testConstChecking.cpp, frontend/test/resolution/testCopyElision.cpp, frontend/test/resolution/testForwarding.cpp, frontend/test/resolution/testInitSemantics.cpp, frontend/test/resolution/testMaybeConst.cpp, frontend/test/resolution/testNew.cpp, frontend/test/resolution/testSplitInit.cpp
This PR changes the frontend to start generating uAST for default initializers, which allows us to support default initializers on classes that inherit. 
This PR replaces the current signature-based implementation for default initializers with uAST for a Function. This Function's body contains the suitable statements to initialize each field, as well as a "super.init" call if applicable. This code currently lacks suitable init-expressions for default-initializable formals, which is left as future work.
An UntypedFnSignature is built manually so that we can force resolution to accept non-existent default values for each formal, regardless of whether it has an init-expression or not.
The resulting TypedFnSignature is created with `typedSignatureInitial`. This might be overkill, but it keeps …
=> Dyno: Default initializers for classes that inherit

util/cron/nightly
This makes a minor change to the nightly script when testing the chapel-blog. Instead of testing from a directory external to `$CHPL_HOME`, now the relevant blog sub directories will be copied into `$CHPL_HOME/test/copied-chapel-blog/` so that reports on failures will not include the full path, which was exposing test machine directory structure.
TESTING:
=> use chapel-blog sources inside chapel/test

frontend/include/chpl/resolution/resolution-types.h, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/intents.cpp, frontend/lib/resolution/prims.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/resolution-types.cpp, frontend/test/resolution/testLoopIndexVars.cpp, frontend/test/resolution/testResolve.cpp, frontend/test/resolution/testResolverVerboseErrors.cpp, frontend/test/test-resolution.h
Closes https://github.com/Cray/chapel-private/issues/6720 by rolling in a minor fix (see 8320546803e3b3cba9e367991ed5a5bf60d4ef46)
This PR intends to address a longstanding concern with the leader/follower API design in which to use a parallel iterator, you need to define a serial iterator as well. Thus, you can't iterate over `foo()` if only `foo(standalone)` or `foo(leader)/foo(follower)` are defined. This PR implements this, detecting calls to iterators that were discarded only because of the `tag`/`followThis` arguments, and re-trying them with the tags in priority order.
The key observation is that the formal-actual map, when it's checking alignment, is actually very well positioned to determine if a call is valid with the exception of missing a `tag` argument: it iterates over all …
=> Dyno: resolve `foo()` to `foo(standalone)` if serial version of the iterator is not available.

test/studies/shootout/nbody/bradc/nbody-blc.chpl
A recent CLBG update kicked out our version of nbody that was both most compact and almost-best-performing, making our nbody#2 version the most compact, but a significant bit slower.  I'd been meaning to submit a modernized version using 'foreach' loops rather than 'for param' loops, so this updates my study version to be based on version 2, but using foreach loops.  I also took the approach of getting 'pi' from the math library rather than defining it manually.
=> Update my study version of nbody to be like nbody#2, but using foreach loops

frontend/include/chpl/framework/all-global-strings.h, frontend/lib/types/CompositeType.cpp, frontend/lib/types/Type.cpp, frontend/test/resolution/testLibrary.cpp
Updates CompositeType to use the leading-underscore version of string, bytes, and locale types so that they match the records declared in module code. The 'is[String|Bytes|Locale]Type' methods are updated to instead check the ID of the type, rather than the name. Lastly, stringify is updated to print the proper reserved names for these types.
Note: The 'locale' type is not tested here due to a pre-existing recursive query bug.
Testing:
=> Dyno: Fix method resolution on string and bytes types

util/cron/test-gpu-cuda.bash
This adds blog testing to a single correctness test for GPU builds, `cray-cs-gpu-correctness-test-gpu-cuda`
It requires a companion PR in CI config https://github.hpe.com/hpe/hpc-chapel-ci-config/pull/1287
=> add blog to gpu-cuda nightly config

util/cron/test-gpu-ex-cuda-11.bash
Since cudatoolkit is deprecated (and also 23.9 was not available anymore), this change switches to using the cuda/11.8 module instead.
Will fix nightly build failures.
=> Change the CUDA module loaded in CUDA 11 EX tests

test/mason/EXECENV, tools/mason/MasonEnv.chpl, tools/mason/MasonPublish.chpl
We've been experiencing some sporadic failures to get the license information for Mason's `--refresh-license` flag.  This is likely due to connection issues.
Adds an environment variable to mason called `MASON_LICENSE_CACHE_PATH` that when present will indicate that the specified cache location should be used for the license repository, if needed.  Updates the `EXECENV` for the tests that were having problems to conditionally set this new environment variable to `REPO_CACHE_PATH` when it is set, which we already use for other cached repos.
Passed a full paratest with futures, and verified that the test passed both with and without `REPO_CACHE_PATH` defined
=> Allow mason to use a license reference repo, to fix testing timeouts

compiler/util/astlocs.cpp, test/modules/vass/userInsteadOfStandard/foo2.good
Prevents error handling code from getting into a cycle of following mutually recursive functions.
Resolves https://github.com/chapel-lang/chapel/issues/26029
Testing:
=> Prevent infinite loop due to mutually recursive module init functions

tools/chapel-py/setup.py, util/config/run-in-venv-with-python-bindings.bash
Adjust build scripts s.t. `chapel-py` can be built when Chapel is configured for Address sanitization.
Note: this currently works only on Linux, as Mac OS has a limitation where `DYLD_INSERT_LIBRARIES` cannot be passed to a child process — which would be needed to specify the path for `libclang_rt.asan.so` to chapel-py's setup script.
Resolves: https://github.com/Cray/chapel-private/issues/6766
Testing:
---
`CHPL_SANITIZE=address`:
| host-cc \ platform | Linux | Mac |
| :--- | :--- | :--- | 
| clang | ✅ | ⚠️ |
| gcc | ✅ | ❓ |
`CHPL_SANITIZE=none`:
|  host-cc \ platform | Linux | Mac |
| :--- | :--- | :--- | 
| clang | ✅ | ✅ |
| gcc | ✅ | ❓ |
✅ = chapel-py builds and works successfully
❓ = couldn't build chpl in this config
⚠️ = fails gracefully
=> Fix chapel-py builds for ASAN config

util/config/run-in-venv-with-python-bindings.bash
Follow on to: https://github.com/chapel-lang/chapel/pull/26050 that adds some missing double braces to `chapel-py`'s run-in-venv script (forgot to add this last commit before merging).
=> Minor fix to `chapel-py`'s run-in-venv script

compiler/Makefile
Adjust the Dyno tests Makefile target to correctly use concurrency (as specified in `make` invocation) on macOS.
The problem was due to different syntax for capture groups and "or" on macOS `sed`. Fixed by adjusting the `sed` invocation to work on either macOS or GNU sed.
Getting a parallel run working also requires using GNU Make 4.x, which isn't the default on macOS -- see [backing issue](https://github.com/Cray/chapel-private/issues/6770).
Resolves https://github.com/Cray/chapel-private/issues/6770.
Testing:
=> Adjust `test-dyno` Makefile to allow parallel on macOS

compiler/passes/convert-uast.cpp, frontend/lib/resolution/Resolver.cpp, frontend/test/resolution/testMethodCalls.cpp, frontend/test/resolution/testNestedFunctions.cpp
Logic in ``resolveIdentifier`` was looking for ambiguity errors between
parenless methods and locally-declared variables, but was instead
issuing errors for paren-ful methods and nested functions as well.
This commit changes resolveIdentifier to only run these errors if a
parenless method is found and if there are redeclarations other than the
paren-less method.
``test15`` in ``testMethodCalls`` is temporarily retired as it is not
actually considered to be an ambiguity in production. This instead
appears to be a bug in which we incorrectly prefer the method over the
nested function.
Testing:
=> Dyno: Fix erroneous ambiguity error for nested functions

compiler/passes/convert-uast.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testMethodCalls.cpp
This moves us toward fully resolving the `sync` keyword to the `_syncvar` record type in dyno. Resolves https://github.com/Cray/chapel-private/issues/6741 and adds a dyno test to capture the fixed resolution issue.
TESTING:
```
chapel/compiler/passes/convert-uast.cpp:4709 in convertRecordType] Unimplemented: unhandled record type: _syncvar
> syncSpinWait.chpl:11: internal error: PAS-CON-AST-5193 chpl version 2.3.0 pre-release (90c1cfa153)
```
=> [dyno] map sync to _syncvar record

util/cron/nightly
This expands the cases when we add the blog directories to the list of directories to test. The change is to stop using the presence of `-examples` with `-blog` to selectively add the blog directories, and instead just add them whenever `-blog` is used and the `testdirs` var already has some values in it. It should avoid the problem found in GPU tests and other configs that just populate `CHPL_NIGHTLY_TEST_DIRS` rather than calling `nightly` with a specific set of flags.
=> add blog dirs to nightly testdirs more generally

util/packaging/homebrew/chapel-main.rb, util/packaging/homebrew/chapel-release.rb
This updates the stored homebrew formulas to match changes made to the released version by homebrew while they were adding python 3.13
this is a trivial change just to match the released Homebrew formula for testing purposes. not reviewed
=> Update homebrew formulas for release and main

util/chplenv/chpl_locale_model.py
It appears that we don't check the value of `CHPL_LOCALE_MODEL` in our environment scripts. I have no idea what we build if it was set to something invalid, but we build _something_. That's pretty bad. This PR adds an error message when `CHPL_LOCALE_MODEL` is set to something other than `flat` or `gpu`.
Tested locally with different settings including leaving it unset.
=> Add a config error for invalid locale model setting

util/cron/test-gpu-ex-cpu.bash, util/cron/test-gpu-ex-cuda-12.bash, util/cron/test-gpu-ex-cuda-12.interop.bash, util/cron/test-gpu-ex-cuda-12.specialization.bash, util/cron/test-perf.gpu-ex-cuda-12.bash, util/cron/test-perf.gpu-ex-cuda-12.um.bash
This adds the following new configurations scripts for testing gpus on HPE Cray EX systems:
- `test-gpu-ex-cpu` (analogous to `test-gpu-cpu` for Cray CS)
- `test-gpu-ex-cuda-12.interop` (analogous to `test-gpu-cuda.interop` for Cray CS)
- `test-gpu-ex-cuda-12.specialization` (analogous to `test-gpu-cuda.specialization` for Cray CS)
- `test-perf.gpu-ex-cuda-12.um` (analogous to `test-perf.gpu-cuda.um` for Cray CS)
=> Add new configs for gpu on hpe cray ex

test/ANNOTATIONS.yaml
- Mandelbrot complex regression
- update blc to use foreach (impacted perf)
- non-blocking put affecting ra-rmo perf on ofi
- mark that we've updated Chapel version used for Arkouda nightly testing
- Large arkouda refactor affecting bigint perf
=> annotations for 10/10/24

compiler/util/files.cpp
If `CHPL_LIB_PATH` has colons in it, we split the path based on the colons. However, if we have a trailing or leading colon, or two colons back to back (`::`) in CHPL_LIB_PATH, it get's added as an empty string. This cases errors since there isn't an argument to go with `-L` for the target compiler.
Ex:
```
clang++: error: argument to '-L' is missing (expected 1 value)
```
This makes the change such the the `addPath` function ignores the empty strings in CHPL_LIB_PATH.
Will resolve nightly test failures in `test-gpu-ex-cuda-12.interop`.
=> Make CHPL_LIB_PATH ignore empty strings

frontend/lib/resolution/Resolver.cpp
We run into these as part of resolving `IO.chpl` with types. After this PR, resolving `IO.chpl` still crashes, but with different errors.
=> fix assertions for non-(`chpl_t` or `chpl_p`) field type resolution on shared/owned

frontend/lib/resolution/InitResolver.cpp, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/default-functions.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testInitSemantics.cpp
This PR fixes an issue where super.init() calls were being generated
despite the lack of a parent class. This lead to resolution failures
when trying to resolve init on the root class.
This kind of error manifested itself when there was an interface in the
inherit-exprs list of the class. The 'initHelper' function was naively
ignoring the possibility of such expressions.
The bug is fixed by relying on ``initialTypeForTypeDecl`` to
compute the parent class rather than doing it manually inside
'initHelper'.
-----
While here, it was convenient to fix another super.init() related bug
when generating default initializers when a parent (or other ancestor
class) had a user-defined initializer. In such cases the compiler should
not be generating formals for classes that define their own …
=> Dyno: Improve super.init() calls in default initializers

third-party/chpl-venv/test-requirements.txt
pyyaml 6.0.2 release, https://github.com/yaml/pyyaml/releases/tag/6.0.2
relates to https://github.com/Homebrew/homebrew-core/pull/193881
=> chore: bump pyyaml to 6.0.2 to support py3.13 build

third-party/chpl-venv/c2chapel-requirements.txt, third-party/chpl-venv/chapel-py-requirements.txt, third-party/chpl-venv/chpldoc-requirements1.txt, third-party/chpl-venv/chpldoc-requirements2.txt, third-party/chpl-venv/cls-test-requirements.txt, third-party/chpl-venv/test-requirements.txt, tools/c2chapel/Makefile
I had started this last week but an outside contributor got to the PyYAML change before I opened my PR :)
This does not tackle updating Sphinx, docutils, sphinx-rtd-theme or sphinxcontrib-chapeldomain, as the best update for those would require bumping the oldest version of Python we support to Python 3.10 (and might require updates to our testing system as a result).  So I'm waiting on the green light for that from the BTR team.
Updates:
- pytest (used by the language server) from 8.2.0 to 8.3.3
- pytest-lsp (used by the language server) from 0.4.1. to 0.4.3
- attrs (used by the python bindings) from 23.1.0 to 24.2.0
- cattrs (used by the python bindings) from 23.1.2 to 24.1.2
- pygls (used by the python bindings) from 1.3.0 to 1.3.1
- typeguard (used by the python bindings) from 3.0.2 …
=> Update remaining python dependencies for various tools

runtime/include/chplmath.h
Fixes a performance issue introduced by https://github.com/chapel-lang/chapel/pull/26048. This PR added `chpl_` wrappers in the runtime for complex math functions in `Math` and `AutoMath`. These functions are marked `static inline`, but that is only a hint to the backend and if they are not i lined there may be a performance penalty (`test/studies/shootout/mandelbrot/jacobnelson/mandelbrot-complex.chpl` saw a 30% slowdown).
This is fixed by replacing `inline` with `___always_inline` (defined in `runtime/include/sys_basic.h`), to force inlining and prevent the regression.
Testing:
=> Resolve performance regression with complex math functions

frontend/lib/resolution/resolution-queries.cpp, tools/chapel-py/src/python-types.h, tools/chpl-language-server/src/chpl-language-server.py, tools/chpl-language-server/test/basic.py, tools/chpl-language-server/test/call_hierarchy.py, tools/chpl-language-server/test/util/utils.py
In the following program, trying to get the call hierarchy for `writeln` did not work on `main`.
```Chapel
writeln("Hello, world!");
```
There were a few issues with this. The first issue is that the the "index" that was fed through a `CallHierarchyItem` to LSP and back to `CLS` was an index into a single file's list of instantiations. Thus, if the function was instantiated in one place, but defined in another, the index would not be valid (or worse, be incorrect). This PR changes this by changing the way typed signatures are mapped to JSON-compatible identifiers; they are instead registered with a `ContextContainer` object, getting a unique ID. The unique ID is then used as JSON data, and can be used to access the same `TypedSignature` object when the JSON is being deserialized.
This, …
=> LSP: fix "call hierarchy" across files

util/packaging/homebrew/chapel-main.rb, util/packaging/homebrew/chapel-release.rb
This updates our homebrew formulas to match the version homebrew has most recently released. It updates the python version in use from 3.12 to 3.13.
note that the patch in the release has since been merged on main so that's why it's not also in `homebrew-main.rb`
trivial change to copies of homebrew formulas for testing only - not reviewed.
=> update chapel homebrew formula to match release

util/test/sub_test.py
This adds the semicolon character to the list of special escaped characters in two functions we use for preparing test command strings in `sub_test.py`. 
It was needed to accommodate HPO testing where the `execopts` expect to pass a `;` as the delimiter between arguments for the `hpo-example.chpl` blog article. I found that when `start_test` was used the program was not seeing any arguments after the first `;` in the `argsString` argument. Manually escaping the character did not work, but adding the `;` to the list of escaped characters in these `ShellEscape` and `ShellEscapeCommand` did.
TESTING:
=> add `;` to list of shell escaped chars in `sub_test.py`

third-party/chpl-venv/c2chapel-requirements.txt, tools/c2chapel/Makefile
Undo version upgrade for pycparser because it is not actually compatible with the newest version of pycparserext (despite it apparently installing cleanly if you didn't have an older version of pycparserext installed on your machine, so far as I can tell)
Explicitly set the version of pycparserext to the latest version.  This should help avoid the testing mishap in the future, since explicitly specifying the version makes it tell us if we upgrade to a version of pycparser that is incompatible with it.
Update the Makefile for c2chapel to stay in line with the pycparser version
Running a full paratest with futures after having built c2chapel
=> c2chapel dependency changes

util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.fast.colo.bash
Now that the basic test infrastructure works, run the full GASNet performance suite w/ co-locales and PSHM enabled.
=> Run full GASNet performance suite w/ co-locales and PSHM

tools/chapel-py/src/method-tables/uast-methods.h
Adds missing VisibilityClause methods to chapel-py, specifically `limitation_kind` and `limitations`.
=> Add missing VisibilityClause methods to chapel-py

test/gpu/native/interop/gpuLibrary/Makefile, test/gpu/native/interop/gpuLibrary/udf2.prediff
Adjusts a test locking in GPU library behavior to respect CXXFLAGS.
This was preventing this test from running properly on some systems where extra flags set in CXXFLAGS are required for GPU compilation.
Note that this PR has no changes to the cmake version of this test, as cmake was automatically respecting CXXFLAGS (as it should)
=> Make GPU library tests respect CXXFLAGS

doc/rst/usingchapel/building.rst
Resolves #26107
The documentation was worded in such a way that it suggested `./configure --prefix=~/` was valid, but we removed support for specifying paths that aren't absolute last year, to more closely match the behavior of `autoconf`.  Remove the suggestion to use `~/` so that future readers don't encounter that error message (or at least don't encounter it on our suggestion).
Double checked the built documentation
=> Remove an outdated suggestion from the `./configure` documentation

third-party/qthread/Makefile
Configure qthreads with a 128-bit cache line on Apple Macs, since that gives a slight performance increases
This was suggested by @insertinterestingnamehere offline and after testing on my M1 mac, I found slight performance improvements in some micro benchmarks
| Benchmark                  | Without explicit cacheline | With explicit cacheline | percent improvement |
| -------------------------- | -------------------------- | ----------------------- | ------------------- |
| empty-coforall             | 1.988                      | 1.812                   |  9.294%             |
| empty-forBegin             | 1.950                      | 1.885                   |  3.357%             |
| empty-forall               | 1.888                      | 1.788                   |  5.434% …
=> Configure qthreads with a 128-bit cache line on Apple Macs

tools/chapel-py/src/method-tables/uast-methods.h, tools/chpl-language-server/src/chpl-language-server.py, tools/chpl-language-server/test/completion.py
This PR expands upon our existing completion support to be location specific. Prior to this PR, only the module level scope was used to provide completion symbols. This PR changes that, so that visible symbols are computed based upon the users cursor.
With this PR, users will get an auto-complete suggestion of 'myVariable' when 'myV' is typed.
```chapel
record myRecord {
var  myVariable = 1;
proc foo() {
myV
}
}
```
Implementation details
This PR uses the fact that the FileInfo visits nodes in order when building segments. So in the above example, the scope for `myRecord` is visited before `foo`. As each scope is entered, we keep track of the location, its Scope object, and the parent scopes. This is precomputed before a user ever requests a completion, so that when that occurs it is just …
=> Expand completion support for language server

test/chplcheck/MissingInIntent.chpl, test/chplcheck/MissingInIntent.good, test/chplcheck/MissingInIntent.good-fixit, test/chplcheck/activerules.good, test/chplcheck/allrules.good, tools/chplcheck/src/rules.py
Adds a `chplcheck` rule to inform users that formals that initialize a field should have an in intent. Doing this can reduce the number of copies made and improve performance.
This PR takes the following approach to implement this
1. Identify all field in an aggregate type
2. For each initializer, identify all formals that have the default intent
3. If a formal is assigned to a field before `init this`, warn
Note that this only handles the cases where the left hand side of `=` can be scope resolved, so something like `this.field = myFormal` will not trigger the warning yet
Future work: As the resolver comes online and is threaded into `chplcheck`, this lint rule should make use of the logic in `InitResolver` to distinguish between initialization and assignment.
=> Add linter rule for missing in intents

modules/packages/Image.chpl
Improves the errors from `Image.mediaPipe` when a user tries to use it without having `ffmpeg` installed.
=> Improve errors when ffmpeg is missing

tools/chpl-language-server/src/symbol_signature.py, tools/chpl-language-server/test/document_symbols.py
Improves the signature printing for the language server. `symbol_signature.py` now handles more cases which improves the user experience when hovering over symbols.
Before this PR
After this PR
Note: `symbol_signature.py` continues to be a stopgap since we have no universal dyno pretty printer yet, see https://github.com/chapel-lang/chapel/issues/24716
=> Improve signature printing for language server

test/release/examples/primers/taskParallel.chpl, test/release/examples/primers/taskParallel.prediff
This updates the task parallel primer to use the term 'task' instead of thread.  While spot-checking the sections affected by this, I also made some localized changes to improve the clarity and precision of the descriptions.  I also added some more material at the front to define what a 'task' is (roughly) and to move a `config const` down closer to where it's used.
I also noticed that the messages printed by the main/first coforall example in this primer were very weird, implying that each statement within the body was printed by a distinct task.  This may have been a copy-paste error from the second coforall loop example, which uses 'begin's, but still surprises me that it'd been around for so long.
Note that I did not do a complete read-through of the primer in the interest of time, …
=> Updates and fixes to task parallel primer

runtime/src/gpu/amd/gpu-amd.c, runtime/src/gpu/nvidia/gpu-nvidia.c
The CUDA and HIP libraries refer to GPUs by unique IDs that are consecutive integers starting at zero. When GPUs are shared by co-locales the IDs of the GPUs used by a particular locale may not start with zero and they may not be consecutive, so they cannot be used as the sublocale ID or to index into arrays. Previous modifications to support co-locales introduced "physical" (global) IDs vs "logical" (relative) IDs, but it wasn't a very clean implementation and recent changes to memory management broke it. This PR cleans up the implementation, makes it more obvious what is going on, and adds various sanity checks.
Tested against `test/gpu/native/multiLocale` both without co-locales and with `CHPL_RT_LOCALES_ON_NODE=2` for both `CHPL_GPU=amd` and `CHPL_GPU=nvidia`. 
Resolves …
=> Fixed physical GPU ID to logical conversions

modules/standard/List.chpl, test/library/standard/List/pop/listPopHaltEmpty.good, test/library/standard/List/pop/listPopIndexHaltEmpty.good
The halt message for calling `popBack` on an empty list was:
```
error: halt reached - Called "list.getAndRemove" on an empty list.
```
This PR fixes the halt message so that the correct method name is used for `getAndRemove` and `popBack`.
resolves: https://github.com/chapel-lang/chapel/issues/26129
=> Fix halt message for `list.popBack`

util/chplenv/chpl_llvm.py, util/chplenv/utils.py
Fixes a regression where `CHPL_LLVM=bundled` on MacOS resulted in a python error in printchplenv. This was due to some incorrect logic in `try_run_command`, which was added as a part of https://github.com/chapel-lang/chapel/pull/26072. This was resulting in `my_stderr` always being either `None` or the empty string, which was not the correct behavior.
This was not caught previously, as `CHPL_LLVM=bundled` is not a common config on MacOS (or tested in nightly tests)
Tested that a full build of `CHPL_LLVM=bundled` works on MacOS
=> Fix `CHPL_LLVM=bundled` on MacOS

compiler/codegen/codegen.cpp, runtime/src/gpu/amd/gpu-amd.c, runtime/src/gpu/common/cuda-shared.h, runtime/src/gpu/nvidia/gpu-nvidia.c
This fixes an issue where the runtime would fail to load the GPU fatbin when sufficiently large hugepages were being used.
```
internal error: gpu-amd.c:62: Error calling HIP function: file not found (Code: 301)
```
This was only an issue `CHPL_GPU=amd`, not `CHPL_GPU=nvidia`. @jhh67 found that copying the global fatbin to a local buffer before calling `hipModuleLoadData` was sufficient to work around the issue. Its not totally clear why `hipModuleLoadData` has this issue, but the fix is simple enough and low impact (this code only runs once per GPU at startup).
This PR applies @jhh67's fix by copying the fatbin only when hugepages are enabled, which requires threading `chpl_gpuBinarySize` into the runtime.
Tested that the following test case works without hugepages and that it doesn't …
=> Fix internal error when using `CHPL_GPU=amd` and hugepages

frontend/lib/parsing/ParserContextImpl.h, tools/chpl-language-server/src/chpl-language-server.py, tools/chpl-language-server/test/basic_resolver.py
This PR implements go-to-definition for calls. It does so by introducing a new segment type (call segments) to denote things called at a given position.
This PR also implements a major overhaul of how `chpl-language-server`'s segment lists work. Specifically, it makes the segment lists work when items stored therein have arbitrary overlapping behavior (nesting, partial overlaps, disjointedness). Consider the following representation of a list of things which are found in a source file (e.g., names, calls, etc.)
```
|------------| A
|-------------| B
|--| C
|---------| D
```
Prior to this PR, CLS stored a sorted list of these items, and used a binary search across the elements' start positions to find the item under the cursor. However, this didn't work in situations such as the B-C …
=> LSP: resolve 'go-to-definition' for calls, including in generic instantiations

test/gpu/native/multiLocale/SKIPIF, util/cron/test-gpu-ex-cuda-12.colocales.bash
Though the GPU runtime includes code to support colocales, it was not tested automatically prior to this PR. This PR adds a new configuration that runs only the tests in `test/gpu/native/multiLocale` using `CHPL_RT_LOCALES_PER_NODE=2`, enabling colocales. In this configuration, the `main` branch before John's fix failed to build, which indicates that it accurately tests the colocale assignment code.
While there, I noticed that even without colocales, the `test/gpu/native/multiLocale` folder is not tested under OFI, since the SKIPIF is more specific and requires GASNet. This PR adjusts the skip if to allow either GASNet or OFI.
I ran:
```bash
CHPL_NIGHTLY_DO_NOTHING=true source ./util/cron/test-gpu-ex-cuda-12.colocales.bash
make -j32
start_test …
```
=> Add nightly job for NVIDIA GPUs + colocales

third-party/qthread/README, third-party/qthread/qthread-src/include/qt_atomics.h
This backports a performance fix to cover a regression from qthreads 1.21.
In particular it adds some platform-specialized assembly that controls processor behavior while busy waiting.
=> Backport Fix For Performance Regression in Qthreads 1.21

frontend/lib/resolution/can-pass.cpp, frontend/test/resolution/testReturnTypes.cpp
Enable Dyno to infer return type based on a shared ancestor between potentially-returned class types.
Adds testing for several such cases, including generic parents.
Resolves https://github.com/Cray/chapel-private/issues/6773.
Testing:
=> Consider common class ancestors for dyno return type inference

compiler/AST/symbol.cpp, test/param/loop/boolInst.chpl, test/param/loop/boolInst.good, test/studies/bale/indexgather/ig-variants.comm-none.good, test/studies/bale/indexgather/ig-variants.good
Fixes https://github.com/chapel-lang/chapel/issues/26142.
Prior to this PR, each creation of a true/false symbol led to a new variable. This, in turn, resulted in redundant instantiations for the same value, including of record types. This meant that two `R(true)`s can actually be distinct, because `true`s could be different. This PR changes this to ensure the same `gTrue` and `gFalse` is returned from `new_BoolSymbol`. This matches the behavior of `new_IntSymbol`, which uses a cache.
This makes an existing test fail (`ig-variants.chpl`), but only because its .good file explicitly locks down the duplicate instantiation behavior, which is undesirable anyway. So, this PR changes that test with the expectation that `foo(true)` creates only a single instantiation, instead of N instantiations …
=> Cache true and false symbol creation

runtime/include/chpl-gpu-impl.h, runtime/src/chpl-gpu.c, runtime/src/gpu/amd/gpu-amd.c, runtime/src/gpu/cpu/gpu-cpu.c, runtime/src/gpu/nvidia/gpu-nvidia.c
This PR re-arranges some of the runtime initialization code to avoid duplicating code for colocale allocation. The reason this was originally a little bit tricky is that vendor-neutral bits (calling out for `topo` information, finding the "closest" devices for each co-locale) was intermixed with vendor-specific API calls to, for example, retrieve the PCI bus number. As a result, the initialization code was a mix of vendor-specific and vendor-neutral code, and was not too easy to separate.
This PR factors out the device-specific fragments of initialization into `impl` functions for each vendor, leaving the vendor-neutral topology and colocale code in `chpl-gpu.c`. The trickiest aspect is that the _iteration over devices to use on the curernt locale is driven by the vendor-neutral code_. …
=> GPU: refactor runtime initialization to extract common code

test/gpu/native/studies/math/mathKernels.suppressif
`gpu/native/studies/math/mathKernels` is now passing on cray-cs. This PR removes the `supressif` file s.t. failures are no longer ignored in nightly testing.
=> remove supressif file for GPU mathKernel test

compiler/optimizations/gpuTransforms.cpp, modules/standard/AutoGpu.chpl, test/gpu/native/basics/itersPerThread.chpl, test/gpu/native/basics/itersPerThread.good
This PR implements the cyclic / round-robin assignment of loop iterations to GPU threads when the user passes a param `true` as the second argument to the `@gpu.itersPerThread` attribute.
This is a straightforward extension of the current implementation of `@gpu.itersPerThread` introduced in #25855 and retains its limitations. This PR advances #22175 by addressing https://github.com/chapel-lang/chapel/pull/25855#issuecomment-2327527618.
Next steps:
Switched PRIM_GPU_SET_BLOCKSIZE and PRIM_GPU_SET_ITERS_PER_THREAD to have the compiler-internal `counter` argument first.
Simplified the checking of the arguments to `@gpu.blockSize` and `@gpu.itersPerThread` in AutoGpu.chpl and in gpuTransforms.cpp.
Moved the call to `generateNumThreads()` to an earlier place within outlineEligibleLoop(), …
=> Cyclic @gpu.itersPerThread

frontend/lib/resolution/can-pass.cpp, frontend/test/resolution/testDisambiguation.cpp
Fixes a disambiguation bug caused by re-checking if an instantiation was correct by using the instantiated param-with-a-value formal with canPass. In the test case added by this PR, we would compare an ``int`` actual to an instantiated ``uint`` formal, which of course have different ``Param*`` classes, meaning the candidate would be discarded.
Testing:
=> Dyno: Fix disambiguation bug with param integral formals

test/gpu/native/deviceAttributes.cuda.c, test/gpu/native/deviceAttributes.hip.c
It looks like for certain versions of HIP you'll get warnings like this if you call a HIP function and discard (don't capture) its result:
```
> deviceAttributes.hip.c:14:3: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
>    14 |   hipDeviceGetAttribute(&val, attr, device);
```
I guess this a best practice as these functions return an error code and if you're not capturing it then you're not doing any error checking.
Anyway, this PR updates the deviceAttributes test to do this error checking and avoid this warning.
While at it, I do the same thing for CUDA.
=> fix deviceattributes test by having cuda/hip calls to avoid nodiscard warning

compiler/resolution/functionResolution.cpp, test/types/records/generic/typeCompareWithDefaults.chpl, test/types/records/generic/typeCompareWithDefaults.good
Fixes https://github.com/chapel-lang/chapel/issues/26132.
This is a very similar issue to the one in https://github.com/chapel-lang/chapel/pull/26151. A builtin function (`: string` in the previous PR, `==` in the current PR) did not correctly handle the case of generic-with-default symbols as arguments. This PR changes that.
=> instantiate types with defaults when appropriate while comparing

compiler/passes/convert-uast.cpp, frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/resolution-types.cpp, frontend/lib/resolution/scope-queries.cpp, frontend/lib/resolution/scope-types.cpp, frontend/lib/uast/post-parse-checks.cpp, frontend/test/uast/testStringify.cpp, test/classes/forwarding/forwarding-to-method-and-non-method.bad, test/classes/forwarding/forwarding-to-method-and-non-method.future, test/classes/forwarding/outside-of-class.chpl, test/classes/forwarding/outside-of-class.good
Closes https://github.com/chapel-lang/chapel/issues/25692.
This PR fixes internal errors with forwarding statements.
The first case is simple -- it occurs when a forwarding statement is used outside a class or record. This is disallowed (forwarding statements are only allowed as part of a class or record per the [forwarding tech note](https://chapel-lang.org/docs/technotes/forwarding.html)). So, this PR adds a new post-parse check to rule out forwarding statements in that location.
The second case (reported by Michael in a comment in https://github.com/chapel-lang/chapel/issues/25692#issuecomment-2332178411) is actually a combination of two errors:
1. The `convert-uast.cpp` step misses `TemporaryConversionSymbols` created in forwarding declarations. This is because forwarding declarations …
=> Fix internal errors in some forwarding statement cases

runtime/src/chpl-gpu.c, runtime/src/gpu/cpu/gpu-cpu.c
There were some renaming and runtime bugs in CPU-as-device mode; this PR fixes them.
=> Fix issues with runtime code in CPU-as-device mode

test/gpu/native/basics/itersPerThread.chpl, test/gpu/native/basics/itersPerThread.good
Exends the test of `@gpu.itersPerThread` with a utility function that groups loop iterations by thread and block that execute them. For example:
```
numIndices 32  itersPerThread 5  blockSize 3  gridSize 3  block
bl th | iters
0  0 |  1  2  3  4  5 .
0  1 |  6  7  8  9 10 .
0  2 | 11 12 13 14 15 .
1  0 | 16 17 18 19 20 .
1  1 | 21 22 23 24 25 .
1  2 | 26 27 28 29 30 .
2  0 | 31 32 .
2  1 | .
2  2 | .
numIndices 32  itersPerThread 5  blockSize 3  gridSize 3  cyclic
bl th | iters
0  0 |  1  8 15 22 29 .
0  1 |  2  9 16 23 30 .
0  2 |  3 10 17 24 31 .
1  0 |  4 11 18 25 32 .
1  1 |  5 12 19 26 .
1  2 |  6 13 20 27 .
2  0 |  7 14 21 28 .
2  1 | .
2  2 | .
```
Also extends sanity checks.
Test enhancement. Not reviewed.
=> Show iterations grouped by GPU thread and block

util/cron/test-gpu-ex-cuda-11.bash, util/cron/test-gpu-ex-cuda-12.bash, util/cron/test-gpu-ex-cuda-12.colocales.bash, util/cron/test-gpu-ex-cuda-12.interop.bash, util/cron/test-gpu-ex-cuda-12.ofi.bash, util/cron/test-gpu-ex-cuda-12.specialization.bash, util/cron/test-perf.gpu-ex-cuda-12.bash, util/cron/test-perf.gpu-ex-cuda-12.um.bash
Our nightly gpu tests that run on an EX machine are using a partition that has both 40GB and 80GB NVIDIA A100's.  This causes issues with our current `deviceAttributes` test and more generally it seems like we should be running our tests (particularly for our perf jobs) on a partition that will have more consistent hardware.
This PR updates our nightly test configs to do that.
If we run into resource issues then we should back this out, but I think we should wait until we encounter such issues before trying to work on the larger, less homogeneous, partition.
See: https://github.com/Cray/chapel-private/issues/6847
=> have nightly gpu ex tests use partition w/ NVIDIA A100 SXM4 40GB

util/cron/test-perf.hpe-cray-ex.ofi.bash
See (https://github.com/Cray/chapel-private/issues/6710). We have several tests in our `hpe-cray-ex-performance-test-perf.hpe-cray-ex.ofi` job failing because they're running out of memory.  This PR updates `CHPL_RT_MAX_HEAP_SIZE` to 50%.
This is what we have it set to in `./common-hpe-cray-ex.bash` so this seems like it should be fine to do.
I haven't manually verified that this resolves all the failing tests, but given that we've had these failures going for a while (and I'm on triage) I don't mind pushing this out as an experimental update and dealing with any fallout that occurs tomorrow.
=> resolve failing tests in nightly cray ex perf job by updating max heap size

frontend/include/chpl/framework/ID.h, frontend/include/chpl/parsing/parsing-queries.h, frontend/include/chpl/resolution/resolution-queries.h, frontend/include/chpl/uast/Builder.h, frontend/include/chpl/uast/BuilderResult.h, frontend/lib/framework/ID.cpp, frontend/lib/parsing/parsing-queries.cpp, frontend/lib/resolution/default-functions.cpp, frontend/lib/resolution/default-functions.h, frontend/lib/resolution/resolution-queries.cpp, frontend/lib/resolution/return-type-inference.cpp, frontend/lib/uast/Builder.cpp, frontend/lib/uast/BuilderResult.cpp, frontend/test/framework/testIds.cpp, frontend/test/resolution/testClasses.cpp, frontend/test/resolution/testConstChecking.cpp, frontend/test/resolution/testCopyElision.cpp, frontend/test/resolution/testForwarding.cpp, frontend/test/resolution/testInitSemantics.cpp, frontend/test/resolution/testMaybeConst.cpp, frontend/test/resolution/testNew.cpp, frontend/test/resolution/testSplitInit.cpp, frontend/test/resolution/testTypeConstruction.cpp
Previously, generated uAST was being created given a particular type
possibly with other information about how the call was being invoked.
Generated uAST was then created as a fake 'included' module with a
parent symbol path was that of the module in which the type was defined.
This uAST was then stored and retrieved using some set/get queries in
``chpl::parsing``.
This PR updates the implementation to instead rely on generated
functions using the type's symbol path as its parent path. This allows
``parseFileContainingIdToBuilderResult`` to use a generated ID's symbol
path and symbol name to query the uAST, as opposed to using the old
getter method. Now, we rely on the ``buildDefaultFunction`` query in
``chpl::resolution``.
For example, a default initializer will have a path like …
=> Dyno: Refactor uAST generation

test/ANNOTATIONS.yaml
Adds an annotation for a recent Arkouda reduction performance regression:
- initial regression caused by: https://github.com/Bears-R-Us/arkouda/pull/3845
- resolved by: https://github.com/Bears-R-Us/arkouda/pull/3874
=> add annotations for arkouda reduce regression and resolution

util/chplenv/chpl_llvm.py
Sometimes when building Chapel the build system will report something like 'C compiler cannot compile executable'. This can indicate the users system is missing some dependencies, or it can mean that extra arguments are needed to work. This PR improves the ability of chplenv to provide those arguments when needed.
Specifically this PR infers when `--sysroot` or `-Wl,-dynamic-linker` need to be passed to clang on linux systems.
Testing
=> Resolve more cases of 'C compiler cannot compile executables'

util/chplenv/overrides.py
Fixes an issue where if a `chplconfig` file has a variable with a value that contains an equals sign, it will break with an error like `Warning: Syntax Error: $CHPL_HOME/chplconfig:line`.
This resolves an issue a user saw on a system where `--gcc-toolchain=...` was apart of the definition for `CHPL_TARGET_CC/CXX`
=> Fix issue with chplconfig not supporting variables with equals signs

frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/can-pass.cpp, frontend/lib/resolution/resolution-queries.cpp
Updates to the Dyno resolver have exposed some bugs that once again break hovering over `string` with the resolver enabled. This PR fixes a number of minor issues that cause crashes. The changes are as follows:
1. **Handle type query domains.** Thus, `[?D]` now resolves to a generic array type as opposed to 'Unknown'.
2. **Treat passing to unknown type as instantiation.** This is important for cases in which type queries need to be populated. They are only populated from substitutions, but substitutions are not created for completely unknown formals, because prior to this change, a completely unknown formal can be passed to without instantiating (i.e., without substitution).
3. **Reject candidates that fail due to inability to infer type queries.** After computing a formal type, we …
=> LSP: fix hovering over a string

util/cron/test-perf.hpe-cray-ex.ofi.bash
Following up on <https://github.com/chapel-lang/chapel/pull/26069>.  Increasing `CHPL_RT_MAX_HEAP_SIZE` for that job helped some previously failing tests to pass. There still remain some tests that look like they're hitting out of memory issues.
If this causes issues tomorrow night I'll send a followup PR to revert. Apologies for the PR noise in the interim.
=> bump up heap size for nightly cray ex perf job again

frontend/lib/resolution/Resolver.cpp, frontend/lib/resolution/Resolver.h, frontend/lib/resolution/resolution-queries.cpp, frontend/test/resolution/testNestedFunctions.cpp, frontend/test/resolution/testTypeQueries.cpp
This PR adds support for non-local receivers to dyno and fixes a bug affecting the resolution of type queries. It adds support for programs like the following:
```chapel
class Foo {
type T;
proc get(type t) type do return t;
proc foo() {
// Here 'nested' is not a method, but 'this' is still visible as
// an outer variable. It is a non-local receiver from the
// parent method 'foo'.
proc nested(x : get(T)) do return x;
return nested(0);
}
}
```
Refactor the `Resolver::methodReceiverType()` method to make use of a new method `closestMethodReceiverInfo()`. Remove `getMethodReceiver` and streamline how receiver information is computed. When resolving, try to compute a local method receiver using whatever means are available. If that fails, consult stack frames for the first method that …
=> dyno: Support non-local receivers and improve resolution of type queries

util/chplenv/overrides.py
While paratesting my branch tonight, I found that
chplenv/chplconfig/warnings/warnings.chpl
was failing due to PR #26178.  Though I'm not that familiar with this logic, it seems that reverting half of the changes in it keeps this test working as expected, though it may suggest we need to do more to both achieve the PR's aim and also keep errors for cases like this.
=> Back out one of the changes in #26178 to get warnings/warnings.chpl working

util/cron/test-hpe-cray-ex-ofi.bash
This adds blog testing to a single cray-ex config. It requires the companion PR https://github.hpe.com/hpe/hpc-chapel-ci-config/pull/1318 to be merged first, then this can be merged and should start testing the blog on the hpe-cray-ex platform
=> add blog testing to hpe-cray-ex-ofi test config

util/cron/common-python-interop.bash, util/cron/getCompiler.py, util/cron/test-python-modules.bash, util/cron/test-python-modules.gasnet.bash
Adds explicit testing of the presence of Cython and numpy to both jobs, and
ZMQ to the multilocale job.
Ensures that the scripts fail if these dependencies are not found.
Does this by creating a couple of helper files:
- a common bash script for checking Cython and numpy
- a python script for getting access to our compiler information.  This seemed
easier than trying to figure out how to do it in bash
When checking for ZMQ, create a temporary directory with a C file that checks if
the header is appropriately installed.  This is similar to the skipif handling
for the job, but distinct due to running before the Chapel compiler is built
(and thus before we can use the `compileline` command like that skipif does).  I
could have potentially updated the skipifs to use this pathway, but left …
=> Make the python interoperability jobs fail if dependencies are not installed

modules/internal/ChapelHashtable.chpl
Fix trying to use an incorrect `followThis` type in the `ChapelHashtable._allSlots` follower iterator.
This appears to have been introduced in https://github.com/chapel-lang/chapel/pull/15739. The corresponding leader, when it lived in `DefaultAssociative`, did yield `(chunk, this)` as the follower expects. But in the move to its own module, the leader was changed to yield just the `chunk`, and the follower was left the same.
I caught this because in [Dyno associative domain resolution efforts](https://github.com/Cray/chapel-private/issues/6833), we need to resolve the serial iterator, and Dyno performs a check that the standalone and follower variants have the same yield type, so it needed to resolve the follower, which then failed due to this issue.
I don't know why this hasn't caused …
=> Fix `followThis` type in `ChapelHashtable._allSlots` follower

test/chplenv/chplconfig/correctness/chplconfig, test/chplenv/chplconfig/correctness/correctness.chpl, test/chplenv/chplconfig/warnings/chplconfig, test/chplenv/chplconfig/warnings/warnings.chpl, test/chplenv/printchplenv/.gitignore, util/chplenv/overrides.py
Properly handles the parsing of chplconfig files. https://github.com/chapel-lang/chapel/pull/26178 added the ability to parse chplconfig variables with values including `=`, but that broke the warning for something like `CHPL_VAR==value`.
This PR resolves the issue by refactoring some of the parsing code in `overrides.py` to check error cases in `skip_line`, rather than relying on python exceptions. Then to avoid duplication of logic, renames `skip_line` to `check_line` and has it return the parsed variable.
Fixes the issue introduced in https://github.com/chapel-lang/chapel/pull/26178 and reverts https://github.com/chapel-lang/chapel/pull/26180
Tested by running `start_test test/chplenv`
=> Properly handle parsing of equals in chplconfig

test/library/standard/Memory/Diagnostics/allocationsIter.suppressif
The `allocations` iterator may yield different number of allocations when `--baseline` is used. The test associated with this iterator should be sensitive to the number of allocations. To make sure to be able to lock in the correct number of allocations while avoiding noise with `--baseline`, this PR adds a suppressif for `--baseline`.
Test:
=> Add a suppressif file for a new test

runtime/include/gpu/chpl-gpu-gen-common.h
This PR resolves the failure to build Arkouda after #26189 in the configuration (comm=none, gpu=nvidia) by adding a missing function chpl_gen_comm_getput_unordered() to chpl-gpu-gen-common.h.
The above .h file already contained `chpl_gen_comm_get_unordered` and `chpl_gen_comm_put_unordered` however was missing `chpl_gen_comm_getput_unordered`, which this PR adds. All three functions are placeholders that print the message "this shouldn't have happened".
The function `chpl_gen_comm_getput_unordered()` is now invoked when compiling Arkouda because:
(a) The kernel chpl_gpu_kernel_ChapelArray_line_2563_ has a CallExpr to PRIM_UNORDERED_ASSIGN, which codegens to a call to chpl_gen_comm_getput_unordered().
(b) The kernel contains a call to BlockArr.dsiAccess(), which calls `nonLocalAccess`. The …
=> Add the missing getput_unordered() for GPUs

runtime/src/comm/ofi/comm-ofi.c, test/runtime/configMatters/comm/bigTransfer.chpl
Implement `chpl_comm_get_nb` as a non-blocking operation in  `CHPL_COMM=ofi`. 
Resolves https://github.com/Cray/chapel-private/issues/6784.
=> Non-blocking GET for CHPL_COMM=ofi

highlight/emacs/chpl-mode.el, highlight/vim/syntax/chpl.vim
Adds some missing keywords I noticed in the vim and emacs syntax highlighters.
Related vscode PR: https://github.com/chapel-lang/chapel-vscode/pull/21
[Reviewed by @lydia-duncan  and @DanilaFe]
=> Add missing keywords to vim and emacs syntax highlighting

tools/chplcheck/src/config.py, tools/chplcheck/src/driver.py, tools/chplcheck/src/rules.py
Makes the internal prefixes (as specified by `--internal-prefix chpl_`) be exposed to linter rules, rather than just the driver. Technically this was already possible, this PR just makes the naming based rules exclude the prefixes, such that `chpl_camelCase` is considered to be camelCase
=> Make internal prefixes available to linter rules

tools/chpl-language-server/src/symbol_signature.py, tools/chpl-language-server/test/document_symbols.py
Adds support for printing something like `new TypeName()` in the language server. This allows users to see new expressions when hovering over a symbol.
=> Print new expressions properly in language server
