chapel-lang/chapel

frontend/lib/resolution/return-type-inference.cpp
frontend/test/resolution/testReturnTypes.cpp

Add dyno support for returns from within param for loops, matching production behavior.
Implemented by extending `ReturnTypeInferrer` to descend into param for loops, and respect `break` and `continue` statements which it can now encounter.
Includes adding testing for the fixed case, as well as several similar patterns of returning within a param loop.
Resolves https://github.com/Cray/chapel-private/issues/6787.
Testing:

Dyno resolve returns within param for loop

---

util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.fast.colo-nopshm.bash
util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.fast.colo.bash

Fixes a typo in the colocales performance graphs that was preventing them from getting correct results.
Problem: The data was being generated in the correct place, but then when `genGraphs` was run it used a different path and failed.

Fix colocales performance graphs

---

test/chplcheck/MisleadingIndentation.chpl
test/chplcheck/MisleadingIndentation.good
test/chplcheck/MisleadingIndentation.good-fixit
tools/chplcheck/src/rules.py

Resolves https://github.com/chapel-lang/chapel/issues/26147
Previously, the linting rule for `MisleadingIndentation` did not warn for cases with a loop inside a loop, `on` statements inside a loop.
This adds support in `chplcheck` for this, and also updates the related test.
New Warnings are generated for cases like this (not exhaustive):
```chapel
for 1..10 do
for 1..10 do
writeln("Hello, world!");
writeln("Hello, world!");  // Lint: rule [MisleadingIndentation] violated
for 1..10 do
on Locale[0] do
writeln("Hello, world!");
writeln("Hello, world!");  // Lint: rule [MisleadingIndentation] violated
on Locale[0] do
for 1..10 do
writeln("Hello, world!");
writeln("Hello, world!");  // Lint: rule [MisleadingIndentation] violated
on Locale[0] do
on Locale[0] do
writeln("Hello, world!"); …
```

Chplcheck misleading indent fix

---

util/cron/test-linux64-llvm19.bash

Adds a new nightly test config to validate the compiler works with LLVM 19
Tested that `make check` works using the LLVM installed via this script

Add nightly test config for LLVM 19

---

doc/rst/usingchapel/prereqs.rst
util/packaging/homebrew/chapel-main.rb
util/packaging/rpm/fc41-gasnet-udp/Dockerfile.template
util/packaging/rpm/fc41-gasnet-udp/spec.template
util/packaging/rpm/fc41/Dockerfile.template
util/packaging/rpm/fc41/spec.template

Adjusts packaging scripts and docs to reflect that we support LLVM 19 as of https://github.com/chapel-lang/chapel/pull/25964

Cleanup packaging scripts and docs to reflect LLVM 19 support

---

compiler/llvm/llvmGlobalToWide.cpp

Fixes some compiler build errors with LLVM 11 introduced by https://github.com/chapel-lang/chapel/pull/25964
Tested that `make check` works with LLVM 11.

Fix build errors with LLVM 11

---

util/chplenv/chpl_llvm.py

Fixes an include path issue caused by #25964.
#25964 changed all `-I` for LLVM includes into a `-isystem` so that they would not be subject to `-Werror`, which could break compiler builds irreparably for some versions of LLVM. However, `-isystem` perturbs the header search order, meaning if LLVM is already installed to a system include path then other stuff may break.
The fix is to use `-isystem-after` instead of `-isystem`, however this is a clang only flag. `-idirafter` has the same effect but exists in both [GCC](https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html#Options-for-Directory-Search) and [clang](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-idirafter-arg), so that is used in this PR. 
Tested that the compiler builds on both a system where …

Fix LLVM include when LLVM is a system install

---

compiler/resolution/ResolutionCandidate.cpp
test/classes/initializers/initequals/generics.chpl
test/classes/initializers/initequals/generics.good

Consider the following program:
```chpl
record G { type T; var x : T; }
proc G.init=(other: this.type) {
this.T = other.T;
this.x = other.x;
}
proc G.init=(other: int) {
this.T = int;
this.x = other;
}
var x : G(?) = 5;
```
Previously this program would fail to compile, and give a confusing error message stating it had found the second 'init=' specifically for 'int', but that it somehow wasn't a candidate.
The bug was caused by some missing logic in ``computeSubstitutions`` which was incorrectly returning 'false' in this case. The solution was to manually ignore a generic 'this' formal for initializers.
Resolves #16497
Testing:

Allow resolution of generic init= with concrete formals

---

frontend/lib/parsing/ParserContextImpl.h
frontend/lib/parsing/bison-chpl-lib.cpp
frontend/lib/parsing/chpl.ypp
frontend/lib/parsing/parser-yylloc-default.h
frontend/test/resolution/testResolverVerboseErrors.cpp
test/errors/parsing/underscores.2.good
test/errors/scope-resolution/redefinition/function-and-var.2.good
test/errors/scope-resolution/redefinition/redefinition-def-with-public-import.2.good
test/errors/scope-resolution/redefinition/redefinition-def-with-public-use.2.good
test/errors/scope-resolution/redefinition/redefinition-formal.2.good
test/errors/scope-resolution/redefinition/redefinition-private-import.2.good
test/errors/scope-resolution/redefinition/redefinition-public-import.2.good
test/errors/scope-resolution/redefinition/redefinition-public-use-as.2.good
test/errors/scope-resolution/redefinition/redefinition-public-use.2.good
test/errors/scope-resolution/use-shadows-formal1.2-0.good
test/errors/scope-resolution/use-shadows-formal2.2.good
tools/chpl-language-server/src/symbol_signature.py
tools/chpl-language-server/test/document_symbols.py

Fixes how symbols are printed in the language server for a few cases
- `new` expressions like `new (foo())()`
- types like `owned C`, `sync int`, and `atomic real`
- postfix expressions like `foo!` and `unmanaged C?`
Additionally, when resolving these I fixed an issue where locations for something like `var x: int;` reported the location as including the `;`. This is complicated by how we handle the default location for null rules in the grammar, but can be worked around by selectively setting the location in a few `_opt` cases.
Tested that `make test-cls` works, `make test-frontend` works, and `start_test test/errors` works
[Reviewed by @DanilaFe and @dlongnecke-cray]

Fix symbol printing in the language server for a few cases

---

frontend/include/chpl/parsing/parsing-queries.h
frontend/lib/parsing/parsing-queries.cpp
frontend/lib/resolution/InitResolver.cpp
frontend/lib/resolution/InitResolver.h
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/call-init-deinit.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testInitSemantics.cpp
frontend/test/resolution/testTypeConstruction.cpp

Prior to this PR InitResolver would always use the RHS type of field initialization statements to set the type of the field. For example, in "this.foo = RHS;", the field 'foo' would always use the type of RHS when resolving any relevant initialization calls (e.g. assignment). A real-world example is initializing a nilable class from ``nil``.
This PR uses ``Resolver::getTypeForDecl`` to check that the types are compatible, and then uses the computed type for 'foo'.
This PR also includes various other improvements needed to get tests working:
- correctly identifying field initialization during call-init-deinit (thanks to @brandon-neth)
- fix faulty "invalid class type construction" error when not dealing with managed classes
- Enable comparisons between types and ``?``
- Fix for faulty …

Dyno: Improve initialization of fields from non-matching types

---

compiler/optimizations/gpuTransforms.cpp
test/gpu/native/basics/itersPerThread.chpl

This PR fixes a bug where the same loop iteration was executed by multiple GPU threads in some cases involving the attribute `@gpu.itersPerThread` with `cyclic` argument set to `true`. The test itersPerThread.chpl is now beefed up to detect this buggy behavior, should it occur again.
This PR upholds the original intention of cyclic `itersPerThread` that maps the loop iterations onto the smallest number of GPU threads such that each thread executes at most `itersPerThread` loop iterations. In a discussion wtihin the group, we leaned against mapping the loop iterations onto ALL the threads that the GPU will fire up for the corresponding kernel, if this is different.
For example, consider a loop with 12 iterations and `itersPerThread=4`. They are mapped over 12/4=3 threads as follows:
| …

@gpu.itersPerThread-cyclic bug fix

---

test/release/examples/gpu/SKIPIF
test/release/examples/gpu/hello-gpu.comm-none.good
util/cron/test-gpu-cpu.bash

This PR enables testing of `release/examples` in the CHPL_GPU=cpu configuration, reverting #24365.
All tests pass except `hello-gpu.chpl` where the comm counts differ from proper gpu execution. Skipif this test for this configuration.
While there, remove an unnecessary .good file.
Testing change requested in #24365, not reviewed.

Enable testing GPU=cpu over release/examples

---

test/release/examples/primers/fact.c
util/cron/test-gpu-cpu.bash
util/cron/test-gpu-ex-cpu.bash

Enable nightly testing of `release/examples` in the cpu-as-device mode, aka CHPL_GPU=cpu, on EX, by analogy to #26221.
While there, fix this error, which we get in CHPL_GPU=amd testing using the bundled LLVM 18:
```
fact.c:17:11: error: cannot initialize a variable of type 'data *' (aka '_data *') with an rvalue of type 'void *'
17 |     data *d = malloc(sizeof(data));
|           ^   ~~~~~~~~~~~~~~~~~~~~
```
Trivial and proposed by @jabraham17. Not reviewed.

More gpu cpu testing

---

test/studies/champs/sub_test

We are observing OOM errors on another CHAMPS executable with the C backend. In the past, we attributed this to a backend compiler bug and skipped another executable with the same issue. This PR follows suit for `prep`. https://github.com/chapel-lang/chapel/pull/25862 is the PR that skipped `post`.

Avoid compiling CHAMPS' prep executable with the C backend

---

compiler/codegen/cg-symbol.cpp
compiler/codegen/codegen.cpp
compiler/include/codegen.h
compiler/llvm/clangUtil.cpp
compiler/optimizations/gpuTransforms.cpp
frontend/include/chpl/uast/PragmaList.h
test/gpu/native/basics/bug23045.chpl
test/gpu/native/cudaOnly/gpuAddNums/gpuAddNums.chpl
test/gpu/native/cudaOnly/gpuAddNums/gpuAddNums_primitive.chpl
test/gpu/native/distArray/issue-26202.chpl
test/gpu/native/distArray/issue-26202.good
test/gpu/native/simpleExternHello.chpl
test/gpu/native/studies/transpose/transpose.chpl
test/gpu/native/threadBlockAndGridPrimitives.chpl
test/release/examples/primers/interopWithC.suppressif
util/cron/common-native-gpu.bash
util/cron/test-gpu-cpu.bash
util/cron/test-gpu-ex-cpu.bash

This PR re-enables GPU testing over `test/release/examples`. For that, it (a) applies a `suppressif` on a test that generates a namespace-related error when compiling under CUDA, which I did not investigate, and (b) fixes the LLVM calling convention that was previously set incorrectly for the compiler-generated gpu-error stubs, causing LLVM verification failure in `release/examples/benchmarks/hpcc/ra-atomics` and a couple others, by introducing `FLAG_GPU_KERNEL` and `pragma "GPU kernel"`.
I tidied up the uses of several flags/pragmas in the compiler and tests. Here are highlights:
| use | old | "gpu codegen" | "gpu and cpu codegen" | new | "gpu codegen" | "gpu and cpu codegen" | "gpu kernel" |
| :--- | --- | :--- | :--- | --- | :--- | :--- | :--- |
| kernel | | + | - | | + | - | + |
| …

Enable release/examples GPU testing

---

test/extern/ferguson/mismatch-errors/mismatch-ri-iv.bad
test/extern/ferguson/mismatch-errors/mismatch-riv-iv.bad
test/extern/ferguson/mismatch-errors/mismatch-riv-iv.prediff

This PR updates two .bad files with the source code location, which is now printed out upon an internal error due to #26231.
While there, duplicate the `.prediff` from one test to the other because it is equally applicable to both.
Test fix, not reviewed.

Update .bad files for #26231

---

test/interop/python/pythonFriendliness/checkNotUsed.suppressif

One of the machines we run on has a problem with the `help("modules")` command that we are testing we didn't break.  This problem is independent of Chapel so should be suppressed until it is fixed (which will be outside of our control)
Verified that the suppressif triggers appropriately on the machine with the issue and doesn't trigger in normal testing.
I'm not entirely convinced it'll give us a "passing suppressif" message, though, but I'm not sure how to do that without also sweeping potential future issues under the rug if the failure mode changes

Suppress a python failure due to a system build issue that is not our fault

---

test/studies/uts/uts_deq.chpl

With #25900 merged, `test/studies/uts/uts_deq.chpl` started failing because it implemented its own `atomic max` routine locally.  Here, I'm removing that overload to try and avoid failures in tonight's testing.

Remove test-specific overload of atomic max

---

util/chplenv/chpl_llvm.py

Prevents unused argument warnings for `--gcc-toolchain` or `--gcc-install-dir`. These occurred when the `clang` being used was correctly configured with `--gcc-install-dir`, but our build system was using `--gcc-toolchain` anyways. 
Previously, users could hit this and would have to set `CHPL_LLVM_GCC_PREFIX=none` to avoid the warning. Now, the build system will only try to infer `--gcc-toolchain` if `--gcc-install-dir` is not already specified in a config file for clang.

Prevent unused argument warning for gcc toolchain

---

util/test/prediff-for-slurm

Fixes a syntax warning in `util/test/prediff-for-slurm` where bad escape sequences where used. The solution is to use a raw string.
Caused by newer python versions doing extra checks

Fix syntax warning for invalid escape sequence in slurm prediff

---

doc/rst/technotes/gpu.rst
test/gpu/native/llvmMoved.chpl

Updates the GPU technote to state that we currently test LLVM 19 and which cuda versions we actually test
Also updates `llvmMoved.chpl`

Update GPU technote to reflect current dependecies

---

util/chplenv/chpl_gpu.py
util/chplenv/chpl_llvm.py

Warn when CHPL_LLVM_VERSION and CHPL_GPU_SDK_VERSION are set in environment variables. These variables are ignored, but if a user sees them in the printchplenv output they may incorrectly set them and expect them to have an effect. This PR adds a warning telling users that it has no effect how to resolve the warning.

Add warnings for setting CHPL_LLVM_VERSION and CHPL_GPU_SDK_VERSION

---

test/interop/python/pythonFriendliness/checkNotUsed.suppressif

Matt pointed out that I had accidentally written the subprocess command in such a way that subprocess was escaping the whole command and so acting like it detected the failure mode when really it was just not running the command in a way that would work.  After fixing that, I also needed to hide the failure output from start_test so it wouldn't think the suppressif had failed.  With that all fixed, we now appropriately suppress the failure mode
Tested locally and on the machine where the failure occurred

Fix the suppressif file to actually detect the failure condition

---

frontend/include/chpl/uast/Comment.h
frontend/include/chpl/uast/MultiDecl.h
frontend/include/chpl/uast/TupleDecl.h
frontend/lib/resolution/Resolver.cpp
frontend/test/resolution/testMultiDecl.cpp

Allow dyno resolution of variable inits in a multiple declaration to use type information from earlier variables in the declaration.
This enables resolving a variable whose initialization part uses a previous variable in the same declaration, such as `var a = 1, b = (1 + a);`, which works in production.
Additionally includes refactoring `MultiDecl` resolution from two loop [nests] (`O(n)` and `O(n^2)`) to one (`O(n^2)`). This is done by traversing the individual decls in an outer loop, then backtracking within an inner loop for each "group" that shares the same type and/or init part. To support this, `AstListNoCommentsIterator` is adjusted from a forward to a bidirectional iterator.
Includes adding tests for the fixed case.
Resolves https://github.com/Cray/chapel-private/issues/6792. …

Dyno let multiple declaration inits use previous variables

---

frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testCast.cpp
frontend/test/resolution/testEnums.cpp

Enable resolving non-param enum-to-string and string-to-string casts within dyno.
Note param enum casts were already implemented in https://github.com/chapel-lang/chapel/pull/25837. However, non-param casts weren't resolving, as this cast isn't implemented in module code.
Includes adding tests for these cases.
Resolves https://github.com/Cray/chapel-private/issues/6864.
Testing:

Resolve non-param {enum,string}->string casts in dyno

---

frontend/lib/resolution/VarScopeVisitor.h
frontend/lib/resolution/call-init-deinit.cpp
frontend/lib/resolution/copy-elision.cpp
frontend/test/resolution/testCallInitDeinit.cpp

Fix a Dyno bug in which an 'already deinited' error would be emitted for an `in` intent record formal passed in turn as an `in` intent argument.
This applied to records because we care about deiniting them, and to `in` intent because it causes a copy or move. `call-init-deinit` detected copy-elision of the `in` formal while moving down the AST and declared it dead (at end of statement), but then emit an error for that same use while moving up the AST and checking for uses of dead variables. Fixed by keeping track of the statement after which a variable is dead, and not emitting errors for use of it within that statement.
A similar case also handled in this PR is the same `in` formal being passed as an argument to the same call multiple times, where just the last usage is copy-elided. …

Fix dyno 'already deinited' for record `in` arg

---

compiler/resolution/functionResolution.cpp
compiler/resolution/preFold.cpp
test/functions/resolution/parenless-return-intent-overloaded-proc-this-imag.chpl
test/functions/resolution/parenless-return-intent-overloaded-proc-this-imag.good
test/functions/resolution/parenless-return-intent-overloaded-proc-this-reasonable.chpl
test/functions/resolution/parenless-return-intent-overloaded-proc-this-reasonable.good
test/functions/resolution/parenless-return-intent-overloaded-proc-this.chpl
test/functions/resolution/parenless-return-intent-overloaded-proc-this.good

Closes https://github.com/chapel-lang/chapel/issues/26263.
The issue in question is that we get an internal error while invoking a return-intent-overloaded parenless procedure. 
```Chapel
record R {}
var r = new R();
var myConstant = 1.0;
proc R.foo {
return myConstant;
}
proc R.foo ref {
return myConstant;
}
r.foo();
```
At the surface level, this is caused by the code that attempts to do return intent overloading; it assumes that the overloaded call is a part of a list. When a field is being invoked, like `r.foo()`, the overloaded call (`r.foo`) is actually the base expression, which is not in any list.
I think it's conceivable for this combination of features to be used in user code; if `myConstant` wasn't an integer but actually a record/class with `proc this` defined on it, `r.foo()` …

Fix overloaded parnless as base expr

---

frontend/include/chpl/resolution/resolution-types.h
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/VarScopeVisitor.cpp
frontend/lib/resolution/resolution-error-classes-list.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testLoopIndexVars.cpp
frontend/test/resolution/testPromotion.cpp

This PR depends on https://github.com/chapel-lang/chapel/pull/26265. The clean diff is https://github.com/chapel-lang/chapel/pull/26273/files/dcfba2c700b91bdd262919a15306116d5be8f1fd..6399bfa6a10b2a62ded679cbd39bec93a142a610.
@bradcray pointed out that it seems to make sense to allow promoted functions over a single argument and loop expressions with a single iterand to have a standalone iterator if their iterand has one. This PR implements this, specifically by doing the following:
* Allowing loops over `zip` with a single argument to invoke the standalone iterator; this brings the behavior of `zip(i())` closer to `i()`
* Adjusting the compiler-generated implementation of `iter these` for loop expressions and promoted functions to allow `STANDALONE` iteration if there's only a single …

Dyno: allow standalone iteration over single-element `zip`s 

---

runtime/src/chpl-launcher-common.c
util/chplenv/chpl_unwind.py
util/test/chpl_launchcmd.py

Fixes a cryptic error that can occur when there are enough environment variables that are long, causing us to run out of space in a buffer. This is especially a problem for something like spack, which is prone to embedding very long paths in many environment variables.
This PR works around this by excluding certain environment variables we know aren't needed, in this case the PR excludes all variables suffixed with `_modshare`. These variables end up being duplicateted, so you have `VAR="some long string"` and `VAR_modshare="some long string"`. Its not important we maintain the duplicates, so this PR just filters them out.
Tested that with this patch the error goes away

Fix cryptic "failed to exec /usr/bin/env" errors with gasnet launchers

---

runtime/src/comm/ofi/comm-ofi.c

Don't set the maximum messages size if the provider is NULL (no provider was found).

Best provider might be NULL

---

test/runtime/stacktrace/fact-linenum-default.bad
test/runtime/stacktrace/fact-linenum-default.chpl
test/runtime/stacktrace/fact-linenum-default.compopts
test/runtime/stacktrace/fact-linenum-default.future
test/runtime/stacktrace/fact-linenum-default.good
test/runtime/stacktrace/fact-linenum-default.skipif
test/runtime/stacktrace/fact-linenum.compopts

Pin debug info the DWARF 4 for a test.
The proper fix is to fix our debug info, this is temporary to get the test passing again
This PR also adds a future to capture the desire to make this work better again

Pin to debug info version for test

---

util/test/paratest.chapcs

Drained nodes cannot have new jobs sent to them. The slurm `sinfo` command, which we use to count how many nodes to launch jobs on, does not have support for filtering out drained nodes. Instead, we separately query the number of drained nodes and subtract it from the total node number. However, we only query the number of drain__ing__ nodes, and not the number of nodes that have already been drained (but are still not accepting new jobs). This PR fixes that. From the [slurm docs](https://slurm.schedmd.com/sinfo.html), `DRAIN` includes both `DRAINING` and `DRAINED`:
> DRAIN (for node in DRAINING or DRAINED states), DRAINED, DRAINING

Exclude draining AND drained nodes from paratests

---

modules/packages/Python.chpl
modules/packages/PythonHelper/ChapelPythonHelper.h

Fixes errors about being unable to link against `Py_DECREF` in older versions of Python, due to `Py_DECREF` being a "complex macro" in older version (Prior to Python 3.11).
Tested with Python 3.10 and 3.13

Fix missing Py_DECREF in older Python versions

---

modules/packages/Python.chpl
test/library/packages/Python/COMPOPTS

Updates the flags needed to build with the Python module to include "-Wl,-rpath", so that there is no reliance on the value of LD_LIBRARY_PATH

Update flags needed to build with Python module

---

modules/packages/Python.chpl
modules/packages/PythonHelper/ChapelPythonHelper.h

Uses the correct pointer types for extern functions. This causes issues in some configurations, especially with the C backend.
For example for `PyUnicode_AsUTF8` it should return `const char*`, not `char*`. 
For the constants like `Py_None`, `Py_True`, and `Py_False`, this PR wraps their definitions in C which discards the const qualifier. While this is unfortunate, their types do not match the other PyObjectPtr types, and could cause other issues.

Use const-qualified pointers where needed in Python module

---

compiler/optimizations/gpuTransforms.cpp

In some cases (multi-locale compilation), we seem to generate more string-like operations in the body of `halt`. They are never triggered (they're in the CPU-only body of the function), but they do get flagged for outer variable access etc. Since we know GPUs won't be running that code, don't flag these as dangerous.
Reviewed by @vasslitvinov -- thanks!

Fix GPU halting under OFI

---

test/performance/memory/microMemoryAllocation.execopts

Prevent timeouts by lowering the number of trials for a test with asan/valgrind

Prevent timeouts by lowering the number of trials for a test with asan/valgrind

---

frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testPromotion.cpp

On main, because we allowed promotion to be applied to functions with the `type` and `param` intents, it was possible to trigger recursive queries, in which `chpl_promotionType` would be applied in a promoted manner. As a concrete example, the following test by @riftEmber caused an infinite recursion error:
```Chapel
use OS;
var x = createSystemError(0);
```
This PR ensures that this no longer happens, by matching the production compiler's behavior and skipping type-returning procedures:
https://github.com/chapel-lang/chapel/blob/df1f0f4965c069960e4053f9347a1e42067dcd80/compiler/resolution/functionResolution.cpp#L1783-L1788
Thank you @riftEmber for diagnosing the issue and reviewing the PR!

Dyno: fix promotion infinite recursion due to type returning functions

---

test/gpu/native/environment/gasnet.compopts

`start_test` sets `CHPL_NETWORK_ATOMICS=ugni` because `CHPL_COMM=ugni`, but the test is passed "--comm gasnet", causing a mismatch between `CHPL_COMM` and `CHPL_NETWORK_ATOMICS`. Also pass the test "--network-atomics none" to prevent this error.

gasnet doesn't support network atomics

---

frontend/test/resolution/testPromotion.cpp

``buildStdContext`` now returns a ``Context*`` rather than a unique_ptr.

Fix dyno testing after #26269

---

test/studies/parboil/SAD/sadSerial.chpl

Fixes `test/studies/parboil/SAD/sadSerial.chpl`, which is currently failing due to the upgrade to LLVM 19.
This PR changes the test to use an if-statement to compute the difference between 2 `uint(16)`, instead of an `abs` with up/down casting. With LLVM 19, the vectorizer is more aggressive and breaks the casting version. See https://github.com/chapel-lang/chapel/issues/26301

Fix parboil test failure with LLVM 19

---

modules/packages/Python.chpl

Fixes some memory leaks in Python.chpl, caused by not de-allocating 2 `c_ptr(wchar_t)` buffers.
tested `start_test test/library/packages/Python --memLeaks`

Fix memory leaks in Python.chpl

---

runtime/include/atomics/cstdlib/chpl-atomics.h
runtime/include/chpl-mem-consistency.h
runtime/src/chpl-cache.c

Finishes some renames from https://github.com/chapel-lang/chapel/pull/25749 that got left behind. These were silently continuing to "just work", but after a system compiler upgrade they no longer do

Fix a few atomics names that were not fully renamed

---

util/cron/test-perf.chapcs.arkouda.release.bash

Adjust Arkouda nightly test to use a version of LLVM supported by that version of Chapel.

Use llvm 18 with Arkouda release

---

util/cron/test-gpu-ex-cuda-12.bash
util/cron/test-gpu-ex-cuda-12.interop.bash
util/cron/test-gpu-ex-cuda-12.ofi.bash
util/cron/test-gpu-ex-cuda-12.specialization.bash
util/cron/test-perf.gpu-ex-cuda-12.bash
util/cron/test-perf.gpu-ex-cuda-12.um.bash

Changes our test scripts to use CHPL_LLVM=system with CHPL_GPU=nvidia on ex test systems, since Chapel works with the system LLVM (which is currently LLVM 19). This should reduce the time spent running CUDA tests on these systems

Use CHPL_LLVM=system with CHPL_GPU=nvidia on ex test systems

---

test/library/packages/Curl/check-http-setopt.prediff

Updates a prediff for a networking test to exclude some output about "using HTTP/1.x". This is needed due to a dependency change on the test system

Update prediff for networking test

---

util/chplenv/chpl_gpu.py

Fixes an issue where warnings in cuda headers would cause the build to fail. By treating those headers as system includes, we can ignore those warnings.
Note: on some systems, there are cuda headers that come from the cray programming environment, which this PR does not handle.

Treat cuda includes as system includes

---

tools/chapel-py/src/core-types-gen.cpp
tools/chapel-py/src/core-types-gen.h
tools/chapel-py/src/core-types.cpp
tools/chapel-py/src/core-types.h
tools/chapel-py/src/error-tracker.h
tools/chapel-py/src/method-tables/core-methods.h
tools/chapel-py/src/python-class.h

Closes https://github.com/chapel-lang/chapel/issues/25937.
This PR improves the situation in which AST or other bridged objects are incorrectly constructed (specifically, when they are constructed explicitly by the user). In this case, their internal representations can contain `null` values, which causes exception. This PR introduces checking for such cases, raising Python exceptions.
Now, none of the following operations produce internal errors, and raise instead:
<details>
<summary>Expand console output</summary>
```console
>>> import chapel
>>> c = chapel.Context()
>>> id = chapel.Identifier(c)
>>> id.unique_id()
Traceback (most recent call last):
File "<python-input-3>", line 1, in <module>
id.unique_id()
~~~~~~~~~~~~^^
RuntimeError: invalid instance of class 'AstNode'; please do not …
```

chapel-py: check for invalid instance of bridged classes to avoid internal errors

---

util/cron/test-gpu-ex-cuda-12.bash
util/cron/test-gpu-ex-cuda-12.ofi.bash
util/cron/test-gpu-ex-cuda-12.specialization.bash
util/cron/test-perf.gpu-ex-cuda-12.bash
util/cron/test-perf.gpu-ex-cuda-12.um.bash

We have previously been advised that on this testing system we should be using `module load cuda`, instead of `module load cudatoolkit`. This was only changed in some of the configs, this PR changes them in all of them

Use module cuda instead of cudatoolkit

---

util/packaging/homebrew/chapel-main.rb
util/packaging/homebrew/chapel-release.rb

This updates our homebrew packaging formulas with changes made by the homebrew maintainers to update `pkg-config` to `pkgconfig`. 
I expect this will mean new bottles for chapel will be built and when that happens the sha256 values for all the bottles will need to be updated.
This PR only updates the formulas we use for testing homebrew and was not reviewed.
TESTING:

update homebrew formulas with changes from upstream

---

util/cron/load-base-deps.bash

Make the `util/cron/load-base-deps.bash` script no-op on subsequent runs after the first, to avoid unnecessarily reloading dependencies.
We have some cases in our network of interdependent `util/cron/common*` scripts that cause this script to get `source`d more than once. To prevent wasting time or encountering the occasional issues from loading Spack into the shell more than once ([1](https://github.com/spack/spack/issues/31275), [2](https://github.com/spack/spack/issues/40901), [3](https://cray.slack.com/archives/CGSFYJN86/p1732123044192589)), guard against re-running this script.
This is something of a workaround because we could also adjust our scripts to not ultimately call `load-base-deps.bash` more than once. However, that might be difficult due to how much interdependency and …

Prevent loading base dependencies more than once

---

runtime/src/chpl-gpu.c

Finding the halt flag on CPU doesn't do anything because there are no kernels. However, it also returns a non-null value (?!), which makes the runtime expect it to have been found. Since there are no kernels and therefore no globals on the CPU, just avoid looking for it altogether.

Fix halt-on-GPU failures in CPU-as-device-mode

---

compiler/resolution/cleanups.cpp
test/types/records/generic/generic-type-standalone-mention.chpl

They aren't used for anything, so deleting them is reasonable.
This fixes https://github.com/chapel-lang/chapel/issues/25885. The crux of that issue is that we incorrectly identify the `R` type as "unused", since it's generic but not used for any sub-classes and is never instantiated. I first attempted to fix the problem by adjusting `isUnusedClass` to respect `SymExprs` still in the tree that still point to the class. However, subsequent code __deletes all generic type declarations, because by that point we expect all occurrences to be concrete__:
```Chapel
new genericType(...); // replaced with a call to concreteType.init
var x: genericType = ...; // replaced with `var x: concreteType`
// the following:
proc foo(type arg) {}
foo(genericType)
// is replaced with:
proc foo() {}
foo();
``` …

Remove top-level `SymExpr`s from the AST

---

util/cron/common-hpe-cray-ex.bash

In https://github.com/chapel-lang/chapel/pull/23774, I unloaded `cray-libsci` from the environment, possibly to avoid some issues with GPU testing. With expanded testing on EX, we are seeing that we need that module for some BLAS tests. Testing it again, I am observing that some GPU tests are passing with that module loaded and BLAS tests work fine. So, I am removing the explicit unload to observe the behavior over a night's testing.

Keep cray-libsci in the EX testing environment

---

test/regex/ferguson/ctests/sub_test

After recent Spack changes, `CC` was being set to clang in some configurations, which conflicted to the `CXX` setting of a gnu compiler. Although only `CXX` is used for this test, chplenv complains about the mismatch. Resolve by setting `CC` analogously.
The specific situation hit was by Lydia, whose bashrc loaded an older spack setup that included LLVM 17 and didn't unset `CC`/`CXX`. It's still unclear why this started being hit after the recent LLVM 19 Spack upgrade, but in any case this test should probably not just fail when encountering a clang `CC`.
Testing:

Set `CC` in addition to `CXX` in regex ctests

---

frontend/CMakeLists.txt

This fixes a CMake configuration: after removing -ljemalloc from CHPL_LLVM_LINK_ARGS, the remaining string is
"-Lpath/to/chapel/third-party/jemalloc/install/host/linux65-x86_64-gnu/lib " (notice the trailing space). According to CMake policy CMP0004, this is not valid, so solve by simply stripping whitespace from the string manually.

Strip CHPL_LLVM_LINK_ARGS after removing jemalloc

---

frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testFieldAccess.cpp

Fix an incorrect ambiguity error when resolving an access to a field on a record variable that is itself a field.
The problem arose like this, using the added test case as an example:
1. In resolving `table.table`, we resolve a call with the name `table`. To find potential candidates we look up the name `table`, and find both the `var table: Bar` field on `Foo` and the `var table : int` field on `Bar`. At this point receiver type isn't considered.
2. We then filter candidates by applicability. For a field accessor, we were only checking a candidate's applicability based on if its name matches a name of a field on the correct receiver type. Both our candidates are named `table`, which is indeed the name of field on the receiver type `Bar`, so both are considered valid.
3. We have two valid …

Fix ambiguity resolving field on record var of same name

---

tools/chapel-py/setup.py

This fixes the generated rpath string for the python bindings shared library. There is a typo in the current version that creates separation and omits a comma from the linker flags format. This can cause a build error when installing Chapel in a prefix on some systems, like perlmutter. 

fix build error for python bindings on some systems

---

doc/rst/tools/mason/guide/environmentvariables.rst

Resolves Cray/chapel-private#6919
I had thought that adding a documentation comment to the new environment variable would mean it got documented, but it looks like Mason's documentation is more manual than that, so update that documentation explicitly.
Double checked the built documentation looked alright

Update the Mason environment variable documentation for MASON_LICENSE_CACHE_PATH

---

frontend/lib/uast/post-parse-checks.cpp
frontend/test/parsing/testParse.cpp
frontend/test/parsing/testParseChecks.cpp

This PR resolves a bug where during incremental compilation (as within the language server) the post-parse-checks are not run after the 1st revision. The problem was that the query framework only supports pointer arguments if the pointer refers to something that was returned from a query that returns `owned` (which is just `std::unique_ptr`) or similar on the heap. Otherwise, the pointer refers to a map entry, which might not change, even if the value does.
The fix is to make `checkBuilderResultQuery` accept a `const AstNode*` for the toplevel expression, which is pointer-ready. The loop that pulls top-level expressions out of a BuilderResult is just moved to the call site of `checkBuilderResultQuery`.
This PR also adjusts filenames used in `testParse` because these tests work with the …

Fix missing post-parse-checks errors in incremental compilation

---

util/cron/load-base-deps.bash

Reverts chapel-lang/chapel#26283
Unfortunately I found the previous change breaks tests with test scripts that contain a `module purge` followed by re-loading dependencies: https://github.com/chapel-lang/chapel/blob/831727315ba47bcd74ea283c9bcd9161f6039697/util/cron/common-hpe-apollo.bash#L11-L13
That's probably an undesirable pattern, but I don't expect to be able to fix it before code freeze, so to get configs that use this working again I'll have to back this out. Once we have the long-term solution of https://github.com/Cray/chapel-private/issues/6913 the original workaround won't be necessary anyways.
[reverting previous PR, not reviewed]

Revert "Prevent loading base dependencies more than once"

---

third-party/llvm/README
third-party/llvm/llvm-src/lib/Transforms/Vectorize/SLPVectorizer.cpp

Backports a fix for https://github.com/llvm/llvm-project/issues/112577 and https://github.com/llvm/llvm-project/issues/118410 to the bundled version of LLVM in our source tree.
Resolves https://github.com/chapel-lang/chapel/issues/26301

Backport LLVM 19.1.5 patch to bundled LLVM

---

compiler/llvm/llvmGlobalToWide.cpp

Fixes a version check protecting usage of `removeAttributes`, which was not added until LLVM 12 (and is not available in LLVM 11)

Fix LLVM version check for LLVM 11

---

compiler/main/driver.cpp
test/compflags/kushal/llvm-incremental.bad
test/compflags/kushal/llvm-incremental.compopts
test/compflags/kushal/llvm-parallel-make.bad
test/compflags/kushal/llvm-parallel-make.chpl
test/compflags/kushal/llvm-parallel-make.compopts
test/compflags/kushal/llvm-parallel-make.future
test/compflags/kushal/llvm-parallel-make.good

Throwing `-j` on a compilation results in `--incremental` being thrown as well, which is not supported by the LLVM back-end.  In issue #26326, Engin points out that the historical wording of the error generated in this case wasn't all that useful for those using '-j' who might not have any idea what the '--incremental' flag does or why they were getting the error.  This PR expands the error to specifically mention those flags as well when used, changes the error to a warning (it's not like your compilation won't work after all), and clones an existing future test to check that it fires and generates the right message in the new cases.
Resolves #26326.

Improve error when using -j with LLVM back-end

---

compiler/llvm/clangUtil.cpp

With CUDA 12.4, PIC is on by default in ptxas. However, with some large codes, we see that ptxas disables PIC and issues a warning about it. Most likely, we are not going to benefit from PIC anytime soon (I don't even know what it means for us to benefit from that.. Generated GPU code as shared library... for multiple Chapel applications?). So, disable PIC for the time being to squash warnings.
I will keep an eye on performance in the next couple of days just in case.
Resolves https://github.com/Cray/chapel-private/issues/6934
Test

Disable PIC for device code compiliation on NVIDIA

---

test/library/packages/Python/COMPOPTS

Fixes the compopts specified for a Python test to handle older Python versions.

Fix testing compopts for old python versions

---

make/compiler/Makefile.gnu

This PR adds `-Wno-psabi` to avoid a GCC warning on i386 along the lines of
```
the alignment of ‘_Atomic long long unsigned int’ fields changed in GCC 11.1
```

Avoid a warning for GCC on i386

---

modules/internal/ChapelLocale.chpl
modules/standard/GPU.chpl

This PR adds chapel doc comments for the `locale.gpuid` proc and `deviceAttributes` proc in the `GPU` module.

create better documentation for gpuId and gpu device attributes

---

CMakeLists.txt
doc/rst/conf.py
doc/rst/language/archivedSpecs.rst
doc/rst/usingchapel/QUICKSTART.rst
doc/rst/usingchapel/chplenv.rst
man/confchpl.rst
man/confchpldoc.rst
test/chpldoc/compflags/combinations/versionhelp-chpldoc.sh
test/compflags/bradc/printstuff/versionhelp.sh

This updates the version numbering throughout the codebase in advance of the 2.3 release.
See https://github.com/chapel-lang/chapel/pull/25957 for past release preparation changes.

set 2.3 to release status

---

runtime/src/chpl-launcher-common.c
util/test/chpl_launchcmd.py

Fixes the string manipulation code for checking which variables to forward to the system launcher (slurm/pbs).
Fixes an off-by-one error that was added in https://github.com/chapel-lang/chapel/pull/26281

Fix string maniuplation in environment forwarding

---

util/chplenv/printchplbuilds.py

Previously printchplbuilds.py was broken, probably by myself in #25875
Example:
```
$ ./util/chplenv/printchplbuilds.py
Traceback (most recent call last):
File "./util/chplenv/printchplbuilds.py", line 466, in <module>
main(sys.argv)
File "./util/chplenv/printchplbuilds.py", line 373, in main
build = Parse(path)
File "./util/chplenv/printchplbuilds.py", line 133, in Parse
var = varNames[state]
KeyError: <State.GASNET_VERSION: 11>
```

Fix printchplbuilds.py error on GASNET_VERSION

---

doc/rst/conf.py
doc/util/versionButton.php

This is the standard update at this point in the release cycle.

Update docs pulldown menu to mark 'docs/main' as 2.4 (pre-release)

---

CMakeLists.txt
man/confchpl.rst
man/confchpldoc.rst
test/chpldoc/compflags/combinations/versionhelp-chpldoc.sh
test/compflags/bradc/printstuff/version.goodstart
test/compflags/bradc/printstuff/versionhelp.sh

This updates the version number to represent version 2.4 with pre-release status. 
The previous PR taking us into 2.3 release was: https://github.com/chapel-lang/chapel/pull/26358
The PR for the previous pre-release update to version 2.3 is here: https://github.com/chapel-lang/chapel/pull/25981
TESTING: 
[reviewed by @tzinsky - thanks!]

update version to 2.4 pre-release

---

frontend/lib/resolution/InitResolver.cpp
frontend/lib/resolution/default-functions.cpp
frontend/test/resolution/testInitSemantics.cpp

Prior to this PR, default initializer arguments for multi-declaration fields did not themselves have default values. Let's say we have three fields declared in this manner: ``var a, b, c: int``. Each of these fields is an ``int`` and should have a default value of ``0``. Due to the way the frontend builds uAST, fields ``a`` and ``b`` did not directly contain a type expression or initialization expression from which a default value could be derived.
This PR updates the logic to correctly copy type expressions and initialization expressions, once encountered, to preceding fields lacking such expressions.
This PR also includes a small fix for generic field initialization, to resolve a bug with the ``Generics/initializersForGenericFields.chpl`` primer.
Testing:

Dyno: Fix default arguments for multi-decl fields

---

doc/rst/conf.py

Fixes a build issue with the chapel-py docs when a previous build had chapel-py and the current build does not.

Fix `make docs` in a dirty source tree with chapel-py

---

util/cron/test-gpu-cpu.bash

Adds a variant of the EX CPU-as-device test config that does not have to run on an EX.

Add variant of CPU-as-device test config

---

test/release/examples/gpu/hello-gpu.chpl
util/test/checkChplInstall

Fixes 'make check' with the GPU locale model. This was not working properly in some configurations, as the check script was expecting a NUMLOCALES file and a `.comm-none.good` file.
This PR also adjusts `hello-gpu.chpl` to calculate the correct result with GPU=cpu.

Fix 'make check' with the GPU locale model

---

test/performance/memory/microMemoryAllocation.execopts

Always use a smaller number of trials for a memory benchmark

Always use a smaller number of trials for a memory benchmark

---

frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/default-functions.cpp
frontend/lib/resolution/default-functions.h
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/types/Type.cpp

This PR generates uAST for ``init=``, ``deinit``, and ``(de)serializers)``, and cleans up some of the relevant implementations while we're at it. This PR also includes a couple of minor changes to either avoid crashes or fix bugs.
Testing:

Dyno: Generate function bodies for init=, deinit, and (de)serializers

---

util/chplenv/chpl_unwind.py

I recently was confused by `CHPL_UNWIND=libunwind` not seeming to work. It's because it should be `CHPL_UNWIND=bundled`. To make it easier to detect related problems in the future, this PR adds checking that `CHPL_UNWIND` is `none` `bundled` or `system` and otherwise emits an error in `printchplenv`.

Add checking that CHPL_UNWIND is a valid value

---

test/performance/memory/microMemoryAllocation.execopts

Adds a missing argument to an execopts file

Add missing argument to execopts

---

util/chplenv/printchplenv.py
util/chplenv/utils.py

Changes how `printchplenv` prints warnings so that the warnings are outputed last. 
Prior to this PR, `printchplenv` warnings could get lost if the terminal scrolled past. This PR puts the warnings last so that users can be more directly notified. The exception is in the error case. If there was an error and printchplenv is going to exit, all to the warnings are printed before the errors, so that users can see warnings that may have lead to the error being produced.
Note: if a user throws `--ignore-errors`, no warning buffering is done, otherwise `printchplenv` may crash without dumping the buffer out.
Testing:
- `CHPL_LLVM_VERSION=2 printchplenv --all` shows the warning at the bottom
- `CHPL_DEVELOPER=1 CHPL_TARGET_COMPILER=gnu CHPL_TARGET_CC=clang CHPL_LLVM_VERSION=2 printchplenv --all` …

Print `printchplenv` warnings at the end of the output

---

modules/standard/Math.chpl
test/library/standard/Math/bradc/lg2neg.compopts
test/library/standard/Math/bradc/lg2zero.compopts

Add a missing check for `boundsChecking` on a bounds check inside of `Math.log2`.

Guard bounds-checking in `log2` with `--checks`

---

test/chplenv/printchplbuilds/printchplbuilds-print1.prediff

Makes `test/chplenv/printchplbuilds/printchplbuilds-print1.chpl` work in more configs.
Namely, that the test now works regardless of the value of `CHPL_HWLOC` and also works with `CHPL_COMM=ofi`

Make printchplbuilds test work in more configs

---

third-party/qthread/README
third-party/qthread/qthread-src/include/qthread/qthread.h
third-party/qthread/qthread-src/src/io.c

Backporting two more performance fixes from https://github.com/sandialabs/qthreads/pull/314.

Backport More Qthreads Performance Fixes

---

test/ANNOTATIONS.yaml

Annotate backported qthreads perf fix from https://github.com/chapel-lang/chapel/pull/26328

Annotate backported qthreads perf fix

---

test/chplenv/chplconfig/warnings/notfound.chpl
test/chplenv/chplconfig/warnings/warnings.chpl

Fixes the whitespace for some tests which changed due to a change in how warnings are printed

Fix whitespace for tests for chplenv warnings

---

util/packaging/homebrew/chapel-release.rb

This updates our tracking formula for homebrew to match the version recently published with the 2.3 release. 
Trivial change to track homebrew released formula for testing - not reviewed.

update hombrew formula to match 2.3 release version

---

util/chplenv/chpl_llvm.py

Fixes an issue where having a system install of LLVM could prevent compiler builds with CHPL_LLVM=bundled.
This issue occurs when a system install of LLVM is in the normal C system includes, but then we treat our bundled LLVM as a system include. Since we were treating our bundled LLVM as a system include (added at the end of the list), the system LLVM headers were being erroneously used by the compiler.
The solution is to add bundled LLVM headers as system includes, but add them to the front of the list instead of the end.
Related previous PR: https://github.com/chapel-lang/chapel/pull/26212

Fix CHPL_LLVM=bundled build when a system LLVM is installed

---

test/chplcheck/.gitignore
test/chplcheck/CLEANFILES
test/chplcheck/Unused.chpl
test/chplcheck/Unused.good
test/chplcheck/UnusedTupleUnpack.chpl
test/chplcheck/UnusedTupleUnpack.good
test/chplcheck/UnusedTupleUnpack.good-fixit
tools/chplcheck/src/rules.py

Fixes an issue where the linter was warning for an UnusedTupleUnpack on `proc foo((x, y))`. Fixing this issue then uncovered a few issues in the handling of tuple unpacks in UnusedFormal, also fixed in this PR.
Tested by running `start_test test/chplcheck`

Fix linter checking for a tuple unpack in a formal

---

.github/workflows/CI.yml

Adds a Github Actions CI check that errors if an unusually large file is introduced in any commit on a PR.
The limit for a "large" file is set to 1MB as a reasonable estimate.
Resolves https://github.com/Cray/chapel-private/issues/4295.
Testing:

Add Github Actions check for new large files

---

.github/workflows/CI.yml

Prevent the new-large-files check from checking the commit being merged into, which caused an error when trying to retrieve its parent.
Follow up to https://github.com/chapel-lang/chapel/pull/26371.

Don't check base commit in large files check

---

modules/packages/Python.chpl

Fixes an issue where in the Python interop module that causes `PYTHONHOME` to be set in some python virtual environments. This would prevent any code using the Python module from running.
This code was intended to make for nicer error messages from the python interpreter, but it did not achieve that goal (so the code was mostly useless) and it messed up some python environments (i.e. conda), so it should be removed.

Make Python interop module more resilient to different python environments

---

runtime/src/topo/hwloc/topo-hwloc.c

Removes the early-out variables `haveTopology`. This resolves https://github.com/chapel-lang/chapel/issues/26405.

Remove early-out in runtime topo layer

---

configure

Currently every Chapel `configure` I run on Linux (regardless of whether or not I pass `--prefix` or `--chpl-home`) prints the following spurious error to the console as the first line of output:
```
pathchk: '': No such file or directory
```
This spurious output appears to be a completely harmless/cosmetic defect. However given that it occurs so early in the build it also means that every time a Spack build of Chapel fails this spurious line of output gets printed as the first detected error in Spack's error summary, which is unfortunate because it's completely a "red herring".
Source inspection reveals the scripting here appears to be Just Plain Wrong: there's a `pathchk` command that is being passed garbage and doesn't accomplish its apparent intended purpose of validating the …

Fix spurious pathchk error output from configure

---

frontend/include/chpl/types/CompositeType.h

Fix an almost certainly not intended not-equals comparison of `name`s in `compositeTypeContentsMatchInner`.
Introduced in https://github.com/chapel-lang/chapel/pull/19109.
Noticed by @DanilaFe .
Testing:

Fix not-equals in `compositeTypeContentsMatchInner`

---

man/chpl.rst
test/compflags/bradc/help/userhelp.good
util/chpl-completion.bash

Fixes the `--help` and man page output after changing `--mem` to `--target-mem`

Fix `--help` and man page output for `--target-mem`

---

test/studies/shootout/submitted/binarytrees-submitted.graph
test/studies/shootout/submitted/binarytrees5.chpl
test/studies/shootout/submitted/binarytrees5.good
test/studies/shootout/submitted/binarytrees5.perfexecopts
test/studies/shootout/submitted/binarytrees5.perfkeys

This belatedly adds a copy of the binarytrees5.chpl benchmark that Jade submitted after the 2.2 release to our submitted directory to track its performance going forward.

Add a copy of binarytrees5.chpl to our submitted directory

---

.github/workflows/CI.yml

Previously failed due to trying to go all the way back to what Github calls the "base" SHA, which turns out is what we'll merge on top of rather than the parent of the first commit in the PR.
Follow up to https://github.com/chapel-lang/chapel/pull/26371.

Handle PRs not based off recent main in large files check

---

util/packaging/docker/test/Dockerfile
util/packaging/docker/test/brew_install.bash
util/packaging/homebrew/chapel-main.rb

This fixes the `homebrew-linux` testing that was broken by a merge conflict when applying the copy of `chapel-main.rb` to the repo for testing. The solution was to change the order of operations so the repo is updated before our new file is copied in. 
Other changes include re-enabling more brew test-bot commands and removing the deletion of the `fltk` sources as they were removed from our third-party directory recently.
TESTING:

fix homebrew-linux test that encountered merge conflict

---

util/cron/common-champs.bash

This PR is an attempt to fix spreading OOM errors with CHAMPS using the C backend.

Try an older version of GCC on CHAMPS testing

---

doc/rst/technotes/throwingInit.rst
modules/packages/DistributedBag.chpl
test/studies/amr/lib/amr/AMRHierarchy_def.chpl

While reading up on the status of throwing initializers, I was surprised to find its technote still refers to 'this.complete();' rather than 'init this;'.  This PR primarily updates that documentation, though I also updated a few (seemingly innocuous) cases that were still using `this.complete()` based on a `git grep`.

Update docs to use 'init this;' rather than 'this.complete();'

---

test/distributions/bradc/extremeBlock.skipif

Our darwin testing machine cannot handle 32 locales under gasnet with segment=fast, so skipif
the test `test/distributions/bradc/extremeBlock.chpl` in that configuration.
For the record, fourteen locales report this:
```
internal>: error: Out of memory allocating "tasking layer unspecified data"
```
Not reviewed. Supported by Brad.

Skipif 'extremeBlock' under gasnet/fast on darwin

---

test/runtime/jhh/numColocales2.skipif

`test/runtime/jhh/numColocales2.chpl` should be skipped with launchers that do not support co-locales.
Resolves https://github.com/Cray/chapel-private/issues/6981.

Skip test with launchers that do not support co-locales

---

compiler/resolution/initializerResolution.cpp

OK, well this is embarrassing.  Despite asserting in the PR message of #26430 that my throwing postinits would do the same thing as throwing inits do, apparently I never actually ran testing with memleaks turned on to make sure that no memory was leaked when a postinit throws, and...  Well, it was.  (Not a defense, but I had inspected the generated code and seen that we were emitting some code to handle its thrown errors, but didn't look closely enough to see that that handling didn't actually do any clean-up, just propagated the error and exited the routine).  Sloppy.
Here, I'm fixing my issue by tucking the call to postinit() into the same try...catch block as the throwing initializer code is put into (when either of them throws), which causes it to inherit the same outcomes, which is …

Close memory leak caused by throwing postinits

---

runtime/src/launch/slurm-gasnetrun_common/slurm-gasnetrun_common.h
runtime/src/launch/slurm-srun/launch-slurm-srun.c

This safeguards spaces and most other symbols in the arguments passed to a compiled Chapel program that uses a slurm launcher, where such a safeguard was missing. For example:
```
./myProgram --myString='Hello, world!'
```
used to behave as if it were `./myProgram --myString=Hello, world!`, i.e., `world!` would be passed as a separate argument to `myProgram_real` when launched with slurm.
This is a stopgap solution to ensure that the test augmented in #26439 passes in slurm configurations. It is not bullet-proof because user arguments containing single quotes and/or backslashes will not be passed through properly.
Next steps: #26381 eliminates static limits on the size of user arguments. In the long run we want to switch from launching using `system()`, when quoting may be necessary, to …

Quote user arguments passed to slurm launchers

---

test/runtime/jhh/numColocales2.skipif

This test requires two co-locales.
[Trivial change to test configuration, not reviewed.]

Skip multi-locale test if CHPL_COMM==none

---

tools/chplvis/Makefile

This PR addresses problems building chplvis when Spack is managing dependencies. We were facing a situation where returned by `fltk-config` a compiler path that didn't exist anymore.

Adjust chplvis makefile to use CHPL_MAKE_HOST_CXX

---

tools/chpl-language-server/src/chpl-language-server.py

Fixes a typo in the error reporting for `chpl-language-server` when `CHPL_DEVELOPER` is set

Fix typo in chpl-language-server debug output

---

compiler/passes/initializerRules.cpp
test/classes/initializers/inheritance/duplicate-super-init.chpl
test/classes/initializers/inheritance/duplicate-super-init.good

Fixes an internal error when `super.init()` appears twice in a initializer and replaces it with a nicer error
Testing

Fix internal error when erroneously writing `super.init` twice

---

util/chplenv/chpl_llvm.py
util/chplenv/overrides.py

Adds the ability to infer `CHPL_LLVM_GCC_INSTALL_DIR`. Resolves https://github.com/chapel-lang/chapel/issues/25925
This PR uses similar logic to the LLVM spack package to determine this. Thanks @PHHargrove for the pointer to this.
Testing
This PR also adds a missing line to `overrides.py` for `CHPL_LLVM_GCC_INSTALL_DIR`

Add ability to infer CHPL_LLVM_GCC_INSTALL_DIR

---

frontend/test/resolution/testPromotion.cpp

In production, the issue (presumably) persists. However, in Dyno everything looks like it works as we'd expect. So, locking down the test case to ensure subsequent changes to Dyno don't break it.

Dyno: add test for issue #11225

---

frontend/test/resolution/testInteractive.cpp
frontend/util/analyze-query-trace

This PR makes a small fix to the timing script, and adjust `testInteractive` to allow saving timing information across generations.
The fix to the timing script avoids division by zero (which happens often on my machine). I've run into the issue many times, but each time neglected to submit a simple fix. 
The change to `testInteractive` adds a new `--time-all-generations` switch to `testInteractive` which configures it to continue gathering query timings across generations, rather than saving the latest generation's timing and discarding others. This way, it's possible to measure the impact of changes to the query system on performance.
My sample script to gather performance switching back and forth between two files:
```bash
#!/bin/bash
pipe=/tmp/testpipe
if [[ ! -p $pipe ]]; then
mkfifo …
```

Dyno: fixes to timing script and infrastructure

---

frontend/lib/resolution/disambiguation.cpp
frontend/test/resolution/testVarArgs.cpp

This fixes an issue discovered in domain module code, in which the following program was considered to be ambiguous:
```Chapel
proc foo(x...) {}
proc foo(x: integral) {}
foo(10);
```
This program is not _actually_ ambiguous, which can be seen by making an appeal to "desugaring" of the vararg version to its non-vararg form:
```Chapel
proc foo(x) {}
proc foo(x: integral) {}
foo(10);
```
The first version of `foo` is fully-generic, while the second is more constrained (it requires an integral type). As a result, the second version is more specific. Dyno didn't detect this because generic vararg formal are given generic tuple types, while the "is fully generic" check was looking for any type. Adjust this by detecting vararg formals and changing the check accordingly.
Reviewed @arezaii -- …

Dyno: fix disambiguation between fully-generic vararg and less generic non-vararg.

---

frontend/test/resolution/testDeprecationUnstable.cpp
frontend/test/resolution/testTypeConstruction.cpp
frontend/test/test-common.cpp
frontend/test/test-common.h
tools/chapel-py/src/method-tables/core-methods.h

This incurs a penalty up front, but prevents odd ordering properties in the query system. It's a workaround for a query system bug detailed in https://github.com/chapel-lang/chapel/pull/26459.
This way, cycles in the standard module dependency graph are always visited in the same order (starting with `ChapelBase`). As a result, we don't create cycles over multiple generations. This workaround does not prevent the issue from occurring in other contexts, such as user projects with circular dependencies. 

Dyno: Resolve auto module visibility statements eagerly

---

third-party/qthread/README
third-party/qthread/qthread-src/include/qthread/qthread.h
third-party/qthread/qthread-src/src/io.c

Partially reverts a Qthreads patch from #26328 which resulted in a performance penalty. The patch was meant to fix some performance regressions, but instead caused more than it helped.
This PR only reverts the changes to the definition of MACHINE_FENCE.
Closes https://github.com/chapel-lang/chapel/issues/26440

Partially revert Qthreads patch from #26328

---

util/chplenv/chpl_llvm.py

Fixes compiler build issues when using a system LLVM that is different than the standard LLVM. For example, an LLVM installed at `/usr/` would conflict with an LLVM installed at `/home/user/llvm-install` (which was accessed by `CHPL_LLVM_CONFIG=/home/user/llvm-install`)
Subsumes https://github.com/chapel-lang/chapel/pull/26212 and https://github.com/chapel-lang/chapel/pull/26402
Previous work had tried to take advantage of various clang/gcc flags to achieve the right behavior, however this not working in all cases. This PR does following.
1. computes the existing search paths for the compiler
2. for each LLVM include directory specified as `-I`
- In a bundled LLVM build: always use '-isystem'
- In a system LLVM build: use '-isystem' if its not an existing search path, otherwise use '-I' …

Fix issues with using a non-default system LLVM with CHPL_LLVM_CONFIG

---

test/extern/ferguson/bug-global-c-array.skipif

Adds a skipif for a future test which has a different failure mode with the C backend

Add skipif for future test

---

compiler/AST/AstDump.cpp
compiler/AST/AstDumpToHtml.cpp
compiler/codegen/cg-symbol.cpp
compiler/codegen/codegen.cpp
compiler/codegen/library.cpp
compiler/include/driver.h
compiler/include/files.h
compiler/include/library.h
compiler/include/log.h
compiler/include/stringutil.h
compiler/llvm/clangUtil.cpp
compiler/main/arg.cpp
compiler/main/driver.cpp
compiler/main/log.cpp
compiler/resolution/functionResolution.cpp
compiler/util/files.cpp
compiler/util/misc.cpp
compiler/util/stringutil.cpp

Removes usages of `FILENAME_MAX` and other hardcoded buffers for path strings, enabling the use of arbitrarily long file paths.
This PR has the same purpose as https://github.com/chapel-lang/chapel/pull/17517, but isn't based off of it as the prior PR was too far behind main.
Resolves https://github.com/chapel-lang/chapel/issues/26261 and contributes to https://github.com/chapel-lang/chapel/issues/8757.
Testing:

Allow arbitrary path lengths in compiler

---

test/ANNOTATIONS.yaml

arkouda tests on 16-node-xc ran with --isolated between 12/25/24 and 1/1/25
Nightly job was configured to run off of: https://github.com/chapel-lang/chapel/compare/main...vasslitvinov:chapel:arkouda-server-per-test

annotate arkouda tests running with --isolated

---

doc/rst/technotes/gpu.rst
util/chplenv/chpl_gpu.py

Require a minimum version of CUDA, 11.7, for building the compiler/runtime with CHPL_GPU=nvidia

Require a minimum of CUDA 11.7 for CHPL_GPU=nvidia

---

doc/rst/language/spec/types.rst
util/devel/chplspell-dictionary

A quick PR to replace Kissinger with Plato.

Enum docs patch

---

modules/standard/MemDiagnostics.chpl
runtime/include/chplmemtrack.h
runtime/src/chplmemtrack.c

We observed some issues with building the runtime on 32-bit systems. This is a fallout from https://github.com/chapel-lang/chapel/pull/26118.
This PR addresses the issue, which was about pointer sizes. While there, I also adjusted a size variable to have `size_t` type for better conformance to standards/conventions. The Chapel wrapper `allocations` still casts things to `uint`, so I don't expect any behavioral change for the user.
Test:

Fix some issues with 32-bit builds on allocations support

---

runtime/src/launch/aprun/launch-aprun.c

Remove some very old (2012) commented-out code containing a use of `FILENAME_MAX`.
Found this doing a final grep for any uses of `FILENAME_MAX` for https://github.com/chapel-lang/chapel/issues/8757.
Follow up to https://github.com/chapel-lang/chapel/pull/26381.

Remove commented sysFilename var with FILENAME_MAX

---

frontend/include/chpl/resolution/scope-types.h
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/resolution-types.cpp
frontend/lib/resolution/scope-queries.cpp
frontend/lib/resolution/scope-types.cpp
frontend/test/resolution/testResolve.cpp
test/deprecated/dmapType.good
test/errors/scope-resolution/redefinition/parenless-and-parenful-fns.1.good
test/errors/scope-resolution/redefinition/parenless-and-parenful-fns.2.good
test/functions/bradc/resolution/arrayVsFn.good

This is a precursor to another PR, which enables resolution of more of the domain module code, and finds this curious case that doesn't work in Dyno:
```Chapel
proc foo(x: int) {}
proc bar(foo: (int, int)) {
var res = foo(0);
}
```
In production, we expect the call to `foo` in the body of `bar` to be a tuple element access, but dyno incorrectly attempts to perform full function resolution. This is difficult since the inner `foo` is not a function.
In production, we resolve this problem by stopping the search for functions when we encounter a variable. In the case of an innermost variable, this is sound since variables are not overloaded or disambiguated (innermost is preferred). In the case of functions, this is sound because any functions defined _after_ the variable during the search …

Dyno: Fix (callable variable, function) disambiguation

---

frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testLoopIndexVars.cpp

Closes https://github.com/Cray/chapel-private/issues/6923.
Depends on https://github.com/chapel-lang/chapel/pull/26454, https://github.com/chapel-lang/chapel/pull/26455 and https://github.com/chapel-lang/chapel/pull/26456 because this causes more Domain methods to be resolved.
The issue was in resolving code like this:
```Chapel
class C {
var x: int;
var y: string;
iter type myIter() {
yield 3;
yield 5;
yield 7;
yield 11;
}
}
for i in C.myIter() do
writeln(i);
```
Previously, dyno incorrectly set `isMethod` to be false, which made the `this` formal for methods to be incorrectly set. This PR adjusts this behavior to correctly track method calls when resolving iterator overloads.

Dyno: fix iterator type methods

---

modules/packages/Python.chpl
test/library/packages/Python/correctness/basicTypes.chpl
test/library/packages/Python/correctness/customType.chpl
test/library/packages/Python/correctness/iteratorTest.chpl
test/library/packages/Python/correctness/iteratorTest.good
test/library/packages/Python/examples/torch/myModel.chpl

Refactors the Python interop module to use inheritance to model Python types. This is a more maintainable and cleaner API than the original prototype.
Testing

Refactor the Python interop module to use inheritance

---

compiler/util/files.cpp
runtime/src/launch/slurm-srun/launch-slurm-srun.c

Fix a handful of errors made in removing `FILENAME_MAX` from the compiler and runtime.
Follow up to https://github.com/chapel-lang/chapel/pull/26357 and https://github.com/chapel-lang/chapel/pull/26381.
[trivial fixes, not reviewed]
Testing:

Fix mistakes from removing `FILENAME_MAX`

---

doc/rst/platforms/windows.rst

Changes the wording around Windows/WSL install information for packages.
I encountered a user who was attempting to install Chapel for multi-locale execution with GASNet. They were building from source (I think thats just because what they were directed to), but they could have just installed the package and saved a lot of time. This made me wonder if our docs should mention the Linux packages on WSL, and I found they do but they also said only shared memory was supported. This PR updates that wording.

Change wording for Windows/WSL packages in docs

---

test/runtime/jhh/numColocales.chpl

`exit(0)` currently doesn't work with `CHPL_LAUNCHER=slurm-srun` and `CHPL_COMM=ofi`, so avoid it.

Modify to avoid `exit(0)`

---

compiler/codegen/cg-symbol.cpp

Removes a workaround for calling functions from an AMD GPU kernel.
This was added in https://github.com/chapel-lang/chapel/pull/22002, but seems to no longer be required. This was causing an LLVM assert to hit when marking a function as both having external linkage and being marked hidden: https://github.com/chapel-lang/chapel/issues/26424
resolves https://github.com/chapel-lang/chapel/issues/26424
Testing

Remove `setVisibility(hidden)` on functions called from AMD kernels

---

compiler/include/vec.h

Fixes a build error with CHPL_DEVELOPER=1 and gcc 14, caused by a warning from gcc. Removing the offending code does not seem to affect correctness
resolves https://github.com/chapel-lang/chapel/issues/26488

Fix CHPL_DEVELOPER build with gcc 14

---

util/cron/test-docker.bash

Fix the check in `util/cron/test-docker.bash` that ensures we're working from the desired release branch when in release mode.
When run in the Jenkins job, this check failed despite having the correct revision checked out. This is because for some reason Jenkins (or the SCM plugin we use, or JJB, not sure) takes the branch you ask to check out, manually dereferences it to the commit it points to, and then checks out that commit by SHA. So `HEAD` points to a SHA rather than the branch name, and `git rev-parse --abbrev-ref HEAD` just returns `HEAD`.
Fixed by comparing the SHA of `HEAD` against the SHA of the desired branch directly.
Testing:

Adjust test-docker release branch check for Jenkins quirk

---

doc/rst/technotes/gpu.rst
test/gpu/native/assertOnFailToGpuizeAttr.chpl
test/gpu/native/assertOnNotGpuEligible.chpl

That test specifically made use of the old, functional form of `assertOnGpu`, and was deleted when that form was removed. However, a couple of comments and the tech note still referenced it. Fix that.

Fixup docs and comments after removal of `assertOnFailToGpuize`

---

test/gpu/native/examples/amd-training/README.md
test/gpu/native/examples/amd-training/basic.chpl

I am going to share this very simple GPU example for a very high-level GPU training slide. This PR checks the code in as a nightly test.

Add a simple GPU example used in a training slide

---

doc/rst/technotes/gpu.rst

An initial prototype of GPU-based halting was implemented in https://github.com/chapel-lang/chapel/pull/26232. This adds documentation for it.

Add a section to tech note about GPU-based halting

---

test/gpu/native/.gitignore
test/gpu/native/deviceAttributes.cleanfiles
test/gpu/native/queryLocaleId.prediff
test/gpu/native/studies/.gitignore
test/gpu/native/varInInnerBlock.prediff

Adds a few missing `.gitignore` and `.cleanfiles` for some GPU tests. This makes sure running `start_test` does not leave behind a bunch of files and dirty the tree

Make sure gpu testing cleans up after itself

---

modules/dists/StencilDist.chpl

The new wording is heavily based on an example provided by Damian. Thanks!

Improve stencilDist documentation

---

util/test/sub_clean

Fixes a usage of `shutil.rmtree` in `sub_clean`, per the [Python docs](https://docs.python.org/3/library/shutil.html#shutil.rmtree) it should not be called on symlinks.
This was causing `sub_clean` to silently fail to delete symlinks to directories, which failed silently due to the `try`/`catch`/`pass` surrounding the code

Fix usage of shutil.rmtree on a symlink in sub_clean

---

test/chplcheck/SKIPIF
test/chplcheck/fixit-interactive/SKIPIF
test/chplcheck/rule-settings/SKIPIF
third-party/chpl-venv/Makefile
tools/chpl-language-server/Makefile
tools/chpl-language-server/chpl-language-server
tools/chpl-language-server/chpl-shim
tools/chpl-language-server/src/chpl-language-server.py
tools/chplcheck/chplcheck
tools/chplcheck/examples/SKIPIF
tools/chplcheck/src/chplcheck.py
tools/chpldoc/findUndocumentedSymbols
tools/chpldoc/findUndocumentedSymbols.py

This PR changes some scripts to ensure all chapel-py based tools always use the same python, i.e. the one from `find-python.sh`. 
We were slightly inconsistent about this before, which meant that if `find-python.sh` returned a different python version than the default `python3` version, runtime errors would occur. This is unlikely to happen to users, since to expose this issue you need to edit `find-python.sh` to return specific versions of python (i.e. `python3.12` instead of `python3`)

Make sure chapel-py based tools always use the same python

---

modules/internal/LocaleModelHelpRuntime.chpl
test/deprecated/taskYield.chpl
test/deprecated/taskYield.good

Deprecations were introduced by the following PRs:
* https://github.com/chapel-lang/chapel/pull/22883
Which occurred more than 6 months ago.
Reviewed by @jhh67 -- thanks!

Delete deprecated 'chpl_task_yield' function

---

modules/standard/CTypes.chpl
test/types/cptr/c_ptrTo_domain.3.good
test/types/cptr/c_ptrTo_domain.4.good
test/types/cptr/c_ptrTo_domain.chpl
test/types/cptr/c_ptrTo_domain.compopts
test/unstable/c_addrOf-domain.chpl
test/unstable/c_addrOf-domain.good

Add unstable overloads of `c_addrOf`/`c_addrOfConst` which take domain arguments.
Eventually (in >=2 releases) these should be made stable if no blocking issues are encountered. At that point we can just remove the error from the main overload, and remove these new overloads.
Includes adding tests for the new unstable functionality.
Resolves https://github.com/Cray/chapel-private/issues/6971.
Testing:

Add c_addrOf[Const] on domain unstable overloads

---

modules/packages/Python.chpl
test/library/packages/Python/examples/numba/apply.chpl

Fixes a few more linux 32 tests for Python, mostly this was due to a mismatch between int/long/size_t.
Follow on to https://github.com/chapel-lang/chapel/pull/26504.

Bundle of 32-bit fixes for Python tests

---

modules/standard/IO.chpl
test/regex/ferguson/extractMatches.chpl
test/regex/ferguson/extractMatches.compopts
test/regex/ferguson/extractMatches.good

Adds an overload of `fileReader.extractMatches` that returns a value, instead of modifying a ref argument. This new overload is unstable, pending a design discussion about it.
This PR also fixes a bug where trying to extract a non-string/bytes value from a match would not compile.
Testing

Add unstable `extractMatches` overload that returns a value

---

modules/standard/Version.chpl
test/library/standard/Version/compareVersionTypes.chpl
test/library/standard/Version/compareVersionTypes.good
test/library/standard/Version/versionCastIsParam.chpl
test/library/standard/Version/versionCastIsParam.good

The deprecated code here precedes the existence of @ deprecated, and thus is over 6 monts old.
The PRs that introduced `versionValue` (versus `sourceVersion`):
* https://github.com/chapel-lang/chapel/pull/21088
Sorry, didn't mean to ping anyone :-) 

Remove deprecated code from Version

---

modules/standard/Errors.chpl
test/deprecated/cpSplittingError.chpl

This is removed in favor of 'CodepointSplitError'.
Deprecations were introduced by the following PRs:
* https://github.com/chapel-lang/chapel/pull/22678
This occurred 2023, which is longer than our deprecation period.

Remove deprecated 'CodepointSplittingError'

---

modules/packages/Python.chpl

Fixes some cases broken by adding `safeCast` to the Python module when fixing linux32 testing. The fix broke linux64.

Adjust calls to safeCast in Python interop module for orderToIndex

---

doc/rst/language/spec/types.rst
modules/standard/Types.chpl

They were deprecated in https://github.com/chapel-lang/chapel/pull/21108 and removed from the compiler in https://github.com/chapel-lang/chapel/pull/23957 Even the removal was more than 6 month ago.

Remove (signatures of) deprecated type comparison operators

---

test/chplcheck/PREDIFF
tools/chplcheck/examples/PREDIFF

Remove the non-portable realpath from chplcheck tests, replacing it with a `cd ...; pwd`
Tested on MacOS and Linux

Remove the non-portable realpath from chplcheck tests

---

test/studies/champs/sub_test
util/cron/common-champs.bash

https://github.com/chapel-lang/chapel/pull/26433 tried to pin an older GCC to avoid [CHAMPS' compilation OOM issues](https://github.com/Cray/chapel-private/issues/6529). That did not help. This PR adds `potential` to the blacklist, and reverts https://github.com/chapel-lang/chapel/pull/26433.

Revert pinning GCC version for CHAMPS testing, stop testing potential

---

frontend/lib/parsing/bison-chpl-lib.cpp
frontend/lib/parsing/chpl.ypp
tools/chpl-language-server/test/highlight.py

Fixes the name location reporting for "if var" and catch statements. This fixes issues with the language server, where more than the symbol name would be highlighted.
Cases fixed
```chapel
if const x = 10 { ... }
try { ... }
catch err: Error {  }
```
Testing

Fix the name location reporting for "if var" and catch statements

---

doc/rst/usingchapel/QUICKSTART.rst

Updates the note about cmake being required int the quickstart instructions, since its already a general prereq.

Remove cmake note in quickstart instructions

---

frontend/lib/resolution/can-pass.cpp
frontend/test/resolution/testClasses.cpp

This change allows for the passing of an 'anymanaged' child class type to an anymanaged type formal constrained by the child's parent type. For example:
```
proc test(type T: Parent) { }
test(Child);
```
Note: Within the body of ``test``, the formal ``T`` will be of type ``Parent``.
The implementation itself modifies our "can pass" logic to always instantiate when passing a valid actual type to an anymanaged formal type, even if the actual itself is 'anymanaged'.
A test is added to lock in this behavior.
Testing:

Dyno: Passing anymanaged child to type formal constrained by parent type

---

.github/workflows/monitor-homebrew.yml

This adds a github action to periodically or manually check the homebrew repo for updates they may have made to our chapel formula. Monitoring this allows us to keep the formula we test main against up to date with new changes the homebrew devs may make.
Currently this runs in a Jenkins job once per night, but just alerts us to the change and requires a user to create the PR. Doing it in a github action should allow the github bot to create the PR for us. 
Future Work TODOs: 
- It might be nice to have another companion action that deletes branches created by this bot after they are merged.
- We might want to notify some set of users if this action runs and finds an existing branch, as a reminder to merge the PR.
[reviewed by @tzinsky - thanks!]

add gh action to monitor homebrew repo

---

compiler/passes/convert-typed-uast.cpp
frontend/include/chpl/types/DomainType.h
frontend/include/chpl/types/QualifiedType.h
frontend/include/chpl/uast/prim-ops-list.h
frontend/lib/resolution/InitResolver.cpp
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/VarScopeVisitor.cpp
frontend/lib/resolution/VarScopeVisitor.h
frontend/lib/resolution/call-init-deinit.cpp
frontend/lib/resolution/prims.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/return-type-inference.cpp
frontend/lib/types/DomainType.cpp
frontend/lib/types/QualifiedType.cpp
frontend/test/resolution/testDomains.cpp

Get associative domain type expressions resolving using their module code in Dyno, and re-enable testing for them.
This PR itself contains little work and mostly just drove Dyno work needed to support the module code.
Contributes to https://github.com/Cray/chapel-private/issues/6729.
Also includes:
- adding a dyno test for _rectangular_ domain literals
- allowing `helpResolveFunction` to run on generic type constructors, per bug fix suggestion from Ben
- adjusting the handling of `param == ?` comparisons which was introduced in https://github.com/chapel-lang/chapel/pull/26219, so that it gets specially handled rather than trying to resolve a defined `==` operator
- skipping recursing into `TupleDecl`s in `VarScopeVisitor` to delay [implementing call-init-deinit support for …

Resolve associative domain type expr module code in Dyno

---

util/cron/test-hpe-cray-ex-ofi.bash

Remove the -examples argument to nightly so the complete test suite is run.

Run complete test suite on HPE Cray EX

---

modules/packages/Python.chpl
modules/packages/PythonHelper/ChapelPythonHelper.h

Fixes to small issues added in a recent PR to the Python interop module
- Py_INCREF on some systems is a macro
- `throws` was missing on a new init overload

Fix two issues with python interop module

---

util/cron/common-arkouda.bash

This PR bumps the Chapel release version Arkouda's nightly testing uses to 2.3.
Resolves https://github.com/Cray/chapel-private/issues/7027

Bump Arkouda release version to 2.3

---

frontend/lib/resolution/Resolver.cpp
frontend/test/resolution/testLoopIndexVars.cpp

This PR implements a missing piece of functionality required by the standard library: `for param` loops over `by`-strided ranges. While there, I noticed that it was quite easy to extend the logic to other situations (more specifically `#` and unbounded ranges). The result is a more general implementation of `for param` iteration.
This is not a "true" implementation, in the sense that it doesn't handle the myriad of behaviors of ranges and striding. Doing so would effectively require a re-implementation of the standard library's range operators, which is a nontrivial amount of work; moreover, what this PR provides is already (or should be) more powerful than production.
Also while there, I modified the test to make it easier to express how the Chapel behavior should correspond to a (C++) …

Dyno: resolve param loops over more range shapes

---

frontend/include/chpl/types/Type.h
frontend/lib/resolution/call-init-deinit.cpp
frontend/lib/resolution/prims.cpp
frontend/lib/types/CompositeType.cpp
frontend/lib/types/Type.cpp
frontend/test/resolution/testResolve.cpp

Implement a few primitives in Dyno, needed for https://github.com/chapel-lang/chapel/pull/26534:
- `scalar promotion type`
- `needs auto destroy`
- `_wide_get_locale`
Adds testing for all except `needs auto destroy`, as its logic is very closely copied from production.
Testing:

Implement various primitives in Dyno

---

test/execflags/gbt/getenv.chpl

`c_string` is no longer defined.

Fix test outdated due to c_string removal

---

modules/internal/ChapelDomain.chpl

Dyno can't yet handle skipping resolving things after (param) conditional returns. So,
```Chapel
if bla then
compilerError("");
foo();
```
Will always resolve `foo()`. Module code does not expect that to be the case. 
Fortunately, Dyno supports `if-else` param folding, so switch the code to use `else`.

Adjust domain module code to make it easier for Dyno

---

util/cron/load-base-deps.bash

Update `util/cron/load-base-deps.bash` to use the location of the new Spack install on `chapcs`/`chapvm` machines.
For https://github.com/Cray/chapel-private/issues/7022.

Update load-base-deps for new chapcs Spack location

---

frontend/include/chpl/types/BasicClassType.h
frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testInterfaces.cpp

Depends on https://github.com/chapel-lang/chapel/pull/26396.
This PR implements return type checking for interfaces. To fit that nicely into the existing structure, it separates the main "find function that matches the given interface requirement" into pieces (building the call, picking a candidate, checking the formals, return type, and return intent). From there, it implements the rules as currently specified in `interfaceResolution`.
The rules are as follows:
For types:
* For iterators, we check the yield type of the iterator, since calls to different `iter` procedures produce distinct _return_ types.
* Otherwise, we expect an exact match of the return type, with the one exception...
* When using a promoted call to satisfy an interface constraint (allowed in production), we require …

Dyno: check return types when validating interface constraints

---

test/compflags/bradc/minimalModules/SKIPIF
test/types/coerce/ferguson/coercion-dispatch-minimal-modules.skipif
tools/chpl-language-server/src/symbol_signature.py

These have been causing nightly failures in some corner cases. I had to use `extern` blocks to use strings with minimal modules (which requires LLVM), and I neglected `CStringLiteral` in CLS because it didn't show up as a (C++) use of the now-removed AST node.

`c_string` removal fixes

---

modules/packages/Python.chpl

Add a missing safeCast to Python module

Add a missing safeCast to Python module

---

test/scan/scanPerf.chpl

Now considers the number of co-locales on the node when determining the problem size.
Resolves https://github.com/Cray/chapel-private/issues/7016.

Scale the problem size by the number of co-locales

---

frontend/test/resolution/testDomains.cpp

Enable testing of associative domain literals in Dyno.
With some concurrent work done on `main`, no changes are needed in this PR to get the tests passing.
Testing:

Resolve associative domain literals

---

test/setchplenv/verify_setchplenv_scripts.py

Adjust test script to skip testing csh if csh is not installed

Skip csh test if csh is missing

---

test/studies/champs/sub_test

`potentialPrep` is the next victim for the C backend OOM issues when testing CHAMPS. This PR skips that test.

Skip potentialPrep with CHAMPS+C testing, too

---

modules/Makefile
modules/minimal/internal/CTypes.chpl
util/config/make_sys_basic_types.py

The removal of C strings and C string literals from Dyno required changes to some minimal module tests; in particular, it required representing C strings the way C represents them -- as pointers to characters. I originally picked `c_char = int(8)`, but this is not correct on all platforms due to signedness. As a result, some minimal module tests were throwing assertion errors.
This PR changes things by actually generating C types for minimal modules. This is just like generating C types for standard modules, but it doesn't generate the various assertions, because `==` is typically not in scope.

Minimal modules: generate minimal CTypes

---

modules/internal/ChapelTuple.chpl
test/types/tuple/homog/tuple-out-of-bounds-access.chpl
test/types/tuple/homog/tuple-out-of-bounds-access.good

This PR updates the `tuple access out of bounds` error to print out the tuple type in addition based on my recent experience being confused by this error. While there, it makes this error message more similar to the array out-of-bounds error.
Example error before this PR:
```
tuple-out-of-bounds-access.chpl:8: error: halt reached - tuple access out of bounds: 23
```
Example error after this PR:
```
tuple-out-of-bounds-access.chpl:8: error: halt reached - tuple index out of bounds
note: index was 23 but the tuple type 23*int(64) has bounds 0..22
```

Improve the tuple out-of-bounds error message

---

util/packaging/homebrew/chapel-main.rb

This adjusts the chapel homebrew formula used to build main in response to changes in https://github.com/chapel-lang/chapel/pull/26514 that removed the exact string `inreplace` was searching for.
Fixes failing homebrew tests.
TESTING:

remove inreplace line for python3 in chpl-venv makefile

---

util/pastPerformance/testReleasesPerformance

Update a path in `util/pastPerformance/testReleasesPerformance` from `/data/cf/chapel/chapel-releases` to `/hpcdc/project/chapel/chapel-releases`.
The previous directory did not exist on that filesystem, so I'm not sure how this has been working so far. Maybe it hasn't actually been getting used. In any case, I did not create the dir on the new filesystem as part of this.
This is the only path needing to be updated outside of the test configs in `util/cron`, which will be changed in a separate PR.
Part of https://github.com/Cray/chapel-private/issues/7042.

Remove use of /data/cf in testReleasesPerformance

---

modules/packages/Python.chpl
test/classes/generic/nonGenericSubclassGenericSuperclass.bad
test/classes/generic/nonGenericSubclassGenericSuperclass.chpl
test/classes/generic/nonGenericSubclassGenericSuperclass.future
test/library/packages/Python/correctness/noExceptions.bad
test/library/packages/Python/correctness/noExceptions.chpl
test/library/packages/Python/correctness/noExceptions.compopts
test/library/packages/Python/correctness/noExceptions.future
test/library/packages/Python/correctness/noExceptions.good
test/library/packages/Python/correctness/noExceptions.prediff

Adds `Python.checkExceptions` (on by default), which allows users to turn off the exception checking to avoid overhead.
This PR also includes a few other cleanups and adds a future for https://github.com/chapel-lang/chapel/issues/26579
- this has 1 expected failure of `argPassingTest`, which tests exceptions 
Future work:
- It would be nice to support this as a per-interpreter param as well, but that opens us up to issues with generics and classes. So for now thats a todo/nice-to-have

Add a config param to avoid Python exception checking overheads

---

util/cron/common-arkouda.bash
util/cron/common-llvm.bash
util/cron/common-mpicc.bash
util/cron/common-native-gpu.bash
util/cron/common-python.bash
util/cron/load-base-deps.bash
util/cron/test-c-backend.bash
util/cron/test-cray-xc-gpu-arkouda.bash
util/cron/test-linux64-gcc101.bash
util/cron/test-linux64-gcc112.bash
util/cron/test-linux64-gcc74.bash
util/cron/test-linux64-gcc91.bash
util/cron/test-linux64-llvm11.bash
util/cron/test-linux64-llvm12.bash
util/cron/test-linux64-llvm13.bash
util/cron/test-linux64-llvm14.bash
util/cron/test-linux64-llvm15.bash
util/cron/test-linux64-llvm16.bash
util/cron/test-linux64-llvm17.bash
util/cron/test-linux64-llvm18.bash
util/cron/test-linux64-llvm19.bash
util/cron/test-linux64-python36.bash
util/cron/test-linux64-python37.bash
util/cron/test-networking-packages.bash
util/cron/test-perf.chapcs.arkouda.release.bash

Replace uses of `/data/cf/chapel` with `/hpcdc/project/chapel` in nightly test scripts, and update to use the new `setup_[gcc,python,llvm].bash` scripts where possible.
The new scripts take version arguments and always pull from a (new) Spack install, replacing the need for many version-specific scripts and manual installs. I have set up all the scripts referenced in these paths as part of this work.
Also includes some side effects:
- The patch versions of Python 3.6 and Python 3.7 used are changed. Spack only offers the latest patch version of each of these long-EOL versions, so this was more convenient.
- Switched to using a new `setup_llvm.bash` to replace `setup_system_llvm.bash` on `/hpcdc`, which always loads from a new Spack.
- Removed the use of a separate …

Switch /data/cf to /hpcdc/project and use new setup scripts

---

util/cron/syncPerfGraphs.py

Update for hostname change from `chapcs11.us.cray.com` to `chapcs11.hpc.amslabs.hpecorp.net`.

Update chapcs11 hostname in syncPerfGraphs

---

util/cron/common-python.bash

Fix a mistake in which the argument to the new Python setup script was checked as part of its path, so the script was considered missing.
Additionally, switch from a warning to a fatal error if the needed Python setup script is not allowed. This will make it impossible to silently use the wrong Python version as we are before this fix.
Follow up to https://github.com/chapel-lang/chapel/pull/26584.

Fix python setup script not being found

---

test/types/tuple/homog/tuple-out-of-bounds-access.suppressif

Follow-up to PR #26580.
`--fast` testing turns of bounds checking, including for tuples, so suppress this test in that configuration.

Suppress tuple-out-of-bounds-access test for --fast

---

test/unstable-keyword/iterator/COMPOPTS
test/unstable-keyword/iterator/onlySerial.bad
test/unstable-keyword/iterator/onlySerial.chpl
test/unstable-keyword/iterator/onlySerial.future
test/unstable-keyword/iterator/onlySerial.good

See #26590 .  Basically, marking any iterator as unstable will cause the unstable warning to fire, even if that particular iterator is not used.  This test demonstrates the issue for serial iterators, but standalone, leader, and follower iterators were also exhibiting the same behavior (and I suspect will be solved by the same solution).

Add a future to lock in the behavior when an iterator is unstable 

---

util/cron/test-cray-xc-arkouda.bash
util/cron/test-cray-xc-arkouda.release.bash

The parquetMultiIO test may exceed the default 300-second timeout.
Resolves https://github.com/Cray/chapel-private/issues/7018.

Increase the Arkouda test timeout to 500 seconds

---

util/cron/test-networking-packages.bash

This is making an assumption about the location of java on the test systems.  This is a trivial change and was tested using this configuration: http://cfljenkins12.us.cray.com:8080/view/TZ%20Builds/job/tz-chapcs-correctness-test-networking-packages/4/.

Remove JAVA_HOME declaration in NetworkingPackages test

---

modules/packages/Curl.chpl

Switch from the deprecated `CURLINFO_CONTENT_LENGTH_DOWNLOAD` constant to its replacement `CURLINFO_CONTENT_LENGTH_DOWNLOAD_T` in the Curl package module.
Per [Curl docs](https://curl.se/libcurl/c/CURLINFO_CONTENT_LENGTH_DOWNLOAD.html), the old constant is deprecated since Curl 7.55, which was released in 2017.
Testing:

Use new CURLINFO_CONTENT_LENGTH_DOWNLOAD_T

---

test/ANNOTATIONS.yaml

- qthreads partial reversion (impacts thread ring shootout benchmark)
- Add annotation indicating we suspect a PR raising the number of gasnet threads may have influenced nbody perf on Apollo. If not due to that, it could also be due to some bimodal machine behavior, graph history makes it look like such behavior may exist.

add annotations week of 1/23/25

---

runtime/include/chpl-mem-desc.h
runtime/src/launch/pbs-gasnetrun_ibv/launch-pbs-gasnetrun_ibv.c

The command buffers used to delete the PBS temporary files were too small, causing the file names to be truncated and the files to not be deleted. The launcher now unlinks the files, obviating the need for a command buffer. This approach also generates an error message if the unlink fails.

Fix temporary file cleanup

---

test/chplcheck/CaseRules.chpl
test/chplcheck/CaseRules.good
tools/chplcheck/src/rules.py

Fixes how we lint extern symbols in chplcheck for name violations.
Extern symbols should not be linted for name violations, because they typically come from another language that has different naming conventions. Furthermore, the user may have no control over the type name (i.e. using a third-party library). `chplcheck` already handled this correctly for functions and variables/types, but not for records. This PR rectifies that.
This PR also adds an opt-out, if the user has renamed their symbol, then they do have full control of the name and this PR turns on linting in that case. In the following program, we should lint the name `chapelFunc`, because that's a name picked by the user and not relevant to the external name.
```chapel
proc "extern_c_func" proc chapelFunc() { }
```
[Reviewed …

Change naming linting for extern symbols

---

test/unstable-keyword/iterator/onlySerial.bad
test/unstable-keyword/iterator/onlySerial.good
test/unstable-keyword/iterator/onlySerial.prediff

And update the .bad/.good files to match that prediff's expectations
Not sure why I keep thinking the module line number adjustments will happen automatically but whatever

Add a prediff to this test to avoid module line number adjustments

---

modules/packages/Python.chpl
test/library/packages/Python/correctness/customType.chpl
test/library/packages/Python/correctness/fromCloudPickle.chpl
test/library/packages/Python/correctness/moduleFromBytes.chpl
test/library/packages/Python/examples/bs4/findLinks.chpl
test/library/packages/Python/examples/torch/myModel.chpl

Removes ClassObject as a special type for the Python module and moves its methods into the Value base class
This PR also adds some missing documention

Remove ClassObject type for Python module

---

util/cron/test-networking-packages.bash

Use `hostname -s` instead of `$HOSTNAME` for the hostname-based path to hadoop, as it's in `chapcs11` without any qualification.
Testing:

Fix test-networking-packages hostname-based hadoop path

---

doc/rst/conf.py
doc/rst/usingchapel/prereqs.rst
third-party/chpl-venv/Makefile.include
third-party/chpl-venv/chapel-py-requirements.txt
tools/chapel-py/setup.py
tools/chapel-py/src/PythonWrapper.h
tools/chapel-py/src/chapel.cpp
tools/chapel-py/src/core-types-gen.cpp
tools/chapel-py/src/core-types-gen.h
tools/chapel-py/src/core-types.cpp
tools/chapel-py/src/core-types.h
tools/chapel-py/src/error-tracker.h
tools/chapel-py/src/iterator-support.cpp
tools/chapel-py/src/iterator-support.h
tools/chapel-py/src/python-class.h
tools/chapel-py/src/python-type-helper.h
tools/chapel-py/src/python-types.h
tools/chpl-language-server/src/chpl-language-server.py
util/chplenv/chpl_home_utils.py
util/config/run-in-venv-with-python-bindings.bash

Refactors chapel-py to only use the C Python Stable API when possible. This means that chapel-py will no longer be constrained to run with the Python version it was built with. This allows users more flexibility in how they use chapel-py.
Testing:
- Building with Python 3.13
- Building with Python 3.10
Performance Impact
|       | main | this PR |
|---|---|---|
| `chplcheck` | 1.7s | 1.7s |
| `chplcheck modules/standard/IO.chpl` | 4.9s | 4.8s |
| `chplcheck modules/standard/Sort.chpl` | 2.9s | 3.2s |

Refactor chapel-py to use the C Python Stable API

---

make/compiler/Makefile.clang

Turns off floating point warning for --no-ieee-float with C backend.
This was working for the LLVM backend but not the C backend. The same solution can be used, just in a different place. The solution for LLVM was added in https://github.com/chapel-lang/chapel/pull/24848
With clang 18+, when using `-ffast-math` (enabled by Chapel's `--no-ieee-float`) a warning is thrown when using some C math functions related to inf and NaN. These warnings can and must be disabled by `-Wno-nan-infinity-disabled` since C math functions are included in all compiles as they are stubbed out in the runtime. 
Future work may include investigating a more fine grained approach. Should we suppress the warning for the runtime stubs but propagate it for user code which falls into this category?

Turn off floating point warning for --no-ieee-float with C backend

---

test/studies/champs/sub_test

Stop applying a patch, as the patch has been accepted upstream and isn't needed.

Stop applying patch in nightly test

---

modules/packages/Python.chpl
modules/packages/PythonHelper/ArrayTypes.c
modules/packages/PythonHelper/ArrayTypes.h
modules/packages/PythonHelper/ChapelPythonHelper.h
test/library/packages/Python/correctness/myArray.chpl
test/library/packages/Python/correctness/myArray.good
test/library/packages/Python/correctness/myArrayReturnArray.chpl
test/library/packages/Python/correctness/myArrayReturnArray.good
test/library/packages/Python/correctness/myArrayReturnArray.prediff
test/library/packages/Python/correctness/myList.chpl
test/library/packages/Python/correctness/myList.good

Adds a new feature to the Python interop support, allowing Chapel arrays to be passed to Python functions without being copied. This allows Python code to modify Chapel arrays in place, rather than copying in/out.
This support is fairly limited to start with, only supporting integer, real, and bool types.

Allow passing Chapel arrays to Python functions without copying

---

modules/internal/ChapelArrayViewElision.chpl
test/optimizations/arrayViewElision/distributed.comm-none.good
test/optimizations/arrayViewElision/distributed.good
test/optimizations/arrayViewElision/distributedToLocal.chpl
test/optimizations/arrayViewElision/distributedToLocal.comm-none.good
test/optimizations/arrayViewElision/distributedToLocal.compopts
test/optimizations/arrayViewElision/distributedToLocal.good
test/optimizations/arrayViewElision/localToDistributed.chpl
test/optimizations/arrayViewElision/localToDistributed.compopts
test/optimizations/arrayViewElision/localToDistributed.good

Michael has bumped into a case where AVE wasn't firing when arrays are of different type (block vs DR particularly). That seems to be because of a check I added for caution in the first PR, which looks like it was easy to remove.
This PR also adds tests, but note that Cyclic vs DR is still not supported. I don't think this is an AVE limitation -- such bulk transfer are probably not supported already.
Test

Expand AVE to arrays of different types

---

util/cron/common-gasnet.bash
util/cron/common-hpe-apollo.bash
util/test/prediff-for-gasnet

Ignore PSHM warning when testing co-locales on GASNet. GASNet will print a warning if PSHM is disabled and there are multiple processes on the same node (i.e., there are co-locales). This warning should be ignored when checking test output.

Ignore PSHM warning when testing co-locales on GASNet

---

frontend/include/chpl/resolution/resolution-error-classes-list.h
frontend/include/chpl/resolution/resolution-types.h
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/Resolver.h
frontend/lib/resolution/resolution-error-classes-list.cpp
test/errors/resolution/noMatchingCandidates.1.good
test/errors/resolution/noMatchingCandidates.2.good
test/errors/resolution/noMatchingCandidates.chpl

This adds detection of an uninitialized variable used as an actual to a non-out formal. The previous error was a generic failure to resolve function [NoMatchingCandidates] and this improves the message by indicating that the candidate did not match because of the uninitialized actual passed to a non-out formal. 
resolves https://github.com/Cray/chapel-private/issues/6624
Example program:
```chapel
proc fn(const arg) {
arg;
}
proc main() {
var x;
fn(x);
x=5;
}
```
in production this produces the following error message:
```
MyTestModule.chpl:9: In function 'main':
MyTestModule.chpl:10: error: 'x' is not initialized and has no type
MyTestModule.chpl:10: note: cannot find initialization point to split-init this variable
MyTestModule.chpl:11: note: 'x' is used here before it is initialized …
```

add split-init error when uninitialized var used as actual

---

CHANGES.md
doc/Makefile.sphinx
doc/rst/developer/bestPractices/GettingStarted.rst
doc/rst/developer/bestPractices/README.md
doc/rst/developer/chips/inactive/14.rst
doc/rst/language/archivedSpecs.rst
doc/rst/technotes/gpu.rst
util/buildRelease/changePrerelease

This PR removes a number of instances of `index.html` files from our docs and code, motivated by:
* making URLs shorter, simpler, and more canonical
* reducing the number of index.html files I find when grepping the website for instances of it
Interestingly, I think there are many remaining uses in the generated docs which, I'm guessing, are inserted by sphinx, though it seems surprising that it wouldn't use directories rather than explicit index.html files…

Reduce use of `index.html`

---

compiler/optimizations/arrayViewElision.cpp
modules/internal/ChapelArrayViewElision.chpl
test/optimizations/arrayViewElision/localToDistributed.comm-none.good

This PR handles two things:
- Trivially: adds/updates good files that were missed in my initial PR.
- More seriously: thwarts optimization when the rhs is a constant, multidimensional array. This is done to work around https://github.com/chapel-lang/chapel/issues/26626. When that issue is resolved, the relevant commit can be reverted.
Test:

Handle two issues that came up after some AVE improvements

---

frontend/lib/resolution/can-pass.cpp
frontend/lib/resolution/default-functions.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/return-type-inference.cpp
frontend/test/resolution/testCast.cpp
frontend/test/resolution/testSubtypePrimitives.cpp

This PR fixes a trivial off-by-one bug with the generation of de/serialize formals. While poking further at IO calls, I observed some other issues with resolution and made some fixes:
- add a workaround for case when extern function return type is not resolved
- Improve 'canPass' to handle passing ``borrowed class`` as an actual, which can occur in ``isSubtype``
- Improves compiler-handled casting to and from unmanaged/borrowed any-classes
This PR also adds some tests to lock in this behavior.
Testing:

Dyno: resolve bug in de/serialize generation, and other fixes

---

frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testReflection.cpp

This PR adds support for the following reflection routines to dyno:
- ``getLineNumber``
- ``getFileName``
- ``getRoutineName``
- ``getModuleName``
Testing:

Dyno: Add support for file-related reflection routines

---

frontend/include/chpl/resolution/can-pass.h
frontend/include/chpl/resolution/resolution-error-classes-list.h
frontend/lib/resolution/InitResolver.cpp
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/Resolver.h
frontend/lib/resolution/can-pass.cpp
frontend/lib/resolution/resolution-error-classes-list.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/signature-checks.cpp
frontend/test/resolution/testEnums.cpp
frontend/test/resolution/testHeapBuffer.cpp
frontend/test/resolution/testInitSemantics.cpp
frontend/test/resolution/testRanges.cpp
frontend/test/resolution/testResolve.cpp
frontend/test/resolution/testVarArgs.cpp

This PR goes through the resolution meta-issue and fixes a number of relatively simple issues encountered in the course of resolving the specs.
Closes https://github.com/Cray/chapel-private/issues/7036 (querying vararg size in `where` clause)
Closes https://github.com/Cray/chapel-private/issues/7034 ("passing nested enums to generic functions", but actually resolving nested enums at all)
Closes https://github.com/Cray/chapel-private/issues/7033 (`range(?)` formals becoming concrete; more broadly, `R(?)` formals becoming concrete for generic-with-defaults `R`)
Closes https://github.com/Cray/chapel-private/issues/7030 (resolving `new` on type aliases to instantiated types).
Closes https://github.com/Cray/chapel-private/issues/6927 (assigning `nil` to `ddata`, but broadly fixing candidate …

Dyno: resolution fixes variety pack

---

util/cron/test-quickstart.bash

Add testing for chpl-language-server to quickstart, since this is a common user config
resolves https://github.com/chapel-lang/chapel/issues/25181

Test chpl-language-server with quickstart

---

test/library/packages/Python/correctness/noExceptions.bad
test/library/packages/Python/correctness/noExceptions.chpl

Fixes a future test by making sure it continues to fail to compile since the feature is not implemented.

Fix noExceptions future test

---

modules/packages/Python.chpl
modules/packages/PythonHelper/ArrayTypes.c
modules/packages/PythonHelper/ArrayTypes.h
modules/packages/PythonHelper/ChapelPythonHelper.h
test/library/packages/Python/correctness/arrays/PRETEST
test/library/packages/Python/correctness/arrays/SUPPRESSIF
test/library/packages/Python/correctness/arrays/gradient.chpl
test/library/packages/Python/correctness/arrays/gradient.good
test/library/packages/Python/correctness/arrays/numpyInterop.chpl
test/library/packages/Python/correctness/arrays/numpyInterop.good
test/library/packages/Python/correctness/arrays/numpyInterop.skipif
test/library/packages/Python/correctness/arrays/usePythonArray.chpl
test/library/packages/Python/correctness/arrays/usePythonArray.good
test/library/packages/Python/correctness/arrays/usePythonArray.py

Add initial support for passing Chapel arrays to Python as Py_buffer's and for reading Python objects that support the Py_buffer API.
This enables the following use case
```chapel
use Python;
proc main() {
var interp = new Interpreter();
var mod = new Module(interp, "buffer");
var doit_numpy = new Function(mod, "doit_numpy");
var doit_torch = new Function(mod, "doit_torch");
var doit_numpy_plus_torch = new Function(mod, "doit_numpy_plus_torch");
var arr = [1, 2, 3, 4, 5];
var pyArr = new Array(interp, arr);
writeln("Calling numpy version: ", arr);
doit_numpy(NoneType, pyArr);
writeln("Back in Chapel: ", arr);
arr = [1, 2, 3, 4, 5];
writeln("Calling torch version: ", arr);
doit_torch(NoneType, pyArr);
writeln("Back in Chapel: ", arr);
arr = [1, 2, 3, 4, 5];
writeln("Calling numpy+torch …
```

Initial Py_buffer support for Chapel 1D arrays

---

README.rst
doc/rst/developer/bestPractices/GettingStarted.rst
doc/rst/language/evolution.rst
doc/rst/platforms/aws.rst
doc/rst/users-guide/base/hello.rst
doc/rst/usingchapel/QUICKSTART.rst
util/build_configs/cray-internal/generate-dev-releaseinfo.bash

This updates URLs within our docs to point to the new website rather than the URLs from the old website.  I believe most of these cases would automatically redirect to the new website, but the more we establish the new URLs as the canonical versions, the happier our Google search dashboard will be.
The one change here that's a little borderline is
https://chapel-lang.org/bugs.html which has been a (client-side) redirect for ages, though what it redirects to isn't the greatest of pages (a docs page that basically says "file a github issue."  Here, I've updated one such instance to avoid the redirect, but there are lots of others that I skipped over, feeling like we should probably establish a better bugs page in general.  I've opened an issue on the chapel-www repository to determine what …

Update docs to point to new webpages rather than old

---

modules/packages/Python.chpl

Hides the documentation for a non-public Python module function. This function was just missing its `@chpldoc.nodoc`

Hide documentation for a non-public Python module function

---

compiler/include/driver.h
compiler/main/driver.cpp
frontend/lib/resolution/call-graph.cpp
frontend/lib/resolution/default-functions.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/resolution-types.cpp
frontend/test/resolution/testInitSemantics.cpp

Closes https://github.com/Cray/chapel-private/issues/7069.
Bundles https://github.com/chapel-lang/chapel/pull/26641 (clean diff IOU) to get at the heart of the issue.
There are two minor issues causing the bug.
1. We resolved `init=` two times (once from `MostSpecificCandidate`, see https://github.com/chapel-lang/chapel/pull/26613) and once in `resolveFnCall`. The latter call was redundant and is vestige of an older version of the resolver.
2. The second `init=` call did not guard `skipIfRunning` like most other calls, and thus didn't circumvent recursion errors.  However, since its purpose was to emit diagnostics from the `init=` body, it's sound to skip recursive calls, since the outer call will still issue these diagnostics.
Since this code is redundant, I simply removed it. Triggering …

Dyno: fix infinite recursion caused by `init=` on "core" types.

---

third-party/gasnet/README
third-party/gasnet/gasnet-src/extended-ref/gasnet_extended_refbarrier.c
third-party/gasnet/gasnet-src/gasnet_help.h
third-party/gasnet/gasnet-src/gasnet_internal.c

This commit includes changes from
https://bitbucket.org/berkeleylab/gasnet/pull-requests/653
The commits fix a race condition causing sporadic crashes on program startup.  We observed these crashes on Mac OS X running on ARM systems with segment=fast (see https://github.com/Cray/chapel-private/issues/7065 ).
Reviewed by @e-kayrakli and @bonachea - thanks!

Include gasnet fix for race condition

---

doc/rst/conf.py
third-party/chpl-venv/chpldoc-sphinx-project/source/conf.py

It isn't clear to me that this logic is actually being used for anything today (building a version of docs without these lines and diffing against other recent docs didn't _seem_ to show any related differences), but I feel better not having this logic in here anyway given that we're not using Google Analytics anymore and don't want to be using cookies.

Remove some logic in docs builds related to Google Analytics

---

test/library/standard/Set/zippering/arrayShorter2.skipif

Passed a fresh checkout of the test with and without `--fast`

Add a skipif for this test with `--fast`, it relies on bounds checking

---

tools/chapel-py/setup.py
util/chplenv/chpl_home_utils.py

This fixes an issue where installing Chapel using `--prefix` would not encode the correct rpath in the shared library that was created for python. The change here looks for the presence of a `configured-prefix` file in the build tree and uses that and the chapel version from `CMakeLists.txt` to encode the proper rpath based on the installation destination.
[reviewed by @jabraham17 and @bonachea - thanks!]

fix bad rpath in chapel-py when using --prefix installs

---

.github/workflows/CI.yml

This adds a new job to our CI process that will conditionally trigger on pushes to main. The new job depends on the `make_doc` job finishing, and then it retrieves the documentation artifact from that job and uploads it to the website's `main` docs.
It was necessary to include the hidden files when creating the artifact from the `make_docs` step so that the updated `.htaccess` file would be included. 
Secrets are stored in github and are never exposed in logs etc. 
Tested with bad docs (failed build) and adding new docs. 
Set to use the `--dry-run` option for now. Once we've had a few days of it in place without issue and confirmed that the updates would be the same or better than our current update method, I'll remove that flag and it will begin actually publishing the docs.
[reviewed by …

add publish docs job to CI

---

modules/packages/PythonHelper/ArrayTypes.c

Adds an explicit cast for discarding const when assigning a string literal to a `char*`

Add an explicit cast for discarding const

---

make/compiler/Makefile.clang

We're seeing the warnings encountered in https://github.com/llvm/llvm-project/issues/76515 for clang 19 in addition to 18, so extend the warning silencing to cover both.

Extend clang 18 deprecation warning silencing to 19

---

frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/call-init-deinit.cpp
frontend/test/resolution/testCallInitDeinit.cpp
frontend/test/resolution/testIf.cpp

Fix two bugs concerning the type of a variable declared with `if var`/`if const`.
Fixes:
- Resolve the variable as non-nilable `unmanaged` if its init part is `unmanaged`, rather than always making it `borrowed`. This is language spec'd behavior.
- Treat the init part as non-nilable when resolving the `=` call from the variable initialization. This previously caused problems as the variable is always non-nilable, and you generally can't assign a nilable value into a non-nilable -- even though we know at runtime it will be non-nilable on this control flow path.
Also adds tests for both fixed cases.
Encountered working on array module code resolution.
Testing:

Fix type and assign call of `if var` declaration

---

frontend/include/chpl/resolution/resolution-queries.h
frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testForwarding.cpp

Fix a bug where Dyno would consider forwarded method candidates even when non-forwarded function candidates were found, for a call within a method.
We only want to search for forwarding candidates if we haven't found any non-forwarding candidates. However, when resolving a call in a method, we first try resolving it as a function and then as a method with an implicit receiver. If we find function candidates, we still want to search for method candidates, but we do not want to search for forwarding method candidates even if there are no non-forwarding method candidates. This PR adds logic to skip that.
Added a test for the fixed case, where the test would previously encounter ambiguity between the non-forwarded function and forwarded method.
This bug was incidentally causing query …

Fix call resolution search order for forwarded proc as method

---

tools/chpl-language-server/test/basic.py

This fixes a chpl-language-server test that was expecting resolution to a shadowed outer scope variable instead of the later defined variable. 
As demonstrated with this code:
```chapel
var y = 42;
{
var x = 2*y;
var y = 2*x;
…
}
```
the use and definition of `y` within the inner block means we will report this as a use-before-define error because we don't bring outer variables into scope when they are redefined inside a block. 
The fix here is just to change the test to use a different variable name and update the expected results.
Previously, dyno was not detecting use-before-define errors in init-expressions like this, but https://github.com/chapel-lang/chapel/pull/26157 added detection for that which caused this test to start failing.
[reviewed by @jabraham17 - thank you!]

fix test in chpl-language-server for use before define, shadowing

---

modules/packages/Python.chpl
test/library/packages/Python/correctness/argPassingTest.chpl
test/library/packages/Python/correctness/argPassingTest.good
test/library/packages/Python/correctness/arrays/gradient.chpl
test/library/packages/Python/correctness/arrays/myArray.chpl
test/library/packages/Python/correctness/arrays/myList.chpl
test/library/packages/Python/correctness/arrays/myList.good
test/library/packages/Python/correctness/arrays/numpyInterop.chpl
test/library/packages/Python/correctness/basicTypes.chpl
test/library/packages/Python/correctness/defaultType.chpl
test/library/packages/Python/correctness/defaultType.good
test/library/packages/Python/correctness/iteratorTest.chpl
test/library/packages/Python/correctness/loadingCode/fromCloudPickle.chpl
test/library/packages/Python/correctness/loadingCode/moduleFromBytes.chpl
test/library/packages/Python/correctness/loadingCode/moduleFromString.chpl
test/library/packages/Python/correctness/subInterp.chpl
test/library/packages/Python/examples/torch/myModel.chpl
test/library/packages/Python/memleaks/lambdas.good

Allows users to omit the return type on a call to Python code when they don't care what the type is. The defaults to `owned Value`, which is a wrapper around the underlying type. This `Value` can be captured by users and later converted to a Chapel type, continue to be used by other functions as a `Value` type (with no extra overhead), or ignored alltogether (in the case a function from python doesn't return anything).
This significantly cleans up some user-facing Python code
Before this PR
```chapel
doNothing(NoneType);
funcReturnsNothing(NoneType, 1, 2, 3);
var x: owned Value = getAValue(owned Value);
```
After this PR
```chapel
doNothing();
funcReturnsNothing(1, 2, 3);
var x: owned Value = getAValue();
```

Allow users to omit the return type on some Python calls

---

test/sparse/vass/sparse-mismatch-dom-err-dom1dom2dom2.skipif

It seems to (sporadically?) fail to exit, even though it still generates the halt message.  This seems likely due to a valgrind upgrade, but I don't think it's consistent enough for a suppressif to be helpful
Verified that running normally with `-respect-skipifs` didn't cause this test to be skipped (so I got the right binary option)

Skip this test with valgrind

---

frontend/lib/resolution/Resolver.cpp
frontend/test/resolution/testTuples.cpp

Closes https://github.com/Cray/chapel-private/issues/7070.
Dyno's initial signatures are deliberately partial. They are used to filter out obviously non-matching candidates, while skipping the difficult parts of instantiation. As a result, they don't incorporate dependent type information, type queries, etc.
This means in such complicated instantiation cases, it's "expected" for unknown types to be present in initial signatures, and compiler logic should work with that. Prior to this PR, the `.type` expression produced `ErroneousType` for `.type` on known things, which broke the aforementioned expectation. This PR changes `.type` to produce `UnknownType` instead, which is preferred anyway since Dyno's convention is to only create `ErroneousTypes` when errors are issued.
Reviewed by …

Dyno: enable more initial signature patterns

---

compiler/passes/parseAndConvert.cpp
frontend/include/chpl/resolution/resolution-queries.h
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/resolution-queries.cpp
test/errors/resolution/compilerDiagnostics.1.good
test/errors/resolution/compilerDiagnostics.2.good
test/errors/resolution/compilerDiagnostics.chpl
test/errors/resolution/compilerDiagnostics.prediff

Closes https://github.com/Cray/chapel-private/issues/7093.
This PR adds a query that gets set when error message are emitted as requested at the desired location. If that query is set, the "fallback" diagnostics are skipped.

Dyno: hook up production to handle Dyno's dual compiler error reporting

---

test/library/packages/Python/examples/torch/myModel.skipif

Skips valgrind testing for a pytorch test. pytorch is triggering valgrind errors that cause issues with nightly testing.

Skip valgrind testing for pytorch test

---

.github/workflows/CI.yml

This adds a restriction to the `publish-docs` github action so that it only runs on `chapel-lang/chapel` and not on forks or mirrors of the repository, where it would always fail due to missing secrets. 
Tested against my own fork with and without matching repository names. 
Trivial change to solve an annoyance in an action that isn't actually doing anything yet. Not reviewed.

limit github action to chapel-lang repo

---

modules/packages/DistributedBag.chpl
test/library/packages/DistributedBag/addBulk.chpl
test/library/packages/DistributedBag/addBulk.good

In the `addBulk` procedure of the `distBag` data structure, things are as follows:
```chapel
inline proc ref addElements(elts): int
{
var size = elts.size;
...
// add the elements to the tail
for elt in elts[0..#size] do block.pushTail(elt);
tail += size;
...
}
```
This produces an issue when the input `elts` is not 0-based (e.g., array slices). For example,
```chapel
const A: [0..9] int = [0,1,2,3,4,5,6,7,8,9];
var bag = new distBag(int);
bag.addBulk(A[2..9], 0);
writeln(bag);
```
returns `[2, 3, 4, 5, 6, 7, 0, 0]` instead of `[2, 3, 4, 5, 6, 7, 8, 9]`.
A fix for this is to iterate over `elts` without specifying the domain, and use a counter to make sure that we do not insert more elements than we can. I also update the tests to make sure that this bug doesn't come back in the future.

Fix issues in `distBag.addBulk`

---

test/library/packages/Python/examples/torch/myModel.skipif

Fixes a typo in a skipif for a test.
The skipif worked to skip the test (since it exited), but I failed to notice the syntax error and subsequent failures in the working case

Fix typo in skipif for myModel

---

frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/default-functions.cpp
frontend/test/resolution/testNew.cpp
frontend/test/resolution/testOperatorOverloads.cpp

Closes https://github.com/Cray/chapel-private/issues/7100.
Closes https://github.com/Cray/chapel-private/issues/7099.
This PR makes minor fixes for Dyno issues that came up as part of resolving spec tests. The intents on `==` and `=` were likely swapped (as Michael pointed out in a comment on  https://github.com/Cray/chapel-private/issues/7099. 

Dyno: a couple more minor fixes

---

util/cron/nightlysubs.pm

Closes https://github.com/Cray/chapel-private/issues/7111.
This PR moves the errors to Brad's desired order and merges the "errors" and "errors in bash commands" (etc.) sections.

Reorder notifications in nightly email to better reflect priority

---

test/domains/compilerErrors/domainFormalUseBeforeDefine.chpl
test/domains/compilerErrors/domainFormalUseBeforeDefine.good

Add regression test for a formal pattern that was previously allowing the use of formals before they were defined due to a bug/limitation in the compiler.
As an example, consider the following function signature:
```chapel
proc foo(baz: t, type t) {
//...
}
```
Here the formal `baz` is declared as having the type `t`, and `type t` is defined as the second formal.
The compiler rightly complains that we've used the `type t` before it was defined.
The solution is to reorder the formals such that the type t is defined first:
```chapel
proc foo(type t, baz: t) {
//...
}
```
However, because we can’t enforce domain type bounds at compile time, doing something similar with a domain appeared to work.
```chapel
proc bar(baz: [d] real, d:domain(1)) {
//...
}
```
This appeared to work because behind …

add tests for use domain formal before defined

---

frontend/lib/resolution/default-functions.cpp

Closes https://github.com/Cray/chapel-private/issues/7090.
Probably closes https://github.com/Cray/chapel-private/issues/7098 (the assertion is during `canPass` for compiler-generated tuple functions, which this PR ought to disable).
In production, we generate `serialize` functions for types if no `serialize` function is present _anywhere in the program_. Dyno, however, is an incremental compiler, and as a result, it cannot use "anywhere in the program" properties (not to mention, due to various scoping rules, the "anywhere in the program" rule can get you into hot water). Instead, Dyno uses a type's definition point to search for `serialize` etc. 
This would be nice, except that we define some serialization functions for builtin types in `ChapelIO`, away from the types' definition …

Dyno: add workaround for finding 'serialize' methods in ChapelIO

---

tools/mason/MasonTest.chpl
tools/mason/MasonUtils.chpl
util/packaging/apt/test/Dockerfile.template
util/packaging/rpm/test/Dockerfile.template

Fixes an issue where `mason` was using the wrong CHPL_HOME path.
Previously, `mason` relied on a CHPL_HOME embedded in the binary. This was used to run tests via `mason test`. However, with `make install` CHPL_HOME would be different at build time versus install time.
This PR resolves the issue by having mason use the following for `CHPL_HOME`.
1. if the env var `CHPL_HOME` is set, use that
2. if `chpl` is available in PATH, use the `CHPL_HOME` from that (as reported by `--print-chpl-home`)
3. otherwise, fallback to the previous CHPL_HOME definition (from ChplConfig).
This PR also adds a step to our packaging configs to exercise `mason test` to ensure it continues to work.
Resolves https://github.com/chapel-lang/chapel/issues/25356

Fix `mason test` not working when `make install` is used

---

doc/rst/tools/chapel-py/chapel-py.rst

Clarifies some of the build requirements for chapel-py.
A user recently had an issue building chapel-py manually (i.e. through pip directly, not make). While we had this process documented, we failed to clarify the dependencies. This PR rectifies that.

Clarify build requirements for chapel-py

---

test/studies/shootout/reverse-complement/bradc/revcomp-blc-gcc8-algs.chpl

The valgrind executions of this test have been timing out with some frequency lately after some system upgrades in the spin version of the algorithm.  I think that, to be correct, the spin versions need to be yielding the processor, and that historically we've "gotten away" with not doing so without penalty or overhead.  Here, I'm updating the test to include the yield in hopes that it helps with the timeouts, and also to see what impact it has on the performance of the test.

Make revcomp variation yield processor when spin-waiting

---

modules/packages/DistributedBag.chpl
test/library/packages/DistributedBag/remove.chpl
test/library/packages/DistributedBag/remove.good

This PR addresses a request that was suggested following the release of the (new) `DistributedBag` module in 2.0. It consists in using `enum VictimPolicy { RAND, RING }` to select the victim selection policy for work stealing (encapsulated in `distBag.remove`), instead of the hard-coded `"rand"`/`"ring"` strings. 
The main benefits are:
-  A cleaner implementation
- The ability for users to select the victim selection policy, which was not possible before
- The flexibility to support additional policies in the future
I have updated the documentation to reflect these changes. 
In order to check the new feature, I added a test where `n` elements are inserted in the segment of task 0, and then drained from all other tasks. Each retrieval operation thus triggers a work stealing operation …

Add an `enum VictimPolicy` in `DistributedBag` module

---

test/ANNOTATIONS.yaml

I've manually verified that the following PR improves the performance of the "Passing and returning strings" test on chapcs:
https://github.com/chapel-lang/chapel/pull/26645

add annotation about perf improvement on pass/return strings test

---

util/cron/common-gasnet.bash
util/cron/common-oversubscribed.bash

Recently, GASNet test configurations have been suffering from a timeout error across multiple tests that manifests as:
```
*** GASNET WARNING: AMUDP_SPMDStartup_AMUDP_NDEBUG returning an error code: AM_ERR_RESOURCE (Problem with requested resource)
from function AMUDP_SPMDStartup
at /ptmp/jenkins/chapel-ci/workspace/chapcs-correctness-test-gasnet-everything/third-party/gasnet/gasnet-src/other/amudp/amudp_spmd.cpp:1026
reason: worker failed DNSLookup on master host name
```
Michael hypothesized that setting CHPL_RT_MASTERIP may help with this failure mode, and I agree it's worth a try, so this adds it to common-gasnet.bash (where we also set up local launching and the like) to see what happens.
This could help with resolving https://github.com/Cray/chapel-private/issues/7062, but I'm not …

Set CHPL_RT_MASTERIP in hopes that it will help with our recent gasnet timeouts

---

test/studies/arkouda/functions.bash
test/studies/arkouda/sub_test
util/cron/common-arkouda.bash
util/cron/common-hpe-apollo.bash
util/cron/common-perf-hpe-apollo-hdr.bash
util/cron/common.bash
util/cron/nightly
util/cron/test-cray-xc-arkouda.bash
util/cron/test-cray-xc-arkouda.release.bash
util/cron/test-cray-xc-gpu-arkouda.bash
util/cron/test-gasnet-asan.arkouda.bash
util/cron/test-hpe-apollo-hdr.arkouda.bash
util/cron/test-hpe-apollo-hdr.arkouda.release.bash
util/cron/test-perf.chapcs.arkouda.bash
util/cron/test-perf.chapcs.arkouda.release.bash
util/cron/test-perf.chapcs.no-local.bash
util/cron/test-perf.cray-cs-hdr.arkouda.bash
util/cron/test-perf.cray-cs-hdr.arkouda.release.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.release.bash

... and, while there, also improve debugging/maintenance capabilities. Commits in this PR should be squashed.
- adds `log` function to be able to print things from Arkouda's `sub_test`
- use `ARKOUDA_SERVER_LAUNCH_PREFIX` to wire in `chpl_launchcmd` in the server launch command. This will be supported by https://github.com/Bears-R-Us/arkouda/pull/4088
- Add the following environment variables to disable parts of Arkouda testing. This has been very valuable during development, where I could simply make the Jenkins use an existing Arkouda build to reduce the turnaround time significantly:
- `CHPL_TEST_ARKOUDA_SKIP_RM_CLONE`
- `CHPL_TEST_ARKOUDA_SKIP_CHAPEL_PY`
- `CHPL_TEST_ARKOUDA_SKIP_BUILD`
- `CHPL_TEST_ARKOUDA_SKIP_MAKE_CHECK`
- `CHPL_TEST_ARKOUDA_SKIP_UNIT_TESTS` (this will be used by …

Add Arkouda IB performance, correctness scripts

---

util/cron/test-perf.chapcs.no-local.bash

I mistakenly merged a debugging code causing nightly failures. This PR reverts that change.

Revert a mistake in chapcs.no-local testing

---

frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testDisambiguation.cpp

This fix is motivated by a real-world example involving real-to-(bytes or string) casting, and the "_real_cast_helper" functions in the ``BytesCasts`` and ``StringCasts`` modules. Both modules leak this function, which eventually leaks out through ``ChapelStandard``, which both of these modules also use. This means the calls to ``_real_cast_helper`` in both modules can see both versions of the function.
Prior to this change, dyno was always using the POI scope for visibility distance calculation. The POI scope, in this case, was at the source of the call to the real-to-string cast (in the user module), where both ``_real_cast_helper`` functions were equally visible. Notably, the candidates themselves were not found using POI.
Following the lead of the production compiler, we should …

Dyno: Fix visibility distance bug by only passing in poiScope when relevant

---

util/test/prediff-for-gasnet

This PR fixes a problem we were seeing is some nightly testing configurations where a `\r` in the output was replaced by a `\n`. It adjusts `prediff-for-gasnet` to use binary I/O to avoid any newline translation that Python's default I/O tries to do.
Follow-up to PR #26611.
Reviewed by @jhh67 - thanks!

Use binary file I/O in prediff-for-gasnet

---

modules/standard/ChapelIO.chpl
modules/standard/IO.chpl
test/functions/deitz/test_write_type_error.good
test/functions/resolution/errors/badWrite.good
test/functions/varargs/typeToVarArgs.good
test/io/serializers/optionalArg.bad
test/io/serializers/unstableWriting.good
test/io/sungeun/funcPtr3.good
test/library/standard/IO/writelnWithSep.chpl
test/library/standard/IO/writelnWithSep.good
test/unstable/binaryFormat.good
test/unstable/writelnSep.chpl
test/unstable/writelnSep.good

Adds a `sep` argument to `write` and `writeln`, which changes the separator between arguments to these functions.
By default, `write` and `writeln` will just concatenate all of the arguments passed to them with no separator. By specifying `sep`, users can now change this
```chapel
writeln(1, 2, 3); // prints as "123"
writeln(1, 2, 3, sep=", "); // prints as "1, 2, 3"
```
This is a new feature that has not undergone design review, so is being added as unstable.
Implementation note: this PR uses `last resort` to work around compiler issues with varargs and keywargs: see https://github.com/chapel-lang/chapel/issues/17188
- Resolves https://github.com/chapel-lang/chapel/issues/25695
- Resolves https://github.com/chapel-lang/chapel/issues/14108

Add a `sep` argument to `writeln`

---

modules/packages/Python.chpl
modules/packages/PythonHelper/ArrayTypes.c
modules/packages/PythonHelper/ChapelPythonHelper.h

Fixes a few issues with the Python module with Python 3.9
- avoids Py_TPFLAGS_SEQUENCE, added in 3.10
- avoids Py_CompileString, which in 3.9 was a macro
Spot checked Python module tests with Python 3.9

Fix Python module version incompatability with Python 3.9

---

frontend/include/chpl/parsing/parsing-queries.h
frontend/lib/parsing/parsing-queries.cpp
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testClasses.cpp
frontend/test/resolution/testCompilerError.cpp
frontend/test/resolution/testResolve.cpp

Closes https://github.com/Cray/chapel-private/issues/7096.
Closes https://github.com/Cray/chapel-private/issues/7031.
Closes https://github.com/Cray/chapel-private/issues/7095.
This PR makes some more fixes to dyno. Included in the medley:
1. We previously relied on `isQueryRunning` to avoid infinite recursion when gathering diagnostics. This does not work with nested functions since they don't start queries. This PR adjusts the check to also visit the resolver's frames and detect recursion that way.
2. We previously did not insert substitutions for `type` formals when they only required coercion and not instantiation. This PR fixes that by always inserting substitutions for `type` formals.
3. We detected module-level variables by checking that the declaration's parent was a module. this …

Dyno: resolution fixes variety pack 2

---

frontend/include/chpl/types/BasicClassType.h
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/can-pass.cpp
frontend/lib/types/BasicClassType.cpp
frontend/test/resolution/testCanPass.cpp
frontend/test/resolution/testTypeQueries.cpp

Closes https://github.com/Cray/chapel-private/issues/6474.
This seemed to be a problem to do with partial instantiations of types. We only handled passing (partially) instantiated class types to fully generic formals. This PR changes this by sharing the instantiation logic between record types and class types, and fixing a minor issue about (incompatible) param instantiations.

Dyno: fix nested type queries

---

util/config/find-python.sh

Adds support for CHPL_PYTHON. This variable allows users and developers to select a different version of Python than the default one in PATH. This variable does not affect builds of the compiler, it is a runtime config only.
Example usage on a system with `python3`, `python3.12` and `python3.13`
```bash
`util/config/find-python.sh` --version # reports 3.13
`CHPL_PYTHON=python3 util/config/find-python.sh` --version # reports 3.13
`CHPL_PYTHON=python3.12 util/config/find-python.sh` --version # reports 3.12
`CHPL_PYTHON=python3.13 util/config/find-python.sh` --version # reports 3.13
```
This PR is intentionally leaving this variable undocumented for now. Changing the python version at runtime could have unintended side effects that would be difficult for users to debug.
[Reviewed by …

Add support for CHPL_PYTHON

---

test/release/examples/primers/FFTWlib.chpl

Fixes a typo in the FFTW primer, where the directions refer to the old filename.
PR https://github.com/chapel-lang/chapel/pull/1651/ renamed the file from testFFTW.chpl to FFTWlib.chpl, but did not update the file name in the text

Fix file name in FFTW primer

---

frontend/lib/resolution/InitResolver.cpp
frontend/lib/resolution/Resolver.cpp
frontend/test/resolution/testInitSemantics.cpp

Closes https://github.com/Cray/chapel-private/issues/6925. (wasn't broken on `main`).
As part of a discussion with Ben, we noticed that the following pattern works in Dyno but likely shouldn't:
```Chapel
record R {
type eltType;
proc init=(other: this.type.eltType) {
}
}
var x: R(int) = 5;
```
In Dyno, we allowed initializers to implicitly keep the types they started with. Since the call to `init=` "began" with `R(int)`, we silently allowed `eltType` to become `int`. However, in production, we require the user to configure the fields explicitly with arguments from the `init=` call.
In fixing this, I also noted that the `init=` call, unlike the `init` call, would not catch it if I changed `eltType` to something incompatible with the original argument. This is because the check for …

Dyno: solidify `init=`, partial instantiations

---

util/cron/test-hpe-cray-ex-ofi.bash

The complete test suite runs too long and never finishes.
This reverts commit c2084e04384a0d179f59343e89f97e734aa91cfd.

Revert "Run complete test suite on HPE Cray EX"

---

util/cron/common-champs.bash

https://github.com/chapel-lang/chapel/pull/26707 moved the following exports to `common-hpe-apollo.bash`
```bash
export CHPL_LAUNCHCMD_NUM_CPUS=144
export CHPL_LAUNCHCMD_QUEUE=f2401THP
```
However, that script is not sourced by `common-champs.bash`, which instead sources the performance version of that script (which is where I moved those exports from). It looks like it is because of complicated web of dependencies and modules that need to be loaded. This is captured by the following comment in `common-champs.bash`
```bash
export CHPL_HOST_PLATFORM=hpe-apollo
export CHPL_TEST_LAUNCHCMD=\$CHPL_HOME/util/test/chpl_launchcmd.py
export CHPL_LAUNCHER_TIMEOUT=pbs
source $UTIL_CRON_DIR/load-base-deps.bash
```
This PR adds the exports at the very top to the exports in this list.

Add some environment variables back in for CHAMPS

---

test/library/packages/Python/skipIfAndInstallPackage.sh
util/test/sub_test.py

Improves some of the logging we do for skipifs/suppressifs in `sub_test.py`. Additionally, improves logging in a Python module specific skipif
For example:

Improve logging for skipifs, especially for the Python module

---

test/studies/arkouda/sub_test

Changes the Arkouda testing we have to use a virtual environment for dependencies. This should resolve some issues we are having in our nightly testing and is better representative of how people actually use Arkouda.
Note: this PR respects the CHPL_TEST_VENV_DIR, which can be specified to re-use a test venv across multiple runs
[Reviewed by @e-kayrakli and @tzinsky]

Change Arkouda sub_test to use a virtual environment for dependencies

---

modules/packages/Python.chpl

Makes the Chapel Python module use the same sys.path as a system Python, respecting things like PYTHONUSERBASE.
[Not reviewed - will get a post-merge review]

Make the Python module sys.path the same as `python`

---

test/library/packages/Python/examples/numba/apply.skipif

Numba/numpy does not like valgrind, skipif the test

Skip numba apply test with valgrind

---

test/parallel/taskCompare/elliot/empty-chpl-remote-taskspawn.ml-timeout

Setting the timeout to 100 seconds for all platforms caused some timeouts on the HPE Cray EX platform. Make the timeout conditional so it is 100 seconds on the HPE Apollo, and (the default) 300 seconds on everything else.

Reduce timeout only on the HPE Apollo platform

---

frontend/include/chpl/resolution/resolution-queries.h
frontend/include/chpl/types/ArrayType.h
frontend/include/chpl/types/DomainType.h
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/prims.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/return-type-inference.cpp
frontend/lib/types/ArrayType.cpp
frontend/lib/types/DomainType.cpp

This came up as a TODO on https://github.com/chapel-lang/chapel/pull/26628, and in a discussion as part of the Dyno meeting. Dyno, unlike production, can't statefully associate runtime types with their domains and arrays. Fortunately, there's a standard function `chpl__convertValueToRuntimeType` (thanks @benharsh for pointing it out) which invokes the corresponding builder. This PR leans on that function to define a query to compute an array's or domain's runtime type, removing runtime types from the substitutions of these types. This fixes a failure in CLS, where resolving the string module resulting in resolving a promoted expression, which, in turn, created an array without a runtime type.

Dyno: Switch to a different mode of computing runtime types in Dyno

---

modules/packages/Python.chpl
modules/packages/PythonHelper/chpl_wchar.h

Use the proper header wchar_t with a C++ compiler, where this should only occur with GPUs

Use the proper header wchar_t with a C++ compiler

---

test/runtime/configMatters/comm/cache-remote/prefetchCounters.chpl
test/runtime/configMatters/comm/cache-remote/prefetchCounters.good

This PR makes several changes to prefetchCounters to avoid instability in the test.
1. It aligns the memory allocated for the test array to avoid the potential for different array buffer alignment causing different behavior.
2. It prefetches data more than a cache page apart (to avoid the possibility for the readahead to impact things, though it shouldn't because multi-page readahead is disabled by default)
3. Instead of waiting for prefetches with a "make work" loop, it waits for a PUT through the cache that happens after the prefetches.
Note that, at present, the logic in `chpl-cache.c` in `do_wait_for` can't necessarily tell the difference between "waited for a prefetch" and "the comms layer thought it had to wait for a prefetch but once it looked it found everything ready". This could …

Address instability in prefetchCounters

---

doc/util/versionButton.php

In my previous commit, I forgot that docs/main is itself a symbolic link to a directory that is automatically updated by Jenkins distinctly from the main static website directory.  The result was that "../" didn't work as a path since it wouldn't end up in 'docs/' bit the directory to which Jenkins syncs.
Here, I've updated the symbolic link to go to the static website to find the versionButton.php.  This time, I've tested this same path on the live website, so as long as I didn't make a trancription error, it ought to work.

Fix versionButton symbolic link

---

util/cron/test-perf.cray-cs-hdr.champs.c-backend.bash

Use clang as the C backend for CHAMPS testing. This is because GCC uses too much memory to compile CHAMPS with NPROCS=0
[Not reviewed]

Use clang as the C backend for CHAMPS testing

---

test/studies/champs/sub_test

Adjusts the CHAMPS sub_test to warn about CHPL_TARGET_COMPILER=gnu
Followup to https://github.com/chapel-lang/chapel/pull/26742
[Not reviewed]

Adjust CHAMPS sub_test to warn about CHPL_TARGET_COMPILER=gnu

---

util/cron/test-perf.chapcs.playground.bash
util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash

This tests the pull request adding the Qthreads 1.22 release candidate in the performance playgrounds to check for any performance regressions/improvements.

Test Qthreads RC In Performance Playgrounds

---

test/release/examples/primers/cClient.suppressif

After https://github.com/chapel-lang/chapel/pull/26741, the `cClient` primer can now be run with the CPU-as-device mode. I confirmed this locally. I didn't dig too deep into why, but this test has an `extern proc` whose return type must have been impacted by that PR. By looking at the last suppressed failure of this test, it looks like an internal compiler error, which could be because the GPU transforms' sensitivity to return types or some bogus AST generated because of it.
Tested locally with cpu-as-device mode.

Remove a GPU locale model suppressif

---

modules/internal/ChapelBase.chpl
modules/standard/Sort.chpl
test/library/standard/Sort/errors/sortArrayField.chpl
test/library/standard/Sort/errors/sortArrayField.good

Improve error message when trying to sort an unsupported record
There are two fixes here
1. Adjust `chpl_field_lt` to always return a value, its not required for normal calls becayse of the `compilerError`, but it seems to trip `canResolve` up.
2. Specialize the error message for `chpl_compare` when the defaultComparator can't be used to sort elements
Resolves https://github.com/chapel-lang/chapel/issues/26729

Improve error message when trying to sort an unsupported record

---

modules/packages/Python.chpl
test/library/packages/Python/correctness/arrays/myDict.chpl
test/library/packages/Python/correctness/arrays/myDict.good
test/library/packages/Python/correctness/basicTypes.chpl
test/library/packages/Python/memleaks/basicTypes.chpl
test/library/packages/Python/memleaks/maps.chpl
test/library/packages/Python/memleaks/maps.good

Resolves Cray/chapel-private#7140
Covers:
- writing the type
- size
- get
- set
- del
- clear
- copy
- contains
Also ensures the type can be converted to and from a Chapel map.
Does not cover:
- items
- keys
- values
- pop
- update
as these methods are handled differently in their C API than in Python itself.
Adds a new PythonException subclass in support of the `del` method, though the use of this subclass seems to be dependent on the Python version (it was used with Python 3.12, but Python 3.10 didn't recognize it while still giving a failure).
Added a basic test of the new type and a memleaks test of it.  Extended the basicTypes test and the memleaks basicTypes test to include it.  Passed a full paratest with futures.

Add support for Python dictionaries to the Python module

---

make/compiler/Makefile.gnu

When compiling on a system with MPICH 4.0.2 and GCC 12.2.0, and `CHPL_TARGET_COMPILER=mpi-gnu`, we were seeing compilation fail (for `make WARNINGS=1`) due to a spurious warning from GCC when building the runtime. This type of spurious warning is already disabled when compiling the generated code. This PR uses `-Wno-error` to make it a warning (not an error) if it comes up when building the runtime with `make WARNINGS=1`.

Avoid fatal warning-as-error when compiling with mpicc

---

test/library/packages/HDFS/hdfsNumbers.suppressif
test/library/packages/HDFS/hello-hadoop.suppressif

It looks like our test environment is missing libjvm (which I think has something to do with Java, judging by the set up steps I followed to replicate nightly's behavior)
Tested the failure in a setting without hadoop and in the environment where the tests fail.

Update the suppressif for these tests

---

util/cron/create_release_aptrpm.bash
util/packaging/apt/common/fill_docker_template.py
util/packaging/apt/debian11-gasnet-udp/Dockerfile.template
util/packaging/apt/debian11/Dockerfile.template
util/packaging/apt/debian12-gasnet-udp/Dockerfile.template
util/packaging/apt/debian12/Dockerfile.template
util/packaging/apt/test/Dockerfile.template
util/packaging/apt/ubuntu20/Dockerfile.template
util/packaging/apt/ubuntu22-gasnet-udp/Dockerfile.template
util/packaging/apt/ubuntu22-ofi-slurm/Dockerfile.template
util/packaging/apt/ubuntu22/Dockerfile.template
util/packaging/apt/ubuntu24-gasnet-udp/Dockerfile.template
util/packaging/apt/ubuntu24-ofi-slurm/Dockerfile.template
util/packaging/apt/ubuntu24/Dockerfile.template
util/packaging/common/build_helpers.sh
util/packaging/common/test_package.py
util/packaging/docker/test/Dockerfile
util/packaging/rpm/amzn2023-gasnet-udp/Dockerfile.template
util/packaging/rpm/amzn2023-ofi-slurm/Dockerfile.template
util/packaging/rpm/amzn2023/Dockerfile.template
util/packaging/rpm/common/fill_docker_template.py
util/packaging/rpm/el9-gasnet-udp/Dockerfile.template
util/packaging/rpm/el9-ofi-slurm/Dockerfile.template
util/packaging/rpm/el9/Dockerfile.template
util/packaging/rpm/fc40-gasnet-udp/Dockerfile.template
util/packaging/rpm/fc40/Dockerfile.template
util/packaging/rpm/fc41-gasnet-udp/Dockerfile.template
util/packaging/rpm/fc41/Dockerfile.template
util/packaging/rpm/test/Dockerfile.template

Allow the use of a cached base Docker image for package builds, _even if_ the network connection is too poor to check if a newer version is available.
Our packaging builds fail frequently, and one of the most common causes is network timeouts while pulling base images. Though Docker is smart about not pulling already-cached images, it still must fetch metadata to determine if a newer image is available for the requested tag, and even this will sometimes time out. So, work around it by:
1. Attempt to pull the image as a best-effort, but ignore failure to do so.
2. Get the SHA256 repo-digest of the image, which is the mechanism Docker uses to find changed images. Note repo-digest vs plain old digest is important here as the former as repo-digest is per-tag, whereas digest is …

Cache package build base images more aggressively

---

Makefile.devel
third-party/chpl-venv/test-requirements.txt
tools/chpl-language-server/Makefile
util/cron/nightly
util/cron/nightly_email_file.pm
util/cron/nightlysubs.pm
util/test/convert_nightly_system_command_log_to_junit_xml.py
util/test/convert_start_test_log_to_junit_xml.py
util/test/merge_junit_xmls
util/test/merge_junit_xmls.py
util/test/start_test.py
util/test/sub_test.py

This PR makes some improvements to the way that we collect JUnit XML entries, which are responsible for 1) flagging Jenkins jobs as "unstable" (as opposed to passing) and 2) showing what failed from the web interface. It does so in the following ways:
1. Hardens the log -> XML extractor against unrelated output. E.g., some prediffs or checks used to print `[Skipping ...`, which was picked up as "skipping a test" when parsing the log output. This is not correct, so this PR introduces an allowlist of all possible skip markers.
2. Ensures that `sub_test` crashes are caught. To this end, standardizes output from failing `sub_test` invocations in `start_test`, and starts treating "Failure running sub_test" as a waypoint of starting / ending a test block (along with `Starting sub_test` and …

Improve what goes into JUnit XML for reporting with Jenkins

---

.github/workflows/CI.yml

This updates the GHCI workflow to stop deleting the `versionButton.php` file on the remote side.
Since https://github.com/chapel-lang/chapel/pull/26670 removed `versionButton.php`, `rsync` wants to delete it now since it doesn't exist on the source side. This adds an `exclude` option to the `rsync` command to ignore it.

exclude versionButton.php from rsync command

---

.github/workflows/monitor-homebrew.yml

This lowers the frequency of checking for changes to the homebrew formula from 4 hours to 24 hours. It also changes the workflow to only run on `chapel-lang/chapel` and not forks of chapel.

Reduce frequency of checking Homebrew formula, limit to chapel-lang/chapel

---

Dockerfile

Remove version specifications for the `debian` base image we use as well as package versions installed in the Docker image, so we always use a reasonable default and don't have to bump versions.
Resolves https://github.com/Cray/chapel-private/issues/6717.
Testing:

Unpin Dockerfile base image and package versions

---

util/cron/common-arkouda.bash

Removes Python 3.9 version pin for arkouda testing.

Remove Python 3.9 version pin for arkouda testing

---

util/cron/load-base-deps.bash

This PR adds a special case for a testing system which has broken mounts on compute nodes. After this PR, dependencies on the lustre filesystem will be used instead. This will enable dynamically loading dependencies.
I'll test this manually to see if the dependencies we'll end up using still work.

Use dependencies in lustre on an XC test system

---

test/optimizations/autoAggregation/perf/autoAggNegativeImpact.prediff

Turn on chpl_launchCmd debugging and save the raw output on the HPE Apollo platform. This is to help with debugging a timeout of this test.

Save raw output from performance test timeout

---

test/scan/scanPerf.ml-execopts

Co-locales necessarily share physical memory, requiring a proportionally smaller problem size.

Reduce the problem size if there are co-locales

---

tools/chplcheck/src/rules.py

Improves the location reporting for the linter rule BoolLitInCondStmt. The location reported is now only for the condition, which makes for much nicer linter warnings (especially when run in the LSP)
Before
After

Improve location reporting for BoolLitInCondStmt

---

runtime/src/launch/slurm-srun/launch-slurm-srun.c

This came up as an unused variable error on `ret`, which is something I added for debugging. But then the debugging code is removed, leaving the variable unused. This PR adds proper error checking based on that variable instead of removing it.
Locally was able to build the runtime with `CHPL_LAUNCHER=slurm-srun`

Add one more error checking in slurm-srun sbatch code path

---

test/release/examples/primers/interopWithC.skipif
test/release/examples/primers/interopWithChpl.skipif

This adds a `.skipif` for the `interopWithChpl.test.c` added yesterday in #26762 if LLVM is not enabled within the Chapel compiler.  This is necessary due to the use of 'extern' blocks within `interopWithC.chpl`, which this test relies upon.  In my original PR, I'd missed that `interopWithC.chpl` has a similar skipif, which has been guarding it from the failures that the new test hit last night.
Referring to `interopWithC.skipif` after filing this fix, I noticed that it's been checking for whether the back-end compiler is LLVM rather than whether the `chpl` compiler was built with LLVM enabled, where the former is broader than the latter (e.g., an LLVM-enabled compiler can use a C back-end but still parse `extern` blocks).  I'm fairly certain that the latter is the only case we need to …

Skip interopWithChpl.test.c if LLVM is not enabled

---

frontend/include/chpl/framework/Context.h
frontend/lib/resolution/InitResolver.h

Compilation Errors: https://gist.github.com/SAtacker/0f8ef0fdef30313fc2072834f8050ec0
What's the problem before C++20? : https://stackoverflow.com/questions/57271400/why-does-aggregate-initialization-not-work-anymore-since-c20-if-a-constructor
Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

[Fix C++20] Does not compile because not an aggregate anymore

---

CMakeLists.txt
doc/rst/conf.py
util/config/update-release-and-version-info

This uses a combination of python scripts and cmake dependencies to keep the version number information consistent with the information in `CMakeLists.txt`. The purpose is to avoid manually having to update the version number across a variety of documents with every release. With this change, the version numbers will be correctly updated based on the status of the `CHPL_OFFICIAL_RELEASE` flag, and the current and previous version numbers. 
This necessitated tracking the past version number as the `archived-spec.rst` file needs to know the previous version number. 
Because we can't predict the past version number from the current one, it was necessary to add these fields to the `CMakeLists.txt` file.
New files that need updating can be handled by creating new instances of the `FileUpdater` …

use cmake and python to keep version numbers updated

---

test/release/examples/primers/cHelper.c
test/release/examples/primers/cHelper.h

Until yesterday, interopWithC.chpl had not been getting tested with the C back-end because its skipif was skipping if LLVM wasn't being used as the back-end compiler (rather than if LLVM was configured so that 'extern' blocks could be used).
After fixing this in https://github.com/chapel-lang/chapel/pull/26783 yesterday, we started getting a warning-as-error for certain back-end C configurations (e.g., gcc, but seemingly not clang) due to 'const'ness being discarded when passing an array out to the external 'sumArray' call.  That call wasn't modifying its array argument, so in this PR, I've added a 'const' qualifier to the routine and its prototype, which makes the issue go away.

Fix a const-ness issue in cHelper.c

---

doc/rst/platforms/udp.rst

This error was sufficiently unfamiliar to me that it would not have occurred to me to apply this fix, and I didn't see any indication of it in our docs, so added this section to capture it and the fix.
I've had this edit sitting in my tree for a few days now, but am pushing it tonight to fire off another smoke test.

Update UDP docs to mention "DNSLookup" error and `CHPL_RT_MASTERIP`

---

util/cron/common-playground.bash
util/cron/test-perf.chapcs.playground.bash
util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash

Aborts the perf playgrounds if any of the git operations to apply an external branch fail

Abort the perf playgrounds if git operations fail

---

util/cron/test-hpe-apollo-hdr.arkouda.bash
util/cron/test-hpe-apollo-hdr.arkouda.release.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.colo.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.release.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.release.colo.bash

https://github.com/Bears-R-Us/arkouda/pull/4088 was merged in couple of days ago. Now we can start testing the `master` Arkouda branch in the new configs. This PR removes specific fork/branch from testing scripts.

Move new Arkouda test configs to the master branch

---

runtime/src/comm/gasnet/comm-gasnet-ex.c

PR #26791 inadvertently introduced a segfault for `verbosity >= 2` and `CHPL_GASNET_SEGMENT=everything`.
In GASNET_SEGMENT_EVERYTHING mode, we don't have a real GASNet segment, and the attempt to invoke `gex_Segment_QuerySize` on the invalid segment introduced by #26791 was causing a segfault.

Fix a regression introduced in #26791

---

util/cron/common-playground.bash
util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash

In #26804 which was merged last night, it appears that a `source $UTIL_CRON_DIR/common-playground.bash` was forgotten, which caused the new subroutine `checkout_branch()` not to be available to be called. This adds that `source`, similar to `test-perf.chapcs.playground.bash` in hopes of resolving it in the next run.
The chapcs playground also didn't run last night, due to getting the standard "divergent branch" error that's common in newer versions of `git` (possibly because these are the first playgrounds we've run on chapcs since the OS upgrade).  So I've added the `--no-rebase` flag to the `git pull` command in order to get the traditional/historical "merge" behavior.

Attempted fixes to both chapcs and apollo playgrounds

---

util/devel/test/apptainer/current/fedora-41-nollvm/image.def
util/devel/test/apptainer/current/fedora-41/image.def
util/devel/test/vagrant/README-distro-timelines.txt

This PR adds apptainer image definition files for Fedora 41 for use in portability testing.

Add Fedora 41 to portability testing

---

test/studies/arkouda/sub_test

Adds the current Arkouda commit being tested to the the log output. This will aid troubleshooting

Add the current Arkouda commit to the log

---

modules/packages/CopyAggregation.chpl

`getEnvInt` calls `createAdoptingBuffer` with the C string returned by `getenv`. It then returns the string cast as an int which frees the string. `getenv` returns a string constant, so this results in the free of an address that was not allocated, resulting in memory corruption. Calling `createCopyingBuffer` does not free the string when `getEnvInt` returns.

Don't free getenv result

---

.github/workflows/CI.yml

This modifies the CI process of uploading the documentation using `upload-artifact` action to include symlinks that don't resolve. The behavior of `upload-artifact` is that it ignores broken symlinks, so the changes to `versionButton.php` that made it a symlink also caused it to stop being included in the docs archive from the `upload-artifact` action.
The workaround is to have tar bundle the `docs/html` directory and then have the `upload-artifact` action upload that instead of the `docs/html` directory. This preserves the symlink, and performing a `diff -r` on the resulting folders shows the only difference is that the one bundled with tar includes `versionButton.php`.
CI change only - Not reviewed

bundle docs in CI step to preserve symlinks

---

util/cron/test-hpe-cray-ex-ofi.bash

Adds an explicit SLURM_PARTITION to a test config. This is required for the machine this config runs on

Use an explicit slurm partition on test config

---

util/cron/test-hpe-apollo-hdr.arkouda.bash
util/cron/test-hpe-apollo-hdr.arkouda.release.bash

This PR switches from `ARKOUDA_QUICK_COMPILE` to `ARKOUDA_DEVELOPER` in Arkouda testing. The effect is that we explicitly throw in `--checks` to make sure to catch errors.

Enable runtime checks in Arkouda testing

---

util/test/prediff-for-slurm

Use bytes instead of strings in a slurm prediff. This is similar to the fix done in https://github.com/chapel-lang/chapel/pull/26712 and https://github.com/chapel-lang/chapel/pull/26735
I am adding this because I noticed the following error messages in our nightly test logs
```
[Elapsed execution time for "release/examples/benchmarks/shootout/mandelbrot" - 5.869 seconds]
[Executing system-wide prediff /............/workspace/hpe-cray-ex-correctness-test-hpe-cray-ex-ofi/chapel/util/test/prediff-for-slurm]
Traceback (most recent call last):
File "/............/workspace/hpe-cray-ex-correctness-test-hpe-cray-ex-ofi/chapel/util/test/prediff-for-slurm", line 38, in <module>
outText = f.read()
File "<frozen codecs>", line 325, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 …
```

Use bytes instead of strings in slurm prediff

---

frontend/lib/resolution/Resolver.cpp

This caused problem building Arkouda without `--dyno`, where a normal "scope resolution" pass triggered resolution, which doesn't work yet.

Dyno: avoid resolving array constructors when scopeResolveOnly is set

---

modules/standard/Map.chpl
test/library/standard/Map/copyInitArgIntent.chpl

I noticed that I wasn't able to pass `map`s as `const ref`s and use them in copy initializers. I believe the fix is simple, but `map` has some complicated internal implementation for class management etc, for which this fix here might be problematic.
Test:

Fix the map.init= arg intent

---

test/unstable/Time/checkTotalMicro.chpl
test/unstable/Time/checkTotalMicro.good
test/unstable/Time/checkTotalMilli.chpl
test/unstable/Time/checkTotalMilli.good

I mistakenly did not add these when adding the methods, rectify that oversight.
Thanks Shreyas for pointing it out!

Add tests for the unstable warnings on totalMicroseconds and totalMilliseconds

---

frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/Resolver.h

As part of getting the typed converter to work, David recently enable resolving the formals of functions when resolving the function as a whole. This triggered a bug in which a missing `ResolutionContext` frame (missing due to call graph tracking not keeping tabs on resolution contexts) made an outer variable that was previously resolved `unknown`. However, the outer variable was stored in the typed signature; in this PR, adjust David's logic to ensure outer variable types are used as proper.
While there, observe that `localGenericToUnknown` is never used, and seems to be handled elsewhere; remove it.

Dyno: fix outer variable bug triggeerd by Atomics module.

---

compiler/passes/convert-typed-uast.cpp
doc/util/nitpick_ignore
frontend/include/chpl/resolution/ResolutionContext.h
frontend/include/chpl/resolution/resolution-queries.h
frontend/include/chpl/resolution/resolution-types.h
frontend/include/chpl/types/Type.h
frontend/lib/resolution/InitResolver.cpp
frontend/lib/resolution/ResolutionContext.cpp
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/Resolver.h
frontend/lib/resolution/call-init-deinit.cpp
frontend/lib/resolution/copy-elision.cpp
frontend/lib/resolution/default-functions.cpp
frontend/lib/resolution/prims.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/resolution-types.cpp
frontend/lib/resolution/return-type-inference.cpp
frontend/lib/types/ArrayType.cpp
frontend/lib/types/CompositeType.cpp
frontend/lib/types/DomainType.cpp
frontend/lib/types/Type.cpp
frontend/test/resolution/testCPtr.cpp
frontend/test/resolution/testClasses.cpp
frontend/test/resolution/testGenericDefaults.cpp
frontend/test/resolution/testHeapBuffer.cpp
frontend/test/resolution/testInitSemantics.cpp
frontend/test/resolution/testNestedFunctions.cpp
frontend/test/resolution/testNew.cpp
frontend/test/resolution/testRanges.cpp
frontend/test/resolution/testTypeConstruction.cpp

This PR enables some basic resolution of nested types by threading a ``ResolutionContext*`` through various API functions:
- resolveFieldDecl
- fieldsForTypeDecl
- typeWithDefaults
- resolveGeneratedCall
- resolveGeneratedCallInMethod
- getCopyOrAssignableInfo
- Type::isPod
- Type::isDefaultInitializable
These changes allow for resolution of nested types, their fields, and
their methods.
In the case of ``resolveFieldDecl``, a ``ResolutionContext`` is not
necessary when ``syntaxOnly=true``.
Other changes:
- Add ``createDummyRC`` as a sentinel for situations where a
ResolutionContext is not readily available. Intended to be replaced
eventually as ResolutionContext becomes more available.
- Hoist ``FieldDetail`` and ``ForwardingDetail`` out of
``ResolvedFields`` so that they can be hashed by …

Dyno: Basic support for resolving nested types

---

compiler/passes/convert-typed-uast.cpp

Fix a C++ compiler bug. Adjust by using a type alias that fully instantiates the tuple type.
Reviewed by @benharsh.

Fix unsupported tuple template argument deduction under 'clang 11.0.0'

---

frontend/doc/doxygen-pitfalls.txt
frontend/include/chpl/types/ParamTag.h
frontend/include/chpl/types/Type.h
frontend/include/chpl/types/TypeTag.h
frontend/include/chpl/uast/AstNode.h
frontend/include/chpl/uast/AstTag.h
frontend/include/chpl/uast/Pragma.h

For reasons unknown, certain symbols recently began causing arcane
errors while building documentation for the frontend. Disabling
documentation for the types affected by this PR silences these
errors. These errors general complained about some kind of duplicate ID.
I'm inclined to think this is some kind of bug in doxygen.

Dyno: Fix duplicate ID documentation errors

---

util/cron/test-networking-packages.bash

[reviewed by @mppf]
With the deprecation of the HDFS module and removal of its main test directory in #26840 , it's time to remove stuff related to Hadoop and HDFS from this job.  If we end up restoring support for the module, we should re-enable this
Running the script on our normal testing machine seemed to work okay, though it looks like we'll need to manually remove `/tmp/hadoop-<our testing username>`

Remove Hadoop stuff from the networking-packages test job

---

modules/packages/CopyAggregation.chpl

This PR improves the CopyAggregation docs as a follow-up to PR #26681.
* documents `copy` methods
* documents `flush` methods including the new `freeBuffers` optional argument

Improve CopyAggregation docs

---

util/build_configs/cray-internal/setenv-xc-x86_64.bash

The Aries conduit has been removed from GASNet as of GASNet-EX 2025.2.0-snapshot, thus we should no longer try to build it.
Resolves https://github.com/Cray/chapel-private/issues/7212.

Remove GASNet comm layer from XC

---

util/config/make_sys_basic_types.py

Fixes a portability issue in the script that generates the type for c_wchar_t on Alpine Linux, found during portability testing for the 2.4 release
The issue was introduced by the addition of `wchar_t` in https://github.com/chapel-lang/chapel/pull/26828
Test that on Alpine 3.20 Chapel builds, make check passes, and that `start_test test/extern/ferguson/` works

Fix portability issue with c_wchar_t on Alpine Linux

---

test/gpu/native/studies/shoc/shoc-sort.suppressif

Add a temporary suppressif for this failing test.
See https://github.com/chapel-lang/chapel/issues/26669 for more details about the issue.
Testing:-

Suppress shoc-sort failures in ROCm6 configuration

---

runtime/src/qio/sys.c

This is a copy of a closed PR https://github.com/chapel-lang/chapel/pull/26452/
Patch was originally submitted by @EduardoMorras, [emorras@emorras.eu](mailto:emorras@emorras.eu)
This fixes a portability issue with FreeBSD 13.4, 14.1, and 14.2 (maybe others) when using LLVM version 19 (maybe others) 
resolves https://github.com/chapel-lang/chapel/issues/22549
TESTING:

fix FreeBSD warning/error about missing `inet_aton`

---

frontend/lib/parsing/ParserContextImpl.h

Removes the unused variable in a structured binding, by removing the structured binding and accessing the first member of the pair.

Remove unused variable from structured binding

---

test/optimizations/autoAggregation/perf/autoAggNegativeImpact.skipif

This test hangs on GASNet with co-locales and should be skipped. See https://github.com/Cray/chapel-private/issues/7173 for details.

Skip test on GASNet with co-locales

---

util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash

This turns off the performance playground on Apollo, which had been testing the new GASNet, hadn't shown any major surprises, and that GASNet is now on main.
This'll be the first run with it off since Ahmad's https://github.hpe.com/hpe/hpc-chapel-ci-config/pull/1369 was merged, so it'll be interesting to see whether it stays blue as expected.
Meanwhile, I've also updated the playground to test Qthreads on multilocale, and will plan to enable that after a night or two of having it off to start gathering data there with an eye towards 2.5.

Turn off Apollo playground for now; set up for Qthreads as next config

---

third-party/chpl-venv/Makefile

Fixes a check for the Python version for test-venv/chpldoc, which was still using Python 3.5. We actually only support Python 3.9+, see https://chapel-lang.org/docs/main/usingchapel/prereqs.html#chapel-prerequisites
[Reviewed by @jhh67 and @mppf]

Fix version check for Python to match docs

---

util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash

This turns Qthreads testing back on in the multilocale playground now that we've merged GASNet testing and tested that the playground's status remains blue when it's unused.

Turn on Qthreads testing in the multilocale playground

---

modules/standard/GMP.chpl
modules/standard/GMPHelper/chplgmp.h

[reviewed by @mppf]
Credit for this idea goes to Michael.
Before this, we were passing un-exported function pointers to external C functions.  This was potentially one of the issues impacting a user code, though there still seem to be other issues.
This PR makes it so that we define those functions in C directly, allowing them to be passed more cleanly (although losing some information about the file where they were called in the process).

Avoid a GMP potential ABI incompatibility with LLVM

---

modules/standard/JSON.chpl
test/io/serializers/jsonHelpers/fromJsonThrows.chpl
test/io/serializers/jsonHelpers/fromJsonThrows.cleanfiles
test/io/serializers/jsonHelpers/fromJsonThrows.good
test/io/serializers/jsonHelpers/fromJsonThrows.preexec

`JSON.fromJson` used the pattern:
```chpl
return reader.read(MyType);
```
this results in calling a compiler-generated deserialization initializer that does not throw. While working on Arkouda checkpointing that led to writing code in which there are uncatchable errors. I worked this around in Arkouda for the time being by having my own `fromJson`-like helper.
This PR adjusts the standard `fromJson` to use the following pattern, from which an error can be thrown and caught as expected:
```chpl
var ret: MyType;
reader.read(ret);
return ret;
```
Test:

Work around an issue preventing users to catch errors from `JSON.fromJson`

---

modules/packages/Socket.chpl

The Socket module uses a sync variable in some of its functions to wait for some events. This sync variable is passed via `c_ptr`s to a callback function. However there are inconsistencies in the types used:
- There are 4 places where this happens: 3 of them uses `sync c_short`, 1 uses `sync int`
- The callback function assumes that the flag is `sync int`.
The callbacks seems to write a `c_short` into this sync variable. Therefore, I assume that `c_short` is a more correct choice. So, this PR makes the sync variable of `c_short` type and adjusts the callback.
Test:

Make the sync flag's type consistent in the Socket module

---

test/arrays/arrOfArrs/leaking.bad
test/arrays/arrOfArrs/leaking.prediff

I forgot to take into account that the amount leaked by this new test could reflect:
* CHPL_COMM=none vs. !=none
* 32- vs 64-bit linux
* C compiler choices
which made my leaking.bad file a bit too specific to where I tested it and broke it in some of our test configurations.  This expands the prediff to not just filter the addresses being leaked but any other integer preceded by 7 spaces, which happens to cover the number of bytes per domain, and total, leaked, but also the count of 1.  This all seems acceptable, though.

Improve portability of leak testing

---

doc/rst/technotes/throwingInit.rst

While writing up my CHANGES.md entries, I realized that I hadn't documented that postinit() routines can now throw, so am adding that to the `throwingInit` tech note here, merging it into the description of throwing initializers since init and postinit() sort of form the initialization process together.
While here, I tried to clarify some of the limitations of the current implementation that weren't clear to me when I was reading this previously (e.g., I read "being able to throw from anywhere in the body of an initializer" as being about being able to throw before `init this;` not about being able to use a `throw` statement at all), and tried to tighten up the description a bit (e.g., talking about cleaning up the memory once rather than twice).

Document that postinit() procedures can throw

---

doc/rst/usingchapel/compiling.rst

Adds a new section to the [compiling](https://chapel-lang.org/docs/2.4/usingchapel/compiling.html) docs, listing various build systems users can use. This PR adds Mason (just a pointer to the mason docs really), Makefile, and CMake
[Reviewed by @lydia-duncan  and @arezaii]

Add build system docs for building chapel projects

---

doc/rst/conf.py

Fixes https://github.com/chapel-lang/chapel/issues/26871, by making sure that `ChapelSysCTypes` is excluded from sphinx as its already included in the CTypes docs
resolves https://github.com/chapel-lang/chapel/issues/26871

Exclude ChapelSysCTypes from the documentation like other builtins

---

doc/rst/usingchapel/chplenv.rst

Updates the docs for `CHPL_LLVM_GCC_INSTALL_DIR` to mention that they can now be inferred.

Update docs for `CHPL_LLVM_GCC_INSTALL_DIR`

---

util/chplenv/chpl_llvm.py

Fixes a regression introduced by https://github.com/chapel-lang/chapel/pull/26761, where explicitly specifying `CHPL_LLVM_GCC_INSTALL_DIR` or `CHPL_LLVM_GCC_PREFIX` would no longer work. This PR just reorders some of the logic introduced by #26761 to allow supporting this again.

Fix CHPL_LLVM_GCC_INSTALL_DIR and CHPL_LLVM_GCC_PREFIX not being able to be overridden

---

test/library/packages/Python/correctness/importError.suppressif

Adds a suppressif for a new test which leaks memory due to https://github.com/chapel-lang/chapel/issues/26437

Add suppressif for memleaks testing for importError test

---

test/ANNOTATIONS.yaml

This seems to have impacted these tests:
https://chapel-lang.org/perf/chapcs/?startdate=2024/08/07&enddate=2025/03/04&graphs=bigintegerperformanceslowops,pidigitsvariations,submittedpidigitsshootoutbenchmark

Add annotation about sysroot change

---

util/cron/test-perf.hpe-apollo-hdr.arkouda.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.colo.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.release.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.release.colo.bash

In manual tests, I see that the `array_transfer` test can take some time to finish. Moreover, sometimes, the average time to finish it almost doubles. That behavior seems random and can push the execution over the client timeout. This PR doubles the timeout.

Double the Arkouda timeout on the new performance configs

---

test/gpu/native/studies/shoc/shoc-sort.skipif

Because I forgot what is `true` in bash 🤦
- Now we're skipping in cpu-as-device again

Fix bug in shoc-sort skipif

---

util/cron/common-arkouda.bash

Fixes the partial checkout logic for arkouda testing to use the `util/test` from main.

Fix the partial checkout logic for arkouda testing

---

doc/rst/platforms/infiniband.rst
doc/rst/platforms/omnipath.rst

This PR is motivated by a desire to talk more about how GASNet and MPI can conflict with one another in their desire for resources, leading to either performance hits or simply an error trying to acquire the desired resources.  It includes an error message that we've seen a few times (ourselves, and by users) in recent Omni-Path runs.  It primarily points off to GASNet documentation for remedies.
While here, I also did some wordsmithing (including an improvement suggested by Paul), added additional links to GASNet documentation about mpi/pmi/ssh spawners, and made sure the OmniPath and IB cases are still in sync (a few things had drifted apart).
Related to this PR:
* @jabraham17 has a start at an attempt to refactor our multilocale documentation to make it better organized and avoid …

Update IB/Omni-Path docs to talk about GASNet and MPI playing nice together / point to GASNet READMEs

---

CONTRIBUTORS.md

Refreshed the list of most recent contributors to reflect those who contributed code, triage, and release artifacts for Chapel 2.4.
Thanks to first-time contributors @ajpotts, @SAtacker, and @EduardoMorras, as well as returning contributors @astatide , and @rchinmay !

Contributors list for Chapel 2.4

---

CONTRIBUTORS.md

Considering that the triaging he's been doing of GASNet portability testing errors and reporting them counts as a contribution to the release artifacts and its quality.

Belatedly adding Paul Hargrove to the CONTRIBUTORS file

---

CHANGES.md

These are the major changes made for Chapel 2.4.  Thanks to everyone who contributed!

CHANGES.md updates for Chapel 2.4

---

CMakeLists.txt
doc/rst/conf.py
man/confchpl.rst
man/confchpldoc.rst
test/chpldoc/compflags/combinations/versionhelp-chpldoc.sh
test/compflags/bradc/printstuff/version.goodstart
test/compflags/bradc/printstuff/versionhelp.sh

This updates the version to reflect v2.5 pre-release status. 
Corresponding PR that marked the tree as 2.4 release: https://github.com/chapel-lang/chapel/pull/26906 
Corresponding PR from previous unfreezening: https://github.com/chapel-lang/chapel/pull/26387
Notice a discrepancy between this PR and 26387. This PR includes changes to `conf.py` where past unfreezenings made the update to `conf.py` as part of the `versionButton.php` changes. Since that file has been moved to the website's tree, we decided to go ahead and include `conf.py` with these changes.
TESTING:
[reviewed by @arifthpe - thanks!]

set 2.5 pre-release, unfreeze main

---

frontend/test/test-common.cpp

We appear to be encountering some kind of issue by placing this static variable at the file-level scope, which results in a double destruction of a ``Context``. Moving it inside ``buildStdContext`` resolves the failures.

Dyno: Fix test-frontend segfaults

---

test/studies/arkouda/sub_test
util/cron/common-arkouda-hpe-apollo-hdr.bash
util/cron/test-hpe-apollo-hdr.arkouda.bash
util/cron/test-hpe-apollo-hdr.arkouda.release.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.release.bash

Adds `--temp-directory` for arkouda testing, to workaround filesystem issues on our test systems

Add `--temp-directory` for arkouda testing

---

util/chplenv/chpl_compiler.py

Warn when using a non-prgenv compiler when it is available. Failing to do this can cause strange build errors, so this warning guides users to do the right thing.

Warn when using a non-prgenv compiler when it is available

---

doc/rst/conf.py

Exclude generated chplcheck rules from the docs, since it gets brought in by `.. include`. This fixes an issue where the docs had duplicate entries for the chplcheck rules. This was only visible by URL manipulation or from the search bar

Exclude generated chplcheck rules from the docs

---

test/chplcheck/ChplPrefixReserved.chpl
tools/chplcheck/src/rules.py

Skips linting for the prefix `chpl_` being reserved on extern functions, because users have no control over extern code in their Chapel code.

Skip ChplPrefixReserved for extern functions

---

frontend/include/chpl/resolution/resolution-types.h
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/Resolver.h
frontend/lib/resolution/call-graph.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testNestedFunctions.cpp
modules/internal/BytesStringCommon.chpl
modules/internal/ChapelRange.chpl

This PR fixes various issues when attempting to use an implicit receiver in a nested function by appropriately setting up certain fields in the Resolver factory methods.
This PR also silences some errors that were being issued by call-graph. It was assumed that these ``resolveFunction`` calls would generally be querying a cached result, but ``ResolutionContext`` never saved its nested function query results in the ``Context`` because it was in an "unstable" state. The results have been stored in ``ResolvedFunction`` however, and are used by this PR to avoid re-resolving the functions without a suitable stack of "frames".
Ideally we wouldn't have to deal with this manually at all and just have ``resolveFunction`` work, but it's not clear to me at this time how to make that happen.
Testing:

Dyno: Improve nested function receivers and call-graph

---

modules/packages/Python.chpl
test/library/packages/Python/correctness/objToString.chpl
test/library/packages/Python/correctness/objToString.good

Adds `repr` as a standalone method to the Python.Value base class. This corresponds to the Python `repr(obj)`.

Add `repr` method to Python.Value base class

---

modules/packages/Python.chpl
test/library/packages/Python/COMPOPTS
util/config/embed-python.sh

Adds an `embed-python.sh` script to make getting the right compilation flags for building Chapel with the Python module easier.
When running code with the Python module standalone, I usually reuse one of the test directories COMPOPTS, but that doesn't really help users. This PR essentially makes that COMPOPTS user-facing to make it easier for users.
As future work, I think we could consider a proper command-line option for the compiler for this, something like `chpl --embed-python .....`. But if we do that, I think the Python module should be treated more like a standard module than a package module.

Add `embed-python.sh` script to make building Chapel+Python code easier

---

frontend/lib/resolution/default-functions.cpp
frontend/lib/resolution/default-functions.h
frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testNestedFunctions.cpp

Fixes initialization of nested types by threading a ResolutionContext through the default-function helpers. Without this context, the initial type signature can fail to resolve if fields rely on outer variables.

Dyno: Resolve initializers for nested types

---

doc/rst/platforms/cray.rst
doc/rst/platforms/infiniband.rst
doc/rst/usingchapel/chplenv.rst
util/chplenv/chpl_comm.py
util/chplenv/chpl_comm_ofi_oob.py
util/chplenv/chpl_comm_segment.py
util/chplenv/chpl_comm_substrate.py
util/chplenv/chpl_compiler.py
util/chplenv/chpl_cpu.py
util/chplenv/chpl_libfabric.py
util/chplenv/chpl_llvm.py
util/chplenv/chpl_platform.py
util/chplenv/compile_link_args_utils.py
util/chplenv/third_party_utils.py

This PR adds support for setting `CHPL_HOST_TARGET=hpe-cray-xd` to support that platform. This also includes adding logic to distinguish between an XD with slingshot and infiniband.
This PR makes several other improvements, including improving OFI_OOB detection, general infiniband detection, general slingshot detection, and general refactoring
Tested on
- 3 different EXs with slingshot
- 2 different XD with IBV
- an hpe apollo with IBV
- an XC
This PR resolves https://github.com/chapel-lang/chapel/issues/26917 and resolves https://github.com/chapel-lang/chapel/issues/26918

Add CHPL_TARGET=hpe-cray-xd and Improve OFI_OOB detection

---

frontend/test/clang/testPch.cpp

For some unknown reason, we need to add the clang C compiler as an argument and call ``setClangFlags``. Otherwise, clang can't find headers like ``stdio.h`` and the test fails. This only occurs on macos.

Dyno: Fix testPch on macos

---

util/pastPerformance/testReleasesPerformance
util/test/perf/perfgraph.js

This adds performance graph data for the 2.4 release. Previous update for 2.3 was https://github.com/chapel-lang/chapel/pull/26393
[reviewed by @arifthpe - thanks!]

add perf graph data for v2.4

---

util/cron/test-perf.hpe-apollo-hdr.arkouda.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.colo.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.release.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.release.colo.bash

These perf test configs fail sporadically with timeouts, this PR doubles the timeout to help prevent that noise.

Double the arkouda perf test timeout on Apollo HDR

---

compiler/AST/AggregateType.cpp
compiler/AST/baseAST.cpp
compiler/AST/view.cpp
compiler/include/baseAST.h
compiler/include/view.h
compiler/passes/convert-typed-uast.cpp
compiler/passes/normalize.cpp
compiler/resolution/addAutoDestroyCalls.cpp
compiler/resolution/callDestructors.cpp
frontend/include/chpl/parsing/parsing-queries.h
frontend/include/chpl/resolution/call-graph.h
frontend/include/chpl/resolution/resolution-types.h
frontend/include/chpl/types/AnyClassType.h
frontend/include/chpl/types/ArrayType.h
frontend/include/chpl/types/BasicClassType.h
frontend/include/chpl/types/CompositeType.h
frontend/include/chpl/types/DomainType.h
frontend/include/chpl/types/ManageableType.h
frontend/include/chpl/types/RecordType.h
frontend/include/chpl/types/TupleType.h
frontend/include/chpl/types/UnionType.h
frontend/include/chpl/uast/Decl.h
frontend/lib/parsing/parsing-queries.cpp
frontend/lib/resolution/call-graph.cpp
frontend/lib/types/BasicClassType.cpp
frontend/lib/types/CompositeType.cpp
frontend/lib/types/RecordType.cpp
frontend/lib/types/Type.cpp
frontend/lib/types/UnionType.cpp

This PR adds more of my contributions to the typed converter. It adds support for compiling more language features such as parenless method calls, field access, logical operator short-circuiting, default values for records, and more! We can now write fun programs like the following.
```chapel
record r {
var x: int;
proc method() { return x; }
}
var r1: r;
var x1 = r1.x;
var x2 = r1.method();
```
- Support inserting AST at either the statement or expression level
- Convert default-argument values for initializer calls (e.g., to support compiler-generated default-initializers)
- Fold away `param` expressions immediately in `convertExpr`
- Attach flags to generated `AggregateType`, mark them as `RESOLVED`
- Convert opaque `types::ExternType*` and attach flags to them when the `type` variable …

dyno: More progress on the typed converter

---

test/library/packages/Python/correctness/objToString.good
test/library/packages/Python/correctness/objToString.prediff

Adds a prediff to sort the output of a Python test, since the output can potentially vary from run to run.

Add prediff to sort output for Python test

---

tools/chpl-language-server/Makefile

Adds logic to cleanup files generated by pytest when testing chpl-language-server

Clean generated pytest files for chpl-language-server

---

test/ANNOTATIONS.yaml
util/cron/test-perf.chapcs.playground.bash
util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash

Stop using perf playgrounds for qthreads
This PR also annotates the qthreads upgrade

Stop using perf playgrounds

---

third-party/qthread/Makefile

Fixes an issue caught in our smoke tests where CMake was trying to be too smart and pick the right sysroot/XCode SDK version. This causes other issues down the line, so this PR prevents CMake from doing that

Prevent qthread cmake from messing up mac builds

---

third-party/qthread/Makefile
third-party/qthread/README
third-party/qthread/qthread-src/CMakeLists.txt

Forces the QThread CMake file to not attempt to set the OSX deployment target.
This PR has the same goal and idea of https://github.com/chapel-lang/chapel/pull/26959, but done more forcefully by editing the CMakeLists.txt file instead of just passing the variable on the command line.
The patch forces `CMAKE_OSX_DEPLOYMENT_TARGET` to be the empty string to override the default CMake behavior (which is to try and infer a correct deployment target). This must be done after `project`, otherwise it gets overridden by the default CMake behavior.
I suspect this is incorrect behavior on CMakes part, as the documentation for [`CMAKE_OSX_DEPLOYMENT_TARGET`](https://cmake.org/cmake/help/v3.31/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html) states that setting it to an empty value prevents CMake from …

Prevent qthread cmake from setting the OSX deployment target

---

util/cron/test-perf.chapcs.playground.bash

Switch the perf playground to test main, not the non-existent branch `chapel`
[Not reviewed -trivial]

Switch playground to test main

---

third-party/qthread/Makefile
util/chplenv/chpl_compiler.py

Changes the qthreads Makefile to specify `CMAKE_[C|CXX]_COMPILER` to a value from `chplenv/chpl_compiler.py`. This allows us to the flags when the compiler has more than just the executable in it.
This also adjusts `chplenv/chpl_compiler.py` to support this use case.
This is required on platforms where `CHPL_TARGET_[CC|CXX]` has more than the executable in it. For example `CHPL_TARGET_CC: clang --gcc-toolchain=/usr`. Specifying this whole string as `CMAKE_C_COMPILER` causes CMake to fail to build. This PR fixes this by only specifying `clang` to `CMAKE_C_COMPILER`, and moving `--gcc-toolchain=/usr` to `CMAKE_C_FLAGS`.

Get the CC/CXX directly from chplenv for qthreads

---

test/library/packages/Python/correctness/paths/checkPaths.chpl

Adjusts the implementation of `test/library/packages/Python/correctness/paths/checkPaths.chpl` to avoid a ton of memory leaks, due to the bug described in https://github.com/chapel-lang/chapel/issues/26965

Adjust `checkPaths` test to avoid memory leak caused by a bug

---

util/devel/dyno_backtrace.py

LLDB exposes a convenient Python API. We can leverage this API to print clean stacktaces while resolving Dyno programs. See also my comment in the file.
```
Dyno stack trace script.
Though Dyno often performs re-computation, it's typical for the
compiler stacktrace to mirror (with a lot of function calls) the trace of
resolving the Chapel program. We can clean up this information, skipping
a lot of in-between frames, and print a Chapel-only trace. That's what this
script does.
To use the script, add the following lines to your .lldbinit file:
command script import /path/to/dyno_backtrace.py
command script add -f dyno_backtrace.backtrace dbt
Then, in the debugger, you can run the `dbt` command to print the Chapel
stack trace.
```
The output looks like this:
```
(lldb) dbt
0: …
```

Dyno: add backtracing LLDB script

---

frontend/lib/resolution/Resolver.cpp
frontend/test/resolution/testTypeQueries.cpp

Resolves https://github.com/Cray/chapel-private/issues/7228. The following program now resolves:
```Chapel
proc foo(x: [?D] ?t) { writeln(D); }
var A: [1..10] int;
foo(A);
```
We simply didn't have logic to handle this case. Now we do.

Dyno: resolve domain and element type queries on arrays

---

frontend/include/chpl/resolution/resolution-queries.h
frontend/lib/resolution/can-pass.cpp
frontend/lib/resolution/disambiguation.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testPromotion.cpp

Closes https://github.com/Cray/chapel-private/issues/7227.
This PR implements field access promotion; that is, we can now resolve code like this:
```Chapel
record pair {
var first: int;
var second: real;
}
var A: [1..10] pair;
var B = A.first;
var C = A.second;
```
I ran into issues implementing this naively, and took a look at how production does this. However, as I discovered in https://github.com/chapel-lang/chapel/issues/26938, production doesn't implement this feature properly, either!
In both Dyno and production, fields are accessed using their "getters". From there, promotion works the same as it does with anything else (by finding methods that apply to the element type, and creating wrappers). The crux of the issue is that we need to "discover" the getters in the current scope. …

Dyno: implement field access promotion

---

util/cron/common-playground.bash

Fixes an issue where the playground would crash when trying to delete a git branch that did not exist yet.
Also adds some improved logging.
[Not reviewed]

Make deleting a branch not an error if it doesn't exist

---

runtime/etc/rtmain.c
util/chplenv/chpl_qthreads.py

Removes unnecessary code after [qthreads upgrade](https://github.com/chapel-lang/chapel/pull/26823). The latest version makes the changes removed here (which were workarounds) obsolete

Remove unnecessary code after qthreads upgrade

---

util/chplenv/chpl_comm_ofi_oob.py

Further improves the ability of the Chapel build system to infer the value of `pmi2` for OFI_OOB. 
This is done in two specific cases
- when `cray-pmi` is loaded: improved by using the correct `pkg-config` name
- when `cray-pmi` is not loaded: improved by looking in the directory where cray-pmi ought to be
Followup to https://github.com/chapel-lang/chapel/pull/26921

Further improve OFI_OOB=pmi2 detection

---

util/cron/common-arkouda.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.colo.bash
util/cron/test-perf.hpe-apollo-hdr.arkouda.release.colo.bash

Normally, we pass `-sync-dir-suffix` to `nightly` to sync a perf test's result into a subdirectory on dreamhost. However, Arkouda syncs its own graphs, where that variable is ineffective. This PR wires in that value through an environment variables to make sure that colocale performance plots go to the right location.

Adjust Arkouda colocale performance testing to sync to the correct dir

---

util/cron/common-arkouda.bash

This PR updates Arkouda testing to use Chapel 2.4 release.

Bump Arkouda's release testing to version 2.4

---

.github/workflows/email.yml

This limits the github workflow `email` to only run on the `chapel-lang/chapel` repo. 
Currently if you merge a commit to the main branch of a fork the `email` workflow will fire and error out. This prevents it from running on forks. 
[reviewed by @arifthpe - thanks!]

limit email workflow to chapel-lang/chapel repo

---

Makefile.devel
doc/Makefile

With the 'versionButton.php' reorganization that took place in PR care with the versionButton.php file.  This PR adds a new target to the developer and doc/ Makefile called 'docs-release' that sets the versionButton.php file up to be the symbolic link we need it to be in the release (which differs from the one we need it to be when we're pushing the 'main' version of the docs to 'docs/main' on the live website).

Add a new docs-release Makefile target

---

frontend/include/chpl/types/BoolType.h
modules/standard/Types.chpl
test/types/bool/bradc/numBitsBytesDefault.good

Adjusts the error message for calling `numBits` on a boolean to reflect the current state of the language, sionce there is no special "default width" bool type.
While there, I also updated some out of date dyno docs on this topic. And while updating these docs, I realized that Dyno defined the `defaultBitwidth` for a bool to be 0, while it defined the bitwidth for any given type to be `8`. I didn't really want to mess with changing that, but it was weird enough that I am noting it here.

Adjust numBits(bool) error message

---

.github/workflows/CI.yml

These take a while, and we don't want them on the slow path.

Dyno/CI: Split linters into a separate job

---

test/chplenv/chplconfig/correctness/chplconfig
test/chplenv/chplconfig/unset_overrides.sh

Fixes a failing test (`test/chplenv/chplconfig/warnings/warnings.chpl`) resulting from https://github.com/chapel-lang/chapel/pull/26501.
This issue occurs in a very strange way.
1. The test system always explicitly sets `CHPL_GASNET_SEGMENT`, in the default shared mem config this will always be `none`
`os.environ["CHPL_GASNET_SEGMENT"] = chpl_comm_segment.get()`
2. This test uses a value of `CHPL_COMM=gasnet` when testing for multiple values of `CHPL_COMM` in a chplconfig file.
3. This test uses a custom script to ensure a clean environment when diff-ing the test output, `test/chplenv/chplconfig/unset_overrides.sh`.
- This script uses the `--overrides` flag of `printchplenv` to determine what variables to unset.
4. By default, `--tidy` is thrown by `printchplenv` to restrict the chplenv …

Fix chplconfig test after improved chplenv error checking

---

frontend/test/CMakeLists.txt
frontend/test/ErrorGuard.cpp
frontend/test/ErrorGuard.h

This is a developer-oriented PR implementing an item that has long since been on my wishlist. It adds a new environment variable, `CHPL_DEBUG_DYNO_DUMP_SYMLINK`, which is intended to point at a destination directory.
The flag affects the Dyno test system by adjusting the `ErrorGuard` behavior in the following way. Whenever it's set, and whenever a dyno tests throws a segmentation fault or hits an assertion, a custom signal handler is invoked. This handler introspects the current error guard's context object for user-defined Chapel files. It then saves the files into a temorary directory, and creates a symbolic link to the path in `CHPL_DEBUG_DYNO_DUMP_SYMLINK`.
This is convenient because it allows developers to quickly inspect the code that was last used when an assertion is encountered. …

Dyno: add environment flag to save currently loaded files into a temporary directory

---

test/ANNOTATIONS.yaml
util/test/check_annotations.py

- Between 3/6/25 and 3/12/25 we see plained perf changes in Stream Performance , Scan Performance, Reduce Performance, Array Creation Performance, DataFrame Display Performance. We've investigated this and haven't found a root cause. We're going to annotate that we suspect these impacts are due to systems changes.
- Temp directory change impacting Arkouda IO tests on hpe-apollo-hdr config (#26949).

Add arkouda perf triage annotations (3/27/25) 

---

.github/workflows/CI.yml

This brings the github action to publish the module docs during the CI workflow live by removing the `dry-run` flag from the `rsync` command. 
CI change only - not reviewed

activate module docs published from ghci

---

compiler/resolution/initializerResolution.cpp
test/classes/initializers/errors/errHandling/deinitFields-arraytype.chpl
test/classes/initializers/errors/errHandling/deinitFields-arraytype.good

This resolves a bug introduced in yesterday's #26690 fix to call deinit() on fields when init/postinit throws.  Specifically, the net I cast was a bit too wide, and we were trying to call deinit() on 'type' fields that are arrays because they look like record fields (yet don't support a 'deinit()' call because we don't suppot 'deinit()' on types).
The fix here is simple, which is to just look for the presence of the "type variable" flag on the symbol and to skip over such cases when we're inserting the deinits.
This showed up in a pair of Python tests:
* test/library/packages/Python/correctness/arrays/nestedArrays.chpl
* test/library/packages/Python/correctness/arrays/numpyInterop.chpl
though they didn't get reported in nightly testing due to a pip unavailability / suppressif issue. …

Fix a bug in handling of array 'type' fields from #26690

---

frontend/include/chpl/resolution/resolution-types.h
frontend/lib/resolution/BranchSensitiveVisitor.h
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/VarScopeVisitor.cpp
frontend/lib/resolution/return-type-inference.cpp
frontend/test/resolution/testCompilerError.cpp

Resolves https://github.com/Cray/chapel-private/issues/7229.
Depends on https://github.com/chapel-lang/chapel/pull/26999.
Quoting from that issue: a lot of Chapel production code (including in library modules) looks like this:
```Chapel
proc foo(param cond) {
if cond then compilerError("This condition should not be met");
codeThatOnlyCompilesIfCondIsFalse();
}
```
These rely on the fact that `codeThatOnlyCompilesIfCondIsFalse()` will not be resolved if an error is already emitted. This means terminating resolution of `foo()`, much like we do with `return` in https://github.com/chapel-lang/chapel/pull/26955.
This PR implements that.
One conceptual curiosity is that this conflicts with Dyno's existing approach of attempting to continue resolving programs to get partial information. …

Dyno: adjust `compilerError` to interrupt resolution of functions

---

test/library/packages/Python/correctness/arrays/PRETEST

Turn logging on for a PRETEST that installs python dependencies, this makes it easier to debug errors

Turn logging on for a PRETEST that installs python dependencies

---

modules/layouts/LayoutCS.chpl
modules/packages/Search.chpl
modules/packages/SortedMap.chpl
modules/packages/SortedSet.chpl
modules/standard/Heap.chpl
modules/standard/List.chpl
modules/standard/Sort.chpl
test/compflags/ferguson/print-module-resolution.good
test/deprecated/Heap/depComparatorNames.chpl
test/deprecated/Heap/depComparatorNames.good
test/deprecated/Search/depComparatorNames.chpl
test/deprecated/Search/depComparatorNames.good
test/deprecated/Sort/comparatorArgs.chpl
test/deprecated/Sort/comparatorArgs.good
test/deprecated/Sort/depComparatorNames.chpl
test/deprecated/Sort/depComparatorNames.good
test/deprecated/Sort/listSort.chpl
test/deprecated/Sort/listSort.good
test/deprecated/SortedMap/depComparatorNames.chpl
test/deprecated/SortedMap/depComparatorNames.good
test/deprecated/SortedSet/depComparatorNames.chpl
test/deprecated/SortedSet/depComparatorNames.good
test/modules/sungeun/init/printModuleInitOrder.good
test/optimizations/deadCodeElimination/elliot/countDeadModules.good

[reviewed by @jabraham17]
This cleans up some deprecations that have been present since at least 2.3, including:
- defaultComparator.compare with `a` and `b` arguments
- reverseComparator.compare with `a` and `b` arguments
- DefaultComparator
- ReverseCompartor
- list.sort
Removes the old deprecation tests, and updates a few tests that respond when modules are removed (since there were some helper modules we used to make nicer deprecation messages for accessing DefaultComparator and ReverseComparator from Search, SortedSet, Heap, and SortedMap)

Remove old sort-related deprecations

---

util/test/chpl_launchcmd.py

This PR adjusts `chpl_launchcmd`, such that it allocates correct number of nodes when `CHPL_RT_LOCALES_PER_NODE` is used. Previously, it just allocated `nl` nodes, which is not the right thing to do with colocales.
This currently only fixes PBS side of the script. I'll try to fix the slurm side in this PR before merging it. Right now, I am planning this for post-release.

Adjust chpl_launchcmd to be able to handle colocales with PBS

---

util/packaging/homebrew/chapel-main.rb

This just pins main's test formula to LLVM 19 now that LLVM 20 is the canonical version in Homebrew. 
Related update to release formula: https://github.com/chapel-lang/chapel/pull/27017/

homebrew testing update to pin llvm 19

---

modules/standard/GPU.chpl
runtime/include/gpu/chpl-gpu-gen-common.h
test/gpu/native/basics/gpuClockOnHost.chpl
test/gpu/native/basics/gpuClockOnHost.good

Inspired by [this discourse topic](https://chapel.discourse.group/t/gpuclock-only-returns-0/41925/1).
This PR adds a warning when `gpuClock` is called from the host. When that happens we always return 0 silently. Understandably, that can be confusing.
There's a question of whether that warning should be suppressable when the same loop is executed both on the CPU and the GPU, for example. However, I see `gpuClock` as an advanced feature that should not be widely used. So, this PR doesn't go that far.
Test:

Add a warning when `gpuClock` is called from the host

---

util/devel/updateGITLOG

One of Arkouda's merge messages introduced some sort of binary character that makes `dos2unix` choke.  This adds a `-f` flag to force our way past it.

Fix updateGITLOG for Arkouda

---

compiler/main/checks.cpp

PR #26990 added record deinit() calls as part of its work to deinitialize classes in the event of throwing initializers / 'new' calls.  This caused all such tests to fail when compiling with --verify, as we have had a pre-existing check for some time to ensure that the compiler-generated code does not delete/destroy/deinit records.
In this PR, I'm removing the check to permit these calls to go through, since the point of 'deinit()' is to support the compiler's ability to call it, like the calls inserted in #26990.
Clearly, the compiler is calling deinit already when destroying things in other code paths, but DavidL and I postulated that it's only doing it through chpl__autoDestroy().  If correct, that suggests my PR could've called chpl__autoDestroy() instead, but I view that call as an …

Remove the check that the compiler doesn't insert deinit's of records

---

test/release/examples/primers/timers.chpl

This fixes two things:
1. The comment said `false` instead of `true`
2. The comment was a little jarring when reading the primer from the docs, I reworded the sentence to better explain what's going on

Fix comment in stopwatch primer.

---

frontend/include/chpl/parsing/parsing-queries.h
frontend/include/chpl/resolution/resolution-types.h
frontend/lib/framework/Context.cpp
frontend/lib/parsing/parsing-queries.cpp
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/resolution-types.cpp
frontend/lib/resolution/scope-queries.cpp
frontend/test/framework/testErrorTracking.cpp
frontend/test/resolution/testDomainsRectangular.cpp
frontend/test/resolution/testInitSemantics.cpp

Fixes all the issues in the way of https://github.com/Cray/chapel-private/issues/7139 except https://github.com/Cray/chapel-private/issues/7264.
This includes:
* Tracking down a query error message issuing bug, in which you could get Dyno to issue a hidden error message
* Disabling implicit receivers for field initializers (how can you compute the field type, which has to happen prior to initializing an object, using a `this` of that same object?).
* Enabling tuple expansion in domain expressions (`{(...ranges)}`, and skipping resolving the builder for unknown types
* Improve the skipping of generic formals in partial instantiation cases by checking not just if a substitution map is present, but if it also contains an ID
* Enable forwarding fields to be treated like real fields (referred …

Dyno: fix bugs in the way of resolving `blockDist`

---

tools/chpl-language-server/src/chpl-language-server.py
tools/chpl-language-server/test/call_inlays.py

The resolver is not finished, but the error messages are becoming more and more reasonable. I think, given that --resolver is experimental, it's safe to enable the errors now.

Enable dyno-driven error messages in LSP

---

frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/prims.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/resolution-types.cpp
frontend/test/resolution/testInterfaces.cpp
frontend/test/resolution/testResolve.cpp
frontend/test/resolution/testTypeQueries.cpp

Ben's comment on the resolver meta issue (https://github.com/Cray/chapel-private/issues/5108#issuecomment-2730119210) indicates that `promotes-default` is a spec test failing for an unknown reason. I took a look; the test was failing due to numerous minor bugs, trigger, in no small part, because it exercises `sort` and the `Sort` module. The bugs were as follows:
1. The `docs only` pragma was ignored when checking interface constraints, causing errors
2. I didn't realize that `static field type`, unlike the other reflection primitives, looks for parent fields as well
3. The parser doesn't always consistently represent type queries, and the array type query instruction only supported some of the cases.
4. for unknown `x`, the resolver could attempt to resolve `x.foo(bar)` as `foo(bar)`. …

Dyno: numerous minor fixes for "promotes default" test

---

frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/call-init-deinit.cpp
frontend/test/resolution/testDomainsSparse.cpp
frontend/test/resolution/testScopeResolve.cpp
frontend/test/resolution/testTaskIntents.cpp
frontend/test/test-resolution.cpp
frontend/test/test-resolution.h

Closes https://github.com/Cray/chapel-private/issues/7139 (resolving `blockDist`)
Closes https://github.com/Cray/chapel-private/issues/7264 (resolving task variables)
This PR implements task variables. I previously identified them as the last component to resolving `blockDist`. However, I was wrong; as a consequence, I rolled in a related fix that does take care of all the issues in `blockDist`.
For task variables, things are very simple. We already have code for handling variable declarations, and we already have code detecting a task variable (as opposed to a task intent). However, one was not using the other. I simply added a call to the "regular" handing of named declarations for task variables, and things "just worked".
The related bug was due to `call-init-deinit` attempting to …

Dyno: resolve task vars and fix errors in `in` task intents

---

runtime/include/gpu/cpu/chpl-gpu-gen-includes.h
test/gpu/native/basics/gpuClockOnHost.skipif

This is to address the fallout from https://github.com/chapel-lang/chapel/pull/27022.
- cpu-as-device implementation of `chpl_gpu_clock` needed line and file number formals
- the new test needs to be skipped with cpu-as-device as the warning we are testing is specific to having actual GPUs
Test:

Fix the cpu-as-device implementation of `chpl_gpu_clock`, skipif a new test

---

make/Makefile.base
util/chplenv/chplenv_verify.py
util/chplenv/printchplenv.py
util/chplenv/utils.py

This PR adds a prototypical new flag to `printchplenv`, `--verify`. This will run verification passes on the current Chapel configuration.
This PR implements a few of these verification checks, the primary ones being checking that the host and target compilers work properly. This can help users diagnose issues with their toolchain, like https://github.com/chapel-lang/chapel/issues/24819
This PR also turns the verification on by default when `printchplenv` is invoked from `make`, but does not abort the build.

Add a verification check to `printchplenv` to catch build system misconfigurations

---

frontend/lib/resolution/Resolver.cpp
frontend/test/resolution/testCompilerError.cpp
test/compflags/stopEarly/dyno-resolve-only.good

It looks like none of our tests need the workaround anymore, and it costs a lot in terms of performance.

Dyno: Roll back silencing errors when resolving transitive functions

---

modules/packages/Python.chpl

Simplifies the logic for entry/exit to Python code from Chapel, by condensing it in a single place.

Simplify Python entry/exit code for handling the GIL

---

modules/packages/Python.chpl
test/library/packages/Python/correctness/iterObject.chpl
test/library/packages/Python/correctness/iterObject.good
test/library/packages/Python/correctness/iterObject.py
test/library/packages/Python/correctness/iterObject.skipif

This PR adds support for iterating over iterable Python objects using native Chapel iteration.

Add support for native Chapel iteration on Python objects

---

modules/packages/Python.chpl

Free the memory allocated for the buffer when we're done with it.  I could have sworn I ran that test with `-memleaks` as well, but maybe I did it with an earlier version of the change or something.  In any case, this thankfully doesn't break the fix.
Passed a full standard paratest, test/library/packages/Python with gasnet, and the test itself with `-memleaks`

Fix the memleaks failure with my new test

---

util/buildRelease/gen_release

This fixes an issue where executable files are no longer executable after being copied, because `copyfile` does not preserve file metadata/mode bits. The fix is to use `copy2`, which does `copyfile` and then also copies the metadata/mode bits
Followup to https://github.com/chapel-lang/chapel/pull/26913

Use copy2 instead of copy to copy files in gen_release

---

util/buildRelease/gen_release

Fixes a portabikity issue with `gen_release`. Switches a call in `gen_release` to use `getpass.getuser` instead of `os.getlogin`. This is whats recommend by [the Python docs](https://docs.python.org/3/library/os.html#os.getlogin)

Use getpass.getuser instead of os.getlogin

---

test/library/packages/Python/correctness/torch/SKIPIF
test/library/packages/Python/examples/numba/apply.skipif
test/library/packages/Python/examples/scipy/checkScipyLinAlg.skipif

Skips a few Python module tests on linux32, as they depend on third party libraries that do not support linux32 well

Skip some python tests on linux32

---

frontend/include/chpl/framework/Context-detail.h
frontend/include/chpl/framework/Context.h
frontend/lib/framework/Context.cpp
frontend/lib/parsing/parsing-queries.cpp
frontend/lib/resolution/InitResolver.cpp
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/prims.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/test/framework/testErrorTracking.cpp
frontend/test/resolution/testCompilerError.cpp

This PR addresses an issue I observed while working on https://github.com/chapel-lang/chapel/pull/27031, namely that resolving `blockDist` was _slow_. After doing some profiling, I observed that a big chunk of time is spent in `storeErrorsFor`, which is a function invoked for `runAndTrackErrors`. My first course of actions was to disable unnecessary calls to `runAndTrackErrors`, which occurred in https://github.com/chapel-lang/chapel/pull/27041. This helped (see below table), but I still observed calls to `storeErrors` when profiling.
This call is unfortunately necessary for correctness: collecting errors needs to work in the presence of query caching, which means that we need to be able to capture errors even if we aren't actually re-running a computation. This is done by traversing the …

Dyno: improve performance when resolving

---

modules/packages/Python.chpl
test/library/packages/Python/correctness/iterObject.suppressif
test/library/packages/Python/memleaks/iterate.chpl
test/library/packages/Python/memleaks/iterate.good

Suppresses a leak in a new test that is caused by a bug in iterator handling: https://github.com/chapel-lang/chapel/issues/27062
While investigating this, I also realized that we were missing a Py_DECREF in `iter these`, so this PR rectifies that (and adds a test to lock it in).

Suppress memory leak testing on Python iteration tests

---

util/test/sub_test.py

Moves calls to `compileline` into where they are actually needed, which is only a small subset of tests. 
Before this PR `start_test examples/hello.chpl` took 22 seconds on my Mac. Now it takes 15 seconds.

Improve performance of `start_test` by reducing what gets computed

---

util/chplenv/chplenv_verify.py

Fixes `printchplenv --verify` when using a bundled LLVM

Fix `--verify` with a bundled LLVM

---

modules/packages/Image.chpl
test/library/packages/Image/readWrongFormat.chpl
test/library/packages/Image/readWrongFormat.cleanfiles
test/library/packages/Image/readWrongFormat.good
test/library/packages/Image/smallMovie.prediff

Improve the errors generated by the Image module when reading an incorrect/invalid file.
This PR also adjusts a few halts in throwing functions to throw catchable errors, rather halting.

Improve errors for invalid files in Image module

---

util/cron/test-hpe-apollo-hdr.arkouda.bash
util/cron/test-hpe-apollo-hdr.arkouda.release.bash

Adjust the instantiation limit to 1024 to resolve compilation issues when testing Arkouda with multiple dimensions, as described in issue https://github.com/Bears-R-Us/arkouda/issues/4227

Increase instantiation limit for Arkouda testing

---

third-party/qthread/README
third-party/qthread/qthread-src/src/CMakeLists.txt

The fast context swap is broken on little-endian ppc. This switches to using the fallback implementation from the system in that case.

Backport Qthreads Fix For ppc64le

---

compiler/main/driver.cpp
doc/rst/tools/chpl-language-server/chpl-language-server.rst
doc/rst/tools/chplcheck/chplcheck.rst
frontend/include/chpl/parsing/parsing-queries.h
frontend/lib/parsing/parsing-queries.cpp
test/chplcheck/configfile-toml.chpl
test/chplcheck/configfile-toml.chplcheckopts
test/chplcheck/configfile.chpl
test/chplcheck/configfile.chplcheckopts
test/chplcheck/configfile.toml
test/chplcheck/configfile.yaml
third-party/chpl-venv/chapel-py-requirements.txt
tools/chapel-py/src/chapel/__init__.py
tools/chapel-py/src/method-tables/core-methods.h
tools/chpl-language-server/src/chpl-language-server.py
tools/chpl-language-server/src/chpl-shim.py
tools/chplcheck/src/chplcheck.py
tools/chplcheck/src/lsp.py
tools/chpldoc/chpldoc.cpp

This PR expands the existing support for using ConfigArgParse to allow for editor-agnostic configuration files. This allows users to specify options for their project in an editor-agnostic way, and then allow CLS/chplcheck to auto-pick them up.
This also integrates nicely with Mason, allowing users to specify CLS/chplcheck options in a Mason.toml file. For example
```toml
[brick]
...
[tool.chplcheck]
disable-rule = ["UnusedLoopIndex"]
```
This PR also expands the options for chplcheck, allowing the following
```toml
...
[tool.chplcheck]
file = ["src/*.chpl"]
add-rules = ["lint/rules.py"]
disable-rule = ["IncorrectIndentation"]
```
This lets users specify all the options needed in 1 file, and then from the project root running just `chplcheck` does the right thing
This PR also adds the …

CLS/chplcheck: Support editor agnostic configuration files

---

util/cron/test-gasnet.darwin.bash
util/cron/test-gasnet.fast.darwin.bash

Fixes two nightly configs that have the incorrect launcher after https://github.com/chapel-lang/chapel/pull/26236. These configs should default to using the GASNet launcher, not a slurm one

Use correct launcher with gasnet nightly tests

---

test/library/packages/Python/memleaks/iterate.skipif

Adds a skipif for a test that only works when iterator inlining is used, meaning `--baseline` testing cannot be run

Add a skipif for a test that requires iterator inlining

---

test/library/packages/Python/correctness/arrays/arrayTypes.skipif
test/library/packages/Python/correctness/arrays/memoryView.skipif

Skips baseline testing for a few tests that exercise throwing iterators, which is not supported by `--baseline`.

Add skipifs for baseline testing for tests with throwing iterators

---

modules/packages/Python.chpl
test/library/packages/Python/correctness/arrays/memoryView.chpl
test/library/packages/Python/correctness/arrays/ndArrayMemoryView.chpl
test/library/packages/Python/correctness/arrays/ndArrayMemoryView.good
test/library/packages/Python/correctness/arrays/usePythonArray.chpl
test/library/packages/Python/correctness/arrays/usePythonArray.execopts
test/library/packages/Python/correctness/arrays/usePythonArray.linux32.good
util/config/embed-python.sh

Fixes a number of portability issues nightly testing revealed, especially on linux 32. However, some issues are also caused by different versions of Python.

Fix Python module portability issues, especially on linux 32

---

test/library/packages/Python/correctness/arrays/arrayTypes.chpl
test/library/packages/Python/correctness/arrays/arrayTypes.good

Removes one test case for the Python module, because its not portable and not that useful to test.
Since the sign of `char` is implementation defined, comparing it against a signed byte may not work on some platforms

Remove non-portable test for Python module

---

test/library/packages/Python/correctness/arrays/ndArray.skipif

Adds a missing skipif for test that requires iterator inlining

Add a missing skipif for test that requires iterator inlining

---

test/library/packages/Python/correctness/exceptionsFromInit.prediff

Adds a prediff for a Python module test whose output can change based on the Python version used.

Add prediff for Python module test with version sensitive output

---

runtime/src/launch/slurm-gasnetrun_common/slurm-gasnetrun_common.h

The code here is longstanding, but has recently started getting tested in GASNet's test configurations as a result of #26236, which makes greater use of slurm by default.  They compile in developer mode to get maximal errors and warnings, and that tripped a warning for some `char* ... = "literal";` declarations that should've been `const char*`.
This suggests that we should potentially be dialing up warnings in our own nightly testing, which is somewhat thematically related to https://github.com/Cray/chapel-private/issues/3138

Add missing `const` qualifiers from `char*` declarations

---

frontend/include/chpl/resolution/resolution-queries.h
frontend/include/chpl/resolution/resolution-types.h
frontend/include/chpl/util/assertions.h
frontend/lib/framework/Context.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/return-type-inference.cpp
frontend/lib/resolution/scope-queries.cpp
frontend/lib/types/Param.cpp

This PR aims to further improve Dyno's resolution performance.
I started by looking at the number of queries we call, in hopes that we can reduce the number of invocations to them. In the past, `idToAst` has been one of Dyno's hottest queries, and this remains to be the case. However, unlike previous times, I found no opportunities to elide calls to this function. Instead, I took the following steps to reduce the amount of work done by Dyno:
* I determined that `scopeForId` and its recursive self-invocations make up the bulk of calls to `idToAst`. I found no ways to reduce uses of `idToAst` in `scopeForId`, but I did find a way to reduce the number of `scopeForId` invocations. It turns out that code `GatherMentionedModules` runs `scopeForId` for every identifier, which invokes …

Dyno: cache function signature instantiations, reduce cache impact of some queries

---

compiler/passes/convert-uast.cpp
modules/internal/ChapelRemoteVars.chpl
test/variables/remote/noinit-vars.chpl
test/variables/remote/noinit-vars.good

Closes https://github.com/chapel-lang/chapel/issues/27068.
This PR adds support for `noinit` remote variables. There was previously no support for them, though I hadn't considered that case and as a consequence hadn't documented them. To support them, a degree of special-casing is required (an `x = noinit` expression is specially treated, and we rewrite initialization expressions for remote variables).
On the technical side, this PR adds a new overload to the remote variable builder. This overload is distinguished from others by a dummy `type` formal which is expected always to be `void` (inspired by the type of the `noinit` global variable). This overload simply constructs a remote variable wrapper with a `noinit`'ed temporary.
While there, I noticed that an assertion was incorrectly …

Add support for `noinit` remote variables.

---

modules/packages/Python.chpl
test/library/packages/Python/correctness/pythonOps.chpl
test/library/packages/Python/correctness/pythonOps.good
test/library/packages/Python/correctness/pythonOps.prediff

Adds native support for calling operator methods on Python objects via Chapel operators.
This allows users to natively write `myPyObj + myOtherPyObj`, rather than `myPyObj.call('__add__', myOtherPyObj)`.
This PR also adds the `pyType` method to get the type of a Python object, essentially `type(obj)` in Python
Resolves https://github.com/chapel-lang/chapel/issues/26911

Add native support for Python operators via Chapel operator overload 

---

doc/rst/usingchapel/compiling.rst
test/cmake/linkWithC/CMakeLists.txt
test/cmake/linkWithC/include/adder.h
test/cmake/linkWithC/main.chpl
test/cmake/linkWithC/src/adder.c
test/cmake/sharedLib/CMakeLists.txt
test/cmake/sharedLib/include/adder.h
test/cmake/sharedLib/main.c
test/cmake/sharedLib/main.chpl
test/cmake/sharedLib/src/adder.c
test/cmake/staticLib/CMakeLists.txt
test/cmake/staticLib/include/adder.h
test/cmake/staticLib/main.c
test/cmake/staticLib/main.chpl
test/cmake/staticLib/src/adder.c
test/cmake/sub_test
util/cmake/CMakeCHPLInformation.cmake

Add the ability to link against external libraries when building Chapel projects with CMake.
Also updated and expanded the docs on using CMake with Chapel

Support linking against external libraries with Chapel's CMake support

---

Makefile
compiler/Makefile
util/buildRelease/install.sh
util/chplenv/chpl_home_utils.py
util/packaging/apt/common/copy_files.py
util/packaging/homebrew/chapel-main.rb
util/packaging/rpm/amzn2023-gasnet-udp/spec.template
util/packaging/rpm/amzn2023-ofi-slurm/spec.template
util/packaging/rpm/amzn2023/spec.template
util/packaging/rpm/el9-gasnet-udp/spec.template
util/packaging/rpm/el9-ofi-slurm/spec.template
util/packaging/rpm/el9/spec.template
util/packaging/rpm/fc40-gasnet-udp/spec.template
util/packaging/rpm/fc40/spec.template
util/packaging/rpm/fc41-gasnet-udp/spec.template
util/packaging/rpm/fc41/spec.template

Adds an install step to move the CMake module files in `util/cmake` to `CHPL_HOME/lib`/`INSTALL_PREFIX/lib/cmake/chpl`
This makes these files readily available to users without needing to copy the files into their project
testing
- tested fedora 41
- tested ubuntu 24

Install CMake files for Chapel projects

---

frontend/include/chpl/framework/Context-detail.h
frontend/include/chpl/framework/Context.h
frontend/include/chpl/framework/all-global-strings.h
frontend/include/chpl/framework/query-impl.h
frontend/include/chpl/resolution/ResolutionContext.h
frontend/lib/framework/Context.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/resolution-types.cpp

Depends on https://github.com/chapel-lang/chapel/pull/27082.
This PR is another in a series of efforts to improve Dyno's performance. It has some minor changes, as well as a major one: enabling a rudimentary caching of function instantiations. Specifically, this PR enables caching and re-use of functions that did not use PoI (most of them, it turns out!). This had a huge impact on resolution performance: in my benchmarks, `chpl --dyno-resolve-only` is now __15-22% faster than production__ with `--stop-after-pass=resolve`.
In this PR, I spent a considerable amount of time looking at the memory allocations in Dyno, motivated by the fact that, when comparing performance, Dyno spent significantly more time in the "system", but a comparable amount of time in "user" execution. I assumed that …

Dyno: enable PoI instantiation cache and make other perf. optimizations

---

test/statements/conditionals/integralReturnTypesInConditional.bad
test/statements/conditionals/integralReturnTypesInConditional.chpl
test/statements/conditionals/integralReturnTypesInConditional.good

This fixes a future that had the same .good/.bad and so always showed as passing.
[test change only, not reviewed]

fix a passing future by adjusting test output

---

doc/rst/platforms/cray.rst
doc/rst/usingchapel/multilocale.rst
modules/packages/MPI.chpl
util/chplenv/chpl_comm.py
util/chplenv/chpl_comm_segment.py
util/chplenv/chpl_comm_substrate.py
util/chplenv/chpl_llvm.py

Removes support for CHPL_COMM_SUBSTRATE=aries, which GASNet no longer supporta.
The [latest update to Chapel's bundled GASNet](https://github.com/chapel-lang/chapel/pull/26830) removed support for CHPL_COMM_SUBSTRATE=aries. While this is not Chapel's preferred setting on aries (preferred is CHPL_COMM=ugni), users trying to use CHPL_COMM=gasnet and CHPL_COMM_SUBSTRATE=aries prior to this PR would get a build time error. This PR makes this a nicer error.
While there, this PR also adds 'ucx' to the list of allowed CHPL_COMM_SUBSTRATE, as it was missing. This support was always there but [previous work](https://github.com/chapel-lang/chapel/pull/26501) had mistakenly broken it
[Reviewed by @arifthpe, @jhh67, and @bonachea]

Remove CHPL_COMM_SUBSTRATE=aries and fix broken CHPL_COMM_SUBSTRATE=ucx

---

frontend/include/chpl/resolution/resolution-types.h
frontend/lib/resolution/InitResolver.cpp
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/call-init-deinit.cpp
frontend/lib/resolution/copy-elision.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/resolution-types.cpp

Co-authored with @arifthpe.
It seems like most of the resolution machinery is using `calledType` only to handle type constructor cases. However, `calledType` is inconsistently set across Dyno: sometimes it's present, sometimes it's not. This PR ensures all uses of `calledType` are for type constructors (this mostly boiled down to replacing `.calledType()` calls with equivalent `.methodReceiverType()` calls). After this, I adjusted all call info constructions to skip adding `calledType` unless they are a type constructor.

Dyno: only use calledType for type constructors

---

util/chplenv/chpl_jemalloc.py

Fixes an error message that printed the same variable name twice, rather than 2 different variable names

Fix printchplenv error message that printed incorrectly

---

test/library/packages/Python/correctness/paths/checkPaths.chpl

Fixes an issue where some methods of Python installation would break this test's output. The specific scenario occurs when a Python install does customization of where libraries are called, this is called "site customization".
A [recent homebrew PR](https://github.com/Homebrew/homebrew-core/pull/218757) changed how the `site-packages` directory was setup and seemed to cause some packages paths to be invisible to the `python3` executable, but not to our Python module. This is because our Python module explicitly looks for site specific customization, which it seems the homebrew install of python does not do by default. This change broke a few nightly test configs, bringing this to our attention.
This can be "resolved" by forciblly resolving the site customization in the specific test that …

Fix Python module paths test in environments with strange Python installs

---

frontend/include/chpl/types/CompositeType.h
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/types/CompositeType.cpp
frontend/lib/types/Type.cpp
frontend/test/resolution/testResolve.cpp

https://github.com/Cray/chapel-private/issues/7304
This is done by treating `sync` more like `range`. Specifically, we directly rewrite `sync` to `_syncvar`, like we rewrite `range` to `_range`. This is an improvement over `main` because on `main`, the rewriting only happens when a call is being handled. As a result, `sync` standalone -- which isn't a call -- isn't handled. Under the new regime, the rewrite happens earlier, enabling both the original support (`sync int` parses as `sync(int)` resolves to `_syncvar(int)`) and adding generic support (`sync` is an alias for `_syncvar`).

Dyno: enable generic `sync` types

---

test/gpu/native/environment/gasnet.chpl
test/gpu/native/environment/gasnet.compopts
test/gpu/native/environment/gasnet.prediff

Removes an old GPU+GASNet test. 
It that was meant to lock in that a user *could not* use GPUs+GASNet. It was then updated to lock in that a user *could* use GPUs+GASNet. But given the test doesn't actually run/do anything and we have full CHPL_COMM!= none testing on a few platforms (although not specifically GASNet), I am removing it.

Remove old GPU+GASNet test

---

test/runtime/ferguson/cache-remote-mock-tests/mock-ra-perf.skipif

https://github.com/chapel-lang/chapel/pull/27108 added a skipif, which was too naive and wasn't processing correctly. This PR uses a Python implementation for that purpose to properly check for an environment variable's value.
This time, I made sure that the `start_test -respect-skipifs` produces the correct output.

Fix the new skipif by using python and more checking

---

modules/internal/ChapelDynamicLoading.chpl

This PR fixes bugs that were breaking `chpl` builds on `linux32` with the `C` backend. It adjusts how the hashtable check `_isKeyZeroBits` is performed to avoid a cast to `int` in the case that the argument is a `c_ptr(void)`. This sidesteps a backend compiler error that is emitted when a 32-bit `void*` is cast to a `int64_t`.
I've also adjusted the hashtable's `_hash` wrapper to use the primitive `object2int` in order to avoid a cast causing a similar error. Future work could add this code to `CTypes.chpl` as the official `c_ptr`/`c_ptrConst` hash method.
These adjustments are to the custom hashtable implementation in the module `ChapelDynamicLoading`. They do not affect the public implementation in `ChapelHashtable`.
TESTING
Reviewed by @benharsh. Thanks much!

dlopen: Fix bugs breaking compilation on `linux32`

---

frontend/include/chpl/resolution/resolution-types.h
frontend/lib/resolution/default-functions.cpp
frontend/lib/resolution/default-functions.h
frontend/lib/resolution/resolution-types.cpp
frontend/lib/resolution/signature-checks.cpp
frontend/test/resolution/testOperatorOverloads.cpp

Closes https://github.com/Cray/chapel-private/issues/7263.
This PR generates various comparison operators as they are generated in production. Roughly, for `==`, the comparison is roughly as follows:
```Chapel
operator ==(lhs, rhs) {
if chpl_field_neq(lhs.field1, rhs.field1) then return false;
// ....
if chpl_field_neq(lhs.fieldN, rhs.fieldN) then return false;
return true;
}
```
For inequality, I generate:
```Chapel
operator !=(lhs, rhs) {
return chpl_field_neq(lhs.field1, rhs.field1) || /* ... */ || chpl_field_neq(lhs.fieldN, rhs.fieldN) || false;
}
```
For comparison, we actually do two order comparisons per field.
```Chapel
operator <=(lhs, rhs) {
if chpl_field_lt(lhs.field1, rhs.field1) then return true;
if chpl_field_lt(rhs.field1, lhs.field1) then return false;
// ....
return true; …
```

Dyno: generate `==`, `<`, `<=`, etc. by comparisons on fields

---

configure

Enforces that errors in `printchplenv` cause `./configure` to also result in an error.
This prevents an issue where `printchplenv` identifies a configure time error and makes no output, but accidentally overwrites the `chplconfig` file and allows builds to continue, just with the default config.
Thanks to @PHHargrove for helping identify and resolve this issue

Make a `printchplenv` error be a `./configure` error

---

modules/packages/Image.chpl

Fixes a bug where the Image module could silently fail to write an image out to a file. This was due to missing error checking logic for an external functions return code.

Fix Image module not checking return codes when writing images

---

modules/packages/ImageHelper/stb_image_helper.h

Adjusts the STB helper header to prefer using Chapel's allocation functions over the system default malloc/free.
This enables the allocations done by STB to be tracked by Chapels memory tracking system

Ensure that STB image library uses Chapel allocation functions

---

frontend/include/chpl/resolution/resolution-queries.h
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/default-functions.cpp
frontend/lib/resolution/prims.cpp
frontend/lib/resolution/resolution-types.cpp
frontend/lib/types/ArrayType.cpp
frontend/lib/types/DomainType.cpp

A few fixes to issues I noticed while going through the primers:
- allow non-sparse subdomain calls
- remove an inaccurate CHPL_UNIMPL warning
- allow assignment between extern types
- avoid an assertion failure when resolving runtime type of generic domain
Testing:

Minor dyno fixes

---

test/dynamic-loading/LoadForeignLibrary.skipif
test/functions/fcf/pointers/Motivators.skipif
test/memory/shannon/printFinalMemStat.prediff

This makes changes for three tests that are failing after https://github.com/chapel-lang/chapel/issues/27050.
1. `test/memory/shannon/printFinalMemStat.chpl` - adjusts the prediff to allow for a wider range of values in the output
2. `test/dynamic-loading/LoadForeignLibrary.chpl` - add a line to skip on darwin (essentially notests this, temporarily)
3. `test/functions/fcf/pointers/Motivators.chpl` - add a `.skipif` to (temporarily) not test on Linux with arm64 as the test currently fails there with a segfault
All the changes except 1. should be undone in the near future.
[reviewed by @dlongnecke-cray]

Adjust some tests to quiet failures 

---

compiler/AST/astutil.cpp
compiler/AST/baseAST.cpp
compiler/AST/symbol.cpp
compiler/AST/type.cpp
compiler/include/type.h
compiler/resolution/cleanups.cpp

This PR fixes nightly test failures when testing with `CHPL_SANITIZE=address` by implementing proper cleanup for `FunctionType*`.
It adjusts both `prune` and the cleanup that occurs after resolution for AST. It adds a proper `FunctionType::verify()` that checks to make sure no types in the function type are stale. It adds a proper destructor to `FunctionType*`. Since `FunctionType*` do not have a `gVec...`, this PR also makes sure to invoke the destructors.
TESTING
Reviewed by @benharsh. Thanks much!

Fix compiler memory leaks by making sure function types are cleaned

---

util/chplenv/chplenv_verify.py

Fixes an erroneous verification warning about missing jemalloc libraries by removing that argument from the link args. For the purposes of verification, its not needed.

Fix erroneous verification warning about not being able to use jemalloc

---

frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/can-pass.cpp
frontend/test/resolution/testLet.cpp

This PR fixes some ambiguity errors in `test/types/coerce/allNumericsBinary.chpl`. It does not, however, fix all resolution errors -- there are still some to do with the `array_get` primitive, and maybe more. I just thought smaller, incremental PRs would be easier to review, and might unblock other tests somehow.
The two main changes are:
* Don't consider variables as "unknown but eligible for `out` intent" in more cases. Today, we resolve calls with unknown formals sometimes, but only when the actual refers to an unknown-typed variable. We take this to potentially mean the the call computes the variable's type via the `out` intent. However, if the variable is part of a loop, or has a type expression, or is set to a value, the `out` intent shouldn't set its type: it's unknown for other …

Dyno: fix ambiguity errors

---

frontend/lib/resolution/prims.cpp
frontend/test/resolution/testResolve.cpp

On `main`, `array_get` only supports `c_ptr`. However, in production, any type with `pragma "data class"` or `pragma "c array"` can be used as an argument for the primitive. This PR adds:
* General handling for any record or class declared "data class". This handling matches production. Any type that has one of the two pragmas has its fields searched for an `eltType` field, and that field is used to compute result of indexing.
* Special handling for `_ddata`, which has the `"data class"` pragma but is specially handled in Dyno's type representation via the `HeapBufferType`, which mirrors `CPtrType`. The handling is nearly identical to `CPtrType`'s handling.

Dyno: implement `array_get` primitive for more types

---

frontend/lib/resolution/prims.cpp
frontend/test/resolution/testResolve.cpp

Curiously, there was a _very_ old issue with the list of primitives in `prims.cpp`: because a `break` was missing, a lot of the string primitives were marked as successfully handled, and returning a boolean. `ascii` was one of those primitives. This PR implements the primitive, and correctly marks the other string primitives unimplemented. This may lead to test failures that were masked, somehow, by the handling of string primitives as boolean-returning functions.

Dyno: Implement `ascii` primitive

---

util/test/paratest.chapcs

Prevents running `paratest.chapcs` or `paratest.chapdl` if the current Chapel environment is using a slurm based launcher.
Using a slurm launcher with these scripts will either result in very slow execution or a confusing error, so these PR heads that off by preventing that from occurring in the first place.
Note: this PR only adjusts `paratest.chapcs`, as `paratest.chapdl` calls `paratest.chapcs`

Prevent running `paratest.chapcs` or `paratest.chapdl` with a slurm launcher

---

frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testResolve.cpp

This PR, which depends on https://github.com/chapel-lang/chapel/pull/27150, fixes the remaining failures in `test/types/coerce/allNumericsBinary.chpl`. 
Specifically, the things that were failing were `.bytes()` on stings (which, consulting `convert-uast.cpp`, I learned is rewritten in production to `chpl_bytes`), and some weird errors about loop labels being incorrect. This, I:
* Observed that rewriting `.bytes()` to `.chpl_bytes()` matches pretty closely the rewriting of `atomic` to `chpl__atomicType`. I also noticed that `.domain` -> `._dom` rewriting is very similar, and not handled there.
* Consulted with @arifthpe to see if it was a bad idea (she didn't seem to think so) to move where `.domain` is handled, then moved `.domain` handling into a new `handleMethodCallSpecial` helper in …

Dyno: implement `.bytes()`, other fixes for `allNumericsBinary.chpl`

---

frontend/include/chpl/resolution/can-pass.h
frontend/include/chpl/resolution/resolution-types.h
frontend/include/chpl/types/TupleType.h
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/Resolver.h
frontend/lib/resolution/call-init-deinit.cpp
frontend/lib/resolution/can-pass.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/scope-types.cpp
frontend/lib/types/TupleType.cpp
frontend/test/resolution/testTuples.cpp
frontend/test/test-resolution.cpp
frontend/test/test-resolution.h

This PR adds support for ``_`` throwaway variables, de-tupled loop index variables e.g., ``for (i, _) in foo() do;``, and ``ref`` tuples.
This is an updated version of #25418 , and is almost entirely the work of @dlongnecke-cray.
Testing:

dyno: Add initial support for ``_`` and de-tupled loop index variables

---

tools/chapel-py/src/core-types.cpp
tools/chapel-py/src/core-types.h

This enables using `str(node)` to get a stringified representation of the AST node.

chapel-py: add dump and stringify capabilities to AstNode

---

frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testCast.cpp

Closes https://github.com/Cray/chapel-private/issues/7295.
This PR implements the compiler-generated `.borrow()` method on unmanaged and borrowed types. The reference production version here is here:
https://github.com/chapel-lang/chapel/blob/6e19ea5cd74fccb382216874412db4cfeae70949/compiler/resolution/functionResolution.cpp#L3315
While there, I noticed that some of the tests in `testCast` are commented out but should work. I re-enabled them.

Dyno: implement builtin borrow

---

frontend/lib/resolution/Resolver.cpp
frontend/test/resolution/testDomainsRectangular.cpp

Closes https://github.com/Cray/chapel-private/issues/7318.
Not much interesting here, just a standard rewrite of a builtin operator to a call to a standard function. A _tiny_ detail is that we swap the arguments of `dmapped` so that `D dmapped dist` becomes `chpl__distributed(dist, D, definedConst)`.
Upon consulting with `convert-uast.cpp`, which is the only place `chpl__distributed` is mentioned, I've determined that `definedConst` is always set to `true`, so this PR keeps that quirk.

Dyno: resolve `dmapped` expressions as calls to `chpl__distributed`

---

test/functions/fcf/pointers/Motivators.skipif

This PR edits the `Motivators.skipif` file with the goal of having this test skipif-ed in the linux/aarch64 testing configuration.
This skipif was introduced in #27138 as an interim solution to suppress a compiler crash in that configuration. It did not fire in that configuration because `CHPL_TARGET_ARCH` has the value `aarch64`, according to the test logs.

Motivators skipif adjustment

---

frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/resolution-types.cpp
frontend/test/resolution/testCast.cpp
frontend/test/resolution/testReductions.cpp

Closes https://github.com/Cray/chapel-private/issues/7320.
Clean diff: https://github.com/chapel-lang/chapel/pull/27155/files/b905dc708c3808fdac291dcf60618fb40c1a6438..9088afe8c45e74998c3c6102e9f8054203b90d16
The forms didn't work for two reasons:
1. Dyno's type-level tuple indexing didn't work. `myTupType(0)` produced a `_tuple(0)` rather than a type corresponding to `myTupType`'s first element. I fix this with changes to `CallInfo::create` and a minor adjustment to `resolution-queries.cpp`
2. Reductions didn't handle `zip` expressions. It turns out the logic for resolving `zip` was already pretty neat and self-contained, so this PR simply moved some calls and arguments around to thread through `zip` handling for reductions. While there, I enabled parallel reductions to resolve.
Also …

Dyno: fixes to enable resolving more reductions

---

doc/rst/language/spec/expressions.rst

[reviewed by @mppf]
Resolves #27165 
Damian noticed that we were accidentally using a `*` operator in an example involving exponentiation, when we should have been using `+`.  He also pointed out that the documentation mentioned a `pow` function but that he was having trouble finding it - I think this is because the `**` operator used to be a function named `pow` a long time ago and we must have missed updating this portion of the spec when it became the `**` operator.
Rectify both of those errors, and use a wordsmithing change he suggested in the previous paragraph.  I also validated that the two code snippets being compared did give the same result now for at least one set of `a, b, y` values.

Fix documentation issue with exponentiation in the spec, pointed out by Damian

---

util/test/paratest.client
util/test/paratest.server

Making this change in support of dyno testing, in the cases where we cannot yet type-convert but want to test for error messages.

Add '-comp-only' to paratest

---

util/cron/test-perf.gpu-ex-rocm.bash

Pins nightly perf testing for CHPL_GPU=amd to use rocm 6.20, since the default on the test system has changed and we do not yet support rocm 6.3.

Pin nightly CHPL_GPU=amd perf testing to use rocm 6.2.0

---

util/chplenv/chpl_launcher.py
util/chplenv/chpl_platform.py

Per the discussion on #27079, changes the default of CHPL_LAUNCHER to none when not on a known cluster and CHPL_COMM=none
Implements the results of https://github.com/chapel-lang/chapel/issues/27079#issuecomment-2807107888
Note: this PR refactors the logic for selecting the default to avoid duplicating logic for the default of `slurm-srun`.
[Reviewed by @arifthpe and @e-kayrakli]
Testing
- with slurm installed
- CHPL_COMM=none 
- `CHPL_COMM=ofi`
- `CHPL_COMM=gasnet CHPL_COMM_SUBSTRATE=ibv`
- without slurm installed
- CHPL_COMM=none 
- `CHPL_COMM=ofi`
- `CHPL_COMM=gasnet CHPL_COMM_SUBSTRATE=ibv`

Default to CHPL_LAUNCHER=none when not on a known cluster and CHPL_COMM=none

---

doc/rst/platforms/infiniband.rst
doc/rst/usingchapel/launcher.rst

Updates the documentation for CHPL_LAUNCHER to reflect what `chplenv` actually does.
The documentation as of this PR reflects the changes done as of https://github.com/chapel-lang/chapel/pull/27147

Update the docs on CHPL_LAUNCHER to reflect current state

---

compiler/AST/type.cpp
compiler/resolution/resolveFunction.cpp
test/arrays/ferguson/return-array-as-int.good
test/arrays/formals/promotedExprAsArrayActual.bad
test/arrays/marybeth/test_arrayops.good
test/arrays/promotion/promotedArgToArrayFormal.bad
test/arrays/shapes/tmacd-promotion.good
test/classes/casts/to-unmanaged-no-init.good
test/classes/errors/nilability-init-field-dflt/init-field-dflt-nonnil-borrowed-from-oknil-owned.good
test/classes/errors/nilability-init-field-dflt/init-field-dflt-nonnil-unmanaged-from-nonnil-owned.good
test/classes/errors/nilability-init-field-dflt/init-field-dflt-nonnil-unmanaged-from-oknil-owned.good
test/classes/errors/nilability-init-field-dflt/init-field-dflt-oknil-unmanaged-from-nonnil-owned.good
test/classes/errors/nilability-init-field-dflt/init-field-dflt-oknil-unmanaged-from-oknil-owned.good
test/classes/fields/default-expression-2.good
test/classes/nilability/bang-array.bad
test/expressions/bradc/reduceVsMathPrec2.bad
test/expressions/bradc/reduceVsMathPrec2.future
test/expressions/bradc/reduceVsMathPrec2.good
test/functions/iterators/errors/incorrectYieldTypes.good
test/functions/iterators/vass/forall-over-iteratorRecord-arg.good
test/functions/resolution/errors/printAdditionalErrors-1.all.good
test/functions/resolution/errors/printAdditionalErrors-1.dflt.good
test/functions/resolution/errors/printAdditionalErrors-1.pae.good
test/io/serializers/unstableWriting.good
test/library/packages/Crypto/utils/buffer2.good
test/library/standard/Reflection/canResolvePromoReturn.good
test/statements/split-init/splitInitIteratorExpressions.bad
test/users/thom/arrArgBlank-promote.good
test/users/thom/arrArgConst-promote.good
test/users/thom/arrArgRef-promote.good

The compiler messages now report the type of an iterable expression as `iterator yielding TYPE` or `promoted expression yielding TYPE`, with an appropriate TYPE. Previously it reported these types simply as `iterator`.
De-futurizes `test/expressions/bradc/reduceVsMathPrec2.chpl`
Changes the article to be used in one of the error messages before the type name from `a` to `an` in some common cases like "from an 'iterator'" or "from an 'owned'".

Iterator type string details

---

frontend/lib/resolution/prims.cpp
frontend/test/resolution/testDomainsSparse.cpp

Closes https://github.com/Cray/chapel-private/issues/7344.
In production, sparse subdomains' runtime type fields are not shared with their parent domain. In fact, there's only one field: `parentDom`. This PR adjusts Dyno's handling of runtime types to match that.

Dyno: match production's handling of sparse subdomains w.r.t RTT

---

frontend/lib/resolution/InitResolver.cpp

Closes https://github.com/Cray/chapel-private/issues/7334, which required resolving:
```Chapel
use ReplicatedDist;
var Space = {1..10};
const ReplicatedSpace = Space dmapped new replicatedDist();
var RA: [ReplicatedSpace] int;
```
To be merged after https://github.com/chapel-lang/chapel/pull/27171. Clean diff: https://github.com/chapel-lang/chapel/pull/27177/files/47946ac16e576a8d92863f8cffb4efebccb2ff96..132e5f2c0931cfbd96003239e9499ab435abbbd3
The `dom` and `eltType` fields are [required as part of the DSI](https://chapel-lang.org/docs/technotes/dsi.html#id11).
In practice, they are relied on in various method on the `_array` builtin record:
https://github.com/chapel-lang/chapel/blob/47946ac16e576a8d92863f8cffb4efebccb2ff96/modules/internal/ChapelArray.chpl#L832-L834 …

Dyno: simplify array type creation

---

compiler/resolution/implementForallIntents.cpp
modules/internal/ChapelReduce.chpl
test/parallel/forall/reduce-intents/ri-error-result-type.chpl
test/parallel/forall/reduce-intents/ri-error-result-type.good
test/reductions/reduceAtomics.bad
test/reductions/vass/illegal-elttype.good

Resolves #27060
The compiler now emits a user-friendly error message when the result of the reduction calculated using a reduce intent cannot be stored in the corresponding outer variable due to a type mismatch.
While there, add a clarification to an existing error message.

Reduce intent -- nice error message upon type error

---

util/chplenv/chpl_gpu.py

Improves the error message about supported ROCm versions to avoid ambiguity.
Before: `Chapel requires ROCm to be a version between 5.0 and 5.5 or between 6 and 6.3, detected version 6.3.0 on system.`
After: `Error: Chapel requires ROCm versions 5.0 to 5.4.x or 6.0 to 6.2.x, detected version 6.3.0 on system.`
Tested with various ROCm versions

Improve error messages when the ROCm version is unsupported

---

util/cron/test-perf.chapcs.playground.bash

Switch the single locale perf playground to test llvm 20
Only the single locale perf playground is switched, as LLVM 20 is not yet available on the multi-locale playground test system

Switch single locale perf playground to test llvm 20

---

test/interop/C/cmakelists/targetToLibToChpl/FooLibrary.notest

Do not test test/interop/C/cmakelists/targetToLibToChpl/FooLibrary.chpl because it fails for me in the standard configuration due to #27173
Not reviewed. This is a temporary measure to avoid the potential impact on nightly testing. To be reverted once this test passes again.

Add FooLibrary.notest

---

compiler/codegen/library.cpp

Switches the suffix for `--library --dynamic` to be `.dylib` on MacOS.

Use the correct library suffix for `--library --dynamic`

---

compiler/llvm/clangUtil.cpp

Adjusts a comment in the compiler about the usage of `-iquote`
This is cleanup from https://github.com/chapel-lang/chapel/pull/27173
[Not reviewed - trivial comment only change]

Adjust a compiler comment to be accurate with the code

---

Makefile
make/Makefile.base

Reduces the number of times `printchplenv --verify` runs. It was found to be significantly slowing down builds because it was being invoked too often (caused by reinvoking `make` many times).
It also adds a developer-only `CHPLENV_SKIP_VERIFY` environment variable to skip these checks all-together.

Reduce the number of times `--verify` runs

---

test/extern/passArrays/printArr.h

This will fix the regressions that #27182 introduced in tests of the C back-end.  Sorry for the noise—I fear it is still going to take me several years to remember that arrays are no longer passed by 'ref' by default...  :(

Update new test to take array as `const *`

---

.github/workflows/meetings.yml

Adds a github workflow to auto-create meeting topics for the public chapel meetings
Resolves https://github.com/chapel-lang/chapel/issues/27143
Tested in a private repo

Add a github workflow to auto-create meeting topics

---

test/library/packages/Python/correctness/arrays/iteration.skipif

Adds a skipif for a test which uses throwing iterators, which is not supported with `--baseline`

Add skipif for --baseline for throwing iterator test

---

modules/internal/ChapelDynamicLoading.chpl
test/dynamic-loading/LoadForeignLibrary.skipif

This PR fixes a silly bug that was breaking the `LoadForeignLibrary.chpl` test on `linux64`. It turns out that we were incorrectly using the `dlopen` handle for `Locales[0]` on any other locale. This PR makes sure to grab the handle for the currently executing locale out of the buffer stored on `Locales[0]`.
The reason this bug was not observed on OSX is because, at least on my machine, when a shared object is dynamically loaded, it appears to be seated in the same virtual address range regardless of the process. I observed the following debugging output on OSX:
```
path: './TestCLibraryToLoad.so'
system-pointers: 0x4604bd80 0x4604bd80 0x4604bd80 0x4604bd80
opened symbols:
```
This isn't a bug: each different locale's process loaded up `./TestCLibraryToLoad.so` at the same exact virtual …

dlopen: Fetch the 'dlopen' handle for the current locale before doing 'dlsym'

---

test/dynamic-loading/LoadForeignLibrary.skipif

Skip the `LoadForeignLibrary.chpl` test if we are running with the C backend. Function pointers aren't supported yet on the C backend. Trivial and not reviewed.

Skip a dynamic loading test if the C backend is being used

---

test/dynamic-loading/LoadForeignLibrary.skipif

In #27210 I skipped a test if `CHPL_LLVM=none`. The intention was to skip the test if the LLVM backend is not being used. Adjust the skipif to check `CHPL_TARGET_COMPILER!=llvm` instead since that is more accurate. Trivial and not reviewed.

Adjust .skipif to check CHPL_TARGET_COMPILER instead of CHPL_LLVM

---

compiler/AST/AggregateType.cpp
compiler/AST/baseAST.cpp
compiler/AST/foralls.cpp
compiler/codegen/cg-CForLoop.cpp
compiler/codegen/cg-expr.cpp
compiler/codegen/cg-symbol.cpp
compiler/codegen/cg-type.cpp
compiler/etc/gdb.commands
compiler/etc/lldb.commands
compiler/include/misc.h
compiler/llvm/llvmUtil.cpp
compiler/passes/convert-typed-uast.cpp
compiler/resolution/cullOverReferences.cpp
compiler/resolution/functionResolution.cpp
compiler/resolution/implementForallIntents.cpp
compiler/resolution/initializerResolution.cpp
compiler/resolution/interfaceResolution.cpp
compiler/resolution/lateConstCheck.cpp
compiler/resolution/lifetime.cpp
compiler/resolution/lowerForalls.cpp
compiler/resolution/lowerLoopContexts.cpp
compiler/resolution/nilChecking.cpp
compiler/resolution/preFold.cpp
compiler/resolution/resolveFunction.cpp
compiler/util/misc.cpp
doc/rst/developer/bestPractices/CompilerDebugging.rst
doc/rst/developer/bestPractices/CompilerIRTricks.rst
frontend/include/chpl/util/break.h
frontend/lib/framework/Context.cpp
frontend/lib/util/break.cpp

Renames `gdbShouldBreakHere` to `debuggerBreakHere` in the compiler. This is so we use a debugger agnostic term as the function can be used with other debuggers (e.g. lldb)

Rename gdbShouldBreakHere to debuggerBreakHere in the compiler

---

compiler/include/llvmUtil.h
compiler/llvm/llvmUtil.cpp

Adds helpers for debugging compiler generated debug information. 
This extends the printing logic for `llvm::Value`, `llvm::Module`, and `llvm::Type` to `llvm::Metadata`.

Add compiler debug printers for LLVM metadata

---

test/library/packages/Python/examples/parquet/readParquet.skipif

Adds a skipif for a few testing configuration where the Python parquet example fails

Add skipifs for new Python parquet example

---

util/cron/common-gpu-nvidia-hpe-cray-ex.bash
util/cron/test-gpu-ex-cuda-11.bash
util/cron/test-gpu-ex-cuda-12.bash
util/cron/test-gpu-ex-cuda-12.colocales.bash
util/cron/test-gpu-ex-cuda-12.interop.bash
util/cron/test-gpu-ex-cuda-12.ofi.bash
util/cron/test-gpu-ex-cuda-12.specialization.bash
util/cron/test-gpu-ex-rocm-62.bash
util/cron/test-gpu-ex-rocm-62.ofi.bash
util/cron/test-perf.gpu-ex-cuda-12.bash
util/cron/test-perf.gpu-ex-cuda-12.um.bash
util/cron/test-perf.gpu-ex-rocm.bash

Due to changes in the nightly testing system's setup, we have to move our `nvidia` testing to a different partition. This PR mainly handles that. Specifically:
- Creates a `common-gpu-nvidia-hpe-cray-ex` script to have `CHPL_LAUNCHER_PARTITION` export, as we repeat that in many scripts.
- While there, also removes `CHPL_LOCALE_MODEL` and `CHPL_TEST_GPU` from individual scripts, as they are set in the `common-native-gpu.bash` script, which is sourced by all GPU test scripts.
The `deviceAttributes` test may fail on the new partition. I am unable to test there, so choose to merge the PR without any change to the test to make progress on nightly testing runs. I'll adjust the test if there's any fallout.

Move nvidia testing to a different partition, cleanup scripts a bit

---

test/library/standard/Debugger/breakpoint/useBreakpoint-gdb.suppressif
test/library/standard/Debugger/breakpoint/useBreakpoint-lldb.suppressif

Adds a suppressif for two debugging tests that do not yet work well with multi-locale code.

Add a suppressif for two debugging tests

---

frontend/lib/resolution/InitResolver.cpp
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/Resolver.h
frontend/lib/resolution/VarScopeVisitor.cpp
frontend/lib/resolution/VarScopeVisitor.h
frontend/lib/resolution/call-init-deinit.cpp
frontend/lib/resolution/copy-elision.cpp
frontend/lib/resolution/default-functions.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/split-init.cpp
frontend/test/ErrorGuard.h
frontend/test/resolution/testCast.cpp
frontend/test/resolution/testDeprecationUnstable.cpp
frontend/test/resolution/testEnums.cpp
frontend/test/resolution/testForwarding.cpp
frontend/test/resolution/testGenericDefaults.cpp
frontend/test/resolution/testHeapBuffer.cpp
frontend/test/resolution/testLoopIndexVars.cpp
frontend/test/resolution/testMethodCalls.cpp
frontend/test/resolution/testMultiDecl.cpp
frontend/test/resolution/testNew.cpp
frontend/test/resolution/testOpaqueExternTypes.cpp
frontend/test/resolution/testOperatorOverloads.cpp
frontend/test/resolution/testResolve.cpp
frontend/test/resolution/testResolverVerboseErrors.cpp
frontend/test/resolution/testRuntimePrimitives.cpp

**Best reviewed commit-by-commit.**
Previously, `call-init-deinit.cpp` had the following comment:
```C++
// TODO: Run this for module initializer code as well. Currently if enabled,
// it breaks a large number of dyno tests that have module-initializer code
// containing things we can't resolve default-init for yet, such as
// fully-defaulted generic types. Either adjust the tests to expect the errors
// for unsupported code, or add the support, then enable this on modules.
if (!resolver.symbol->isModule()) {
```
It seems like we are far enough along that module-level variables don't break things in any cases I've tried. So, re-enable these steps. Lots of tests were relying on them not being invoked, so update those. While there, fix a number of bugs that came up. See each individual …

Dyno: enable module scope checks

---

frontend/lib/resolution/split-init.cpp

This warning gets escalated into an error on some compilers.
Trivial, will not be reviewed, but was actually reviewed by @dlongnecke-cray -- thanks!

Dyno: fix an unused variable warning.

---

util/cron/test-gpu-ex-cuda-12.specialization.bash

I missed this file while adjusting the partition we run GPU testing on. The end result was that we were using the default partition which is AMD-based, but this config is for NVIDIA. So, we were getting `no CUDA-capable device is detected`

Add the missing include to the GPU specialization config

---

frontend/lib/resolution/VarScopeVisitor.cpp
frontend/lib/resolution/VarScopeVisitor.h
frontend/lib/resolution/call-init-deinit.cpp
frontend/lib/resolution/copy-elision.cpp
frontend/lib/resolution/split-init.cpp
frontend/test/resolution/testCopyElision.cpp
frontend/test/resolution/testCustomInfer.cpp
frontend/test/resolution/testDeprecationUnstable.cpp
frontend/test/resolution/testHeapBuffer.cpp
frontend/test/resolution/testInitSemantics.cpp
frontend/test/resolution/testMultiDecl.cpp
frontend/test/resolution/testOperatorOverloads.cpp
frontend/test/resolution/testPromotion.cpp
frontend/test/resolution/testResolve.cpp
frontend/test/resolution/testResolverVerboseErrors.cpp
frontend/test/resolution/testTuples.cpp
frontend/test/resolution/testTypePropertyPrimitives.cpp
frontend/test/test-resolution.cpp

This PR started off with a simple idea: Reduce special cases for types that do not need init/deinit.
Right now we do not sufficiently account for all cases in which a type does not need init/deinit, meaning that sometimes we skip checks and others we don't. Instead of incomplete skipping of checks and resolution for the sake of simplicity, let's just make it actually work for such types.
This also helps simplify things for typed conversion, as this commit will cause assignment operators to be resolved and stored. Another benefit is increased testing of copy-elision/split-init rules now that we're testing against integers more regularly as well.
This PR required a change from using 'idToParentId' to 'ID::contains' to account for usage in nested calls.
-----
The next change improves copy …

Dyno: Various copy-elision and split-init fixes

---

compiler/passes/convert-typed-uast.cpp

Ignores an unused tuple element. Trivial, not reviewed.

Fix gcc-74 config

---

frontend/include/chpl/resolution/resolution-queries.h
frontend/include/chpl/types/ArrayType.h
frontend/include/chpl/types/FnIteratorType.h
frontend/include/chpl/types/PromotionIteratorType.h
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/disambiguation.cpp
frontend/lib/resolution/maybe-const.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/return-type-inference.cpp
frontend/lib/types/ArrayType.cpp
frontend/lib/types/FnIteratorType.cpp
frontend/lib/types/PromotionIteratorType.cpp

Closes https://github.com/Cray/chapel-private/issues/7333. There's no issue for const field accessors, but this would close that too.
The original program I set out to make work was this:
```Chapel
proc helper(ref data) {
data[5] = 10;
}
proc test() {
var A : [1..10] int;
helper(A[1..5]);
}
test();
```
The curiosity here is that `ref data` accepts a mutable reference, and we are passing it a slice. Normally, a value produced by an expression cannot be passed to a mutable reference, since it's a temporary. However, slices produce values that _alias_ other arrays. Although they are values, they can be used for non-const references.
The fact that the result of slicing `A` is const for const `A` and non-const for non-const `A` seemed similar to how field access works (fields are refs if the …

Dyno: const ref field access, aliasing arrays

---

frontend/lib/resolution/BranchSensitiveVisitor.h
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/VarScopeVisitor.cpp
frontend/lib/resolution/VarScopeVisitor.h
frontend/lib/resolution/return-type-inference.cpp
frontend/test/resolution/testReturnTypes.cpp

Evidently this is necessary, since we have existing examples that rely on return type inference in cases like `throw; return`.
To make this work, adjust the BranchSensitiveVisitor and its related types to distinguish between "throws" and "returns", and adjust the `isDoneExecuting` check to not return true for throws. Then, for analyses that DO ignore code after throwing etc., broaden the early-return check to include throwing in addition to `isDoneExecuting`.
This has the net effect of making the Dyno resolver proceed past `throws` statements, resolving expressions etc. in `return` and `yield`s, as well as making return type inference do something similar.

Dyno: continue resolution after 'throws'

---

frontend/test/resolution/testOpaqueExternTypes.cpp

This fixes a broken dyno test by updating the expected general error message text added in https://github.com/chapel-lang/chapel/pull/27203, to match the more specific error message that was added in https://github.com/chapel-lang/chapel/pull/27038.
TESTING:
trivial change to test's expected error output only - not reviewed

update dyno test's expected error message text

---

.github/workflows/monitor-homebrew.yml

This changes the Github workflow that compares our Homebrew formula to the published formula to run three times a day instead of once. 
With this change, the formula should be checked at 7am, 1:30pm, and 4:30pm pacific daylight time. When the time change occurs in the fall, these will run at 6am, 12:30pm, and 3:30pm pacific standard time. 
[reviewed by @arifthpe - thanks!]

increase frequency of GH homebrew checks

---

doc/Makefile
doc/rst/language/spec/conversions.rst
doc/rst/language/spec/records.rst

As pointed out in #27249, we have not been testing a few of our examples in the records chapter of the spec.  As a result, they silently broke when we added the requirement that a mixed-type `init=` must also define a cast between those types.  This adds the missing casts and makes the remaining examples testable.  It also adds a mention of the requirement and its rationale.
While here, I did some other cleanup:
* made other reasonable examples in the chapter not mentioned in #27249 testable/tested
* renamed a test called `paramPassing.chpl` to `argPassing.chpl` because we're not passing `param`s in it
* renamed "Advanced Copy Initialization" to "Mixed-Type Copy Initialization" because it seems more precise, and the term "Advanced" never really gave me any idea what I'd find in the …

Make spec's docs of `init=` on records testable and refresh them so they work again

---

util/cron/test-perf.chapcs.arkouda.release.bash

Adjust one of the Arkouda release nightly jobs to use the correct LLVM version

Use LLVM 19 with the Arkouda release job

---

doc/rst/usingchapel/multilocale.rst
util/chplenv/chpl_comm_segment.py

Adds a build time check for CHPL_GASNET_SEGMENT=everything and CHPL_COMM_SUBSTRATE=smp|ucx, which is unsupported and can fail in surprising ways to users.
This PR also updates the documentation to reflect that this configuration is unsupported.
Resolves https://github.com/chapel-lang/chapel/issues/27224
[Reviewed by @jhh67 and @bonachea]

Make using CHPL_GASNET_SEGMENT=everything and CHPL_COMM_SUBSTRATE=smp|ucx a build time error

---

util/packaging/homebrew/chapel-main.rb

Unpins the LLVM 19 as a dependency for the homebrew formula in our tree.
Normal release procedures should result in this change being propagated to homebrew-core.

Unpin LLVM 19 for homebrew formula

---

doc/rst/technotes/gpu.rst
test/gpu/native/llvmMoved.chpl
test/gpu/native/llvmMoved.skipif

Updates the GPU technote to reflect the new LLVM support for 20, which is now tested nightly.
As part of that, it updates `llvmMoved.chpl` to match. Additionally, I made the skipif for the test more directly check its predicate.

Update GPU technote to reflect new LLVM support

---

compiler/llvm/clangUtil.cpp

Avoids warnings about unused "-c" in newer clang versions when parsing extern blocks with CHPL_LLVM!=none and CHPL_TARGET_COMPILER!=llvm
Spot checked `start_test examples/primers/interopWithC.chpl`

Avoid warnings about `-c` and `-fsyntax-only`

---

runtime/src/gpu/nvidia/gpu-nvidia-cub.cc

Adds some missing calls to `CUDA_CALL` in the cub wrappers for reductions and sorts

Add missing calls to `CUDA_CALL` in cub wrappers

---

frontend/test/ErrorGuard.cpp

We have noted that `std::filesystem` is not available to GCC 7.5 -- which we support -- which caused build failures on certain machines. This PR replaces the uses of `std::filesystem` with code from the LLVM support library, which we alwaysa bring in, and which builds on the 7.5 GCC machines.

Dyno: Use LLVM support library instaed of std::filesystem

---

modules/packages/UnitTest.chpl
test/library/packages/UnitTest/AssertRegexMatch/SKIPIF
test/library/packages/UnitTest/AssertRegexMatch/testAssertRegexMatch.chpl
test/library/packages/UnitTest/AssertRegexMatch/testAssertRegexMatch.good

I needed this check while working on the Prometheus module. Granted, users can do their own checking and use `assertTrue`, but it feels like hiding the regular expression details would be a good addition to the UnitTest library.
Test

Add `assertRegexMatch` to the UnitTest module

---

compiler/main/driver.cpp

This was turning up in Arkouda testing, though it's unclear if it was actually causing a failure there.

Avoid missing brace warning in new edition code

---

doc/rst/language/spec/modules.rst

Fixes a docs rendering error in the spec for modules, caused by extraneous white space
Tested with `make spectests` and `make docs`.

Fix docs rendering error in spec for modules

---

doc/rst/technotes/gpu.rst
util/chplenv/chpl_gpu.py
util/cron/common-gpu-nvidia-hpe-cray-ex.bash
util/cron/test-gpu-ex-cuda-12.bash
util/cron/test-gpu-ex-cuda-12.interop.bash
util/cron/test-gpu-ex-cuda-12.ofi.bash
util/cron/test-gpu-ex-cuda-12.specialization.bash

Disallows using LLVM 20 with CHPL_GPU=nvidia, due to upstream LLVM issues
See https://github.com/llvm/llvm-project/issues/141626 and https://github.com/chapel-lang/chapel/issues/27273
This PR also updates the docs and test configs

Disallow LLVM 20 with nvidia GPUS

---

util/build_configs/build_configs.py
util/test/convert_start_test_log_to_junit_xml.py

This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```

Resolve logger warnings

---

util/config/find-python.sh

The `--version-sort` argument is not specified by POSIX. Instead, use multi-key numeric sort.
Reviewed by @jabraham17 and @arifthpe -- thanks!

Use a different version of the `sort` command to ensure portability

---

util/cron/test-perf.gpu-ex-cuda-12.bash
util/cron/test-perf.gpu-ex-cuda-12.um.bash

Fixes CHPL_GPU=nvidia performance tests on EX by removing CHPL_LLVM=system

Fix CHPL_GPU=nvidia performance tests on EX

---

modules/packages/Python.chpl

The one above it was private, so make this one private as well

Hide another function that was accidentally getting included in the docs

---

util/cron/common-arkouda.bash

Use the most up-to-date llvm/Makefile for arkouda release testing to pull in https://github.com/chapel-lang/chapel/pull/27315

Use the most up-to-date llvm/Makefile for arkouda release testing

---

test/library/standard/Debugger/breakpoint/useBreakpoint-lldb.compopts
test/llvm/debugInfo/gdb/targetVar.skipif
test/llvm/debugInfo/lldb/targetVar.prediff
test/llvm/debugInfo/lldb/targetVar.skipif
util/test/prediff-for-debug

Cleans up a few tests that were failing in some configs
- Skips valgrind testing, as that messes up text matching
- Adds `--no-munge-user-idents` with the C backend
- Skips baseline testing, as that results in more temps that show up in the debug output
- Adds a prediff for `settings set` for lldb to help with `--memLeaks` testing
- rewrites `util/test/prediff-for-debug` to avoid binary IO failures

Cleanup a few tests after fixing global debug information

---

modules/standard/Sort.chpl

Follow-up to PR #27277. This PR adjusts the documentation for `proc sort` to describe the current algorithm choice. It also addresses issue #27295 by adjusting the example `compare` method in the Sort documentation.

Improve sort docs after new impl

---

doc/rst/developer/bestPractices/EditionsDev.rst
doc/rst/developer/bestPractices/index.rst
doc/rst/technotes/editions.rst
doc/rst/technotes/index.rst
man/chpl.rst
test/edition/basics/attributeCheck.chpl

Reviewed by @jabraham17
Resolves Cray/chapel-private#7409
This adds two documents related to the new editions feature:
- A user-facing technote on how to use the feature and what to expect
- A developer-oriented document, covering implementation tips for both new editions and how to link breaking changes to editions
To support the developer document, I made a small modification to one of the editions tests so that it could be linked in the documentation.  This will hopefully prevent that example from breaking without us noticing it.
Also fixed an issue I noticed with the man page description of the flag.
Looks good with `make docs`, passed a full paratest with futures (due to the test and man page update).

Add editions documentation

---

third-party/gasnet/Makefile
third-party/gasnet/Makefile.setup

Add a `-Wno-incompatible-pointer-types` for the gasnet build to avoid issues with GCC 15
[Reviewed by @jhh67, Reviewed and co-contributed by @bonachea and @PHHargrove]

Workaround a GASNet issue with GCC 15

---

util/packaging/rpm/amzn2023-gasnet-udp/rpmlintrc
util/packaging/rpm/amzn2023-ofi-slurm/rpmlintrc
util/packaging/rpm/amzn2023/rpmlintrc
util/packaging/rpm/common/fill_docker_template.py
util/packaging/rpm/common/rpmlintrc
util/packaging/rpm/el10-gasnet-udp/rpmlintrc
util/packaging/rpm/el10-ofi-slurm/rpmlintrc
util/packaging/rpm/el10/rpmlintrc
util/packaging/rpm/el9-gasnet-udp/rpmlintrc
util/packaging/rpm/el9-ofi-slurm/rpmlintrc
util/packaging/rpm/el9/rpmlintrc
util/packaging/rpm/fc41-gasnet-udp/rpmlintrc
util/packaging/rpm/fc41/rpmlintrc
util/packaging/rpm/fc42-gasnet-udp/rpmlintrc
util/packaging/rpm/fc42/rpmlintrc

Fixes an issue seen the el10 package builds, where rpmlint would complain about an unused filter.
We did see builds pass with el10, but apparently one of the dependencies changes and caused this to start occurring. Its annoying that rpmlint is so picky (the warning is about us silencing another warning that doesn't occur), but the simple solution is to just stop trying to filter our that one warning for el10
Tested el10 and el9 locally.

Fix el10 package builds due to rpmlint error

---

README.rst

Twitter is still referenced in the resources section, even though the name was deprecated in July 2023 in favor of X. Since the website now refers to X, this PR proposes to update the reference accordingly.

Updates Twitter link

---

util/buildRelease/testReleaseHelp

Closes https://github.com/chapel-lang/chapel/issues/26561
Closes https://github.com/chapel-lang/chapel/issues/14133 (excluding the additional Travis CI check request)
Port [`testReleaseHelp`](https://github.com/chapel-lang/chapel/blob/main/util/buildRelease/testReleaseHelp) to bash.
Test run logs (using `cmake-3.25.1`):
<details>
<summary>Log</summary>
```bash
@subhramit ➜ /workspaces/chapel (convert-script) $ ./util/buildRelease/testReleaseHelp make
Setting CHPL_HOME to /workspaces/chapel
Updating PATH to include /workspaces/chapel/bin/linux64-x86_64
and /workspaces/chapel/util
Updating MANPATH to include /workspaces/chapel/man
Setting CHPL_COMM to none
Setting CHPL_TASKS to fifo
Setting CHPL_TARGET_MEM to cstdlib
Setting CHPL_HOST_MEM to cstdlib
Setting CHPL_GMP to none
Setting CHPL_RE2 …
```

Convert `testReleaseHelp` script to bash

---

test/library/standard/Sort/correctness/partitioning-sort-ml.compopts
test/library/standard/Sort/correctness/partitioning-sort-utilities-ml.compopts
test/library/standard/Sort/correctness/partitioning-sort-utilities.chpl
test/library/standard/Sort/correctness/partitioning-sort-utilities.compopts
test/library/standard/Sort/correctness/partitioning-sort.chpl
test/library/standard/Sort/correctness/partitioning-sort.compopts

* enables extra checking for more test coverage
* reduces the number of configurations / problem sizes tested to avoid the tests taking too long
* intended to address timeouts in the gasnet + quickstart configuration

Limit tests to avoid timeouts for partitioning-sort tests

---

test/library/standard/Sort/correctness/partitioning-sort-utilities.chpl
test/library/standard/Sort/correctness/partitioning-sort.chpl

Follow-up to PRs #27277 and #27382 to address timeouts in gasnet+quickstart. Does so by reducing the problem size when running multilocale.

Reduce partitioning-sort test problem size for multilocale

---

runtime/src/chplcast.c
test/types/imag/inf-conversion.chpl
test/types/imag/inf-conversion.good
test/types/imag/nan-conversion.chpl
test/types/imag/nan-conversion.good

[reviewed by @mppf]
On my local machine, I was seeing that casting `infi` ("imaginary infinity"), from a string to the `imag` type was working just fine, but when I took it to our main testing machine, it was encountering a "bad cast" error.  This change avoids that error so that the cast works in both settings.
Adds a test locking in that the bug has been fixed with `infi`, and a test of doing the same thing with `nani` (which always worked).

Fix a bug with casting inf to imag

---

runtime/src/chplcast.c
test/types/imag/badStringInfiCast.chpl
test/types/imag/badStringInfiCast.good

My comparison was stopping early and so accepting things that weren't actually a match.
Add the test case Brad wrote to lock in that the fix worked.  It only was needed on linux, since the code follows a different path for Macs.

Fix bug pointed out by Brad allowing casting `infisomething` to imag 

---

modules/dists/PrivateDist.chpl
test/distributions/private/equals.chpl
test/distributions/private/equals.good
test/distributions/private/passToTypedFormal.chpl
test/distributions/private/passToTypedFormal.good

The previous implementation  of `==` on `privateDist` objects relied on a dsi procedure that had not been implemented for privateDists, which seems to have been a mistake of mine in #23393.  However, since all privateDists are equivalent (they take no arguments), this is overkill, and we can just declare them equal in the routine as it stands. Add this capability and a test of it, as well as a test that exercises `==` indirectly by passing an array argument to a formal with a `privateDist` domain.

Fix implementation of PrivateDist equality and inequality

---

test/parallel/cobegin/gbt/cobegin-stacksize.skipif

Supersedes https://github.com/chapel-lang/chapel/pull/27366
This test started to fail after https://github.com/chapel-lang/chapel/pull/27277. This is probably because having more code compiled in after that PR. Since the test is for an error condition, we decided to skip it with linux32.

Skip cobegin-stacksize with linux32

---

frontend/lib/util/chplenv.cpp

Fixes an issue where chapel would fail to find the runtime library. This would occur in the following scenario
* the user did a prefix install
* the user then made a "view" of that prefix install by creating new directories and symlinking all the files
* the user also set CHPL_HOME
Chapel would then see CHPL_HOME being set, and because the directories containing Chapel were not the same inodes detection for a prefix-based install would fail. This would then result in Chapel looking in the wrong place for libraries.
In a prefix based install, users should not be setting CHPL_HOME (as there is no need to), but if they do it usually "just works". This fixes things so that even if a user (or the spack package) set CHPL_HOME it still works.
Fixes the issue described in …

Fix errors about missing runtime if user sets CHPL_HOME in a prefix install with a "view"

---

tools/chapel-py/setup.py

Makes the chapel-py build not rely on CHPL_HOME being in the environment
This is motivated by build environments which may not have CHPL_HOME set, like the spack package

Make chapel-py build not rely on CHPL_HOME

---

compiler/llvm/clangUtil.cpp
doc/rst/technotes/gpu.rst
runtime/src/gpu/nvidia/Makefile.share
util/chplenv/chpl_gpu.py
util/cron/common-gpu-nvidia-hpe-cray-ex.bash

Resolves an issue where Chapel's nvidia GPU support was broken with LLVM 20+, due to changes in the clang driver.
See https://github.com/llvm/llvm-project/issues/141626 for more details on the original issue and the solution. TL;DR With LLVM 20+ the PTX assembly is no longer included in the GPU binary by default, meaning we can only target the exact architecture specified in CHPL_GPU_ARCH. Passing `--cuda-include-ptx=all` restores the previous behavior.
Resolves https://github.com/chapel-lang/chapel/issues/27273 and reverts https://github.com/chapel-lang/chapel/pull/27282
Tested on an EX with `start_test test/gpu/native/reduction`
[Reviewed by @arifthpe and @e-kayrakli]

Resolve issue with Chapel's nvidia GPU support with LLVM 20+

---

util/test/checkCopyrights.bash

Fixes an issue introduced by https://github.com/chapel-lang/chapel/pull/26576 where running `smokeTest lint` on a Chapel source tree with an existing build fails due to missing copyrights in generated files.

Exclude generated minimal modules from copyright check

---

make/compiler/Makefile.gnu

Fixes an issue where a user could have a Chapel install without the HOST_CXX compiler being available (e.g. a binary linux OS package), but the build system would try and invoke it when building launchers.
This issue was not a correctness issue, just when building a Chapel program a bunch of erroneous output would appear when invoking the Makefiles for the launcher. The fix is to just skip these C++ checks when the `Makefile.gnu` file is used to build a launcher, since none of the Chapel launchers require C++. This is done by replacing the invocations of `HOST_CXX` with a default value, since the result is just used to generate a set of compilation flags which are never used.
resolves https://github.com/chapel-lang/chapel/issues/27130
Tested that this resolves #27130 in an environment …

Don't run C++ compiler checks when building launchers

---

tools/mason/MasonNew.chpl

Adds `doc` to the gitignore generated by mason, similar to how `target` is ignored
Resolves https://github.com/chapel-lang/chapel/issues/25015

Add `doc` to the list of initial ignored files in mason

---

test/llvm/alignment/check-align16.skipif
test/llvm/debugInfo/lldb/targetVar.skipif

Skips two tests that fail with older LLVMs
Both of these LLVMs will likely be removed when resolving https://github.com/chapel-lang/chapel/issues/27269, so this is not a huge priority to fix these tests for old LLVMs

Skip two tests with older LLVMs

---

test/chpldoc/nested.doc.chpl
test/chpldoc/nested.doc.good
tools/chpldoc/chpldoc.cpp

This PR fixes a bug with the indentation of documentation for nested type methods, which previously was not being indented. Previously, in #23558, I made a fix focused on nested types, but failed to recognize the issue would apply to methods on those types as well.
The solution here is to increment the indentation depth for both the nested type and its children, _and_ to carry over that indentation depth through calls to ``rstDoc``.
Before, ``rstDoc`` would start from a depth of 1 and relied on the way that child documentation was combined to get correct indentation. When ``rstDoc`` returns, the result is stored in a list of children objects. Later, when we go to process those children, we increment the indentation depth before printing their contents. This only works if the child has a …

Fix chpldoc indentation of documentation text for methods on nested types

---

doc/rst/tools/mason/guide/externaldependencies.rst
doc/rst/tools/mason/guide/manifestfile.rst
doc/rst/tools/mason/start/whymason.rst

Expands the existing docs for Mason.toml to be more explicit about what belongs in a Mason.toml file.
Resolves https://github.com/chapel-lang/chapel/issues/13787

Expand the docs for the Mason.toml manifest

---

runtime/src/comm/gasnet/comm-gasnet-ex.c
third-party/gasnet/Makefile.setup

This commit removes the warning-suppression flag introduced (at my suggestion) in #27351 in favor of adding the type casts required to fix the subject of the warnings.
Relative to the original fix using the compiler flag, this approach re-enables the compiler warning for other code.
The compiler's warning-suppression flag in `third-party/gasnet/Makefile` is still required when building `third-party/gasnet` until/unless the GASNet-EX snapshot is updated.  However, that is not in-scope for this pull request.
CC: @bonachea

Improve workaround for comm-gasnet-ex + GCC-15

---

test/llvm/PREDIFF

Fixes a bad bash script that was resulting in us being unable to find FileCheck.
I failed to notice this in my testing because the script would fall back to another install of FileCheck on some systems, and so the bad bash scripting went unnoticed.
[not reviewed]

Fix bash script for finding llvm FileCheck

---

doc/rst/conf.py

Exclude AutoGPU from the docs, since it is `include`d in the GPU docs. This prevents AutoGPU from showing up in search results.

Exclude AutoGPU from the docs

---

util/packaging/rpm/amzn2023-gasnet-udp/rpmlintrc
util/packaging/rpm/amzn2023-ofi-slurm/rpmlintrc
util/packaging/rpm/amzn2023/Dockerfile.template
util/packaging/rpm/amzn2023/spec.template
util/packaging/rpm/el10-gasnet-udp/rpmlintrc
util/packaging/rpm/el10-ofi-slurm/rpmlintrc
util/packaging/rpm/el10/Dockerfile.template
util/packaging/rpm/el10/spec.template
util/packaging/rpm/el9-gasnet-udp/rpmlintrc
util/packaging/rpm/el9-ofi-slurm/rpmlintrc
util/packaging/rpm/el9/Dockerfile.template
util/packaging/rpm/el9/spec.template
util/packaging/rpm/fc41-gasnet-udp/rpmlintrc
util/packaging/rpm/fc41/spec.template
util/packaging/rpm/fc42-gasnet-udp/rpmlintrc
util/packaging/rpm/fc42/spec.template

Fixes some OS dependencies which were broken in https://github.com/chapel-lang/chapel/pull/25340.
The "fix" is to remove `slurm-devel` as a dependency, this still allows the package to build everything and be installed. Just if a user tries to run a compiled chapel progam using `slurm-srun` they will not be able to (which was the case before, they need to have slurm installed AND configured properly)
For simplicity, this PR also removes a few other dependencies that are not being used yet
Also cleaned up some files that were left behind due to conflicting PRs

Fix dependencies for el9, el10, and amzn2023

---

util/packaging/docker/github-ci/Dockerfile

Updates the CI image to use newer dependencies.
Updates from LLVM/clang 13 to 19. To do this, also updates the OS from Ubuntu 22 LTS to Ubuntu 24 LTS. This is required to [drop support for older LLVMs](https://github.com/chapel-lang/chapel/issues/27269)

Update CI image to a newer OS/package depedencies

---

doc/rst/technotes/editions.rst
modules/internal/ChapelDomain.chpl
test/library/standard/Sort/errors/sortDomainArray.assoc7-removed.good
test/library/standard/Sort/errors/sortDomainArray.compopts

Removes the `iter sorted` method on associative arrays, which was meant to be removed/unstable in 2.0 but was forgotten. Since removing it now constitutes a breaking change, this PR removes it in the next edition of Chapel.
[Reviewed by @ShreyasKhandekar  and @lydia-duncan]

Remove `sorted` in the pre-edition

---

modules/standard/Map.chpl

Resolves a TODO in the `Map` docs which was blocked by a chpldoc/chapeldomain bug. That [bug](https://github.com/chapel-lang/chapel/issues/23776) is fixed with https://github.com/chapel-lang/sphinxcontrib-chapeldomain/pull/103 and https://github.com/chapel-lang/chapel/pull/27468, so the TODO can be resolved

Resolve TODO in `Map` docs

---

third-party/chpl-venv/Makefile

Fixes a build issue with chapel-py when trying to use a very old version of pip.
This issue is the source of a nightly test problem where pip 20 is used. The issue is that when installing from a setup.py, that version of pip copies the source tree to a temp directory, which breaks our method of finding CHPL_HOME.
The fix in this PR is to always upgrade pip when making our chpldeps venv.
NOTE: this does not fix the root issue, if a user tries to do `pip install tools/chapel-py` with an older pip, it will not work.

Fix chapel-py build issues with older pip

---

util/packaging/apt/debian11/Dockerfile.template
util/packaging/apt/debian11/control.template

Fixes the debian 11 package build after dropping LLVM 11 support, since debian 11 defaults to LLVM 11. The fix is to explicitly specify a LLVM version

Fix debian 11 package build after dropping llvm 11 support

---

tools/chapel-py/CMakeLists.txt

Fixes an issue in detecting CHPL_HOST_CC|CXX.
This was cuaght by post merge smoke tests, on systems where CHPL_HOST_CC|CXX has extra arguments. CMake really doesn't like passing more than one arg to CMAKE_C*_COMPILR, so the solution is to split it apart and pass the extra stuff to CMAKE_C*_FLAGS.

Fix detection of CHPL_HOST_CC|CXX in chapel-py

---

tools/chapel-py/CMakeLists.txt

Fixes the chapel-py build with CHPL_LLVM=none
The fix is to always pass the LLVM flags to chapel-py, since CHPL_LLVM=none still uses LLVM (due to CHPL_LLVM_SUPPORT)

Fix chapel-py build with CHPL_LLVM=none

---

modules/standard/Subprocess.chpl
test/library/standard/Spawn/doc-examples/example_signal.chpl

[contributed by @Guillaume-Helbecque, reviewed by Lydia]
Test a last code block in `Subprocess` doc that I missed in #27379.
Passed a fresh run of the new test and the built documentation looks good.

Test last code block in `Subprocess` doc

---

doc/rst/platforms/aws.rst
doc/rst/platforms/comm-layers/libfabric.rst
doc/rst/platforms/networks/infiniband.rst
doc/rst/technotes/optimization.rst

This PR adds documentation for `CHPL_RT_COMM_OFI_DEDICATED_AMH_CORES=true` and improves some documentation of related settings.

Document CHPL_RT_COMM_OFI_DEDICATED_AMH_CORES=true

---

doc/rst/tools/chapel-py/chapel-py.rst
third-party/chpl-venv/Makefile
tools/chapel-py/CMakeLists.txt

Fixes the issue that https://github.com/chapel-lang/chapel/pull/27502 tried to fix, where an incorrect CC/CXX was inferred by Python/CMake.
The fix of CC/CXX broke more configurations than it fixed, because in many situations we rely on CC/CXX to infer HOST_CC/HOST_CXX
<details>
<summary> details of issue </summary>
The problem is that CC/CXX are being set to some value and passed to the CMakeLists.txt, which is then passed along as a part of the environment when invoking `printchplenv`. On some systems, this can break `printchplenv`'s detection of the host compiler. Some of these problems where fixed by improving `printchplenv`, but fundamentally one problem that can occur is that `chapel-py` and dyno end up using different compilers, which can have ABI problems.
I originally thought …

Handle CC/CXX for the chapel-py build

---

runtime/src/chpl-launcher-common.c
runtime/src/launch/slurm-gasnetrun_common/slurm-gasnetrun_common.h

Fixes 1 memory fault and 2 memory leaks in the slurm-gasnetrun_ launchers. The memory fault was resulting in a confusing corruption of the `salloc` launch command, with garbage bytes being inserted. This was only repeatable with specific file name lengths. The problem was caused by strings not being properly null terminated, which was caused by an off-by-one error resulting from a bad assumption about `vsnprintf`. To debug and fix this memory fault I used valgrind, which flagged 2 other memory leaks (also fixed in this PR).
Testing
- Note that running with `--show-leak-kinds=all` shows a bunch of extra leaks in `config.c`
Future work: What would it take to rewrite parts of the launchers in C++, instead of C. While rewriting the launchers in something other than C had been a long term …

Fix memory faults in slurm-gasnetrun_* launchers

---

util/cron/create_release_aptrpm.bash
util/packaging/common/.gitignore
util/packaging/common/build_helpers.sh

Simplifies packaging building helpers to make the code more maintainable in the future and easier to diagnose issues with it.
This creates less places someone needs to update files to add new OSes, and makes the command much simpler and easier to remember (with a help message when its wrong)

Simplify package building helpers

---

doc/rst/usingchapel/chplenv.rst

Adds an index entry for `chplconfig` files so its more searchable in the docs
[Trivial - not reviewed]

Add `.. index::` for chplconfig to make it more searchable

---

test/chplcheck/rule-settings/SKIPIF

Fixes a skipif that was always returning `True`.

Fix broken skipif for chplcheck test

---

doc/rst/developer/bestPractices/MemoryProfiling.rst
doc/rst/developer/bestPractices/index.rst
third-party/jemalloc/Makefile
util/chplenv/chpl_jemalloc.py

Adds some documentation on building the Chapel compiler (and to some extent Chapel programs) with jemalloc's memory profiler.
This is intended to be a developer-only feature, as its most useful for developing and improving the Chapel compiler.
This PR also includes some build system changes to support the direction outlined in `doc/rst/developer/bestPractices/MemoryProfiling.rst`

Add developer support for jemalloc memory profiling

---

modules/internal/ChapelArray.chpl
modules/internal/ChapelBase.chpl
modules/internal/ChapelRange.chpl
modules/internal/MemConsistency.chpl
modules/standard/CTypes.chpl
modules/standard/MemMove.chpl

Changes some internal modules to avoid inlining checks, since that can cause larger compilation times/memory usage. In some cases, this PR factors out the checks into another function so that they will not be duplicated in highly generic inlined functions (which do real work and probably should still be inlined).
Using arkouda as my proxy for a large Chapel application, this change saves 1% execution time.
This PR also removes some unused functions from MemMove.
<details>
<summary>useful scripts I wrote while working on this PR</summary>
Find inline functions with halts/compilerErrors
```python
import chapel
import sys
files = sys.argv[1:]
ctx = chapel.Context()
ctx.set_module_paths([], [])
for file in files:
asts = ctx.parse(file)
for (fn, _) in chapel.each_matching(asts, …
```

Avoid inlining functions that just do checks

---

modules/packages/TOML.chpl
test/library/packages/TOML/test/stringEscapes.chpl
test/library/packages/TOML/test/stringEscapes.good

Fixes an issue I came across where the TOML library does not correctly parse some strings, particularly ones with commas or escaped quotes (`\"`/`\'`).
This PR fixes the regex (which needed to be updated in two places) and refactors the code to remove some duplication.

Fix parsing of string values in TOML files

---

util/cron/test-gpu-xc-cuda.ugni.bash

Avoid using the bundled LLVM on this test machine to save machine time. This will fall back to the LLVM 14 from spack installed on the system

Do not use the bundled LLVM on XC+ugni

---

test/types/file/bradc/scalar/floatcomplexexceptions-aarch64.chpl
test/types/file/bradc/scalar/floatcomplexexceptions-aarch64.compopts
test/types/file/bradc/scalar/floatcomplexexceptions-aarch64.good
test/types/file/bradc/scalar/floatcomplexexceptions-aarch64.skipif
test/types/file/bradc/scalar/floatcomplexexceptions.skipif

[reviewed by @e-kayrakli]
This test failed on our aarch64 system due to system sign differences when computing the square root of -1.  It also has the same behavior on my arm Mac, but that was solvable with a platform-specific .good file and the platform for our aarch64 testing is linux64.  Since the only way to distinguish it is via the CHPL_TARGET_ARCH, skip the original test with `CHPL_TARGET_ARCH=aarch64` and make a soft-link copy of the test that only runs in that setting (using the same expected output as the darwin run).
Verified that the test skipped when expected and that the output matched that of darwin before reusing its .good file

Make a version of the floatcomplexexceptions test for aarch64

---

test/technotes/doc-examples/FirstClassProceduresCastOffFormalName.chpl

Stop doing `a == b == c` as that's deprecated. Fixes incorrect output for future file. Trivial and not reviewed.

Adjust future to stop using chained '==' as that is deprecated

---

util/packaging/rpm/amzn2023/spec.template
util/packaging/rpm/el10/spec.template
util/packaging/rpm/el9/spec.template
util/packaging/rpm/fc41/spec.template
util/packaging/rpm/fc42/spec.template

Adds a chpl-shim entry to `%files` in the spec file for RPM builds. This was missed in https://github.com/chapel-lang/chapel/pull/27528

Add chpl-shim entry to %files in spec for RPM builds

---

frontend/lib/resolution/can-pass.cpp
frontend/test/resolution/testFunctionCalls.cpp

Closes https://github.com/Cray/chapel-private/issues/7398.
Chapel's function resolution proceeds in two phases:
1. A simple "zippering" of formals and actuals, in which each pair is independently checked for compatibility
2. A dependency-aware sequential traversal in which type information (e.g., type queries) from all preceding formal/actual pairs is carried forward into subsequent ones.
For the initial phase, it's entirely possible for some formal type expressions to be missing information (e.g., if we have `formal2: f(formal1.type)`. In this case, the existing call resolution logic marks `f(...)` as having unknown type, and allows actuals to be passed to it. More strict checking is deferred until phase 2. However, prior to this PR, this allowing-unknown-formals was not done for `type` …

Dyno: Relax unknown-formal rule to enable more initial signature patterns

---

frontend/lib/resolution/default-functions.cpp
frontend/test/resolution/testEnums.cpp

Closes https://github.com/Cray/chapel-private/issues/7402.
The following code now resolves fine in `--dyno-resolve-only`:
```Chapel
proc main() {
var m = memoryOrder.seqCst;
writeln(chpl__enumToOrder(m));
}
```
The issue was that internal modules don't auto-use `ChapelBase`. 
https://github.com/chapel-lang/chapel/blob/4ac1978a54a367e368369b177d97d7ef1014cea2/frontend/lib/resolution/scope-queries.cpp#L523-L528
As a result, they don't have access to `==`. In production this doesn't come up because `chpl__enumToOrder` gets placed into `ChapelBase` (?!). In Dyno, we can't do this. Instead, this PR inserts a `use` statement into `chpl__enumToOrder` to simulate having access to the necessary methods etc.

Dyno: fix enumToOrder for enums declared in internal modules

---

util/cron/common-whitebox.bash
util/cron/load-base-deps.bash

[reviewed by @jabraham17]
Adjusts:
- the whitebox tests to load dependencies
- RHEL to use the right path to the Python 3.11 version (thanks Jade for pointing that out!)

More Python testing adjustments

---

frontend/lib/resolution/Resolver.cpp
frontend/test/resolution/testLoopIndexVars.cpp

Closes https://github.com/Cray/chapel-private/issues/7404.
This PR enables `param` iteration over ranges of enums. For instance, the following program produces one warning for every element in `letters`:
```chapel
enum letters {a, b, c, d, e, f}
for param c in letters.a..letters.f {
compilerWarning(c:string);
}
```
Curiously the original reproducer in https://github.com/Cray/chapel-private/issues/7404 does not work as expected, because warnings are not emitted from inside `main`. Not sure why that's the case, but it seems to be independent of `param` iteration.
While there, this PR resolves signedness concerns (preventing overflow etc.).
The high-level outline of the change is to think of iteration over enums as iteration over the indices of their elements. This is similar to, but not the …

Dyno: Iterate over param enum ranges

---

third-party/chpl-venv/Makefile
tools/chapel-py/src/core-types.cpp
tools/chapel-py/src/core-types.h
tools/chapel-py/src/method-tables/uast-methods.h
tools/chpl-language-server/src/chpl-language-server.py
tools/chpl-language-server/src/symbol_signature.py
tools/chpl-language-server/test/basic.py
tools/chpl-language-server/test/document_symbols.py

Fixes an issue where hovering over a primary method would just show `this`. Now it will show the method name properly. Along the way, I also added the type name for secondary methods (and primary methods when resolution is enabled)
In this PR:
* added `hash` and rich comparison to AstNode in chapel-py
* added `is_this` to Formal in chapel-py
* used the new comparison ops for AstNode to improve code quaility
* fixed hovering over a primary method
* improved printing of a secondary method by adding the type name
* improved printing of a primary method by adding the type name (only when resolution is enabled). This only works well when the type/method is fully concrete, because there is no way to compute an instantiation from a hover. In the future, it would be nice to be able to show the …

Fix printing of symbol in CLS when hovering

---

frontend/include/chpl/resolution/resolution-types.h
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/resolution-types.cpp
frontend/test/resolution/testPromotion.cpp

Closes https://github.com/Cray/chapel-private/issues/7401.
Specifically, this PR properly handles calls to methods that are the scalar type" of another type. E.g., this makes it possible to invoke a method on each element of an array or records/classes. Sample code from #7401: 
```Chapel
record R {
proc helper() {
return 5;
}
}
proc main() {
var A : [1..10] R;
var B = A.helper();
}
```

Dyno: promote methods

---

frontend/lib/resolution/VarScopeVisitor.cpp
frontend/test/resolution/testCallInitDeinit.cpp

Closes https://github.com/Cray/chapel-private/issues/7329.
This causes the following program to cause a copy initialization of `a`:
```Chapel
record R {
}
proc consume(ref x) {}
proc test() {
var a : R;
var ret = a:R;
consume(a);
return ret;
}
var x = test();
```
The error in the original issue was resolved by @benharsh as of https://github.com/chapel-lang/chapel/pull/27486; the program in the example works under `--dyno-resolve-only`. The key contribution of this PR is the invocation of the copy initializer, which production introduces via a call to `_removed_cast`, which has an `in` intent.
In the spirit of dyno -- where we try to avoid odd calls to unexpected internal functions -- this PR does not replicate the call to `_removed_cast`. Instead, it simply detects the auto-implemented …

Dyno: implement removed cast copy behavior

---

util/cron/common-whitebox.bash

I may need to make a special dependencies script just for our whiteboxes, but at a glance the only thing we didn't want was LLVM, since it was confusing our CC setting, so try just unloading it.

Unload the llvm module after loading the other dependencies for wb testing

---

util/cron/common-whitebox.bash

[reviewed by @arifthpe]
Instead of loading the normal base dependencies and unloading llvm, load a new base dependencies script I've created specially for the whiteboxes that doesn't include llvm from the start.  I'm doing this in case something about trying to load that llvm version is what is throwing off the CC computation for whitebox testing

Attempt to fix the whiteboxes, again

---

compiler/optimizations/deadCodeElimination.cpp
compiler/passes/normalize.cpp
compiler/resolution/callDestructors.cpp
frontend/include/chpl/uast/PragmaList.h

Adjusts the new dead code optimization added in https://github.com/chapel-lang/chapel/pull/27562 to avoid removing module deinit's.
The pass was avoiding removing regular deinit's, but module deinit's get unmarked as destructors and so weren't handled.

Adjust new dead code optimization to not remove module deinit

---

doc/rst/usingchapel/debugging.rst
runtime/etc/debug/chpl_lldb_pretty_print.py
runtime/src/comm/none/comm-none.c

Adds some initial pretty printing logic to ``--lldb`` for COMM=none programs. This pretty print works entirely for the C backend and partially for the LLVM backend (for now). 
This PR adds printers for the following types
- strings
- ranges
- homogeneous tuples
- local default rectangular domains
- local default rectangular arrays
Resolves https://github.com/chapel-lang/chapel/issues/27197
Note that this does NOT add tests of the pretty printer, as our primary linux64 nightly test machine has an LLDB without Python support. Its possible we can adjust this install or add testing on other machines.
Future work
- figure out why class types are resolved as `std::nullptr_t` with LLVM (see https://github.com/chapel-lang/chapel/issues/27603)
- figure out how to get these tested.
[Reviewed by …

Add initial LLDB pretty printer for some base Chapel types

---

frontend/lib/resolution/try-catch-analysis.cpp
frontend/test/resolution/testCatch.cpp

Closes https://github.com/Cray/chapel-private/issues/7403.
This PR addresses an internal error caused by the try-catch pass expecting a resolution result where there is none. Since the resolver always sets the type of try-catch variables, I deduced the issue was due to the resolver never visiting the code that `TryCatchAnalyzer` (TCA) is handling.
Indeed, the `Resolver` visitor, as well as many other Dyno visitors, skip dead code. However, TCA was not hooked up to do this, and thus was visiting dead code and balking at the lack of resolution results. This PR adjusts the TCA to also be branch-sensitive, by having it inherit from `BranchSensitiveVisitor` and invoke the necessary methods.

Dyno: branch sensitive try-catch

---

test/library/draft/DistributedMap/use-distributed-map.chpl
test/library/packages/Curl/doc-examples/CurlExamples.prediff
test/library/standard/Sort/correctness/SortTypes.chpl

Adjust two tests that sporadically die with a signal 9 in `correctness-test-c-backend`. While here, adjust `.prediff` for another sporadic failure to have it keep the original output around.

Reduce problem sizes of two tests which sporadically sig-9 in nightly

---

third-party/gasnet/Makefile.setup

Ignore errors when GASNET_INC_MAKEFILE is missing. This should only occur when someone explicitly deletes a gasnet include makefile, like in the homebrew formula (see #27626).
#27626 removed the gasnet include makefiles because they hardcode an incorrect compiler path from homebrew. This is fine, because once Chapel is built those makefiles aren't needed. But they are needed to run `make check`, which `brew test chapel` will run

Ignore errors when GASNET_INC_MAKEFILE is missing

---

test/library/standard/CommDiagnostics/doc-examples/CommDiagnosticsLittleExample1.compopts
test/library/standard/CommDiagnostics/doc-examples/CommDiagnosticsLittleExample1.good

This PR throws the `--no-cache-remote` flag explicitly for a new `CommDiagnostics` test. It is thrown implicitly on certain nightly testing configurations such as for `asan` and that affects comm counts. Trivial and not reviewed.

Throw '--no-cache-remote' when running new CommDiagnostics test

---

util/cron/test-linux64-python39.bash

[reviewed by @arifthpe]
Now that we're dropping support for Python 3.9 in chpldoc, start_test, etc, this job needed to be adjusted to test that scenario.  We want to make sure the compiler works and other things that support it, only.

Update the Python 3.9 job to match our Python 3.7 job

---

test/memory/shannon/printFinalMemStat.good

Revert changes made in #27237 after #27600 changed the output once again. A `param` branch was evaluating to `true`, and an array-view was allocated in a module's `deinit()` code. This accounted for the extra 192 bytes. Now that code does not run (for the moment).

Accept changes to .good file for 'printFinalMemStat.chpl'

---

compiler/codegen/cg-expr.cpp
modules/internal/ChapelDynamicLoading.chpl
test/dynamic-loading/SKIPIF
test/functions/fcf/pointers/SKIPIF

This PR adds support for older versions of LLVM that require typed pointers (currently the only version of LLVM we support that uses typed pointers by default is LLVM-14).
When issuing an indirect call we usually pass in a `void*` storing the address of the local pointer. This PR just adds a bitcast instruction to the function pointer type when the macro `HAVE_LLVM_TYPED_POINTERS` is defined.
We already do a similar thing when calling vtable pointers, so I found inspiration there.
I tested this with `LLVM-14` on `linux64` with `COMM=gasnet` and `COMM=none` and all the procedure pointer tests seem to pass.

dlopen: Add support for LLVM-14 typed pointers

---

third-party/gasnet/Makefile
third-party/gmp/Makefile
third-party/hwloc/Makefile
third-party/jemalloc/Makefile
third-party/libfabric/Makefile
third-party/libunwind/Makefile
third-party/mimalloc/Makefile
third-party/qthread/Makefile
third-party/re2/Makefile

Without this change, if CHPL_LIB_PIC is set in `chplconfig` (rather than as an environment variable) then third-party libraries would be built without -fPIC.

Use CHPL_MAKE_LIB_PIC instead of CHPL_LIB_PIC in Makefiles

---

test/studies/champs/functions.bash
test/studies/champs/sub_test

Changes how our CHAMPS testing works to run all compiles, instead of stopping when one CHAMPS executable fails to compile.
This means that even if one fails to compile, other executables will still be built/tested.

Prevent 1 CHAMPS failure from running other CHAMPS tests

---

modules/packages/UnitTest.chpl
test/library/packages/ArgumentParser/ArgumentParserTests.compopts
test/library/packages/UnitTest/AssertEqual/test_string_equality.compopts
test/library/packages/UnitTest/doc-examples/Runner.compopts
test/library/packages/UnitTest/doc-examples/Runner.skipif
test/library/packages/canCompileNoLink/testSockets.compopts

Fixes some tests when using `CHPL_RE2=none`, and tells the user how to fix it in the error message
Tested failing tests `start_test test/library/packages/UnitTest/doc-examples/Runner.chpl test/library/packages/UnitTest/AssertEqual/test_string_equality.chpl test/library/packages/canCompileNoLink/testSockets.chpl test/library/packages/ArgumentParser/ArgumentParserTests.chpl`

Fix tests when using `CHPL_RE2=none`

---

frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testIterators.cpp

Closes https://github.com/Cray/chapel-private/issues/7558.
The bug was caused by iterator varargs being wrapped in an extra layer of tuples. This happened because vararg formals are instantiated with the tuple of arguments passed to them, and subsequent re-runs just passed that tuple directly instead of expanding it.

Dyno: vararg iterator fix

---

frontend/include/chpl/framework/all-global-strings.h
frontend/include/chpl/resolution/can-pass.h
frontend/include/chpl/resolution/resolution-queries.h
frontend/include/chpl/types/CompositeType.h
frontend/include/chpl/types/Type.h
frontend/lib/resolution/can-pass.cpp
frontend/lib/resolution/default-functions.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/resolution-types.cpp
frontend/lib/types/ClassType.cpp
frontend/lib/types/CompositeType.cpp
frontend/lib/types/Type.cpp
frontend/test/resolution/testClasses.cpp
frontend/test/resolution/testMethodCalls.cpp

Closes https://github.com/Cray/chapel-private/issues/7559.
Closes https://github.com/Cray/chapel-private/issues/7560.
Also, improves the "equivalent treatment" of the implementation-detail manager record `_owned` and the builtin `owned` type in Dyno.
Both of the issues addressed by this PR were due to insufficiently advanced "syntactic genericity" checks. This is a step in the resolution of Chapel types in which the genericity of fields (and thus, whether they need to go into a type constructor) is determined. In production, a field is generic if (1) it refers to a generic type (2) somewhere in its type expression, the question mark `?` occurs. There is a comment there saying "Dyno should be more principled".
This PR improves Dyno's syntactic genericity checks to be more principled. …

Dyno: Improve genericity checks and allow `_owned(C)` -> `owned C` conversion

---

frontend/include/chpl/types/Param.h
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/types/Param.cpp
frontend/test/resolution/testCast.cpp

Closes https://github.com/Cray/chapel-private/issues/7604.
Dyno didn't allow casting `param` strings to numbers, even at runtime. This was because, if we detected a pair of primitive types in a `param` casts, we either performed the cast at compile time, or failed. However, the proper approach is to fall through to "regular" casts, so that the following two forms can be equivalent:
```Chapel
//form 1
var myVar = "1";
var res = myVar : int;
// form 2
var res = "1" : int;
```
This PR does that.

Dyno: allow casting param string to num

---

frontend/include/chpl/framework/ID.h
frontend/lib/framework/ID.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testEnums.cpp

Closes https://github.com/chapel-lang/chapel/issues/27624.
This PR implements casting a qualified string to the type (reporting errors if the qualifier is mismatched). The destination type is encoded in the `rhs` of the cat anyway, so the qualifier only serves for validation.

Dyno: allow casting qualified `param` strings to enums

---

frontend/lib/resolution/can-pass.cpp
frontend/test/resolution/testResolve.cpp

Closes https://github.com/Cray/chapel-private/issues/7599.
Thanks to work by @dlongnecke-cray, `isPod` is implemented. All I had to do was hook up the type class, and make a version of the tests based on David's original ones.

Dyno: implement built-in `chpl_anyPOD` type class

---

frontend/lib/resolution/try-catch-analysis.cpp
frontend/test/resolution/testCatch.cpp

Closes https://github.com/Cray/chapel-private/issues/7624.
Follows up on https://github.com/chapel-lang/chapel/pull/27591, which introduced branch-sensitivity to try-catch analysis. What was missing was a call to `markFatalError`, which is required when traversing calls to `compilerError`, to tell the branch-sensitive visitor to stop visiting subsequent code. Thus, in some cases, we'd try to access code past the end of available resolution information, and crash. This should fix that.
Notably, the error message / error handling for broken iterators (that have `compilerError` in them) is not addressed by this PR. It's a limitation of the compiler's handling of erroneous code, so it is taking a bit of a back seat. See https://github.com/Cray/chapel-private/issues/7620 (the specific error …

Dyno: fix branch-sensitive parts of try-catch analysis

---

util/cron/test-rhel.linux64.bash

[reviewed by @arifthpe]
This job has started sporadically running out of memory when making the compiler in parallel, likely due to running docker on the machine as well.  Reduce the amount of parallelism used when making the compiler to alleviate this issue.
Note: Of the jobs running on that machine, this seems to be the one most likely to run out of memory.  If the other ones start regularly exhibiting this behavior and this works to alleviate this job, I'll update them similarly

Limit the amount of parallelism used when running our RHEL job

---

frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/resolution-types.cpp
frontend/test/resolution/testResolve.cpp
frontend/test/resolution/testTuples.cpp
frontend/test/resolution/testTypeQueries.cpp

This is a tuple-themed one.
Closes https://github.com/Cray/chapel-private/issues/7553.
Closes https://github.com/Cray/chapel-private/issues/7554.
Closes https://github.com/Cray/chapel-private/issues/7556.
Closes https://github.com/Cray/chapel-private/issues/7555.
Would've closed an issue for resolving star-tuple queries too, but I didn't see one.

Dyno: resolution fixes variety pack 5

---

test/types/scalar/bradc/bitNegateBool.dyno.good
test/types/scalar/bradc/bitNegateBoolParam.dyno.good
test/types/scalar/bradc/valAsType.dyno.good
util/test/sub_test.py

Updates sub_test to prefer files ending with .dyno.good when testing with the ``--dyno-resolve-only`` compopts. This allows us to silence some error-message-related failures in dyno testing while we work through actual bugs.
Testing:

Add support for preferring .dyno.good files in testing

---

test/release/examples/benchmarks/Makefile

Removes `lcals` from a Makefile. `lcals` was removed from the benchmarks directory in https://github.com/chapel-lang/chapel/pull/23527, but this was left behind.
Resolves https://github.com/chapel-lang/chapel/issues/27710

Remove lcals from Makefile

---

runtime/src/topo/hwloc/topo-hwloc.c
test/runtime/jhh/colocales/Makefile
test/runtime/jhh/colocales/colocales.py
test/runtime/jhh/colocales/m1max.xml
test/runtime/jhh/colocales/m1pro.xml
test/runtime/jhh/colocales/m3pro.xml

This PR fixes some issues with our co-locale binding support. Prior to this PR, some architectures like Arm macs would run into internal runtime errors when trying to use colocales (for example with the smp substrate). This was due to the assumption that when trying to bind to an architectural feature, each partition had the same number of cores.
This PR takes the simple approach of just bailing out when it detects it cannot bind colocales to an architectural feature. [Other work](https://github.com/chapel-lang/chapel/pull/27243) had tried to be smart about this and keep looking for other architectural features to bind to, but this approach is simpler and less error-prone. Ideally, if a user requests an odd (as in unexpected) number of colocales, they should get that number of colocales …

Fix binding of colocales on non-homogeneous architectures

---

modules/internal/ChapelDynamicLoading.chpl

The branch in the module deinit for `ChapelDynamicLoading` tries to fan out and do cleanup on all locales, but currently the branch doesn't check if `numLocales > 1`. By checking to see if there are multiple locales we can avoid an allocation for an array view.

dlopen: Adjust module `deinit()` to avoid doing unnecessary work

---

util/cron/test-perf.hpe-apollo-hdr.gasnet-ibv.playground.bash

Switches the perf playground back to none

Stop using the perf playground for gasnet

---

util/buildRelease/gen_release

Adds `chpl-parallel-dbg` to gen_release.
this was left out of https://github.com/chapel-lang/chapel/pull/27644.
Note this intentionally does not add `chpl-parallel-dbg` to `install.sh` yet, that is future work

Add chpl-parallel-dbg to gen_release

---

modules/Makefile

In https://github.com/chapel-lang/chapel/issues/17387#issuecomment-3005908809, Ben noticed that we were missing the dollar signs for these variables, which prevented the generated rst files to be removed as intended. This makes that update.

Add missing $ for varibles in Makefile

---

frontend/include/chpl/parsing/parsing-queries.h
frontend/include/chpl/resolution/resolution-queries.h
frontend/include/chpl/resolution/resolution-types.h
frontend/lib/parsing/parsing-queries.cpp
frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/default-functions.cpp
frontend/lib/resolution/resolution-error-classes-list.cpp
frontend/lib/resolution/resolution-queries.cpp
frontend/lib/resolution/resolution-types.cpp
frontend/test/resolution/testResolve.cpp
frontend/test/resolution/testVarArgs.cpp

This variety pack is on the smaller side. It mostly addresses not-yet-categorized issues in `test/type_variables`.
First, I noted that my changes to `isFieldSyntacticallyGeneric` -- which started leaning more heavily on `getTypeGenericity` -- broke some test case. The reason was that, although I used an `ignore` set to prevent recursion, at some point the recursion, we invoke a query without the set, and end up not really tracking recursion at all. Instead, I adjust the logic to _first_ find all the types reachable from the type constructor, and then avoid recursing into them. The reason I think this is valid is in a comment in the diff: these types _better_ be concrete, or we wouldn't be able to build a type constructor.
I also noticed in `test/type_variables` that we don't properly …

Dyno: resolution fixes variety pack 6

---

compiler/llvm/clangUtil.cpp
doc/rst/developer/bestPractices/Sanitizers.rst
doc/rst/usingchapel/debugging/sanitizers.rst
test/deprecated/cpSplittingError.good
util/chplenv/chpl_llvm.py
util/chplenv/chpl_sanitizers.py

Adds support for CHPL_SANITIZE_EXE=address with LLVM.
Previously, this was only supported when using the C backend with either clang/gcc. This change will allow users to use asan in a config closer to the default.
Also removes an unused .good file and cleans up some `chpl_llvm.py` logic related to LLVM versions.
- resolves https://github.com/chapel-lang/chapel/issues/27113 since asan will now be supported with LLVM
- resolves https://github.com/Cray/chapel-private/issues/1984

Support CHPL_SANITIZE_EXE=address with LLVM

---

compiler/AST/primitive.cpp
compiler/AST/type.cpp
modules/standard/CTypes.chpl
test/extern/ferguson/c-array/c_array-anymanaged-and-generic.chpl
test/extern/ferguson/c-array/c_array-anymanaged-and-generic.good
test/extern/ferguson/c-array/c_array-anymanaged.chpl
test/extern/ferguson/c-array/c_array-anymanaged.good
test/extern/ferguson/c-array/c_array-generic.chpl
test/extern/ferguson/c-array/c_array-generic.good
test/extern/ferguson/c-array/c_array-unmanaged-and-generic.chpl
test/extern/ferguson/c-array/c_array-unmanaged-and-generic.good

Fixes an issue where attempting to `new c_array` with a generic type would segfault. 
This was caused when determine the return type of the primitive `array_get`. I fixed that in this PR (it now gives an internal error) and then to give a better user error I added a check for generic types in the `CTypes` initializer.
Without the check for generics
```
CTypes.chpl:242: internal error: invalid attempt to get reference type [AST/primitive.cpp:367]
```
With the check for generics
```
error: c_array element type cannot be generic
```
Resolves https://github.com/chapel-lang/chapel/issues/22301

Fix segfault caused by creating a generic c_array

---

compiler/resolution/preFold.cpp

Removes some old compiler code originally added to support a deprecated 'kind' field in IO's fileReader and fileWriter. The field itself has been gone for some time now, so we can remove the compiler workaround.
Testing:

Remove old compiler workaround for deprecated 'kind' field

---

modules/internal/ChapelDynamicLoading.chpl
modules/internal/ChapelLocks.chpl
test/dynamic-loading/LockGuard.chpl
test/dynamic-loading/LockGuardBadTaskIntent.chpl
test/dynamic-loading/LockGuardBadTaskIntent.good
test/dynamic-loading/PointerCacheInternals.chpl

This PR introduces a first attempt at a new locking abstraction. I've added it to the `modules/internal/ChapelLocks.chpl` module and named it `chpl_lockGuard` for now as I don't want to go through the process of making it user-facing.
Often times when writing code with critical sections I find that there are a few major irritations:
- The data and the lock are separate: one must remember to associate a specific lock variable with a data variable
- Critical sections are not lexically obvious, e.g., for every `lock` call there must be a matching `unlock` call
- Most irritating: accessing the data does not guarantee that the lock was taken
The first bullet point can't always be entirely avoided (sometimes you have one lock to N pieces of data). The second can be addressed by utilizing the …

dlopen: Add a new locking abstraction and use it in dlopen code

---

frontend/include/chpl/resolution/resolution-types.h
frontend/lib/resolution/resolution-queries.cpp
frontend/test/resolution/testNestedFunctions.cpp

Closes https://github.com/Cray/chapel-private/issues/6021.
After @dlongnecke-cray's work w/ nested functions, this was pretty trivial. 

Dyno: Implement resolving linkage names for procedures

---

test/types/chplhashtable/recordOfNonHashRecord.good
test/types/chplhashtable/recordOfNonHashRecord.prediff

A hashtable test is failing because a recent PR of mine introduced 3 more types which add their `.hash()` method to the set of visible candidates. Adjust the prediff for this test to replace e.g., "and 41 other candidates" with "and XXX candidates". Hopefully lowering the number of times the `.good` file for this test needs to be touched in the future.

Adjust prediff used by hashtable test

---

modules/internal/ChapelDynamicLoading.chpl
test/dynamic-loading/LoadForeignLibrary.chpl
test/dynamic-loading/LoadForeignLibrary.comm-none.good
test/dynamic-loading/LoadForeignLibrary.good

This PR fixes a rather embarassing bug with `loadSymbol`. When the same symbol was loaded twice the program would crash, because I forgot to emplace appropriate entries into the symbol table maintained by a `chpl_binaryInfo`. It also adds a test with heavy cross-locale contention which (more than) adequately covers the bug.

dlopen: Fix a bug in `loadSymbol`, add test with cross-locale contention

---

runtime/etc/debug/chpl_lldb_pretty_print.py

Fixes debugger pretty printing with the C backend when munging is turned off, a common debugging setup
When munging, the Chapel compiler will add a suffix (`_chpl`) to type names. When not munging, this suffix is not present.  So with munging turned off the regex matching various types needs to ignore the `_chpl` suffix.

Fix debugger pretty printing with the C backend when munging is turned off

---

compiler/llvm/llvmDebug.cpp
runtime/etc/debug/chpl_lldb_pretty_print.py
test/llvm/debugInfo/basicTypes.skipif
test/llvm/debugInfo/basicTypes.suppressif
test/llvm/debugInfo/lldb/SKIPIF
test/types/tuple/errors/tuple-init.bad

Fixes a few errors from merging https://github.com/chapel-lang/chapel/pull/27613
- fixes merge issues between https://github.com/chapel-lang/chapel/pull/27613 and https://github.com/chapel-lang/chapel/pull/27777 in the pretty printer
- adds missing skipifs and suppressifs where needed
- while there, removes an unrelated .bad file which is causing other nightly failures
- fixes the typed pointers build with LLVM 14

Fixes a few failures from merging a debug info PR

---

Makefile
Makefile.devel
third-party/chpl-venv/Makefile

Adjusts the makefile targets for `cls-test-venv` to be correct

Adjust cls-test-venv to be correct

---

Makefile
Makefile.devel
third-party/chpl-venv/Makefile

Adjusts the cls-test-venv Makefile target to properly create the cls test venv. 
Reapplies https://github.com/chapel-lang/chapel/pull/27800, plus some fixes now that `cls-test-venv` is only in `Makefile.devel`

Adjust cls-test-venv to be actually correct

---

compiler/AST/AggregateType.cpp
compiler/AST/FnSymbol.cpp
compiler/AST/type.cpp
compiler/include/AggregateType.h
compiler/include/FnSymbol.h
compiler/include/ModuleSymbol.h
compiler/include/symbol.h
compiler/include/type.h

Removes the unused `doc` field, which is leftover from when `chpldoc` was a compiler pass instead of a standalone tool.

Remove the unused `doc` field in the compiler

---

util/cron/test-perf.hpe-apollo-hdr.arkouda.playground.bash

This PR puts https://github.com/Bears-R-Us/arkouda/pull/4819 in the Arkouda perf playground. We expect [Scan regressions](https://github.com/Bears-R-Us/arkouda/issues/4810) to recover.

Put Arkouda PR 4819 on the performance playground

---

test/gpu/interop/cuBLAS/level1/test_cublas1.chpl
test/gpu/interop/cuBLAS/level1/test_cublas1.compopts
test/gpu/interop/cuBLAS/level1/test_cublas1.good
util/cron/test-gpu-ex-cuda-12.interop.bash

Fixes a failing cublas test with new cuda.
One of the cublas calls is segfaulting with the latest cuda version. Rather than investing the time to fix it (not sure where the problem is, on the cuda side or the chapel side. Nothing has changed on the Chapel side though), I am just turning off that one test
Also adjusts the logic to determine the cublas path
I opened https://github.com/chapel-lang/chapel/issues/27830 for the cublas crash

Fixes a failing cublas interop test with new cuda

---

util/cron/common-hpe-cray-ex.bash
util/cron/test-hpe-cray-ex-ofi.bash

Attempts to fix some nightly test failures caused system issues by building on a compute node
Tested with the following to emulate what `nightly` does
```bash
export CHPL_NIGHTLY_DO_NOTHING=1
source util/cron/test-gpu-ex-rocm-62.ofi.bash
perl test.pl
```
```perl
$make = "";
if (exists($ENV{'CHPL_NIGHTLY_MAKE'})) {
$make = $ENV{'CHPL_NIGHTLY_MAKE'};
} elsif (exists($ENV{'MAKE'})) {
$make = $ENV{'MAKE'};
} else {
$make = `$utildir/chplenv/chpl_make.py`;
chomp($make);
}
print "Using make: $make\n";
system("set -x && $make -j128");
```

Workaround system issues by building on a compute node

---

compiler/backend/beautify.cpp
compiler/llvm/clangUtil.cpp
frontend/include/chpl/util/filesystem.h
frontend/lib/util/filesystem.cpp

Switches some code that uses the pattern `fork/join + exec (mv, ...)` to rename files, since that can mess up a debug session during codegen (specifically codegenPartTwo).
Resolves https://github.com/chapel-lang/chapel/issues/25672

Improve debuggability of compiler by avoiding fork/join/exec

---

test/release/examples/hello6-taskpar-dist.nl-1.good
test/release/examples/hello6-taskpar-dist.nl-2.good
util/test/checkChplInstall

In some environments, like github actions, we may need to run `make check` with less than the number of locales requested by `hello6`. This PR allows that with the new internal env flag CHPL_CHECK_MAX_LOCALES

Add CHPL_CHECK_MAX_LOCALES to support limited environments

---

frontend/lib/resolution/Resolver.cpp
frontend/lib/resolution/Resolver.h
frontend/lib/resolution/resolution-types.cpp
frontend/test/resolution/testResolve.cpp
frontend/test/resolution/testTuples.cpp
frontend/test/resolution/testTypeQueries.cpp

Resolves all valid-program failures in `types/typdefs`, `types/typeFunctions`. Also resolves `types/tuple/BitWidthQueryInReturnTypeComponent`.
Each fix is its own change.
* Fixes tuple unpacking for tuple _types_. Prior to this change, `(...(1, 1.0))` and `(...(int, real))` had the exact same effect. After this change, the latter case passes `type` actuals (rather than `var` actuals), which is to be expected, since the whole thing is a tuple type, of which there aren't even necessarily values.
* Makes an adjustment to the handling for `x.foo` to trigger resolution of the field / parnless proc in more cases. This is necessary because some of our tests invoke `genericType.parenlessProc`, which is apparently fine and allowed. Prior, all generic types were skipped when resolving the dot, and …

Dyno: various fixes for `test/types`

---

frontend/lib/resolution/call-init-deinit.cpp

The call-init-deinit code assumes that move initialization is called with known LHS and RHS. In some error-producing cases, an out formal's type can be generic or unknown, which results in violating this assumption.
I adjusted the surrounding logic which calls resolveMoveInit, instead of weakining the assumption, because it seems attractive to let that assertion catch other cases of unknown LHS/RHS for us to inspect and decide what to do with.

Dyno: avoid asserting cases in call-init-deinit

---

make/compiler/Makefile.clang
make/compiler/Makefile.gnu
make/compiler/Makefile.intel

Changes the runtime to always compile with the C gnu11 standard, regardless of the minimum version of the C standard supported by that compiler. This change only affects clang, gnu, and intel compilers
resolves https://github.com/chapel-lang/chapel/issues/27826
resolves https://github.com/Cray/chapel-private/issues/7654

Change the runtime to always compile with the C gnu11 standard

---

compiler/main/arg.cpp
test/compflags/bradc/help/helpsettings.chpl
test/compflags/bradc/help/helpsettings.compopts
test/compflags/bradc/help/helpsettings.good
test/compflags/bradc/help/helpsettings.prediff
test/compflags/bradc/help/sub_test
test/compflags/bradc/help/userhelp.noexec

Fixes `--help-settings --devel`, which was broken by https://github.com/chapel-lang/chapel/pull/19956. #19956 added a new 'X' type for the argument parser, which meant that `--help-settings` was running into an "unexpected case", because #19956 did not add support for `--help-settings`
Also adds testing for `--help-settings` to help catch such regression in the future. The new test is NOT exhaustive, and just makes sure the compiler doesn't crash, not that the output looks right (since that is hard to test in a portable manner)

Fix --help-settings for new 'X' support

---

make/compiler/Makefile.clang

Removes an incorrect compiler option which is considered unknown for `-std=gnu11`

Remove incorrect compiler option for clang20

---

tools/chplcheck/src/chplcheck.py
util/config/run-in-venv-with-python-bindings.bash

Improves the startup performance of `chplcheck` by being lazier about loading dependencies
- moves calls to `printchplenv` to be only when needed, as these can be slow on some systems
- this will also affect CLS
- only import the lsp when we actually are running the lsp
- this gave me a 1-2s improvement of startup for the CLI
- I also cleaned up some unused imports  

Improve startup performance of `chplcheck`

---

util/packaging/homebrew/chapel-main.rb
util/packaging/homebrew/chapel-release.rb

Updates the 2 bundled homebrew formulas to match the upstream formula
- `chapel-release.rb` is updated to match the upstream exactly
- `chapel-main.rb` is updated to match the upstream, as all important changes have been upstreamed

Update bundled homebrew formulas to match upstream
