test/classes/initializers/inheritance/overloaded.chpl
test/classes/initializers/inheritance/overloaded.good

Behaves as desired, though that may be more accidental than by design.  Could
probably do with more extensive tests, so those will come at a later date.
Verified a fresh checkout.

Add a test of overloaded fields and initializers

---

test/llvm/llvm-invariant/SKIPIF

This is a trivial follow-on to PR #6802.

Add a SKIPIF

---

compiler/resolution/initializerResolution.cpp
compiler/resolution/visibleCandidates.cpp

This is a simple PR that updates the signatures for a small set of functions that
implement the filtering of ResolutionCandidates.
Before this PR the functions in the call chain were of the form
void <foo>(CallInfo& info, ResolutionCandidate* candidate, Vec<ResolutionCandidate*>& result);
On "success" the candidate would be inserted in result[] in a leaf of the call chain.
On "failure" it would not be; the original caller in to this path would be responsible
for determining that the candidate was not inserted then deleting it.
result[] was not referenced in other way during this flow.
This PR updates the chain to be of the form
bool <foo>(CallInfo& info, ResolutionCandidate* candidate);
The original caller inserts the accepted candidate in to the list of candidates[] or
deletes the …

Visible candidate

---

test/expressions/ferguson/if-expr/ifi.skipif
test/functions/deitz/nested/test_nested_var_iterator3.skipif

Remove skipifs for old futures

---

.travis.yml

Run the annotations checker and lookForBadAlloc script as part of travis
See https://github.com/chapel-lang/chapel/issues/6758 for context

Increase amount of travis testing

---

util/chplenv/chpl_home_utils.py
util/printchplenv

Infer CHPL_HOME in printchplenv and only print "*" if CHPL_HOME is explicitly
set.
Resolves https://github.com/chapel-lang/chapel/issues/4982

Have printchplenv infer CHPL_HOME

---

test/ANNOTATIONS.yaml

I've had an IOU to add these for far too long...  Track memory-related
ups and downs from the past month or so.

Add a number of memory leak annotations

---

util/cron/test-perf.chapcs.playground.bash

(following the suite of  #6816)

Test perf of forall-intent changes in perf playground

---

compiler/passes/parallel.cpp

PR #6877 added a new method to get the initialization point for a symbol, but left the old implementation in place (and asserted that the two matched). This PR simply removes the old implementation.
Passed quickstart+gasnet test/release/examples/primers

Cleanup get initialization

---

test/llvm/vectorization/simple_loop_novec.future

Make this test a .future to pass nightly testing

---

.gitignore
third-party/gmp/Makefile

Fix `make clobber` for gmp

---

util/test/paratest.chapcs

The comment clarifies the usage of the script.

Add a comment to paratest.chapcs

---

test/llvm/fast-flags/SKIPIF

Fixes a problem introduced in PR #6926. Thanks to @lydia-duncan for pointing out the issue.

Add a forgotten SKIPIF

---

test/ANNOTATIONS.yaml

- [chapcs](http://chapel.sourceforge.net/perf/chapcs/?startdate=2017/07/17&enddate=2017/08/11&graphs=arrayvectoroperations,jacobiemittedcodesize)
- Remove handling of references from copyPropagation (#6779)
-  Array as vector: Allow domains to implement specialized assignment (#6722)
- Array as vector: Regression:  This has proved tricky to track down / reproduce - not annotated for this PR.
- [16 node XC](http://chapel.sourceforge.net/perf/16-node-xc/?startdate=2017/07/23&enddate=2017/08/10&graphs=hpcchplreleaseperfgflopsn255nb32,hpccraonperfgupsn233nu10m,hpccrarmoperfgupsn233nu10m,hpccstreamepperfgbsn5723827200,hpccglobalstreamperfgbsn5723827200,hpccpromotedstreamperfgbsn5723827200,prkstencilvariationsperf,isxvariations)
- With comm=ugni, register large arrays dynamically (#6947)
- …

08/10/2017 Performance Annotations

---

compiler/resolution/functionResolution.cpp

Trivial :- Pull handling for a tryFailure out of resolveExpr()
Before this PR resolveExpr() was approximately 250 lines of text (3 - 4 screens full)
with somewhat convoluted control flow.
This is the first of a short sequence of simple PRs that will pull blocks of functionality
out of resolveExpr() and in to appropriate helper functions to reduce clutter and
expose the control/data flow. 
This PR extracts the code for handling a tryFailure in to a simple helper function.

Pull handling of tryFailure out of resolveExpr()

---

compiler/resolution/functionResolution.cpp

Continue trivial refactoring of resolveExpr()
1.  Co-locate implementation of issueCompilerError() near the single use within resolveExpr()
2. Extract the code for handling FLAG_DELAY_GENERIC_EXPANSION in to a helper
3. Extract the code for handling type constructors in to a helper
Standard compilation/testing protocol

Resolve expr 3

---

compiler/resolution/functionResolution.cpp

Continue trivial refactoring of resolveExpr()
1. Relocate isParamResolved() to be close to sole call site in resolveExpr()
2. A few "white space" adjustments
Conventional compilation/paratest protocol

Resolve expr 4

---

compiler/resolution/functionResolution.cpp

Continue with a sequence of trivial refactorings of resolveExpr()
1. Simplify the handling of an iteratedExpr within a Forall stmt
2. Extract the "second phase" of resolveExpr() to a new helper function
3. Cleanup resolveExpr() and resolveExprPhase2()
Conventional testing for compilation modes and correctness

Resolve expr 7

---

modules/internal/String.chpl

If chpl__deserialize is called on the same node as the string, then
return an unowned string alias instead of copying.
Move the '__serializeHelper' record outside of the string record to
avoid a string copy into the 'outer' field.
Testing:

Improve string serialization performance across local on-stmts

---

test/modules/packages/distributedIters/DistributedIters.chpl
test/modules/packages/distributedIters/perf/benchmarkDistributedIters.chpl
test/modules/packages/distributedIters/perf/benchmarkDistributedIters.perfexecopts

Updated performance tests for DistributedIters module for new distributed dynamic iterator. Compares between distributed-dynamic, -guided, and block-distributed default iterator. Includes NOTEST for now, but also perfexecopts and perfkeys for future reference.

DistributedIters dynamic performance tests draft.

---

tools/mason/Makefile
tools/mason/MasonBuild.chpl
tools/mason/MasonHelp.chpl
tools/mason/MasonNew.chpl
tools/mason/MasonUpdate.chpl
tools/mason/MasonUtils.chpl
tools/mason/mason.chpl

This PR adds the licenses to the source code of mason. I used the python script in util/buildRelease.

Added licenses to Mason src code

---

compiler/resolution/postFold.cpp

A second step towards straightening out postFold.
This PR makes trivial updates to postFoldMove() in order to
simplify/clarify the control flow.  Primarily a task of breaking
down a large unnecessarily convoluted function in to a smaller
set of helpers.
Passed conventional compilation/testing protocol.

Post fold 2

---

compiler/resolution/postFold.cpp

Continue to make small improvements to postFold for PRIM_MOVE
A few very minor clean up operations.
Conventional compilation/testing protocol

postFoldMove() :- Trivial clean up

---

compiler/AST/AstDumpToNode.cpp

Trivial format updates to a few forms in AstDumpToNode
Passed conventional compilation protocol and abbreviated testing.

Trivial tweaks to output of AstDumpToNode

---

compiler/resolution/functionResolution.cpp

Straight forward updates to the error print routines in functionResolution.cpp
Lydia proposed that I attempt to improve the output produced for
resolution failures with a focus on initializer misses.  While ramping up for
this I decided to make a trivial pass over printResolutionErrorAmbiguous()
and printResolutionErrorUnresolved().
Conventional compilation/testing protocol

Trivial cleanup for error print routines in functionResolution.cpp

---

test/parallel/taskCount/runningTaskCount/single-locale/begin.chpl
test/parallel/taskCount/runningTaskCount/single-locale/combined.chpl

Just wrap some begins with a sync

Fix some valgrind issues for newly added task-counting tests

---

modules/standard/IO.chpl

It wasn't that useful anyway and adds some noise to the code.

Remove _format_debug and associated formatted I/O debug printing

---

test/release/examples/benchmarks/isx/isx.chpl

Use a global domain instead of a local per-array domain now that serialization eliminates the overhead at scale.

Use global domain in ISx

---

.gitignore

... given that it's in CLEANFILES

Added .mason to .gitignore

---

util/cron/test-perf.chapcs.playground.bash

Test performance of inlining all direct iterators regardless of the number of
yields in them.

Test perf of inlining all direct iterators in perf playground

---

test/domains/vass/assoc-idxtype-error-2.chpl
test/multilocale/vass/this-in-taskfns-in-ctors.chpl

While there, updated comments in another test.

converted a test to initializers

---

test/modules/standard/Spawn/spawn-error.good
test/modules/standard/Spawn/spawn-error2.good

Forgot to update the good files on these tests. Thanks to @ronawho for catching this.

update spawn error good files

---

modules/dists/BlockDist.chpl
test/arrays/rankChange/distRankChangeAssign.bad
test/arrays/rankChange/distRankChangeAssign.future

Fix block rankchange bug

---

modules/packages/Collection.chpl
test/modules/packages/collections/CollectionBulk.chpl
test/modules/packages/collections/CollectionBulk.compopts
test/modules/packages/collections/CollectionBulk.skipif
test/modules/packages/collections/CollectionCounter.chpl
test/modules/packages/collections/CollectionCounter.compopts
test/modules/packages/collections/CollectionNQueens.chpl
test/modules/packages/collections/DequeOrdering.chpl
test/modules/packages/collections/DequeParity.chpl

PR to remove LICM concerns/bug notes, and revised units tests to no longer avoid triggering LICM bug.
Currently there is another bug exposed with nested declarations being hoisted?

GSoC Collections - LICM Changes

---

modules/packages/DistributedIters.chpl

Use a better heuristic for distributedDynamic's default localeChunkSize, and leave it as undefined in the documentation until we can find one backed by more experimentation.

Improve performance for distributedDynamic iterator

---

test/studies/graph500/v3/Graph500_Modules/BFS.chpl
test/studies/graph500/v3/Graph500_Modules/BFS_1D_onV.chpl
test/studies/graph500/v3/Graph500_Modules/Scalable_Graph_Generator.chpl
test/studies/graph500/v3/main.chpl

Some Block leaks still exist but I haven't been able to track them
down yet.

Close major leaks in Graph500 v3 code

---

test/studies/graph500/kristyn/Graph500_1D_onV/Graph500_Modules/BFS.chpl
test/studies/graph500/kristyn/Graph500_1D_onV/Graph500_Modules/BFS_1D_onV.chpl
test/studies/graph500/kristyn/Graph500_1D_onV/Graph500_Modules/Scalable_Graph_Generator.chpl
test/studies/graph500/kristyn/Graph500_1D_onV/main.chpl
test/studies/graph500/v2/BFS.chpl
test/studies/graph500/v2/main.chpl
test/studies/graph500/v3/Graph500_Modules/BFS_1D_onV.chpl

* propagate same changes from v3 to other active versions
* improve freeing of Level_Sets in v3 to free instances
on remote locales
TODO: We need to extend memleaks testing to better handle
multi-locale runs...

Close additional graph 500 leaks

---

doc/rst/developer/bestPractices/ContributorInfo.rst

Michael follows a different pattern than I do, so add his to the document as
well.

Add alternate rebase strategy, too, to ContributorInfo

---

compiler/optimizations/loopInvariantCodeMotion.cpp

Fix how we insert hoisted expressions into the pre-headers of loops. LICM
mostly operates on basic-blocks, but when we hoist invariant expressions we
need to hoist out of the loop AST. Previously, to find the loop AST we would
look at the header basic-block, grab the first expression, and walk up the
tree until we found the parent loop. However, since basic blocks aren't updated
with updates to the AST, this would mean that if we hoisted the first expr, the
next thing to be hoisted would be doubly hoisted.
In reality this never occurred because the first expression was always a
defExpr and LICM was mistakenly not hoisting defExprs before. #6692 starts
hoisting defExprs, and this PR is needed to avoid the double hoisting. This PR
just creates a reference to the loopAST when the basic-block …

Fix licm bug that could result in hoisting to the wrong loop

---

compiler/optimizations/loopInvariantCodeMotion.cpp

In LICM, hoist the defPoints of invariants if they are also within the loop.
In our plans to add GPU code generation, we want to automatically create GPU kernels from forall loops. In order to do so, we want to generate code such as: 
```
if (GPU requested) {
launch GPU kernel;
} else {
original CPU forall loop code;
}
```
However, to do so, we need to have the def points of invariants also moved up out of the loop, since our GPU loop creation pass is currently after optimizations have completed and we need to reference those variables.
More generally, this fixes a bug with LICM that is currently not surfacing. If you had code like:
```
for i in 1..10 {
var a: int;
a = 2;
b = a + a;
}
```
LICM would transform that into:
```
a = 2;
for i in 1..10 {
var a: int;
b = a + a;
}
```
This fix …

In LICM, hoist the defPoint of the invariant being hoisted

---

test/studies/IMSuite/vertexColor/vertexColoring-serial.chpl

Graph nodes needed to be freed at end of run.

Close memory leak for vertex coloring problem

---

test/npb/ep/mcahir/ep.chpl
test/studies/labelprop/labelprop-tweets.chpl
test/studies/lsms/shemmy/m-lsms.chpl

Clean up some additional tests

Clean up some miscellaneous user-level memory leaks

---

test/runtime/gbt/comm/bigTransfer.chpl

At least on 32-bit linux systems, the maximum allocation seems to be
1gb, not 2gb.  To reflect this, add a limiter based on the size of the
size_t type.

Adjust bigTransfer to not over-allocate on 32-bit systems.

---

test/deprecated/csr.good

Thanks @mppf for catching this.

Update line number in CSR deprecation test

---

doc/rst/platforms/cray.rst

Update the Cray platform documentation to reflect changes for configs
with CHPL_COMM=ugni and a hugepage module loaded.  Mainly the changes
have to do with array allocation and its side effect, the SIGBUS that
can result when we run out of memory allocating an array.  I also did
some minor rephrasing, changed `2^10` (bc(1) syntax?) to `2**10` (Chapel
syntax) for KiB etc., and (I hope) improved the discussion about why and
how to select a craype-hugepages module.  While here I also added a
mention of the Aries 64-bit real add disability, for completeness.

Update Cray platform documentation.

---

runtime/src/launch/slurm-srun/launch-slurm-srun.c

Fix a race in slurm-srun:determineSlurmVersion(). Previously we wrote the
contents of `sbatch --version` out to a tmp file and then read the file to
determine versions. Unfortunately, we used the same tmp file so this would
result in segfaults and other sporadic failures if 2 programs were running from
the same directory. While we run concurrent testing on crays, we use unique
subdirs so we haven't run into this in nightly testing. This was discovered by
the gasnet team's CI testing.
There's no reason to be using a tmp file anyways (this code was originally
copied from the slurm-gasnetrun_ibv launcher) so just use chpl_run_utility1K
instead. I copied the pattern we use in determineQsubVersion.
Note that slurm-gasnetrun_ibv and pbs-gasnetrun_ibv also need to be updated,
but I'll do that in …

Fix a race in our slurm-srun launcher while determining the slurm version

---

doc/rst/tools/mason/mason.rst
tools/mason/Makefile
tools/mason/MasonBuild.chpl
tools/mason/MasonHelp.chpl
tools/mason/MasonUpdate.chpl
tools/mason/MasonUtils.chpl
tools/mason/README.rst
tools/mason/mason.chpl

- Print error messages to stderr
- Consistent ordering of mason subcommands
- Remove some commented-out code
- Add some missing documentation

Tidy up Mason

---

doc/rst/technotes/localeModels.rst

This removes the multi-ddata discussion from the Performance
Considerations section, and substitutes a discussion of recent work to
allocate arrays separately.

Update locale models doc to reflect recent work.

---

runtime/src/launch/slurm-gasnetrun_ibv/launch-slurm-gasnetrun_ibv.c

Same as #7441, but for slurm-gasnetrun_ibv instead of slurm-srun. You can
really tell how much our launchers are clones of each other when the version
number function was still called `determineQsubVersion()`
I just copied the determineSlurmVersion() code from slurm-srun, and removed
some checks for nccs/torque, which were leftover from when this was copied from
the qsub version.

Fix race in slurm-gasnetrun_ibv launcher while determining the slurm version

---

modules/Makefile
modules/internal/ChapelError.chpl
modules/internal/fixInternalDocs.sh

This PR adds chpldoc documentation for the ChapelError module.
Reviewed by @psahabu.

Add internal types Errors documentation

---

doc/rst/technotes/initializers.rst
modules/internal/ChapelError.chpl

Fixi typos

---

doc/rst/technotes/initializers.rst

Update doc/rst/technotes/initializers.rst
1. Add a new section 'Order of Initialization' that helps to motivate the
subsequent discussion of phase 1 and phase 2.
2. Update subsequent portions of the text to meet the 80 column goal to
the extent practical.

Add a section 'Order of Initialization' early in the document

---

doc/rst/meta/primers/index.rst
doc/rst/technotes/errorHandling.rst
test/release/examples/primers/Makefile
test/release/examples/primers/README
test/release/examples/primers/errorHandling.chpl

with @mppf
- overhauls the technote to be in line with current release
- creates a primer to give a brief overview of error handling features

Updating the error handling documentation

---

test/release/examples/primers/errorHandling.good

Trivial, not reviewed. Updates a .good file only.

Fix errorHandling.good to match adjustments to the primer

---

test/release/examples/primers/Makefile
test/release/examples/primers/README

as requested by @awallace-cray 
Verified updated files since last release are reflected in README.
Verified 'make' in primers directory completes successfully.

Update primers readme, Makefile

---

test/release/examples/primers/Makefile

As requested by @awallace-cray

Add LinearAlgebralib to primers/Makefile

---

doc/rst/developer/chips/10.rst
doc/rst/technotes/reduceIntents.rst

Bringing it up-to-date with the current master and the current thinking.
For example, all Open Issues that were listed there are resolved
right now, so I removed them.
While there, touched CHIP 10 to follow up on Lydia's feedback on #7477
by adding another "must" and re-filled that paragraph.

Update the tech note on reduce intents

---

test/arrays/elliot/maximalUintArray.future
test/release/examples/benchmarks/lulesh/lulesh.execenv
test/release/examples/benchmarks/miniMD/explicit/miniMD.execenv
test/release/examples/benchmarks/miniMD/miniMD.execenv
test/types/range/elliot/rangeLength/rangeLengthOverflow.future

JIRA 160 => #7533
JIRA 161 => #7530
JIRA 162 => #7531

Update stale jira references for issues that have been migrated to github

---

test/CC-GRAPHFILES

New test was missing from CC-GRAPHFILES.

Add a new test that was missing from CC-GRAPHFILES

---

modules/standard/Spawn.chpl
test/modules/standard/Spawn/ugni/spawn-system.chpl
test/modules/standard/Spawn/ugni/spawn-system.fork.good

Updates some comments and updates the .good file as well. (A previous update had left the .good file incorrect).

Move refs to JIRA issue 133 to GitHub issue #7550

---

util/pastPerformance/testReleasesPerformance
util/test/perf/perfgraph.js

testReleasesPerformance
perfgraph.js

Post-release 1.16.0: update perf metadata.

---

test/classes/bradc/arrayInClass/genericArrayInClass-real.chpl
test/distributions/diten/Cyclic.chpl
test/distributions/diten/Dimensional.chpl
test/distributions/diten/testCyclic.chpl
test/domains/diten/assocDomIntersect.chpl
test/sparse/CS/multiplication/performance.chpl
test/studies/hpcc/STREAMS/bradc/stream-block1dclass.chpl
test/studies/hpcc/common/bradc/BradsBlock1D.chpl

Close a number of memory leaks in user-level code that represent the top of our second tier of leakers.

Close a series of reasonably obvious user-level memory leaks

---

test/modules/packages/Crypto/saru/kdf/pbkdf2-2.good

PR #7559 added a line to the test before the expected error but failed to
update the .good file.

Update line number in .good for test pbkdf2-2

---

test/types/range/vass/writeranges-1.future

I happened to notice that Brad's recent PR resolved a future.
Convert the future to a passing test

Convert a passing range alignment future to a passing test

---

compiler/passes/normalize.cpp

While pulling on threads associated with uses of default type constructors I tripped over
fixup_array_formals() in normalize.cpp.  While it was possible to see roughly what it was
doing, it was hard to understand what it was really doing.  I spent a little time to be able
to read it and then applied that to a simple refactoring that, I believe, makes it more
straight forward to read.
This PR does not affect behavior.  It implements these changes as a series of small
changes to simplify any effort to verify the correctness of the transformations.
Passed a small portion of release/ in all configurations.  Passed full paratest
with futures for both single-locale and --no-local.

Fixup array formals

---

compiler/passes/normalize.cpp

Begin to simplify normalize::fixupQueryFormals()
An early sub-pass of normalize transforms procedure
formals with query terms e.g.
proc foo(x : ?t, y : t) { ... }
The compiler function fixupQueryFormals() has
two completely different behaviors
1) For parameterized primitives e.g
proc +(a: int(?w), b: int(w)) return __primitive("+", a, b);
the chapel function is replaced with new functions in
which 'w' is instantiated with the valid value i.e.
proc +(a: int( 8), b: int( 8)) return __primitive("+", a, b);
proc +(a: int(16), b: int(16)) return __primitive("+", a, b);
proc +(a: int(32), b: int(32)) return __primitive("+", a, b);
proc +(a: int(64), b: int(64)) return __primitive("+", a, b);
Note again that the source chapel function is deleted as
part of this transformation.
2) In all other …

Extract handling of parameterized primitives from fixupQueryFormals

---

STATUS.devel

Removes types/enum/sungeun/cast_enum_weird_4.future and
types/enum/diten/enumDeclInFn.future

Remove tests from STATUS.devel that I fixed yesterday

---

compiler/resolution/wrappers.cpp

wrap 2 :- continue to split wrappers in to manageable blocks of code
On master buildWrapperForDefaultedFormals() is nearly 400 lines
of somewhat tortuous code. This PR breaks this down to 7 more
manageable functions.
This factoring was developed on a separate branch with extensive
testing.  This PR applies that update in a relatively large number of
commits to help clarify the trivial transformations that are being
applied.
Ran a small portion of release/ for each config.
Passed single-locale paratest with futures on gcc/linux64
Passed paratest with futures and --no-local on gcc/linux64
Verified mem-leaks are unchanged (code includes uses of initCopy/autoCopy)

Wrappers 2

---

test/classes/ferguson/dynamic-cast-generic-insn.chpl
test/classes/ferguson/dynamic-cast-generic-insn.good

@daviditen pointed out that the example code in this issue is now passing, thanks!
This PR just adds the test so the functionality doesn't regress.
See also issue #6051.

Add the test from issue #6051

---

util/cron/test-linux64-vm.bash

Test results will just be sent to me, this is just to test the machine out.

Add a duplicate linux64 test config to see how it runs on a new VM

---

modules/packages/Crypto.chpl

As discussed [here](https://github.com/chapel-lang/chapel/pull/7560) and [here](https://github.com/chapel-lang/chapel/pull/7390).

Change return type of EVP_CIPHER_CTX_init

---

compiler/codegen/expr.cpp

The test test/arrays/elliot/nearMaximalUintArray.chpl was failing with
LLVM compilation because of a bug in how Chapel was generating
getelementptr instructions.
The relevant case is something like this:
%eptr = getelementptr inbounds i64, i64* %ptr, i8 %idx
According to the LLVM IR manual, such a GEP should sign-extend %idx
to the size of the pointer. But in the case of nearMaximalUintArray.chpl,
we need it to zero extend instead.
Since LLVM IR integer types do not differentiate between signed and
unsigned, solving this problem amounts to adding a sign/zero extend in
the Chapel code generator, where we know whether the index is signed or
not. I accomplished that by creating a new function in codegen/expr.cpp,
extendToPointerSize, and calling it in select places.
In order to prevent …

Fix sign/zero extending for LLVM GEP instructions

---

compiler/include/llvmUtil.h
compiler/util/clangUtil.cpp

The current master branch of LLVM, which is a pre-release form of LLVM 6, included some trivial changes that prevented our front-end from building. This PR updates our code to compensate.
Reviewed by @dmk42 - thanks!

Add support for building with current LLVM master

---

test/studies/sudoku/dinan/sudoku-simple.compopts
test/studies/sudoku/dinan/sudoku-smart.compopts

We started observing the same symptoms as in #7602 
in two other sudoku tests. I am applying the same solution
here as Ben did there.

Added .compopts just like #7602

---

modules/packages/DistributedIters.chpl

Two assert messages named the serial iterator instead of the iterator kind they're in.

correct distributedDynamic debug statements

---

util/devel/test/vagrant/fedora-27-cloud-base/Vagrantfile

I wanted to check if Fedora 27 comes with LLVM 4 (it does not), so I created this Vagrantfile.
Reviewed by @awallace-cray - thanks!

Adds a fedora 27 vagrantfile

---

compiler/passes/normalize.cpp

Continue to refactor the normalization of calls to Constructors and to TypeConstructors
Tweak isCallToTypeConstructor() to scan a little better.
Limited testing with each config
Passed full paratest with -futures

normalize new expr :- tweak isCallToTypeConstructor()

---

compiler/resolution/resolveFunction.cpp

Continue to refine resolveFunction() et al
Minor updates to resolveFormals().
Compiled with the conventional configurations.  Passed a single-locale paratest.

resolveFunction :- simplify resolveFormals()

---

compiler/resolution/resolveFunction.cpp

Continue to refine resolveFunction() et al
Minor updates to updateIfRefFormal().
Compiled with the conventional configurations. Passed a single-locale paratest.

Refine resolveFunction.cpp :- Refine updateIfRefFormal()

---

compiler/resolution/resolveFunction.cpp

Continue to refine resolveFunction() et al
Minor updates to resolveSpecifiedReturnType().
Compiled with the conventional configurations. Passed a single-locale paratest.

Refine resolveFunction.cpp :- Refine resolveSpecifiedReturnType()

---

compiler/resolution/resolveFunction.cpp

Continue to refine resolveFunction() et al
Before this PR, protoIteratorClass() was about  1.5 pages of slightly
convoluted code that included subtle/hidden data flow dependencies.
This PR partitions this function in to a handful of simple functions that
clarify the business logic.
Ran a portion of release for each configuration.  Passed a single-locale paratest.

Resolve function 8

---

compiler/resolution/resolveFunction.cpp

Continue to refine resolveFunction.cpp et al
This PR simplifies the resolveFunction() itself with
a focus on extracting the handling of constructors
and the default type constructor.
Compiled with/without CHPL_DEVELOPER on clang/darwin
and gcc/linux64.
Ran a portion of release for each configuration.
Passed a single-locale paratest.

Resolve function 9

---

test/parallel/forall/reduce-intents/ri-a1-ident-ref-ret.chpl
test/parallel/forall/reduce-intents/ri-a1-ident-ref-ret.good

In addition to testing 'const' identities that `identity` returns by const ref, also test 'var' identities that `identity` returns by ref.

beef up the ri-a1 test

---

tools/chplvis/DataModel.cxx
tools/chplvis/Event.h
util/devel/lookForTabs

Update lookForTabs to use 'git grep' instead of 'find -exec grep', and to also
search for tabs in the tools/ directory.
Removed a few tabs from chplvis source files.

Update look for tabs

---

runtime/etc/Makefile.include
util/config/compileline

While there, added options to clarify C vs C++ compile commands. They are a potential solution to issue #7666.
Reviewed by @ronawho and @ben-albrecht - thanks!

Rewrite compileline in Python

---

util/cron/syncPerfGraphs.py

We've had a few cases where our perf graphs have failed to sync to dreamhost.
The failures seem to be sporadic and resolve quickly, so retry 5 times with a
30 second delay to hopefully minimize the number of sync failures we see.
If this isn't enough time, we can always switch to an exponential backoff
scheme, but I'm keeping it simple to start.

Retry performance graph sync a few times

---

doc/rst/technotes/libraries.rst

This is a documentation update missed in PR #7814.

Compileline compile c++ docs

---

runtime/src/comm/ugni/comm-ugni.c

This improves the performance of PRK stencil and the scalability of Stream
global. Both now perform on par with the reference up to at least 256 nodes.
Previously, when ugni did a remote fork it would do a chpl_task_yield() while
waiting for an ACK from the remote locale. This allowed the local computation
to run and starve the forking task until the long running local computation was
done. What ended up happening for prk-stencil and stream-global is that:
1) locale 0 would do a local task-spawn and queue the tasks for the kernel
2) locale 0 would do a remote task-spawn to locale 1
3) locale 0 would yield while waiting for an ACK back from locale 1
4) locale 0 was allowed to run the tasks queued for the local kernel in step 1
5) locale 0 finishes the kernel, finally resumes spawning …

Stop doing a task-yield while forking remote tasks under ugni

---

compiler/resolution/functionResolution.cpp
compiler/resolution/preFold.cpp
compiler/resolution/tuples.cpp

Tweaks for defaultTypeConstructor
Thie PR rolls up a handful of trivial commits
that simplify functions that interact with
defaultTypeConstructor.
Compiled with/without CHPL_DEVELOPER on
clang/darwin and gcc/linux64.  Tested each
configuration on a portion of release/
Passed multiple paratests while developing
the code for these commits.  Passed a final
paratest with -futures

Type constr

---

modules/internal/String.chpl

Strings should take ownership of buffers during construction even if the buffer begins with a null-terminator.
Testing:

Fix string leak for zero-length c_strings

---

compiler/resolution/virtualDispatch.cpp

Continue to make modest improvements to virtualDispatch.cpp
A short sequence of trivial commits to break the obvious
sub-passes out from resolveDynamicDispatches().

Virtual dispatch 2

---

test/classes/initializers/compilerGenerated/arrayField-compInit.bad
test/classes/initializers/generics/typeAlias.bad
test/classes/initializers/generics/typeFunctions/fnReturnsConcrete.bad

Update these .bad files after the locale model initializer change this morning

---

compiler/resolution/virtualDispatch.cpp

Continue to make modest improvements to virtualDispatch.cpp
A small sequence of commits to simplify addToVirtualMaps()

Virtual dispatch 4

---

compiler/resolution/virtualDispatch.cpp

Continue to make modest improvements to virtualDispatch.cpp
Continued simplification of addToVirtualMaps();

Virtual dispatch 5

---

compiler/resolution/virtualDispatch.cpp

Continue to make modest improvements to virtualDispatch.cpp
Extract primary helpers from resolveOverride()

Virtual dispatch 6

---

test/arrays/ferguson/semantic-examples/1-return-promoted-expr.bad
test/arrays/ferguson/semantic-examples/1-return-promoted-expr.chpl
test/arrays/ferguson/semantic-examples/1-return-promoted-expr.future
test/arrays/ferguson/semantic-examples/1-return-promoted-expr.good
test/arrays/ferguson/semantic-examples/valgrind-futures/4-return-promoted-expr-local.chpl
test/arrays/ferguson/semantic-examples/valgrind-futures/4-return-promoted-expr-local.future
test/arrays/ferguson/semantic-examples/valgrind-futures/4-return-promoted-expr-local.good
test/arrays/ferguson/semantic-examples/valgrind-futures/4-return-promoted-expr-records.chpl
test/arrays/ferguson/semantic-examples/valgrind-futures/4-return-promoted-expr-records.future
test/arrays/ferguson/semantic-examples/valgrind-futures/4-return-promoted-expr-records.good

These futures investigate returning a promoted expression.
Test changes only - not reviewed.

Add futures for issue #7994

---

compiler/AST/AggregateType.cpp

Begin to update dispatchParents[]
While working on virtualDispatch.cpp I was reminded of the current
problems with Vec<Type*> Type::dispatchParents.
As far as I can tell this should be
std::vector<AggregateType*> AggregateType::dispatchParents.
Take a step in this direction by eliminating the indirect coupling
between AggregrateType::toSuperField() and dispatchParents[].
Compiled with/without CHPL_DEVELOPER on clang/darwin and
gcc/linux64. Ran a portion of release/ for each configuration.
Passed a single-locale paratest with -futures.

dispatchParents :- Minor update for AggregateType::toSuperField()

---

modules/packages/SharedObject.chpl
test/library/packages/SharedObject/shared-nil-assign.chpl
test/library/packages/SharedObject/shared-nil-in-arg.chpl
test/library/packages/SharedObject/shared-nil-return.chpl

In some cases involving `Shared(nil)` objects, `Shared` was calling `retain()`
on `nil`.  Fix it by testing for `nil` before calling `retain()`.
Add 3 tests that made `nil` dereferences before this change but pass now.

Fix `nil` dereferences from `Shared(nil)` objects

---

test/types/records/init/condFieldInit.bad
test/types/records/init/condFieldInit.future
test/types/records/init/condFieldType.bad
test/types/records/init/condFieldType.future

These tests were resolved by #8033 but I didn't notice they got resolved before
merging.

Remove .bad and .future for now passing tests

---

compiler/include/typeSpecifier.h

Fix typos in typeSpecifier.h

---

doc/rst/developer/chips/20.rst
doc/rst/developer/chips/README.md

I've rewritten it to focus more on examples & describing what's going wrong in the examples. It sketches some solution ideas but doesn't go very in depth on them.

Rewrite CHIP 20 to focus on function hijacking

---

doc/rst/developer/chips/20.rst

CHIP 20: Formatting, correction in Overloads section

---

doc/rst/developer/chips/20.rst
test/chplvis/README

Fix typos in chip 20 and chplvis README

Fix typos in chip 20 and chplvis README

---

util/devel/chplspell-dictionary

chpspell dictionary updates

---

modules/standard/Path.chpl
test/library/standard/Path/victor-ludorum/joinPath/testcases.chpl
test/library/standard/Path/victor-ludorum/joinPath/testcases.good

Adding **joinPath()** function to **path.chpl** file . This function is helpful in joining path names . 
@lydia-duncan Kindly review this , references #6012 and suggest necessary changes

joinPath() function issue #6012

---

compiler/resolution/functionResolution.cpp

Minor tweaks to resolveNewHandleConstructor()
I am starting to look at the code for resolving each variation
for PrimNew.
This PR makes a few trivial adjustments to the path for
legacy class/records that continue to rely on constructors
to aid my evaluation.
Compiled with/without CHPL_DEVELOPER on clang/darwin
and gcc/linux64.  Tested each configuration on a portion of
release.  Passed a paratest with futures.

Prim new constr

---

test/classes/initializers/generics/typeFunctions/fnReturnsGeneric.bad

Updated a .bad for #8125

---

util/devel/test/vagrant/chapelbranch.sh

Minor fix in vagrant script

---

modules/internal/ChapelArray.chpl
test/domains/userAPI/isEmptyTestDomain.chpl
test/domains/userAPI/isEmptyTestDomain.good

With reference to  #7721, I made the pull request, its my first PR on Chapel, if there is any changes (I suppose tests, but I found the necessary test at  test/domains/claridge/DomainIsEmpty.chpl) then please tell me.

Add _domain.isEmpty() procedure

---

test/domains/claridge/DomainIsEmpty.future

Removes the .future now that #7721 is resolved

Retire DomainIsEmpty future test

---

spec/Classes.tex
spec/Generics.tex
spec/Records.tex

This is a proposed specification change to go along with PR #7672.

Proposed spec change for param/type fields accessible from type

---

spec/Data_Parallelism.tex
spec/Procedures.tex

See also issues #7868, #7889.
This is a follow-on to PR #7858.

Update spec about default args, promotion

---

.github/ISSUE_TEMPLATE.md

Ask issue filers: "Is this a blocking issue with no known work-arounds?"

Ask if issue is blocking users on GitHub issue template

---

compiler/optimizations/remoteValueForwarding.cpp

PR #8073 migrated an auto-destroy for coforall index variables
to the task function. If the task function is also an on, there
might be RVF and serialization occurring. For the following two
tests, that was causing a yielded domain to be destroyed twice.
studies/hpcc/STREAMS/bradc/stream-block1dpar-arr
studies/hpcc/STREAMS/bradc/stream-block1dpar
To fix the issue, this commit adjusts insertSerialization to
explicitly handle the case in which an argument is destroyed
in the task function. If the argument is still passed in some
form, it will still be destroyed there. If the argument is no
longer passed (which is the case when there isn't a runtime type),
instead destroy the index variable immediately after the
serialize call.
The adjustment adds asserts to check that the auto-destroy
call …

Adjust RVF serialize/deserialize for new auto destroy placement

---

runtime/src/mem/jemalloc/mem-jemalloc.c

Instead of a boolean for `have_fixed_comm_layer_heap` add an enum to track `FIXED`,
`DYNAMIC`, and` NONE`.
The only functional difference is that we won't do an "initial" setup
allocation after initializing the shared heap for the DYNAMIC case.

Cleanup how we detect the shared heap type in jemalloc shim

---

doc/rst/developer/chips/20.rst

@lydia-duncan and I have been improving this CHIP.

Edit CHIP 20 further

---

runtime/src/comm/ugni/comm-ugni.c

Every time the polling task handles a request it has to respond to the
initiator.  It may need to release the remote-fork request buffer the
initiator used and/or it may need to send a "done" indication to the
initiator.  In the past the polling task has used synchronous PUTs for
these, that is, it did a PUT and then waited for the network response
before continuing.  That has the advantage that if an error occurs
either in the network or at the remote node, the polling thread will
kill the job before starting any other work.  However, it also reduces
the polling thread's throughput because at least one network round-
trip latency must pass between when the polling task finishes handling
one request and starts handling the next.
Here, switch to handling request reponse completions …

Do nonblocking responses in the polling task

---

doc/rst/developer/chips/23.rst

Introduce Chip 23 to provide supporting material for the new initializer proposal

Introduce Chip23

---

doc/rst/developer/chips/23.rst

Chip 23 :- Fix simple logic error

Chip23 :- Fix simple logic error

---

runtime/src/comm/ugni/comm-ugni.c

We have long limited the number of uGNI comm domains we use to 30.  This
number was chosen for the original comm-ugni implementation, and was
appropriate at that time since the Gemini chip only has 32 NIC tiles.
We didn't update it when Aries arrived, although that chip has 128 NIC
tiles.  For a long time this was not a problem, since we didn't have
compute nodes with enough processors to use more than 30 comm domains.
(Generally speaking one only needs as many comm domains as one has CPUs
to initiate transactions on them.)  But with the advent of 36-core
compute nodes in Aries-based systems that's no longer true.
Here, up the limit on uGNI comm domains to 120 for Aries-based systems.
In order to make this work with the remote fork request indexes sent via
the remote CQ mechanisms, I also …

Use up to 120 comm domains on Aries-based systems

---

modules/internal/ChapelError.chpl
modules/packages/BLAS.chpl

Continues the effort of removing try! and halt from our modules where possible.

Remove try! and halt from BLAS module

---

compiler/AST/AggregateType.cpp
compiler/AST/FnSymbol.cpp
compiler/AST/type.cpp
compiler/include/AggregateType.h
compiler/include/FnSymbol.h
compiler/include/type.h
compiler/passes/InitNormalize.cpp
compiler/passes/normalize.cpp

Begin to integrate recent initializer work to master
I have developed a branch with a number of updates to support migration to the
new initializer proposal. This is the first of a handful of PRs to merge that code to
master.
This PR integrates a few trivial "helper" functions and some "while there" cleanup
that was performed along the way.
Compiled with/without CHPL_DEVELOPER on clang/darwin and gcc/linux64.  Tested
on a small portion of release/ for each configuration.  Also verified with CHPL_LLVM=llvm
on linux64.
This code has been tested extensively in the context of the development branch.
Passed a single-locale paratest

Init prop 1

---

compiler/passes/normalize.cpp

Continue to merge initializer code to master
This PR introduces a first implementation of postInit() for the new proposal.  If a record or
a class hierarchy defines a postInit() then it will be invoked.  This start point does not
include a thoughtful implementation for "compiler generated" implementations of
postInit(). This was tested extensively on my first development branch when I tried to
implement phase 2 behavior using postInit() rather than initDone() but in the short term
this is a lower priority behavior.
Compiled/smoke-tested on the common configurations.  Passed a full single-locale
paratest.

init-proposal :- Introduce support for postInit()

---

compiler/include/InitNormalize.h
compiler/include/initializerRules.h
compiler/passes/InitNormalize.cpp
compiler/passes/initializerRules.cpp

Continue to merge initializer branch to master
This PR introduces the basic support for detecting initDone().  Also removes 1 version of code
that was replicated (as statics) in two different files.
Compiled/tested with expected configurations.
Passed a single-locale paratest

init-proposal :- Introduce support for initDone()

---

compiler/passes/InitNormalize.cpp

Continue to merge initializer branch to master
This PR tweaks a portion of the normalization of class/record fields.
Compiled with expected configurations and each configuration was
tested on a small portion of release/
Passed a single-locale paratest

init-proposal :- Tweak field normalization

---

doc/rst/developer/chips/23.rst

Update the Chip for the initializer proposal to better match the latest view of this work.

chip23 :- Update the chip to match recent work

---

test/types/records/init/record-with-record-param.chpl
test/types/records/init/record-with-record-param.future
test/types/records/init/record-with-record-param.good

Add the future test/types/records/init/record-with-record.param.chpl

Add future for a record with a param record field

---

doc/rst/developer/bestPractices/GeneratedCode.txt
doc/rst/developer/bestPractices/TestSystem.rst
doc/rst/technotes/dsi.rst
doc/rst/tools/chpldoc/chpldoc.rst
doc/rst/usingchapel/tasks.rst
man/chpl.rst
man/chpldoc.rst
modules/packages/LAPACK.chpl
spec/Data_Parallelism.tex
test/reductions/thomasvandoren/test/TestScanCountsInherit.future
test/reductions/thomasvandoren/test/TestScanCountsInherit.good
test/release/examples/primers/chpldoc.doc.chpl
test/studies/HDFS/tzakian/multiloc/README.csep524.multiloc
third-party/libhdfs3/README
util/README
util/test/checkChplInstall

Fix assorted dead links

---

test/ANNOTATIONS.yaml

Sorry for the delay @chapel-lang/perf-team.
- all: Change default intent for range to const in (#8368)

perf annotations, 2/15

---

test/performance/comm/low-level/remote-fetchAmos.ml-perf.graph

In the last commit of #8520, I failed to add one file.  Do so now.

Add a file left out of #8520.

---

runtime/src/comm/ugni/comm-ugni.c

Add an option to have the polling thread block until an active message arrives
instead of actively polling for one. Specifically, instead of doing CqGetEvent
with a sched_yield() when there's no event just do CqWaitEvent.
The current polling scheme creates a significant amount of contention for any
task running on the same core as the polling thread. This is particularly
harmful to benchmarks like ISx, where performance is limited by the slowest
task.
Using CqWaitEvent requires that we create the CQ with GNI_CQ_BLOCKING. Creating
a CQ with GNI_CQ_BLOCKING does add some extra latency/overhead between when an
event arrives and when we can find out about it. This can unfortunately
increase the latency for AMs. This only seems to impact micro-benchmarks, but
we need to do some more …

Add an opt-in mechanism to reduce contention from ugni's polling thread

---

test/users/Deeksha96/StringAlgorithms.chpl
test/users/Deeksha96/testStringAlgorithms.chpl

This pull request is in reference to the issue #8271 
Please have a look and suggest any changes required.

String max-min rotation added

---

util/chplenv/chpl_home_utils.py
util/run-in-venv.bash

Use the new common helper routines added in #8661

Stop hard-coding path to virtualenv dir in ./run-in-venv

---

compiler/include/files.h
compiler/passes/docs.cpp
compiler/util/files.cpp

Use the new common helper routines

Stop hard-coding path to virtualenv dir in the chpldoc code

---

doc/rst/users-guide/TODO

This is a minor set of edits to the users guide plan that I've had sitting around for awhile.

Mark requested topics for users guide as such

---

test/ANNOTATIONS.yaml

- [16 node XC](https://chapel-lang.org/perf/16-node-xc/?startdate=2018/02/22&enddate=2018/03/08&suite=performancetracking)
- 3/1 system update - impact observed on 3/4
- [chapcs](https://chapel-lang.org/perf/chapcs/?startdate=2018/02/22&enddate=2018/03/08&graphs=hpccratime,arrayviewcreation,arrayvsddataserialaccesses,jacobiemittedcodesize,fannkuchreduxn12,stringtemporarycopies,passingandreturningstrings,searchesovernstrings)
- Many regressions on 3/3 due to #8547

Perf Triage Annotations for 3/8

---

test/studies/shootout/reverse-complement/bradc/revcomp-blc.chpl

This is a variation of bharsh's mark-skip-read-begin version of revcomp which strives to clean up some of the control flow and use more const variables; it also handles empty files without problems.

Variation on bharsh's mark-skip-read-begin version of revcomp

---

compiler/resolution/functionResolution.cpp

Continue to adjust the resolution of PRIM_NEW
Before this PR there were two helper functions that handled two variations on
generic functions.  These functions are reasonably large/complex and are almost
identical.
This intermediate PR merges these two functions together.
Passed limited testing for each configuration.
Passed single-locale paratest with -futures

ResolveNew :- Merge the two functions that handle new exprs for "generic" functions

---

compiler/resolution/lowerIterators.cpp

* Do not insert 'blockStmt' into the AST just to remove it immediately after. In expandRecursiveIteratorInline().
* Collect only CallExprs, not all ASTs, because only CallExprs are used. In expandBodyForIteratorInline().

Remove some not-needed AST operations

---

compiler/util/clangUtil.cpp

This PR adjusts our integration with clang so that it
only uses public clang API functions for clang >=6.
For earlier clang versions, we needed to use internal
clang headers in order to perform two operations.
Reviewed by @dmk42 - thanks!

integration with clang >= 6 uses only public API

---

compiler/codegen/expr.cpp

PR #8194 changed codegenFieldPtr in a way that
inadverdently broke --llvm-wide-opt.
In --llvm-wide-opt mode, wide pointers are represented
as address-space-100 pointers in the LLVM IR, so they
are still subject to GEP / load / etc.
codegenFieldPtr was using Type* castType for two purposes:
1. to compute the GEP offset to use
2. to cast the type to.
For --llvm-wide-opt mode, the first use needed to
use a "wide pointer" so it would code generate to
an address-space-100 pointer. But the second use
needed the non-wide pointer, since the wide pointer
doesn't actually contain the field.
This commit addresses this problem by moving some
fLLVMWideOpt conditionals later in the code. The
change to when ret.isLVPtr is set seems more correct
since base might have be modified after this condition
in …

Fix --llvm-wide-opt after PR #8194

---

modules/internal/String.chpl
test/types/records/ferguson/assert-locale-record/myrecord.chpl
test/types/records/ferguson/expiring-value-alias.chpl
test/types/records/ferguson/must-init-record/myrecord.chpl
test/types/records/ferguson/self-pointer-record/myrecord.chpl
test/types/records/ferguson/tracking-record/myrecord.chpl

It was pointed out that these comments all refer to a future that has since been
resolved.  Remove the comments.
Resolves #8509

Remove comment about resolved future

---

doc/rst/usingchapel/compiling.rst

Document the chpl-completion.bash script in usingchapel/compiling.

Add documentation for chpl tab autocompletion script

---

compiler/resolution/lifetime.cpp

Fix typos in lifetime.cpp

---

doc/rst/technotes/dsi.rst

This PR updates the DSI technote to describe the bulk-transfer interface defined in #5310.

Document Bulk-Transfer Interface

---

compiler/AST/build.cpp
compiler/parser/parser.cpp
compiler/resolution/functionResolution.cpp
compiler/resolution/implementForallIntents2.cpp
compiler/resolution/resolveFunction.cpp
compiler/util/files.cpp
doc/rst/developer/adding-a-tasking-model.txt
modules/internal/DefaultRectangular.chpl
modules/standard/IO.chpl
test/Samples/README
test/release/examples/primers/parIters.chpl
third-party/README
third-party/llvm/README
third-party/llvm/unpack-llvm.sh

Fix more dead links.
Reviewed by @ben-albrecht.
Passed full local futures testing.

Dead links

---

third-party/chpl-venv/Makefile
third-party/chpl-venv/Makefile.include
third-party/chpl-venv/test-requirements-python2.txt
third-party/chpl-venv/test-requirements.txt
third-party/chpl-venv/virtualenv.txt
util/chplenv/chpl_python_version.py

#8850 failed post-merge smoke tests. Going to revert, and debug those post-release.

Revert #8850

---

CONTRIBUTORS.md

This is the CONTRIBUTORS.md file for Chapel 1.17, reflecting those who I believe have contributed code that will appear in the release tarball / module since Chapel 1.16.

CONTRIBUTORS.md for Chapel 1.17

---

doc/rst/technotes/initializers.rst

Reviewed by @benharsh, @bradcray, @lydia-duncan

Update the initializers tech note

---

doc/rst/technotes/initializers.rst

Tried to rephrase this text to make postinit in 1.17 seem less like something that's barely working and more like something that adds value and seems to be working as we'd expect.  Other minor local tweaks while here.

Further wordsmithing of the postinit section

---

test/GRAPHFILES
test/Samples/Performance/cleanCopy/foobar.chpl
test/Samples/Performance/cleanCopy/foobar.execopts
test/Samples/Performance/cleanCopy/foobar.good
test/Samples/Performance/cleanCopy/foobar.graph
test/Samples/Performance/cleanCopy/foobar.perfkeys

This adds a sample performance test, to reference from the TestSystem.rst
documentation updates

Add a sample performance test

---

util/pastPerformance/testReleasesPerformance
util/test/perf/perfgraph.js

Ref https://github.com/chapel-lang/chapel/issues/8979

Release 1.17.0: update testReleasesPerformance

---

compiler/optimizations/remoteValueForwarding.cpp

Minor removal of seemingly-obsolete code.
Convert 'ref' intent to 'in' intent of the formal that underwent RVF.
Testing:

tidy up in remoteValueForwarding

---

doc/rst/developer/bestPractices/TestSystem.rst

Fix typos in TestSystem.rst

---

util/dockerfiles/Dockerfile
util/dockerfiles/gasnet/Dockerfile

Cherry-pick #9108 from master branch to release/1.17 branch

Docker images should have test-venv

---

compiler/codegen/codegen.cpp

Fix LLVM smoke tests after PR #8982.
Trivial bug fix, not reviewed.
Passed full local --llvm testing.

Fix LLVM smoke tests after PR #8982

---

util/config/compileline

Fix typos and spacing issues compileline help messages

---

util/printchplenv

Fix a couple typos in printchplenv help messages

---

modules/dists/BlockCycDist.chpl
modules/dists/BlockDist.chpl
modules/dists/CyclicDist.chpl
modules/dists/DimensionalDist2D.chpl
modules/dists/ReplicatedDist.chpl
modules/dists/SparseBlockDist.chpl
modules/dists/StencilDist.chpl
modules/internal/ChapelError.chpl
modules/internal/DefaultRectangular.chpl
modules/internal/String.chpl
modules/layouts/LayoutCS.chpl
modules/packages/Buffers.chpl
modules/packages/Crypto.chpl
modules/packages/DistributedBag.chpl
modules/packages/DistributedDeque.chpl
modules/packages/Sort.chpl
modules/standard/DateTime.chpl
modules/standard/List.chpl
test/deprecated/error-msg-removed.chpl
test/deprecated/error-msg-removed.good
test/deprecated/error-msg-removed2.chpl
test/deprecated/error-msg-removed2.good

Update module docs to mention initializers instead of constructors

---

util/cron/test-perf.chapcs.playground.bash

Devs - feel free to grab perf playground when desired.

Test no-ref-temps in perf playground

---

test/types/tuple/sungeun/hetTupleWithArrayInitWithType.future
test/types/tuple/sungeun/hetTupleWithArrayInitWithType.skipif
test/types/tuple/sungeun/hetTupleWithDomainInitWithType.future
test/types/tuple/sungeun/hetTupleWithDomainInitWithType.skipif

Un-future hetTupleWith{Array,Domain}InitWithType

---

compiler/resolution/lowerForalls.cpp

Add comments with more details on certain aspects of lowerForalls.
While there, add details for task-private variables for #9487.

Expand top-level comments for lowerForalls

---

modules/packages/Crypto.chpl
test/library/packages/Crypto/saru/aes/aesTest1.chpl
test/library/packages/Crypto/saru/blowfish/bfTest1.chpl
test/library/packages/Crypto/saru/blowfish/bfTest2.chpl
test/library/packages/Crypto/saru/hashing/hash1.chpl
test/library/packages/Crypto/saru/hashing/hash2.chpl
test/library/packages/Crypto/saru/hashing/hash2.good
test/library/packages/Crypto/saru/kdf/pbkdf2-1.chpl
test/library/packages/Crypto/saru/kdf/pbkdf2-2.chpl

As suggested here, https://github.com/chapel-lang/chapel/issues/9491
cc/ @daviditen

Added enums as a mode of selection for cipher variations.

---

util/build_configs.py

Minor updates and improvements to util/build_config.py
Noticed while working https://github.com/chapel-lang/chapel/issues/9551

build_config.py: add --dry-run, --llvm=system, fix CHPL_HOME default

---

compiler/codegen/expr.cpp
compiler/optimizations/deadCodeElimination.cpp
compiler/resolution/resolveFunction.cpp

Reverts chapel-lang/chapel#9586

Revert #9586 "Preserve non-ref type for ref-intent formals"

---

test/users/npadmana/mpi/test_mpi.skipif

As recommended [here](https://github.com/chapel-lang/chapel/pull/9560#issuecomment-391231126)
TODO: apply this also to the tests in library/packages/MPI?

Update skipif to enforce fifo tasking, at Nikhil's recommendation

---

util/test/sub_clean

Correct and improve the comment (c is the file, not f),
and rename f to d since it's a directory.

Clean up sub_clean's cleanCleanfiles

---

test/classes/ferguson/generic-type-method-simple1.bad
test/classes/ferguson/generic-type-method-simple2.bad
test/classes/ferguson/generic-type-method-simple3.bad
test/classes/ferguson/generic-type-method-tuple.bad
test/classes/initializers/noReturnInInit.bad
test/functions/bradc/resolution/smallIntParamCoerce.bad
test/regexp/elliot/I-fail-without-re2.bad
test/types/records/bharshbarger/remoteBlankRecord.bad
test/types/records/bharshbarger/remoteInRecord.bad
test/users/ferguson/int32method.bad

.bad files should only exist when there is a corresponding .future.  Remove
them otherwise.

Remove .bad files with no corresponding .future files

---

test/library/standard/DataFrames/psahabu/FilterNoIndexSeries.bad

#9696 changed the printing format of Series, but did not fix the underlying issue of the future. Updating the .bad file to reflect this.

fix FilterNoIndexSeries.bad

---

modules/dists/SparseBlockDist.chpl

Some of my changes during development of PR #9677 caused problems with
this code (when changing scope resolution for the this type for primary
methods to make them more like secondary methods). Since nested classes
are not working well with initializers, it seems smart to avoid using
nested classes in module code at this point. For this reason, this PR
moves TargetLocaleComparator to a standalone record outside of
SparseBlockDom.
Passed full local testing and gasnet testing.

Move TargetLocaleComparator out of class SparseBlockDom

---

test/reductions/partial/DRimpl.chpl

This re-enables testing of DRimpl.chpl. The changes are:
* Create an honest ReduceOp for the composite reduction.
* Avoid memory leaks.
What was leaking was the array returned by PartRedOp.generate()
before I switched that to returning by ref. TODO: why?
TODO remains: need major changes related to PartRedOp.generate():
* Support the case where perElemOp.generate() is something other
than identity, by executing it on every element of PartRedOp.value
and returning the result.
* Support the case where the output type != the accumulation type.
This is probably the same as the previous bullet.
* On the contrary, fully support the case where where perElemOp.generate()
returns identity, by avoiding any processing at all by PartRedOp.generate().
This is for performance.

Re-enable testing of partial reductions over DR

---

doc/rst/developer/adding-a-launcher.rst
doc/rst/developer/bestPractices/launcherInterface.rst

As part of investigating a Urika-specific launcher in #9668, I documented the launcher interface.

Add short document describing launcher interface

---

test/compflags/ferguson/unstable-class.compopts
test/compflags/ferguson/unstable-class.init.good

Add second compilation configuration with slightly different output under initializers.

Update undecorated class warning test for initializers

---

runtime/src/topo/hwloc/topo-hwloc.c

PR #9862 broke on macOS because hwloc_get_proc_cpubind() returns "not
supported" there.  Allow for that, basically ignoring CPU binding on
that platform.  This will at least get release/examples and the smoke
testing working again.  Afterward I'll look further into whether we
need to support the notion of accessible-vs-not on macOS.

Allow for hwloc_get_proc_cpubind() not supported on macOS.

---

runtime/src/comm/ugni/comm-ugni.c

Avoid a remote memory region lookup for network atomics
This passes the `remote_mr` to `do_nic_amo()` instead of having `do_nic_amo()`
perform the lookup itself. The remote address must be registered in order for
us to do a network atomic, which means we're already doing a lookup beforehand.
This just saves the result of the `mreg_for_remote_addr()` that we're doing
beforehand and passes it along to `do_nic_amo()`.
Roughly speaking this transforms:
```c
if (mreg_for_remote_addr(obj, loc) == NULL)
do_fork_amo(...);
else
do_nic_amo(...);  // was doing mreg_for_remote_addr() itself
```
into:
```c
mem_region_t* remote_mr;
if ((remote_mr = mreg_for_remote_addr(obj, loc)) == NULL)
do_fork_amo(...);
else
do_nic_amo(..., remote_mr); // _not_ doing mreg_for_remote_addr()
```
In practice, I don't …

Avoid a remote memory region lookup for network atomics

---

test/types/void/param-return-void.bad
test/types/void/param-return-void.chpl
test/types/void/param-return-void.future
test/types/void/param-return-void.good

This is a future for issue #9152

Future for returning _void from branches

---

test/mason/subdir-commands/PREDIFF
test/mason/subdir-commands/PREEXEC

This PR should make the recently merged sub-directory PR pass testing without any noise thanks to @ronawho

Quiet testing noise from ill-formed sed command

---

third-party/hwloc/README
util/chplenv/chpl_3p_hwloc_configs.py

I've forgotten to update this list the last couple times I upgraded hwloc, so
update it now. Also add upgrading instructions to the hwloc README like we have
for hwloc/gasnet and make sure the instructions mention the whitelist
Closes https://github.com/chapel-lang/chapel/issues/9950

Update the hwloc whitelist

---

modules/standard/IO.chpl
spec/Iterators.tex

* Update as-arrays example in spec to show promotion to array 
* Update typo in openwriter docs 
Verified the adjusted spec test passes.
Resolves #9993.

Fix two documentation issues

---

test/visibility/scoping-shadows-error-message.bad
test/visibility/scoping-shadows-error-message.chpl
test/visibility/scoping-shadows-error-message.future
test/visibility/scoping-shadows-error-message.good

Add a test demonstrating the request for a better use-before-def error message

---

runtime/src/tasks/qthreads/tasks-qthreads.c

This resolves a sporadic hang during qthread's `chpl_task_exit()`. Before this
types/tuple/diten/tupleComparisons.chpl would hang once every ~25,000 trials,
but with this PR it passed 1,000,000 trials
In the qthreads shim, the canexit sync variable is used as part of teardown in
`chpl_task_exit()`, where we currently do a `qthread_syncvar_fill()` from a
non-qthread. Qthreads has support for performing syncvar operations from a
non-qthread by creating a temporary qthread to do the operation. For some
reason `qthread_syncvar_fill()` does this through a syncvar_nonblocker_func
which does not wait for the sync operation to complete before returning as
opposed syncvar_blocker_func which does wait for the sync operation to complete
before returning.
For some reason that I don't totally …

Convert the canexit syncvar_t in the qthreads shim to an aligned_t

---

util/buildRelease/install.sh

Resolves #10093
Thanks to @PHHargrove for finding this problem and suggesting the fix.

Add fixpath.py to make install

---

test/mason/mason-test/.mason.NOTEST

change mason start_test file from `.mason.NOTEST` to `.mason.notest`

Mason: NOTEST -> notest

---

test/studies/lulesh/release-valgrind/lulesh-sedov15oct.good

Remove unused file
test/studies/lulesh/release-valgrind/lulesh-sedov15oct.good
This file was orphaned by dac6ebe

Remove unused lulesh/release-valgrind/lulesh-sedov15oct.good

---

modules/standard/ChapelHaltWrappers.chpl

Halt wrapper for https://github.com/chapel-lang/chapel/issues/10192

Add an exhaustiveSelectHalt wrapper

---

runtime/src/tasks/qthreads/tasks-qthreads.c

Document why we call qthread_initialize() in a separate pthread (Greg and I
were often confused about the motivation for this, so I figured I'd write it
down now that we understand some of the reasons.) From the new comments:
```c
// We call this routine in a separate pthread for 2 main reasons:
// 1) qthread_initialize() converts the current thread into a shephered (the
//    "real mccoy" shepherd) and creates a qthread on top of that. If we called
//    this from the main process we'd have to be very careful about using
//    pthread mutexes, sched_yield, and other similar constructs that don't
//    play well with qthreads in the rest of the runtime. That's a lot of
//    effort and easy to forget about, so we want to avoid that.
//
// 2) qthread_finalize() only does anything when …
```

Document why we call qthread_initialize() in a separate pthread

---

compiler/resolution/functionResolution.cpp

* Allow resolveFieldSymbol() to work on an already-resolved
PRIM_SET_MEMBER. While there, refactor the code for clarity.
* Fix removeRandomPrimitive() as follows.
removeRandomPrimitive() removes certain PRIM_SET_MEMBER calls.
Due to #10132, the calls that already included a correct field Symbol
were sheltered from such removal. This PR un-shelters them.

Improve resolution of PRIM_SET_MEMBER

---

modules/standard/IO.chpl
test/io/ferguson/error-invalid-channel.chpl
test/io/ferguson/error-invalid-channel.close.good
test/io/ferguson/error-invalid-channel.execopts
test/io/ferguson/error-invalid-channel.write.good

Throw for some operations on invalid channel

---

modules/standard/Types.chpl
test/modules/bradc/printModStuff/foo.good
test/modules/sungeun/init/printModuleInitOrder.good
test/modules/vass/deinit-order-modules.verbose.good

Closes https://github.com/chapel-lang/chapel/issues/9837

Convert halts in safeCast() to safeCastCheckHalt wrappers

---

compiler/AST/AstDump.cpp
compiler/AST/view.cpp
compiler/include/AstDump.h
compiler/passes/scopeResolve.cpp
compiler/resolution/implementForallIntents.cpp
compiler/resolution/lowerForalls.cpp
test/classes/delete-free/owned/forall-shadow-vars.chpl
test/classes/delete-free/owned/forall-shadow-vars.good

Forall shadow variable is a borrow by default when the outer variable is owned or shared.

foralls capture owned/shared as borrows by default

---

modules/internal/OwnedObject.chpl

We will revisit the question of copy-initializer and ref-intent at a later time.
Testing:

Convert 'owned' to use initializers

---

test/GRAPHFILES
test/studies/bale/toposort/toposort.chpl
test/studies/bale/toposort/toposort.execopts
test/studies/bale/toposort/toposort.perf.graph
test/studies/bale/toposort/toposort.perfcompopts
test/studies/bale/toposort/toposort.perfexecopts
test/studies/bale/toposort/toposort.perfkeys
test/studies/bale/toposort/toposort.time.graph

This adds the Bale Toposort benchmark, includes it in regression tests and performance tests.
resolves #10210

Bale-Toposort Benchmark (Serial, Shared Memory Parallel)

---

modules/standard/IO.chpl
test/io/ferguson/string-style-with-length-error.chpl
test/io/ferguson/string-style-with-length-error.good

Convert halts in IO.chpl to halt wrapper call, assert, or throw

Convert halts in I/O

---

compiler/passes/insertLineNumbers.cpp
modules/internal/ChapelError.chpl
test/memory/psahabu/lineno-memLeaks.prediff

This PR addresses baseline failures after PR #10295
and adjusts insertLineNumber to be more readable and maintainable.

Further line number improvements

---

modules/standard/BigInteger.chpl

Test Documentation for proc bigint.divexact(const ref n: bigint, const ref d: bigint)  created.

Document bigint.divexact

---

compiler/resolution/functionResolution.cpp

Follow-on to PR #10393 to avoid make-time warnings with clang.
Verified Hellos pass on OS X.

Remove collectVisibleMethodsNamed

---

test/visibility/generated-assignment.chpl

Add reproducer that #10512 fixed

---

doc/rst/usingchapel/prereqs.rst
util/chplenv/compiler_utils.py

After #10506 , add the Allinea compiler to two additional locations.

Allinea follow-up

---

modules/packages/DistributedBag.chpl
modules/packages/DistributedDeque.chpl
modules/packages/TOML.chpl
modules/standard/Barriers.chpl
test/classes/diten/deleteobject.chpl
test/compflags/ferguson/default-unmanaged.default.good
test/exercises/boundedBuffer/solutions/boundedBuffer-atomic.chpl
test/types/typedefs/lydia/def-new-on-type-alias.chpl
test/users/ferguson/module_new.chpl

Fix tests identified by PR #10568 that should be using unmanaged.

Unmanaged deletes

---

modules/dists/CyclicDist.chpl
modules/packages/AllLocalesBarriers.chpl
test/classes/delete-free/lifetimes/borrow-escapes.chpl
test/classes/diten/reassign_outer.chpl
test/classes/ferguson/generic-inherit3.chpl
test/classes/ferguson/generic-inherit4.chpl
test/parallel/forall/task-private-vars/records.chpl
test/release/examples/benchmarks/miniMD/helpers/initMD.chpl
test/release/examples/benchmarks/shootout/binarytrees.chpl
test/release/examples/benchmarks/shootout/chameneosredux-fast.chpl
test/release/examples/programs/genericStack.chpl
test/release/examples/users-guide/taskpar/walkTreeUsingBegins.chpl

Fixes problems with --warn-unstable and deleting borrowed.
Relevant to PR #10568.

More warn-unstable updates

---

modules/standard/Types.chpl
test/library/standard/Types/is-owned-shared-unmanaged.chpl
test/library/standard/Types/is-owned-shared-unmanaged.compopts

Add isOwnedClass/isSharedClass/isUnmanagedClass/isBorrowedClass
At first I thought these would be important to get DimensionalDist2D to
work with owned. That turned out not to be the case, but I believe they
should be added for completeness.

Add isOwnedClass etc

---

compiler/resolution/implementForallIntents.cpp

Ensure that in- and ref-intent shadow variables
have a value type (not ref type) from the beginning,
i.e. from when they are resolved.
Not reviewed.

Force val types for shadow vars

---

compiler/passes/normalize.cpp
test/expressions/if-expr/unexpected-AST.chpl
test/expressions/if-expr/unexpected-AST.good

This fix by @benharsh  resolves a minor issue with resolving IfExprs.
It was triggered by the added test, which is not meaningful in itself.

Fix a minor issue with IfExpr

---

runtime/src/comm/ugni/comm-ugni.c

Previously, we incorrectly counted GNI_POST_AMO as part of rcvd_bytes because
it fell into an else branch. Now we only track PUT/GET FMA/RDMA operations.
This also adds a helper function for that logic partially to simplify call
sites and partially to eliminate branches that aren't needed when perfstats
aren't enabled (although the compiler probably optimized these away anyways)

Fix rcvd_bytes and sent_bytes performance counters in ugni

---

util/build_configs/.gitignore
util/build_configs/README.md
util/build_configs/build_configs.py
util/build_configs/functions.bash
util/build_configs/module-functions.bash
util/build_configs/setenv-example-1.bash
util/build_configs/setenv-example-2.bash
util/build_configs/setenv-example-3.bash

A realistic Chapel configuration for Cray-XC systems.
Implements https://github.com/chapel-lang/chapel/issues/10461

build_configs: add setenv-example-3.bash (#9551)

---

test/types/records/tupleFields/detupleFieldDecl.future

Add issue numbers to
test/types/records/tupleFields/detupleFieldDecl.future

Add issue numbers to detupleFieldDecl future

---

test/studies/comd/elegant/arrayOfStructs/util/AccumStencilDist.chpl
test/studies/comd/elegant/arrayOfStructs/util/EAM.chpl
test/studies/comd/elegant/arrayOfStructs/util/Potential.chpl
test/studies/comd/elegant/arrayOfStructs/util/Simulation.chpl
test/studies/comd/llnl/CoMD.chpl
test/studies/comd/llnl/utils/force.chpl
test/studies/comd/llnl/utils/forceeam.chpl
test/studies/comd/llnl/utils/forcelj.chpl
test/studies/comd/llnl/utils/helpers.chpl
test/studies/comd/llnl/utils/setup.chpl

Updates both CoMD implementations to use unmanaged.
Not sure why earlier efforts to migrate code missed these.
Reviewed-ish by @benharsh - thanks!

Use unmanaged in comd

---

util/devel/test/vagrant/README-distro-timelines.txt
util/devel/test/vagrant/netbsd-NetBSD-7.0/Vagrantfile
util/devel/test/vagrant/provision-scripts/netbsd-pkgin-deps.sh
util/devel/test/vagrant/ubuntu-bionic64/Vagrantfile

* Update a README
* add a NetBSD 7 vagrant config
* adds an Ubuntu 18.04 "Bionic Beaver" 64-bit vagrant config
Reviewed by @awallace-cray - thanks!

Update distro timelines, add NetBSD and Ubuntu 18.04

---

runtime/src/comm/ugni/comm-ugni.c

A few misc cleanups to ugni NIC atomics that I noticed while working on
buffered atomics cleanups:
- Move NIC AMO sanity checks to a helper function
- Move size, alignment, and registration checks to a helper function to
avoid code duplication. Also add these checks to buffered atomics.
* Cleanup NIC AMO spacing/formatting
* Move amo perfstats_inc to a common location, and unify alignment of some
assignment statements for setting up the post AMO post descriptors.
* Switches the NF operand casting to use a ternary operator and more
importantly corrects the operand casting for the buffered NF case.
Previously, we always casted to a 64 bit type, which was wrong for 32 bit
operations.

Cleanup ugni NIC atomics

---

test/mason/mason-update-toml-error/mason-chpl-version-update.chpl
test/mason/pkgconfig-tests/pcTest.chpl
test/mason/spack-integration/mason-external.good

A few post #10862 fixes caught in nightly testing.

Mason refactor fix

---

modules/Makefile
modules/packages/BufferedAtomics.chpl

Closes https://github.com/chapel-lang/chapel/issues/10845

Add documentation for Buffered Atomics

---

modules/packages/BLAS.chpl
test/library/packages/LinearAlgebra/correctness/no-dependencies/no-flags/no-flags.chpl
test/library/packages/LinearAlgebra/correctness/no-dependencies/promotion-flattening.chpl

After #10929, users should not need to throw extra flags such as `--set blasImpl=none` when compiling a `LinearAlgebra` program with no BLAS calls and no BLAS headers available, such as this example:
```chpl
use LinearAlgebra;
var A = Matrix(3,3);
```
However, the module-level `checkBLAS()` call introduces the `cblas.h` dependency back into all programs compiling with `BLAS`, requiring `--set blasImpl=none` to compile programs like the one above.
This PR removes the `checkBLAS()` call restoring behavior back what #10929 originally set out to do.
AFAIK, the `checkBLAS()` procedure was developed primarily as a debugging tool to
roughly check the compatibility of an underlying BLAS implementation
based on defined constant values. There's no great reason this call should
remain in the …

Drop checkBLAS call from BLAS module

---

modules/internal/OwnedObject.chpl
modules/internal/SharedObject.chpl
modules/internal/fixInternalDocs.sh
test/classes/delete-free/error-owned-record.good
test/classes/delete-free/error-shared-record.good
test/classes/ferguson/delete-free/owned-error-nonclass.good
test/classes/ferguson/delete-free/shared-error-nonclass.good
test/deprecated/owned-shared-from-borrow.chpl

Updates Owned and Shared documentation to be reasonable given the recent language changes.

Fix owned shared chpldocs

---

test/release/examples/benchmarks/miniMD/helpers/forces.chpl
test/release/examples/benchmarks/miniMD/helpers/initMD.chpl
test/release/examples/benchmarks/miniMD/miniMD.chpl

This is not a major change or win, but nice to use the managed
class features.

Switch miniMD over to use managed classes

---

util/devel/chplspell
util/devel/chplspell-dictionary
util/devel/chplspell-dictionary.fileids.json

chplspell dictionary update.  Add NetCDF.chpl to skip list.

chplspell dictionary update.  Add NetCDF.chpl to skip list.

---

test/arrays/ferguson/from-iterator/for-yields-no-arrays.good

Apparently I also got the .good wrong in #11043.
Fixing it here.

Adjust .good for a working test

---

test/deprecated/override-warning.chpl
test/deprecated/override-warning.good

Adds a test to test/deprecated to remind us about issue #11069.

File to remind us about issue 11069

---

doc/rst/language/evolution.rst

Documents, at a very high level:
* initializers
* delete-free changes
* override

Language Evolution Updates

---

CONTRIBUTORS.md

I was surprised that two schools would have such similar acronyms and didn't spend as much time Googling as I should have.

Fix confusion on my part about IIIT-Hyderabad vs. IIT-Hyderabad

---

doc/util/versionButton.php

That'll teach me to try and comment my code...

Fix comment style from # to //

---

compiler/passes/buildDefaultFunctions.cpp
modules/dists/CyclicDist.chpl
test/classes/initializers/records/generics/explicitAssignment.good
test/compflags/lydia/noUseNoinit/recordIncorrectAssignment.good
test/expressions/lydia/noinit/recordIncorrectAssignment.good
test/types/records/ferguson/default-compare-mixed-insn.1.good
test/types/records/ferguson/default-compare-mixed-insn.2.good
test/types/records/ferguson/default-compare-mixed-insn.3.good
test/types/records/ferguson/default-compare-mixed-insn.4.good
test/types/records/ferguson/default-compare-mixed-insn.5.good
test/types/records/ferguson/default-compare-mixed-insn.6.good
test/types/records/ferguson/default-compare-mixed-insn.chpl
test/types/records/ferguson/default-compare-mixed-insn.compopts
test/types/records/ferguson/default-compare-mixed-insn.prediff
test/types/records/init/generic/mismatch2.bad
test/types/records/init/generic/mismatch2.future
test/users/engin/partial_reduction_support/modules/dsiMethods.chpl

Don't allow assign/==/!= between different record instantiations

---

compiler/optimizations/loopInvariantCodeMotion.cpp

* removes trailing whitespace
* creates a function to apply LICM to just one FnSymbol

Clean up spacing in LICM

---

test/studies/bale/indexgather/ig.ml-perf.graph
test/studies/bale/indexgather/ig.ml-time.graph

Was mistakenly graphing histogram instead of indexgather

Fix bale indexgather graphs

---

doc/util/versionButton.php

Make Chapel 1.18 the "current" release for online docs

---

doc/util/versionButton.php

This reverts commit f15c2a4657ae16e9d5a91080ac2927fcdadec7af.

Revert "Make Chapel 1.18 the "current" release for online docs"

---

modules/standard/DateTime.chpl

Remove a workaround for issue #5267, fixed in PR #5952.

Remove a bug workaround from the DateTime module

---

test/types/records/init/init-post-postinit.bad
test/types/records/init/init-post-postinit.chpl
test/types/records/init/init-post-postinit.future
test/types/records/init/init-post-postinit.good

Belatedly add future for #8991

Add future about calling init/postinit post-initialization

---

modules/internal/ChapelRange.chpl
test/types/range/memberDiffStrides.bad
test/types/range/memberDiffStrides.future

Un-futurize the test added in #11230 .

Fix a bug in range.member(range)

---

CONTRIBUTORS.md

Follow-on to PR #11025.
Delhi is the way the university web site https://iiitd.ac.in/ spells it.

Dehli -> Delhi in CONTRIBUTORS.md

---

compiler/passes/resolveIntents.cpp

Addresses reference to closed issue #5266 pointed out in #11215.

Tidy up blankIntentForThisArg

---

test/optimizations/copyPropagation/cp-problem2.bad
test/optimizations/copyPropagation/cp-problem2.chpl
test/optimizations/copyPropagation/cp-problem2.future
test/optimizations/copyPropagation/cp-problem2.good

See the test and #11312 for details.

Add a bug future for #11312

---

test/library/packages/Sort/RadixSort/distSortEg.chpl
test/library/packages/Sort/RadixSort/distSortEg.good
test/library/packages/Sort/RadixSort/flagsort.chpl
test/library/packages/Sort/RadixSort/flagsort.good
test/library/packages/Sort/RadixSort/flagsortMSB.chpl
test/library/packages/Sort/RadixSort/simpleMerge.chpl

This PR adds an in-place most-significant-digit first radix sort and an example of distributed sorting.

added distributed sort example and flagsort MSB

---

compiler/codegen/expr.cpp

This is a follow-on to PR #11367.

Fix compiler build issue with system llvm

---

modules/internal/ChapelArray.chpl

... when capturing a range-shaped iterable into an array.
When invoking `proc chpl__initCopy(ir: _iteratorRecord)` on a
range-shaped `_iteratorRecord`, that range is known since #10942.
Therefore we know how many elements we are going to get, so we can
allocate a _ddata with that many elements up front, without the need
to resize it as the elements come in.
While there:
* factor out the calls to __primitive("array_alloc"),
* remove a stray comment - OK-ed by DavidI.
Testing: linux64; valgrind.

Allocate full-length ddata at once

---

util/test/send_email.py

This change allows `send_email.py` to use an authenticated TLS SMTP
connection if new cmdline parameters `--smtp-user` and
`--smtp-password` (and/or the corresponding environment variables)
are given by the caller.
The default behavior has not changed: if no smtp options are given,
the script will attempt to make an unencrypted, unauthenticated SMTP
connection to `localhost`.
This change implements just enough SMTP flexibility to meet
Cray-internal requirements.

send_email.py can use authenticated TLS SMTP connection

---

test/exercises/boundedBuffer/boundedBuffer.chpl
test/exercises/boundedBuffer/solutions/boundedBuffer-atomic.chpl
test/exercises/boundedBuffer/solutions/boundedBuffer-sync.chpl

This makes them all more similar and minimal in terms of their use
of managed types

Minor refresh to bounded buffer codes

---

test/exercises/c-ray/solutions/c-ray-1.chpl
test/exercises/c-ray/solutions/c-ray-1a.chpl
test/exercises/c-ray/solutions/c-ray-2.chpl
test/exercises/c-ray/solutions/c-ray-2a.chpl
test/exercises/c-ray/solutions/c-ray-3.chpl
test/exercises/c-ray/solutions/c-ray-3a.chpl
test/exercises/c-ray/solutions/c-ray-4.chpl
test/exercises/c-ray/solutions/c-ray-4a.chpl
test/exercises/c-ray/solutions/c-ray-5.chpl
test/exercises/c-ray/solutions/c-ray-6.chpl
test/exercises/c-ray/solutions/c-ray-7.chpl
test/exercises/c-ray/solutions/c-ray-8.chpl

Whoops, got caught by surprise by this one until post-merge spot-checking.
Sorry for the additional PR.

Switch c-ray from .member to .contains

---

test/GRAPHFILES
test/exercises/c-ray/old/c-ray.perfcompopts

In reorganizing the directories in hopes of cleaning things up, I
forgot that this was a performance test, so broke the paths.
Sorry for the noise.

Fix c-ray perf test

---

test/types/records/lydia/recordOffset-classField.skipif
test/types/records/lydia/recordOffset-cstringField.skipif
test/types/records/lydia/recordOffset-generic.skipif
test/types/records/lydia/recordOffset-stringField.skipif
test/types/records/lydia/recordOffset.skipif

I'm going to write something that would incorporate the different output for 32
bit systems on Monday (I'm too lazy to do that on my weekend)

Skip these tests on 32 bit systems for now

---

runtime/src/comm/ugni/comm-ugni.c

Rename some variables and rework some control flow paths to make this
code a little easier to follow for people who aren't already familiar
with the code. This is cleanup based on my experience with first
learning this code, but it's taken me a while to PR it.

Make some readability improvements to the ugni fetching amo code

---

highlight/highlight/langDefs/chpl.lang

+ Add binary and octal integers.
+ Allow underscores in numbers
- This doesn't support hexadecimal floating point right, but no worse than
it was previously

Update highlight syntax highlighter

---

compiler/AST/LoopStmt.cpp
compiler/codegen/CForLoop.cpp
compiler/codegen/DoWhileStmt.cpp
compiler/codegen/LoopStmt.cpp
compiler/codegen/WhileDoStmt.cpp
compiler/include/LoopStmt.h
compiler/resolution/lowerIterators.cpp

It's a lot less common with the third e.

Spell vectorizable with only two e's

---

compiler/resolution/functionResolution.cpp

Init some internal-module global variables early
When a global param in an internal module has a simple initializer
or a global type alias is for a simple type, allow them to be used
even before their declarations would be resolved according to the
standard resolution order.
"Obvious" cases are, for example:
```chpl
param localeModelHasSublocales = false;
type chpl_table_index_type = int;
```
This change eliminates the need to tune the placement of global params
within the internal modules, which we had to do in the past.
This was motivated by my upcoming work, where localeModelHasSublocales
needs to be referenced before its module gets resolved.
We could extend this feature to vars and consts, for example:
```chpl
var chpl__testParOn = false;
```
In addition to setting such a variable's …

Init some internal-module global variables early

---

test/ANNOTATIONS.yaml

- [meteor](https://chapel-lang.org/perf/chapcs/?startdate=2018/10/31&enddate=2018/11/16&graphs=meteorshootoutbenchmarkn2098) improvements (#11570)
- [array-view-creation](https://chapel-lang.org/perf/chapcs/?startdate=2018/10/31&enddate=2018/11/16&graphs=arrayviewcreation) stabilization (#11609)

Add perf annotations for 2018-11-29

---

runtime/src/tasks/qthreads/tasks-qthreads.c

We used to use the value of `CHPL_RT_CALL_STACK_SIZE` as the actual
value of the qthread stack size. However qthreads also has data
structures that it allocates next to stacks (guard pages, runtime data
structures for context switching) so in #10254 we starting using up some
of the user task space for these data structures so we could better pack
task stacks into hugepages. As a result of this, if the user set a
really low stack size, we could end up wrapping around when we subtract
the guard pages and telling qthreads to use ~MAX(size_t) sized stacks.
To remedy this, warn if there wasn't at least one page available for the
actual task stack and bump the size to ensure there is. This also rounds
the actual task stack up to the nearest page size.
For architectures with 4K pages, we were …

Warn if the call stack size is too small under qthreads

---

util/cron/test-perf.chapcs.playground.bash

Developers: feel free to take it over any time.

Perf playground to test reduce exprs

---

test/studies/shootout/spectral-norm/bradc/spectralnorm-blc.chpl

Goal: How much can we reduce CPU time by doing so?

Switch my study version of spectral norm over to a serial implementation

---

util/test/sub_test

Outline the check for known (Jira documented) failure modes and convert
it from a cascading if-stmt into an iterated search.  While here, add a
check for Jira 283.

Restructure known Jira checking and add a check for Jira 283.

---

runtime/src/comm/ofi/comm-ofi.c

comm=ofi has been supporting the interface for "fast" executeOns, but
running the actual on-stmt body functions in tasks just like regular
executeOns.  Here, call the on-body function directly from the AM
handler, like in a real comm layer.

Really support "fast" executeOn in comm=ofi.

---

runtime/src/comm/ugni/comm-ugni.c

This has a very slight performance improvement for buffered operations:
| test        | old      | new      |
| ----------- | -------- | -------- |
| histogram   | 362 MB/s | 365 MB/s |
| indexgather | 380 MB/s | 384 MB/s |
This also adds small wrappers for spinlock lock/unlock.

Use acquire/release memory orders for buffered AMO/GET locks

---

tools/mason/MasonUtils.chpl

Correction to #12043 caught in post-merge testing.

Mason: Fix SPACK_ROOT path

---

runtime/include/chpl-mem-desc.h
runtime/src/chplcast.c

Switch string->int casts to use chpl_mem_alloc/free instead of
chpl_malloc/free.

Switch from chpl_malloc/free to chpl_mem_alloc/free

---

runtime/src/comm/ugni/comm-ugni.c

Previously, we used a single spinlock to protect any access to the unordered op
linked lists. This meant there could only ever be a single reader or writer.
The buff-atomics-stress test does concurrent ops and flushes to stress the
implementation. Prior to #12113, there was no chain to protect, but adding the
chain meant each flush needs to acquire the list lock. By using a reader/writer
lock we can allow for multiple readers.
With this, the concurrent flushing test is nearly as fast as it was before.

Use a reader/writer lock to protect unordered op chains in ugni

---

compiler/resolution/callDestructors.cpp

This change prevented #12131 from merging into master, due to #12159.
Instead of muddying #12131 by pulling lots of master changes into it, I am merging this change separately.

Add missing change for #12131

---

compiler/AST/foralls.cpp

The processing done by labelSerialIterAsParallel(), added in #12131,
turns out to be unnecessary. Removing it.
Thanks @mppf for drawing my attention to this in his review.

remove labelSerialIterAsParallel()

---

runtime/src/comm/ugni/comm-ugni.c

Misc comment cleanups and speed improvements for ugni perfstats:
- Cacheline align/pad perfstat counters (improves perf)
- Switch 1B from UL to L (should have been done in 3decd4b218)
- Update timer cost comments. On 28-core BW `clock_gettime()` seems
to take ~420ns per call, not ~80. However, if we link dynamically
vDSO is used and each call is only ~15 ns. So far I haven't been
successful in doing static linking except for vDSO (which I think
just means dynamic libc)
Here's some quick timings for:
```c
for (int i=0; i<10000000; i++)
(void)clock_gettime(CLOCK_MONOTONIC, &tmp);
```
Compiled with `cc -O3 timer.c {-static, -dynamic}`:
| config   | time   | time/trial |
| -------- | ------ | ---------- |
| -static  | 4.17 s | 417 ns     |
| -dynamic | 0.15 s |  15 ns     |

Misc ugni perfstat improvements

---

util/build_configs/cray-internal/setenv-xc-x86_64.bash

See internal chapel-code 7523f52 for more info.

Bump our cce gen compiler for KNL to 8.7.3

---

doc/rst/meta/primers/index.rst
test/release/examples/primers/Makefile
test/release/examples/primers/README
test/release/examples/primers/specialMethods.chpl
test/release/examples/primers/specialMethods.good

This new primer goes over methods that have special meaning for classes and
records. Updated the Makefile and README to include the new file.

Add a primer going over special methods for classes and records

---

runtime/src/comm/ugni/comm-ugni.c

Simplify comm domain acquisition in ugni
Don't bother checking the cq_cnt or fork_request buffer before
acquiring a comm domain. It's an extra atomic op and we tend to run
with a thread per core so it's rare to run into cases where the cq_cnt
is high or where the fork_request buffer is already taken.
Basically we now just do a test-and-test-and-set lock to acquire a comm
domain. If we were able to acquire the comm domain, we then check the
cq_cnt and if needed look for a free request buffer. This logic is
easier to follow and I believe will be better for the common case.
With the code reduction, this makes acquire_comm_dom small enough to
inline.
If we wanted to we could also make the cq_cnt non-atomic now since we
only access it while the comm domain is acquired. I'm not sure that's
a …

Simplify how we acquire comm domains in ugni

---

compiler/passes/externCResolve.cpp

Fix compilation warnings in externCResolve

---

runtime/src/comm/ugni/comm-ugni.c

Make some minor cleanups and add some comments to our comm domain
alignment in ugni:
- Don't overalign the comm domain array
- Add a comment describing why padding/alignment is important
I do not expect this to have any performance impact
Related to https://github.com/chapel-lang/chapel/issues/11974

Minor cleanups to ugni comm domain alignment

---

modules/standard/Random.chpl
test/library/standard/Random/choiceTest.chpl
test/library/standard/Random/choiceTest.compopts
test/library/standard/Random/choiceTestErrors.chpl
test/library/standard/Random/choiceTestErrors.compopts

Added `Random.choice()`, which returns a random sample from an array.
The interface for `Random.choice()` was influenced by [`numpy.choice()`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.choice.html), as discussed in #9805.
Added a test, which confirms that the choice statistics are within 5% of the expected probabilities for 10000 choices. I've run this test for 1000 trials to confirm we won't be getting sporadic failures in nightly testing. Also added a test to confirm the error cases.
Additionally, fixed the documentation of a few `Random` procedures, which should say `defaultRNG` instead of `PCG`.
Future work could incorporate support for:
- complex and bigint types
- further optimizations
Closes #9805

Random.choice()

---

runtime/src/launch/slurm-gasnetrun_ibv/launch-slurm-gasnetrun_ibv.c

This is similar to https://github.com/chapel-lang/chapel/pull/950
There is no reason to be using an expect script, it was only used because the
launcher was ported from pbs-gasnetrun_ibv, which maybe required it. The expect
script added carriage returns, which meant you couldn't just use it under
start_test. It also obviously required expect, which is not available on all
systems (e.g. it's not available on internal Cray CS machines.)
Additionally the expect script merged stderr into stdout, so this is a
prerequisite for https://github.com/chapel-lang/chapel/issues/12259
This also quotes the env var propagation, which caused problems on systems
where there were env vars with special characters.
Testing (hellos+types/string/dmk/utf8_env):

Don't use expect script for slurm-gasnetrun_ibv launcher

---

test/classes/delete-free/lifetimes/forall-of-new-borrowed-escapes.bad

Though I thought I tested against futures a few days ago and saw
no problems, this one seems to have slipped past me.  Due to the
new loops I added, numbering for loop expressions changes, messing
up this .bad file.  Fix that.

Update .bad w.r.t. scan shape preservation fix

---

test/library/packages/csv/CSV.chpl

The error condition is known at compile-time,
so report it then, instead of waiting for execution.
Alas the read/write functions still throw,
because of cast during read() and because of
the underlying channel's write() during write().

Replace throws with compile-time errors in CSV

---

test/GRAPHFILES
test/scan/scanPerf.chpl
test/scan/scanPerf.good
test/scan/scanPerf.graph
test/scan/scanPerf.perfcompopts
test/scan/scanPerf.perfexecopts
test/scan/scanPerf.perfkeys

This adds a simple performance test of + scans on 1D arrays to see how the
performance differs as we improve scans.

Add a simple performance test of a + scan on a 1D local array

---

test/studies/bale/histogram/histo-atomics-forall-opt.ml-execopts
test/studies/bale/histogram/histo-atomics.ml-perf.graph
test/studies/bale/histogram/histo-atomics.ml-time.graph
test/studies/bale/indexgather/ig.ml-perf.graph
test/studies/bale/indexgather/ig.ml-time.graph

Fix multi-locale .graph files and .dat destination issues from #12269

Fix bale histogram and indexgather graphs

---

test/studies/bale/indexgather/ig.ml-perf.graph
test/studies/bale/indexgather/ig.ml-time.graph

Fix bale indexgather graphs (round 2)

---

doc/rst/technotes/extern.rst

Follow-on to PR #12156
Resolves #12220 

Update C interop technote for c_array, removal of extern classes

---

doc/rst/technotes/nilChecking.rst

Follow-on to PR #11238.
Resolves #11294.

Add an example to the nil checking technote

---

spec/Records.tex

Update Records section for =/==/!= being same-type

---

doc/rst/technotes/lifetimeChecking.rst

Follow-on to #11795 and #8673.

Add technote on lifetime checking

---

doc/rst/usingchapel/launcher.rst
doc/rst/usingchapel/tasks.rst

My ofi docs PR just now included some line break changes that should not
have been there.  Remove those.
And, while fixing these, I spotted a word ("If") I'd mistakenly removed
in that PR.  Restore that, too.

Fix a couple of flaws in my ofi doc PR just now.

---

CONTRIBUTORS.md

This is an update to the CONTRIBUTORS list to call out those developers who contributed to the code, documentation, and files that will appear in the 1.19 release.

Contributors list for Chapel 1.19

---

CHANGES.md

These are the CHANGES.md updates for Chapel 1.19

CHANGES updates for 1.19

---

test/release/examples/benchmarks/lulesh/README
test/release/examples/patterns/README
test/release/examples/primers/Makefile
test/release/examples/primers/README

Thanks to Karlon for catching these.

Add missing files to the test/release/* READMEs and Makefiles

---

doc/rst/technotes/lifetimeChecking.rst

Remove an unnecessary decl from lifetime checking technote

---

test/types/records/ferguson/expiring-value-alias.chpl
test/types/records/ferguson/expiring-value-alias.good

While there, update some comments to be more accurate

Free memory in expiring-value-alias test

---

compiler/main/version.cpp
compiler/main/version_num.h
man/confchpl.rst
man/confchpldoc.rst
test/compflags/bradc/printstuff/version.goodstart
test/compflags/bradc/printstuff/versionhelp.sh

I only updated where I had previously changed from 1.19.0 pre-release
to 1.19.0. Places where I had updated from 1.18.0 to 1.19.0 I have
left at 1.19.0.
Compared changes from #12584.

Update versioning to 1.20.0 pre-release.

---

test/arrays/shapes/visibility-error.chpl

Switched to default allocation to guarantee a free.

Close user-level leak in visibility-error.chpl test

---

doc/rst/developer/bestPractices/Deprecation.rst

- Include examples, with specific suggested wording
- Include info about deprecation tests

Update deprecation documentation

---

test/compflags/ferguson/unstable-new.chpl

Fix a leak in this test

---

test/library/standard/DataFrames/DataFrames.chpl

Now that 'borrowed' is implicit in undecorated class types, remove it to improve readability:
* in formal arguments' types
* in local variables' types
* in `new` expressions
Testing: `test/library/standard/DataFrames/psahabu` directory.

Remove 'borrowed' in DataFrames.chpl

---

compiler/llvm/clangUtil.cpp

Follow-on to PR #11835, which checked for -Wl,-Bdynamic in
the gather_prgenv program name (rather than its output). This PR
fixes it to check the output.
It might also be possible/reasonable to omit -lpthread library
arguments when using a Cray PrgEnv (like we do for -lhugetlbfs).

Fix --llvm check for default to dynamic linking on Cray systems

---

test/patterns/eureka/eureka.chpl
test/patterns/eureka/eureka.good

You can't use a `break` statement in a `forall` statement, but you can
still write a parallel eureka pretty easily.  This little example shows
how.

Add a parallel eureka pattern.

---

util/cron/test-darwin.bash

It's taking almost a day so use paratest so we can finish sooner.

Use paratest for darwin testing

---

runtime/src/comm/ofi/comm-ofi.c

If a provider could support network AMOs for a given datatype only for
one or two of the non-fetching, fetching, and comparison atomic op
classes but not all three of those, the logic in comm=ofi would use
network AMOs for the supported op classes and drop back to Active
Messages and CPU AMOs for the unsupported op classes.  But that would
mix two kinds of initiators for a single datatype, potentially leading
to non-coherence.  Here, arrange to use network AMOs for all ops for a
given datatype iff the provider supports those for all three atomic op
classes, and otherwise use AMs and CPU AMOs for all ops.
(Note that we're not aware of any providers that have partial network
atomic op support as described here, but the new code is still the safer
way to go.  And the new logic is probably a …

Make sure comm=ofi AMOs are coherent.

---

modules/packages/UnorderedCopy.chpl

Fix bug/typo from https://github.com/chapel-lang/chapel/pull/12979

Fix typo in extern decl for chpl_comm_get_unordered_task_fence

---

test/classes/delete-free/isClassTest.good

Missed in https://github.com/chapel-lang/chapel/pull/12994

Quiet isClassTest failure

---

test/extern/ferguson/externblock/readme_example-error.good

Follow-on to PR #12958 to resolve a testing failure.

Fix readme_example-error.good following #12958

---

compiler/AST/symbol.cpp
compiler/optimizations/deadCodeElimination.cpp

This PR updates the compiler to instead invoke the string initializer that accepts a c_string instead of casting to a c_ptr and invoking a different initializer.
Testing:

Simplify string literal initialization

---

compiler/passes/expandExternArrayCalls.cpp

If the retExprType is 'void' then just call the wrapped function, but don't
try to return anything.  Fixes two --baseline testing issues.

Check for void retExprType in expandExternArrayCalls

---

compiler/passes/parallel.cpp

`needHeapVars()` only detected it "needed" to heap allocate local vars
under fifo w/ stack checks and --no-local or gasnet-{fast,large}. These
configs don't require locals (stack vars) to be heap allocated, so we
can remove needHeapVars() and the code to heap promote local variables.
For context/history: we used to put locals on the heap if there was a
possibility they would be communicated because in the past our comm
layers could only do comm for memory that came from the registered heap.
Nowadays all our comm layers can do out-of-segment comm. There is a
performance hit for doing so because you have to trampoline, but
qthreads stacks are allocated from our heap, which means we won't
trampoline. fifo w/ stack checks may need to trampoline, but we don't
care about performance there. …

Don't heap promote local variables

---

modules/dists/CyclicDist.chpl
modules/internal/localeModels/numa/LocaleModel.chpl

Follow-on to PR #13050.
* fix issue with CyclicDist
* fix issue with numa locale model

Fix nilability failures

---

test/ANNOTATIONS.yaml

Performance improved for locks, regressions for strings.

Performance annotations for week of 2019-05-30

---

compiler/codegen/expr.cpp

In support of an upcoming PR that will add unordered PUTs

Make some minor cleanup to unordered codegen

---

test/optimizations/remoteValueForwarding/alwaysRVFscopes.comm-none.lm-numa.good
test/optimizations/remoteValueForwarding/alwaysRVFscopes.lm-numa.good
test/optimizations/remoteValueForwarding/alwaysRVFscopes.no-local.good

This test is pretty sensitive to the number and depth of locales,
so it needed lm-numa and no-local .good files in addition to the
ones I'd originally added.

Add .good files that were missing / needed

---

modules/standard/Random.chpl

Missed in https://github.com/chapel-lang/chapel/pull/13116

Replace a manual lock in Random with LocalSpinLock

---

test/studies/prk/Stencil/optimized/stencil-opt.chpl
test/studies/prk/Stencil/stencil.chpl

This is an elegance improvement that should not longer result in a
performance hit due to PR #13146.

Change foralls into promoted op= for PRK Stencil

---

spec/Types.tex

Add a section for the 'nothing' type to the spec after the 'void' type section.

Add the 'nothing' type to the spec

---

compiler/passes/scopeResolve.cpp

This came out from my work on #13158. The top-level scopeResolve()
function was too long to comprehend easily. This change moves
its pieces into separate functions, leaving scopeResolve() short.
While there, move scopeResolve() to the bottom, according to
its being as the main function in its .cpp file.

Refactor scopeResolve()

---

modules/internal/DefaultAssociative.chpl
test/io/ferguson/assoc-domains.chpl
test/io/ferguson/assoc-domains.good

Implement reading of associative domains

---

test/library/packages/UnitTest/EqualLinkedList.bad
test/library/packages/UnitTest/EqualLinkedList.good

The LinkedList `.good` file was actually supposed to be the `.bad`. Added an empty `.good` for the expected behavior when this test someday passes.

Update LinkedList future .good/.bad

---

test/mason/mason-test-exit/exitCodeTest.future

Changed test into a future to quiet nightly testing

Changed the exit code test to a future

---

test/library/standard/Math/log-ints.chpl

Related to https://github.com/Cray/chapel-private/issues/282

Avoid left shift that changes sign in log-ints test

---

test/classes/nilability/nilable-equalities.chpl
test/classes/nilability/nilable-equalities.good

This test shows that https://github.com/Cray/chapel-private/issues/241 is resolved.

Add a test of string representations and equalities for class types

---

test/chplenv/sub_test_filters.notest
test/chplenv/sub_test_filters/compiler-error.chpl
test/chplenv/sub_test_filters/compiler-warning.chpl
test/chplenv/sub_test_filters/runtime-error.chpl
util/test/sub_test

`sub_test` filters were not working on errors that occurred during compile-time. This PR fixes compile-time error filtering (notably for intel error), and refactors the `sub_test` filtering code a little bit.
Also added some tests for debugging sub_test filters.

Sub test filter improvements

---

test/execflags/sungeun/about.prediff

Minor fix for `test/execflags/sungeun/about.chpl` to pass with `CHPL_LLVM=system`

Fix test/execflags/sungeun/about.chpl for CHPL_LLVM=system

---

test/errhandling/diten/tryExprOpen.bad

Fix a .bad file after #13327
Trivial and not reviewed but thanks to @lydia-duncan for pointing out the issue.

Update a .bad file after I/O changes

---

runtime/src/comm/gasnet/comm-gasnet.c

Move start/stop into separate functions in preparation for using a
built-in gasnet polling thread for ibv instead of creating our own.

Refactor gasnet polling setup/teardown

---

runtime/src/comm/gasnet/comm-gasnet.c

Remove near identical exit_common and exit_any_dirty routines and just
inline the code into chpl_comm_exit.
Also remove exit_any_clean from gasnet shim since it's dead code.

Cleanup gasnet exit routines

---

runtime/src/comm/ofi/comm-ofi.c

These frees up `chpl_comm_barrier()` for use in module code and reduces
interference from the main process. Same as #8533, but for ofi.
Resolves https://github.com/Cray/chapel-private/issues/322

Put the main process to sleep while waiting for shutdown in ofi

---

doc/rst/users-guide/base/bogus.rst

Classic error... reliance on 'git status -uno' caused me to forget new file

---

doc/rst/users-guide/base/bogus.rst
doc/rst/users-guide/index.rst

Verified that the web pages are sync-ing properly, so backing this
bogus change out.

Remove bogus file

---

runtime/src/comm/gasnet/comm-gasnet.c

Avoid interference from an active polling/progress thread by using a
blocking progress thread. Here we use `GASNET_RCV_THREAD` to tell gasnet
to create another thread that will block while waiting for incoming AMs.
This eliminates contention from the progress thread when there are no
incoming AMs.
Note that this thread only services network AMs, and would not progress
a shared-memory channel. This isn't a problem for us since we currently
run with a process per node and disable shared-memory support for IBV
with `--disable-pshm`.
This slightly increases the latency of AMs for gasnet-ibv, but
eliminating interference has non-trivial improvements for most
multi-locale benchmarks. The performance trade-offs are similar to
what we saw when we made a similar change for ugni in #9068.
Part of …

Use a blocking progress thread for gasnet-infiniband

---

compiler/passes/buildDefaultFunctions.cpp
test/interop/C/multilocale/static/withVerify.chpl
test/interop/C/multilocale/static/withVerify.compopts
test/interop/C/multilocale/static/withVerify.darwin.good

This PR will resolve #13461. In multi-locale interop, we inject the extern function `chpl_mli_smain` into the AST, where it is called by `chpl_gen_main`. That function symbol is marked extern, but did not also have the `FLAG_LOCAL_ARGS` flag.
I've also added one new test to `interop/C/multilocale/static` to lock in this new behavior. 
Testing:

Add FLAG_LOCAL_ARGS to `chpl_mli_smain` function symbol

---

util/test/sub_test

Follow on to https://github.com/chapel-lang/chapel/pull/13378

Check compiler and exec output for intel license filter

---

compiler/AST/symbol.cpp
compiler/include/symbol.h
compiler/passes/buildDefaultFunctions.cpp
compiler/passes/scopeResolve.cpp
compiler/resolution/functionResolution.cpp
test/classes/delete-free/borrow-resolution.chpl
test/classes/delete-free/borrow-resolution.good
test/classes/delete-free/borrowed/user-defined-borrow.good

Resolves #13438 
All credit goes to @mppf 
Test:

Remove buildClassBorrowMethod

---

test/mason/publish-tests/.gitignore
test/mason/publish-tests/EXECENV
test/mason/publish-tests/PREDIFF
test/mason/publish-tests/PREEXEC
test/mason/publish-tests/SKIPIF
test/mason/publish-tests/publishGitCheck.chpl
test/mason/publish-tests/publishGitCheck.good
tools/mason/MasonPublish.chpl

-removed prediff
-added preexec
-tweaked publishGitCheck test
-improved arguement parsing

Fixed paths of SKIPIF and EXEVENV

---

test/mason/publish-tests/noFork.chpl
test/mason/publish-tests/noFork.good
test/mason/publish-tests/noFork.prediff

-checks to see if 'fatal' and the username exist in the output and returns and empty file if so

Fixing noFork test 

---

test/parallel/sync/bradc/testBadSyncSingle-arr.good
test/parallel/sync/bradc/testBadSyncSingle-arr2.good
test/parallel/sync/bradc/testBadSyncSingle.prediff

Fix line numbers in testBadSyncSingle

---

test/analysis/alias/PREDIFF
test/analysis/alias/array-in-class.compgood
test/analysis/alias/array-in-class2.compgood
test/analysis/alias/array-of-arrays.compgood
test/analysis/alias/array-of-classes.compgood

Address analysis/alias/array-of-classes.chpl failures with NUMA

---

runtime/src/comm/ofi/comm-ofi.c

While working on #13612 we had noticed that if we did a `local_yield()`
instead of a `sched_yield()` while waiting for the network transaction to
complete after initiating an AM, the performance of global stream was
cut in half.  It turns out that this was due to the comm=ofi equivalent
to the problem fixed in comm=ugni by #7915:
- Locale 0 does a local task-spawn to queue the tasks for the inner
coforall across the PUs.
- Locale 0 does a remote task-spawn to locale 1 for the coforall-on
across nodes.
- Locale 0 yields while waiting for the network response from locale 1.
- The local tasks queued on locale 0 in the first step all run.
- Locale 0 finishes the kernel and resumes spawning remote tasks for the
coforall-on.
- The remaining locales queue their local tasks and finish the kernel. …

In comm=ofi, don't yield during the network wait for executeOnNB AMs.

---

modules/internal/DefaultRectangular.chpl

Fix an error with a size mismatch when deleting an array. This was causing
errors in a test on ugni platforms.

Fix another deletion size mismatch error

---

test/chplenv/sub_test_filters.notest
util/test/sub_test

As part of moving JIRAs over to private chapel issues, I'm
updating the filter for this issue as well.

Convert JIRA 357 filters over to "internal issue #398"

---

runtime/src/comm/ofi/comm-ofi.c

The ofi comm layer has had 15-20 nagging timeouts, some solid and some
sporadic but always close to timing out, ever since we've been able to
do full testing on it.  Here, use a so-called "wait set" to reduce that
problem greatly.  Wait sets are a mechanism that allows grouping CQs and
counters to allow waiting on all of them at once.  Here we make the AM
handler responsible not only for handling inbound AMs and ensuring
progress on its own outbound RMA, but also for ensuring progress on any
RMA inbound to its node, for providers which require that.  We now only
have a couple of tests that time out, and many tests that never did time
out are also running much faster.
In a related change, I outlined the transmit context/endpoint creation
code into a utility function, to help make it more …

Use a "wait set" to reduce comm=ofi timeouts quite a bit.

---

test/library/standard/DateTime/testDatetimeTZ.chpl
test/llvm/llvmDebug/llvmDebug_test.chpl
test/llvm/tbaa/tbaa_class.chpl
test/llvm/tbaa/tbaa_scalar.chpl

Fix 4 more tests for --no-legacy-nilable-classes

---

runtime/src/comm/ugni/comm-ugni.c

We've been seeing some hangs with large strided communication under
ugni. Ugni implements strided comm with non-blocking GETs/PUTs. For
non-blocking GETs that trigger RDMA over FMA we've been seeing hangs
that I haven't been able to narrow down yet.
For now just use blocking RDMA GETs for large non-blocking transfers.
This is faster than doing non-blocking FMA and avoids the hangs we've
been seeing.
Related to https://github.com/Cray/chapel-private/issues/437

Avoid non-blocking RDMA GETs under ugni

---

test/ANNOTATIONS.yaml
util/test/check_annotations.py
util/test/perf/perfgraph.js

Add annotations for progress thread improvements

Add some 16-node-cs annotations

---

modules/packages/Curl.chpl
modules/packages/HDFS.chpl

Follow-up to #13820
Fixes compilation errors in Curl and HDFS support packages.

Fix networking packages after #13820

---

test/multilocale/vass/on-nil.chpl
test/stress/deitz/test_10k_local_coforall_with_remote_update.chpl

Fix gasnet-quickstart failures after 13820

---

test/functions/ferguson/query/query-class-management-nilability-combinations.bad
test/functions/ferguson/query/query-class-management-nilability-combinations.chpl
test/functions/ferguson/query/query-class-management-nilability-combinations.future
test/functions/ferguson/query/query-class-management-nilability-combinations.good
test/library/packages/LAPACK/TestHelpers.chpl

Follow-on to PR #13820.
Applies a workaround for issue #13721 to LAPACK tests and adds a future relevant to that issue.

Fix lapack 13820

---

modules/internal/tasktable/on/ChapelTaskTable.chpl

Follow-on to PR #13820.
ChapelTaskTable needed to be updated to reflect current nilability rules.

Fix ChapelTaskTable for nilability

---

modules/internal/localeModels/knl/LocaleModel.chpl

Make `LocaleModel.chpl` for KNL pass nil checking, which has recently become more rigorous, ex. #13869, #13820.
Tested with `CHPL_LOCALE_MODEL=knl` over hellos and primers.

Make KNL LocaleModel pass nil checking

---

util/test/sub_test

(Very) small PR that updates `sub_test` to direct to private issue #474 instead of JIRA 333 (which is now closed).

Update sub_test string to point to private issue instead of JIRA

---

doc/rst/tools/mason/mason.rst

First pass at adding  documentation for mason-publish and mason offline

Updating documentation for mason.rst

---

test/types/string/vass/bogus-backslash.bad
test/types/string/vass/bogus-backslash.chpl
test/types/string/vass/bogus-backslash.future
test/types/string/vass/bogus-backslash.good

This is the .future for #13946

Future for bogus '\' in param strings

---

util/test/sub_test

Point to https://github.com/Cray/chapel-private/issues/482 instead of JIRA 287.

Update sub_test clock skew filter to point to to private issue

---

doc/rst/language/evolution.rst

Start to modify the language evolution document for 1.20 so that
other documentation can refer to the appropriate sections. I will
fill in these sections in an upcoming PR.

Start language evolution changes

---

doc/rst/language/evolution.rst

Continuing PR #14003 to write the language evolution text for 1.20.

Fill in the language evolution text

---

modules/standard/IO.chpl

Document channel.seek

---

modules/standard/Reflection.chpl
test/library/standard/Reflection/fileInfo.chpl
test/library/standard/Reflection/fileInfoInlineFunction.chpl
test/library/standard/Reflection/fileInfoNestedFunction.chpl
test/library/standard/Reflection/fileInfoNestedModule.chpl

Update names of these functions to match the most agreeable names from issue
#13680. Update tests to use the new names.

Change names of functions to get module/routine/file name and line number

---

spec/Classes.tex

#14021 added some spec tests that weren't working yet. This PR fixes them.

Fix spec tests

---

doc/rst/tools/mason/mason.rst

Add information about the new `mason test` behavior for unit tests to the mason docs.
Also include an example of listing tests in the manifest file.

Update mason docs w.r.t. mason test

---

spec/Conversions.tex

Tweaks to Conversions.tex

---

test/localeModels/nspark/loc-in-locales.good

Fix test that broke from changing the number of lines in IO.chpl in #14080.

Update .good that includes IO.chpl line numbers

---

doc/util/versionButton.php

Whoops, apparently that last PR was not so trivial that I couldn't mess
it up.  This should be more correct.

Update staged version

---

doc/rst/developer/bestPractices/TestSystem.rst

This PR adds description for creating and running multilocale and commcount tests.

Document multilocale performance and commcount testing

---

test/extern/fnPtrs/improveErrorForFcfMismatch.bad
test/extern/fnPtrs/sugarFcfTypes.bad
test/extern/fnPtrs/sugarFcfTypes2.bad

This PR adjusts some .bad files for FCF tests that I missed during initial testing for #14163 (I did not run futures).

Adjust .bad files for some FCF tests

---

doc/rst/platforms/cray.rst

This duplicates #14235 into the release/1.20 branch.

Update platform documentation for Cray Shasta systems.

---

util/cron/common-memleaks.bash
util/cron/common-perf.bash
util/cron/common.bash
util/cron/historify-logs
util/cron/nightly

For more info see https://github.com/Cray/chapel-private/issues/409

Move NightlyPerformance directory from /data/sea to /cray/css

---

doc/rst/platforms/cray.rst
doc/rst/usingchapel/multilocale.rst
runtime/src/comm/gasnet/comm-gasnet.c
third-party/gasnet/Makefile
util/chplenv/chpl_comm_segment.py
util/chplenv/chpl_comm_substrate.py
util/config/gather-pe-chapel-pkgconfig-libs.bash

Remove XE support from the gasnet Makefile, chplenv, and documentation

Remove vestiges of gasnet XE/XK support and documentation

---

test/studies/hpcc/common/bradc/unit/parRandom2-domblock.bad
test/studies/hpcc/common/bradc/unit/parRandom2-domblock64.bad

Fix two futures .bad files

---

runtime/src/comm/ofi/comm-ofi.c

Libfabric providers may have a maximum RMA transfer size they can
support.  We have not been paying attention to that in comm=ofi.  Do so
here, by splitting transfers that are larger than that.  In ml-16
performance testing, performance/comm/low-level/arrayTransfer has been
failing (with a CQ overrun) in its largest (1/4-mem array) test configs.
With this change, those now pass.
This resolves https://github.com/Cray/chapel-private/issues/595.

In comm=ofi, split RMA transfers that are larger than the provider can do.

---

test/functions/jplevyak/zeroarity-bound-error-1.good

The error message now has additional information in it, so the .good file needs
an update.

Fix a test that needed an update after Vass's #14486

---

compiler/resolution/visibleFunctions.cpp

Two private functions in the same scope will have the same answer for if they
are visible to the current call, so there isn't any point to checking any later
ones after we have the answer for the first private function in a scope.
Initial results put this at a 1.11x improvement to resolution, and a 1.08x
improvement to compilation.
Passed a full standard paratest with futures, and release/examples with
CHPL_COMM=gasnet

Only check visibility once per scope instead of once per private function

---

util/cron/common-cray-cs.bash

Load fftw module for cray cs testing

---

test/npb/ft/npadmana/ft_transposed.ml-perf.graph
test/npb/ft/npadmana/ft_transposed.skipif

The elegant version times out under gasnet mpi

Skip NPB-ft for gn-mpi perf testing

---

modules/internal/ChapelLocale.chpl

Warm up tasking layers that have a fixed number of tasks (like qthreads)
as well as the memory layer during startup. Here we effectively do:
```chpl
coforall 0..#here.maxTaskPar do
new warmupAllocation();
```
But we use some lower level primitives since we're early in
initialization. Tasking layers like qthreads have a fixed number of
threads that tasks are then multiplexed over. Those threads don't grab
initial space for task stacks so we pay the allocation (and potentially
registration/broadcasting) penalty when the task is first created. Here
we move that cost from user-code to our startup. This is primarily just
shuffling time from user-code to initialization so we can get more
accurate timings for micro-benchmarks. That said this could have a
slight benefit for real applications …

Warm up the runtime before entering user code

---

runtime/src/comm/ofi/comm-ofi.c

We were throwing `FI_MR_ALLOCATED` in the memory registration hints, but
that's not correct unless all the pages in every registered region
exist.  Here, stop throwing that unless it looks like we will have a
fixed heap.  This fixes a bug which caused immediate internal errors at
program startup in multi-node programs without a fixed heap on Cray CS
systems, as each node tried and failed to register its entire virtual
address range.  Because we were throwing `FI_MR_ALLOCATED` libfabric was
selecting the 'verbs;ofi_rxm' provider, but that doesn't support
scalable memory registration.  Now without `FI_MR_ALLOCATED` we get the
'tcp;ofi_rxm' provider instead.  That does support scalable MR.  Thus
programs that don't communicate much but are sensitive to NUMA affinity
(such as `stream-ep`) now …

Don't throw FI_MR_ALLOCATED unless all the pages exist.

---

runtime/src/comm/ofi/comm-ofi.c

We get the libfabric `-FI_EMFILE` error code when it needs to open a file
but we've reached the open file limit.  Basically it's the same thing as
the `EMFILE` errno code.  Here, improve our handling of this one: don't
only print it for the 'tcp' provider, and also don't only print it when
some computation based on numLocales and comm concurrency is larger than
the open file limit.  We're just not smart enough to get that right in
all cases.

Improve the message comm=ofi prints for FI_EMFILE.

---

test/arrays/formals/queryArrOfArr.bad
test/arrays/formals/queryArrOfArr.chpl
test/arrays/formals/queryArrOfArr.future
test/arrays/formals/queryArrOfArr.good
test/arrays/formals/queryArrOfArr2.bad
test/arrays/formals/queryArrOfArr2.chpl
test/arrays/formals/queryArrOfArr2.future
test/arrays/formals/queryArrOfArr2.good
test/arrays/formals/queryMultiDimByRange.bad
test/arrays/formals/queryMultiDimByRange.chpl
test/arrays/formals/queryMultiDimByRange.future
test/arrays/formals/queryMultiDimByRange.good

Add futures related to querying array domains/ranges

---

doc/rst/language/spec.rst

This updates the spec for the changes in #14573, #14579,
including test chagnes. While there, a slight rephrasing
of the postfix-`!` operator.

Spec updates for nilability changes

---

modules/packages/EpochManager.chpl
modules/packages/LockFreeQueue.chpl
modules/packages/LockFreeStack.chpl

This brings these modules to compliance with #14579 by inserting postfix-`!` calls as needed.
While there, replace some nilable types with non-nilable ones to reduce the need in postfix-`!`. Remove the `prototype` annotations on the modules because they are no longer needed.

Update EpochManager, LockFreeQueue, LockFreeStack for nilability

---

test/types/records/generic/partial-instantiation-equivalence.bad
test/types/records/generic/partial-instantiation-equivalence.chpl
test/types/records/generic/partial-instantiation-equivalence.future
test/types/records/generic/partial-instantiation-equivalence.good

Add future for #14286

---

doc/rst/language/spec.rst

Spec changes to go along with PR #14564.

Spec changes for split init

---

test/ANNOTATIONS.yaml

Covers explicit changes to compilation and moving the compiler performance tests
to specific VMs

Add compiler performance annotations tracking my changes

---

test/classes/initializers/parentCall/inBeginOn.comm-none.good
test/classes/initializers/parentCall/inBeginOn.comm-none.lm-numa.good
test/classes/initializers/parentCall/inBeginOn.no-local.good
test/classes/initializers/siblingCall/inBeginOn.comm-none.good
test/classes/initializers/siblingCall/inBeginOn.comm-none.lm-numa.good
test/classes/initializers/siblingCall/inBeginOn.no-local.good

Fix .good files for inBeginOn in local configurations

---

test/studies/shootout/reverse-complement/bradc/revcomp-blc.chpl

This is a code cleanup of my revcomp to prepare for a code review with the perf team and eventual submission to the CLBG site.
I also restored the second QIO hint.  It doesn't seem to have a big impact on the chapcs machines, but since it's what we've been using and I couldn't get rid of both, I figured I'd leave it in for now.

Revcomp cleanup in preparation for review and submission

---

modules/internal/String.chpl

This PR reverts the string.these improvements which turned out some failures that are not immediately clear to me. Until I can afford the time to take a deeper look into it, this PR reverts the change.

Revert "Merge pull request #14685"

---

modules/internal/String.chpl

This PR improves the performance of `string.these`. This is mainly motivated by
performance regression after UTF8 validation. After that, every single-character
string yielded by this method was validated. Now, this method uses the
non-validating factory function.
While there, this PR also changes the logic which was to extract a codepoint
from string (encode), then, create a string from the codepoint (decode). This
codepoint-based logic was unnecessary. After this PR, we decode the string
at the current position in order to determine the length of the next codepoint,
then copy a buffer out with that length and create the string on top of that.
I attempted this first in #14685, which I reverted in #14720. The issue was not
appending a null-byte to the generated strings which caused subtle …

Improve string.these

---

util/dockerfiles/Dockerfile

Updated debian:9.5 to debian:10

release/chapel1.20 branch change ONLY

---

compiler/resolution/AutoDestroyScope.cpp
compiler/resolution/addAutoDestroyCalls.cpp

Follow-on to #14776
* add a comment
* rename isExprStmt to stmtIsExpr

Make minor changes suggested by review of 14776

---

test/studies/shootout/regexdna-redux/regexdna-redux.graph

For some reason I made the lists in this graph file space-separated, but they should be comma-separated. This PR fixes that.

Add missing commas in the graph file

---

runtime/src/comm/ugni/comm-ugni.c

It was using an uninitialized atomic to only issue the warning once.
That happened to work for intrinsics/cstlib atomics, but is generally
wrong. Switch to using pthread_once to ensure the warning is only
issued once.

Fix a bug in ugni's out-of-memory-regions warning code

---

doc/rst/developer/README.partialInstantiation

Some language fixes that I came across when reading the `partialInstantiation` doc.

Grammar fixes

---

runtime/src/comm/ofi/comm-ofi.c

Our provider handling has been a bit slapdash, and with work on
unordered atomics about to start this is a good time to clean it up.  So
here, add a provider set type and operations upon it, then rearrange and
rewrite so as to do checks against available and in-use providers in the
same way.
Then, get rid of network-based checks.  These weren't necessarily
accurate anyway and are better done as provider-based checks.  For
example, the part of the check in init_fixedHeap() for needing a fixed
heap when using the gni provider on a Cray XC system was effectively
ignoring what provider would be used, and we don't need a fixed heap if
we're using the tcp provider.
While here, improve the getinfo-related debug support.

More-principled provider handling in comm=ofi.

---

modules/packages/DistributedBag.chpl
modules/packages/DistributedDeque.chpl

Add RVF pragma to DistributedDeque and DistributedBag records
Fixes https://github.com/chapel-lang/chapel/issues/13257

Add pragma to DistributedDeque and DistributedBag

---

modules/standard/Random.chpl

Add throws tags to functions in Random module

---

test/chpldoc/compflags/textonly/interruptingSingleComment.doc.bad
test/chpldoc/compflags/textonly/interruptingSingleComment.doc.future

Was resolved by #14900, but I missed it when looking through test results.

Remove the .bad and .future from this file as well

---

test/mason/spack-integration/mason-external.good

Update a .good file missed in  #14881

Update .good for mason update output

---

test/chpldoc/compflags/version/PREDIFF
test/chpldoc/compflags/version/SKIPIF
test/chpldoc/compflags/version/projectVersion.no-tag.doc.good
test/chpldoc/compflags/version/projectVersion.no-tag.multi.doc.good
test/chpldoc/compflags/version/projectVersion.no-tag.single.doc.good
test/chpldoc/compflags/version/projectVersion.tag.alpha.doc.good
test/chpldoc/compflags/version/projectVersion.tag.beta.doc.good
test/chpldoc/compflags/version/projectVersion.tag.rc.doc.good

- trim the output file to get only 'version' from the file
- replace test files to accept new format

fix project version test files

---

test/release/examples/benchmarks/hpcc/ra.chpl

Switch from using a local block to localAccess for ra-on. This allows
the fast-on optimization to trigger, which eliminates task creation. The
local block was originally added in 4a8cedf8fc to enable the fast-on
optimization, but it looks like there's been a regression since then.
With the local block today we're still emitting PUT/GET calls (that end
up being local) that thwart the fast-on optimization. Longer term we
want to deprecate support for the local block anyways, so switch to
localAccess.
RA-on performance for XC (Aries/ugni) and CS (FDR-IB/gasnet-ibv-large):
| config  | Before      | After       |
| ------- | ----------- |  ---------- |
| Cray-XC | 0.0119 GUPS | 0.0143 GUPS |
| Cray-CS | 0.0018 GUPS | 0.0027 GUPS |

Use localAccess for ra-on

---

compiler/AST/AggregateType.cpp
compiler/AST/FnSymbol.cpp
test/arrays/ferguson/array-of-owned-error1.good
test/arrays/ferguson/array-of-owned-error2.good
test/arrays/ferguson/array-of-owned-return.bad
test/users/npadmana/twopt/do_smu_soa-error.bad

These calls are expensive and slow down compilation significantly.
Testing:

Remove calls to getUserInstantiationPoint

---

runtime/src/comm/ugni/comm-ugni.c

Sigh...
Thanks to @e-kayrakli for catching this before nightly testing ran.

Add missing curly bracket that I overlooked in my review of #15031

---

test/library/packages/Itertools/Itertools.chpl

Remove throws from Itertools iterators until #7134 is resolved. Resolves baseline failures in nightly testing.

Remove throws from Itertools iterators 

---

doc/rst/developer/bestPractices/ContributorInfo.rst

Fix broken link contributor info TOC

Fix broken link contributor info TOC

---

compiler/resolution/preFold.cpp

When using --baseline, dead code elimination doesn't fire, so some
dead variables that I left in the IR sloppily resulted in codegen
problems.  Here, I've introduced additional code to search for and
remove those variables, refactoring the previous code slightly.

Fix heterogeneous tuple loops for --baseline runs

---

test/classes/ferguson/delete-free/owned-borrow-check.chpl
test/classes/ferguson/delete-free/owned-borrow-check.future
test/classes/ferguson/delete-free/owned-borrow-check.good
test/classes/ferguson/delete-free/owned-borrow-check.skipif

It had several problems due to language updates. It
now gives an error as expected.

Fix the future owned-borrow-check.chpl

---

doc/rst/language/spec/classes.rst

Use the term "borrowed C" in a comment in a spec example

---

modules/standard/Path.chpl
modules/standard/Spawn.chpl

In accordance with #11417.
@lydia-duncan please review. Thanks!

Add throws tags to functions in Path module

---

test/performance/comm/low-level/array-gets.ml-perf.graph
test/performance/comm/low-level/array-puts.ml-perf.graph
test/performance/comm/low-level/arrayTransfer.chpl
test/performance/comm/low-level/arrayTransfer.ml-execopts

Add a performance test that does misaligned 1M GETs/PUTs. We know our
misaligned GET performance isn't optimal. Add a performance test to
see how far off we are and to track future improvements.
For https://github.com/Cray/chapel-private/issues/636

Add a perf test that does misaligned comm

---

test/library/standard/FileSystem/nonUTF8/basic.chpl
test/library/standard/IO/nonUTF8/basic.chpl
test/library/standard/Path/nonUTF8/basic.chpl

I missed these tests in #14986 because they are skipped in most systems.

Fix non-UTF8 path tests

---

doc/rst/developer/bestPractices/ContributorInfo.rst

Add release process info to Contributor Info page

Add release process info to contributorinfo

---

test/classes/casts/class-type-cast.chpl
test/classes/casts/class-type-cast.good
test/classes/casts/class-type-cast2.bad
test/classes/casts/class-type-cast2.chpl
test/classes/casts/class-type-cast2.future
test/classes/casts/class-type-cast2.good

This is a pair of tests, one that works, one that should but doesn't, that shows how you can (or should be able to) cast between nilable and non-nilable class types.

Add working and non-working test of casting between class types

---

runtime/src/launch/slurm-srun/launch-slurm-srun.c

By default we ask slurm to give us access to all "CPUs" (as reported by
`sinfo --format="%c"`. However, this fails if the nomultithreaded hint
was provided. Update our logic to detect if that var is set, and if so
only ask for physical cores (CPU / threadPerCore)
Resolves https://github.com/chapel-lang/chapel/issues/15127
Closes https://github.com/Cray/chapel-private/issues/847

Only ask for physical cores if SLURM_HINT=nomultithreaded

---

doc/rst/developer/bestPractices/ContributorInfo.rst
doc/rst/developer/bestPractices/TestSystem.rst
test/release/examples/primers/learnChapelInYMinutes.chpl

Fix some grammar mistakes I came across when reading the docs. Also fix the capitals in GitHub.

Fix grammar and capitals in docs

---

test/types/unions/union-copy-init3.bad

Update this .bad which seems to have changed with module changes.
This test looks like it's going to be a maintenance burden, but I'm not taking the time to write a prediff for it because I've been trying to "go home" for the past hour and a half and am not very good at scripting.

Update union-copy-init.bad which has fallen out of sync

---

test/visibility/import/nested2.bad

I think Michael's changes today changed the behavior for this test.
I'm not entirely clear on what it was supposed to be testing or what
it would take to retire it, so am hoping Lydia and/or Michael can look
at it tomorrow and decide what needs to be done.

Update nested2.bad w.r.t. today's changes

---

doc/rst/tools/mason/mason.rst

Fixes render error in mason documentation.
fixes #15280

fix for mason docs

---

compiler/optimizations/optimizeForallUnorderedOps.cpp

Remove debug code from forall-unordered-opt fix PR

---

modules/dists/StencilDist.chpl
test/distributions/bharshbarg/fastFollowerEquality.chpl
test/distributions/bharshbarg/fastFollowerEquality.good

Fast followers for Stencil regardless of element type

---

runtime/src/comm/ofi/comm-ofi.c

Add a poll set to the wait set that is already used by the comm=ofi AM
handler.  This should improve our ability to progress inbound traffic
while waiting for outbound traffic to complete.  Not being able to do
that seems to have been the cause of at least some of the timeouts we
have been seeing in full testing of comm=ofi.

Add a poll set in the comm=ofi AM handler.

---

doc/rst/language/spec/modules.rst

This updates the spec slightly w.r.t. recent changes relating to super/sub-module visibility.  While here, I did some wordsmithing in adjacent paragraphs.

Update documentation with respect to super/sub-module visibility.

---

doc/rst/language/spec/procedures.rst
doc/rst/language/spec/variables.rst

Updates spec sections on split initialization and out intent.
See also PR #14917 and PR #15113.

Improve spec for split init & out

---

doc/rst/language/spec/classes.rst
doc/rst/language/spec/records.rst
doc/rst/language/spec/variables.rst

Update spec based on CHIP 13, add copy elision

---

test/types/tuple/types/testTuple.bad
test/types/tuple/types/testTuple.future

Defuturize tuple of tuples of non-nilable classes test.
Follow-up to #15377

Defuturize tuple of tuples of non-nilable classes test

---

CONTRIBUTORS.md

This is the CONTRIBUTORS.md file for Chapel 1.21.  Thanks to everyone who contributed!

CONTRIBUTORS file for Chapel 1.21

---

CHANGES.md

Here is a short list of CHANGES that you might find present in Chapel 1.21
[entries contributed by the team, edited by me, reviewed by @ronawho]

CHANGES.md file for Chapel 1.21

---

compiler/main/version_num.h
doc/rst/conf.py
doc/rst/language/archivedSpecs.rst
doc/rst/usingchapel/QUICKSTART.rst
doc/rst/usingchapel/chplenv.rst
man/confchpl.rst
man/confchpldoc.rst
test/compflags/bradc/printstuff/version.goodstart

Referenced updates made for 1.21: https://github.com/chapel-lang/chapel/compare/512d4a03d0d6...e6731d8a2509

Update version number to 1.22.0.

---

test/npb/ft/npadmana/DistributedFFT.chpl
test/npb/ft/npadmana/ft_transposed.chpl
test/npb/ft/npadmana/ft_transposed_comp_only.chpl
test/npb/ft/npadmana/ft_transposed_comp_only.compopts

Make DistributedFFT.chpl index-neutral so it's compatible with 1.21 and
1.22. I've opened a PR upstream for this and will bring in an "official"
version later, but for now I wanted to get this in for 0-based tuple PR.
This also adds a `--no-codegen` version of npadmana/ft_transposed.chpl.
ft_transposed.chpl requires FFTW, so it's skipped for a standard test run. This
variant will help us catch compile time errors before nightly testing and is
similar to #14605.

Make DistributedFFT.chpl index neutral

---

test/studies/shootout/chameneos-redux/hannah/chameneos-redux-cas.chpl

Fix an OOB error that I missed because it only showed up on perf runs

---

doc/rst/language/spec/data-parallelism.rst
doc/rst/language/spec/expressions.rst
modules/internal/ChapelTuple.chpl
test/exercises/c-ray/c-ray.chpl
test/exercises/c-ray/solutions/c-ray-1.chpl
test/exercises/c-ray/solutions/c-ray-1a.chpl
test/exercises/c-ray/solutions/c-ray-2.chpl
test/exercises/c-ray/solutions/c-ray-2a.chpl
test/exercises/c-ray/solutions/c-ray-3.chpl
test/exercises/c-ray/solutions/c-ray-3a.chpl
test/exercises/c-ray/solutions/c-ray-4.chpl
test/exercises/c-ray/solutions/c-ray-4a.chpl
test/exercises/c-ray/solutions/c-ray-5.chpl
test/exercises/c-ray/solutions/c-ray-6.chpl
test/exercises/c-ray/solutions/c-ray-7.chpl
test/exercises/c-ray/solutions/c-ray-8.chpl

This is what I found doing a scan of documents looking for places that still revealed 1-based bias.

Additional cleanups related to switching from 1-based to 0-based programming

---

test/release/examples/primers/classes.chpl

Adds an unmatched backquote in classes primer
resolves #15108

Adds an unmatched backquote in classes primer

---

modules/internal/Bytes.chpl
modules/internal/BytesStringCommon.chpl
modules/internal/String.chpl
modules/internal/fixInternalDocs.sh

Fixes the following issues:
- Few procs were not rendered because of misplaced comments
- Bytes doc didn't go through a post processing script
- #15411 missed to update the same script

Small doc fixes

---

modules/internal/ChapelIteratorSupport.chpl

This PR does some comment juggling to get the docs to render again.

Minor changes in vectorizing iterator docs

---

modules/packages/FFTW.chpl

Rearrange comments to fix chpldoc rendering.

Minor changes in FFTW doc.

---

modules/standard/DynamicIters.chpl
modules/standard/IO.chpl

With respect to #15477 
@lydia-duncan please review

Doc fixes for IO and DynamicIters

---

doc/util/versionButton.php

With luck, this could be the first time I've gotten this update right in one try.....

Update docs version button for today's release

---

doc/util/versionButton.php

This is the version button update for our pre-1.22 release now that everything's ready.

Update master to 1.23 now that it's labeled as such

---

test/distributions/privatization/runtime/addAndGetAndClearPrivatizedInParallel.chpl

Close a leak in addAndGetAndClearPrivatizedInParallel.chpl

---

compiler/resolution/visibleFunctions.cpp

Did I really never compile this before filing a PR?  Or did I fail
to push a commit to the PR?  Why did Travis not check my PR?
Who let me on this team?  We may never know the answers to
these questions...

Fix broken code I just committed in PR #15320

---

runtime/src/comm/ofi/comm-ofi.c

Over time the ofi comm layer has built up a lot of variability in how
transactions are initiated and waited for and how progress is ensured,
based on what kind of transaction was being done and who (worker or AM
task) was doing it.  Here, adjust so that in so far as possible we do
things the same way in all cases.
We used to wait out EAGAINs resulting from ofi_rxm dynamic connection in
different ways for different kinds of transactions.  Now we do it the
same way everywhere, so we don't need to specify a progress function to
call while waiting.
There were many instances of divergent flow control based on whether the
endpoint in question used a CQ or a counter for completions.  Here, get
rid of nearly all of that by recording the fid and a pointer to an
appropriate completion-consuming …

Improve transaction waiting and progress handling in comm=ofi.

---

compiler/optimizations/loopInvariantCodeMotion.cpp

LICM computes all aliases in a given function. Previously, it was
computing those aliases for each loop in that function, but that
wastes a lot of time, especially for large functions with many loops.
Only compute the aliases once per function and pass them to the loops.
This halves LICM for Arkouda.

Only compute LICM aliases once

---

doc/rst/usingchapel/QUICKSTART.rst
doc/rst/usingchapel/chplenv.rst

The PR focuses on improving the friendliness of the page to less experienced users, more specifically, providing more information about setting up the environment.
resolves https://github.com/chapel-lang/chapel/issues/14988

improve QUICKSTART.rst

---

test/multilocale/deitz/needMultiLocales/privateLimitedDistributedArrayClass1.chpl
test/multilocale/deitz/needMultiLocales/privateLimitedDistributedArrayClass2.chpl
test/multilocale/deitz/needMultiLocales/test_frag_main.chpl
test/multilocale/diten/localBlock/needMultiLocales/localBlock1.chpl
test/multilocale/diten/localBlock/needMultiLocales/localBlock6.chpl
test/multilocale/diten/needMultiLocales/DijkstraTermination.chpl
test/optimizations/bulkcomm/ptrArray/widePtrArrayAssignment.chpl
test/studies/comd/elegant/arrayOfStructs/util/AccumStencilDist.chpl
test/studies/hpcc/common/bradc/BradsBlock1D.chpl

This PR closes some trivial leaks in tests that only show up on multilocale
runs.
Modified tests pass with gasnet.

Close some multilocale test leaks

---

test/studies/arkouda/sub_test
util/cron/common-arkouda.bash

Test Arkouda master now that it's compatible with chapel-master again

Go back to testing arkouda master

---

util/build_configs/cray-internal/setenv-xc-x86_64.bash

See https://github.com/Cray/chapel-private/issues/918

Remove KNL locale model from the cray XC module

---

modules/internal/ChapelRange.chpl
test/types/range/userAPI/byteRangeTest.good
test/types/range/userAPI/codepointRangeTest.good
test/types/range/userAPI/rangeAPItest.chpl
test/types/range/userAPI/simpleRangeTest.good

Add range.isBounded() function, an alternative approach to isBoundedRange()
Fixes https://github.com/chapel-lang/chapel/issues/15528

[Feature] range.isBounded() function

---

tools/mason/MasonExternal.chpl

minor fix in `MasonExternal.chpl` following up from #15641

replace ~/.mason with MASON_HOME

---

modules/packages/LinearAlgebra.chpl
test/library/packages/LinearAlgebra/correctness/testEigen.chpl

* Added the `eigh` and `eigvalsh` routines to `LinearAlgebra`
* Testing.
* Documentation
Partially addresses #15621

Eigensystems for symmetric/hermitian matrices

---

test/studies/shootout/reverse-complement/bradc/revcomp-blc.chpl

These are mostly style cleanups, though also with a bit of focus
on performance.  Specifically, I:
* added basic comments
* switched to channel.offset to find the end of the buffer read in
* changed some variable and procedure names
* switched to a zippered loop for the reversal because it supports changing to a `forall`
* refactored and renamed some common subexpressions a bit

More updates to my version of revcomp

---

test/studies/shootout/reverse-complement/bradc/revcomp-blc.chpl

I was originally thinking that I'd focus on both a serial and parallel version of revcomp, but the serial version isn't consistently that much faster than the one that we've already submitted, so I'm going to go straight to this parallel version instead.

Make blc study version of revcomp parallel

---

tools/mason/MasonHelp.chpl

Fix minor typo in MasonHelp

---

modules/packages/LinearAlgebra.chpl

Fix minor typo in LinearAlgebra from #15626 
Thanks for catching @cassella !

Fix minor typo in LinearAlgebra

---

util/cron/common-arkouda.bash

See https://github.com/mhmerrill/arkouda/pull/372

Upgrade Arkouda release testing from 1.20 to 1.22

---

runtime/src/comm/ofi/comm-ofi.c

Dynamic connection establishment as implemented by certain providers
(RxM being one) can put us in a situation where we've reached the open
file limit but we're not getting the corresponding error code (-EMFILE)
from our own calls to libfabric, which would enable us to produce our
specific "open files limit" error message.  Here, implement periodic
liveness checks from node 0 to the other nodes, to determine when this
is so and report it.
A "liveness check" is really just a test that sending a small AM to a
remote node doesn't result in an unrecoverable error.  The logic is
coded so as to minimize the associated overhead, notably by only doing a
check every 10 seconds, and using an adjustable integer counter as a
proxy for the 10-second timeout since time checks are expensive.
With this …

In comm=ofi, do liveness checks.

---

test/distributions/robust/arithmetic/performance/multilocale/alloc.block.good
test/distributions/robust/arithmetic/performance/multilocale/alloc.cyclic.good
test/distributions/robust/arithmetic/performance/multilocale/alloc.cyclic.na-none.good
test/distributions/robust/arithmetic/performance/multilocale/alloc_all.block.good
test/distributions/robust/arithmetic/performance/multilocale/alloc_all.cyclic.good
test/distributions/robust/arithmetic/performance/multilocale/alloc_all.cyclic.na-none.good

PR #15777 reduced commcounts, I changed some good files but missed some, too.
This PR fixes those.
Tested with {block, cyclic} X {na-none, ugni}

Accept more positive commcount changes

---

test/functions/generic/withExternType.bad
test/functions/generic/withExternType.chpl
test/functions/generic/withExternType.future
test/functions/generic/withExternType.good

Add the test withExternType.chpl

---

modules/packages/LinearAlgebra.chpl

Fix outdated LinearAlgebra documentation wrt to opting out of BLAS and LAPACK dependencies

Fix outdated LinearAlgebra documentation

---

CHANGES.md

This is an update to the CHANGES file in anticipation of a release of Chapel addressing gcc 10.x issues.

Proposed CHANGES file for 1.22.1

---

test/library/standard/List/init/listInitGenericError.good
test/library/standard/List/init/listInitGenericError.prediff

so that it is no longer sensitive to List line numbers.

Add a prediff to listInitGenericError.chpl

---

test/library/standard/List/init/listInitGenericError.good
test/library/standard/List/init/listInitGenericError.prediff

Fix a test related to line number
Follows up https://github.com/chapel-lang/chapel/pull/15837
@ben-albrecht Kindly review.

Fix a test related to line number

---

test/functions/iterators/elliot/dynamicDispatch/parallel-virtual-par-iters.bad
test/functions/iterators/elliot/dynamicDispatch/serial-virtual-par-iters.bad

Follow the lead of PR #15859 in updating two more .bad files to adapt to
changes resulting from PR #15713.

Update the order of errors in a couple of .bad files.

---

test/visibility/rename/renameUsedMod/renameChain.bad
test/visibility/rename/renameUsedMod/renameChain.future

Remove the .future and .bad file from this test now that it passes

---

doc/rst/platforms/cygwin.rst

Add notes to Cygwin documentation regarding performance, Windows 10

---

test/functions/generic/poi/shadowing-field.bad
test/functions/generic/poi/shadowing-field.chpl
test/functions/generic/poi/shadowing-field.future
test/functions/generic/poi/shadowing-field.good
test/functions/generic/poi/shadowing-method.bad
test/functions/generic/poi/shadowing-method.chpl
test/functions/generic/poi/shadowing-method.future
test/functions/generic/poi/shadowing-method.good

Add tests for POI bug Issue 15937

---

util/cron/test-perf.cray-cs.arkouda.bash

See if this helps with current OOM issues

Increase heap size for arkouda 16-node-cs testing

---

runtime/include/mem/jemalloc/chpl-mem-impl.h
runtime/src/mem/jemalloc/mem-jemalloc.c
util/cron/test-perf.cray-cs.arkouda.bash

jemalloc uses arenas to reduce allocation contention and improve the
performance of concurrent allocations. Typically, a thread will gain
affinity for a specific arena, and future allocations will be satisfied
by that arena. This is great for performance, but it can introduce
fragmentation, which can be a problem for large allocations. To reduce
fragmentation, satisfy large allocations (32 MiB or larger) out of a
single arena. This limits concurrency for large allocations, but those
won't be as common and we're typically not doing them in parallel.
As an example of where things were going wrong -- in a program that
allocates large arrays with multiple trials, we might end up allocating
arrays from thread/arena-0 for the first trial, but then out of
thread/arena-1 for the second trial. …

Reduce fragmentation for large allocations

---

compiler/parser/README

Based on a suggestion from @damianmoz - thanks for the suggestion.

Add flex version requirement to compiler/parser/README

---

test/optimizations/autoLocalAccess/zipper/withInitializerCall.chpl
test/optimizations/autoLocalAccess/zipper/withInitializerCall.good

I fixed a similar test with a leak before. This one was added after that
fix, although I have copied it from the original leaky version and thus created
another leak :(

Delete unmanaged instances in test

---

doc/rst/technotes/lifetimeChecking.rst

A few tweaks to lifetimeChecking.rst

A few tweaks to lifetimeChecking.rst

---

test/GRAPHFILES
test/library/standard/Map/timeMapMinusEqual.chpl
test/library/standard/Map/timeMapMinusEqual.perfcompopts
test/library/standard/Map/timeMapMinusEqual.perfkeys

Add a test that times doing big -= operations on maps.

Add a performance test of -= on maps

---

test/library/standard/Map/timeMapMinusEqual.chpl

Thanks for the heads up @ronawho. Updated to make the first iteration match the
rest.

Fix map performance test to always time fullMap-fullMap

---

runtime/src/chpl-cache.c

Follow-up to PR #16020. Thanks to @ronawho for noticing.

Fix spelling error in a comment

---

test/library/standard/Map/timeMapMinusEqual.graph

I missed this file in the commit for the test. Commit it now.

Commit the graph file for new performance test

---

modules/standard/Map.chpl

For the minus-equal operation on two maps, inline the body of the `remove`
function and then hoist the locking operations and calls to
`table.maybeShrinkAfterRemove` out of the loop. This way, when a lot of elements
are removed, locking, unlocking, and shrinking the table only happens once
instead of once per element removed.

Optimize map -= operation

---

modules/internal/ChapelBase.chpl

Previously, we only used parallel array init for POD types because we
had performance issues with arrays-of-arrays. That performance issue was
resolved in #15895, so we can now enable parallel init for all arrays. We
will probably need to retune our heuristic for switching between serial
and parallel init especially for non-POD types, but to start just use
the existing 2MB threshold.
Resolves https://github.com/chapel-lang/chapel/issues/6689
Part of https://github.com/chapel-lang/chapel/pull/16070

Enable parallel array init for all types

---

test/ANNOTATIONS.yaml

- [RA atomics improvement](https://chapel-lang.org/perf/chapcs/?startdate=2020/05/30&enddate=2020/07/16&graphs=hpccratime)
PR: Enable parallel array init for all types (#16070)
- [Serial reduction regression](https://chapel-lang.org/perf/chapcs/?startdate=2020/04/01&enddate=2020/07/16&graphs=serialreductionstyles)
PR: Enable parallel array init for all types (#16070)
- [PTRANS improvement](https://chapel-lang.org/perf/chapcs/?startdate=2020/04/24&enddate=2020/07/16&graphs=hpccptranstimenumrows5733)
PR: Distribution improvements for automatic localAccess (#15959)
- [New leaky test](https://chapel-lang.org/perf/chapcs/?startdate=2020/04/18&enddate=2020/07/16&graphs=numberoftestswithleaks)
PR: Add tests for set, map, list of arrays (#16034)
A new test bumps into an existing/known leak.
- …

Add performance annotations

---

modules/packages/LinearAlgebra.chpl

Remove redundant control flow in transpose

---

test/classes/generic/nestedGenericTypes.bad

Adjust the .bad file for a future affected by #16060.

Update .bad file for future affected by #16060

---

compiler/include/bison-chapel.h
compiler/parser/bison-chapel.cpp

PR #16064 made a small change to the parser but I forgot to commit the rebuilt parser.
This PR commits the rebuilt parser.

Rebuild parser after noinit PR

---

compiler/include/bison-chapel.h
compiler/parser/bison-chapel.cpp

PR #16064 made a small change to the parser but I forgot to commit the rebuilt parser.
This PR commits the rebuilt parser.

Rebuild parser after noinit PR 16064

---

util/build_configs/cray-internal/setenv-shasta-x86_64.bash
util/build_configs/cray-internal/setenv-xc-aarch64.bash
util/build_configs/cray-internal/setenv-xc-x86_64.bash

Adjusts some compiler versions:
- Bumps target CCE version to 10.0.2
- Bumps target GCC version to 9.3.0

Adjust target compiler versions for some Cray configs

---

runtime/src/comm/ofi/comm-ofi.c

The primary effect of the work here is to stop communicating the memory
registration keys all-to-all when we do scalable registration, because
in that case we specify the key ourself and thus already know what it
is.  It also slightly accelerates the control flow for getting local
descriptors and remote keys with scalable registration.  Finally, while
here I made some adjustments to the code that decides between basic and
scalable registration.
This relates to Cray/chapel-private#1178 but doesn't close it.

Slightly improve support for scalable memory registration.

---

test/modules/diten/returnRecordDiffModule.chpl

I could have sworn I ran the test and it passed but I must have missed
looking closely at it or something because the .good file required the
writeln to be uncommented.

Uncomment writeln in this test

---

compiler/resolution/functionResolution.cpp

I meant to include this as the last commit on #16158.
This change is needed for correctness.
Not reviewed as it stays with the spirit of #16158
and is reflected in its PR message.

Missed change on #16158

---

util/buildRelease/testRelease
util/cron/nightly
util/cron/start_opt_test
util/tokencount/tokctnightly

This adds a new Discourse mailing alias to notifications of interesting script-based events.

Add Discourse mailing aliases to notifications of interesting events

---

test/library/standard/Set/assign/setAssign.chpl
test/library/standard/Set/clear/setClear.chpl
test/library/standard/Set/contains/setContains.chpl
test/library/standard/Set/difference/setDifference.chpl
test/library/standard/Set/intersection/setIntersection.chpl
test/library/standard/Set/symmetricDifference/setSymmetricDifference.chpl
test/library/standard/Set/union/setUnion.chpl

Separately assert each is 0 instead.

Set tests: don't compare a == b == c == 0 to check they're all 0.

---

modules/packages/LinearAlgebra.chpl

Parallel matrix multiplication based on loop tiling.
Adapted from [Chapel PRK DGEMM](https://github.com/chapel-lang/chapel/blob/master/test/studies/prk/DGEMM/dgemm.chpl)
~~Performance graphs against Naive approach~~ (not needed anymore as a local dot perf test already exists)

Loop tiled matrix multiplication

---

modules/packages/LinearAlgebra.chpl

Throw errors when Linear Algebra function does not support distributed vectors/matrices

Distributed linear algebra error

---

modules/packages/LinearAlgebra.chpl
modules/standard/List.chpl
test/library/packages/LinearAlgebra/correctness/no-dependencies/correctness.chpl

Add diag support for matrices with different range offsets/strides.

Change local diag to support domains with non-uniform dimensions

---

compiler/llvm/llvmAggregateGlobalOps.cpp
compiler/llvm/llvmGlobalToWide.cpp

Updates to compiler to build with LLVM 11

---

test/mason/publish/create-registry/.gitignore
test/mason/publish/create-registry/CLEANFILES
test/mason/publish/create-registry/create-registry.chpl
test/mason/publish/create-registry/create-registry.good

The previous test behavior was publishing to a directory that was part ofthe Chapel repository. This resulted in local commits to the Chapel git repo after running this test, showing up as:
```
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified:   pathToRegistry/registry (new commits)
```
Now we just publish to a new directory `registry` which is not git-ignored.

Simplify create-registry test to avoid leftover git artifacts

---

tools/protoc-gen-chpl/Makefile

Add source and header files as dependencies for building protoc-gen-chpl.

Fix faulty dependency while building protoc-gen-chpl

---

test/library/standard/Map/mapOfArray.skipif

Pointed out by Elliot in a post merge review

Use 'in' instead of '==', as the command can have multiple options

---

compiler/resolution/functionResolution.cpp
test/classes/delete-free/issue-15586.chpl
test/classes/delete-free/issue-15586.good
test/param/ifExprCopyInitBug.bad

Fix problem with new applied to a borrowed nilable type argument

---

compiler/passes/checkResolved.cpp
modules/standard/CommDiagnostics.chpl
test/extern/bradc/emptyRecords/emptyrecordexternfn.chpl
test/extern/ferguson/intent-errors.chpl
test/extern/ferguson/intent-errors.good
test/users/ferguson/uninit_test.chpl

Add error for extern/export with out/inout intent

---

test/classes/delete-free/issue-15586.chpl

Test was added in https://github.com/chapel-lang/chapel/pull/16380
start_test -memleaks passed locally

Close a leak in a new test

---

doc/rst/platforms/macosx.rst

Caught by the ever-vigilant @cassella
---
Signed-off-by: Brad Chamberlain <bradcray@users.noreply.github.com>

Remove incomplete, unused link

---

test/library/standard/Random/stonea/fillRandomAssociative.good
test/library/standard/Random/stonea/permutationAssociative.good
test/library/standard/Random/stonea/shuffleAssociative.good

Follow-up to PR #16441 and PR #16175.

Update a few random tests after error message change

---

test/arrays/slices/commCounts/sliceBlockWithRanges.good
test/distributions/robust/arithmetic/performance/multilocale/assignReindex.block.good
test/distributions/robust/arithmetic/performance/multilocale/assignReindex.cyclic.good
test/distributions/robust/arithmetic/performance/multilocale/assignReindex.cyclic.na-none.good
test/distributions/robust/arithmetic/performance/multilocale/assignReindex.replicated.good
test/distributions/robust/arithmetic/performance/multilocale/assignReindex.replicated.na-none.good
test/distributions/robust/arithmetic/performance/multilocale/assignSlice.block.good
test/distributions/robust/arithmetic/performance/multilocale/assignSlice.cyclic.good
test/distributions/robust/arithmetic/performance/multilocale/assignSlice.cyclic.na-none.good
test/distributions/robust/arithmetic/performance/multilocale/assignSlice.replicated.good
test/distributions/robust/arithmetic/performance/multilocale/assignSlice.replicated.na-none.good
test/distributions/robust/arithmetic/performance/multilocale/reduceSlice.block.good
test/distributions/robust/arithmetic/performance/multilocale/reduceSlice.cyclic.good
test/distributions/robust/arithmetic/performance/multilocale/reduceSlice.cyclic.na-none.good
test/distributions/robust/arithmetic/performance/multilocale/reduceSlice.replicated.good
test/distributions/robust/arithmetic/performance/multilocale/reduceSlice.replicated.na-none.good
test/distributions/robust/arithmetic/performance/multilocale/sliceOps.block.good
test/distributions/robust/arithmetic/performance/multilocale/sliceOps.cyclic.good
test/distributions/robust/arithmetic/performance/multilocale/sliceOps.cyclic.na-none.good
test/distributions/robust/arithmetic/performance/multilocale/sliceOps.replicated.good

https://github.com/chapel-lang/chapel/pull/16477 removed an assignment that was
increasing communication for no reason. Brad fixed some of these commcounts in
https://github.com/chapel-lang/chapel/pull/16503. This PR fixes the rest.

Fix commcount changes after #16477

---

test/ANNOTATIONS.yaml

Add recent performance annotations and some that we missed previously
over the course of the release cycle.

Add perf annotations for 2020-10-01

---

test/library/packages/LinearAlgebra/correctness/testCholeskyComplexError.good
test/library/packages/LinearAlgebra/correctness/testCholeskyRealError.good

Trivial fix to Cholesky*Error good files

---

doc/rst/language/spec/interoperability.rst
doc/rst/technotes/extern.rst
doc/rst/technotes/libraries.rst

Follow-up to PRs #15903, #16163, #16334, and #16452.

Update interop technotes to discuss limitations & implicit uses

---

CONTRIBUTORS.md

This is the CONTRIBUTORS.md file for the Chapel 1.23 release.

Contributors file for Chapel 1.23

---

CHANGES.md

Chapel version 1.23 contains many good changes.  Here's a list of the most notable ones.

CHANGES file for Chapel 1.23

---

test/library/draft/cuBLAS/cuBLAS.chpl
test/library/draft/cuBLAS/level1/test_cublas1.compopts

---
Signed-off-by: Sarah Nguyen <slnguyen@users.noreply.github.com>

Adding notest file to skip cublas wrapper tests

---

test/ANNOTATIONS.yaml

Add recent arkouda annotations and some historical compilation time
annotations.

Add perf annotations for 2020-10-15

---

util/pastPerformance/testReleasesPerformance
util/test/perf/perfgraph.js

Updating statistics for the 1.23.0 release.

Update stats tracking for release 1.23.0.

---

util/cron/common-arkouda.bash

See https://github.com/mhmerrill/arkouda/pull/530

Upgrade Arkouda release testing from 1.22 to 1.23

---

test/expressions/noinit/array-noinit-resize.bad
test/expressions/noinit/array-noinit-resize.chpl
test/expressions/noinit/array-noinit-resize.compopts
test/expressions/noinit/array-noinit-resize.future
test/expressions/noinit/array-noinit-resize.good

Add a future for noiniting new elements on resize

---

runtime/src/comm/ofi/comm-ofi.c

Fix an improper exit() call in my PR just merged.

Don't exit()!

---

test/llvm/llvmDebug/llvmDebug_test.py

Follow up to PR #16613 and PR #16560
System LLVM installations use versioned commands
like instead of llvm-dwarfdump we have llvm-dwarfdump-10.
This commit adjusts the test to handle that.

Adjust llvmDebug_test.py to handle system llvm

---

modules/internal/ChapelIteratorSupport.chpl

Resolves https://github.com/Cray/chapel-private/issues/1392
Fixes memory leak in `test/reductions/reduceLoopOfPromoted.chpl`
This applies the solution for avoiding memory leaks, discovered in #16518
for the then-added chpl_elemTypeForReducingIterables(), to iteratorIndexType().
Moves the explanatory comments there as well.
While there, splits a couple of long lines, which I was supposed
to do in #16518.
Does not affect other known memory leaks.
Future work: apply the same solution to iteratorIndex() itself.
For that, it needs to be passed the iterator itself
rather than an iterator class (as it is done now).

Fix memory leak in reduceLoopOfPromoted.chpl

---

test/library/standard/List/initEquals/list-init-eq-many.chpl
test/library/standard/List/initEquals/list-init-eq-many.good

I meant to include this test in #16708.

Add test for new list copy-init behavior

---

test/ANNOTATIONS.yaml

Add recent annotations and add some "end" markers to long annotations to
make it easier to get to the end and add new ones.

Add perf annotations for 2020-11-19

---

doc/rst/developer/bestPractices/GettingStarted.rst

While reviewing new hire documentation, I found that this file was
feeling pretty stale, yet we still point to it.  Took a refresh
pass over it as a result.

Refresh GettingStarted.rst

---

test/ANNOTATIONS.yaml
util/test/check_annotations.py

Adds a patch to check_annotations proposed by @ronawho and fixes some annotation
mistakes that it shows.

Fix some annotations and improve the checker

---

util/build_configs/cray-internal/setenv-hpe-cray-ex-x86_64.bash

This resolves https://github.com/Cray/chapel-private/issues/1523.

Remove refs to our private libfabric from the built runtime tree.

---

test/distributions/deitz/test_block_representation.good

Fix test_block_representation.good

---

util/cron/test-perf.cray-cs-hdr.arkouda.bash
util/cron/test-perf.cray-cs-hdr.arkouda.release.bash

We have testing on 56 Gbps FDR IB currently. Add some additional testing
on newer 200 Gbps HDR IB.
For https://github.com/Cray/chapel-private/issues/1490

Add HDR InfiniBand Arkouda perf testing

---

test/chpldoc/globals/variablepatterns.doc.bad
test/chpldoc/globals/variablepatterns.doc.catfiles
test/chpldoc/globals/variablepatterns.doc.chpl
test/chpldoc/globals/variablepatterns.doc.future
test/chpldoc/globals/variablepatterns.doc.good

Add a chpldoc future

---

modules/standard/IO.chpl
runtime/src/qio/regexp/re2/re2-interface.cc
test/regexp/ferguson/bug-16891.chpl
test/regexp/ferguson/bug-16891.good
test/regexp/ferguson/bug-16891.txt

Fix readf regexp handling at end of file

---

.gitignore
modules/standard/DateTime.chpl
test/library/standard/DateTime/testDatetime.chpl

Add %f to datetime.strftime()

---

modules/standard/DateTime.chpl

Signed-off-by: Lee Killough <lee.killough@hpe.com>

Add pragma

---

test/extern/ferguson/externblock/issue-14830-import.chpl
test/extern/ferguson/externblock/issue-14830-import.good
test/extern/ferguson/externblock/issue-14830-submodule.chpl
test/extern/ferguson/externblock/issue-14830-submodule.good
test/extern/ferguson/externblock/issue-14830.h

Resolves #14830
Issue #14830 was resolved by other PRs but we didn't notice and we didn't 
add the reproducer for the problem. This PR just adds two variants of the
reproducer as a test.

Add test from issue 14830

---

test/ANNOTATIONS.yaml

- new leaking test and fix for it
- scan noinit optimization
- arkouda prod reduce regression and fix

Add perf annotations for 2021-01-14

---

.gitignore

Signed-off-by: Lee Killough <lee.killough@hpe.com>

Revert adding testDateTime to .gitignore
